- app/client/src/components/formControls/DropDownControl.tsx
This PR enables the dropdown component to fetch its options dynamically from the redux state. It will allow for further enhancements to the component like hooking the options to response of an API call or any other variable. This is part of the UQI project and the change is completely backwards compatible.
Fixes #10191 
// Code coverage diff between base branch:release and head branch: feat/10191-drop-down-allow-dynamic-options 
:red_circle: | total | 55.12 **(0)** | 36.65 **(0)** | 34.54 **(0)** | 55.64 **(-0.01)**
:red_circle: | …
> feat: Connect drop down to redux state to fetch options dynamically

- app/client/src/workers/Actions.test.ts
- app/client/src/workers/Actions.ts
Fix not getting the params properly when old signature is used with no function passed in callbacks
Fixes #10211 
Updated jest tests with new cases
// Code coverage diff between base branch:release and head branch: fix/passig-params-correctly 
:green_circle: | total | 55.1 **(0)** | 36.63 **(0.01)** | 34.52 **(0)** | 55.63 **(0.01)**
:green_circle: | app/client/src/workers/Actions.ts | 91.55 **(0.25)** | 68.85 **(5.06)** | 80 **(0)** | 90.48 …
> fix: action.run signature check

- app/client/src/utils/DSLMigrations.ts
Fixing client build because of unused variable
// Code coverage diff between base branch:release and head branch: chore/fix-client-build 
:red_circle: | total | 55.04 **(-0.01)** | 36.56 **(-0.01)** | 34.49 **(0)** | 55.56 **(0)**
> chore: Fixing client build because of unused variable

- app/client/src/sagas/PageSagas.tsx
Fetch js collections API was missing after page clone
Fixes #10142 
// Code coverage diff between base branch:release and head branch: fetch-js-collection-after-clone 
:red_circle: | app/client/src/sagas/PageSagas.tsx | 23.88 **(-0.07)** | 6.1 **(0)** | 14.71 **(0)** | 25.78 **(-0.09)**</details>
> fix: fetch js collections after page clone

- app/client/src/constants/AppsmithActionConstants/ActionConstants.tsx
Order of execution was not proper because the dynamic parameters embedded inside url without any trailing slashes and query params did not match with url grouping regex to convert the query params to dsl params. 
Fixes #10049 
Fixes #10055
1. Create Api1 - 'CatImage'
2. Create Api2 - 'CatFacts' - Dependent on Api1 - added via Header
3. Create Api3 - 'Suggestions' - Dependent on Api2 - added via Header
4. Create Api4 - 'Genderize' - Dependent on Api3 - added via url & not params
5. Map all of the results to widgets
6. Refresh page & observe
> fix: url action execution order for actions on page load

- .github/workflows/integration-tests-command.yml
- .github/workflows/test-build-docker-image.yml
> Set a file path for the git to store files during the CI runs. As this was not set earlier TCs were failing with the error `Creating a directory failed`   
> chore: Add env variable for git filesystem in CI

- app/client/src/sagas/ActionExecution/DownloadActionSaga.ts
- app/client/src/sagas/ActionExecution/downloadActionUtils.ts
This PR prevents corruption of downloaded file when base64 string is supplied to download action
Fixes #3559
Manual
// Code coverage diff between base branch:release and head branch: fix/handle-base64-encoded-strings-in-download-action 
:red_circle: | total | 55.06 **(-0.01)** | 36.56 **(-0.01)** | 34.49 **(-0.01)** | 55.58 **(0)**
:red_circle: | app/client/src/sagas/ActionExecution/DownloadActionSaga.ts | 30.77 **(-2.56)** | 0 **(0)** | 0 **(0)** | 30.77 **(-2.56)**
:sparkles: :new: | **app/client/src/sagas/ActionExecution/downloadActionUtils.ts** | **75** | …
> fix: downloaded file gets corrupted when base64 string is used in download action

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GlobalSearch/GlobalSearch_spec.js
- app/client/cypress/locators/GlobalSearch.json
- app/client/src/components/editorComponents/GlobalSearch/SnippetsFilter.tsx
Clicking on the `filter` text wasn't opening the filter menu. The check to see when the element contains in the parent wrapper was returning false for unknown reason. Using composedPath which has the path of an elements parent's instead to fix this.
Fixes #9427 
Cypress
// Code coverage diff between base branch:release and head branch: fix/filter-dropdown 
:green_circle: | total | 55.04 **(0)** | 36.57 **(0.01)** | 34.49 **(0)** | 55.56 **(0)**
:green_circle: | app/client/src/components/editorComponents/GlobalSearch/SnippetsFilter.tsx | 19.23 **(0)** | 4.08 …
> fix: filter menu not opening in snippet search

- deploy/docker/entrypoint.sh
This key ends up with incorrect permissions sometimes for whatever reason. If that situation occurs, with this PR, a simple restart of the container should fix the permiossions.
> chore: Set MongoDB Key permissions everytime

- app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/Aggregate.java
- app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/constants/FieldName.java
- app/server/appsmith-plugins/mongoPlugin/src/main/resources/editor/aggregate.json
- app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
- This PR adds a `limit` field which sets the `batchSize` for `aggregate` command. This way the user can set the number of documents they want in their Mongo query result. 
- `limit` is set to `10` initially. However, for pre-existing Mongo actions, migration has been added to set this field to `101` - which is the default value that has been used by Mongodb in the absence of any user set value.  Ref: https://docs.mongodb.com/manual/tutorial/iterate-a-cursor/
Fixes #2290
- JUnit TC
- Manual
> feat: Mongo plugin: add `limit` field to `aggregate` command to allow users to define `batchSize` 

- app/client/src/components/ads/Dropdown.tsx
- app/client/src/pages/Editor/GeneratePage/components/GeneratePageForm/GeneratePageForm.tsx
- app/client/src/pages/Editor/GeneratePage/components/GeneratePageForm/GoogleSheetForm.tsx
There were few alignments happening in the crud app builder. Specifically in the dropdown component.
Fixes #9037
Fixes #9428
Fixes #10194
- Bug fix 
// Code coverage diff between base branch:release and head branch: fix/alignment-issues 
:green_circle: | total | 55.07 **(0.01)** | 36.57 **(0.01)** | 34.49 **(0)** | 55.58 **(0)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | …
> fix: alignment issues in dropdown component of ads

- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ApplicationForkingServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ApplicationForkingServiceTests.java
Fork application is currently a slow API because it needs to create an application, fork all the pages, and then copy all the actions and collections. This process may take time and the client may cancel the request. This leads to the flow getting stopped midway producing corrupted DB objects. The PR ensures that even though the client may have cancelled the flow, the forking of the application should proceed uninterrupted and whenever the user refreshes the page, the sane forked application is available.
Fixes #10184 
> JUnit TC
> Manual test
> chore: Make sure to keep forked application in valid state even if client exits the flow before server responds 

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Autocomplete_spec.js
This PR contains cypress test for Bug #9003
Fixes #9490
locally
// Code coverage diff between base branch:release and head branch: AutocompleteBugTests 
:green_circle: | total | 55.06 **(0)** | 36.57 **(0.01)** | 34.49 **(0)** | 55.58 **(0)**
> test: Autocomplete not working for Appsmith specific JS APIs

- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCEImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PageLoadActionsUtilCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutActionServiceTest.java
- This PR fixes the page load action execution order when the actions have been set to run on page load explicitly via the settings tab by the user and its data has not been referenced in any other widget or action. e.g.
- create `action1` and `action2`.
- make `action2` dependent on `action1` by adding `{{action1.data}}` in `action2`'s body.
- set both `action1` and `action2` to run on page load via settings tab. Do not reference `action1` and `action2` data in any other widget or action.
Fixes #10242 
- JUnit TC
- Manual
> fix: fix page load action execution order

- app/client/src/widgets/CameraWidget/component/index.tsx
- app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx
Fixes #10283
- Bug fix
// Code coverage diff between base branch:release and head branch: fix/http-issue-with-filepicker 
:red_circle: | total | 55.07 **(0)** | 36.59 **(0)** | 34.54 **(0)** | 55.56 **(-0.01)**
:red_circle: | app/client/src/widgets/CameraWidget/component/index.tsx | 10.53 **(-0.03)** | 14.72 **(0)** | 0 **(0)** | 12.41 **(-0.04)**
:red_circle: | app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx | 32.41 **(-0.92)** | 0 **(0)** | 20.69 **(0)** | 33.33 **(-1.01)**</details>
> fix: App crashes when a modal has a filepicker?

- app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/GitControllerCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java
For the sync/prune operation in git sync we are deleting the stale branches from local(if there is no remote tracking branch in git client). But suppose if the current checked out branch remote counter part is deleted from remote this operation will fail. This change set will fix this issue. We are excluding the current checked out branch from delete operation even though its remote counter part is deleted. 
Fixes #10333 
- Locally
- JUnit tests
> fix: Cannot delete current branch

- app/client/src/widgets/CameraWidget/component/index.tsx
- app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx
(cherry picked from commit f646eeafc1bbe442450d797e383080ca21ca6182)
>
- This change requires a …
> fix: App crashes when a modal has a filepicker? (#10376)

- app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/PageNameIdDTO.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewPageServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java
We've added slug for pages. Each page has a slug which is generated from name automatically. In our get pages API `/api/v1/pages/application/<app_id>`, the slug names were not included in the Page DTO. This PR adds slug name in this API response.
Fixes #10271 
- JUnit test
- Manually
> feat: Add page slug in the get pages API

- app/client/Dockerfile
The `appsmith-editor` image can't be run directly today because the HTTP configuration file is copied to the wrong location. This PR fixes the file location.
> chore: Fix path to http nginx config file

- app/client/cypress/support/commands.js
- app/client/src/api/ApplicationApi.tsx
The trailing slash causes issues in Vercel's deploy preview when creating an app. The server ends up responding with 405 Method Not Allowed error. 
- Manual
// Code coverage diff between base branch:release and head branch: create-app-405 
:red_circle: | total | 55.01 **(0)** | 36.71 **(-0.01)** | 34.7 **(0)** | 55.51 **(0)**
:red_circle: | app/client/src/api/ApplicationApi.tsx | 51.02 **(0)** | 0 **(0)** | 5 **(0)** | 52.17 **(-1.16)**
:red_circle: …
> chore: Removing trailing slash from application API endpoint.

- app/client/src/pages/Editor/WidgetsEditor/CanvasContainer.tsx
Fixed issue in widget pane, was not closing when navigate to Datasource page via omnibar.
Fixes #9194 
- Tested navigation from omnibar
- Tested navigation from run query in property pane.
// Code coverage diff between base branch:release and head branch: fix/9194-widget-pane-switching-issue 
:green_circle: | total | 55.07 **(0.01)** | 36.57 **(0.01)** | 34.52 **(0.01)** | 55.58 **(0.01)**
:green_circle: | app/client/src/pages/Editor/WidgetsEditor/CanvasContainer.tsx | 96.77 **(0.77)** | 66.67 **(0)** | 100 **(0)** | 96.77 **(0.77)** …
> fix: Widget pane not closing when switching from canvas

- app/client/src/components/editorComponents/form/fields/StyledFormComponents.tsx
- app/client/src/components/formControls/DropDownControl.tsx
- app/client/src/components/formControls/DynamicInputTextControl.tsx
- app/client/src/components/formControls/FilePickerControl.tsx
- app/client/src/components/formControls/FixedKeyInputControl.tsx
- app/client/src/components/formControls/InputTextControl.tsx
- app/client/src/components/formControls/KeyValueArrayControl.tsx
- app/client/src/components/formControls/KeyValueInputControl.tsx
- app/client/src/components/formControls/PaginationControl.tsx
- app/client/src/components/formControls/WhereClauseControl.tsx
- app/client/src/pages/Editor/APIEditor/CurlImportForm.tsx
- app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
The ADS changes caused the UI for where clause component to break. The reason was the customStyles option is not getting properly extracted in the control component.
Also replaced `vh` with `vw` for the width of the components as per the guidelines from ADS.
Fixes #10406 
// Code coverage diff between base branch:release and head branch: fix/10406-where-clause-ui-fixes 
:green_circle: | total | 54.98 **(-0.01)** | 36.72 **(0.04)** | 34.7 **(-0.01)** | 55.49 **(-0.01)**
:green_circle: | app/client/src/components/formControls/DropDownControl.tsx | 44.83 **(0)** | …
> fix: Where clause UI fixes (10406)

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_Widget_Add_button_spec.js
This PR fixes failing button color validation test of Table_widget_add_button spec.
locally
// Code coverage diff between base branch:release and head branch: FlakyTestsFixes 
:red_circle: | total | 54.96 **(-0.01)** | 36.64 **(-0.01)** | 34.68 **(0)** | 55.47 **(-0.01)**
> test: Adding fix for Table_widget_add_button spec's test

- app/client/src/pages/Editor/FirstTimeUserOnboarding/IntroductionModal.tsx
The signposting intro modal has images overflowing the width. Adding back image widths which where removed in https://github.com/appsmithorg/appsmith/commit/8395f5e18f9cb55ae3f8672d32cae8171854f784#diff-bc602b2a6716d7e958e76414c31fce543a15919b02a26a222805ccd7e2508786L161
Currently on release
After fix
Manually
// Code coverage diff between base branch:release and head branch: fix/first-time-onboarding-image 
> fix: Signposting intro modal UI issue

- app/client/src/components/ads/TreeDropdown.tsx
- app/client/src/pages/Editor/QueryEditor/TemplateMenu.tsx
This PR fixes two things
- It fixes the hover background on the datasource query template menus to have sharp edges.
- It fixes the Icon color for the Delete button in the actions menu dropdown when hovered, Initially the red icon color is turned to black when hovered, now it doesn't anymore.
Fixes #9200 and #9192
- Bug fix (non-breaking change which fixes an issue).
Manual Tests employed.
// Code coverage diff between base branch:release and head branch: fix/fix-ui-inconsistencies 
:green_circle: | total | 54.96 **(0)** | 36.65 **(0.01)** | 34.68 **(0)** | 55.47 **(0)** …
> fix: Fixes UI inconsistencies on the app

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Chart_Widget_Loading_spec.js
This PR contains fix for Chart_Widget_Loading_spec's test.
locally 
// Code coverage diff between base branch:release and head branch: FlakyTestsFix 
:red_circle: | total | 54.99 **(-0.02)** | 36.6 **(-0.01)** | 34.82 **(0)** | 55.47 **(-0.02)**
:x: | ~~app/client/src/widgets/CircularProgressWidget/constants.ts~~ | ~~100~~ | ~~100~~ | ~~100~~ | ~~100~~
:x: | ~~app/client/src/widgets/CircularProgressWidget/index.ts~~ | ~~100~~ | ~~100~~ | ~~100~~ | ~~100~~
:x: | …
> test: Adding fix for Chart_Widget_Loading_spec

- app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/ActionViewDTO.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/GlobalExceptionHandler.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ResponseUtils.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/ResponseUtilsTest.java
- app/server/appsmith-server/src/test/resources/test_assets/ResponseUtilsTest/mockObjects.json
Keeping this in a draft state as TCs are still pending 
> When the resources attached to the application like page, action and actionCollection don't get saved in a sane state because of NPE or some other issues like subscription is closed from client side defaultResourceIds gets saved as a null object. This is throwing the exception today. This PR will henceforth just logs such scenarios but will send the valid response to client   
Fixes #10451 #10084
> Manual test
> fix: Gracefully handle defaultResourceIds exception

- app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/BulkAppendMethod.java
- This PR fixes the issue when bulk inset of data overwrites existing rows
Fixes #5076
- Manually and verifies against test google sheet
- No new test case added
- Tested that existing tests are passed.
> fix: Google Sheet Bulk Insert, overwrites existing rows

- app/server/appsmith-git/src/main/java/com/appsmith/git/service/GitExecutorImpl.java
> Inconsistency in git clients in commit history with root is being used as committer. JGit picks up the global config for committer name and if that is not set then root is used. So if the authorName set by user is different from the global git config then we will see different name in git client as commiter and authorName are different.
Ideally the authorNames are configured by git clients but since we act as a proxy between the users git repo we see the `root` because the git server is not able to find this user(the one user has set in the profile/config section)
As fix we are explicitly setting the committer info while committing to avoid this issue. 
Fixes #10517 
- Locally
> fix: Use the authorName as committer to avoid the inconsistency with name 

- app/client/src/actions/jsActionActions.ts
- app/client/src/api/JSActionAPI.tsx
- app/client/src/pages/Editor/Explorer/JSActions/JSActionContextMenu.tsx
- app/client/src/pages/Editor/Explorer/JSActions/MoreJSActionsMenu.tsx
- app/client/src/sagas/JSActionSagas.ts
- app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/BulkAppendMethod.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/ActionCollectionMoveDTO.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutCollectionServiceCEImpl.java
- The issue is when moving a JavaScript objects in between pages they are not getting renamed
- Made server side changes thereby sending back the renamed object and got it resolved
Fixes #10492
- Manually
// Code coverage diff between base branch:release and head branch: fix-10463-JSObject_Cloning_issue 
:green_circle: | total | 55.11 **(0)** | 36.87 **(0)** | 34.99 **(0)** | 55.6 **(0.01)**
:red_circle: | …
> fix: Fix 10463 js object cloning issue

- app/client/src/widgets/DividerWidget/component/index.tsx
> In Divider Widget cap in added transparent color in case of no color selected
Fixes #10335
// Code coverage diff between base branch:release and head branch: bug/divider-no-color-issue 
:red_circle: | app/client/src/widgets/DividerWidget/component/index.tsx | 64.58 **(0)** | 40 **(-2.25)** | 41.67 **(0)** | 69.05 **(0)**</details>
> fix: handle no color as transperant

- app/client/src/sagas/PostEvaluationSagas.ts
- app/client/src/selectors/dataTreeSelectors.ts
- app/client/src/workers/evaluation.test.ts
- app/client/src/workers/evaluationUtils.test.ts
- app/client/src/workers/evaluationUtils.ts
This PR removes private widgets from autocomplete hints
Fixes #10534 
- Manual
- Jest
// Code coverage diff between base branch:release and head branch: fix/remove-private-widgets-from-autocomplete 
:green_circle: | total | 55.12 **(0.01)** | 36.88 **(0.01)** | 35.01 **(0.02)** | 55.6 **(0.01)**
:red_circle: | app/client/src/sagas/PostEvaluationSagas.ts | 16.44 **(-0.11)** | 0 **(0)** | 0 **(0)** | 20 **(-0.17)**
:green_circle: | app/client/src/workers/evaluationUtils.ts | 59.69 **(1.54)** | 55.56 **(1.07)** | 64.91 **(1.95)** | 57.54 **(1.63)**</details>
> fix: Remove private widgets from autocompletion

- app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/AppendMethod.java
- app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/BulkAppendMethod.java
- app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/BulkUpdateMethod.java
- app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/ClearMethod.java
- app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/CopyMethod.java
- app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/CreateMethod.java
- app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/DeleteRowMethod.java
- app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/DeleteSheetMethod.java
- app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/UpdateMethod.java
> Fixed the error when google sheet name contains space 
> Verified error is not thrown for sheet name containing special chars.
Fixes #10502
- Bug fix (non-breaking change which fixes an issue) 
Manual testing
> fix: 10502-Space in Google Sheet name

- app/client/src/components/ads/MultiselectDropdown.test.tsx
- app/client/src/components/ads/MultiselectDropdown.tsx
- app/client/src/components/propertyControls/MultiSelectControl.tsx
- app/client/src/components/propertyControls/StyledControls.tsx
Use `Tab` to focus the dropdown
`Enter` or `Space` to open dropdown
`Arrow Up` and `Arrow Down` keys to focus dropdown menu items
`Space` or `Enter` to select items
`Esc` to close dropdown menu
Fixes #10373 
Manually tested and Jest tests added
// Code coverage diff between base branch:release and head branch: feat/keyboard-accessible-multiselect-dropdown 
:green_circle: | total | 55.23 **(0.12)** | 37.06 **(0.19)** | 35.29 **(0.3)** | 55.71 **(0.12)**
:green_circle: | app/client/src/components/ads/MultiselectDropdown.tsx | 83.87 **(63.62)** | 70.83 …
> feat: Add keyboard navigation to multiselect dropdown

- app/client/src/workers/DataTreeEvaluator.ts
- app/client/src/workers/evaluate.ts
- app/client/yarn.lock
When any js object function was referred to in any other js object function. it was throwing an error that `function does not exist`
The problem was while checking is a function asych, we were not adding existing functions which are stored as part of resolvedFunctions hence it was not getting the reference. I have added all resolvedFunctions as part of global data to avoid reference errors
Fixes #10150 
- Test A
- Test B …
> fix: added all js object functions as part of global data while checking isAsync

- app/client/src/components/ads/TableDropdown.tsx
> Members list of any selected organization wasn't getting sorted correctly based on **Role** column. Fixed this issue.
Fixes #10447
- Select an organization
- Click 3 dots on the right-hand side of the organization card.
- Click Members from the list.
- Invite multiple users with different roles assigned to them.
- Now, try sorting the members based on the Role column.
- Each user should have the correct role next to their name (unlike before).
> fix: Incorrect member list sorting on user roles

- app/client/src/utils/JSPaneUtils.tsx
This change adds hints to the JS Objects editor to let devs know that they can now use JS promises or async/await on appsmith. This change makes the JS promise feature more discoverable. See myFunc2 in the below screenshot
- New feature
Tested on my locally
> feat: Add code hints for JS promises in JS Object editor

- app/server/appsmith-plugins/restApiPlugin/src/main/resources/form.json
- Make query params visible when an API datasource is saved. Currently only header info is shown on the page immediately following the `save` datasource action. 
- Make query params visible on the right hand section when a REST API action is edited. 
- TBD: some FE side changes will be added separately.
Fixes #9930 
- Manual
> fix: make query params visible in various flows when saved in REST API datasource

- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java
> When local repo and DB are not in sync, if the branch is present in local repo but the corresponding app is absent in DB,  sync-branch is failing with resource not found exception. This change set will add error handler to catch this condition and delete the stale branch from file system 
- Locally
- Unit Tests
> fix: Logic to delete stale git branch which are not in db

- app/client/src/widgets/ListWidget/widget/index.tsx
When the List Widget's height is less than the height of the template container height, the path to the list of its children becomes "not defined".
Fixes #10668
Manual
// Code coverage diff between base branch:release and head branch: fix/broken-list-widget 
:red_circle: | total | 55.05 **(0)** | 36.66 **(-0.01)** | 34.98 **(0)** | 55.45 **(0)**
:red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | …
> fix: broken list widget

- app/client/src/components/editorComponents/CodeEditor/constants.ts
- app/client/src/components/editorComponents/CodeEditor/lintHelpers.ts
- app/client/src/globalStyles/CodemirrorHintStyles.ts
- app/client/src/workers/lint.ts
This PR introduces warnings in linting. Users get warned when an unused variable is present in the code.
Fixes #10589 
Manual
// Code coverage diff between base branch:release and head branch: fix/show-lint-error-for-unused-variables 
:green_circle: | total | 55.01 **(0.01)** | 36.57 **(0.01)** | 34.93 **(0)** | 55.41 **(0.01)**
:sparkles: :new: | **app/client/src/components/editorComponents/CodeEditor/constants.ts** | **100** | **100** | **100** | **100**
:green_circle: | app/client/src/components/editorComponents/CodeEditor/lintHelpers.ts | 97.33 **(0.23)** | …
> fix: show lint when unused variable is present in code

- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ApplicationForkingServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ApplicationForkingServiceTests.java
This reverts commit c1a32c9dfe0a258f2f64aa6fcdb3c439556fa4a9. We have fixed the issue which resulted in infinite loop during the fork application [here](https://github.com/appsmithorg/appsmith/pull/10455), when the subscription does not get canceled by the client 
Fork application is currently a slow API because it needs to create an application, fork all the pages, and then copy all the actions and collections. This process may take time and the client may cancel the request. This leads to the flow getting stopped midway producing corrupted DB objects. The PR ensures that even though the client may have cancelled the flow, the forking of the application should proceed uninterrupted and whenever the user refreshes the page, the sane forked application is available.
Fixes #10184 
- Bug fix …
> chore: Make sure to keep forked application in valid state even if client exits the flow before server responds

- app/client/src/workers/DataTreeEvaluator.ts
Fixes #10691 
Manual
// Code coverage diff between base branch:release and head branch: fix/edge-cases-in-private-widgets 
:red_circle: | total | 55.01 **(0)** | 36.49 **(-0.01)** | 34.71 **(-0.02)** | 55.4 **(-0.01)**
:red_circle: | app/client/src/workers/DataTreeEvaluator.ts | 75.73 …
> fix: Evaluate PrivateWidgets to fix list widget children evaluation issue

- app/client/src/widgets/DocumentViewerWidget/component/index.test.tsx
- app/client/src/widgets/DocumentViewerWidget/component/index.tsx
Added Iframe for load Base64 PDF in document viewer widget
Fixes #10756 
// Code coverage diff between base branch:release and head branch: fix/pdf-document-viewer 
:green_circle: | total | 55 **(0)** | 36.49 **(0.01)** | 34.71 **(0)** | 55.4 **(0)**
:green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0)**
:red_circle: | …
> fix: Added iFrame to load Base64 PDF data in document viewer widget

- app/client/src/widgets/DocumentViewerWidget/component/index.test.tsx
- app/client/src/widgets/DocumentViewerWidget/component/index.tsx
Reverts appsmithorg/appsmith#10770
// Code coverage diff between base branch:release and head branch: revert-10770-fix/pdf-document-viewer 
:red_circle: | total | 55 **(0)** | 36.48 **(-0.01)** | 34.71 **(0)** | 55.4 **(0)**
:green_circle: | app/client/src/widgets/DocumentViewerWidget/component/index.tsx | 40.37 **(-1.16)** | 45.65 **(4.83)** | 16.67 **(0)** | …
> revert: "fix: Added iFrame to load Base64 PDF data in document viewer widget"

- app/client/src/pages/Editor/Explorer/Datasources/DatasourceEntity.tsx
Fixes the rename behavior of datasources in explorer. It will not have the names transformed with underscore anymore and would have a length limit of 30 (just like how it works in the datasources page header).
Fixes #4904 
- Manual
// Code coverage diff between base branch:release and head branch: fix/4904-datasource-rename-explorer 
:green_circle: | total | 55.02 **(0.01)** | 36.51 **(0.01)** | 34.73 **(0)** | 55.41 **(0)**
:red_circle: | app/client/src/pages/Editor/Explorer/Datasources/DatasourceEntity.tsx | 37.5 **(-1.63)** | 0 **(0)** | 0 **(0)** | 37.5 …
> fix: Consistent rename behaviour for datasources

- app/client/src/components/ads/EditableText.test.tsx
- app/client/src/components/ads/EditableText.tsx
- app/client/src/components/ads/EditableTextSubComponent.tsx
- app/client/src/pages/Editor/PropertyPaneTitle.test.tsx
- app/client/src/pages/Editor/PropertyPaneTitle.tsx
- Added a key-down listener as an effect in PropertyPaneTitle to listen to F2 key and trigger isEditing to true.
- Added a new onBlurEverytime callback prop to EditableTextSubComponent to call it every time the user unfocus from the input, the existing onBlur calls only if there is a change in the value in the input field.
- Since EditableText is a wrapper component around EditableTextSubComponent added onBlurEverytime there also.
- Using this new onBlurEverytime in PropertyPaneTitle we will set isEditing to false.
Fixes #9413
- Manual UI Testing
- Added jest tests for PropertyPaneTitle and EditableText.
// Code coverage diff between base branch:release and …
> feat: added a keydown listener to focus property pane title on pressing f2

- app/client/src/constants/Colors.tsx
- app/client/src/constants/messages.ts
- app/client/src/pages/Editor/gitSync/QuickGitActions/index.tsx
- app/client/src/pages/Editor/gitSync/components/BetaTag.tsx
- app/client/src/pages/Editor/gitSync/components/BranchList.tsx
- app/client/src/pages/Editor/gitSync/components/TabItem.tsx
chore: beta tags for git sync
- Manually
// Code coverage diff between base branch:release and head branch: git-sync-beta-tags 
:green_circle: | total | 55.02 **(0.01)** | 36.51 **(0.01)** | 34.72 **(-0.01)** | 55.42 **(0.01)**
:red_circle: | app/client/src/constants/messages.ts | 74.83 **(-0.02)** | 100 **(0)** | 25.41 **(-0.04)** | 80.31 **(0.02)**
:sparkles: :new: | **app/client/src/pages/Editor/gitSync/components/BetaTag.tsx** | **75** | **100** | **0** | **75**
:green_circle: | app/client/src/pages/Editor/gitSync/components/BranchList.tsx | 23.78 …
> chore: beta tags for git sync

- app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ActionControllerCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ApplicationForkingServiceTests.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ExamplesOrganizationClonerTests.java
Fixes #10630
Unsure of how this filter was introduced at all since a separate method for actions except JS had been created. Might have been a merging issue, just reverted the filter change to fix the issue.
> fix: Removed filter of JS actions from get actions call

- app/client/src/sagas/WidgetOperationSagas.tsx
- app/client/src/sagas/WidgetOperationUtils.test.ts
- app/client/src/sagas/WidgetOperationUtils.ts
On certain occasions, we find that paths which are defined in a widget's `dynamicTriggerPathList` and `dynamicBindingPathList` don't really exist in the widget. This has been observed in the [MenuButton widget](https://github.com/appsmithorg/appsmith/issues/10768)
This results in issues in subsequent evaluations. The details with respect to the exact issue in the evaluations are unclear -- nevertheless, having orphaned paths is akin to having a bad DSL. This fix purges then during property update.
Fixes #10791
Fixes #10768 
Jest test added for the purging function. 
Tested manually using the steps shown in #10768 
// Code coverage diff between base branch:release …
> fix: Purge orphaned paths from dynamic path lists in widgets

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Checkbox_group_spec.js
- app/client/src/components/propertyControls/KeyValueComponent.tsx
Fixes #8503  (issue)
// Code coverage diff between base branch:release and head branch: fix/add-option 
:red_circle: | total | 55.01 **(0)** | 36.5 **(0)** | 34.72 **(-0.01)** | 55.4 **(-0.01)**
:green_circle: | app/client/src/components/propertyControls/KeyValueComponent.tsx | 15.79 **(0.08)** | 24 **(0)** | 0 **(0)** | 17.14 **(-0.05)**
> fix:  add pre-filled option on adding an option to a checkbox or radio button

- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/dtos/PreparedStatementValueDTO.java
- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/FilterDataServiceCE.java
- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/IFilterDataServiceCE.java
- app/server/appsmith-interfaces/src/test/java/com/appsmith/external/services/FilterDataServiceTest.java
Fixes #10798
When the where clause params have a repeated key, they're getting merged since we're using a map to store these parameters. We end up having a lesser key count for params and hence see this error. Fix was to convert the map into a list to parse through irrespective of repetition. Also introduced a DTO instead of using a map to allow consistent and cleaner consumption.
> fix: Fixed issue with H2 where PS parameters were getting merged if the keys were the same

- app/client/src/components/ads/TreeDropdown.tsx
This PR has the fix the overflow not scrolling when the list of queries are more than the screen height in Execute query section.
Fixes #10835
- Tested locally by adding more than 20 queries.
// Code coverage diff between base branch:release and head branch: bug-fix/10835-execute-query-overflow-scroll 
:green_circle: | total | 54.93 **(0)** | 36.39 **(0.01)** | 34.6 **(0)** | 55.34 **(0)**
> fix: Execute query overflow scroll issue

- app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Organization.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ResponseUtils.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ApplicationFetcherImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ApplicationFetcherCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/ResponseUtilsTest.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ApplicationFetcherUnitTest.java
- app/server/appsmith-server/src/test/resources/test_assets/ResponseUtilsTest/mockObjects.json
> While fetching the applications for the homepage using all the orgs we were not updating the applicationPageIds which was resulting in the unexpected state as the client always expects the default ids for all the resources. 
Fixes #10793
> JUnit test
> Manual test
> fix: Update ApplicationPageId with defaultPageId while fetching applications for homepage 

- app/client/src/sagas/PageSagas.tsx
- app/client/src/utils/helpers.test.ts
- app/client/src/utils/helpers.tsx
**Summary of changes**
- Added a function called `isInvalidDynamicBindingPath` in the PageSagas.tsx
**Motivation**
- This function will log error into the sentry whenever the property value is not Dynamic and the bindingPath is still present in the `dynamicBindingPathList`
- Thus the function - Checks if dynamicBindingPathList contains a property path that doesn't have a binding
Fixes #10712
I have update the unit test file: `helpers.test.ts` 
The test case checks the following:
- Check if the DSL is not altered
- Checks if dynamicBindingPathList contains a property path that doesn't have a binding …
> fix: added sentry exception for invalid DynamicBindingListPath

- app/client/cypress.env.json
- app/client/src/widgets/MultiSelectTreeWidget/widget/index.tsx
- app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
- app/client/src/widgets/SwitchWidget/component/index.tsx
FIxes onOptionChange for TreeSelect and Multiselect
Fixes #9078
Fixes #9598
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: fix/OnOptionChange-called-twice-in-Tree-select 
:green_circle: | app/client/src/widgets/SwitchWidget/component/index.tsx | 93.75 **(0.42)** | 62.5 **(0)** | 50 **(0)** | 93.75 …
> fix: onOptionChange on TreeSelects and fix Switch Toggle

- app/client/src/constants/WidgetValidation.ts
- app/client/src/workers/evaluationUtils.ts
- app/client/src/workers/validations.ts
This PR updates typescript interface `Validator`, makes `props` required from optional. We are doing so in order ensure that props is passed for `ValidationTypes.FUNCTION`. 
Fixes #10850 
Not required.
// Code coverage diff between base branch:release and head branch: fix/10850-make-props-required 
:green_circle: | total | 54.95 **(0.01)** | 36.4 **(0.01)** | 34.61 **(0)** | 55.36 **(0.01)**
:green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 72.55 **(1.96)** | …
> fix: props is now required in type Validator

- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java
- app/server/appsmith-server/src/test/resources/test_assets/ImportExportServiceTest/valid-application.json
> When the application is imported from the JSON file with null pageId for action and actionCollection, internal server error is thrown. This PR will use the unpublished resource pageId as a fallback when the published one don't have one for actions and/or action collection and then import the application.
Fixes https://github.com/appsmithorg/appsmith/issues/10857
> Junit TC
> Manual testing
> fix: Fix NPE during import when page ids are missing for published action and actionCollection 

- app/client/src/components/editorComponents/JSResponseView.tsx
The response tab was disabled if the code has lint warnings. We want to disable it only on errors.
Fixes #10824 
// Code coverage diff between base branch:release and head branch: 10824-fix 
> fix: enable response tab in js editor even if it has warnings

- .github/workflows/integration-tests-command.yml
- .github/workflows/test-build-docker-image.yml
Support reuse of github actions
Using github cache we avoid rerunning successful jobs 
Fixes # 
Tested push workflow in my own fork.
ok-to-test flow is not tested.
> test: Support reuse of github actions

- app/client/src/components/editorComponents/ApiResponseView.tsx
This PR introduces an Headers tab to the API pane response view, thus giving users the ability to see the headers attached to the responses of their queries.
Fixes #9766
Manual Tests.
// Code coverage diff between base branch:release and head branch: feat/show-response-header 
:red_circle: | total | 54.94 **(0)** | 36.39 **(-0.01)** | 34.61 **(0)** | 55.34 **(-0.01)**
:red_circle: | app/client/src/components/editorComponents/ApiResponseView.tsx | 56.41 **(-2.26)** | 38.46 **(-5.02)** | 0 **(0)** | 56.41 …
> feat: adds Headers tab to the Api response view

- app/client/src/actions/metaActions.ts
- app/client/src/reducers/entityReducers/metaReducer.ts
- app/client/src/sagas/EvaluationsSaga.ts
- app/client/src/workers/evaluationUtils.ts
Fixes #10818
Changing the logic to only update metaReducer values when there is a change between previous dataTree and current data tree. 
**Caveat** - This logic assumes that when a widget property's default and meta value both change, it is okay to give preference to the default value and clear the meta.
For meta-evaluation changes refer - https://github.com/appsmithorg/appsmith/pull/10401
// Code coverage diff between base branch:release and head branch: fix/metaEval-raceCondition 
:red_circle: | total | 54.94 **(0)** | 36.38 **(-0.01)** | 34.61 **(0)** | …
> fix: Race condition issue of meta reducer update

- app/client/src/constants/AppsmithActionConstants/ActionConstants.tsx
- app/client/src/workers/DataTreeEvaluator.test.ts
- app/client/src/workers/DataTreeEvaluator.ts
- app/client/src/workers/evaluate.test.ts
- app/client/src/workers/evaluate.ts
- app/client/src/workers/validations.ts
Description:
Bringing back #9651 with some changes. (Which was reverted here #10322).
- Will support `this.params` in normal function IIFE's. (replacing `this.params` with `executionparams`)
- Will fix #10784
---
List of covered scenarios:
no optional chaining `this.params`:
- `{{ (function() { return this.params.condition })() }}`
- `{{ (() => { return this.params.condition })() }}`
- `{{ this.params.condition }}`
with optional chaining `this?.params`:
- `{{ (function() { return this?.params.condition })() }}`
- `{{ (() => { return this?.params.condition })() }}`
- `{{ this?.params.condition }}`
with optional chaining `this?.params?`:
- `{{ (function() { return this?.params?.condition })() }}`
- `{{ (() => { return this?.params?.condition })() }}`
- `{{ this?.params?.condition }}` …
> fix: passing params from JS to API/SQL query

- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/FilterDataServiceCE.java
- app/server/appsmith-interfaces/src/test/java/com/appsmith/external/services/FilterDataServiceTest.java
- The sort component introduced as part of UQI currently fails if any of the column names are empty. This is a problem because if a sort component is added to a query editor form then at least one sort component with an empty column gets added by default, which can make the query fail.
- This PR adds changes to ignore all the empty column names (or ignore the sort conditon if all column names are empty). 
Fixes #10896
- JUnit TC
- Manual
> fix: handle empty column name in UQI sort component

- app/server/appsmith-git/pom.xml
- app/server/appsmith-git/src/main/java/com/appsmith/git/converters/GsonDoubleToLongConverter.java
- app/server/appsmith-git/src/main/java/com/appsmith/git/converters/GsonUnorderedToOrderedSetConverter.java
- app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
- app/server/appsmith-git/src/main/java/com/appsmith/git/service/GitExecutorImpl.java
- app/server/appsmith-git/src/test/java/GsonDoubleToLongConverterTest.java
- app/server/appsmith-git/src/test/java/GsonUnorderedToOrderedSetTest.java
- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/dtos/GitStatusDTO.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/CompareDslActionDTO.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitFileUtils.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/CompareDslActionDTOTest.java
> As Set is an unordered datatype, this is causing unnecessary changes to the file system during the commit operation even if the user has not altered anything since the last commit.
Fixes #10932
> JUnit TC
> Manual test
> fix: Sort unordered set elements before committing to git repo so as to have same serialised output string for identical set of elements

- app/client/src/actions/metaActions.ts
- app/client/src/constants/AppsmithActionConstants/ActionConstants.tsx
- app/client/src/reducers/entityReducers/metaReducer.ts
- app/client/src/sagas/EvaluationsSaga.ts
- app/client/src/utils/DSLMigrations.ts
- app/client/src/utils/migrations/TableWidget.ts
- app/client/src/workers/DataTreeEvaluator.test.ts
- app/client/src/workers/DataTreeEvaluator.ts
- app/client/src/workers/evaluate.test.ts
- app/client/src/workers/evaluate.ts
- app/client/src/workers/evaluationUtils.ts
- app/client/src/workers/validations.ts
Merged
• [#10826](https://github.com/appsmithorg/appsmith/pull/10826)
• [#10837](https://github.com/appsmithorg/appsmith/pull/10837)
• [#10897](https://github.com/appsmithorg/appsmith/pull/10897)
Merging release blocker fixes
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: chore/releaseBlockerFixes-v1.6.9 
:green_circle: | total | 55.03 **(0.04)** | 36.49 **(0.18)** | 34.74 **(0.06)** | 55.43 **(0.06)**
:green_circle: | app/client/src/components/ads/DraggableList.tsx | 44.26 **(8.39)** | 33.33 **(14.69)** | 21.43 **(-5.24)** | 51.02 **(12.27)** …
> chore: releaseBlockerFixes-v1.6.9

- app/client/src/components/editorComponents/form/fields/StyledFormComponents.tsx
- app/client/src/pages/Editor/FormControl.tsx
This PR fixes the margin top property for info texts beneath Checkboxes and other form controls.
Fixes #10783 
Manual tests.
// Code coverage diff between base branch:release and head branch: fix/fix-checkbox-info-text 
:red_circle: | total | 54.98 **(-0.01)** | 36.32 **(0)** | 34.67 **(-0.01)** | 55.37 **(0)**
:red_circle: | app/client/src/components/editorComponents/form/fields/StyledFormComponents.tsx | 65.38 **(-2.62)** | 15.56 **(-0.35)** | 0 **(0)** | 65.38 **(-2.62)**
:red_circle: | app/client/src/pages/Editor/FormControl.tsx | 24.44 **(-1.14)** | 0 …
> fix: fix margin top issues with checkbox form controls

- app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/FirestorePlugin.java
- app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/utils/WhereConditionUtils.java
- app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java
Fixed issue with Firestore in fetching data while using numbers in the where condition.
Other Fixes made in the where condition :
1. When using Boolean
2. When using Date
3. When Using Timestamp
4. When given space in the key
5. When Space given in the Value
Fixes #9414
> Manually
> fix: 9414 Firestore where clause not fetching numbers

- app/client/src/constants/messages.ts
- app/client/src/workers/helpers.test.ts
- app/client/src/workers/helpers.ts
- app/client/src/workers/validations.test.ts
- app/client/src/workers/validations.ts
When we have large, improperly formatted, data being validated; large number of error messages are rendered in the debugger.
For example, if we're trying to bind an array with 20000 entries (objects) in a chart widget, and these entries do not have `x` and `y` properties, validations return 20000 error messages (one for each entry). When the debugger tries to render these many messages, the application freezes for a few seconds. 
The solution here, is to bail out of validations early **_IF_** we have already encountered a fixed number (in this case 10) of validation errors and show these messages in the debugger.
Does it negatively effect DX?
Fixing the issues shown so far will trigger another validation. As a result,
- If there are more validation errors, they will be displayed. 
- If …
> fix: limit validation errors in debugger

- app/client/src/components/formControls/BaseControl.tsx
- app/client/src/components/formControls/PaginationControl.tsx
- app/client/src/components/formControls/SortingControl.tsx
- app/client/src/pages/Editor/FormControl.tsx
This PR addresses the following issues:
- Pagination fields should be in single row
- Too much gap between label and first input field in Sort component
- Need a way to assign initial value to Pagination component.
**Type of change**
Manual Tests.
// Code coverage diff between base branch:release and head branch: fix/fix-uqi-components 
:red_circle: | total | 54.98 **(-0.01)** | 36.31 **(-0.01)** | 34.68 **(0)** | 55.37 **(0)**
:red_circle: | app/client/src/components/formControls/PaginationControl.tsx | 60 **(0)** | 50 **(-50)** | 25 **(0)** | 58.62 **(0)** …
> fix: fixes uqi component issues

- app/client/src/constants/messages.ts
- app/client/src/workers/validations.ts
[`$RefreshReg$`](https://stackoverflow.com/questions/66472945/referenceerror-refreshreg-is-not-defined) issue shows up in the browsers log, when running the application using `yarn start`
This was introduced in #10886 ( mea culpa 😞 )
To fix this we need to remove all references to `messages.ts` from the files in the worker folder. This is until a proper fix that allows this reference is figured.
Existing tests must pass for this to be valid
> fix: Remove references of messages.ts in worker files

- app/client/src/widgets/MapWidget/widget/index.tsx
- Pinned location should move when location changes on the map when Map & marker centering is turned on. Currently, the pin moves as location changes but manual intervention is needed to center or even bring the pin into view since it does not auto-adjust.
- Update center meta property accordingly when defaultMarkers or mapCenter properties were changed
Fixes #9844 
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: fix/9844-map-pin-center 
:red_circle: | total | 55.06 **(-0.01)** | …
> fix: Map pin does not center when location is changed and centering option is turned on

- app/client/src/components/editorComponents/ActionNameEditor.tsx
- app/client/src/components/utils/NameEditorComponent.tsx
- app/client/src/constants/messages.ts
- app/client/src/pages/Editor/Explorer/Entity/Name.tsx
- app/client/src/pages/Editor/JSEditor/JSObjectNameEditor.tsx
- app/client/src/selectors/actionSelectors.tsx
- app/client/src/selectors/ui.tsx
- app/client/src/selectors/widgetSelectors.ts
1. Added Datasource Icon on the left of the query name on the Query Editor page to signify the type of editing datasource query
2. There were multiple components with similar logic to identify the conflicting names when editing names of JSObject, Query Name, PageName, Names in the Entity Explorer Menu. Revamped and added a new wrapper component for Multiple Components so that logic for name editing remains at one point.
Fixes #10542 
1. Changing Name from the Query Editor page and see if it reflects on the entity explorer as well.
2. Changing Name from the Page Editor page and see if it reflects on the entity explorer as well.
3. Changing Name from JS Object Editor page and see if …
> feat: added datasource icon on left of entity name, revamped name editor

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/CurrencyInput_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Phone_input_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/input_v2_spec.js
- app/client/src/widgets/BaseInputWidget/widget/index.tsx
- app/client/src/widgets/CurrencyInputWidget/widget/index.tsx
Fixes #10859
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: fix/phone-input-widget-reset 
:green_circle: | total | 54.99 **(0)** | 36.33 **(0.02)** | 34.68 **(0)** | 55.37 **(0)**
:red_circle: | …
> fix: Phone Input and Input widget not getting reset on submit issue

- app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/Aggregate.java
- app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java
Fixes #5326, by making JSON string validation more strict.
- Test case is added [testAggregateCommandWithInvalidQuery](https://github.com/appsmithorg/appsmith/blob/9d8d980b356dab2d109bbc047b5c021d8d0de4f5/app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java#L1441)
> fix: Added stricter validation for Mongo pipeline

- app/client/src/widgets/TextWidget/component/index.tsx
When we introduced tailwind to the project, the default heading styles on text widget got ruined. This PR fixes that.
Fixes #10936 
- Bug fix
// Code coverage diff between base branch:release and head branch: fix/text-widget-default-styles 
:red_circle: | total | 55.01 **(-0.01)** | 36.35 **(0)** | 34.69 **(0)** | 55.39 **(-0.01)**
> fix: Header tags are not styled correctly in the Text widget

- app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
- app/server/appsmith-git/src/main/java/com/appsmith/git/service/GitExecutorImpl.java
- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/Stopwatch.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
Git APIs are slow today and these also involves a lot of operation:
- Hydration and rehydration from and to Mongo DB
- Copying the serialized objects file system
- Working with local as well as remote git APIs
Current PR simply logs the execution time in milliseconds for the above-mentioned tasks, which can be utilized to optimize the implementation
Fixes #11068 
> Manual test
> chore: Add stopwatch to log execution time by process name

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/input_v2_spec.js
- app/client/cypress/support/commands.js
- app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx
- app/client/src/widgets/BaseInputWidget/widget/index.tsx
Fixes #10893
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: fix/input-widget-validation-property 
:green_circle: | total | 55.06 **(0)** | 36.39 **(0.01)** | 34.7 **(0)** | 55.43 **(0)**
> fix: Input, Phone and Currency input widgets valid property validations

- app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
> Looking at the performance advisor from the MongoDB atlas we can see the issue is with the indexes which are present today for ActionCollection and NewAction, this PR updates the indexes as suggested and creates a compound indexes based on pageIds and deleted field.
Fixes https://github.com/appsmithorg/appsmith/issues/11139
> fix: Update indexes for ActionCollection and NewAction to improve the query performance for getResourceByPageId

- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/PluginUtils.java
- app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java
- app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/constants/AmazonS3Action.java
- app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/utils/TemplateUtils.java
- app/server/appsmith-plugins/amazons3Plugin/src/main/resources/editor/delete_many.json
- app/server/appsmith-plugins/amazons3Plugin/src/main/resources/editor/root.json
- app/server/appsmith-plugins/amazons3Plugin/src/test/java/com/external/plugins/AmazonS3PluginTest.java
- Add a new command `Delete multiple files`. This command will allow users to delete many files at once. Currently, only one file can be deleted at a time. 
- It takes an array of files as config parameter from the user e.g. `["file1", "file2"]`
- Add template for the new command.
- Unrelated:
- Add template for the command `Create multiple files`
Fixes #10918
- JUnit TC
- Manual
> feat: S3 plugin: add command to delete multiple files at a time

- app/client/src/entities/Datasource/RestAPIForm.ts
- app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
- app/client/src/transformers/RestAPIDatasourceFormTransformer.ts
- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/ExceptionHelper.java
- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/SSLHelper.java
- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ActionExecutionResult.java
- app/server/appsmith-plugins/arangoDBPlugin/src/main/java/com/external/utils/SSLUtils.java
- app/server/appsmith-plugins/restApiPlugin/pom.xml
- app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
Enabled use of self-signed certificates for REST APIs. We're expected to create a datasource for all APIs that need this feature. Addition is non-intrusive to existing actions because of null check and exact value checks.
I've also updated the error handling to always go to the root of the exception since that might help us debug issues more easily. Might want to take up handling different types of errors to give more sensible messages in a separate issue.
https://user-images.githubusercontent.com/5298848/153184897-b5d78a15-3a59-4c53-b128-e826cdf00278.mov
Fixes #4608 
- Manually tested since we haven't mocked out client yet. Should invest in this infra soon …
> feat: Self-signed certificates for REST APIs

- app/server/appsmith-plugins/amazons3Plugin/src/main/resources/editor/read.json
- This PR removes the `Expiry Duration` field from the `Read file` command of `S3` plugin.
- An `Expiry Duration` field got added to `Read file` command mistakenly some time post migration to UQI schema. This field did not exist with the read command before the migration and does not get used even now.
Fixes #11115 
- Manually
> fix: S3 plugin: remove `Expiry Duration` config from  `Read file` query

- app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/Aggregate.java
- app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/Count.java
- app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/Distinct.java
- app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/utils/MongoPluginUtils.java
- app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java
This is a cleaned up version of PR #10626 without client side code.
Refer to: https://github.com/appsmithorg/appsmith/pull/10626.
`app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java`
> feat: Add Mongo Templates for plugin.

- app/client/package.json
- app/client/yarn.lock
Upgrade jshint
// Code coverage diff between base branch:release and head branch: chore/bump-up-jshint 
:red_circle: | total | 55.42 **(-0.03)** | 36.99 **(-0.02)** | 35.3 **(-0.09)** | 55.8 **(-0.04)**
:red_circle: | app/client/src/components/ads/StepComponent.tsx | 40.91 **(-52.19)** | 66.67 **(-23.33)** | 0 **(-100)** | 40.91 **(-52.19)**
:red_circle: | app/client/src/constants/IconConstants.tsx | 100 **(0)** | 83.33 **(-4.17)** | 100 **(0)** | 100 **(0)**
:red_circle: | app/client/src/icons/ControlIcons.tsx | 68.42 **(-1.5)** | 100 **(0)** | 35.38 **(-3.08)** | 68.42 **(-1.5)**</details>
> chore: upgrade jshint to fix security alert

- app/client/src/widgets/RateWidget/widget/index.tsx
- When we change the value of the Rating widget we can see the stars flicker (flash).
- This was due to the value prop override caused by spreading `{...this.props}`. Thanks @sbalaji1192 for the insights on derived properties.
Fixes #10697 
- Tested Manually on the Canvas.
> fix: rating widgets flickering when value is reduced.

- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/FilterDataServiceCE.java
- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/IFilterDataServiceCE.java
- app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/GetValuesMethod.java
- app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/Method.java
- Fix for Larger data introduced down the row grid
- Fix for mixed Numeric DataType like Number and Float
- Fix to ignore data of another DataType introduced down the line not Matching the Original DataType (first row datatype)
Fixes #7794 
Fixes #9667
- Bug fix (non-breaking change which fixes an issue) 
- Existing @Tests were checked to work fine
- Added new @Tests to test new implementation
> fix: 7794 Google Sheet Fails with Mixed Datatype

- app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
- app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java
When calling test datasource on MongoDB if it encounters an unauthorized error plugin ignores that and shows a successful message. It's because in test datasource logic we call a query that tries to access the admin database of MongoDB, so it's possible to get an unauthorized error even if we have access to other user-defined databases. 
Now after this fix if it gets an unauthorized error accessing the admin database it will try to access the default database to make sure that credentials are valid or not.
Fixes #11067 
- Tested manually with a MongoDB datasource that needed credentials accessing it.
> fix: showing invalid credentials message on  MongoDB test datasource if there is an unauthorized error

- app/client/src/components/editorComponents/form/fields/StyledFormComponents.tsx
- app/client/src/pages/Editor/FormControl.tsx
Manually
// Code coverage diff between base branch:release and head branch: fix/encryted-tage-form-spacing 
:green_circle: | app/client/src/components/editorComponents/form/fields/StyledFormComponents.tsx | 67.86 **(2.48)** | 17.39 **(1.83)** | 0 **(0)** | 67.86 **(2.48)**</details>
> fix: Spacing for encrypted tag for form control

- app/server/appsmith-git/src/main/java/com/appsmith/git/service/GitExecutorImpl.java
- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/git/GitExecutor.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/constants/AnalyticsEvents.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/GitControllerCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> A user should have an option to regenerate the ssh keys for the git connected applications in case the key is compromised. This change set adds an API to test the connection after the key is regenerated by the user. 
Fixes #10299
- Locally
- TC's on the way
> feat: Add api to check the git connection after the key is regenerated

- app/client/cypress/fixtures/promisesBtn.json
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/PromisesSpec.ts
- app/client/src/actions/batchActions.ts
- app/client/src/actions/metaActions.ts
- app/client/src/actions/pageActions.tsx
- app/client/src/actions/pluginActionActions.ts
- app/client/src/constants/ReduxActionConstants.tsx
- app/client/src/sagas/ActionExecution/ResetWidgetActionSaga.ts
- app/client/src/sagas/ActionExecution/StoreActionSaga.ts
- app/client/src/sagas/EvaluationsSaga.ts
- app/client/src/sagas/PostEvaluationSagas.ts
If we don't let the evaluation finish before completing resetWidget and storeValue, next function in promise chain is executed before it's effects are reflected in the data tree
Fixes #11110 
TODO
// Code coverage diff between base branch:release and head branch: fix/reset-and-store-wait-till-evaluation 
:red_circle: | total | 55.53 **(-0.01)** | 37 **(-0.01)** | 35.76 **(0)** | 55.87 **(-0.01)**
:red_circle: | app/client/src/components/editorComponents/form/fields/StyledFormComponents.tsx | 65.38 **(-2.48)** | 15.56 **(-1.83)** | 0 **(0)** | 65.38 **(-2.48)** …
> fix: Wait for evaluation before completing resetWidget and storeValue functions

- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java
> This PR removes the theme ids during the git commit as this info is already present in `editModeTheme` and `publishedTheme`
> chore: Remove theme ids during git commit

- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeStringUtils.java
- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/FilterDataServiceCE.java
- app/server/appsmith-interfaces/src/test/java/com/appsmith/external/helpers/DataTypeStringUtilsTest.java
- Fix for Comma delimited Number with or without decimal places
Fixes #8878 
- Bug fix (non-breaking change which fixes an issue) 
- Existing @Tests were checked to work fine
- Added new @Tests to test new implementation
> fix: 8878 - To handle Comma delimited float values

- app/client/src/components/ads/Icon.tsx
- app/client/src/components/ads/common.tsx
There are few places in code where we are using switch control flow. Switch itself if not bad, but in our cases, we are simply returning or using cases for one-to-one mapping. This PR brings that 1-1 mapping to a lookup table.
Lookup tables have added benefit of being faster than control structures, the case checks are replaced with keys lookup in the table.
Fixes #11224 
- Performance enhancement
- Code cleanup
Manually.
// Code coverage diff between base branch:release and head branch: 11224-lookup-tables 
:green_circle: | total | 55.7 **(0.16)** | 37.06 **(0.06)** | 35.76 **(0.01)** | 56.05 **(0.18)** …
> chore: introduce lookup tables inplace of switch

- app/client/src/workers/DataTreeEvaluator.ts
Don't make `trigger fields` dependent on anything else.
This PR annuls the changes in #10941 
Fixes #11136 
Manual
// Code coverage diff between base branch:release and head branch: fix/revert-trigger-field-dependencies 
:red_circle: | total | 55.69 **(-0.01)** | 37.05 **(-0.01)** | 35.75 **(0)** | 56.05 **(0)**
:red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 …
> fix: remove dependencies from trigger fields

- app/client/src/pages/Editor/gitSync/components/DeployedKeyUI.tsx
- app/client/src/pages/Editor/gitSync/components/TabItem.tsx
Show notification banner on SSH key generation and regeneration
Remove BETA tag from Git Connection
Fixes #11248 
Manually
> fix: update git connect modal

- app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
- app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java
Test MongoDB datasource shows ok even if there is no database matching the name in the 'Default Database Name' input.
Fixes #11214
- Test case [`MongoPluginTest.testDatasourceFailWithInvalidDefaultDatabaseName()`](https://github.com/appsmithorg/appsmith/blob/979bd9b2d066f1ab028001fa8e91827569786698/app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java#L189)  is added
- Tested manually
> fix: Fixed test MongoDB datasource shows ok even if there is no database matching the name in the 'Default Database Name' input

- app/client/perf/src/ci/supabase.js
We are saving only the last performance run data when there are multiple runs.
This PR fixes it.
> chore: Save data of all performance runs

- app/client/src/widgets/RateWidget/component/index.tsx
- The Rating widget has 2 color properties - active color & inactive color. When we select the value "No color", both activeColor & inactiveColor props receive no value and default to black color for both states.
- My solution was to default to the - #D6D6D6 color when we pass "No color" for the inactive value rather than the browser's default black color, if the user wants black for the inactive value he can simple choose black from the color-picker.
Fixes #10766
- Tested Manually on the Canvas.
// Code coverage diff between base branch:release and head branch: fix/10766-rating-inactive-color  …
> fix: Rating Widget inactive-color.

- deploy/helm/README.md
- deploy/helm/Setup-https.md
- deploy/helm/templates/NOTES.txt
- deploy/helm/templates/ingress.yaml
- deploy/helm/values.yaml
- Refactor Helm ingress template with default path. Add flow to configure template in case no domain provided
- Update document follow implementation. Add section Expose Appsmitth 
- Follow section Expose Appsmith in document & able to get the public address for Appsmith
> feat: Refactor helm ingress template to configure without domain

- app/client/src/pages/Editor/Explorer/JSActions/JSActionEntity.tsx
- app/client/src/reducers/entityReducers/jsActionsReducer.tsx
In case of a slow network, if the user clicks on the newly created js object before API finishes. Navigated path doesn't get js object id hence app crashes.
Fixes #10601 
// Code coverage diff between base branch:release and head branch: 10601-fix 
:green_circle: | total | 55.44 **(0.01)** | 37 **(0.01)** | 35.3 **(0)** | 55.82 **(0.01)**
:red_circle: | app/client/src/pages/Editor/Explorer/JSActions/JSActionEntity.tsx | 58.33 **(-2.54)** | 0 **(-100)** | 0 **(0)** | 58.33 **(-2.54)**
:green_circle: | app/client/src/reducers/entityReducers/jsActionsReducer.tsx | …
> fix: push js object after creation

- app/client/src/widgets/PhoneInputWidget/component/ISDCodeDropdown.tsx
> update CSS for ISD code DropDown it is a fixed issue of Phone number placeholder collapses when input is disabled
Fixes #10686 
// Code coverage diff between base branch:release and head branch: fix/phone-number-placeholder 
:green_circle: | total | 55.45 **(0)** | 37.01 **(0.01)** | 35.39 **(0)** | 55.84 **(0)**
:red_circle: | app/client/src/widgets/PhoneInputWidget/component/ISDCodeDropdown.tsx | 51.11 **(-1.16)** | 23.53 …
> fix: updated css for ISDCode Dropdown

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ApiPaneTests/API_Multipart_spec.js
- app/client/src/sagas/ApiPaneSagas.ts
- app/client/src/selectors/apiPaneSelectors.ts
This PR fixes post body type switcher in API editor, Prior to this PR, switching the post body to Raw changes the content-type to "text/plain", This fixes that by preserving the previous content-type when user switches to raw or none body type. It also gives users the flexibility to use any non supported content type, while in Raw body mode.
// Code coverage diff between base branch:release and head branch: fix/post-body-switcher  …
> fix: Prevent content-type header from changing when switching to raw mode in API pane

- app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx
`* { scrollbar-width: thin; }` adds a scrollbar to every element, firefox takes this personally and adds a second scrollbar to git connect modal when the content starts overflowing.
This PR removes `scrollbar-width` from git-connect container.
Fixes #10844 
Manually.
Before changes:
After changes:
https://user-images.githubusercontent.com/1573771/155083564-b9280fbb-8931-4e0a-86d3-8fd3b4f71365.mov
> chore: remove second scrollbar from git connect modal

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/DatePicker_2_Default_spec.js
- app/client/src/workers/validations.ts
In the worker thread, we were using lodash's cloneDeep function to clone the data tree, we recently started using a new library to clone to improve performance ([PR](https://github.com/appsmithorg/appsmith/pull/11001/files)).
Due to this change, Datepicker defaultValue is no longer evaluating to string, it gets evaluated to moment object, which results in the above error.
Fixes #11381 
- Test A
- Test B …
> fix: Update date ISO string validations

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_Widget_Add_button_spec.js
- app/client/cypress/locators/Widgets.json
- app/client/src/components/ads/ColorPickerComponent.tsx
- app/client/src/widgets/TableWidget/widget/index.tsx
Make table button transparent when no color is selected
Fixes #10276
- Cypress test
// Code coverage diff between base branch:release and head branch: fix/button-color-does-not-change-to-transparent 
:red_circle: | app/client/src/utils/WorkerUtil.ts | 88.98 **(-0.78)** | 68.63 **(-3.92)** | 100 **(0)** | 92.38 **(-0.95)**
> fix: make table button transparent when no color is selected

- deploy/docker/docker-compose.yml
This is an inconsistency fix. We are already providing the `latest-dev` from our documentation, it's just not set so in this example file.
> chore: Use `latest-dev` for watchtower

- app/server/appsmith-server/src/main/java/com/appsmith/server/notifications/EmailSender.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/EmailEventHandlerCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/EmailEventHandlerTest.java
When someone adds a comment to a thread, we send a email notification to the subscribers of that thread. The email has resply-to set to appsmith email address. If someone replies to that email, it's sent to an appsmith email address. This PR sets comment author's email address in the reply-to field so that replying to that email will be sent to the authors inbox.
Fixes #11016
- Unit tests
- Manually
> fix: Set comment authors email address as reply to field in comment notification email

- app/client/src/components/ads/DraggableList.tsx
Bug:
- Drag and drop a page on an overlap with another and the list items don't proceed to assume normal positions.
- The screen then crashes due to and undefined prop.
Fix:
- Validate if updateDragging is truthy before calling the function.
Fixes #11191
1. Create multiple pages in an app.
2. Go to Pages Editor screen.
3. Drag n drop a page to re-order them. Attempt to drop the selected page in an overlapping position with another.
4. Observe that the pages assume standard positioning after the drop and re-order if necessary.
// Code coverage diff between base branch:release and head branch: fix_11191_page_dragging …
> fix: page dragging in Pages editor

- app/client/src/sagas/JSActionSagas.ts
After deletion of js object, URL was redirected towards another js object causing pages to change. Instead, it will now redirect to the page make it consistent across Appsmith
Fixes #8502 
// Code coverage diff between base branch:release and head branch: 8502-fix 
:green_circle: | total | 55.72 **(0.01)** | 37.09 **(0.01)** | 35.78 **(0)** | 56.08 **(0.01)**
:green_circle: | app/client/src/sagas/JSActionSagas.ts | 17.39 **(0.72)** | 2.13 **(0.17)** | 6.67 **(0)** | 20.61 **(0.9)**</details>
> fix: after JS object delete success move to page url

- app/client/src/utils/helpers.tsx
Completed fix for Page Name in preview mode, Deploy Mode was done in #10667 
Fixes #9969
> Visual testing
> fix: long page name text cutting off in preview mode

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/DatePicker_2_Default_spec.js
- app/client/src/workers/validations.ts
Cherry picking fix from #11399.
// Code coverage diff between base branch:master and head branch: chore/fix-date-iso-validations 
:red_circle: | total | 55.76 **(0)** | 37.09 **(-0.04)** | 35.81 **(0)** | 56.12 **(0)**
:red_circle: | app/client/src/workers/validations.ts | 81.32 **(-0.63)** | 70.57 **(-0.66)** | 76.67 **(0)** | 82.39 **(-1)**</details>
> fix: Update date ISO string validations (#11399)

- app/client/src/widgets/BaseInputWidget/component/index.tsx
Steps To Reproduce
1. Drag and drop an Input widget
2. In Icon property from property pane set an icon
3. Observe that the left border of the widget is not displayed.
Fixes #11198 
- Test A
- Test B
> fix: UI of Input widget is not proper when icon is set and left aligned

- app/client/src/components/ads/Button.tsx
- app/client/src/components/ads/Dropdown.tsx
- app/client/src/pages/Editor/PropertyPane/ConnectDataCTA.tsx
- app/client/src/pages/Editor/PropertyPane/PropertyPaneConnections.tsx
- app/client/src/pages/Editor/PropertyPane/PropertyPaneView.tsx
The header section of the property pane includes the copy, delete, connect data buttons and incoming and outgoing entities dropdown is made accessible via keyboard.
Use `Tab` keys to shift focus and `Enter` | `Space` to interact with a component in focus.
In case of dropdown, make use of `ArrowUp` and `ArrowDown` keys to change the selection and `Enter` | `Space` to click the selected option. `Esc` to close the dropdown.
Fixes #11338 
Manually
// Code coverage diff between base branch:release and head branch: kbd-accessible-pp-header 
:red_circle: | total …
> feat: Keyboard accessible property pane header

- app/server/appsmith-server/src/main/java/com/appsmith/server/services/CurlImporterServiceImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CurlImporterServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java
Before if the content-type was not specified and there was a body value, curl import (in the new datasource page) was treating the request as form-urlencoded, but now it tries to guess the content-type for the request.
it checks for `x-www-form-urlencoded` or `json` or sends it as raw without any content-type header.
Fixes #7900
- Tested manually
- Unit tests are fixed for it
> fix: curl import tries to guess the content-type from the body if content-type header is not specified

- app/rts/src/server.ts
We don't need to allow all origins to access the RTS API anymore.
> Remove CORS allow-star from RTS

- app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
Also taking this opportunity to create a new Changelog class, with incremented order at the class-annotation level. Let's add all future migrations to this class instead?
Partially resolves https://github.com/appsmithorg/appsmith/issues/10848.
> chore: Fix casing of plugin names

- app/client/src/pages/Editor/APIEditor/CurlImportForm.tsx
- app/client/src/sagas/ActionExecution/PluginActionSaga.ts
This PR fixes the bad UI designs and UX on the Curl Editor Page, It also allows the use of Shortcuts on the curl editor page i.e. the CMD + Enter shortcut key, making it possible for users to use the shortcut key to execute Curl import queries.
Fixes #11029 
- [] I have made corresponding changes to the documentation
// Code coverage diff between base branch:release and head branch: fix/fix-curl-editor-page 
:green_circle: | app/client/src/components/ads/Dropdown.tsx | 82.21 **(1.28)** | 61.85 **(0.76)** | 69.44 …
> fix: Fixes UI and functionality issues on the Curl editor page

- app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
>  When the user tries to connect a repo(gitLab or any) and if the repo contains `.yml` file connect fails with error.
`.yml` files are used for CI purpose and we should allow such scenarios.
Fixes #11430 
- Locally
> fix: Fix git connect failure for repo with yml CI files

- app/client/src/actions/evaluationActions.ts
- app/client/src/api/PluginApi.ts
- app/client/src/pages/Editor/QueryEditor/index.tsx
- app/client/src/reducers/evaluationReducers/formEvaluationReducer.ts
- app/client/src/sagas/FormEvaluationSaga.ts
- app/client/src/sagas/QueryPaneSagas.ts
The new dynamic value fetch system for dropdowns of UQI forms was a GET request. This fix changes that request to a POST request so that we can send extra payload with the call like `datasourceId`, `pluginId` and `actionId`.
Fixes #10762 
// Code coverage diff between base branch:release and head branch: fix/10762-update-api-params-for-uqi-dynamic-vals 
:red_circle: | app/client/src/sagas/FormEvaluationSaga.ts | 23.38 **(0)** | 10 **(-1.54)** | 25 **(0)** | 28.13 **(0)**
:green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(1.64)** …
> fix: Update api params for dynamic fetched values

- deploy/helm/Setup-https.md
Typo fix, the code block given already gets the `hostname` correctly, but the text around it talks about IP Address, instead of the host name.
Includes some formatting fixes as well.
> docs: Fix ip/hostname nomenclature in HTTPS doc

- app/client/package.json
Add showdown types package as a dev dependency for the client
As a fix for #7443 in PR #8121 we missed the package.json entry for `@types/showdown`
If all tests pass, this change shouldn't have effected the current client.
// Code coverage diff between base branch:release and head branch: fix/add-showdown-types 
:green_circle: | total | 55.72 **(0)** | 37.06 **(0.01)** | 35.79 **(0)** | 56.08 **(0)**
> fix: Add showdown types

- app/client/src/wdyr.ts
Release failing on local environment due to a replacement of require to import statement in #8121
All this PR does is to revert the changes made in `wdyr.ts`
Fixes:
Visually tested, also all preexisting tests should pass
> fix: revert #8121

- app/client/src/ce/constants/messages.ts
Fix extraneous space at the start of the input placeholder in the signup page.
- Manual
// Code coverage diff between base branch:release and head branch: sharat87-patch-1 
> chore: Fix extra space in email placehoder in signup page

- app/client/src/widgets/CanvasWidget.tsx
> Fix Vertical scroll issue in embed mode as well fix Scroll issue in View Mode and Model View.  
-  Height is considered `100%` when widgetId is `MAIN_CONTAINER_WIDGET_ID` . 
-  rest all widget we consider height  `snapRows * GridDefaults.DEFAULT_GRID_ROW_HEIGHT`
Fixes #9858 
// Code coverage diff between base branch:release and head branch: fix/handle-maincontainer-height 
:red_circle: | …
> fix: handle main container height

- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/Condition.java
- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/FilterDataServiceCE.java
- app/server/appsmith-interfaces/src/test/java/com/appsmith/external/services/FilterDataServiceTest.java
- app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/GetValuesMethod.java
To fetch data from Google Sheet with empty where condition, ie with no entry in Where Conditions, value field
For example, user needs this implementation as he want to search a member with no emailId from the googlesheet database.
**Features/Scenarios implemented and Tested regarding the values in the condition:**
1. When Value is Empty ""    - Pass
2. When Value is Null     null  -  Pass
3. When Value is Space  " "   - Pass
4. When Two conditions are  "" -  Pass
5. When Two conditions are null - Pass
6. When one Condition is Null and other empty - Pass
7. When both has value    - Pass
8. When both condition are empty  - Pass
9. Test for EQ  with empty / Null /  with_value   - Pass
10. Test for 'IN' for with  empty / Null     - Pass
11. Test for 'NOT_IN'  with  empty / Null     - Pass
12. …
> fix: 9824 Google Sheet to filter empty condition ver.2

- app/client/src/widgets/InputWidgetV2/widget/derived.js
- app/client/src/widgets/InputWidgetV2/widget/derived.test.ts
- app/client/src/widgets/InputWidgetV2/widget/index.tsx
In Number type Input, when value is empty, it gets converted to `0`. As a result isValid check passes. as part of this commit we made sure that the empty string is handled properly in the isValid check.
Fixes #11438 
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: fix/number-type-input-required 
:green_circle: | total | 55.74 **(0)** | 37.08 …
> fix: Number type input should honour required property when value is an empty string

- deploy/docker/scripts/init_ssl_cert.sh
- Refactor `init_ssl_cert` script to cat 2 configuration files on local build instead of fetching it 
> Feature: Remove curl call to download certbot config files for ssl

- app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/NewActionServiceCEImplTest.java
CE unit tests need to refer to CE implementations to be able to resolve dependencies accurately.
> chore: Changed test class reference to CE

- app/client/src/components/ads/CalloutV2.tsx
- app/client/src/pages/Settings/DisconnectService.tsx
- app/client/src/pages/UserProfile/General.tsx
- app/client/src/sagas/SuperUserSagas.tsx
- app/client/start-https.sh
> Remove reset password button on Edit profile page, if form login is disabled. This is because it should work only for form login. The password can be reset for other log-in options viz Google/Github on the respective platforms.
> Increase the restart banner timeout from 30s to 60s.
Fixes #11593 
> Tested reset password button shows up only when form login is enabled.
// Code coverage diff between base branch:release and head branch: hotfix/reset_pwd_btn 
:green_circle: | total | 55.72 **(0)** | 37.02 **(0.01)** | 35.18 **(0)** | 56.06 **(0.01)** …
> fix: Remove reset password button if form login is disabled

- app/client/src/sagas/ApiPaneSagas.ts
Make apiContentType nullable
// Code coverage diff between base branch:release and head branch: fix/make-apiContentType-nullable 
:red_circle: | total | 55.72 **(0)** | 37 **(-0.01)** | 35.01 **(0)** | 56.06 **(0)**
:red_circle: | app/client/src/sagas/ApiPaneSagas.ts | 16.59 **(0)** | 1.19 **(-0.11)** | 9.09 **(0)** | 18.75 **(0)**
> fix: Fix apiContentType bug

- app/client/src/sagas/ActionSagas.ts
when js object is edited loading state goes into infinite loading state. The reason was entity saving state was not getting event for js object success 
Fixes #11529 
// Code coverage diff between base branch:release and head branch: 11529-fix 
> fix: update success event was missing for js edit for loader to top

- app/client/src/widgets/CameraWidget/component/index.tsx
The aspect ratio should be kept no matter how the widget width or height is resized
Fixes #10591 
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: fix/10591-camera-aspect-ratio-issue-in-width 
> fix: Aspect ratio of video changes when Camera widget is longer in width than the aspect ratio

- app/client/src/sagas/QueryPaneSagas.ts
This PR fixes default action config values not being sent to and saved on the server side. This results to initial values not being picked up on the server side despite being shown to users unless they explicitly change a field.
Fixes #11544
// Code coverage diff between base branch:release and head branch: fix/default-values-not-set 
:red_circle: | total | 55.82 **(0)** | 37.17 **(-0.01)** | 35.2 **(0)** | 56.16 **(0)**
:red_circle: | app/client/src/sagas/QueryPaneSagas.ts | 22.66 **(0)** | 10 **(-0.87)** | 18.18 **(0)** | 26.67 **(0)**
:red_circle: | …
> fix: Default action config values not being set

- app/client/src/pages/Editor/IntegrationEditor/DatasourceCard.tsx
Reword Message 
No query is using this datasource -> No query in this application is using this data source
Fixes #11477
Manually
> fix: reword datasource message

- app/server/appsmith-server/src/main/resources/docker-compose.yml
- deploy/aws_ami/docker-compose.yml
- deploy/docker/README.md
- deploy/docker/docker-compose.yml
This is because watchtower:latest-dev doesn't run on ARM architectures.
> chore: Change watchtower to latest from latest-dev

- app/server/appsmith-plugins/smtpPlugin/src/main/resources/editor/root.json
SMTP is registered as a UQI plugin, and hence needs to follow the format per UQI aggregation.
> fix: Modified root json for SMTP to comply with UQI aggregation rules

- app/server/appsmith-plugins/graphqlPlugin/plugin.properties
- app/server/appsmith-plugins/graphqlPlugin/pom.xml
- app/server/appsmith-plugins/graphqlPlugin/src/main/java/com/external/connections/APIConnection.java
- app/server/appsmith-plugins/graphqlPlugin/src/main/java/com/external/plugins/GraphQLPlugin.java
- app/server/appsmith-plugins/graphqlPlugin/src/main/resources/form.json
- app/server/appsmith-plugins/pom.xml
- app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
- Note: Currently it is being merged to development branch `feat/graphql`.
- Create entry for new GraphQL plugin in application database. 
- Create empty plugin methods. The implementation for these methods and adding test cases will be taken up as a separate PR. 
- TBD (as separate PR - all these things will be done before final merge to the release branch):
- add implementation for methods
- add Test cases
- clean up POM file
- any other TODO mentioned in any of the comments. 
Fixes #11616 
- Manual
> feat: create empty graphQL plugin

- app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonConfig.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/EnvManagerCEImpl.java
> fix: Fix startup failing if signup disabled is empty

- app/client/src/sagas/QueryPaneSagas.ts
- app/client/src/sagas/SaaSPaneSagas.ts
- app/client/src/utils/AnalyticsUtil.tsx
Added analytics event to track datasource dropdown usage in query editors
- Analytics
- Manual
// Code coverage diff between base branch:release and head branch: chore/datasource_switcher_analytics 
:green_circle: | app/client/src/sagas/QueryPaneSagas.ts | 23.08 **(0.42)** | 10 **(0)** | 18.18 **(0)** | 27.1 **(0.43)**
:green_circle: | app/client/src/sagas/SaaSPaneSagas.ts | 38.18 **(0.44)** | 25 **(0)** | 50 **(0)** | 46.51 **(0.17)**
> chore: Added analytics event to track datasource dropdown usage in query editors

- app/client/src/pages/Editor/RequestConfirmationModal.tsx
This PR fixes the flickering of the Modal confirmation when running an action via cmd+enter shortcut.
Fixes #11612 
// Code coverage diff between base branch:release and head branch: fix/modal-flickering-bug 
:red_circle: | total | 55.82 **(0)** | 37.16 **(-0.01)** | 35.2 **(0)** | 56.16 **(0)**
> fix: Fixes confirmation modal flickering bug

- app/client/src/components/ads/Dropdown.tsx
- app/client/src/pages/Editor/APIEditor/ApiAuthentication.tsx
- app/client/src/pages/Editor/APIEditor/Form.tsx
- app/client/src/sagas/DatasourcesSagas.ts
1.  Filter Empty headers on saving the API as a datasource
2. Fixed UI for Param tab in which top padding was removed for key value headers
3. Placeholder text is fixed as `Please select an option` from `Please select a option`
4. Save DS button is disabled if the url is empty in the Auth Tab of API. 
Fixes #11071 
1. Click on `Create an API` in Datasource Page
2. Go to Param Tab and observe UI
3. Go to Auth Tab and Click on `Save as Datasource` button when url is empty and observe
4. Without adding any headers try to save api as a datasource then observe no empty headers are created now
// Code coverage diff between base branch:release and head branch: fix/rest-api …
> fix: Rest API UI issues (Empty DS headers, UI for Param tab, Save DS button, Placeholder)

- app/client/src/widgets/TableWidget/component/TableFilterPane.tsx
- When the Table is placed at the top of the Canvas the Filterplane overflows / gets out of the canvas. It was fixed before but due to some changes the `CANVAS_WIDGET` collapses in deploy mode.
- We are now using `id = root` element itself as the `BoundaryParent` and also have a save offset of 70.
Fixes #7996
- Tested Manually
// Code coverage diff between base branch:release and head branch: fix/table-filter-pane-overflow 
:red_circle: | total | 55.82 **(0)** | 37.17 **(-0.01)** | 35.2 **(0)** | 56.16 **(0)**
:red_circle: | …
> fix: Added root element as the ParentBoundary for TableFilterPane.

- app/client/src/components/formControls/DropDownControl.tsx
- app/client/src/pages/Editor/DataSourceEditor/JSONtoForm.tsx
Updated the conditions for checking the value as undefined or null for updating the dropdown selection and validation for form submit button if any of the fields value is `false`.
Fixes #11710 
- Create an authenticated datasource and change the `Send Appsmith signature header` dropdown to `Yes` and then change it to `No`. Earlier the `Session Details Signature Key` input not used to go away but now it does go away and the validation of form works successfully.
// Code coverage diff between base branch:release and head branch: fix/dropdown-control  …
> fix: Updated conditions for dropdown control to take in false also as value

- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/InvisibleActionFields.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ApplicationJson.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java
Added a temporary fix for missing action attribute `userSetOnLoad` in exported JSON files. This fixes the issue with explicit on page load actions not being triggered for imported apps. This fix is not a clean implementation however, since we're adding business logic in a separate field that is not easy to track. We'll be handling a proper fix in #11701 which will require a version upgrade for exported files.
Fixes #11698 
- JUnit test
> fix: Adds user set on load prop from actions to exported JSON file

- app/client/src/ce/constants/messages.test.ts
- app/client/src/ce/constants/messages.ts
- app/client/src/components/ads/NotificationBanner.tsx
- app/client/src/index.css
- app/client/src/pages/Editor/gitSync/GitSyncModal.tsx
- app/client/src/pages/Editor/gitSync/QuickGitActions/BranchButton.tsx
- app/client/src/pages/Editor/gitSync/QuickGitActions/index.tsx
- app/client/src/pages/Editor/gitSync/Tabs/Deploy.tsx
- app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx
- app/client/src/pages/Editor/gitSync/components/BranchList.tsx
- app/client/src/pages/Editor/gitSync/components/DeployPreview.tsx
- app/client/src/pages/Editor/gitSync/components/DeployedKeyUI.tsx
- app/client/src/utils/helpers.tsx
Git Sync feature has some loose ends, visually speaking. This PR addresses a few of those concerns.
Fixes #11558 
Manually for visual changes, and yarn test:unit for unit tests.
Changes so far:
1. Faster tooltips for bottom bar quick actions
2. Branch popover has a backdrop like the modals do.
3. More than 9 changes are reported as it is
4. Recent commit shows "less than a minute" ago
5. BETA tag removed from popover
6. Faster tooltips for sync branch button in popover
7. Placeholder for commit message
8. Relevant placeholder for git remote input
9. Padding for content in modal is decreased
10. Notification banner is aligned with SSH key box
https://user-images.githubusercontent.com/1573771/157437661-0d00675f-91de-4400-aa35-d6a1475f07b2. …
> fix: polish git-sync feature

- app/client/src/components/ads/TextInput.tsx
- app/client/src/pages/Editor/gitSync/Tabs/Deploy.tsx
We were using a text area in the commit message box which was causing issues on Mac, Windows; on Chrome, Firefox. This PR removes that, and fixes the issue.
Fixes #11237 
Manually.
Before changes:
https://user-images.githubusercontent.com/1573771/155091047-3b0cf8e7-ac27-45cb-87e2-0d009dafc586.mov
After changes (Mac, Firefox):
https://user-images.githubusercontent.com/1573771/155115648-7cb35e00-c945-4495-a904-07851790258f.mov
// Code coverage diff between base branch:release and head branch: 11237-fix-commit-message-box 
:red_circle: | total | 55.89 **(0)** | …
> fix: limit commit message area expansion and text spillover

- app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/ClearMethod.java
- app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/GetValuesMethod.java
In Google sheet when fetching data the error message thrown is showing a wrong field name when Cell Range is not entered.
Resolved by changing the error messages.
Fixes #11220
Manual Testing Done
> fix: 11220 GSheet incorrect error message fixed

- app/client/src/entities/Action/index.ts
- app/client/src/pages/Editor/IntegrationEditor/NewApi.tsx
- app/client/src/sagas/PluginSagas.ts
- app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
- Note: Currently it is being merged to development branch feat/graphql.
- You can create GraphQL datasource
- You can update the datasource
- You can click and navigate to GraphQL API Editor : ( for now the Editor rendered is similar to the normal API Editor but eventually it will be changed in different PRs.)
Fixes #10545 #10547
Manual by creating a graphql datasource
> feat: Added a flow to create a GraphQL datasource 

- deploy/docker/entrypoint.sh
When starting the fat container with `APPSMITH_MONGODB_URI` variable set to a value that has query params, like `mongodb+srv://user:pass@appsmith.abcde.mongodb.net/testdb?retryWrites=true&w=majority`, then the fat container ignores it and goes ahead with using a local MongoDB server.
The problem is that we generated a `pre-define.env` file, that gets the following line (among many others like it):
```sh
APPSMITH_MONGODB_URI=mongodb+srv://user:pass@appsmith.abcde.mongodb.net/testdb?retryWrites=true&w=majority
```
This file is then sourced with `. pre-define.env`. When this runs, this file is evaluated like a shell script, and the shell's glob based file-name expansions take affect.
So for this line, the shell looks for a file that looks _like_ …
> fix: Fix special char handling in pre-define env

- app/client/src/ce/pages/AdminSettings/config/authentication/index.tsx
- app/client/src/ce/pages/AdminSettings/config/types.ts
- app/client/src/components/ads/TagInputComponent.tsx
- app/client/src/components/ads/TextInput.tsx
- app/client/src/pages/Settings/FormGroup/Common.tsx
> Add asterisk for mandatory fields to give users a better User experience on the Admin settings page.
Fixes #11824 
- Updating UX
- Tested UI for Admin settings page to show asterisk on all mandatory fields.
// Code coverage diff between base branch:release and head branch: chore/mandatory-fields 
:green_circle: | total | 55.88 **(0)** | 37.24 **(0.01)** | 35.22 **(0)** | 56.19 **(0)**
:red_circle: | app/client/src/components/ads/TagInputComponent.tsx | 12.7 **(-0.41)** | 3.77 **(-0.31)** | 0 **(0)** | 13.56 **(-0.48)**
:red_circle: | app/client/src/pages/Settings/FormGroup/Common.tsx | 100 **(0)** | 86.36 …
> chore: Add asterisk for mandatory fields

- app/client/cypress.json
Putting Fork_template in ignoreTestFiles until the issue #11842 is fixed to unblock CI.
// Code coverage diff between base branch:release and head branch: ignoreTemplatespec 
:green_circle: | total | 55.88 **(0)** | 37.24 **(0)** | 35.22 **(0)** | 56.2 **(0.01)**
> test: commenting Fork_Template until fixed to unblock CI

- deploy/docker/scripts/run-nginx.sh
When interpolating env variables in the index.html file, we are overwriting the index.html file with placehoders and are doing this everytime there is a change.
This means if an env variable is _added_, it's value will be interpolated. But if one is modified or removed, this doesn't affect anything, since the placeholder is lost and there is no way for us to affect this change.
This PR fixed the problem by keeping a copy of the original index.html on first-start, and using that to interpolate every time.
Fixes #11848
> fix: Fix removal of env variables not working in NGINX

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Onboarding/GuidedTour_spec.js
- app/client/src/pages/Editor/FirstTimeUserOnboarding/IntroductionModal.tsx
- app/client/src/sagas/InitSagas.ts
- app/client/src/sagas/OnboardingSagas.ts
This broke after https://github.com/appsmithorg/appsmith/pull/11084. The [onboarding flow](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/sagas/OnboardingSagas.ts#L75) was starting before the editor being reset, hence once the onboarding started it immediately gets terminated when the editor is being reset. 
The fix for this is to wait for editor being reset when we starting onboarding from the editor. Also we mark reset editor as success after all actions has been dispatched.
Fixes #11831 
Cypress test
// Code coverage diff between base branch:release and head branch: fix/onboarding-not-starting 
Status | File | % Stmts | % Branch | % Funcs | % …
> fix: onboarding not starting from intro modal

- app/client/src/components/propertyControls/IconSelectControl.tsx
Icon Selector's width was not recalculated when the property pane was resized.
This also fixes an issue in JSONForm Widget where it is unable to display Icon Selector if the property pane section is hidden initially.
Thanks, @ashit-rath for coming up with a good solution.
Fixes #11735 
Manually
// Code coverage diff between base branch:release and head branch: fix/icon-selector-width 
:red_circle: | total | 55.87 **(-0.01)** | 37.25 **(0.02)** | 35.23 **(-0.01)** | 56.2 **(-0.01)**
:green_circle: | app/client/src/components/propertyControls/IconSelectControl.tsx …
> fix: Icon Selector width on propety pane resize

- app/client/src/workers/evaluationUtils.ts
Valid errors in `list widget` children are captured in the list widget itself. These errors are captured in `listwidget.template` . The private widgets (List widget children) add redundant errors to the debugger, sometimes these errors are wrong (`currentItem not defined`) because these widgets do not have access to currentItem and currentIndex during evaluations. For example, when there is an error in `Button1` widget present in the list widget, 
Before 
Now
Fixes #8677 
Functions used have been unit tested
// Code coverage diff between base branch:release and head branch: fix/currentItem-not-defined  …
> fix: do not show errors for private widgets

- app/client/src/sagas/OnboardingSagas.ts
The onboarding test was failing sometimes as the organisation list wasn't fetched yet while try to create an app for onboarding.  So the fix is to wait for the organisation list to be fetched if it isn't fetched yet.
Has a test already
// Code coverage diff between base branch:release and head branch: fix/onboarding-test 
:red_circle: | total | 55.87 **(0)** | 37.23 **(0)** | 35.22 **(0)** | 56.18 **(-0.01)**
:red_circle: | app/client/src/sagas/OnboardingSagas.ts | 21.05 **(-0.57)** | 1.16 **(-0.03)** | 4.35 **(0)** | 23.88 **(-0.55)**
:red_circle: | …
> fix: wait for organisation list to be fetched before creating an application for welcome tour

- app/client/src/ce/pages/UserAuth/Login.tsx
- app/client/src/ce/pages/UserAuth/SignUp.tsx
> Fix for signup link is not visible on the login screen when signup is disabled for all users. It should work for invited users.
> If the user has disabled signup, then only invited users are allowed to signup. The user trying to signup on signup page is invited or not is decided by the backend and shows an error if not invited.
> If the user has disabled form login, then signup link on login screen is disabled. This is because users can signup using Google/Github even via Login screen Google/Github buttons.
Fixes #11919
- Tested by disabling signup for all users using the admin settings page.
> fix: Show signup link even if signup toggle is off

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Button_spec.js
- app/client/src/widgets/ButtonWidget/widget/index.tsx
- Button Icon Alignment resets to `Alignment.Left` after we select a new icon. Fix was simple the `IconName` property with an updatehook was missing - `dependencies: ["iconAlign"]`
Fixes #11808 
- Tested Manually on the Canvas.
// Code coverage diff between base branch:release and head branch: fix/button-icon-alignment 
:green_circle: | total | 55.88 **(0)** | 37.25 **(0.01)** | 35.22 **(0)** | 56.2 **(0.01)** …
> fix: Button Icon Alignment on Icon Change

- app/client/src/components/editorComponents/GlobalSearch/index.tsx
The top 5 results on omnibar documentation search are default docs fetched from github (raw githug api). Removing this since we are fetching this from algolia itself by adding a "isDefault" attribute to these docs.
- Manual
// Code coverage diff between base branch:release and head branch: chore/remove-def-docs 
:red_circle: | total | 55.86 **(-0.02)** | 37.23 **(-0.01)** | 35.18 **(-0.04)** | 56.17 **(-0.02)**
:red_circle: | app/client/src/components/editorComponents/GlobalSearch/githubHelper.ts | 23.53 **(-23.53)** | 0 **(-50)** | 0 **(-100)** | 23.08 …
> chore: removed api calls to fetch default docs from github

- app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Theme.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ThemeServiceCEImpl.java
- app/server/appsmith-server/src/main/resources/system-themes.json
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/ThemeServiceTest.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ApplicationForkingServiceTests.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java
- app/server/appsmith-server/src/test/resources/test_assets/ImportExportServiceTest/valid-application-with-custom-themes.json
Changes the name of the default theme by introducing a new theme property - display name. 
Fixes #11885
- JUnit test
- Manually
> feat: Added migration to change default theme name

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ApiPaneTests/API_all_sidebar_actions_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ExplorerTests/Entity_Explorer_Entity_Renaming_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ExplorerTests/Entity_Explorer_Widgets_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Pages/Hide_Page_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/ExplorerTests/Entity_Explorer_CopyQuery_RenameDatasource_spec.js
- app/client/cypress/support/commands.js
- app/client/src/pages/Editor/Explorer/Datasources.tsx
- app/client/src/pages/Editor/Explorer/Datasources/DatasourceEntity.tsx
- app/client/src/pages/Editor/Explorer/Entity/EntityProperties.tsx
- app/client/src/pages/Editor/Explorer/Entity/index.tsx
- app/client/src/pages/Editor/Explorer/EntityExplorer.test.tsx
- app/client/src/pages/Editor/Explorer/JSActions/JSActionContextMenu.tsx
- app/client/src/pages/Editor/Explorer/hooks.ts
- app/client/src/pages/Editor/Explorer/mockTestData.ts
Changes to show newly created datasource on the explorer. This will show up only if there are less 3 active datasource in the application.
Fixes #11031
- Manual
// Code coverage diff between base branch:release and head branch: fix/show-default-datasources-in-explorer 
:green_circle: | total | 55.63 **(0.07)** | 36.87 **(0.05)** | 34.95 **(0.09)** | 55.93 **(0.07)**
:green_circle: | app/client/src/ce/constants/messages.ts | 76.8 **(0.05)** | 100 **(0)** | 31.12 **(0.14)** | 81.43 **(0)**
:green_circle: | app/client/src/pages/Editor/Explorer/Datasources.tsx | …
> fix: Show newly created datasources on the entity explorer

- app/client/src/api/TemplatesApi.ts
- app/client/src/sagas/TemplatesSagas.ts
The response meta was added as mentioned in https://github.com/appsmithorg/appsmith/issues/11661. So the response structure changed which needs an update on the frontend.
Previous response structure
```
{
applicationId: ...
...
}
```
After the response meta addition from the backend
```
{
responseMeta: {
...
},
data: {
applicationId: ...
....
}
}
```
The frontend change is to conform to this spec.
Manually
// Code coverage diff between base branch:release and head branch: fix/reposnse-parsing 
:green_circle: | total | 55.63 **(0)** | 36.88 **(0.01)** | 34.95 …
> chore: update import template response parsing

- app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/JsonSchemaMigration.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/CreateDBTablePageSolutionCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java
- app/server/appsmith-server/src/test/resources/test_assets/ImportExportServiceTest/file-with-v1.json
> When we run the schema updates we specify the JSON migration to keep the change backward compatible for already exported files. This check was missing for the template which we use for CRUD page generation. This PR introduces the migration for stored JSON file used for CRUD page.  
Fixes https://github.com/appsmithorg/appsmith/issues/11867
> Manual test
> fix: Handle JSON schema migration for CRUD page generation JSON template

- deploy/docker/templates/supervisord/redis.conf
- Redirect default Redis log to supervisor child process log.
[Redis and NGINX logs aren't collected in the logs folder with fat container](https://github.com/appsmithorg/appsmith/issues/11787)
- Build new image and check the log at `stacks/logs/redis/redis.log`
> fix: Redirect Redis log to supervisord log

- app/client/src/pages/Editor/DataSourceEditor/DBForm.tsx
The extra Host and port Input boxes displayed when the user click to edit a Datasource is removed
Fixes #9664
Manually
// Code coverage diff between base branch:release and head branch: fix/extra-key-value-datasource 
:red_circle: | total | 55.65 **(0)** | 36.9 **(-0.01)** | 34.96 **(0)** | 55.96 **(0)**
:red_circle: | app/client/src/pages/Editor/DataSourceEditor/DBForm.tsx | 50.79 **(-1.67)** | 18.18 **(-1.17)** | 9.09 **(0)** | 55.36 **(-2.05)**
:red_circle: | app/client/src/selectors/commentsSelectors.ts | 83.61 **(-1.64)** | 61.76 **(-2.95)** | 73.33 **(0)** …
> fix: remove extra key value pair for DataSource

- app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
Staging environment issue. The `formData` is coming up as `null` in some places which is causing an NPE.
Stack trace:
```
Caused by: java.lang.NullPointerException: null
at com.appsmith.server.migrations.DatabaseChangelog2.mapMongoToNewFormData(DatabaseChangelog2.java:422)
at com.appsmith.server.migrations.DatabaseChangelog2.migrateMongoActionsFormData(DatabaseChangelog2.java:520)
at com.appsmith.server.migrations.DatabaseChangelog2.updateActionFormDataPath(DatabaseChangelog2.java:146)
```
> fix: Fix NPE in form-data migration

- deploy/docker/entrypoint.sh
- deploy/docker/utils/bin/check_replica_set.js
When running the fat container, with an external MongoDB, where the user only has the following permission:
```js
{
"role" : "readWrite",
"db" : "appsmith"
}
```
The container fails to start. Although this permission is sufficient to work with `changeStream`s, we get the following error instead:
```
Checking Replica Set of external MongoDB
********************************************************************
*          MongoDB Replica Set is not enabled                      *
********************************************************************
```
This PR fixes the problem by checking for `changeStream` only in the DB that we have access to, and only on a specific collection, the `user` collection. This way, even if the user doesn't have permissions on the whole database, we can still work …
> fix: Fix replicaset checking with limited permissions

- app/client/src/components/propertyControls/StyledControls.tsx
- app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx
The reset button made keyboard accessible by removing unwanted tab indexes and setting focus styling.
Manual
> feat: Makes the reset button keyboard accessible

- deploy/docker/entrypoint.sh
Currently, to check if Redis URI is local or not, we only check for `127.0.0.1` and not for `localhost`, and we also check for the port to be 6379, which doesn't actually have to be.
This change is actually copied from line 71, where we perform a similar check for MongoDB URI.
> fix: Check Redis URL for `localhost` as well

- app/client/cypress/fixtures/datasources.json
- app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datasources/AuthenticatedApiDatasource_spec.js
- app/client/cypress/locators/DatasourcesEditor.json
- app/client/cypress/support/commands.js
- app/client/src/pages/Editor/DataSourceEditor/DBForm.tsx
- Upon updating an authenticated API data source it routes to a blank page
Fixes #12045
Manually
// Code coverage diff between base branch:release and head branch: fix/blank-screen-in-datasource 
:green_circle: | total | 55.59 **(0)** | 36.79 **(0.01)** | 34.91 **(0)** | 55.9 **(0)**
:red_circle: | app/client/src/pages/Editor/DataSourceEditor/DBForm.tsx | 49.23 **(-1.56)** | 17.14 **(-1.04)** | 9.09 **(0)** | 55.36 **(0)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 …
> fix: blank screen in datasource view mode

- deploy/docker/scripts/init_ssl_cert.sh
- deploy/docker/scripts/run-nginx.sh
When migrating from slim-containers to fat-containers, if SSL is enabled, then the resulting fat-container setup fails to start NGINX with the following error:
```
/opt/appsmith/run-nginx.sh: line 26: /appsmith-stacks/data/certificate/conf/options-ssl-nginx.conf: No such file or directory
```
To solve this, we are saving the SSL configurations in the appropriate places irrespective of whether we are using SSL or not. If SSL is enabled, they will be used, otherwise, they lie dormant.
> fix: Work with copied cert files after fat migration

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Switchgroup_spec.js
- app/client/src/widgets/SwitchGroupWidget/component/index.tsx
- When selectedValues is undefined, the app is crashed
- Make selected prop for the component to return empty array if its value is falsy
Fixes #12078 
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: fix/12078-switchgroup-selected-undefined 
:red_circle: | app/client/src/widgets/SwitchGroupWidget/component/index.tsx | 26.67 **(0)** | 11.76 **(-0.74)** | 0 **(0)** | 36.36 **(0)**</details>
> fix: Switch group widget is crashed when selectedValues is undefined

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Button_tooltip_spec.js
- app/client/src/widgets/ButtonWidget/component/index.tsx
> What should be done:
> What has been done:
- Remove disable popover prop
Fixes #7554 
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: fix/7554-disabled-button-enable-tooltip 
:red_circle: | total | 55.59 **(0)** | 36.78 **(-0.01)** | 34.91 **(0)** | 55.9 **(-0.01)**
> fix: Even disabled button tooltip should show

- deploy/docker/utils/bin/index.js
- deploy/docker/utils/bin/utils.js
- deploy/docker/utils/package-lock.json
- deploy/docker/utils/package.json
Upgrading the boxen dependency because a transitive dependency ansi-regex needs to be upgraded. If the boxen dependency is not being used, we can remove it from the dependency list as well.
> chore: Upgrading boxen dependency

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/MultiSelect_spec.js
- app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
Display the right label for multi-select default values
Fixes #12020
- Cypress Test
> fix: multiselect default label issue

- deploy/docker/scripts/run-nginx.sh
The nginx run script is missing a `mkdir` command which is causing it to not start.
> fix: Fix fat container not starting NGINX

- app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/FirestorePlugin.java
- Rename `smartBsonSubstitution` to `smartJsonSubstitution` for Firestore plugin variable, since `Bson` word would be misleading. 
- Addresses review comment on https://github.com/appsmithorg/appsmith/pull/10572 
Fixes #7110 
- internal: variable rename
> chore: rename variable

- deploy/ansible/README.MD
Typo fix: `--extra-var` to `--extra-vars`
> docs: Fixing typo in Ansible playbook. Modifying --extra-var to --extra-vars

- app/client/src/pages/Editor/RequestConfirmationModal.tsx
This PR fixes the quick flashing of the modals with already accepted action confirmations when a new run action confirmation has been made by the user
(Notice the quick flashing after confirmation)
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/7f5c93f919b149ab859a11e2233651b6-00001.gif)](https://www.loom.com/share/7f5c93f919b149ab859a11e2233651b6)
Fixes #12142 
// Code coverage diff between base branch:release and head branch: fix/flickering-confirmation-modal 
:red_circle: | app/client/src/utils/WorkerUtil.ts | 88.98 **(-0.78)** | 68.63 **(-3.92)** | …
> fix: Fix flickering confirmation modal

- app/client/src/pages/common/AppHeader.tsx
> App Editor Header was being seen on some of the Admin settings pages. Fixed it in this PR by adding a separate route for the Admin settings page in the App Header component. 
Fixes #12261 
- Tested all pages of admin settings to see if it all has the same app header -> page header
// Code coverage diff between base branch:release and head branch: hotfix/header-admin-settings 
:red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 …
> fix: Added routing for admin settings page in App Header

- app/client/src/widgets/IframeWidget/component/index.tsx
- app/client/src/widgets/IframeWidget/widget/index.tsx
This PR moves to comparing the actual iframe contentwindow object with the postmessage source to invoke the onMessageReceived callback. This allows multiple iframes with same origin to keep their messages separate, as well as allows srcDocs to have postmessage in their code as well.
Fixes #11779 
Please note that even though #11779 only describes the srcDoc use case, it seems from the code that having multiple iframes with same origin will also be buggy with the existing implementation.
Brought up locally connecting to appsmith staging server, and tested the examples given in #11779 as well as the case where we have multiple iframes.
> fix: Match iframe by object not origin.

- contributions/docs/InternalFunctions.md
Removing the description box from the function doc template for contribution. The description box adds the introduction in the title description that has a character limit in Gitbook.
> fix: Updating contribution guidelines for functions

- contributions/docs/Widgets.md
Removing the description box from the widget template for contribution. The description box adds the introduction in the title description  that has a character limit in Gitbook
> fix: Updating contribution guide for widgets

- app/client/src/pages/Editor/WidgetsEditor/CanvasContainer.tsx
When an app has multiple pages and multiple widgets on the canvas then the canvas only partially loads when switching pages and only half of the loading icon is visible.
Changes container height to 100vh instead of 100%
Fixes #12271 
- Bugfix
// Code coverage diff between base branch:release and head branch: fix/canvas-cut-issue 
:green_circle: | total | 55.69 **(0.01)** | 37.08 **(0)** | 35.25 **(0)** | 55.95 **(0.01)**
> fix: Canvas gets trimmed off when loading applications

- app/client/src/components/editorComponents/Debugger/DebuggerLogs.tsx
- app/client/src/components/editorComponents/Debugger/Errors.tsx
This PR resolves alignment issues on the error and log tabs in Response views.
Fixes #12314
- [] I have made corresponding changes to the documentation
// Code coverage diff between base branch:release and head branch: fix/fix-response-tab-allignment 
:red_circle: | total | 55.68 **(-0.01)** | 37.08 **(0)** | 35.25 **(0)** | 55.94 **(-0.01)**
> fix: Fix allignment issues on api response tabs

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/DatePicker_2_Default_spec.js
- app/client/src/widgets/DatePickerWidget2/component/index.tsx
>  In DatePicker Widget when DefaultDate value is moment Object then a date is not visible without refresh, To fix this issue update internal selected date condition
Fixes #11409 
// Code coverage diff between base branch:release and head branch: fix/datepicker-state 
:red_circle: | total | 55.68 **(-0.01)** | 37.08 **(0)** | 35.25 **(0)** | 55.94 **(-0.01)**
:red_circle: | …
> fix: updated internal selectedDate condition

- app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx
- app/client/src/sagas/PostEvaluationSagas.ts
- app/client/src/utils/DynamicBindingUtils.test.ts
- app/client/src/utils/DynamicBindingUtils.ts
- app/client/src/workers/DataTreeEvaluator.ts
- app/client/src/workers/evaluationUtils.ts
Cause of issue
The `widgetProperties` object in the property control has its evaluated values in a populated structure.  Hence, the path for retrieving values needs to change accordingly.
Populated Structure
Unpopulated Structure
Fixes #11913 
Jest
// Code coverage diff between base branch:release and head branch: fix/evaluated-value-is-undefined-for-nested-property-paths 
:green_circle: | total | 55.69 **(0)** | 37.09 **(0.01)** | 35.25 **(0)** | 55.95 **(0.01)**
:green_circle: | app/client/src/utils/DynamicBindingUtils.ts | 83.98 **(0.09)** | 70.69 **(0.15)** …
> fix: Support evaluated value in nested property paths

- app/server/appsmith-server/src/main/java/com/appsmith/server/constants/Url.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/UsagePulseController.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/UsagePulseControllerCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/domains/UsagePulse.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomUsagePulseRepository.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomUsagePulseRepositoryImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/UsagePulseRepository.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomUsagePulseRepositoryCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomUsagePulseRepositoryCEImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/UsagePulseRepositoryCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/UsagePulseService.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/UsagePulseServiceImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UsagePulseServiceCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UsagePulseServiceCEImpl.java
The usage pulse API at `/usage-pulse` only accepts `POST` requests, for only creating records. No payload body is expected either. The object saved contains the currently logged-in user, and the timestamp.
> feat: Add UsagePulse API, create-only

- Dockerfile
This PR adds an `apt-get upgrade --yes` command in building the Docker image, so that all packages are upgraded to their latest versions.
> chore: Run apt upgrade in appsmith image

- app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
This PR ensures the Save and Authorize button only shows when user has chosen the OAuth2 authentication type for rest api datasource forms.
Fixes #12437
// Code coverage diff between base branch:release and head branch: fix/remove-save-and-authorize-button 
:red_circle: | app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx | 23.48 **(0)** | 12.2 **(-0.22)** | 2.44 **(0)** | 24.54 **(0)**</details>
> fix: Fix issue with oauth2 save and authorize button

- app/client/src/ce/pages/UserAuth/SignUp.tsx
> Redirection from signup to login page doesn't include query params. This redirection happens when form login is disabled. This has been fixed in this PR.
Fixes #11932 
> Checked if the redirection passes on the query parameters from signup page to login page.
// Code coverage diff between base branch:release and head branch: hotfix/signup-redirection 
:red_circle: | app/client/src/utils/WorkerUtil.ts | 88.98 **(-0.78)** | 70.59 **(0)** | 100 **(0)** | 92.38 **(-0.95)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | …
> fix: sending query params on redirection from signup to login page

- app/client/cypress/fixtures/listwidgetdsl.json
- app/client/src/widgets/ListWidget/widget/derived.js
hotfix: #12438 (cherry picked from commit [50efc6](https://github.com/appsmithorg/appsmith/commit/50efc68fd36c5b9f13292568286bee430afcfeff))
Manual
// Code coverage diff between base branch:master and head branch: hotfix/12438-list-pagination 
:green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0)**</details>
> fix: old list widgets incorrect page size (#12443)

- app/client/src/pages/Editor/PropertyPane/PropertyHelpLabel.tsx
Making the property title not focusable via keyboard improves the keyboard navigation experience.
Fixes #12412 
- manually
// Code coverage diff between base branch:release and head branch: feat/make-property-title-not-focusible 
:red_circle: | total | 55.72 **(0)** | 37.15 **(-0.01)** | 35.44 **(0)** | 55.98 **(0)**
> feat: Make property title not focusable with keyboard

- app/client/src/components/ads/ListSegmentHeader.test.tsx
- app/client/src/components/ads/ListSegmentHeader.tsx
The component ListSegmentHeader contains a styled horizontal rule, git branch feature doesn't require that rule. This PR puts horizontal rule behind a flag.
Jest tests that are contained within the PR.
// Code coverage diff between base branch:release and head branch: feat-update-ListSegmentHeader 
:green_circle: | total | 56.19 **(0.01)** | 37.68 **(-0.01)** | 35.69 **(0.03)** | 56.43 **(0.01)**
:green_circle: | app/client/src/components/ads/ListSegmentHeader.tsx | 100 **(36.36)** | 100 **(0)** | 100 …
> feat: update list segment header

- app/client/src/ce/constants/messages.test.ts
- app/client/src/ce/constants/messages.ts
- app/client/src/sagas/GitSyncSagas.ts
We are not showing a few errors from git status API.
Fixes #12274 
// Code coverage diff between base branch:release and head branch: 12274-fix-show-error-notification-on-ssh-regeneration 
:red_circle: | total | 56.18 **(0)** | 37.67 **(-0.02)** | 35.67 **(0.01)** | 56.42 **(-0.01)**
:green_circle: | app/client/src/ce/constants/messages.ts | 77.13 **(0.06)** | 100 **(0)** | 32.2 **(0.19)** | 82.02 **(0.15)**
:red_circle: | app/client/src/sagas/GitSyncSagas.ts | 9.15 **(-1.01)** | 0.24 **(-0.02)** | 4.35 **(0)** | 11.46 **(-1.29)**
:red_circle: | …
> fix: show errors from git status

- app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java
- app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/utils/DatasourceUtils.java
- app/server/appsmith-plugins/amazons3Plugin/src/test/java/com/external/plugins/AmazonS3PluginTest.java
- Currently S3 plugin datasource requires the `region` field to be non-empty for it to work (when configured with `other` as the datasource type from dropdown). However, this field is not required for many S3 offerings. Hence, making it non-mandatory.
Fixes #11109
- JUnit TC
- Manual
> fix: make region a non-mandatory field

- app/client/src/api/ApiUtils.ts
- app/client/src/pages/tests/mockData.ts
- app/client/src/pages/tests/slug.test.tsx
- app/client/src/reducers/uiReducers/applicationsReducer.tsx
- app/client/src/sagas/InitSagas.ts
- app/client/src/store.ts
Fixes page launch 404 when launching an application(not git synced) right after visiting a git synced application on the same tab.
Should have been introduced because of the client side routing changes done on the /applications pages
Fixes #12558 
- Manual
// Code coverage diff between base branch:release and head branch: fix/page-launch-error-from-dashboard 
:green_circle: | total | 56.28 **(0.02)** | 37.74 **(0.01)** | 35.88 **(0.04)** | 56.52 **(0.03)**
:green_circle: | app/client/src/store.ts | 90.38 **(4.96)** | 58.33 **(0)** | 80 **(0)** | 89.13 **(5.8)** …
> fix: page launch error from dashboard

- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java
> When we do import-export the imported application does not have the same page sequence as to exported application. This change maintains the page order while exporting the application so that the order is maintained when we import the app. 
Fixes #8508 
- Locally
- JUnit Tests(on the way)
> fix: While importing the application page sequence does not match with the source application

- app/client/src/pages/tests/slug.test.tsx
- app/client/src/utils/AppsmithUtils.tsx
fixes pages tab navigation in preview mode for git apps.
- Manual
// Code coverage diff between base branch:release and head branch: fix/tab-navigation-preview-mode-git-apps 
:green_circle: | total | 56.29 **(0)** | 37.78 **(0.04)** | 35.92 **(0.04)** | 56.53 **(0.01)**
:green_circle: | app/client/src/selectors/editorSelectors.tsx | 75.43 **(1.29)** | 61.74 **(0)** | 60 **(3.75)** | 73.8 **(1.07)** …
> fix: Pages tab navigation in preview mode for git apps

- app/client/src/workers/DataTreeEvaluator.ts
There was an unexpected error during evaluation because of a missing config for APIs. Added sanity check to validate prroperty path only if it has config
Fixes #12454 
// Code coverage diff between base branch:release and head branch: promises-prod-issue 
:red_circle: | total | 55.72 **(0)** | 37.14 **(-0.02)** | 35.44 **(0)** | 55.98 **(0)**
:red_circle: | app/client/src/workers/DataTreeEvaluator.ts | 75.81 **(-0.12)** | …
> fix: added sanity check to avoid unexpected eval error

- app/client/src/pages/Editor/APIEditor/ApiRightPane.tsx
Added a null check for `datasourceConfiguration` which was referring to `url` key and application was breaking if `datasourceConfiguration` becomes undefined.
Fixes #12513 
Manually tested
// Code coverage diff between base branch:release and head branch: fix/12513-datasourceConfig-null-check 
:red_circle: | total | 56.24 **(-0.01)** | 37.68 **(-0.01)** | 35.91 **(0)** | 56.47 **(0)**
:red_circle: | app/client/src/pages/Editor/APIEditor/ApiRightPane.tsx | 43.28 **(0)** | 40.74 **(-3.26)** | 0 **(0)** | 46.67 **(0)**
:red_circle: | …
> fix: added a null check for datasourceConfiguration to refer url key

- app/client/src/widgets/TableWidget/component/AutoToolTipComponent.tsx
- app/client/src/widgets/TableWidget/component/TableStyledWrappers.tsx
Fix URL column type on table widget by adding padding to the cell
Fixes #12130
- Visual
// Code coverage diff between base branch:release and head branch: fix/Align-Table-widget-URL-Column-type 
:red_circle: | total | 56.24 **(0)** | 37.67 **(-0.01)** | 35.92 **(0)** | 56.47 **(0)**
> fix: align Table widget URL Column type

- app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/OAuth2AuthorizationCode.java
- app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/OAuth2ClientCredentials.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java
OAuth2 [spec](https://www.rfc-editor.org/rfc/rfc6749#section-4.1.3) requires token requests to be form url encoded type. This change converts the content type for these requests to match.
Fixes #11952 
- Tested with monday.com
- Regression tested with Auth0
- Test instance up on test.appsmith.com, being tested for NetSuite
> fix: Using form url encoded content type for token requests

- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PageLoadActionsUtilCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutActionServiceTest.java
If Api1 and Api2 are marked to be run on page load manually, and only Api1 is referred to in a widget, Api1 gets added twice in the scheduling order.
This has been fixed by only adding the difference between total user set actions and already mapped user set actions to the scheduling order.
Fixes #12596
- JUnit test case
> fix: Only add missing user set actions to scheduling order

- app/server/appsmith-server/src/main/resources/system-themes.json
Recently we had to make some changes in the config of default themes and those changes are required on the release server.
> chore: Update theming default themes configs

- app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx
- app/client/src/transformers/RestAPIDatasourceFormTransformer.ts
This PR fixes the way the app crashes on the API and Datasource editors due to absent datasourceConfigurations.
Fixes #12556 
// Code coverage diff between base branch:release and head branch: fix/fixes-creating-api-bug 
:red_circle: | total | 56.3 **(0)** | 37.74 **(-0.01)** | 35.92 **(0)** | 56.52 **(0)**
:red_circle: | app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx | 28.89 **(0)** | 2.84 **(-0.08)** | 3.23 **(0)** | 30.72 **(0)**
:green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(1.64)** | 64.71 …
> fix: Fix app crash on navigation to API and Datasource Editor

- app/client/cypress/support/Pages/JSEditor.ts
Updating JSOnPageLoad pop-up text message validation to accommodate the new 'Beta' tag introduced due to #12657 
Fixes JSOnLoadActions_Spec failure in CI runs
Cloud/Release
- [] I have made corresponding changes to the documentation
> test: Automation script update to fix JSOnPageLoad pop-up text message

- app/client/src/utils/WidgetFactory.tsx
- app/client/src/utils/WidgetLoadingStateUtils.test.ts
- app/client/src/utils/WidgetLoadingStateUtils.ts
- app/client/src/utils/WidgetRegisterHelpers.tsx
- app/client/src/widgets/BaseWidget.tsx
- app/client/src/widgets/TableWidget/index.ts
- app/client/src/widgets/TableWidget/widget/index.tsx
- app/client/src/workers/DataTreeEvaluator.ts
Reverts appsmithorg/appsmith#11875
Reason: critical issue #12528 (cyclic dependency)
brings back linting issue #11943
// Code coverage diff between base branch:release and head branch: revert-11875-fix/onclick-linting-issue 
:red_circle: | total | 56.29 **(-0.01)** | 37.72 **(-0.02)** | 35.93 **(0.01)** | 56.52 **(0)**
:green_circle: | app/client/src/utils/WidgetFactory.tsx | 74.47 **(-0.02)** | 72.22 **(-1.46)** | 64.71 **(3.6)** | 74.47 **(-0.02)**
:red_circle: | app/client/src/utils/WidgetLoadingStateUtils.ts | 96.67 **(-0.16)** | 90 **(-2)** | 100 **(0)** | 97.96 **(-0.12)**
:red_circle: | …
> fix: "Revert: trigger fields linting issue"

- app/client/src/pages/Editor/gitSync/components/BranchList.tsx
This PR removes list segment header rule from git branch list.
Fixes #12612 
Manually.
// Code coverage diff between base branch:release and head branch: feat-remove-segment-header-rule-from-git-branch-list 
:red_circle: | total | 56.27 **(0)** | 37.72 **(-0.01)** | 35.92 **(0)** | 56.5 **(0)**
> feat: remove horizontal rule from git branch list

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GitSync/Connection_spec.js
- app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx
- app/client/src/pages/Editor/gitSync/utils.test.ts
- app/client/src/pages/Editor/gitSync/utils.ts
As of today we accept almost anything in git connect modal for remote URL. The URL should be ssh/git one. This PR fixes it. 
New RE is: `/^((git|ssh)|(git@[\w\.]+))(:(\/\/)?)([\w\.@\:\/\-~]+)(\.git)$/`
Fixes #11996 
Manually.
// Code coverage diff between base branch:release and head branch: 11996-fix-git-remote-url-validation 
:green_circle: | total | 56.25 **(0.01)** | 37.69 **(0.02)** | 35.93 **(0.02)** | 56.48 **(0.01)**
:green_circle: | app/client/src/pages/Editor/gitSync/utils.ts | 100 **(50)** | 100 **(100)** | 100 **(100)** | 100 **(66.67)**</details>
> fix: introduce new regexp for remote url validation

- deploy/docker/scripts/run-nginx.sh
The `run-nginx.sh` script fails to run when `APPSMITH_CUSTOM_DOMAIN` environment variable is not set. This PR fixes that problem.
> fix: Fix server not starting when custom domain not set

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Applications/ApplicationURL_spec.js
- app/client/src/AppRouter.tsx
- app/client/src/constants/routes.ts
- app/client/src/pages/Editor/BottomBar/ManualUpgrades.tsx
- app/client/src/pages/common/PageNotFound.tsx
- app/client/src/utils/AnalyticsUtil.tsx
- Added analytics for manual upgrade and client side 404
- Added redirect logic to route /:applicationSlug/:pageSlug-:pageId -> /app/:applicationSlug/:pageSlug-:pageId
- Manual
- Cypress
// Code coverage diff between base branch:release and head branch: analytics-manual-upgrade 
:green_circle: | app/client/src/constants/routes.ts | 96.1 **(0.1)** | 100 **(0)** | 66.67 **(0)** | 95.95 **(0.12)**
:red_circle: | app/client/src/pages/Editor/BottomBar/ManualUpgrades.tsx | 90.32 **(-1.35)** | 85 **(0)** | 76.92 **(0)** | 88.68 **(-1.52)**</details>
> chore: Added analytics for manual upgrade and adds redirection

- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/Condition.java
- app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/MethodConfig.java
- app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/MethodConfigTest.java
- Earlier GSheet plugin had check based on null value that would ignore empty where conditions. However, due to a recent change the client has now started to return empty string instead of null value against empty input fields of where clause. This PR updates the previous check to now rely on the following condition to ignore where condition: (1) all column names are empty (2) all operators are empty. In case both the conditons are not met simultaneously then an error is shown to the user if the configuration is found to have missing column name or operator.
Fixes #12701 
- JUnit TC
- Manual
> fix: update check for GSheet where condition

- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java
> When we do import-export the imported application does not have the same page sequence as to exported application.
Fixes #8508
- Locally
- JUnit Tests
> fix: Maintain page order during file import

- app/client/package.json
- app/client/yarn.lock
Fix the iframe injection in development mode.  
Fixes #12722 
chore
Manually 
// Code coverage diff between base branch:release and head branch: fix/react-overlay 
:red_circle: | total | 56.33 **(-0.01)** | 37.73 **(-0.01)** | 35.94 **(0)** | 56.56 **(0)**
> chore: react overlay issue

- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java
> When the user tries to import an app from an empty git repo then we are just throwing the Internal Server error. But ideally we should let the user know that the failure is due to empty repo. 
Fixes #12749 
- Locally
- JUnit tests
> fix: Git import error message for empty repo

- app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/OAuth2AuthorizationCode.java
- app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/OAuth2ClientCredentials.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java
Fixes #11952
The conversion logic needs to handle both numeric and string return types since different providers seem to follow different norms.
We do not have the ability to test for this fix right now. However, monday.com and Dropbox are two providers that have been identified with having this difference and tested for. We should add these providers in our manual test suite.
> fix: Conversion logic for expires in field

- app/client/src/components/editorComponents/ApiResponseView.tsx
- app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
- app/client/src/pages/Editor/QueryEditor/index.tsx
- app/client/src/selectors/entitiesSelector.ts
This PR fixes google sheets datasources from not appearing in the datasource options dropdown. and it also addresses some misalignment issues in the response body tab.
Fixes #12762
// Code coverage diff between base branch:release and head branch: fix/saas-datasource-name-in-dropdown 
:green_circle: | total | 56.34 **(0)** | 37.75 **(0.01)** | 35.95 **(0)** | 56.57 **(0.01)**
:green_circle: | app/client/src/components/editorComponents/ApiResponseView.tsx | 49.52 **(0.48)** | 30.48 **(1.35)** | 0 **(0)** | 51 **(0.49)** …
> fix: Fix google sheets datasource options

- app/client/src/components/ads/Dropdown.tsx
This PR fixes the way the app crashes when the arrow down key is used in the where clause dropdown component.
Fixes #12706 
// Code coverage diff between base branch:release and head branch: fix/arrow-down-where-issue 
:green_circle: | total | 56.34 **(0)** | 37.75 **(0.01)** | 35.95 **(0)** | 56.56 **(0)**
:green_circle: | app/client/src/components/ads/Dropdown.tsx | 84.23 **(0)** | 62.91 **(0.15)** | 73.61 **(0)** | 83.26 **(0)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 …
> fix: Fix app crash on arrow down in where clause

- .github/workflows/github-release.yml
The Github release workflow takes a lot of time for client build step. Moving to Buildjet to speed this CI workflow.
> chore: Migrating Github release workflow to use Buildjet for client build

- app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
- app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/utils/DatasourceUtils.java
- app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java
- app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/utils/DatasourceUtilsTest.java
The mongo plugin retries creating connections passively in the pool all the time right now because the pool is initialized with a setting to always have at least one connection open. This fix forces all datasources to allow 0 connections as well. This will allow incorrect datasource configurations to not keep attempting the connection. 
Also contains refactoring since the logic for URIs was crowding the `MongoPluginExecutor` class.
Do we also need to be checking for the duration of time that each connection is held on to even when idle?
Fixes #4142
- Unit tests for parameter additions
- Manually tested for connection recreation attempts
> fix: Fixes Mongo connection pool minimum size to 0

- deploy/docker/scripts/run-nginx.sh
The redundant `init_ssl_cert` function call was preventing the clean up of ngnix process, if the certificate provisioning had failed, and preventing falling back to using `nginx-app-http.conf`.
Fixes # [12814](https://github.com/appsmithorg/appsmith/issues/12814)
Tested manually on a sandbox instance, by setting an invalid APPSMITH_CUSTOM_DOMAIN
> fix: Removed redundant init_ssl_cert function call

- app/client/src/components/ads/Dropdown.tsx
This PR includes the changes for overriding the margin and padding for the custom render option in Appsmith Design System dropdown component.
Fixes #12025
- Checked the dropdown which implements custom render. for eg. Generate page select datasource dropdown 
// Code coverage diff between base branch:release and head branch: fix/12025-ads-select-component-selected-flag-style-fix 
:red_circle: | app/client/src/components/ads/Dropdown.tsx | 84.23 **(0)** | 62.83 **(-0.08)** | 73.61 **(0)** | 83.26 **(0)**</details>
> fix: Overriding margin and padding for custom render in the dropdown component

- app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitUtils.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/GitUtilsTest.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java
> It would be a good idea to set a connection timeout, because in firewall environments, there's a good chance HTTPS is blocked off without refusing the connection, which might still cause a timeout. We are currently using blocking IO call for checking the repo status which is highly undesirable in webflux environment. 
This PR fixes the above mentioned issues. 
Fixes #12721 #12407 
- Locally
- JUnit tests
> fix: Connection timeout for git connect when the git repo is behind a firewall

- app/server/appsmith-server/src/main/java/com/appsmith/server/constants/FieldName.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/OrganizationServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/OrganizationServiceTest.java
From the general settings page, if you try to update the organization name, it can be left empty. 
[![Reported Issue](https://cdn.loom.com/sessions/thumbnails/8562f9ae102746fa9f94c1e3f3fef8e3-with-play.gif)](https://loom.com/embed/45f0b5c1570c4337b248fc3989306c57 "Issue video")
This PR fixes that on the backend and throws an invalid parameter exception.
Fixes #[12301](https://github.com/appsmithorg/appsmith/issues/12301)
- Tested on local app
[![Test Video](https://cdn.loom.com/sessions/thumbnails/8562f9ae102746fa9f94c1e3f3fef8e3-with-play.gif)](https://www.loom.com/embed/8562f9ae102746fa9f94c1e3f3fef8e3 "Test Video")
- Verified the added test case for this.
> fix: Organization name can be empty

- app.json
- Remove postdeploy script define in app.json which is used for Heroku one click deployment
> fix: Remove postdeploy script in app.json for heroku

- app/client/src/components/editorComponents/ApiResponseView.tsx
- app/client/src/pages/Editor/APIEditor/ApiRightPane.tsx
This PR handles:
1. JSON responses for content-types like application/ld+json which always return stringified json objects as a response (this is unlike content-types like application/json which return an array of objects).
2. A misalignment inconsistency in the ApiRightPane of the ApiEditor page.
Fixes #3911 and #12780
// Code coverage diff between base branch:release and head branch: feat/handle-stringified-json-response 
:red_circle: | total | 56.34 …
> feat: Handle stringified json response and fix alignment issue

- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java
> We should not delete the application resource for when the default branch is updated. We should only delete the git branch from file system. Note this applies only for the appsmith default branch which is used to connect all the resources across child applications. 
Fixes #12931 
- Postman
- JUnit
> fix: Handle logic to delete the application resource during git delete branch flow

- app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/constants/GitConstants.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitFileUtils.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/GitFileUtilsTest.java
> As a part of git-directory update we have introduced a bug where if the entity names includes the `-` we were not able to filter the entities in the individual page directory. This PR introduces a new name-seperator to avoid such issues. 
> Also in the merge operation we used to delete only the unpublishedPages which resulted in stale pages, where page object had the applicationId but the same application did not had the reference of pageId in `pages` and `publishedPages` array. As a fix we are now not committing the entities in git which has non-null `deletedAt` field inside the unpublished resource as we expect commit flow will be triggered only after the publish.   
Fixes #13023 #13064 
> JUnit testcase
> Manual testing
> fix: Fix issues in git flows when pages don't have reference in application object

- app/client/src/reducers/uiReducers/applicationsReducer.tsx
> When syncing git on branch list popup, default branch is updated from latest.
Fixes #12988 
> Please check it manually from linked issue.
// Code coverage diff between base branch:release and head branch: fix/12988-delete-origin-default-branch 
:red_circle: | total | 56.49 **(0)** | 37.98 **(-0.01)** | 36.27 **(0)** | 56.7 **(-0.01)**
:red_circle: | app/client/src/reducers/uiReducers/applicationsReducer.tsx | 15.24 **(-0.76)** | 20 **(-7.27)** | 11.76 **(-0.48)** | 13.86 **(-0.57)**
:red_circle: | app/client/src/selectors/commentsSelectors.ts | 83.61 …
> fix: 12988 - deleting original default branch

- app/server/appsmith-plugins/amazons3Plugin/src/main/resources/editor/list.json
Updated the condition to show the `expiry` key for the `list files` type of s3 query
Fixes #12981
Manually
> fix: Updated the condition to show expiry key

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/JSONFormWidget/JSONForm_FieldEvents_spec.js
- app/client/src/widgets/JSONFormWidget/fields/RadioGroupField.tsx
- app/client/src/widgets/RadioGroupWidget/component/index.tsx
Fixes #13022 
- Manual
- Cypress
// Code coverage diff between base branch:release and head branch: fix/13022-jsonform-radiogrp-event 
:red_circle: | total | 56.48 **(-0.01)** | 37.98 **(-0.01)** | 36.27 **(0)** | 56.7 **(-0.01)**
> fix: onOptionChange event not triggering in JSON Form radio group field

- app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java
- app/server/appsmith-plugins/postgresPlugin/src/test/java/com/external/plugins/PostgresPluginTest.java
In Postgres CURD page, the TimeStamp with TimeZone field caused error when updating.
Resolved that issue by adding "JDBC override parameter for postgress" as per the below recommendations.
[https://support.delphix.com/Continuous_Compliance_Engine_(formerly_Masking_Engine)/Resolving_Varchar_Cast_Errors_on_PostgreSQL_(KBA6993)](https://support.delphix.com/Continuous_Compliance_Engine_(formerly_Masking_Engine)/Resolving_Varchar_Cast_Errors_on_PostgreSQL_(KBA6993))
Findings :
Part 1:
The application can work without this fix in the following way
Example of working syntax for updating TimeStampTS without this fix is : 2022-04-11 05:30:00
This is saved as UTC format in the DB, when fetching necessary conversions are required based on the fetching location and displayed in the right field in the …
> fix: 11141-JDBC override parameter for resolving TZ Cast Errors

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Modal_spec.js
- app/client/src/pages/Editor/Explorer/Entity/index.tsx
- app/client/src/pages/Editor/Explorer/Files/index.tsx
- app/client/src/sagas/ModalSagas.ts
Brings active JSObject, API and queries in entity explorer into viewport. 
Fixes #11937 
Fixes #10740 
- Manual
- Cypress
// Code coverage diff between base branch:release and head branch: fix/11937-explorer-scroll-to-active-entity 
:red_circle: | total | 56.48 **(0)** | 37.96 **(-0.01)** | 36.27 **(0)** | 56.7 **(0)**
:green_circle: | app/client/src/pages/Editor/Explorer/Files/index.tsx | 76.19 **(-0.13)** | 27.78 **(-5.55)** | 50 **(10)** | 79.49 **(-1.07)**
:green_circle: | app/client/src/sagas/ModalSagas.ts | 36.61 **(0.34)** | 18.42 **(-1.02)** | 23.08 …
> fix: scroll to active entity in explorer on route change

- app/client/perf/src/ci/supabase.js
We were saving the values of the last run for all five runs of the perf test suite. This PR fixes it.
// Code coverage diff between base branch:release and head branch: fix/perf-infra-data-collection 
:green_circle: | total | 56.48 **(0.01)** | 37.94 **(0.01)** | 36.19 **(0)** | 56.7 **(0.01)**
> chore: Fix perf infra data collection

- app/client/src/components/propertyControls/FieldConfigurationControl.tsx
- app/client/src/widgets/JSONFormWidget/component/Field.tsx
- app/client/src/widgets/JSONFormWidget/component/Form.tsx
- app/client/src/widgets/JSONFormWidget/fields/ArrayField.tsx
- app/client/src/widgets/JSONFormWidget/fields/useRegisterFieldValidity.ts
- app/client/src/widgets/JSONFormWidget/fields/useUpdateInternalMetaState.ts
- app/client/src/widgets/JSONFormWidget/schemaParser.test.ts
- app/client/src/widgets/JSONFormWidget/schemaParser.ts
- app/client/src/widgets/JSONFormWidget/widget/propertyConfig/helper.test.ts
Using "klona/full" causes crashes and unexpected behavior
Fixes #13192 
// Code coverage diff between base branch:release and head branch: fix/13192-jsonform-klona 
:green_circle: | total | 56.47 **(0.01)** | 37.92 **(0)** | 36.19 **(0.02)** | 56.69 **(0.01)**
:green_circle: | app/client/src/components/editorComponents/Debugger/index.tsx | 76.6 **(0.51)** | 26.92 **(0)** | 87.5 **(1.79)** | 78.26 **(0.48)**
:green_circle: | app/client/src/pages/Editor/BottomBar/ManualUpgrades.tsx | 90.32 **(0.85)** | 85 **(1.67)** | 76.92 **(1.92)** | 88.68 **(-1.12)** …
> fix: Replace "klona/full" -> "klona" in JSONForm to avoid crash in dev environment

- app/client/cypress/support/ApiCommands.js
- app/client/src/components/editorComponents/ApiResponseView.tsx
This PR changes the response tab name from "Body" to "Response"
// Code coverage diff between base branch:release and head branch: fix/response-body-tab-name 
:green_circle: | total | 56.49 **(0)** | 37.99 **(0.01)** | 36.28 **(0)** | 56.71 **(0)**
:green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0.78)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0.95)**</details>
> fix: Change response tab name

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/JSONFormWidget/JSONForm_FormProperties_spec.js
- app/client/src/utils/autocomplete/EntityDefinitions.ts
- app/client/src/widgets/JSONFormWidget/component/Form.tsx
- app/client/src/widgets/JSONFormWidget/component/index.tsx
- app/client/src/widgets/JSONFormWidget/widget/index.tsx
Adds a form level property called `isValid` which can be used to check if the current form is valid (passes all validation) or not
Fixes #12771 
- Cypress
// Code coverage diff between base branch:release and head branch: feature/jsonform-invalid-property 
:red_circle: | total | 56.48 **(-0.01)** | 37.98 **(-0.01)** | 36.27 **(0)** | 56.7 **(-0.01)**
:red_circle: | …
> feat: JSONFrom add isValid form level property to represent overall form validity

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Applications/ExportApplication_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OrganisationTests/OrgImportApplication_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Params/PassingParams_Spec.ts
This PR fixes the Export spec & OrgImport failure by adding wait after the dsl is loaded & then navigate to the application
Also fixes PassingParams spec failure by adding wait before validating table!
Fixes ExportSpec & OrgImporSpec & PassingParams failure in CI runs
Fix for failure case (non-breaking change which adds functionality)
Release - CI
// Code coverage diff between base branch:release and head branch: test/Exportflakyfix 
:green_circle: | total | 56.46 **(0)** | 37.94 **(0)** | 36.17 **(0)** | 56.69 **(0.01)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 …
> test: Automation script update to fix ExportSpec/PassingParams failure

- app/client/src/pages/Editor/gitSync/utils.test.ts
- app/client/src/pages/Editor/gitSync/utils.ts
Azure SSH url was not getting accepted by FE code while connecting an application to git.
Fixes #12891 
Unit tests
> fix: git remote SSH url for Azure | FE

- app/client/src/pages/Editor/PropertyPane/Generator.tsx
Resolve the react error in dev mode due to no key passed in the Boxed component.
> fix: no key warning

- Dockerfile
- Disable uid/gid bit when building docker image.
- Keep files ownership of user/group.
- Build the image and run app to make sure it's functional normally.
> fix: disable uid/gid bits for fat container

- app/client/cypress/fixtures/githubSource.json
- app/client/cypress/support/AdminSettingsCommands.js
- app/client/src/ce/constants/messages.ts
- app/client/src/pages/Settings/DisconnectService.tsx
- app/client/src/pages/Settings/SettingsForm.tsx
> Added check for disconnect button clicked once to avoid Internal server error on multiple clicks.
Fixes [#13235](https://github.com/appsmithorg/appsmith/issues/13235)
> Checked if multiple clicks on Disconnect SAML button doesn't lead to Internal server error.
// Code coverage diff between base branch:release and head branch: fix/disconnect-btn-check 
:red_circle: | total | 56.46 **(0)** | 37.94 **(0)** | 36.16 **(-0.01)** | 56.68 **(0)**
:red_circle: | app/client/src/ce/constants/messages.ts | 77.97 **(-0.03)** | 100 **(0)** | 34.85 **(-0.09)** | 82.19 …
> fix: add check for disconnect button clicked once

- app/client/src/components/editorComponents/ActionCreator/index.tsx
- Reset on `onSucess` and `onError` inside the action selector generates `() => ()` as opposed to `() => {}`.
Fixes #12663 
- Tested Manually on the Canvas.
// Code coverage diff between base branch:release and head branch: fix/onSuccess-reset 
:green_circle: | total | 56.34 **(0)** | 37.75 **(0.01)** | 35.96 **(0)** | 56.56 **(0)**
> fix: onSucess & onError action selector.

- app/client/src/sagas/ActionExecution/PluginActionSaga.ts
We add a fallback for the responseViewType in case the default responseType of the plugin is not included in the response dataTypes array.
Fixes #13310
// Code coverage diff between base branch:release and head branch: fix/response-display-format-fallback 
:red_circle: | total | 56.46 **(0)** | 37.92 **(-0.02)** | 36.16 **(-0.01)** | 56.68 **(0)**
:red_circle: | app/client/src/sagas/ActionExecution/PluginActionSaga.ts | 17.22 **(-0.11)** | 1.88 **(-0.23)** | 9.09 **(-0.43)** | 19.77 **(-0.15)**
:green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 …
> fix: Add fallback for responseType, in case it does not exist

- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeStringUtils.java
- app/server/appsmith-interfaces/src/test/java/com/appsmith/external/helpers/DataTypeStringUtilsTest.java
We were only allowing simple data types to be parsed as a table, but most datasources allow complex nested structures within a column as well. This fix allows anything that looks like a map to be represented as a table.
Fixes #13310 
- JUnit test cases
> fix: Parse nested structures as tables for action execution results

- deploy/helm/Setup-https.md
Specified ingress.class to nginx setting in helm chart https docs.
> While updating Appsmith with ssl using Helm, I came across an error due to ingress class of the ingress controller not matching ingress class in the ingress resource manifest(nginx), the proposed change solved the issue.
> ci: Adding ingress.class parameter to nginx setting in helm chart docs

- app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ApplicationJson.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java
- app/server/appsmith-server/src/test/resources/test_assets/ImportExportServiceTest/invalid-application-without-pageId-action-collection.json
- app/server/appsmith-server/src/test/resources/test_assets/ImportExportServiceTest/valid-application-with-custom-themes.json
- app/server/appsmith-server/src/test/resources/test_assets/ImportExportServiceTest/valid-application-with-page-added.json
- app/server/appsmith-server/src/test/resources/test_assets/ImportExportServiceTest/valid-application-with-page-removed.json
- app/server/appsmith-server/src/test/resources/test_assets/ImportExportServiceTest/valid-application-with-un-configured-datasource.json
- app/server/appsmith-server/src/test/resources/test_assets/ImportExportServiceTest/valid-application-without-action-collection.json
- app/server/appsmith-server/src/test/resources/test_assets/ImportExportServiceTest/valid-application-without-theme.json
- app/server/appsmith-server/src/test/resources/test_assets/ImportExportServiceTest/valid-application.json
> Page order sequence gets messed up when we do git import. The reason is because of the parallel execution of task by stream API, which is used to process page from the application json file. We don't have control over this. So we have decided to add the page order to the metadata of json file which is exported. This list is then referred while importing application into the org. 
Fixes #12944 
- Locally 
- Junit Tests
> fix: Page order sequence for git import

- app/client/src/components/editorComponents/ApiResponseView.tsx
- app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
Adds space to both sides of the response run button.
Fixes #13027
// Code coverage diff between base branch:release and head branch: fix/add-space-to-response-run-button 
:red_circle: | app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx | 34.23 **(-0.3)** | 25 **(-0.77)** | 0 **(0)** | 35.68 **(-0.3)**</details>
> fix: Add space to both sides of response run button

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GenerateCRUD/Mongo_Spec.js
- app/client/src/sagas/PageSagas.tsx
Fixes #13013 
Cypress
// Code coverage diff between base branch:release and head branch: fix/prevent-dual-execution-of-pageload-action-when-generating-page-from-templates 
:green_circle: | total | 56.46 **(0)** | 37.92 **(0.01)** | 36.15 **(0)** | 56.69 **(0.01)**
> fix: prevent multiple execution of pageload actions when generating page from template

- .github/workflows/TestReuseActions.yml
- .github/workflows/integration-tests-command.yml
- .github/workflows/test-build-docker-image-fat.yml
- .github/workflows/test-build-docker-image.yml
Why did CI break?
- We use github actions cache to store jobstate for the previous runs. The default cache is invalidated incase the job fails. To support rerunning only failed tests, we use custom cache martijnhols/actions-cache@v3. Recently new changes into custome cache broke our workflow https://github.com/MartijnHols/actions-cache.
What is the solution?
- We are hardcoding the the version to use 3.0.2.
Why did CI break?
- We use github actions cache to store jobstate for the previous runs. The default cache is invalidated incase the job fails. To support rerunning only failed tests, we use custom cache martijnhols/actions-cache@v3. Recently new changes into custome cache broke our workflow https://github.com/MartijnHols/actions-cache.
What is the solution?
- We are …
> test: changed custom actions cache version to 3.0.2

- Dockerfile
Fix fat image not building in CI on release branch. This PR changes the Redis version in the fat container to v5, where it was v6 in the past. The PPA we were relying on to get v6 has upgrade to v7 and doesn't have the v6 packages anymore. But the v7 package's dependencies appear to be broken so we get the following error when installing from the PPA:
```
redis : Depends: redis-server (< 6:6.2.6-2rl1~focal1.1~) but 6:7.0.0-1rl1~focal1 is to be installed
```
PPA: https://launchpad.net/~redislabs/+archive/ubuntu/redis?field.series_filter=focal#packages
> fix: Redis installation in Dockerfile

- app/client/src/components/ads/Dropdown.test.tsx
- app/client/src/components/ads/Dropdown.tsx
Hide the empty row which appears due to the vertical padding of https://github.com/appsmithorg/appsmith/blob/release/app/client/src/components/ads/Dropdown.tsx#L672
Fixes #10329
Unit test
// Code coverage diff between base branch:release and head branch: fix/crud-dropdown 
:green_circle: | total | 56.46 **(0)** | 37.93 **(0.01)** | 36.15 **(0)** | 56.68 **(-0.01)**
:green_circle: | app/client/src/components/ads/Dropdown.tsx | 85.88 **(0.11)** | 66.96 **(1.38)** | 77.78 **(0)** | 85 **(0.06)**
:green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** …
> fix: dropdown showing an empty row when the options list is empty

- app/client/src/widgets/TableWidget/component/TableStyledWrappers.tsx
- app/client/src/widgets/TableWidget/component/TableUtilities.tsx
Fix misalignment in the table widget checkbox when using multiselect Row
Fixes #12615
- Visual
// Code coverage diff between base branch:release and head branch: fix/table-mutiselect-checkbox-alignment 
> fix: table Widget Multiselect Row checkbox alignment

- app/client/src/widgets/IframeWidget/component/index.tsx
add `allow="camera; microphone"` so it will allow camera & mic access inside iframe
Fixes #12924 
- dragged iframe & set URL to https://blog.minhazav.dev/research/html5-qrcode.html
- make sure camera works
> fix: allow camera & mic access for page in iframe

- app/client/src/components/formControls/utils.ts
- app/client/src/constants/DatasourceEditorConstants.ts
- app/client/src/sagas/ActionSagas.ts
Added a function to fix the corrupt state of mongo query. Function adds the missing config for all the commands in mongo query.
Fixes #13228 
// Code coverage diff between base branch:release and head branch: fix/mongo-query-payload 
:red_circle: | total | 56.43 **(-0.01)** | 37.81 **(-0.05)** | 36.02 **(-0.01)** | 56.64 **(-0.01)**
:red_circle: | app/client/src/components/formControls/utils.ts | 65.58 **(-8.66)** | 42.14 **(-18.06)** | 80.95 **(-8.52)** | 65 **(-7.73)**
:green_circle: | app/client/src/sagas/ActionSagas.ts | 12.67 **(0.1)** | 1.34 **(-0.16)** | 8 …
> fix:added fixActionPayloadForMongoQuery

- app/client/src/pages/Editor/JSEditor/JSFunctionSettings.tsx
Removes unwanted line in js editor settings 
Fixes #13490 
> chore: add overflow to js editor settings

- app/client/src/components/ads/Button.test.tsx
- app/client/src/components/ads/Button.tsx
- app/client/src/widgets/ButtonWidget/component/DragContainer.tsx
- app/client/src/widgets/ButtonWidget/component/index.tsx
When the "Run" button is clicked - it gets the disabled styles indicating a user should not be able to perform clicks while a particular query is running. But this does not prevent the operations to be performed repeatedly by clicking the button in the loading state.
This PR fixes this issue by checking if the button is not in a loading state, and only then allowing the onclick handler to be executed.
Fixes #12144
**Screenshots:**
**Before:**
https://user-images.githubusercontent.com/10229595/160589310-39e86f64-804c-4f01-9ed7-8779afb2e1d8.mov
**After fixing the issue:**
https://user-images.githubusercontent.com/10229595/160589949-12bc5c77-5898-4c9f-b269-5a2723e3012f.mov
**After fixing the issue for canvas**
https://user-images.githubusercontent.com/10229595/161064807-dc0d6f84-c99b-48b3-904 …
> fix: don't run onClick event handler when button is disabled

- app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ApplicationJson.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> Import-Export fails or takes a long time to respond when there is a lot of pages in the app. This was introduced in v1.6.22 due to the pageOrder filed that was added to the json file.
Fixes #13398 
- Locally
> fix: Optimize flow to maintain page order during export-import

- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCEImpl.java
> Fix the NPE thrown during the sendAnalytics event of action execution when the createdAt field is empty.
> fix: Add null check for createdAt field in analytics event

- app/client/src/entities/DataTree/dataTreeJSAction.test.ts
- app/client/src/pages/Editor/Explorer/helpers.test.ts
- app/client/src/utils/JSPaneUtils.test.ts
- app/client/src/utils/autocomplete/EntityDefinitions.test.ts
Fixes #10581
Jest
// Code coverage diff between base branch:release and head branch: chore/js-editor-tests 
:green_circle: | total | 56.62 **(0.2)** | 37.99 **(0.19)** | 36.11 **(0.09)** | 56.83 **(0.19)**
:green_circle: | app/client/src/entities/DataTree/dataTreeJSAction.ts | 100 **(85.29)** | 71.43 **(71.43)** | 100 **(100)** | 100 **(87.1)**
:green_circle: | app/client/src/pages/Editor/Explorer/helpers.tsx | 84.06 **(7.25)** | 58.51 **(18.08)** | 100 **(14.29)** | 84.21 **(8.77)**
:green_circle: | app/client/src/utils/JSPaneUtils.tsx | 90.7 …
> chore: Add JS editor test cases

- app/client/src/pages/setup/SignupSuccess.test.tsx
- app/client/src/pages/setup/SignupSuccess.tsx
- app/client/src/pages/setup/Welcome.tsx
- app/client/src/pages/setup/common.tsx
The welcome form is shown for a while sometimes before redirecting to another screen(can be checked with invited users).
As a fix returning a loader instead of the non-super user form.
Fixes #13549 
Before
https://user-images.githubusercontent.com/67054171/165237317-0060c012-42ea-4b2d-b600-00436dae845e.mov
After fix
https://user-images.githubusercontent.com/67054171/165237426-faa34581-eb79-4cc6-974d-1f5b696af510.mov
Unit test
// Code coverage diff between base branch:release and head branch: fix/signup-invite-user-route 
:red_circle: | total | …
> fix: welcome form shown for a while after signup

- app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/LayoutOnLoadActions/OnLoadActions_Spec.ts
- app/client/src/sagas/InitSagas.ts
Fixes #13504 
// Code coverage diff between base branch:release and head branch: fix/prevent-execution-of-pageload-actions-before-actions-are-fetched 
:red_circle: | total | 56.42 **(-0.01)** | 37.8 **(-0.01)** | 36.07 **(0)** | 56.64 **(-0.01)**
:red_circle: | app/client/src/sagas/InitSagas.ts | 48.65 **(-1.91)** | 33.85 **(-2.82)** | 58.33 **(0)** | 51.59 **(-2.41)**
> fix: only execute pageload actions after successfully fetching actions and jscollections in view mode

- app/client/cypress/support/Pages/JSEditor.ts
- app/client/src/components/utils/NameEditorComponent.tsx
- app/client/src/pages/Editor/JSEditor/JSObjectNameEditor.tsx
- app/client/src/sagas/JSPaneSagas.ts
- app/client/src/selectors/actionSelectors.tsx
- app/client/src/selectors/ui.tsx
For newly created `JSObjects` name gets highlighted for easy editing
Fixes #13213 
Cypress
// Code coverage diff between base branch:release and head branch: chore/highlight-name-for-newly-created-js-objects 
:red_circle: | total | 56.43 **(0)** | 37.79 **(-0.01)** | 36.06 **(-0.01)** | 56.65 **(0)**
:green_circle: | app/client/src/components/utils/NameEditorComponent.tsx | 20.41 **(1.66)** | 0 **(0)** | 0 **(0)** | 21.28 **(1.71)**
:green_circle: | app/client/src/pages/Editor/JSEditor/JSObjectNameEditor.tsx | 53.57 **(1.72)** | 20 **(0)** | 0 **(0)** | …
> chore: highlight name input field for newly created js objects

- deploy/helm/templates/statefulset.yaml
- deploy/helm/values.yaml
- Added a new variable `secretName` in `HELM/values.yaml` to specify the K8s Secret object that has been created by the user, outside the Appsmith helm flow.
- The secret data will be added to the deployment instance as ENV variables (overwriting the values in configMap if they have also been specified there).
- The secret resource will be of the format below, with the keys corresponding to the actual Appsmith ENV variable and the values as base64-encoded string:
```
apiVersion: v1
data:
APPSMITH_GOOGLE_MAPS_API_KEY: bW9uZ291c2Vy
kind: Secret
metadata:
name: appsmith-secret
type: Opaque
```
Fixes # [11752](https://github.com/appsmithorg/appsmith/issues/11752)
Manually on AWS EKS
> feat: Support getting values from secrets in helm chart configuration

- app/client/src/pages/Editor/gitSync/GitSyncModal.tsx
This scrollbar was introduced due to change in effective width of the container.
The breaking change was introduced in PR #12189
The exact change that causes this bar to appear is https://github.com/appsmithorg/appsmith/pull/12189/files\#diff-a9e89817480e902f90382662965dfc200a72566de917626db002de7a7e2920ddR51
By hiding overflow, we get rid of the horizontal scrollbar.
Fixes #13508 
Manually.
Notice: horizontal bar in modal at bottom
On release: 
https://user-images.githubusercontent.com/1573771/166429201-5e7c9d14-f196-4b39-9ac5-19ab58c663bc.mov
Notice: **no** horizontal bar in modal at bottom
On the deployed preview of this PR:
https://user-images.githubusercontent.com/1573771/166429268-a1c56ecd-6a4f-439d-b40f-cae5012969c0.mov …
> fix: remove horizontal scrollbar

- app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/LayoutOnLoadActions/OnLoadActions_Spec.ts
- app/client/src/sagas/InitSagas.ts
* prevent execution of onPageLoad actions before sucessful actions fetch
* Perform url update before fetching actions and jscollections
(cherry picked from commit 7261834fe539545b72d34aa75df9036f645f726d)
Fixes #13504 
// Code coverage diff between base branch:master and head branch: hotfix/prevent-onpageload-error-in-view-mode 
:red_circle: | total | 56.42 **(-0.01)** | 37.8 **(0)** | 36.07 **(0)** | 56.64 **(-0.01)**
:red_circle: | app/client/src/sagas/InitSagas.ts | 48.65 **(-1.91)** | 33.85 **(-2.82)** | 58.33 **(0)** | 51.59 **(-2.41)**</details>
> fix: only execute pageload actions after successfully fetching actions and jscollections in view mode (#13521)

- app/client/src/sagas/WidgetOperationSagas.tsx
- app/client/src/sagas/WidgetOperationUtils.test.ts
- app/client/src/sagas/WidgetOperationUtils.ts
- Introduced a new utility `getValueFromTree` that looks for path which
keys have dot characters in them
- BATCH_UPDATE_WIDGET_PROPERTY updates multiple properties of a widget and updates the state.
when two widget emits BATCH_UPDATE_WIDGET_PROPERTY parallely (happens on crud page creation),
the state updates done by the first BATCH_UPDATE_WIDGET_PROPERTY is overwritten by the second
BATCH_UPDATE_WIDGET_PROPERTY before it gets flushed to store, since both are processed parallel.
So we have created an actionChannel to buffer the eventsand process them only when the previous
event changes get flushed out to the state.
Why this was not observed previously?:
Typically when building an application, user drops one widget at a time. So we never ran into a
situation where two …
> chore: Update property from property pane to use improved get strategy & BATCH_UPDATE_WIDGET_PROPERTY to be processed serially

- .github/workflows/helm-release.yml
Add github action workflow that support to release new Helm version if it does not exist
Opening in place of https://github.com/appsmithorg/appsmith/pull/12950, as an internal PR.
> ci: Add github action workflow to release new helm version (#12950)

- app/client/src/sagas/WidgetOperationSagas.tsx
- app/client/src/sagas/WidgetOperationUtils.ts
Adding check to skip pasting logic while grouping widgets
Fixes #13572 
- 
manual UI testing
// Code coverage diff between base branch:release and head branch: groupingPushesBelowFix 
:red_circle: | app/client/src/sagas/WidgetOperationSagas.tsx | 61.52 **(-0.05)** | 51.09 **(-0.18)** | 60.78 **(0)** | 63.37 **(0.08)**
> fix: skip copying logic while grouping

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/JSONFormWidget/JSONForm_ArrayField_spec.js
- app/client/src/widgets/JSONFormWidget/fields/ArrayField.tsx
When `Allow currency change` in Currency Input and `Allow country code change`  in Phone Number Input are enabled for the fields in an Array Field type, the dropdowns enabled to change the `Country Code` and `Currency Code` does not update when selected.
Solution - 
The propertyPath which is used to update the particular field's configuration in the schema was incorrect. `__array_item__.children` was being appended twice before passing it down to the children.
Fixes #13270 
-Cypress
// Code coverage diff between base branch:release and head branch: fix/13270-jsonform-currencycode  …
> fix: JSONForm currency and phone input dropdown not working in Array Field

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GitSync/DisconnectGit_spec.js
- app/client/src/pages/Editor/gitSync/DisconnectGitModal.tsx
Revoke button can be pressed multiple times. This code change stops that.
Fixes #12164
Cypress test
// Code coverage diff between base branch:release and head branch: fix-12164 
:green_circle: | total | 56.57 **(0)** | 38.35 **(0.01)** | 35.84 **(0)** | 56.82 **(0)**
> fix: disable revoke button after first click

- app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/LayoutOnLoadActions/JSOnLoadActions_Spec.ts
- app/client/src/sagas/JSPaneSagas.ts
This PR prevents the "successful execution" toast message that shows up on page load in view mode.
Fixes #13581
Cypress
// Code coverage diff between base branch:release and head branch: fix/show-js-execution-successful-toast-on-edit-mode 
:red_circle: | total | 56.58 **(0)** | 38.36 **(-0.01)** | 35.84 **(0)** | 56.82 **(0)**
:green_circle: | app/client/src/sagas/JSPaneSagas.ts | 16.67 **(0.58)** | 1.03 **(-0.02)** | 4.55 **(0)** | 19.31 **(0.72)**
:green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0.78)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 …
> fix:only show js successful execution toast message in edit mode

- app/client/src/pages/Editor/gitSync/components/GitChangesList.tsx
We are using "updated" and "modified" in git changes list. We should be using "modified" consistently, this PR fixes that.
Fixes #13652 
Manually.
// Code coverage diff between base branch:release and head branch: fix-13652 
:red_circle: | total | 56.57 **(-0.01)** | 38.36 **(-0.01)** | 35.84 **(0)** | 56.82 **(0)**
> fix: use "modified" instead of "updated" in git changes list

- app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java
Fixes a failing junit test due to theme name change.
- JUnit test
> fix: Test failing for theme name change

- app/client/src/widgets/CheckboxGroupWidget/component/index.tsx
- app/client/src/widgets/CheckboxGroupWidget/widget/index.tsx
1. Wrapped the CheckboxGroup default component in the React.forwardedRef so that the incoming ref from the parent widget can be hooked up with the CheckboxGroupContainer.
2. Hooked the BaseWIdget `contentRef` to the CheckboxGroupContainer component via CheckboxGroup Widget.
Fixes #13049 
- Manually
// Code coverage diff between base branch:release and head branch: feature/dh-stdzn-checkbox-group  …
> feat: dynamic height checkbox group standardization

- app/client/src/widgets/RadioGroupWidget/component/index.tsx
- app/client/src/widgets/RadioGroupWidget/widget/index.tsx
1. Wrapped the RadioGroup default component in the React.forwardedRef so that the incoming ref from the parent widget can be hooked up to the RadioGroupContainer.
2. Hooked the BaseWIdget `contentRef` to the RadioGroupContainer component via RadioGroup Widget.
Fixes #13050  
- Manually
// Code coverage diff between base branch:release and head branch: feature/dh-stdzn-radio-group-widget 
:green_circle: | total | 56.49 **(0.02)** | 37.98 **(0.05)** | 36.27 **(0.08)** | 56.71 **(0.01)**
:red_circle: | app/client/src/actions/reflowActions.ts | 75 …
> feat: dynamic height radio group widget standardization

- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java
> During the git import if we give the empty repo url, we just throw the error and inform the user. But we missed out is not creating the application in such scenarios. This PR fixes the app getting created when the repo is empty. 
Fixes #13446 
- JUnit test
- Locally
> fix: Application created when the repo is empty in git import flow

- app/client/src/actions/pageActions.tsx
- app/client/src/sagas/InitSagas.ts
- app/client/src/sagas/PageSagas.tsx
As a quick fix to prevent the on-page load actions from firing before the actions are even fetched, we had reverted the changes to make fetch page DSL call parallel in [13587](https://github.com/appsmithorg/appsmith/pull/13587). Unfortunately, theming PR brought back parallelisation and the issue along with it. 
This PR ensures that the on-page-load actions are only made after actions are fetched while preserving parallelisation.
Fixes #13504 
- Manual
// Code coverage diff between base branch:release and head branch: fix/onload-action 
:red_circle: | …
> fix: delay on page load actions till all actions are retrieved

- app/client/src/components/editorComponents/ActionNameEditor.tsx
- app/client/src/components/editorComponents/EditableText.tsx
- app/client/src/pages/Editor/DataSourceEditor/FormTitle.tsx
> Added underline on hover for the titles in Queries, JS and Datasources.
Fixes #13329 
// Code coverage diff between base branch:release and head branch: Fix/Hover-state-of-renaming-titles 
:red_circle: | total | 56.59 **(0)** | 38.39 **(0)** | 35.83 **(-0.01)** | 56.83 **(0)**
:red_circle: | app/client/src/components/editorComponents/EditableText.tsx | 25 **(-0.42)** | 14.63 **(-0.75)** | 6.67 **(-0.47)** | 27.27 **(-0.51)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | 36.21 **(0)** | 56.99 …
> fix: Hover state of renaming titles

- .github/workflows/label-checker.yml
Check for the label "Test Plan Approved" in PRs
If this does not exist the PR check will fail
> Check for "Test Plan Approved" Label in PRs

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts
- app/client/cypress/support/Pages/JSEditor.ts
- app/client/src/ce/constants/messages.ts
- app/client/src/components/editorComponents/CodeEditor/constants.ts
- app/client/src/components/editorComponents/JSResponseView.tsx
- app/client/src/pages/Editor/JSEditor/Form.tsx
- app/client/src/reducers/entityReducers/jsActionsReducer.tsx
- app/client/src/sagas/EvaluationsSaga.ts
- app/client/src/sagas/JSPaneSagas.ts
- app/client/src/selectors/entitiesSelector.ts
This PR ensures that only parse errors prevent the execution of js functions. Parse errors/ Lint errors within a function (that don't render the entire JS Object invalid) don't cause all functions to be unrunnable.
Fixes #12012 
Cypress
// Code coverage diff between base branch:release and head branch: fix/prevent-lint-warnings-from-blocking-execution-in-js-objects 
:red_circle: | total | 56.58 **(-0.01)** | 38.38 **(-0.02)** | 35.83 **(-0.01)** | 56.83 **(-0.01)**
:red_circle: | app/client/src/ce/constants/messages.ts | 77.81 **(-0.02)** | 100 **(0)** | 34.35 …
> fix: prevent lint warnings from blocking execution in js objects

- app/client/src/sagas/InitSagas.ts
Added theme error effects into failureActionEffect during app initialisation.
- Minor refactor
- Manual
> chore: safe crash application on theme APIs failure

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Applications/ApplicationURL_spec.js
- app/client/src/pages/AppViewer/PrimaryCTA.tsx
- app/client/src/sagas/ErrorSagas.tsx
Fixes truncated query params in redirect URLs
Fixes #11422 
- Manual
- Cypress
> fix: persists query param in redirect urls

- app/client/cypress/integration/Smoke_TestSuite/Application/CommunityIssues_Spec.ts
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GitSync/GitSyncedApps_spec.js
Updated gitSyncedApp_spec and CommunityIssues_pec as per modified data
locally
// Code coverage diff between base branch:release and head branch: updateCypressTests 
> test: update cypress tests as per added test data in TED

- app/client/src/pages/Editor/Explorer/Files/Submenu.tsx
- app/client/src/pages/Editor/Explorer/Files/index.tsx
Open explorer submenu when "Add Query/JS" button is clicked.
- Manual
// Code coverage diff between base branch:release and head branch: fix/trigger-submenu-new-query-btn 
:green_circle: | total | 56.61 **(0)** | 38.55 **(0.01)** | 35.89 **(0)** | 56.86 **(0.01)**
:green_circle: | app/client/src/pages/Editor/Explorer/Files/Submenu.tsx | 69.77 **(0.63)** | 44.83 **(0)** | 42.11 **(3.22)** | 69.33 **(0.76)**
:red_circle: | app/client/src/pages/Editor/Explorer/Files/index.tsx | 75.56 **(-1.18)** | 33.33 **(5.55)** | 42.86 **(-7.14)** | 79.49 **(-0.51)**</details>
> fix: Trigger submenu instead of omnibar when Add Query/JS" button is clicked.

- app/client/src/widgets/JSONFormWidget/component/Form.tsx
- app/client/src/widgets/JSONFormWidget/component/index.tsx
- app/client/src/widgets/JSONFormWidget/widget/index.tsx
**Created again because of merge conflicts.**
1. Wrapped the JSONForm default component in the React.forwardRef so that the incoming ref from the parent widget can be hooked up to the Form component underneath.
2. Wrapped the Form component in the React.forwardRef and set the `ref` to the FormBody component (div).
2. Hooked the BaseWidget `contentRef` to the JSONForm component via JSONForm Widget.
Fixes #13060 
- Manually
> feat: dynamic height json form widget standardisation

- app/client/src/widgets/DatePickerWidget2/component/index.tsx
- app/client/src/widgets/DatePickerWidget2/widget/index.tsx
**Created again because of merge conflicts.**
1. Passed the `contentRef` to `DatePickerComponent` from `DatePickerWidgetV2`.
2. Wrapped the `DatePickerComponent` class component in the React.forwardRef, and added a new optional prop `innerRef` to pass it to its child `StyledControlGroup`.
4. `StyledControlGroup` is a styled component on top of `ControlGroup` and there is no way to hook it up the ref dom element, so wrapped `StyledControlGroup` in a `div`.
Fixes #13059
- Manually
> feat: dynamic height datepicker widget standardisation

- app/client/src/reducers/uiReducers/appThemingReducer.ts
**Summary of Changes**
Emptied the theming stack when REDUX Action FETCH_APP_THEMES_SUCCESS is executed.
Fixes #13836 
Manually tested
// Code coverage diff between base branch:release and head branch: fix/fix-reset-theme-stack 
:green_circle: | total | 56.62 **(0.01)** | 38.56 **(0.01)** | 35.9 **(0)** | 56.86 **(0)**
:red_circle: | app/client/src/reducers/uiReducers/appThemingReducer.ts | 28 **(-1.17)** | 100 **(0)** | 13.33 **(0)** | 28 **(-1.17)**
:green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(1.64)** | 64.71 **(2.95)** | 73.33 …
> fix: added empty stack in sppThemingReducer

- app/client/src/pages/Settings/config/email.ts
> Add a field for a reply-to email address on the email config page to start receiving emails for invitations and forgot password flow.
Fixes #13853 
> Checked if new field added on Email config settings page and is linked to `APPSMITH_REPLY_TO` variable as expected.
// Code coverage diff between base branch:release and head branch: fix/reply-to-address 
:green_circle: | total | 56.56 **(0)** | 38.55 **(0.01)** | 35.87 **(0)** | 56.8 **(0)**
:green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(1.64)** | 64.71 **(2.95)** | 73.33 **(0)** | …
> fix: add a field for a reply-to email address on the email config page

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/JSONFormWidget/JSONForm_FormProperties_spec.js
- app/client/src/components/propertyControls/IconSelectControl.tsx
In the property pane of the JSON Form widget; were 2 icon selectors both of them in a different collapsed section. As the popover width was being set by targeting the class .bp3-select-popover, the first was getting overridden by the second instance of the popover and thus getting the width of 0 (because of the hidden state of 2nd icon selector).
They now have separate class names based on id.
Fixes #13879 
- Cypress
// Code coverage diff between base branch:release and head branch: fix/13879-collapsed-section-icon 
:red_circle: | total | 56.56 **(0)** | 38.54 …
> fix: Property pane - Hidden sections icon select popover not opening properly

- app/client/src/pages/Editor/Explorer/Entity/AddButton.tsx
- app/client/src/pages/Editor/Explorer/Files/Submenu.tsx
Adds selected state to Query/JS add button in explorer when submenu is open.
- Manual
// Code coverage diff between base branch:release and head branch: chore/highlight-plus-icon-query-js 
:green_circle: | app/client/src/pages/Editor/Explorer/Files/Submenu.tsx | 69.77 **(0)** | 45.16 **(0.33)** | 42.11 **(0)** | 69.33 **(0)**</details>
> chore: Added selected state for query/js add button in the explorer

- app/client/src/components/editorComponents/CodeEditor/generateQuickCommands.tsx
- app/client/src/sagas/SnipingModeSagas.ts
Fixes text overlap for datasources with longer names in slash commands.
Fixes #13868 
- Manual
// Code coverage diff between base branch:release and head branch: fix/13868-text-overlap-slash-commands 
:red_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 70.59 **(-1.96)** | 100 **(0)** | 93.33 **(0)**</details>
> fix: Text overlap in slash commands

- app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datasources/ElasticSearchDatasource_spec.js
- app/client/cypress/locators/DatasourcesEditor.json
- app/client/cypress/support/dataSourceCommands.js
- app/client/src/components/ads/TextInput.tsx
- app/client/src/components/formControls/KeyValueArrayControl.tsx
Fixes validation regex checks blocking onChange function from firing in KeyValue array form input.
Fixes #13919
// Code coverage diff between base branch:release and head branch: fix/fix-key-value-validation-check 
:green_circle: | total | 56.65 **(0.01)** | 38.62 **(0.01)** | 35.97 **(0)** | 56.9 **(0.01)**
:green_circle: | app/client/src/components/ads/TextInput.tsx | 79.84 **(0.61)** | 63.89 **(1.3)** | 87.5 **(0)** | 78.63 **(0.66)** …
> fix: Fix validation check that is blocking input from changing

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/JSONFormWidget/JSONForm_Footer_spec.js
- app/client/src/widgets/JSONFormWidget/component/Form.tsx
SONForm submit/reset button should always be at the bottom of the form
Fixes #12599
Cypress
// Code coverage diff between base branch:release and head branch: task/12599-jf-sticky-button-footer 
:red_circle: | app/client/src/widgets/JSONFormWidget/component/Form.tsx | 28.28 **(-0.59)** | 18.52 **(-0.71)** | 0 **(0)** | 29.79 **(-0.32)**</details>
> task: JSONForm footer should always stick to bottom when fixed footer enabled

- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/PluginUtils.java
- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/SmartSubstitutionUtils.java
- app/server/appsmith-plugins/graphqlPlugin/src/main/java/com/external/plugins/GraphQLPlugin.java
- app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
- Add JSON smart substitution support for GraphQL query variables section.
Fixes #12391
- Manual
- JUnit TC will be written as part of issue https://github.com/appsmithorg/appsmith/issues/12388 before the `feat/graphql` branch is merged to `release`
> feat: add smart json substitution logic for query variables in GraphQL plugin

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ApiPaneTests/API_MultiPart_Spec.ts
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/JSObjectToInput_Spec.ts
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/JSObjectToListWidget_Spec.ts
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/Promises_Spec.ts
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts
- app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OnLoadTests/JSOnLoad_Spec.ts
- app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Params/PassingParams_Spec.ts
- app/client/cypress/support/Objects/CommonLocators.ts
- app/client/cypress/support/Pages/JSEditor.ts
- app/client/src/components/editorComponents/JSResponseView.tsx
Fixes #13764
Cypress
// Code coverage diff between base branch:release and head branch: chore/prioritize-parse-errors-in-debugger-callout 
:red_circle: | total | 56.64 **(0)** | 38.6 **(-0.01)** | 35.96 **(0)** | 56.89 **(0)**
:red_circle: | app/client/src/components/editorComponents/JSResponseView.tsx | 50 **(-1.22)** | 25.88 **(-0.63)** | 8.33 **(0)** | 51.85 **(-1.31)**
:red_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 70.59 **(-1.96)** | 100 **(0)** | 93.33 **(0)**</details>
> fix: prioritize parse errors in debugger callout

- app/client/src/components/editorComponents/JSResponseView.tsx
- app/client/src/pages/Editor/JSEditor/Form.tsx
- app/client/src/pages/Editor/JSEditor/JSFunctionRun.tsx
- app/client/src/pages/Editor/JSEditor/JSObjectNameEditor.tsx
- app/client/src/pages/Editor/JSEditor/styledComponents.ts
- app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
- app/client/src/sagas/InitSagas.ts
This PR makes the JS Editor page consistent with that of the Query page
Fixes #11008 
Fixes #12303
Manual (Only UI changes)
// Code coverage diff between base branch:release and head branch: js-editor-inconsistency 
:green_circle: | total | 56.62 **(0.01)** | 38.54 **(-0.01)** | 35.91 **(0.01)** | 56.86 **(0)**
:red_circle: | app/client/src/pages/Editor/JSEditor/Form.tsx | 28.77 **(-0.96)** | 0 **(0)** | 0 **(0)** | 32.81 **(-1.04)**
:red_circle: | app/client/src/pages/Editor/JSEditor/JSObjectNameEditor.tsx | 53.13 **(-0.44)** | 20 **(0)** | 0 **(0)** | 53.13 …
> fix: Js editor inconsistency

- app/client/src/widgets/JSONFormWidget/schemaParser.test.ts
- app/client/src/widgets/JSONFormWidget/schemaParser.ts
In an existing JSONForm consisting of an object, if the value is changed for that particular object to `null` in the source data, the app crashes as the parser is not able to process is appropriately.
The ideal scenario is that `null` doesn't change a fields configuration unlike a value changing from a number to a string.
Solution:
Modify the typing of the sourceData key to `unknown` rather than using `as`; which triggered multiple warnings leading to the proper validation of the `sourceData` in the parser.
Fixes #13948 
- Jest test cases were added to run null and undefined keyed source data over the same schema to verify that the schema configuration doesn't change.
<details><summary>:green_circle: Total coverage has …
> fix: JSONForm modify source data object to null causes crash

- app/client/src/pages/UserProfile/General.tsx
Fixes "There was an unexpected error" error message in reset password flow from user profile screen.
Fixes #13872 
- Manual
// Code coverage diff between base branch:release and head branch: fix/reset-password-error-message 
> fix: Error message thrown on reset password from user profile screen

- app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/MongoConfig.java
>
Migrations should run before application is started to avoid side effects caused by API calls
- Test A
- Test B
> Fix for running migrations before application start

- app/client/src/widgets/SwitchGroupWidget/component/index.tsx
- app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
1. Wrapped the SwitchGroup default component in the React.forwardedRef so that the incoming ref from the parent widget can be hooked up to the SwitchGroupContainer.
2. Hooked the BaseWIdget `contentRef` to the SwitchGroupContainer component via SwitchGroup Widget.
Fixes #13051 
- Manually
// Code coverage diff between base branch:release and head branch: feature/dh-stdzn-switch-group-widget  …
> feat: dynamic height switch group widget standardization

- app/client/src/pages/AppViewer/BrandingBadge.tsx
- app/client/src/pages/AppViewer/BrandingBadgeMobile.tsx
Fixes #14017
- Bug fix
// Code coverage diff between base branch:release and head branch: fix/branding-badge-url 
> fix: Redirect to website home instead of appsmith home on watermark 

- app/client/src/widgets/RateWidget/component/index.tsx
- app/client/src/widgets/RateWidget/widget/index.tsx
**Created again because of merge conflicts**
1. Wrapped the RateWidget default component in the React.forwardRef so that the incoming ref from the parent widget can be hooked up to the `RateComponent` component underneath.
2. Wrapped the `RateComponent` component in the React.forwardRef and set the ref to the `RateContainer` component (div).
3. Hooked the BaseWidget contentRef to the JSONForm component via JSONForm Widget.
4. `RateComponent` uses the ref to `RateContainer` so type casted it `React.MutableRef`.
Fixes #13438 
- Manually
> feat: dynamic height RateWidget standardisation

- app/client/src/widgets/JSONFormWidget/fields/SelectField.test.tsx
- app/client/src/widgets/JSONFormWidget/fields/SelectField.tsx
The Select field only considers `null` and `undefined` as invalid values.
But when we consider the select widget, it considers empty string as invalid value along with `null` and `undefined`.
This PR aligns the implementation and makes the JSON Form's select field consider and empty value as an invalid value when the `Required` property is enabled.
Fixes #13981
Jest Test:
The validation function is tested in 3 test cases
1. When required is enabled and the values are either valid or invalid -> It should return valid
2. When required is enabled and the values are valid -> It should return valid
3. When required is enabled and the values are invalid -> It should return invalid
<details><summary>:green_circle: Total coverage has …
> fix: JSONForm Select field validate empty string as an invalid value

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Form_With_CheckBox_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Switch_spec.js
- app/client/cypress/locators/commonlocators.json
- app/client/src/components/constants.ts
- app/client/src/constants/WidgetConstants.tsx
- app/client/src/utils/DSLMigrations.ts
- app/client/src/utils/migrations/PropertyPaneMigrations.ts
- app/client/src/widgets/CheckboxWidget/component/index.tsx
- app/client/src/widgets/CheckboxWidget/index.ts
- app/client/src/widgets/CheckboxWidget/widget/index.tsx
- app/client/src/widgets/JSONFormWidget/fields/CheckboxField.tsx
- app/client/src/widgets/JSONFormWidget/fields/SwitchField.tsx
- app/client/src/widgets/SwitchWidget/component/index.tsx
- app/client/src/widgets/SwitchWidget/index.ts
- app/client/src/widgets/SwitchWidget/widget/index.tsx
- app/client/src/widgets/constants.ts
> In switch and checkbox add a property of position,alignment, label color, size, and font style and add migration for the same
Fixes #13586 
// Code coverage diff between base branch:release and head branch: fix/issue-13586 
:green_circle: | total | 56.66 **(0.04)** | 38.7 **(0.07)** | 35.99 **(0.05)** | 56.91 **(0.04)**
:green_circle: | app/client/src/components/editorComponents/ErrorBoundry.tsx | 95.45 **(18.18)** | 100 **(12.5)** | 85.71 **(42.85)** | 95 **(20)**
:green_circle: | app/client/src/utils/DSLMigrations.ts | 73.97 **(0.14)** | 69.7 …
> fix: checkbox, switch property fields update, migration added

- app/client/src/components/designSystems/appsmith/header/DeployLinkButton.tsx
This PR removes the 200ms transition delays that comes by default with the blueprint popover component.
This override is only for the deploy button though.
Fixes #13927 
- Manual
// Code coverage diff between base branch:release and head branch: fix/remove-animation-deploy-button 
> fix: Remove animation in deploy button

- app/client/src/components/ads/Tooltip.tsx
- app/client/src/pages/Editor/Explorer/Files/Submenu.tsx
- app/client/src/pages/common/SharedUserList.tsx
Sets the default transition duration on tooltip component to 0.
Fixes #13926 
Fixes #13923 
- UX change
- Manual
// Code coverage diff between base branch:release and head branch: fix/remove-tooltip-animation 
:green_circle: | total | 56.62 **(0)** | 38.64 **(0.01)** | 35.94 **(0)** | 56.87 **(0)**
:green_circle: | app/client/src/components/ads/Tooltip.tsx | 100 **(0)** | 87.5 **(4.17)** | 100 **(0)** | 100 **(0)**
> fix: Removes transition animation on tooltip component

- app/client/src/widgets/SingleSelectTreeWidget/component/index.tsx
- app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
Created again because of merge conflicts.
1. Passed the `contentRef` to `SingleSelectTreeComponent` from `SingleSelectTreeComponent`.
2. Wrapped the `SingleSelectTreeComponent` functional, component in the React.forwardRef.
3. Set the final `ref` from React.forwardRef to `TreeSelectContainer` which is a styled `div`.
Fixes #13057
- Manually
> feat: dynamic single tree select widget standardisation

- app/client/src/pages/Editor/MainContainer.test.tsx
- app/client/src/pages/Editor/MainContainer.tsx
- app/client/src/pages/Editor/WidgetsEditor/CanvasContainer.tsx
- app/client/src/pages/Editor/WidgetsEditor/index.tsx
- app/client/src/reducers/uiReducers/mainCanvasReducer.ts
- app/client/src/selectors/mainCanvasSelectors.tsx
- app/client/src/utils/hooks/useDynamicAppLayout.tsx
When there are widgets on the canvas, on refresh the width of the widget flickers due to a bug in dynamic app layout logic. This PR fixes that
Fixes #12292
- Bug fix
// Code coverage diff between base branch:release and head branch: fix/flickering-of-canvas-width 
:green_circle: | total | 56.64 **(0)** | 38.61 **(0.01)** | 35.96 **(0)** | 56.9 **(0.01)**
:green_circle: | app/client/src/pages/Editor/WidgetsEditor/CanvasContainer.tsx | 100 **(2.38)** | 77.78 **(15.28)** | 100 **(0)** | 100 **(2.44)**
:red_circle: | app/client/src/pages/Editor/WidgetsEditor/index.tsx | 93.55 **(-0.2)** | 60 **(0)** …
> fix: Canvas jitters on page refresh on an application where widgets don't occupy the entire width of the canvas

- app/client/src/components/editorComponents/WidgetNameComponent/index.tsx
Changed the condition to display errored widgetLabel only when focused or selected and not permanently.
Fixes #13873 
Manual UI verification
// Code coverage diff between base branch:release and head branch: widgetLabelErrorFix 
:green_circle: | app/client/src/components/editorComponents/WidgetNameComponent/index.tsx | 96.97 **(0)** | 84.91 **(1.27)** | 100 **(0)** | 96.88 **(0)**</details>
> fix: stop showing errored widget labels prmanently and show them only on hover or when selected

- app/rts/src/server.ts
Fix NPE in RTS when the `connectionCookie` is `undefined`.
> fix: NPE when `connectionCookie` is `undefined`

- app/client/Dockerfile
- deploy/docker/scripts/healthcheck.sh
Added a fix for the docker health check on editor with ssl enabled for `appsmith-ce` fat container and the slim client `appsmith-editor`
// Code coverage diff between base branch:release and head branch: FIX/health-check-https 
> fix: added healthcheck for editor with https

- app/client/src/pages/Editor/WidgetSidebar.tsx
Auto-focus search input box when widgets library is open in explorer
Fixes #13929 
- Manual
// Code coverage diff between base branch:release and head branch: chore/focus-widget-search-input 
:green_circle: | app/client/src/pages/Editor/WidgetSidebar.tsx | 66.67 **(3.03)** | 38.89 **(22.22)** | 37.5 **(8.93)** | 63.64 **(2.35)**
> chore: Focus search input box when widgets library is opened

- app/client/jest.config.js
- Add `testEnvironment` in the jest config file to `jsdom` this is needed for the CI run on the cra-5 branch.
- Increase `testTimeout` in the jest config, from default 5000 to 9000.
- Need to run all the jest test cases on the CI and re-run the workflow multiple times to ensure all test cases pass, without timeout error
-  …
> fix: update jest env and test-timeout

- app/rts/Dockerfile
The Node version isn't inline with that in the `package.json`, which was making the Docker build fail. This PR fixes this.
> fix: Fix Node version in RTS' Dockerfile

- app/server/appsmith-git/pom.xml
- app/server/appsmith-interfaces/pom.xml
- app/server/appsmith-plugins/pom.xml
- app/server/appsmith-plugins/rapidApiPlugin/pom.xml
Seeing [this](https://stackoverflow.com/questions/66801256/java-lang-illegalaccesserror-class-lombok-javac-apt-lombokprocessor-cannot-acce) error due to old lombok package version. We have updated the version in most of the pom files in an earlier release but few pom files still use the old version.
Ref: https://theappsmith.slack.com/archives/CPQNLFHTN/p1653413674448529
Fixes #14080 
- Manually running `mvn clean compile` results in build success
> fix: Upgrade Lombok package version to 1.18.22 to avoid build error #14080

- app/client/src/widgets/ModalWidget/component/index.tsx
The modal widget's name was not getting focused on adding a new modal widget. This was happening since the autofocus is happening on the modal's Overlay component.
This PR disables the autofocus on the modal overlay.
Fixes #14204
- Manual
// Code coverage diff between base branch:release and head branch: fix/modal-autofocus 
:red_circle: | total | 56.7 **(-0.01)** | 38.66 **(0)** | 36.21 **(-0.01)** | 56.96 **(0)**
:green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0.78)** | 72.55 **(3.92)** | 100 **(0)** | 93.33 **(0.95)**
:red_circle: | …
> fix: name not getting focused on adding new modal widget

- app/client/src/sagas/ActionExecution/PluginActionSaga.ts
- app/client/src/sagas/ActionExecution/PluginActionSagaUtils.test.ts
- app/client/src/sagas/ActionExecution/PluginActionSagaUtils.ts
For this issue, the server returns no datatypes for an api or query response, Normally these datatypes should be returned for every API or Query, but in case they don't, we want to protect against such occurence.
Fixes #14146 
Jest
PluginActionSagaUtils.test.ts
// Code coverage diff between base branch:release and head branch: fix/fix-empty-datatype 
:red_circle: | total | 56.71 **(0)** | 38.65 **(-0.02)** | 36.22 **(0)** | 56.96 **(0)**
:red_circle: | app/client/src/sagas/ActionExecution/PluginActionSaga.ts | 17.22 **(0)** | 1.69 **(-0.14)** | 9.09 **(0)** | …
> fix: Add null checks for empty datatypes in api/query responses

- app/client/src/sagas/EvaluationsSaga.ts
- app/client/src/workers/evaluation.worker.ts
`evalMetaUpdates` was undefined, we tried using `evalMetaUpdates.length`.  
- It was noticed that when we have dataCloneError, in that case, workerResponse become
```
workerResponse = { errors: [{context: "someJSON", message:"error message"}]
```
Here,  `evalMetaUpdates` is undefined in `evaluateTreeSaga` and hence the crash as we use `evalMetaUpdates.length`.
- `evalMetaUpdates` has a moment object in the given application, this leads to DataCloneError.
- We stringify and parse evalMetaUpdates to avoid `DataCloneError`
- We set a default value as `[]` to `evalMetaUpdates` in `evaluateTreeSaga` 
Fixes #14299
- Manually
Test will be added in separate PR 
-  DataCloneError case
-  Normal success case
> fix: crash due to evalMetaUpdate

- app/client/src/widgets/MultiSelectTreeWidget/component/index.styled.tsx
> Update CSS in MultiSelectTree Widget and it fixed the issue of the Header node checkbox of a MultiTreeSelect widget does not display properly on hovering
Fixes #14026
> fix: updated css clash with tree select

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/DatePicker_2_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GitImport/GitImport_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GitSync/GitSyncedApps_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GitSync/RegenerateSSHKey_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/LayoutValidation/AppPageLayout_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Replay/Replay_Editor_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/WidgetGrouping/WidgetGrouping_spec.js
- app/client/cypress/locators/gitSyncLocators.js
- app/client/cypress/support/commands.js
- app/client/cypress/support/gitSync.js
This PR contains cypress tests for regenerate SSH key flow and fixes flaky tests:
- ReplayEditor_spec
- WidgetGrouping_spec
- GitSyncedApps_spec
- DatePicker_2_spec
locally
> test: Add regenerate SSH key tests

- .github/workflows/integration-tests-command.yml
We ran performance tests on machine provided by github and buldjet machine for a while to see how they perform. 
We have seen a lot of deviation in runs done on github making the data useless. With this PR we no longer run the tests on github machine.
Fixes #14301
CI related, no impact on users.
Will be tested after merge.
> chore: Run perf tests only on buildjet machine

- app/client/src/components/editorComponents/ApiResponseView.tsx
- app/client/src/pages/Editor/QueryEditor/Table.tsx
> When a response to an API is string for TABLE datatype, app crashes. 
Fixes #14242
> fix: Handle string datatype in api response

- app/client/src/utils/hooks/useDynamicAppLayout.tsx
this PR fixes the following bug:
> [This](https://release.app.appsmith.com/app/earworm/home-6219207a0276eb01d22fec5e/edit) app is stuck in a loading state and I'm unable to edit the app. The app can be viewed in view mode though
Fixes #14381
- Bug fix
> fix: App canvas is stuck in loading state ( Desktop Layout ) 

- app/server/appsmith-server/pom.xml
Fix release server image not coming up due to the following error:
```
java.lang.ClassNotFoundException: okhttp3.OkHttpClient$Builder
```
> fix: Fix okhttp dependency

- app/client/src/selectors/gitSyncSelectors.tsx
Updating git documentation fallback url. This URL shouldn't exist, because git documentation is BE driven.
> fix: fallback url for git documentation

- app/client/src/pages/Editor/gitSync/Tabs/Deploy.tsx
Due to file locks commit and discard might take a while, this PR updates the progress bar progress-speed. This makes user easy as earlier progress bar was stuck at 90% and users felt that progress bar was stuck.
Manually.
https://user-images.githubusercontent.com/1573771/171134294-73da4403-59bc-4a15-b45d-5aa0219407fe.mov
https://user-images.githubusercontent.com/1573771/171134029-707cc255-eeb1-4da7-9989-5afd74a126a3.mov
// Code coverage diff between base branch:release and head branch: chore-make-git-progress-bar-slow 
:green_circle: | total | 56.71 **(0)** | …
> chore: slowed down git commit and discard progress bar

- app/client/cypress/integration/Smoke_TestSuite/Application/CommunityIssues_Spec.ts
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/JSObjectToInput_Spec.ts
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/CRUD_JSONForm/Mongo_Spec.ts
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/CRUD_JSONForm/MySQL_Spec.ts
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/CRUD_JSONForm/Postgres_Spec.ts
> Fix the frequently failing & flaky test scripts to improve the stability of CI runs
Specs/Cases targgetted:
> Smoke_TestSuite/Application/CommunityIssues_Spec.ts
> Smoke_TestSuite/ClientSideTests/Binding/JSObjectToInput_Spec.ts
> Smoke_TestSuite/ClientSideTests/CRUD_JSONForm/Mongo_Spec.ts
> Smoke_TestSuite/ClientSideTests/CRUD_JSONForm/MySQL_Spec.ts
> Smoke_TestSuite/ClientSideTests/CRUD_JSONForm/Postgres_Spec.ts
- Script fix (non-breaking change which fixes an script issue)
> Release CI
> test: Script fixes for flaky tests

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/CRUD_JSONForm/Postgres_Spec.ts
- app/client/cypress/support/Pages/PropertyPane.ts
- app/client/src/sagas/AppThemingSaga.tsx
When we change to modern, the toast shows Theme default applied.. It should have been Theme Modern applied. This PR fixes this.
Fixes #14487 
- Bug fix
> fix: Toast shows wrong theme name when changing themes

- app/client/src/sagas/WidgetOperationUtils.test.ts
- app/client/src/sagas/WidgetOperationUtils.ts
List widget:
Update `dynamicTriggerPathList` with new widget names upon copying.
Fixes #14028
- Unit test
- [Repro steps](https://github.com/appsmithorg/appsmith/issues/14028#issuecomment-1147268849) manually tested
> fix: list copy - update dynamic trigger path list names

- app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationSuccessHandlerCE.java
Security.STATE_PARAMETER_ORIGIN is already set to "origin="
When we open a private application url in incognito window ( where appsmith is not logged in) and log in via any Ouath (github/google)  mechanism, after successful authentication we will be redirected to Default "/applications" page instead of actual application 
Manually
> fix: Redirection after login does not work for Google and Github

- .github/workflows/release-drafter.yml
Adding the parameter `commitish` to release-drafter to ensure that all draft releases are created on the `master` branch and not on the default `release` branch of the repo. This ensures that we don't make mistakes when tagging a release for Appsmith. 
> chore: Adding the configuration parameter to ensure that the target branch is master for all releases are created

- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/ActionServiceCE_Test.java
If the client has not been refreshed and contains old copies of rest api actions (where workspaceId is absent and only orgnaizationId is present), then this PR aims to add the workspace id to such nested datasources.
Fixes #14599
> fix: Adding workspaceId when missing with organizationId present in REST API actions

- .github/workflows/integration-tests-command.yml
We don't need sudo on the main script, we can use sudo in node scripts to set process priority
> ci: Remove sudo from perf tests command

- .github/workflows/test-build-docker-image.yml
Use buildjet runners for Cypress tests, and fewer of them.
> ci: Use buildjet runners for Cypress tests, and fewer of them

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ActionExecution/StoreValue_spec.ts
- app/client/src/actions/pageActions.tsx
- app/client/src/entities/DataTree/actionTriggers.ts
- app/client/src/sagas/ActionExecution/StoreActionSaga.ts
- app/client/src/workers/Actions.test.ts
- app/client/src/workers/Actions.ts
`yield take(ReduxActionTypes.UPDATE_APP_STORE_EVALUATED)` inside storeValueLocally saga can catch previous storeValue action and complete the latest call too.
This was not expected behaviour with promisified storeValue as we need to track completion of each storeValue action separately.
Fixes #14653
Manual & Cypress
> fix: multiple storeValue action completion track

- .github/workflows/test-build-docker-image.yml
Reverts appsmithorg/appsmith#14636
Reverting this change for now because there is an issue when re-running the failed specs. The action is unable to find the correct directory. 
Check error at: https://github.com/appsmithorg/appsmith/runs/6987190225?check_suite_focus=true#step:9:9
> ci: Revert "ci: Use buildjet runners for Cypress tests, and fewer of them"

- app/client/src/utils/EditorUtils.ts
- After the cra-5 release I noticed the moment-timezone code in `EditorUtils` is still commented. I have updated the file and changed the async import for webpack 5.
- Tested manually on the canvas
> fix: editor utils moment async import

- app/client/src/widgets/JSONFormWidget/widget/helper.test.ts
- app/client/src/widgets/JSONFormWidget/widget/helper.ts
- app/client/src/widgets/JSONFormWidget/widget/propertyConfig.test.ts
- app/client/src/widgets/JSONFormWidget/widget/propertyConfig.ts
When the JSONForm auto-generate option is disabled, new source data is added and the `GENERATE FORM` button is clicked; the newly generated fields do not get current theme applied.
Reason:
In the property config, the function that gets called when the `GENERATE FORM` button is clicked, the function does not use the `childStylesheet` property present in the widget props.
Solution:
Passing of the `childStylesheet` to the appropriate function makes the theme config available to the schema parser to generate the new field with the theme config.
Fixes #14677 
Manual -
The steps to reproduce the issue was followed and made sure the theme gets applied correctly.
Jest -
The function that gets called when the `GENERATE FORM` is pressed is tested …
> fix: JSONForm - Generate Form button apply theme on new fields

- app/client/src/sagas/GitSyncSagas.ts
As of today, we can click sync-branches button and open merge tab multiple times in quick sessions, that causes api call to be made for every such interaction. This PR throttles those api calls.
Related: #14619 
Fixes #14638 
> chore: throttle git apis

- app/client/src/pages/Editor/gitSync/Tabs/Merge.tsx
Disable branch drop down until mergeStatus call returns.
> fix: disable branch dropdown until merge status returns

- app/client/src/ce/constants/messages.ts
- app/client/src/components/editorComponents/ActionCreator/Fields.tsx
- app/client/src/components/editorComponents/ActionCreator/index.tsx
- app/client/src/entities/DataTree/actionTriggers.ts
- app/client/src/sagas/ActionExecution/ActionExecutionSagas.ts
- app/client/src/sagas/ActionExecution/PostMessage.test.ts
- app/client/src/sagas/ActionExecution/PostMessageSaga.ts
- app/client/src/utils/autocomplete/EntityDefinitions.ts
- app/client/src/workers/Actions.test.ts
- app/client/src/workers/Actions.ts
This pull request exposes `window.postMessage()` as a global function in the Appsmith platform.
Post message safely enables cross-origin communication between window objects.
**Example use-case** - Appsmith page embedded within an iframe which communicates with the container website
**More on post message here** - https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage
**References used for this PR:**
1. Geolocation APIs - https://github.com/appsmithorg/appsmith/pull/9295
2. setInterval and clearInterval support - https://github.com/appsmithorg/appsmith/pull/8158
**Fixes** #7241 
**Screen recording** - 
https://user-images.githubusercontent.com/10229595/163362579-18b5a26c-5ae5-40da-a4ff-3335ee024da5.mov
Test plan 
- …
> feat: Add a field for the post message api exposure

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Switchgroup_spec.js
- app/client/src/workers/evaluationUtils.test.ts
- app/client/src/workers/evaluationUtils.ts
When translating diffs, if an array value changes to a string, all `MemberExpressions` of the array should be removed from the dependency map.
For example.
- Previous
```
ENTITY.options = [
{
label: "name",
value: {{name}}
},
{
label: "name",
value: {{name2}}
}
]
```
- Current (after switching to js mode)
```
ENTITY.options = "[
{
label: "name",
value: {{name}}
},
{
label: "name",
value: {{name2}}
}
]"
```
ENTITY.options[0] and ENTITY.options[1] (and their child nodes eg, ENTITY.options[0].value) should be removed from the dependencyMap
Fixes #14669 
Jest
> fix: prevent cyclic dependency when switching to js mode

- app/client/src/constants/ast.ts
- app/client/src/workers/DataTreeEvaluator/DataTreeEvaluator.ts
- app/client/src/workers/ast.test.ts
- app/client/src/workers/ast.ts
When JSObject function has code for variable declaration like below. In such cases, those properties also gets added as JSObject property which is not expected.  
```
newConfig.runners[0].issue.labels[edit_name.text] = {
conditions: [],
requires: 1,
testFunc: () => { 
console.log()
}
}
```
We will need to make sure to only parse JSobject's properties and not internal object property or function, this PR changes logic to do so.
- Change the parsing logic to track variableDeclarator and check for JSObject being declared and find its properties using the AST Node.
- As we are exactly checking JSobject Node we won't have any incorrect properties defined or any property missed.
Fixes https://github.com/appsmithorg/appsmith/issues/14836
> fix: JsObject parsing

- app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
Made cursor transparent when any datasource is selected in switch datasource dropdown and there is no searched input.
Cursor becomes visible when any input is typed.
Fixes #13746
Manually
> fix: made blinking cursor transparent for switch datasource

- app/client/src/widgets/CheckboxGroupWidget/component/index.tsx
- app/client/src/widgets/CheckboxGroupWidget/widget/index.tsx
> Checkbox-group widget breaking UI issue due to the inline and style alignment.
Fixes #14327  
> Steps you can reproduce:
> For Test 1:
- Drag and drop a checkbox group widget
- Add around 3 or 4 more options.
- Set the inline property to off, and label position to top or auto
- Set Style Alignment to either - End/Center/Around.
> For Test 2:
- Drag and drop a checkbox group widget
- Add around 3 or 4 more options.
- Set the inline property to on, and label position to top or auto
- Then stretch the bottom border of the widget.
> fix: checkbox-group widget breaking UI issue

- app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts
- app/client/cypress/support/Objects/CommonLocators.ts
- app/client/cypress/support/Pages/JSEditor.ts
- app/client/src/components/editorComponents/JSResponseView.tsx
- app/client/src/entities/AppsmithConsole/index.ts
- app/client/src/sagas/DebuggerSagas.ts
- app/client/src/sagas/EvaluationsSaga.ts
- app/client/src/sagas/JSPaneSagas.ts
- app/client/src/sagas/PostEvaluationSagas.ts
- app/client/src/workers/evaluate.ts
- app/client/src/workers/evaluation.worker.ts
This PR introduces js function execution errors in the debugger. These errors behave in the same way as those of Apis
They get removed when
Fixes #14503 
Cypress tests
> fix: show js function execution errors in debugger

- app/client/src/pages/Editor/gitSync/components/GitErrorPopup.tsx
During a refatoring, one of the location where the ConflictInfo component is invoked from was getting an empty string; that was making current app open up in new tab instead of git repo.
Fixes #14674 
> fix: pass remote url to ConflictInfo component

- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/PluginUtils.java
- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DataUtils.java
- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DatasourceUtils.java
- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/HeaderUtils.java
- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/HintMessageUtils.java
- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/InitUtils.java
- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/SmartSubstitutionUtils.java
- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/TriggerUtils.java
- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/URIUtils.java
- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ActionConfiguration.java
- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/PaginationType.java
- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/Property.java
- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/plugins/BasePlugin.java
- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/plugins/BaseRestApiPluginExecutor.java
- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/plugins/PluginExecutor.java
- app/server/appsmith-plugins/graphqlPlugin/src/main/java/com/external/plugins/GraphQLPlugin.java
- app/server/appsmith-plugins/graphqlPlugin/src/main/java/com/external/utils/GraphQLBodyUtils.java
- app/server/appsmith-plugins/graphqlPlugin/src/main/java/com/external/utils/GraphQLConstants.java
- app/server/appsmith-plugins/graphqlPlugin/src/main/java/com/external/utils/GraphQLHintMessageUtils.java
- app/server/appsmith-plugins/graphqlPlugin/src/main/java/com/external/utils/GraphQLPaginationUtils.java
- app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/helpers/DataUtilsTest.java
- app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCEImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PageLoadActionsUtilCEImpl.java
- This PR provides server-side support for pagination feature of GraphQL plugin. Two types of pagination is supported: limit offset based and cursor based. 
- In case a user has configured a query variable in both the query variables editor box and the pagination tab then a warning / hint message is returned to the client. Hint message is computed and returned at the time of query edit and at the time of query execution.
- Minor refactor: Some singleton pattern helper classes have been modified to allow for inheritance and extension. This was also suggested as a feedback on one of the earlier PRs. 
Fixes #13830 
- Manual
- TBD: JUnit TC will be added as part of a different PR.
> feature: GraphQL pagination server side support

- app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datasources/AuthenticatedApiDatasource_spec.js
- app/client/src/pages/Editor/DataSourceEditor/DatasourceSection.tsx
This prevents non-populated labels (labels with empty values) from showing up in the datasource view page
Before:
After:
Fixes #14181 
Manual, Cypress
> fix: Prevent non populated labels from showing up in datasource page

- app/client/src/pages/AppViewer/AppViewerHeader.tsx
Due to recent changes in app viewer header, we ended adding a UI bug where header is transparent in comment mode. This PR fixes that.
Fixes #15051
- Bug fix
> fix: Transparent bg on app viewer header in comment mode

- app/client/craco.common.config.js
- Added webpack socket url to `craco.common.config.js` to fix the hot reloading issue.
- Dev Config fix (non-breaking change which fixes an issue)
- Test the hot reloading by running the project change some files to see it working.
> fix: webpack hot reload issue

- app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/QueryPane/SwitchDatasource_spec.js
- app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
Switching Datasource on the query pane or api pane editor was showing non-similar datasources in dropdown. The list is now filtered using the `pluginId` of the current datasource with the other active datasources.
Fixes #13326
1. Create an application
2. Add multiple datasources (some similar, some different)
3. Create a query or api for one of the above datasources
4. When the editor opens, go to switch datasource dropdown and click on it
5. You will now see a list of only similar datasources (earlier all the active datasources were listed)
> fix: switch datasource option list contains similar ds

- app/client/src/pages/Editor/PropertyPane/PropertySection.tsx
- PropertyPane collapse animation was very slow. I have decreased the `transitionDuration` property to `20ms` I have not removed the animation totally because its causing layout shifts.
Fixes #13928
- Tested manually on the canvas the animation is fast now.
> fix: collapse animation changed transition duration.

- app/client/src/pages/Editor/gitSync/Tabs/Deploy.tsx
We were allowing empty commit messages, this PR doesn't allow that. We are also trimming message ourselves before sending it to backend service.
Fixes #15050 
> fix: accept non-empty commit messages

- app/client/src/pages/Settings/SettingsForm.tsx
- app/client/src/pages/Settings/components.tsx
> Add back button on individual authentication config pages
Fixes #15137 
> Checked if the back button is displayed on individual authentication config pages and on clicking it the page is taken back to authentication list page.
> chore: add back button on individual authentication config pages

- app/client/src/pages/AppViewer/BackToHomeButton.tsx
We used a button instead of an anchor in app home button in view mode. Due to this, we were not able to right-click on it. This PR replaces the button with a link
Fixes #15086
- Bug fix
> fix: Not able to right click on app home button in view mode

- app/client/src/pages/Applications/ApplicationCard.tsx
- Adds href to edit/launch buttons in application dashboard.
- Added preventDefault to stop full page reload and do client side navigation.
- Manual
> fix:  add anchor tag behaviours to edit/launch buttons in applications dasboard

- scripts/local_testing.sh
This script enables running any given branch as a fat container locally. Pre-requisites for running this script are that Docker be installed and running on your machine, and port 80 be open for use.
The script defaults to running on `release` branch if no argument is provided.
Usage:
```
./scripts/local_testing.sh chore/local-testing
```
Fixes #15078 
- Utility script
> chore: Added script to run Appsmith branches locally

- app/client/src/components/formControls/utils.test.ts
- app/client/src/components/formControls/utils.ts
The issue was caused whenever the value of current data was undefined. Added a default empty string in the get function if the value is undefined.
Fixes #15112 
- Unit tests
> fix: added default value for switch view type

- app/client/src/pages/Editor/gitSync/components/BranchList.tsx
During branch creation, a bit of text was clinging to each other. Put them as per the design.
Fixes #15014 
https://user-images.githubusercontent.com/1573771/179295053-d5940ba7-2a9f-41a9-965d-596bff69ac71.mov
> fix: break branch creation text, fix text casing

- app/client/src/pages/Editor/gitSync/Tabs/Deploy.tsx
- app/client/src/pages/Editor/gitSync/components/ConflictInfo.tsx
ConflictInfo was showing up along side discard button. Moved it to a row of its own.
Fixes #15113 
> fix: show conflict info properly

- app/client/src/pages/Editor/Explorer/Files/Submenu.tsx
- Shortcut key-up and key-down were not working because the list of file operations on ui were filtered out of the `sectionTitle` but on key actions it was being referred to which was adding in the offset for the current active item.
Fixes #15264
- Test A
- Test B
> fix: query creation via shortcut

- deploy/docker/utils/bin/estimate_billing.js
- deploy/docker/utils/bin/index.js
- deploy/docker/utils/bin/utils.js
- deploy/docker/utils/package-lock.json
- deploy/docker/utils/package.json
This PR adds to the `estimate_billing` option to the `appsmithctl` command. This will help existing users estimate their bill when they consider upgrading to the paid edition.
Usage: 
```
appsmithctl estimate_billing 
Options:
--sessionPrice    The price per active session. Defaults to 0.3 
--priceCap        The price cap for a user in a given month. Defaults to 15
```
A user can also run the command for various scenarios to determine the optimum capacity tier.
Manually
> chore: Adding the appsmithctl command to estimate the bill for an existing Appsmith user

- app/client/cypress/fixtures/tableV2NewDsl.json
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/TableV2/TableV2_Color_spec.js
- app/client/src/components/ads/DraggableList.tsx
- app/client/src/components/propertyControls/PrimaryColumnsControlV2.tsx
- app/client/src/sagas/WidgetAdditionSagas.ts
- app/client/src/widgets/TableWidgetV2/component/cellComponents/EditActionsCell.tsx
- app/client/src/widgets/TableWidgetV2/widget/propertyConfig/PanelConfig/Styles.ts
Fixes #15174
- Test A
- Test B
> fix: cell background for edit actions column in Table v2

- app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
- app/client/src/pages/Editor/DataSourceEditor/index.tsx
Earlier the API auth error redirects the url of the application with query params `response_status` and `display_message` which used to show error toast in edit mode only. But now the logic has been moved to view mode and removed from edit mode for plugin datasource `RestAPIDatasourceForm` only.
Fixes #12600 
Manually
> fix: api auth fails displays error on view mode now

- app/client/src/widgets/MapWidget/component/index.tsx
> Map widget is not working properly when I change the default value of lat and lang to string. so I changed the default value string to a number.
Fixes #9844 
- Drop a Map widget on canvas
- Set the default value to `{
"lat": "25.122",
"long": "50.132",
"title": "Location1"
}`
- Look the map is not showing any marker on the Map widget.
> fix: changed the marker(default) value string to number

- deploy/docker/utils/bin/estimate_billing.js
This PR fixes a bug where the `appsmithctl` command was not able to read the environment variable property for the MongoDB URL when estimating the billing. This renders the billing script unusable in Docker containers.
Manual
> chore: Fixing bug where the Mongo DB URL wasn't being picked up by the billing script

- deploy/docker/scripts/run-java.sh
It appears we see the following error when starting a fat container instance:
```
/opt/appsmith/run-java.sh: line 21: isset: command not found
```
Although it doesn't affect the functionality of Appsmith today, it may if the `NO_PROXY` is set to a non-empty value in the future. This PR fixes the error for good.
First seen at: https://app.intercom.com/a/apps/y10e7138/inbox/inbox/conversation/164629100136239#part_id=comment-164629100136239-15602739687
> fix: Fix `isset` command not found

- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ApplicationForkingServiceCEImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ApplicationForkingServiceTests.java
This PR temporarily fixes the ApplicationForkingServiceTests failing on CI. Since `applicationForkingService.forkApplicationToWorkspace()` is long running process some of the occurrences of this is converted to synchronous `block()` to avoid test failures.
- Tests on local
> fix: Converted ApplicationForkingServiceTests to synchronous

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug15283_spec.ts
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Linting/ErrorReporting_spec.ts
- app/client/src/workers/ast.ts
- app/client/yarn.lock
Previous version of the astring library doesn't preserve parenthesis when transforming AST to JS Code. This led to syntax error when null coalesce and logical expressions are used together.
The latest version of astring library fixes this.
Fixes #15283 
Test plan
> chore: Upgrade astring version from v1.7.5 to v1.8.3

- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCEImpl.java
Also introduced `dsName` which is the flattened location for `datasource.name`. Have not removed the older property in this PR.
The properties will now look like:
```
{
"actionCreated": "2022-07-28T09:39:16.558Z",
"actionId": "62e259443d32b3767ffbd3d5",
"appId": "62b18a27cb9b083be9d9e3f2",
"appMode": "edit",
"appName": "My first application",
"datasource": {
"name": "Movies"
},
"dsCreatedAt": "2022-07-18T07:33:58.461Z",
"dsId": "62d50ce64cd13c70bf5db4ae",
"dsIsMock": true,
"dsIsTemplate": "",
"dsName": "Movies",
"instanceId": "62b189f7cb9b083be9d9e34d",
"isExampleApp": false,
"isSuccessfulExecution": true,
"name": "Query1",
"orgId": "62b18a27cb9b083be9d9e3f1",
"originService": "appsmith-server",
"pageId": "62b18a28cb9b083be9d9e3f5",
"pageName": "Page1",
"pluginName": "MongoDB",
"request": …
```
> chore: Added isMock and isTemplate to action execution analytics

- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/FilterDataServiceCE.java
- app/server/appsmith-interfaces/src/test/java/com/appsmith/external/services/FilterDataServiceTest.java
The issue that this PR is attached to suffers from two problems. 
1. When the data type in the first row of the data is a string, and a subsequent row sends an integer type, we were not displaying the integer type data because of type mismatch
2. When the data type in the first row of the data is an integer, and a subsequent row sends a string type, we were not displaying the string type data because of type mismatch
The first issue is a matter of raising the type in its hierarchy, which is a compatible change. This PR introduces this hierarchy for our types to fix this issue. However, this is a very hacky fix to get the user out of this state of unusability. Ideally, we would want to rely on a single known type for that column.
The second issue is not handled by this PR at all. This is …
> fix: Added type static hierarchy to allow compatible types

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/JSONFormWidget/JSONForm_FieldProperties_spec.js
- app/client/src/components/propertyControls/JSONFormComputeControl.tsx
When a Regex property is entered a value like `^\d+$`. Under the hood, the value for the JSONForm is stored in this format
```{{sourceData, formData, fieldState) => (`^\d+$`))(JSONForm1.sourceData, JSONForm1.formData, JSONForm1.fieldState)}}```
As this is a binding, it is evaluated and due to evaluation the `\d` is treated as an escape sequence and the `\` is removed.
So the solution is to not use the default binding template of the JSONForm when the value that is being entered in the property pane is not a dynamic value. In this way the regex will be treated as a plain text and won't get evaluated
If a user wants to use a regex in a binding the `\` has to be escaped i.e `{{^\\d+$}}`
Fixes #14109 
1 cypress test is added to an existing …
> fix: JSONForm input field REGEX validation

- app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitUtils.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/GitUtilsTest.java
> Update the regex which validates the ssh url to include a few cases as listed in the issue.
Fixes [# (issue)](https://github.com/appsmithorg/appsmith/issues/15432)
- Locally
- JUnit
> fix: ssh url validation to include a few cases where `-` is present in the url

- app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/SegmentConfig.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/UserSignupCEImpl.java
The Installation setup complete event is not getting sent _sometimes_, and it's behavior looks very much like there's some race condition somewhere. I'm proposing this change towards two goals.
One, currently, we send the event after the user-entered data is saved to the DB. But, there's no actual dependency, no point to waiting on that for sending the event. The actual user itself, is already created and signed up. So, one change is that we don't wait for the DB update to be applied. I'm also changing `.onSuccess` to `.map`, hoping that might make a difference.
Two, make a debug log entry to see if it is our callback function that's not getting invoked, or if Segment's API isn't doing it's job, when the event is not sent.
This PR also fixes formatting of Segment error messages.
> fix: Fix potential delay in sending setup completion

- app/server/appsmith-plugins/graphqlPlugin/src/main/java/com/external/plugins/GraphQLPlugin.java
- fix self cyclic dep error in GraphQL plugin
- self referencing data path concept was introduced in one of the earlier commits. The idea is to ignore any dynamic binding in these paths when computing on page load actions / cyclic dep errors.
Fixes #15529 
- Manual
> fix: fix self cyclic dep error in GraphQL plugin

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/TableV2/columnTypes/menubutton_spec.js
- app/client/src/widgets/TableWidgetV2/component/cellComponents/MenuButtonCell.tsx
- app/client/src/widgets/TableWidgetV2/component/cellComponents/menuButtonTableComponent.tsx
- app/client/src/widgets/TableWidgetV2/widget/index.tsx
- app/client/src/widgets/TableWidgetV2/widget/propertyConfig/PanelConfig/ButtonProperties.ts
- app/client/src/widgets/TableWidgetV2/widget/propertyConfig/PanelConfig/MenuItems.ts
Menu items now have access to currentRow in backgroundColor, textColor, Disabled and Visible properties.
Fixes #13808
Fixes #12359
4 new cases have been written to check the bindings in said properties.
> fix: provide access to currentRow in table widget menubutton items

- app/client/src/pages/Editor/gitSync/utils.test.ts
- app/client/src/pages/Editor/gitSync/utils.ts
Fixes issue by allowing `-` in subdomain/domain.
Fixes #15432 
> fix: Improve ssh url checking for git import

- app/client/src/ce/pages/AdminSettings/config/authentication/AuthPage.tsx
- app/client/src/ce/pages/AdminSettings/index.tsx
- app/client/src/utils/hooks/useOnUpgrade.ts
We were booting intercom only on auth pages of admin settings, this PR boots the intercom on all admin settings.
Fixes #15570
- Bug fix
- by QA manually
> fix: Delay in display of Intercom pop up when user tries to upgrade the Watermark property

- app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
- app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java
- Currently some cases have been seen where a Mongo plugin query fails with error message: `state should be: server session pool is open`. 
- As per my investigation, this occurs because the connection pool at this point has already been closed. Hence running any query against the closed connection pool results in a `IllegalStateException`. 
- At this point it is not known what is causing the connection pool to close. 
- This PR introduces a change to handle the `IllegalConnectionException` as a `StaleConnectionException` which would result in the connection pool being re-created. 
- Note: It was not possible to check for closed connection before executing the query because the `MongoClient` object does not seem to expose any `isClosed` kind of method.  
Fixes #15548
- Bug fix …
> fix: fix Mongo plugin query execution failure 

- deploy/docker/templates/docker.env.sh
- deploy/docker/templates/nginx/nginx-app-http.conf.template.sh
- deploy/docker/templates/nginx/nginx-app-https.conf.template.sh
The control to configure what domains are allowed to embed Appsmith apps is still available, but the default of not allowing anything except for `'self'` is changed to allow everything.
While this is convenient, we encourage our users to configure their frame ancestors to limit what domains can embed their Appsmith apps.
> fix: Change to allow all domains to embed Appsmith apps

- app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceContextServiceImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceContextServiceTest.java
We were not refreshing the datasourceContext cache in case of stale connections, this PR fixes that and tests it via `UpdatableConnection` types which would be the most frequent use case that saw such failures. 
Reproduction on release:
1. Create an Authorization Code OAuth2 enabled REST API datasource
2. Go through authentication, create an API and ensure that it works
3. Create a new workspace, and fork this app into that workspace
4. Try to authorize the datasource in the new workspace and re-run the API. This will not work on release. It should work on this branch,
Fixes #15597 
-JUnit test
> fix: Do not cache updatable connections

- app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts
- app/client/cypress/support/Pages/JSEditor.ts
- app/client/cypress/support/commands.js
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceTest.java
Sync JS functions are not meant to ever run on page load automatically, since we have disabled the ability for users to set them to run on page load. This fix resets the relevant props on each update, so that the fields are not reused from when the function used to be recognized as async.
[Slack thread](https://theappsmith.slack.com/archives/C02K0SZQ7V3/p1658734579510539)
Fixes #13197 
- JUnit tested
- Cypress tested
> fix: Reset sync function fields on each update

- app/server/appsmith-server/src/main/resources/system-themes.json
This PR - adds `accentColor` and `fontFamily`properties to the chart widget's config for all the themes.
Fixes #10974 
N/A
> feat: added accentColor and fontFamily to the theme config chartwidget

- app/client/src/api/TemplatesApi.ts
- app/client/src/pages/Templates/TemplateView.tsx
- app/client/src/pages/Templates/index.tsx
- app/client/src/sagas/TemplatesSagas.ts
- app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ApplicationTemplateControllerCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationTemplateServiceCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationTemplateServiceCEImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
Add datasource's that are not configured to the template API response. This is to ensure that for SAAS templates, user is prompted the with reconnect datasource modal. 
Frontend changes involves adding reconnect modal to be shown in the template list page and in the template detailed view page. The deploy preview won't have templates fork working as it requires backend changes to be merged to release.
https://user-images.githubusercontent.com/67054171/182368698-53de623d-4f9d-4035-a47b-52e205619d89.mov
Fixes #15463
- Locally
> feat: Added unconfigured datasources to the template API response

- deploy/helm/README.md
- deploy/helm/templates/statefulset.yaml
- deploy/helm/values.yaml
Some services such as istio need labels to identify pods. This will allow those services to be configurable.
Fixes #15351 
New feature (non-breaking change which adds functionality)
Using this in our production cluster
> feat: Add pod labels to allow for selector labels across different configs

- deploy/helm/templates/statefulset.yaml
This is so that the `livenessProbe` doesn't aggressively
restart the pod before the Appsmith container is live.
Fixes #10778.
> fix: Add `startupProbe` to Appsmith pods

- app/client/src/workers/DataTreeEvaluator/test.ts
- app/client/src/workers/DependencyMap/index.ts
This PR simply re-orders the update of the triggerfieldDependencyMap. Deleted trigger fields are deleted from the map after updating their references. So that in the case where there is a self-referencing (eg, button1.onClick depending on button1), we don't try to update deleted entries.
Fixes #15695 
Jest
> fix: Correctly update trigger field dependency map

- app/client/src/sagas/WebsocketSagas/WebsocketSagas.ts
When Appsmith is running in a cluster, the websocket connections from client to RTS fail to establish. Here's what happens:
We don't set `transports` explicitly, when connecting to RTS, so it takes the default of `["polling", "websocket"]`.
So, socket.io first tries to connect to RTS with polling, with the intention to upgrade to a websocket later. However, the polling transport type doesn't work, when RTS is running as a cluster.
The issue we are seeing here, is exactly as described in this SO post (https://stackoverflow.com/a/45063176/151048), copied here to preserve:
<blockquote markdown>
For socket.io v2.0.3 (js client),when you use socket.io on client side the client socket.io makes some network calls as explained:
1. When io.connect() is called, the  socket.io library makes a call …
> fix: Disable polling transport for RTS

- app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
- app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
Fixes issue for checking for invalid hosts even when there are redirects in the Rest API plugin.
- Junit test
> fix: Adding a check for invalid hosts on redirects as well

- app/server/appsmith-plugins/elasticSearchPlugin/src/main/java/com/external/plugins/ElasticSearchPlugin.java
- app/server/appsmith-plugins/elasticSearchPlugin/src/test/java/com/external/plugins/ElasticSearchPluginTest.java
This PR fixes an issue where a potentially malicious user can connect to disallowed hosts from the Elasticsearch plugin within Appsmith. This is because Elasticsearch client SDK is a HTTP interface underneath the hood. 
- Junits for the following:
- create datasource with disallowed host
- validate datasource with disallowed host
- test datasource with disallowed host
> fix: Adding checks to prevent disallowed hosts from connecting via Elasticsearch plugin

- app/server/appsmith-plugins/graphqlPlugin/pom.xml
- app/server/appsmith-server/pom.xml
- Currently, the graphql branch code builds and runs fine on the terminal but on IntelliJ it throws the following runtime error: `java.lang.NoClassDefFoundError: graphql/parser/InvalidSyntaxException`. To overcome this error I tried to figure out any dependency conflicts or class path related issues but couldn't come up with any way to resolve it. Finally as a workaround I have moved the dependency to the `pom.xml` file of the main API server module while keeping the dependency in the `GraphQLPlugin`'s `pom.xml` under `provided` scope. This has resolved the issue for now. This fix may not be the most accurate but is not expected to cause any harm. 
- Created a new issue to track its proper fix: https://github.com/appsmithorg/appsmith/issues/15718
- Update package version.
Fixes #13145 
- …
> fix: fix class def not found error

- app/client/src/widgets/InputWidgetV2/widget/index.tsx
- app/client/src/widgets/JSONFormWidget/widget/propertyConfig/properties/input.ts
- app/client/src/widgets/constants.ts
Added JS toggle button for Icon property of Input widget and JSON Form widget's text, email, number and password input fields so that icon can be dynamically configured for these inputs.
Fixes #9614
- Manual
> feat: JS toggle for icon property of Inputs

- app/client/src/widgets/InputWidgetV2/widget/index.tsx
- app/client/src/widgets/JSONFormWidget/widget/propertyConfig/properties/input.ts
Fix a bug where the users are unable to clear icon in an Input widget.
Fixes #16006
- Manual
> fix: unable to remove Icon on Input widget

- app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
- Use `Workspace` class during database migration instead of `Organization` class since the `Organization` class has been deprecated now. 
Fixes #15975 
- Manual
- Looks like any automated test may not be possible here.
> fix: fix graphql plugin installation in existing workspaces

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug16047_spec.ts
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Linting/BasicLint_spec.ts
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Linting/ErrorReporting_spec.ts
- app/client/src/pages/Editor/JSEditor/index.tsx
Shows page not found URL for invalid JSEditor link
Fixes #16047 
> fix: Show invalid page UI for invalid jsobject page

- app/client/src/pages/Editor/JSEditor/utils.ts
For most browsers the default type of button is `submit`, this could cause the page to reload when clicked. Setting button type to `button`, prevents this behavior.
Fixes #15502
[[Manual](https://github.com/appsmithorg/TestSmith/issues/2025)](https://github.com/appsmithorg/TestSmith/issues/2025)
> fix: Set button type to prevent reload of page when clicked

- app/client/src/widgets/ListWidget/widget/index.tsx
Avoid re-rendering the list widget children in the List widget when making Canvas operations
Fixes #11620
- Test A
- Test B
> fix: prevent children rerender in listwidget

- app/server/appsmith-plugins/graphqlPlugin/src/main/java/com/external/plugins/GraphQLPlugin.java
- app/server/appsmith-plugins/graphqlPlugin/src/main/java/com/external/utils/GraphQLPaginationUtils.java
- When a variable is defined in both the pagination section and the query variables section then a warning message is shown to the user. Currently, this warning message is displayed twice on the screen because it is returned back by the API server as part of two different responses i.e. as a response to the update endpoint call and as a response to the execute endpoint call. This PR removes the warning message from the execute response so that it gets displayed only at one place. 
Fixes #16099 
- Manual
- JUnit TC will be added as part of another issue: #12388
> fix: GraphQL plugin: remove duplicate warning message from action execution response

- app/client/package.json
Though we only use msw in `development` environment, when we run `yarn build` the `public/mockServiceWorker.js` still gets bundled and will be an unused file in build. We don't want that, so added a `postbuild` script which removes the file from the build folder post build.
Fixes #14395
- Manual
> chore: remove mockServiceWorker.js from build since its not needed in prod

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug15372_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug15372_spec.ts
- app/client/src/sagas/EvaluationsSaga.ts
The catch block was not working for an async function in safari/firefox. On further debugging we found that different browsers were sending different call stacks to the response payload, making it fail on firefox and safari. We are only extracting the error message now to keep it consistent across browsers.
Screen recording (firefox) - 
https://user-images.githubusercontent.com/10229595/180390210-bb578a5a-f930-4dbe-aaff-6fafbd536dd9.mov
Fixes #15372 
- Manual
- Cypress tests
> fix: catch block not working in firefox and safari for async functions

- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/constants/GitConstants.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/constants/GitDefaultCommitMessage.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> Refactor git constants. The reason is that when we override the implementation for git flow in ee code base these can be reused.
- Locally
> chore: refactor git constants

- .github/workflows/client-build.yml
- .github/workflows/github-release.yml
- .github/workflows/integration-tests-command.yml
- .github/workflows/test-build-docker-image.yml
- app/client/src/ce/configs/index.ts
- app/client/src/ce/configs/types.ts
- app/client/src/ce/constants/messages.ts
- app/client/src/components/designSystems/appsmith/help/DocumentationSearch.tsx
- app/client/src/pages/Home/LeftPaneBottomSection.tsx
- app/client/src/pages/common/MobileSidebar.tsx
This PR adds the string `Community` along with the Appsmith version. This will help users identify the type of instance that they are running.
Manually
> fix: Display community edition along with version

- .github/workflows/build-rts.yml
- .github/workflows/integration-tests-command.yml
- .github/workflows/server.yml
- .github/workflows/test-build-docker-image.yml
This PR moves the server compilation for in standalone workflow, `ok-to-test` and `test-build-push` workflows to Buildjet. This is an experiment to see if we can prevent jobs from being queued in Github and also if there is greater reliability when server JUnit tests run on self-hosted runners via Buildjet.
Also, cleaning up some CI workflows to remove references to release-frozen branch.
- Tech debt
- CI run in this PR
> ci: Moving server builds to Buildjet to confirm if it's faster and more reliable

- app/client/src/ce/constants/messages.ts
- app/client/src/components/designSystems/appsmith/help/DocumentationSearch.tsx
- app/client/src/pages/Home/LeftPaneBottomSection.tsx
- app/client/src/pages/common/MobileSidebar.tsx
The edition string will only be shown for self hosted instances. This change is being done because Appsmith Cloud doesn't yet support Business edition yet.
Manual
> chore: Removing the Community/Business edition display for cloud hosting. 

- app/client/src/pages/Applications/index.tsx
- app/client/src/pages/common/PageWrapper.tsx
> Hiding the add new button in new workspace created if user has app viewer access
Fixes #9041 
- Logged in with User A and created a new workspace with no applications in it.
- Shared this Organization with User B with App viewer permission only.
- Logged in with User B and verify the workspace doesn't show any add new button inside or next to the share button.
> fix: Hiding the add new button in new workspace created if user has app viewer access

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/CurrencyInput/CurrencyInput_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/PhoneInput/Phone_input_spec.js
- app/client/package.json
- app/client/src/components/propertyControls/DropDownControl.tsx
- app/client/yarn.lock
- PropertyPane Dropdowns for the `currencyInput` & `phoneInput` widgets close on when user types in space or if no result match.
Fixes #16369 
Fixes #16374
- Tested Manually on the canvas.
> fix: Property pane dropdown for currency and phone input widgets.

- app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Application.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java
Today, every public app has its own permission group which provides access to anonymous user. When such an app is exported, the permission group must not be exported as well to ensure that only the configuration (and not the access) is exported.
> fix: For a public app, do not export the default permission group

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/JSParse_Spec.ts
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Multiselect/Multi_Select_Tree_spec.js
- app/client/src/widgets/MultiSelectTreeWidget/widget/derived.js
- app/client/src/widgets/MultiSelectTreeWidget/widget/derived.test.ts
- app/client/src/widgets/MultiSelectTreeWidget/widget/index.tsx
- app/client/src/widgets/MultiSelectTreeWidget/widget/parseDerivedProperties.ts
- app/client/src/widgets/SingleSelectTreeWidget/component/index.tsx
- app/client/src/widgets/SingleSelectTreeWidget/widget/derived.js
- app/client/src/widgets/SingleSelectTreeWidget/widget/derived.test.ts
- app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
- app/client/src/widgets/SingleSelectTreeWidget/widget/parseDerivedProperties.ts
- app/client/src/widgets/WidgetUtils.ts
This Fixes issues with Both Single Tree Select and Multi Tree Select.
- Clearing Values
- `SelectedOptionLabels` for both widgets
Fixes #16367
Fixes #16365
Fixes #15466
- Unit Test
> fix: TreeWidgets issues

- app/client/cypress/fixtures/tableV2ColumnOrderDsl.json
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/TableV2/TableV2_Column_Order_spec.js
- app/client/cypress/locators/commonlocators.json
- app/client/src/widgets/TableWidgetV2/widget/index.tsx
- Table V2 will now maintain the original order of the columns even if some of the columns returned change
- The new columns will show up at the end
Fixes #13979 
> fix: Table reverts column positions on sorting if columns returned differ

- app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/QueryPane/GoogleSheetsQuery_spec.js
- app/client/cypress/locators/DatasourcesEditor.json
- app/server/appsmith-plugins/googleSheetsPlugin/src/main/resources/editor/insert.json
When creating insert queries for google sheets datasource, the rowObject placeholder text was not accurate. In the placeholder text of rowObject, the keys in the placeholder text object did not have any quotes around them, so if user passes the rowObject in this format without any quotes around the keys then "Plugin Failed to parse JSON" issue is thrown on running such query.
Fixes #16391
- Cypress Test
> fix: gsheets insert command placeholder issue fixed

- app/server/appsmith-server/src/main/resources/application.properties
To make the server log timestamp agnostic of the individual instance set up, we've configured all logs to always show timestamp as per UTC.
> chore: Converted server log timestamps to UTC

- app/client/src/pages/Applications/ApplicationCard.tsx
Chrome 105 gives precedence for the width and height of an element set by css over that set by an svg. 
Fixes https://github.com/appsmithorg/appsmith/issues/16470
On local on Chrome 105
> fix: large app icons

- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DatasourceUtils.java
- app/server/appsmith-plugins/graphqlPlugin/pom.xml
- app/server/appsmith-plugins/graphqlPlugin/src/main/java/com/external/utils/GraphQLConstants.java
- app/server/appsmith-plugins/graphqlPlugin/src/main/java/com/external/utils/GraphQLPaginationUtils.java
- app/server/appsmith-plugins/graphqlPlugin/src/test/java/com/external/plugins/GraphQLPluginTest.java
- Handle the use case where the cursor value is `undefined` during the first run. This is expected because the cursor value is supposed to be fetched using a query run. Since during the first query run (no query has been run before this) no data is available the cursor value is `undefined` for which the client returns `null` string back to the API server. The API server handles this case by skipping to add the `cursor` key value pair as variables when the value is `null` string which is interpreted by the GraphQL server as a simple non paginated query.
Fixes #16477 
- JUnit TC
- Manual
> GraphQL: handle case where cursor value is null

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/Bind_API_with_List_Widget_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/Bind_TableV2Widget_selectedRow_Input_widget_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/Bind_TableWidget_selectedRow_Input_widget_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/Binding_TableV2_Widget_DefaultSearch_Input_widget_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/Binding_Table_Widget_DefaultSearch_Input_widget_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/Table_Property_ToggleJs_With_Binding_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/Widgets_Default_data_validation_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ExplorerTests/Entity_Explorer_DragAndDropWidget_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Git/GitDiscardChange/DiscardChanges_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/DuplicateApplication_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/PropertyPane/PropertyPaneJsEnabledVisible_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ThemingTests/Theme_FormWidget_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Button/ButtonGroup_MenuButton_Width_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Chart/Custom_Chart_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Form/FormWidget_With_RichTextEditor_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/List/List4_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Migration_Spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Others/MapChart_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Switch/SwitchGroup2_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/TableV2/pagesize_spec.js
- app/client/cypress/support/ApiCommands.js
- app/client/cypress/support/commands.js
- app/client/cypress/support/widgetCommands.js
This PR fixes linting errors thrown by eslint in the Cypress code base. Ideally, we shouldn't have any such linting errors.
- Refactoring change
- Since there is no change in actual logic, relying on CI to ensure that all the tests pass.
> chore: Fixing lint errors in the Cypress code base

- app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
Update bad theme migration should only run once.
> chore: update-bad-theme should only run once.

- app/client/src/serviceWorker.js
After this change, we will actively avoid index.html from SW cache. It will always fetch it from the network instead
- Test A
- Test B
> fix: Never cache index.html via Service Worker

- app/client/src/widgets/ListWidgetV2/index.ts
- app/client/src/widgets/ListWidgetV2/widget/index.tsx
- app/client/src/widgets/MetaWidgetContextProvider.tsx
Meta widget's APIs such as `updateWidgetProperty`/`executeAction` would get called on the meta widgets properties. Ideally any sort of such updates should be propagated to the actual widgets so that it gets cloned to the reset of the meta widgets present in different rows of the list widget.
In order to override, the EditorContext's values are overridden and that in turn would modify the behaviour in the `BaseWidget` of every meta widget.
The `MetaWidgetContextProvider` can be used in any widget to override any child widgets API. Only those methods that are passed to `MetaWidgetContextProvider` are overridden the rest stay the same as the original API methods.
Fixes #15778 
> feat: List v2 POC - Override base widgets default API

- app/server/appsmith-plugins/googleSheetsPlugin/pom.xml
- app/server/appsmith-plugins/saasPlugin/pom.xml
Due to mismatched dependency version of `spring-webflux`, the Saas and the Google Sheets plugins fail to make any external HTTP requests. This PR fixes that.
This issue was introduced in #14427, and has not been promoted to `master` branch yet.
> fix: Fix LinkageError in Saas & GSheets plugins

- .github/workflows/ok-to-test.yml
The expression was treated as a string and always evaluated as true.
> ci: Update ok-to-test.yml to run only on pull request comments

- app/client/src/components/editorComponents/CodeEditor/styledComponents.ts
This PR fixes the border bottom of the code editor component not being highlighted when it is in focus using the Keyboard tab key.
Fixes #15696
Manual Test.
> fix: Fix border bottom highlight issue

- .github/workflows/perf-test.yml
- .github/workflows/test-build-docker-image.yml
The depot docker step wasn't initialized. This was causing Docker builds to fail.
- Relying on CI
> ci: Fixing the package step for test-build-docker workflow

- app/client/src/widgets/TableWidgetV2/widget/propertyConfig/contentConfig.ts
To resolve this issue I swapped out two properties of this object, `placeholderText` and `defaultValue`, to change the placeholder zero for an actual 0 character.
Fixes #15810
I followed these steps:
1. Start your development environment and login
2. Create a new app
3. D&D a table widget onto the canvas and select it
4. Check in the properties pane that the `Default Selected Row` property contains a zero character
> fix: Table widget default selected row should display value "0" instead of a watermark

- .github/workflows/test-build-docker-image.yml
It looks like this was a typo carried over from merging in https://github.com/appsmithorg/appsmith/pull/16658. This allows the arg to actually be passed into the action going forward.
cc: @trishaanand @mohanarpit
> ci: Fix `build_args` to be `build-args` for Depot builds

- deploy/docker/entrypoint.sh
Updated `entrypoint.sh` to use a mongo shell eval command instead of` appsmithctl check-replica-set` for **external mongo db**.
Partially fixes(Workaround): [16104](https://github.com/appsmithorg/appsmith/issues/16104)
> fix: entrypoint.sh external mongo replica set check

- .github/workflows/test-build-docker-image.yml
Fixes the reference to `github.sha` in the Docker build workflows.
cc @mohanarpit
> fix(ci): fix tag reference to `github.sha`

- app/client/src/components/designSystems/appsmith/PositionedContainer.tsx
- app/client/src/components/editorComponents/DraggableComponent.tsx
- app/client/src/components/editorComponents/ResizableComponent.tsx
- app/client/src/components/editorComponents/SnipeableComponent.tsx
- app/client/src/selectors/ui.tsx
- app/client/src/selectors/widgetReflowSelectors.tsx
- app/client/src/selectors/widgetSelectors.ts
- app/client/src/utils/hooks/useClickToSelectWidget.tsx
- app/client/src/utils/hooks/usePositionedContainerZIndex.ts
- app/client/src/widgets/BaseWidget.tsx
Fixes the wasted widget layer renders in edit mode. Makes the hover on widget 4x faster, and drag and drop, resizing smoother.
Fixes #12949 
This PR optimizes dragging and resizing to some extent, reaming will be taken up as a separate issue #16610
No breaking performance improvement
Profiling before and after.
> perf: Widget layer optimization

- .github/workflows/client-build.yml
- .github/workflows/rts-build.yml
- .github/workflows/server-build.yml
The problem was being caused by reusable modules taking the same job id
> ci: Fixing the caches for server,client and rts build

- deploy/docker/entrypoint.sh
docker-compose used 
entrypoint.sh ---> commited entrypoint_script.
APPSMITH_MONGODB_URI --> the release mongo_db url
```
version: "3"
services:
appsmith:
image: index.docker.io/appsmith/appsmith-ee@sha256:652eaee6e60fe8e057da3045bd72050442a8ecb0eeb48dc3ef0f5c92ba2f6c7d
container_name: appsmith
ports:
- "80:80"
- "443:443"
volumes:
- ./stacks:/appsmith-stacks
- ./entrypoint.sh:/opt/appsmith/entrypoint.sh
environment:
APPSMITH_MONGODB_URI: mongodb+srv://appsmithadmin:mL43Druzp2O9DufEMK0V@mobtools-test-cluster-swrsq.mongodb.net/mobtools?retryWrites=true&minPoolSize=1&maxPoolSize=10&maxIdleTimeMS=900000&authSource=admin
restart: unless-stopped
```
output of docker-compose up :
```
Attaching to appsmith
^[[36mappsmith    |^[[0m Initialize .env file
^[[36mappsmith    |^[[0m Load environment …
```
> fix: docker entrypoint script to check mongo replicaset

- app/client/src/components/editorComponents/DynamicHeightOverlay.tsx
hiding the overlay while dragging the widget
> fix: hiding the overlay while dragging the widget

- app/client/start-https.sh
When the system NGINX conf has a `pid` directive, the additional `pid` directive in the value to `-g` argument causes a `duplicate pid directive` error.
In this fix, we _always_ specify a conf file for `nginx`, and never let it have the system config. This way, no matter what the system config contains or not contains, the behaviour of this script shouldn't be influenced by it.
> fix: Fix NGINX in start-https clashing with system conf

- app/client/start-https.sh
The location of the default NGINX config is not garanteed to be the same on all machines. So in this PR, we change from a hard-coded path to `mime.types`, and compute it at runtime.
> Fix hard-coded mime.types location

- app/server/appsmith-interfaces/pom.xml
- app/server/pom.xml
The `interfaces` module has h2 version set at 2.1.210, but what all the plugins are actually using is 1.4.200.
This is because `org.springframework.boot:spring-boot-dependencies:2.6.5` sets `h2.version` as `1.4.200`, overriding what the `interfaces` module lists.
The sources for this conclusion are, one, the output of `mvn dependency:tree -Dincludes=com.h2database`, copied below. This clearly shows that while the `interfaces` module loads version `2.1.210`, all plugins load `1.4.200`.
```
...
[INFO] ----------------------< com.appsmith:integrated >-----------------------
[INFO] Building Integrated Appsmith 1.0-SNAPSHOT                         [1/25]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:3.1.2:tree …
```
> fix: Fix h2 version mismatch

- deploy/docker/entrypoint.sh
- deploy/docker/templates/supervisord/mongodb.conf
Docker for Windows, is documented to not support Linux style file permissions in container volumes. So, `chmod 600` on the MongoDB key file does't seem to do anything, and we still see the key file at 755.
However, WSL2 is itself an Ubuntu environment, and so supports chmod style file permissions at any path that's not mounted as a volume to the Windows host.
To fix this, in this PR, we copy the key file from the volume path to a location that's not mounted as a volume (`/mongodb-key`), and set appropriate permissions on that file.
> fix: Fix key file permissions error on Windows

- app/rts/build.sh
- app/rts/src/services/AstService.ts
- Due to change in the function name in the AST shared module, rts build was not getting completed successfully which was giving errors for the file aliasing.
- Copy of node_modules was not working on the mac machine due to `-L` flag, so added a `Or` condition to run the same command with `-r` only.
Fixes #16875
- Test A
- Test B
> fix: build error due to fn name change, copy node_modules on mac error

- app/server/appsmith-plugins/googleSheetsPlugin/src/main/resources/editor/fetch_many.json
We weren't sending table heading row index information along with the sheet url and name parameters to fetch the columns in Google Sheets integration. This PR starts to send this information along. As a result, every time the table heading row index value changes, we can expect the projection field to get updated.
Fixes #16868 
- Manually tested on local, no possibility of unit tests or integration tests for GSheets.
> fix: Make projection fields refresh when table heading row index selection is updated

- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/Param.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/NewActionServiceCEImplTest.java
Parts in multipart requests can appear in any order. Earlier we assumed that the parts should maintain a strict order and that assumption leads us to this infrequent NPE.
Parts in multipart requests can appear in any order. In order to avoid NPE, the original name of the parameters along with the client-side data type are set here as it's guaranteed at this point that the part having the `parameterMap` is already collected.
Fixes #16722 
- Manually through Appsmith App and the Postman client
> fix: Fix NPE in execute API (#16722)

- app/client/src/widgets/TextWidget/widget/index.tsx
Hiding the Overflow options in the Text widget if Auto Height is enabled.
> fix: auto height text widget hide overflow

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug9334_Spec.ts
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/InvalidURL_Spec.ts
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/MultipleOnPageLoadConfirmation_Spec.ts
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Linting/BasicLint_spec.ts
- app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OnLoadTests/JSOnLoad1_Spec.ts
- app/client/src/ce/constants/messages.ts
- app/client/src/sagas/ActionExecution/PluginActionSaga.ts
- app/client/src/workers/DataTreeEvaluator/index.ts
Previously, the UserCancelledActionExecutionError was getting thrown after user cancels an onpageload js execution, this was bubbling up to the parent catch block, causing all other onPageLoad executions to fail.
Fixes #15340 
Cypress
**Test Plan**
Manual -
> fix: cancelled execution causing multiple on page load execution failures

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/TableV2/TableV2Filter2_Spec.ts
- app/client/src/widgets/TableWidgetV2/component/CascadeFields.tsx
- app/client/src/widgets/TableWidgetV2/component/TableFilterPaneContent.tsx
**Bug 12638**
After adding 3 filters to a table and removing the second filter, the current second filter `value` was showing the old second filter `value`. This was happening because we were not passing unique keys to the filters while rendering the filters list.
Hence added a unique key to filter in filters list.
**Bug 12642**
After adding 3 filters and then changing the operator of second filter from `AND` to `OR` or vice versa, then removing the **first** filter caused the operator to go back to the previous value.
This was happening because we are adding the `OR` operator to a filter by default. When we are changing the operator from the dropdown the value gets updated to the second filter only in the state. All other filters persisted with the previous operator value.
Hence this has …
> fix: Table filter issues

- .github/workflows/github-release.yml
The if condition was erroneous in the github release workflow which caused the Docker images to built for a specific tag but not be pushed as the `latest` tag. 
- Personal repository
> ci: Fixing the github release workflow to push the latest tags for Docker images

- app/server/appsmith-plugins/elasticSearchPlugin/src/main/resources/form.json
The current error message gives no clue that I need to add a `http://` at the start.
> chore: Fix host error message in Elasticsearch config

- deploy/docker/templates/nginx/nginx-app-http.conf.template.sh
- deploy/docker/templates/nginx/nginx-app-https.conf.template.sh
This is a fix towards the chunk loading errors problem. When a URL to an asset responds with 404, no matter it's content, it shouldn't be cached.
Slack conversation: <https://theappsmith.slack.com/archives/CGBPVEJ5C/p1663899164615419?thread_ts=1663753895.315929&cid=CGBPVEJ5C>.
With this change, we get a 404 for missing assets, but 200 for missing paths:
> fix: For paths with an extension, give 404 if missing

- Dockerfile
We need to generate heapdumps in release/prod and to generate we need jcmd and jstack in the fat-container
> ops: use jdk instead of jre to generate heapdumps

- app/client/src/components/editorComponents/ActionCreator/Fields.tsx
- app/client/src/components/editorComponents/ActionCreator/constants.ts
- app/client/src/components/editorComponents/ActionCreator/utils.test.ts
Navigate to was throwing an error when the target window was changed from same -> new and vice versa.
The issue was occurring because PR #16947 removed the quotes surrounding the navigation field's values. Restoring the quotes back results in the regex being replaced correctly
Fixes #17050 
- Manually
- Updated jest tests
> fix: navigate to throws error when changing from same to new window and vice versa

- app/client/src/components/editorComponents/DropTargetComponent.tsx
- app/client/src/reducers/entityReducers/widgetConfigReducer.ts
- app/client/src/sagas/PageSagas.tsx
- app/client/src/sagas/dynamicHeightSagas.ts
- app/client/src/selectors/editorSelectors.tsx
- app/client/src/utils/hooks/useDynamicAppLayout.tsx
- app/client/src/widgets/ContainerWidget/component/index.tsx
- app/client/src/widgets/ContainerWidget/widget/index.tsx
- app/client/src/widgets/TabsWidget/index.ts
- Fixes issue where scroll height of container like widget's canvas was never resetting after we fixed the undo-redo issue
- Fixes issue where undo after move/add/delete/cut/paste/resize of a widget was not working.
> POC: Dynamic height undo redo issue

- app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx
Fix a bug in the release where the js toggle button was getting disabled even when we clear the input field.
Fixes #17106
- Manual
> fix: unable to enable JS toggle button even if the value is empty

- app/client/src/pages/common/ClientError.tsx
- app/client/src/pages/common/PageNotFound.tsx
- app/client/src/pages/common/ServerTimeout.tsx
- app/client/src/pages/common/ServerUnavailable.tsx
The error pages within Appsmith weren't using the design system components. Now they conform to the Appsmith Design System
**Before**
**After**
Manual
> chore: Making the error pages conform to the design system

- app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
- app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java
Fixes #11880 
Server side smart substitution parses js bounded (numbers/string representation of number arguments) as  **whole numbers**, and **decimal numbers** regardless if they are placed in quotes **" "**. This feature creates a bug for mongo regex substitution as **mongo regex attributes** only takes string arguments.  This PR fixes before mentioned characteristic.
> Bug Fix: Now, digit/ number arguments could be provided to the $regex with smart substitution turned on. 
The backend changes has been tested:
- Junit test cases
- Manually
> fix: MongoPlugin smart substitution for regex arguments

- app/client/src/components/propertyControls/InputTextControl.tsx
When the default value to INPUT_TEXT property control is 0, instead of showing the value 0, it is showing the placeholder text. This was because we were not properly checking for undefined value while rendering the component. This is fixed in this PR.
Fixes #17080
Fixes #17063 
- Manual
> fix: Placeholder being shown when value is zero

- app/client/src/widgets/DynamicHeightContainer.tsx
Added overflow-x hidden when overflow-y is active in the dynamic height container.
> fix: auto height limits horizontal scroll

- app/rts/build.sh
- app/rts/package.json
- app/rts/tsconfig.json
Adding of Jest Test Cases resulted in wrong build which was unable to start the rts server.
Added :
- removal of old build folder to create fresh build everytime
- exclusion of jest config and test cases in build directory
- changed coverage directory
Fixes #17176
- Test A
- Test B
> fix: failing rts build due to jest config

- deploy/docker/entrypoint.sh
Fix for setting the env `HOSTNAME` to '`heroku_dyno`' for heroku deployment.
> fix: set HOSTNAME env for heroku deployment

- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationTemplateServiceCEImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ReleaseNotesServiceCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ReleaseNotesServiceCEImpl.java
The `getReleasedVersion` method returns the current running version, _only_ if it dosen't end with `-SNAPSHOT`. If it does end with `-SNAPSHOT`, then it'll return the version from the most recent entry in the release notes.
The effect of this is that when fetching template applications, on version `v1.8.1-SNAPSHOT`, we pass in version as `v1.8.0` (which would be the most recent in release notes), which means the latest and greatest of templates won't ever be listed on prod.
The cloud-services API is actually capable of handling versions with `-SNAPSHOT` in them just fine. This server just isn't sending it.
This fix will send the current running version as is to cloud-services so we get more accurate results.
> fix: Fix template filtering version mismatch

- app/client/src/utils/WidgetFeatures.ts
- app/client/src/widgets/BaseWidget.tsx
Added the dynamic container into the deploy mode as well by enhancing the `getWidgetComponent` to add the dynamicHeightContainer in the getPageView. I didn't try to refactor the code because that will involve removing some code from the `getCanvasView` (ErrorBoundary).
> fix: auto height limits deploy mode

- app/client/src/widgets/RichTextEditorWidget/component/index.tsx
Imported the LabelWithTooltip in RichTextEditor from the repo itself rather than the design system.
> fix: LabelWithTooltip for RichTextEditor for Dynamic Height

- app/server/appsmith-plugins/graphqlPlugin/src/main/java/com/external/utils/GraphQLPaginationUtils.java
- app/server/appsmith-plugins/graphqlPlugin/src/test/java/com/external/plugins/GraphQLPluginTest.java
- Currently, if cursor-based pagination has been configured for a GraphQL query then it tries to fetch the next page results irrespective of whether the query run has been triggered via a paginated widget (e.g. table widget) or simply run by clicking the `run` button on the query config page. As a result, if a GraphQL query has the pagination tab configured with cursor pagination then clicking on the `run` button `k` times will fetch `k` next page results instead of showing the same result each time. The expected behavior is that it should fetch the next page results only when triggered via a paginated widget. This PR fixes this behavior. 
Fixes #17086 
- JUnit TC
> fix: fix GraphQL query run behaviour post cursor based pagination configuration

- app/client/src/widgets/VideoWidget/index.ts
Add #000 default background color to the video widget. This enables the Video Widget borders to follow the theme even when the container is not the same size as the video.
Fixes #11021
- Manually
> feat: Video Widget Reskinning

- app/server/appsmith-plugins/arangoDBPlugin/src/main/resources/form.json
> ArangoDB has changed it's default db name from `default` to `_system`. This PR make the corresponding changes.
Fixes #15899 
> I ran corresponding plugin test cases and passed all test cases.
> fix: Arango plugin: change default db name to _system

- app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datasources/ArangoDataSourceStub_spec.js
Update the default db name from default to _system for ArangoDataSourceStub_spec.js test
locally
> test: Update ArangoDataSourceStub_spec.js

- app/client/src/widgets/CheckboxWidget/component/index.tsx
- app/client/src/widgets/SwitchWidget/component/index.tsx
Word-break CSS rules added for Switch and Checkbox widget when Dynamic Height is enabled.
> fix: labels switch checkbox widget

- .gitignore
Ignore `yalc` files when developing; `yalc` helps in integrating design-system changes in development.
> chore: update gitignore with yalc

- app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ActionDependencyEdge.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewPageServiceCEImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PageLoadActionsUtilCEImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/RefactoringSolutionCEImpl.java
Since the older way of storing on load actions does not conform to the new type, this PR adds null checks to simply ignore all of the older values. These values are not used today and will be overridden as soon as an update layout is performed on the page, so they are inconsequential.
Fixes #17494
> fix: Added null check for action dependency edge

- app/client/src/components/editorComponents/CodeEditor/index.tsx
- app/client/src/components/propertyControls/InputTextControl.tsx
Enhanced the InputTextControl to accept two more event handlers for focus and blur from the property pane config.
Now for any widget `INPUT_TEXT` control in it's property pane config can accept two more properties called `onBlur` and `onFocus` which will respond to focus and blur events from the field in the property pane.
> feat: InputTextControl enhanement

- app/server/appsmith-plugins/mongoPlugin/src/main/resources/editor/find.json
This PR increases the size of MongoDB's Query field by changing the Query field form control to `QUERY_DYNAMIC_TEXT`.
Fixes #17265 
> fix: Switches mongo field type from dynamic input text to dynamic text

- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> When a template is imported. The app is reset to the old URL format. Because the applicationVersion is reset to 1. This currently breaks deployed apps.
Fixes #17428 
- Locally
> fix: App Version issue where the app was getting reset to old url after the template was merged to existing application

- .github/workflows/integration-tests-command.yml
- .github/workflows/server-build.yml
- .github/workflows/test-build-docker-image.yml
This PR adds  APPSMITH_AUDITLOG_ENABLED: true to CI in order to add cypress tests for audit logs
> ci: Add env variable Appsmith_Auditlog_Enabled to CI

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/TableV1/TableFilter2_Spec.ts
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/TableV2/TableV2Filter2_Spec.ts
- app/client/src/widgets/TableWidgetV2/widget/derived.js
Ends with operator not working in certain scenarios.
Here the issue is that we are using `lastIndexOf` without considering the edge case where this method might return a `-1`. When `lastIndexOf` returns -1 the condition for endsWith operation returns true for certain string lengths where it should have returned false.
Handled this by updating the endsWith checking logic.
Fixes #13334 
- Cypress tests
> fix: Ends with operator not working as expected

- deploy/docker/templates/nginx/nginx-app-http.conf.template.sh
- deploy/docker/templates/nginx/nginx-app-https.conf.template.sh
Currently, supervisor UI shows up like this:
Instead of showing up as illustrated in the Documentation here: https://docs.appsmith.com/getting-started/setup/instance-management/supervisor.
This PR fixes that.
> fix: Fix assets not loading in supervisor UI

- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceImplTest.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutActionServiceTest.java
Server side was allowing JS collection names to be duplicated in an app that took Appsmith apps to an inconsistent state. This PR fixes the logic for these checks.
Reproduction:
1. Create a new app, and open this app in another tab as well
2. Create a new JSObject in tab 1
3. Try to create a new JSObject in tab2. An error is seen on the page
4. Refresh the page
5. The app shows two JSObjects on the same name, but one of them won't have functions in the run dropdown.
Fixes #13692 
Fixes #14755
- JUnit test
> fix: Fixed check for duplicate JSObject names in an application page

- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DataUtils.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/TenantControllerCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/TenantServiceCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/TenantServiceCEImpl.java
Return the tenant object so that the `userPermissions` are part of the object.
- 
- Manual
> chore: Updating the tenant API to return the complete object instead of just the configuration

- app/server/appsmith-server/src/main/java/com/appsmith/server/constants/PatternConstants.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/WorkspaceServiceTest.java
> Website regex has missed the `/` at the end of websites. So adding that.
Fixes #8970 
>  WorkspaceServiceTest$validUpdateWorkspaceValidWebsite
> fix: update regex and test case for organisation website

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Filepicker/FilePickerV2_spec.js
- app/client/cypress/locators/Widgets.json
- app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx
To remove the `selectedFiles` meta property whenever the cancel button is clicked. This will make sure to remove the files from the redux store and also from the uppy's instance. 
Fixes #17659
Updated the `FilePickerV2_spec.js` with the following scenario:
- Click on cancel button
- Check the file picker button for the file count text. Since all files are deleted the text inside the file picker button becomes "Select Files"
- Check the API page and check the evaluated value inside the binding
> fix: remove file references on click of cancel button

- app/client/src/widgets/BaseInputWidget/widget/index.tsx
> Made changes to baseinputwidget label style - Emphasis Property
Fixes #15542 
This has been tested locally on my Computer
> fix: JS option missing for Label Font Style in Input widget

- app/client/src/actions/controlActions.tsx
- app/client/src/constants/PropertyControlConstants.tsx
- app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx
- app/client/src/reducers/entityReducers/widgetConfigReducer.ts
- app/client/src/sagas/WidgetOperationSagas.tsx
- app/client/src/sagas/dynamicHeightSagas.ts
- app/client/src/selectors/editorSelectors.tsx
- app/client/src/utils/DSLMigrations.ts
- app/client/src/utils/WidgetFactory.tsx
- app/client/src/utils/WidgetFactoryHelpers.ts
- app/client/src/utils/WidgetFeatures.ts
- app/client/src/utils/WidgetRegisterHelpers.tsx
- app/client/src/utils/WidgetRegistry.tsx
- app/client/src/utils/treeManipulationHelpers/dynamicHeightReflow.ts
- app/client/src/widgets/BaseWidget.tsx
- app/client/src/widgets/CategorySliderWidget/widget/index.tsx
- app/client/src/widgets/DynamicHeightContainer.tsx
- app/client/src/widgets/JSONFormWidget/index.ts
- app/client/src/widgets/NumberSliderWidget/widget/index.tsx
- app/client/src/widgets/RadioGroupWidget/component/index.tsx
- app/client/src/widgets/RadioGroupWidget/widget/index.tsx
- app/client/src/widgets/RangeSliderWidget/widget/index.tsx
- app/client/src/widgets/SelectWidget/component/index.styled.tsx
- app/client/src/widgets/SelectWidget/component/index.tsx
- app/client/src/widgets/TabsWidget/index.ts
- app/client/src/widgets/WidgetUtils.ts
- app/client/src/widgets/constants.ts
- app/client/src/workers/DataTreeEvaluator/test.ts
> fix: Auto Height Feature - Resolve issues and restructure code

- app/client/src/widgets/RadioGroupWidget/component/index.tsx
- app/client/src/widgets/SwitchGroupWidget/component/index.tsx
Used the isDynamicHeightEnabled prop to set the height of SwitchGroup and RadioGroup widgets from 32px to 100% in case of inline mode.
> fix: Switch and Radio group widget height fix

- app/client/src/components/editorComponents/Debugger/Resizer/index.tsx
We were getting some storing some wrong states when switching between certain action entities 
This would mess up context restore of Response pane heights. This PR makes sure that response pane
is mounted with correct values
Fixes #17749
Manually
> fix: Response Pane height context restore issue in some cases

- app/client/src/pages/Applications/index.tsx
> Updated left panel height on the home page due to the addition of admin settings to fix overlapping issue.
Fixes [#17786](https://github.com/appsmithorg/appsmith/issues/17786)
> Tested it locally and checked this fixes the issue.
> fix: Updating left panel height on home page due to addition of admin settings

- app/client/src/ce/pages/workspace/WorkspaceInviteUsersForm.tsx
- app/client/src/components/editorComponents/form/FormDialogComponent.tsx
- app/client/src/components/editorComponents/form/fields/DropdownWrapper.tsx
- app/client/src/components/editorComponents/form/fields/SelectField.tsx
> Add max dropdown height to solve scrolling issue in dropdown on invite modal.
Fixes [#17804](https://github.com/appsmithorg/appsmith/issues/17804)
- Manual
> Tested it out locally on the invite modal. If the dropdownMaxHeight prop is passed, then the max height of the dropdown has that value and is scrollable in that area.
> fix: Add max dropdown height

- app/client/src/widgets/BaseWidget.tsx
Removed the class property expectedHeight from BaseWidget as it is not useful in the overlay logic after some changes.
> fix: remove expected height

- app/client/src/widgets/RichTextEditorWidget/component/index.tsx
Fixed the left alignment issue of label in the rich text editor by adding some styles applied only when the dynamic height is enabled.
> fix: rich text editor dynamic height

- contributions/ServerSetup.md
> Local server set up requires configuring the env variable APPSMITH_GIT_ROOT to be configured. This is PR adds the same info to the docs for the server set-up guidelines.
> chore: Add git file system env to server setup guidelines

- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/PluginUtils.java
- app/server/appsmith-interfaces/src/test/java/com/appsmith/external/helpers/PluginUtilsTest.java
- app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/MethodConfig.java
Fixes #16251
as per the suggestion
> [Apparently](https://app.smartlook.com/org/9b6c5c859e85745d01196fa4/project/e373e3a21d27278fd281d8b0/recordings?filter=ff5c57b6ed2be106f1ea85e57140fec16b4d51f5fee6aabb1d66950bcbfb4742&player=1&session=7WzknO24Dx&visitor=vesDHD7SFx) this user had bound the url string to a value that evaluated to a number. Possibly the same kind of error for other users before this. We shouldn't fail here in either case, can switch this to safer conversion.
- added a util method in PluginUtils which was earlier returning Object class, but is now returning a casted String.
- this method is a wrapper on the existing method only
- added junit to verify the error in casting in the existing method
- added junit to verify the correct casting behaviour in the new method
- Bug …
> fix: ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String 

- app/client/src/components/editorComponents/EditorContextProvider.test.tsx
- app/client/src/components/editorComponents/EditorContextProvider.tsx
- app/client/src/constants/WidgetConstants.tsx
- app/client/src/pages/AppViewer/index.tsx
- app/client/src/pages/Editor/WidgetsEditor/index.tsx
Enables the meta widget API i.e `modifyMetaWidgets` in the view mode.
In View mode the `EditorContext` is set using the `EditorContext.Provider`.
In Edit mode the `EditorContext` is set using the `EditorContextProvider` component.
Due to this any new API introduced would have to be added to the view mode and edit mode separately even thought the methods are same.
This PR aims to the usage of the `EditorContextProvider` component in both view mode and edit mode.
Fixes #16847 
Jest
All the API methods that are introduced in each modes (view/edit) are verified for the availability 
> chore: meta widget enable in view mode

- app/server/appsmith-server/src/main/java/com/appsmith/server/services/LayoutCollectionServiceImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCEImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutCollectionServiceCEImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCEImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewPageServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceImplTest.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceTest.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceServiceTest.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/NewPageServiceTest.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/ActionServiceCE_Test.java
> Set the user permissions for Datasources, Pages, Actions and JS Objects
Fixes https://github.com/appsmithorg/appsmith/issues/17870
> This has been tested manually with running POST API calls.
> JUnit Test cases updated/added
> - ActionCollectionServiceTest$testCreateActionCollection
> - DatasourceServiceTest$datasourceDefaultNameCounterAsPerWorkspaceId
> - DatasourceServiceTest$createDatasourceWithNullPluginId
> - DatasourceServiceTest$createDatasourceNotInstalledPlugin
> - DatasourceServiceTest$createDatasourceValid
> - NewPageServiceTest$testCreateDefault
> - ActionServiceCE_Test$createValidActionAndCheckPermissions
> - ActionServiceCE_Test$createValidAction_forGitConnectedApp_getValidPermissionAndDefaultIds
> - …
> feat: set user permissions to objects when creating

- app/client/src/ce/pages/AdminSettings/index.tsx
- app/client/src/pages/Applications/ProductUpdatesModal/index.tsx
> Reducing the number of /new API calls by calling it on the Admin settings page only when a user tries to view the release notes in the Version tab.
Fixes [#17887](https://github.com/appsmithorg/appsmith/issues/17887)
- Reduce the number of API calls
> Tested that the /new API is getting called in the Admin settings page only when the user clicks on view release notes in the Version tab. Also, I checked that the home page what's new click is not affected by this change and neither is the number of /new API calls on the Home page.
- Manual
> chore: Reducing the number of /new API calls

- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeServiceUtils.java
- app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/datatypes/MySQLSpecificDataTypes.java
- app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySQLPluginDataTypeTest.java
This commit adds support for handling array-like data in MySQL
- If the data type identified by the client side is of type ARRAY it will be treated as STRING as MySQL doesn't have support for ARRAY data type
Fixes #17702 
- Manual
- JUnit
> fix: Internal server error in case of ARRAY type in MySQL (#17702)

- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AstServiceCEImpl.java
- app/server/appsmith-server/src/main/resources/application.properties
We'll make use of a generous timeout of 1 second instead so that these attempts do have an end.
> chore: Removing AST connection acquisition pool limit

- app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CacheableRepositoryHelperCEImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/PermissionGroupServiceCEImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/repositories/ce/CacheableRepositoryCEImplTest.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/WorkspaceServiceTest.java
To ensure that we are not leaving behind dangling default roles, we must delete the default roles generated on create of a workspace when the same is deleted.
> chore: Delete default permission groups when workspace is deleted

- app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/UpdateMany.java
- app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/utils/MongoPluginUtils.java
- app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/utils/MongoPluginUtilsTest.java
Fixes #11419
Based on the suggestion : https://github.com/appsmithorg/appsmith/pull/12241#discussion_r844997566
> Hi @devnamrits , this approach has a drawback. If we do this, then we can never validate any input as valid or invalid. e.g. If `this.update` is `"abc"` then this will be parsed as a valid input which is not intended. Essentially this change converts any input into a valid input. However, what we want is to be able to detect if the user input is valid or not. Up until now we have only tried to check if the input is a valid `Document` or not, which in this case is not sufficient since MongoDB 4.2 onwards it also accepts an array of Documents (pipleine) as well. Hence, IMO, the correct approach here should be to parse for two things - (1) valid Document (2) valid array of …
> fix: MongoPlugin Update Command : parsing valid document or array of valid documents

- app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
> The method currently makes multiple DB calls
> 1) Fetch all workspace ids where the plugin id is not present
> 2) Fetch complete workspace details with these ids (1 query per workspace id)
> 3) Assign plugin and save each workspace
- Does not exactly fix the issue #16762 but does address it partially since the update happens in batches vs 1 by 1. Please check out the comment section to understand more. 
Fixes 
> The fix performs one single update query. The query adds the plugin to all workspaces where the plugin doesn't already exist.
> No data is fetched in java
> No tests found in the repo.
> Check if installation of plugin to all workspaces works when there are multiple workspaces and …
> chore: Refactor DB changelog to install plugins in workspace with single query

- .github/workflows/client-build.yml
Remove PR from insert query as its sometimes not available and row can be uniquely identified with the run_id and attempt
Fixes: https://github.com/appsmithorg/appsmith/issues/17916
> ci: Remove PR from create run meta query

- app/client/src/entities/FeatureFlags.ts
- app/client/src/pages/Applications/ImportApplicationModal.tsx
Three flags GIT, GIT_IMPORT and AUDIT_LOGS are not being used in FE anymore. This PR removes those extra flags.
Continuation of https://github.com/appsmithorg/appsmith/pull/18029
Fixes #18036 
- Chore
- Manual
> chore: remove extra feature flags | FE

- app/client/src/widgets/MenuButtonWidget/widget/index.tsx
The menu button was not having the js option for icon but its children buttons had the js option for icon
Fixes #11142
Media
- Manually
> fix: added JS on menu button

- app/client/src/sagas/ApplicationSagas.tsx
On forking application ( a hush hush operation ), workspace was not set up to the current one. The current one will be the one where the application is being forked.
Fixes #18045 
Notice the "Resource not found" error and that the /members response is error.
https://user-images.githubusercontent.com/1573771/199471301-b3803039-8940-47a6-bd00-e24309041102.mov
Notice that error pop up doesn't come up and the /members response is valid.
https://user-images.githubusercontent.com/1573771/199471455-78403152-de61-4961-b194-587fcff649bf.mov
- Manual
> fix: set current workspace id in redux store

- app/client/src/components/editorComponents/AutoHeightOverlay.tsx
- app/client/src/widgets/AutoHeightContainer.tsx
- app/client/src/widgets/BaseWidget.tsx
- app/client/src/widgets/WidgetUtils.test.ts
- app/client/src/widgets/WidgetUtils.ts
The BaseWidget now does the following:
Fixes #17993
- Manual (Smoke test, should not break existing apps)
- Jest (For new functions added)
- Cypress (Existing tests)
~~- [NA] I have made corresponding changes to the documentation~~
> feat: base widget Auto height enhancements

- app/server/appsmith-server/src/main/java/com/appsmith/server/acl/AclPermission.java
This is a hot fix for the issue seen by a few instances which have manually upgraded Community Edition after a gap. This led to an old migration which relied on a deleted field for serialization failing leading to server not coming up. This issue was not seen by any instance which was on auto upgrade. This was faced only by a few instances who upgraded to the latest after a gap.
> chore: Re-adding the read permission group AclPermission

- app/client/src/utils/WidgetFeatures.ts
- app/client/src/utils/hooks/useWidgetConfig.ts
- app/client/src/widgets/BaseWidget.tsx
- app/client/src/widgets/DynamicHeightContainerWrapper.tsx
The DynamicHeightContainer is added all widgets which donot have `isCanvas` property. This means that widgets like container widgets should not have this container wrapper. Unfortunately, with the current mechanism things this may not work, as old DSLs may not have the `isCanvas` property properly defined. 
To get around this we'll get the `isCanvas` value from the widget configs in the reducers.
This makes us convert the `addDynamicHeightContainer` function into a React component, which uses hooks to fetch the config.
> fix: old DSL container collapse

- scripts/local_testing.sh
- Currently, the `local_testing.sh` script fails when building external contributor PRs because the source branch belongs to a non-Appsmith repository. `local_testing.sh` is used by the QA team to manually test PR changes before merge. This PR updates the script to include any non-Appsmith repository as a `remote` reference to the local Git context which would allow us to pull the related external contributor branch on our local setup for manual test. 
- New usage example : `/scripts/local_testing.sh -r https://github.com/lifeneedspassion/appsmith.git fix/17747-js-error`
Fixes #18023 
- Manual
- Automated test does not seem feasible at the moment
> fix: update local_testing.sh to build image for external contributor PRs

- app/client/src/widgets/RichTextEditorWidget/component/index.tsx
Fixed the position of the limits label to the right so that it will not intersect with the handle dot.
> fix: auto height limits rich text editor min height

- app/client/src/utils/WidgetFeatures.ts
Changed react to reacts in the helpText of the dynamic height property in the property pane.
> fix: grammatical error in the help text

- app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepositoryImpl.java
Deleting the application throws a 500 error if there are soft-deleted JSObjects present. This happens when apps are exported from older versions of Appsmith and imported to new versions and if there are soft-deleted JSObjects present in the exported JSON.
Fixes #18181 
- Manual
> fix: Error deleting application when soft-deleted entities are present in the application

- app/client/src/widgets/TabsWidget/widget/index.tsx
Solved the issue by disabling the scroll for the child canvas widget in the tabs widget.
> fix: auto height tabs double scroll

- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/PluginUtils.java
> Generate page from google sheet datasource was throwing exception.
> Fixed that exception using simple null check.
Fixes #18102
- Manual
> fix: Google sheet datasource fix

- app/client/start-https.sh
When a stale PID file is left from a previous kill of NGINX, the script is unable to recover from this situation. This fix handles this case.
[Slack conversation with more details](https://theappsmith.slack.com/archives/C02K2MZERSL/p1666689938774649).
> fix: Stale PID file breaking start-https.sh script

- app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/BaseAppsmithRepositoryCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceTest.java
Recently we found there were issues happening because of the deprecated `deleted` param in entities for soft-delete operation. In the latest version, we only use `deletedAt` field for soft-delete. This PR correct the usage of old `deleted` field only filter and adds the current field to the filter.
Fixes #18161
- Manual
- JUnit
> fix: Corrected usage of old soft deleted filter in BaseAppsmithRepository

- app/client/src/serviceWorker.js
- app/client/src/utils/AppsmithUtils.tsx
We used to log sentry errors every time we faced a chunk load error. Now we will only do it after 3rd failure in the retry mechanism
Fixes #17258
Media
- Manually
> fix: Log ChunkLoadError on Sentry only after 3rd failure

- app/client/src/reducers/entityReducers/autoHeightReducers/autoHeightLayoutTreeReducer.ts
- app/client/src/utils/treeManipulationHelpers/dynamicHeightReflow.ts
> task: Dynamic height reflow fixes in Branch

- deploy/helm/templates/ingress.yaml
fixes: [18207](https://github.com/appsmithorg/appsmith/issues/18207)
> fix: add certmanager and classname fields in ingress

- app/client/src/utils/autoHeight/generateTree.ts
Sort Space based on original position if dynamic positions are equal while generating tree.
Fixes #18399
- Manual
> fix: Invisible Widgets Overlap while switching back and forth between edit and preview modes in rare cases

- app/server/appsmith-server/src/main/java/com/appsmith/server/constants/FieldName.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCEImpl.java
This PR sends the number of binding parameters to the analytics data on execute action event.
Fixes #17565 
- Manual
> chore: Add binding parameters' count to analytics data on execute action event

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Text/Text_new_feature_spec.js
- app/client/src/widgets/TextWidget/component/filters/LinkFilter.ts
- app/client/src/widgets/TextWidget/component/helpers.tsx
- app/client/src/widgets/TextWidget/component/index.tsx
On using anchor with href without `https` or `http`, It creates invalid URL which leads to 404 page. This PR fixes that invalid URL.
Fixes #18204 
- Bug fix
- Manual
> fix: Using an html tag within a Text widget to access a web page, without the https:// appended causes application to crash

- app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
- app/client/src/pages/Editor/QueryEditor/Table.tsx
- app/client/src/pages/Editor/QueryEditor/index.tsx
- app/client/src/pages/Editor/__tests__/QueryEditorTable.test.tsx
Vertical scroll bar is missing in response tab for database queries
Fixes #17653
- Manual
- Jest
> fix: table scroll issue fixed

- app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/SegmentConfig.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AnalyticsServiceCEImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCEImpl.java
> This PR fixes the issue of the Segment - `IllegalArgumentException : Either anonymousId or userId must be provided.`
> We were passing the entire dsl on the update layout call to the segment. This was more than the 32KB limit of the segment. When we hit this error we have an onError method which catches all the segment call failures and tries to send the error details back to the segment with details. This is present in `SegmentConfig` class. But with the Segment library upgrade from 2.1.1 to 3.3.1, Segment expects either userId or anonymousId to be present always. It can't be an empty string. 
So adding the `segmentError` as user details in case of the Segment call failures.
> chore: Reduce size of payload to data sent to Segment

- app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx
Changed value to ref so that it retain value across renders
Fixes #18191 
- Manual
> Fix: Unable to delete the checkbox group items inside the list widget

- app/client/src/components/autoHeightOverlay/index.tsx
- app/client/src/components/editorComponents/DropTargetComponent.tsx
- app/client/src/sagas/autoHeightSagas/containers.ts
- app/client/src/sagas/autoHeightSagas/helpers.ts
- app/client/src/sagas/autoHeightSagas/index.ts
- app/client/src/sagas/autoHeightSagas/widgets.ts
- app/client/src/widgets/TabsWidget/component/index.tsx
- app/client/src/widgets/TabsWidget/index.ts
- app/client/src/widgets/TabsWidget/widget/index.tsx
- app/client/src/widgets/withWidgetProps.tsx
> fix: issues related to tabs widget in auto height

- app/client/src/utils/autoHeight/constants.ts
- app/client/src/utils/autoHeight/generateTree.test.ts
- app/client/src/utils/autoHeight/generateTree.ts
- app/client/src/utils/autoHeight/helpers.ts
- app/client/src/utils/autoHeight/reflow.test.ts
- app/client/src/utils/autoHeight/reflow.ts
Fixes issue where widget spacing keeps increasing when moving widgets and updating auto height
This change maintains the distance to be the same as the one with the nearest above widget before the update.
https://user-images.githubusercontent.com/103687/204091036-5f2c15d8-5951-4993-98c1-e76209b5a7bf.mov
https://user-images.githubusercontent.com/103687/204092362-57f69e99-0d6d-4bc6-855d-5b5053fbfbda.mov
- Manual
- Jest
- Cypress
> fix: widgets increase spacing 

- app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datasources/AuthenticatedApiDatasource_spec.js
- app/client/cypress/support/Pages/DataSources.ts
- app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
- app/server/appsmith-server/src/main/java/com/appsmith/server/constants/Entity.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java
When I save and authorize a new authenticated api datasource successfully, I expect to see the overview of that datasource, but instead I see the new datasources pane.
Fixes #18051
- Manual
- Cypress
> fix: gsheet save and authorize redirect issue fixed

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_EvaluatedPopup_spec.js
- app/client/src/widgets/ListWidgetV2/index.ts
`logBlackList` prevented errors from getting to the Evaluation popup, also, the datapath has been changed, so we don't need `List1.template.Text1.text`. We just access it from the data tree directly. This introduced meta widget appearance in the debugger. This issue would be solved in https://github.com/appsmithorg/appsmith/issues/18382.
Fixes #16576
- Cypress
> fix: evaluated popup value and error for list v2

- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewPageServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/NewPageServiceTest.java
We were disregarding view mode while retrieving the application object. This meant that we always showed app layout settings from edit mode (default being used even in published mode). This PR fixes that.
Fixes #18363 
- Manual
- JUnit
> fix: Added view mode param to returned application object

- app/client/src/sagas/WebsocketSagas/handleAppLevelSocketEvents.tsx
We have added a check to confirm if an Appsmith version is set. That way when building an instance without an version number will not keep failing the version check.
> We will not show an Appsmith update dialog when no version is set
Fixes #18485
More context
https://theappsmith.slack.com/archives/CGBPVEJ5C/p1669193068825349
- Manual
> fix: Appsmith version update dialog showing up when no version is set

- app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts
- app/client/src/widgets/ListWidgetV2/widget/index.tsx
This a perf only PR.
The meta canvas widget which has the individual item's containers id as children was re-generated for every render cycle even when it wasn't required. This lead to un-necessary re-renders in the child widgets.
Problem:
The `this.prevMetaMainCanvasWidget` was getting mutated as it got the value from `mainCanvasWidget` in line 341 (widget/index.tsx). The mutation was that the base widget adds `creatorId` to the meta widgets before calling the action. This addition of createdId gets mutated to the `this.prevMetaMainCanvasWidget` and thus when deep equaled in re-render, `this.prevMetaMainCanvasWidget` has `creatorId` and `mainCanvasWidget` does not as it is re-generated.
The above fix led to another problem of the main canvas widget getting removed when page changed for a …
> perf: Listv2 regeneration of meta canvas widget for every re-render

- app/client/src/components/autoHeightOverlay/index.tsx
When we drag the min/max to each other and make them equal, we see a flicker to the past value in the one we are dragging.
We do a batch update when the two values collide, and then set the diff to 0 therefore it goes back to its previous value but then the batch completes and resets the value which we wanted to set hence the flicker. Now we set the diff after the batch update completes.
Fixes #18548
Media
-- Before
https://user-images.githubusercontent.com/17961105/204501044-6c062a75-9f76-444c-bee3-5e9c1d365815.mov
-- After
https://user-images.githubusercontent.com/17961105/204501270-0cb17733-8321-4644-a151-d349473a07e6.mov
- Manual
> fix: flicker issue when both the min max values collide

- app/client/src/components/editorComponents/EditableText.tsx
> Adding additional optional props to editable text component
Fixes [#18543](https://github.com/appsmithorg/appsmith/issues/18543)
> New feature (non-breaking change which adds functionality)
> These are additional optional props that are added and don't require testing unless being used.
- Manual
> chore: Adding additional optional props to editable text component

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Git/GitSync/Merge_spec.js
Fixes merge_spec.js by adding wait before clicking the branch dropdown in git modal.
locally
> test: fix merge_spec.js cypress test

- app/client/src/pages/Applications/ApplicationCard.tsx
- app/client/src/pages/Applications/index.tsx
- app/client/src/pages/Editor/Explorer/Pages/PageContextMenu.tsx
- app/client/src/pages/Editor/Explorer/Pages/index.tsx
- app/client/src/pages/Editor/PagesEditor/ContextMenu.tsx
- app/client/src/pages/Editor/PagesEditor/PageListItem.tsx
- app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
- On first load the page list item icons were not permission driven due to the fact that we only fetch permissions on each page visit. But this has been changed in another PR and we were fetching all page permissions on the first fetch all call and stored it in redux store. So In this PR we simply get the permissions by page ID from redux store.
- Also fixes a missed out `Create datasource` CTA on the query right pane's switch datasource dropdown.
- Also makes `Duplicate` & `Fork` of Application to be permission driven. Requires both Edit application permission on App and Create application permission on workspace.
Fixes #18556 
Fixes #18573 
Media
https://www.loom.com/share/df6233abd2a14e4aa78767198184a6c9
- Manual
> fix: page list item icons aren't permission driven on first load

- app/client/src/workers/Evaluation/JSObject/index.ts
Every time we load an application we parse each js object body using AST to get the key, value pair of functions, and variables. After parsing we get all functions in string format but to execute these functions we need them in function format. To convert string to function we use evaluateSync function but we were providing `isTriggred` as true which was adding all platform functions to GLOBAL_DATA. As part of this transformation, cloning of the data tree was happening internally which adds time for parseJSActions function. So to reduce this time, we are sending isTriggred as false. 
- Manual
- Jest
- Cypress
> fix: Reduces cloning by not adding platform functions

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ActionExecution/NavigateTo_spec.ts
- app/server/appsmith-server/src/main/resources/features/init-flags.yml
Recently, navigation broke where params were not retained when using the navigateTo function. Adding an assertion here to make sure it does not break again
> chore: Update NavigateTo tests to verify params

- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/PermissionGroupServiceCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/PermissionGroupServiceCEImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCEImpl.java
Fixes #18216
Today, the workspace delete assumes that the user is a member of the workspace (which is indeed true for community editition). But with Granular Access Control, a non member could also be given the permission to delete the workspace. In that case, the user would not have access to the default workspace roles (since she isn't a member). During delete, the operation includes both delete of the workspace and doing a cleanup of default roles to which the user doesn't have any permission. To evade this, we are just checking for the user having the permission to delete the workspace. If she has the required permission on the workspace, we are letting the cleanup of the default roles without permission.
> fix: If the user has delete permission on the workspace, allow the user to delete the workspace and also delete the default roles (without permission)

- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceServiceTest.java
When the datasource is updated, in the response the server did not set the current permissions of the user. This is now required as part of granular access control for the client to enable/disable actions on top of the datasource (like create a query, save, etc.). This PR adds the permissions in the response.
Fixes #18601
> fix: Add user permission in the response for update datasource api

- app/client/src/pages/Editor/DataSourceEditor/SaveOrDiscardDatasourceModal.tsx
- app/client/src/pages/Editor/DataSourceEditor/index.tsx
- app/client/src/pages/Editor/SaaSEditor/DatasourceForm.tsx
- app/client/src/pages/common/datasourceAuth/index.tsx
There has been some change to the datasource create flow. Before as soon as the user click the `+` next to the datasource entity, it creates a datasource and then let the user edit the datasource form. But now, we only create datasource only when the user saves the datasource. 
Since the datasource only gets created on save, there will be no permissions. So the CTAs which are permission driven will all be disabled in EE.  So fixed that and handled it for the scenarios mentioned in the linked issue.
Fixes #18600 
Media
- Manual
> fix: update permission driven ctas to handle auto save update changes

- app/client/src/pages/Editor/DataSourceEditor/DBForm.tsx
- app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
- app/client/src/pages/Editor/SaaSEditor/DatasourceForm.tsx
This fixes even more issues on create datasource flow which are missed out when fixing #18600 . This fixes cases listed in the below issue. 
>TL;DR Create datasource flow permission driven cta fixes.
Fixes #18644
Media
https://www.loom.com/share/5555fd58ffbd44f08971acc82def770c
- Manual
> fix: datasource title not editable and ctas disabled on create

- app/client/start-https.sh
Added `--https-port` and `--http-port`, so you can set a custom port instead of the default 80 and 443. This is useful if you want to test Appsmith when using a non-standard port, fox example, how `appsmith.URL.host` behaves, or how OAuth redirects behave etc.
We also add a shortcut to start this with release endpoint. Just using `release` is now the same thing as using `https://release.app.appsmith.com`. This is useful to people like me who are _very_ good with typos.
> chore: Support using custom port(s) for listening in the start-https.sh script

- deploy/helm/templates/ingress.yaml
These fields were supported earlier and with our new ingress template. 
we dont need certManager , we configure it with tls and kubernetes secret as follows.
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
name: ingress-resource
annotations:
kubernetes.io/ingress.class: nginx
spec:
rules:
- host: poc-helm3.bluekiri.tech
http:
paths:
- path: /helloworld
backend:
serviceName: hello-app
servicePort: 8080
```
and the field className has been changed to `ingressClassName`
> chore: fix ingress fieldname in appsmith

- app/client/src/reducers/entityReducers/autoHeightReducers/autoHeightLayoutTreeReducer.ts
- app/client/src/sagas/autoHeightSagas/helpers.ts
- app/client/src/sagas/autoHeightSagas/widgets.ts
Fix issue where auto height was throwing an error when a fixed modal widget's children were changing height automatically
Fixes #18681
Before:
https://user-images.githubusercontent.com/103687/205632585-9dc28071-7dbc-408e-9010-71cf5b2e2699.mov
After:
https://user-images.githubusercontent.com/103687/205632610-3b52e00e-f7cf-48dc-8bd4-4b316151a0c6.mov
- Manual
- Cypress: [PENDING](https://www.notion.so/appsmith/Cypress-Test-scenarios-50557ff33f2745498396a4215b9a77ed)
> fix: Auto height breaks for fixed modal's children

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Git/GitDatasourceChange/CreateBranch_DiscardDatasource_spec.js
- app/client/src/pages/Editor/DataSourceEditor/index.tsx
- app/client/src/pages/Editor/SaaSEditor/DatasourceForm.tsx
From a new branch in a git connected application (say "Test"), when I create new datasource, and in the new datasource page, I click on Back, and click on Don't Save, the branch gets changed from Test to Main.
Fixes #18665 
Media
- Manual
- Cypress
> fix: datasource autosave git issue fixed

- app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AstServiceCEImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutServiceTest.java
This PR adds two new attributes to invalid binding errors. These are:
- oldParent: The DSL object before this iteration
- currentKey: The path component that this iteration is currently at
These two additions will help us better understand what the state of the app was during failure.
- Chore
- Manual
> chore: Improved metadata on logs when reading DSL fails

- app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java
There's one error that has the `errorType` set to `null`, which is causing an NPE. This PR includes a concrete value for `errorType` for this error.
The other change is we removed the _double-formatting_ of the error messages, which is actually not used anywhere.
We also fix the single quotes in error messages. They disappear. Yes. See screenshot:
Reason is that single-quotes are treated special in message formats. To get one single quote in formatted output, we need two. Refer 
<https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/text/MessageFormat.html>.
> fix: Fix NPE on reset password, and message formats

- app/client/src/pages/Applications/index.tsx
Remove the redundant share CTA from the organization menu
Fixes #18720
Media
- Manual
> fix: Remove redundant share CTA from org menu

- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java
Fixes #18371 
With GAC, it is possible now to take away edit permissions for a given page even though the user might have edit on the entire application (except a particular page). This change ensures that as long as the user has view permission on a page, they would still be able to open the said page in the editor.
> chore: Fetch pages in editor with READ permissions

- app/client/src/widgets/TableWidgetV2/component/header/actions/index.tsx
Fixes #18346
Now toggling the show filter and show download properties from the property pane should not hide/show the add new row link in the table header
- Manual
> fix: show filter & show download should not control add new row link visibility in table widget

- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/RestAPIActivateUtils.java
- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/plugins/BaseRestApiPluginExecutor.java
- app/server/appsmith-plugins/graphqlPlugin/src/main/java/com/external/plugins/GraphQLPlugin.java
- app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
**Description**
Rename file.
Fixes https://github.com/appsmithorg/appsmith/issues/16670
Just a renaming class name, its usage and associated object names from RestAPITriggerUtils to RestAPIActivateUtils
Reason: Name "Trigger" context has been used to denote dynamic calls. This class is to performs the built api call on execute command
Ref #16687
Checklist:
> chore: rename_triggerUtils

- app/client/src/components/editorComponents/Button.tsx
- app/client/src/entities/Engine/AppEditorEngine.ts
- app/client/src/pages/Editor/Explorer/Files/index.tsx
- app/client/src/sagas/PluginSagas.ts
> Fetching the plugin form config for queries if datasource is not viewable.
> TL;DR: Change is being done for GAC. Shouldn't impact users.
Fixes [#18372](https://github.com/appsmithorg/appsmith/issues/18372)
> Tested this on the GAC feature branch and now its working as expected.
- Manual
> fix: fetching the plugin form config for queries if datasource is not viewable

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Omnibar_spec.js
- app/client/src/ce/constants/messages.test.ts
- app/client/src/ce/constants/messages.ts
- app/client/src/ce/pages/AdminSettings/LeftPane.tsx
- app/client/src/ce/pages/AdminSettings/config/authentication/AuthPage.tsx
> Updating the text from enterprise to business to maintain consistency
Fixes [#18788](https://github.com/appsmithorg/appsmith/issues/18788)
Media
- Renaming
> Checked pages using Enterprise text are now showing Business text.
- Manual
> chore: Updating the text from enterprise to business to maintain consistency

- app/client/build.sh
- app/client/src/widgets/ContainerWidget/component/index.tsx
- app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts
- app/client/src/widgets/ListWidgetV2/widget/index.tsx
1. Container widget layout thrashing is avoided by using fastdom on direct DOM mutations in useEffect.
2. Avoid regeneration of widgets when none of the regeneration options are modified.
3. Memoize the renderChildren based on the change of `metaWidgetChildrenStructure`
Fixes #16786
Media
- Performance
- Manual
> perf: Performance changes related to render and regenration

- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java
The call to `sendMail` is calling a reactor chain, that subscribes separately. This `sendMail` call is already finished, before the `updateTenantLogoInParams` function even starts running. The `defer` won't be able to protect here, unless we move the `emailMono` variable's value to be inside the `Mono.defer`.
This change is very similar to https://github.com/appsmithorg/appsmith-ee/pull/826.
> Fix potential race condition in sending email

- app/client/src/ce/reducers/tenantReducer.ts
- app/client/src/ce/sagas/tenantSagas.tsx
- app/client/src/ce/utils/permissionHelpers.tsx
- app/client/src/pages/Applications/index.tsx
> Updating the logic for getting tenant permissions to show new workspace button
Fixes [#18660](https://github.com/appsmithorg/appsmith/issues/18660)
> Works as expected now.
- Manual
> fix: Updating the logic for getting tenant permissions to show new workspace button

- .github/workflows/integration-tests-command.yml
- .github/workflows/perf-test.yml
- .github/workflows/test-build-docker-image.yml
This PR adds replicaSet to the mongodb url used in the CI. This is to support the mongoDB transaction PR - https://github.com/appsmithorg/appsmith/pull/14939
> ci: Add replicate set to the mongodb url for transaction PR

- app/client/src/pages/Editor/IntegrationEditor/DatasourceCard.tsx
Hide CTAs of datasource in active datasource options menu when there are no permissions.
Fixes #18786 
Media
[Loom video](https://www.loom.com/share/610fceaacdac4994b026f7ab82792901)
- Manual
> fix: datasource active tab options menu is not permission driven

- .github/workflows/perf-test.yml
While fixing this in the earlier PR a stray job is added, which is not required. This PR fixes it.
fixes: #18687
> ci: Fix perf test failure due to a wrong step added earlier

- .github/workflows/fat-migration.yml
- This PR adds a new fat-migration.yml file which will run all cases in fat container instead of dev.app.appsmith
- This PR will not affect any existing Push/Workflow dispatches as its a separate action file
- Moving to fat container will not be put into action until RBAC is live - so as to not trigger any new challenge at last minute
- New .yml file
- Cypress CI runs
> test: Migration to FatContainer (new .yml faile)

- app/client/src/sagas/WidgetSelectionSagas.ts
Fix for unknown scenario where a widget selection request is received but no such widget exists
Media
> fix: Modal opening or closing type error

- .github/workflows/integration-tests-command.yml
Makes perf tests a blocking check and doesn't let the PR get merged until the perf tests have passed.
> ci: Make perf tests a blocking check

- app/client/src/sagas/WidgetSelectionSagas.ts
- app/client/src/selectors/entitiesSelector.ts
Issue:
Modal widget was getting closed after dropping a new widget.
Problem:
After the merge of this feature #18326 in the `openOrCloseModalSaga` we were using `state.ui.pageWidgets` which is not giving us an updated map of the new widgets added to the Modal, hence it was not able to check whether that widget parent is a Modal Widget.
Solution:-
Replaced `state.ui.pageWidgets` map with `state.entities.canvasWidgets` in the `openOrCloseModalSaga` which gives us the information of the newly dropped widget and solve the isse.
Fixes #18952
Media
- Manual
> fix: modal widget close on new widget drop

- app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
- Replace Appsmith's mock server endpoint usage with `MockWebServer` so that the JUnit TC pass / fail status does not depend on any external API service availability.  
- Ref: https://theappsmith.slack.com/archives/CGBPVEJ5C/p1670995379860729
> fix: replace Appsmith's mock server endpoint with MockWebServer

- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCEImpl.java
> To accommodate for datasource context adaption for environments, Some datasourceService methods needs to be aware of `environment name` in order to evaluate the `datasource configuration` for the given environment
> TL; DR : This Pr changes method signature for fetching  datasource by actionId
Fixes #18760  
Ref #18762 
> Chore
- Manual
- Jest
> chore: method signature changed for getCachedDatasourceForActtionExecution

- .github/workflows/client-build.yml
- .github/workflows/github-release.yml
- .github/workflows/server-build.yml
- .github/workflows/test-build-docker-image.yml
This PR moves the Github runners from Buildjet to Github large runners because of concurrency concerns.
> ci: Moving the runners to use Github large runners instead of Buildjet

- app/client/public/logger.js
Restricts /usage-pulse call only to urls containing "/app/". 
`sendPulse` fires a call to /usage-pulse endpoint in the server. Tracking metions of sendPulse:
1. [client/public/logger.js#L84 DOMContentLoaded](https://github.com/appsmithorg/appsmith/blob/release/app/client/public/logger.js#L84)
2. [client/public/logger.js#L44 pointerDown](https://github.com/appsmithorg/appsmith/blob/release/app/client/public/logger.js#L44)
3. Here we remove the event listener added on the line 44 (above). [client/public/logger.js#L47](https://github.com/appsmithorg/appsmith/blob/release/app/client/public/logger.js#L47)
First two result in calling `punchIn`, which calls `sendPulse` [here](https://github.com/appsmithorg/appsmith/blob/release/app/client/public/logger.js#L80)
It is defined …
> chore: restrict when /usage-pulse can be fired

- app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java
> The `validCloneApplicationWhenCancelledMidWay` became flaky during the code changes due to https://github.com/appsmithorg/appsmith-ee/pull/843 so increasing the timeout in the test case for canceling midway.
Media
> Test case change for flaky tests.
> ci: flaky test validCloneApplicationWhenCancelledMidWay

- app/client/src/pages/Editor/DataSourceEditor/JSONtoForm.tsx
- app/client/src/pages/Editor/gitSync/ReconnectDatasourceModal.tsx
> Updating UI for icons and import modal content height
Fixes #19111 #19112 
> Checked the UI locally and looks fine now - icons + scrollable height of the import modal content. 
- Manual
> fix: Updating UI for icons and import modal content height

- app/server/appsmith-server/src/main/resources/application.properties
This should upgrade the MongoDB we use for running server tests to v5.
> chore: Upgrade test MongoDB to v5

- app/client/src/pages/Editor/JSEditor/Form.tsx
- app/client/src/pages/Editor/JSEditor/utils.ts
> Adding a check for execute permission to display the line gutter on the JS Object editor
Fixes [#19183](https://github.com/appsmithorg/appsmith/issues/19183)
> This works as expected now and the line gutter icon is now seen only if you have execute access on the JS Object editor.
- Manual
> fix: Adding a check for execute permission to display the line gutter on the JS Object editor

- app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppSmithErrorWebExceptionHandler.java
We handle this in the global error handler, looking for the error message that indicates this cause, and include a cookie deletion header, so the user can recover by logging in again.
> fix: Logout user, if session deserialization fails

- app/client/src/reducers/entityReducers/actionsReducer.tsx
> Removing temporarily copied action to a page when API responds with an error.
Fixes [#19159](https://github.com/appsmithorg/appsmith/issues/19159)
> Tested the same scenario locally. The issue was with coping an action to another page that doesn't have a create action permission. Fixed that in this PR and it reverts to the old state without page refresh when API responds with an error. Moving the action works fine with an error response from API. Didn't need any fixing.
- Manual
> fix: Removing temporarily copied action to a page when API responds with an error

- app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx
> Adding permission checks on save & edit datasource buttons next to API field
Fixes #19248 
> Works now based on permission.
- Manual
> fix: Adding permission checks on save & edit datasource buttons next to API field

- app/client/src/sagas/PageSagas.tsx
> Fetching page by id when new page is created via crud API to fix page error saying you do not have access to edit the page.
Fixes [#19222](https://github.com/appsmithorg/appsmith/issues/19222)
> Tested it with the steps provided in the issue. It works fine now without any error.
- Manual
> fix: Fetching page by id when new page is created via crud API

- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/UserAndAccessManagementServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/WorkspaceServiceTest.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ShareWorkspacePermissionTests.java
Fixes #19244 
Fixes #17606
If an existing member is invited again from the Share modal with a different role, the user gets assigned the other role as well. This breaks the framework that a member of the workspace can only have a SINGLE role. This breaks other flows like update role/delete member etc because they all run with the assumption that the member can not have more than one role in the workspace. This PR fixes this by throwing an error if a user is being invited again to the workspace.
> fix: invite user should not update existing member's role

- .github/workflows/perf-test.yml
Earlier code wasn't checked out correctly when test-build-docker workflow ran, this PR adds conditional checkout.
> ci: Reactor perf tests checkout step to checkout the code correctly.

- app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/PageControllerCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewPageServiceCEImpl.java
The NewPage document contains DSL details for a page as well. When we don't need this information, we can use a projection that disables this field. User was facing a problem with this call taking 12 seconds to complete with those details. (document is 1 MB in size for them)
> fix: Added projection for page call that only needs application id details

- app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
The `Add datasource` CTA in query pane is not permission driven.
Fixes #19274
- Manual
> fix: add datasource CTA in the query pane is not permission driven

- Dockerfile
- deploy/docker/templates/supervisord/application_process/backend.conf
- deploy/docker/templates/supervisord/application_process/rts.conf
- scripts/start-backend.sh
Fixes: [19207](https://github.com/appsmithorg/appsmith/issues/19207)
**By default on start-up**
```
root@ab348246fff8:/appsmith-stacks/logs# head backend/backend-ab348246fff8.log
Waiting for RTS to start ...
RTS started.
Starting Backend server...
Load environment configuration
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/appsmith/backend/server.jar!/BOOT-INF/lib/logback-classic-1.2.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/appsmith/backend/server.jar!/BOOT-INF/lib/slf4j-reload4j-1.7.36.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type …
```
> chore: Add dependency to start backend only if rts is ready

- app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/BaseAppsmithRepositoryCEImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomApplicationRepositoryCEImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomDatasourceRepositoryCEImpl.java
Projection support added as part of https://github.com/appsmithorg/appsmith/pull/18904 was undone during another refactor for the git rbac changes. Adding projection back for appsmith repository functions.
> chore: Adding projection back to BaseAppsmithRepository

- deploy/helm/templates/statefulset.yaml
- deploy/helm/values.yaml
Small enhancement to permit usage of different image registries
Fixes #18833 
- Manual
> feat: override helm chart images for init containers

- app/server/appsmith-plugins/firestorePlugin/src/main/resources/editor/addToCollection.json
- app/server/appsmith-plugins/firestorePlugin/src/main/resources/editor/createDocument.json
- app/server/appsmith-plugins/firestorePlugin/src/main/resources/editor/deleteDocument.json
- app/server/appsmith-plugins/firestorePlugin/src/main/resources/editor/getCollection.json
- app/server/appsmith-plugins/firestorePlugin/src/main/resources/editor/root.json
- app/server/appsmith-plugins/firestorePlugin/src/main/resources/editor/setDocument.json
- app/server/appsmith-plugins/firestorePlugin/src/main/resources/editor/updateDocument.json
The firestore query fields were very difficult to understand and use. This PR cleans up the UI to help make it simpler.
- Manual
> fix: Fix firestore plugin Configuration

- deploy/docker/utils/bin/backup.js
- deploy/docker/utils/bin/backup.test.js
- deploy/docker/utils/bin/index.js
- deploy/docker/utils/bin/mongo_shell_utils.js
- deploy/docker/utils/bin/utils.js
- deploy/docker/utils/bin/version.js
`appsmithctl version` - Util to display current Appsmith version
`appsmithctl mongo-eval '<mongo query>'  [--pretty]` - Util to run mongo queries
> feat: appsmithctl version and mongo-eval utils

- .github/workflows/perf-test.yml
With the latest build, we’ve upgraded to Java 17.   By default, Ubuntu ships with Java 11.
> ci: Add java setup step to perf-test workflow

- app/client/src/widgets/ListWidgetV2/index.ts
- app/client/src/widgets/withWidgetProps.tsx
widgetProps of BottomRow, RightColumn, and minHeight all had values of `NaN` but the props had their correct value.
So switching this when it's either `undefined` or `NaN` fixed the issue.
Although, further investigation should be done why it gets `NaN` or `undefined`
Fixes #19498
- Manual
> fix: dropping of canvas widget issue.

- app/client/package.json
- app/client/src/pages/workspace/AppInviteUsersForm.tsx
- app/client/yarn.lock
> Updating the input field placeholder on app invite users modal
Fixes [#19506](https://github.com/appsmithorg/appsmith/issues/19506)
> Visited the edit page of an application and clicked on the share modal to check the input field placeholder on the invite modal. Group(s) is no longer seen on the release cloud, as expected.
- Manual
> fix: Updating the input field placeholder on app invite users modal

- app/client/src/widgets/ListWidgetV2/index.ts
Replicated the behaviour in List v1 to disabled the auto height property in all the child widgets.
Fixes #19503 
Media
- Manual
- Jest
- Cypress
> …
> feat: listv2 disable auto height for all child widgets

- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/RefactoringSolutionCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ce/RefactoringSolutionCEImplTest.java
- app/server/appsmith-server/src/test/resources/com/appsmith/server/solutions/ce/refactorDslWithOnlyWidgets.json
- app/server/appsmith-server/src/test/resources/com/appsmith/server/solutions/ce/refactorDslWithOnlyWidgetsWithNewList.json
If a widget was being refactored from `Text1` to `Text2`, and the same application had a List widget with a template widget of the name `Text12`, then the refactor logic was breaking the recalculation of dynamic binding path list. This fix checks for the complete name instead of a partial match.
Reproduction and context:
https://theappsmith.slack.com/archives/C02JV8G1MP0/p1672388698340299?thread_ts=1671080059.752969&cid=C02JV8G1MP0
Fixes one cause of #10037 
- Manual
- Junit
> fix: Fixed an edge case with refactoring widget names similar to template widget names

- app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
In case decryption of an existing value fails, ignore that field for re-encryption.
> fix: Corrupted encryption cannot be re-encrypted

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug16683_Spec.ts
- app/client/cypress/support/Pages/ApiPage.ts
- app/client/src/utils/ApiPaneUtils.tsx
This PR fixes API query params from being truncated when a dynamic binding expression is added to the API Url.
Fixes #16683 
- Cypress
> fix: Fix api url binding params

- app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts
since `currentItem` uses `TEMPLATE` as `evaluationSubstitutionType` and can't be made to be dynamic depending on its value, passing the stringified value in `{{ }}` would evaluate the string back to it's original value
Fixes #19652 
- Cypress
> fix: incorrect currentItem value

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/ApplicationURL_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/ForkApplication_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Workspace/ShareAppTests_spec.js
- app/client/src/ce/sagas/userSagas.tsx
The segment initialization for the anonymous user is creating a race condition and due to that two cypress test have become flaky(ShareAppTests_spec.js and ApplicationURL_spec.js). Temporarily commenting it out in this PR and will enable it after fixing the race condition.
Media
> A video or a GIF is preferred. when using Loom, don’t embed it because it looks like it’s a GIF. instead, just link to the video
> Please describe the tests that you ran to verify your changes. Provide …
> chore: send static anonymous id for anonymous users in usage pulse call

- app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/QueryPane/EmptyDataSource_spec.js
- app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java
- app/server/appsmith-plugins/postgresPlugin/src/test/java/com/external/plugins/PostgresPluginTest.java
- The PR removes the empty password validation check for PostgreSQL while creating a new data source.
- The JUnit test case is added for the same. Implemented using a separate PostgreSQL container with Trust Authentication enabled for the Same.
- Please note for testing from UI perspective we have to create a user with Trust auth enabled to validate the above changes.
Fixes  #14003
- Bug Fix(non-breaking change which adds functionality)
- Manual
- JUnit TC added
> fix: PostgreSQL Trust Authentication Login

- app/client/yarn.lock
While building the application, there was a warning about outdated browserlist. This PR updates that and removes that warning.
Media
Warning
No warning
- Manual
- Jest
- Cypress
> chore: update browser list

- .github/workflows/test-build-docker-image.yml
Add JAVA setup step to perf tests in test build workflow.
This is a possible fix for perf tests on running because backend server was not up.
> ci: Add JAVA setup step to perf tests in test build workflow

- app/client/cypress/fixtures/Listv2/simpleListWithCurrencyWidget.json
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/ListV2/Childwigets/List_Inputs_spec.js
- app/client/src/widgets/CurrencyInputWidget/widget/index.tsx
When a value is large, it is represented in formatted text i.e if value is 123456789 then it is shown as 123,456,789. Once a page is revisited, the meta prop `text` already has a value i.e `123,456,789` and on component mount of CurrencyWidget, the `formatText` is called by default. This in turn calls the function `parseFloat("123,456,789")` which trims everything.
Added a check to only format the text if it is in a non-formatted form. 
Fixes #19787 
Media
[LOOM](https://www.loom.com/share/b3c00efe6b8f48ad84b942bee7073afa)
- Cypress
> fix: List v2 - Currency widget text trim of page change

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug15909_Spec.ts
- app/client/src/sagas/EvaluationsSaga.ts
- app/client/src/sagas/PostEvaluationSagas.ts
- app/client/src/selectors/entitiesSelector.ts
- app/client/src/utils/autocomplete/dataTreeTypeDefCreator.ts
This PR adds JS function data to autocompletion hints
Fixes #15909 
Cypress
> fix: Show JS Function data in autocompletion hints

- deploy/helm/Chart.yaml
- deploy/helm/templates/ingress.yaml
- deploy/helm/templates/statefulset.yaml
- deploy/helm/values.yaml
- Updated ngnix as default ingress class in `values.yaml`
- Upgraded mongo's deployment image to `v5.0.12` as the previous 4.4.11 is deprecated
- Added `imagePullSecrets` to enable pulling images from private docker registries
- Added conditional to check for k8s version >=1.1.8 to handle both old and new k8s version scenarios for setting up the Ingress controller class name.
> fix: helm install values checks

- app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/InstanceConfig.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CacheableRepositoryHelperCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CacheableRepositoryHelperCEImpl.java
1. Pre fetch and set the anonymous user cache instead of fetching it when its required. This is now done on startup. In case any request for anonymous user permission group ids comes through and the cache is not ready, we throw an error to request the user to try again in some time. This stops the DDOS on the mongo database
2. In case the session is in bad state and the user object is malformed, before we fetch the user permission group ids, we check the presence of email, tenant and user id before making a bad database query which was another reason for DDOS.
> fix: This fixes the DDOS that appsmith production database faced when the sessions set in redis were in bad state.

- app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/UsagePulseControllerCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UsagePulseServiceCEImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java
> As we are using updateUser method within UsagePulse (`api/v1/usage-pulse`) API to update the hashedEmail. This requires the user to possess required permission but as this is a internal usecase it's safe to expose a method to perform the update operation.
Fixes https://github.com/appsmithorg/cloud-services/issues/226
- Manual
> fix: Usage pulse delivery for invalid user where manage user permission is missing 

- app/client/src/workers/Linting/utils.ts
Linting was broken in EE repo.
Since ActionTriggerFunctionName is imported from `ce/entities/DataTree/actionTriggers`.
Changed to `@appsmith/entities/DataTree/actionTriggers` namespace.
> chore: update import for ActionTriggerFunctionNames

- app/client/src/sagas/ApiPaneSagas.ts
- app/client/src/utils/ApiPaneUtils.tsx
This issue occurs when users switch the datasource of an API action, and the actionConfiguration headers is empty. This PR adds conditional checks to prevent an error from happening.
Fixes #18682
Media
> fix: Return undefined for nonexistent action headers

- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Datepicker/DatePicker2_spec.js
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Datepicker/DatePickerV2Updated_spec.js
- app/client/src/widgets/DatePickerWidget2/component/index.tsx
- app/client/src/widgets/DatePickerWidget2/widget/index.tsx
- app/client/src/widgets/JSONFormWidget/fields/DateField.tsx
Visual support for required state for date picker did not exist earlier this PR fixes it. It shows a danger border when required condition is not fulfilled.
Fixes # (#19547)
- Manual
- Cypres
https://github.com/appsmithorg/TestSmith/issues/2165
> fix: date picker required fix (#19547)

- app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitUtils.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/GitUtilsTest.java
> When the git service is self hosted, one can chose to not to set up a domain name. But this set up does not work with the current git sync feature. This PR fixes this bug by supporting such use cases. 
Fixes https://github.com/appsmithorg/appsmith/issues/19878
- Manual
- JUnit
> fix: Add support for the shh url that does not contain domain name

- app/client/src/workers/Evaluation/evaluate.ts
- app/server/appsmith-server/src/main/resources/features/init-flags.yml
Enables JS libs for all users without removing the references of feature flag code.
- Manual
> chore: disable JS Libs feature flag 

- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImplV2.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceV2Tests.java
> Instead of the generic error message which confuses the user during the git sync failure due to the hydration from file to db or vice versa, we are now showing a better error message which does not confuse the user. 
- Manual
> fix:use correct error message for git import failures

- app/client/src/pages/common/PageHeader.tsx
- app/client/src/pages/common/ProfileDropdown.tsx
license error page for non-admin users. Added an option to hide the edit profile link from the profile dropdown in the header.
Fixes https://github.com/appsmithorg/cloud-services/issues/209
- Manual
- Jest
- Cypress
> chore: code split changes for license error page for non admin user

- app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datasources/GraphQL_spec.ts
- This PR skips the GraphQL cases until the endpoint used in the spec responds or is changed to point to TED GraphQL
> test: Skipping GraphQL tests until endpoint responds to unblock CI

- app/client/src/ce/sagas/userSagas.tsx
For anonymous users, we need segment id, so if telemetry is off we're initiating the segment without tracking and once we get the id, the analytics object is purged.
Fixes https://github.com/appsmithorg/cloud-services/issues/231
- Manual
- Jest
- Cypress
> chore: send anonymous id from segment for anonymous users in usage pulse call

- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/DecryptedSensitiveFields.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImplV2.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceV2Tests.java
When an application is exported with credentials i.e. template application, it does not contain the bearer token authentication credentials. As a result, when user is trying to import this application, the datasource configuration popup appears. This PR fixes this issue.
TL;DR enable export-import application with bearer token authentication
Fixes #19415 
Media
- Manual
- Jest
> fix: Forking fails when template has REST datasource with Bearer Token Authentication

- deploy/docker/entrypoint.sh
- Updated redis.conf to set the Redis rdb directory to `/appsmith-stacks/data/redis` bind-mount directory, so that the data is persisted after the container restarts/updates. ( This was causing user sessions on Appsmith installations using the embedded Redis to reset after every container restart, since the redis data was not being persisted)
- Updated redis.conf for the embedded Redis to increase the snapshot frequency to dump after every 15 sec if at least 1 key changed
Fixes #19768
- Manual
> fix: Redis rdb persistance | User session persistance

- app/client/cypress/fixtures/Listv2/listWithServerSideData.json
- app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_BasicServerSideData_spec.js
- app/client/src/widgets/ListWidgetV2/widget/index.tsx
When the server side list widget is reset, the page no resets to 1 and if it resets from a higher page; the `On Page Change` query should re-trigger to get the latest data for page 1.
Fixes #19940
Fixes issue 17 in the [tracker](https://docs.google.com/spreadsheets/d/1kWosVCH622m9hohVKyFRdrr7TUa_exO8thwjo8Aqe2M/edit#gid=0)
- Manual
- Cypress
> fix: List widget with serverside enabled, resetting should re-trigger page change query

- app/client/start-https.sh
We use `APPSMITH_ALLOWED_FRAME_ANCESTORS` env variable to determine the CSP value for `frame-ancestors` in the Docker container, but we don't do this in the `start-https.sh` script, which is used during development. This PR fixes this inconsistency.
> chore: Add frame-ancestors CSP during dev time

- app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/InstanceConfig.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ExampleApplicationsAreMarked.java
Testcases were flaky because loading cache after application is ready is happening in async with testcases, so sometimes testcases fails if cache is not loaded by the time testcase executes.
Testcases fail and gives the following error message `Appsmith server is not ready. Please try again in some time`
This fixes the issue by running startup process in sync after application is ready.
And there is a genuine failure of testcase `exampleApplicationsAreMarked` which is fixed.
> fix: flaky tests due to startup happening async

- app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Tenant.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/TenantServiceImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/TenantServiceCEImpl.java
In the tenant response, this PR adds the current `instanceId` to the tenant response.
Why do we need it? This will be used to power the `Upgrade` buttons in Admin Settings to start the U&B flow.
Why add it to the tenant API? So that for U&B flows on the cloud, we can add something like a `tenantId` there, in the same request, so this felt like the right place.
Potential performance impact? Unlikely. The `instanceId` is permanently cached in the process memory, so this is a one-time DB-call, in the lifetime of the server process.
> feat: Add `instanceId` in tenant response

- .github/workflows/build-deploy-preview.yml
- .github/workflows/on-demand-build-docker-image-deploy-preview.yml
- scripts/deploy_preview.sh
Successful-run: https://github.com/appsmithorg/appsmith-ci/actions/runs/3986060223
Example: https://github.com/appsmithorg/appsmith-ci/pull/2
[Reference](https://github.com/appsmithorg/appsmith-ci/pull/2#issuecomment-1400174700) 
go ahead and comment:
```
/build-deploy-preview
```
If the commit is fine then you should another comment from github-actions like below
```
Tests running at: https://github.com/appsmithorg/appsmith-ci/actions/runs/xxxxxx
Workflow: On demand build Image and deploy Deploy-Preview.
PR: #.
URL: #ce.appsmith.com
```
> chore: Deploy preview of a PR

- app/client/src/pages/common/CanvasArenas/hooks/useBlocksToBeDraggedOnCanvas.ts
Regardless of where we drop the Modal widget, its parent should be MAIN_CONTAINER_WIDGET_ID
fixes: #19601
> fix: Modal dropped inside a widget getting limited to parent size

- .github/workflows/perf-test.yml
- app/client/cypress/setup-test-ci.sh
> Add back setup of ui nginx environment using docker while setting up tests
Fixes # [(issue)](https://github.com/appsmithorg/appsmith/issues/20124)
- Manual
> Fix: add back setup of ui environment in setup-test-ci workflow

- app/client/src/widgets/TableWidget/component/TableAction.tsx
- app/client/src/widgets/TableWidget/component/TableStyledWrappers.tsx
Added a bottom border to the entire table header div element.
Fixes #18339 
- Manual
> fix: table border issue fix (#18339)

- app/client/src/widgets/CheckboxGroupWidget/component/index.tsx
> In CheckBoxGroupComponent, when `isSelectAll` is enabled, it takes two clicks to check/uncheck it rather then one. The reason for this issue was, the custom className `select-all` given to `StyledCheckbox` component. The same className is available from tailwind which adds the `user-select: all` property, making the label text of select all option to be selectable. So it used to select the text on first click, and then used to check the select all option on second click.
Fixes #18880 
- Manual
> fix: resolve issue of double click to select all in checkbox group

- app/client/src/widgets/CheckboxGroupWidget/component/index.tsx
> This `SelectAll` component was using `isDisabled` prop internally, but the disabled state was passed in `disabled` prop. Although the internal `ChecboxLabel` component is using disabled prop, so to make `SelectAll`'s disabled prop name consistent, I used `disabled` prop, rather than `isDisabled`.
Fixes #18208 
- Manual
> fix: resolve issue of inconsistent color of select all label in disabled state.

- app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/TableV2/Add_new_row_spec.js
- app/client/src/widgets/TableWidgetV2/component/Table.tsx
An enabled add new button was hidden when other header components are disabled, this PR fixes it. 
Fixes  #19762
- Manual
- Cypress
> fix: add new button is always visible as long as it is enabled (#19762)

- app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java
- app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java
- In case of MySQL the JSON DB type is stored as a binary object in the DB. This is different from MariaDB where it is stored as a text.Since we currently use MariaDB driver for MySQL plugin as well the driver reads the JSON DB type data as byte array. This PR adds change to convert this byte array to string before sending back the response. 
- Currently, we assume utf-8 encoding when reading the data back into JSON string (since MySQL uses a subset by default ie. utf-8mb3/4), however other encodings can be configured. I have created a new feature request to track it: https://github.com/appsmithorg/appsmith/issues/20088
Fixes #19867 
- Manual
- JUnit
> Link issues raised during DP …
> fix: MySQL Plugin: update handling of JSON DB type

- app/client/src/widgets/TableWidgetV2/widget/propertyConfig/PanelConfig/DateProperties.ts
This PR removes the condition where on Image date column type hidden property is false
Fixes #20173
- Manual
- Make sure that date settings is not available in any other column type
- Make sure that date settings is only available when column type is date and editable is true
> fix: date settings visibility for different column types

- app/client/cypress/integration/Regression_TestSuite/ClientSideTests/JSLibrary/Library_spec.ts
- app/client/src/workers/Evaluation/__tests__/evaluate.test.ts
- app/client/src/workers/Evaluation/handlers/jsLibrary.ts
- app/client/src/workers/Evaluation/handlers/setupEvalEnv.ts
- app/client/src/workers/common/JSLibrary/index.ts
Fixes a bug where application in edit mode loses references to installed libraries immediately after it is deployed.
Fixes #20245 
- Manual
- Cypress
Add a test case to the existing [test plan](https://github.com/appsmithorg/TestSmith/issues/2125) on custom libraries
> fix: missing reference to installed libraries when an application is deployed

- deploy/helm/Chart.lock
- deploy/helm/Chart.yaml
Fixes: [20000](https://github.com/appsmithorg/appsmith/issues/20000)
- [Bug]: Update appsmith version from 1.16.0 to the current 1.9.4 version
* Though we deploy the latest appsmith version. In the helm chart we show that we are deploying appsmith version as 1.16.0 and its confusing . We are now fixing it with this PR
- Correct helm chart versions for redis and mongo. This, helps in deploying the desired versions of redis and mongo which appsmith supports. 
*  Previously, When we deploy appsmith along with redis and mongo . It used to deploy redis v7.0.4 and mongo v6.0.3.
with this changes we deploy the supported versions of redis and mongo which is v6 and v5 respectively.
before:
```
I have no name!@tempappsmith-mongodb-0:/$ mongosh
Current Mongosh Log ID:	63d2128c2e4dabde5a68f8f8 …
```
> fix: update chart.lock and app versions

- app/client/src/sagas/GitSyncSagas.ts
We will queue all requests to the git api to match the implementation on the server. This way we do not have parallel git related requests to the server which could cause weird ui behaviour.
> Queue git related actions from client to improve stability
Fixes #20218
Media
https://user-images.githubusercontent.com/12022471/215749012-9b76cbd0-bcdd-4a3d-8f71-5253af8374f5.mov
- Manual
> feat: Git actions queue

- deploy/aws_ami/docker-compose.yml
- deploy/docker/README.md
- deploy/docker/docker-compose.yml
We're `watchtower:latest-dev` image for the `--schedule` support. This was only available in the `latest-dev` version of Watchtower.
Now, this feature is available in the `latest` version of Watchtower, so we should be fine switching back to `latest`.
More importantly, the `latest-dev` version of Watchtower, doesn't have ARM images built. It only has AMD images built today. So this watchtower service fails to start on ARM architectures. This PR fixes that.
> fix: Change watchtower to latest

- app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ExchangeUtils.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/UserSignupCEImpl.java
The problem was that the Mono returned by `analyticsService.sendEvent` was returned inside a `.map` call, which, (almost) always results in a bug.
This PR fixes that.
> chore: Fix Installation complete event not being sent

- app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ExplorerTests/Scrolling_Spec.ts
- app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Git/GitImport/GitImport_spec.js
- app/client/cypress/support/Pages/AggregateHelper.ts
- app/client/cypress/support/Pages/GitSync.ts
- Skipping GitImport & Scrolling specs which are flaky in CI to unblock PR's merge
- Will be analysed more & added back to running suite
> test: Skipping Cypress flaky tests to unblock CI

- app/server/entrypoint.sh
Since Spring 6/JDK 17 upgrade, our analytics code errors out unless we expose the `java.time` module to our project. This has been fixed for fat container scripts, but slim containers were not updated. This PR makes the same changes to slim containers.
Fixes #20323
- Manual
> fix: Added JVM arg to opens java.time module to project

- app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/ProjectProperties.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/UserUtilsCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomUserDataRepositoryCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomUserDataRepositoryCEImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/AnalyticsServiceImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AnalyticsServiceCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AnalyticsServiceCEImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserDataServiceCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserDataServiceCEImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ReleaseNotesServiceCEImpl.java
Currently, analytics events don't include Appsmith version information. This PR adds version, and edition information to all events.
> chore: Add version to analytics events

- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/HealthCheckServiceCEImpl.java
The current Redis timeout of 1s is triggering a lot of false-positives, where we report as down, but operate just fine. In this PR, we change this to 3s, in an attempt to reduce the number of such false-positives.
We increase it to 3s _only_, just so we don't change too much too fast. If this also creates too many false-positives, we revisit.
> chore: Increase Redis timeout in /health from 1s to 3s

- app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/ListV2/Childwigets/List_Modal_Stats_Check_Radio_spec.js
- app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_event_bindings.js
- app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.test.ts
- app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts
The new logic to asses if a particular item is template item was not implemented in case of the parent container cache calculation. This resulted in incorrect value population in the cache.
Refactored the cache generation to DRY the code.
https://docs.google.com/spreadsheets/d/1kWosVCH622m9hohVKyFRdrr7TUa_exO8thwjo8Aqe2M/edit?pli=1#gid=1460346791&range=12:12
Fixes #20344
- Manual
- Jests
- Cypress
> fix: list v2 nested list container widget reference

- app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationSuccessHandlerCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/CustomServerOAuth2AuthorizationRequestResolverCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/constants/Security.java
> Cognito returns **Malformed URI** for redirect when User tries to Login. Due to this, browser ends up throwing `400 Bad Request`. In order to fix this, we have removed the padding from the `state` query parameter which we send to the OIDC, in order to avoid the cases where the additional `=` will lead to malformed URIs being created. Read [here](https://stackoverflow.com/questions/6916805/why-does-a-base64-encoded-string-have-an-sign-at-the-end) for Additional information on the Base64 encoding and padding.
> Also, we are changing the delimiter from `=` to `-` when server tries to find the redirect URI for other use cases.
> Server uses `,` in order to split the state to get the `origin value`. Now we will use `@` instead of `,`.
> TL;DR, remove `=` and `,` in order to avoid malformed …
> fix: remove padding from state used in OIDC authorise

- .github/workflows/ci-test.yml
- This PR Stops SSH which is run on port 22 for enabling it for Local Gitea support from TED
> test: TED support for GITEA

- .github/workflows/ci-test.yml
- This PR reverts https://github.com/appsmithorg/appsmith/pull/20471
- ci-test yml file update
> test: TED support for GITEA (stop ssh revert)

- app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/Modal/Modal_focus_spec.js
- app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/Modal/Modal_functionaliy_spec.js
- app/client/src/widgets/ModalWidget/component/index.tsx
This fix checks the modal's content and check if any of the input widgets state has autofocused enabled. If it does it allows the html autoofocus attribute to resolve the focus state and if not the focus is shifted to the modal.
Fixes #19957 
- Manual
- cypress
> https://github.com/appsmithorg/TestSmith/issues/2183
> fix: modal autofocus fix issue #19957

- app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java
Added a new AppsmithError to handle invalid license key.
- Manual
> chore: Added AppsmithError for invalid license key entered

- app/client/src/ce/utils/adminSettingsHelpers.ts
- app/client/src/sagas/ErrorSagas.tsx
> Adding a soft trigger for login with SSO in embedded apps as a BE feature only
Fixes [#19527](https://github.com/appsmithorg/appsmith/issues/19527)
> Tested out locally with Google/Github/OIDC/SAML. Works as BE feature only. 
- Manual
> chore: Adding a soft trigger for login with SSO in embedded apps as a BE feature only

- app/server/.run/ServerApplication.run.xml
- app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/UsagePulseServiceImpl.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UsagePulseServiceCEImpl.java
- app/server/appsmith-server/src/test/java/com/appsmith/server/services/UsagePulseServiceTest.java
> We are working on usage and billing feature and as a part of usage calculation, we are recording the usage pulses at 1 hr intervals today. As the business cases are evolving we received a request to log the pulses for every 5mins instead of an hour. Just to provide the existing stats for the past month on our cloud alone we have received 155545 pulses with 1hr intervals between the pulses. Also going forward if are doing it with 5mins intervals this count is going to increase by 12 folds. Now considering we will not be monetising the cloud platform until multi-tenancy is out, do we have usecase where we still need the usage data? If not we would like to stop recording these usage pulses on Appsmith cloud and bring it back after multitenancy is live. Until then self-hosted EE instances …
> chore: Remove usage pulse logging for Appsmith cloud

- app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java
- app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java
- Currently, the code for destroying MySQL connection is incorrect. Hence, MySQL plugin is not able to close connections that are no longer required resulting in connection leak. This PR fixes it.
Fixes #20552
- Manual
- To test it manually: (1) check number of open conn to MySQL DB (2) click on `Test` datasource button for a successful test (3) check the number of open connections again and verify that number of conn is same as in step (1) 
- JUnit TC
> fix: MySQL Plugin: fix connection leak in datasource destroy

- deploy/docker/scripts/run-java.sh
When we have `NO_PROXY=localhost,one.com,two.com,three.com`, then the current implementation will pass the following to the backend server:
```
localhost|one.com,two.com,three.com
```
This will mean that only `localhost` will bypass the proxy, which is not what's expected.
This PR fixes this problem, so that the following is sent to the backend server:
```
localhost|one.com|two.com|three.com
```
This will mean that requests to all four of them, will bypass the proxy, as expected.
> fix: NO_PROXY not set correctly on backend server

- app/rts/src/server.ts
- app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonConfig.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/InstanceConfig.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AstServiceCEImpl.java
- app/server/appsmith-server/src/main/resources/application.properties
- deploy/docker/templates/nginx/nginx-app-http.conf.template.sh
- deploy/docker/templates/nginx/nginx-app-https.conf.template.sh
Issue: Nginx and RTS used the same env PORT for binding it's service, while the backend server had the rts port hardcoded on its rts uri.
- Renamed env PORT to APPSMITH_RTS_PORT for starting the rts server.
- Updated nginx config templates to use env `APPSMITH_RTS_PORT`
- Added appsmith.rts.port property in server to use env APPSMITH_RTS_PORT
- Updated CommonConfig.java rtsBaseDomain to use appsmith.rts.port
> fix: renamed rts port env to APPSMITH_RTS_PORT

- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/RequestCaptureFilter.java
- app/server/appsmith-interfaces/src/main/java/com/appsmith/util/WebClientUtils.java
- app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
We're missing a filter to check for requests that contain a direct IP address, that's listed in the disallow-list. This PR fixes that.
> fix: Issue with filter not working with IPs

- app/client/src/pages/Editor/Canvas.tsx
- app/client/src/pages/Editor/WidgetsEditor/CanvasContainer.tsx
Scaling applied on the top level of the canvas was causing the modal to be limited to the canvas. This will remove scaling for now to fix the issue and will pick up a better scaling strategy instead
> Bug fix for issue introduced in modals when working with multi pane layout 
Fixes #19657
- Manual
> fix: modal opening issue

- app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/MustacheHelper.java
- app/server/appsmith-interfaces/src/test/java/com/appsmith/external/helpers/MustacheHelperTest.java
- app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
Appsmith always treats something as dynamic binding if it follows this pattern `{{.*}}`. This behavior leads to experiencing some edge cases when the value of the binding contains a pattern like the above. Before this fix, if the no value is found for binding it would get replaced by `null`.
In this PR it won't get replaced by `null` rather the original string prevails.
Fixes #11688 
Media
- Manual
- JUnit
> fix: Do not replace binding with `null` if no value found (#11688)

- deploy/docker/entrypoint.sh
When running on CPUs without an AVX instruction, the embedded MongoDB cannot run. It fails to run with a cryptic error message, and they are forced to reach out to support for help.
This PR adds a check, and a warning message, if trying to use embedded MongoDB on a CPU without the AVX instruction.
> fix: Check for AVX instruction, and produce a warning

- contributions/ServerSetup.md
Add steps to convert stand alone to clustered set up for mongodb containers in server set up guide.
> docs: Add steps to enable the replica set for mongodb

- app/client/src/sagas/GitSyncSagas.ts
Changes made in the PR - https://github.com/appsmithorg/appsmith/pull/20258 were reverted by file lock PR to test a few scenarios but forgot to undo them and got merged to release. 
So this PR adds the changes done by the original PR
> chore: Undo the git actions queue changes

- app/client/src/widgets/TextWidget/component/index.tsx
Swapping `word-break: break-all;` to `overflow-wrap: break-word;` in the "Show more" modal.
Before
After
Fixes https://github.com/appsmithorg/appsmith/issues/20413
Bug fix (non-breaking change which fixes an issue)
Manual
> fix: change word truncate behavior in show more modal

- app/client/docker/templates/nginx-app-http.conf.template
- app/client/docker/templates/nginx-app-https.conf.template
- app/client/docker/templates/nginx-app.conf.template
- app/client/start-https.sh
- app/server/appsmith-server/src/main/resources/application.properties
- deploy/docker/templates/nginx/nginx-app-http.conf.template.sh
- deploy/docker/templates/nginx/nginx-app-https.conf.template.sh
- deploy/template/nginx_app.conf.sh
We're increasing the default limit of request payload on cloud so that 100 MB files that are base 64 encoded can also be uploaded via Appsmith.
Fixes #20424
- Manual
> fix: Increased Nginx limit to 150 MB to allow 100 MB Base 64 encoded files

- .github/workflows/ci-test.yml
- Specifying the branch name to pull from ci-oldstack in ci-test.yml
- ci-test.yml
- Cypress
> ci: Specifying the branch name to pull from ci-oldstack in ci-test.yml

- .github/workflows/ci-test.yml
- Updated the pat to access appsmithorg/ci-oldstack
- Cypress
> ci: Updated the pat to access appsmithorg/ci-oldstack

- app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/TableV2/TableV2_misc.js
- app/client/src/widgets/TableWidgetV2/constants.ts
- app/client/src/widgets/TableWidgetV2/widget/index.tsx
When user adds any sort of binding to the column name of a table from property pane Columns section, the table breaks.
This was happening because of the column label getting stored as undefined or as an object that the binding evaluates to.
Only string values are expected in column label. Hence the table was breaking for non string values of column label.
This PR fixes this issue by replacing the column name with a default text "customColumn" whenever the column label is not of type string
https://www.loom.com/share/1c5feab1aafa43abaac757d853a02770
Fixes #20663 
- Cypress
> https://github.com/appsmithorg/TestSmith/issues/2188
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on …
> fix: Table breaks on adding binding to column name

- app/client/src/ce/pages/AdminSettings/config/general.tsx
- app/client/src/ce/pages/workspace/Members.tsx
- app/client/src/ce/pages/workspace/WorkspaceInviteUsersForm.tsx
> Updating profile image API URL for members page and invite modal. 
> Also, changing the telemetry setting on the Admin settings page from toggle to checkbox for better UX.
> Updating invite user event payload.
Fixes [#19453](https://github.com/appsmithorg/appsmith/issues/19453) [#20492](https://github.com/appsmithorg/appsmith/issues/20492)
Media
> Tested both the above changes manually on local and it works as expected.
- Manual
- Jest
- Cypress
> fix: Updating profile image API url for members page and invite modal

- deploy/docker/utils/bin/mongo_shell_utils.js
The cmd util appsmithctl now used `mongosh` instead of the legacy `mongo` shell.
> fix: update mongo cmd in evalMongo to use mongosh

- .github/workflows/server-build.yml
This is needed for writing tests using the Env API.
> ci: Add APPSMITH_ENVFILE_PATH to server workflow

- deploy/docker/scripts/run-java.sh
Appsmith supports running with a HTTP proxy, that can be configured with `HTTP_PROXY` or `HTTPS_PROXY` env variables. Like this:
```sh
HTTP_PROXY=http://myproxy:8080
HTTPS_PROXY=http://myproxy:8443
```
However, this proxy support didn't support authentication. This PR implements that. Now, proxy with authentication can be configured like this:
```sh
HTTP_PROXY=http://user:password@myproxy:8080
HTTPS_PROXY=http://user:password@myproxy:8080
```
This is not syntax or standards invented by Appsmith. This is the standard way proxy is usually configured.
Fixes #16330
🍰
> feat: Support for proxy authentication

- app/client/src/components/editorComponents/DropTargetComponent.tsx
When we drag a widget within a container like widget, the container expands instantly. However, when we don't drop the widget and bring the mouse point outside the canvas, the auto height fails to kick in, as no action has been performed. This results in the container like widget's  height to remain as it was. This leads to incorrect height for the container like widget. 
This PR fixes it by forcing a new computation when the container like widget's internal canvas receives a new height.
Fixes #20907 
Media
Before
https://user-images.githubusercontent.com/103687/220900648-81cb5a0e-9aea-4d21-901e-29a8aa99c6b2.mov
After
https://user-images.githubusercontent.com/103687/220900630-725929dc-ce87-4b92-aec4-1305acd79e18.mov
- Bug fix (non-breaking …
> fix: force auto height on no drop

- app/client/src/ce/workers/Evaluation/evaluationUtils.test.ts
- app/client/src/ce/workers/Evaluation/evaluationUtils.ts
- app/client/src/workers/common/DataTreeEvaluator/index.ts
Cause of issue
During evaluation, JS Functions are stored as String objects, rather than string literals. This was done to allow us to add a ".data" property to it.
Solution
Before translating diffs, String objects should be converted to literals, and separated from the ".data" field
Fixes #20893 
-WIP
> fix: incorrect jsfunction diff

- app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/InstanceConfig.java
In cloud services logs we are experiencing tons of `415 application/octet-stream `exceptions  related to the `api/v1/installation`. i.e when we register a new instance from the cloud services. as a consequence instance ids can't be registered.
This might be happening due to automatic setting of content-type to octet-stream, can't say for sure.
Here we are enforcing a "application/json" content-type.
- We are also experiencing unauthorised access exception logs thrown when we try to get remote plugins for the instance 
on endpoint `api/v1/plugins?instanceId={{instanceId}}` 
According to our hypothesis this one is thrown because the instance couldn't be registered in first place. hence the repo has no history of this particular instance id
> TL;DR enforced a application/json content type on …
> fix: enforcing content-type header while registering the instance id

- app/client/src/utils/helpers.tsx
- app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationSuccessHandlerCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCE.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCEImpl.java
> Updating the SignUp success flow to take into account, if the new User can create Workspace or not.
> Issue: 
> When the admin revokes the Create Workspace permission, the existing flow is still trying to create the workflow post the signup, which throws an Internal Server Error.
> Solution:
> A check has been introduced which will skip the Workspace Creation step, if the admin has blocked Workspace Creation from the **Default Role for All Users** role.
> Also, another change in behaviour is the redirection strategy.
> When the Create Permission is revoked, the user will land on the HomePage.
> When the permission is not revoked, user will land on a new Application with the Onboarding tutorial (this exists).
Fixes https://github.com/appsmithorg/appsmith/issues/20980
Media
> A video or a …
> fix: redirection to HomePage when CREATE WORKSPACE permission revoked from Default Role

- .github/workflows/ci-test.yml
- app/client/cypress/fixtures/datasources.json
- This PR changes the mapping port of GITEA TED form 3000 to 3001 because while building client/server locally Appsmith uses localhost:3000
- Script yml update (non-breaking change which fixes an issue)
> test: Change mapping port for GITEA to 3001

- app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Layout.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration004ResetOnPageLoadEdgesInLayouts.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/models/export/LayoutMetadata.java
- app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCEImpl.java
- app/server/appsmith-server/src/test/resources/test_assets/ActionCollectionServiceTest/mockObjects.json
Since an Appsmith application is not limited by the number of interconnections it can make, it is possible for users to create graphs so complex that we end up having MBs of data in a relatively simple page as well. This was causing failures in a user's app since they were now unable to update their app any further. We do not really use this property anywhere in our logic today, and this is essentially redundant information. This PR gets rid of the edges property from the layout and runs a migrations to clean up all existing pages as well. 
If we do find a need for this property in the future, a simple update layout on each of these pages would do the trick.
Fixes #20680 
- Manual …
> fix: Removed on page load edges from layout model

- app/client/src/widgets/SelectWidget/component/index.tsx
This PR fixes an issue reported by a sentry in which the select widget was crashing due to null selected option.
Fixes #20875
- Bug fix
- Not sure how to reproduce it so just added the null check.
> fix: Select widget isOptionSelected > TypeError: Cannot read properties of null (reading 'value')

- app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/ListV2/ListV2_nested_List_widget_spec.js
- app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_BasicChildWidgetInteraction_spec.js
- app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_Meta_Hydration_ClientSide_spec.js
- app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_Meta_Hydration_ServerSide_spec.js
- app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_autocomplete_spec.js
- app/client/cypress/support/commands.js
- app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.test.ts
- app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts
Avoid cyclic dependency in child widget when using level data to reference Parent List widget
Fixes #20793 
- Cypress
> https://github.com/appsmithorg/TestSmith/issues/2187
> fix: remove parent list widget from child widget level data

- .github/workflows/ci-test.yml
- This PR updates the ci-test.yml file to empty the failed_spec_ci folder which still holds the previoulsy (or attempt-1) failures & hence prints the attempt-1 failures also in the attempt-2 git comment in PRs.
- ci-test.yml file update
> test: Fix to remove previous failing tests from Git Comment history

- .github/workflows/client-build.yml
- .github/workflows/test-build-docker-image.yml
Effectively reverts changes from https://github.com/appsmithorg/appsmith/pull/20669, since we depend on this for usage tracking.
> ci: Use release Segment Key

- deploy/docker/entrypoint.sh
Some merge problem in the fix from https://github.com/appsmithorg/appsmith/pull/20055 caused this line to not get the change.
> fix: Use `mongosh` instead of `mongo` command in entrypoint

- app/client/docker/templates/nginx-app-http.conf.template
- app/client/docker/templates/nginx-app-https.conf.template
- app/client/docker/templates/nginx-app.conf.template
- app/client/start-https.sh
- deploy/docker/templates/nginx/nginx-app-http.conf.template.sh
- deploy/docker/templates/nginx/nginx-app-https.conf.template.sh
This reverts commit b3dbd85dbe1312faf630405f54f2003134534f1f.
This causes NGINX to fail to start if IPv6 is not available on the system.
> fix: Revert container-internal communication when using IPv6
