app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ApplicationForkingServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ApplicationForkingServiceTests.java
=> ci: Release v1.6.7

app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/RestApiImportControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/CurlImporterServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/PostmanImporterServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApiImporterCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/BaseApiImporterCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CurlImporterServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/PostmanImporterServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java
> As the branch name param was not taken into consideration when importing the curl for the application connected to git, while saving the action branchName was not getting saved which resulted in resource not found error. This PR introduces the branchName param for `create method` in `RestAPIImportControllerCE` which saves the action with branchName so that action can be identified by `defaultActionId` and `branchName`. 
Fixes #10354
> JUnit TC
> Manual Test
=> fix: Fix for import curl when app is connected to git

app/client/src/widgets/DatePickerWidget2/widget/derived.js
>  Upgrade DatePicker derived property condition 
Fixes #10317
// Code coverage diff between base branch:release and head branch: bug/form-date-picker-validation-break 
:green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0.78)** | 72.55 **(3.92)** | 100 **(0)** | 93.33 **(0.95)**
:red_circle: | app/client/src/widgets/DatePickerWidget2/widget/derived.js | 61.54 **(-38.46)** | 38.89 **(-61.11)** | 100 **(0)** | 61.54 **(-38.46)**</details>
=> fix: datepicker derived property condition updates

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/JSObject_To_ListWidgetSpec.ts
This PR skips tests from JSObject_To_ListWidgetSpec.ts until Bug #10284  is fixed
Tested on Fat container - release
// Code coverage diff between base branch:release and head branch: test/SkippingTest 
:red_circle: | total | 55.01 **(0)** | 36.6 **(0)** | 34.82 **(0)** | 55.49 **(-0.01)**
=> test: Skipping JSObjectToListWidgetSpec.ts until open bug fix

app/client/src/components/ads/TreeDropdown.tsx
> Fixed the hover selector in Treedropdown for menu item.
Fixes #10577 
- [] I have commented my code, particularly in hard-to-understand areas
=> fix: hover highlight for menu item

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_Download_validation_spec.js
=> test: Table Download test

app/client/cypress.json
Ts tests having 3rd part APIs and some flaky tests to be reworked
// Code coverage diff between base branch:release and head branch: test/TsSpec 
:green_circle: | total | 55.09 **(0)** | 36.88 **(0.01)** | 35.01 **(0)** | 55.57 **(0.01)**
=> test: commented Ts tests

app/client/src/sagas/DatasourcesSagas.ts
Fixes active source flash page upon clicking on save data source button
Fixes #8444 
Manually
// Code coverage diff between base branch:release and head branch: fix/active-datasoure-flash-page 
:green_circle: | total | 55.07 **(0.01)** | 36.57 **(0.01)** | 34.51 **(0)** | 55.58 **(0.01)**
:green_circle: | app/client/src/sagas/DatasourcesSagas.ts | 13.46 **(0.05)** | 2.4 **(0)** | 9.09 **(0)** | 15.93 **(0.06)**
:green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0.78)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0.95)**</details>
=> fix: Active datasource page flashes to user upon clicking the Save DataSource Button.

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CurlImporterServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CurlImporterServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java
> When the application is connected to git and user tries to import a curl it's working fine for default branched application but fails if user creates a sub-branch from the default branch and then tries to import the curl.
Fixes #10637
> Junit TC
> Manual test
=> fix: Bugfix for curl import in the child branch when application is connected to git

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/exceptions/pluginExceptions/AppsmithPluginError.java, app/server/appsmith-plugins/saasPlugin/src/main/java/com/external/plugins/SaasPlugin.java
=> fix: Removed tracking on Sentry for unsupported plugin operation

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
> Current PR update the indexes mainly for action collection as these were missing earlier. Also added more indexes concerned with the `gitSyncIds` as we are launching the import application via Git in couple of weeks.
> Manual test run
=> chore: Update mongo indexes to improve the query performance

app/client/src/widgets/DatePickerWidget2/component/index.tsx, app/client/src/widgets/DatePickerWidget2/index.ts, app/client/src/widgets/DatePickerWidget2/widget/index.tsx
> updated closeOnSelection default value, onDateSelected logic update
Fixes #10168
// Code coverage diff between base branch:release and head branch: fix/datepicker-close 
:green_circle: | total | 55.01 **(0)** | 36.6 **(0.01)** | 34.82 **(0)** | 55.49 **(0)**
:green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0)**</details>
=> fix: updated closeOnSelection default value, onDateSelected logic update

app/client/src/pages/Editor/FormControl.tsx, app/client/src/pages/Editor/QueryEditor/helpers.tsx, app/client/src/pages/Editor/QueryEditor/index.tsx, app/client/src/selectors/formSelectors.ts
1. Wrapped the `FormControl` component with `React.memo` component to restrict the unwanted rendering due to unwanted value changes not being used by the component
2. Memoized `FormControlFactory.createControl` using `useMemo` hook to restrict the change of the created component's reference to avoid unwanted re-rendering.
3. Converted the logic of getting the `ConfigErrors` to use selector function and used `ShallowEqual` Algorithm of `React-Redux` to restrict the unwanted re-rendering of the component due to change in the `EvaluationErrors`.
`FormControl` Component was re-rendering more than 90 times for each component that got reduced to 1 time for each component on page load and was re-rendering more than 10 times that got reduced to 2 times for each component on any input change. …
=> fix: Memoized the Form Control Component reducing unwanted re-rendering

app/client/src/widgets/ListWidget/widget/index.tsx
(cherry picked from commit db3e29e15dfc16cfb4d12b9f93876399c27957ac)
This pull request is promoting the critical issue with list widget.
=> fix: Fix crash on broken list widget (#10670)

app/client/src/pages/Editor/APIEditor/ApiRightPane.tsx, app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx, app/client/src/transformers/RestAPIDatasourceFormTransformer.ts
Display Query Parameters data on the API Section cards and form.
Fixes #(9930)
Manually
// Code coverage diff between base branch:release and head branch: fix/authenticated-api-query-parameters 
:red_circle: | total | 55.04 **(-0.01)** | 36.66 **(-0.01)** | 34.97 **(0)** | 55.44 **(-0.01)**
:red_circle: | app/client/src/pages/Editor/APIEditor/ApiRightPane.tsx | 42.19 **(-2.07)** | 45 **(-5)** | 0 **(0)** | 45.61 **(-2.54)**
:red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 …
=> fix: Add query parameters to Options/Form

app/client/src/api/ApiUtils.ts
increase axios timeout for git specific APIs
- Manually
// Code coverage diff between base branch:release and head branch: increase-timeouts-git-sync-apis 
:green_circle: | app/client/src/api/ApiUtils.ts | 59.32 **(-0.33)** | 40.91 **(4.07)** | 80 **(0)** | 56.36 **(-0.24)**
=> chore: increase axios timeout for git specific APIs

app/client/src/widgets/ButtonWidget/component/index.tsx
Fix loading of recaptcha script
Fixes #10716 
=> fix: recaptcha script not loading

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ActiveDatasource/ActiveDatasource.spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/TableWidgets_NavigateTo_Validation_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Replay/Replay_Editor_spec.js
This PR contains fix for Replay_editor_spec and TableWidgets_NavigateTo_Validaton_spec.
Locally 
// Code coverage diff between base branch:release and head branch: FlakyTestsFix 
:green_circle: | total | 55 **(0)** | 36.49 **(0.01)** | 34.71 **(0)** | 55.4 **(0)**
=> test: Fixed flaky tests Replay_editor and Table_navigateTo_validation_spec 

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
=> fix: Disabled generate CRUD page feature for MsSQL plugin

app/client/src/pages/Editor/ReflowBetaCard.tsx
Minor change the Reflow Beta Tag to match the updated Designs in https://www.figma.com/file/i80YbQLLs5mXthjIHclPpX/Appsmith-Design-System?node-id=6529%3A26079
=> chore: change reflow Beta tag

app/client/src/pages/Editor/IntegrationEditor/DatasourceHome.tsx
Fix overlapping issue in datasources sections
Fixes #7391
Manually
=> fix: Datasources section overlap

app/client/src/sagas/DatasourcesSagas.ts
- fix for `name of undefined error`
Fixes #6195
Manually
// Code coverage diff between base branch:release and head branch: fix/name-of-undefined-datasource 
:red_circle: | app/client/src/sagas/DatasourcesSagas.ts | 13.51 **(0)** | 2.26 **(-0.14)** | 8.7 **(0)** | 16.12 **(0)**
=> fix: Name of undefined error in datasource catch Block

.github/workflows/TestReuseActions.yml
This workflow will test reuse. 
Fixes # 
Tsted in myfork
=> chore: Test reuse actions

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/constants/ErrorReferenceDocUrl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/constants/Assets.java
> This PR updates the URLs as per the latest `git-sync` documentation
=> chore: Update doc urls for errors related to git

app/client/src/components/propertyControls/PrimaryColumnsControl.tsx
> Fix table widget column visibility when using the Primary Column control to hide or show columns and reordering the column position
Fixes #9635
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: fix/table-column-visibility 
:red_circle: | app/client/src/components/propertyControls/PrimaryColumnsControl.tsx | 30.22 **(-0.34)** | 11.11 **(0)** | 14.29 …
=> fix: table column visibility

app/client/src/constants/messages.ts, app/client/src/pages/Editor/gitSync/RepoLimitExceededErrorModal.tsx, app/client/src/selectors/gitSyncSelectors.tsx
chore: update text and doc url
- Manually
// Code coverage diff between base branch:release and head branch: chore-update-doc-link 
:green_circle: | total | 54.94 **(0)** | 36.4 **(0.01)** | 34.61 **(0)** | 55.35 **(0)**
:green_circle: | app/client/src/selectors/gitSyncSelectors.tsx | 71.14 **(0.28)** | 11.58 **(1.1)** | 14.29 **(0.29)** | 62.37 **(0)**
:red_circle: | app/client/src/utils/WorkerUtil.ts | 88.98 **(-0.78)** | …
=> chore: update text and doc url for git disconnect modal

.github/workflows/integration-tests-command.yml
build server and ui test ran inspite of being success full
Fixes # 
Code reivew
=> test: Fix reuse actions

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GenerateCRUD/Mongo_Spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GenerateCRUD/MySQL_Spec.js, app/client/cypress/support/commands.js, app/client/gitbook-algolia-lambda.js, app/server/scripts/node/dump-examples-org.js
>
> Use this template to quickly create a well-written pull request. Delete all quotes before creating the pull request.
> Summary: I replaced all occurrences of "==" and "!=" with their type-safe counter parts "===" and "!===" fixing the problem described in #7445
Fixes #7445
- No tests were conducted
=> chore: replaced == and != with === and !===

.github/workflows/integration-tests-command.yml
Currently performance Job is not skipped in case of successfull run
Fixes # 
code reivew
=> test: Reuse performance actions

app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java, app/server/appsmith-server/src/main/java/com/appsmith/server/featureflags/FeatureFlagEnum.java, app/server/appsmith-server/src/main/resources/features/init-flags.yml
> PR to remove feature flag for git APIs, we are still keeping the git-import under the feature flag as this is still in progress
=> chore: Remove feature-flag for git

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_MultiRowSelect_spec.js, app/client/src/widgets/TableWidget/component/index.tsx, app/client/src/widgets/TableWidget/widget/index.tsx
> fix Select and deselect all in table widget when multiselection is enabled
Fixes #10669
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: fix/select-and-deselect-in-table-widget 
:green_circle: | total | 55.03 **(0)** | 36.37 **(0.01)** | 34.71 **(0)** | 55.41 **(0)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** …
=> fix: Multiselection in table widget

.github/workflows/TestReuseActions.yml, .github/workflows/integration-tests-command.yml, .github/workflows/test-build-docker-image.yml
replace full path with github workspace
Fixes # 
Tested my fork
code reivew
=> test: replace full path with github workspace

.github/workflows/TestReuseActions.yml, .github/workflows/integration-tests-command.yml, .github/workflows/test-build-docker-image.yml
Replace full path with github workspace
=> test: replace full path with github workspace (#11047)

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitUtils.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> Add git hosting provider to analytics event. 
Fixes #11056 
- Test A
- Test B
=> feat: Add gitHosting provider to analytics

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ApplicationForkingServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ApplicationForkingServiceTests.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java
> Update error message for resource not found error for export, duplicate and fork application APIs
Fixes #9458
> Junit TC
- [ x I have performed a self-review of my own code
=> fix: Update error handling for resource not found exception

app/client/src/pages/Editor/gitSync/ReconnectDatasourceModal.tsx, app/client/src/selectors/entitiesSelector.ts
> Fixing issues of git import flow
Fixes #10950 
> Follow attached issues
=> fix: 10950 - git import issues

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Autocomplete_spec.js, app/client/cypress/locators/DynamicInput.json, app/client/src/components/ads/Button.tsx, app/client/src/components/ads/MultiselectDropdown.test.tsx, app/client/src/components/ads/MultiselectDropdown.tsx, app/client/src/components/ads/TreeDropdown.test.tsx, app/client/src/components/ads/TreeDropdown.tsx, app/client/src/components/editorComponents/CodeEditor/index.test.tsx, app/client/src/components/editorComponents/CodeEditor/index.tsx, app/client/src/components/editorComponents/CodeEditor/styledComponents.ts, app/client/src/components/propertyControls/MultiSelectControl.tsx, app/client/src/components/propertyControls/StyledControls.tsx
Merged Following PRs:
- #10397
- #10005 
- #10641 
Fixes #10373
Fixes #9920
Fixes #10608
Fixes #6391
Fixes #10665
Manually tested and Jest tests are written to cover keyboard UX scenarios.
// Code coverage diff between base branch:release and head branch: pp-keybaord-navigation 
:green_circle: | total | 55.47 **(0.41)** | 37.06 **(0.67)** | 35.33 **(0.63)** | 55.86 **(0.43)**
:green_circle: | app/client/src/actions/editorActions.ts | 100 **(10)** | 100 **(0)** | 100 **(33.33)** | 100 **(0)** …
=> feat: keyboard accessible multi-select dropdown, action selector and text input

app/client/src/workers/DataTreeEvaluator.ts
- Cause of issue
Currently, trigger fields do not depend on any node. Hence changes in nodes they should depend on doesn't cause linting to re-occur. 
Fixes #10939 
Fixes #9738 
Manual
// Code coverage diff between base branch:release and head branch: fix/prevent-unneccessary-lint-error-in-trigger-fields 
:green_circle: | total | 54.99 **(0)** | 36.33 **(0.01)** | 34.67 **(-0.01)** | 55.37 **(0)**
:red_circle: | …
=> fix: keep linting in trigger field in sync with the state of the datatree 🐛 

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitUtils.java
> Fixes NPE for git-sync analytics when the remote url is empty
- Test A
=> fix: NPE in git analytics

app/client/src/widgets/RichTextEditorWidget/component/index.tsx
> Add some extra Plugins to RTE
Fixes #10633
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: feat/add-more-toolbar-and-plugin-to-RTE 
:green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 72.55 …
=> feat: add more plugins to rich text editor

app/server/appsmith-git/src/main/java/com/appsmith/git/constants/Constraint.java, app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java
> Update error reporting for the git connect API
=> fix: Update error handling for git connect

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/AppsmithBeanUtils.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/MustacheHelper.java, app/server/appsmith-interfaces/src/test/java/com/appsmith/external/helpers/AppsmithBeanUtilsTest.java, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/ActionCollectionDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitFileUtils.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ActionCollectionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutCollectionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewPageServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/CreateDBTablePageSolutionCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/ResponseUtilsTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java
Please pay attention to code changes in NewActionServiceCEImpl.java
=> chore: Minor code refactoring for bean utils and action execution

app/client/src/widgets/SelectWidget/component/index.styled.tsx
> Fix Select Widget overflow after resize
Fixes #10410
// Code coverage diff between base branch:release and head branch: fix/Select-Widget-Overflow 
:red_circle: | total | 55.06 **(0)** | 36.38 **(-0.01)** | 34.7 **(0)** | 55.43 **(0)**
=> fix: select widget overflow

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/controllers/ApplicationControllerTest.java
> Fixes the failing test for application controller for multipart header exceeds limit
=> fix: Fix error code for application controller

app/client/src/sagas/ApiPaneSagas.ts
This ensures backward compatibility with previously created Actions is bug free.
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
// Code coverage diff between base branch:release and head branch: fix/fix-body-in-get-request 
:red_circle: | app/client/src/sagas/ApiPaneSagas.ts | 15.57 **(0)** | 1.43 **(-0.09)** | 9.09 **(0)** | 17.49 **(0)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 …
=> fix: ensure backward compatibility with older Actions.

app/client/src/components/ads/DialogComponent.tsx
Dialogs like ProductUpdates and ImportApplicationModal (git-import) have an icon in header, which was showing a pointer type cursor on hover. This PR removes that.
Fixes #11212 
Manually.
// Code coverage diff between base branch:release and head branch: 11212-remove-onhover-pointer 
:green_circle: | total | 55.55 **(0.01)** | 37.01 **(0)** | 35.76 **(0)** | 55.88 **(0)**
:green_circle: | app/client/src/components/ads/DialogComponent.tsx | 87.18 **(0)** | 63.33 **(1.79)** | 85 **(0)** | 86.49 **(0)** …
=> chore: remove pointer cursor from dialog header icons.

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PingScheduledTaskCEImpl.java
Signed-off-by: Shrikant Sharat Kandula <shrikant@appsmith.com>
Minor change in data structure of analytics data points.
=> chore: Move data counts to properties for analytics (#11236)

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Debugger/PageOnLoad_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Chart_Widget_Loading_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Dropdown_spec.js
Cherry pick PR for fixing flaky tests.
=> test: Fix flaky test (#11324)

app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
Update the Label of the `refreshTokenClientCredentialsLocation` dropdown
Fixes #11106
=> chore: Update config label in Rest API datasource config page

app/rts/src/models.ts, app/rts/src/server.ts, app/rts/src/version.js, app/rts/tsconfig.json
This is a simple code cleanup PR.
Fixes: no-issue
- Code cleanup
Manually
=> chore: reformat code in rts/

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Chart_Widget_Loading_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_Widget_Add_button_spec.js, app/client/src/widgets/TableWidget/widget/index.tsx, app/client/src/workers/evaluate.ts
Support for promises in Table buttons
Fixes #11122
> TODO
// Code coverage diff between base branch:release and head branch: fix/promises-in-table-buttons 
:green_circle: | total | 55.75 **(0)** | 37.16 **(0.01)** | 35.81 **(0)** | 56.11 **(0)**
:green_circle: | app/client/src/workers/evaluate.ts | 89.86 **(-0.51)** | 76.92 **(1.92)** | 84 **(0)** | 89.15 **(-0.53)**</details>
=> fix: Promises in Table buttons

app/client/src/pages/Applications/ImportApplicationModal.tsx, app/client/src/pages/Editor/gitSync/ReconnectDatasourceModal.tsx, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> Fixing UI isssues
Fixes #10950 
> Please see attached issue
=> feat: 10950 git import issues

app/client/src/pages/Applications/ImportApplicationModal.tsx, app/client/src/pages/Applications/index.tsx, app/client/src/pages/Editor/gitSync/ReconnectDatasourceModal.tsx
Reverts appsmithorg/appsmith#11568
=> Revert "feat: 10950 git import issues"

.github/workflows/integration-tests-command.yml, .github/workflows/test-build-docker-image.yml
Failed tests are only filtered for spec. We need to make them case insenistive
Fixes # 
Code reivew
=> test: Test fix grep spec case insesitive

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
- Cosmetic change: Fix method name.
Fixes #11616 
- Manual
=> fix: fix migration method name 

app/client/src/widgets/TableWidget/component/TableStyledWrappers.tsx, app/client/src/widgets/TableWidget/component/TableUtilities.tsx
Cells in table widget are not center-aligned
Fixes #11638
Fixes #11671 
Fixes #11670 
Fixes #11668 
- Visual test
// Code coverage diff between base branch:release and head branch: fix/table-cell-getting-displaced 
:green_circle: | total | 55.82 **(0)** | 37.18 **(0.01)** | 35.2 **(0)** | 56.16 **(0)**
=> fix: Table widget value displacement

app/client/gitbook-algolia-lambda.js, app/client/src/components/editorComponents/GlobalSearch/githubHelper.ts
Updates Appsmith docs used from v1.2.1 to v1.3
- Version upgrade
- Manual
// Code coverage diff between base branch:release and head branch: chore/update_docs_version 
=> chore: Update appsmith docs version to 1.3

app/client/src/pages/Editor/APIEditor/CurlImportForm.tsx
Changed the CURL Import page design with respect to design system.
Fixes #11647 
Comparing with the designs.
// Code coverage diff between base branch:release and head branch: fix/curl-ui 
:red_circle: | total | 55.8 **(-0.02)** | 37.17 **(0)** | 35.14 **(-0.06)** | 56.14 **(-0.01)**
:red_circle: | app/client/src/pages/Editor/APIEditor/CurlImportForm.tsx | 48.15 **(-26.14)** | 87.5 **(-1.39)** | 4.35 **(-20.65)** | 49.02 **(-29.11)**
:green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0.78)** | 72.55 …
=> fix: curl import ui fixes wrt to design system

deploy/helm/Chart.yaml, deploy/helm/README.md, deploy/helm/templates/ingress.yaml
- Change path type in rule of ingress template to `Prefix`
- Update document for Helm installation without domain
=> fix: Update Helm ingress template & document

app/client/src/pages/Editor/GlobalHotKeys.tsx
Changed keyboard short for create new query/JS Object to cmd + plus
- Shortcut change. Low Impact
- Manual
// Code coverage diff between base branch:release and head branch: fix/create_new_keyboard_shortcut 
:green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(1.64)** | 64.71 **(2.95)** | 73.33 **(0)** | 90.59 **(2.35)**</details>
=> fix: Changing shortcut opt + shift + N -> cmd + plus

deploy/docker/entrypoint.sh, deploy/docker/utils/bin/check_replica_set.js, deploy/docker/utils/bin/index.js, deploy/docker/utils/bin/utils.js, deploy/docker/utils/package-lock.json, deploy/docker/utils/package.json
- Use changeStream API from mongoDB driver to check if replica set is enabled
- Create new appsmithctl command `appsmith check-replica-set` or `appsmithctl crs`
- issue: https://github.com/appsmithorg/appsmith/issues/11418
1. Start Appsmith with docker/docker-compose
1. Prepare non-admin user (read/write or read-only permission) with replica set enable (using cloud mongo, container image) and EXTERNAL\_URI
2. Run Appsmith with docker/docker-compose
3. Update mongoDB connection string to EXTERNAL\_URI
4. Restart container
[![66,1,66,1](https://collab.geekup.vn/uploads/images/gallery/2022-03/scaled-1680-/9hyvVm2l2hIFI94O.png)] …
=> fix: mongodb permission issue when checking replica set status

app/client/cypress.env.json, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Inputv2_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Phone_input_spec.js, app/client/src/widgets/BaseInputWidget/widget/index.tsx, app/client/src/widgets/InputWidgetV2/widget/derived.js, app/client/src/widgets/InputWidgetV2/widget/derived.test.ts, app/client/src/widgets/InputWidgetV2/widget/index.tsx, app/client/src/widgets/PhoneInputWidget/widget/index.tsx
When number type is selected in an input widget. Text is converted to a number as the user types it. so when the user enters a `0` right after the decimal point, the decimal point disappears. this is because `Number(1.0)` is `1`. We have made the text to be a derived property. so that the user can enter as many `0` after the decimal point.
Fixes #11449
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: fix/numeric-input-with-zero 
Status | File | % Stmts | % …
=> fix: numeric type input should accept zero after decimal point

.github/workflows/test-build-docker-image-fat.yml, .github/workflows/test-build-docker-image.yml, app/client/cypress/integration/Smoke_TestSuite_Fat/ClientSideTests/AdminSettings/Admin_settings_spec.js
Test support fat container
Fixes #
Tested in my fork
// Code coverage diff between base branch:release and head branch: test-Support-fat-container-in-CI 
:red_circle: | total | 55.87 **(-0.01)** | 37.22 **(-0.01)** | 35.24 **(0)** | 56.2 **(-0.01)**
=> test: Test support fat container in ci

.github/workflows/TestReuseActions.yml, .github/workflows/test-build-docker-image-fat.yml, .github/workflows/test-build-docker-image.yml, app/client/public/index.html
=> chore: Remove Google Analytics

app/client/cypress/setup-test-fat.sh
Adding setup test for fat conatiner
Fixes #
=> test: Adding setup test for fat container

app/client/src/components/editorComponents/EditableText.tsx, app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx
This PR fixes some alignment issues. 
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/dc2c832c8ebb41e5966ff8f99cc1ad98-00001.gif)](https://www.loom.com/share/dc2c832c8ebb41e5966ff8f99cc1ad98)
// Code coverage diff between base branch:release and head branch: fix/fix-embedded-url-misallignment 
:green_circle: | total | 55.83 **(0.01)** | 37.16 **(0)** | 35.21 **(0)** | 56.14 **(0)**
=> fix: fix embedded url misalignment

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AnalyticsServiceCEImpl.java
=> fix: Analytics sendEvent should be able to send events even during sign in process

.github/workflows/test-build-docker-image-fat.yml, app/client/cypress_fat.json
Cypress env for fat container
Fixes #
tested in fork
// Code coverage diff between base branch:release and head branch: cypress-env-for-fat-container 
:red_circle: | total | 55.82 **(0)** | 37.15 **(-0.01)** | 35.21 **(0)** | 56.14 **(0)**
=> test: Cypress env for fat container

app/client/gitbook-algolia-lambda.js
This pull request updates our lambda that syncs Gitbook with Algolia
=> updated gitbook sync to work with new APIs

app/client/src/sagas/ActionExecution/PluginActionSaga.ts
Fixes #11711 
Manual
// Code coverage diff between base branch:release and head branch: fix/file-upload-not-converting-blob-url 
:red_circle: | total | 55.87 **(-0.01)** | 37.24 **(0.01)** | 35.22 **(0)** | 56.18 **(-0.01)**
:red_circle: | app/client/src/sagas/ActionExecution/PluginActionSaga.ts | 18.38 **(-0.54)** | 2.42 **(-0.08)** | 10.53 **(-0.58)** | 21.12 **(-0.5)** …
=> fix: convert blob urls in object type values

app/server/appsmith-server/src/main/java/com/appsmith/server/constants/AnalyticsEvents.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AnalyticsServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AnalyticsServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ThemeServiceCEImpl.java
This PR adds analytics events on different actions on themes - save, customize, delete, apply.
Fixes #11397
- Manually
=> feat: Added analytics events on themes

.github/workflows/integration-tests-command.yml, .github/workflows/test-build-docker-image.yml
Fixed if condition
Tested in own fork. Code review
=> test: Test fix build rts dependency

app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/ApplicationTemplate.java
Added two new fields to templates - `productImageUrl` and `sortPriority`. 
Fixes #11877
- Manually
=> feat: Added new fields to templates

.github/workflows/integration-tests-command.yml
Added if for fat container
code reivew
=> test: Added if for fat container

.github/workflows/integration-tests-command.yml
fixed build artifacts download
Fixes #
code review
=> test: fixed build artifacts download

.github/workflows/integration-tests-command.yml
changed for rerun for docker
code review
=> test: changed for rerun

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GitSync/DisconnectGit_spec.js, app/client/src/ce/constants/messages.test.ts, app/client/src/ce/constants/messages.ts, app/client/src/pages/Editor/gitSync/DisconnectGitModal.tsx, app/client/src/pages/Editor/gitSync/RepoLimitExceededErrorModal.tsx, app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx, app/client/src/pages/Editor/gitSync/components/GitConnectError.tsx
Resolves rest of git polishing issues
Fixes #11750 
Manually.
// Code coverage diff between base branch:release and head branch: 11750-fix-rest-git-sync-polishing-issues 
:red_circle: | total | 55.65 **(0)** | 36.91 **(0)** | 34.95 **(-0.01)** | 55.96 **(0)**
:red_circle: | app/client/src/ce/constants/messages.ts | 76.75 **(-0.05)** | 100 **(0)** | 30.99 **(-0.13)** | 81.49 **(0.06)**</details>
=> fix: revoke access and limit reached modal updates

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> Update the error message with more meaningful information
Fixes #11757 
- Locally
=> chore: Update error message for checkout remote branch flow

app/client/perf/src/perf.js
New import flow doesn't have the import app button after the dsl is selected.
>
- This change requires a …
=> Remove the click on import app button

app/client/cypress.json, app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/QueryPane/Postgres_Spec.js, app/client/cypress/locators/GeneratePage.json, app/client/src/sagas/QueryPaneSagas.ts, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/DatasourceStructure.java, app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/utils/TemplateUtils.java, app/server/appsmith-plugins/amazons3Plugin/src/test/java/com/external/plugins/AmazonS3PluginTest.java, app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java, app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/Aggregate.java, app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/Count.java, app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/Delete.java, app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/Distinct.java, app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/Find.java, app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/Insert.java, app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/UpdateMany.java, app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/utils/MongoPluginUtils.java, app/server/appsmith-plugins/mongoPlugin/src/main/resources/dependency.json, app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/CreateDBTablePageSolutionCEImpl.java
Fixes #12033
// Code coverage diff between base branch:release and head branch: fix/nn-patch-6 
:red_circle: | total | 55.63 **(0)** | 36.86 **(-0.01)** | 34.94 **(0)** | 55.94 **(0)**
=> fix: S3 formData path for bucket name

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/EnvManagerCEImpl.java
=> chore: Send test email error message to client

.github/workflows/test-build-docker-image.yml
Fixing minor typo in the test-build-docker.yml Github workflow.
=> chore: Fixing minor typo in the test-build-docker.yml Github workflow

app/client/src/utils/autocomplete/EntityDefinitions.ts
Fix autocomplete issues for Select widget
Fixes #10851
- Visually
- 
// Code coverage diff between base branch:release and head branch: fix/filterText-in-autocomplete 
:green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0)**
:red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 …
=> fix: Select Widget autocomplete

app/client/src/components/editorComponents/Debugger/DebugCTA.tsx
Fixes #11826 
Manual
// Code coverage diff between base branch:release and head branch: fix/page-reloads-when-debug-button-is-clicked 
:red_circle: | total | 55.63 **(0)** | 36.85 **(-0.01)** | 34.94 **(0)** | 55.93 **(-0.01)**
=> fix: page reloads when  debug-button is clicked

app/client/cypress/fixtures/listwidgetdsl.json, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/Bind_API_with_List_Widget_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Switchgroup_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GitSync/Git_spec.js, app/client/cypress/support/commands.js
Skip Git flaky test until fixed
=> test: Skip Git flaky test to unblock CI

app/util/plugin-generation/package-lock.json, app/util/plugin-generation/package.json
Creating the package.json file for the `plugin-generation` folder as this folder only has the `package-lock.json` file and not the dependency file itself. This is required for static analyzers to suggest security updates and track our dependencies.
=> chore: Adding the package.json file to plugin-generation folder

app/client/src/RouteBuilder.ts, app/client/src/ce/pages/AdminSettings/BreadcrumbCategories.tsx, app/client/src/ce/pages/AdminSettings/config/authentication/AuthPage.tsx, app/client/src/constants/routes.ts, app/client/src/pages/Editor/BottomBar/ManualUpgrades.tsx, app/client/src/pages/Editor/GeneratePage/components/GeneratePageForm/GeneratePageForm.tsx, app/client/src/pages/Settings/LeftPane.tsx, app/client/src/pages/Templates/LeftPaneTemplateList.tsx, app/client/src/pages/Templates/Template/index.tsx, app/client/src/sagas/ActionExecution/NavigateActionSaga.ts
Moves admin and templates URL builder functions into RouteBuilder.ts
- Code Refactor
- Manual
// Code coverage diff between base branch:release and head branch: chore/move-new-builder-functions 
:red_circle: | total | 55.76 **(-0.01)** | 37.2 **(-0.01)** | 35.35 **(0)** | 56.01 **(-0.01)**
:red_circle: | app/client/src/RouteBuilder.ts | 82.91 **(-1.94)** | 81.67 **(-3.75)** | 34.78 **(3.2)** | 79.79 **(-0.98)**
:green_circle: | app/client/src/constants/routes.ts | 96 **(2.59)** | 100 **(33.33)** | 66.67 **(9.53)** | 95.83 **(1.64)**
:red_circle: | app/client/src/selectors/commentsSelectors.ts | 83.61 **(-1.64)** | …
=> chore: Move url builder functions into RouteBuilder.ts

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Applications/ApplicationURL_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GitSync/GitBugs_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GitSync/Git_spec.js, app/client/cypress/support/commands.js
- Added test for  Bug:10773 When user delete a resource form the child branch and merge it back to parent branch, still the deleted resource will show up in the newly created branch
- Fixed flaky tests
locally
// Code coverage diff between base branch:release and head branch: gitTests 
:red_circle: | app/client/src/utils/WorkerUtil.ts | 88.98 **(-0.78)** | 68.63 **(-3.92)** | 100 **(0)** | 92.38 **(-0.95)**</details>
=> test: add test for git sync bug #10773 

app/client/src/components/editorComponents/GlobalSearch/SnippetsDescription.tsx, app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx, app/client/src/constants/ApiEditorConstants.ts, app/client/src/pages/Editor/APIEditor/ApiAuthentication.tsx, app/client/src/pages/Editor/APIEditor/ApiRightPane.tsx, app/client/src/pages/Editor/APIEditor/CommonEditorForm.tsx, app/client/src/pages/Editor/APIEditor/RapidApiEditorForm.tsx, app/client/src/pages/Editor/APIEditor/RestAPIForm.tsx, app/client/src/pages/Editor/APIEditor/index.tsx, app/client/src/pages/Editor/Explorer/JSDependencies.tsx, app/client/src/pages/Editor/PropertyPane/PanelPropertiesEditor.tsx, app/client/src/sagas/PluginSagas.ts, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
- Note: Currently it is being merged to development branch feat/graphql.
- This PR has common Editor functionality extracted from API Editor in order to use the common things in GraphQL Editor
Fixes #10549
- API Datasource is to be tested carefully for this change.
=> feat: Created a common editor that can be used by API as well as GraphQL

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Applications/ApplicationURL_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Applications/DuplicateApplication_spec.js, app/client/cypress/support/commands.js, app/client/src/RouteBuilder.ts, app/client/src/pages/Applications/index.tsx, app/client/src/pages/Editor/BottomBar/ManualUpgrades.tsx, app/client/src/pages/Editor/gitSync/ReconnectDatasourceModal.tsx, app/client/src/sagas/ApplicationSagas.tsx, app/client/src/sagas/InitSagas.ts
Fixes incorrect slug replacement when duplicating, import and export.
Fixes #12306 
Fixes #12307 
- Cypress
- Manual
// Code coverage diff between base branch:release and head branch: hotfix/slug-replacement-duplicate-fork 
:red_circle: | total | 55.69 **(-0.02)** | 37.08 **(-0.02)** | 35.25 **(-0.04)** | 55.95 **(-0.02)**
:green_circle: | app/client/src/RouteBuilder.ts | 82.91 **(0)** | 82.35 **(0.68)** | 34.78 **(0)** | 79.79 **(0)**
:red_circle: | app/client/src/sagas/ApplicationSagas.tsx | 20.74 **(-0.07)** | 4.08 **(-0.3)** | 9.09 **(0)** | 23.79 **(-0.1)** …
=> fix: fixes url slugs during duplicate, import and export feature.

app/client/src/pages/setup/SignupSuccess.tsx
Fixes oauth login flow for new users
Fixes #12304 
- Manual
// Code coverage diff between base branch:release and head branch: hotfix/12304-broken-oauth-login-flow 
:red_circle: | total | 55.68 **(-0.01)** | 37.08 **(0)** | 35.25 **(0)** | 55.94 **(-0.01)**
=> fix: oauth login flow for new users

app/client/src/RouteBuilder.ts, app/client/src/pages/Editor/gitSync/ReconnectDatasourceModal.tsx
> As variable validation issue, application blocked. Resolved by adding condition
Fixes #12163 
> Please follow linked issue
// Code coverage diff between base branch:release and head branch: fix/12163-gsheet-authentication-failing-when-importing-app 
:green_circle: | total | 55.69 **(0.01)** | 37.06 **(-0.01)** | 35.25 **(0)** | 55.95 **(0.01)**
:red_circle: | app/client/src/RouteBuilder.ts | 82.91 **(0)** | 80.77 **(-1.58)** | 34.78 **(0)** | 79.79 **(0)**
:green_circle: | app/client/src/utils/WorkerUtil.ts | …
=> fix: 12163 - fixed issue of google authorization redirecting on reconnect modal

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java, app/server/appsmith-server/src/test/resources/test_assets/ImportExportServiceTest/valid-application-with-page-added.json
> The actions of type API binding fails when the user import it from git. This is introduced recently due to the fix raised for the visibility of git connected apps. It is because of the missing org id. Affects git import, git checkout remote branch and git pull. 
Fixes #12328 
- Locally
- JUnit tets
=> fix: Fix binding for APIs during git import

app/client/src/ce/pages/AdminSettings/config/authentication/index.tsx, app/client/src/pages/Settings/config/general.ts
Text changes on admin settings. https://theappsmith.slack.com/archives/C02JT9CSE6L/p1648624665504049?thread_ts=1648622706.217239&cid=C02JT9CSE6L
Manually
=> chore: update text in admin settings

app/client/src/widgets/JSONFormWidget/fields/DateField.tsx
=> fix: JSONForm date field tooltip visibility

app/client/src/components/ads/JSToggleButtonComponent.tsx, app/client/src/components/ads/Tooltip.tsx, app/client/src/components/ads/index.ts, app/client/src/components/editorComponents/form/ToggleComponentToJson.tsx, app/client/src/components/editorComponents/form/fields/StyledFormComponents.tsx, app/client/src/components/formControls/EntitySelectorControl.tsx, app/client/src/components/formControls/SortingControl.tsx, app/client/src/components/formControls/WhereClauseControl.tsx, app/client/src/pages/Editor/FormConfig.tsx, app/client/src/pages/Editor/FormControl.tsx, app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx
1. Update the Switch to json button as per designs which corresponds to a button with JS
Before:
After:
2. Tooltip position should be fixed with label underlined which supports tooltip
Before:
After:
3. Remove the arrow in the Entity Selector Component
Before:
After:
4. Sort By ui should be similar to Where Clause
5. Update the UI of Where Clause so that when condition added should not shrink the ui and where label should be present beforehand the addition of any clause
6. First element should also have a cross icon to reset the first row in the Where Clause
Before:
After:
Fixes #12349
> Please also list any relevant details for …
=> fix: updated uqi forms ui, clubbed JS switch button to ads, updated tooltip design

app/client/src/widgets/JSONFormWidget/widget/propertyConfig.ts
Fixes #12206
- Change in copy of tooltip text
// Code coverage diff between base branch:release and head branch: task/json-form-modify-tooltip 
:red_circle: | total | 55.55 **(0)** | 37.01 **(-0.01)** | 35.18 **(0)** | 55.85 **(-0.01)**
=> chore: JSON form autogenerate control tooltip text changes

.github/workflows/copy-labels.yml
Update the workflow to use the Appsmith repo for github actions
=> fix: Use the Appsmith repo for custom github actions

app/client/src/api/ApiUtils.ts
The API to fetch application and page list details was missing branchName in its header causing the page list from master branch to load.
- Manual
// Code coverage diff between base branch:release and head branch: hotfix/missing-git-branch-app-pages-api 
:green_circle: | total | 55.67 **(0.01)** | 37.05 **(0.01)** | 35.26 **(0)** | 55.93 **(0.01)**
:green_circle: | app/client/src/api/ApiUtils.ts | 60 **(0.68)** | 43.48 **(2.57)** | 80 **(0)** | 57.14 **(0.78)**</details>
=> fix: Incorrect page list in deployed branches

app/client/src/api/ApiUtils.ts
(cherry picked from commit 7f390d0c00c0a0feda5c16a5c26b8e3ee0e95609) to fix navigation issue in prod
- Manual
// Code coverage diff between base branch:master and head branch: hotfix/prod-navigation-issue 
:red_circle: | total | 55.68 **(-0.01)** | 37.05 **(0)** | 35.25 **(0)** | 55.94 **(0)**
:green_circle: | app/client/src/api/ApiUtils.ts | 60 **(0.68)** | 43.48 **(2.57)** | 80 **(0)** | 57.14 **(0.78)**
=> fix: Incorrect page list in deployed branches (#12416)

.github/workflows/integration-tests-command.yml, .github/workflows/test-build-docker-image.yml
Test make fat tests blocking change
Fixes # 
code review
=> test: Test make fat tests blocking change

.github/workflows/test-build-docker-image.yml
fix push workflow
fix push workflow
code review
=> test: fix push workflow

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GitSync/Git_spec.js, app/client/src/sagas/InitSagas.ts
Branch names that contain special character were not decoded properly in the utility method. 
Changes made to rely on branchName provide by react router in view mode.
Fixes #12448 
- Manual
// Code coverage diff between base branch:release and head branch: hotfix/decode-branch-name-request-header 
:red_circle: | app/client/src/sagas/InitSagas.ts | 41.18 **(0)** | 17.74 **(-0.29)** | 50 **(0)** | 45.16 **(0)**</details>
=> fix: remove encoding of branch name with / in it

app/client/src/sagas/InitSagas.ts
(cherry picked from commit 4b462ae623abbcc84d37a267829b4c033c479401)
Fixes application crash when branch name contains "/"
- Manual
// Code coverage diff between base branch:master and head branch: hotfix/broken-branched-applications 
:red_circle: | total | 55.68 **(-0.01)** | 37.05 **(-0.01)** | 35.25 **(0)** | 55.94 **(0)**
:red_circle: | app/client/src/sagas/InitSagas.ts | 41.18 **(0)** | 17.74 **(-0.29)** | 50 **(0)** | 45.16 **(0)**
:red_circle: | app/client/src/utils/WorkerUtil.ts | 88.98 **(-0.78)** | 70.59 **(-1.96)** | 100 **(0)** | 92.38 …
=> fix: fixes app crash in view when branch name contain '/'

app/client/src/pages/Editor/Explorer/Datasources/QueryTemplates.tsx
This PR fixes the issue where initial values for actions created through datasource templates are not being filled up.
Fixes #9455
// Code coverage diff between base branch:release and head branch: fix/fix-template-default-values 
:red_circle: | total | 55.72 **(0)** | 37.15 **(-0.01)** | 35.44 **(0)** | 55.97 **(-0.01)**
:red_circle: | app/client/src/pages/Editor/Explorer/Datasources/QueryTemplates.tsx | 47.06 **(0)** | 28.57 **(-11.43)** | 0 **(0)** | 48.48 **(0)**
:red_circle: | app/client/src/utils/WorkerUtil.ts | 88.98 **(-0.78)** | 70.59 **(-1.96)** | 100 …
=> fix: Fixes issue with initial values

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GitSync/Connection_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GitSync/RepoLimitExceededErrorModal_spec.js, app/client/cypress/locators/gitSyncLocators.js, app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx
Git tests have been failing for a while now, creating a nuisance for contributors whose pull requests get stuck. This PR fixes two consistently failing tests.
Automation testing.
// Code coverage diff between base branch:release and head branch: fix-failing-git-tests 
:red_circle: | total | 55.72 **(0)** | 37.15 **(-0.01)** | 35.44 **(0)** | 55.98 **(0)**
=> test: Fix failing git sync tests

.github/workflows/test-build-docker-image.yml
change load docker condition
Fixes # 
Code review
=> test: change load docker condition

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Applications/ApplicationURL_spec.js, app/client/cypress/support/commands.js, app/client/src/RouteBuilder.ts, app/client/src/sagas/ApplicationSagas.tsx, app/client/src/sagas/PageSagas.tsx, app/client/src/store.ts, app/client/src/utils/helpers.tsx
Fixes 404 on renaming a new page in applications with Legacy URLs
- Manual
- Cypress
// Code coverage diff between base branch:release and head branch: fix/404-page-rename 
:green_circle: | total | 56.2 **(0.02)** | 37.67 **(0.01)** | 35.72 **(0.01)** | 56.43 **(0)**
:green_circle: | app/client/src/RouteBuilder.ts | 83.33 **(0.42)** | 80.77 **(0)** | 37.5 **(2.72)** | 80 **(0.21)**
:green_circle: | app/client/src/store.ts | 85.42 **(-0.94)** | 58.33 **(8.33)** | 80 **(0)** | 83.33 **(0)**
:red_circle: | app/client/src/sagas/ApplicationSagas.tsx | 20.54 …
=> fix: 404 on renaming new pages in apps with legacy URLs

.github/workflows/integration-tests-command.yml
=> test: commented load docker license

app/client/src/ce/constants/messages.ts
Added beta tag for js function's onPageLoad setting
=> chore: added beta to onPageLoad for js actions

app/client/cypress/support/Pages/JSEditor.ts
Updating JSOnPageLoad pop-up text message validation to accommodate the new 'Beta' tag introduced due to https://github.com/appsmithorg/appsmith/pull/12657
Fixes JSOnLoadActions_Spec failure in CI runs
Cloud/Release
=> test: Automation script update to fix JSOnPageLoad pop-up text message

.github/workflows/test-build-docker-image.yml
commented license addition
Fixes #
code review
=> test: commented license addition

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Phone_input_spec.js
=> chore: Fix failing test case in phone input onSubmit spec

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/Datasource.java, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/ActionDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCEImpl.java
=> feat: Add analytics events to track user activation

app/client/src/actions/jsPaneActions.ts, app/client/src/reducers/entityReducers/jsActionsReducer.tsx, app/client/src/sagas/JSPaneSagas.ts
[![LOOM DEMO](http://cdn.loom.com/sessions/thumbnails/8e04d1eeb479415d8d5138d83150fa01-00001.gif)](https://www.loom.com/share/8e04d1eeb479415d8d5138d83150fa01)
Fixes #12818 
Manual
// Code coverage diff between base branch:release and head branch: fix/no-loading-state-js-editor 
:red_circle: | app/client/src/sagas/JSPaneSagas.ts | 16.16 **(-0.07)** | 1.05 **(0)** | 4.55 **(0)** | 18.69 **(-0.09)**</details>
=> fix: show loading state in JS Editor

app/client/src/pages/Editor/gitSync/Tabs/Deploy.tsx, app/client/src/pages/Editor/gitSync/Tabs/Merge.tsx, app/client/src/pages/Editor/gitSync/components/ConflictInfo.test.tsx, app/client/src/pages/Editor/gitSync/components/ConflictInfo.tsx, app/client/src/pages/Editor/gitSync/components/GitErrorPopup.tsx, app/client/src/pages/Editor/gitSync/components/MergeStatus.tsx
Refactor `ConflictInfo` component to make it testable.
Fixes #12508 
Tests attached.
// Code coverage diff between base branch:release and head branch: fix-merge-tab 
:green_circle: | total | 56.39 **(0.04)** | 37.78 **(0.04)** | 36.01 **(0.07)** | 56.61 **(0.04)**
:green_circle: | app/client/src/ce/constants/messages.ts | 77.33 **(0.1)** | 100 **(0)** | 32.96 **(0.28)** | 82.04 **(0)**
:green_circle: | app/client/src/components/ads/Button.tsx | 90.97 **(0)** | 76.52 **(0.87)** | 95.56 **(0)** | 91.55 **(0)** …
=> fix: merge tab issues

app/client/src/pages/Editor/PropertyPane/Generator.tsx
Add Key to Boxed Component
Chore
=> chore: Key missing error in Boxed component

app/client/src/components/ads/formFields/CopyUrlForm.tsx, app/client/src/components/ads/formFields/TextAreaField.tsx
> Added new form field component in ads. Also, updated copy URL form component.
Fixes #11265 
> Tested on EE as this is not getting used on CE.
// Code coverage diff between base branch:release and head branch: feat/saml-common 
:red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | 56.74 …
=> chore: add common code for SAML

app/server/appsmith-server/src/main/resources/system-themes.json
Theme config were missing config for Progress widget and select widget 2. This PR adds config for those widgets.
=> chore: Update theming default themes configs

app/server/Dockerfile
=> chore: Added jcmd to Appsmith server image

app/client/cypress/integration/Smoke_TestSuite/EnterpriseTests/AdminSettings/Admin_settings_spec.js
> added edition check on cypress to avoid merge conflicts on EE
Fixes #12973 
// Code coverage diff between base branch:release and head branch: fix/merge-conflict-ee 
:red_circle: | total | 56.47 **(0)** | 37.92 **(-0.01)** | 36.19 **(0)** | 56.69 **(0)**
:red_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 70.59 **(-1.96)** | 100 **(0)** | 93.33 **(0)**</details>
=> fix: add edition check on cypress to avoid merge conflicts on EE

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationTemplateServiceCEImpl.java
=> feat: updated download template App API to download from cloud services

app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/GitUtilsTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java
This PR adds a backend validation for git URLs on the backend side. Plus added some more test cases for URLs
Fixes #12054
- Manual via local version of app as well as via Postman API
=> fix: Add validation for Git URLs on server

.github/workflows/integration-tests-command.yml
Sometime the ui test result step does not get updated. Adding some debugging to figure out why
=> Add debugging for ui test result step

app/client/src/components/editorComponents/ApiResponseView.tsx, app/client/src/constants/DefaultTheme.tsx, app/client/src/pages/Editor/APIEditor/ApiRightPane.tsx, app/client/src/pages/Editor/APIEditor/Form.tsx, app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
- Border Witdth issues 
- Border Color issues 
- Height issues
Fixes #9495 
Manually
// Code coverage diff between base branch:release and head branch: fix/9495-datasource-ui 
=> fix: datasource ui style issues resolved

app/client/src/pages/Applications/ApplicationCard.tsx
> when delete a master branch, and edit application, correct branch name should be selected.
Fixes #13183 , #13184 
> Please check linked issues
// Code coverage diff between base branch:release and head branch: fix/13184-master-branch-issue 
:green_circle: | total | 56.46 **(0)** | 37.92 **(0.01)** | 36.17 **(0)** | 56.69 **(0.01)**
:green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0.78)** | 72.55 **(1.96)** | 100 …
=> fix: 13183, 13184 - fixed issue of correct branch name on edit mode

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCEImpl.java
=> fix: Throw error on trying to access non-existent unpublished action

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/PropertyPane/PropertyPaneJsEnabledVisible_spec.js, app/client/src/components/editorComponents/CodeEditor/index.tsx
https://codemirror.net/doc/manual.html#addon_autorefresh
auto refresh was imported but not enabled, this will fix it.
Fixes #13227 
- Tested manually by repeating steps provided in issue video
=> fix: code hidden issue for JS Enabled fields

.github/workflows/integration-tests-command.yml
A bad script caused the action to fail. This change fixes that
=> Fix integration test action

app/server/appsmith-server/src/main/resources/system-themes.json
This PR updates some values in the default themes json
=> chore: Update default themes

Dockerfile
Cherry picking hotfix to resolve Redis installation in CI.
=> fix: Redis installation in Dockerfile (#13428)

app/client/src/ce/constants/messages.ts, app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx
> Update a label of remote URL input box when importing application from git
Fixes #12603 
> refer linked issue
// Code coverage diff between base branch:release and head branch: fix/12603-git-import-modal-message 
:red_circle: | app/client/src/ce/constants/messages.ts | 77.83 **(-0.01)** | 100 **(0)** | 34.42 **(-0.05)** | 81.78 **(0.02)**
:green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0)**
:red_circle: | …
=> fix: 12603 - git import modal message of remote url inputbox

app/client/src/pages/Editor/DataSourceEditor/DBForm.tsx, app/client/src/pages/Editor/gitSync/ReconnectDatasourceModal.tsx
> fixed issue with redirecting urls from oauth
Fixes #12456 
> Please refer linked issue
// Code coverage diff between base branch:release and head branch: fix/12456-oauth-redirecting-issue 
:green_circle: | total | 56.43 **(0)** | 37.81 **(0.01)** | 36.07 **(0)** | 56.65 **(0)**
:red_circle: | app/client/src/pages/Editor/DataSourceEditor/DBForm.tsx | 48.53 **(0)** | 13.64 **(-0.31)** | 9.09 **(0)** | 50 **(0)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** | 41.67 **(0.84)** | …
=> fix: 12456 - oauth redirection issue

app/client/src/pages/Editor/PagesEditor/PageListItem.tsx, app/client/src/utils/DynamicBindingUtils.ts
Updates node-forge libraries version in entity explorer
Fixes #13323 
- Manual 
=> fix: update JS libs version numbers in entity explorer

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/Bind_TabWidget_Input_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/LayoutWidgets/Tab_new_scenario_spec.js
Contains fix for test Bind_TabWidget_Input_spec and Tab_new_scenario_spec
locally
- [] My code follows the style guidelines of this project
=> test: fix Tab widget related cypress tests

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CurlImporterServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java
We now check for possible sub-shell calls within the cURL input and throw an error if we detect one.
Fixes #11977 
- JUnit test case
=> fix: Throw error when trying to import a cURL command that has a subshell

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/EnvManagerCEImpl.java
Functional breakdown for authentication analytics feature is done with reference to https://github.com/appsmithorg/appsmith/pull/13462
Fixes #13071 
- Manually via local app
- Manually via Postman local
=> Chore: Functional breakdown for authentication analytics feature

Dockerfile, app/client/Dockerfile, app/server/Dockerfile, deploy/docker/scripts/healthcheck.sh
Added **healthcheck** to the fat dockerfile. The `healthcheck.sh` script used `supervisorctl` to check for the status of all the process to determine the health.
Added healthcheck to thin server and editor docker file.
Manually
// Code coverage diff between base branch:release and head branch: feat/docker-healthcheck 
:green_circle: | total | 56.47 **(0.01)** | 37.92 **(0.01)** | 36.15 **(0)** | 56.69 **(0.01)** …
=> feat: added healthcheck to docker

contributions/ServerSetup.md
Included WSL based Windows server setup and build steps 
Fixes #13562 
> Changes made on the document ServerSetup.md
> I made changes only in document.
=> Server setup steps on Windows using WSL

.github/workflows/integration-tests-command.yml, .github/workflows/test-build-docker-image.yml
Fix fat container rerun
code review
- [] I have added tests that prove my fix is effective or that my feature works
=> test: Fix fat container rerun

app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java
=> fix: Fix build failure

app/server/appsmith-server/src/main/resources/system-themes.json
=> chore: add theme stylesheet for Table widget v2

app/client/src/ce/constants/messages.ts, app/client/src/pages/Editor/Explorer/Datasources/DatasourceStructureContainer.tsx
update error message
Fixes #12171
=> chore: update error message for no schema available for a datasource

app/client/src/pages/Editor/gitSync/Tabs/Deploy.tsx, app/client/src/pages/Editor/gitSync/components/GitChangesList.test.tsx, app/client/src/pages/Editor/gitSync/components/GitChangesList.tsx, app/client/src/pages/Editor/gitSync/utils.test.ts, app/client/src/pages/Editor/gitSync/utils.ts
- Rename variables for better readability.
- Extract code from bigger component.
- Improve boolean logic
- Extract logic out of component
- Unit tests
- Refactoring
Unit tests
// Code coverage diff between base branch:release and head branch: git-enhance-1 
:green_circle: | total | 56.61 **(0.02)** | 38.54 **(0.17)** | 35.89 **(0.03)** | 56.86 **(0.02)**
:green_circle: | app/client/src/pages/Editor/gitSync/utils.ts | 96.55 **(1.1)** | 77.78 **(11.11)** | 85.71 **(2.38)** | 95.45 **(2.12)**
:sparkles: :new: | **app/client/src/pages/Editor/gitSync/components/GitChangesList.tsx** | **72.73** | **77.54** | **54.17** …
=> chore: refactor git code

.github/workflows/label-checker.yml
Don't check for "Test Plan Approved" Label for performance PR
=> Don't check for "Test Plan Approved" Label for performance PR

app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java
=> test: Fix test failures due to the new connect flow

app/client/cypress/fixtures/formSelectDsl.json, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/select_Widget_Bug_spec.js, app/client/cypress/locators/commonlocators.json, app/client/src/widgets/SelectWidget/component/index.tsx
Make the Filtering in Select widget more predictable. 
Fixes #13754 
- Cypress Tests
// Code coverage diff between base branch:release and head branch: fix/select-widget-filtering 
:red_circle: | app/client/src/widgets/SelectWidget/component/index.tsx | 14.96 **(-1.45)** | 0 **(0)** | 4.55 **(-0.21)** | 15.52 **(-1.57)**</details>
=> fix: Select widget filtering

app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ApplicationControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ThemeControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitFileUtils.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ThemeServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ThemeServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ThemeServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ThemeServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ApplicationForkingServiceTests.java
Theming API was not considering branches. This PR fixes the issue.
Fixes #13860
- Manually
- JUnit tests
=> fix: Theming issue when application has multiple git branches

app/client/src/ce/pages/AdminSettings/LeftPane.tsx, app/client/src/ce/pages/AdminSettings/Main.tsx, app/client/src/ce/pages/AdminSettings/config/authentication/index.tsx, app/client/src/components/editorComponents/form/fields/DropdownWrapper.tsx, app/client/src/components/editorComponents/form/fields/SelectField.tsx, app/client/src/pages/Settings/FormGroup/Dropdown.tsx, app/client/src/pages/Settings/SettingsForm.tsx, app/client/src/pages/Settings/components.ts
> Optimize naming conventions for variables and functions as suggested in PRs #346 #220
Fixes #13884 
- optimize naming conventions
> Tested if there are no errors after these changes during runtime.
// Code coverage diff between base branch:release and head branch: chore/optimize-code 
:green_circle: | total | 56.56 **(0)** | 38.55 **(0.01)** | 35.88 **(0.01)** | 56.81 **(0.01)**
:x: | ~~app/client/src/components/ads/formFields/SelectField.tsx~~ | ~~31.58~~ | ~~0~~ | ~~0~~ | ~~35.29~~</details>
=> chore: optimize naming conventions for variables and functions

app/client/src/workers/DataTreeEvaluator/test/DataTreeEvaluator.test.ts, app/client/src/workers/DataTreeEvaluator/test/mockUnEvalTree.ts
Fixes #12826
Checked that this test case fails before #12684
// Code coverage diff between base branch:release and head branch: test/async-tag 
:green_circle: | total | 56.67 **(0.08)** | 38.42 **(0.06)** | 35.93 **(0.07)** | 56.92 **(0.08)**
:green_circle: | app/client/src/workers/Actions.ts | 95.83 **(4.16)** | 68.85 **(0)** | 90 **(10)** | 95.31 **(4.68)**
:green_circle: | app/client/src/workers/evaluate.ts | 91.78 **(6.16)** | 64.47 …
=> fix: Add unit tests for async tag

contributions/docs/GlobalFunctions.md
Add document to the contributing guide for adding global functions to the Appsmith platform
Fixes #13167
- Add documentation
- Testing is not required
=> docs: Add docs for adding a global function to Appsmith

contributions/docs/GlobalFunctions.md
Fix styles and broken links for global functions
No tests needed
=> Update docs for global functions

app/client/src/widgets/PhoneInputWidget/widget/index.tsx
=> chore: update placeholder

app/client/cypress/fixtures/largeJSONData.json, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts, app/client/cypress/support/Objects/CommonLocators.ts, app/client/src/components/editorComponents/CodeEditor/constants.ts, app/client/src/components/editorComponents/CodeEditor/index.tsx, app/client/src/components/editorComponents/CodeEditor/lintHelpers.test.ts, app/client/src/components/editorComponents/CodeEditor/lintHelpers.ts, app/client/src/pages/Editor/JSEditor/Form.tsx
For large code editor content, the recursive process of getting the binding location during linting can cause the App to crash (depending on the size of the call stack).  This check is not necessary for a JS Object since its binding location is constant (for a valid JS Object).
- Performance
Difference between previous and current time to process JS Editor lint annotations (for several trials and same content).
Previous (78ms max.)
Current (1.3 ms max.)
Custom lint error when JS Object doesn't start with 'export default'
Fixes #14002 
Fixes #9252
- Jest
- Cypress …
=> fix: improve jseditor linting performance

.github/workflows/TestReuseActions.yml, .github/workflows/build-rts.yml, .github/workflows/client-build.yml, .github/workflows/github-release.yml, .github/workflows/integration-tests-command.yml, .github/workflows/test-build-docker-image-fat.yml, .github/workflows/test-build-docker-image.yml, app/client/.nvmrc, app/client/package.json, app/rts/package.json, contributions/ClientSetup.md
- Update the node version to v.16.15.0 in package.json and CI files.
Fixes #14079 
- Need to test the CI and Build.
- Run test cases on the CI
=> chore: Update node version to 16.15.0 LTS

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ApiPaneTests/API_Search_spec.js
Cherry picked a fix of a failing cypress test. https://github.com/appsmithorg/appsmith/pull/14154
=> hotfix: Remove third party api in cypress test (#14154)

app/server/appsmith-git/pom.xml, app/server/appsmith-interfaces/pom.xml, app/server/appsmith-plugins/pom.xml, app/server/appsmith-plugins/rapidApiPlugin/pom.xml, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
- Update lombok version to fix maven compilation error: https://stackoverflow.com/questions/66801256/java-lang-illegalaccesserror-class-lombok-javac-apt-lombokprocessor-cannot-acce
- Update database change log file according to the changes introduced in the release.
- Manual
=> fix: fix build error

app/server/appsmith-server/src/main/java/com/appsmith/server/constants/Assets.java
> Update the url for git sync
Fixes https://github.com/appsmithorg/appsmith/issues/13821
=> chore: Update docs url for connecting to repo flow

app/client/src/constants/ThirdPartyConstants.tsx
> Add document link for SAML
Fixes #14284 
- Update document link
> Needs to be tested on Enterprise edition
=> chore: update document link for SAML

app/client/src/widgets/ListWidget/widget/index.tsx
Cursor Pagination Fix for list widget
Fixes #13946 
> Visual Test
// Code coverage diff between base branch:release and head branch: fix/Firestore-Pagination-in-list-widget 
:red_circle: | total | 56.71 **(-0.01)** | 38.66 **(-0.01)** | 36.22 **(0)** | 56.96 **(-0.01)**
:red_circle: | app/client/src/widgets/ListWidget/widget/index.tsx | 66.56 **(-0.44)** | 28.72 **(-0.3)** | 62.26 **(0)** | 65.96 **(-0.47)**</details>
=> fix: Cursor pagination in list widget

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/PluginUtils.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/plugins/CrudTemplateService.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/FilterDataServiceCE.java, app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/GoogleSheetsMethodStrategy.java, app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsAppendMethod.java, app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsDeleteMethod.java, app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsGetMethod.java, app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsUpdateMethod.java, app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/TemplateMethod.java, app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/plugins/GoogleSheetsPlugin.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
Fixes #14312 
Fixes #14349 
Fixes #14359
=> UQI: More fixes around CRUD, migrations and error handling

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
> In import application flow we are using the save instead of saveAll even if we have the list of objects which can be saved at once. This PR updates the related execution to use saveAll in possible places.
Fixes #14363
- Performance optimization
> Tested the flow with application having 52 pages, following are the results for multiple execution:
Execution time before code changes:
6560ms, 6088ms, 7597ms, 6140ms
After code changes:
5701ms, 4375ms, 4487ms, 4912ms
=> chore: Improve the import application flow performance

app/client/package.json, app/client/src/utils/AppsmithUtils.tsx, app/client/src/widgets/RichTextEditorWidget/component/index.tsx, app/client/yarn.lock
Fixes #13885 
Manual
// Code coverage diff between base branch:release and head branch: feature/13885-rte-spellcheck 
:red_circle: | total | 56.55 **(-0.01)** | 38.54 **(-0.01)** | 35.87 **(0)** | 56.8 **(0)**
=> feat: Rich Text Editor enable browser spellcheck

app/client/src/ce/selectors/organizationSelectors.tsx, app/client/src/comments/CommentsShowcaseCarousel/index.tsx, app/client/src/comments/inlineComments/AddCommentInput.tsx, app/client/src/comments/inlineComments/useOrgUsers.tsx, app/client/src/ee/selectors/organizationSelectors.tsx, app/client/src/pages/AppViewer/AppViewerHeader.tsx, app/client/src/pages/AppViewer/PageMenu.tsx, app/client/src/pages/AppViewer/index.tsx, app/client/src/pages/Editor/EditorHeader.tsx, app/client/src/pages/Editor/IntegrationEditor/MockDataSources.tsx, app/client/src/pages/organization/AppInviteUsersForm.tsx, app/client/src/pages/organization/General.tsx, app/client/src/pages/organization/Members.tsx, app/client/src/pages/organization/OrgInviteUsersForm.tsx, app/client/src/pages/organization/settings.tsx, app/client/src/sagas/ApiPaneSagas.ts, app/client/src/sagas/ApplicationSagas.tsx, app/client/src/sagas/CurlImportSagas.ts, app/client/src/sagas/DatasourcesSagas.ts, app/client/src/sagas/GitSyncSagas.ts, app/client/src/sagas/JSPaneSagas.ts, app/client/src/sagas/OrgSagas.ts, app/client/src/sagas/PluginSagas.ts, app/client/src/sagas/ProvidersSaga.ts, app/client/src/utils/hooks/useOrg.tsx
This PR splits the code which is needed for hiding the appsmith watermark in view mode
Fixes #14143
- New feature 
=> chore: code split for hiding branding badge

app/client/src/RouteBuilder.ts, app/client/src/ce/pages/AdminSettings/BreadcrumbCategories.tsx, app/client/src/ce/pages/AdminSettings/LeftPane.tsx, app/client/src/ce/pages/AdminSettings/Main.tsx, app/client/src/ce/pages/AdminSettings/config/authentication/AuthPage.tsx, app/client/src/components/ads/Dropdown.tsx, app/client/src/components/ads/Icon.tsx, app/client/src/components/ads/MenuItem.tsx, app/client/src/components/ads/SearchInput.tsx, app/client/src/components/editorComponents/form/FormDialogComponent.tsx, app/client/src/components/editorComponents/form/fields/DropdownWrapper.tsx, app/client/src/components/editorComponents/form/fields/SelectField.tsx, app/client/src/constants/Colors.tsx, app/client/src/constants/routes.ts, app/client/src/entities/FeatureFlags.ts, app/client/src/pages/Settings/SettingsForm.tsx, app/client/src/pages/Settings/components.ts, app/client/src/pages/organization/helpers.ts, app/server/appsmith-server/src/main/java/com/appsmith/server/featureflags/FeatureFlagEnum.java, app/server/appsmith-server/src/main/resources/features/init-flags.yml
> Refactor code for RBAC feature
Fixes #13009 
- Code Refactor
> Just tested if the below functionalities work as usual on CE:
- Admin settings routes
- Dropdowns
- Search bars (UI)
=> chore: Refactor code for RBAC feature

deploy/docker/utils/bin/backup.js, deploy/docker/utils/bin/export_db.js, deploy/docker/utils/bin/index.js, deploy/docker/utils/bin/restore.js, deploy/docker/utils/bin/utils.js
Introduces an `appsmithctl backup` and `appsmithctl restore` command that'll backup and restore everything.
TODO
=> feat: Backup & Restore commands

app/client/cypress.json, app/client/cypress/fixtures/datasources.json, app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/ExplorerTests/Entity_Explorer_Datasource_Structure_spec.js
> Fixes CI Mongo spec failures
- New DB name (non-breaking change which adds functionality)
> Release CI
=> test: Updating Mongo DB name to match Mongo TED database name

app/client/cypress.json, app/client/cypress/fixtures/datasources.json, app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/ExplorerTests/Entity_Explorer_Datasource_Structure_spec.js, app/client/src/utils/hooks/useDynamicAppLayout.tsx
hotfix for #14400 and #14389 for the master branch
=> fix: App canvas is stuck in loading state ( Desktop Layout ) + Updating Mongo DB name to match Mongo TED database name 

.github/workflows/packer-ami-build.yml, deploy/packer/template.json.pkr.hcl
For every appsmith-release  we release an ami image into aws and Digital Ocean to make life of users easy
Fixes #14144 
- Tested the pipeline.
=> Feat: Add workflow to publish packer image

deploy/docker/utils/bin/restore.js
Restore.js - encryptionSalt variable typo fix
=> fix: restore encryption sale var typo fix

app/server/appsmith-server/src/main/java/com/appsmith/server/acl/AppsmithRole.java, app/server/appsmith-server/src/main/java/com/appsmith/server/constants/FieldName.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/UserGroup.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/UserInGroup.java, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/InviteUsersDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/UserGroupRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserGroupServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserGroupServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/WorkspaceServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ApplicationForkingServiceTests.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ShareWorkspacePermissionTests.java
=> Feat rbac invite user

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java
=> made inviteUsers cancelable

.github/workflows/label-checker.yml
Add case for test plan checker to ignore "Release Promotion", "CI" and "Design System POD" PRs
=> ci: Update Test plan checker

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java
When a new branch is created where source branch has a custom theme, theme is not copied.
Fixes #14645
- Manually
- JUnit
=> fix: Custom theme not copied when creating new branch

app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/WorkspaceControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/UserInGroup.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/UserRole.java, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/UserAndGroupDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomUserGroupRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomUserGroupRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomUserRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomUserRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/WorkspaceServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserGroupServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserGroupServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/WorkspaceServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/WorkspaceServiceUnitTest.java
=> Feat: RBAC Get members using defaultgroups

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/AppThemingTests/Theming_spec.js, app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OnLoadTests/JSOnLoad_Spec.ts, app/client/src/pages/AppViewer/PrimaryCTA.tsx
Fixes the CI failures happening on theming spec
=> fix: Edit App button not confirming to the theme

app/server/appsmith-server/pom.xml, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/WorkspaceControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/UserGroupInfoDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/WorkspaceServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/configurations/ModelMapperConfig.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/WorkspaceServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/WorkspaceServiceUnitTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ShareWorkspacePermissionTests.java
=> feat: Updated get roles API to return default user groups

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
Changed the datasource component for graphql
Fixes #14716
Manually
=> fix: Updated the graphql ds to use api ds form

app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserServiceTest.java
Fixes the test failure for anonymous users in user service test
- Manually
=> fix: Test failure for get profile of anonymous users

app/server/appsmith-server/src/test/java/com/appsmith/server/controllers/ApplicationControllerTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/controllers/WorkspaceControllerTest.java
Fixes build failure due to missing dependency in controller tests.
- JUnit tests
=> fix: Server build failure due to failing tests

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/PluginUtils.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/JsonSchemaMigration.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceTriggerSolutionCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/CreateDBTablePageSolutionTests.java
- Switched server schema migration version
- Created mock object for test
- Swapped out replace string logic
=> Fixed a few test errors

.github/workflows/integration-tests-command.yml, .github/workflows/test-build-docker-image.yml
add matrix for fat container tests
Fixes # 
code walk through
=> test: add matrix for fat container tests

app/client/src/constants/ThemeConstants.tsx
Updates the border radius and box shadow labels in widgets
Fixes #13992
- Bug fix
=> fix: Updates border radius and box shadow labels in widgets

app/client/src/widgets/CheckboxGroupWidget/component/index.tsx, app/client/src/widgets/CheckboxGroupWidget/widget/index.tsx
Reverts appsmithorg/appsmith#14820
=> fix: revert checkbox-group widget breaking UI issue

app/client/src/components/ads/JSToggleButtonComponent.tsx
Bring back the changes from [#12754](https://github.com/appsmithorg/appsmith/pull/12754/files#diff-f3eff15dabb2b9466b860525f8c37b74e0e4153683efa81509da4f7d5c101906R72) which got removed in [#14869](https://github.com/appsmithorg/appsmith/pull/14869/files#diff-8d717ab3347955fb87b6230fc080d294e4e2d5a21c0a93764d549b6eaec3d327R6)
Fixes #14973
- Manual
=> fix: Disabled state UI for JS toggle button

app/client/src/components/formControls/DropDownControl.tsx, app/client/src/components/formControls/DynamicInputTextControl.tsx, app/client/src/components/formControls/DynamicTextFieldControl.tsx, app/client/src/components/formControls/EntitySelectorControl.tsx, app/client/src/components/formControls/PaginationControl.tsx, app/client/src/components/formControls/SortingControl.tsx, app/client/src/components/formControls/WhereClauseControl.tsx
Minor changes to bring UQI components in sync with design system and fix alignment issues
Fixes #15022 
- Test A
- Test B
=> fix: UQI UI alignment fixes

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
=> fix: Handled migration of empty condition objects, or missing operators

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug14299_Spec.ts, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ExplorerTests/JSEditorContextMenu_Spec.ts, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/TableBugs_Spec.ts, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/TableFilter_Spec.ts, app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/GenerateCRUD/Postgres_Spec.ts, app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts, app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OnLoadTests/JSOnLoad_Spec.ts, app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Params/PassingParams_Spec.ts, app/client/cypress/support/Pages/AggregateHelper.ts, app/client/cypress/support/Pages/EntityExplorer.ts
> This PR fixes the Postgres spec failure in CI runs introduced due to PR #15035 
- Fix for failure case (non-breaking change which tests functionality)
> CI runs
=> test: Script fixes for failing cases due to UQI css changes

app/client/src/components/editorComponents/GlobalSearch/GlobalSearchHooks.tsx, app/client/src/pages/Editor/Explorer/Files/Submenu.tsx, app/client/src/utils/AnalyticsUtil.tsx
Send only pageId for redirect call.
Fixes #15175
Manually
=> fix: curl import error

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Git/GitDiscardChange/DiscardChanges_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Modal_spec.js, app/client/cypress/support/gitSync.js, app/client/src/reducers/uiReducers/gitSyncReducer.ts, app/client/src/sagas/GitSyncSagas.ts
After discard is successful, reload the default page.
Fixes #13736
=> fix: reload default page on discard

app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomUserRepositoryCEImpl.java
=> fixed isUserEmpty function

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserWorkspaceServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ApplicationFetcherCEImpl.java
=> fixes for user homepage and get members

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ExplorerTests/Create_Mongo_query_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Iframe_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Git/GitSync/GitSyncedApps_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ThemingTests/Theme_FormWidget_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Custom_Chart_spec.js, app/client/cypress/support/commands.js, app/client/cypress/support/widgetCommands.js
This PR fixes tests:
- GitSyncedApp_spec.js
- Custom_Chart_spec.js
- Theme_FormWidget_spec.js
- Create_Mongo_query_spec.js
- Iframe_spec.js
- Test A
- Test B
=> test: Fix flaky cypress tests

app/client/src/constants/ThirdPartyConstants.tsx, app/client/src/pages/Editor/gitSync/utils.ts, app/client/src/selectors/gitSyncSelectors.tsx
With the new documentation structure, updating the URLs which are being used in tests.
=> test: Update documentation URLs used in tests

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java
=> fixed bulkAddUserMono not getting executed

app/client/cypress.json, app/client/src/comments/AppComments/AppComments.tsx, app/client/src/comments/AppComments/AppCommentsHeader.tsx, app/client/src/notifications/NotificationsList.tsx, app/client/src/pages/Editor/ToggleModeButton.tsx, app/server/appsmith-server/src/main/resources/email/commentAddedTemplate.html
Adds deprecation warning for comments
Resolves #15364
=> chore: Deprecation warning for comments

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/BaseDomain.java, app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationSuccessHandlerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/UserSignupCEImpl.java
=> fix: for creating default first app in workspace after user signs up

app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ApplicationForkingServiceTests.java
Fixes issue in ApplicationForkingServiceTests
- Local tests
=> chore: Fixing flaky test in ApplicationForkingServiceTests

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
> Fix the NPE issue in theming while copying the properties. 
> Locally
=> chore: NPE issue while copying in git-theming migration

app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/PluginWorkspaceDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ApplicationForkingServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ApplicationFetcherUnitTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ApplicationForkingServiceTests.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/AuthenticationServiceTest.java
=> Solution test fixes

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/exceptions/BaseException.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ActionConfiguration.java, app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java, app/server/appsmith-plugins/arangoDBPlugin/src/main/java/com/external/plugins/ArangoDBPlugin.java, app/server/appsmith-plugins/dynamoPlugin/src/main/java/com/external/plugins/DynamoPlugin.java, app/server/appsmith-plugins/elasticSearchPlugin/src/main/java/com/external/plugins/ElasticSearchPlugin.java, app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/FirestorePlugin.java, app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/plugins/GoogleSheetsPlugin.java, app/server/appsmith-plugins/mssqlPlugin/src/main/java/com/external/plugins/MssqlPlugin.java, app/server/appsmith-plugins/mssqlPlugin/src/test/java/com/external/plugins/MssqlPluginTest.java, app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java, app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java, app/server/appsmith-plugins/rapidApiPlugin/src/main/java/com/external/plugins/RapidApiPlugin.java, app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/plugins/RedisPlugin.java, app/server/appsmith-plugins/redshiftPlugin/src/main/java/com/external/plugins/RedshiftPlugin.java, app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/OAuth2ClientCredentials.java, app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java, app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java, app/server/appsmith-plugins/smtpPlugin/src/main/java/com/external/plugins/SmtpPlugin.java, app/server/appsmith-plugins/snowflakePlugin/src/main/java/com/external/plugins/SnowflakePlugin.java, app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/MDCConfig.java, app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/MdcConfig.java, app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/GlobalExceptionHandler.java, app/server/appsmith-server/src/main/java/com/appsmith/server/filters/MDCFilter.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java, app/server/appsmith-server/src/main/resources/application.properties, app/server/appsmith-server/src/test/java/com/appsmith/server/configurations/MDCConfigTest.java
The primary intent of this PR was to include request metadata into Sentry for the error logging that we have. This was not possible to do so far because the `GlobalExceptionHandler` loses track of the context of the user by the time flow of execution reaches there. There are a bunch of fixes that this PR introduces to address this, and a few other concerns with our logging.
1. We now explicitly pass the context map via Appsmith exceptions so that the exception handler can use this information while logging errors.
2. Introduced a hook on to Webflux signals so that the MDC context from the original subscription flows into all the threads that are spawned during the course of an API request execution. This makes sure that the error signals also retain the original MDC context data so that …
=> chore: Better server logging infra

app/server/appsmith-server/src/main/java/com/appsmith/server/acl/ce/PolicyGeneratorCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/UpdatePermissionGroupDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/PermissionGroupServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserWorkspaceServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCEImpl.java
=> backend api changes for invite flow

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ExplorerTests/Create_Mongo_query_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Git/GitSync/GitSyncedApps_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Git/GitSync/Git_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Git/GitSync/Merge_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Git/GitSync/SwitchBranches_spec.js, app/client/cypress/support/ApiCommands.js, app/client/cypress/support/gitSync.js
This PR fixes flaky git tests by adding additional wait 
locally
=> test: fix git cypress tests

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/ce/FilterDataServiceCE.java, app/server/appsmith-plugins/snowflakePlugin/src/main/java/com/external/plugins/SnowflakePlugin.java, app/server/appsmith-plugins/snowflakePlugin/src/main/java/com/external/utils/ExecutionUtils.java
This is based on warnings from Sonar's static code analysis.
=> chore: Closing resources to ensure there are no memory leaks

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java
This fixes the flaky tests case in ApplicationForkingServiceTests
- JUnit Repeated Tests on local
=> chore: Fixed flaky ApplicationForkingServiceTests

contributions/ClientSetup.md
Updating the ClientSetup.md to include instructions to run cypress tests with TED 
- Test A
- Test B
=> chore: Update ClientSetup.md

app/server/appsmith-server/src/test/java/com/appsmith/server/configurations/SeedMongoData.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ExamplesWorkspaceClonerTests.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ShareWorkspacePermissionTests.java
=> fixed solutions test cases

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserWorkspaceServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserWorkspaceServiceUnitTest.java
=> fixed WorkspaceServiceUnitTest

app/server/appsmith-server/src/test/java/com/appsmith/server/configurations/SeedMongoData.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserServiceWithDisabledSignupTest.java
=> UserServiceWithSignupDisabledTests fixed

app/client/src/comments/AppComments/AppComments.tsx, app/client/src/notifications/NotificationsList.tsx, app/server/appsmith-server/src/main/resources/email/commentAddedTemplate.html
Update messaging to reflect the new deadline of commenting deprecation
=> chore: Extend commenting deprecation deadline to 1.7.12

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserWorkspaceServiceCEImpl.java
=> fixed deleted users

app/client/src/components/utils/helperComponents.tsx, app/client/src/pages/workspace/Members.tsx
Added spacing for the listing UI, header and back button.
- Manual
=> fix: members page style update -- added spacing 

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Linting/BasicLint_spec.ts, app/client/src/components/editorComponents/CodeEditor/constants.ts, app/client/src/workers/Lint/utils.ts
This PR adds [crypto web api](https://developer.mozilla.org/en-US/docs/Web/API/Crypto) support in linting
Fixes #15469 
=> fix: Add support for crypto API in linting

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
=> populate userIds from email incase userId is invalid

app/client/src/sagas/ActionExecution/ActionExecutionSagas.ts, app/client/src/sagas/ActionExecution/PluginActionSaga.ts
> fix issue of showing additional property  success: true field to API response when it is triggered through an event
Fixes #15540 
=> fix: revert success flag from trigger response

app/client/src/pages/workspace/General.tsx, app/client/src/pages/workspace/Members.tsx, app/client/src/pages/workspace/settings.tsx
> Updated the UI for members page.
Fixes #15697 
> Tested the UI for desktop and mobile
=> fix: update UI for members page

deploy/docker/templates/nginx/nginx-app-http.conf.template.sh, deploy/docker/templates/nginx/nginx-app-https.conf.template.sh
Nginx config changes: 
- Disabled nginx server tokens
- Set Gzip-types to *
Fixes: [15700](https://github.com/appsmithorg/appsmith/issues/15700)
=> fix:disable nginx server tokens, set gzip_type to *

app/server/reactive-caching/src/main/java/com/appsmith/caching/CachingConfig.java, app/server/reactive-caching/src/main/java/com/appsmith/caching/aspects/CacheAspect.java, app/server/reactive-caching/src/main/resources/META-INF/spring.factories
=> Added autoconfiguratiosn for caching module

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
=> migrations sturdy towards restart

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
=> permission group read permission for viewer permission group

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCEImpl.java
>
Sort the collection of permission group returned to client in order of Administrator, Developer and Viewer.
Fixes #15708
> Please also list any relevant details for your test …
=> sort the permission group list

app/client/src/utils/WidgetFactory.tsx
Error messages related to widget configuration which are helpful only for Widget developers might cause confusion to our users.
So, removing them for a better UX.
Fixes #15811
- Manual
=> fix: Remove unwanted logs which may confuse the users

app/server/appsmith-server/src/main/java/com/appsmith/server/domains/PermissionGroup.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/MigrationHelperMethods.java
Adding indexes to the permission group collection. Also adding the set of userGroupIds for permission group.
=> chore: add usergroup ids and indexes to permission group

app/server/appsmith-plugins/elasticSearchPlugin/src/main/java/com/external/plugins/ElasticSearchPlugin.java, app/server/appsmith-plugins/elasticSearchPlugin/src/test/java/com/external/plugins/ElasticSearchPluginTest.java, app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java, app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
Cherry picked the following:
- https://github.com/appsmithorg/appsmith/pull/15782
- https://github.com/appsmithorg/appsmith/pull/15834
=> fix: Cherry pick security fixes

app/server/appsmith-server/src/main/java/com/appsmith/server/constants/FieldName.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AnalyticsServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ApplicationForkingServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
This PR adds more data to existing analytics events for audit purposes
- Local tests
=> feat: Added more data to existing analytics events

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/UserUtils.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AnalyticsServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/UserSignupCEImpl.java
>
Summary of changes
1.  Fixed NPE in AnalyticsServiceCEImpl
2. User made super user before running other operations in signupAndLoginSuper
3. Deferred calling of createInstanceConfigForSuperUser in makeSuperAdmin->switchIfEmpty
4. Updated fieldname to update in makeSuperUser
Fixes #15869
- This change …
=> Fix for enabling admin settings

app/client/package.json, app/client/yarn.lock
This PR updates the `babel-plugin-styled-components` since it was breaking design-system components in local development.
Fixes [#15913](https://github.com/appsmithorg/appsmith/issues/15913)
- Checked in local whether component are working fine or not
=> fix: design system package conflict with styled-component

app/server/appsmith-server/src/main/java/com/appsmith/server/featureflags/strategies/AppsmithUserStrategy.java, app/server/appsmith-server/src/main/java/com/appsmith/server/featureflags/strategies/EmailBasedRolloutStrategy.java
@mohanarpit : If these logs are no longer required for debugging, request you to approve the PR. This should reduce a little bit of unnecessary noise from server logs.
=> chore: Removing debug feature flag logs from the server

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/UserUtils.java
=> fix for evicting cache when super user is made

app/rts/Dockerfile
Changed the docker commands to fix the building of docker image for rts server
- Test A
- Test B
=> fix: RTS Docker image build error

app/client/cypress/setup-test-fat.sh
Removed the conflicting part with TED
=> fix: Removed the conflicting part with TED

app/client/src/components/ads/Radio.tsx
Trigger radio on change handler only when it is not a part of selected option element. 
Fixes #15956
- Test A
- Test B
=> fix: cursor pagination separate flag error

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/ExportApplication_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Workspace/DeleteWorkspace_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Workspace/LeaveWorkspaceTest_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Workspace/MemberRoles_Spec.ts, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Workspace/ShareAppTests_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Workspace/UpdateWorkspaceTests_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Workspace/WorkspaceSettings_validation_spec.js, app/client/cypress/locators/HomePage.js, app/client/cypress/support/Pages/HomePage.ts, app/client/cypress/support/WorkspaceCommands.js, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/UserUtils.java
Fixes workspace related cypress tests as per new ACL structure and add use case when user has been invited as a developer/app viewer/admin in the workspace. When this user invites other users, the roles available for the invite should show accordingly.
locally
=> test: update workspace cypress tests

app/client/src/workers/DependencyMap/index.ts
Fixes #15524 
Currently unable to reproduce
=> fix: undefined triggerpath dependency

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserWorkspaceServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/WorkspaceServiceTest.java
=> fix: Sort members of workspace according to role name and then by username

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
- Currently all the required data is already being sent. This PR introduces a minor change to rename the plugin name along the same lines as the REST API plugin since the current plugin name could be a bit misleading. 
Fixes #12394 
- Manual via setting up a test segment account
- Automated test for this seems not possible at the moment.
=> fix: provide analytics data for graphql plugin

Dockerfile, app/rts/build.sh
- Added the removal of rts previous build before building new image
- Fixed Fat container copying of dist folder to rts image directory path in docker container
Fixes #16091
- Test A
- Test B
=> fix: rts fat container docker image

.github/workflows/integration-tests-command.yml, .github/workflows/test-build-docker-image.yml, app/client/cypress/setup-test.sh
TED run command updated
Locally
=> fix: TED run command updated

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCEImpl.java
Execute action triggered events were not getting logged because of a lack of subscription. Fixed in place.
- Locally connected to segment
=> fix: Logging execute events again

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Multiselect/Multi_Select_Tree_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Select/Single_Select_Tree_spec.js, app/client/package.json, app/client/src/widgets/JSONFormWidget/fields/MultiSelectField.tsx, app/client/src/widgets/JSONFormWidget/helper.ts, app/client/src/widgets/MultiSelectTreeWidget/component/index.tsx, app/client/src/widgets/MultiSelectTreeWidget/widget/index.tsx, app/client/src/widgets/MultiSelectWidget/component/index.tsx, app/client/src/widgets/MultiSelectWidget/widget/index.tsx, app/client/src/widgets/MultiSelectWidgetV2/component/index.tsx, app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx, app/client/src/widgets/SingleSelectTreeWidget/component/index.tsx, app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx, app/client/src/widgets/useDropdown.tsx, app/client/yarn.lock
> Show not found text when the search field does not match listed options
Fixes #15119 
=> fix: search functionality in tree select

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserWorkspaceServiceCEImpl.java
=> undo sorting change

app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OnLoadTests/JSOnLoad1_Spec.ts, app/client/package.json, app/client/yarn.lock
- This PR fixes the http-proxy reference
=> test: Fixing http-proxy version

app/client/src/components/formControls/DropDownControl.tsx
Added the condition to remove older column names and update the projection values to the existing columns only.
eg : 
- *projection value* : key - `entities.actions[actionIndex].config.actionConfiguration.formData.projection.data`  , value - `['a', 'b', 'c']`
- *trigger value* : key - `evaluations.triggers[actionId].rows_get_projection.fetchDynamicValues.data`, value - `[{ label: 'A', value: 'a' }, { label: 'B', value: 'b' }, { label: 'D', value: 'd' }]`
`selectedOptions` are created by filtering all options with only option value present in selectedValue.
- *options*: `[{ label: 'A', value: 'a' }, { label: 'B', value: 'b' }, { label: 'D', value: 'd' }]`
- *selectedOptions* : `[{ label: 'A', value: 'a' }, { label: 'B', value: 'b' }]`
- *selectedValue*: `['a', 'b', 'c']`
- …
=> fix: old column names exists even after renamed columns

app/client/src/pages/workspace/Members.tsx, app/client/src/pages/workspace/WorkspaceInviteUsersForm.tsx
> Fixed the UI of the members page dropdown popup
Fixes #16063 
> Tested the UI of the dropdown to be as expected
=> fix: UI of the members page dropdown popup

app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/QueryPane/Mongo_Spec.js, app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/QueryPane/Mongo_Spec.ts, app/client/src/components/formControls/DynamicTextFieldControl.tsx, app/client/src/constants/QueryEditorConstants.ts, app/client/src/sagas/QueryPaneSagas.ts
This PR fixes the creation of Find, Create, Update and Delete templates for MongoDB Raw command.
Fixes #16019 
Cypress Tests
=> fix: Fix template for MongoDB Raw command

app/client/cypress/support/Pages/HomePage.ts
=> test: Update MemberRoles_spec test

app/client/src/utils/autocomplete/TernServer.ts
Hotfix to resolve `focusedValue` undefined error 
=> fix: ternserver code

app/client/src/components/editorComponents/form/fields/StyledFormComponents.tsx, app/client/src/pages/Editor/FormConfig.tsx
Reverts appsmithorg/appsmith#15866
=> fix: Reverting Fix Encrypted Text alignment

app/server/appsmith-server/src/main/java/com/appsmith/server/domains/PermissionGroup.java
=> Initialize assignedToUserIds and assignedToGroupIds

.github/workflows/integration-tests-command.yml, .github/workflows/test-build-docker-image.yml
Fixed the s3 image download location path.
Locally
=> fix: changed the download paths

app/client/src/pages/Settings/FormGroup/group.tsx
> Fixed import of the admin settings button
=> fix: import of admin settings button

.github/workflows/integration-tests-command.yml
=> fix: a typo (conatiner -> container)

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/TableV2/pagesize_spec.js, app/client/src/widgets/TableWidgetV2/widget/derived.js
Fixes #15984 
- Test A
- Test B
=> fix: Table widget pagesize in short row height mode

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Autocomplete/Autocomplete_JS_spec.ts, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/Bind_MultiSelect_Button_Text_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/AllInputWidgets_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/AllWidgets_default_meta_spec.js, app/client/cypress/locators/WidgetLocators.ts, app/client/cypress/support/Pages/AggregateHelper.ts, app/client/cypress/support/Pages/ApiPage.ts, app/client/cypress/support/Pages/JSEditor.ts, app/client/src/constants/defs/browser.json, app/client/src/pages/Editor/JSEditor/Form.tsx, app/client/src/utils/autocomplete/AutocompleteSortRules.ts, app/client/src/utils/autocomplete/EntityDefinitions.ts, app/client/src/utils/autocomplete/TernServer.test.ts, app/client/src/utils/autocomplete/TernServer.ts, app/client/src/utils/autocomplete/dataTreeTypeDefCreator.test.ts, app/client/src/utils/autocomplete/dataTreeTypeDefCreator.ts, app/client/src/utils/autocomplete/keywordCompletion.ts
=> fix: autocompletion issues

app/client/src/constants/Currency.tsx
> Added missing currency for Vanuatu
- Addition to list of constants
=> feat: Added Vanuatu Vatu to currency list

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/CollectionUtils.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/MigrationHelperMethods.java
=> feat: Adding cache eviction for users whose permissions change due to super user changes

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCEImpl.java
This adds the missing analytics event for workspace creation
- Locally
=> fix: Added analytics event for workspace creation

app/client/src/ce/pages/AdminSettings/index.tsx, app/client/src/pages/Settings/components.tsx
> Shifted loader component to common file so that it can be used in other components as well.
Fixes #16376 
- Refactoring
> Tested if the loader on Admin settings screen is working as expected.
=> refactor: Shift loader component to common file

.github/config.yml
Updated the message to include request for raising a review, its a critical piece of information people should have
- content change
- None
=> chore: Update the welcome bot message

app/client/src/components/ads/DraggableListComponent.tsx, app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx, app/client/src/components/editorComponents/Debugger/hooks/useGetEntityInfo.tsx, app/client/src/components/editorComponents/DropTargetComponent.tsx, app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx, app/client/src/pages/AppViewer/AppViewerPageContainer.tsx, app/client/src/pages/Editor/APIEditor/Form.tsx, app/client/src/pages/Editor/JSEditor/Form.tsx, app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx, app/client/src/pages/Editor/PropertyPaneTitle.tsx, app/client/src/pages/Editor/WidgetsEditor/CanvasContainer.tsx, app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx, app/client/src/pages/common/CanvasArenas/hooks/useBlocksToBeDraggedOnCanvas.ts, app/client/src/sagas/CanvasSagas/SelectionCanvasSagas.ts, app/client/src/sagas/DatasourcesSagas.ts, app/client/src/utils/DynamicBindingUtils.test.ts, app/client/src/utils/klona.test.ts, app/client/src/widgets/ChartWidget/component/index.tsx, app/client/src/widgets/FormWidget/widget/index.tsx, app/client/src/widgets/ListWidget/widget/index.tsx, app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx, app/client/src/widgets/SelectWidget/component/index.tsx, app/client/src/widgets/SelectWidget/widget/index.tsx, app/client/src/widgets/TableWidget/component/AutoToolTipComponent.tsx, app/client/src/widgets/TableWidget/component/index.tsx, app/client/src/widgets/TableWidget/widget/index.tsx, app/client/src/widgets/TableWidgetV2/component/index.tsx, app/client/src/widgets/TableWidgetV2/widget/index.tsx, app/client/src/widgets/TextWidget/component/index.tsx
The change is a refactoring work. All usages of isEqual method from lodash has been replaced with equal method from fast-deep-qual/es6. This shall optimise the speed of execution as already analysed by the task creator.
Fixes #16421 
This has not been tested other than reviewing the code changes.
=> fix: Refactoring to replace all usages of isEqual method from lodash with equal method from fast-deep-equal/es6

app/server/appsmith-server/src/main/resources/system-themes.json
This PR adds QR Scanner to the System Themes. Merging this change in a separate PR. This should be merged before #15990 to enable testing #15990 on DPs.
- Manually tested.
=> feat: Add QR Scanner to System Themes

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
=> fix: Duplicating themes where 1:many applications mapping exists

.github/workflows/test-build-docker-image.yml
>
Adding perf tests as part of merge workflows.
Fixes #16281
- Test A
- Test B
=> fix: adding perf test runs to workflows post merge to release.

.github/workflows/test-build-docker-image.yml
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX18Nmxq3Pw3IMuA7ciipYQCHUl7ws61BXY%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=PUr4nwX)
>
making changes to perf-test workflow to work for pr merge as well as pr approval.
Fixes #16281
- Breaking change (fix or feature that would …
=> fix: fixing perf test workflow during merge.

app/client/src/utils/autocomplete/TernServer.ts
Fixes #16569
Manual Test 
Will automate the test in this PR - https://github.com/appsmithorg/appsmith/pull/16314
=> fix: Add remove def when updating def

app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/AuthenticationSuccessHandler.java, app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationSuccessHandlerCE.java
Fixes #16548
In case of form login, the signup and login flow ensures the mandatory creation of first workspace before creating the first app. This was missing of OAuth2 signup flow.
=> fix: Creating default workspace for SSO signed up users before creating first application

.github/workflows/test-build-docker-image.yml
removing "Exit if Server hasnt started" step.
Fixes #16281 
- Test A
- Test B
=> fix: removing "Exit if Server hasn't started" coz its not needed.

.github/workflows/integration-tests-command.yml, .github/workflows/test-build-docker-image.yml
- This PR makes changes for moving from Chrome to Electron browser for CI runs & fixes the git hub runners failure issue incases of Chrome version updates
- Browser name update
=> test: Moving from Chrome to Electron browser for CI runs

app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/AuthenticationSuccessHandler.java, app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationSuccessHandlerCE.java
=> fix: Duplicate default workspaces for first login using SSO

.github/workflows/integration-tests-command.yml, .github/workflows/test-build-docker-image.yml
- This PR makes changes to run CI on latest stable Chrome always
- Browser update
=> test: Running CI on latest Chrome browser

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Git/GitSync/RepoLimitExceededErrorModal_spec.js
We need to organize the Cypress test suite in a way that we have different checks running in CE vs EE.
- Relying on CI
=> ci: Removing the git repo limit test as this test will fail in EE.

.github/workflows/integration-tests-command.yml, .github/workflows/rts-build.yml, .github/workflows/test-build-docker-image.yml
This is for integration-test and test-build-docker workflow steps.
- Forked repository
=> ci: Fixing the notification & Depot Docker build step 

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Git/GitImport/GitImport_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Git/GitSync/Git_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Git/GitSync/Merge_spec.js, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Git/GitSync/RepoLimitExceededErrorModal_spec.js, app/client/cypress/support/gitSync.js
This PR adds a check to run RemoLimitExceededModal_spec in CE repo only and fixes following flaky tests
- Merge_spec.js
- Git_spec.js
- GitSyncedApp_spec.js
Locally
=> test: Fix flaky git tests

app/client/src/constants/WidgetConstants.tsx, app/client/src/utils/DSLMigrations.ts
=> chore: fix table widget migration merge conflict

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OtherUIFeatures/Fork_Template_spec.js
Updated the locator in Fork_template_spec in order to make sure the test always pick the Customer Support Dashboard template to fork and do not become flaky
locally
=> test: update cypress test fork_template_spec 

app/client/src/components/editorComponents/CodeEditor/lintHelpers.test.ts, app/client/src/components/editorComponents/CodeEditor/lintHelpers.ts, app/client/src/workers/Lint/index.ts, app/client/src/workers/Lint/utils.ts
=> fix: incorrect lint error position

.github/workflows/integration-tests-command.yml
Fix tar download for rts
Code review
=> ci: Fix tar download for rts

.github/workflows/integration-tests-command.yml
=> ci: Fix rts dist

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/converters/GsonISOStringToInstantConverter.java
Added code to the java.time.Instant deserializer to handle Instants represented as JSON Objects.
No dependency changes.
Fixes #16320 
I have an application export file that would not import, as described in issue #16320 
I was able to import the file with this fix.
The export was generated on Appsmith 1.7.5
The import was done on the latest release branch (as of the date of this PR).
=> fix: Deserialize java.time.Instant objects that are represented as JSON objects

.github/workflows/integration-tests-command.yml
=> ci: Fix ui-test cache

app/client/src/widgets/TableWidgetV2/constants.ts, app/client/src/widgets/TableWidgetV2/widget/index.tsx
Fixes #16725
- Test A
- Test B
=> fix: table widget issue where editableCell is undefined

app/client/src/components/editorComponents/DynamicHeightOverlay.tsx
Filling the signifiers with priamry color
=> feat: filling the signifiers with priamry color.

app/client/src/constants/WidgetConstants.tsx, app/client/src/sagas/dynamicHeightSagas.ts
=> Fix issue #16590

app/client/src/components/editorComponents/DynamicHeightOverlay.tsx
made the signifiers dashes border draggable
=> fix: made the signifiers dashes border draggable

app/client/src/components/editorComponents/DynamicHeightOverlay.tsx
signifiers cannot be dragged less than 4
=> fix: signifiers cannot be dragged less than 4

app/server/appsmith-server/src/main/java/com/appsmith/server/domains/UserSession.java
This PR adds the user's name to the userSession.
- on local dev
=> chore: Added users name to sessionUser

.github/workflows/test-build-docker-image.yml
Fix ci cache & rts build for push workflow
Fix ci cache & rts build for push workflow
code review
=> ci: Fix ci cache & rts build for push workflow

.github/workflows/test-build-docker-image.yml
removed rts download for modues
removed rts download for modues
code review
=> ci: removed rts download for modues

.github/workflows/test-build-docker-image.yml
Fix ci cache & rts build for push workflow
Fix ci cache & rts build for push workflow
code review
=> ci: Fix ci cache 

.github/workflows/test-build-docker-image.yml, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/TriggerUtils.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/URIUtils.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/util/WebClientUtils.java, app/server/appsmith-plugins/graphqlPlugin/src/main/java/com/external/plugins/GraphQLPlugin.java, app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java, deploy/docker/entrypoint.sh, deploy/docker/templates/supervisord/mongodb.conf
Promotion to master V1.8.1 try 4
=> chore: v1.8.1 promotion try 4

app/client/src/widgets/CodeScannerWidget/widget/index.tsx
=> fix: added a condition to check for accentColor

app/client/src/widgets/BaseWidget.tsx, app/client/src/widgets/CheckboxGroupWidget/component/index.tsx, app/client/src/widgets/DynamicHeightContainer.tsx, app/client/src/widgets/RadioGroupWidget/component/index.tsx, app/client/src/widgets/SwitchGroupWidget/component/index.tsx
Tried solving the scroll issue for widgets when there are limits
=> fix: auto height limits scroll issue

app/client/src/widgets/BaseWidget.tsx, app/client/src/widgets/DynamicHeightContainer.tsx
Auto height input label out of border problem mentioned in bug #16590
=> fix: auto height input label oob

app/client/src/ce/constants/messages.ts, app/client/src/components/editorComponents/StoreAsDatasource.tsx
Updated the texts for save as datasource or edit datasource button present in Api editor at two places (one in authentication tab and the other on the right side of url field).
Fixes #12842
- Test A
- Test B
=> fix: updated message changes for auth tab, capital texts

app/client/src/sagas/EvaluationsSaga.ts, app/client/src/sagas/dynamicHeightSagas.ts, app/client/src/utils/treeManipulationHelpers/dynamicHeightReflow.ts, app/client/src/widgets/BaseWidget.tsx, app/client/src/widgets/withWidgetProps.tsx
- Adds feature to make sure invisible widgets don't take space in view mode.
- Adds feature to make sure replay updates don't get called in view mode.
=> (WIP): In view mode, invisible widgets now donot take space

app/client/src/widgets/BaseWidget.tsx
Removed the scroll container for container-type widgets.
=> fix:auto height container container

app/server/appsmith-server/src/main/java/com/appsmith/server/featureflags/FeatureFlagEnum.java, app/server/appsmith-server/src/main/resources/features/init-flags.yml
Creating a feature flag for internal testing of Templates phase 2
=> feat: Create a feature flag for Templates: Phase 2

app/server/reactive-caching/src/main/java/com/appsmith/caching/components/RedisCacheManagerImpl.java
Adding logs for cache miss, cache put and cache eviction to debug corrupted cache entry state.
=> chore: Adding cache logs for debugging

app/client/src/utils/WidgetFeatures.ts, app/client/src/widgets/JSONFormWidget/widget/index.tsx
- Fix issue where using a value less than 4 caused an error for min and max dynamic height
- Fix issue where JSONForm did not adhere to min and max dynamic height limits.
=> WIP: POC: fix dynamic height issues 

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ExplorerTests/Admin_settings_spec.js, app/client/cypress/integration/Smoke_TestSuite_Fat/ClientSideTests/AdminSettings/Admin_settings_spec.js, app/client/cypress/integration/Smoke_TestSuite_Fat/ClientSideTests/FormLogin/EnableFormLogin_spec.js, app/client/cypress/integration/Smoke_TestSuite_Fat/ClientSideTests/Github/EnableGithub_spec.js, app/client/cypress/integration/Smoke_TestSuite_Fat/ClientSideTests/Google/EnableGoogle_spec.js, app/client/cypress/support/AdminSettingsCommands.js, app/client/src/pages/Home/LeftPaneBottomSection.tsx, app/client/src/pages/common/MobileSidebar.tsx, app/client/src/pages/common/ProfileDropdown.tsx
Moving "Admin Settings" from Profile menu to LeftBottomPane.
=> feat: introduce admin settings to left bottom pane

contributions/docs/TestAutomation.md
> This PR includes changes to document on contributing to Cypress Test suite
Fixes #12358
- Documentation update
=> docs: Update Cypress link in test automation README

app/client/src/widgets/BaseWidget.tsx
Fixed the should dynamic height logic to respect the min-height limit.
=> fix: fixed the should dynamic height logic to respect the min height limit

scripts/local_testing.sh
Build fat container locally using local changes. So that you don't have to commit and push changes to do a local test
=> feat: [scripts] Add option for using local changes instead of a git branch

app/client/src/components/editorComponents/DropTargetComponent.tsx, app/client/src/reducers/entityReducers/canvasWidgetsReducer.ts, app/client/src/reducers/entityReducers/widgetConfigReducer.ts, app/client/src/sagas/PageSagas.tsx, app/client/src/sagas/WidgetAdditionSagas.ts, app/client/src/sagas/dynamicHeightSagas.ts, app/client/src/selectors/editorSelectors.tsx, app/client/src/utils/WidgetFeatures.ts, app/client/src/utils/hooks/useDynamicAppLayout.tsx, app/client/src/widgets/ContainerWidget/component/index.tsx, app/client/src/widgets/ContainerWidget/widget/index.tsx, app/client/src/widgets/JSONFormWidget/widget/index.tsx, app/client/src/widgets/TabsWidget/index.ts
- This PR enables dynamic height for modal widget
=> Modal widget adheres to dynamic height

app/client/src/constants/WidgetConstants.tsx, app/client/src/entities/Replay/ReplayEntity/ReplayCanvas.ts, app/client/src/sagas/dynamicHeightSagas.ts, app/client/src/widgets/BaseWidget.tsx, app/client/src/widgets/ContainerWidget/component/index.tsx, app/client/src/widgets/JSONFormWidget/widget/index.tsx, app/client/src/workers/replayUtils.ts
=> fix: Dynamic height issue fixes

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/EnvManagerCEImpl.java
This PR fixes an NPE issue that happens when the authentication method is configured while the .env file was empty initially.
- Locally
=> fix: Fixed NPE issue with analytics event on authentication method configuration

app/client/src/pages/Editor/Explorer/Entity/EntityProperties.tsx, app/client/src/pages/Editor/Explorer/Entity/EntityProperty.tsx, app/client/src/utils/AnalyticsUtil.tsx
Added events "SHOW_BINDINGS_TRIGGERED" and "BINDING_COPIED"
Fixes #15876
- Chore (non-breaking chore)
=> chore: Add analytic events for show bindings pane

app/rts/build.sh, app/rts/package.json, app/rts/tsconfig.json
Hotfix to resolve rts build failure
- removal of old build folder to create fresh build everytime
- exclusion of jest config and test cases in build directory
- changed coverage directory
- Test A
- Test B
=> fix: failing rts build due to jest config

app/server/appsmith-server/pom.xml
=> chore: Fixing dependencies

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/EnvManagerCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/EnvManagerTest.java
=> fix: Fix escaping single quotes in env variable values

.github/workflows/integration-tests-command.yml, .github/workflows/test-build-docker-image.yml
add rerun support for fat
code review
=> ci: Add retry for fat container

.github/workflows/integration-tests-command.yml, .github/workflows/test-build-docker-image.yml
=> ci: Fix ci download dup

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/Promises_Spec.ts, app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/GenerateCRUD/Postgres2_Spec.ts, app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Postgres_DataTypes/Json_Spec.ts, app/client/cypress/support/Objects/CommonLocators.ts, app/client/cypress/support/Pages/AggregateHelper.ts, app/client/cypress/support/Pages/DeployModeHelper.ts
- This PR includes fixes for Json spec + Promises spec to unblock CI run failures
- Script fixes (non-breaking change which fixes a cypress script)
- CI runs
=> test: Script updates for flaky tests to unblock CI

.github/workflows/integration-tests-command.yml, .github/workflows/test-build-docker-image.yml
=> ci: Fix fat rerun

app/client/src/ce/pages/workspace/WorkspaceInviteUsersForm.tsx
> Fixed retaining of selected role in the dropdown
Fixes #17257 
> Tested locally
=> fix: Handle retaining of selected role in the dropdown

app/client/src/sagas/TemplatesSagas.ts
Fixes #17023 
Fixes #17270
Fixes #17272
Fixes a scenario which was missed by https://github.com/appsmithorg/appsmith/pull/17038. That PR was related to not making use of the pages returned by the response of the fork template api as they were incorrect. This PR removes the usage of the same for navigation. Instead to  get the page id we make use of the get all pages selector.
Manually. Tests are being added in a different PR https://github.com/appsmithorg/appsmith/pull/17036
=> fix: scenario where unselecting the first page and importing fails

app/client/src/widgets/TableWidgetV2/widget/derived.js
Removed a console error log from a derived property function as it was confusing the user and serving no purpose.
Fixes #14104
=> chore: Remove the unnecessary error log from the derived property function

.github/workflows/integration-tests-command.yml
The ui-test-result step succeeds even though the one of ui-test matrix step fails. This PR should hopefully fix that problem.
=> ci: Update integration-tests-command.yml to handle failures in ui-test step

Dockerfile
This PR fixes outdated comment.
Comment :)
It wasn't.
=> chore: Fix outdated comment

.github/workflows/integration-tests-command.yml
=> chore: Corrected usage of OR operator

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCEImpl.java
Fixed the wrong event data being sent for page view events. 
- Manually
=> fix: Fixed wrong event data on page view event

app/client/src/widgets/BaseWidget.tsx, app/client/src/widgets/ModalWidget/widget/index.tsx
Abstracted the check for dynamic height with limits enabled as isDynamicHeightWithLimitsEnabledForWidget.
=> fix: abstraction checking dynamic enabled

app/client/src/components/editorComponents/DynamicHeightOverlay.tsx, app/client/src/widgets/BaseWidget.tsx
Abstracted the static value of 10 in dynamic height overlay to GridDefaults.
=> fix: change static values grid defaults

app/client/src/widgets/BaseWidget.tsx
Abstracted min and max dynamic height limits to getters.
=> fix: min max dynamic height getter abstraction

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
> Use the isRepoPrivate attribute for analytics instead of the Application object to avoid NPE.
Fixes NPE from [Sentry](https://sentry.io/organizations/appsmith/issues/3020188411/?project=1546547&referrer=regression_activity-email)
=> chore: Fix NPE in git service analytics

.github/workflows/integration-tests-command.yml, .github/workflows/test-build-docker-image.yml
- This PR includes changes for starting rts server for AST changes to take effect
- yml file updates
=> test: RTS server start

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/constants/AnalyticsEvents.java, app/server/appsmith-server/src/main/java/com/appsmith/server/constants/FieldName.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/EnvManagerCEImpl.java
This PR adds analytics events for admin settings update events
- Manually
=> feat: Added analytics events for admin settings updates

app/client/src/ce/constants/messages.ts, app/client/src/components/formControls/BaseControl.tsx, app/client/src/components/formControls/InputTextControl.tsx, app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx, app/client/src/pages/Editor/__tests__/AuthenticatedAPIErrorValidation.test.tsx
Added frontend validation checks for access token url and url in authenticated API datasource configuration.
Fixes #12750 
- Manually
- Jest Unit Tests
=> fix: added url validations in authenticated API DS

.github/workflows/integration-tests-command.yml
added to pull workflow
code review
=> ci: added to pull workflow 

.github/workflows/integration-tests-command.yml
=> ci: fix Pull workflow

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonConfig.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/TenantController.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/EnvManagerImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/EnvManagerCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/EnvManagerTest.java
Also fixing the ObjectMapper configuration to serialize empty beans in the entire product
- Local JUnit & Manual
=> chore: Fixing the API to fetch current tenant configuration

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceContextServiceTest.java
> Fix NPE for datasource archive method analytics.
=> chore: Add properties to analytics event

app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx, app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx, app/client/src/pages/Editor/PropertyPane/PropertySection.tsx, app/client/src/selectors/jsPaneSelectors.ts, app/client/src/selectors/queryPaneSelectors.ts
EE client build is broken due to not following proper code splitting strategy; one file in particularly didn't get split earlier and changes to that file broke the client build on EE.
This PR fixes the issues.
=> chore: Fixing broken client build

app/server/appsmith-server/src/main/java/com/appsmith/server/featureflags/FeatureFlagEnum.java, app/server/appsmith-server/src/main/resources/features/init-flags.yml
=> chore: Added feature flag for datasource environments

app/client/src/components/editorComponents/DynamicHeightOverlay.tsx
Add selectors for the following
=> fix: Auto Height Feature - add selectors for tests

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/SegmentConfig.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/PingScheduledTaskImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PingScheduledTaskCEImpl.java
=> fix: Fix typo in cloud-hosting check and NPE from Segment

app/client/src/constants/DefaultTheme.tsx
Removed height auto css rule from the default theme.
=> fix: removed height auto default theme

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonConfig.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
This PR adds indexes as recommended by MongoDB cloud.
=> chore: Add recommended indexes

app/client/package.json, app/client/yarn.lock
This PR applies the fix for #17645 via [this PR](https://github.com/appsmithorg/design-system/pull/229) onto this repository 
Fixes #17645 
via DP on a local machine
=> fix: toast font on windows

app/client/src/utils/AnalyticsUtil.tsx
See https://www.notion.so/530051a2083040b5bcec15a46121aea3 for details.
=> chore: Change Segment CDN to our proxy

app/client/src/components/editorComponents/DynamicHeightOverlay.tsx
Added the base styles for the overlay like position and z-index in its styled component CSS!
=> fix: modal css auto height with limits

app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/AppsmithRepository.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/BaseAppsmithRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomConfigRepositoryCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/configurations/SeedMongoData.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ExamplesWorkspaceClonerTests.java
Adding base function to set the user permissions for a user in any domain object. 
As part of this, we also add default permission group to the `SeedMongoData`. Without this fix, the JUnit tests go into an infinite loop. Also fixing the `ExampleWorkspaceClonerTest` file.
- JUnit
=> chore: Adding base repository function to add user permissions to generic domain object

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCEImpl.java
Fix NPE for AuditLogs service Test when the action config is null.
=> chore: NPE for action execution tests

app/client/src/ce/pages/AdminSettings/LeftPane.tsx, app/client/src/ce/pages/AdminSettings/config/authentication/AuthPage.tsx, app/client/src/components/editorComponents/EditableText.tsx, app/client/src/pages/Settings/SaveSettings.tsx, app/client/src/pages/Settings/components.tsx
> Update styles of admin settings page.
Fixes [#17759](https://github.com/appsmithorg/appsmith/issues/17759)
- refactor
> Tested the UI on admin settings page in EE.
=> refactor: Update styles of admin settings page

app/client/src/ce/pages/AdminSettings/index.tsx
Only fetch admin settings if the user is Super User.
=> fix: admin settings fetch

app/client/src/pages/Applications/index.tsx, app/client/src/pages/Home/LeftPaneBottomSection.tsx
> Updating left panel CSS on the home page to avoid using definite heights for the sections in it.
Fixes [#17786](https://github.com/appsmithorg/appsmith/issues/17786)
Before:
https://www.loom.com/share/7eead6fcf6f9433eb3a85e4a98fca290
After:
https://www.loom.com/share/59df8c436ba644c9b75b17228ea5c885
https://www.loom.com/share/b6308241e10c48b283f9331b181fe9f0
=> fix: Updating left panel CSS on home page

app/client/src/widgets/BaseInputWidget/component/index.tsx
Fixed the input field stretching issue in case of Dynamic height by adding some CSS styles when isDynamicHeight is true.
=> fix: input label dynamic height issue

app/server/appsmith-server/src/test/java/com/appsmith/server/configurations/SeedMongoData.java
Fixing the flaky behaviour in `SeedMongoData`. This code is creating a race condition that causes the test to fail to start in some cases.
=> chore: Fixing flaky behaviour in SeedMongoData

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AnalyticsServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ThemeServiceCEImpl.java
Adds some changes to layout update and theme change analytics events
- Manual
- JUnit
=> chore: Changes in layout and theme analytics events

app/client/src/widgets/DynamicHeightContainer.tsx
Added a bit of padding of 4px to the right of the scroll container of dynamic height with limit.
=> fix: added a little bit padding of 4px to the right of scroll container

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AnalyticsServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ThemeServiceCEImpl.java
(cherry picked from commit 31b03e893914a23fc9771acca72937d588319174)
Cherry-picked changes for corrected Analytics event for page updates
=> chore: Changes in layout and theme analytics events (#17827)

app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/WorkspaceControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/WorkspaceApplicationsDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/WorkspaceMemberInfoDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/ce/WorkspaceMemberInfoCE_DTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/events/AbstractCommentEvent.java, app/server/appsmith-server/src/main/java/com/appsmith/server/events/CommentAddedEvent.java, app/server/appsmith-server/src/main/java/com/appsmith/server/events/CommentThreadClosedEvent.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserWorkspaceServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserWorkspaceServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ApplicationFetcherCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/EmailEventHandlerCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserWorkspaceServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserWorkspaceServiceUnitTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/WorkspaceServiceTest.java
> Refactor `getWorkspaceMember` service and api call to introduce a new DTO class to be used in the EE version.
Fixes #17890 
> Since no functionality has changed, this doesn't require any new test case.
=> chore: refactor workspace members api

app/client/src/ce/constants/messages.test.ts, app/client/src/ce/constants/messages.ts
- Removes EE string
- Adds tests.
Fixes #17116
=> chore: remove EE string and add tests | audit-logs | fe

app/client/src/widgets/TableWidget/widget/index.tsx, app/client/src/widgets/TableWidgetV2/index.ts
Removed the dynamic height logic from the table widget.
=> fix: remove dynamic height table widget

app/server/appsmith-plugins/mssqlPlugin/pom.xml, app/server/appsmith-plugins/postgresPlugin/pom.xml, app/server/appsmith-plugins/redshiftPlugin/pom.xml
- update HikariCP package version. This update will allow us to use new configuration knobs that HikariCP has added as well as the fixes that would have gone in making the new version of the package. 
Fixes #17803 
- Chore
- Not possible to write a separate automated test for this at the moment. As long as all the CI tests pass it should be sufficient.
=> fix: update HikariCP package version

app/client/src/actions/dynamicHeightActions.ts, app/client/src/reducers/entityReducers/dynamicHeightReducers/dynamicHeightLayoutTreeReducer.ts, app/client/src/sagas/CanvasSagas/DraggingCanvasSagas.ts, app/client/src/sagas/InitSagas.ts, app/client/src/sagas/PageSagas.tsx, app/client/src/sagas/ReplaySaga.ts, app/client/src/sagas/WidgetAdditionSagas.ts, app/client/src/sagas/WidgetDeletionSagas.ts, app/client/src/sagas/WidgetOperationSagas.tsx, app/client/src/sagas/WidgetOperationUtils.ts, app/client/src/sagas/dynamicHeightSagas.ts, app/client/src/selectors/editorSelectors.tsx, app/client/src/utils/WidgetFeatures.ts, app/client/src/utils/treeManipulationHelpers/dynamicHeightReflow.ts, app/client/src/widgets/BaseInputWidget/component/index.tsx, app/client/src/widgets/BaseWidget.tsx, app/client/src/widgets/CanvasWidget.tsx, app/client/src/widgets/withWidgetProps.tsx
=> fix: Auto-Height invisible widgets

app/rts/package.json, app/rts/src/controllers/Ast/AstController.ts, app/rts/src/server.ts, app/rts/yarn.lock
>Used morgan(a standard logger middleware function in nodejs) to log the response time or the time taken to server a particular request.
Fixes #17924
=> fix: Add performance metric for requests in RTS

app/client/src/widgets/StatboxWidget/index.ts
Enabled dynamic height for stat box widget
=> fix: enabled dynamic height for stat box widget

app/client/src/widgets/RichTextEditorWidget/component/index.tsx
Added a min height to rich text editor so that it does not collapse
=> fix: added a min height to rich text editor so that it does not collapse

app/client/src/utils/autoHeight/reflow.test.ts, app/client/src/utils/boxHelpers.test.ts
Added 2 tests for boxHelper/areIntersecting and 1 simple test for reflow/computeChangeInPositionBasedOnDelta.
=> feat: auto height reflow lib

.github/workflows/client-build.yml
Fixes: https://github.com/appsmithorg/appsmith/issues/17916
ref: https://theappsmith.slack.com/archives/C02MUD8DNUR/p1667191022856219
=> ci: Rearrange client build steps

app/client/src/components/editorComponents/EditorContextProvider.tsx, app/client/src/pages/AppViewer/index.tsx
This allows widgets to call certain auto height related actions necessary for the feature to work correctly.
Fixes #17959
- Manual
- The test for this PR is to make sure the application works correctly in all existing cypress tests.
~~- [NA] I have commented my code, particularly in hard-to-understand areas~~
~~- [NA] I have made corresponding changes to the documentation~~
~~- [NA] I have added tests that prove my fix is effective or that my feature works~~
=> feat: Add auto height actions to context

.github/pull_request_template.md
=> chore: add QA checklist for PR's

app/server/appsmith-server/src/main/java/com/appsmith/server/acl/PolicyGenerator.java, app/server/appsmith-server/src/main/java/com/appsmith/server/acl/ce/PolicyGeneratorCE.java
1. Minor refactor of PolicyGeneratorCE
2.  Added new lateral graph edges to connect indirect relatives directly
3. Added missing relationships between permissions
=> chore: Add missing relationships for RBAC

.github/workflows/client-build.yml
Fixes: https://github.com/appsmithorg/appsmith/issues/17916
=> ci: Fix a typo in client-build workflow

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ActionExecution/ClearStore_spec.ts, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ActionExecution/RemoveValue_spec.ts, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Others/Autocomplete_spec.js, app/client/src/ce/constants/messages.ts, app/client/src/components/editorComponents/ActionCreator/constants.ts, app/client/src/components/editorComponents/ActionCreator/index.tsx, app/client/src/entities/DataTree/actionTriggers.ts, app/client/src/sagas/ActionExecution/ActionExecutionSagas.ts, app/client/src/sagas/ActionExecution/StoreActionSaga.ts, app/client/src/utils/autocomplete/EntityDefinitions.ts, app/client/src/workers/Actions.test.ts, app/client/src/workers/Actions.ts
At the moment developer can add to store & update store
This Implementation is to allow developer
- Clear all store value
- Clear specifics value from store
Fixes https://github.com/appsmithorg/appsmith/issues/11639
=> feat: Clear store values

.github/ISSUE_TEMPLATE/--bug-report.yaml
added video log field to issue template
- chores; changes in the issue template
- Not required
=> chore: added video log field to issue template

app/client/src/reducers/entityReducers/autoHeightReducers/autoHeightLayoutTreeReducer.test.ts, app/client/src/reducers/entityReducers/autoHeightReducers/canvasLevelsReducer.test.ts
1. Added tests for canvasLevelReducers.
2. Added tests for autoLayoutHeightTreeReducer.
=> fix: auto height reducers tests

app/client/src/utils/WidgetFeatures.test.ts, app/client/src/utils/WidgetFeatures.ts
=> feat: widget features test

app/client/src/pages/Templates/Filters.tsx, app/client/src/pages/Templates/TemplateList.tsx, app/client/src/pages/Templates/index.tsx
This PR is for making the template list sidebar consistent with the application page sidebar. 
fixes https://github.com/appsmithorg/appsmith/issues/17880
**Current Template list page**
---
**Fixed Template list page**
=> chore: template list sidebar consistent with application page sidebar

app/client/src/reducers/entityReducers/dynamicHeightReducers/dynamicHeightLayoutTreeReducer.ts, app/client/src/sagas/CanvasSagas/DraggingCanvasSagas.ts, app/client/src/sagas/WidgetOperationSagas.tsx, app/client/src/utils/WidgetFeatures.ts, app/client/src/widgets/JSONFormWidget/widget/index.tsx
=> fix: Auto Height Fixes

app/client/src/components/autoHeight/AutoHeightContainer.test.tsx, app/client/src/widgets/RichTextEditorWidget/component/index.tsx
Removed the center alignment from rich text editor.
=> fix: rich text editor center alignment issue

app/client/src/components/editorComponents/ErrorTooltip.tsx, app/client/src/widgets/BaseWidget.tsx
Fixed the auto height not working issue.
=> fix: input widgets issue

app/client/src/widgets/BaseWidget.tsx
Fixed the preview and deploy mode.
=> fix: preview deploy mode

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/TableV2/TableV2_spec.js, app/client/src/widgets/TableWidgetV2/widget/index.tsx
Fixes #18184
- Manual
- Cypress
=> fix: Cyclic deps in Table widget shouldn't crash the app

app/client/src/sagas/dynamicHeightSagas.ts
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1mB6Q3qAGOwMz3xUblaPyqrU9qq9ZaY%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=7ZUXYHm)
>
> if no issue exists, please create an …
=> fix: fixing auto height in childless containers.

app/client/src/components/editorComponents/CodeEditor/index.tsx, app/client/src/reducers/lintingReducers/lintErrorsReducers.ts, app/client/src/selectors/dataTreeSelectors.ts, app/client/src/selectors/lintingSelectors.ts, app/client/src/workers/Linting/utils.ts
- Cherry Pick - `5acc08c`
Media
> Please also list any relevant details for your test …
=> fix: lint perf

app/client/src/reducers/entityReducers/autoHeightReducers/canvasLevelsReducer.test.ts
Fixed the canvasLevelsReducers test.
=> fix: canvasLevelsReducers test

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/MigrationHelperMethods.java
Cherry-pick https://github.com/appsmithorg/appsmith/pull/18222.
Signed-off-by: Shrikant Sharat Kandula <shrikant@appsmith.com>
=> fix: Fix NPE if email in admin emails doesn't have a user (#18222)

app/client/src/utils/WidgetFeatures.ts, app/client/src/utils/treeManipulationHelpers/dynamicHeightReflow.ts, app/client/src/widgets/BaseWidget.tsx
Removed auto height min max config from widget features.
=> fix: removed auto height min max config from widget features

app/client/src/sagas/dynamicHeightSagas.ts, app/client/src/utils/treeManipulationHelpers/dynamicHeightReflow.ts
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19YEXOj3eYk38lfEmRxMC24ZxjrwwueTMQ%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=tbpt57i)
>
> if no issue exists, please create an …
=> fix: Fixing Modal Height updates

app/client/src/widgets/DynamicHeightContainer.tsx, app/client/src/widgets/DynamicHeightContainerWrapper.tsx
Added background color of Text widget back to the auto height container scroller.
=> fix: text widget background auto height

app/client/src/components/autoHeight/AutoHeightContainer.tsx, app/client/src/utils/autoHeight/reflow.ts
Making getEffectedBoxes a Recursive function in autoHeight Reflow to improve performance
=> feat: Making getEffectedBoxes a Recursive function in autoHeight Reflow

app/client/src/utils/DSLMigration.test.ts, app/client/src/utils/DSLMigrations.ts, app/client/src/utils/migrations/MigrateLabelPosition.ts
Fixed migrate label position test failing issue.
=> fix: migrate label position test failing issue

app/client/src/components/autoHeight/AutoHeightContainer.tsx, app/client/src/components/autoHeight/AutoHeightContainerWrapper.tsx, app/client/src/widgets/WidgetUtils.ts
Fixed the auto height zero and limits issue.
=> fix: Auto height zero and limits issue

.github/workflows/test-build-docker-image.yml
fix upload success
Fixes # 
- Manual
=> ci: fix upload success

app/server/appsmith-server/src/main/resources/features/init-flags.yml
Add back feature flag for context switching
=> chore: add back feature flag for context switching

app/server/appsmith-server/src/main/resources/features/init-flags.yml
PR is to cherry pick commit cdcb6a00198750cac145419003590376c3da6af8.
This Cherry Pick contains code to add back context switching feature flag.
=> fix: add back feature flag for context switching (#18417)

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DynamicHeight/DynamicHeight_Multiple_Container_spec.js
Multiple container test need to wait for an action to complete updated test to handle the same.
=> test: fixed DH flaky test

.github/workflows/perf-test.yml
New perf test suite we have requires TED, this PR sets it up as a part of performance tests.
Fixes #18438
Non breaking change to CI
=> ci: Setup ted for perf tests

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/InstanceConfig.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PluginScheduledTaskCEImpl.java
Added some logs as well as moved from zipped results to sequential requests for CS and RTS
=> chore: Switched to sequential checks instead of a parallel one for RTS check

app/client/src/components/editorComponents/form/ToggleComponentToJson.tsx, app/client/src/components/formControls/utils.test.ts, app/client/src/components/formControls/utils.ts, app/client/src/pages/Editor/APIEditor/CommonEditorForm.tsx, app/client/src/reflow/reflowHelpers.ts, app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/InstanceConfig.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AnalyticsServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PluginScheduledTaskCEImpl.java
This is a PR to fix Reflow overlap issue that was introduced while accommodating dynamic height limits while reflowing.
add missed width and height limits instead of incrementing depth by 1
- Manual
=> fix: Overlapping of widgets while reflowing other widgets

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
Noticed the NPE error on git checkout remote branch flow on a user call.
=> chore: Fix analytics NPE for checkout remote branch flow

app/client/cypress/integration/Smoke_TestSuite_Fat/ClientSideTests/EmbedSettings/EmbedSettings_spec.js, app/client/cypress/support/AdminSettingsCommands.js
Increase timeout to wait for server restart
=> chore: fix flaky embed settings test

app/server/appsmith-server/src/test/java/com/appsmith/server/services/PageServiceTest.java
The DSL used in the test did not conform to our schema and was hence not triggering the execute on load logic for the original action itself.
Fixes #16724
- Manual
- JUnit
=> chore: Fixed a failing assertion in page clone test

.github/workflows/integration-tests-command.yml
Fix failed spec list in fat container
Code review
=> ci: fix-fat-failedspec

app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
HotFix for multiselect crashing
Handle undefined state of selectedOptionValues
Fixes #18578
- Manual
- Jest
- Cypress
=> fix: multiselect crashing

app/client/cypress/integration/Smoke_TestSuite_Fat/ClientSideTests/EmbedSettings/EmbedSettings_spec.js
Commenting out flaky embed settings assertion temporarily.
=> chore: comment out flaky assertion

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Workspace/MemberRoles_Spec.ts
> Updating spec for member roles
- Integration test update
- Cypress
=> fix: Updating spec for member roles

app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
Hotfix from this commit https://github.com/appsmithorg/appsmith/commit/058500704efa72c901ff3d519cfa0cfd2be2e3e0
=> fix: multiselect crashing (#18577)

app/client/src/widgets/TableWidgetV2/component/header/actions/ActionItem.tsx
=> fix: table widget header links should have pointer cursor when hovered

.github/workflows/pr-labeler.yml, .github/workflows/pr-test-file-check.yml
Test file check workflow was added with another workflow and was not working properly
- Extracted into its own workflow
- Added a label check to skip on non relevant PR
=> ci: Improve the test file check workflow

app/client/src/sagas/PostEvaluationSagas.ts, app/client/src/selectors/debuggerSelectors.tsx, app/client/src/widgets/BaseWidget.tsx, app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts, app/client/src/widgets/ListWidgetV2/widget/index.tsx, app/client/src/workers/Evaluation/evaluationUtils.ts
Filtered The data tree to remove meta Widgets(Non-Template) from the tern server and updated the debugger Selector to exclude meta Widgets(Non-Template)
Fixes #18382
- Manual
=> fix: remove meta widget from debugger and tern server

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AnalyticsServiceCEImpl.java
Action execution analytics events were not fired when the user is anonymous. This PR fixes that.
- Manual
=> fix: Corrected action execution analytics event

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
…responding object
>
This change is to synchronize permission to newly created git branched object from default branch object, for CE permission model this has no effect
Media
> A video or a GIF is preferred. when using …
=> chore: Synchronize Page,Action and ActionCollection object from original corresponding object

app/client/src/pages/Editor/AppSettingsPane/AppSettings/PageSettings.tsx
Updated import statement for reducer.
=> chore: update import to fix compilation issue

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/UserAndAccessManagementServiceCEImpl.java
Same thing as https://github.com/appsmithorg/appsmith/pull/18882, a couple of more cases.
=> chore: Fix more potential race condition in sending emails

.github/workflows/integration-tests-command.yml, .github/workflows/perf-test.yml, .github/workflows/test-build-docker-image.yml
This reverts commit bc8022caf218ef20b2cac2ad0e5a2213a2d3d8dc.
PR - #18873
=> ci: revert Add replicate set to the mongodb url for transaction PR

contributions/docs/GlobalFunctions.md
>
Added a title to GlobalFunctions.md so it matched the other .md files.
Fixes #17629
> Global Functions Doc Missing Heading
=> docs: Added a title to GlobalFunctions.md

.github/workflows/integration-tests-command.yml, .github/workflows/test-build-docker-image.yml
Adds 3 more github runners for fat container tests
=> ci: Add three more runners for the fat container tests

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/BugTests/Bug18876_Spec.ts, app/client/cypress/support/Pages/DataSources.ts, app/client/src/pages/Editor/APIEditor/ApiAuthentication.tsx, app/client/src/pages/Editor/DataSourceEditor/SaveOrDiscardDatasourceModal.tsx
PR fixes issues with reading userPermissions value from an undefined datasource object.
Fixes #18876 
- Cypress
=> fix: Error handling for undefined datasource in API Authentication

.github/workflows/perf-test.yml
Remove all the steps added to make perf tests work on EE
fixes: https://github.com/appsmithorg/appsmith/issues/18687
=> ci: Fix perf tests failure

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java
Fixes https://github.com/appsmithorg/appsmith/issues/18371
=> chore: use read permission to fetch pages in edit mode

app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationServiceImplV2.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImplV2.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceV2Tests.java
>
The purpose of this PR is to split import export service in V1 and V2, bug fixes will be done in V1 and new features will be added to V2, soon we will switch everything to V2, currently V2 is only used by git import/export service.
> if no issue exists, please create an issue and ask the maintainers about …
=> chore: Splitted import export service code for V2

app/client/src/constants/userConstants.ts
> Adding adminSettingsVisible variable in User type for supporting GAC
> TL;DR - This change is GAC related. Does not impact users.
> Tested it on GAC feature branch. Works as expected.
- Manual
=> chore: Adding adminSettingsVisible variable in User type

app/client/package.json, app/client/yarn.lock
> Updating the version of the design system dependency
Fixes [#18487](https://github.com/appsmithorg/appsmith/issues/18487)
- Version update
> Tested on GAC feature branch. Works as expected.
- Manual
=> chore: Updating the version of the design system dependency

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CurlImporterServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ItemServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutCollectionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/CreateDBTablePageSolutionCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ExamplesWorkspaceClonerCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceImplTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutActionServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/PageServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/ActionServiceCE_Test.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ApplicationForkingServiceTests.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ExamplesWorkspaceClonerTests.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceV2Tests.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ce/RefactoringSolutionCETest.java
Fixes https://github.com/appsmithorg/appsmith/issues/18928
=> fix: [GAC] editing js objects should use read permission for creating actions

app/client/cypress/fixtures/datasources.json, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Git/GitSync/GitSyncedApps_spec.js, app/client/cypress/locators/HomePage.js, app/client/cypress/support/commands.js, app/client/cypress/support/dataSourceCommands.js, app/client/cypress/support/index.js, app/client/cypress/support/widgetCommands.js
Adds common test methods that are to be used in RBAC and fix flaky test
=> test: add common test methods for RBAC

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewPageServiceCEImpl.java
Fixes https://github.com/appsmithorg/appsmith/issues/18979
=> chore: [GAC] Using correct permissions to fetch the application object using view mode

.github/workflows/CypressAddKnownfailedtests.yml, .github/workflows/integration-tests-command.yml, app/client/cypress/knownfailures, app/client/cypress/xataadd.sh, app/client/cypress/xatadel.sh
Comment failing tests to PR
Fixes # 
Code review. Tested in local fork
=> ci: Comment failing tests to PR

app/client/src/ce/constants/messages.ts, app/client/src/ce/pages/AdminSettings/LeftPane.tsx, app/client/src/ce/pages/workspace/Members.tsx, app/client/src/components/editorComponents/EditableText.tsx, app/client/src/pages/workspace/settings.tsx
> Addressing changes requested by the design team during design QA
Fixes #19040
> UI updates
> Checked UI locally to be working as per points mentioned in the issue.
- Manual
=> chore: Addressing changes requested by the design team during design QA

.github/workflows/integration-tests-command.yml
fix pr number in adding failed tests
Media
=> ci: fix PR number in adding failed tests

app/client/src/pages/setup/DataCollectionForm.tsx, app/client/src/pages/setup/SetupForm.tsx
Reverts appsmithorg/appsmith#19052
=> Revert "chore: remove telemetry option"

app/client/src/entities/DataTree/dataTreeJSAction.test.ts, app/client/src/entities/DataTree/dataTreeJSAction.ts, app/client/src/entities/DataTree/types.ts, app/client/src/workers/Evaluation/JSObject/index.ts, app/client/src/workers/Evaluation/JSObject/utils.ts, app/client/src/workers/Evaluation/__tests__/evaluation.test.ts, app/client/src/workers/common/DataTreeEvaluator/index.ts, app/client/src/workers/common/DataTreeEvaluator/mockData/ArrayAccessorTree.ts, app/client/src/workers/common/DataTreeEvaluator/mockData/NestedArrayAccessorTree.ts, app/client/src/workers/common/DataTreeEvaluator/mockData/mockUnEvalTree.ts, app/client/src/workers/common/DataTreeEvaluator/test.ts, app/shared/ast/index.ts, app/shared/ast/src/jsObject/index.ts
Reverts appsmithorg/appsmith#18357
We see some issues in performance with this PR, hence we are reverting it currently. 
Rishabh and I will create a task for this and then look further into this
=> revert: Parse js actions for view mode changes

app/client/src/entities/DataTree/dataTreeJSAction.test.ts, app/client/src/entities/DataTree/dataTreeJSAction.ts, app/client/src/entities/DataTree/types.ts, app/client/src/workers/Evaluation/JSObject/index.ts, app/client/src/workers/Evaluation/JSObject/utils.ts, app/client/src/workers/Evaluation/__tests__/evaluation.test.ts, app/client/src/workers/common/DataTreeEvaluator/index.ts, app/client/src/workers/common/DataTreeEvaluator/mockData/ArrayAccessorTree.ts, app/client/src/workers/common/DataTreeEvaluator/mockData/NestedArrayAccessorTree.ts, app/client/src/workers/common/DataTreeEvaluator/mockData/mockUnEvalTree.ts, app/client/src/workers/common/DataTreeEvaluator/test.ts, app/shared/ast/index.ts, app/shared/ast/src/jsObject/index.ts
Cherry-pick #19033 to master
Fixes #19089
=> chore: Cherry-pick #19033 to master

.github/workflows/integration-tests-command.yml, .github/workflows/test-build-docker-image.yml
Ci fix run result due to deprecated 
Media
code reivew
=> ci: Ci fix run result due to deprecated 

app/client/src/ce/constants/messages.ts, app/client/src/ce/pages/workspace/Members.tsx, app/client/src/ce/pages/workspace/WorkspaceInviteUsersForm.tsx, app/client/src/pages/AppViewer/AppViewerHeader.tsx, app/client/src/pages/AppViewer/PageMenu.tsx, app/client/src/pages/Applications/index.tsx, app/client/src/pages/Editor/EditorHeader.tsx, app/client/src/pages/workspace/settings.tsx
> Splitting messages to support cloud messages
Fixes [#19097](https://github.com/appsmithorg/appsmith/issues/19097)
- Code splitting
> Checked locally
- Manual
- Jest
- Cypress
=> chore: Splitting messages to support cloud messages

.github/workflows/integration-tests-command.yml, .github/workflows/perf-test.yml, .github/workflows/test-build-docker-image.yml
This PR adds the perf tests back, but still not a blocking check.
=> ci: Add perf tests back

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Workspace/MemberRoles_Spec.ts, app/client/package.json, app/client/yarn.lock
> Updating DS version and adding a test for search on the members page. Updating the DS version to fix the issue on GAC where two tabs show active in a scenario where current tab changes are not saved by the user and he tries to switch the tab.
Fixes [#19088](https://github.com/appsmithorg/appsmith/issues/19088)
- Adding new test & updating DS version
> Ran the new test locally and it passed. DS change has been tested with the alpha version on EE.
- Manual
- Cypress
=> chore: Updating DS version and adding test for search on members page

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ActionCollectionServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceImplTest.java
Fixes https://github.com/appsmithorg/appsmith/issues/19129
=> fix: Adding user permissions in the response of move JS object between pages

app/client/src/ce/pages/workspace/WorkspaceInviteUsersForm.tsx
> Updating invite user event
Fixes [#16152](https://github.com/appsmithorg/appsmith/issues/16152)
- Updating analytics
> Tested local browser consoles.
- Manual
=> chore: Updating invite user event

.github/workflows/helm-release.yml
fixes: [18864](https://github.com/appsmithorg/appsmith/issues/18864)
=> ci: Fix failing helm publish pipeline

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/PolicyUtils.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java
Test cases added at : https://github.com/appsmithorg/appsmith-ee/pull/912
Fixes https://github.com/appsmithorg/appsmith/issues/19077
=> fix: Give datasource execute for public application without permission

app/client/cypress/fixtures/Listv2/emptyList.json, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_BasicChildWidgetInteraction_spec.js, app/client/src/entities/DataTree/dataTreeFactory.ts, app/client/src/sagas/ModalSagas.ts, app/client/src/sagas/WidgetOperationUtils.ts, app/client/src/sagas/WidgetSelectionSagas.ts, app/client/src/sagas/autoHeightSagas/helpers.ts, app/client/src/sagas/selectors.tsx, app/client/src/widgets/BaseWidget.tsx, app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.test.ts, app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts, app/client/src/widgets/ListWidgetV2/widget/index.tsx, app/client/src/widgets/MetaHOC.tsx, app/client/src/widgets/TableWidget/component/TableFilterPane.tsx, app/client/src/widgets/TableWidgetV2/component/header/actions/filter/FilterPane.tsx
1. Makes the first item of each page configurable
2. Retains changes in the first item when data changes
3. Regenerates appropriate no of items when data changes.
Issue 2
1. Drop an input widget
2. Type something in the input widget of first item
3. Go to page 2
4. Type something different in the input widget of the first item
5. Go to page 1 and observe the input value from Step 2 is retained
6. Go to page 2 and observe the input value from Step 4 is retained
Issue 3
For this first check in the base widget the behavior and then check here for comparison
1. Drop a List v2 widget
2. Make the widget taller
3. Drop the following data
```
[  { "id": 1, "name": "Blue" },
{ "id": 2, "name": "Pink" },
{ "id": 3, "name": "Black" }]
```
4. Then update the data to
```
[{ "id": 0, "name": "Green" }, …
```
=> fix: configurable item in edit mode

app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewPageServiceCEImpl.java
Performance improvement on the /pages GET call
=> fix: Added projection for PageDTO during pages call

app/client/src/ce/constants/messages.ts, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/PageControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewPageServiceCEImpl.java
This reverts commit 23652a185baa288e23ffb76bb29d436398a96f03.
=> Revert "chore: Back merge v1.8.15 (#19288)"

app/client/src/ce/constants/messages.ts, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/PageControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewPageServiceCEImpl.java
Should only contain what is already on master
=> chore: Back merge v.1.8.15

app/server/appsmith-server/src/main/resources/features/init-flags.yml
Add features flag for Multi Pane Layouts for only a specific email ids
=> chore: Add Multi Pane Layout feature flag for specific emails

app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewPageServiceCEImpl.java
Simply a refactor in code to reuse generic repository layer that didn't used to exist when this hot fix was made.
Fixes #19351 
- Chore
- Manual
- Existing unit tests
=> chore: Moved usage of projection query from custom to generic

app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts, app/client/src/sagas/PostEvaluationSagas.ts, app/client/src/workers/Evaluation/JSObject/index.ts, app/client/src/workers/Evaluation/JSObject/utils.ts
This is a hotfix change for the issue created due to a data tree split where JSObject has `name` as a variable and a function is modified to change behavior from sync to async or vice versa.
Fixes https://github.com/appsmithorg/appsmith/issues/19310
- Manual
- Cypress
=> fix: jsObject updates

.github/workflows/label-checker.yml
Ensure Test Plan Approval for all Engineering pods
=> ci: Ensure Test Plan Approval for all Engineering pods

app/server/appsmith-server/src/main/java/com/appsmith/server/constants/Url.java
> Update the health check url from `/api/health` to `/api/v1/health`
Fixes https://github.com/appsmithorg/appsmith/issues/19424
Media
> URL end point has been changed.
=> fix: update health check url

app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts, app/client/src/widgets/ListWidgetV2/widget/index.tsx
=> fix: use metagenerator to cache data

app/client/cypress/fixtures/Listv2/Listv2JSObjects.json, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/ListV2/ListV2_SerververSide_spec.js, app/client/src/selectors/debuggerSelectors.tsx, app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts, app/client/src/widgets/ListWidgetV2/widget/helper.ts, app/client/src/widgets/ListWidgetV2/widget/index.tsx
1. Fixed SelectedItemView and TriggeredItemView
2. Further improved metaWidget Error Suppression
Thought Process for the solution https://miro.com/app/board/uXjVP1rCNHM=/
Fixes #18730
- Cypress
=> fix: serverside selected and triggered row issues

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
Please ref: 
https://theappsmith.slack.com/archives/C0341RERY4R/p1672923468366099
=> fix: Remove empty unset op during encryption migration

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
Should be what already exists in master at v1.9.1
=> ci: Back merge v1.9.1

app/client/src/components/editorComponents/CodeEditor/markHelpers.ts
Added default value while updating markers for child nodes
Media
- Manual
- 
=> fix: Added default value to prevent code editor crash

.github/workflows/integration-tests-command.yml, .github/workflows/test-build-docker-image.yml
> Added host gateway to fix cloud services connectivity issue
Media
> Delete anything …
=> ci: Add host gateway to connect cloud services

app/server/appsmith-server/src/main/resources/features/init-flags.yml
Changed the billing and usage feature flag email to usage@appsmith.com
Fixes https://github.com/appsmithorg/cloud-services/issues/205
- Manual
- Jest
- Cypress
=> chore: change billing and usage feature flag email

app/client/src/widgets/TableWidget/component/TableAction.tsx
>
This fixes a UX issue in the table v1 widget. Under the filters and download button the border appear to be missing, this commit fixes it.
Fixes #18322 
- Manual
=> fix: This fixes the border issue for the table v1 widget (#18322)

.github/pull_request_template.md
(None of these options are relevant in this scenario, hence the PR)
- Jest
- Cypress
=> chore: add chore as a type of change

app/client/cypress/fixtures/Listv2/ListWithInputForSelectedAndTriggerRow.json, app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_onRowClick_spec.js, app/client/src/ce/utils/autocomplete/EntityDefinitions.ts, app/client/src/widgets/ListWidgetV2/widget/derived.js, app/client/src/widgets/ListWidgetV2/widget/derived.test.js, app/client/src/widgets/ListWidgetV2/widget/index.tsx, app/client/src/widgets/ListWidgetV2/widget/propertyConfig.ts
Add triggereitem to List v2
Rename onRowClick to onItemClick on List v2
Fixes #19739
- Cypress
=> fix: API change

.github/workflows/integration-tests-command.yml
Hides the list of failed tests behind a spoiler to avoid making PR pages very long
Fixes # N/A
=> ci: Add spoiler to list failed ui tests

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/RTE/RichTextEditor_spec.js, app/client/src/widgets/RichTextEditorWidget/component/index.tsx
Added support for emoji picker in RTE(#19450), Emoji can be added through the toolbar and editor as well.
Fixes #19450 
- Manual
Checked if able to add emoticons through toolbar.
Checked if emoticon dropdown shows up when there is description text matching emoticons.
- Cypress
Test Plan:
https://github.com/appsmithorg/TestSmith/issues/2159
=> feat: emoji picker (#19450)

.github/workflows/test-build-docker-image.yml
Add serve module back, it was removed in earlier pr.
=> chore: Add serve module back

README.md
Reverts appsmithorg/appsmith#19800
=> Revert "ci: Update README.md"

app/server/reactive-caching/src/main/resources/META-INF/spring.factories, app/server/reactive-caching/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, app/server/reactive-caching/src/test/java/com/appsmith/testcaching/CacheApplication.java, app/server/reactive-caching/src/test/java/com/appsmith/testcaching/configuration/RedisTestContainerConfig.java, app/server/reactive-caching/src/test/java/com/appsmith/testcaching/model/ArgumentModel.java, app/server/reactive-caching/src/test/java/com/appsmith/testcaching/model/NestedModel.java, app/server/reactive-caching/src/test/java/com/appsmith/testcaching/model/ParentModel.java, app/server/reactive-caching/src/test/java/com/appsmith/testcaching/model/TestModel.java, app/server/reactive-caching/src/test/java/com/appsmith/testcaching/service/CacheTestService.java, app/server/reactive-caching/src/test/java/com/appsmith/testcaching/test/TestCachingMethods.java
>
Spring Boot 2.7 introduced a new META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports file for registering auto-configurations, while maintaining backwards compatibility with registration in spring.factories. With this release, support for registering auto-configurations in spring.factories has been removed in favor of the imports file.
> Add a TL;DR when …
=> fix for caching library autoconfiguration

app/client/src/widgets/ListWidget/component/ListPagination.tsx
It is ARIA, and the attribute is `aria-label`; code had `area-label`. This PR fixes that typo.
- Manual
=> chore: fix typo from area to aria

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/InstanceConfig.java, app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CacheableRepositoryHelperCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CacheableRepositoryHelperCEImpl.java, app/server/reactive-caching/src/main/resources/META-INF/spring.factories, app/server/reactive-caching/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, app/server/reactive-caching/src/test/java/com/appsmith/testcaching/CacheApplication.java, app/server/reactive-caching/src/test/java/com/appsmith/testcaching/configuration/RedisTestContainerConfig.java, app/server/reactive-caching/src/test/java/com/appsmith/testcaching/model/ArgumentModel.java, app/server/reactive-caching/src/test/java/com/appsmith/testcaching/model/NestedModel.java, app/server/reactive-caching/src/test/java/com/appsmith/testcaching/model/ParentModel.java, app/server/reactive-caching/src/test/java/com/appsmith/testcaching/model/TestModel.java, app/server/reactive-caching/src/test/java/com/appsmith/testcaching/service/CacheTestService.java, app/server/reactive-caching/src/test/java/com/appsmith/testcaching/test/TestCachingMethods.java
Hot fix for perf issues on /me endpoint
=> fix: Load anon permission groups on server start up and caching component fixes

app/server/appsmith-plugins/snowflakePlugin/pom.xml, app/server/appsmith-plugins/snowflakePlugin/src/main/java/com/external/plugins/SnowflakePlugin.java
- Use `JSON` format instead of `Arrow` format: Snowflake JDBC connector uses `Apache Arrow` library internally to read data in `Arrow` format as opposed to the `JSON` format. `Apache Arrow` library in turn has a conflict with JDK16+ which causes the Snowflake connector to fail. This PR fixes this issue by forcing the Snowflake connector to use `JSON` format instead of `Arrow` format. 
- Ref: https://community.snowflake.com/s/article/SAP-BW-Java-lang-NoClassDefFoundError-for-Apache-arrow
- Update JDBC connector package version.
- Remove redundant dependency inclusion lines from POM file. The removed dependencies are already included as part of the `appsmith-server` module. 
Fixes #19784 
- Manual 
- No automated TC could be added because …
=> fix: fix Snowflake JDBC driver connectivity issue

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/InstanceConfig.java, app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java
=> fix: Modified upgrade path error for v1.9.2

app/server/appsmith-plugins/snowflakePlugin/pom.xml, app/server/appsmith-plugins/snowflakePlugin/src/main/java/com/external/plugins/SnowflakePlugin.java
- add hotfix for Snowflake JDBC connector issue #19784
=> fix: Add hotfix for Snowflake plugin driver

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCEImpl.java
- TL;DR formatting changes and added a protected 
- Chore 
- Manual
=> chore:  formatting and access modifier changes

README.md
Added This project is tested with BrowserStack
- Manual
=> docs: Adding Browserstack endorsement on our README

app/server/appsmith-git/src/main/java/com/appsmith/git/configurations/GitServiceConfig.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Application.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceV2Tests.java
- Remove published JS libraries from becoming part of the exported application when exporting for Git. 
- This was causing a problem with git status because git status would consider the published libraries as well when fetching git diff however, when creating commit only unpublished libraries are used. 
- I am not sure why, but it seems to fix the git merge issue as well - not sure at the moment. Waiting for a verification from QA on this. (Update: QA has verified this as well)
Fixes #19764 #19766 
- Manual
- JUnit TC
=> fix: fix git related issues in Custom JS Library feature

app/shared/ast/.eslintrc.json, app/shared/ast/.prettierrc
To maintain consistency in output and prevention of unnecessary code edits, this PR adds eslint and prettier config  to the shared module.
Media
> Please describe the tests that you ran to …
=> chore: Add eslint and prettier config to shared module

app/server/appsmith-server/src/main/java/com/appsmith/server/models/export/ActionConfigurationMetadata.java, app/server/appsmith-server/src/main/java/com/appsmith/server/models/export/ActionMetadata.java, app/server/appsmith-server/src/main/java/com/appsmith/server/models/export/ApplicationMetadata.java, app/server/appsmith-server/src/main/java/com/appsmith/server/models/export/ApplicationResource.java, app/server/appsmith-server/src/main/java/com/appsmith/server/models/export/DatasourceMetadata.java, app/server/appsmith-server/src/main/java/com/appsmith/server/models/export/JSObjectMetadata.java, app/server/appsmith-server/src/main/java/com/appsmith/server/models/export/LayoutMetadata.java, app/server/appsmith-server/src/main/java/com/appsmith/server/models/export/PageMetadata.java, app/server/appsmith-server/src/main/java/com/appsmith/server/models/export/ThemeMetadata.java
Added models for export, this will be used in Import/Export V2 service.
=> feat: added models for export

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/Input/Input_Multiline_spec.js
Add cypress tests for multiline and singleline data-type in input widget
Media
> …
=> test: add cypress test for multiline and singleline datatype for input widget

.github/workflows/integration-tests-command.yml
Makes perf tests a blocking check.
=> ci: Make perf tests a blocking check

app/client/src/pages/common/ErrorPages/Page.tsx
Code split changes for License issue landing page from non admin user
related https://github.com/appsmithorg/cloud-services/issues/209
- Manual
- Jest
- Cypress
=> chore: [code split] License issue landing page for non admin user

.github/workflows/upgrade-appsmith-tests.yml
- This PR removes the Upgrade workflow from being triggered in oktotest
- Yml Script fix (non-breaking change which fixes an issue)
=> test: Fix upgrade workflow run

.github/workflows/test-build-docker-image.yml
Fix a type created due to inconsistent names.
=> ci: Update test-build-docker-image.yml

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_TriggerRow_SelectedRow.js, app/client/src/ce/constants/messages.ts, app/client/src/ce/utils/autocomplete/EntityDefinitions.ts, app/client/src/sagas/WidgetOperationSagas.tsx, app/client/src/widgets/BaseWidget.tsx, app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts, app/client/src/widgets/ListWidgetV2/widget/index.tsx, app/client/src/widgets/ListWidgetV2/widget/propertyConfig.test.ts, app/client/src/widgets/ListWidgetV2/widget/propertyConfig.ts
1. Issue with SSP when Primary key is not selected(My datasource here was a google sheet) https://www.loom.com/share/d4f7f799ec0c473f88015110b441fc9a
2. Listv2 and the canvas crashes when we refresh the data from the QUERIES/JS  section and then come back to the widget and do item selection on pagination https://www.loom.com/share/fed18e8f9aed4300a3ffa1d0a7b18502
3. Canvas crashes when we click on List item after resetting the List widget(List widget should NOT be on page 1 during resetting) https://www.loom.com/share/511d3ec8988742878867507bc7fd61a8
4. We are not showing any of the Child widgets (widgets inside a nested List) view properties on calling triggrerdViewItems
5. remove the paste operation when copied from Listv2 container item …
=> fix: QA callouts on List V2

.github/workflows/test-build-docker-image.yml
Fix typo in test-build workflow.
=> ci: Fix typo in test build workflow

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_BasicServerSideData_spec.js, app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.ts
Fixes any poor UX due performance degradation when server side pagination is not used properly.
Fixes #19940
Fixes issues in tracker [15](https://docs.google.com/spreadsheets/d/1kWosVCH622m9hohVKyFRdrr7TUa_exO8thwjo8Aqe2M/edit#gid=0&range=15:15) and [32](https://docs.google.com/spreadsheets/d/1kWosVCH622m9hohVKyFRdrr7TUa_exO8thwjo8Aqe2M/edit#gid=0&range=32:32)
Media
- Manual
- Cypress
=> feat: generate only visible items in server side rendered data

.github/workflows/test-build-docker-image.yml
changed ubunut latest for ci
codereview
=> ci: changed ubunut latest for ci

app/client/src/widgets/CheckboxGroupWidget/component/index.tsx
Removes un-used import to fix build failures in CI
Media
> Please also list any …
=> chore: removed unused import

app/client/src/workers/common/DataTreeEvaluator/index.ts
=> feat: Add a function to evaluate when differences is passed as an input

.github/workflows/on-demand-build-docker-image-deploy-preview.yml, scripts/deploy_preview.sh
Make upgrades easy for deploy previews.
=> ci: make upgrades easy to deploy-previews

app/client/src/ce/pages/AdminSettings/config/authentication/AuthPage.tsx, app/client/src/utils/hooks/useOnUpgrade.ts
> Refactoring the code of the Upgrade flow for OIDC and SAML to fix the issue of intercom popup not opening on click of upgrade button.
Fixes [#20241](https://github.com/appsmithorg/appsmith/issues/20241)
> Tested the function call locally and it is now getting triggered.
- Manual
=> fix: Refactoring the code of the Upgrade flow for OIDC and SAML

app/rts/src/test/server.test.ts, app/shared/ast/src/index.ts
Handle IIFE (Immediately Invoked Function Expression) refactor in RTS sever
=> fix: Handle iife in rts sever

app/client/cypress/integration/Regression_TestSuite/ServerSideTests/OnLoadTests/JSOnLoad_cyclic_dependency_errors_spec.js, app/rts/src/test/server.test.ts, app/shared/ast/src/index.ts
This PR fixes the false cyclic dependency error Cypress tests and the basic Lint error Cypress tests.
Media
> Please …
=> fix: Unblocking CI - Unexpected cyclic dependency error and Lint spec fixes

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PingScheduledTaskCEImpl.java
Updates the analytics tracking of instance stats to use the instance Id instead of IP address
- Manual
=> chore: Changed Id of analytics to instance id from ip

app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/ResponseDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PluginScheduledTaskCEImpl.java
=> fix: NPE on server startup

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/constants/CommonFieldName.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/dtos/ExecuteActionDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/constants/Constraint.java, app/server/appsmith-server/src/main/java/com/appsmith/server/constants/ce/FieldNameCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCEImpl.java
This property will give us an insight into what range of parameter sizes users are working with.
Fixes #20128 
- Locally via Segment
=> chore: Added total parameter size in execution DTO to analytics

app/client/src/usagePulse/index.ts
- Decrease the usage pulse trigger interval to 5 minutes.
- In another PR we will add changes to make this value driven by backend
Media
> Please also list any relevant details for …
=> chore: decrease usage pulse trigger interval to 5 minutes

app/server/appsmith-server/src/main/resources/application.properties
Removed api path from `APPSMITH_TRACING_ENDPOINT`
=> fix: minor update on  APPSMITH_TRACING_ENDPOINT

app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationSuccessHandlerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/CustomServerOAuth2AuthorizationRequestResolverCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/constants/Security.java
=> fix: Cherry pick fixes for Cognito OIDC

.github/workflows/ci-test.yml, .github/workflows/fat-migration.yml, .github/workflows/perf-test.yml
- This PR maps port 22 to 2222 (revert)
=> test: TED support for GITEA

.github/workflows/ci-test.yml
- This PR reverts #20471 
- ci-test yml file update
=> test: TED support for GITEA (stop ssh revert)

app/client/cypress/fixtures/modalWidgetBGcolorDSL.json, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/Modal_background_spec.ts, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/Others/Canvas_scrolling_spec.js, app/client/cypress/support/Objects/CommonLocators.ts, app/client/src/components/propertyControls/ColorPickerComponentV2.tsx, app/client/src/pages/AppViewer/BrandingBadgeMobile.tsx, app/client/src/pages/AppViewer/index.tsx, app/client/src/utils/WidgetSizeUtils.test.ts, app/client/src/utils/WidgetSizeUtils.ts, app/client/src/utils/hooks/useClickToSelectWidget.tsx, app/client/src/widgets/ModalWidget/component/index.tsx, app/client/src/widgets/ModalWidget/widget/index.tsx
The following issues were caused because of the recent changes with respect to auto height instant update.
In the recent change, we removed a few wrappers around containers which seemed unnecessary. This led to the fact that in deploy mode, these wrappers were not present. The issue with this was that, these wrappers were responsible for the modal widget's background color styling. This also led to an issue where the background color was not applied in edit mode.
To fix this, we've added a wrapper in the component and removed all styling logic from the widget. This is because, the component is responsible for the actual rendering and what users see. The widgets should act as an interface, and as a result, should not deal with styling.
Fixes #20434 
Fixes #20405 
Fixes #20436 
- Bug fix …
=> fix: Modal widget background issues

app/client/src/utils/AnalyticsUtil.tsx
> Fixes https://github.com/appsmithorg/appsmith/issues/18829
> From Analytics 2.0 onwards, batching to deliver of multiple events with fewer API calls for faster performance
[https://segment.com/blog/analytics-js-2/](https://segment.com/blog/analytics-js-2/)
[https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#batching](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#batching)
> Add batching strategy to segment analytics while loading the script inside AnalyticsUtil
> [https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#batching](https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/#batching)
Why are we doing this, i.e, exact issue with the performance?
- Whenever …
=> fix: Add batching strategy to segment analytics tracking so that events are sent to segment in batches instead of individual

app/client/cypress/integration/Regression_TestSuite/ClientSideTests/IDE/Command_Click_Navigation_spec.js, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/OtherUIFeatures/ForkApplication_spec.js, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/TableV2/Add_new_row_spec.js, app/client/cypress/support/widgetCommands.js
- Added clean up for command_click_naviagtion_spec
- Add_new_row_spec.js
- ForkApplication_spec.js
=> test: Fix flaky tests

app/client/cypress/integration/Regression_TestSuite/UpgradeAppsmith/UpgradeAppsimth_spec.js, app/client/cypress/support/commands.js
- Skipping validations in UpgradeAppsmith_spec.js
- Cypress
- Cypress
=> test: skipping test in upgrade appsmith spec

app/client/src/sagas/EvalWorkerActionSagas.ts, app/client/src/sagas/EvaluationsSaga.ts, app/client/src/workers/Evaluation/JSObject/Collection.ts, app/client/src/workers/Evaluation/JSObject/JSFunctionProxy.ts, app/client/src/workers/Evaluation/JSObject/JSVariableProxy.ts, app/client/src/workers/Evaluation/JSObject/JSVariableUpdates.ts, app/client/src/workers/Evaluation/JSObject/__test__/mutation.test.ts, app/client/src/workers/Evaluation/JSObject/checkUpdate.ts, app/client/src/workers/Evaluation/JSObject/index.ts, app/client/src/workers/Evaluation/JSObject/sendUpdatedDataTree.ts, app/client/src/workers/Evaluation/JSObject/utils.ts, app/client/src/workers/Evaluation/evaluate.ts, app/client/src/workers/Evaluation/evaluation.worker.ts, app/client/src/workers/common/DataTreeEvaluator/index.ts
=> chore: trigger-jsVarUpdate-eval

app/client/src/utils/DynamicBindingUtils.ts, app/client/src/workers/Evaluation/JSObject/JSVariableProxy.ts, app/client/src/workers/Evaluation/evaluation.worker.ts, app/client/src/workers/Evaluation/functionDeterminer.ts, app/client/src/workers/common/DataTreeEvaluator/index.ts
Fixes https://github.com/appsmithorg/appsmith/issues/20309
- Manual
- Jest
- Cypress
=> fix: proxy clone error

app/client/src/ce/entities/DataTree/actionTriggers.ts, app/client/src/ce/workers/Evaluation/Actions.ts, app/client/src/ce/workers/Evaluation/PlatformFunctions.ts, app/client/src/ee/entities/DataTree/actionTriggers.ts, app/client/src/ee/workers/Evaluation/PlatformFunctions.ts, app/client/src/sagas/ActionExecution/NavigateActionSaga.ts
https://github.com/appsmithorg/appsmith/pull/20168 deleted certain files as part of a larger refactor that is now causing [sync](https://github.com/appsmithorg/appsmith-ee/actions/runs/4152653640/jobs/7183759288) job on ee repo to fail with merge conflict. This PR temporarily adds those files back. 
Fixes #
Media
- Chore …
=> chore: Add missing imports errors for ee repo sync

app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/NavigateTo_spec.ts, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Binding/Promises_Spec.ts, app/client/src/ce/workers/Evaluation/Actions.ts
Changes imports - workers/Evaluation/fns to @appsmith/workers/Evaluation/fns
- Manual
=> chore: fix imports to resolve EE conflicts

app/client/src/ce/workers/Evaluation/Actions.ts, app/client/src/workers/Evaluation/JSObject/Collection.ts, app/client/src/workers/Evaluation/JSObject/JSVariableUpdates.ts, app/client/src/workers/Evaluation/JSObject/index.ts, app/client/src/workers/Evaluation/evaluation.worker.ts
Only create a proxy of JSObject for async evaluation to avoid tracking updates for sync evaluation.
- Manual
- Jest
- Cypress
=> fix: avoid-updateTracking-syncEval

.github/workflows/ci-test.yml, .github/workflows/client-build.yml, .github/workflows/on-demand-build-docker-image-deploy-preview.yml, .github/workflows/perf-test.yml, .github/workflows/server-build.yml, .github/workflows/test-build-docker-image.yml, .github/workflows/upgrade-appsmith-tests.yml
=> ci: fix artifact names across the ci

app/client/src/ce/pages/Upgrade/businessEdition/UpgradeToBEPage.tsx
- Scale image accordingly when you zoom in or zoom out, and when you resize the browser.
Fixes [#336](https://github.com/appsmithorg/cloud-services/issues/336)
Media
https://www.loom.com/share/57f96e7ebec944b98ffac299011eec2f
- Manual
=> fix: scale down image on resizing of container

app/client/src/ce/pages/AdminSettings/LeftPane.tsx, app/client/src/ce/utils/signupHelpers.ts, app/client/src/constants/ThirdPartyConstants.tsx, app/client/src/pages/setup/SignupSuccess.tsx, app/client/src/utils/hooks/useOnUpgrade.ts
- Removes feature flags for usage & billing.
- moves pricing url to constant.
=> chore: remove feature flags

.github/workflows/ci-test.yml
Disable telemetry in ci-test 
Code review
=> ci: Disable telemetry in ci-test 

app/client/src/workers/Evaluation/JSObject/JSVariableUpdates.ts, app/client/src/workers/Evaluation/JSObject/__test__/mutation.test.ts, app/client/src/workers/Evaluation/JSObject/checkUpdate.ts, app/client/src/workers/Evaluation/JSObject/index.ts, app/client/src/workers/Evaluation/JSObject/sendUpdatedDataTree.ts, app/client/src/workers/Evaluation/JSObject/utils.ts, app/client/src/workers/Evaluation/evaluation.worker.ts, app/client/src/workers/common/DataTreeEvaluator/index.ts
=> fix: map-set-mutation

app/client/cypress/integration/Regression_TestSuite/UpgradeAppsmith/UpgradeAppsimth_spec.js
- Updated condition to run the test only on CE
- Cypress
- Cypress
=> test: fix for UpgradeAppsmith test

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/constants/AnalyticsEvents.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AnalyticsServiceCEImpl.java
Added extra events for license-related analytics events. Also did some functional breakdown of code
- Manual
=> chore: Added extra analytics events for license

app/client/src/workers/Evaluation/fns/utils/TriggerEmitter.ts
Changes required for this PR https://github.com/appsmithorg/appsmith-ee/pull/1083/
=> chore: export batching method for ee PR 

app/client/cypress/integration/Regression_TestSuite/Application/PromisesApp_spec.js, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ThemingTests/Basic_spec.js, app/client/cypress/integration/Regression_TestSuite/ServerSideTests/GenerateCRUD/Postgres2_Spec.ts, app/client/cypress/support/Pages/AggregateHelper.ts, app/client/src/components/designSystems/appsmith/autoLayout/AutoLayoutLayer.tsx
=> change wrapper width

app/server/appsmith-server/src/main/java/com/appsmith/server/featureflags/FeatureFlagEnum.java, app/server/appsmith-server/src/main/resources/features/init-flags.yml
Removed usage and billing feature flag
- Manual
=> chore: Remove feature flag billing and usage

app.json
After Heroku removes the free tier for their service, app.json is now outdated. 
Fixes #19538
- Manual , Heroku install
=> fix: Update app.json, Heroku deployment is broken

app/client/src/ce/workers/Evaluation/Actions.ts, app/client/src/sagas/EvaluationsSaga.ts, app/client/src/workers/Evaluation/JSObject/JSVariableProxy.ts, app/client/src/workers/Evaluation/fns/utils/TriggerEmitter.ts
Fixes #
Media
- Manual
- Jest
- Cypress
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped …
=> fix: mutation-issues

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImplV2.java
> Add missing log statement for the content type error scenario.
=> chore: Add missing log statements

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java
Refactoring to make the `updateTenantLogoInParams` function testable in EE code.
=> chore: Refactor tenant email param

app/client/src/widgets/CheckboxGroupWidget/index.ts, app/client/src/widgets/RadioGroupWidget/index.ts, app/client/src/widgets/SwitchGroupWidget/index.ts
- Added auto layout configuration for `checkbox, switch & radio` group widgets.
Fixes #20598 
Media
- Manual
> Link issues raised during …
=> feat: responsive config for group widgets

app/client/src/workers/Evaluation/JSObject/Collection.ts, app/client/src/workers/Evaluation/JSObject/JSVariableProxy.ts, app/client/src/workers/Evaluation/JSObject/JSVariableUpdates.ts, app/client/src/workers/Evaluation/JSObject/__test__/mutation.test.ts, app/client/src/workers/Evaluation/JSObject/checkUpdate.ts, app/client/src/workers/Evaluation/JSObject/index.ts, app/client/src/workers/Evaluation/JSObject/sendUpdatedDataTree.ts, app/client/src/workers/Evaluation/__tests__/Actions.test.ts, app/client/src/workers/Evaluation/__tests__/timeout.test.ts, app/client/src/workers/Evaluation/evaluate.ts, app/client/src/workers/Evaluation/fns/__tests__/LocalStorage.test.ts, app/client/src/workers/Evaluation/fns/__tests__/interval.test.ts, app/client/src/workers/Evaluation/fns/__tests__/run.test.ts, app/client/src/workers/Evaluation/fns/mock.ts, app/client/src/workers/Evaluation/fns/overrides/interval.ts, app/client/src/workers/Evaluation/fns/overrides/timeout.ts, app/client/src/workers/Evaluation/fns/utils/Messenger.ts, app/client/src/workers/Evaluation/fns/utils/Promisify.ts, app/client/src/workers/Evaluation/fns/utils/__tests__/Promisify.test.ts, app/client/src/workers/Evaluation/functionDeterminer.ts, app/client/src/workers/Evaluation/handlers/evalExpression.ts, app/client/src/workers/Evaluation/handlers/evalTrigger.ts, app/client/src/workers/Evaluation/handlers/executeSyncJS.ts, app/client/src/workers/Evaluation/validations.ts, app/client/src/workers/Linting/utils.ts, app/client/src/workers/common/DataTreeEvaluator/index.ts
=> chore: refactor js object mutation

.github/workflows/ci-test.yml
=> ci: updated the PAT to access the appsmithorg/ci-oldstack

app/client/cypress/integration/Regression_TestSuite/UpgradeAppsmith/UpgradeAppsimth_spec.js
- Un skipping the UpgardeAppsmith_spec.js
- Cypress
- Cypress
=> test: Un skipping the UpgardeAppsmith_spec.js

app/client/src/workers/Evaluation/JSObject/index.ts, app/client/src/workers/Evaluation/fns/utils/Messenger.ts
=> fix: remove proxy object from dataTree

app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_BasicChildWidgetInteraction_spec.js, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_BasicServerSideData_spec.js, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_Meta_Hydration_ClientSide_spec.js, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_Meta_Hydration_ServerSide_spec.js
Improve Listv2 tests
https://theappsmith.slack.com/archives/C02JV8G1MP0/p1676925949886009
- Cypress
=> chore: improve list widget test

.github/ISSUE_TEMPLATE/--bug-report.yaml
template changes to add environment details
=> chore: template changes

.github/workflows/ci-merge-check.yml, .github/workflows/ci-test-check.yml, .github/workflows/ok-to-test.yml
Add ci test check command
Media
- Manual
=> ci: Add ci merge check command

app/client/src/workers/Evaluation/JSObject/JSVariableProxy.ts, app/client/src/workers/Evaluation/JSObject/JSVariableUpdates.ts, app/client/src/workers/Evaluation/JSObject/checkUpdate.ts, app/client/src/workers/Evaluation/JSObject/index.ts, app/client/src/workers/Evaluation/evaluate.ts
=> fix async evaluation

app/client/src/widgets/AudioRecorderWidget/index.ts, app/client/src/widgets/ButtonGroupWidget/index.ts, app/client/src/widgets/CameraWidget/index.ts, app/client/src/widgets/ChartWidget/index.ts, app/client/src/widgets/CodeScannerWidget/index.ts, app/client/src/widgets/DocumentViewerWidget/index.ts, app/client/src/widgets/FormWidget/index.ts, app/client/src/widgets/IframeWidget/index.ts, app/client/src/widgets/ImageWidget/index.ts, app/client/src/widgets/JSONFormWidget/index.ts, app/client/src/widgets/ListWidget/index.ts, app/client/src/widgets/ListWidgetV2/index.ts, app/client/src/widgets/ProgressWidget/index.ts, app/client/src/widgets/RichTextEditorWidget/index.ts, app/client/src/widgets/StatboxWidget/index.ts, app/client/src/widgets/TableWidgetV2/index.ts, app/client/src/widgets/TabsWidget/index.ts, app/client/src/widgets/TextWidget/index.ts, app/client/src/widgets/VideoWidget/index.ts
- Add width and height constraints to 2d widgets.
Media
- Manual
> Link issues raised during DP testing for better visiblity and tracking (copy link …
=> feat: 2d widget responsiveness

app/client/src/sagas/JSLibrarySaga.ts
This PR tracks the current application id as part of the INSTALL_LIBRARY event
Fixes #20821 
Nil
=> chore: Add application Id to INSTALL_LIBRARY event

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AnalyticsServiceCEImpl.java
Adds hashed email domain to some events.
=> chore: Add email domain hash

app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Git/GitWithJSLibrary/GitwithCustomJSLibrary_spec.js, app/client/cypress/support/Objects/ObjectsCore.ts, app/client/cypress/support/Pages/LibraryInstaller.ts
Add cypress tests for custom js library with git
=> test: Add tests for custom JS library with Git

.github/workflows/perf-test.yml, .github/workflows/test-build-docker-image.yml
- Fix Perf test workflow failing due to caching step
- Remove the steps related to caching node_modules dependencies since this is supported in the setup phase
`actions/setup-node@v3` now support caching of dependencies using `actions/cache` under the hood
https://github.com/actions/setup-node#caching-global-packages-data
- Tested on CI using the Test, Build, Deploy workflow
- Manual
=> ci: Fix/debug failed post perf tests

app/client/src/ce/workers/Evaluation/evaluationUtils.test.ts, app/client/src/components/editorComponents/CodeEditor/index.tsx, app/client/src/components/editorComponents/Debugger/hooks/debuggerHooks.ts, app/client/src/sagas/DebuggerSagas.ts, app/client/src/sagas/EvaluationsSaga.ts, app/client/src/selectors/dataTreeSelectors.ts, app/client/src/utils/configTree.ts, app/client/src/workers/Evaluation/handlers/evalTree.ts, app/client/src/workers/common/DataTreeEvaluator/index.ts, app/client/src/workers/common/DependencyMap/index.ts
=> 1 step2 split data tree split

app/client/src/workers/Evaluation/functionDeterminer.ts
We perform dry runs of functions in JSObject to determine the nature(sync/async) of it. This PR disables firing audit log events during these dry runs by setting `isTriggerBased` boolean to false in createExecutionContext flow while editing the JSObject.
- Manual
=> chore: Disable audit logs during function dry runs

app/client/src/pages/Editor/BottomBar/index.tsx, app/client/src/pages/Editor/WidgetSidebar.tsx, app/client/src/pages/Editor/index.tsx, app/client/src/pages/Editor/routes.tsx, app/client/src/pages/common/PaneCountSwitcher.tsx, app/client/src/reducers/uiReducers/multiPaneReducer.ts, app/client/src/selectors/multiPaneSelectors.ts
>
Fixes https://github.com/appsmithorg/appsmith/issues/21063
Media
> Please delete options that are not …
=> chore: switch panes

app/client/src/pages/Editor/WidgetsEditor/index.tsx, app/client/src/pages/common/CanvasArenas/hooks/useCanvasDragging.ts, app/client/src/sagas/WidgetSelectionSagas.ts, app/client/src/utils/helpers.tsx
#20202 had caused a performance regression in widget selection specifically around opening and closing modals. It was noticed that focusing on widget caused the increased rendering time.
Focusing involved:
- scrolling a widget into view
- flashing the widget
These two functions are not really needed when a modal is selected since the modal already comes top and centre. Removing these two functions for widgets solved the rendering performance issue. 
Numbers:
| Test Case                | Before Widget Selection | With Widget Selection | Current PR |
|--------------------------|-------------------------|-----------------------|------------|
| Misc Open Complex Modal  | 2035.65                 | 2267.84               | 2101.03    |
| Misc Open Simple Modal   | 1191.92                 | …
=> fix: Optimise Modal open performance

app/client/src/pages/Settings/SettingsForm.tsx
> Adding a check for telemetry checkbox unchecked state even though the setting should be on
Fixes [#21191](https://github.com/appsmithorg/appsmith/issues/21191)
> Tested locally now using the steps indicated in the linked issue. Works as expected now.
- Manual
=> fix: Adding a check for telemetry checkbox unchecked state even though the setting should be on

app/client/src/pages/Editor/MainContainerLayoutControl.tsx
Reverting changes of icons of app layout designed as part of polishing efforts done whilst working on mobile responsiveness.
Fixes #21201
Media …
=> fix: Reverting new icons for app layout

.github/workflows/perf-test.yml
Disable telemetry in perf tests.
=> ci: Disable telemetry in perf tests

app/client/src/components/formControls/BaseControl.tsx, app/client/src/components/formControls/utils.test.ts, app/client/src/components/formControls/utils.ts, app/client/src/pages/Editor/DataSourceEditor/JSONtoForm.tsx, app/server/appsmith-plugins/googleSheetsPlugin/src/main/resources/form.json
This PR adds code review improvements for feature flag in gsheets form config as per https://github.com/appsmithorg/appsmith/pull/20395
Fixes #20925 
Media
- Manual
=>  chore: improvements added in gsheet form config for feature flag

.github/workflows/client-build.yml, .github/workflows/on-demand-build-docker-image-deploy-preview.yml, .github/workflows/server-build.yml
**Case-1:**
**`/build-deploy-preview skip-tests=true`**
**Client-jest skipped**
**Server Build taking less time**
**Case-2:**
**`/build-deploy-preview `**
**Case-3**
**`/build-deploy-preview  env=release`**
**github-action**
**final-dp:**
=> ci: build lite version of deploy preview

app/client/src/widgets/BaseInputWidget/component/index.tsx, app/client/src/widgets/CategorySliderWidget/index.ts, app/client/src/widgets/CheckboxWidget/component/index.tsx, app/client/src/widgets/DatePickerWidget2/component/index.tsx, app/client/src/widgets/MultiSelectTreeWidget/component/index.styled.tsx, app/client/src/widgets/MultiSelectWidgetV2/component/index.styled.tsx, app/client/src/widgets/NumberSliderWidget/index.ts, app/client/src/widgets/RangeSliderWidget/index.ts, app/client/src/widgets/RateWidget/component/index.tsx, app/client/src/widgets/SelectWidget/component/index.styled.tsx, app/client/src/widgets/SingleSelectTreeWidget/component/index.styled.tsx, app/client/src/widgets/SwitchWidget/component/index.tsx
- Add necessary min heights to widgets, adjust height in accordance to the bounding box padding.
Media
> Please describe the …
=> feat: add responsive min-height to all widgets

app/client/cypress.json, app/client/src/workers/Evaluation/evaluate.ts
Fixing the typo related to function name.
Fixes https://github.com/appsmithorg/appsmith-ee/issues/1172
Media
- Manual
- Jest
- Cypress
> Link …
=> fix: closedFn-undefined

app/client/src/widgets/withLazyRender.tsx
Fixes #20558
Media
- Manual
- Jest
- Cypress
> Add Testsmith test cases …
=> chore: [lazy canvas rendering] check observer exist before disconnecting while cleaning up

app/client/src/usagePulse/index.ts, app/client/src/widgets/withLazyRender.tsx
=> chore: release v1.9.11 - cherry-pick

app/client/cypress/package.json
- fixing cypress dependency issues
- Cypress
- Cypress
=> test: fixing cypress dependency issues

.github/workflows/perf-test.yml
- Updated the path to download the artifact in perf-test.yml
- perf-test.yml
- Manual
=> ci: Updated the path to download the artifact in perf-test.yml

.github/workflows/perf-test.yml
- Fixing the working directory in perf-test.yml
- perf-test.yml
- Manual
=> ci: Fixing the working directory in perf-test.yml

.github/workflows/build-docker-image.yml, .github/workflows/ci-debugging.yml, .github/workflows/ci-test.yml, .github/workflows/integration-tests-command.yml, .github/workflows/perf-test.yml, .github/workflows/test-build-docker-image.yml, app/client/cypress/apply-patches.js, app/client/cypress/fixtures/listv2PaginationDsl.json, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/ListV2/ListV2_PageNo_PageSize_spec.js, app/client/cypress/package.json, app/client/src/utils/widgetRenderUtils.tsx, app/client/src/widgets/ListWidgetV2/widget/index.tsx, app/server/appsmith-git/src/main/java/com/appsmith/git/service/GitExecutorImpl.java, ci-debug.sh
=> chore: Hotfix Release v1.9.11.1

Dockerfile
Updated the container runtime node version (dockerfile service layer) to v16.x
=> feat: Updated appsmithctl node version to v16.x

app/client/src/ce/constants/messages.ts, app/client/src/pages/setup/constants.ts
Updated the role information to skills
- Manual
=> fix: role skills

app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug19982_Spec.ts, app/client/src/workers/Evaluation/JSObject/Collection.ts, app/client/src/workers/Evaluation/JSObject/JSVariableProxy.ts, app/client/src/workers/Evaluation/JSObject/JSVariableUpdates.ts, app/client/src/workers/Evaluation/JSObject/__test__/JSVariableProxy.test.ts, app/client/src/workers/Evaluation/JSObject/__test__/mutation.test.ts, app/client/src/workers/Evaluation/JSObject/__test__/removeProxy.test.ts, app/client/src/workers/Evaluation/JSObject/index.ts, app/client/src/workers/Evaluation/evaluate.ts, app/client/src/workers/Evaluation/fns/__tests__/interval.test.ts, app/client/src/workers/Evaluation/fns/__tests__/run.test.ts, app/client/src/workers/Evaluation/fns/geolocationFns.ts, app/client/src/workers/Evaluation/fns/overrides/interval.ts, app/client/src/workers/Evaluation/fns/overrides/timeout.ts, app/client/src/workers/Evaluation/fns/utils/ExecutionMetaData.ts, app/client/src/workers/Evaluation/fns/utils/Promisify.ts, app/client/src/workers/Evaluation/fns/utils/__tests__/Promisify.test.ts, app/client/src/workers/Evaluation/functionDeterminer.ts, app/client/src/workers/Evaluation/handlers/evalTrigger.ts, app/client/src/workers/common/DataTreeEvaluator/index.ts
=> fix: js object var edit

.github/workflows/ci-debugging.yml, .github/workflows/ci-test.yml
- This PR includes MsSQL as separate docker container inside CI that can be used for running mssql ds test cases in CI
- CI-Debugging tmate session
=> test: Setup MSSQL docker container for CI runs

.github/workflows/ci-test.yml
- This PR reverts the loading of data into MsSQL container with docker exec, until JDBC driver issue fixed.
- Yml file update (commenting)
=> test: Comment init loading into MsSQL container

.github/workflows/ci-test.yml
- This PR init loads the data into MsSQL container after starting it
=> ci: Init loading data into MsSQL container 

.github/workflows/ci-test.yml
- This PR reverts the loading of data into MsSQL container with docker exec - login timeout issue fixed.
- Yml file update (commenting two lines of code)
=> revert: Init Load into MSSQL container 

.github/workflows/perf-tests-command.yml
Add   build-docker-image step to perf-test command
=> ci: Fix /perf-test command (#21457

app/server/appsmith-server/src/main/resources/features/init-flags.yml
This PR updates the feature flag for Limiting Gsheet Access project, earlier the feature flag was added for appsmith and moolya domain users, but now it is updated to only for account integrations@appsmith.com
Fixes https://github.com/appsmithorg/appsmith/issues/21390
Media
- Manual
=> chore: feature flag value updated for gsheets

.github/workflows/integration-tests-command.yml
- Deleting duplicate specs while commenting failed specs in the pr
- integration-tests-command.yml
- Manual
=> ci: Deleting duplicate specs while commenting in the pr

app/client/src/ce/sagas/ContextSwitchingSaga.ts
Add a null check 
Fixes #21307
- none
=> fix: Add a null check for actions during Context Switching

app/server/appsmith-server/src/main/java/com/appsmith/server/acl/AclPermission.java, app/server/appsmith-server/src/test/java/com/appsmith/server/acl/AclPermissionTest.java
> add utility to check if a permission is for an entity
Media
> `testIsPermissionForEntity`
=> chore: add utility to check if a permission is for an entity

app/client/src/widgets/CheckboxGroupWidget/widget/index.tsx, app/client/src/widgets/JSONFormWidget/widget/propertyConfig/properties/common.ts, app/client/src/widgets/RadioGroupWidget/widget/index.tsx, app/client/src/widgets/RichTextEditorWidget/widget/index.tsx, app/client/src/widgets/SwitchGroupWidget/widget/index.tsx
- Hide fontsize property control in autolayout mode.
Media
> Please describe the tests that you ran to verify your changes. …
=> fix: hide label font size in autolayout

app/client/src/actions/pageActions.tsx, app/client/src/sagas/WidgetAdditionSagas.ts, app/client/src/sagas/WidgetOperationSagas.tsx, app/client/src/utils/autoLayout/positionUtils.ts, app/client/src/widgets/BaseWidget.tsx
Retains user defined width in percentage of viewport width for horizontally resizable hug widgets
Fixes #21463
=> feat: Keeps track of user defined width for widgets

app/client/src/selectors/entitiesSelector.ts
Replicating the changes of EE in CE https://github.com/appsmithorg/appsmith-ee/pull/941/files#diff-3b6510f706b68a0372cb976a4bfc8b1f85c822ce6d402ace608dc11636d81407
- Chore 
- Manual
- Jest
- Cypress
=> chore: fix merge conflict with ee

.github/workflows/ci-test.yml
- Updated the combined_failed_spec_ci path in ci-test.yml
- ci-test.yml
- Manual
=> ci: Updated the combined_failed_spec_ci path in ci-test.yml

.github/workflows/integration-tests-command.yml, .github/workflows/test-build-docker-image.yml
- Removed the artifact deleting as we need the artifact in case of rerun on cancel
- Workflow yml files
- Manual
=> ci: Removed the artifact deleting as we need the artifact in case of rerun on cancel

app/client/src/selectors/navigationSelectors.ts
Fixes `Command_Click_Navigation_spec`
Not sure why the [original PR](https://github.com/appsmithorg/appsmith/pull/21492) passed though. ([Test run](https://github.com/appsmithorg/appsmith/actions/runs/4465550932))
=> ci: fix Command_Click_Navigation_spec test

app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ActionCollectionControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ActionControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ApplicationControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ApplicationTemplateControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/AssetControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/BaseController.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ConfigControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/CustomJSLibControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/DatasourceControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/GitControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/HealthCheckControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/IndexControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/InstanceAdminControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ItemControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/LayoutControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/MarketplaceControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/NotificationControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/PageControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/PluginControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ProviderControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/RestApiImportControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/SaasControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/TenantControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ThemeControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/UsagePulseControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/UserControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/WorkspaceControllerCE.java
This PR reverts the changes on controller method that happened by mistake. It adds JsonView annotation on all controller methods.
Earlier PR: https://github.com/appsmithorg/appsmith/pull/20086
=> reverted jsonview changes on controllers

app/client/cypress/support/commands.js
- This PR aims to fix the welcome screen button click failures seen recently in CI runs
- Script fix
=> test: Cypress - Welcome screen - Before hook FailureFix - CI runs

app/client/src/sagas/AutoLayoutUpdateSagas.tsx
Updates mobileBottomRow & mobileRightColumn while processing auto dimension updates.
Fixes #21587
Fixes #21651
=> fix: Makes the auto dimension update to work on mobile view

contributions/AppsmithWidgetDevelopmentGuide.md
=> chore: Use correct function name in documentation for meta properties

app/client/packages/wds/src/utils/colors.ts
=> feat: Widgets color generation utility functions

app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/ListV2/ListV2_PropertyPane_spec.js, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_Meta_Hydration_ServerSide_spec.js, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_dataIdentifierProperty_spec.js, app/client/cypress/support/commands.js
- Listv2_Meta_Hydration_ServerSide_spec.js
- Listv2_dataIdentifierProperty_spec.js
- ListV2_PropertyPane_spec.js
=> test: Cypress - Fix Flaky Tests

app/client/cypress/support/commands.js
- Keeping the telemetry & Stay in touch toggles on which was missed in previous merge
- Cypress run local
=> test: Segment call interception cont.,

app/client/cypress/support/commands.js
- This PR corrects the api request validation in case of the welcome toggles left ON
- Script fix
=> test: Segment call interception conts.,

app/client/src/widgets/CodeScannerWidget/index.ts, app/client/src/widgets/CodeScannerWidget/widget/propertyConfig/contentConfig.ts
- Remove Button mode for scanner widget in auto layout.
Fixes #21378 
Media
- Manual
> Link issues raised during DP testing for better visiblity …
=> fix: remove button mode for scanner widget.

.github/workflows/integration-tests-command.yml
- Added dub points for failed-spec comment
- YML File changes
- Manual
=> ci: Added dub points for failed-spec comment

app/client/cypress/support/commands.js
> Adding intercept for admin env API to send origin request header
> Ran analytics spec locally and tested it out to be successfully completed.
- Cypress
=> ci: Adding intercept for admin env API to send origin request header

app/client/cypress/support/commands.js
- This PR fixes the welcome screen button click - which sometimes fails the spec in before hook itself
- Script fix
=> test: Cypress - Flaky fix

app/client/src/resizable/autolayoutresize/index.tsx, app/client/src/utils/autoLayout/positionUtils.ts
- Removes the min height/width restriction from autolayoutresize
- Checking for minHeight within positionUtils
Fixes #21462
=> fix: Manual resize doesn't properly respect min dimensions

app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ExplorerTests/Entity_Explorer_Widgets_Copy_Paste_Delete_Undo_Keyboard_Event_spec.js, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Git/GitImport/GitImport_spec.js, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/Form/Form_With_CheckBox_spec.js
- GitImport_Spec.js
- Entity_Explorer_Widgets_Copy_Paste_Delete_Undo_Keyboard_Event_spec.js
- Form_With_CheckBox_spec.js
=> test: Cypress - Flaky test fix

app/client/package.json, app/client/yarn.lock
Updates this release: https://github.com/appsmithorg/design-system/pull/420
Depends on https://github.com/appsmithorg/design-system/pull/420 as well.
- Manual
- Jest
- Cypress
=> chore: update alpha release

app/client/src/utils/JSPaneUtils.tsx
Update the JSObject template 
1. Introduce JSObject variable mutation and improve its discoverability 
2. Show autocomplete suggestions for `this` keyword
3. Move away from complex arrow syntax for function declaration
Fixes #21489
- Chore 
- Cypress
=> chore: update js object template

app/client/cypress/support/commands.js, app/client/src/RouteChangeListener.tsx, app/client/src/actions/focusHistoryActions.ts, app/client/src/ce/sagas/NavigationSagas.ts, app/client/src/components/editorComponents/CloseEditor.tsx, app/client/src/components/editorComponents/WidgetNameComponent/index.tsx, app/client/src/pages/Editor/DataSourceEditor/BackButton.tsx, app/client/src/pages/Editor/FirstTimeUserOnboarding/Checklist.test.tsx, app/client/src/pages/Editor/FirstTimeUserOnboarding/Tasks.test.tsx, app/client/src/pages/Editor/GlobalHotKeys/GlobalHotKeys.test.tsx, app/client/src/utils/history.ts, app/client/src/utils/hooks/useClickToSelectWidget.tsx, app/client/src/utils/hooks/useWidgetSelection.ts, app/client/test/testUtils.tsx
Added following new events for gaps inside analytics
- ActionBackButton
- CanvasClick
Fixes #21417
- Manual
=> chore: Add new navigation scenarios for route change event

.github/workflows/integration-tests-command.yml
- This PR adds the Flaky list application link into the git comments section on completion of the run, so the PR owners have easy access to it.
=> ci: Adding Identified Flaky tests app link into Git comments section in a PR

app/client/src/widgets/IframeWidget/component/index.tsx
- Iframe was not taking full width in autolayout mode added `width: 100%` to the container.
Fixes #21886 
Media
> …
=> fix: iframe width in autolayout mode.

app/client/src/actions/pageActions.tsx, app/client/src/sagas/PageSagas.tsx
Improve error reporting for missing page id
Media
> Please also list any relevant …
=> chore: Move error from saga to action creator

app/client/src/pages/AppViewer/AppPage.styled.tsx, app/client/src/pages/Editor/WidgetsEditor/index.tsx
- Navigation panel height issue resolved, added `height:  100vh` in preview mode.
Fixes #22013
Media
> Delete …
=> fix: navigation height in preview mode.

app/client/src/pages/workspace/settings.tsx
> Updating logic for redirection on Members settings page on Workspace settings
Fixes [#22034](https://github.com/appsmithorg/appsmith/issues/22034)
> Tested it manually on my local and works as expected now.
- Manual
=> fix: Updating logic for redirection on Members settings page on Workspace settings

app/client/cypress/integration/SanitySuite/Datasources/AuthenticatedApiDatasource_spec.js, app/client/cypress/integration/SanitySuite/Datasources/RestApiOAuth2Validation_spec.js
- This PR fixes the reference issues for the Sanity suites
=> test: Cypress - Fix reference issue in spec for Sanity suite

app/rts/package.json, app/rts/yarn.lock, app/shared/ast/rollup.config.js
This issue fixes RTS build failure due to `(node:3527) [DEP0128] DeprecationWarning: Invalid 'main' field in @shared/ast`. More information can be found [here](https://nodejs.org/api/deprecations.html#dep0128-modules-with-an-invalid-main-entry-and-an-indexjs-file).
The bug here was that, when the ast package was built, we were not updating the package.json of the build to point to index.js directly, instead it was pointing to `build/index.js`. This was not a problem in nodejs 14, However new versions of nodejs requires we drop the "build/" and simply make it `index.js`.
Before:
After: 
Fixes #22118
- Manual …
=> fix: fix package.json file for ast build

app/client/cypress/support/Pages/EntityExplorer.ts
- This PR improves the ExpandCollpase() method - so the Expand method does not fail in CI
- Script fixes
- Cypress CI runs
=> test: Cypress - EntityExplorer ExpandCollapse() improvement

deploy/docker/templates/nginx/nginx-app-http.conf.template.sh, deploy/docker/templates/nginx/nginx-app-https.conf.template.sh
=> chore: Add Cache-Control header for static assets

deploy/docker/templates/nginx/nginx-app-http.conf.template.sh, deploy/docker/templates/nginx/nginx-app-https.conf.template.sh
Reverts appsmithorg/appsmith#21951
=> Revert "chore: Add Cache-Control header for static assets"

.github/workflows/client-build.yml
Fixes: [22072](https://github.com/appsmithorg/appsmith/issues/22072)
Running as part of individual builds:
https://github.com/appsmithorg/appsmith/actions/runs/4605026111/jobs/8136569091
=> fix:skipping jest-tests in client workflow

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ActionPermission.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ApplicationPermission.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/DatasourcePermission.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/DomainPermission.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/PagePermission.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/PermissionGroupPermission.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/WorkspacePermission.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ActionPermissionCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ActionPermissionCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ApplicationPermissionCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ApplicationPermissionCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourcePermissionCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourcePermissionCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DomainPermissionCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PagePermissionCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PagePermissionCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PermissionGroupPermissionCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PermissionGroupPermissionCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/WorkspacePermissionCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/WorkspacePermissionCEImpl.java
This refactoring PR moved common methods of permission classes to a new base class.
Fixes #22127 
- Manual
- JUnit tests
- Jest
- Cypress
=> chore: Moved common methods of permission classes to base class

app/client/src/workers/Evaluation/fns/utils/TriggerEmitter.ts
Changes to fix the jest test failure on EE. 
- Chore
=> fix: Changes to fix ee jest test

app/client/src/pages/common/ErrorPages/Page.tsx
Adding a class used for test cases in EE.
https://github.com/appsmithorg/appsmith-ee/pull/1132/files#diff-2bf42f6d56d5e36ea2878cfbcc7adacf12443855ea03055e39f632402b8921fe
This created a conflict [here](https://github.com/appsmithorg/appsmith-ee/actions/runs/4656127341/jobs/8239454392).
=> chore: fix merge conflict

.github/workflows/integration-tests-command.yml
- This PR updates the text message that gets commented after a PR run
=> ci: Update the text in Git comment flaky tests app link

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/InstanceConfig.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/InstanceConfigHelper.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/InstanceConfigHelperImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/InstanceConfigHelperCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/InstanceConfigHelperCEImpl.java
For air gap instances, public internet will be restricted and as a result, API calls which will be made during the instance registration should be gracefully handled for air-gap isnatnce. As a part of this, the current PR creates a helper class from Instance config class to have a custom implementation on the EE repo.
Corresponding EE PR: https://github.com/appsmithorg/appsmith-ee/pull/1263
Related issue: https://github.com/appsmithorg/appsmith/issues/21500
- Manual
=> chore: Add helper methods for instance configuration class

app/client/src/actions/debuggerActions.ts, app/client/src/sagas/DebuggerSagas.ts
> Adds errorID, tat and appsmith error code to plugin execution errors
Fixes #22348 
- Manual
=> chore: Add telemetry for resolved error message

.github/workflows/on-demand-build-docker-image-deploy-preview.yml, scripts/deploy_preview.sh
fixes: [248](https://github.com/appsmithorg/cloud-deployment/issues/248)
https://github.com/appsmithorg/appsmith-ci/pull/14#issuecomment-1504569726
This doesnt delete the existing stacks 
https://github.com/appsmithorg/appsmith-ci/pull/14#issuecomment-1504842238
this deletes the stack, database in mongo and therefore creating a complete new stack
=> ci: add recreate option for dps

app/server/appsmith-plugins/graphqlPlugin/pom.xml, app/server/appsmith-plugins/graphqlPlugin/src/test/java/com/external/plugins/GraphQLPluginTest.java, app/server/appsmith-server/pom.xml
This PR upgrades the Graphql dependency to the latest stable release.
=> chore: Upgrading graphql dependency

app/client/src/ce/constants/messages.ts, app/client/src/ce/pages/workspace/Members.tsx, app/client/src/pages/workspace/DeleteConfirmationModal.tsx
Updating the message on delete user confirmation modal
Fixes [#22425](https://github.com/appsmithorg/appsmith/issues/22425)
- Manual
=> fix: Updating the message on delete user confirmation modal

app/client/package.json, app/client/yarn.lock
Updating the version for design-system-old dependency
Fixes [#22033](https://github.com/appsmithorg/appsmith/issues/22033)
- Manual
- Jest
- Cypress
=> chore: Updating the version for design-system-old dependency

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java
- Update plugin name to `Oracle` from `Oracle plugin`
- Update plugin icon
Related to #20796 
- Manual
=> fix: fix oracle plugin info

.github/workflows/cleanup-dp.yml, scripts/cleanup_dp.sh
[20765](https://github.com/appsmithorg/appsmith/issues/20765)
=> ci: add workflows to cleanup merged deploy-previews

.github/workflows/cleanup-dp.yml, scripts/cleanup_dp.sh
Succesful run: https://github.com/appsmithorg/appsmith/actions/runs/4718116171/jobs/8367371248
=> ci: uncomment debug statements and clear dps when merged

contributions/ServerSetup.md
Update docs to point to the arm architecture images for mongodb and redis for local setup of server in Apple Silicon
Fixes #22402 
> Documentation update
- Manual
=> docs: Add docker instructions for apple silicon

app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Templates/Fork_Template_spec.js, app/client/cypress/integration/SmokeSuite/Application/ReconnectDatasource_spec.js
>
Fixes tests by adding looking for required element from the root
This is done by passing `{ withinSubject: null, }` as config to `cy.get()`
Media
- Cypress
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on …
=> chore: Adds fix for flaky tests of reconnect datasources list.

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/WorkspaceServiceTest.java
> Change the update workspace flow to update using the MongoTemplate `updateFirst` rather than Repository `save`
Media
> `testWorkspaceUpdate_checkAdditionalFieldsArePresentAfterUpdate` 
=> chore: change workspace update from save to update object

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/constants/AnalyticsConstants.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AnalyticsServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AnalyticsServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/UserSignupCEImpl.java
This PR adds/updates the fields which are getting reported as a part of `Setup Complete Event` as a part of onboarding revamp project.
Fixes https://github.com/appsmithorg/cloud-services/issues/675
- Manual
=> feat: Update the Installation Setup Complete event to better track the analytics

app/client/package.json, app/client/src/WidgetQueryGenerators/MongoDB.test.ts, app/client/src/WidgetQueryGenerators/MongoDB.ts, app/client/src/WidgetQueryGenerators/PostgreSQL.test.ts, app/client/src/WidgetQueryGenerators/PostgreSQL.ts, app/client/src/WidgetQueryGenerators/index.ts, app/client/yarn.lock
Developed a postgresql query generator which translates one click binding form config to the corresponding query.
Fixes #21508
- Manual
- Jest
=> [one click binding] Postgre query adaptor changes

app/client/cypress/integration/Regression_TestSuite/ClientSideTests/SettingsPane/EmbedSettings_spec.ts
Fixes test case failures in EmbedSettings spec.
- Cypress
=> fix: Cypress fix - failed embedsettings spec

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration007UpdatePluginDocsLink.java
New links will lead users directly to the most relevant sections in the docs.
- Manual
=> fix: Modified plugin documentation links

app/client/cypress/integration/Regression_TestSuite/ClientSideTests/AdminSettings/Admin_settings_spec.js, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ExplorerTests/Admin_settings_spec.js, app/client/cypress/integration/Regression_TestSuite/EnterpriseTests/AdminSettings/Admin_settings_spec.js, app/client/cypress/support/commands.js
- This PR fixes the flaky ExplorerTests/Admin_settings_spec.js in CI runs
=> test: Cypress - fix for ExplorerTests/Admin_settings_spec.js 

.github/workflows/client-build.yml
Increased clientbuild runner
- Manual
None
None
=> ci: Increased clientbuild runner

app/client/cypress/fixtures/datasources.json, app/client/cypress/integration/Regression_TestSuite/ServerSideTests/Datasources/Redis_Basic_Spec.ts, app/client/cypress/support/Pages/DataSources.ts
- This PR includes tests for Redis datasource - basics tests with querying in query page
- New script
- Cypress CI runs
=> test: Cypress - Automated Basic tests for Redis datasource

app/client/src/components/utils/helperComponents.tsx, app/client/src/pages/workspace/SettingsPageHeader.tsx, app/client/src/pages/workspace/settings.tsx
The PR deduplicate workspace setting tab components.
Media
> Please also list any …
=> fix: [ADS 2.0] workspace setting tab component deduplication

app/client/build.sh
- Try increasing the memory limit for node process to test client build OOM error.
Media
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can …
=> chore: increase build process heap size

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/WorkspaceServiceTest.java
> This is a helper migration PR which contains the following changes:
> - #22549 (This contains the changes which will only update the required fields in the workspace and not the entire workspace document. This is needed for the Migration 102 in EE PR.)
> if no issue exists, please create an issue and ask the maintainers
about this first
Media
> A video or a GIF is preferred. when using Loom, don’t embed because it
looks like it’s a GIF. instead, just link to the video
=> chore: helper migration commits before migration runs

app/client/cypress/integration/Regression_TestSuite/ServerSideTests/ApiTests/API_Bugs_Spec.js, app/client/cypress/integration/SanitySuite/Datasources/Airtable_Basic_Spec.ts, app/server/appsmith-plugins/graphqlPlugin/src/main/java/com/external/plugins/GraphQLPlugin.java, app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java, app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
Merging for cypress tests passing to master
=> fix: airtable spec fix

app/client/src/widgets/MetaHOC.tsx, app/client/src/widgets/TextWidget/component/index.tsx
=> chore: Hotfix Release v1.9.17

app/client/src/widgets/RichTextEditorWidget/component/index.tsx
Added code option in tinyMCE editor 
Fixes: https://github.com/appsmithorg/appsmith/issues/13882
- Manual
steps to test
- click on Widgets + icon
- search for 'rich text editor
- in rich text editor you should be able to see '<>' icon
- on clicking '<>' icon, you'll be able to see the HTML source code
- if you add any HTML code, should be able to see changes in editor
=> feat: added TinyMCE code plugin

app/client/package.json, app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx, app/client/src/pages/Editor/EntityNotFoundPane.tsx, app/client/src/sagas/ActionSagas.ts, app/client/yarn.lock
Fixes some issues with the deduplicated api pages.
- Manual
- Jest
- Cypress
=> fix: Fix some of the errors

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java
Fix for Google Sheets generate CRUD
=> fix: Default to empty structure when not available

app/client/src/pages/Applications/ProductUpdatesModal/index.tsx, app/client/src/pages/Editor/BottomBar/ManualUpgrades.tsx, app/client/src/pages/Editor/BottomBar/index.tsx, app/client/src/pages/tests/slug.test.tsx
This PR deduplicate Manual product update modal & upgrade icon & tooltip in the bottom bar.
https://www.loom.com/share/f78e477036ec4a19b3c301d4065b1f5d
Issue listed on [notion](https://www.notion.so/appsmith/f353d8c6bd664f79ad858a42010cdfc8?v=f04cde23f6424aeb9d5a6e389cd172bd&p=2d695457152f40af93a7ad40c2a762e5&pm=s)
> Please describe the tests that you ran to verify your changes. Provide instructions, so we can …
=> feat: Deduplicate Manual Product Update Modal

.github/pull_request_template.md
Cleaned up template heading and section styles on PR template
=> chore: cleaned up formatting for the template

app/client/src/ce/constants/messages.ts, app/client/src/ce/pages/Applications/EmbedSnippetTab.tsx, app/client/src/ce/pages/Applications/index.tsx, app/client/src/ce/pages/workspace/Members.tsx, app/client/src/ce/pages/workspace/WorkspaceInviteUsersForm.tsx, app/client/src/components/editorComponents/form/FormDialogComponent.tsx, app/client/src/components/utils/helperComponents.tsx, app/client/src/pages/AppViewer/Navigation/components/ShareButton.tsx, app/client/src/pages/Applications/EmbedSnippet/DimensionsInput.tsx, app/client/src/pages/Applications/EmbedSnippet/PrivateEmbeddingContent.tsx, app/client/src/pages/Applications/EmbedSnippet/Snippet.tsx, app/client/src/pages/Applications/EmbedSnippet/useUpdateEmbedSnippet.tsx, app/client/src/pages/Editor/EditorHeader.tsx, app/client/src/pages/Templates/ForkTemplate.tsx, app/client/src/pages/common/SubHeader.tsx, app/client/src/pages/workspace/AppInviteUsersForm.tsx, app/client/src/pages/workspace/ManageUsers.tsx, app/client/src/pages/workspace/SettingsPageHeader.tsx, app/client/src/pages/workspace/settings.tsx, app/client/src/utils/AppsmithUtils.tsx
Reverts appsmithorg/appsmith#22484
=> Revert "feat: Deduplicate share modal and members page"

app/client/src/components/editorComponents/CodeEditor/generateQuickCommands.tsx, app/client/src/entities/FeatureFlags.ts
We will now start to use lowercase for ff names.
=> fix: Renaming ff to conform to new type

deploy/helm/Chart.yaml, deploy/helm/values.yaml
Fixes: [21796](https://github.com/appsmithorg/appsmith/issues/21796)
=> helm: add node selectors for appsmith sub-charts

app/client/src/utils/helpers.tsx
HTML character codes require using html elements. Replaced it with unicode.
https://www.notion.so/appsmith/Toast-texts-are-broken-on-Redo-and-Undo-actions-7f25d936b42d43b5a59d6838a0cbf46d
>
>
>
>
>
> …
=> fix: undo redo toast message (ADS)

app/client/src/pages/AppViewer/Navigation/components/BackToAppsButton.tsx
https://www.notion.so/appsmith/All-Apps-tooltip-dedup-14e1e612d1164c2ca5df078b3fb6f50e
>
>
>
>
>
>
>
>
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments …
=> chore: deduplicate view mode all apps tooltip

app/client/src/pages/Editor/gitSync/components/BranchList.tsx, app/client/src/pages/Editor/gitSync/components/BranchMoreMenu.tsx, app/client/src/pages/Editor/gitSync/components/DeployPreview.tsx, app/client/src/pages/Editor/gitSync/components/StatusLoader.tsx
https://www.notion.so/appsmith/f353d8c6bd664f79ad858a42010cdfc8?v=f04cde23f6424aeb9d5a6e389cd172bd&p=e7d219f90e8e43b59b16527704918966&pm=s
- Fixes branch name loader overlap
- Update stroke color of cloud icon
- Reduce size of spinner
- Fixes delete branch name stuck at loading state. The menu item click was causing the branch item onClick to be called, stopping event propagation fixes this. 
https://github.com/appsmithorg/appsmith/assets/67054171/04ea4691-5faa-4b33-858c-78c6af66909f
- Chore (housekeeping or task changes that don't …
=> fix: git ADS issues

app/server/appsmith-server/src/main/java/com/appsmith/server/services/WorkspaceServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCEImpl.java
Only a refactoring task, does not require testing.
=> chore: Refactored a few workspace related methods for reusability

app/client/src/entities/FeatureFlags.ts, app/client/src/widgets/withLazyRender.tsx, app/server/appsmith-server/src/main/java/com/appsmith/server/featureflags/FeatureFlagEnum.java, app/server/appsmith-server/src/main/resources/features/init-flags.yml
This PR removes the lazy canvas rendering feature flag and makes the feature available for all the users.
Fixes https://github.com/appsmithorg/appsmith/issues/21633
Media
> Please also …
=> chore: Remove lazy canvas rendering feature flag - LAZY_CANVAS_RENDERING

app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationSuccessHandlerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/UserSignupCEImpl.java
> The code changes in the PR are supposed to capture duration of business operation logics which are executed during the creation of user.
Fixes #22147 
> None. We are adding logs to capture duration of business operation logic.
=> chore: add logs to capture duration for operations

app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/plugins/RedisPlugin.java, app/server/appsmith-plugins/redisPlugin/src/test/java/com/external/plugins/RedisPluginTest.java
- Changed the error message returned in case of an invalid hostname for Redis.
- This PR does not solve the issue for mongo.
Fixes #21405  
- Manual
- JUnit
=> fix: Redis Error Message Fix

app/client/src/pages/Editor/FirstTimeUserOnboarding/Statusbar.tsx
Fixes close button color
https://www.notion.so/appsmith/First-time-onboarding-Build-your-own-app-flow-c91aa60666b2488db5b0b0abc0321ab9?pvs=4#3f5a4dbb39d74933991e847036f37289
Before
After
>
>
>
>
>
>
>
>
> Link issues raised during DP testing for …
=> fix: signposting close button color

app/client/src/pages/Editor/gitSync/ReconnectDatasourceModal.tsx
https://www.notion.so/appsmith/Reconnect-Datasource-Modal-is-broken-62201e5b77834410a114801dd80ce752
https://github.com/appsmithorg/appsmith/assets/67054171/9797f23d-12ea-4775-83ed-6c70660fcc7b
>
>
>
>
>
> …
=> fix: datasource connect modal scroll

app/client/src/pages/Editor/gitSync/QuickGitActions/BranchButton.tsx, app/client/src/pages/Editor/gitSync/components/BranchList.tsx
https://www.notion.so/appsmith/Git-Fresh-Issue-e7d219f90e8e43b59b16527704918966?pvs=4#c9ed0604dca248d590bde8c29cdd9378
>
>
>
>
>
>
>
>
> Please describe the tests that you ran to …
=> fix: git create branch loader alignment

app/server/appsmith-server/src/main/resources/features/init-flags.yml
This PR removes feature flag for Auto Layout so that the new Auto Layout editor is available for all the users.
=> feat: Auto Layout editor for everyone

.github/workflows/on-demand-build-docker-image-deploy-preview.yml
Fix an incorrect artifact download path
=> ci: Fix an incorrect artifact download path

app/client/src/pages/setup/DetailsForm.tsx
> Changed Type correctly to Re-enter Password
Fixes #23026 
=> fix: #23026, Changed type correctly to Re-enter password

app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java, app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithErrorCode.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CurlImporterServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java
- Changed the error message returned in case of empty input from the user for CURL import
Fixes #12008 
- Manual
=> fix: CURL empty command error msg fix

app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/ClearStore_spec.ts, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/RemoveValue_spec.ts, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ActionExecution/StoreValue_spec.ts, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug18369_Spec.ts, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug20841_Spec.ts, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/formHasChanged_Spec.ts, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ExplorerTests/Entity_Explorer_Pin_spec.js, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Git/GitImport/GitImport_spec.js, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/JSLibrary/Library_spec.ts, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Linting/AsyncFunctionsBoundInSyncFields_Spec.ts, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Linting/BasicLint_spec.ts, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Linting/EntityPropertiesLint_spec.ts, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Linting/ErrorReporting_spec.ts, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/OtherUIFeatures/Logs_spec.ts, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ThemingTests/Basic_spec.js, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/DocumentViewer/DocumentViewer_spec.ts, app/client/cypress/integration/Regression_TestSuite/ServerSideTests/JsFunctionExecution/Fetch_Spec.ts, app/client/cypress/integration/Regression_TestSuite/ServerSideTests/JsFunctionExecution/JSFunctionExecution_spec.ts, app/client/cypress/integration/Regression_TestSuite/ServerSideTests/OnLoadTests/APIOnLoad_Spec.ts, app/client/cypress/integration/Regression_TestSuite/ServerSideTests/OnLoadTests/JSOnLoad1_Spec.ts, app/client/cypress/integration/Regression_TestSuite/ServerSideTests/OnLoadTests/JSOnLoad2_Spec.ts, app/client/cypress/integration/Regression_TestSuite/ServerSideTests/Params/PassingParams_Spec.ts, app/client/cypress/integration/Regression_TestSuite/ServerSideTests/Postgres_DataTypes/Array_Spec.ts, app/client/cypress/integration/Regression_TestSuite/ServerSideTests/Postgres_DataTypes/Json_Spec.ts, app/client/cypress/integration/Regression_TestSuite/ServerSideTests/Postgres_DataTypes/UUID_Spec.ts, app/client/cypress/support/Objects/CommonLocators.ts, app/client/cypress/support/Pages/AggregateHelper.ts, app/client/cypress/support/Pages/DataSources.ts, app/client/cypress/support/Pages/EntityExplorer.ts, app/client/src/pages/Editor/Explorer/index.tsx
https://www.notion.so/appsmith/Entity-Git-Cypress-Fixes-59e5727873774d009b19f34f3013bd38
>
>
>
>
>
>
>
> …
=> chore: explorer cypress tests

contributions/ServerSetup.md
Fixes #23257
This PR fixes the structure of content in server setup documentation.
=> chore: fix server setup documentation

app/client/src/pages/Editor/Explorer/Libraries/Installer.tsx
Updating URL for addition of recommended JS libraries
=> fix: Updating URL for addition of recommended JS libraries

app/client/src/ce/constants/messages.ts, app/client/src/components/editorComponents/ActionCreator/viewComponents/Action/ActionSelector.tsx, app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx, app/client/src/pages/Editor/FirstTimeUserOnboarding/IntroductionModal.tsx, app/client/src/widgets/TableWidget/widget/propertyConfig.ts, app/client/src/widgets/TableWidgetV2/widget/propertyConfig/PanelConfig/TextFormatting.ts
Fixes more adhoc issues 
More details here: 
1. https://www.notion.so/appsmith/f353d8c6bd664f79ad858a42010cdfc8?v=f04cde23f6424aeb9d5a6e389cd172bd&p=0fa2aeee24b14b259f35be3a514d9961&pm=s
2. https://www.notion.so/appsmith/f353d8c6bd664f79ad858a42010cdfc8?v=f04cde23f6424aeb9d5a6e389cd172bd&p=806099be0cec4f43b70bf4d27786df66&pm=s
3. https://www.notion.so/appsmith/f353d8c6bd664f79ad858a42010cdfc8?v=f04cde23f6424aeb9d5a6e389cd172bd&p=ac5e339b03a2462280e365338e55eb14&pm=s
4. https://www.notion.so/appsmith/f353d8c6bd664f79ad858a42010cdfc8?v=f04cde23f6424aeb9d5a6e389cd172bd&p=6feb20d625d44e2e8b90a593276d4e6b&pm=s
5. https://www.notion.so/appsmith/f353d8c6bd664f79ad858a42010cdfc8?v=f04cde23f6424aeb9d5a6e389cd172bd&p=f8320f6ef1ef412aac837dcb4cb9ca3e&pm=s
- Bug fix (non-breaking change which fixes …
=> fix: Fix adhoc issues

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration011AddPluginTypeIndexToNewActionCollection.java
> TL;DR: Adding index in NewAction collection
-  ApplicationId
-  PluginType
-  deletedAt
Fixes #23273 
=> chore: adding index for new action

app/client/src/globalStyles/tooltip.ts, app/client/src/pages/Settings/FormGroup/Radio.tsx
Fixing the styles for the Tooltip component under old design system
=> fix: Styles for the Tooltip component under old design system

app/client/src/pages/Settings/FormGroup/Button.tsx, app/client/src/pages/Settings/FormGroup/Checkbox.tsx, app/client/src/pages/Settings/FormGroup/Common.tsx, app/client/src/pages/Settings/FormGroup/CopyUrlForm.tsx, app/client/src/pages/Settings/FormGroup/Radio.tsx, app/client/src/pages/Settings/FormGroup/TextAreaField.tsx, app/client/src/pages/Settings/FormGroup/TextInput.tsx, app/client/src/pages/Settings/FormGroup/group.tsx, app/client/src/pages/Settings/config/branding/SettingsForm.tsx
Updating labels of input fields under Admin settings
=> fix: Updating labels of input fields under Admin settings

app/client/src/ce/constants/messages.ts, app/client/src/pages/Editor/IntegrationEditor/UnsupportedPluginDialog.tsx
This PR fixes https://www.notion.so/appsmith/Modal-in-Datasources-CRUD-page-needs-changes-b803a36490324e9bbe3d9b7999395c04
>
>
>
>
>
>
>
>
- New feature (non-breaking change which adds …
=> fix: Ads 2.0 Plugin not supported modal deduplication

app/client/src/ce/constants/messages.ts, app/client/src/components/editorComponents/Debugger/index.tsx, app/client/src/pages/Editor/CanvasLayoutConversion/hooks/useAutoToFixedLayoutFlow.ts, app/client/src/pages/Editor/CanvasPropertyPane/index.tsx, app/client/src/pages/Editor/MainContainerLayoutControl.tsx
Updating text copies
Fixes https://www.notion.so/appsmith/Sentence-case-changes-c835223800934488880fa1c388a9a953?pvs=4 https://www.notion.so/appsmith/Debugger-tooltip-copy-for-no-errors-51b6a29f060e4992bed28b3810a8bc1b?pvs=4
=> fix: Updating text copies

app/client/src/components/editorComponents/CodeEditor/styledComponents.ts, app/client/src/components/editorComponents/LazyCodeEditor/index.tsx, app/client/src/components/editorComponents/PropertyPaneSidebar.tsx, app/client/src/components/propertyControls/ComputeTablePropertyControl.tsx, app/client/src/components/propertyControls/JSONFormComputeControl.tsx, app/client/src/components/propertyControls/ListComputeControl.tsx, app/client/src/components/propertyControls/MenuButtonDynamicItemsControl.tsx, app/client/src/components/propertyControls/TableComputeValue.tsx, app/client/src/components/propertyControls/TableInlineEditValidPropertyControl.tsx, app/client/src/components/propertyControls/TableInlineEditValidationControl.tsx, app/client/src/pages/Editor/AppSettingsPane/AppSettings/NavigationSettings/ImageInput.tsx, app/client/src/pages/Editor/AppSettingsPane/AppSettings/NavigationSettings/utils.ts, app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx
UI for curly braces in property pane suggestions
=> fix: UI for curly braces in property pane suggestions

app/client/package.json, app/client/src/pages/Editor/APIEditor/PostBodyData.tsx, app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
Fixes: https://www.notion.so/appsmith/Generate-page-from-Data-QA-callouts-eec8521b7d7b4b47bf7f424bb544fe49?pvs=4#4e1f78b509c34674889f16282ed3e945
Fixes: https://www.notion.so/appsmith/f353d8c6bd664f79ad858a42010cdfc8?v=f04cde23f6424aeb9d5a6e389cd172bd&p=b1c6f2e41eea4bb88372659e5d956d31&pm=s
>
>
>
>
>
>
>
>
=> fix: Fix ads adhoc issues v2

app/client/src/pages/Editor/EditorAppName/NavigationMenuData.ts, app/client/src/pages/Editor/Explorer/Widgets/WidgetContextMenu.tsx
=> fix: ADS2.0 sentence casing  

app/client/src/pages/Editor/GuidedTour/DeviationModal.tsx
This PR deduplicate Deviation modal https://www.notion.so/appsmith/Deviation-modal-in-Guided-tour-1d114d26fea0480fa8a3b96995a9db83
>
>
>
>
>
>
>
>
>
>
> Please describe the tests that …
=> chore: [ADS 2.0] Deduplication of deviation modal in guided tour

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/UserSignupCEImpl.java
> With this code change we are trying to determine which of the operations present inside the Mono [here](https://github.com/appsmithorg/appsmith/blob/65fa4938433630a2eeefc9cd879b983f604f9f63/app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/UserSignupCEImpl.java#L264). 
> Note: 
> One preconceived notion, which I am taking here is that `getExternalAddressMono ` may be the culprit behind the slowness, because it makes call to an external address `"https://api64.ipify.org"`.  This doesn't mean that we are ruling out the other operations, and have added the logs there as well. 
Fixes #22147 
>
>
- Chore (housekeeping or task changes that …
=> chore: add duration logs inside secondary functions

app/client/src/entities/Engine/AppEditorEngine.ts
Adds null check before logging "EDITOR_OPEN" analytics event.
Fixes #15220
>
>
>
>
>
>
>
=> fix: Added null check before logging analytics

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserWorkspaceServiceCEImpl.java
Log event when default workspace role is updated for a user from members page.
Fixes #22614 
>
>
>
Existing functionalities should work properly.
>
>
>
>
>
=> fix: add audit log event for updating workspace role for member

app/client/src/ce/pages/workspace/WorkspaceInviteUsersForm.tsx
Adding button type to invite button on share modal
=> fix: Adding button type to invite button on share modal

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/NetworkUtils.java
> This is a temporary fix which will return a dummy IP instead of fetching the IP.
>
>
>
>
>
>
>
> …
=> temp fix: return dummy ip address

app/client/src/components/editorComponents/form/FormDialogComponent.tsx, app/client/src/components/formControls/FilePickerControl.tsx, app/client/src/pages/Applications/ForkApplicationModal.tsx, app/client/src/pages/Applications/ProductUpdatesModal/index.tsx, app/client/src/pages/Editor/BottomBar/ManualUpgrades.tsx, app/client/src/pages/Editor/CanvasLayoutConversion/ConversionButton.tsx, app/client/src/pages/Editor/CanvasLayoutConversion/SnapShotBannerCTA.tsx, app/client/src/pages/Editor/DataSourceEditor/SaveOrDiscardDatasourceModal.tsx, app/client/src/pages/Editor/EditorHeader.tsx, app/client/src/pages/Editor/FirstTimeUserOnboarding/IntroductionModal.tsx, app/client/src/pages/Editor/RequestConfirmationModal.tsx, app/client/src/pages/Editor/gitSync/DisconnectGitModal.tsx, app/client/src/pages/Editor/gitSync/GitSyncModal.tsx, app/client/src/pages/Editor/gitSync/RepoLimitExceededErrorModal.tsx, app/client/src/pages/Templates/ForkTemplate.tsx, app/client/src/pages/common/SubHeader.tsx, app/client/src/pages/workspace/DeleteConfirmationModal.tsx
This PR fixes https://www.notion.so/appsmith/Add-widths-to-modal-current-modal-implemented-modal-looks-large-on-larger-screen-972c227840134904987d7d4e0e540dcc
>
>
>
>
>
>
>
>
>
>
> …
=> fix: ADS 2.0 Add width to modals

app/client/src/components/editorComponents/LazyCodeEditor/CodeEditorFallback.tsx, app/client/src/components/editorComponents/LazyCodeEditor/styles.tsx, app/client/src/components/editorComponents/LightningMenu/LightningMenuTrigger.tsx, app/client/src/pages/Editor/gitSync/components/PushFailedWarning.tsx, app/client/src/pages/setup/DetailsForm.tsx
Deduplicating spinner and callout on query editor and git modal
Fixes first 3 point assigned to me here: https://www.notion.so/appsmith/Old-ds-component-sanity-f1c03d9ecaac44598b3b6ca029541f32?pvs=4
=> chore: Deduplicating spinner and callout on query editor and git modal

app/client/src/pages/Editor/PropertyPane/PropertyPaneSearchInput.tsx, app/client/src/pages/Editor/PropertyPane/PropertyPaneTitle.tsx
- Fix property pane search input
- https://www.notion.so/appsmith/f353d8c6bd664f79ad858a42010cdfc8?v=f04cde23f6424aeb9d5a6e389cd172bd&p=cb7c24b910c64946b31bf8ff88c36205&pm=s
>
>
>
>
> …
=> fix: searchinput and property pane title input.

app/client/src/workers/Evaluation/fns/utils/TriggerEmitter.ts
Fixes https://github.com/appsmithorg/appsmith/issues/21211
=> chore: use set to only send unique paths

app/client/src/sagas/ErrorSagas.tsx
Removing the check for embed param in private embedding
Fixes [#23364](https://github.com/appsmithorg/appsmith/issues/23364)
=> fix: Removing the check for embed param in private embedding

app/client/cypress/e2e/Regression_TestSuite/ClientSideTests/ExplorerTests/Scrolling_Spec.ts, app/client/cypress/locators/AppNavigation.json, app/client/cypress/support/Pages/DataSources.ts, app/client/cypress/support/Pages/EntityExplorer.ts, app/client/cypress/support/commands.js
###
Fixes scrolling spec.ts and adds some locators and airgap onboarding change.
=> fix: scrolling spec

app/client/src/ce/constants/messages.ts
Updating texts to sentence case
>
>
>
>
>
>
>
>
> Delete …
=> fix: Updating texts to sentence case

app/client/cypress/e2e/Regression_TestSuite/ClientSideTests/Widgets/List/List1_spec.js, app/client/cypress/e2e/Regression_TestSuite/ClientSideTests/Widgets/ListV2/ListV2_PageNo_PageSize_spec.js
=> fix: list v2 pageNo spec

app/server/appsmith-plugins/redshiftPlugin/src/main/java/com/external/utils/RedshiftDatasourceUtils.java, app/server/appsmith-plugins/snowflakePlugin/src/main/java/com/external/plugins/SnowflakePlugin.java
This PR includes changes for:
- Snowflake
- Redshift
> TL;DR: Modifying connection string to reduce auxiliary connection to datasources in order to required properties.
Fixes #22659 
This has been tested
>
>
=> chore: added application name in JDBC url for connection URI

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/HealthCheckServiceCEImpl.java
Hopefully, this should give us information on what's the cause for the timeout errors.
=> chore: Log timeout error information

app/client/cypress/e2e/Regression_TestSuite/ClientSideTests/EmbedSettings/EmbedSettings_spec.js
=> chore: embed settings cypress test fix

app/client/cypress/e2e/Regression_TestSuite/ClientSideTests/Workspace/Workspace_validation_spec.js, app/client/cypress/locators/HomePage.js, app/client/cypress/support/Pages/AggregateHelper.ts, app/client/cypress/support/Pages/HomePage.ts, app/client/cypress/support/WorkspaceCommands.js, app/client/src/pages/common/SharedUserList.tsx
https://www.notion.so/appsmith/Regression_TestSuite-ClientSideTests-Workspace-Workspace_validation_spec-js-143416ff23be40388bd94a88fef2dc6b
=> chore: workspace validation fixes

app/client/cypress/e2e/Regression_TestSuite/ClientSideTests/IDE/Command_Click_Navigation_spec.js, app/client/cypress/e2e/Regression_TestSuite/ClientSideTests/Widgets/Datepicker/DatePicker_Toggle_js_spec.js, app/client/cypress/support/widgetCommands.js, app/client/src/components/editorComponents/CodeEditor/generateQuickCommands.tsx
- https://www.notion.so/appsmith/Regression_TestSuite-ClientSideTests-Autocomplete-PropertyPaneSuggestion_spec-ts-b0193b1cf00443748c2b4e2d55c0ee49
- https://www.notion.so/appsmith/Regression_TestSuite-ClientSideTests-Widgets-Datepicker-DatePicker_Toggle_js_spec-js-8172d375846449b8a74d7ddcd80e0f45
>
>
>
>
- Breaking change (fix or feature that would cause existing functionality to not work as …
=> fix: cypress test cases for adsv2

app/client/cypress/e2e/Regression_TestSuite/ServerSideTests/QueryPane/S3_2_spec.js, app/client/cypress/support/Pages/DataSources.ts, app/client/cypress/support/commands.js
S3 : https://www.notion.so/appsmith/Regression_TestSuite-ServerSideTests-QueryPane-S3_2_spec-js-4197c0831e3a44d69c56e653f557d806?pvs=4
Graphql : https://www.notion.so/appsmith/SanitySuite-Datasources-GraphQL_spec-ts-861a475d511c45529940345e050d4086?pvs=4
Gsheet : https://www.notion.so/appsmith/SanitySuite-Datasources-GoogleSheetsStub_spec-ts-b1ac3c0cd0da4389ba1068fa787908b4?pvs=4
>
>
>
>
- Breaking …
=> fix: cypress test for ads v2

app/client/cypress/support/Pages/DataSources.ts
=> fix: generate crud spec fix

app/client/cypress/support/RapidMode.ts, app/client/cypress/support/commands.js, app/client/cypress/support/index.js, contributions/docs/TestAutomation.md
=> chore: Refactor RapidMode and add optimization if a test uses DSL

app/client/package.json, app/client/src/components/propertyControls/DatePickerControl.tsx, app/client/src/index.css, app/yarn.lock
- https://www.notion.so/appsmith/Date-picker-changes-17f6e1fad2554f46b47cb465c45153e2
>
>
>
>
>
>
>
>
- …
=> fix: date picker time input & footer

app/client/cypress/support/Pages/ApiPage.ts, app/client/src/components/editorComponents/form/fields/DropdownFieldWrapper.tsx, app/client/src/components/editorComponents/form/fields/KeyValueFieldArray.tsx, app/client/src/components/editorComponents/form/fields/RequestDropdownField.tsx, app/client/src/constants/ApiEditorConstants/CommonApiConstants.ts, app/client/src/utils/DynamicBindingUtils.ts
- Api multipart key value field error : https://www.notion.so/appsmith/Post-API-throwing-error-on-epic-22f2e165888a4cdba29fdd24f3d5e70c
- Command click on mysql editor : https://www.notion.so/appsmith/Command-Click-not-working-in-the-SQL-Editor-365149f6cb1c4eddaaf4c7d1cbccc715
>
>
>
>
- Chore …
=> fix: api form key value field, command click on mysql editor

.github/workflows/ci-test.yml
=> Update ci-test.yml-for ADS run

.github/workflows/ci-test.yml
Reverts appsmithorg/appsmith#23507
=> Revert "Update ci-test.yml-for ADS run"

app/client/src/ce/workers/Evaluation/Actions.ts, app/client/src/workers/Evaluation/JSObject/index.ts, app/client/src/workers/Evaluation/__tests__/Actions.test.ts, app/client/src/workers/Evaluation/__tests__/evaluate.test.ts, app/client/src/workers/Evaluation/evaluate.ts, app/client/src/workers/Evaluation/functionDeterminer.ts, app/client/src/workers/Evaluation/handlers/evalExpression.ts, app/client/src/workers/Evaluation/handlers/evalTree.ts, app/client/src/workers/Evaluation/handlers/evalTrigger.ts, app/client/src/workers/Evaluation/validations.ts, app/client/src/workers/Linting/globalData.ts, app/client/src/workers/Linting/index.ts, app/client/src/workers/Linting/utils.ts, app/client/src/workers/common/DataTreeEvaluator/index.ts
=> feat: support linting for setter methods
