app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ApplicationControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationSnapshotServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationSnapshotServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationSnapshotServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/ApplicationSnapshotServiceUnitTest.java
This PR adds the option to delete an application snapshot in the following cases:
- A DELETE API that'll delete an application snapshot
- The restore API should delete the underlying application snapshot if the restore is successful
Fixes #21215
Media
- Manual
- JUnit tests
> …
=> feat: Add option to delete a application snapshot

app/client/src/usagePulse/index.ts
Fixes https://github.com/appsmithorg/cloud-services/issues/589
Media
- …
=> chore: [Usage pulse] view mode check should factor in the widget path in URL

.github/workflows/integration-tests-command.yml, .github/workflows/perf-test.yml, .github/workflows/test-build-docker-image.yml
- Added steps to use the pre built docker image instead of building a new one in perf-test.yml
- perf-test.yml
- Manual
=> ci: Added steps to use the pre built docker image instead of building a new one

app/client/cypress/fixtures/formWithtabdsl.json, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/BugTests/Bug18369_Spec.ts, app/client/src/widgets/FormWidget/widget/index.tsx
This PR adds a default value of `false` for the hasChanges meta property of the Form Widget
Fixes #18369 
- Cypress
=> fix: Add default value for hasChanges meta property in Form Widget

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationPageServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserWorkspaceServiceTest.java
When an application is cloned, it's not published. As a result if the user tries to open the new application in view mode, it throws error. This PR fixes it.
Fixes #21309
Media
- Manual
- JUnit test
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments …
=> fix: cloned application is not published

.github/workflows/integration-tests-command.yml, .github/workflows/test-build-docker-image.yml
- Added step to delete the failed-spec-ci after combining all results to address the issue
- ci
- Manual
=> ci: Fix for failed spec comment issue

app/client/src/widgets/SelectWidget/widget/index.tsx
This PR removes a useless property called Colors is visible in the property pane which does not have any sub-property inside it.
Fixes #19241
- Bug fix
- Manual
=> chore: remove unused control in select widget

app/client/src/components/editorComponents/ResizableUtils.ts, app/client/src/resizable/autolayoutresize/index.tsx
- We can still resize `Button & Rating` widgets diagonally, we should disable the diagonal resize handlers for those widgets that cannot be resized vertically.
Fixes #21412 
Media
- Manual
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on …
=> fix: disable diagonal resize for widgets in auto layout

.github/workflows/ci-test.yml
- This PR removes the restarting of the MsSQL container which is throwing error sometimes in CI runs - WARNING: Failed to load /var/opt/mssql/mssql.conf ini file with error open /var/opt/mssql/mssql.conf: no such file or directory
- yml file update
=> ci: Stop restarting MsSQL container

app/client/src/components/propertyControls/BaseControl.tsx, app/client/src/components/propertyControls/PrimaryColumnsControlV2.tsx, app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx
For large number of columns trying to toggle the column takes a lot of time. We need to merge updates together to improve UX response time. This PR supports batch updates and there is significant improvement in the update time.
Fixes #21294 
- Manual
=> chore: batch property updates for column editable properties #21294

deploy/docker/entrypoint.sh
If the replicaSet check fails, we see the following error:
```
readWrite command not found
```
This is because of using the command interpolation backticks in the double-quoted string.
=> fix: Fix command interpolation error in replicaSet check

.github/workflows/ci-test.yml, .github/workflows/integration-tests-command.yml, .github/workflows/test-build-docker-image.yml
- Removing the old combined failed spec file
- workflow files
- Manual
=> ci: Removing the old combined failed spec file

app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/TableV2/pagesize_spec.js
- This PR fixes the pagesize_spec.js from TableV2 folder which is now consistently failing in CI
- Script fix
=> test: Cypress - TableV2/pagesize spec fix

app/client/build.sh, app/client/package.json, app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx, app/client/src/sagas/FormEvaluationSaga.ts, app/client/src/widgets/ChartWidget/widget/propertyConfig.test.ts, app/client/src/widgets/ListWidget/widget/index.tsx, app/yarn.lock
This is a follow-up to #20964 that fixes a couple surfaced issues. See commit descriptions for more details.
- Manual: running `yarn build` (ensuring the build would pass) and `yarn start` (ensuring the app loads correctly)
=> fix: yarn 3 upgrade issues

.github/workflows/build-wds-preview.yml, .github/workflows/wds-vercel-preview.yml, app/client/build-wds-storybook.sh, app/client/build.sh
- Removed WDS storybook from the client build.sh.
- Added workflow to deploy Vercel previews for release and prod.
- Added workflow to trigger event on commenting `/build-wds-preview` to a PR.
=> ci: storybook build and deploy for appsmith wds

scripts/deploy_preview.sh
Add env variable APPSMITH_CLOUD_SERVICES_BASE_URL to make sure the licence_key generation requests hit only release-cs i.e "https://release-cs.appsmith.com/" and not production-cs "https://cs.appsmith.com/"
=> ci: add release-portal url for deploy-previews

.github/workflows/ci-test.yml, .github/workflows/integration-tests-command.yml, .github/workflows/test-build-docker-image.yml
- Deleting the combined-failed-spec-ci in ci-test-result
- Yml file changes
- Manual
=> ci: Deleting the combined-failed-spec-ci in ci-test-result

.github/workflows/ci-test.yml, .github/workflows/integration-tests-command.yml, .github/workflows/test-build-docker-image.yml
- Reverting the use of combined-failed-spec-ci artifact instead of cache
- yml file changes
- Manual
=> ci: Reverting the use of combined-failed-spec-ci artifact instead of cache

app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/ListV2/Listv2_BasicClientSideData_spec.js, app/client/src/widgets/ListWidgetV2/widget/index.tsx
Reset Page Number when server-side pagination is just turned on.
Fixes #20635
- Cypress
> https://github.com/appsmithorg/TestSmith/issues/2184
=> fix: reset page number server side pagination is just enabled in List widget

app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginFormsTest.java
- Added a test case for array type input for many form update command as mentioned in [#17732](https://github.com/appsmithorg/appsmith/pull/17732)
Fixes #17732
- JUnit
=> chore: JUnit TC For Many Form Update

.github/workflows/ci-test.yml, .github/workflows/integration-tests-command.yml, .github/workflows/test-build-docker-image.yml
- Fix for combined-failed-spec-ci cache not found issue
- YML file changes
- Manual
=> ci: Fix for combined-failed-spec-ci cache not found issue

app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java, app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/exceptions/MongoPluginErrorMessages.java, app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginDatasourceTest.java
- This PR adds a check to throw a proper error if the default database name is empty and an invalid database name is provided in the authentication section for mongo db.
- Added JUnit test cases for the same. one for an invalid db name and one for a valid db name (Both with empty default db name)
- There is one more issue observed here which is not taken part in this ticket. When you try to save the mongo data source with the default database name and empty database name under auth section. Once you try to save the data source it will throw an internal server error. Created a ticket for the same: https://app.zenhub.com/workspaces/data-integration-pod-6322a759b3296d249ce5c4ed/issues/gh/appsmithorg/appsmith/21598
Fixes #12260 
- Bug Fix(non-breaking change which adds functionality)
- Manual …
=> fix: MongoDB Invalid DB Name Error Msg

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/InitUtils.java, app/server/appsmith-plugins/graphqlPlugin/src/test/java/com/external/plugins/GraphQLPluginTest.java, app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
- Added trim method to remove the whitespace from the URL while creating the request URL.
- Notion doc for the issue and fix: https://www.notion.so/appsmith/API-GraphQL-URL-With-Whitespaces-449a8fa4f3fa49e490b4b4b0fe5a16d1
Fixes #21629 
- Manual
- JUnit
=> fix: API Url Whitespace Bug Fix

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ExchangeUtils.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AnalyticsServiceCEImpl.java
We get the `User-Agent` header for frontend events today, but not for backend events. This PR get the `User-Agent` header value, from the current request context, if any, and sends it along with any analytics events.
[Relevant Slack sonversation](https://theappsmith.slack.com/archives/C02MUD8DNUR/p1679579820266469?thread_ts=1679496974.642199&cid=C02MUD8DNUR).
Sample backend event with `userAgent`:
=> chore: Include user-agent in events from backend

.github/workflows/ci-test.yml
- This PR includes Arango as separate docker container inside CI that can be used for running Arango datasource test cases in CI
=> ci: Starting Arango DB container for running Arango test scripts in CI runs

app/client/cypress/integration/Regression_TestSuite/EnterpriseTests/AdminSettings/Admin_settings_spec.js
Fixes failing cypress test where it was trying to redirect to access control link which was not accessible in EE.
- Cypress
=> test: fix failing admin settings test

.github/workflows/ci-test.yml
- Resetting the failed_spec_ci in case of success in ci-test.yml
- yml file changes
- Workflow run
=> ci: Resetting the failed_spec_ci in case of success in ci-test.yml

app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java, app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java
We seem to have introduced a hard coded 4 seconds execution timeout in the MySQL plugin that was. causing the more complicated queries to throw a stale connection exception. This PR reverts that change to allow queries to run completely.
Fixes #17324 
- Manual
- JUnit
- 
Please use [this](https://www.notion.so/appsmith/Secondary-Stale-Connection-Issue-498b349be64b494abf8d5a34a23a45b8) document to verify all scenarios where we were seeing a stale connection exception.
=> fix: Removed hard coded 4 seconds timeout for action execution in MySQL

app/client/cypress/integration/Regression_TestSuite/ClientSideTests/AppNavigation/AppNavigation_spec.js, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/AppNavigation/NavigationSettings_spec.js, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/AppNavigation/SidebarCollapse_spec.js, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/AppNavigation/Sidebar_spec.js, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/AppNavigation/TopInline_spec.js, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/AppNavigation/TopStacked_spec.js
Reducing the number of `it` blocks in Cypress test cases helps us save costs on Cypress cloud. This PR does a refactor on Cypress tests written for App Navigation.
Fixes #21847 
- Manual
- Cypress
=> fix: Combine app navigation tests where possible to reduce Cypress cloud costs

deploy/docker/entrypoint.sh
We're already checking for the AVX instruction, and producing a helpful message about it. But, we're doing that check _after_ we invoke the `mongod` process, which fails on such processes, and the error message is never shown.
This PR changes this, by doing the check before that `mongod` command is run.
=> chore: Check for AVX instruction earlier than the first mongod run

app/client/src/reducers/entityReducers/pageListReducer.tsx
> Updating the page permissions only if the data is being sent to the reducer to avoid making page permissions blank and leading to GAC-based error for auto-saving of pages.
Fixes [#20677](https://github.com/appsmithorg/appsmith/issues/20677)
> Followed the steps mentioned in the issue before and after this fix. Before the fix, the issue was reproducible. After the fix, the issue is resolved and we don't see the error anymore.
- Manual
=> fix: Updating the page permissions only if the data is being sent to the reducer

app/client/src/pages/Templates/Template/RequestTemplate.tsx
Update Request Template URL
Update the REQUEST_TEMPLATE_URL to account for changes made to the Template Request App.
https://github.com/appsmithorg/appsmith/issues/21520
- I have run the client and clicked on the "Request For A Template" button from the template tab. I confirmed that it redirected to the previous link, I made the change swapping the old URL string for the new one, saved and aran the test again. The new link directs to the correct page on the Request Template App.
- [✔️ ] My code follows the style guidelines of this project
- [ ✔️ ] I have performed a self-review of my own code
- [✔️ ] My changes generate no new warnings
=> fix: update request template url

app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java, app/server/appsmith-git/src/main/java/com/appsmith/git/service/GitExecutorImpl.java
> We're currently creating an empty txt file even when there is no body for an API call. For eg, in GET API calls. We should check whether there is content in a file before creating the file.
Fixes #21683 
- Manual
=> fix: do not create files for empty body of queries in the git repo

app/client/src/pages/Editor/AppSettingsPane/PaneHeader.tsx
Add a hover state to the close icon.
Fixes #19198
- Manual
=> fix: settings pane close icon hover

app/server/appsmith-plugins/smtpPlugin/src/main/resources/editor/send.json
Fixed the attachment placeholder for a query created on SMTP datasource
Fixes #21458 
- Manual
For sending email with attachments, tested `{{FilePicker.files}}` and `{{[FilePicker.files[0]]}}`, both works successfully but `{{FilePicker.files[0]}}`
=> fix: Changed SMTP placeholder for SMTP plugin (#21458)

app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ExplorerTests/Entity_Explorer_Query_Datasource_spec.js, app/client/cypress/integration/Regression_TestSuite/ServerSideTests/ApiTests/API_ContextMenu_spec.js, app/client/src/reducers/uiReducers/editorContextReducer.ts
Fix test case failing because of changes in https://github.com/appsmithorg/appsmith/pull/21789
It caused failures in tests that had a move of action involved.
This change will update the test cases to open the entity collapsible section after a move of action
> Fix failing test case
- Cypress
=> fix: Entity Explorer test case

app/client/cypress/integration/Regression_TestSuite/ClientSideTests/OtherUIFeatures/Omnibar_spec.js, app/client/src/components/editorComponents/GlobalSearch/index.tsx, app/client/src/components/editorComponents/GlobalSearch/useRecentEntities.tsx, app/client/src/components/editorComponents/GlobalSearch/utils.tsx
The Omnibar is supposed to update its order to ensure recent items are listed first. This stopped working at some time and this PR fixes it
> Omnibar will list recently accessed items first
Fixes #18963
- Manual
- Cypress
=> fix: Omnibar not showing recent entities

.github/workflows/build-docker-image.yml, .github/workflows/client-build.yml, .github/workflows/github-release.yml, .github/workflows/on-demand-build-docker-image-deploy-preview.yml, .github/workflows/rts-build.yml, .github/workflows/shared-modules.yml, .github/workflows/test-build-docker-image.yml, .github/workflows/upgrade-appsmith-tests.yml, app/client/.gitignore, app/client/build.sh
This PR improves the duration of the `client-build` CI pipeline:
- Enables proper package caching for Yarn 3. This lowers the `yarn install` time from 5m to ~50s (starting with the second run). ea8114f59e9fa7018809084d0b17dde800a776d5
- Packs build artifacts into an archive before uploading. GitHub actions require a separate API call for every file they need to upload, so the more files there are, the longer it takes. This lowers the artifact uploading time from ~5.5m to 30 seconds. 53b8eb2836b0aca74b2e1759fee9473bf1a0f228
- Disables ESLint plugin during the production build. The ESLint plugin is unnecessary since we have a separate ESLint checking step. This saves ~1 minute per build. 21c8ea8c17540c594679cb3d5c4678500af9e262
- Chore (housekeeping or task changes that don't impact user …
=> Improve the CI build time

app/server/appsmith-interfaces/src/main/java/com/appsmith/util/SerializationUtils.java, app/server/appsmith-server/src/test/java/com/appsmith/server/configurations/CommonConfigTest.java
This PR sets the `Public` as default view class for JsonView. It'll be overridden if the controller has it's another view set. This will prevent any accidental case when JsonView annotation is missing.
Fixes #21948
- Manual
- JUnit tests
=> chore: Add default view for JsonView

app/server/appsmith-server/src/main/java/com/appsmith/server/domains/UserData.java, app/server/appsmith-server/src/test/java/com/appsmith/server/configurations/CommonConfigTest.java
This PR fixes the build failure which got introduced because of the recent PR merged as a part of enabling default JsonView https://github.com/appsmithorg/appsmith/pull/21766
=> fix: Build failure because of access token signature difference in EE repo

app/client/src/ce/constants/messages.ts, app/client/src/ce/pages/workspace/WorkspaceInviteUsersForm.tsx
Updating empty state for members in the invite modal. Earlier, we used to show a message that email setup needs to be completed to invite users, but this doesn't hold true today. So we are removing this and adding the message "You haven't invited any users yet" in case there are no members to show in the invite modal.
Fixes [#22017](https://github.com/appsmithorg/appsmith/issues/22017)
> This has been tested manually and works as expected.
- Manual
=> chore: Updating empty state for members in the invite modal

app/server/appsmith-git/src/main/java/com/appsmith/git/service/GitExecutorImpl.java
> Fix string index out of bound during the git status API
Fixes #22025 
- Manual
=> fix: Git connected apps are showing a status error

app/client/craco.common.config.js, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Performance/LinkRelPreload_Spec.js, app/client/cypress/support/index.js, app/client/package.json, app/client/public/index.html, app/client/src/pages/Editor/EditorHeader.tsx, app/client/src/widgets/ChartWidget/widget/index.tsx, app/client/src/widgets/RichTextEditorWidget/widget/index.tsx, app/client/webpack/IconChunkNamingPlugin.js, app/yarn.lock
This PR implements route preloading for edit and view modes. In my tests on an emulated 4G connection, this makes edit and view modes load 1-1.5s sooner¹:
_↑ Edit mode. (Each line is a separate test run. `es5` is the `bundle-optimization` build, `es5-preload` is this branch’s build. `spinnerRender` is time until the spinner became visible; `fmp` is time until widgets became visible._
_↑ View mode_
_¹ — Unfortunately, a large chunk of the delay is slow waterfalling API responses which I can’t control (but Appsmith is working on separately). Hence, while the absolute improvement is big, the relative one is small._
- During the build time, we now emit two new files (`build/edit.html` and `build/view.html`). These files are identical to `build/index.html`, with the only difference – they …
=> perf: preload route chunks for view and edit modes

contributions/ClientSetup.md
In the Client Setup Document section for [Create local HTTPS certificates](https://github.com/appsmithorg/appsmith/blob/release/contributions/ClientSetup.md#if-you-would-like-to-hit-a-different-appsmith-server), removed the URL https://release.app.appsmith.com/ from the command ./start-https.sh as this step is already mentioned in the section [If you would like to hit a different Appsmith server](https://github.com/appsmithorg/appsmith/blob/release/contributions/ClientSetup.md#if-you-would-like-to-hit-a-different-appsmith-server)
Fixes #21955
- NA
=> chore: Removed server url from start-https command in ClientSetup

.github/workflows/ci-test.yml
- This PR includes ElasticSearch as separate docker container inside CI that can be used for running ElasticSearch datasource test cases in CI
- Yaml file update
=> ci: Starting ElasticSearch DB container for running test scripts in CI runs

.github/workflows/ci-test.yml
The License key is unused in this repo. Setting it here is misleading, and can cause confusions at best, or missed accidental License failures at worst.
This PR removes the License key occurrences from `ci-test.yml`.
Note: Please review/approve only. Don't merge. This will likely cause a conflict, so I'd like to be available when this is merged so I can resolve the conflict. Thanks!
=> ci: Remove license in ci-test.yml

app/client/craco.build.config.js, app/client/src/serviceWorker.js
This pull request works around [a problematic V8 heuristic](https://bugs.chromium.org/p/chromium/issues/detail?id=1428605) that makes bundle init much slower. This heuristic affects both `release` and `bundle-optimization` branches, but seem to be triggering more frequently in `bundle-optimization`.
The PR works around the heuristic by moving the pre-caching step from the `install` event to the `activate` one (which, per [this V8 blog post](https://v8.dev/blog/code-caching-for-devs#use-service-worker-caches), disables the heuristic).
On repeat visits, this seems to make main bundle init **8× faster (!)** compared to the `release` branch. (See the last screenshot below for more details.)
We use the [`workbox`](https://github.com/GoogleChrome/workbox) library in our service worker. …
=> perf: work around the V8 service worker regression

app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java
Added tests for querying various data types in MySQL plugin
Fixes #20069
- JUnit
=> chore: Added test for various data types (#20069)

app/client/src/workers/Evaluation/handlers/evalTree.ts, app/client/src/workers/Linting/index.ts, app/client/src/workers/Linting/types.ts, app/client/src/workers/Linting/utils.ts
PR inlines the initiateLinting function in the evalTree file in an attempt to optimize bundling
Nil
=> chore: lint bundling optimization

app/client/src/components/utils/CollapseComponent.tsx, app/client/src/pages/Editor/IntegrationEditor/DatasourceCard.tsx
Fix: Active datasource listing: Show more button should become show less when clicked
In the active datasource listing page, when the user clicks on "show more", the button name should be changed to "Show less".
In general, show more is changed to show less as a good usability practice.
Fixes #21368
Media
[Screencast from 2023-04-01 23-01-04.webm](https://user-images.githubusercontent.com/85070570/229305889-e7e75150-2ce5-4139-90c5-d3f199ce446e.webm)
- Jest
=> fix: Show more button should become show less when clicked

contributions/ClientSetup.md, contributions/ServerSetup.md
There was an error setting up MongoDB replica on docker image in server setup on a local machine.
The issue is highlighted in this link : https://www.linkedin.com/pulse/single-node-mongo-replica-docker-sumit-sengupta/
=> fix: improve documentation for setting Appsmith server locally

app/rts/package.json, app/rts/yarn.lock, app/shared/ast/package.json
> Adding dependencies in RTS to fix module not found errors in docker logs.
Fixes [#22193](https://github.com/appsmithorg/appsmith/issues/22193)
- By building fat container on the branch.
=> fix: Adding dependencies in RTS

app/client/start-https.sh
Caching causes more problems than it solves, during development time. This PR explicitly disables all cache during development.
=> chore: Disable all caching during dev time

.github/workflows/github-release.yml, .github/workflows/on-demand-build-docker-image-deploy-preview.yml, .github/workflows/test-build-docker-image.yml
GitHub's Variables, unlike Secrets, don't get masked in the output, and are ideal for non-secret... _variables_. I'm switching on such secret here, and depending on our experience with this, we'll look to moving more.
Of course, goes without saying, do NOT use these variables for secrets. When in doubt, use Secrets.
[Learn more about Variables](https://docs.github.com/en/actions/learn-github-actions/variables).
- I'd like approvals from all three of you before I merge this please.
- Please approve only, don't merge. I'll merge this _after_ we tag the upcoming version.
=> ci: Use vars for DOCKER_HUB_ORGANIZATION

app/server/appsmith-plugins/arangoDBPlugin/src/main/resources/templates/CREATE.aql, app/server/appsmith-plugins/mssqlPlugin/src/main/resources/templates/CREATE.sql, app/server/appsmith-plugins/mysqlPlugin/src/main/resources/templates/CREATE.sql, app/server/appsmith-plugins/oraclePlugin/src/main/resources/templates/CREATE.sql, app/server/appsmith-plugins/postgresPlugin/src/main/resources/templates/CREATE.sql, app/server/appsmith-plugins/redshiftPlugin/src/main/resources/templates/CREATE.sql, app/server/appsmith-plugins/snowflakePlugin/src/main/resources/templates/CREATE.sql
Hint text in create query in SQL-based data sources showing double `nameInput.text` field.
This PR replaced second `nameInput.text` field with `emailInput.text` in all sql datasources where this issue was occurring.
Fixes #22011
Fixes #22117
- Manual
- Jest
- Cypress
=> fix: Hint text in create query (sql based datasources)

app/client/src/widgets/PhoneInputWidget/widget/index.tsx, app/client/src/widgets/TableWidgetV2/widget/propertyUtils.ts
Fixes #22207
Fixes #22209 
The [sentry](https://github.com/appsmithorg/appsmith/issues/22207) issue occurred because the code was trying to access the `sticky` property of a column that did not exist in the table widget. Hence to mitigate this I have added an optional chaining check.
This PR also fixes #22209 by adding optional chaining while accessing the `text` prop in the phone input widget
- Manual
- Check that the console error is not thrown similar to the above sentry issue.
=> fix: null check before accessing accessing properties in table and phone input widget

app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Linting/BasicLint_spec.ts, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/ThemingTests/Basic_spec.js, app/client/cypress/integration/Regression_TestSuite/ServerSideTests/Params/PassingParams_Spec.ts, app/client/cypress/support/Pages/AggregateHelper.ts, app/client/cypress/support/Pages/EntityExplorer.ts
- This PR adds timeout for the EntityExpand() - to solve all the recent issue seen with Expanding of Entity Explorer items - either after refresh/page load/from view to edit mode navigations
- Script update (non-breaking change which fixes CI timeout issues with EntityExplorer click)
- Cypress CI run
=> test: Cypress - Flaky fix 

app/client/src/sagas/PostEvaluationSagas.ts
Sending unserializable data between threads causes a DataClone error. This occurs when a user tries to return a Function, a Promise, or any [unclonable data type](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Structured_clone_algorithm#things_that_dont_work_with_structured_clone) from a JS function.
The proposed solution is to create a lint error that prevents users from returning unclonable data types. This will take some time, so in the meanwhile, we are disabling sending logging this error to sentry. Once we have worked on this solution, we will enable sentry again.
Fixes #2654 - temporary fix till we come up with a more definitive solution
Media
- not needed
- Manual
=> fix: Remove sentry logging of clone errors 

app/client/cypress/fixtures/tableV2NewDslWithPagination.json, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/TableV2/TableV2_PropertyPane_spec.js, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/TableV2/TableV2_Widget_Copy_Paste_spec.js, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/TableV2/TableV2_pagination_spec.js, app/client/cypress/support/Pages/Table.ts, app/client/src/ce/utils/autocomplete/EntityDefinitions.ts, app/client/src/widgets/TableWidgetV2/constants.ts, app/client/src/widgets/TableWidgetV2/widget/index.tsx
… (#10522)
Fixes #10522
We have added two new boolean meta properties, previousPageVisited and nextPageVisited, that are set whenever respective pagination button is clicked. This property is updated for server side pagination mode as well as non server side pagination mode.
By default, both properties are set to false.
When the user clicks on previous page button or tries to enter a page number which is less than current page number, `previousPageVisited` is set to `true` and `nextPageVisited` is set to `false`.
The users can use these property as follows in their code : 
```
myFun1: () => {
if (Table1.nextPageVisited == true){
NextQuery.run()
}
else if (Table1.prevPageVisited == true){
PrevQuery.run()
}
else {
BaseQuery.run()
}
}
```
> …
=> fix: Table Widget property to specify if prev or next buttons were pressed

app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/FirestorePlugin.java, app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/exceptions/FirestoreErrorMessages.java, app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java
- The following PR fixes the issue where the firestore test data source was returning success even after providing an invalid project id.
- The PR address the invalid project id only not the db URL as it is fetched from the auth json If the URL is invalid in user provided entry. Also, the value is mutable at runtime from the firestore side.
-  For more detailed description of the following can be found in the notion doc here: https://www.notion.so/Firestore-c3f5c816a68a45b18395da74be97d666
Fixes #21373 
- Manual
- JUnit
=> fix: Firestore Invalid DS Test Success

app/client/src/components/formControls/DropDownControl.tsx
In google sheet query creation, when I select operation as insert many, update one, and update many, in the entity dropdown only sheet rows option is enabled by default, other options of spreadsheet and sheet are disabled, Since a single option is enabled for these operations we can default the dropdown to this option for above three operations. This PR fixes that.
Fixes #21700 
- Manual
=> fix: Fix annoying issue with Entity form control in google sheets

app/client/cypress/integration/Regression_TestSuite/ClientSideTests/IDE/MaintainContext&Focus_spec.js, app/client/src/components/editorComponents/CodeEditor/index.tsx
When typing content in the editor, the autocomplete menu pops up to suggest possible matches. If we press escape, the autocomplete menu closes but the editor loses focus, and users have to click again to regain focus and type.
This PR fixes this issue and removes this defect.
Fixes #21999 
Screen recording - https://www.loom.com/share/697f689f85b7426d88032f6487a9f7d9
- Manual
- Cypress
=> fix: Maintain focus on editor when Escape is pressed with autocomplete menu open

app/client/cypress/integration/SanitySuite/Datasources/GoogleSheetsStub_spec.ts, app/server/appsmith-plugins/googleSheetsPlugin/src/main/resources/form.json
This PR fixes for google sheet datasource create:
- Remove asterics of scope
- Copy of the permissions drop down should be "Read" instead of "Read Files"
Fixes #22383 
Media
- Manual
=> fix: gsheet ui issues fixed

app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/JSONForm/JSONForm_FieldProperties_spec.js, app/client/src/widgets/JSONFormWidget/fields/MultiSelectField.tsx
When invalid `Options` is passed to a multiselect field in a JSONForm, the widget crashes.
Example of invalid `Options`
```js
{{ [ { label: "asd", value: "zxc"}, null ] }}
```
The second option is `null` which makes the whole `Options` property as invalid.
Fixes #20791
- Manual
- Cypress
> https://github.com/appsmithorg/TestSmith/issues/1466
=> fix: JSONForm multiselect field with invalid option crash

app/client/cypress/fixtures/testdata.json, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/TableV2/TableV2_Sorting_spec.js, app/client/cypress/support/widgetCommands.js, app/client/src/widgets/TableWidgetV2/widget/derived.js
Fixes #19928 
Steps to repro:
1. Add a custom column named `customColumn1` to a table.
2. Modify the computed value for it to `{{currentIndex}}`.
3. Ensure that sorting is working for the table using `customColumn1`.
4. Go to property pane settings for this column and rename it to `customColumn2` from its title in the property pane.
5. Ensure that sorting is working using `customColumn2`.
Actual Behavior:
Sorting isn't working using `customColumn2`.
Expected Behavior:
Sorting should work using `customColumn2`.
=> fix: Sorting by renamed custom column

app/client/src/pages/setup/DetailsForm.tsx, app/client/src/pages/setup/SetupForm.tsx
- Since telemetry and newsletters are by default disabled in airgap we don't need it for airgapped instances.
Fixes #22369 
Media
- Manual
=> fix: hide telemetry form for airgap instance

app/client/src/widgets/TableWidgetV2/component/Table.tsx, app/client/src/widgets/TableWidgetV2/widget/derived.js
This PR adds optional chaining while accessing the properties of `editableCell` object in the table widget.
Fixes #20789
Please refer to the [comment.](https://github.com/appsmithorg/appsmith/issues/20789#issuecomment-1515845278)
=> fix: null check before accessing editableCell property in table widget

app/client/cypress.json
Disabling hot reloading would disable running of cypress tests on its own whenever anything is changed in the current test case.
I think this might be helpful for scenarios when a developer is writing/completing their test case and don't intend to re-run the test until they have completed their code. This would prevent unnecessary test runs and keep the memory footprint low.
A lower foot print would help in reduced flakiness when an actual test run is required.
If a developer wants to re-run the test, they have to switch cypress app nonetheless, and can press the refresh button at that time.
Please suggest if this would appropriate as a team wide change.
=> Disable hot reloading of cypress tests

deploy/docker/scripts/supervisor_event_listener.py
Event Listener Python script fixes:
- Added exception handling in health check request
- Updated backend health check point to `http://localhost:8080/api/vi/health`
=> fix: Supervisord event listener health check exception Handling

app/server/appsmith-plugins/googleSheetsPlugin/src/main/resources/editor/fetch_many.json
In the google sheets query for operation `Fetch Many`-->`Sheet Rows`, the tooltip is as follows:
this example is incorrect, it should be `...Table1.pageSize`, and not just `pageSize`
Fixes #21384
- Manual
=> fix: tooltip in gsheets query pagination field

app/client/packages/design-system/theming/src/utils/TokensAccessor/LightModeTheme.ts
tl;dr No longer adding parasitic chroma in achromatic seeds, better middle in yellows and reds, non-muddy `active` derivatives.
Fixes #22512 
- Manual
=> chore: WDS color `bgAccentSubtle` light mode fixes

app/client/src/actions/evaluationActions.ts, app/client/src/sagas/FormEvaluationSaga.ts, app/client/src/sagas/QueryPaneSagas.ts, app/client/src/workers/Evaluation/formEval.ts, app/server/appsmith-plugins/googleSheetsPlugin/src/main/resources/editor/root.json
This PR fixes:
- When google sheet datasource is created with selected sheets scope, in this case we need to disable spreadsheet option in the entity dropdown of the query, so that user cannot delete/insert from selected sheets
Fixes #22152 
Media
- Manual
=> feat: disable spreadsheet entity in case of insert/delete one

app/server/appsmith-server/src/main/java/com/appsmith/server/domains/UserData.java, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/UserProfileDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/UserUpdateDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserServiceTest.java
Currently, there is no way for us to know any details about a user when they reach out to support via Intercom. Thus, we are not able to offer the right level of support to them basis their current plan.
The idea is to ask for consent to share user details with Appsmith before Intercom is enabled for a user, the basis which support can determine the right level of support.
This PR helps to store and retrieve the flag variable for a particular user which says whether the consent was given or not.
Fixes #22611
- Manual
- JUnit
=> feat: To store user's Intercom email share consent on backend

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration008CreateIndexDefaultDomainIdDefaultDomainTypeDropIndexDefaultWorkspaceId.java
> Create a new index on permission group with `defaultDomainId` + `defaultDomainType` + `deleted` +`deletedAt` in order to improve the performance of the queries which are used to find the permission groups using `defaultDomainId` and `defaultDomainType`. 
> Also, we are going to remove an already existing index: `permission_group_workspace_deleted_compound_index` which was used earlier, when we were still dependent on `defaultWorkspaceId`
Fixes #22674 
Media
> Tested locally by running the …
=> chore: create a new index on permission groups for defaultDomainId & defaultDomainType

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration008CreateIndexDefaultDomainIdDefaultDomainTypeDropIndexDefaultWorkspaceId.java
> Create a new index on permission group with `defaultDomainId` +
`defaultDomainType` + `deleted` +`deletedAt` in order to improve the performance of the queries which are used to find the permission groups using `defaultDomainId` and `defaultDomainType`.
> Also, we are going to remove an already existing index:
`permission_group_workspace_deleted_compound_index` which was used earlier, when we were still dependent on `defaultWorkspaceId`
Fixes #22674 
Media
> A video or a GIF is preferred. when using Loom, don’t embed because it
looks like it’s a GIF. instead, just link to the video
> Tested locally by running the …
=> hot-fix: add a new index for permission group for performance improvement

app/client/packages/design-system/theming/src/utils/ColorsAccessor/ColorsAccessor.ts, app/client/packages/design-system/theming/src/utils/TokensAccessor/LightModeTheme.ts
tl;dr Slightly darker canvas background for very light seeds. It is still perceptually light mode, but now `bgAccent` doesn't need to be dark/dirty to stay visible against app background.
Fixes #22568 
- Manual
=> chore: Refine bg and bgAccent (light mode)

app/client/cypress/integration/Regression_TestSuite/ServerSideTests/Datasources/Redis_Basic_Spec.ts
- This PR fixes the redis spec failures in CI. When HGet run on a Hash set in Redis DB - the results can be in any order & hence spec is failing in CI on multiple runs. Hence commenting the index check.
- Cypress CI runs
=> test: Cypress - Redis spec fix for CI runs

app/client/package.json, app/client/src/pages/Editor/FirstTimeUserOnboarding/Checklist.tsx, app/client/src/pages/UserProfile/UserProfileImagePicker.tsx, app/client/yarn.lock
- In an airgapped instance, the `No internet connection` message from uppy should be disabled.
Fixes #22366 
Media
- Manual
=> fix: disable uppy informer and hide welcome tour cta for airgap

app/client/cypress/integration/SanitySuite/Datasources/Airtable_Basic_Spec.ts
=> fix: Remove JSON.parse for accessing Airtable query result (#22711)

app/client/cypress/locators/apiWidgetslocator.json, app/client/src/pages/Editor/APIEditor/Pagination.tsx
REST API pagination tab has inconsistent casing for `URL` - it is `url` and `Url` in some places:
#19550 
Media
- Manual
=> fix: casing for url,Url to URL in restapi pagination tab

app/server/appsmith-plugins/firestorePlugin/src/main/resources/editor/addToCollection.json, app/server/appsmith-plugins/firestorePlugin/src/main/resources/editor/createDocument.json, app/server/appsmith-plugins/firestorePlugin/src/main/resources/editor/setDocument.json, app/server/appsmith-plugins/firestorePlugin/src/main/resources/editor/updateDocument.json
> Firestore plugin -> "Timestamp Path" field must not be required field (isRequired: false)
Closes #21180 
=> fix: [#21180] Firestore plugin -> "Timestamp Path" fix

app/client/cypress/integration/SanitySuite/Datasources/GoogleSheetsStub_spec.ts, app/server/appsmith-plugins/googleSheetsPlugin/src/main/resources/form.json
- The following PR changes the label values seen by the user in the scope selection drop-down menu while creating a Google Sheet data source.
- The changes accommodate for one specific scope that was present in the previous implementation and is not present now i.e read/write without delete permission for which a new scope has been added.
- Also with these changes the migration for old data sources is not required since we have added all the previously used scopes here.
- Figma Link: https://www.figma.com/file/TcFhqEbAc8ymHTRF5wR1qv/Limited-GSheet-Access?node-id=506-32761
- Notion link for migration: https://www.notion.so/appsmith/Google-Sheet-Migration-ab7bbfbdae1f40189a957b6ae5374145
Fixes #22327 
- This change requires a …
=> fix: Google Sheets Scope Label Change

app/client/packages/design-system/headless/package.json, app/client/packages/design-system/theming/package.json, app/client/packages/design-system/widgets/package.json, app/client/packages/storybook/package.json, app/client/yarn.lock
We are for using the same version in packages as the main app. [This code](https://github.com/appsmithorg/appsmith/blob/release/app/client/packages/design-system/theming/package.json#L12-L19) should says yarn take the version from the main package.json. But for some reason, yarn resolves it in his own way, so we decided to delete these lines and leave only information about React only in `peerDependencies`.
- Manual
=> fix: remove unnecessary packages dependency settings

app/client/src/ce/sagas/ApplicationSagas.tsx
Making sure that whenever a user creates a new app, we will have the entity explorer will uncollapsed Widgets, Query Datasource sections so that the user can find the entities they create easily
Fixes #21893
Media
https://user-images.githubusercontent.com/12022471/233955568-52b0e645-86b8-4058-adb3-48c9f4a7b501.mov
- Manual
- Cypress
=> feat: Unfurl all Entity Explorer sections in new app

app/client/src/entities/AppTheming/index.ts, app/client/src/widgets/InputWidget/index.ts, app/client/src/widgets/InputWidget/widget/index.tsx, app/client/src/widgets/JSONFormWidget/index.ts, app/client/src/widgets/JSONFormWidget/widget/index.tsx, app/client/src/widgets/TableWidgetV2/index.ts, app/client/src/widgets/TableWidgetV2/widget/index.tsx
Added setter configs to JsonForm, Input and Table widgets to be used to build the setters in evaluations
Fixes #22701  
=> feat: Added setter configs to JsonForm, Input and Table widgets

app/client/packages/design-system/theming/src/utils/TokensAccessor/LightModeTheme.ts
tl;dr Gradated hover and active manipulation (more for darker colors, less for lighter), inverted rules for very light seeds
Fixes #22713
https://user-images.githubusercontent.com/80973/234889970-05792d7c-e5c7-49b0-80a2-6c9b31d2751d.mov
- Manual
=> chore: WDS Color `bgAccentHover` and `bgAccentActive` (light mode)

app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Autocomplete/PropertyPaneSuggestion_spec.ts, app/client/cypress/package.json, app/client/cypress/support/index.js, app/client/package.json, app/client/src/components/editorComponents/CodeEditor/EditorConfig.ts, app/client/yarn.lock
This adds the ability to select an option from the autocomplete suggestions list using the `Tab` key while writing code. Earlier, users could use only the `Enter` key to do so. All code editors support `Tab` for autocomplete.
Fixes #20448 
- Cypress
[Test Plan](https://github.com/appsmithorg/TestSmith/issues/2377)
=> feat: Add support for tab in autocompletion

app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Autocomplete/Autocomplete_Spec.ts, app/client/cypress/support/Pages/PropertyPane.ts, app/client/src/utils/autocomplete/CodemirrorTernService.ts
When using autocomplete suggestion, earlier on selecting a function the cursor was placed at the end of the parenthesis forcing the user to press one more key (left arrow) before filling the arguments. Now the cursor is placed right between the parenthesis.
Fixes #20449 
- Cypress
=> fix: cursor position not between parenthesis for function autocomplete

app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/Input/Inputv2_spec.js, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/JSONForm/JSONForm_FieldProperties_spec.js, app/client/src/widgets/BaseInputWidget/component/index.tsx, app/client/src/widgets/BaseInputWidget/widget/index.tsx, app/client/src/widgets/InputWidgetV2/component/index.tsx, app/client/src/widgets/InputWidgetV2/widget/Utilities.ts, app/client/src/widgets/InputWidgetV2/widget/index.tsx, app/client/src/widgets/JSONFormWidget/constants.ts, app/client/src/widgets/JSONFormWidget/fields/BaseInputField.tsx, app/client/src/widgets/JSONFormWidget/widget/propertyConfig/helper.ts, app/client/src/widgets/JSONFormWidget/widget/propertyConfig/properties/common.ts
This PR brings in the autofill toggle when the user selects either email or password. It is always defaulted to the enabled state, the user need to toggle it off to get the text widget to have autocomplete attribute set to "off".
Fixes #22566 
- Manual
- Cypress
=> feat: autocomplete feature for email and password

app/client/src/widgets/MetaHOC.tsx
Fixes #22527 
Based on debugging the performance logs, it seems like for now that the console log on every character type is causing a lag in the performance.
This becomes more accentuated for a list widget. Commenting out the logging for now since the issue is marked critical
In the meanwhile, @SatishGandham will help to triage the further cause of this issue.
=> fix: Remove console log on MetaWidgetUpdate

app/client/src/ce/pages/Applications/index.tsx
This PR fixes below points
- Workspace menu not able to close when confirmation text is present
- Left pane text ellipsis causing text break into two lines.
- Manual
- Jest
- Cypress
=> fix: Homepage menu and listItem bug fixes

deploy/docker/entrypoint.sh
Because tracing is turned on in the `entrypoint.sh`, everything we source also log all names and values, including the `docker.env` file. This means all env values are printed to the logs.
This PR disables the tracing to fix this. It was enabled originally for improved logging information for some of the issues we were facing at the time, but if we still need such logging information, we need to log those explicitly with `echo`, instead of using `xtrace`.
=> fix: Don't log all env variables when starting up

app/client/src/utils/helpers.tsx
Fixes the scenario where the selected widget was not getting scrolled to on page change. When the selected widget was a container, it was not getting scrolled. This will update the scenarios where the page will scroll to the selected "container" widget
> Fix the bug where the selected container widget was not in view
Fixes #22099
Media
https://user-images.githubusercontent.com/12022471/234842826-bae5388f-7813-441e-814b-7669179e211d.mov
- Manual
=> fix: Scroll to selected widget failing when it's a container

.github/workflows/CypressAddKnownfailedtests.yml
"github.event.issue.title" is potentially untrusted. avoid using it directly in inline scripts. instead, pass it through an environment variable. see https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions for more details.
=> fix: Security Vulnerability in GitHub Workflows

app/client/src/utils/hooks/useBrandingTheme.ts
- Wrap favicon url with getAssetUrl function.
Fixes #22903
- Manual
=> fix: branding favicon url airgapped

app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/TableV2/Add_new_row_spec.js, app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Workspace/ShareAppTests_spec.js, app/client/cypress/support/commands.js, app/client/cypress/support/index.js
Fixes #22878
This pr adds a flag called 'rapidMode' in cypress index file.
```
cypress/support/index.js
let rapidMode = {
enabled: false, // Set it to true to skip app creation during a test re-run
appName: "4a9b62a0", // Replace it with your app name
pageName: "page1", // Replace it with the page name
pageID: "644f8d6e21506c33a366854b", // Replace it with pageID
url: function () {
return `app/${this.appName}/${this.pageName}-${this.pageID}/edit`;
},
};
```
When rapid mode is enabled, the cypress test will
1. Skip relogin if the test user is already logged in.
2. Skip creation of a new app and use a previously created app, passed as param.
The flag needs to be disabled when the code needs to be merged to release, and is meant for debugging/testing while writing tests on local development …
=> chore: Add rapid mode to skip new app creation in cypress test

app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/utils/SheetsUtil.java, app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/SheetsUtilTest.java
This PR fixes:
- In gsheet datasource query, the spreadsheet list was not getting fetched. This Pr fixes the issue with trigger API, so that list of spreadsheets can be fetched successfully.
Fixes #22890 
Media
- Manual
- JUnit
=> fix: gsheet trigger 500 issue fixed

app/client/src/utils/hooks/useBrandingTheme.ts
- Favicon was not showing up because there was a typo.
Fixes #22895 
Media
- Manual
- Cypress
=> fix: fix favicon not showing up on release

app/client/src/utils/autoLayout/positionUtils.test.ts, app/client/src/utils/autoLayout/positionUtils.ts
Issue: Fill widgets are not assigned 64 columns on mobile viewport if placed in the same flex layer.
Fix: Add a check for mobile viewport to override the minWidth logic.
Fixes # ([issue](https://github.com/appsmithorg/appsmith/issues/22917))
- Manual
- Jest
=> fix: assign 100% width to fill widgets on mobile viewport

app/server/envs/dev.env.example, contributions/ServerSetup.md
Documentation update for server side set up, and a change to default value in env variables for Mongo to comply with the one we are using in the set up docs, to allow for a quick start and lower chance of failure.
=> fix: Updated server set up docs to lower confusion from logs

app/client/src/constants/Datasource.ts, app/client/src/pages/Editor/SaaSEditor/GoogleSheetFilePicker.tsx, app/client/src/sagas/DatasourcesSagas.ts
This PR fixes a bug:
- Google sheet file picker is not visible in firefox browser.
Fixes #22753 
Media
- Manual
=> fix: firefox file picker not showing up issue fixed

app/client/src/widgets/TableWidgetV2/widget/propertyUtils.test.ts, app/client/src/widgets/TableWidgetV2/widget/propertyUtils.ts
Input validation object signature was incorrect for totalrecordscount, so that has caused the error not to show up. Have corrected in this PR
Fixes #22550 
- Manual
- Jest
> https://github.com/appsmithorg/TestSmith/issues/2371
=> fix: no input validation error in totalRecordsCount

.github/workflows/build-docker-image.yml
We're setting up Java, but aren't using it in this workflow. This PR removes it.
=> ci: Remove unused java setup step

app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/PageNameIdDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewPageServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/NewPageServiceTest.java
Need to add userPermissions in response to newPages Api inside pages array: These are the APIs
/v1/pages?applicationId={applicationId}&mode={mode} - Get method
/v1/pages/application/:applicationId - Get method
Added userPermissions in the response of the above APIs.
These are the changes done in the following file to add userPermission in the newPage Api response
1. New FieldName added which is used in query
2. userPermission attribute added in PageNameIdDTO
3. userPermission coming from db set to response in NewPageServiceCEImpl
4. Test cases updated
Fix #21887
1. Manual testing through postman and UI
2. Junit
=> fix: added userPermissions in newPage Api

app/client/src/reducers/entityReducers/actionsReducer.tsx
In this PR `ActionReducer` code was refactored to use `createImmerReducer` instead of `createReducer`, which helped in solving the gsheet error of spreadsheet name mismatch and api url field update failing autosave by updating the redux
store values properly.
When a query that was used to create a spreadsheet is changed, the query's meta values are not updated, and the server encounters the spreadsheet name mismatch error. This was taking place because the server was keeping outdated values due to the redux store's failure to update with the latest values. It was happening as a result of an outdated reducer implementation in ActionReducer that didn't use createImmerReducer (using package immer). 
This also fixes the issue with the api url field failing autosaving with updated values. …
=> fix: action reducers were using old implementation of updating state

app/client/cypress/integration/Regression_TestSuite/ClientSideTests/Widgets/TableV2/TableV2_PropertyPane_spec.js, app/client/src/ce/constants/messages.ts, app/client/src/components/propertyControls/TableInlineEditValidPropertyControl.tsx, app/client/src/components/propertyControls/TableInlineEditValidationControl.tsx
Fixes #20235
This pull requests adds a prompt message to min/max/regex/errorMessage/required input validation fields. Also fixed css styling on the prompt message for these fields as well as additionally on Valid/ComputedValue fields.
The design shared by @vasanthappsmith is attached below : 
- [x ] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] I have made corresponding changes to the documentation
- [ x] My changes generate no new warnings
- [ x] I have added tests that prove my fix is effective or that my feature works
- [ x] New and existing unit tests pass locally with my changes
=> fix: Add message prompt on min field

app/client/src/pages/Editor/Explorer/Datasources/DatasourceEntity.tsx, app/client/src/pages/Editor/IntegrationEditor/DatasourceCard.tsx, app/client/src/pages/Editor/SaaSEditor/DatasourceForm.tsx
This PR fixes 
1. Click on gsheet datasource from entity explorer was landing onto edit instead of view mode
2. Edit button on active datasource page and on view mode page of gsheet datasource wasn't working
3. Even after successful authorization of gsheet datasource, it was showing `Authorisation failed, to continue using this data source authorize now.` thereby restricting users to create a query.
Fixes #23093
Fixes #23104
Fixes #20343
>
> …
=> fix: edit button fixes, authorisation wrong message fixed

app/client/src/pages/Editor/EditorAppName/index.tsx, app/client/src/pages/Editor/EditorHeader.tsx
Fixes tooltip showing up when the dropdown is open. Updates the hover color for the  app name.
Fixes https://www.notion.so/appsmith/Hover-state-and-tooltip-are-missing-over-renaming-the-app-677d4f298e67418dacd092bc4176fd33
Media
https://user-images.githubusercontent.com/67054171/236460058-12074c76-f6dc-42cf-8b40-b737ca2e8eed.mov
- Manual
- Jest
- Cypress
> Link issues raised during DP testing for better visiblity and …
=> fix: editor app name hover state

app/client/src/workers/Evaluation/fns/actionFns.ts, app/client/src/workers/Evaluation/fns/index.ts, app/client/src/workers/Evaluation/getEntityForContext.ts
Set the `api.data` as soon as promise is resolved to avoid race condition.
NOTE: We have added a logic to set the global context similar to storeValue as a temporary fix. 
Fixes #23052
=> fix: set Api.data on promise resolution

app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java, app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/utils/MySqlErrorUtils.java, app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java
- Changed the error message returned in case of an invalid username/password for MySQL.
- Removed the exact exception from the error message returned to the user.
Fixes #13977 
- Manual
- JUnit
=> fix: MySQL Error Message Fix

app/server/appsmith-server/src/main/resources/features/init-flags.yml
Bug in the way ME feature flags were defined.
=> fix: Spaces are disallowed when defining ff emails

.github/workflows/on-demand-build-docker-image-deploy-preview.yml, .github/workflows/test-build-docker-image.yml, .github/workflows/upgrade-appsmith-tests.yml
This PR fixes artifact download paths that were accidentally left incorrect. 
Related commit: https://github.com/appsmithorg/appsmith/pull/21667/commits/1d40e98a3dfa9267a8bdcccc897de39be2d7bf4a
>
>
>
>
>
=> ci: correct the artifact download paths

app/client/src/widgets/TableWidgetV2/component/cellComponents/IconButtonCell.tsx
This PR passes a prop named: `hasOnClickAction` as `true` to the `StyledButton` of the `IconButtonCell` component of the table widget v2. 
**Root cause:** This happens so because inside the IconButtonWidget’s component we conditionally showcase the background color. If `hasOnClickAction` exists then we show change in BG color on hover. 
**************Reason:************** People use icon button widget as icon widget as well. If there's no onclick then people just want to use the icon as a way to display something
**********Proposed solution:********** Always pass the `hasOnClickAction` as true to the IconButtonWidget’s component via table cell
Fixes #17775 
> …
=> fix: enable change in background color on hover for Icon Button cell in Table widget V2

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserServiceTest.java
This PR makes the Intercom consent flag true always for the cloud-hosted version.
Fixes #23214
>
=> chore: Intercom consent is defaulted to true on cloud hosting

app/client/packages/design-system/theming/src/utils/TokensAccessor/DarkModeTheme.ts, app/client/packages/design-system/theming/src/utils/TokensAccessor/LightModeTheme.ts, app/client/packages/design-system/widgets/src/components/Spinner/index.styled.tsx
tl;dr Fixed APCA contrast checks and logic for `bdNeutral`, fixed `bdAccent` check too (see also #23218 for more stuff to fix). Adjusted gradations of hover for the color to make it visible in both modes.
Fixes #22823   
New on the left, current on the right (using the latest DP instead of release deploy, since it's failing at the moment of creation of this PR)
https://github.com/appsmithorg/appsmith/assets/80973/cfcb7aa7-17cd-454d-a452-779efba20158
- Manual
=> chore: WDS colors `bdNeutral` and `bdNeutralHover`

app/client/src/ce/pages/workspace/Members.tsx, app/client/src/ce/pages/workspace/WorkspaceInviteUsersForm.tsx, app/client/src/pages/Applications/ApplicationCard.tsx, app/client/src/pages/Applications/ApplicationMenu.css, app/client/src/pages/workspace/settings.tsx
Updating height for Select and Menu components on home page & members page
Fixes https://www.notion.so/appsmith/Unnecessary-scroll-in-drop-downs-menus-9ab1171baab54e6dbae70d617e96449b?pvs=4
=> fix: Updating height for Select and Menu components on home page & members page

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
Update error message for git import for the Auth issues. Using the standard error message of connect flow.
=> chore: use the standard error message for auth fails in git import

app/server/appsmith-plugins/snowflakePlugin/src/main/java/com/external/plugins/SnowflakePlugin.java, app/server/appsmith-plugins/snowflakePlugin/src/test/java/com/external/plugins/SnowflakePluginTest.java
- Set a flag called InitializationFailTimeout to -1 to create the connection pool asynchronously.
- Set the **connectionTimeout** value to timeout to handle any issue with the connection as the pool is getting created asynchronously now.
- Changed the error message returned to the user for an invalid Snowflake URL.
Fixes #16140 
Fixes #22035 
- Manual
- Junit
=> fix: Snowflake error msg fix on test datasource timeout

app/client/src/entities/DataTree/dataTreeWidget.ts, app/client/src/utils/WidgetFactory.tsx, app/client/src/utils/WidgetRegisterHelpers.tsx, app/client/src/widgets/constants.ts
This PR adds code to generate setter config inside the configTree from the static widget setter config. 
Fixes https://github.com/appsmithorg/appsmith/issues/22820
- Manual
- Jest
- Cypress
=> feat: Generate setter config

app/client/src/sagas/DatasourcesSagas.ts
An undefined value in the updateDraftsagas is causing the app to crash. This PR prevents that from happening.
Fixes #22947
>
>
>
>
>
>
>
=> fix: Fix undefined value in updatedraftsagas

app/client/start-https.sh
This is the same fix from https://github.com/appsmithorg/appsmith/pull/6981. Unfortunately, looks like we've missed this and has caused wasted time again.
=> chore: Fail when backend has a trailing slash

app/client/cypress/integration/Regression_TestSuite/ClientSideTests/OtherUIFeatures/Omnibar_spec.js
This change removes the index search in omnibar tests to reduce flakiness
=> chore: Remove index search in omnibar tests

app/client/src/pages/Editor/FirstTimeUserOnboarding/IntroductionModal.tsx
Preventing modal close action on clicking outside of the modal
Fixes https://www.notion.so/appsmith/Welcome-modal-should-not-be-dismissed-on-losing-focus-3620f488f27743bba9bbb54dc4c0bb85?pvs=4
=> fix: Preventing modal close action on clicking outside of the modal

app/client/cypress/e2e/Regression_TestSuite/ClientSideTests/Templates/ForkTemplateToGitConnectedApp.js
Skipping this test case, until we have unique test id for loader while switching branch from @albinAppsmith , currently it fails because it tries to assert loader not to be present in git sync modal after creating branch, but since saving page loader exists it becomes flaky as both have same class name.
=> test: skip forkTemplateToGitConnectedApp_Spec 

.github/workflows/ci-test-limited.yml
- This PR reduces the jobs used count to minimal in ci-limited-tests.yml for safer side
- Folks using it can add/remove jobs further as needed in their PR along with updating limites-tests.txt present in cypress folder for running limited Cypress tests
=> ci: Reducing jobs count in ci-test-limited.yml

app/client/src/utils/configTree.ts, app/client/src/workers/Evaluation/evalTreeWithChanges.ts, app/client/src/workers/common/DataTreeEvaluator/index.ts
This PR prevents evalTree and configTree from being undefined values.
Fixes #23283 
Nil
>
>
>
>
>
=> fix: Prevent evalTree and configTree from being undefined

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/UserSignupCEImpl.java
> The code changes here move the analytics event to a separate thread which are sent while creating a super user. This was causing a performance, because of an external call which happens from Appsmith. Moving these 2 events to a separate thread will not have any impact on the Super user creation flow.
Fixes https://github.com/appsmithorg/appsmith/issues/22147
>
> This will be tested as part of Cypress test cases, where we have seen reproductions of the timeout.
>
>
>
>
=> fix: send analytics event diff thread super user creation

.github/workflows/github-release.yml
Add yarn install step to github-release-workflow as the one in rts/build.sh is not running for some reason.
https://github.com/appsmithorg/appsmith/actions/runs/5042500455/jobs/9044379038
=> ci:  Add yarn install step to github-release-workflow

app/client/cypress/e2e/Regression/ClientSide/DynamicHeight/Multiple_Container_spec.js
Fixed Multiple-Container spec under Dynamic Heights.
- After Adding a new option to Checkbox widget the new option was getting added in the same line so the height remained same
- Now we are adding another option to validate auto height feature across widgets used in testing within the spec
=> test: updated the container spec

.github/workflows/github-release.yml
Cherry picking workflow to allow github release workflow to go through
=> ci:  Add yarn install step to github-release-workflow (#23593)

app/client/cypress/e2e/Regression/ClientSide/Widgets/Sliders/CategroySlider_spec.ts, app/client/cypress/fixtures/categorySliderWidgetDsl.json, app/client/src/widgets/CategorySliderWidget/validations.ts
Fixes #23228
Steps to Repro:
1. Dnd Category Slider Widget
2. Toggle JS Mode in options field
3. Enter `[[]]`
4. Observe the crash
Expected behavior : The widget shouldn't crash
=> fix: Fix crash on passing invalid mark option to category slider widget

app/client/craco.dev.config.js
Fixes #23631
This PR disables the react overlay seen during development.
This improves developer efficiency while writing code and running tests as the developer will not have to manually close the overlay.
The prettier warnings will show up nonetheless because of pre-commit lint hook, so I believe that this change shouldn't affect the processes around code quality
=> chore : disable react overlay for warnings/error in dev mode

app/client/src/pages/Editor/gitSync/DisconnectGitModal.tsx
Adds a back button to git revoke access modal. Clicking on the back button takes user back to the previous modal. This PR is in accordance with ADS v2
Fixes #23032 
Before
After
Manually tested
=> fix: adding a back button in git revert modal

app/client/craco.build.config.js, app/client/src/serviceWorker.js
This PR prevents the service worker from caching the icons.
For the background on why we moved from `.filter()` to `exclude: []`, see https://github.com/appsmithorg/appsmith/pull/21996#discussion_r1156075049 (that PR was reverted later).
>
>
>
>
>
>
=> fix: don’t cache icons by the service worker

app/client/packages/design-system/theming/src/utils/TokensAccessor/DarkModeTheme.ts, app/client/packages/design-system/theming/src/utils/TokensAccessor/LightModeTheme.ts
tl;dr Fixed APCA contrast checks for both light and dark modes (detailed info in the ticket). Refined how we pick shade or tint for `fgOnAccent`.
Fixes #23218    
- Manual
=> fix: WDC color APCA checks

app/client/src/pages/Editor/DataSourceEditor/index.tsx, app/client/src/pages/Editor/SaaSEditor/DatasourceForm.tsx, app/client/src/pages/common/datasourceAuth/AuthMessage.tsx
Fixes a bug raised for the reconnect modal of g sheets. 
Fixes #
=> fix: reconnect modal and viewmode of g sheets plugin

app/client/cypress/integration/Regression_TestSuite/ClientSideTests/OneClickBinding/TableWidget/mongoDB_spec.ts
Added test cases to test one click binding for a MongoDB datasource.
Fixes #22993
>
>
>
>
>
>
=> chore: [One-click binding] mongodb testcases cypress

.github/workflows/build-client-server.yml, .github/workflows/ci-test-limited.yml, app/client/cypress/e2e/Regression/ClientSide/Git/GitImport/GitImport_spec.js, app/client/cypress/e2e/Regression/ServerSide/JsFunctionExecution/JSFunctionExecution_spec.ts, app/client/cypress/e2e/Regression/ServerSide/OnLoadTests/JSOnLoad1_Spec.ts, app/client/cypress/e2e/Regression/ServerSide/OnLoadTests/JSOnLoad2_Spec.ts, app/client/cypress/e2e/Regression/ServerSide/OnLoadTests/JsOnLoad3_Spec.ts, app/client/cypress/limited-tests.txt, app/client/cypress/support/Pages/JSEditor.ts
- This PR handles the proper click of No & Yes in the confirmation modals during a query/js object run
- Also updated the ci-test-limited.yml for Installing dependencies from right path
- GitImport - 5th case - flakyfix
- Unskips the JsOnload3 spec
- JSFunctionExecution_spec.ts - flaky fix
>
=> test: Cypress | Handling confirmation dialogs

app/client/src/widgets/InputWidgetV2/widget/derived.js, app/client/src/widgets/InputWidgetV2/widget/derived.test.ts
Fixes #23576
Steps to repro:
QA Steps:
1. Use an email with four letter extension : .info, .tech
2. Check case insensitive extension validations. Both .info and .INFO should be valid email addresses
=> fix: Add email validation for 4 letter email domain extension names

app/client/packages/design-system/theming/src/utils/TokensAccessor/LightModeTheme.ts
tl;dr Preserving more color in fgAccent when the seed doesn't pass the contrast check, more saturated and pure color for better harmony. Also fixed `fg` that missed a return for achromatic seeds rule.
Fixes #22699 
https://github.com/appsmithorg/appsmith/assets/80973/e4731b10-fa4c-45bb-a0e1-9591a9bbce2a
- Manual
=> chore: Refined `fgAccent` (light mode), fixed missing return in `fg` (light mode)

app/client/cypress/support/commands.js
Fix Airgapped cypress tests failing due to superuser expecting anonymousdata and newsletter to be true.
>
>
>
>
>
>
>
>
=> ci: add failure cases for airgapped superuser creation cypress check

app/client/src/ee/api/ApiUtils.ts, app/client/src/pages/Editor/DataSourceEditor/DSFormHeader.tsx, app/client/src/pages/Editor/DataSourceEditor/index.tsx, app/client/src/pages/Editor/SaaSEditor/DatasourceForm.tsx, app/client/src/pages/common/datasourceAuth/index.tsx, app/client/src/reducers/entityReducers/datasourceReducer.ts
Fixes bug of gsheets not going into edit mode
Fixes #23775
>
>
>
>
>
>
>
>
=> fix: gsheets edit mode switch

app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Application.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitFileUtils.java
The Git Repo only includes the Edit Mode resources for the Application.json as right after committing we deploy the application. This change set removes Publish Mode App Settings and Custom JS Libs from the Git commit.
Fixes #22785
=> chore: Exclude published mode resources for navigation settings and custom JS libraries

app/client/src/entities/DependencyMap/__tests__/index.test.ts, app/client/src/entities/DependencyMap/index.ts
This PR Introduces an extensible, unit-tested relationship graph entity.
Fixes #23446
>
>
>
>
>
=> chore: Create graph entity

app/client/packages/design-system/theming/src/utils/TokensAccessor/DarkModeTheme.ts, app/client/packages/design-system/theming/src/utils/TokensAccessor/LightModeTheme.ts
tl;dr Smoother fallbacks when we're failing APCA contrast check as a border for the seed (more chroma, closer to the neutral lightness)
Fixes #22630   
https://github.com/appsmithorg/appsmith/assets/80973/b13122c8-9159-4337-ae77-4dfa2df2151d
- Manual
=> chore: refine WDS color `bdAccent`

app/client/cypress/locators/welcomePage.json, app/client/cypress/support/commands.js, app/client/src/pages/setup/DetailsForm.tsx
Split button into 2 button components to fix issue in firefox.
Slack Thread: https://theappsmith.slack.com/archives/CGBPVEJ5C/p1685460441276709
Fixes #23902
>
>
>
>
>
>
>
>
=> fix: split button into 2 button components to fix issue in firefox.

deploy/docker/scripts/run-nginx.sh
We replace env variables in `index.html`, `view.html` and `edit.html`, just before start NGINX. But the `.gz` versions of these files don't have these changes applied to them. This PR gzips those HTML files again, after the substitutions are applied.
From https://github.com/appsmithorg/appsmith/pull/23539#issuecomment-1554509537.
=> fix: Re-gzip html files after env variables substitution

app/client/public/index.html
In earlier PR #23882, along with moving the env variables before the script injection, we also moved zippy setup.
Moving it back below the script injection now.
=> chore: Move zippy setup after the script injection.

app/client/cypress/e2e/Regression/ServerSide/GenerateCRUD/MySQL1_Spec.ts, app/client/cypress/e2e/Regression/ServerSide/GenerateCRUD/Postgres1_Spec.ts, app/client/cypress/e2e/Regression/ServerSide/OnLoadTests/JSOnLoad2_Spec.ts, app/client/cypress/e2e/Regression/ServerSide/QueryPane/Mongo_Spec.ts, app/client/cypress/support/Pages/HomePage.ts
- Toast validation for JSOnLoad2_Spec.ts that is failing in CI runs
- GenerateCRUD/MySQL1_Spec.ts
- GenerateCRUD/Postgres1_Spec.ts
- GenerateCRUD/Mongo_Spec.ts
=> test: Cypress | StartPage - GenerateApp flaky fix

app/client/cypress/e2e/Regression/ClientSide/PeekOverlay/PeekOverlay_Spec.ts, app/client/cypress/fixtures/datasources.json, app/client/src/components/editorComponents/CodeEditor/index.tsx, app/client/src/constants/WidgetValidation.ts, app/client/src/selectors/dataTreeSelectors.ts
Don't show peek overlay on undefined variables.
Also filter internal property `pageList`.
Fixes #23817
https://www.loom.com/share/751ce60facdb446d9c1bb4208dc697c4
>
>
>
Tested random variables and strings for negative check
>
>
none
>
>
>
=> fix: peeking on undefined properties

app/client/cypress/e2e/Regression/ServerSide/ApiTests/CurlImportFlow_spec.js, app/client/cypress/support/Pages/ApiPage.ts, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CurlImporterServiceCEImpl.java
This PR fixes:
- When we import api request using curl and if api request does not have any header values, the imported request looks like below, empty key value headers are missing.
Fixes #19214 
>
>
>
>
>
>
>
>
>
>
>
>
> Link issues raised during DP testing for better visiblity and tracking (copy link from …
=> fix: curl import empty headers issue fixed

app/client/src/utils/hooks/useWidgetFocus/useWidgetFocus.tsx
The useWidgetFocus is failing in autoLayoutMode. The hook was meant for absolute positioning mode, not for autolayout where everything is positioned relatively.
Fixes #23880
>
- Bug fix 
>
>
>
=> fix: Cannot read properties of undefined (reading 'matches') 

app/client/cypress/e2e/Regression/ClientSide/Autocomplete/Autocomplete_Spec.ts, app/client/src/ce/utils/autocomplete/EntityDefinitions.ts, app/client/src/widgets/MultiSelectTreeWidget/widget/index.tsx, app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
Added "children" to autocomplete list for multiTree and singleTree widgets
Fixes #23641
>
>
>
>
>
>
>
>
>
>
>
>
>
=> fix: Added "children" to autocomplete list for multiTree and singleTree widgets

app/client/cypress/e2e/Regression/ClientSide/Autocomplete/Autocomplete_JS_spec.ts, app/client/src/components/editorComponents/CodeEditor/index.tsx
PR to fix autocomplete trigger
- Disables autocomplete trigger when ctrl/meta/alt is pressed except for (ctrl/meta)+space.
- Disable autocomplete inside strings and comments
Fixes #15429
>
>
- Keyboard shortcut check for autocomplete
- Copy paste action-based check
- autocomplete suggestions inside strings and comments
https://github.com/appsmithorg/appsmith/pull/24025#issuecomment-1577062645
>
>
>
=> fix: Autocomplete trigger changes

app/client/.eslintrc.js, app/client/cypress/.eslintrc.json
Dangling it.only tests skips other tests in the file and reduces our test coverage.
Added rule in .eslintrc to detect it.only calls in test files.
Cypress tests are named as `*_spec.js`, `*_Spec.js`, `*_spec.ts` and `*_Spec.ts`, whereas other tests follow the `*.test.js|ts|jsx` convention. So, I added this rule differently for Cypress and Default ESLint configuration.
Fixes #23708
>
Test Cases:
- Cypress: Button_Text_WithRecaptcha_spec.js contains it.only test, which starts getting detected by ESLint after this change.
- Default: Randomly picked files (which has *.test.js, *.test.ts, or *.test.tsx extensions) and  changed some it tests to it.only tests. All these cases where detected by ESLint after this change.
> …
=> chore: Linter check for dangling it.only tests

app/client/.eslintrc.js, app/client/cypress/.eslintrc.json
Reverts appsmithorg/appsmith#23991
Reverting because lint check is failing in our test suite. Will raise another PR along with lint check passing
=> Revert "chore: Linter check for dangling it.only tests"

app/client/src/components/editorComponents/ActionExecutionInProgressView.tsx
When action execution is triggered, we show no signs or indications of the action running in other parts of the page except for the run button, This PR introduces a spinner in the ResponseView for both APIs and Queries.
Fixes #23956 
>
>
>
>
>
>
>
>
>
>
>
=> feat: add loading spinner for action execution

app/client/src/pages/Editor/GeneratePage/components/DataSourceOption.tsx
Fixes the connect new data source button height issue in the generate page form.
Fixes https://github.com/appsmithorg/appsmith/issues/24167
>
>
>
>
>
>
>
>
=> fix: connect datasource size issue in the generate page form

deploy/docker/entrypoint.sh
Fixes: [24013](https://github.com/appsmithorg/appsmith/issues/24013)
The issue started with the introduction of adding of startup-events. Because of the ipv6 header
```
server {
listen 80 default_server;
listen [::]:80 default_server;
}
```
present in the 
`/etc/nginx/sites-enabled/default` and calling nginx [here](https://github.com/appsmithorg/appsmith/blob/release/deploy/docker/entrypoint.sh#L392). 
With this change we are removing ```listen [::]:80 default_server;``` from the file before starting nginx.
=> fix: ipv6 nginx startup error

app/client/cypress/support/widgetCommands.js
Fixes test flakiness with mongo_db spec.
>
>
>
>
>
>
>
=> chore: reduction in flakines

app/client/src/components/editorComponents/CodeEditor/index.tsx
When a user navigates between SQL queries the AI window persists causing Accept/Reject to overwrite code in intended places. This PR fixes it by force closing AI window, when dataTreePath passed to code editor changes
>
>
>
>
>
>
>
>
>
=> fix: close AI window on navigating between SQL queries

app/client/packages/design-system/theming/src/color/DarkModeTheme.ts
tl;dr Changed from naive `lighten` and `darken` to a proper color-agnostic algos
Fixes #23870 
https://github.com/appsmithorg/appsmith/assets/80973/640dfe12-2696-4b53-a06b-71ac19648e88
- Manual
=> fix: WDS color `bgAccentSubtle` (dark mode)

app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/PropertyControl_spec.ts, app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/TableWidget/mongoDB_spec.ts, app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/TableWidget/postgres_spec.ts
**Skipped below flaky tests to unblock CI**
- OneClickBinding/PropertyControl_spec.ts
- OneClickBinding/TableWidget/mongoDB_spec.ts
- OneClickBinding/TableWidget/postgres_spec.ts
=> test: Cypress - Skipping tests to unblock CI

app/client/.eslintrc.js, app/client/src/ee/.eslintrc
Overriding the import @appsmith eslint rule on EE folder
Fixes [#24183](https://github.com/appsmithorg/appsmith/issues/24183)
=> chore: Overriding the import @appsmith eslint rule on EE folder

deploy/docker/entrypoint.sh
Fixes: [24013](https://github.com/appsmithorg/appsmith/issues/24013)
The issue started with the introduction of adding of startup-events.
Because of the ipv6 header
```
server {
listen 80 default_server;
listen [::]:80 default_server;
}
```
present in the 
`/etc/nginx/sites-enabled/default` and calling nginx
[here](https://github.com/appsmithorg/appsmith/blob/release/deploy/docker/entrypoint.sh#L392).
With this change we are removing ```listen [::]:80 default_server;```
from the file before starting nginx.
=> chore: fix ipv6 nginx startup error

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration013UnsetEncryptionVersion2Fields.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration110UnsetEncryptionVersion2Fields.java
> Unsetting auth fields in datasource docs to avoid decryption failure happening on update to appsmith-ee v1.9.20.5
Fixes #24267
>
>
>
> Test product sanity on a sample db
=> fix: migration for encryption

app/client/src/ce/sagas/ActionExecution/ActionExecutionSagas.ts, app/client/src/constants/AppsmithActionConstants/ActionConstants.tsx, app/client/src/sagas/EvalWorkerActionSagas.ts, app/client/src/sagas/EvaluationsSaga.ts, app/client/src/workers/Evaluation/fns/utils/ExecutionMetaData.ts, app/client/src/workers/Evaluation/fns/utils/TriggerEmitter.ts, app/client/src/workers/Evaluation/fns/utils/jsObjectFnFactory.ts
This PR introduces logging of js function execution
Fixes #23995 
>
>
>
>
>
>
>
>
=> chore: Log JS Function execution

app/client/src/api/GitSyncAPI.tsx, app/client/src/sagas/GitSyncSagas.ts, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/GitControllerCE.java
After introducing the rebase with discard, this PR is to remove the old cold that was there to support pull flow with discard.
=> chore: remove the doPull flag from the git discard API

app/client/cypress/e2e/Regression/ClientSide/Onboarding/GuidedTour_spec.js, app/client/cypress/support/commands.js, app/client/src/components/editorComponents/ActionCreator/viewComponents/Action/ActionTree.test.tsx, app/client/src/components/editorComponents/ActionCreator/viewComponents/Action/ActionTree.tsx
show callback button in action selector cards for chain-able actions by default
- Removed touched state from ActionCard that tracks interaction on card.
- Added unit test to assert callback button render
>
>
>
>
>
>
>
>
>
>
=> fix: show callback button in action selector cards for chainable actions by default

app/client/src/pages/Editor/APIEditor/CommonEditorForm.tsx
When only dynamic bindings are pasted in the API url, the run button is remains disabled.
Fixes #24297 
>
>
>
>
>
>
>
=> fix: Fix blocked api execution for url path fields

app/client/cypress/e2e/Regression/ServerSide/ActionExecution/Block_Execution.ts, app/client/cypress/fixtures/datasources.json, app/client/cypress/support/Pages/DataSources.ts, app/client/src/constants/QueryEditorConstants.ts, app/client/src/entities/Action/index.ts, app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
The configProperty path for Post UQI datasource's body field  is stored in actionConfiguration.formData.body.data, other older pre UQI format SQL datasources  actionConfiguration.body. This adds a check for such post UQI datasources like Oracle.
Fixes #24350 
>
>
>
>
>
>
> Please describe …
=> fix: Block Action execution for Post UQI datasources like oracle

app/client/packages/design-system/theming/src/color/ColorsAccessor.ts, app/client/packages/design-system/theming/src/color/DarkModeTheme.ts, app/client/packages/design-system/theming/src/color/LightModeTheme.ts, app/client/packages/design-system/theming/src/color/types.ts
tl;dr Checking whether seed falls into the interval and picking most distant red
Fixes #22365   
https://github.com/appsmithorg/appsmith/assets/80973/4dc4d9bb-1baa-4d34-87d0-57f08b7af2c2
- Manual
=> feat: WDS algorithmic negative colors

app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_TestExecuteWithDynamicBindingInUrl_spec.ts, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/exceptions/pluginExceptions/AppsmithPluginError.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/exceptions/pluginExceptions/AppsmithPluginErrorCode.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DatasourceUtils.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/InitUtils.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/DatasourceStorage.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/plugins/BaseRestApiPluginExecutor.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/plugins/PluginExecutor.java, app/server/appsmith-interfaces/src/test/java/com/appsmith/external/plugins/DatasourceUtilsTest.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceStorageServiceCEImpl.java
- Earlier the client would by default set a URL in REST API query config in `datasource.url` path if it could not parse the URL properly. This made sure that `datasource.url` path was non-empty as long as user entered some value in the URL input box on the REST API query config page. However, this was changed recently to fix an issue related to showing the evaluated value of dynamic binding on the client. As per the current logic, the default path for the URL has been updated to `actionConfiguration.path`. Hence, for newer REST API queries where `datasource.url` is emtpy, a validation error shows up.  This PR includes changes to stop the empty URL validation check for embedded datasources on REST API datasource URL as it can be empty now for embedded datasource. 
- …
=> fix: fix execution of REST API query when dynamic binding is present in the URL

deploy/docker/entrypoint.sh
This will complete: [23522](https://github.com/appsmithorg/appsmith/issues/23522)
Currently, when we deploy appsmith on cloudrun we see this error. This commit will fix this issue
```
2023-06-14 12:32:10.513 IST
Mounting File Sytem
2023-06-14 12:32:10.521 IST
mount.nfs: mount point /appsmith-stacks does not exist
2023-06-14 12:32:10.533 IST
Container called exit(32).
```
=> create stackpath in cloudrun based deployment

app/client/src/ce/pages/UserAuth/Login.tsx, app/client/src/ce/pages/UserAuth/SignUp.tsx, app/client/src/ce/utils/index.ts
This is a supportive PR for https://github.com/appsmithorg/appsmith-ee/pull/1606
Please see [this comment](https://github.com/appsmithorg/appsmith-ee/pull/1606#issuecomment-1590634326).
>
>
>
>
- This change requires a …
=> feat: add htmlPageTitle hook and use it in login and sign up pages

app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx, app/client/src/widgets/TableWidgetV2/component/cellComponents/HeaderCell.tsx
Sort and Freeze controls where visible even after disabling them. This caused unwanted premature truncation of the header text.
Now, when both the controls are disabled, we don't see the freeze/sort drop-down.
Fixes #23200 
[Screencast from 02-06-23 11:59:25 AM IST.webm](https://github.com/appsmithorg/appsmith/assets/48979376/b0381f6a-f596-4931-bf45-e7b397097091)
>
>
>
>
>
>
>
>
=> fix: Sort/Freeze control existing after they are disabled

app/client/cypress/support/Pages/DataSources.ts
- This PR fixes the Airtable dropdown value change from ‘Bearer token’ to ‘Personal access token’
=> test: Cypress | AirtableSpec dropdown value fix

app/client/cypress/e2e/Regression/ClientSide/ActionExecution/disableJSToggle_spec.ts, app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/PropertyControl_spec.ts, app/client/cypress/support/Pages/PropertyPane.ts, app/client/src/actions/controlActions.tsx, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/DatasourceDropdown/index.tsx, app/client/src/components/propertyControls/BaseControl.tsx, app/client/src/components/propertyControls/OneClickBindingControl.tsx, app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx, app/client/src/sagas/WidgetOperationSagas.tsx, app/client/src/utils/PropertyControlFactory.tsx, app/client/src/utils/PropertyControlRegistry.tsx
Now, on table data property of Table widget, we can switch between js mode and non js mode when there is a value.
Fixes https://github.com/appsmithorg/appsmith/issues/24354
>
>
>
>
>
> …
=> chore: [one click binding] allow switching between js mode and non js mode on property control

app/client/cypress/support/Pages/DeployModeHelper.ts
- This PR adds the No Error toast to NavigateBacktoEditor() which sometimes results in Edit page not being load in CI runs
- Attempts to capture Widgets/Input/Input_spec.js [recent run failure](https://cloud.cypress.io/projects/eyxvp8/runs/36365/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D)
=> test: Cypress

app/client/packages/design-system/theming/src/color/DarkModeTheme.ts, app/client/packages/design-system/theming/src/color/LightModeTheme.ts
tl;dr Better logic and looks for light mode `bgAccentSubtle*` state colors 
Fixes #24034  
- Manual
=> feat: WDS colors `bgAccentSubtle*` (light mode)

app/client/cypress/e2e/Regression/ClientSide/Widgets/JSONForm/JSONForm_CurrencyField_spec.ts, app/client/cypress/locators/WidgetLocators.ts, app/client/src/widgets/JSONFormWidget/fields/CurrencyInputField.tsx
This issue is happening because we are getting lodash library as `undefined` when we pass it to` derived.value` function here. This is happening because of the following reason:
* [Bundle optimisation PR](https://github.com/appsmithorg/appsmith/pull/21667) introduces a new plugin called: `babel-plugin-lodash`. It helps in transforming the imports. 
* But this plugin doesn't work on the following pattern: `import _ from "lodash"`. Here it replaces `_` with `undefined`
[ This file](https://github.com/appsmithorg/appsmith/blob/3bc50d9632cf269935aed6657092ddb8b7e8c92f/app/client/src/workers/common/JSLibrary/lodash-wrapper.js#L1) explains the exact scenario that we are facing.
There is also [an open bug](https://github.com/lodash/babel-plugin-lodash/issues/235) for this issue on the …
=> fix: change to lodash wrapper

app/client/cypress/e2e/Regression/ClientSide/Widgets/Filepicker/FilePickerV2_CSV_spec.js, app/client/cypress/locators/commonlocators.json
This PR fixes the flaky test seen in FilePickerV2_CSV_spec.js.
The fix has been to replace wait with network interceptors.
=> chore: Use cypress interceptors instead of wait to fix file csv flaky test

.github/workflows/integration-tests-command.yml
Fixes #24700
These changes will allow the CI to skip tests if there are no changes in server folder when using ok-to-test command. This will save CI minutes
=> chore: Skip tests in server build if no changes in server files for ok-to-test command

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration009RemoveStructureFromWithinDatasource.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration012RenameIndexesWithLongNames.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration015RemoveNullEnvIdDatasourceStrucutureDocuments.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/DatasourceStructureSolutionTest.java
Have placed a more specific unique index on datasourceStorageStructure collection. Applying the index wouldn't cause any problems because of general uniqueness already existing.
> TLDR; changing the index for datasourceStorageStructure collection
Fixes #24628 
>
>
=> fix: changing the index for datasourceStorageStructure collection

app/client/cypress/support/e2e.js
Added some logs to be printed on failure. Hoping this would help in debugging the loading issue. Will remove it later once it is fixed.
Related to https://github.com/appsmithorg/appsmith/issues/23713
=> chore: log editor state on test failure

.github/workflows/integration-tests-command.yml
This PR prints github event when ok-to-test command is run. This is needed for debugging optimization changes to skip server tests if there are no server side changes.
=> chore: print workflow information

.github/workflows/integration-tests-command.yml
This PR fixes incorrect diff calculation between base and head of the pull request raised. This diff is used for determining if server tests should run or not.
Related PR to this is : https://github.com/appsmithorg/appsmith/pull/24731
=> chore : Fix/skip test optimization

app/client/cypress/support/RapidMode.ts, app/client/src/widgets/TableWidgetV2/widget/utilities.test.ts, app/client/src/widgets/TableWidgetV2/widget/utilities.ts
Fixes #24344
Steps to repro are in the connected issue.
=> fix: Fix default selected row on a page change when primary key is selected in a table and is unavailable in new data

app/client/src/widgets/RadioGroupWidget/component/index.tsx
When the label is on the left of the radio widget, the options are aligned to the top of the container.
In this PR this issue is fixed.
Fixes #23847
>
>
>
>
>
>
>
>
=> fix: Radio Group options are aligned with the label

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/DatasourceStructureSolutionTest.java
> TL;DR  now returning empty datasourceStructure object instead of Mono.empty, also added the analytics call back.
The issue has started in sentry because a snippet has recently been added to expect some response from server, if the response is empty it throws error 
Fixes #23675
=> fix: returning empty  datasourceStucture instead of empty on invalid

app/client/cypress/e2e/Regression/ClientSide/OtherUIFeatures/Omnibar_spec.js
Skipping this test as it is dependent on docs link, which make it flaky whenever docs are updated and also this feature is getting removed soon: https://theappsmith.slack.com/archives/CNQ9Q91C0/p1684828154586489 
locally
=> test: Skip omnibar documentation test

app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/columnTypes/select_spec_2.ts, app/client/cypress/support/Pages/Table.ts, app/client/src/widgets/TableWidgetV2/component/cellComponents/SelectCell.tsx, app/client/src/widgets/TableWidgetV2/widget/propertyUtils.test.ts, app/client/src/widgets/TableWidgetV2/widget/propertyUtils.ts
This PR passes a `[]` to the select component when some values in the select options that are passed to the select cell component are `null`.
This fixes issue where the table widget breaks when select options for the select column type contains `{{null}}` or `{{[null, null]}}`
Fixes #24857
- To test that table widget does not break when `{{[null]}}`, `{{[null, null]}}`, `{{null}}` is passed to select options or new row select options.
- To test that table widget does not break when select options or new row select options contains API binding that does not have any data 
- should test that select column dropdown has no results found string when select option is {{null}}
- should test that select column dropdown has no results found …
=> fix: add null check for select options in table widget

app/client/src/workers/common/DataTreeEvaluator/validationUtils.ts
`getValidatedTree` method which gets called during first tree setup sets errors into an invalid location causing the validation error to not show up on page reload. This PR fixes the error location.
>
>
Fixes #24664
>
>
>
>
>
>
>
>
>
>
>
>
>
>
=> fix: Fixed corrupt validation error on page reload

app/server/appsmith-server/pom.xml, app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/RedisConfig.java, app/server/appsmith-server/src/main/resources/application.properties
This PR adds support to Appsmith server to be able to connect to ElastiCache Redis with cluster mode turned on. When the `APPSMITH_REDIS_URL` is set to `redis://...`, the current default behaviour is preserved. But if it is set to `redis-cluster://...`, then we setup a pooled connection with cluster mod enabled.
=> feat: Add support for connecting to Redis clusters

.github/workflows/add-label.yml
=> ci: Cypress-only-fixes label workflow fix

.github/workflows/add-label.yml
=> ci: Cypress-only-fixes label workflow fix-II

.github/workflows/add-label.yml
=> ci: Cypress-only-fixes label workflow fix-III

.github/workflows/add-label.yml
=> ci: Cypress-only-fixes label workflow fix-IV

.github/workflows/add-label.yml
=> ci: Cypress-only-fixes label workflow fix-V

.github/workflows/add-label.yml
- This PR removed the Add Cypress-Only-Fixes Label on PR Merge workflow to run from PR merge until fixed
=> ci: Cypress-only-fixes label workflow remove

app/client/src/workers/Evaluation/handlers/jsLibrary.ts, app/client/src/workers/common/DependencyMap/utils.ts, app/client/src/workers/common/JSLibrary/resetJSLibraries.ts
Removed redundant copy operation around extractInfoFromBinding. This has brought an improvement to the setupUpdateTree function. Seen a reduction of eval computation by 60% when changing the table data from 3200 records to 10000 records.
Fixes #24753 
>
>
>
>
>
>
>
>
>
>
=> chore: [perf optimisations for large data sets] optimised extract info binding code

app/client/src/pages/common/datasourceAuth/AuthMessage.tsx
This PR resolves documentation issue with google sheets. We see learn more CTA, when creating google sheets datasource, that takes us to the documentation for google sheets. Earlier we used to show documentation using modal from omnibar, now we have[ removed the documentation option itself from omnibar](https://github.com/appsmithorg/appsmith/pull/24787), thus it started failing. This PR fixes the issue
Fixes #25005 
>
>
>
>
>
>
>
>
> Please describe the tests that you ran to verify your changes. Also list any relevant details …
=> fix: gsheets documentation issue fixed on datasource page

app/client/cypress/e2e/Regression/ClientSide/OtherUIFeatures/Logs2_spec.js, app/client/src/workers/Evaluation/evaluation.worker.ts
All errors from synchronous user code are handled by evaluation engine. But if a user action schedules a timer and the callback code contains an error, this error is never caught causing sentry to log it. This PR adds a global "error" event listener on the worker that handles all such uncaught errors, by logging it to console and in-app debugger.
Fixes #24039
>
>
>
>
>
>
>
>
>
>
=> fix: Log uncaught errors to debugger

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
Add execution time for the performance improvement for the git status API
=> chore: Add execution time for git status API

app/server/appsmith-server/src/main/java/com/appsmith/server/constants/ce/LicensePlan.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/PricingPlan.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ce/TenantConfigurationCE.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/TenantServiceCETest.java
Added LicensePlan to tenant to get details about the user's current plan
>
>
>
>
>
>
>
>
=> chore: Added license plan to tenant

app/client/cypress/e2e/Regression/Apps/CommunityIssues_Spec.ts, app/client/cypress/e2e/Regression/ClientSide/AppNavigation/TopStacked_spec.ts, app/client/cypress/support/Pages/AssertHelper.ts
- This PR adds new method - WaitForNetworkCall()
- Trail fix for flaky spec ClientSide/AppNavigation/TopStacked_spec.ts
>
=> test: Cypress | Flaky fixes

app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomUserRepositoryCEImpl.java
> To check if the users repository is empty or not, we now limit the query to 1 more than the number of system generated emails. This will not work as expected, if we keep on adding new emails to system generated user emails.
Fixes [[SCIM Bug]: Logging out of the Appsmith asks you to setup the instance again.](https://github.com/appsmithorg/appsmith/issues/25098)
>
>
>
>
>
>
>
>
=> chore: limit the number of users to 1 + number of system generated emails

app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/TenantServiceCETest.java
This PR fixes the TenantServiceCETest failure that happens on EE codebase
>
>
>
>
>
>
>
>
>
>
>
=> fix: Changes to fix CE test failure on EE

app/server/appsmith-server/src/main/resources/features/init-flags.xml
Removes ff4j configuration so that there is only one source of truth for ff configs for ME, ie, Flagsmith.
Fixes #25074 
Fixes #25075 
=> chore: Removed ff4j configuration in favour of Flagsmith

app/client/packages/design-system/theming/src/color/DarkModeTheme.ts, app/client/packages/design-system/theming/src/color/LightModeTheme.ts
tl;dr States and other derivatives of `bgNegative`. Also minor adjustment for `bgPositiveSubtle` in dark mode.
Fixes #24511 
- Manual
=> feat: WDS color `Negative`, states and `Subtle` variant

deploy/helm/Chart.yaml, deploy/helm/templates/NOTES.txt, deploy/helm/templates/statefulset.yaml
Fixes: [21271](https://github.com/appsmithorg/appsmith/issues/21272)
Fixes: [221](https://github.com/appsmithorg/cloud-deployment/issues/221)
Fixes: [24020](https://github.com/appsmithorg/appsmith/issues/24020)
This will help update the init-container image and also updates the probes so that user doesnt find the necessity to restart manually. Rather, kubelet restarts it by self.
**Case-1:**
```
(base) ➜  helm git:(update/cosmetic/changes/ce) ✗ cat values.yaml | grep probes
(base) ➜  helm git:(update/cosmetic/changes/ce) ✗ helm install appsmith . -n goutham --create-namespace --dry-run  > temp.yaml
(base) ➜  helm git:(update/cosmetic/changes/ce) ✗ tail -n 60 temp.yaml
{}
image: "index.docker.io/appsmith/appsmith-ce:latest"
imagePullPolicy: IfNotPresent
ports:
- name: http
containerPort: …
```
=> chore: update init-container images and update probes

app/client/cypress/e2e/Regression/ClientSide/BugTests/GitBugs_Spec.ts, app/client/cypress/support/Objects/CommonLocators.ts, app/client/cypress/support/Pages/GitSync.ts, app/client/src/ce/constants/messages.ts, app/client/src/pages/Editor/gitSync/components/DiscardChangesWarning.tsx, app/client/src/pages/Editor/gitSync/components/GitChangesList.tsx
Discard message were conditionally not shown. It caused a bug when only navigation settings were changed. Removed the condition to include the message every-time.
Fixes #24946 
Before
After
>
>
>
>
>
>
>
>
=> fix: git discard message

app/client/cypress/e2e/Regression/ClientSide/Binding/TableV2_Widget_API_Pagination_spec.js, app/client/src/widgets/TableWidgetV2/component/header/actions/index.tsx
This PR fixes the issue mentioned below by preventing the click event when the next page button is disabled and when it is table's last page.
Fixes #22477
- should check whether the next page button is disabled and not clickable when last page is reached
>
>
>
>
>
=> fix: prevent click event on disabled next page button of table widget

app/client/src/components/editorComponents/ActionRightPane/SuggestedWidgets.tsx, app/client/src/components/editorComponents/ActionRightPane/index.tsx, app/client/src/pages/setup/SignupSuccess.tsx, app/client/src/utils/storage.ts
- Created a `USER_SIGN_UP` flag when the user lands on signup success page. It will have object with key as `emailId` & values as `created-on timestamp` and will be stored in indexDB.
- Show feature walkthrough to only users having `USER_SIGN_UP` flag set.
Fixes #25195
>
>
>
>
- Chore (housekeeping or task changes that …
=> feat: new user signed up flag and show walkthough only if its set

app/client/src/globalStyles/CodemirrorHintStyles.ts
Fixes the style for linting errors in the tooltip.
Earlier, They were presented side by side in case of multiple errors.
Now, They will appear vertically stacked as shown in the screenshot attached below
Fixes #24974
https://appsmith-bda3x9h6s-get-appsmith.vercel.app
Locally tested.
skip-testPlan
=> fix: vertically stack lint errors in the tooltip (#24974)

app/client/src/pages/Editor/MainContainer.tsx
This PR fixes The bubble of the no. of commits is partially visible in preview mode
Fixes #24859
>
>
>
- [x ] My code follows the style guidelines of this project
- [] I have commented my code, particularly in hard-to-understand areas
=> fix: The bubble of the no. of commits in bottom bar in preview mode

app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug25148_Spec.ts, app/client/src/pages/Editor/APIEditor/ApiAuthentication.tsx
Due to absence of `userPermissions` in Datasource object being sent to the Api authentication component, the `edit datasource` button was being disabled. Now the `userPermissions` with regard to datasource, is being added to its object to enable disable the `edit ds` button.
Fixes #25148 
>
>
- This change requires a documentation …
=> fix: edit ds button was disabled due to no user perm in ds object

app/client/src/entities/Engine/AppEditorEngine.ts, app/client/src/sagas/PageSagas.tsx, app/client/src/utils/DSLMigrations.ts
We missed a race condition in: #25104 which caused some test cases to fail. This would rarely happen to any new apps in production but to ensure backwards compatibility we are updating the code itself
=> fix: removes race conditions in recent perf optimisation

app/client/packages/design-system/theming/src/color/DarkModeTheme.ts, app/client/packages/design-system/theming/src/color/LightModeTheme.ts
tl;dr Wrong color was exported (`bdWarning` instead of `bdWarningHover`)
- Bug fix
- Manual
=> fix: WDS color `bdWarningHover` return

app/client/src/widgets/TableWidgetV2/widget/reactTableUtils/getColumnsPureFn.tsx
- When the table's column width is greater than the component width the table widget crashes.
>
>
Fixes #25166 
https://vdqm24wed6.vmaker.com/record/q4yZXh8n0uv7sVrl
>
>
>
>
>
>
>
>
=> fix: Table crashes when column width is greater than component width

app/client/src/plugins/Linting/Linter.ts, app/client/src/plugins/Linting/linters/index.ts, app/client/src/sagas/LintingSagas.ts
This PR is a follow-up to https://github.com/appsmithorg/appsmith/issues/23865. It removes the main thread linter implementation which isn’t used today but does affect the bundle size, increasing it by ~1 MB of minified code:
Context: https://3perf.slack.com/archives/C01SGCF8PM0/p1689156352117669 (to open in Appsmith workspace, replace `3perf.slack.com` with the Appsmith Slack domain)
>
=> perf: remove BaseLinter implementation

app/client/packages/design-system/theming/src/color/DarkModeTheme.ts, app/client/packages/design-system/theming/src/color/LightModeTheme.ts
tl;dr States and other derivatives of `bgNeutral`, some fixes for `bgNeutral` logic itself.
Fixes #24512  
- Manual
=> feat: WDS color `bgNeutral`, states and `Subtle` variant

app/client/cypress/e2e/Sanity/Datasources/Port_Number_Placeholder_Spec.ts
- Add cypress test case to validate that the port number placeholder value mentioned in any datasource config page is valid. 
Fixes #25066 
>
>
>
>
>
>
=> chore: add cypress test case to validate port number placeholder

app/client/cypress/e2e/Sanity/Datasources/MockDBs_Spec.ts, app/client/src/pages/Editor/FormControl.tsx, app/client/src/utils/editorContextUtils.ts
This is a follow-up to https://github.com/appsmithorg/appsmith/issues/23960.
In above issue, we picked the first available entity (table/collection, etc) and show the user a read query by default. With a [[real datasource](https://www.notion.so/7b5b3f6302cc4a8e93f8ecd1a3965cad?pvs=21)](https://www.notion.so/7b5b3f6302cc4a8e93f8ecd1a3965cad?pvs=21), it is not possible to know which is the most meaningful entity to choose. However, with mock datasources, we do have the option because we own the underlying databases.
This PR adds that functionality, In case of Users mock DB, we will populate the query editor with `select * from public.users limit 10`, as Users mock DB contains users table.
Fixes #25247 
>
> …
=> feat: default table name populated in query editor for mock datasources

app/client/src/pages/Editor/PropertyPane/PropertySection.tsx
- On table widget, when you click on `Connect data` , if the `Data` column in the prop pane is collapsed, the one click binding options dropdown open in absolute position (0,0) top left corner of the page. So auto expanding the data column when the user clicks on connect data.
Fixes #25254 
>
>
>
>
>
>
>
>
>
>
> Link issues …
=> fix: auto expand data section in prop pane on connect data

app/client/src/utils/hooks/useWidgetFocus/handleTab.ts, app/client/src/utils/hooks/useWidgetFocus/tabbable.test.ts, app/client/src/utils/hooks/useWidgetFocus/tabbable.ts
The tabbing logic was failing where there was no widget on canvas except modal widget.
Added a null check to fix it.
Fixes #23880
=> fix: Cannot read properties of undefined (reading 'matches')

app/server/appsmith-git/src/main/java/com/appsmith/git/constants/CommonConstants.java, app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/DSLTransformerHelper.java, app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java, app/server/appsmith-git/src/test/java/com/appsmith/git/helpers/DSLTransformHelperTest.java
fix the Tabs Widget issue for canvas split
Fixes #25411 
>
>
>
>
>
>
>
>
>
>
>
=> chore: hotfix v1.6.28

app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
fix: signposting is showing up on non postgres screens
Fixes #25439 
>
>
>
>
>
>
>
> …
=> fix: signposting is showing up on non postgres screens

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceStorageServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/CreateDBTablePageSolutionCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceTriggerSolutionCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceStorageServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/DatasourceStructureSolutionTest.java
> this Pr is regarding error handling when no DatasourceConfiguration is found in datasourceStorage, now we are erroring out with error message for no configuration found.
Fixes #25350
=> fix: added error handling when no config found in datasourceStorage

app/server/appsmith-server/src/main/java/com/appsmith/server/constants/ce/AnalyticsConstantsCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/DatasourceAnalyticsUtils.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceStorageServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceStorageServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ActionExecutionSolutionCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java
> CE support for adding instrumentation for environment name and environmentId in EE. 
EE needs instrumentation for 
- Environment Id
- Environment Name
in the below given flows, this PR is to address the required ce changes for the same, we have used a default environmentName `unused_env` for CE, this will be replaced in EE by the respective names in analytics
Fixes #https://github.com/appsmithorg/appsmith/issues/24955
- Breaking change, this change will break EE, required PR to fix the issue: https://github.com/appsmithorg/appsmith-ee/pull/1847
=> chore: Multiple environment instrumentation

app/client/cypress/e2e/Regression/ServerSide/JsFunctionExecution/PlatformFn_spec.ts, app/client/src/sagas/ActionExecution/ShowAlertActionSaga.ts
The toaster component, part of the react design system, generates a unique id for each toast. The id is generated based on a content string and the options Json. When the content and options are identical, duplicate ids are generated. Toaster ignores any toast with duplicate IDs.  Explicitly passing a unique id overrides the internal id generation logic. This ensures that all toasters are displayed, even if the content and options are identical.
Fixes #16135 
None
>
- [x ] Manual
- [ x] Cypress
>
>
cypress test case is defined in 
`app/client/cypress/e2e/Regression/ServerSide/JsFunctionExecution/PlatformFn_spec.ts/2.Bug 16135 ShowAlert with same texts, when invoked from different triggers are combined
`
> Link issues raised during DP …
=> fix: ShowAlert with same texts, when invoked from different triggers are combined 

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ApplicationForkingServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ForkExamplesWorkspaceServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceContextServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/MockDataServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/WorkspaceServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/ActionServiceCE_Test.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/ApplicationServiceCETest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ApplicationForkingServiceTests.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/AuthenticationServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/CreateDBTablePageSolutionTests.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/DatasourceStructureSolutionTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/DatasourceTriggerSolutionTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ForkExamplesWorkspaceServiceTests.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ce/ActionExecutionSolutionCETest.java
> PR for interface modification for rbac changes. 
This PR is changing methods signature for getDefaultEnvironmentId by adding the `AclPermission` parameter.
This param will be used to pass arguments to decide whether the user has access for a particular operation. If this argument is set to null, we don't require any permission.
Although in CE all calls will consistently return a mono of unused_env, however In EE, this would be different.
=> chore: changing interface method

app/client/cypress/e2e/Regression/ClientSide/BugTests/DatasourceSchema_spec.ts
This PR fixes the failing cypress test DatasourceSchema_spec.ts on Appsmith-ee.
>
>
>
>
>
>
>
=> chore: Fix cypress test blocker on ee

app/client/src/sagas/EvaluationsSaga.ts, app/client/src/sagas/PostEvaluationSagas.ts, app/client/src/workers/Evaluation/evalTreeWithChanges.ts, app/client/src/workers/Evaluation/handlers/evalTree.ts, app/client/src/workers/Evaluation/types.ts, app/client/src/workers/common/DataTreeEvaluator/index.ts, app/client/src/workers/common/DataTreeEvaluator/validationUtils.ts
Debugger logs were only updated according to the evaluation order earlier this led to an issue as after revalidation we need to update the debugger errors. 
Fixes #24905
- Validation sanity test
=> fix: revalidation logic 

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ActionExecutionSolutionCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ce/ActionExecutionSolutionCEImplTest.java
Changes to start to consider embedded datasources as oos in env
=> fix: Added embedded check for true env

app/client/src/entities/Engine/AppEditorEngine.ts, app/client/src/utils/editor/EditorUtils.ts, app/client/src/utils/editor/browserTabsTracking.ts
Added tracking for seeing open editor tabs with the same app. This is to check if the user is trying to edit the same app in multiple tabs and will help us make better decisions in Context Switching project
fixes #25141
=> chore: [Analytics] Track open tabs with the same editor

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceStorageServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceStorageServiceTest.java
> Error handling changes when we don't find any datasource storage
- Ideally error should only be thrown when we are trying to execute/use datasource configuration in some ways, therefore it's not necessary to throw error. Additionally, Page load could be blocked due to this, hence removed throwing error from flows where no execution is happening, I.e fork, fetch
Fixes #25605 
=> chore: modified error handling when datasource storage is not found for execution

.github/workflows/client-build.yml, .github/workflows/client-lint.yml, .github/workflows/client-unit-tests.yml, .github/workflows/docs/integration-tests-command.md, .github/workflows/docs/quality-checks.md, .github/workflows/docs/test-build-docker-image.md, .github/workflows/integration-tests-command.yml, .github/workflows/quality-checks.yml, .github/workflows/server-build.yml, .github/workflows/test-build-docker-image.yml, app/client/.gitignore, app/server/README.md
QC now has all server and client side formatting and unit tests check. This would be a compulsory check for merge.
ok-to-test hence does not needs unit tests to run. This should reduce run times by half an hour.
TBD also now does not need Cypress to run at all before package. Since package never required tests to pass on release, this change simply reduces the time between pushing to release and the changes reflecting on release.app.appsmith.com 
A few other clean ups across the board.
=> ci: Moved QC around, removed unit tests running with ok to test

app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/UserSessionDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CacheableFeatureFlagHelperCEImpl.java
> This PR adds the user createdAt trait in flagsmith for the user identifiers.
Fixes #25702 
>
>
>
>
>
>
>
>
=> fix: added createdAt to redis session key and user trait (#25702)

app/client/src/pages/Editor/APIEditor/ApiAuthentication.tsx
In case the staging config is not present, the app crashes when user switched to staging config while keepng the authenticated tab open for an API connected to multiple env ds. Added a null check for the same and using the ds ID from the parent ds.
Fixes #25696
=> fix: oauth empty config check

app/client/src/pages/Editor/EditorAppName/index.tsx, app/client/src/pages/Editor/EditorHeader.tsx
We noticed that empty applications sometimes do not show the application name. This was caused by a style issue where the height of the component was defaulted to 1px even if the name actually exists in the component. To fix this, we are forcing the styles to always be set to the header height. 
Also refactored the Editor header component a bit.
Fixes #25457
>
>
>
>
>
>
>
>
=> fix: Application name does not show up sometimes

app/client/cypress/support/Pages/AdminSettings.ts
1. Changed access specifiers: _adminSettingsBtn in AdminSetting from private - public
=> test: Cypress - changed access specifiers of _adminSettingsBtn

app/client/src/ce/utils/Environments/index.tsx, app/client/src/pages/Editor/GeneratePage/components/GeneratePageForm/GeneratePageForm.tsx, app/client/src/pages/Editor/GeneratePage/components/GeneratePageForm/hooks.ts, app/client/src/pages/Editor/IntegrationEditor/DatasourceCard.tsx
Generate page crud was checking for the config from DS storage even for non env enabled datasources. This PR fixes that.
Fixes #25640
=> fix: config checks for generate page CRUD

app/client/cypress/e2e/Sanity/Datasources/MockDBs_Spec.ts
- Movies is now returning 2 records for default query as opposed to 1, hence this PR to fix it in CI runs
- 
>
=> test: Cypress | Fix Datasources/MockDBs_Spec.ts 

app/client/cypress/e2e/Sanity/Datasources/MockDBs_Spec.ts, app/client/cypress/limited-tests.txt, app/client/cypress/support/Pages/DataSources.ts
- This PR fixes - Datasources/MockDBs_Spec.ts
- It improves the CheckResponseRecordsCount() to validate if record count matches the min value sent for validation
=> test: Cypress | Fix Datasources/MockDBs_Spec.ts

Dockerfile
This will allow us to set a separate cloud-services URL during build time.
=> chore: Add APPSMITH_CLOUD_SERVICES_BASE_URL as build arg

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/TenantServiceCEImpl.java
This change is [already made in EE](https://github.com/appsmithorg/appsmith-ee/blob/9b9a39e488cfbaf4a8f7b8a2a4d1d05db77f950d/app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/TenantServiceCEImpl.java#L123). This PR is about paying the back-sync debt.
=> chore: Prevent null tenantConfiguration, needed for EE

deploy/docker/templates/nginx/nginx-app-http.conf.template.sh, deploy/docker/templates/nginx/nginx-app-https.conf.template.sh
This is to fix OAuth redirect URI not being computed correctly, when deployed to CloudRun.
More details at http://sharats.me/drafts/story-of-a-forwarded-header.html.
=> fix: Extend Forwarded header, if present

.github/workflows/build-docker-image.yml
This should enable using unchanged layers from the `release` image, as a cache, and build PR images faster. We only do this for images built for PRs and not for direct `release` or `master` branches.
=> ci: Use cache from release image to build faster

deploy/docker/entrypoint.sh
When `APPSMITH_CLOUD_SERVICES_BASE_URL` is an empty string, Spring's interpolation in `application.properties` doesn't take the default value. This PR sets up the `entrypoint.sh` script so that it'll `unset` this env variable, when it's empty.
=> fix: Fix missing cloud services URL when env variable is empty

app/client/src/sagas/JSPaneSagas.ts
This PR adds `consoleStatements` field to JS_OBJECT_FUNCTION_RUN analytics event
Fixes #25532 
Nil
>
>
>
>
>
=> chore: Add console statements log to JS_RUN event

Dockerfile, app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CloudServicesConfig.java, app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/SharedConfigImpl.java, app/server/appsmith-server/src/main/resources/application.properties, deploy/docker/entrypoint.sh
This will allow us to
1. Bake different CS URLs for release and master builds.
2. Be resilient to the CS URL being set to empty string, as opposed to not being set at all.
=> chore: Graceful handling for empty CS URL

.github/workflows/ad-hoc-deploy-preview.yml, .github/workflows/build-docker-image.yml, .github/workflows/on-demand-build-docker-image-deploy-preview.yml, .github/workflows/test-build-docker-image.yml
When running Appsmith release image, it's currently using production CS, which is causing a lot of incompatibility related errors since `release` moves much faster than prod.
This changes this. Note that for `:latest` and `:nightly` images, we do NOT change this default. There's no change for Docker images with those tags. We _only_ want change `:release` image, DP images, and images built for Cypress runs.
=> ci: Default to release CS unless building for prod

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/SecurityConfig.java
Fix critical problem where public apps are redirecting to login page, because of product-alerts API not accepting anonymous users.
=> fix: Fix failing product alert API for anonymous user

app/client/cypress/e2e/Regression/ClientSide/Debugger/Widget_property_navigation_spec.ts, app/client/cypress/e2e/Regression/ClientSide/ExplorerTests/Widgets_Sidebar.ts, app/client/src/selectors/editorSelectors.tsx
- Fixes an issue where widgets from WDS were showing up in Airgap.
- Remove the map widget from the widgets list in the widget sidebar cypress test.
>
>
>
>
>
>
>
>
> Please describe …
=> fix: Cypress test for widget sidebar in Airgap

.github/workflows/ad-hoc-deploy-preview.yml, .github/workflows/on-demand-build-docker-image-deploy-preview.yml
The currently used `v1` is deprecated, and not recommended anymore. The `v4` changes a few things. Some details are in the following pages:
1. https://github.com/docker/build-push-action/blob/v2/UPGRADE.md
2. https://github.com/docker/build-push-action/blob/4fad532b9fdbfb80f436784834374a1c11834153/README.md#customizing
Essentially, in the current code, `build-args` isn't working. This should fix that.
=> ci: Update docker/build-push-action to v4

app/client/cypress/e2e/Regression/ClientSide/BugTests/InputTruncateCheck_Spec.ts
- This PR uncomments the PinUnpinEntityExplorer() check in InputTruncateCheck_Spec.ts - as it is handled now to click on EE pin based on its presence in the application in this [PR](https://github.com/appsmithorg/appsmith/pull/25901/files#diff-491bdd1b772e351aca1199411640be4a848e84646253ddc249b7daad57bbbf1b) & merged to release.
- This PR is revert of [this PR change](https://github.com/appsmithorg/appsmith/pull/25919)
=> test: Cypress | Uncomment EE-Pin check in InputTruncateCheck_Spec.ts

app/client/src/sagas/DebuggerSagas.ts
Add Appmode in debugger analytics
Fixes #25730
- Chore 
>
=> chore: Add appmode in debugger analytics

app/client/src/pages/Editor/Explorer/Datasources/DatasourceStructureContainer.tsx
When the column field is an empty array, it breaks searching, this PR fixes that issue.
Fixes #25540 
>
>
>
>
>
>
>
>
=> fix: Fix search for s3 datasources

.github/workflows/on-demand-build-docker-image-deploy-preview.yml, Dockerfile, scripts/generate_info_json.sh
This adds a `/opt/appsmith/info.json` file to Docker images, with the following sample content:
```json
{
"commitSha": "0521ba2c0d7a62cef3d4def66fc15b59cc34ceef",
"commitUrl": "https://github.com/appsmithorg/appsmith/commit/0521ba2c0d7a62cef3d4def66fc15b59cc34ceef",
"branch": "release",
"date": "2023-08-02T12:52:53+00:00",
"isCI": false
}
```
We're enabling this only for images built for DPs currently, and will then extend to other workflows as well.
Notice that we copy `info.*json` instead of `info.json`. The reason is so that the Docker build doesn't fail, even if the `info.json` file doesn't exist. This lets us publish this to each workflow in turn, slowly and carefully.
[Relevant Slack conversation](https://theappsmith.slack.com/archives/C02MUD8DNUR/p1686197957141419).
=> chore: Add info.json to Docker images

app/client/src/components/editorComponents/WidgetComponentBoundary.tsx, app/client/src/widgets/ContainerWidget/component/index.tsx, app/client/src/widgets/WidgetUtils.ts
This PR moves the logic of closing the highlight walkthrough to the widget boundary component. This allows us to retain the closure of walkthrough as well as retain the onItemClick event functionality of list widget.
Fixes #25941
>
>
>
>
- should test that `onItemClick` event works when clicked on the blank space of the list item
- should test that highlight walkthrough get closed when clicked on the widget.
>
>
>
>
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped …
=> fix: moved the logic of highlight walkthrough to widget boundary

.github/workflows/integration-tests-command.yml, .github/workflows/test-build-docker-image.yml
https://theappsmith.slack.com/archives/C02GAUE9P5H/p1691118635067769?thread_ts=1690990621.675539&cid=C02GAUE9P5H
CE deployment has failed for 1.9.31. This was added back here https://github.com/appsmithorg/appsmith/commit/fcb7b04092ab895cc1646c58c4b051a2cfed4019.
=> chore: fix bad merge

app/client/cypress/e2e/Regression/ClientSide/BugTests/GitBugs_Spec.ts, app/client/cypress/support/Pages/GitSync.ts, app/client/src/pages/Editor/gitSync/components/BranchListItem.tsx, app/client/src/pages/Editor/gitSync/components/RemoteBranchListItem.tsx
adds loading state when checking out to a remote branch
Fixes #25591 
>
>
>
>
>
>
>
>
=> fix: adding loading state on remote branch switching

app/client/cypress/e2e/Regression/ClientSide/Widgets/Others/Progress_spec.js, app/client/cypress/locators/WidgetLocators.ts, app/client/cypress/locators/Widgets.json, app/client/cypress/support/Pages/PropertyPane.ts
Added cases for: 
1. Check Progress, Number of steps, Counterclockwise Show result elements disabled on infinite looping enablement
2. Check binding in Progress property 
3. Check progress widget visibility based on visible state
4. Assert expected error texts
=> test: Cypress - progress widget cases 

app/client/packages/design-system/theming/src/color/DarkModeTheme.ts
=> fix: WDS `fgAccent` for achromatic seeds (dark mode)

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/SecurityConfig.java, deploy/docker/templates/nginx/nginx-app-http.conf.template.sh
So far, only calls that go to the Java backend, had the `X-Content-Type-Options` header in the responses. This PR adds them to all responses by
1. adding it to NGINX configuration.
2. removing it from Spring security's configuration, so we don't end up with _two_ `X-Content-Type-Options` headers in the response.
=> chore: Add `X-Content-Type-Options` to all downstream responses

Dockerfile
We're pinning MongoDB to 5.0.14, but can just as well run 5.0.19. This PR makes sure we install the latest v5 of MongoDB, every time we build the image.
=> chore: Install latest MongoDB v5

app/client/cypress/e2e/Regression/ClientSide/Debugger/Widget_property_navigation_spec.ts, app/client/cypress/e2e/Regression/ServerSide/Datasources/ConnectionErrors_Spec.ts, app/client/cypress/e2e/Regression/ServerSide/LoginTests/LoginFailure_spec.js, app/client/cypress/support/Pages/AggregateHelper.ts
- AssertElementVisible() revert due to CI failures
- Fixes dragdrop coordinates in Debugger/Widget_property_navigation_spec.ts
- Fixes S3 ACCESS_KEY in ConnectionErrors_Sepc.ts
- /LoginTests/LoginFailure_spec.js - another trial fix
- Remove unused method AssertElementNotVisible
>
=> test: Cypress | CI Stabilize

app/client/src/pages/common/datasourceAuth/index.tsx
Updating `pageId` in the reconnect modal for Gsheets authorization. It was taking the `pageId` of the old delete page for authorization from the query params. This has been fixed by using props instead if its inside reconnect modal.
Fixes [#26024](https://github.com/appsmithorg/appsmith/issues/26024)
=> fix: Updating the pageId in the reconnect modal for Gsheets authorization

app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug25982_Spec.ts, app/client/src/components/formControls/DropDownControl.tsx
Whenever a switch is made between two UQI queries, the command default to the initial value even if the user had previously selected a value. This PR fixes that issue.
Fixes #25982 
Fixes #25088 
>
>
>
>
>
>
>
=> fix: Fix uqi query switching issue

app/client/src/pages/Editor/PropertyPane/PropertySection.tsx
The property pane for this specific widget will only have the data section expanded if the walkthrough is launched for a specific widget after the API action result has been bound to any widget through new binding UI. This will happen for :
- new users
- users having feature flag `ab_ds_binding_enabled` value true
- when the user clicks on binding widget through suggested or sniping mode from right side pane of the action editor
`when all the above conditions meet`
figma link : https://www.figma.com/file/kbU9xPv44neCfv1FFo9Ndu/User-Activation?type=design&node-id=1149-74041&mode=design&t=sqLQ7DgClGfR31l9-4
Fixes #25419
>
>
> Please delete options that are not …
=> fix: open data section, collapse other section if walkthru opened for widget

deploy/docker/scripts/init_ssl_cert.sh
The template script has been moved recently, but it hasn't been updated here.
=> fix: Fix NGINX config template path in cert provisioning script

app/client/cypress/e2e/Sanity/Datasources/MsSQL_Basic_Spec.ts, app/client/src/pages/Editor/QueryEditor/Table.tsx
Whenever a count query is run on an MsSQL Query, the returned data is this `{"": 10}`, which breaks the app because, the Table component cannot render table data cells for empty strings as Headers.
Fixes #24556 
>
>
>
>
>
>
>
>
=> fix: MsSQL count breaks app

app/client/packages/design-system/theming/src/color/DarkModeTheme.ts
=> fix: WDS colors checks for non-achromatic seeds (dark mode)

Dockerfile, deploy/docker/utils/package.json
Update:
- Mobed jest to` devDependenies` of package manifest.
- Updated Dockerfile to install utils with `--only=prod` arg for npm install cmds.
Tested manually
=> fix: moved jest to devdependencies for appsmithctl and updated dockerfile to exclude it during install

scripts/build_dp_from_branch.sh, scripts/deploy_preview.sh
For DP images, this now defaults to release-cs, so we don't need to explicitly set this anymore.
This can be confirmed by running the following:
```
image=appsmith/appsmith-dp:ce-25909
docker pull "$image"
docker image inspect "$image" --format '{{join .Config.Env "\n"}}' | grep CLOUD_SERV
```
=> ci: Use default CS URL for DPs

app/client/cypress/e2e/Regression/ClientSide/Autocomplete/JS_AC1_spec.ts, app/client/cypress/e2e/Regression/ServerSide/GenerateCRUD/MongoURI_Spec.ts, app/client/cypress/e2e/Regression/ServerSide/OnLoadTests/JSOnLoad2_Spec.ts, app/client/cypress/e2e/Regression/ServerSide/QueryPane/S3_1_spec.js, app/client/cypress/e2e/Sanity/Datasources/Arango_Basic_Spec.ts, app/client/cypress/limited-tests.txt, app/client/cypress/support/AdminSettingsCommands.js
- This PR covers below:
- S3 Widget Binding added
- Skipped test fix - Autocomplete/JS_AC1_spec.ts fix
- ClientSide/EmbedSettings/EmbedSettings_spec.js - increased timeout for server restart hung
- ServerSide/GenerateCRUD/MongoURI_Spec.ts - trial fix - 2nd flaky case 
- Sanity/Datasources/Arango_Basic_Spec.ts - due to DS not appearing in EE
>
=> test: Cypress | (DI) S3 added validations + CI Stabilize

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/plugins/PluginExecutor.java, app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java, app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/constants/FieldName.java, app/server/appsmith-plugins/amazons3Plugin/src/test/java/com/external/plugins/AmazonS3PluginTest.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/CreateDBTablePageSolutionCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/CreateDBTablePageSolutionTests.java
- Currently the server side code flow for generate CRUD page contains plugin specific check and plugin specific implementation in the common code module. This is a anti-pattern. This PR introduces a method in the plugin module such that each plugin can define their own implementation and the current code is refactored to remove any plugin specific check or handling. 
- Please note that there are other instances of plugin specific handling on the same page, those would be addressed as part of a separate pull request. The part that is being handled now should open up the way to introduce MsSQL CRUD page generation, hence this portion has been prioritized for now. 
Fixes #26290
> Add Testsmith test cases links that …
=> chore: refactor crud page flow to move plugin specific handling to plugin module

app/client/src/workers/common/DependencyMap/utils.ts
Spread operator was introduced back in `extractInfoFromBinding` method in #25339 causing a performance regression. This PR reverts this change
>
>
- Performance Fix
>
>
>
>
>
>
>
>
>
=> chore: Perf regression fix

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CacheableFeatureFlagHelperCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/FeatureFlagServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserDataServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/FeatureFlagServiceCETest.java
When we introduced the tenant level flags, it's not been added in get all flags for user instead we added these in the user data service to get all the feature flags for user. As we are progressing with 1 click upgrade-downgrade project to avoid future confusion around feature flagging I was hoping to expose single method to get all the relevant feature flags for user. This includes:
1. Local flags from ff4j
2. User level flags from Flagsmith
3. Tenant level flags from Flagsmith (These will be shared across the userbase with same tenantId)     
This PR unifies the flags with single method `getAllFeatureFlagsForUser`.
Fixes https://github.com/appsmithorg/appsmith/issues/26547
=> fix: Add tenant feature flags to get all feature flags for user 

app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationSuccessHandlerCE.java
> Login source of users is not tagged properly, if they are invited and then directly login using an OAuth2 mechanism.
> With the change in checks post successful authentication, the users will have the correct login source.
Fixes https://github.com/appsmithorg/appsmith/issues/26519
>
>
>
>
>
>
>
>
=> fix: update checks for updating the login source on successful authentication

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceContextServiceTest.java
When going through REST API updatable connection flow (which is for every authenticated ds execution), we were using a method that does not decrypt values after saving the configuration in DB. This was causing requests to fail since the encrypted data would not be expected to make sense to these endpoints.
This was affecting anything marked as `@Encrypted` in a datasource configuration. Hence includes client credentials as well as self signed certificates in its scope.
Fixes #24910 
>
>
Tested this issue with Self Signed Certificate [Appsmith PR branch setup on local, SelfSigned Cert created locally with the help of this [Documentation](https://github.com/nidhi-nair/self-signed)]
1. Tested with Authentication type set to None
2. Tested …
=> fix: Make sure updatable connections come back with decrypted tokens

app/client/src/widgets/JSONFormWidget/fields/DateField.tsx
This PR adds a check to the date field's value. Along with the existing checks we also check if the value is of type string.
This change solves the issue mentioned below that occurs whenever the defaultValue for the date field in the property pane is an array of string.
Fixes #24675
>
>
>
>
>
>
>
>
=> fix: add datatype check for date field validity jsonform

app/client/src/ce/pages/AdminSettings/LeftPane.tsx, app/client/src/ce/pages/AdminSettings/config/auditLogsConfig.ts, app/client/src/ce/pages/AdminSettings/config/authentication/AuthPage.tsx, app/client/src/ce/pages/AdminSettings/config/branding/index.tsx, app/client/src/ce/pages/AdminSettings/config/general.tsx, app/client/src/ce/pages/AdminSettings/config/provisioning.ts, app/client/src/ce/pages/AdminSettings/config/types.ts, app/client/src/ce/pages/AdminSettings/config/userlisting.ts, app/client/src/ce/pages/workspace/Members.tsx, app/client/src/pages/Settings/FormGroup/Checkbox.tsx, app/client/src/pages/Settings/config/ConfigFactory.ts
- Updating UI for members page to remove the borders between rows.
- Updating the condition for upgrade tags on the left pane of admin settings, to use feature flags instead.
Fixes [#26627](https://github.com/appsmithorg/appsmith/issues/26627)
=> fix: Updating UI for members page and admin settings left pane upgrade tags

Dockerfile, deploy/docker/templates/nginx/nginx-app.conf.sh
Removes this `Server` header in all responses from Appsmith.
```
curl -sSI http://localhost | grep 'server:'
```
It currently shows this:
```
server: nginx
```
=> fix: Add nginx-extras and remove Sever header

app/client/cypress/e2e/Regression/ClientSide/VisualTests/AppPageLayout_spec.js, app/client/cypress/e2e/Regression/ClientSide/VisualTests/DatasourcePageLayout_spec.js, app/client/cypress/e2e/Regression/ClientSide/VisualTests/JSEditorComment_spec.js, app/client/cypress/e2e/Regression/ClientSide/VisualTests/JSEditorIndent_spec.js, app/client/cypress/e2e/Regression/ClientSide/VisualTests/JSEditorSaveAndAutoIndent_spec.js, app/client/cypress/e2e/Regression/ClientSide/VisualTests/WidgetsLayout_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/Camera/Image_Spec.ts, app/client/cypress/e2e/Regression/ClientSide/Widgets/Camera/Video_Spec.ts
Excludes visual tests as it is failing the package step in CI for promotion since reference screenshots are missing causing error in report generation, will be raising another PR to fix tests
copied commit from: https://github.com/appsmithorg/appsmith/pull/26651
=> test: Skip Cypress visual tests to unblock promotion

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/CreateDBTablePageSolutionCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourcePermissionCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourcePermissionCEImpl.java
CRUD Page generation used edit datasource and edit application permissions till now. Updated the same to create page actions and create pages permissions respectively to support custom role creation on BE.
Fixes #26738
=> fix: Using correct permissions on datasource and application during crud page instead of edit permissions

app/client/src/widgets/PhoneInputWidget/widget/index.tsx
> Add a graceful handling to avoid crashing on soft refresh.
>
>
Fixes #26693 
>
>
>
>
>
>
>
>
>
>
1. Dragged and dropped phone input widget on canvas and deployed the app - Entered value and switched environments. 
2. Set a default value for phone input widget, and deployed the app - switched environments. 
3. Dragged and dropped  other input widgets [Currency / …
=> fix: PhoneInputWidget crash on switching environment

app/client/cypress.config.ts, app/client/cypress/package.json, app/client/cypress_ci.config.ts, app/client/cypress_ci_custom.config.ts, app/client/cypress_ci_hosted.config.ts, app/client/package.json, app/client/yarn.lock
- This PR downgrades the Cypress version to V12.17.4 again to capture the screenshot & video for reporting purpose.
=> test: Downgrade Cypress to v12.17.4 to capture the screenshot & video for reporting

app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/ce/GitPrivateRepoCEImplTest.java
As we have started using the @FeatureFlagged for selectively calling the methods from different classes based on the feature flag support, this needs a valid user object to detect if the feature is supported for the current user. This PR adds the api_user context for running the testcases and also adds the mocking for FeatureFlagService which will be used only in EE codebase, but added here to avoid any future merge conflicts.
=> fix: JUnit testcases failures for EE codebase

app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java
PR to update the mocking from helper class to CS API calls to fetch the supported private repo.
=> chore: Mock CS calls in Git service tests instead of the helper method

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CacheableFeatureFlagHelperCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CacheableFeatureFlagHelperCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/FeatureFlagServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/FeatureFlagServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/FeatureFlagServiceCETest.java
PR to add the fallback mechanism when call to CS to fetch the feature flags at tenant as well as user level fails for some reason. With this PR once the feature flag response is received for the first time user will never lose the access of the feature.
Fixes https://github.com/appsmithorg/appsmith-ee/issues/2130
>
>
>
>
>
>
>
=> feat: Provide a fallback for feature flags when server is unable to connect to CS

app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug26716_Spec.ts, app/client/cypress/support/Pages/AggregateHelper.ts, app/client/cypress/support/Pages/DataSources.ts, app/client/src/pages/Editor/Explorer/Datasources.tsx, app/client/src/pages/Editor/Explorer/hooks.ts
This PR fixes issue with datasource not getting highlighted in entity explorer:
Suppose we have 3 datasources in our applications: Users, Movies, and one Postgres or MySQL datasource. Once we create these datasources, we can see them getting populated in entity explorer -> datasource section.
So there were two issues here:
- If I select Users, I am able to see the Users datasource info on the right pane but its not active in the entity explorer, Similarly If I switch to movies, right pane gets updated with movies info but in the entity explorer, we cannot see movies getting highlighted as thats the active selection
- If I am on Users datasource review page, I reload the page, now I can see active selection of Users being highlighted in the entity explorer, but now if we switch to Movies, …
=> fix: entity explorer issue with datasources is fixed

app/client/cypress/e2e/GSheet/AllAccess_Spec.ts, app/client/cypress/e2e/GSheet/ReadNWrite_Access_Spec.ts, app/client/cypress/e2e/GSheet/ReadOnly_Access_Spec.ts, app/client/cypress/e2e/GSheet/SelectedSheet_Access_Spec.ts, app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/RowsGetMethod.java
This PR fixes the issue with filter format in gsheet query creation:
The issue occurs when say the spreadsheet has data in the following format:
Now if we write a query with where clause to to fetch all records with Id < 3, it returns first two records as expected. Now if we change the filter format to cell range and define cell range as b2:b4, It should return `Name: test1 test2 test3`, but instead it throws error, because it first filters out data based on cell range provided, and post that it checks if the where conditions are defined in actionConfig and applies that on the result set to filter data. In above example result set would be `Name: test1 test2 test3` and it tries to apply the where clause condition of `Id < 2`
In order to solve the issue, we need to apply where conditions …
=> fix: gsheet cell range filter format issue fixed

app/client/cypress_ci_custom.config.ts
- Since Airtable is external Datasource & the api call fails when multiple hit multiple times, skipping it from normal oktotest workflows since its run once per day via scheduled runs.
=> test: Cypress | Skip Airtable from CustomConfig

Dockerfile
Updated Dockerfile to install mongo v6.x instead of v5.x.
Manually - Upgrade from v5.x to v6.x
CI
=> chore: update dockerfile to install mongodb v6.x

app/server/pom.xml
We get `2.1.214` from Spring now, we don't need this override anymore.
=> chore(deps): Remove pinned H2 database version

deploy/docker/entrypoint.sh, deploy/docker/templates/supervisord/redis.conf
Step towards not changing anything in the filesystem at runtime, except for things in `/tmp`.
=> chore: Redis config don't write to filesystem at runtime

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/datatypes/ArrayType.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/datatypes/JsonObjectType.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeStringUtils.java
- A user shared [error logs](https://theappsmith.slack.com/archives/C0341RERY4R/p1692015569650229) with us with this error: `Malicious payload, having non natural depths`. As per [this](https://stackoverflow.com/questions/76333714/azure-load-testing-error-o-a-j-e-j-j-jsonpostprocessor-net-minidev-json-parse) thread, this error could occur because `minidev` JSON parser is not thread safe. Currently, in some places we use the `minidev` JSON parser defined as a static variable that could be used concurrently by multiple threads. This PR replaces those static variable definitions with thread local variables.  
Fixes #26932 
>
>
- Not aware how to write automated test for this at the moment. …
=> fix: move static JSON parsers to local variables

app/server/appsmith-server/src/main/java/com/appsmith/server/aspect/FeatureFlaggedMethodInvokerAspect.java, app/server/appsmith-server/src/test/java/com/appsmith/server/aspect/FeatureFlaggedMethodInvokerAspectTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/aspect/component/TestComponent.java, app/server/appsmith-server/src/test/java/com/appsmith/server/aspect/component/TestComponentImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/aspect/component/ce/TestComponentCE.java, app/server/appsmith-server/src/test/java/com/appsmith/server/aspect/component/ce/TestComponentCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/aspect/component/ce_compatible/TestComponentCECompatible.java, app/server/appsmith-server/src/test/java/com/appsmith/server/aspect/component/ce_compatible/TestComponentCECompatibleImpl.java
As per earlier implementation we were using the reflection to find out the declared method in super class based on the feature flag status. This PR fallback to Java inheritance structure to get the method instead of specifically looking for the one within the class.  
Fixes https://github.com/appsmithorg/appsmith/issues/27065
>
>
>
>
>
>
>
>
=> fix: Use inheritance to invoke the method instead of looking for declared one in aspect invoker

.github/workflows/on-demand-build-docker-image-deploy-preview.yml
We're installing quite a few pieces of software, although they're already availble in the CI environments. See https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md.
This has led to one failure where it failed to download Helm (because of a sporadiv 403), where `helm` was already installed and this step wasn't even needed.
This PR does this:
1. Print the versions of the tools we need.
2. Install MongoSH v6.
3. Install Kubectl pinned to v1.23, since the one that comes by default is 1.28, which is too new.
References:
[As seen in this run](https://github.com/appsmithorg/appsmith/actions/runs/6121523768/job/16617184408).
[MongoDB v6 installation](https://www.mongodb.com/docs/v6.0/tutorial/install-mongodb-on-ubuntu/#install-mongodb-community-edition).
=> ci: Remove installs of packages already available

app/server/appsmith-server/src/main/java/com/appsmith/server/cron/CleanUpOldLogs.java, deploy/docker/fs/etc/cron.d/cleanup-logs
This is moving the cleanup script to delete old log files, from being a cron job, to being a scheduled task in the backend server. Why?
1. We want to support running Appsmith with readonly root, which is a request from security teams at enterprise companies.
2. Cron doesn't play nice. It wants to save a `.pid` file under `/var/run`, so it fails to start when running with readonly root. This is not configurable.
3. Since our use of cron is minimal only, we're moving away from it, especially since the backend server is already capable of running scheduled tasks.
4. This moves one job, there's still another. Based on experience from this, we'll work on the other.
Another advantage to doing this is that since this job is now running in the backend server, which has access to MongoDB and …
=> chore: Move cleanup logs from cron to backend server

deploy/helm/Chart.yaml, deploy/helm/Publish-helm-chart.md, deploy/helm/templates/statefulset.yaml
Updated` appsmith/appsmith` helm-chart to` 2.0.5` with `allowPrivilegeEscalation` disabled.
=> chore: disable allowprivilegeescalation in the securitycontext of helm chart

app/client/cypress/e2e/Regression/ClientSide/Onboarding/SignpostingDiscovery_spec.ts
In the video for the failure it looks like we aren't waiting for the query to be created, the fix here waits for the query page to be visible after clicking on create query.
=> chore: fix flaky signposting test

app/client/packages/design-system/theming/src/color/src/DarkModeTheme.ts, app/client/packages/design-system/theming/src/color/src/LightModeTheme.ts, app/client/packages/design-system/theming/src/color/tests/DarkModeTheme.test.ts, app/client/packages/design-system/theming/src/color/tests/LightModeTheme.test.ts
Related #26018 
Added tests for 
- bgNeutralActive color
- bgNeutralSubtle color
- bgNeutralSubtleHover color
- bgNeutralSubtleActive color
- bgPositive color
- bgPositiveHover color
- bgPositiveActive color
- bgPositiveSubtle color
- bgPositiveSubtleHover color
- bgPositiveSubtleActive color
- bgNegative color
- bgNegativeHover color
- bgNegativeActive color
- bgNegativeSubtle color
- bgNegativeSubtleHover color
- bgNegativeSubtleActive color
- bgWarning color
- bgWarningHover color
- bgWarningActive color
- bgWarningSubtle color
- bgWarningSubtleHover color
- bgWarningSubtleActive color
=> chore: add tests for bgNeutralSubtle + bgNeutralActive + bgPositives + bgNegatives

app/client/src/ce/api/ApiUtils.ts, app/client/src/sagas/DatasourcesSagas.ts, app/client/src/utils/storage.ts
For /token call during import process, the env API is not fetched so the envId passed was wrong. Earlier, we used to fetch from localstorage. This PR adds the wait call in the saga so that the envs are always fetched before we can use the token call.
Fixes #27172 
>
>
>
Tested the following on CE DP:
1. Tested import from home page with all Datasources - including OAuth and GSheets
2. Tested fork of the above app into another workspace
3. Tested import from inside the application with Gsheets DS
4. Tested import from …
=> fix: gsheets import headers fix

Dockerfile
Get fixes for CVE-2022-25883 in npm:semver and CVE-2021-3572 in pypi:pip.
=> chore(deps): Update and get CVE fixes for pip and semver

app/client/cypress/e2e/Regression/ClientSide/Workspace/MemberRoles_Spec.ts, app/client/src/ce/pages/Applications/index.tsx, app/client/src/pages/Editor/DataSourceEditor/DatasourceViewModeSchema.tsx, app/client/src/pages/common/SubHeader.tsx, app/client/src/pages/workspace/ManageUsers.tsx, app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java
Make manage users sentence cased & handle mobile UI when top banner is seen
Fixes [#27339](https://github.com/appsmithorg/appsmith/issues/27339)
=> fix: Make manage users sentence cased & handle mobile UI when top banner is seen

deploy/docker/fs/opt/appsmith/templates/nginx-app.conf.sh
This just responds with the contents of `/opt/appsmith/info.json` as is, with a JSON content type.
This will enable showing the right date on the frontend, as well as on Flow. See [this Slack thread](https://theappsmith.slack.com/archives/C02MUD8DNUR/p1694762058953999?thread_ts=1694757060.520329&cid=C02MUD8DNUR) for the confusion we're solving for.
=> feat: Add `/info` endpoint for details about the Appsmith version running

app/client/src/workers/common/DataTreeEvaluator/index.ts, app/client/src/workers/common/DataTreeEvaluator/test.ts
Klona operations are being performed on the dataTree for every evaluation cycle. This computation is heavy and scales up for large dataset. Over here we optimise code to limit klona deepClones for every evaluation cycles and noticed reduction of eval scripting time of upto 40% for apps hosting about 40000 records. Seen a 20-25% reduction in eval scripting in MISC test cases, these test cases host about 20000 records.
Fixes #27048
>
>
>
>
>
>
>
>
=> chore: skip klona for eval updates (#27048)

app/client/src/components/featureWalkthrough/walkthroughRenderer.tsx, app/client/src/pages/Editor/PropertyPane/PropertySection.tsx
If the `WIDGET_ID_SHOW_WALKTHROUGH` localstorage key exists (which gets created when we bind the widget using suggested widget or new widget from action right side pane binding UI), and the property pane opened for current widget selected doesn't have the same widget id, then clear the key from local storage and do not collapse the property sections for the widget in property pane.
Fixes #26776 
>
>
- Chore …
=> fix: property pane if tabledata section doesn't exist, clear widget id

app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySQLDatasourceValidationTest.java, app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java
- A separate file had been created earlier to segregate all the datasource validation tests for MySQL but only few tests had been moved to it. This PR moves the remaining tests to this file. This should help de-clutter the main test file which has become too lengthy to read. 
Fixes #26830
>
>
>
>
>
>
>
>
=> chore: move MySQL datasource validation tests to a separate file

deploy/docker/fs/opt/appsmith/entrypoint.sh
[Slack Conversation](https://theappsmith.slack.com/archives/C0341RERY4R/p1694794275962369).
=> fix: Fix escaping for _multiple_ single quotes in env variables

deploy/docker/fs/opt/appsmith/run-postgres.sh
When PostgreSQL starts, we see the following errors in the logs:
```
mkdir: 
cannot create directory ‘/tmp/appsmith/postgres-stats’
: Permission denied
```
And then this over and over again:
```
postgres stdout | 2023-09-19 15:34:34.504 UTC [1759] LOG:  could not open temporary statistics file "/tmp/appsmith/postgres-stats/global.tmp": No such file or directory
```
The problem is that in `postgres.conf`, we set `user=postgres`, which doesn't have access to create things in `/tmp`.
This PR removes this configuration and lets the default be, which will be a temp folders _under_ the data directory.
=> fix: Postgres permission error in creating the stats folder

deploy/docker/fs/opt/appsmith/run-java.sh
When running with a custom `PORT` env variable, NGINX server will be listening on this port. In the backend's startup script, `run-java.sh`, we're checking for RTS being up or not, at `localhost`. So when the port is not 80, then this will never succeed, because it'll be looking for NGINX at the wrong port.
Instead, the fix here will make the backend startup script hit RTS _directly_ on RTS server's own port, instead of going via NGINX. This means it's independent of both the `PORT` env variable and the NGINX server, and only dependent on RTS being up, which is really what we want here.
=> fix: Fix backend failing to start when running with a custom PORT

app/server/appsmith-server/src/main/java/com/appsmith/server/aspect/FeatureFlaggedMethodInvokerAspect.java, app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/InstanceConfig.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/InstanceConfigHelperImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/InstanceConfigHelperCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/InstanceConfigHelperCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/FeatureFlagServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/FeatureFlagServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/aspect/FeatureFlaggedMethodInvokerAspectTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/aspect/component/TestComponentImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/aspect/component/ce/TestComponentCE.java, app/server/appsmith-server/src/test/java/com/appsmith/server/aspect/component/ce/TestComponentCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/FeatureFlagServiceCETest.java
In the current implementation, only reactive methods can be bifurcated based on feature flag status. This limitation arises from the fact that the method invoker aspect class relies on `featureFlagService.check`, which operates in a reactive manner. With the introduction of this PR, we're addressing this limitation by introducing a new class-level variable. This variable is updated each time tenant-level flags are retrieved. For reactive methods, we continue to utilize the reactive `featureFlagService.check` functionality, preserving the option to explore user-level flag experimentation.      
Fixes https://github.com/appsmithorg/appsmith/issues/27450
>
>
>
>
>
> Link …
=> feat: Introduce support for non-reactive method to bifurcate the implementation based on feature flag status

app/client/src/components/editorComponents/CodeEditor/EditorConfig.ts, app/client/src/components/editorComponents/CodeEditor/assistiveBindingHinter.ts, app/client/src/components/editorComponents/CodeEditor/commandsHelper.ts, app/client/src/components/editorComponents/CodeEditor/index.tsx
Removes DataTree and customDataTree from hinter's interface since they are no longer relevant.
>
>
>
>
>
>
>
>
>
>
>
=> chore: normalise code editor hinter interface

app/client/src/pages/AdminSettings/FormGroup/TagInputField.tsx
Removing styles from instance admin emails to avoid keeping it a scrollable input
=> chore: Removing styles from instance admin emails to avoid keeping it a scrollable input

app/client/src/workers/common/DataTreeEvaluator/index.ts, app/client/src/workers/common/DataTreeEvaluator/test.ts
Reverting change for skip klona changes, this commit reverts the fix for https://github.com/appsmithorg/appsmith/issues/27048
Fixes #27048
>
>
>
>
>
>
>
=> fix: revert skip klona

app/server/appsmith-server/src/main/java/com/appsmith/server/aspect/FeatureFlaggedMethodInvokerAspect.java
This Fixes the problem of more than one capital letter in the feature flagged class name start like PACConfigurationService.
=> feat: fix more than one capital letter in class name start

app/client/packages/design-system/theming/src/color/src/DarkModeTheme.ts, app/client/packages/design-system/theming/src/color/src/LightModeTheme.ts, app/client/packages/design-system/widgets/src/styles/src/textInputStyles.ts
Closes #26854
Increased contrast by lowering lightness shift, increasing opacity of placeholder element to 100%. Current on the right
=> chore: WDS `fgNeutralSubtle` fine-tuning

app/client/cypress/e2e/Regression/ClientSide/ExplorerTests/Pin_spec.js
In the test we were looking for the add js libraries button, but we cannot add js libraries on airgap. So skipping add libraries from the assertion list.
=> chore: fix airgap explorer test

app/server/appsmith-git/pom.xml, app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/SshTransportConfigCallback.java
Should resolve the following CVE reports:
1. https://github.com/appsmithorg/appsmith/security/dependabot/263
1. https://github.com/appsmithorg/appsmith/security/dependabot/264
=> chore: fix the jgit version updates in other places

app/client/src/ce/selectors/entitiesSelector.ts, app/client/src/components/editorComponents/CodeEditor/utils/sqlHint.ts
This PR adds autocomplete support for table schema on SQL editor. It also increases (slightly) the number of showable autocompletion hint options to 270.
Fixes #27163 
>
>
>
>
>
>
>
>
>
>
=> feat: Add autocomplete support for table schema on SQL editor

app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/DatasourceDropdown/useDatasource.tsx
Fixes https://github.com/appsmithorg/appsmith/issues/27555
>
>
>
>
>
>
>
>
> …
=> fix: [airgap] use local assets url in one click binding

app/client/src/pages/Editor/IntegrationEditor/IntegrationsHomeScreen.tsx
Removing saas integrations section on the datasources page for airgap, as it is not supported.
Fixes [#27544](https://github.com/appsmithorg/appsmith/issues/27544)
=> fix: Removing saas integrations section on datasources page for airgap

app/client/src/pages/Editor/gitSync/ReconnectDatasourceModal.tsx, app/client/src/sagas/DatasourcesSagas.ts
This PR fixes issue with gsheet import and redirection. When an application containing a couple of datasources like mysql, postgres and gsheet are imported, we are shown reconnect datasource modal, suppose we first configure all datasources except gsheet, lastly we select gsheet datasource and save and authorise, we are not being redirected to authorisation.
The issue occurred because after saving each datasource, that datasource was disappearing from the list of datasources shown on left panel in reconnect datasource modal, so if we configure gsheet datasource at last, it would remove datasource from the list and lose all the context. So the request sent to `/oauth` endpoint would be cancelled.
This PR essentially solves 2 issues:
- datasource disappearing from left panel in reconnect …
=> fix: gsheet issue with import and redirection fixed

app/server/appsmith-server/src/main/java/com/appsmith/server/constants/ce/FieldNameCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/PluginScheduledTaskUtilsCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ConfigServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ConfigServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/PluginServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/PluginScheduledTaskImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PluginScheduledTaskCEImpl.java
Contains changes to make sure workspaces update only when a new plugin is added to cs.
=> chore: Added checks to only return plugins when new updates are present

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PluginScheduledTaskCEImpl.java
In order to not skip plugin init
=> chore: Fixed flatmapping cs req

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java, app/server/appsmith-server/src/test/resources/test_assets/ImportExportServiceTest/valid-application-without-action-collection.json
This fixes the NPE when the user is trying to import an application JSON that has no action collection.
Fixes #27646
N/A
>
=> fix: NPE during import when ApplicationJson has no action collection

app/client/packages/rts/build.sh, app/client/packages/rts/package.json, app/client/yarn.lock
Use separate specifici `esbuild` for building RTS, instead of reusing the one coming from storybook.
As recommended in [this comment](https://github.com/appsmithorg/appsmith/pull/27310#pullrequestreview-1652734575).
=> chore: Use separate specific esbuild for RTS

app/client/src/ce/reducers/uiReducers/applicationsReducer.tsx
We removed the clone/duplication feature, but if an app for some reason has an empty navigation settings object - it doesn't show any pages in the navbar nor any of the customization options for navigation inside the app settings pane. This PR adds a check for this and uses the default navigation settings as a fallback.
Fixes #27721
Fixes #23565
To recreate this scenario, we can import this app that has an empty navigation settings object. [App JSON here.](https://github.com/appsmithorg/appsmith/files/12791775/navigationSettingsEmptyObject.json.zip)
>
>
>
>
>
>
>
=> fix: If navigation settings object is empty in application details, use the default settings

deploy/docker/fs/opt/appsmith/templates/nginx-app.conf.sh
In the NGINX configuration we generate, we're redirecting _all_ HTTP requests to HTTPS, when HTTPS is enabled. But the HTTP-01 challenge works on port 80 and is getting redirected to 443.
This usually fine, as Let's Encrypt respects that redirect and completes the challenge on port 443. But, if port 443 is blocked to outside access, the cert renewal will fail. This PR fixes that.
Tested on a server with port 80 open and 443 closed to outside Internet. Cert renewal fails without this PR's changes, and works with this PR's changes.
=> fix: Route for HTTP-01 challenge, instead of redirecting

Dockerfile, deploy/docker/fs/opt/appsmith/entrypoint.sh
This removes ~70 medium/low severity CVEs reported on our Docker image, by removing `build-essential` from being installed by default in the Docker image.
We only need it when compiling Redis, which is needed on _some_ ARM systems, that re configured with a page-size of greater than 4096. For example, CentOS 8.
=> chore: Remove `build-essential` by default in the Docker image

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration025AddIndexDeletedInApplication.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration026AddIndexTenantAndDeletedInWorkspace.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration027AddIndexDatasourceIdAndDeletedInAction.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCEImpl.java
> Adding indices to classes
- Workspace (`tenantId`, `deleted`, `deletedAt`)
- Application (`deleted`, `deletedAt`)
- NewAction ((`unpublishedAction.datasource._id`, `deleted`, `deletedAt`),  (`publishedAction.datasource._id`, `deleted`, `deletedAt`))
Fixes #23360 
=> chore: adding indices to workspace, application and newAction class

app/client/src/widgets/FormWidget/widget/index.tsx
- Remove autoDimension observation of FormWidget's height. It is causing an infinite loop.
=> fix: remove dimension observation for form widget

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/UserUtilsCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/PACConfigurationService.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/PACConfigurationServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/PACConfigurationServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/PACConfigurationServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce_compatible/PACConfigurationServiceCECompatible.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce_compatible/PACConfigurationServiceCECompatibleImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce_compatible/UserServiceCECompatibleImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/PACConfigurationServiceCETest.java
Fetching super admin permission group without user context check using retrieveById.
=> chore: Using retrieve by id for fetching super admin permission group

app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationSuccessHandlerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/filters/PreAuth.java, app/server/appsmith-server/src/main/java/com/appsmith/server/ratelimiting/RateLimitConfig.java, app/server/appsmith-server/src/main/java/com/appsmith/server/ratelimiting/RateLimitService.java, app/server/appsmith-server/src/main/java/com/appsmith/server/ratelimiting/RateLimitServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/ratelimiting/aspects/RateLimitAspect.java, app/server/appsmith-server/src/main/java/com/appsmith/server/ratelimiting/ce/RateLimitServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/ratelimiting/ce/RateLimitServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java
Refactor : While debugging the production downtime, took a deeper look into the code path of rate limiting. Blocking calls to redis were being made on the main threads which can impact the overall response times of the appsmith server (since the number of main threads equals no of CPUs on the machine). No blocking calls should be made in the main thread. Moving executions to bounded elastic threadpool and making the reset flow reactive. Also the code was not split according to the code split guidelines of the server. Taking care of that as well.
=> fix: Making login rate limit service reactive

Dockerfile
=> chore: Install NodeJS manually instead of with the deprecated script

app/client/src/ce/constants/messages.ts, app/client/src/ce/pages/Applications/ApplicationCardList.tsx
Change in no apps message in home page
Fixes #27775
>
>
>
>
>
>
>
>
>
>
>
>
=> chore: No apps message changes in workspace home page

app/client/.husky/check-staged-files.sh, app/client/.lintstagedrc.json
1. Optimise `lint-staged` scripts so that they are not executed twice. For some patterns, I removed the `prettier` checks since they are executed by`eslint` checks as well.
2. Add caching for all scripts.
3. Optimisation of the `git secrets`, now we check only staged files. Earlier we checked all the files that `git ls-files` returns. [Here more about this.](https://github.com/awslabs/git-secrets#options-for-scan).
=> fix:lint staged

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/FeatureFlagConfig.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/FeatureFlagServiceCEImpl.java
PR for updating the FF4J configuration to avoid auto-creating the feature flags for FF4J if the same is not present in the FF4J context. 
We are planning to remove the FF4J dependency but with this change the flakiness we are seeing in EE codebase will be fixed. This is because with auto-creation enabled FF4J tries to add the flag to the feature store. This ends up in ConcurrentModification exceptions for the `LinkedHashmap` which is being used under the hood.    
Ref thread: https://theappsmith.slack.com/archives/CPQNLFHTN/p1697109849578459
Fixes https://github.com/appsmithorg/appsmith-ee/issues/2635
>
>
>
=> chore: Remove autogeneration of feature flag if the same is not present in `FF4J` context

.github/workflows/perf-test-v2.yml, .github/workflows/perf-tests-command.yml
-  Run perf tests in parallel
- Remove v2 from /perf-test workflow as we can run v2 by passing the ref
Fixes #23791
=> ci:  Run perf tests in parallel

app/client/cypress_ci_custom.config.ts
- This PR skips MsSQL_Basic_Spe.ts from CI runs since its runing out of memory in multiple CI runs
- Until this is added to TED or we find other ways - will be run locally during regression
=> test: Cypress | Skip MsSQL_Basic_Spec.ts spec in CI

.github/workflows/perf-tests-command.yml
-  Run perf tests in parallel
- Remove v2 from /perf-test workflow as we can run v2 by passing the ref
Fixes #23791
=> ci: Add perf v2 job to perf test command

Dockerfile, deploy/docker/fs/opt/appsmith/entrypoint.sh, deploy/docker/fs/opt/appsmith/mongodb-fixer.sh
Tests:
```
root@3d74d52465e2:/opt/appsmith# mongo --version
MongoDB shell version v4.4.18
Build Info: {
"version": "4.4.18",
"gitVersion": "8ed32b5c2c68ebe7f8ae2ebe8d23f36037a17dea",
"openSSLVersion": "OpenSSL 1.1.1f  31 Mar 2020",
"modules": [],
"allocator": "tcmalloc",
"environment": {
"distmod": "ubuntu2004",
"distarch": "x86_64",
"target_arch": "x86_64"
}
}
root@3d74d52465e2:/opt/appsmith# mongo --host mongodb://appsmith:yCPaeoA3wx2JR@localhost:27017/appsmith
MongoDB shell version v4.4.18
connecting to: mongodb://localhost:27017/appsmith?compressors=disabled&gssapiServiceName=mongodb
Implicit session: session { "id" : UUID("fd2d11fd-f5f6-457b-a16d-8437ba2d9872") }
MongoDB server version: 4.4.18
---
The server generated these startup warnings when booting: …
```
=> chore: Update embedded MongoDB Schema version

app/client/src/components/editorComponents/CodeEditor/hintHelpers.test.ts, app/client/src/components/editorComponents/CodeEditor/hintHelpers.ts, app/client/src/components/editorComponents/CodeEditor/utils/sqlHint.ts
This PR adds unit tests for the SQL hinter class. It tests that the number of hints shown is never greater than the threshold set[ here](https://github.com/appsmithorg/appsmith/pull/27329)
Fixes #27757 
- 
>
>
>
>
>
>
=> chore: SQL hinter automated test

app/client/src/pages/UserAuth/SignUp.tsx
Adds a try catch around the recaptcha code on signup page. This is handled similarly else where in the code base. https://github.com/appsmithorg/appsmith/blob/release/app/client/src/widgets/ButtonWidget/component/index.tsx#L361.
The intention here is to catch the [timeout](https://github.com/appsmithorg/appsmith/issues/20764) error and not log to sentry as it isn't really crashing the app. There is a lot of sentry logs for this originating from the signup page. 
Fixes https://github.com/appsmithorg/appsmith/issues/20764
>
>
>
>
>
>
>
=> chore: add try catch for signup recaptcha

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/InstanceConfig.java
In addition to the polling loop that waits for backend to be ready to delete the loading page, this PR will make the backend also try and delete the loading page once it's ready to accept incoming requests.
Tested locally.
=> fix: Race condition in deleting the loading page

app/client/src/pages/setup/constants.ts
With https://github.com/appsmithorg/appsmith/issues/27915 issue, we changed the profiling questions during new user onboarding. However, the subtexts to the options should be changed according to the new [design](https://www.figma.com/file/kbU9xPv44neCfv1FFo9Ndu/User-Activation?type=design&node-id=3134-18334&mode=design&t=m8UYj5Qkl3iBplFk-0).
Fixes #28159
>
>
>
>
>
>
>
>
=> feat: change the subtexts for options to profiling questions

deploy/docker/fs/opt/appsmith/entrypoint.sh
Cherry pick fix for when Supervisor credentials are missing in env variables.
=> fix: Fail startup when supervisor creds are missing

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/constants/PluginConstants.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceContextServiceTest.java
> Rest Api used cached datasourceContext which was providing older tokens. Now when we look for  datasourceContext we provide a new context.
Fixes #27699 
=> fix: removed datasourceContextCaching for RestAPI

app/client/src/widgets/MultiSelectWidgetV2/component/index.styled.tsx
Checkboxes in the multi select widget should be positioned to the left and not right 
Fixes #28100
> Link issues raised during DP testing for better visibility and tracking (copy link from comments dropped on this PR)
=> fix: multi-select dropdown checkbox alignment regressed

app/client/cypress/support/commands.js
In the cypress test suite,post super user is registered we should only wait for getWorkspace in the CE repo since the EE repo has the License plan selection page.
Fixes #28140 
>
>
>
>
>
>
>
>
>
>
>
=> fix: wait for getWorkspace only in CE repo

app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java, app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java
- Add check for column value being `null` when column type is `JSON`. This check was mistakenly not added before. Adding it now as part of this PR. 
- Add JUnit TC. 
Fixes #27645 
>
>
>
>
>
>
>
>
=> fix: MySQL plugin: add check for null column value for JSON column type

app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserServiceWithDisabledSignupTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/ApplicationServiceCETest.java
> ApplicationServiceCETest is flaky in the setup, so breaking down the setup into multiple steps to pinpoint the failure.
=> chore: changes to pinpoint errors in ApplicationServiceCETest

app/client/src/constants/TemplatesConstants.ts, app/client/src/pages/Editor/CommunityTemplates/Modals/CommunityTemplatesPublishInfo.tsx
Adds link for `learn more` buttton in publish to community template modal.
Fixes #28218
>
>
>
>
>
>
>
>
>
>
=> fix: `learn more` button on community templates

app/client/packages/design-system/theming/src/theme/src/ThemeProvider.tsx, app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx, app/client/src/layoutSystems/anvil/common/hooks/useWidgetBorderStyles.ts, app/client/src/layoutSystems/common/draggable/DraggableComponent.tsx, app/client/src/layoutSystems/common/mainContainerResizer/MainContainerResizer.tsx, app/client/src/sagas/AutoLayoutUpdateSagas.tsx, app/client/src/sagas/autoHeightSagas/index.ts
Fixes #28203 
- Borders are added to widgets separately now, as there is no resizer in Anvil
- Fix main container jump when hovering over the main container resizer
- Add height 100% to themeprovider so that the layout preset for main canvas can render correctly
- Stop widgets from focusing in preview mode
- Prevent AutoHeight Sagas from running in Anvil
- Prevent Auto Layout sagas from running in Anvil
=> fix: Misc. fixes for anvil

app/server/appsmith-server/src/main/java/com/appsmith/server/actioncollections/exports/ActionCollectionExportableServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/actioncollections/imports/ActionCollectionImportableServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/datasources/exports/DatasourceExportableServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/datasources/imports/DatasourceImportableServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/exports/exportable/ExportableServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/exports/internal/ExportApplicationServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/imports/importable/ImportableServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/imports/internal/ImportApplicationServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/jslibs/exports/CustomJSLibExportableServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/jslibs/imports/CustomJSLibImportableServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/newactions/exports/NewActionExportableServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/newactions/imports/NewActionImportableServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/newpages/exports/NewPageExportableServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/newpages/imports/NewPageImportableServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/onpageload/internal/PageLoadExecutablesUtilCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/plugins/exports/PluginExportableServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/plugins/imports/PluginImportableServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/themes/exports/ThemeExportableServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/themes/imports/ThemeImportableServiceCEImpl.java
Breaks down all the exportable and importable methods into structured calls to parallelize where possible, and enable overriding.
=> chore: Refactored import and export svc methods for modularity

app/client/cypress/e2e/Regression/ClientSide/Autocomplete/PropertyPaneSuggestion_spec.ts, app/client/cypress/e2e/Regression/ClientSide/Widgets/Others/Autocomplete_spec.js, app/client/packages/ast/src/index.ts, app/client/packages/ast/src/utils.ts, app/client/src/ce/sagas/index.tsx, app/client/src/sagas/TernSaga.ts, app/client/src/utils/autocomplete/AutocompleteSortRules.ts, app/client/src/utils/autocomplete/CodemirrorTernService.ts, app/client/src/utils/autocomplete/__tests__/TernServer.test.ts, app/client/src/utils/autocomplete/dataTypeSortRules.ts
This PR improves autocompletion hints discovery by
- Taking entities' recency of usage into consideration when sorting hints
- Showing entity names at the top, before supported functions and properties
- Deprioritizing the Function constructor and the MainContainer entity
Fixes #27870 
Fixes #17684 
Fixes https://github.com/appsmithorg/appsmith/issues/24975
>
>
>
>
>
https://github.com/appsmithorg/appsmith/pull/28222#issuecomment-1777487126
>
>
>
=> fix: improve autocompletion hints discovery

app/server/appsmith-server/src/main/java/com/appsmith/server/actioncollections/imports/ActionCollectionImportableServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/newactions/imports/NewActionImportableServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/newpages/imports/NewPageImportableServiceCEImpl.java
Since pageMap contains duplicates from unpublished and published pages, any computation done on top of it needs to use only the distinct list from the value set of this map. This fix ensures we use distinct object references only.
Fixes #28377
=> chore: Fixes imported action refs getting reset to null in layouts

app/client/src/widgets/IframeWidget/widget/index.tsx
> This is a second attempt to add an "isVisible" property to the iframe widget. The first attempt (PR: #28243) became too messy due to rebasing. 
>
> In this current PR, an "isVisible" property is added to the iframe widget, consistent with how other widgets work. 
>
>
Fixes #27991 
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
=> fix: Feature/iframe dynamic visibility (2nd attempt)

app/client/src/pages/AppViewer/utils.ts, app/client/src/widgets/WidgetUtils.ts
Renaming the widget utility function `calulateHoverColor` to `calculateHoverColor`.
Reason: typo
Fixes: 
#28473
=> fix: calculateHoverColor typo

.github/workflows/github-release.yml
Add Build arguements to github-release build and push pipeline
=> fix: failing github-release pipeline

.github/workflows/integration-tests-command.yml, .github/workflows/integration-tests-with-documentdb-command.yml, .github/workflows/test-build-docker-image.yml
Disables automated perf tests on CI that are no longer used. Saves CI costs by about 2.4%
Fixes #28510
=> ci: Disable perf tests on CI

app/client/src/workers/Evaluation/handlers/__tests__/jsLibrary.test.ts, app/client/src/workers/Evaluation/handlers/jsLibrary.ts
This fixes the installation of libraries in native ESM build which doesn't contain a default export. 
**Root cause**:
ESM builds are flattened and the default export is added to the prototype chain of the library object. When the default export is empty, the installation fails at Object.create (prototype creation) step.
>
>
Fixes #28576 
>
>
>
>
>
>
>
>
>
=> fix: Installation of libraries without a default export

app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug28287_Spec.ts, app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
This PR fixes second part of the issue #28287 . First part, where data was not getting shown in response tab even if data is present, was fixed in PR #28296 . Second part is where we want to keep the debugger tab open, when query response is present. Its fixed in this PR.
https://github.com/appsmithorg/appsmith/assets/30018882/09e390a7-a311-4200-9e3f-71a0cd241a4f
Fixes #28428 
>
>
>
>
>
>
>
>
> Add …
=> fix: response tab open by default in case of page load query

app/client/cypress/e2e/Regression/ClientSide/Widgets/Input/RTL_support.ts, app/client/cypress/e2e/Regression/ClientSide/Widgets/Multiselect/RTL_support.ts, app/client/cypress/e2e/Regression/ClientSide/Widgets/Select/RTL_support.ts, app/client/src/ce/entities/FeatureFlag.ts, app/client/src/widgets/BaseInputWidget/component/index.tsx, app/client/src/widgets/BaseInputWidget/widget/index.tsx, app/client/src/widgets/InputWidgetV2/component/index.tsx, app/client/src/widgets/InputWidgetV2/widget/index.tsx, app/client/src/widgets/MultiSelectWidgetV2/component/index.styled.tsx, app/client/src/widgets/MultiSelectWidgetV2/component/index.tsx, app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx, app/client/src/widgets/SelectWidget/component/SelectButton.tsx, app/client/src/widgets/SelectWidget/component/index.styled.tsx, app/client/src/widgets/SelectWidget/component/index.tsx, app/client/src/widgets/SelectWidget/constants.ts, app/client/src/widgets/SelectWidget/widget/index.tsx, app/client/src/widgets/components/LabelWithTooltip.tsx
Fixes https://github.com/appsmithorg/appsmith/issues/28469
>
>
>
>
>
>
>
>
> Add Testsmith test cases links that relate to this …
=> feat: RTL support for input, select and multi-select widget

app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce_compatible/GitServiceCECompatibleImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/GitServiceCETest.java
This PR makes the update branch protection API transactional.
Fixes #28648
>
>
>
=> chore: Add transactional to the update protected branches

deploy/docker/base.dockerfile
The current latest release at https://github.com/adoptium/temurin17-binaries/releases/tag/jdk-17.0.9%2B9.1, doesn't include binaries for Linux, and so the Java download step fails in our base Docker image build. This PR fixes that.
Sidenote, had we not had this base image and application image separation, this bug would've blocked all our CI pipelines and the whole team. 🙂
=> chore: Java download URL in base image dockerfile

app/client/src/ce/entities/FeatureFlag.ts, app/server/appsmith-server/src/main/java/com/appsmith/server/featureflags/FeatureFlagEnum.java
- For feature flag `ab_onboarding_flow_start_with_data_dev_only_enabled`:
- add default value on the client 
- add it to the list of available feature flags that can be used on the API server. 
Fixes #28548 
>
- It seems not possible to add automation test for this change at the moment. 
>
>
>
>
>
=> chore: add default value for feature flag on the client side

app/client/cypress/support/Pages/GitSync.ts, app/client/src/actions/gitSyncActions.ts, app/client/src/ce/constants/messages.ts, app/client/src/ce/entities/FeatureFlag.ts, app/client/src/ce/utils/planHelpers.ts, app/client/src/components/editorComponents/GlobalSearch/HelpBar.tsx, app/client/src/constants/ThirdPartyConstants.tsx, app/client/src/layoutSystems/common/dropTarget/DropTargetComponentWrapper.tsx, app/client/src/pages/AppViewer/PrimaryCTA.test.tsx, app/client/src/pages/AppViewer/PrimaryCTA.tsx, app/client/src/pages/Editor/EditorHeader.tsx, app/client/src/pages/Editor/GlobalHotKeys/GlobalHotKeys.tsx, app/client/src/pages/Editor/WidgetsEditor/MainContainerWrapper.tsx, app/client/src/pages/Editor/WidgetsEditor/NavigationPreview.tsx, app/client/src/pages/Editor/gitSync/QuickGitActions/index.tsx, app/client/src/pages/Editor/gitSync/Tabs/ConnectionSuccess.tsx, app/client/src/pages/Editor/gitSync/Tabs/GitSettings/GitDefaultBranch.tsx, app/client/src/pages/Editor/gitSync/Tabs/GitSettings/GitProtectedBranches.tsx, app/client/src/pages/Editor/gitSync/Tabs/GitSettings/constants.ts, app/client/src/pages/Editor/gitSync/Tabs/GitSettings/hooks.ts, app/client/src/pages/Editor/gitSync/Tabs/Merge.tsx, app/client/src/sagas/GitSyncSagas.ts, app/client/src/selectors/gitSyncSelectors.tsx
- Adds license flag for branch protection
- Disables omni-bar and keyboard shortcuts for protected branches
- Adds navigation for multiple pages
- Hides preview on protected views
- Adds feature flag for Git Connection Success
Fixes #28056 
>
>
>
>
>
>
>
>
=> fix: git branch protection fixes

app/client/cypress/e2e/Regression/ClientSide/SetProperty/WidgetPropertySetters2_spec.ts, app/client/cypress/limited-tests.txt
- This PR fixes /SetProperty/WidgetPropertySetters2_spec.ts flaky CI behavior
-
=> test: Cypress | CI Flaky fix

app/client/src/components/editorComponents/EntityExplorerSidebar.tsx
After new sidebar, existing entity explorer was not taking full height and was causing issues in scrolling the canvas. This PR fixes that issues.
Fixes https://github.com/appsmithorg/appsmith/issues/28710
>
>
>
>
>
>
>
=> fix: Extra space is being introduced at the bottom of the canvas on scrolling down

app/client/src/pages/Editor/DataSourceEditor/DatasourceSection.tsx
Fixed css for view mode of DS config, change affects only EE feature custom environments
Fixes #28439
>
>
>
>
>
>
>
>
> Add …
=> chore: fix css for DS view mode

app/client/src/pages/Editor/AppSettingsPane/AppSettings/index.tsx
Sets the App Settings state to closed when navigating away from App Settings
Fixes #28736
>
>
>
>
>
>
>
>
=> fix: App settings navigating out fixes

app/client/src/pages/AppViewer/index.tsx
Fixed logic check for showing bottom bar from `environmentList.length  &&` to `environmentList.length > 0 &&`. This was causing the variable to be set as o instead of false.
Fixes #28778
>
>
>
>
>
>
> …
=> chore: fixed logic for bottom bar visibility

app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug28750_Spec.ts, app/client/cypress/e2e/Regression/ClientSide/BugTests/DatasourceSchema_spec.ts, app/client/cypress/support/Pages/DataSources.ts, app/client/src/ce/constants/messages.ts, app/client/src/pages/Editor/DatasourceInfo/DatasourceStructure.tsx, app/client/src/pages/Editor/DatasourceInfo/DatasourceStructureContainer.tsx
This pr fixes:
- Let schema table accordions be closed on searching table
- Search placheholder changed to `Search for table`
Fixes #28750 
>
>
>
>
>
>
>
>
> Please describe the tests that you ran to verify …
=> fix: schema accordions don't open on search, placeholder for search input

app/client/src/pages/Editor/DataSourceEditor/DSFormHeader.tsx, app/client/src/pages/Editor/DataSourceEditor/DatasourceBlankState.tsx, app/client/src/pages/Editor/IDE/LeftPane/CreateDatasourcePopover.tsx
Recently added the Generate Page button on the Datasource screen. This change will ensure the button only shows up if the Datasource is authorised. It will also disable the button if the user does not have the appropriate permissions
We made a change to disable the add button recently but the expectation is that the button is not visible at all
=> fix: Further DS Sidebar permission fixes

app/client/cypress/scripts/util.ts, app/client/package.json, app/client/yarn.lock
From AWS SDK for JavaScript v2 [README](https://github.com/aws/aws-sdk-js):
> We are formalizing our plans to make the Maintenance Announcement (Phase 2) for AWS SDK for JavaScript v2 in 2023.
This PR migrates AWS SDK for JavaScript v2 APIs to v3 using [aws-sdk-js-codemod](https://www.npmjs.com/package/aws-sdk-js-codemod).
```console
$ npx aws-sdk-js-codemod@0.26.1 -t v2-to-v3 app/client/cypress/scripts/util.ts
```
Required as AWS SDK for JavaScript v2 will be put into maintenance
N/A
ToDo
ToDo
ToDo
=> chore: migrate AWS SDK for JavaScript v2 APIs to v3

Dockerfile, deploy/docker/fs/opt/appsmith/entrypoint.sh, deploy/docker/fs/opt/appsmith/renew-certificate.sh, deploy/docker/fs/opt/appsmith/run-with-env.sh, deploy/docker/fs/opt/appsmith/templates/supervisord/cron.conf
Running an Appsmith as a non-root user:
```sh
docker run --name appsmith --user 70:70
```
The `70:70` figures are the UID and GID respectively. It can mostly be any number, safe to user figures are 70 to 79, or anything above 200 and below 65000. The important bit, is that it shouldn't change on restart or manual updates etc.
No product functionality should be affected when running as a non-root user.
=> feat: Support running as a non-root user

app/client/src/ce/entities/FeatureFlag.ts, app/client/src/ce/pages/Editor/routes.tsx, app/client/src/components/editorComponents/EntityExplorerSidebar.tsx, app/client/src/navigation/featureFlagHooks.ts, app/client/src/pages/Editor/AppSettingsPane/PaneHeader.tsx, app/client/src/pages/Editor/CanvasPropertyPane/index.tsx, app/client/src/pages/Editor/DataSourceEditor/JSONtoForm.tsx, app/client/src/pages/Editor/EditorHeader.tsx, app/client/src/pages/Editor/EditorName/NavigationMenuData.ts, app/client/src/pages/Editor/Explorer/EntityExplorer.tsx, app/client/src/pages/Editor/IDE/LeftPane/index.tsx, app/client/src/pages/Editor/IDE/MainPane/index.tsx, app/client/src/pages/Editor/IDE/Sidebar/index.tsx, app/client/src/selectors/ideSelectors.tsx, app/client/src/utils/hooks/useDynamicAppLayout.tsx
Adds a new feature flag to control the rollout of the App sidebar. It needs to be different as the earlier feature flag was shipped to users already and they may not be on the latest version.
fixes: #28877
=> chore: Add an extra feature flag to control App sidebar rollout

app/client/src/ce/constants/messages.ts
Fixes a small typo in error message in welcome signup form.
=> fix: Typo in error message when passwords fields don't match.

.github/workflows/ci-test-custom-script.yml
Note: We have to create `LAUNCHDARKLY_BUSINESS_FLAGS_SERVER_KEY` secret before merging this PR.
=> chore: Add  `LaunchDarkly` configs in CI run to mock feature flags

app/client/src/pages/Editor/gitSync/QuickGitActions/index.tsx
When uncommitted changes and remote changes are present, protected branches should have pull enabled
Fixes #28900
>
>
>
>
>
>
>
>
>
>
>
=> fix: enable pull when branch is protected

deploy/docker/fs/opt/appsmith/entrypoint.sh
Fix issue with alias names clashing in `keytool -import` command, when there's more than one cert file in the `ca-certs` folder.
The fix is to explicitly set the alias for each `keytool -import` run, to the file itself, so clashes don't happen.
=> fix: Adding multiple certs in ca-certs folder

app/client/cypress/e2e/Sanity/Datasources/SMTPDatasource_spec.js, app/client/cypress/fixtures/SMTPTestdsl.json, app/client/src/sagas/ActionExecution/PluginActionSaga.ts
Sets query data to `undefined` when execution fails
Fixes #28817
>
>
>
>
>
>
>
> …
=> fix: Handle data update for query execution failure

app/client/cypress/e2e/Regression/ClientSide/Binding/ButtonWidgets_NavigateTo_validation_spec.js
The test failed while navigating to appsmith website where it was asserting text on website, changed it to assert URL instead.
>
locally
=> test: Cypress| fix ButtonWidgets_NavigateTo_Validation_spec.js

app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug28764_Spec.ts, app/client/src/components/editorComponents/CodeEditor/index.tsx
This PR ensures that the editor's input value is updated before code is linted.
Fixes #28764 
>
>
>
>
>
>
>
>
> Please describe the tests that you ran to verify your changes. Also list any relevant details …
=> fix: lint editor after input value is updated

app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug28731_Spec.ts, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/DatasourceDropdown/useSource/useConnectToOptions.tsx
In this PR, transformed API/Query data ( based on the widget's expected data type) is used after 1-click binding. This is aimed at improving 1-click binding success.
Fixes #28731 
>
>
>
>
>
>
>
>
> Please …
=> feat: Transform API/Query data based on widget's expected data type after 1-click binding

.github/workflows/ci-test-custom-script.yml
Note: We have to create `LAUNCHDARKLY_BUSINESS_FLAGS_SERVER_KEY` secret before merging this PR.
(cherry picked from commit 67d7e773b9325b0f710cdd697d8feb74abfba1a5)
=> chore: Add  `LaunchDarkly` configs in CI run to mock feature flags (#28761)

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationTemplateServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/ApplicationTemplateServicePublishTemplateTest.java
When the templates endpoint on cloud services is not reachable from the platform, toasts with a generic error message appear. The messaging needs to be improved to indicate that this owing to the templates (or any other relevant endpoint) on cloud services.
Fixes https://github.com/appsmithorg/appsmith/issues/23196
>
>
>
>
>
=> chore: Add error handling for the community template upload flow

app/server/appsmith-server/src/main/java/com/appsmith/server/refactors/applications/RefactoringSolutionCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/refactors/applications/RefactoringSolutionCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutCollectionServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/refactors/RefactoringSolutionTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceImplTest.java
Added `contextType` as a param for `isNameAllowed` method so that the method can be reused for other contexts as well.
=> chore: Added context type handling for isNameAllowed

app/server/appsmith-server/src/main/java/com/appsmith/server/exports/internal/PartialExportServiceCEImpl.java
Fix partial export for git connected apps. 
Fixes https://github.com/appsmithorg/appsmith/issues/28997
>
>
>
>
>
>
=> fix: partial export for git connected apps

app/server/appsmith-server/src/main/java/com/appsmith/server/imports/internal/PartialImportServiceCEImpl.java
Fix partial import issue in git connected app. When the update call was triggered due to the EncryptionHandler not being triggered there was Hex coded string issue for SSH keys. Replaced the update call parameter with the actual updates and not whole application object. 
Fixes https://github.com/appsmithorg/appsmith/issues/29000
>
>
>
=> fix: partial import for git connected apps

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/exceptions/pluginExceptions/AppsmithPluginError.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/OAuth2.java, app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/GlobalExceptionHandler.java
When we have google sheet datasource with invalid authorisation and if we create a query on it, it redirects us back to login page. This PR fixes that issue.
`Root cause:`
The issue occurred because when datasource has invalid authorisation, authenticationResponse property inside a datasourceConfig object is null, which results in exception being thrown by the API. This exception has status code of 401. Whenever client receives a response with 401 error code, it logs out the user and redirects them back to login page.
`Fix:`
In this PR, that exception status code is changed from 401 to 500, so that error is thrown but logout and redirection does not happen.
Fixes #28988 
>
>
> A video or a GIF is …
=> fix: gsheet invalid ds query redirect issue fixed

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ScheduledTaskCEImpl.java
PR for fixing the logs where we were referencing the feature flags are getting fetched from CS, which is not the case for airgapped version.
=> chore: Update logs for scheduled job for fetching tenant features

app/server/appsmith-server/src/test/java/com/appsmith/server/exceptions/GlobalExceptionHandlerTest.java
This PR adds junit test case to ensure that whenever there is appsmithPluginException on server, we never expose the plugin status code directly, instead we use generic 500 internal server error. The actual plugin status code is visible inside `response.status`.
Fixes #29037 
>
>
>
>
>
>
>
>
>
>
> Link issues raised during DP testing for better visiblity and tracking (copy …
=> chore: junit test added for catchPluginException to assert http status

.github/workflows/server-build.yml, app/server/pom.xml
=> ci: Add retry for JUnit failures in the CI workflow

app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/columnTypes/Select1_spec.ts, app/client/src/components/editorComponents/ActionCreator/index.tsx
This PR reverts the"No action"  cue in action selector
Fixes #29013 
<br/>
>
>
>
>
>
>
>
>
>
>
>
=> fix: Remove "No action"  cue in action selector

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/CreatorContextType.java
> Add workflow to the CreatorContextType enum
>
>
>
>
>
> Since we are only adding an enum, no testing required.
>
>
>
>
>
=> chore: add workflow creator context type

app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java, app/server/appsmith-plugins/amazons3Plugin/src/test/java/com/external/plugins/AmazonS3PluginTest.java
> This PR adds unsigned URLs in the response for single and multiple file uploads in s3. 
Fixes #28098 
>
>
>
>
>
>
>
>
=> feat: added unsigned url for single and multi-file uploads (#28098)

app/client/packages/rts/src/version.js
This will bring us one step closer to the `info.json` being the one source of truth for the version information. We shouldn't need the step to overwrite the contents of the `version.js` file during build in CI.
=> chore: Use version from info.json directly

app/client/src/ce/components/editorComponents/Debugger/ErrorLogs/getLogIconForEntity.tsx, app/client/src/ce/utils/getEntityPayloadInfo.ts, app/client/src/components/editorComponents/Debugger/ErrorLogs/components/LogEntityLink.tsx, app/client/src/ee/components/editorComponents/Debugger/ErrorLogs/getLogIconForEntity.tsx, app/client/src/entities/AppsmithConsole/index.ts
- Fix the widget icon in debugger 
- Makes the LogEntityLink component extendable 
Fixes #29144
>
>
>
>
>
>
>
>
=> fix: widget icon in debugger

app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug29131_spec.ts, app/client/src/ce/sagas/JSActionSagas.ts, app/client/src/sagas/ActionSagas.ts, app/client/src/workers/Evaluation/JSObject/index.ts, app/client/src/workers/common/DataTreeEvaluator/index.ts
> Repeated refactor operations seems to leave stale JS Objects in the dataTree causing the dataTree to occupy namespace that no longer exists. This seems to have stemmed from the `updateEvalTreeWithJSCollectionState` method in app/client/src/workers/common/DataTreeEvaluator/index.ts, where we update the existing evalTree with JSObjects and their variables from the previous unEvalTree. 
> This PR modifies `updateEvalTreeWithJSCollectionState` to not apply variable state to evalTree if the entity is not present.
Fixes #29162
>
>
>
>
- Bug fix (non-breaking change which fixes an …
=> fix: deleted JSObject names are not released for later use

app/client/src/components/editorComponents/ActionCreator/index.tsx, app/client/src/components/editorComponents/ActionCreator/viewComponents/Action/ActionSelector.tsx, app/client/src/components/editorComponents/ActionCreator/viewComponents/Action/ActionTree.tsx, app/client/src/components/editorComponents/ActionCreator/viewComponents/Action/index.tsx
> Pass down props from ActionSelector control all the way to action selector form component to render widget specific fields like currentRow, currentIndex etc in autocomplete in ActionSelector.
>
Fixes #29049 
>
>
>
>
>
>
>
>
=> fix: autocomplete for widget specific properties in action selector form fields

app/client/src/navigation/FocusSelectors.ts
This PR fixes the context switching bug in queries page.
Fixes https://github.com/appsmithorg/appsmith/issues/29201
>
>
>
>
>
>
>
>
=> fix: Context switching bug for queries

deploy/docker/base.dockerfile
This will install Caddy into the base image, ahead of incoming changes to replace NGINX and Certbot with Caddy.
=> chore: Install Caddy ahead of PR to enable Caddy support

.github/workflows/add-label.yml, .github/workflows/ci-test-custom-script.yml, .github/workflows/ci-test-hosted.yml, .github/workflows/ci-test-limited.yml, .github/workflows/ci-test-with-documentdb.yml, .github/workflows/ci-test.yml
Using `GITHUB_OUTPUT` to save environment variables instead. This is to remove lots of warnings in the CI run and make it easier to read the summary.
Refer: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> ci: Removing set-output in CI workflows as it's a deprecated command.

.github/workflows/client-build.yml, .github/workflows/rts-build.yml, .github/workflows/server-build.yml
This code is duplicated from generate_info_json.sh script, but that's temporary. We'll be moving towards not having the version computation in the workflows at all, and all components getting version information from `info.json` alone. Essentially treating `info.json` as the source of truth for this.
=> ci: Fix version calculation in workflows

scripts/generate_info_json.sh
Fixes #29506.
The version in `info.json` never had the `v` prefix, but we never used it for anything significant, so we never noticed it. Until in `v1.9.51`.
=> fix: Fix version name's `v` prefix in info.json

deploy/docker/fs/opt/appsmith/caddy-reconfigure.mjs, deploy/docker/fs/opt/appsmith/entrypoint.sh
We're setting the default value for APPSMITH_ALLOWED_FRAME_ANCESTORS before we initialize env variables from docker.env. This make the default value take a higher precedence over the value configured in docker.env. And since the value in docker.env is the one configured from Admin Settings, it feels like the value configured from the UI is being ignored.
This fixes the problem by moving the check for this env variable to inside the reconfigure script, and so doesn't affect any env variables.
=> chore: Cherry pick fix for frame-ancestors configuration

app/server/appsmith-server/pom.xml
As the code references for ff4j is already removed, this PR removes the entry from dependency list.
=> chore: Remove ff4j dependency from pom.xml

app/client/src/pages/Editor/GlobalHotKeys/GlobalHotKeys.test.tsx, app/client/src/pages/Editor/GlobalHotKeys/GlobalHotKeys.tsx
Removes hotkey for Pinning Entity Explorer as it is not used anymore. 
Removes hotkey for preview mode as it ill designed and causes problems with new users
=> fix: remove hotkey shortcuts for Entity Explorer and Preview mode

app/client/package.json, app/client/yarn.lock
Issue: Admin settings embedded setting tag was rendering a radio button inside.
Cause: In design system, while styling the radio button, it was only looking for child span. This means any span comes inside the Radio button children, will be considered as the radio part.
Fixes https://github.com/appsmithorg/appsmith/issues/28889
>
>
>
>
>
>
>
>
=> fix: Admin setting radio button issue

app/client/src/layoutSystems/anvil/integrations/sagas/pasteSagas.ts, app/client/src/layoutSystems/anvil/layoutComponents/presets/ModalPreset.tsx, app/client/src/layoutSystems/anvil/utils/constants.ts, app/client/src/widgets/wds/WDSModalWidget/widget/index.tsx
1. Add copy paste functionality for Modal. The behaviour has to be similar to MainCanvas.
2. Introduce a min-height for modal preset for easy DnD of widgets.
https://github.com/appsmithorg/appsmith/assets/5424788/dc68aec6-b966-46a8-a3a1-1500088b3832
=> feat: add copy paste functionality for modal widget

app/server/appsmith-server/src/main/java/com/appsmith/server/domains/TenantConfiguration.java, app/server/appsmith-server/src/test/java/com/appsmith/server/domains/EqualityTest.java
Lack of checking fields in parent's class meant that the `.equals()` method from `@Data` annotation in `TenantConfiguration` never compared the values of fields in parent class. This meant that some part of Hibernate's dirty-checking is getting thrown off, and changes to TenantConfiguration aren't getting saved to database in Postgres.
Lombok even warns about this exact thing, but it's unfortunate we don't take warnings as seriously as errors.
So instead, I added a test which would fail when this annotation is missing in cases like this.
=> chore: Fix `equals` on `TenantConfiguration`

app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/BaseAppsmithRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/params/QueryAllParams.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/BaseService.java
Extending the fluent repository API to `queryAllWithStrictPermissionGroups`.
=> chore: Fluent API for strict permission query

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/UserSignupCEImpl.java
On signup failure, we need to redirect the client to same signup page they were on, for the error message to show up. So instead of redirecting to the homepage, we get the path from the incoming request and use that.
=> fix: Signup error redirect to wrong path

app/client/packages/design-system/theming/src/token/src/tokensConfigs.json
Closes #30890 
This is not a full refinement, because we set height/block-size explicitly for some of our widgets with styles [such as these](https://github.com/appsmithorg/appsmith/blob/0d16dc0382b8fdd46dba8b5dc65c7cfc7c496c03/app/client/packages/design-system/widgets/src/components/Button/src/styles.module.css#L171). As such, changes to e.g. inner spacing only affect the horizontal/inline size and not the vertical/block one since the block padding doesn't affect an element that has block size set explicitly.
Ideally, we should switch to implicit sizing to fully embrace multi-dimensional sizing and density theming control over the widget dimensions (i.e. control it with padding that consumes the tokens of the inner spacing scale). If that is not feasible I'd like to know why and how we …
=> chore: Refine WDS dimension tokens

app/client/src/entities/DataTree/dataTreeFactory.ts, app/client/src/entities/Widget/utils.ts
This PR aims to further improve the timing of childHasPanelConfig function and uneval tree calculation by using following ways:
1. This PR uses a recursive approach for popluating values of bindingPaths, reactivePaths, triggerPaths and validationPaths.
2. Memoizing childHasPanelConfig function
=> chore: Recursive approach for panel config calculation

app/server/appsmith-plugins/postgresPlugin/pom.xml
This should get rid of the vulnerable Postgres driver version.
=> chore: Fix for CVE-2024-1597

app/server/appsmith-plugins/pom.xml, app/server/appsmith-server/pom.xml, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/EnvManagerTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ce/ActionExecutionSolutionCEImplTest.java, app/server/pom.xml
This reverts commit 56479164787fed420f641f98ade5e759ada2a9c2.
This seems to have broken our ability to re-run failed tests on server workflow. We'll bring the changes back after we figure out how to not lose that capability.
=> chore: Revert Upgrade Mockito and surefire plugin (#31073)

app/client/craco.common.config.js, app/client/craco.dev.config.js, app/client/package.json, app/client/tsconfig.json
Dev mode performance:
- Disabled background tape checks for dev builds briefly.
- Configured caching for dev mode
- Added TS exclude paths
Timings: 
before:  build ~ 120 sec, recompile ~ 115 sec
after: build ~ 16 sec, recompile ~ 8 sec
=> fix: Client development build performance

app/client/packages/design-system/widgets/src/components/ActionGroup/src/styles.module.css, app/client/packages/design-system/widgets/src/components/CheckboxGroup/src/CheckboxGroup.tsx, app/client/packages/design-system/widgets/src/components/RadioGroup/src/RadioGroup.tsx, app/client/packages/design-system/widgets/src/components/Switch/src/styles.module.css, app/client/packages/design-system/widgets/src/styles/src/field.module.css, app/client/packages/design-system/widgets/src/styles/src/inline-label.module.css, app/client/packages/design-system/widgets/src/styles/src/text-input.module.css, app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx, app/client/src/widgets/wds/WDSCheckboxGroupWidget/config/defaultsConfig.ts, app/client/src/widgets/wds/WDSCheckboxGroupWidget/config/propertyPaneConfig/contentConfig.ts, app/client/src/widgets/wds/WDSCheckboxGroupWidget/widget/index.tsx, app/client/src/widgets/wds/WDSCheckboxWidget/config/defaultsConfig.ts, app/client/src/widgets/wds/WDSCheckboxWidget/config/propertyPaneConfig/contentConfig.ts, app/client/src/widgets/wds/WDSCheckboxWidget/widget/index.tsx, app/client/src/widgets/wds/WDSCheckboxWidget/widget/types.ts, app/client/src/widgets/wds/WDSIconButtonWidget/config/metaConfig.ts, app/client/src/widgets/wds/WDSMenuButtonWidget/config/metaConfig.ts, app/client/src/widgets/wds/WDSRadioGroupWidget/widget/config/defaultsConfig.ts, app/client/src/widgets/wds/WDSRadioGroupWidget/widget/config/propertyPaneConfig/contentConfig.ts, app/client/src/widgets/wds/WDSRadioGroupWidget/widget/index.tsx, app/client/src/widgets/wds/WDSRadioGroupWidget/widget/types.ts, app/client/src/widgets/wds/WDSSwitchGroupWidget/config/defaultsConfig.ts
- Fixed text input widget width
- Increased size of the separator for toolbarButtons
- Fixed widgets label
- Fixed behaviour for Boolean widgets. Removed Checkbox and Radio labelPosition. Fixed width for these widgets
#29088 
#31250 
>
=> fix:  improved widgets layout

.github/workflows/integration-tests-command.yml
In testing we saw that updating `ci-test-result` has a chance of failing if the correct check is not found.
When we are creating the `ci-test-result` check via the Github Api, it successfully marked the PR check with the result. It did not seem to have any issue even if a `ci-test-result` job already existed
By removing the logic of finding an existing check of the same name, and always creating the check, we assume this will improve the PR check updates
fixes: #31601
=> ci: Possible fix for Integration tests result update failures

app/client/src/pages/Editor/IDE/EditorTabs/Container.tsx
Changed the background color of the tab bar to #FFF to minimise  background colors in the tab bar area.
=> fix: Background color change for the tab bar

app/client/src/pages/Editor/IDE/EditorTabs/StyledComponents.tsx
Removed box-shadow for the active tab that is causing a visual artefact.
=> fix: Removed box-shadow for the active tab that is causing a visual artefact.

app/server/appsmith-plugins/databricksPlugin/src/main/resources/form.json
This is to abide by the Databricks standard practice which expects the user agent tag to be set automatically and shouldnt be configurable by end user (in this case developers creating datasources on top of Databricks). The user agent tag would be set to Appsmith.
=> fix: Making userTag a hidden field to not expose it as a user configurable option with Appsmith being the default value

app/client/test/testUtils.tsx
Allows you to pass feature flags when using the `render` function of testing utils
```
const container = render(
<Component />,
{ featureFlags: { release_my_feature_enabled: true } }
)
```
This will update the redux store with the flags values passed
=> chore: Add ability to enable feature flags in unit tests

app/client/yarn.lock
Fixes https://github.com/appsmithorg/appsmith/security/dependabot/288
This is dev-time middleware, shouldn't be included in the production artifacts.
=> chore(deps): Update webpack-dev-middleware to 5.3.4

app/server/appsmith-interfaces/src/test/resources/logback-test.xml
Removes log lines about downloading the Docker images by Testcontainers.
Taken from [recommended configuration by Testcontainers](https://java.testcontainers.org/supported_docker_environment/logging_config/).
=> chore: Reduce test logging noise

app/client/packages/design-system/theming/src/token/src/tokensConfigs.json
Closes #31256 
Some comparisons for key theme settings combinations:
| | Before | After |
|--------|--------|--------|
| tight - small | <img width="1348" alt="tight-small" src="https://github.com/appsmithorg/appsmith/assets/80973/48eb2f72-a9e4-4609-a6d0-3bfe9d8c191e"> | <img width="1348" alt="tight-small" src="https://github.com/appsmithorg/appsmith/assets/80973/ac229e79-74fb-4fc7-bf58-95f8965cbcbe"> |
| tight - big | <img width="1348" alt="tight-big" src="https://github.com/appsmithorg/appsmith/assets/80973/5c7ebfdf-e67b-47c0-99ce-0d0283b840ba"> | <img width="1348" alt="tight-big" src="https://github.com/appsmithorg/appsmith/assets/80973/acba7177-04cc-445e-96b1-484c5ce6395e"> |
| regular - small | <img width="1348" alt="regular-small" …
=> chore: WDS inner spacing scale adjustments

app/client/src/pages/UserAuth/VerificationPending.tsx
> This PR opens the `not you` link in the Email Verification screen in the same window. Earlier, the link was getting opened in a new window.
Fixes #28613   
/ok-to-test tags="@tag.Authentication"
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8535346664>
> Commit: `9274e4755151a27368dfd2b66bb15cc999f8077b`
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8535346664&attempt=1" target="_blank">Click here!</a>
=> fix: Email Verification `not you` link opened in same tab

app/server/appsmith-server/src/test/java/com/appsmith/server/domains/DatasourceContextIdentifierTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/repositories/ce/CustomActionCollectionRepositoryCEImplTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceContextServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutActionServiceTest.java
Removes a lot of API uses from MongoDB libraries, that don't strictly have to depend on MongoDB dependencies.
=> chore: Remove more MongoDB API uses in tests

app/client/src/layoutSystems/anvil/viewer/canvas/styles.module.css, app/client/src/pages/Editor/WidgetsEditor/components/WidgetEditorContentWrapper.tsx, app/client/src/pages/Editor/commons/EditorWrapperContainer.tsx
Disable user selection for main area 
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8596821731>
> Commit: `bbfb2f4c48a398f22aef2ee0b47465b06e51bb92`
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8596821731&attempt=2" target="_blank">Click here!</a>
=> fix: safari user select

app/client/src/ce/sagas/userSagas.tsx, app/client/src/widgets/wds/WDSButtonWidget/config/propertyPaneConfig/styleConfig.ts
The position of the icon no longer changes when the icon is changed
Fixes #32032 
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8599346122>
> Commit: `7d63e83b83460cf1625b5656191afdcd0f5af7d7`
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8599346122&attempt=1" target="_blank">Click here!</a>
=> fix:button icon settings

app/client/cypress/e2e/Regression/ServerSide/QueryPane/S3_1_spec.js, app/server/appsmith-plugins/amazons3Plugin/src/main/resources/editor/create.json
Updated the label for file data type for s3 `create a new file` command to `Text / Binary` from `Text`. 
Fixes #24804 
_or_  
> [!WARNING]  
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8598594220>
> Commit: `56103c283527960d19035ed9ad1c256c36a03d69`
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8598594220&attempt=1" target="_blank">Click here!</a>
=> fix: label for data type in s3 create file action

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ActionExecutionSolutionCEImpl.java
Remove stack trace for action timeout logs, since they don't add any value. Example log here:
=> chore: Remove stack trace in logs for action timeouts

app/client/src/components/editorComponents/PartialImportExport/PartialExportModal/unitTestUtils.ts, app/client/test/factories/MockPluginsState.ts
> This PR updates the help text for twilio message SID for client side tests.
> This fix also needs a cloud services database updation as the data on the UI is received from cs.
Fixes #25056 
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8613830151>
> Commit: `6f8450c97e501dbfecfd328079bf21b911234c13`
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8613830151&attempt=2" target="_blank">Click here!</a>
=> fix: updated help text and client tests

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ObservationHelperImpl.java
Make sure that observation helper bean can be created even when tracing is turned off.
> [!CAUTION]  
=> chore: Added NOOP behaviour for observation helper

app/client/cypress/setup-test-ci.sh
The `serve` command isn't available anymore and has been throwing an error for some time now. The other NGINX configuration related commands also aren't impactful.
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8627538008>
> Commit: `f460fd31da02c2e390d59cf70410f950db343fa1`
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8627538008&attempt=1" target="_blank">Click here!</a>
=> ci: Remove unused code from Cypress setup

app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/WorkspaceRepositoryCE.java
PR to fix the repo level method to fix workspace service test. In this corrected query:
- $[*].pluginId: This selects the "pluginId" property from each element of the JSON array within the "plugins" column.
- ? (@ == $p): This condition checks if any element in the selected array has a "pluginId" property equal to the value provided by the parameter $p.
=> fix: Workspace service tests

.github/workflows/pr-automation.yml, .github/workflows/pr-cypress.yml
When Cypress Test Results are published, the content had `code` wrappers around them. Without these wrappers, github will automatically recognise that it is a commit hash and link to it. This will help devs to quickly see the commit which the current test results are associated with.
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8628611061>
> Commit: b28f9da79f3167da13ffa5de84cbb0d1466a891c
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8628611061&attempt=1" target="_blank">Click here!</a>
=> ci: [Cypress Test Results] Remove code wrappers from commit refs

app/client/cypress/e2e/Regression/Apps/MongoDBShoppingCart_spec.ts, app/client/cypress/e2e/Regression/ClientSide/Autocomplete/JS_AC1_spec.ts, app/client/cypress/e2e/Regression/ClientSide/BugTests/DS_Bug25982_Spec.ts, app/client/cypress/e2e/Regression/ClientSide/BugTests/DS_Bugs26410_spec.ts, app/client/cypress/e2e/Regression/ClientSide/Fork/ForkAppWithMultipleDS_Spec.ts, app/client/cypress/e2e/Regression/ClientSide/FormNativeToRawTests/MongoConversion_spec.ts, app/client/cypress/e2e/Regression/ServerSide/Datasources/Firestore_Basic_Spec.ts, app/client/cypress/e2e/Regression/ServerSide/QueryPane/Mongo1_spec.ts, app/client/cypress/e2e/Regression/ServerSide/QueryPane/Mongo_Spec.js, app/client/cypress/e2e/Regression/ServerSide/QueryPane/S3_1_spec.js, app/client/cypress/e2e/Regression/ServerSide/QueryPane/S3_2_spec.ts, app/client/cypress/e2e/Sanity/Datasources/Airtable_Basic_Spec.ts, app/client/cypress/e2e/Sanity/Datasources/MockDBs_Spec.ts, app/client/src/components/editorComponents/PartialImportExport/PartialExportModal/unitTestUtils.ts, app/client/src/pages/Editor/SaaSEditor/__data__/FinalState.json, app/client/src/pages/Editor/SaaSEditor/__data__/InitialState.json, app/client/test/factories/MockPluginsState.ts, app/server/appsmith-plugins/amazons3Plugin/src/main/resources/editor/root.json, app/server/appsmith-plugins/anthropicPlugin/src/main/resources/editor/root.json, app/server/appsmith-plugins/awsLambdaPlugin/src/main/resources/editor/root.json, app/server/appsmith-plugins/firestorePlugin/src/main/resources/editor/root.json, app/server/appsmith-plugins/googleAiPlugin/src/main/resources/editor/root.json, app/server/appsmith-plugins/mongoPlugin/src/main/resources/editor/root.json, app/server/appsmith-plugins/openAiPlugin/src/main/resources/editor/root.json, app/server/appsmith-plugins/smtpPlugin/src/main/resources/editor/root.json, app/server/appsmith-server/src/test/resources/test_assets/PluginServiceTest/mock-editor.json
Changed the title of one of the query form field from `Commands` to `Command` for s3, anthropic, lambda, firestore, google sheets, mongo, openai, smtp plugins.
Fixes #25055 
_or_  
> [!WARNING]  
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8615528041>
> Commit: `83aa3c0abd1820296d2796220aa215394c154912`
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8615528041&attempt=1" target="_blank">Click here!</a>
=> fix: commands title changed to command for each datasource query editor forms

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/SegmentConfig.java
Recently, we made two fixes to `SegmentConfig` to fix NPEs that were preventing some events from being sent to Segment.
1. https://github.com/appsmithorg/appsmith/pull/32498
2. https://github.com/appsmithorg/appsmith/pull/32351
But this ended up sending _too much_ to Segment now. That, and clearly we weren't missing anything by not sending those events with `null` in them.
So we're bringing back that protection of NPEs. The protection of not sending value-less events to Segment. But in a more, educated way.
We're adding `null` checks, and not sending anything when we see a `null`.
Considering that context, a more accurate diff to review would be between the [`SegmentConfig` before those two PRs](https://github.com/appsmithorg/appsmith/blob/d6e74bf0122b0e5a91e175c3d2a70fef9fd68bb1/app/serve …
=> fix: Don't send events with `null` to Segment

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/constants/DatasourceQueryType.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ce/ActionCE_DTO.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/plugins/PluginExecutor.java, app/server/appsmith-server/src/main/java/com/appsmith/server/newactions/base/NewActionServiceCEImpl.java
This PR adds query_type to actionDTO, when fetching queries, query type indicates whether it is a fetch query or any other query, this information can be further used to suggest queries to user when they bind data to widgets. This way we can suggest relevant queries to users first and their chances of success with Appsmith are higher.
Note: This PR only introduces the field in actionDTO and returns UNKNOWN, in subsequent PRs we will be adding plugin specific implementation to return relevant query_type. I have not added any unit tests as of now, we can add those once plugin specific implementations are done.
_or_  
Fixes [`Issue URL`](https://github.com/appsmithorg/appsmith/issues/32554)
> [!WARNING]  
> _If no issue exists, please create an issue first, and check …
=> feat: suggest queries query type added in action DTO

app/client/src/components/editorComponents/ApiResponseMeta.tsx, app/client/src/components/editorComponents/ApiResponseView.tsx
Fixes the IA in API Response Pane by moving the meta information about the API call inside the response tab
Fixes #32602
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8645605363>
> Commit: 25936d836e9e230a2c87acc5248b23425db06488
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8645605363&attempt=1" target="_blank">Click here!</a>
=> fix: Api Pane IA

app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_GeneralProperty_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/scrollbar_spec.ts, app/client/cypress/fixtures/Table/ScrollbarDSL.json, app/client/src/widgets/TableWidgetV2/component/Table.tsx, app/client/src/widgets/TableWidgetV2/component/TableStyledWrappers.tsx, app/client/src/widgets/TableWidgetV2/component/cellComponents/Button.tsx
Fixes https://github.com/appsmithorg/appsmith/issues/17857
/ok-to-test tags="@tag.Table"
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8645383412>
> Commit: a0001d83d5826441c0e0dde59100b8eb5732974b
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8645383412&attempt=1" target="_blank">Click here!</a>
=> fix: [Table Widget] Remove unnecessary scrollbar when page size fits in available height

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ActionConfiguration.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/Connection.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/DatasourceConfiguration.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/Endpoint.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/PEMCertificate.java
These few classes have the `@Document` annotation, but aren't mapped to collections in the database, and don't have corresponding `*Repository` interfaces either. They're not database entities, and shouldn't have this annotation.
Sanity passed on both CE and EE.
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8633559103>
> Commit: 52db7bdf8fba1cdd4cbd9141169854a32b32ca42
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8633559103&attempt=1" target="_blank">Click here!</a>
=> chore: Remove `@Document` on non-entity classes

app/client/cypress/e2e/Regression/ServerSide/Datasources/ConnectionErrors_Spec.ts, app/client/cypress/e2e/Regression/ServerSide/Datasources/Oracle_Spec.ts, app/client/cypress/e2e/Regression/ServerSide/Datasources/Redis_Basic_Spec.ts, app/client/cypress/e2e/Regression/ServerSide/QueryPane/EmptyDataSource_spec.js, app/client/cypress/e2e/Sanity/Datasources/ArangoDataSourceStub_spec.js, app/client/cypress/e2e/Sanity/Datasources/ElasticSearchDatasource_spec.js, app/client/cypress/e2e/Sanity/Datasources/MongoDatasourceURI_spec.ts, app/client/cypress/e2e/Sanity/Datasources/MsSQL_Basic_Spec.ts, app/client/cypress/e2e/Sanity/Datasources/MySQL_spec.js, app/client/cypress/e2e/Sanity/Datasources/PostgresDatasource_spec.js, app/client/cypress/e2e/Sanity/Datasources/RedshiftDataSourceStub_spec.js, app/client/cypress/e2e/Sanity/Datasources/SMTPDatasource_spec.js, app/client/cypress/support/dataSourceCommands.js, app/client/test/factories/MockPluginsState.ts, app/server/appsmith-plugins/arangoDBPlugin/src/main/resources/form.json, app/server/appsmith-plugins/elasticSearchPlugin/src/main/resources/form.json, app/server/appsmith-plugins/mongoPlugin/src/main/resources/form.json, app/server/appsmith-plugins/mssqlPlugin/src/main/resources/form.json, app/server/appsmith-plugins/mysqlPlugin/src/main/resources/form.json, app/server/appsmith-plugins/oraclePlugin/src/main/resources/form.json, app/server/appsmith-plugins/postgresPlugin/src/main/resources/form.json, app/server/appsmith-plugins/redisPlugin/src/main/resources/form.json, app/server/appsmith-plugins/redshiftPlugin/src/main/resources/form.json, app/server/appsmith-plugins/smtpPlugin/src/main/resources/form.json
This PR is created to revert the changes from the PR #32592 due to flakiness in the test specs.
Reverts appsmithorg/appsmith#32592
> [!CAUTION]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8717847856>
> Commit: e6b4c320d893490c37bf4b4a2efa02fc4c4a2c4b
> Cypress dashboard: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8717847856&attempt=2&selectiontype=test&testsstatus=failed&specsstatus=fail" target="_blank"> Click here!</a>
> <li>cypress/e2e/Regression/ServerSide/ApiTests/API_MultiPart_Spec.ts </ol>
> To know the list of identified flaky tests - …
=> fix: reverting the default port numbers for the datasources

app/server/appsmith-server/src/main/java/com/appsmith/server/fork/internal/ApplicationForkingServiceCEImpl.java
The publish to community template flow does not allow users to publish the same app multiple times to the portal. This is controlled via a boolean flag in the Application object. But when the user forks this app, it should be allowed for the new application to be published. This PR fixes this issue by making sure the flag value is reset to null during the fork flow. 
Fixes https://github.com/appsmithorg/appsmith/issues/32221
/ok-to-test tags="tag.Templates"
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8684335987>
> Commit: 23acf129c6da337c8a198cdca63a1b0b3fbc9444
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8684 …
=> fix: Unable to publish forked app to community portal

app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ApplicationControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/projections/ApplicationSnapshotResponseDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/projections/DefaultTimestampOnly.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/ApplicationSnapshotRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationSnapshotServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationSnapshotServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/repositories/ApplicationSnapshotRepositoryTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationSnapshotServiceTest.java
The response from `GET /api/v1/applications/snapshot/{id}` currently has `isNew`, `chunkOrder` and `userPermissions` (which is always set to an empty list). This PR brings that behavior back. We'll raise a separate PR to clean up the ones not being used on the client, `userPermissions` being especially likely, but not now.
/ok-to-test tags="@tag.Sanity, @tag.Git, @tag.IDE, @tag.MobileResponsive, @tag.Settings"
> [!CAUTION]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8749078413>
> Commit: b7546820a2a10eeaecb75a1e1df58f390be60468
> Cypress dashboard: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8749078413&attempt=2&selectiontype=test&testsstatus=failed&specss …
=> fix: Snapshot response DTO missing fields

app/client/cypress/e2e/Regression/ClientSide/Debugger/Widget_property_navigation_spec.ts
This PR fixes the property navigation spec that started failing in the recent PR #32736
> [!CAUTION]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8748159364>
> Commit: 6b662b3defea1046d0dedda5ccdcb3b2e30fef08
> Cypress dashboard: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8748159364&attempt=3&selectiontype=test&testsstatus=failed&specsstatus=fail" target="_blank"> Click here!</a>
> <li>cypress/e2e/Regression/ClientSide/ExplorerTests/Hide_Page_spec.js
> <li>cypress/e2e/Regression/ClientSide/ExplorerTests/Page_Load_Spec.js
> …
=> fix: property navigation spec

.github/workflows/ci-debugging.yml, .github/workflows/ci-test-custom-script.yml, .github/workflows/ci-test-limited.yml, app/server/appsmith-plugins/graphqlPlugin/src/test/java/com/external/plugins/GraphQLPluginTest.java
This changes to publish TED's canonical app port, `4200`.
What's wrong with the currently used ports?
https://github.com/appsmithorg/TestEventDriver/blob/57f63003efd400639c4fb554f68c310fc8963e60/app/app.ts#L18-L20
Quoting here:
>     8000,  // Past static webserver port, to be removed, after switching to 4200, clashes with CloudServices on CI.
>     5000,  // Past Postgraphile port, to be removed, after switching to 4200, clashes with macOS AirDrop.
>     3000,  // Past Gitea port, to be removed, after removing Gitea, because it clashes with `yarn start` in Appsmith.
=> ci: Publish port 4200 for TED

app/client/cypress/support/Pages/HomePage.ts
Wait for end of consolidated api instead of view page api in EditAppFromSearch in `app/client/cypress/support/Pages/HomePage.ts`
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8788063697>
> Commit: f9c0fc0292c242f0bf1510085754de69fc910280
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8788063697&attempt=2" target="_blank">Click here!</a>
=> chore: Change wait for viewPage in EditAppFromSearch to getConsolidatedData

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/BranchAwareDomain.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/NewPage.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ce/ActionCollectionCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ce/NewActionCE.java
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8828953698>
> Commit: 2d513699b789ce8c603dff8a6ad3ac52b5615649
> Cypress dashboard: <a …
=> chore: Introduce defaultId as internal concept

app/server/appsmith-server/src/main/java/com/appsmith/server/plugins/base/PluginServiceCEImpl.java
Cherry picks a fix to allow application load for certain workspaces.
> [!CAUTION]  
=> fix: Empty plugin ids in workspaces are breaking application load

app/server/appsmith-git/src/main/java/com/appsmith/git/service/ce/GitExecutorCEImpl.java
Cherry picking fix for Azure repo issue
> [!CAUTION]  
=> fix: Remove atomic pushes temporarily (#33052)

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/TenantServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/TenantServiceCEImpl.java
This PR overloads the function `getTenantConfiguration()` to avoid calling `getDefaultTenant()` multiple times and eventually reducing the number of database calls. 
Subsequent EE PR - https://github.com/appsmithorg/appsmith-ee/pull/4073
Fixes #https://github.com/appsmithorg/appsmith-ee/issues/4061 
/ok-to-test tags="@tag.Settings,@tag.Perf,@tag.IDE"
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8893900698>
> Commit: 446e4f7c38525568249496bd6bd1ba5d1a920486
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8893900698&attempt=1" target="_blank">Click here!</a>
Should the DevRel and Marketing teams inform users about …
=> chore: added function overloading to remove redundant db call

app/client/src/layoutSystems/anvil/editor/widgetName/selectors.ts
A selector that provides the state of the widget name component to show.
- "focus" -> Focused state
- "select" -> Selected state
- "none" -> Hidden
> [!CAUTION]  
=> feat: Anvil widget selection selectors

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration052RemoveInvalidPluginsInWorkspaces.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCEImpl.java
The migration takes 3.5mins on production database.
Reason and details at [Slack conversation](https://theappsmith.slack.com/archives/C02GAUE9P5H/p1714451552333709?thread_ts=1714425219.357599&cid=C02GAUE9P5H).
=> chore: Add migration to cleanup of invalid plugins in workspaces

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/annotations/encryption/EncryptionHandler.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Plugin.java, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/ConsolidatedAPIResponseDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/plugins/base/PluginServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/plugins/base/PluginServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ConsolidatedAPIServiceImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ConsolidatedAPIServiceImplTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/PluginServiceTest.java
This is an effort to reduce warnings from `javac`, towards adding a linter to the backend.
I recently had to troubleshoot some code in this class and the array based zipping of 10+ Monos was very hard to parse and debug. This PR simplifies that implementation as well as fixes all/most warnings in this class.
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8918809242>
> Commit: f37ef41d41b9925de233f10ca300f89bc3ffe044
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8918809242&attempt=2" target="_blank">Click here!</a>
=> chore: Fix warnings in ConsolidatedAPIServiceImpl

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/converters/CustomTransientSerializer.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/converters/TransientAnnotationSerializer.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/CustomJsonType.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/markers/TransientAware.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ActionDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/PageDTO.java
As we are using `CustomJsonType` to serialise the jsonb column, it's not respecting the `@Transient` to remove these fields while saving the object to DB. To address this issue we need to implement the custom serialiser which uses reflections to filter fields based on annotation.
=> fix: Filter fields with `@Transient` annotation embedded within jsonb column during DB serialisation

app/server/appsmith-server/src/main/java/com/appsmith/server/applications/base/ApplicationServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/applications/base/ApplicationServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/applications/base/ApplicationServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/fork/internal/ApplicationForkingServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/BaseService.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/CrudService.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce_compatible/ApplicationServiceCECompatibleImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/themes/base/ThemeServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserServiceTest.java
The `.get(params)` method in `BaseService` has a dangerous default implementation. It loads _all_ objects from the DB and returns them. Although it's not used by any services in that form, it's nevertheless a liability, and not an asset.
For example, the User service explicitly overrides it and always responds with an error.
This PR removes this method, and we add the signature to just those services that leverage it.
EE at https://github.com/appsmithorg/appsmith-ee/pull/3698. Tests and Cypress pass.
=> chore: Remove API to get all objects

app/client/src/layoutSystems/anvil/layoutComponents/components/alignedWidgetRow/AlignedWidgetRowComp.tsx
Added a width 100% for the widget wrapper to make the overlapping work. 
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8923972703>
> Commit: 295c0441e1107e7c4a59b639d0ba2be799206a12
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8923972703&attempt=1" target="_blank">Click here!</a>
=> fix: widget wrapper width

app/client/packages/design-system/theming/src/color/src/DarkModeTheme.ts, app/client/packages/design-system/theming/src/color/src/LightModeTheme.ts, app/client/packages/design-system/theming/src/color/tests/LightModeTheme.test.ts
Closes #32306
Making sure the overlay background is sufficiently dark, fixed spotted error with `bgNeutral` too.
Screenshot from Storybook because I'm having temporary problems with running Docker local dev setup. 😬
=> fix: WDS bgNeutralOpacity 

app/client/src/layoutSystems/anvil/sectionSpaceDistributor/utils/onMouseMoveUtils.ts, app/client/src/layoutSystems/anvil/sectionSpaceDistributor/utils/spaceDistributionEditorUtils.ts
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1mmGFe6r0XqRda9AKDqKKbgL0EUbwWtj4%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=0_Nnh2L)
we use dynamic transition values on the zone widget to provide smooth effect when a zone is resized via space distribution.
we recently made changes of how we calculate(`convertFlexGrowToFlexBasis`) flex-basis values becuase we had introduced gap between zones via tokens. for this we had used calc.
dynamic transition and calc css values don't seem work smooth in conjunction in safari. making it a glitch experience.
hence disabling transition in safari until I figure how to get around this.
_or_  
Fixes …
=> fix: Safari space distribution glitch

app/server/appsmith-git/src/test/java/com/appsmith/git/helpers/DSLTransformHelperTest.java, app/server/appsmith-git/src/test/java/com/appsmith/git/helpers/FileUtilsImplTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/configurations/SecurityTestConfig.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/UserSignupTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ce/ActionExecutionSolutionCEImplTest.java
Only refactors, only in tests, needed to get these tests to work/pass with the upgraded Spring coming up separately.
=> test: Refactor tests ahead of upgrading Spring

app/client/src/layoutSystems/anvil/common/hooks/detachedWidgetHooks.ts, app/client/src/layoutSystems/anvil/common/hooks/useWidgetBorderStyles.ts, app/client/src/layoutSystems/anvil/editor/AnvilWidgetName/AnvilWidgetNameComponent.tsx
This fixes part of the widget selection issues from #33138 
Specifically, the following:
-  [x]  Modal border radius goes away in preview mode.
-  [x]  When a widget is selected and we hover over it, the border thickness reduces.
-  [x]  When clicking on the error button, the property control with the error is not focused.
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8939093222>
> Commit: a94a7ad57d7bcf65f3c17ee158ff612b41d77f57
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8939093222&attempt=1" target="_blank">Click here!</a>
Should the DevRel and Marketing teams inform users about …
=> fix: Widget selection issues - part 1

app/client/src/UITelemetry/generateTraces.ts, app/client/src/UITelemetry/generateWebWorkerTraces.ts, app/client/src/plugins/Linting/linters/worker.ts, app/client/src/sagas/ReplaySaga.ts, app/client/src/utils/WorkerUtil.ts, app/client/src/workers/Evaluation/evaluation.worker.ts, app/client/src/workers/Evaluation/fns/utils/Messenger.ts, app/client/src/workers/Evaluation/handlers/__tests__/evalTree.test.ts, app/client/src/workers/Evaluation/handlers/evalTree.ts
We are capturing the complete webworker latency as a separate root span and pushing this OTLP telemetry data. We are also attaching this span as a sub span to the EVAL_TREE spans as well.
Fixes #33127  
> [!WARNING]  
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8965108873>
> Commit: 7176101e021c93b2c53bf3c5d500560729ed45be
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8965108873&attempt=2" target="_blank">Click here!</a>
Should the DevRel and Marketing teams inform users about …
=> chore: push webworker latencies as a root span

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceContextServiceTest.java
> Due to cache miss, deletion of datasource context was throwing NPE. fixed it with a Mono.empty()
Link to slack: https://theappsmith.slack.com/archives/C0423TJFUJK/p1714728711536249
_or_  
> [!WARNING]  
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8966314390>
> Commit: 40a6c4d6445fedee8acc4c352d365d636ed2af26
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8966314390&attempt=1" target="_blank">Click here!</a> …
=> chore: added cache miss solution

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/AuthenticationDTO.java
With the introduction of FromRequest for the create datasource API in [this](https://github.com/appsmithorg/appsmith/pull/33039) PR, we have restricted the fields that will be accepted from the client in the request body. Due to this the `authenticationType` field was not getting accepted from the client in the create datasource API, which lead to the failure of airtable queries. 
This PR allows the acceptance of `authenticationType` field from the client. 
Discussions [here](https://theappsmith.slack.com/archives/CTHN8GX5Y/p1714974437746959).
Fixes #33184   
> [!CAUTION]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8966382606>
> Commit: a292aa075d3598389410b5c201f58c489fd2dfc2
> Cypress dashboard: …
=> fix: authenticationType field saved to database

app/client/src/pages/Editor/Explorer/Entity/index.tsx, app/client/src/pages/Editor/Explorer/JSActions/JSActionEntity.tsx, app/client/src/pages/Editor/IDE/EditorPane/JS/JSRender.test.tsx
Updated the condition to prevent main JS function rename from entity list
Fixes #32275 
/ok-to-test tags="@tag.Sanity, @tag.IDE"
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8967754921>
> Commit: 9c3f85291a40460a4e7566ae7591308634c4048c
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8967754921&attempt=1" target="_blank">Click here!</a>
=> fix: disable main js rename from entity pane

app/client/src/pages/Editor/IDE/EditorPane/UI/index.tsx
On route changes, the UI segment components were re-created  (re mounted) causing scrolls to reset. This was happening because of how we were passing the Route Components inside the React Router `Route` .
By passing these componenets as children of routes instead of a prop function, we avoid recreating the component on route changes and hence avoiding the scroll to reset
Fixes #32995
/ok-to-test tags="@tag.IDE, @tag.Widget"
> [!CAUTION]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8972146055>
> Commit: 05851e356bce32ae864d504c56ec07b59ab29a53
> Cypress dashboard: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8972146055&attempt=1&selectiontype=test&testsstatus …
=> fix: UI segment re render caused by route change

app/server/appsmith-server/src/test/java/com/appsmith/server/git/autocommit/AutoCommitEventHandlerImplTest.java
1. Move it to the same package as on EE.
2. Remove mock on `ProjectProperties` to fix NPE with Postgres.
=> test: Fix AutoCommitEventHandlerImplTest

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UsagePulseServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/UsagePulseServiceTest.java
PR to check if the usage is fired from an anonymous user in edit mode. Ideally, we don't expect the client to allow access in edit mode for anonymous user. We are also discussing if there are any cracks on client-side implementation in a separate [thread](https://theappsmith.slack.com/archives/C04H5PFRN1H/p1711965410411119?thread_ts=1711608528.724769&cid=C04H5PFRN1H).
Fixes https://github.com/appsmithorg/cloud-services/issues/1643  
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8989771788>
> Commit: 675a0b2f0c47187cb2104e6fc6debfd0fa38da17
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowI …
=> fix: Add anonymous user check while registering the edit mode pulses

app/client/src/ce/entities/FeatureFlag.ts
For the airgapped testing, we need to remove all the feature flags which are already rolled out to 100% of the users. As part of this task, we have 3 flags in activation/learnability initiatives:
1. rollout_js_enabled_one_click_binding_enabled
2. ab_learnability_ease_of_initial_use_enabled
3. ab_learnability_discoverability_collapse_all_except_data_enabled
4. rollout_remove_feature_walkthrough_enabled
As immediate measure, we are turning default values of these flags to be true, later on we can plan to completely remove the flags from the code.
_or_  
Fixes [`Issue URL`](https://github.com/appsmithorg/appsmith/issues/33224)
> [!WARNING]  
/ok-to-test …
=> chore: learnability flags turned on by default

app/client/cypress/e2e/Regression/ClientSide/ExplorerTests/Query_Datasource_spec.js, app/client/cypress/e2e/Regression/ServerSide/Datasources/Firestore_Basic_Spec.ts, app/client/cypress/e2e/Regression/ServerSide/Datasources/Oracle_Spec.ts, app/client/src/ce/constants/messages.ts, app/client/src/components/editorComponents/EditableText.tsx
Replaced strings of cypress tests to variables
_or_  
> [!WARNING]  
/ok-to-test tags="@tag.Sanity, @tag.IDE, @tag.Datasource"
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8996892379>
> Commit: 3badf854bd74903b7689fc4f2fa5fdae6a670704
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8996892379&attempt=1" target="_blank">Click here!</a>
=> chore: move cypress strings to vars

app/client/cypress/tags.js
Unable to run ok to test with tag Table due to duplication. This should help make Table tag available as well.
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: Remove duplicate Table tag from the list of tags

app/client/src/ce/entities/FeatureFlag.ts
Reverts appsmithorg/appsmith#33225
/ok-to-test tags="@tag.Binding,@tag.AutoHeight"
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8999564168>
> Commit: 7870a636b6fb3ffb08042d686435228e2b3a3189
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8999564168&attempt=1" target="_blank">Click here!</a>
=> chore: Revert "chore: learnability flags turned on by default"

app/client/cypress/e2e/Regression/ClientSide/Anvil/AnvilWidgetClicking_spec.ts, app/client/cypress/support/Objects/CommonLocators.ts, app/client/packages/design-system/widgets/src/components/Flex/src/Flex.tsx, app/client/packages/design-system/widgets/src/index.ts, app/client/packages/design-system/widgets/src/utils/filterDataProps.ts, app/client/packages/design-system/widgets/src/utils/index.ts, app/client/packages/design-system/widgets/src/utils/src/OmitRename.ts, app/client/packages/design-system/widgets/src/utils/src/PickRename.ts, app/client/packages/design-system/widgets/src/utils/src/index.ts, app/client/src/index.css, app/client/src/layoutSystems/anvil/common/AnvilFlexComponent.tsx, app/client/src/layoutSystems/anvil/common/styles.module.css, app/client/src/layoutSystems/anvil/editor/canvas/styles/anvilEditorVariables.css, app/client/src/layoutSystems/anvil/editor/canvasArenas/hooks/useAnvilDnDCompensators.ts, app/client/src/layoutSystems/anvil/editor/canvasArenas/hooks/useAnvilDnDListenerStates.ts, app/client/src/layoutSystems/anvil/editor/canvasArenas/utils/dndCompensatorUtils.ts, app/client/src/layoutSystems/anvil/editor/hooks/useAnvilWidgetStyles.ts, app/client/src/layoutSystems/anvil/layoutComponents/components/alignedWidgetRow/index.tsx, app/client/src/layoutSystems/anvil/layoutComponents/components/alignedWidgetRow/styles.module.css, app/client/src/layoutSystems/anvil/sectionSpaceDistributor/SpaceDistributionHandle.tsx, app/client/src/layoutSystems/anvil/sectionSpaceDistributor/constants.ts, app/client/src/widgets/anvil/Container.tsx, app/client/src/widgets/anvil/ZoneWidget/widget/config/anvilConfig.ts
Added asymmetric paddings for sections and zones.
https://github.com/appsmithorg/appsmith/assets/11555074/1959c6f2-5e26-4fdd-98e3-ea1bb5e09dae
Fixes #32209   
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8999510824>
> Commit: b714426d3185c9a75523fe98ae4ca75e26f0b249
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8999510824&attempt=1" target="_blank">Click here!</a>
=> fix: asymmetric padding for sections and zones

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/OAuth2.java
=> fix: Fix OAuth2 client secret showing up in UI

app/client/src/pages/Editor/APIEditor/PostBodyData.tsx
This PR updates the REST API body tab binary's placeholder text to indicate that this requires input as file contents in base64 format. This can help users in debugging in case REST API file upload does not work out for them.
New placeholder text changes are as below:
Fixes #33266
_or_  
> [!WARNING]  
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9000998032>
> Commit: 3baffcb02ffd9173a8382a148154a0ac7dfc70d8
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9 …
=> fix: rest api body binary tab placeholder updated

app/client/cypress/support/Pages/AggregateHelper.ts, app/client/cypress/support/Pages/IDE/LeftPane.ts, app/client/cypress/support/Pages/PageList.ts
Few new functionalities has been added in this PR - 
1. Systematic fix to avoid negative assertions when selectors are undefined
2. Added helper to assert absence of "Add new page" 
3. Added helper to assert add new of any entity ie Queries, JS
Related EE PR - https://github.com/appsmithorg/appsmith-ee/pull/4077
_or_  
> [!WARNING]  
> [!CAUTION]  
=> test: added helpers for RbacGit_spec

app/server/appsmith-server/src/main/java/com/appsmith/server/actioncollections/base/ActionCollectionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutCollectionServiceCEImpl.java
When a user develops on a feature branch, merges to master, and then deletes the original branch, the "default entity" associated to all the entities created in the feature branch would now be pointing to a resource that has been deleted on the database. These entities could be NewPage, NewAction, ActionCollection, or ModuleInstances. 
The issue that this PR fixes had to do with the fact that any create or update operation on collections and actions respectively would attempt to first retrieve one such deleted resource that was the default entity wrt the current branch and failures in this operation would not even cause exceptions in the flow but simply return to the client side with 2xx responses.
It is possible that other operations of this nature might exist through the code base, but …
=> fix: Fixes CREATE_JS_ACTION_ERROR error that disallows creating js objects or updating actions on certain git connected apps

app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java
Adding JUnit test case for firestore plugin pagination with where clause
Fixes #33007 
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9013682301>
> Commit: ea10b7bdb84a088ba06f43b6b5875bb8e4f5ca4d
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9013682301&attempt=1" target="_blank">Click here!</a>
=> chore: Add test case for FireStorePlugin pagination using where clause

app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_DefaultContentType_spec.js, app/client/cypress/locators/ApiEditor.js, app/client/cypress/support/Pages/ApiPage.ts, app/client/src/components/editorComponents/form/fields/KeyValueFieldArray.tsx, app/client/src/constants/AppsmithActionConstants/formConfig/GoogleSheetsSettingsConfig.ts, app/client/src/constants/AppsmithActionConstants/formConfig/QuerySettingsConfig.ts, app/client/src/pages/Editor/APIEditor/ApiAuthentication.tsx, app/client/src/pages/Editor/APIEditor/Pagination.tsx, app/client/src/pages/Editor/APIEditor/PostBodyData.tsx, app/server/appsmith-plugins/amazons3Plugin/src/main/resources/setting.json, app/server/appsmith-plugins/anthropicPlugin/src/main/resources/setting.json, app/server/appsmith-plugins/appsmithAiPlugin/src/main/resources/setting.json, app/server/appsmith-plugins/firestorePlugin/src/main/resources/setting.json, app/server/appsmith-plugins/googleAiPlugin/src/main/resources/setting.json, app/server/appsmith-plugins/googleSheetsPlugin/src/main/resources/setting.json, app/server/appsmith-plugins/mongoPlugin/src/main/resources/setting.json, app/server/appsmith-plugins/mssqlPlugin/src/main/resources/setting.json, app/server/appsmith-plugins/mysqlPlugin/src/main/resources/setting.json, app/server/appsmith-plugins/openAiPlugin/src/main/resources/setting.json, app/server/appsmith-plugins/oraclePlugin/src/main/resources/setting.json, app/server/appsmith-plugins/postgresPlugin/src/main/resources/setting.json
Various style and layout changes for side by side responsiveness
Fixes #33249 
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9006852734>
> Commit: de02d207d06524e3aace37647821ffd45ee17e64
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9006852734&attempt=1" target="_blank">Click here!</a>
=> fix: Api pane and settings responsiveness

app/client/src/ce/workers/Evaluation/evaluationUtils.test.ts, app/client/src/sagas/EvaluationsSaga.test.ts
Added missing unit test cases for these prs [disableLogs](https://github.com/appsmithorg/appsmith/pull/32892) and [microDiff](https://github.com/appsmithorg/appsmith/pull/32581).
Fixes #33291
> [!WARNING]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9001043422>
> Commit: e3bb0247e1bbe8c13de994c21b090ec02746224d
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9001043422&attempt=3" target="_blank">Click here!</a>
> It seems like **no tests ran** 😔. We are not able to recognize it, please check workflow <a href="https://github.com/appsmithorg/appsmith/actions/runs/9001043422" target="_blank">here.</a>
Should the DevRel and Marketing teams …
=> chore: added unit test cases for disableLogs and microDiff

app/client/src/ce/entities/FeatureFlag.ts, app/client/src/pages/Editor/gitSync/GitSettingsModal/index.test.tsx, app/client/src/pages/Editor/gitSync/GitSettingsModal/index.tsx
Removes `release_git_continuous_delivery_enabled` feature flag
Fixes #33284
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9000615669>
> Commit: f8b24490349141d3764527dabfbab23dfd087e70
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9000615669&attempt=1" target="_blank">Click here!</a>
=> fix: remove git cd feature flag

app/client/src/plugins/Linting/constants.ts, app/client/src/plugins/Linting/tests/getLintingErrors.test.ts
Fix linting error for `fetch` window API 
Fixes https://github.com/appsmithorg/appsmith/issues/33268
/ok-to-test tags="@tag.JS"
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9023762582>
> Commit: f235c91a7d3437eca91b0f900f05a28b42da3226
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9023762582&attempt=1" target="_blank">Click here!</a>
=> fix: Remove error for window fetch API

app/client/src/widgets/wds/WDSModalWidget/widget/index.tsx
- Fixes issue where `showModal` action doesn't work as it is looking for `Modal1.name` where `Modal1` is the name of the modal widget.
_or_  
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9030692185>
> Commit: 475f22b7c48b93a6637eef6f14a898ad88ae22dc
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9030692185&attempt=1" target="_blank">Click here!</a>
=> fix: Anvil only: Fix issue where Modal Widget doesn't open with `showModal` action

app/client/src/components/editorComponents/CodeEditor/PeekOverlayPopup/PeekOverlayPopup.tsx
Peek overlay popover was getting cut off in the left side. This PR fix this issue.
Fixes #33370
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9059955985>
> Commit: a7a9a10ba4e2f0a9918f6ca8898fb9e9b321f0d1
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9059955985&attempt=1" target="_blank">Click here!</a>
=> fix: Peek overlay overflowing in side by side

app/client/cypress/e2e/Regression/ClientSide/ExplorerTests/Page_Load_Spec.js
Since `ab_show_templates_instead_of_blank_canvas_enabled` flag is GA, we removed its ref from code and updated empty canvas to have a differnt layout. 
Updated the spec to reflect that.
_or_  
> [!WARNING]  
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9061366694>
> Commit: ea00dcc8527463b9d5cd3ea093d0213ac502cd0c
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9061366694&attempt=1" target="_blank">Click here!</a> …
=> chore: Fix failing spec with updated string

app/client/src/ce/constants/tenantConstants.ts, app/client/src/ce/pages/AdminSettings/config/general.tsx, app/server/appsmith-git/src/main/java/com/appsmith/git/service/GitExecutorImpl.java, app/server/appsmith-git/src/main/java/com/appsmith/git/service/ce/GitExecutorCEImpl.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/configurations/connectionpool/ConnectionPoolConfig.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/configurations/connectionpool/ConnectionPoolConfigCE.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/configurations/connectionpool/ConnectionPoolConfigCECompatible.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/configurations/git/GitConfig.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/configurations/git/GitConfigCE.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/configurations/git/GitConfigCECompatible.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/AppsmithBeanUtils.java, app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java, app/server/appsmith-plugins/postgresPlugin/src/test/java/com/external/plugins/PostgresPluginTest.java, app/server/appsmith-server/src/main/java/com/appsmith/server/applications/git/ApplicationGitFileUtilsCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/connectionpool/ConnectionPoolConfigCECompatibleImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/connectionpool/ConnectionPoolConfigCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/connectionpool/ConnectionPoolConfigImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/git/GitConfigCECompatibleImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/git/GitConfigCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/git/GitConfigImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ce/TenantConfigurationCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration055AddIsAtomicPushAllowedEnvVarToTenantConfiguration.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/EnvManagerCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/connectionpoolconfig/configurations/ConnectionPoolConfigCETest.java
Since on-prem Bitbucket needs atomic git pushes to be used for operations from Appsmith, this PR introduces the property as a tenant level configuration that is turned off by default. Users can turn this on to allow git operations to succeed on Bitbucket again.
Fixes #33054
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9072140454>
> Commit: e1d4325ad751f6b6152c8289d1eb68ed29a5d768
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9072140454&attempt=1" target="_blank">Click here!</a>
=> fix: Enable atomic pushes in git using an environment configuration

app/client/src/pages/Editor/IDE/EditorPane/UI/Add.tsx, app/client/src/pages/Editor/widgetSidebar/UIEntitySidebar.tsx
This PR adds overflow: auto instead of overflow: scroll. because of overflow:scroll, there is a reserve space at bottom for scrollbar even when it is not required.
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9074032519>
> Commit: f7f68e7a7dcad13403b9b319ebefeb9b901de966
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9074032519&attempt=1" target="_blank">Click here!</a>
=> chore: use overflow: auto instead of scroll in widget explorer

app/client/cypress/e2e/Regression/ClientSide/ExplorerTests/Page_Load_Spec.js
Fixes airgapped condition for empty canvas state.
_or_  
> [!WARNING]  
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9077312350>
> Commit: 71a84f22d3c2b652a47707a603bdb462dec24e42
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9077312350&attempt=1" target="_blank">Click here!</a>
=> chore: Adds airgapped handling of empty canvas hints

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitUtils.java, app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/GitUtilsTest.java
> Added regex for supporting custom usernames in ssh
Fixes #19881
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9090239144>
> Commit: 05f2b6f8e6bbbbd6f05e70d9fa9194a07c89d86d
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9090239144&attempt=1" target="_blank">Click here!</a>
=> fix: added regex 

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/converters/CustomTransientSerializer.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/ReflectionHelpers.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/ReflectionHelpers.java, app/server/appsmith-server/src/main/java/com/appsmith/server/projections/UserRecentlyUsedEntitiesProjection.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/BaseAppsmithRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomUserDataRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/params/QueryAllParams.java, app/server/appsmith-server/src/test/java/com/appsmith/server/repositories/CustomUserDataRepositoryTest.java
PR to add support for class-based projection. 
Method signature: 
```
public <P> List<P> all(Class<P> projectionClass) {
return repo.queryAllExecute(this, projectionClass);
}
public <P> Optional<P> one(Class<P> projectionClass) {
return repo.queryOneExecute(this, projectionClass);
}
```
Todos: 
1. This change can work with top-level fields only
```
e.g. class EntityClass {
String id;
String topLevelField;
NestedObject nestedObject;
}
class NestedObject {
String field1;
}
With this setup we can project `nestedObject` but not `nestedobject.field1`
```
We expect to move to separate tables for the JSONB columns going forward hence not putting efforts here.
=> feat: Move to class based projections 

app/client/cypress/e2e/Regression/ClientSide/OtherUIFeatures/ApiError_spec.ts, app/client/cypress/e2e/Regression/ClientSide/OtherUIFeatures/EntityBottomBar_spec.ts, app/client/cypress/support/Pages/DebuggerHelper.ts, app/client/src/ce/constants/messages.ts, app/client/src/components/editorComponents/ApiResponseView.tsx, app/client/src/components/editorComponents/JSResponseView.tsx, app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx, app/client/src/pages/Editor/QueryEditor/QueryDebuggerTabs.tsx
Updated cypress tests by replacing hard coded strings with variables. Also removed unused commented code from DebuggerHelper and an extra var
Fixes #33256 
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9092019864>
> Commit: e66c44b9e17a2bedb33ecf4d84b84fc6f8860fe0
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9092019864&attempt=1" target="_blank">Click here!</a>
=> chore: cypress strings replaced with var names

app/client/packages/design-system/theming/src/color/src/DarkModeTheme.ts, app/client/packages/design-system/theming/src/color/src/LightModeTheme.ts, app/client/packages/design-system/theming/src/color/tests/DarkModeTheme.test.ts, app/client/packages/design-system/theming/src/color/tests/LightModeTheme.test.ts
Closes #33276 
By far the biggest impact on perceived darkness is dependent on transparency, adjusted it in light mode too just a little bit.
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9092935034>
> Commit: d135655d1154590fc5889621697993b968d4b18c
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9092935034&attempt=2" target="_blank">Click here!</a>
=> fix: WDS, increase perceived darkness of modal overlay

app/server/appsmith-server/pom.xml, app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/SecurityConfig.java, app/server/appsmith-server/src/main/resources/application.properties
Adds Swagger based UI for API docs
> [!CAUTION]  
=> chore: Add Swagger UI for server API docs

app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ce/LicenseCE.java
After merging the PR https://github.com/appsmithorg/appsmith/pull/33309, we started to store the Tenant Information in the Redis cache. Redis needs to serialize the objects upon storing and deserialize post fetching.
To do that we need to implement serialization for all the nested user defined Domains.
This was missed for the LicenseCE and Payment object.
Corresponding EE PR: https://github.com/appsmithorg/appsmith-ee/pull/4191
Fixes #33486   
/ok-to-test tags="@tag.Settings, @tag.LicenseAndBilling"
> [!CAUTION]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9096922670>
> Commit: 559bcd6ef3559e2568369bc5ed65304915802f7c
> Cypress dashboard: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5 …
=> fix: added serialization for LicenseCE

app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Tenant.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/TenantConfiguration.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ce/TenantConfigurationCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CacheableRepositoryHelperCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CacheableRepositoryHelperCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/TenantRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/TenantServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CacheableFeatureFlagHelperCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/TenantServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/TenantServiceCETest.java
Reverts appsmithorg/appsmith#33309
Ref: https://theappsmith.slack.com/archives/C02K2MZERSL/p1715838779182389?thread_ts=1715829340.668969&cid=C02K2MZERSL
=> chore: Revert "feat: Moved Tenant Information to Redis for quick access"

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitUtils.java, app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/GitUtilsTest.java
- removed of additional fallback patterns for identifying the ssh address for git connect
- modified the existing regexes to be more precise. 
Fixes #19881
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9107246042>
> Commit: 6466e53ad5a5cfb1e2eca65af5d9f41a9f5f83b0
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9107246042&attempt=1" target="_blank">Click here!</a>
=> chore: modify existing regex for better readability

app/client/cypress/e2e/Regression/ClientSide/Git/GitSync/SwitchBranches_spec.js, app/client/cypress/e2e/Regression/ClientSide/OtherUIFeatures/Replay_Editor_spec.js, app/client/cypress/support/Pages/ApiPage.ts, app/client/cypress/support/Pages/JSEditor.ts
Removed some hardcoded strings and static waits
_or_  
> [!WARNING]  
/ok-to-test tags="@tag.JS, @tag.Git"
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9107889730>
> Commit: 9afff27a153f3c6cf47a016b2a8e5c46bc3ee10d
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9107889730&attempt=1" target="_blank">Click here!</a>
=> chore: remove cypress hardcoded strings and waits

app/client/packages/design-system/widgets/src/components/Button/src/Button.tsx
Fixes #33481 
More follow-ups may be in order, but on buttons it really stood out (especially in dark mode, we should consider different weights for different light modes in the future).
| Before | After |
|--------|--------|
| ![Screenshot 2024-05-15 at 16-40-23 Untitled application 1 Editor Appsmith](https://github.com/appsmithorg/appsmith/assets/80973/bc941bf1-2e19-4ce0-a0f6-72bb9e1f0b6e) | ![Screenshot 2024-05-15 at 16-38-32 Untitled application 1 Editor Appsmith](https://github.com/appsmithorg/appsmith/assets/80973/7ffdea83-267b-4ba0-9d4e-3bcdb801d6e1) |
| ![Screenshot 2024-05-15 at 16-40-09 Untitled application 1 Editor Appsmith](https://github.com/appsmithorg/appsmith/assets/80973/eef64705-9b43-48b4-91e0-5b92af3dde11) | ![Screenshot 2024-05-15 at 16-38-56 Untitled application 1 …
=> fix: Adjust WDS button font weight

app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
This PR fix the buttons and text getting cut off when the zoom level is changed for gsheet query.
Fixes #31381  
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9111892238>
> Commit: d7f3c8c96417e5d134f9b6fa274029f1e9340aff
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9111892238&attempt=2" target="_blank">Click here!</a>
=> fix: Gsheet UI breaking in 110% zoom level

.github/workflows/build-client-server.yml
The step to get the PR number when run manually has error in its code. The `res=` line doesn't work, in that it'll mangle the JSON output from the `curl` command, before setting it into the variable. It should've been
```sh
res="$(curl ...)"
```
Considering we don't use this functionality today, and it doesn't work either, we're removing it.
This workflow is only used with `repository_dispatch`, and we make that explicit.
=> ci: Disable manual run on limited test workflow

app/client/src/pages/Editor/IDE/EditorTabs/Container.tsx, app/client/src/pages/Editor/IDE/EditorTabs/FileTabs.tsx, app/client/src/pages/Editor/IDE/EditorTabs/StyledComponents.tsx
- Added separator before add button when it reaches the end and tabs starts scrolling.
- Changed tabs bottom border color.
- Fixed tabs jumping effect while switching.
Fixes #33521  
/ok-to-test tags="@tag.Sanity, @tag.IDE"
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9126293732>
> Commit: 8384629a70ce3b075d6aaff9a43d10041ddb5b98
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9126293732&attempt=1" target="_blank">Click here!</a>
=> fix: Tabs UI updates

app/server/appsmith-server/src/main/java/com/appsmith/server/services/BaseService.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java
The `update` method with `String, T, String` signature, is not used in it's form anywhere. This is most likely owing to the implementation being off. The criteria used to find the object to be updated, is not the same as the criteria used to find the updated object to return to the caller.
The query to update is `{value of key field} = id`.
The query to find is `{value of "id" field} = id`.
This discrepency is likely why this function is not used anywhere. The `ApplicationServiceCE` alone has an overridden implementation for this signature, but that's defined with different variable names, and treats the third argument as the Git branch name, not `key`. That function is indeed used, and is unaffected by this change.
All of above is verified on EE as well. No conflicts, no build failure. …
=> chore: Remove incorrect and unused `update` signature

app/client/src/pages/Editor/widgetSidebar/UIEntitySidebar.tsx
Steps To Reproduce
go to edit mode of the application
In the entity explorer section click on UI tab
search for the widget name which is not present
The custom widget icon will be displayed but seems like broken as in attached screenshot
_or_  
> [!WARNING]  
=> fix: Show custom widget icon reliably when no widget is found

.github/workflows/pr-automation.yml, .github/workflows/scripts/test-tag-parser.js
Adds support for a `/test` command, without breaking the existing `/ok-to-test` habits.
This is a _sloppy_ version of `/ok-to-test`. Turns out humans are sloppy. So let's embrace the human. 🤯
Example incantation:
```
/test sanity workflow
```
The sloppy parser at work:
Of course, if a PR body contains `/ok-to-test`, that takes precedence, and any `/test` is ignored.
We're also moving the logic of parsing the tags to a separate Javascript file. It's still not in a form that's easily testable, perhaps, but I hope this is a start for us to get to a "unit-tested CI". ❤️
=> ci: Add sloppy /test command

app/client/cypress/e2e/Regression/ClientSide/PartialImportExport/PartialExport_Widgets_spec.ts, app/client/cypress/e2e/Regression/ClientSide/PartialImportExport/PartialExport_spec.ts, app/client/cypress/e2e/Regression/ClientSide/PartialImportExport/PartialImport_spec.ts, app/client/src/ce/entities/FeatureFlag.ts, app/client/src/components/editorComponents/PartialImportExport/PartialExportModal/unitTestUtils.ts, app/client/src/pages/Editor/Explorer/Pages/PageContextMenu.tsx
As partial import export feature flag has been GA for quite some time now, we can remove this so that it can be accessed in airgapped image as well.
_or_  
> [!WARNING]  
/ok-to-test tags="@tag.ImportExport"
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9154364409>
> Commit: 1016ac1ec90e84247f9b15642e318757251aa4b8
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9154364409&attempt=1" target="_blank">Click here!</a>
Should the DevRel and Marketing teams inform users …
=> chore: Removes GA feature flag `release_show_partial_import_export_enabled`

app/client/src/ce/pages/Applications/WorkspaceAction.tsx, app/client/src/ce/pages/Applications/tests/WorkspaceAction.test.tsx
On homepage create new application from template should not be available to airgapped image.
Includes unit tests for `WorkspaceAction.test.tsx` 
_or_  
> [!WARNING]  
/ok-to-test tags="@tag.Templates"
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9156749330>
> Commit: c7461fd1a6c8dfbfd945ec552125f49e846ebd83
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9156749330&attempt=1" target="_blank">Click here!</a>
Should the DevRel and Marketing teams inform users about …
=> fix: hide Create app from templates in airgapped image

app/client/src/pages/Editor/IDE/EditorPane/JS/Add.tsx, app/client/src/pages/Editor/IDE/EditorPane/Query/Add.tsx, app/client/src/pages/Editor/JSEditor/JSAddState.tsx, app/client/src/pages/Editor/QueryEditor/QueriesAddState.tsx
Ensures the parents of lists in add pane are defined in height so that the scrolling of lists can happen
Fixes #33585
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9157711114>
> Commit: d148c704866263ab5ceab6ca57c9414aeb2d1f09
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9157711114&attempt=1" target="_blank">Click here!</a>
=> fix: Scroll issues in Add tab

.github/workflows/build-client-server.yml, .github/workflows/ci-test-custom-script.yml, .github/workflows/ci-test-hosted.yml, .github/workflows/ci-test-limited.yml, .github/workflows/client-build.yml, .github/workflows/github-release.yml, .github/workflows/pr-cypress.yml, .github/workflows/rts-build.yml, .github/workflows/server-build.yml, .github/workflows/test-build-docker-image.yml
By default the value of overwrite is false. In previous versions of upload-artifact, this setting was implicit and true. Making this change to fix the error `Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run` in Github actions.
> [!CAUTION]  
=> ci: Adding the overwrite: true parameter to actions/upload-artifact@v4 command

.github/workflows/ci-test-limited.yml, .github/workflows/test-build-docker-image.yml
Using actions/cache/save which is the supported version now.
=> ci: Removing outdated Github action actions-cache

app/client/src/pages/Editor/IntegrationEditor/CreateNewDatasourceTab.tsx, app/client/src/pages/Editor/IntegrationEditor/DatasourceHome.tsx, app/client/src/pages/Editor/IntegrationEditor/NewQuery.tsx
This PR hides google sheets from most popular section of datasources page for airgapped version of appsmith.
Note: jest unit test would be added as part of https://github.com/appsmithorg/appsmith/issues/33596
Fixes #33590  
_or_  
> [!WARNING]  
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9158106089>
> Commit: a49094af46de1ba40ec27489a570a7723236d2e0
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9158106089&attempt=1" target="_blank">Click here!</a> …
=> fix: hide gs from airgap from most popular section

.github/workflows/client-build.yml, .github/workflows/pr-cypress.yml, .github/workflows/scripts/client-build-compliance.js
We have a check when running Cypress tests to ensure that no new `.js` files are added under Cypress folder. This PR moves this check to a separate JS file. There's another check that does some ADS compliance, which I'll port in a follow-up PR.
Why am I hitting on this? One, to move away from `umani/changed-files` workflow, which has randomly failed for us in the past, and id doesn't do so much special for us anyway. Two, this workflow is the last usage of `APPSMITH_CI_TEST_PAT` secret, so I should be able to remove that secret as well. One less secret.
=> ci: Move check for new JS Cypress tests to GitHub script

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/RepositoryHelperMethods.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/ce/V10__createSystemThemes.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/ce/V11__cleanPermissionsInPermissionGroups.java
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: Migration for system themes

deploy/docker/fs/opt/appsmith/caddy-reconfigure.mjs
Looks like while replacing NGINX with Caddy, Heroku deployment usecase was missed.
Updated Caddyfile generation to use `$PORT` if available.
Fixes #33555 
Tested on Heroku Standard-2x Dyno.
> [!CAUTION]  
=> fix: Consider heroku deployment while generating Caddyfile

app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/AppsmithRepository.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/BaseAppsmithRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomActionCollectionRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomActionCollectionRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutCollectionServiceCEImpl.java
Reduce usage of MongoDB-specific APIs. Needed for Postgres. 
/test sanity
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9159562023>
> Commit: 563b633b814562a6d300cf09a5ac233b0ecee54b
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9159562023&attempt=1" target="_blank">Click here!</a>
=> chore: Remove UpdateDefinition from MongoDB API

app/client/src/layoutSystems/anvil/editor/AnvilEditorDetachedWidgetOnion.tsx, app/client/src/layoutSystems/anvil/editor/canvasArenas/AnvilModalDropArena.tsx, app/client/src/layoutSystems/anvil/editor/canvasArenas/hooks/useAnvilDnDEventCallbacks.ts, app/client/src/layoutSystems/anvil/editor/canvasArenas/hooks/useAnvilDnDEvents.ts, app/client/src/layoutSystems/anvil/editor/canvasArenas/hooks/useAnvilDnDListenerStates.ts, app/client/src/layoutSystems/anvil/editor/hooks/useAnvilDetachedWidgetsDnD.ts, app/client/src/layoutSystems/common/selectors.ts, app/client/src/layoutSystems/withLayoutSystemWidgetHOC.test.tsx
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX19Ze0CWc0MPiDhT4RTyUsPUbCSPCyn6Lc%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=DEipBn-)
In this PR, we are adding an enhancement to DnD of modal widgets.
DnD was implemented only for layouts so in the case of modal, the header and footer are not layouts and DnD is not triggered when a widget is being dragged on top of these components of a modal.
However for the user to be able to efficiently use the DnD of modal, mouse events of the modal are also needed to be processed.
To enable this we have a new hook that wraps all detached widgets in editor mode only, `useAnvilDetachedWidgetsDnD`
It makes sure mouse move …
=> feat: enable DnD for entire modal widget(including header and footer).

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/DSLMigrationUtils.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/RTSCaller.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/InstanceConfigHelperCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AstServiceCEImpl.java
We need this flexibility for some API calls in the EE, and it doesn't make much sense to have separate API signatures for CE/EE.
/test sanity
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9173253978>
> Commit: 422aaa8863aa3aa0039ac60cb46e370ea89127f7
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9173253978&attempt=1" target="_blank">Click here!</a>
=> chore: Refactor RTSCaller API signatures for more flexibility

app/client/src/widgets/wds/WDSBaseInputWidget/config/contentConfig.ts, app/client/src/widgets/wds/WDSInputWidget/config/propertyPaneConfig/contentConfig.ts
Fixes #33192
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9173647447>
> Commit: dfcc9ca09ad310f6ecad93c7ac924c61cbb4d50e
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9173647447&attempt=1" target="_blank">Click here!</a>
=> chore: hide fields in input widget when field is readonly

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/UserConfig.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/UpdateSuperUserHelper.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/UpdateSuperUserHelperCE.java
This PR replaces repeating updateSuperUser migration that was existing on MongoDB, and instead create bean for the same because of dependency injection used in migration previously.
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: creating super user bean through bean

app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/SshTransportConfigCallback.java
RSA with default JCE does not support OpenSSH format which is needed for backwards compatibility with Azure repos and the SHA1 keys we used to generate for them earlier.
_or_  
> [!WARNING]  
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9185405942>
> Commit: ddc01b0473d48c4c9a7e8ed310f6bbedc15fe920
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9185405942&attempt=1" target="_blank">Click here!</a>
Should the DevRel and Marketing teams …
=> chore: Switched key factory for RSA to BC as well

app/client/src/ce/selectors/entitiesSelector.ts, app/client/src/pages/Editor/IDE/EditorPane/JS/Add.tsx, app/client/src/pages/Editor/IDE/EditorPane/Query/Add.tsx, app/client/src/pages/Editor/IDE/EditorPane/Query/QueryRender.test.tsx, app/client/src/pages/Editor/IDE/EditorPane/components/SegmentAddHeader.tsx
Fixes issues in add pane 
Fixes #33583
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9178183004>
> Commit: eeb8f4067fd18779380c0918ba9c4bd294b5134d
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9178183004&attempt=1" target="_blank">Click here!</a>
=> fix: Add pane issues

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonDBConfig.java, deploy/docker/fs/opt/appsmith/entrypoint.sh
Reverts appsmithorg/appsmith#33652
Reverting the change as the root cause was different https://theappsmith.slack.com/archives/C0134BAVDB4/p1716393908273869?thread_ts=1716375955.137629&cid=C0134BAVDB4
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9201290830>
> Commit: 8e623fa37565078c23f1a307cbdfa416cfa89ed0
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9201290830&attempt=1" target="_blank">Click here!</a>
=> revert: "fix: Remove the strict check for mongo url"

deploy/docker/base.dockerfile
The newer NodeJS version `20.13` requires a more recent version of glibc, one which isn't available on Ubuntu 20.04 yet. We need to stick to NodeJS v20.11 until we can update Ubuntu itself to 22.04, or the updated glibc shows up in Ubuntu 20.04.
Pinning NodeJS version for now to unblock.
/test sanity
> [!IMPORTANT]
> 🟣 🟣 🟣 Your tests are running.
> Tests running at: <https://github.com/appsmithorg/appsmith/actions/runs/9203860279>
> Commit: 4d0f6063e063660f8502b493e2f07f04d6beb6ce
> Workflow: `PR Automation test suite`
=> chore: Pin NodeJS version to the one in package.json

app/client/src/widgets/wds/WDSCurrencyInputWidget/widget/index.tsx
Fixes #31604
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9202493096>
> Commit: 9f675180c1efd31a272f73dfa9193192710222de
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9202493096&attempt=1" target="_blank">Click here!</a>
=> chore: don't trigger onFocus for readonly currency input widget

app/client/src/ce/api/UserApi.tsx, app/client/src/ce/pages/AdminSettings/config/general.tsx, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/InstanceAdminControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/EnvManagerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/EnvManagerCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/EnvManagerTest.java
/ok-to-test tags="@tag.Settings,@tag.Sanity"
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9203402018>
> Commit: 200f008e602d5173a6167209b8b7804c086e8fb8
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9203402018&attempt=1" target="_blank">Click here!</a>
=> fix: Remove the feature to download docker-compose file from admin settings

app/client/src/widgets/wds/WDSCurrencyInputWidget/config/autocompleteConfig.ts, app/client/src/widgets/wds/WDSCurrencyInputWidget/widget/derived.js, app/client/src/widgets/wds/WDSCurrencyInputWidget/widget/index.tsx, app/client/src/widgets/wds/WDSPhoneInputWidget/config/autocompleteConfig.ts, app/client/src/widgets/wds/WDSPhoneInputWidget/widget/index.tsx
Minor refactor consistency with WDSInputWidget. This PR refactors "text" to parsedText and "value" to rawText so there is no confusion in what is what.
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9205775397>
> Commit: 527ec195718795a33804d23728447431f274343b
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9205775397&attempt=1" target="_blank">Click here!</a>
=> chore: refactor text and value to parsedText and rawText

app/client/src/ce/utils/AnalyticsUtil.tsx
Updating the nomenclature for version in analytics from `appsmithVersion` to `version`.
Fixes [#1672](https://github.com/appsmithorg/cloud-services/pull/1672)
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9206459797>
> Commit: e3c1923a57deda96f88945a2be8cdba1c395ccba
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9206459797&attempt=1" target="_blank">Click here!</a>
=> chore: Updating the nomenclature for version in analytics from `appsmithVersion` to `version`

.github/workflows/ci-debugging.yml, .github/workflows/ci-test-custom-script.yml, .github/workflows/ci-test-limited.yml
The upcoming TED version is about come with a Git repo, baked into the image. We're going to use this to test import of git repos.
But since we mount a blank folder onto this, the baked-in contents of `/git-server/repos` is effectively cleared and overwritten. This PR fixes that. We don't really need this volume mount, should be okay to remove.
/test sanity
=> ci: Don't mount volume for TED's git repos

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ImportExportUtils.java
- modified logic to copy the ApplicationDetails object of the importedApplication to existing application
Fixes #24920
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9207111058>
> Commit: 9d426c0ab94360ad964fbaaa267ee2485c10a322
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9207111058&attempt=1" target="_blank">Click here!</a>
=> fix: added fix for vanishing appdetails

.github/workflows/ci-test-custom-script.yml, .github/workflows/ci-test-limited.yml
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9210729164>
> Commit: ffb04c3dd1eb214aa4d3cdd3d97a28ca0ada7de1
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9210729164&attempt=1" target="_blank">Click here!</a>
=> chore: Cleanup Flagsmith envs from CI

app/client/src/sagas/ApiPaneSagas.ts
Alternate solution to #33627 to fix the `NA` group of newly created Rest API actions
Fixes #33583
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9218802021>
> Commit: 74c7bd40f21cc47754bde9a44d4ae47728063bb8
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9218802021&attempt=1" target="_blank">Click here!</a>
=> fix: new API getting added into the NA group

app/client/src/layoutSystems/anvil/integrations/modalSelectors.ts, app/client/src/widgets/wds/WDSModalWidget/widget/index.tsx
Closing the modal widget name component was delayed due to the fact that the DOM node that the widget name component used as a reference, was still available even after the modal wasn't visible on the Canvas. 
This was due to the floating-ui taking time to remove the DOM node.
As a fix, I've made react remove the DOM node when the state for the modal visibility is set to `false`.
Now, the widget name component closes as soon as it discovers that the reference is hidden.
Additional fix: Changed the detached widget hook functions to be agnostic of the term "modal".
Fixes #33381  
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9219824326>
> Commit: …
=> fix: Anvil: Fix the delay in closure of modal widget name component on modal close

.github/workflows/scripts/test-tag-parser.js
**/test all**
> [!WARNING]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9243140883>
> Commit: abf3814fd6bfa308353d1042e5df2ef75e02fd0a
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9243140883&attempt=1" target="_blank">Click here!</a>
> It seems like **no tests ran** 😔. We are not able to recognize it, please check workflow <a href="https://github.com/appsmithorg/appsmith/actions/runs/9243140883" target="_blank">here.</a>
=> ci: Support for "all" tag in /test and allow bold

app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/ApplicationCreationDTO.java
Test for this is already there, `AnvilAppNavigation_spec`, which is currently marked as flaky. Will unmark once we merge this in, verified to pass locally. It's the _only_ functionality in the product that uses this field in the request body today.
/test sanity
=> chore: Fix typo in request field name

app/client/src/api/ActionAPI.tsx
For action update API, client is sending in some fields that the server isn't expecting. As part of tightening what the server accepts in APIs for better security testing, this PR removes these unexpected fields, and sends only what the server knows about, and expects.
/test sanity datasource
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9250048039>
> Commit: f0f19256da15996a2dbf3acc9bf18483c9a3c3b2
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9250048039&attempt=1" target="_blank">Click here!</a>
=> chore: Remove unexpected fields in action update payload

.github/workflows/test-build-docker-image.yml
CI-Test-Result should fail depending on unit tests
=> CI: CI-Test-Result should fail depending on unit tests

deploy/docker/fs/opt/appsmith/generate-infra-details.sh
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: Update incorrect docker tagging and add fargate tag in deployment telemetry 

app/client/src/ce/constants/ModuleConstants.ts
Updates to module constants for easy extension in EE
PR for https://github.com/appsmithorg/appsmith-ee/pull/4257
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9218704577>
> Commit: ca8fbda349f665207bbd1c36339a8ac01c60b43d
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9218704577&attempt=1" target="_blank">Click here!</a>
=> chore: update module constants

.github/workflows/scripts/test-tag-parser.js, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/LayoutControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/LayoutUpdateDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutServiceCEImpl.java
Goal is to remove `Layout` class being used to deserialise request payloads. There's two routs in `LayoutControllerCE` that are doing this.
1. The `POST /api/v1/layouts/pages/{pageId}` seems unused, so removing that.
2. The `PUT /api/v1/layouts/{layoutId}/pages/{pageId}` only gets a single field in the JSON body, called `dsl`. So we introduce a `record` to accept just that.
All in an effort towards remove `@JsonProperty` from `Layout`, so it can work correctly with Postgres.
**/test all**
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9254557613>
> Commit: a8ebac28e571d3c89ec8a5fcb6ac9cdc1e8f308f
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9e …
=> chore: Don't use `Layout` class for parsing request payloads

app/client/cypress/support/queryCommands.js
RCA: There are many unused commands within queryCommands.js file
Solution:
Checked the queryCommands in both CE and EE repository and we are removing those commands which are not used in any tests as part of cleanup activity
Equivalent EE PR: https://github.com/appsmithorg/appsmith-ee/pull/4280
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9184621910>
> Commit: 5a42872d27a69c2453038410755ea17bbb0ad6f8
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9184621910&attempt=1" target="_blank">Click here!</a>
=> test: updated queryCommands file

app/client/cypress/support/themeCommands.js
RCA: There are many unused commands within themeCommands.js file
Solution:
Checked the themeCommands in both CE and EE repository and we are removing those commands which are not used in any tests as part of cleanup activity
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9184741418>
> Commit: 84481f0e7ad9cdf5c70019c9f1c9d058fb89306c
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9184741418&attempt=1" target="_blank">Click here!</a>
=> test: updated themeCommands

app/client/cypress/support/WorkspaceCommands.js
RCA: There are many unused commands within workspaceCommands.js file
Solution:
Checked the workspaceCommands in both CE and EE repository and we are removing those commands which are not used in any tests as part of cleanup activity
Equivalent EE PR: https://github.com/appsmithorg/appsmith-ee/pull/4280
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9184655745>
> Commit: 043cf1259bd354509b337b561c9fab5079ff49ee
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9184655745&attempt=1" target="_blank">Click here!</a>
=> test: updated workspace commands

app/client/src/components/editorComponents/PartialImportExport/PartialExportModal/unitTestUtils.ts, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/AuthenticationDTO.java
The `hasExpired` method has a `@JsonView` annotation, that causes it to be included in JSON responses. But the return type of this method is `Mono<Boolean>`, so obviously, it doesn't produce anything useful in the resulting JSON:
This is from the response of updating an authenticated API with basic auth.
Client doesn't care for this field in the response.
This is failing to be serialized at all, when saving to database in Postgres.
**/test sanity datasource**
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9256537717>
> Commit: 9204d9f01c62d2981eb03c3603a7294a9cc5b41d
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=92 …
=> chore: Remove `@JsonView` on `hasExpired` method

app/server/appsmith-server/src/test/java/com/appsmith/server/controllers/PageControllerTest.java
This test isn't actually testing anything since the page creation API doesn't accept any `customSlug` field at all.
=> test: Page creation API doesn't have a `customSlug` field

app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/GlobalExceptionHandler.java
We see this:
```
400 BAD_REQUEST "Failed to read HTTP message";; JSON decoding error: Unrecognized field "showNavbar" (class com.appsmith.server.dtos.ApplicationCreationDTO), not marked as ignorable;; Unrecognized field "showNavbar" (class com.appsmith.server.dtos.ApplicationCreationDTO), not marked as ignorable (6 known properties: "workspaceId", "color", "icon", "name", "showNavBar", "positioningType"])
at [Source: (org.springframework.core.io.buffer.DataBufferInputStream); line: 1, column: 156] (through reference chain: com.appsmith.server.dtos.ApplicationCreationDTO["showNavbar"])
```
<details>
<summary>Instead of this (collapsed cause it's too big)</summary>
```
org.springframework.web.server.ServerWebInputException: 400 BAD_REQUEST "Failed to read HTTP message"
at …
```
=> chore: No stack trace on 400

app/client/src/widgets/wds/WDSTableWidget/widget/derived.js
Fixes #33773
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9265326451>
> Commit: ce5ab34c71fa21bd56322859cd21813ed7aed7aa
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9265326451&attempt=1" target="_blank">Click here!</a>
=> chore: Default search text is considered irrespective of 'allow searching' toggle value

.github/workflows/rts-build.yml
This is being done to ensure that RTS jest test cases are run in TBP on release as well as master.
_or_  
> [!WARNING]  
> [!CAUTION]  
=> test: Running jest test cases if no PR is present as part of RTS build

app/client/cypress/support/dataSourceCommands.js
RCA: There are many unused commands within dataSourceCommands.js file
Solution:
Checked the dataSourceCommands in both CE and EE repository and we are removing those commands which are not used in any tests as part of cleanup activity
Equivalent EE PR: https://github.com/appsmithorg/appsmith-ee/pull/4280
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9184573870>
> Commit: 5b15c17728d13ccb6324346204421e0fb8c746bc
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9184573870&attempt=1" target="_blank">Click here!</a>
=> test: updated dataSourceCommands file

app/client/src/components/propertyControls/IconSelectControlV2.tsx
Fixes #33302
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9265300420>
> Commit: 5c9aedab4a27061b197e4a9ef89111dabc0f9d0f
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9265300420&attempt=1" target="_blank">Click here!</a>
=> chore: Icon property field stretches beyond the property pane boundary

app/client/cypress/support/ApiCommands.js
RCA: There are many unused commands within ApiCommands.js file
Solution:
Checked the ApiCommands in both CE and EE repository and we are removing those commands which are not used in any tests as part of cleanup activity
Equivalent EE PR: https://github.com/appsmithorg/appsmith-ee/pull/4280
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9184697515>
> Commit: f0a8dcfe6e30b924152335cfed1d376c501deaea
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9184697515&attempt=1" target="_blank">Click here!</a>
=> test: updated ApiCommands

app/client/packages/design-system/theming/src/color/src/DarkModeTheme.ts, app/client/packages/design-system/theming/src/color/tests/DarkModeTheme.test.ts
Fixes #33623 
| Before | After |
|--------|--------|
| ![Screenshot 2024-05-28 at 12-10-22 Untitled application 1 Editor Appsmith](https://github.com/appsmithorg/appsmith/assets/80973/3206e718-d062-4d86-8d6d-adf7cf1c00f2) | ![Screenshot 2024-05-28 at 12-12-08 Untitled application 1 Editor Appsmith](https://github.com/appsmithorg/appsmith/assets/80973/aea0ef7c-fe38-41ec-bcd9-31df4e4c49c7) | 
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9267589083>
> Commit: 57a332a7a2f141df4479f265f235df56fb1654bf
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9267589083&attempt=1" …
=> chore: WDS inputs in dark mode with better visibility

app/client/src/layoutSystems/anvil/editor/AnvilWidgetName/index.tsx, app/client/src/layoutSystems/anvil/editor/AnvilWidgetName/utils.ts
Even if the parent widget is already selected, show the parent widget selection toggle in widget name components
> [!WARNING]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9284066525>
> Commit: b6832ad46fa0866e5f89963ab02d08e8b2585139
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9284066525&attempt=2" target="_blank">Click here!</a>
> It seems like **no tests ran** 😔. We are not able to recognize it, please check workflow <a href="https://github.com/appsmithorg/appsmith/actions/runs/9284066525" target="_blank">here.</a>
=> fix: Anvil: Always show parent toggle in widget name component

app/server/appsmith-server/src/main/java/com/appsmith/server/imports/internal/partial/PartialImportServiceCEImpl.java
This change ensures that the name clashing issue does not check for widget names as we are doing that on client side.
* In addition it also filter out names that are non-clashing.
Fixes #
_or_  
> [!WARNING]  
/ok-to-test tags="@tag.Widget, @tag.Templates"
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9288005025>
> Commit: 5e5c6507c322727a0dd9791ea999c40f93509388
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9288005025&attempt=1" target="_blank">Click here!</a> …
=> fix: Update PartialImportServiceCEImpl to fetch all existing entities with true flag

app/client/packages/design-system/widgets/src/components/Checkbox/chromatic/Checkbox.chromatic.stories.tsx, app/client/packages/design-system/widgets/src/components/Checkbox/src/Checkbox.tsx, app/client/packages/design-system/widgets/src/components/Checkbox/src/styles.module.css, app/client/packages/design-system/widgets/src/components/Checkbox/stories/Checkbox.stories.tsx, app/client/packages/design-system/widgets/src/styles/src/field.module.css
Fixes #33444
> [!WARNING]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9297202278>
> Commit: 895c87c82e1b55e4d604870c89512200c408ef41
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9297202278&attempt=1" target="_blank">Click here!</a>
> It seems like **no tests ran** 😔. We are not able to recognize it, please check workflow <a href="https://github.com/appsmithorg/appsmith/actions/runs/9297202278" target="_blank">here.</a>
=> chore: Checkbox widget does not show an asterisk to indicate it's a required

app/client/src/widgets/wds/WDSInputWidget/component/index.tsx, app/client/src/widgets/wds/WDSInputWidget/component/types.ts, app/client/src/widgets/wds/WDSInputWidget/widget/index.tsx
Fixes #33080
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9300922932>
> Commit: fc768c03c81d4fe8371c2f708535c3a1194e6073
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9300922932&attempt=1" target="_blank">Click here!</a>
=> chore: Don't allow paste if input type is number and pasted text is not

app/client/src/ce/constants/messages.ts
General sub text should't contain share as there is no such option.
Fixes #19200
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9298988680>
> Commit: 0cbaea95bdeb1661b2e44b0a972495b8c549c990
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9298988680&attempt=3" target="_blank">Click here!</a>
=> fix: correct general settings description

app/client/start-caddy.sh, app/client/start-https.sh
- Remove the deprecated message in `start-https.sh` script and suggestion to use caddy as it is still work in progress. 
/test perf
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9305335810>
> Commit: f3be0a2e583ac409d32dcdbdc50f67e168fa0215
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9305335810&attempt=1" target="_blank">Click here!</a>
=> chore: Remove deprecated start-https.sh message

app/client/src/layoutSystems/anvil/editor/AnvilWidgetName/index.tsx
- Fixes issue where we couldn't drag multiple widgets from the widget name component
- Previous and incorrect implementation:
- When starting a drag from the widget name component, we force selected the widget being dragged, so even if multiple widgets were selected, only one would drag.
- Fix approach
- When starting a drag from the widget name component, we check if the widget being dragged is focused. If it is focused, we select the widget before dragging. Otherwise, we directly allow dragging without any checks.
- The widget name component only shows up when the widget is either focused or selected. If it is selected, we don't need to select any widgets and whichever widgets are selected, they will be dragged. However, if a widget is only focused, we need to make sure that the …
=> fix: Anvil: Drag multiple widgets from widget name component

app/client/src/pages/Editor/DataSourceEditor/DSFormHeader.tsx
This PR addresses the issue where the confirmation popup does not dismiss after deleting a datasource. The issue was resolved by adding a key attribute to the MenuWrapper component, ensuring that React properly re-renders the component.
- Added key={datasourceId} to the MenuWrapper component in order to force React to re-render the component correctly.
Fixes #32954  
- Verified that the confirmation popup now dismisses properly after a datasource is deleted.
- Ensured that there are no regressions in related functionality.
- Video link - https://www.loom.com/share/35bb795e4ec04cbf807635b064ef3d1d?sid=9013d1a7-d528-453d-87e4-79d555321c98
> [!CAUTION]   …
=> fix: Confirmation popup not dismissing after deleting a datasource

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonConfig.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Tenant.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/TenantServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/TenantServiceCEImpl.java
PR to add `adminEmailDomainHash` field in GET tenant response, which will be consumed by client to add in analytics events.
Relevant thread: https://theappsmith.slack.com/archives/C04H5PFRN1H/p1715153325878529 
/ok-to-test tags="@tag.Settings"
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9297621747>
> Commit: ee43608aadcc84e180a280d54b41906fe5ff4953
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9297621747&attempt=1" target="_blank">Click here!</a>
=> chore: Add admin email domain hash to get tenant API

app/client/src/ce/workers/Evaluation/generateOverrideContext.ts, app/client/src/ee/workers/Evaluation/generateOverrideContext.ts, app/client/src/workers/Evaluation/__tests__/evaluate.test.ts, app/client/src/workers/Evaluation/evaluate.ts, app/client/src/workers/common/DataTreeEvaluator/index.ts, app/client/src/workers/common/DataTreeEvaluator/test.ts
Adds `overrideContent` to be set during the execution of actions during runtime with execution params. This features enables to override properties/paths of entities during runtime and not affecting the dataTree. For now, this will be used for module instance execution in EE
PR for https://github.com/appsmithorg/appsmith-ee/pull/4304
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9312695760>
> Commit: aed3c9944144a00c353d490ff8ef0fa117e20c06
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9312695760&attempt=1" target="_blank">Click here!</a>
Should the DevRel and Marketing teams inform …
=> chore: Add override context during runtime params eval

app/client/src/widgets/TableWidgetV2/widget/propertyConfig/PanelConfig/Data.ts, app/client/src/widgets/TableWidgetV2/widget/utilities.ts
Fixes #33858
/ok-to-test tags="@tag.Table"
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9318008514>
> Commit: 1ea0a6325c234a41c431c92329e3fa8e9d4fdf45
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9318008514&attempt=1" target="_blank">Click here!</a>
=> fix: add customJS control for currency, notation and thousand separator

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/git/constants/GitConstants.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/git/constants/ce/GitConstantsCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java, app/server/appsmith-server/src/main/java/com/appsmith/server/git/AutoCommitEventHandlerCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/git/AutoCommitEventHandlerImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/git/GitRedisUtils.java, app/server/appsmith-server/src/main/java/com/appsmith/server/git/autocommit/helpers/AutoCommitEligibilityHelperImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/RedisUtils.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/CommonGitServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CommonGitServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce_compatible/CommonGitServiceCECompatibleImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce_compatible/GitServiceCECompatibleImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/git/autocommit/AutoCommitEventHandlerImplTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/git/autocommit/helpers/AutoCommitEligibilityHelperTest.java
- Introduction of context to redis file locks for git operations. Now the lock would be aware of what command has placed the it.
_or_  
> [!WARNING]  
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9318823149>
> Commit: 278716d520d9a08e5b39bc24faf770840bf45220
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9318823149&attempt=1" target="_blank">Click here!</a>
=> chore: Adding logging mechanism to find out context of redis git locks

app/client/src/pages/Editor/DataSourceEditor/DBForm.tsx
Made callout text in database sources selectable.
Fixes #33676 
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9306800336>
> Commit: 7abb5b85200e82178ff3d4aeed937aca15bc0ee8
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9306800336&attempt=1" target="_blank">Click here!</a>
=> perf: make text selectable

app/client/cypress/e2e/Regression/ClientSide/Branding/Branding_spec.js, app/client/cypress/e2e/Regression/Enterprise/AdminSettings/Admin_settings_spec.js, app/client/cypress/locators/AdminsSettings.js, app/client/src/ce/pages/AdminSettings/Branding/UpgradeBanner.tsx
Updating the locator for upgrade button on admin settings
_or_  
> [!WARNING]  
/ok-to-test tags="@tag.Settings"
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9316188465>
> Commit: 34d8a389fe7a06f400f794696daad5171c4fdef7
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9316188465&attempt=1" target="_blank">Click here!</a>
=> test: Updating the locator for upgrade button on admin settings

app/server/appsmith-server/src/main/java/com/appsmith/server/domains/GitProfile.java
The `GitProfile` is not used as an entity class, and doesn't need a collection/table in the database.
=> chore: Remove unneeded `@Document` on GitProfile

app/client/src/ce/api/ApplicationApi.tsx, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Application.java
Not removing this field from Cypress test resources, so that we continue to test with past export files.
/test all
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9344945556>
> Commit: b97cece10c2e20d9552ac0942badd9d9a9e47850
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9344945556&attempt=2" target="_blank">Click here!</a>
=> chore: Remove `unreadCommentThreads`

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/constants/AnalyticsConstants.java, app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonConfig.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/User.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/UserRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AnalyticsServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/TenantServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UsagePulseServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PingScheduledTaskCEImpl.java
PR to enhance analytics:
- User tracking: DAU, WAU, MAU  
- Hashed admin email domain
Update `instance_stats` properties for ref:
```
{
"event": "instance_stats",
"properties": {
"DAU": 2,
"MAU": 3,
"WAU": 3,
"adminEmailDomainHash": "eb93d881805376ef5297d8ac6fe95970f47d7bbd8d849b3a0d9c7af188caf648",
"cloudProvider": "",
"deployedAt": "",
"edition": "CE",
"efs": "",
"emailDomainHash": "eb93d881805376ef5297d8ac6fe95970f47d7bbd8d849b3a0d9c7af188caf648",
"hostname": "",
"instanceId": "6656f32dd841a66006d1ddc3",
"numActions": "8",
"numApps": "2",
"numDatasources": "2",
"numOrgs": "2",
"numPages": "2",
"numPublicApps": "0",
"numUsers": "3",
"tool": "",
"version": "UNKNOWN"
},
"receivedAt": "2024-05-31T11:48:35.831Z",
"timestamp": "2024-05-31T11:48:35.831Z",
"type": "track",
"userId": …
```
=> chore: Add admin email domain hash and user tracking to analytics events

app/client/packages/design-system/headless/src/components/TextArea/src/TextArea.tsx, app/client/packages/design-system/widgets/src/styles/src/text-input.module.css
Fixes #33099
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9318021083>
> Commit: 5f1ea63400f06fa9d22e0aa41c81e44fdf7b1deb
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9318021083&attempt=1" target="_blank">Click here!</a>
=> chore: Fix extra space at the end of multi-line input widget #33099

app/client/src/pages/Editor/PropertyPane/PropertyPaneView.tsx, app/client/src/pages/Editor/PropertyPane/helpers.tsx, app/client/src/widgets/CircularProgressWidget/widget/index.tsx, app/client/src/widgets/DatePickerWidget/widget/index.tsx, app/client/src/widgets/DropdownWidget/widget/index.tsx, app/client/src/widgets/FilepickerWidget/widget/index.tsx, app/client/src/widgets/FormButtonWidget/widget/index.tsx, app/client/src/widgets/IconWidget/widget/index.tsx, app/client/src/widgets/InputWidget/widget/index.tsx, app/client/src/widgets/ListWidget/widget/index.tsx, app/client/src/widgets/MultiSelectWidget/widget/index.tsx, app/client/src/widgets/ProgressBarWidget/widget/index.tsx
@rajatagrawal 
- In this PR I have added **getEditorCallout** method which can also used to return deprecataed messages. 
- I have updated above method for these deprecated widgets:
-   InputWidget
-   DropdownWidget
-   DatePickerWidget
-   IconWidget
-   FilePickerWidget
-   MultiSelectWidget
-   FormButtonWidget
-   ProgressBarWidget
-   CircularProgressWidget
-   ListWidget
**OUTPUT:**
> [!TIP]  
>
Fixes …
=> chore: Move widget deprecation messages from propertyPaneView to individual Widget configurations

app/client/src/ce/constants/messages.ts
@RoopKrrish9696 , Please review
> [!TIP]  
> _User should be able to get correct tooltip message :
When the remote branch is ahead of the local branch along with the user is having some uncommitted changes.
Tooltip message should be “You have uncommitted changes, please commit or discard your changes before pulling the remote changes”._
> in simple words, we have added `commit or discard` in the message
Fixes #`32973`  
_or_  
Fixes https://github.com/appsmithorg/appsmith/issues/32973
> [!WARNING]  
> [!CAUTION]  
Should the DevRel and Marketing teams inform users …
=> feat: tooltip message change of git pull button

app/client/src/components/editorComponents/Debugger/LogItem.tsx
Individual words in debugger messages can now be selected.
Fixes #22110
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9370104155>
> Commit: 2fe182144e71e0b5fc610d680a38caadc0fe557e
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9370104155&attempt=1" target="_blank">Click here!</a>
=> fix: make individual words in label selectable #22110

app/client/src/components/editorComponents/CodeEditor/constants.ts, app/client/src/components/editorComponents/CodeEditor/styledComponents.ts, app/client/src/components/editorComponents/LazyCodeEditor/styles.tsx, app/client/src/globalStyles/CodemirrorHintStyles.ts, app/client/src/utils/autocomplete/ternDocTooltip.tsx
The color for a code property is being used more than once but not available as a constant. This PR changes that.
I also moved the `CodeEditorColors` enum to a file where it's less likely to cause circular dependencies. It was moved from `{...}/CodeEditor/styledComponents.ts` to `{...}/CodeEditor/constants.ts`.
_Not related to an existing issue._
> [!CAUTION]  
=> chore: add `PROPERTY` color constant in `CodeEditorColors`

app/client/src/ce/navigation/FocusStrategy/AppIDEFocusStrategy.test.ts, app/client/src/ce/navigation/FocusStrategy/AppIDEFocusStrategy.ts
[`FocusRetentionSaga`](https://github.com/appsmithorg/appsmith/blob/d71e050fa6ad1da1aed222d756fb2c523c75d322/app/client/src/sagas/FocusRetentionSaga.ts) is not respecting the GraphQL API editor [subtype](https://github.com/appsmithorg/appsmith/blob/release/app/client/src/ce/navigation/FocusElements/AppIDE.ts#L162-L164) when the page is being loaded because it's running its focus management logic before knowing that the action being edited is in fact a GraphQL plugin action.
So now I am waiting for the app's actions and plugins to be loaded before the [focus retention logic](https://github.com/appsmithorg/appsmith/blob/d71e050fa6ad1da1aed222d756fb2c523c75d322/app/client/src/sagas/FocusRetentionSaga.ts#L183-L210) is run.
<table>
<tr>
<td><strong>Before
<td><strong>After
<tr>
<td> …
=> fix: fetch actions and plugins before choosing which GQL editor tab to focus

app/server/appsmith-server/src/main/java/com/appsmith/server/git/autocommit/helpers/GitAutoCommitHelperImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ConsolidatedAPIServiceImpl.java
- In the last implementation of auto-commit we were comparing dslVersion of page dsl object with rts's latest version as a criteria to trigger auto-commit. This check was implemented in the page fetch section of `consolidated api call (page load)` itself. Since page dsls are migrated in the consolidated api, hence we required this check to be executed before the pages of application were migrated. Now that is not the case anymore. hence order of execution for home page load is not a constraint anymore. A removal is in order.
- Added a feature flag annotation with `release_git_autocommit_feature_enabled` to stop feature flag leaks on publisheAutocommitEvent method call.
_or_  
> [!WARNING]  
> _If no issue exists, please create an issue first, and …
=> chore: removed constraint on order of execution for consolidated apis

app/client/src/widgets/wds/WDSInputWidget/widget/index.tsx
Fixes #34000
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9460620209>
> Commit: fd17eacb6f9edee8905fb5cf1054b56822f2c3cd
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9460620209&attempt=1" target="_blank">Click here!</a>
=> chore: fix Read only widget incorrectly triggers configured actions that are hidden because of the toggle

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/BaseDomain.java
Remove the `deleted` field since
1. it'll be removed from `release` branch soon.
2. we aren't creating the corresponding `deleted` column in database tables anyway.
=> chore: Remove `deleted` boolean field

app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Application.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ce/ArtifactCE.java
Adds a method that is not exposed externally yet to start to get baseId information in applications.
Carried from https://github.com/appsmithorg/appsmith-ee/pull/4408
> [!CAUTION]  
=> chore: Add baseId to app

app/client/src/pages/Editor/EditorName/index.tsx, app/client/src/pages/Editor/EditorName/useNavigationMenuData.ts
Reverted missed out code in https://github.com/appsmithorg/appsmith/pull/34367
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9608916182>
> Commit: a2525661414e7bb571914ede981383778e9c4d56
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9608916182&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.IDE`
=> chore: Fix missing changes in revert #34313

.github/workflows/build-client-server.yml
Fix non used matrix parameter in build-client-server.yml. It was removed from originated function parameter.
Fixes #`34418`  
> [!IMPORTANT]
> 🟣 🟣 🟣 Your tests are running.
> Tests running at: <https://github.com/appsmithorg/appsmith/actions/runs/9640650543>
> Commit: acc2e4d8af13ae3c29a429c0e4db069976d69826
> Workflow: `PR Automation test suite`
=> ci: Fix non used matrix parameter in build-client-server.yml

app/client/cypress/e2e/Regression/ClientSide/Git/GitSync/Merge_spec.js, app/client/cypress/limited-tests.txt, app/client/cypress/locators/gitSyncLocators.js, app/client/cypress/support/gitSync.js
RCA:
Locator was updated in the Ts helper and there was Js helper which was not updated
Solution:
Replaced js locator with ts locator
=> test: updated js methods to refer ts locators for Git Tests

scripts/deploy_preview.sh
If we don't specify a version with `--version`, the `help upgrade` command takes the latest version. [Ref documentation](https://helm.sh/docs/helm/helm_upgrade/).
=> ci: Use latest version of helm chart for DPs

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/BaseDomain.java, app/server/appsmith-server/src/test/java/com/appsmith/server/configurations/CommonConfigTest.java
**/test ImportExport git**
> [!CAUTION]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9761964432>
> Commit: 44fd1e67988bee13cbb8a3353825f04304daaf93
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9761964432&attempt=2&selectiontype=test&testsstatus=failed&specsstatus=fail" target="_blank">Cypress dashboard</a>.
> Tags: @tag.ImportExport, @tag.Git
> <li>cypress/e2e/Regression/ClientSide/Git/GitSync/GitSyncedApps_spec.js</ol>
> <a href="https://internal.appsmith.com/app/cypress-dashboard/identified-flaky-tests-65890b3c81d7400d08fa9ee3?branch=master" target="_blank">List of identified …
=> Revert "chore: Don't include `new` in responses (#34617)"

contributions/CodeContributionsGuidelines.md
As we are have been seeing contributors are adding new cypress tests we want to execute it using `ci-test-limit`. We need to always make a change to limited-tests file to run new test now we will trigger `ci-test-limit` directly to save efforts. 
Fyi: we need to revert `limited-tests.txt` after everything looks good on PR. this step to reduce one step effort from our side
_or_  
> [!WARNING]  
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9804245011>
> Commit: 8384096f415124619b17aac586b4a98ccd3717a5
> <a …
=> chore: added one more step for limited-tests to contributor guidelines

app/server/appsmith-server/src/test/java/com/appsmith/server/extensions/AfterAllCleanUpExtension.java, app/server/appsmith-server/src/test/java/com/appsmith/server/git/GitExecutorTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/testhelpers/cleanup/DBCleanup.java
PR to create separate helper class for adding the cleanup stage. This also makes sure `AfterAllCleanUpExtension` only implements the `AfterAllCallback` to achieve the isolation.
=> chore: Refactor cleanup methods for tests

app/server/appsmith-server/src/main/java/com/appsmith/server/datasources/base/DatasourceServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/datasources/base/DatasourceServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/datasources/importable/DatasourceImportableServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/ce/MappedImportableResourcesCE_DTO.java, app/server/appsmith-server/src/test/java/com/appsmith/server/imports/internal/ImportServiceTests.java
In the import service, we are trying to import datasources using the combination of Flux and Flatmap to create the reactive chain. This translates to creating multiple threads to accomplish the task in an efficient manner. After we introduced database dry ops, where we are now sharing the map of ops type to the object for which the operation needs to be performed. This caused a `concurrentModificationException` as datasourceService layer is referring to same object via different threads.   
/ok-to-test tags="@tag.ImportExport, @tag.Sanity, @tag.Git"
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9861701410>
> Commit: cf63fab15f7e3717b566306f8ea598662f18aea9
> <a …
=> fix: Concurrent modification exception during the datasource import flow

app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/columnTypes/Select1_spec.ts, app/client/src/widgets/TableWidgetV2/component/cellComponents/SelectCell.tsx
Reverts appsmithorg/appsmith#34743
_or_  
> [!WARNING]  
> [!CAUTION]  
=> fix: Cherrypick/revert-34872

app/client/src/components/editorComponents/CodeEditor/EditorConfig.ts, app/client/src/components/editorComponents/CodeEditor/hintHelpers.ts, app/client/src/components/editorComponents/CodeEditor/index.tsx, app/client/src/utils/autocomplete/AutocompleteSortRules.ts, app/client/src/utils/autocomplete/CodemirrorTernService.ts
> [!TIP]  
>
Fixes #34920  
_or_  
> [!WARNING]  
> [!CAUTION]  
=> fix: no queries to bind cta added in autocomplete

app/client/src/utils/autocomplete/CodemirrorTernService.ts
Added a check to filter the autocomplete options only for a single level i.e. if we have `{{}}` then list options like `Query1`, `Table1` etc, if we have `{{Query1}}` then list `Query1.data`, `Query1.clear` etc.
Fixes #35128
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: filtering the autocomplete options to be single level from input query

deploy/docker/fs/opt/appsmith/utils/bin/backup.js, deploy/docker/fs/opt/appsmith/utils/bin/constants.js, deploy/docker/fs/opt/appsmith/utils/bin/export_db.js, deploy/docker/fs/opt/appsmith/utils/bin/import_db.js, deploy/docker/fs/opt/appsmith/utils/bin/restore.js, deploy/docker/fs/opt/appsmith/utils/bin/utils.js
=> fix: failing backup and restore appsmithctl

app/client/src/pages/AppViewer/index.tsx, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/JsonSchemaMigration.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/JsonSchemaVersions.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/JsonSchemaVersionsFallback.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/MigrationHelperMethods.java, app/server/appsmith-server/src/main/java/com/appsmith/server/newactions/clonepage/ActionClonePageServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/imports/internal/ImportServiceTests.java, app/server/appsmith-server/src/test/java/com/appsmith/server/migrations/JsonSchemaMigrationTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/migrations/JsonSchemaVersionsTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/PageServiceTest.java
(cherry picked from commit 2ca40ecd391ea5553f99ad3a99e3eaa2cd337a30)
Added the hotfix for the hidden pages navigation issue.
Fixes #35557 
_or_  
> [!WARNING]  
> [!CAUTION]  
=> fix: hidden page was not being checked for route change

app/client/src/components/editorComponents/CodeEditor/index.tsx
Cherry picks https://github.com/appsmithorg/appsmith/commit/9b59d4da170a928f037cbe4518977aec1198b5f4
> [!CAUTION]  
=> fix: issue with opening custom widget source editor  (#35463)

app/client/src/pages/Editor/Explorer/Entity/EntityProperties.tsx, app/client/src/pages/Editor/IDE/EditorPane/Explorer.tsx, app/client/src/pages/Editor/IDE/EditorPane/index.tsx
Fix side effect introduced in #35611 that caused the widget pane to not be scrollable and extend beyond the IDE
Also fixes the show bindings issue not rendering correctly
Fixes #35584
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/10364931153>
> Commit: db587d1622bac1312da463a3f747c1b2bdf5763d
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=10364931153&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.IDE`
> Spec:
> <hr>Tue, 13 Aug 2024 07:11:51 UTC
=> fix: Widget Overflow and Show Binding issue

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/converters/OauthTypeConverter.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/OAuth2.java
With `@JsonProperty` we expect the fields to respect during (de)serialisation, but as per current values stored in MongoDB these are saved as per enum constants and not with the JsonProperty. Now on pg hibernate do follow all the annotation from Jackson and hence the de-serialization is failing there. To fix this we are introducing a custom (de)serialiser. 
Fixes https://github.com/appsmithorg/appsmith/issues/35764, https://github.com/appsmithorg/appsmith/issues/35818
/test datasource,sanity,fork,importExport,git,GSheet
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/10495391384>
> Commit: fceea9b23aa40326a0bfdbc0f1b34b89ae713b30
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7 …
=> chore: Fix Oauth2Type (de)serialization issue

app/client/cypress/e2e/Regression/ClientSide/Widgets/Checkbox/CheckboxGroup2_spec.js, app/client/cypress/limited-tests.txt
RCA:
Test was failing after removing retry, the issue was it was clicking on a checkbox which was not required.
the retry actually was bringing back the system to right state by clicking again.
Solution:
We removed the step that was unnecessary in this case which resolved the issue
EE: https://github.com/appsmithorg/appsmith-ee/pull/4992
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/10616697878>
> Commit: e599c6d0149814c38049aaba7828465361d8f43b
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=10616697878&attempt=1" target="_blank">Cypress dashboard</a>.
> Spec:
> <hr>Thu, 29 Aug 2024 …
=> test: updated tests for checkboxgroup

app/client/src/Datasource/components/ReconnectDatasourceForm.tsx, app/client/src/pages/Editor/gitSync/ReconnectDatasourceModal.tsx
Datasource modularisation - Take out reconnect datasource dependencies out of DatasourceEditor (part 1)
_or_  
> [!WARNING]  
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/10577633946>
> Commit: 2f06f3462ae073440b62c9cc7f7ab14a0fc0d1c2
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=10577633946&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Datasource`
> Spec:
> <hr>Tue, 27 Aug 2024 12:38:08 UTC
Should the DevRel and Marketing teams inform …
=> chore: reconnect ds detached from datasource editor part 1

app/server/appsmith-server/src/main/resources/application.properties
- Added thread in the logs, now an method running on threads would be visible.
for e.g. 
`[2024-09-02 06:56:16,840] [boundedElastic-2] requestId= userEmail= traceId= spanId= - Adding manage workspace policy map indices` 
The second brackets hold the thread on which this logging was run, the thread utilised is same as the one in which process is running.
> [!WARNING]  
> [!CAUTION]  
=> chore: Added threads to logging

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/Datasource.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/DatasourceConfiguration.java
- Added `Git.class` annotation in the datasource Configuration section for embedded datasource to keep the changes in file system 
_or_  
> [!WARNING]  
> [!CAUTION]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/10696824510>
> Commit: 18cbf33ede94c68f67585698bb4d3fa21231e3c6
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=10696824510&attempt=1&selectiontype=test&testsstatus=failed&specsstatus=fail" target="_blank">Cypress dashboard</a>.
> Tags: @tag.Git
> Spec: 
> The following are …
=> fix: Embedded datasource persistence changes for git.

app/client/src/sagas/ActionSagas.ts, app/client/src/sagas/ErrorSagas.tsx
Cherry Pick the PR: https://github.com/appsmithorg/appsmith/pull/36244
=> chore: Cherry Pick RBAC error fix

app/client/package.json, app/client/src/PluginActionEditor/components/PluginActionToolbar.tsx, app/client/src/ce/pages/Editor/AppPluginActionEditor/components/AppPluginActionToolbar.tsx, app/client/src/ce/pages/Editor/AppPluginActionEditor/components/PluginActionMoreActions.tsx, app/client/yarn.lock, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/DatasourceConfiguration.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/JsonSchemaMigration.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/JsonSchemaVersionsFallback.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/MigrationHelperMethods.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/utils/JsonSchemaMigrationHelper.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/ConsolidatedAPIServiceImplTest.java
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!WARNING]
> Tests have not run on the HEAD 71261b1e6e5dae84c3e69a345451bb3b551a4afe yet
> <hr>Mon, 16 Sep 2024 07:56:15 UTC
=> 16/09 Daily Promotion

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/converters/JSONObjectDeserializer.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/converters/JSONObjectSerializer.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/JsonForDatabase.java, app/server/appsmith-interfaces/src/test/java/com/appsmith/external/converter/JSONObjectDeserializerTest.java, app/server/appsmith-interfaces/src/test/java/com/appsmith/external/converter/JSONObjectSerializerTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutActionServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/ConsolidatedAPIServiceImplTest.java
This adds a custom serialiser and deserialiser to handle null values in the page DSL. The DSL object can have properties with null values and the object mapper used for the `jsonb` or the `CustomJsonType` had a custom implementation of object mapper which by default does not allow null values to persist to db. 
This change has added a new serialiser and deserialiser that is registered with created object mapper to include null values.
This is applied only for the `JSONObject` type attribute as of now.
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/10935288236>
> Commit: 01304913e4580887305a1bbeac534fee249fdf3f
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-658 …
=> chore: add custom serialiser and deserialiser to handle null values in the page DSL

.github/workflows/test-build-docker-image.yml
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: Add step to place server artifacts for `package-master` stage

app/client/cypress/e2e/Regression/ClientSide/IDE/Canvas_Context_Property_Pane_1_spec.js, app/client/cypress/limited-tests.txt
This test spec was working fine on EE/CE this fix will handle scenario in airgap environment
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/11026655789>
> Commit: f120b71d43a06123060ccfc3fcc0b3feb7b72d71
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=11026655789&attempt=1" target="_blank">Cypress dashboard</a>.
> Spec:
> <hr>Wed, 25 Sep 2024 05:41:09 UTC
=> test: fix test in airgap for canvas context prop

app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_Edit_spec.js, app/client/cypress/limited-tests.txt
Replacing the 3rd party API with TED API
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/11027894410>
> Commit: 0446747b46e74c3ea16b86578cab06fe04346b94
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=11027894410&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Datasource`
> Spec:
> <hr>Wed, 25 Sep 2024 07:37:49 UTC
=> test: replace 3rd party API1 CE

app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_Edit_spec.js, app/client/src/PluginActionEditor/components/PluginActionForm/PluginActionForm.tsx, app/client/src/PluginActionEditor/components/PluginActionForm/components/CommonEditorForm/hooks/useGetFormActionValues.ts, app/client/src/PluginActionEditor/components/PluginActionResponse/PluginActionResponse.tsx, app/client/src/widgets/BaseInputWidget/component/index.test.tsx, app/client/src/widgets/BaseInputWidget/component/index.tsx, app/client/src/workers/Evaluation/handlers/jsLibrary.ts
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> 27/09 Daily Promotion

app/client/cypress/e2e/Regression/ServerSide/OnLoadTests/JsOnLoad3_Spec.ts, app/client/cypress/limited-tests.txt
replace 3rd party API with TED
/ok-to-test tags="@tag.JS"
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/11102666520>
> Commit: 06354a9c09ce1e5f7d9018ce4eabeaac857ba023
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=11102666520&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.JS`
> Spec:
> <hr>Mon, 30 Sep 2024 09:26:01 UTC
=> test: replace 3rd party api with TED

app/client/cypress/e2e/Regression/ClientSide/Widgets/TreeSelect/Tree_Select_2_spec.ts, app/client/cypress/limited-tests.txt
Replaced 3rd Party API with TED
/ok-to-test tags="@tag.Select"
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/11102740010>
> Commit: 692dd2810fb4520bac6fe8aec3658a0cb70525ba
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=11102740010&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Select`
> Spec:
> <hr>Mon, 30 Sep 2024 09:21:05 UTC
=> test: replaced 3rd party apit in treeSelect

deploy/docker/fs/opt/appsmith/caddy-reconfigure.mjs
Changes
1. Remove the Cache Control header in the handle errors block. This change makes sure that the Cache control header set for /static/* route is remove in case the file is not found.
2. Rename the skip_log directive to log_skip. 
As per the caddy server docs
> Prior to v2.8.0, this directive was named skip_log, but was renamed for consistency with other directives.
Ref: https://caddyserver.com/docs/caddyfile/directives/log_skip
----
After this change the following are the response headers for a requests to valid and invalid static file path.
```
curl -I https://ce-36590.dp.appsmith.com/static/js/main.43ec809e.js
```
```
HTTP/1.1 200 OK
Accept-Ranges: bytes
Cache-Control: public, max-age=31536000, immutable
Content-Length: 7859533
Content-Security-Policy: default-src 'self' …
```
=> fix: remove cache control headers for requests handled with an error in Caddy

app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/spec_utility.ts, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/DatasourceDropdown/useSource/useConnectToOptions.tsx, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/WidgetSpecificControls/OtherFields/Field/Dropdown/useDropdown.tsx, deploy/docker/fs/opt/appsmith/entrypoint.sh, deploy/docker/fs/opt/appsmith/pg-utils.sh
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> 08/10 Daily Promotion

app/client/src/ce/hooks/hooks.test.ts, app/client/src/ce/hooks/index.ts
This PR fixes two issues:
1. When importing older application jsons with applicationVersion 1, they get redirected to `/applications` (older url) as opposed to `/app` (newer slug based url). This results in new query button not showing up on datasource view page, because new query button is hidden behind a condition of editorType and editorType was depending on the new url path. This PR fixes the issue by adding support for older path as well to provide backwards compatibility.
2. Second similar issue was seen intermittently, when we do save and authorise in REST API datasource, then sometimes the redirection was happening to older url (/applications), in that case new query button would not show up. This has been fixed too
Fixes #35626   
_or_  
> [!WARNING]  
> _If no …
=> fix: New query button does not show up issue fixed

app/client/packages/design-system/widgets/src/components/AIChat/src/AIChat.tsx, app/client/packages/design-system/widgets/src/components/AIChat/src/ChatDescriptionModal/ChatDescriptionModal.tsx, app/client/packages/design-system/widgets/src/components/AIChat/src/ChatDescriptionModal/index.ts, app/client/packages/design-system/widgets/src/components/AIChat/src/ChatDescriptionModal/types.ts, app/client/packages/design-system/widgets/src/components/AIChat/src/ChatTitle/styles.module.css, app/client/packages/design-system/widgets/src/components/AIChat/src/ThreadMessage/ThreadMessage.tsx, app/client/packages/design-system/widgets/src/components/AIChat/src/ThreadMessage/styles.module.css, app/client/packages/design-system/widgets/src/components/AIChat/src/styles.module.css, app/client/packages/design-system/widgets/src/components/Modal/src/index.ts, app/client/src/modules/ui-builder/ui/wds/WDSAIChatWidget/widget/index.tsx, app/client/src/widgets/ChartWidget/widget/ChartsRendered.test.tsx, app/client/src/widgets/ChartWidget/widget/index.tsx
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> 14/10 Daily Promotion

app/client/packages/design-system/theming/src/color/src/DarkModeTheme.ts, app/client/packages/design-system/theming/src/color/src/LightModeTheme.ts, app/client/packages/design-system/widgets/src/components/Button/src/styles.module.css, app/client/packages/design-system/widgets/src/components/Button/src/types.ts, app/client/packages/design-system/widgets/src/components/Text/src/types.ts
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/11362114942>
> Commit: e1fc66eb329aa58c08ae6147cc6a5bb1d8107a17
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=11362114942&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Anvil`
> Spec:
> <hr>Wed, 16 Oct 2024 09:07:10 UTC
=> chore: add soft token + add subtle button variant

.coderabbit.yaml
Updated the tone to reflect a professional development environment instead of a teacher in a classroom.
Fixes #`36934`  
> [!WARNING]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/11381087559>
> Commit: d07f1e616cd49f69001cba3f9a10d13fc11a2286
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=11381087559&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: @tag.IDE
> Spec: 
> It seems like **no tests ran** 😔. We are not able to recognize it, please check <a href="https://github.com/appsmithorg/appsmith/actions/runs/11381087559" target="_blank">workflow here</a>.
> <hr>Thu, 17 Oct 2024 08:31:44 UTC
Should the DevRel and Marketing teams inform users about this …
=> chore: Change tone for Coderabbit, a code review bot

.github/workflows/ad-hoc-docker-image.yml
PR to add support for custom pg image during the ad-hoc-builder script. Procedure for the hotfixes from v1.45 is as follows:
1. Create a hotfix branch from the tag where we need the hotfix, `hotfix/<version>` and note down the commit-sha
2. Create hotfix branch `pg-hotfix/<version>` from commit sha on `pg` branch from step 1
3. Cherry-pick commits from release to hotfix branches
4. Build the server locally by running `./build.sh -DskipTests` within server directory to avoid any build failures at later stages on both the hotfix branches
5. If we are seeing any build failure involve `@db-infra` team as required 
6. Run the ad-hoc image builder with `pg-hotfix/<version>` branch to generate `pg` specific tag `pg-vx.y.z`
7. Do the sanity testing with postgres url
8. Only after successful …
=> chore: Add custom tag for pg build in ad-hoc image builder

deploy/docker/fs/opt/appsmith/pg-utils.sh
Use password while creating pg_trm extension on remote postgres. 
_or_  
> [!WARNING]  
> [!CAUTION]  
=> fix: use password while creating extension

app/client/src/pages/common/SearchBar/EntitySearchBar.tsx
Fixes application redirection issue from search bar ~
1. Appends branch to the url
Fixes https://github.com/appsmithorg/appsmith/issues/36782
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/11390479742>
> Commit: 02eb26e4911a4854daeb068f1c80004cec66de96
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=11390479742&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Git`
> Spec:
> <hr>Thu, 17 Oct 2024 18:34:15 UTC
=> fix: adding branch in url for search entities

app/client/cypress/limited-tests.txt, app/client/cypress/support/Pages/DataSources.ts
Airgap test was failing because it was not able to click a particular dropdown.
EE: https://github.com/appsmithorg/appsmith-ee/pull/5412
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/11457437998>
> Commit: 8ca5c3643a4a77bbd71797dc59488ae7897a93b3
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=11457437998&attempt=2" target="_blank">Cypress dashboard</a>.
> Spec:
> <hr>Tue, 22 Oct 2024 10:45:27 UTC
=> test: udpated locator for GenetateCrud test

.github/workflows/test-vulnerabilities-data.yml, app/client/cypress/e2e/Regression/ClientSide/Autocomplete/JS_AC2_spec.ts, app/client/packages/design-system/widgets/src/components/Modal/src/Modal.tsx, app/client/packages/design-system/widgets/src/components/Modal/src/types.ts, app/client/packages/design-system/widgets/src/components/Modal/stories/ModalExamples.tsx, app/client/packages/design-system/widgets/src/testing/ComplexForm.tsx, app/client/src/layoutSystems/anvil/viewer/canvas/styles.module.css, app/client/src/modules/ui-builder/ui/wds/WDSModalWidget/widget/index.tsx, app/client/src/pages/Editor/APIEditor/CommonEditorForm.tsx, app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx, app/client/src/workers/Evaluation/JSObject/index.ts, app/client/src/workers/Evaluation/JSObject/test.ts, app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/constants/ErrorMessages.java, app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/plugins/GoogleSheetsPlugin.java, app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/utils/SheetsUtil.java, app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/SheetsUtilTest.java, scripts/scout_vulnerabilities_data.sh, scripts/trivy_vulnerabilities_data.sh
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> 24/10 Daily Promotion

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/constants/spans/ce/OnLoadSpanCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java
> This PR removes the extra metrics that were added which clouded up the newrelic. 
Old PR https://github.com/appsmithorg/appsmith/pull/37010 is to be closed because extra indentation was added due to the IDE configuration.
Fixes #37051 
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/11493693400>
> Commit: 51ecb28956b5c7fa6b12e18428161614017407ba
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=11493693400&attempt=1" target="_blank">Cypress dashboard</a>.
> Spec:
> <hr>Thu, 24 Oct 2024 06:48:22 UTC
=> chore: removed unwanted metrics

.github/workflows/server-build.yml
We’ve often faced challenges in running server-specific tests efficiently for individual PRs. To streamline this process and improve testing speed, I’ve implemented the workflow dispatch feature, enabling quick and on-demand execution of server tests.
Fixes #`37060`  
> [!WARNING]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/11497895741>
> Commit: 48c3cd9618bc4a4dc61d0ecdb612cc1798f07442
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=11497895741&attempt=6" target="_blank">Cypress dashboard</a>.
> Tags: @tag.IDE
> Spec: 
> It seems like **no tests ran** 😔. We are not able to recognize it, please check <a …
=> chore: Update dispatch option

.github/workflows/server-build.yml, app/client/packages/dsl/src/index.ts, app/client/src/PluginActionEditor/hooks/index.ts, app/client/src/PluginActionEditor/hooks/useHandleDuplicateClick.ts, app/client/src/actions/datasourceActions.ts, app/client/src/actions/pluginActionActions.ts, app/client/src/ce/constants/messages.ts, app/client/src/ce/pages/Editor/AppPluginActionEditor/components/ToolbarMenu/Copy.tsx, app/client/src/ce/sagas/helpers.ts, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/DatasourceDropdown/types.ts, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/DatasourceDropdown/useSource/useConnectToOptions.tsx, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/DatasourceDropdown/useSource/useDatasourceOptions.tsx, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/DatasourceDropdown/useSource/useOtherOptions.tsx, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/index.tsx, app/client/src/components/propertyControls/OneClickBindingControl.tsx, app/client/src/entities/Engine/AppEditorEngine.ts, app/client/src/pages/Editor/Explorer/Actions/ActionEntityContextMenu.test.tsx, app/client/src/pages/Editor/Explorer/Actions/ActionEntityContextMenu.tsx, app/client/src/pages/Editor/Explorer/Actions/MoreActionsMenu.tsx, app/client/src/pages/Editor/JSEditor/Form.tsx, app/client/src/pages/Editor/JSEditor/JSEditorToolbar/JSEditorToolbar.tsx, app/client/src/pages/Editor/JSEditor/JSEditorToolbar/JSHeader.tsx, app/client/src/pages/Editor/JSEditor/JSEditorToolbar/JSObjectNameEditor/JSObjectNameEditor.tsx, app/client/src/pages/Editor/JSEditor/JSEditorToolbar/JSObjectNameEditor/index.tsx, app/client/src/pages/Editor/JSEditor/JSEditorToolbar/JSObjectNameEditor/old/JSObjectNameEditor.tsx, app/client/src/sagas/ActionSagas.ts, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/constants/spans/ce/OnLoadSpanCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> 25/10 Daily Promotion

app/client/cypress/e2e/Regression/ClientSide/Widgets/Datepicker/DatePicker2_spec.js, app/client/cypress/limited-tests.txt, app/client/cypress/support/commands.js
EE PR:https://github.com/appsmithorg/appsmith-ee/pull/5438
Updated SetDate method as the older method was not working anymore
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/11512762742>
> Commit: 1e0ec01036959df5289b6d131f804166a7775e8f
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=11512762742&attempt=2" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.All`
> Spec:
> <hr>Fri, 25 Oct 2024 08:22:21 UTC
=> test: fix datepicker tests

.github/workflows/ci-test-custom-script.yml
disabled ssh sockets which can interfear with ted
_or_  
> [!WARNING]  
> [!CAUTION]  
=> CI: disabled ssh sockets which can interfear with ted

app/client/packages/ast/src/actionCreator/index.ts
I removed ts expect error comments while upgrading the jest lib. This was erroneous, the comments are still needed. No change in functionality, just to suppress ts errors.
> [!CAUTION]  
=> chore: restore removed ts expect error comments

app/server/appsmith-plugins/appsmithAiPlugin/src/main/java/com/external/plugins/AppsmithAiPlugin.java, app/server/appsmith-plugins/appsmithAiPlugin/src/main/java/com/external/plugins/services/AiFeatureService.java, app/server/appsmith-plugins/appsmithAiPlugin/src/main/java/com/external/plugins/services/features/ImageCaptioningServiceImpl.java, app/server/appsmith-plugins/appsmithAiPlugin/src/main/java/com/external/plugins/services/features/ImageClassificationServiceImpl.java, app/server/appsmith-plugins/appsmithAiPlugin/src/main/java/com/external/plugins/services/features/ImageEntityExtractionServiceImpl.java, app/server/appsmith-plugins/appsmithAiPlugin/src/main/java/com/external/plugins/services/features/TextClassificationServiceImpl.java, app/server/appsmith-plugins/appsmithAiPlugin/src/main/java/com/external/plugins/services/features/TextEntityExtractionServiceImpl.java, app/server/appsmith-plugins/appsmithAiPlugin/src/main/java/com/external/plugins/services/features/TextGenerationServiceImpl.java, app/server/appsmith-plugins/appsmithAiPlugin/src/main/java/com/external/plugins/services/features/TextSummarizationServiceImpl.java, app/server/appsmith-plugins/appsmithAiPlugin/src/test/java/com/external/plugins/services/features/ImageCaptioningServiceImplTest.java, app/server/appsmith-plugins/appsmithAiPlugin/src/test/java/com/external/plugins/services/features/ImageClassificationServiceImplTest.java, app/server/appsmith-plugins/appsmithAiPlugin/src/test/java/com/external/plugins/services/features/ImageEntityExtractionServiceImplTest.java, app/server/appsmith-plugins/appsmithAiPlugin/src/test/java/com/external/plugins/services/features/TextClassificationServiceImplTest.java, app/server/appsmith-plugins/appsmithAiPlugin/src/test/java/com/external/plugins/services/features/TextEntityExtractionServiceImplTest.java, app/server/appsmith-plugins/appsmithAiPlugin/src/test/java/com/external/plugins/services/features/TextGenerationServiceImplTest.java, app/server/appsmith-plugins/appsmithAiPlugin/src/test/java/com/external/plugins/services/features/TextSummarizationServiceImplTest.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ActionExecutionSolutionCEImpl.java
> Add executeActionDTO as an additional parameter when executing queries for Appsmith AI Plugin
Fixes https://github.com/appsmithorg/appsmith/issues/37637
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/11949422399>
> Commit: 116c3842f59001837599aab01fb907e1e290cf45
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=11949422399&attempt=1" target="_blank">Cypress dashboard</a>.
> Spec:
> <hr>Thu, 21 Nov 2024 09:04:26 UTC
=> chore: add executeActionDTO as additional parameter to be used when creating query for AppsmithAI plugin queries

.github/workflows/test-vulnerabilities-data.yml
Update name of the workflow for each search and visibility.
Tested on my forked repository:
Fixes # [`Issue Number`  ](https://app.zenhub.com/workspaces/stability-pod-6690c4814e31602e25cab7fd/issues/gh/appsmithorg/appsmith/37695)
> [!CAUTION]  
=> chore: Update for workflow name

.github/workflows/client-build.yml, .github/workflows/server-build.yml
=> ci : fix git lfs migrate

.github/workflows/server-build.yml
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: Reverted server cache skip changes

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/MigrationHelperMethods.java
PR to fix the issue with evicting the cache lines for super users added via env. Migration was getting stuck at `updateSuperUsers` repetitive migration as Mongock was not able to complete the eviction with PermissionGroupRepository which underneath have dependency on mongo driver. 
Fixes https://github.com/appsmithorg/appsmith/issues/37703
/test Sanity
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/12054789155>
> Commit: fccb1b34f5df87dc06f06ecfba31491b1f805093
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=12054789155&attempt=1" target="_blank">Cypress dashboard</a>.
> Spec:
> <hr>Wed, 27 Nov 2024 17:23:12 UTC …
=> fix: Super user cache eviction when user is added via env variable

app/client/start-https.sh
> [!WARNING]
> Tests have not run on the HEAD 0ce2dfa92e53dfbe93b02c29e75699dfcc77a10f yet
> <hr>Fri, 29 Nov 2024 10:20:32 UTC
=> chore: Always get version from $backend

app/client/start-https.sh
=> chore: Find version after backend is ready

.github/workflows/ad-hoc-docker-image.yml, scripts/generate_info_json.sh
PR to add version field in generate info json script. This will be used to override the version coming from the GH so that hotfixed tags should refelect the correct version instead of some random commit sha.
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: Add version input for generate info json script

app/client/cypress/e2e/Regression/ClientSide/OtherUIFeatures/EntityBottomBar_spec.ts, app/client/cypress/limited-tests.txt
Query result set had changed we updated the query accordingly
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/12196327858>
> Commit: 29660e7ae6853069d7c39aa8aaf6a0c07a572ba6
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=12196327858&attempt=1" target="_blank">Cypress dashboard</a>.
> Spec:
> <hr>Fri, 06 Dec 2024 10:08:47 UTC
=> test: fixed failing EntityBottomBar spec

.github/workflows/client-build.yml
fix client build cache
_or_  
> [!WARNING]  
> [!CAUTION]  
=> ci: fix client build cache

app/client/src/pages/Editor/AppPluginActionEditor/components/ToolbarMenu/Move.tsx
Fixes an issue where move between pages in query context menu was not possible.
Fixes [#38117](https://github.com/appsmithorg/appsmith/issues/38117)
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/12468165994>
> Commit: 1ef7d576fc5d8c9261279cdc77c69c9688826262
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=12468165994&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.IDE`
> Spec:
> <hr>Mon, 23 Dec 2024 14:47:50 UTC
=> fix: cannot see move to page option when there are exactly two pages in the app 

app/client/cypress/e2e/Regression/ServerSide/OnLoadTests/OnLoadActions_Spec.ts, app/client/cypress/limited-tests.txt
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/12592022906>
> Commit: 92ca095e01d4ec7c2ffd3382129df66e7c6dce6d
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=12592022906&attempt=1" target="_blank">Cypress dashboard</a>.
> Spec:
> <hr>Fri, 03 Jan 2025 03:37:24 UTC
=> test: flaky check for onload spec

app/client/cypress/e2e/Regression/ClientSide/PublishedApps/PublishedModeToastToggle_Spec.ts, app/client/cypress/limited-tests.txt
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/12592573790>
> Commit: a174b8a1167c5da3851af49999956edd0e9ff251
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=12592573790&attempt=2" target="_blank">Cypress dashboard</a>.
> Spec:
> <hr>Fri, 03 Jan 2025 06:17:34 UTC
=> test: flaky check for published Spec

app/client/packages/design-system/ads/src/List/List.tsx
Resolving merge conflict
_or_  
> [!WARNING]  
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/12666175355>
> Commit: 639f92ac62fb0c633099c4ecfdfef514288a3561
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=12666175355&attempt=1" target="_blank">Cypress dashboard</a>.
> Spec:
> <hr>Wed, 08 Jan 2025 08:25:59 UTC
=> fix: Resolving merge conflict

app/client/packages/design-system/ads/src/List/List.stories.tsx, app/client/packages/design-system/ads/src/List/List.styles.tsx, app/client/packages/design-system/ads/src/List/List.tsx, app/client/packages/design-system/ads/src/List/List.types.tsx, app/client/packages/design-system/ads/src/Templates/EntityExplorer/Editable/index.ts, app/client/packages/design-system/ads/src/Templates/EntityExplorer/Editable/useEditableText.test.tsx, app/client/packages/design-system/ads/src/Templates/EntityExplorer/Editable/useEditableText.ts, app/client/packages/design-system/ads/src/Templates/EntityExplorer/Editable/utils.ts, app/client/packages/design-system/ads/src/Templates/EntityExplorer/EntityItem/EntityItem.stories.tsx, app/client/packages/design-system/ads/src/Templates/EntityExplorer/EntityItem/EntityItem.styles.ts, app/client/packages/design-system/ads/src/Templates/EntityExplorer/EntityItem/EntityItem.tsx, app/client/packages/design-system/ads/src/Templates/EntityExplorer/EntityItem/EntityItem.types.ts, app/client/packages/design-system/ads/src/Templates/EntityExplorer/EntityItem/index.ts, app/client/packages/design-system/ads/src/Templates/EntityExplorer/index.ts, app/client/src/IDE/Components/EditableName/EditableName.test.tsx, app/client/src/IDE/Components/EditableName/EditableName.tsx, app/client/src/IDE/Components/EditableName/useValidateEntityName.ts, app/client/src/pages/Editor/IDE/EditorTabs/EditableTab.tsx, app/client/src/pages/Editor/IDE/LeftPane/DataSidePane.test.tsx, app/client/src/pages/Editor/IDE/LeftPane/DataSidePane.tsx
Cherry-picking ADS entity item changes to master to resolve conflicts in the List component in ADS
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/12667094860>
> Commit: 1c4b237f998e90b26f1098ff6786718e5a98c030
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=12667094860&attempt=1" target="_blank">Cypress dashboard</a>.
> Spec:
> <hr>Wed, 08 Jan 2025 09:32:55 UTC
=> feat: ADS Entity Item (#38442)

app/client/packages/design-system/ads/src/List/List.tsx, app/client/packages/design-system/ads/src/List/List.types.tsx, app/client/packages/design-system/ads/src/Templates/EntityExplorer/Editable/useEditableText.test.tsx, app/client/packages/design-system/ads/src/Templates/EntityExplorer/Editable/useEditableText.ts, app/client/packages/design-system/ads/src/Templates/EntityExplorer/EntityItem/EntityItem.stories.tsx, app/client/packages/design-system/ads/src/Templates/EntityExplorer/EntityItem/EntityItem.tsx, app/client/packages/design-system/ads/src/Templates/EntityExplorer/EntityItem/EntityItem.types.ts
Reverts appsmithorg/appsmith#38524
=> Revert "chore: Housekeeping of List Item and Entity Item"

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/TenantServiceCEImpl.java
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: Adding stack trace for errors in fetching tenant from redis to debug the root cause

app/client/src/entities/Engine/AppEditorEngine.ts, app/client/src/entities/Engine/index.ts
Context - https://theappsmith.slack.com/archives/C0134BAVDB4/p1740027639910039?thread_ts=1739904050.960349&cid=C0134BAVDB4
The app store wasn't getting hydrated from local storage in view mode because of the changes in the PR  https://github.com/appsmithorg/appsmith/pull/39255
_or_  
> [!WARNING]  
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/13429852595>
> Commit: d9c5c62e4cb99be7c96adbb0e483a4b7d0882758
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=1342985259 …
=> chore: Fix appsmith store hydration from localstorage in view mode

app/client/src/ce/pages/AppViewer/KnowledgeBase/KBViewerFloatingButton.tsx, app/client/src/ee/pages/AppViewer/KnowledgeBase/KBViewerFloatingButton.tsx, app/client/src/pages/AppViewer/index.tsx, app/client/src/utils/storage.ts, app/server/appsmith-git/src/main/java/com/appsmith/git/files/FileUtilsCEImpl.java, app/server/appsmith-git/src/main/java/com/appsmith/git/files/FileUtilsImpl.java, app/server/appsmith-git/src/test/java/com/appsmith/git/helpers/FileUtilsImplTest.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ce/ApplicationCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/git/fs/GitFSServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/CommonGitFileUtilsCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/jslibs/exportable/CustomJSLibExportableServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration065_CopyTenantIdToOrganizationId.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration066_CacheBustTenantOrgMigration.java, app/server/appsmith-server/src/test/java/com/appsmith/server/git/resourcemap/ExchangeJsonConversionTests.java
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> 21/02 2nd Daily Promotion

app/client/packages/design-system/widgets/src/components/TextArea/src/TextArea.tsx
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/13654597103>
> Commit: 1a55cb73b5afa9d96db1e2b0d3d4556828b40ac6
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=13654597103&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Anvil`
> Spec:
> <hr>Tue, 04 Mar 2025 13:41:18 UTC
=> chore: use margin instead of padding in WDS textarea

app/client/src/pages/Editor/CustomWidgetBuilder/Editor/Header/CodeTemplates/Templates/anvilTemplates/react.ts, app/client/src/pages/Editor/CustomWidgetBuilder/Editor/Header/CodeTemplates/Templates/react.ts, app/client/src/widgets/CustomWidget/widget/defaultApp.ts
Fixes #39584
This was an unnecessary third-party dependency in our code. While we will not prevent anyone from using it in their applications, it is not required in the default templates. Therefore, we are removing it. For further information, please refer to this [conversation](https://theappsmith.slack.com/archives/CGBPVEJ5C/p1742841918575179?thread_ts=1742812032.686439&cid=CGBPVEJ5C).
Fixes #39584
_or_  
> [!WARNING]  
/ok-to-test tags="@tag.Sanity, @tag.Widget, @tag.Anvil"
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/14053696768>
> Commit: db2573d7cc5662e919ad327a768e351447a70899
> …
=> chore: Remove 3rd party dependencies from Custom widget

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/RunBehaviorEnum.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ce/ActionCE_DTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/ActionControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutActionServiceTest.java
Migrating executeOnLoad to runBehavior enum
_or_  
> [!WARNING]  
> [!CAUTION]  
=> feat: Migrate executeOnLoad to runBehavior enum

app/client/src/PluginActionEditor/constants/PluginActionConstants.ts, app/client/src/PluginActionEditor/transformers/RestActionTransformers.test.ts, app/client/src/ce/constants/messages.ts, app/client/src/components/editorComponents/PartialImportExport/PartialExportModal/unitTestUtils.ts, app/client/src/components/formControls/DropDownControl.tsx, app/client/src/constants/AppsmithActionConstants/formConfig/ApiSettingsConfig.ts, app/client/src/constants/AppsmithActionConstants/formConfig/GoogleSheetsSettingsConfig.ts, app/client/src/constants/AppsmithActionConstants/formConfig/QuerySettingsConfig.ts, app/client/src/entities/Action/index.ts, app/client/src/pages/Editor/JSEditor/JSEditorToolbar/components/JSFunctionSettings.tsx, app/client/src/pages/Editor/JSEditor/JSEditorToolbar/types.ts, app/client/src/pages/Editor/SaaSEditor/__data__/FinalState.json, app/client/src/pages/Editor/SaaSEditor/__data__/InitialState.json, app/client/test/factories/MockPluginsState.ts, app/server/appsmith-plugins/amazons3Plugin/src/main/resources/setting.json, app/server/appsmith-plugins/anthropicPlugin/src/main/resources/setting.json, app/server/appsmith-plugins/appsmithAiPlugin/src/main/resources/setting.json, app/server/appsmith-plugins/firestorePlugin/src/main/resources/setting.json, app/server/appsmith-plugins/googleAiPlugin/src/main/resources/setting.json, app/server/appsmith-plugins/googleSheetsPlugin/src/main/resources/setting.json, app/server/appsmith-plugins/mongoPlugin/src/main/resources/setting.json, app/server/appsmith-plugins/mssqlPlugin/src/main/resources/setting.json, app/server/appsmith-plugins/mysqlPlugin/src/main/resources/setting.json, app/server/appsmith-plugins/openAiPlugin/src/main/resources/setting.json, app/server/appsmith-plugins/oraclePlugin/src/main/resources/setting.json, app/server/appsmith-plugins/postgresPlugin/src/main/resources/setting.json
Replacing `executeOnLoad` with `runBehavior` in all action config settings
Figma: https://www.figma.com/design/qFXimqMSH45aviBOdTfDXu/Reactive-Queries-JS?node-id=61-16773&t=rv594VlMSm75Bvcb-0
Fixes [#39831](https://github.com/appsmithorg/appsmith/issues/39831)
> [!CAUTION]  
=> feat: Replacing `executeOnLoad` with `runBehavior` in all action config settings

app/client/src/actions/pluginActionActions.ts, app/client/src/api/PageApi.tsx, app/client/src/ce/reducers/entityReducers/actionsReducer.tsx, app/client/src/ce/reducers/entityReducers/jsActionsReducer.tsx, app/client/src/pages/Editor/JSEditor/JSEditorToolbar/types.ts
Update type for run behavior for some instances
Fixes #
> [!CAUTION]  
=> chore: Update type for run behavior for some instances

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/enums/FeatureFlagEnum.java, app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/ExecutionMethod.java, app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/FileListMethod.java, app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/plugins/GoogleSheetsPlugin.java
Removed usage of flag release_google_sheets_shared_drive_support_enabled as this feature is enabled for all.
Fixes #40618  
_or_  
> [!WARNING]  
/ok-to-test tags="@tag.Datasource, @tag.Sanity"
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/14911706942>
> Commit: b2fdf94d752d1b5ed12daee862cf1475a19559d2
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=14911706942&attempt=2" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Datasource, @tag.Sanity`
> Spec:
> <hr>Thu, 08 May 2025 19:03:27 UTC …
=> fix: removed usage of gs shared drive flag

app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ce/NewActionCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCEImpl.java
This PR provides backward compatibility for older actions which do not have runBehaviour property in the DB. When such actions have been configured to be run on page load explicitly, they will get executed as other actions which get set to be run on page load when binding happens.
- Create app on production ([app.appsmith.com](http://app.appsmith.com/))
- Create mock db users datasource
- Create 3 queries, Q1, Q2 and Q3
- Attach Q1 to table so it runs on page load
- Change executeOnLoad setting of Q3 to page load
- Export this app
- Import this on our DP
- Observe that Q3 does not run on page load
Fixes #40633   
_or_  
> [!WARNING]  
/ok-to-test …
=> feat: execute on load backwards compatibility backend changes

app/client/src/utils/Analytics/mixpanel.ts
Cherry Picking this into Master - https://github.com/appsmithorg/appsmith/pull/40717
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/15162814431>
> Commit: b6c3243b013f42aa4888b5b94a3c5310714fd119
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=15162814431&attempt=1" target="_blank">Cypress dashboard</a>.
> Spec:
> <hr>Wed, 21 May 2025 13:41:25 UTC
=> fix: mixpanel start stop recording check

app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCEImpl.java
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> 30/05 Daily Promotion

app/client/cypress/e2e/Regression/ClientSide/Widgets/Input/Inputv2_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/ListV2/Listv2_BasicClientSideData_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/ListV2/Listv2_Nested_EventBindings_spec.js, app/client/cypress/support/Pages/AggregateHelper.ts, app/client/src/constants/WidgetConstants.tsx, app/client/src/git/sagas/fetchStatusSaga.ts, app/client/src/git/sagas/initGitSaga.ts, app/client/src/git/sagas/triggerAutocommitSaga.ts, app/client/src/git/store/actions/fetchStatusActions.ts, app/client/src/git/store/gitArtifactSlice.ts, app/client/src/pages/Editor/PropertyPane/index.tsx, app/client/src/utils/Analytics/mixpanel.ts, app/client/src/utils/editor/EditorUtils.ts, app/client/src/widgets/CurrencyInputWidget/widget/index.tsx, app/client/src/widgets/InputWidget/widget/index.tsx, app/client/src/widgets/InputWidgetV2/widget/index.tsx, app/client/src/widgets/PhoneInputWidget/widget/index.tsx, app/client/src/widgets/RichTextEditorWidget/widget/index.tsx, app/client/src/widgets/wds/WDSCurrencyInputWidget/widget/index.tsx, app/client/src/widgets/wds/WDSInputWidget/widget/index.tsx, app/client/src/widgets/wds/WDSPhoneInputWidget/widget/index.tsx, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/SessionUserServiceCEImpl.java
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> 06/06 Daily Promotion

app/client/src/ce/utils/signupHelpers.ts
Added `isMultiOrgEnabled` property to the `RedirectUserAfterSignupProps` interface to support multi-organization functionality in the signup redirect flow.
- Added optional `isMultiOrgEnabled?: boolean` property to `RedirectUserAfterSignupProps` interface in `app/client/src/ce/utils/signupHelpers.ts`
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/16159330322>
> Commit: f3e264df4248cfdd3d4b8e766ecbdef0f11b4c78
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=16159330322&attempt=1" target="_blank">Cypress dashboard</a>.
> Spec:
> <hr>Wed, 09 Jul 2025 03:53:42 UTC …
=> feat: add multi-org support to signup redirect helpers

app/client/cypress/support/Pages/GitSync.ts, app/client/src/ce/utils/signupHelpers.ts, app/client/src/pages/setup/SignupSuccess.tsx
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> 11/07 Daily Promotion

app/client/src/pages/Editor/AppsmithLink.tsx
…1135)
Updating the logo in App editor to use branding logo instead.
Fixes [#41134](https://github.com/appsmithorg/appsmith/issues/41134)
> [!CAUTION]  
> If you modify the content in this section, you are likely to disrupt
the CI result for your PR.
> [!TIP]  
>
_or_  
> [!WARNING]  
> _If no issue exists, please create …
=> 28/07 Daily Promotion

.github/workflows/ad-hoc-docker-image.yml
Remove unused argument from generate_info_json.sh script call
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> fix: update info generation step in ad-hoc image
