appsmithorg/appsmith

app/client/cypress/e2e/Regression_TestSuite/ClientSideTests/ExplorerTests/Entity_Explorer_Pin_spec.js, app/client/cypress/e2e/Regression_TestSuite/ClientSideTests/Widgets/Others/Autocomplete_spec.js
=> fix: airgap tests

app/client/cypress/e2e/Regression_TestSuite/ClientSideTests/Binding/Bind_tableApi_spec.js, app/client/cypress/e2e/Regression_TestSuite/ClientSideTests/Binding/Bind_tableV2Api_spec.js
fixes Bind_tableApi_spec.js and Bind_tableV2Api_spec.js
=> fix: Table API Spec

app/client/cypress/e2e/Regression_TestSuite/ClientSideTests/BugTests/Moment_Spec.ts
=> test: Cypress - Moment_spec.ts flaky fix

app/client/cypress/e2e/Regression_TestSuite/ClientSideTests/Git/GitSync/SwitchBranches_spec.js, app/client/cypress/e2e/Regression_TestSuite/ClientSideTests/Templates/ForkTemplateToGitConnectedApp.js
fix failing SwitchBranch_spec test
=> test: fix SwichBrances_Spec test

app/client/cypress/e2e/Regression_TestSuite/ServerSideTests/ApiTests/API_Edit_spec.js
Skip API_Edit_spec.js test failing due to bug
=> test: skip API_Edit_spec.js

app/client/cypress/e2e/Regression_TestSuite/ClientSideTests/Binding/Bind_tableApi_spec.js, app/client/cypress/e2e/Regression_TestSuite/ClientSideTests/Binding/Bind_tableV2Api_spec.js
- Fixed Binding/Bind_tableV2Api_spec.js & Binding/Bind_tableApi_spec.js
=> test: Cypress - Bind_TableApi_Specs Fix

app/client/cypress/e2e/Regression_TestSuite/ClientSideTests/Git/GitSync/SwitchBranches_spec.js
Fixes flaky test SwitchBranch_spec.js
=> test: fix flaky SwitchBranch_spec.js

app/client/cypress/e2e/Regression_TestSuite/ClientSideTests/OtherUIFeatures/Omnibar_spec.js
=> fix: adding a fix for omnibar spec failing on airgap

.github/workflows/ci-test.yml
Reverts appsmithorg/appsmith#23553
=> Revert "ci: Fix for cypress rerun cache issue"

app/client/cypress/locators/Widgets.json, app/client/cypress/support/WorkspaceCommands.js, app/client/cypress/support/commands.js, app/client/src/pages/Applications/ApplicationCard.tsx
Updating locators for EE tests
>
>
>
>
>
>
>
>
> Delete …
=> chore: Updating locators for EE tests

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/plugins/PluginExecutor.java, app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/plugins/GoogleSheetsPlugin.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/DatasourceControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/DatasourceStructureSolutionImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java
This PR removes an unused endpoint to reduce the scope of changes for multiple environments
No testing required for this change, regression would cover testing for this.
=> chore: Remove unused datasource query endpoint

app/client/cypress/e2e/Regression_TestSuite/ClientSideTests/Widgets/Audio/audio_spec.js, app/client/cypress/e2e/Regression_TestSuite/ServerSideTests/QueryPane/Postgres_Spec.js
Fixes #
- QueryPane/Postgres_Spec.js - fix for EE run failures
=> test: Cypress fix for QueryPane/Postgres_Spec.js

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java
- Added events for Data source schema fetch failure.
Fixes #23131 
=> chore: analytics event for schema fetch failure

app/client/cypress/e2e/Regression/ClientSide/Git/GitSync/SwitchBranches_spec.js
Fixes flaky test SwitchBranch_spec.js
Locally
=> test: fix SwitchBranch_Spec flaky test

app/client/src/ce/workers/Evaluation/Actions.ts, app/client/src/entities/DataTree/dataTreeFactory.ts, app/client/src/entities/DataTree/types.ts, app/client/src/workers/Evaluation/setters.ts
=> feat: Add validation for setter method

.github/reviewers.yml
Added workflow to add DS pod team members as default reviewers.
>
>
>
>
>
>
>
=> fix: Added DS pod as reviewer for all PR that changes client

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ActionExecutionSolutionCEImpl.java
Added small fix for failing CI
=> added true environment call before validation of environmentIds  in datasourceStroageService

app/server/appsmith-server/src/test/java/com/appsmith/server/services/WorkspaceServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ce/ActionExecutionSolutionCETest.java
=> chore: Fixed blocking test in ws

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/MockDataServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ActionExecutionSolutionCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ce/ActionExecutionSolutionCEImplTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ce/ActionExecutionSolutionCETest.java
Fixing the way we consume some methods to avoid txn conflicts on EE
=> chore: Fixing CI post ME merge

app/client/cypress/e2e/Regression/ClientSide/ActionExecution/ActionSelector_JsToNonJSMode_spec.ts, app/client/cypress/support/Objects/CommonLocators.ts, app/client/cypress/support/Pages/PropertyPane.ts, app/client/src/components/editorComponents/ActionCreator/viewComponents/ActionSelectorView/index.tsx
This fixes an issue where the action selector value was not showing up in the popup for integration options. This issue was introduced in release by [this PR](https://github.com/appsmithorg/appsmith/pull/23242).
Before|After
--|--
>
>
>
>
>
>
>
>
=> fix: action selector popup value for integrations

app/client/src/workers/Evaluation/setters.ts
- Pass the `props` in validate function 
- Throw error when value is sent as `undefined` in setter
>
>
>
=> fix: validation error

app/client/src/components/editorComponents/Debugger/ErrorLogs/components/LogCollapseData.tsx
Error having no spaces and a long string was rendering the error in such a way that the width of the pane was increasing and the right api pane was being pushed out of the screen.
>
>
>
>
- This change requires a documentation …
=> fix: log item error expanding the api editor width 

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration012TransferToDatasourceStorage.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/solutions/DatasourceStorageMigrationSolution.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/solutions/ce/DatasourceStorageMigrationSolutionCE.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ce/ActionExecutionSolutionCEImplTest.java
This PR is a skeleton for DS migration to storage
=> chore: Datasource configuration migration to storage scaffold

app/client/src/components/editorComponents/CodeEditor/index.tsx, app/client/src/components/editorComponents/form/fields/DynamicTextField.tsx
> Adds AI powered SQL generation for postgres queries
>
>
>
>
>
>
>
>
>
>
=> chore: changes to support AI in SQL editors

app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Application.java, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/ApplicationPagesDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewPageServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewPageServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/NewPageServiceTest.java
This PR embeds the snapshot time with the response to get pages API so that client does not need to trigger another API. It'll also help to get rid of the 404 error for get snapshot API which floods our logs.
Fixes #23701
>
>
>
>
>
>
>
>
=> chore: Return snapshot date with application and details API

app/client/src/ce/pages/workspace/WorkspaceInviteUsersForm.tsx, app/client/src/ce/sagas/userSagas.tsx
We are updating the UI for the Invite modal in an error state.
Fixes 
1. [#23773](https://github.com/appsmithorg/appsmith/issues/23773) 
2. https://www.notion.so/appsmith/Select-list-is-not-scrollable-on-Share-modal-f7fd270375cb4a9b8571f1a016d7ed82?pvs=4 
>
>
>
=> chore: Invite modal UI in error state

app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/ApplicationTemplate.java
Add new fields pertaining to template metadata
Fixes https://github.com/appsmithorg/appsmith/issues/23416
>
>
>
>
>
=> feat: add template metadata fields

app/client/src/workers/Evaluation/setters.ts, app/client/src/workers/Evaluation/validations.ts
=> feat: Add strict boolean validation check

app/client/src/components/editorComponents/GlobalSearch/SearchModal.tsx
This PR fixes https://www.notion.so/appsmith/Snippets-overlay-renders-blurred-text-0cdc147a619a430cbcfd113879a5f712
>
>
>
>
>
>
>
> …
=> Fix: Snippets overlay renders blurred text

app/client/src/ce/pages/Applications/EmbedSnippetTab.tsx
Updating the to function in embed snippet tab component
>
=> fix: Updating the to function in embed snippet tab component

app/client/cypress/e2e/Regression/ClientSide/ActionExecution/PostWindowMessage_spec.ts
- This PR fixes the PostWindowMessage_spec flaky fix in CI runs
=> test: Cypress | Fix PostWindowMessage_spec

app/client/src/ce/constants/messages.ts, app/client/src/ce/pages/AdminSettings/config/authentication/index.tsx, app/client/src/pages/common/AvatarComponent.tsx
Updating UI on admin settings page for better UX
Fixes [#23835](https://github.com/appsmithorg/appsmith/issues/23835)
>
=> chore: Updating UI on admin settings page for better UX

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration012TransferToDatasourceStorage.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration109TransferToDatasourceStorage.java
This PR just uncomments the migration annotation in order to make this migration effective, This annotation was commented to implement the EE override before execution of this migration file.
Note: This PR needs to be merged only when we have placed a merge freeze 
This should be merged before the merge of PR: https://github.com/appsmithorg/appsmith-ee/pull/1533
=> chore: name refactor and enabling migration 012 by adding changeunit annotation

app/client/cypress/e2e/Regression/ClientSide/Autocomplete/Autocomplete_setters_spec.ts, app/client/src/utils/FilterInternalProperties/Widget.ts, app/client/src/widgets/MultiSelectWidgetV2/index.ts, app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx
Fixes #23650 
>
>
>
>
>
>
>
>
>
>
>
=> Test: Added tests for autocomplete for widget property setters

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationSnapshotServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/ApplicationSnapshotServiceUnitTest.java
>
>
This PR fixes an issue that's triggered due to merge conflicts. We accidentally removed the code from the restore snapshot service that replaces the actual ids with default ids when application is connected to git.
Fixes #22956
>
>
>
>
>
>
>
>
=> fix: Return default application and page id in the restore snapshot response

.github/workflows/ci-test.yml
Added dummy intercom key in env for CI runs.
This will enable intercom option in the UI only for CI and thus cypress test cases can be written around it.
>
>
>
>
>
>
>
>
> Please …
=> feat: dummy intercom key for CI workflow

app/client/public/404.html
To gather more information about chunk load errors (#22905) we are adding some tracking info in the error page
=> feat: Add sentry and smartlook tracking on 404 page

app/client/src/sagas/DatasourcesSagas.ts
When update datasource draft saga is called for Rest APIs, an incorrect redux form name is used, hence the error.
Fixes #23686
Fixes #23681 
>
>
>
>
>
>
>
=> fix: Fix update datasource draft logic

app/client/cypress/support/Pages/Table.ts, app/client/src/components/propertyControls/DraggableListCard.tsx, app/client/src/components/propertyControls/PrimaryColumnsControl.tsx, app/client/src/components/propertyControls/PrimaryColumnsControlV2.tsx
Fixes https://github.com/appsmithorg/appsmith/issues/23910
1. Fixes `Column Title` to `Column title` in table widget column name
2. Fixes border color when tab title or column title are same.
>
>
>
>
>
>
>
> …
=> fix: text overflow issue in tab & table widget

app/client/cypress/e2e/Regression/Apps/MongoDBShoppingCart_spec.js, app/client/cypress/e2e/Regression/ClientSide/OtherUIFeatures/ErrorMessages_spec.ts, app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_CurlPOSTImport_spec.js
**Skipped below flaky tests to unblock CI**
- MongoDBShoppingCart_spec.js
- ErrorMessages_spec.ts
- API_CurlPOSTImport_spec.js
=> test: Cypress - Skipping tests to unblock CI

app/client/cypress/e2e/Regression/ClientSide/OtherUIFeatures/ErrorMessages_spec.ts
Fixes flakiness in Error messages spec file
N/A
N/A
=> fix: error messages spec and remove flakiness

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitFileUtils.java
Reverting the PR - https://github.com/appsmithorg/appsmith/commit/58fb03e18a31348a78ad307180a34e6a91a47c2c
=> chore: revert Exclude published mode resources for customJSLibs

app/client/public/index.html, app/client/src/Globals.d.ts, app/client/src/index.tsx
Make some necessary non function changes here to reduce conflicts with EE.
=> chore: CDN related changes

app/client/cypress/e2e/Regression/ClientSide/OtherUIFeatures/ForkApplication_spec.js, app/client/src/pages/Editor/gitSync/ReconnectDatasourceModal.tsx
Fixes the failing flaky cypress test for ForkModal that was triggering reconnect modal.  The spec was calling skip to application but the link created was wrong which created this flakiness. The reconnect modal also has a fix for listing datasources with all the values which are not present in the unconfigured datasources list.
>
>
>
> …
=> fix: fork application spec & reconnect modal fix

app/client/package.json, app/client/yarn.lock
=> chore: bump appsmith-design-system

app/client/generators/widget/templates/index.js.hbs, app/client/src/widgets/AudioWidget/index.tsx, app/client/src/widgets/BaseInputWidget/index.ts, app/client/src/widgets/CanvasWidget.tsx, app/client/src/widgets/DatePickerWidget/index.ts, app/client/src/widgets/DividerWidget/index.ts, app/client/src/widgets/FilepickerWidget/index.ts, app/client/src/widgets/IconWidget/index.ts, app/client/src/widgets/ListWidgetV2/MetaWidgetGenerator.test.ts, app/client/src/widgets/QRGeneratorWidget/index.ts, app/client/src/widgets/SkeletonWidget.tsx, app/client/src/widgets/TabsMigrator/index.ts
There were some autocomplete definitions declaration I missed last time I refactored the code. Adding them now.
=> chore: Add missing autocomplete definition declarations

app/client/src/pages/setup/SetupForm.tsx
>  add additional checks for super user form not not be submitted more than once
Fixes #23938 
>
>
>
>
>
>
>
>
>
>
>
>
=> fix: add additional checks for super user form not not be submitted more than once

app/client/cypress/e2e/Regression/Apps/MongoDBShoppingCart_spec.js, app/client/cypress/e2e/Regression/ServerSide/OnLoadTests/JSOnLoad2_Spec.ts
- MongoDBShoppingCart_spec.js
- JSOnLoad2_Spec.ts
=> test: Cypress - Flaky fixes

app/client/cypress/support/Pages/AggregateHelper.ts
- This PR fixes the flaky network validation for MySQL1_Spec.ts that is failing in CI runs
>
=> test: Cypress | Flaky fix MySQL1_Spec.ts 

app/client/cypress/e2e/Regression/Apps/MongoDBShoppingCart_spec.js, app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/PropertyControl_spec.ts, app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/TableWidget/mongoDB_spec.ts, app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/TableWidget/postgres_spec.ts
- This PR skips the identified flaky tests in CI until they are fixed
- OneClickBinding/PropertyControl_spec.ts
- OneClickBinding/postgres_spec.ts
- OneClickBinding/mongoDB_spec.ts
- Apps/MongoDBShoppingCart_spec.ts
=> test: Cypress | Skipping tests to unblock CI

contributions/docs/TestAutomation.md
> Updated CLI args in TestAutomation.md to run cypress locally
>
Fixes #23798
>
>
>
>
>
>
>
>
> Add Testsmith test cases links …
=> fix: CLI args to run cypress locally in run mode does not work from TestAutomation.md

contributions/ClientSetup.md
Fix documentation for client setup
=> chore: Fix client setup documentation: Add steps for running backend server from docker + run jest tests locally + fix overall structure

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceTriggerSolutionCEImpl.java
> TL;DR:  When environmentId header is absent from client side, ensuring it finds the default environmentId to proceed
Fixes #23840
=> fix: added fallback handling of environmentId header absent in trigger call

app/client/cypress/e2e/Regression/Apps/PromisesApp_spec.js
- This PR gives a trial fix for Apps/PromisesApp_spec.js which is failing in CI
=> test: Cypress | Flaky fix for Apps/PromisesApp_spec.js

app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
Fixes https://github.com/appsmithorg/appsmith/issues/23417
>
>
>
>
>
=> feat: Add support for yaml extension for the git connect flow validation

.github/workflows/ci-test.yml, app/client/cypress/e2e/Regression/ClientSide/OtherUIFeatures/ForkApplication_spec.js, app/client/cypress/e2e/Sanity/Datasources/Airtable_Basic_Spec.ts, app/client/cypress/support/Pages/DataSources.ts, app/client/src/pages/Editor/gitSync/ReconnectDatasourceModal.tsx
> TL;DR Fixes CI for master from PRs
- #23885 
- #23959 
- #23946 
These Pr are cherry picked from release
=> fix: ci failures fixes

app/client/cypress/e2e/Regression/ClientSide/Autocomplete/Autocomplete_JS_spec.ts, app/client/cypress/e2e/Regression/ClientSide/Widgets/Modal/Modal_focus_spec.js, deploy/docker/entrypoint.sh
>
>
>
>
>
>
>
>
- Breaking change (fix or feature that would cause …
=> chore: Merge conflict resolution with master

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration109TransferToDatasourceStorage.java
Contains a migration to move configurations to a new collection
=> ci: Migrating datasource configuration to storage

app/client/packages/rts/start-server.sh
> RTS build is failing because start-server.sh is looking for `server.js` in` dist/rts/`, but `server.js` is located in `dist/`
Fixes #24168 
>
>
>
>
>
>
>
>
>
>
>
>
>
>
=> chore: fix RTS start failure script

app/client/src/ce/api/ApiUtils.ts
=> chore: Add two more sentry logs when REQUEST_NOT_AUTHORISED and PAGE_NOT_FOUND alongwith rejecting respective promises with the whole error object

app/client/cypress/e2e/Regression/Apps/ImportExportForkApplication_spec.js, app/client/cypress/fixtures/forkedApp.json, app/client/cypress/support/Pages/AggregateHelper.ts, app/client/cypress/support/Pages/DataSources.ts
- This PR fixes the flaky spec - ImportExportForkApplication_spec in CI runs
- Script fix
=> test: Cypress | Flaky fix

app/client/cypress/e2e/Regression/Apps/ImportExportForkApplication_spec.js, app/client/cypress/e2e/Regression/ClientSide/Templates/TemplatesPage_spec.ts
This spec should not run in airgapped config.
>
>
>
>
>
>
>
>
>
>
>
>
=> fix: Adds airgap support for templates page spec

deploy/docker/entrypoint.sh
Cherry pick https://github.com/appsmithorg/appsmith/pull/24199.
=> cherry-pick: IPv6 error when starting container

Dockerfile, deploy/docker/entrypoint.sh
Fixes: [23522](https://github.com/appsmithorg/appsmith/issues/23522)
=> chore: update entrypoint to deploy appsmith on cloudrun

app/client/cypress/e2e/Regression/Apps/ImportExportForkApplication_spec.js
=> fix: Adds linting to ImportexportforkApplicationSpec

app/client/src/utils/autocomplete/dataTreeTypeDefCreator.ts, app/client/src/widgets/ButtonWidget/widget/index.tsx, app/client/src/widgets/CurrencyInputWidget/index.ts, app/client/src/widgets/CurrencyInputWidget/widget/index.tsx, app/client/src/widgets/ListWidgetV2/index.ts, app/client/src/widgets/ListWidgetV2/widget/index.tsx, app/client/src/widgets/SwitchWidget/widget/index.tsx
- Added setterConfig to CurrencyInputWidget
Enhanced the CurrencyInputWidget by introducing a setterConfig for better customization.
- Added setterConfig to List Widget V2
- Added support for `.then` and `.catch` autocomplete for setter methods
>
>
>
>
>
=> fix: issues raised for widget property setter

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java
After upgrade to v1.9.21, google sheets datasource would lose authentication after every couple of hours, causing all queries to fail. This PR fixes that issue. 
The issue started occurring after v1.9.21 because of the changes made as a part of multiple environments. Once the access token expires, we make an API call to google to refresh the access token. This API call does not return refresh token and hence we were setting refresh token as null. On subsequent refresh calls, this refresh token would be passed as null, hence causing failure in refresh. 
Fixes #24236 
>
>
>
>
- …
=> fix: gsheet continuous re authorisation required issue fixed

app/client/cypress/support/Pages/AggregateHelper.ts
=> ci: Fixing the default value syntax for update input parameter

app/client/src/ce/pages/workspace/WorkspaceInviteUsersForm.tsx, app/client/src/ce/sagas/SuperUserSagas.tsx, app/client/src/ce/sagas/tenantSagas.tsx, app/client/src/pages/Settings/config/advanced.ts, app/client/src/utils/AnalyticsUtil.tsx
Add instance id property to all analytic events
Fixes [#24243](https://github.com/appsmithorg/appsmith/issues/24243)
=> chore: Add instance id property to all analytic events

app/client/src/ce/pages/UserAuth/ThirdPartyAuth.tsx
Adding key icon on login buttons for OIDC and SAML
Fixes [#23899](https://github.com/appsmithorg/appsmith/issues/23899)
>
=> fix: Adding key icon on login buttons for OIDC and SAML

app/client/src/WidgetQueryGenerators/GSheets/index.test.ts, app/client/src/WidgetQueryGenerators/GSheets/index.ts, app/client/src/WidgetQueryGenerators/index.ts, app/client/src/WidgetQueryGenerators/types.ts, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/TableOrSpreadsheetDropdown/index.tsx, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/TableOrSpreadsheetDropdown/useTableOrSpreadsheet.tsx, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/ConnectData/useConnectData.ts, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/DatasourceSpecificControls/GoogleSheetControls/SheetsDropdown/index.tsx, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/DatasourceSpecificControls/GoogleSheetControls/SheetsDropdown/useSheets.tsx, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/DatasourceSpecificControls/GoogleSheetControls/TableHeaderIndex/index.tsx, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/DatasourceSpecificControls/GoogleSheetControls/TableHeaderIndex/useTableHeader.ts, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/WidgetSpecificControls/index.tsx, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/styles.tsx, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/utils.ts, app/client/src/components/propertyControls/OneClickBindingControl.tsx
Developed Gsheets query generator for one click binding epic.
Fixes #23255
>
>
>
>
>
>
>
>
=> chore: [one click binding] gsheets query adaptor

app/client/src/pages/Editor/GuidedTour/constants.tsx
Minor change to text in onboarding flow.
Fixes #24252 
>
>
>
>
>
>
>
>
>
>
>
>
>
>
=> fix: Modifies Action selector copy in onboarding flow

app/client/package.json, app/client/yarn.lock
=> chore: use stable design-system release

app/client/cypress/locators/GithubForm.json, app/client/cypress/support/AdminSettingsCommands.js, app/client/src/ce/constants/forms.ts, app/client/src/ce/constants/messages.ts, app/client/src/ce/pages/AdminSettings/config/authentication/index.tsx
Add redirect and homepage URL on Github config page for better user experience.
Fixes [#24390](https://github.com/appsmithorg/appsmith/issues/24390)
=> chore: Add redirect and homepage URL on Github config page

app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx, app/client/src/constants/AppsmithActionConstants/ActionConstants.tsx, app/client/src/utils/ApiPaneUtils.tsx
This PR improves the evaluated value experience to be able to accommodate more edge cases and also process different url input types that a user can provide especially in the case of query parameters.
Fixes #24299 
>
>
Verified below - 
[https://www.as/{{true](https://www.as/%7B%7Btrue) ? 'ass' : 'add'}}/{{Button1.text}}/{{'hgg'}}?{{Button1.isVisible}}={{Button1.text}}&{{Alert_text.text}}=hey
[https://www.as/{{true](https://www.as/%7B%7Btrue) ? 'ass' : 'add'}}/{{Button1.text}}/{{'hgg'}}?{{Button1.isVisible}}={{Button1.text}}&{{Alert_text.text}}=hey/{{Alert_text.text}} …
=> fix: Improve evaluated url experience

app/client/src/ce/pages/AdminSettings/config/authentication/AuthPage.tsx, app/client/src/components/formControls/KeyValueArrayControl.tsx
Updating key value array control component to support custom attributes on SAML config page
Fixes [#24288](https://github.com/appsmithorg/appsmith/issues/24288)
=> feat: Updating key value array control component to support custom attributes on SAML config page

app/client/cypress/e2e/Regression/ClientSide/Widgets/WidgetPropertySetters_spec.ts, app/client/src/workers/Evaluation/setters.ts
Added tests for linting in widget property setters
Fixes #23651
>
>
>
>
>
>
>
> …
=> Added tests for linting in widget property setters

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration014UpdateOraclePluginDocumentationLink.java
- Add migration to fix Oracle documentation link. 
Fixes #24399 
>
>
>
>
>
=> fix: add migration to update Oracle doc link

app/client/package.json, app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx, app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx, app/client/src/pages/common/CanvasArenas/hooks/useCanvasDragToScroll.ts, app/client/src/sagas/FormEvaluationSaga.ts, app/client/src/utils/WorkerUtil.test.ts, app/client/src/widgets/ButtonGroupWidget/component/index.tsx, app/client/src/widgets/TableWidgetV2/widget/index.tsx, app/client/src/workers/Evaluation/fns/overrides/fetch.ts, app/client/yarn.lock
Adds the @types/web to cleanup some ignored typescript errors
=> chore: Cleanup some typescript web issues

app/client/src/ce/constants/tenantConstants.ts, app/client/src/ce/reducers/settingsReducer.ts, app/client/src/ce/utils/adminSettingsHelpers.ts, app/client/src/components/formControls/KeyValueArrayControl.tsx, app/client/src/ee/constants/tenantConstants.ts, app/client/src/pages/Settings/SettingsForm.tsx
Optimizing the solution for supporting tenant config on admin settings
=> chore: Optimizing the solution for supporting tenant config on admin settings

app/client/cypress/e2e/Regression/ClientSide/Git/GitDiscardChange/DiscardChanges_spec.js, app/client/cypress/support/gitSync.js, app/client/src/api/GitSyncAPI.tsx, app/client/src/ce/constants/messages.test.ts, app/client/src/ce/constants/messages.ts, app/client/src/pages/Editor/gitSync/Tabs/Deploy.tsx, app/client/src/pages/Editor/gitSync/components/DiscardChangesWarning.tsx, app/client/src/sagas/GitSyncSagas.ts, app/server/appsmith-git/src/main/java/com/appsmith/git/service/GitExecutorImpl.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/git/GitExecutor.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/GitControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java
Due to one of the corrupted app state in release, we are going to revert this and retest it and release later. 
https://theappsmith.slack.com/archives/CTHN8GX5Y/p1686637493386649
=> chore: revert git rebase with discard

app/client/cypress.config.ts
- This pR fixes the cypress.config.ts file syntax error that helps to run tests locally
- config filr fix (non-breaking change which fixes an issue)
=> test: Cypress | Local config file syntax fix

app/client/src/ce/components/editorComponents/GPT/trigger.tsx, app/client/src/components/editorComponents/CodeEditor/index.tsx, app/client/src/entities/FeatureFlags.ts
CE changes to support https://github.com/appsmithorg/appsmith-ee/pull/1644
>
>
>
>
>
>
>
>
>
>
>
>
>
>
> Link issues raised during DP testing for better visiblity and tracking (copy link …
=> chore: use separate feature flags for JS expressions and SQL query AI

app/client/src/pages/Editor/APIEditor/GraphQL/Pagination.tsx
In Datasource, Graphql pagination settings copy is changed as:
* Paginate via limit and offset ----> Paginate using limit and offset
* Paginate via cursor based ----> Paginate using cursor
Fixes # #24469 
>
>
>
>
>
>
>
>
>
>
=> fix: update graphql pagination label cop

.github/workflows/client-lint.yml, .github/workflows/client-prettier.yml, .github/workflows/client-unit-tests.yml, app/client/build.sh
Separation to different steps of running lint, prettier, and jest unit tests
>
=> chore: separation of client build steps

app/client/src/components/formControls/KeyValueArrayControl.tsx, app/server/appsmith-plugins/arangoDBPlugin/src/main/resources/form.json, app/server/appsmith-plugins/elasticSearchPlugin/src/main/resources/form.json, app/server/appsmith-plugins/mongoPlugin/src/main/resources/form.json, app/server/appsmith-plugins/mssqlPlugin/src/main/resources/form.json, app/server/appsmith-plugins/mysqlPlugin/src/main/resources/form.json, app/server/appsmith-plugins/oraclePlugin/src/main/resources/form.json, app/server/appsmith-plugins/postgresPlugin/src/main/resources/form.json, app/server/appsmith-plugins/redisPlugin/src/main/resources/form.json, app/server/appsmith-plugins/redshiftPlugin/src/main/resources/form.json, app/server/appsmith-plugins/smtpPlugin/src/main/resources/form.json
This PR fixes : 
- the functionality of placeholder for the key value array control which was earlier accessing `placeholderText` key from a wrong path for host.
- Added placeholders for different datasources as well
Fixes #23487
>
>
>
>
- This change …
=> fix: functionality of placeholdertext in key value array control

.github/workflows/ci-test.yml
- This PR sets the commit message for Cypress dashboard display
=> ci: Set Commit Message update

.github/workflows/ci-test.yml
- This PR includes the commit id in Cypress dashboard title
=> ci: Set Commit Message

.github/workflows/ci-test.yml
- This PR tries to set the proper branch name of a PR
=> ci: Set Branch name

app/client/src/pages/Editor/Explorer/Datasources/DatasourceEntity.tsx, app/client/src/sagas/DatasourcesSagas.ts
When a mock datasource is created, we the fetch datasource structure like other datasources.
Fixes #24463 
>
>
>
>
>
>
>
>
=> fix: Fix get structure for Mock datasources

.github/workflows/ci-test.yml, app/client/cypress/e2e/Regression/ClientSide/AdminSettings/Admin_settings_spec.js, app/client/cypress/e2e/Regression/ClientSide/ExplorerTests/Admin_settings_spec.js, app/client/cypress/e2e/Regression/ClientSide/ExplorerTests/Scrolling_Spec.ts, app/client/cypress/e2e/Regression/ClientSide/OtherUIFeatures/Omnibar_spec.js, app/client/cypress/e2e/Regression/ClientSide/ThemingTests/Theme_FormWidget_spec.js, app/client/cypress/e2e/Regression/ServerSide/OnLoadTests/JSOnLoad2_Spec.ts, app/client/cypress/support/Pages/AggregateHelper.ts, app/client/cypress/support/Pages/DataSources.ts, app/client/cypress/support/Pages/HomePage.ts
- This PR fixes Cypress flaky tests as mentioned below:
- JS_AC_spec.ts
- Admin_settings.js
- Theme_FormWidget_spec.js
- Scrolling_Spec.ts
- JSOnLoad2_Spec.ts
- Pick up the branch name from PR number
- Script update (non-breaking change which fixes an issue)
>
>
=> test: Cypress | Flaky fixes

.github/workflows/ci-test.yml
- This PR fixes the syntax error in ci-test.yml
=> ci: Fix Syntax in ci-test.yml

.github/workflows/ci-test.yml
- This message updates the COMMIT_INFO_MESSAGE_FINAL
=> ci: Comit Message update

.github/workflows/ci-test.yml, app/client/cypress/e2e/Regression/ClientSide/ThemingTests/Theme_FormWidget_spec.js, app/client/cypress/e2e/Regression/ClientSide/ThemingTests/Theme_MultiSelectWidget_spec.js, app/client/cypress/support/Pages/AppSettings/ThemeSettings.ts
- This PR fixes flaky ThemingTests
=> test: Cypress | ThemingTests fixes

.github/workflows/ci-test.yml
- This PR fixes the syntax for  Set Pull Request Title
=> ci: Set Pull Request Title syntax fix

.github/workflows/ci-test.yml
- This PR updates the Push wokflow message
=> ci: COMMIT_INFO_MESSAGE update

.github/workflows/ci-test.yml
- This PR updates the Set Pull Request Title to view thew event details
=> ci: Set Pull Request Title update

app/client/cypress/e2e/Regression/ClientSide/Autocomplete/Bug23641_Spec.ts, app/client/cypress/e2e/Regression/ClientSide/Autocomplete/Bugs_AC_Spec.ts, app/client/cypress/e2e/Regression/ClientSide/Binding/API_with_List_Widget_spec.js
- This PR fixes the import updates of few specs to import only required objects & not all from ObjectsCore
>
>
>
=> test: Cypress | Few specs import updates

.github/workflows/ci-test.yml
- This PR take only EVENT_COMMITS message to display in title
=> ci: EVENT_COMMITS message update

.github/workflows/ci-test.yml
- This PR fixes the issue in getting in PR title for push workflows
=> ci: PR title text format update

app/client/cypress/e2e/Regression/ClientSide/Binding/InputWidget_Table_Sorting_spec.js
- InputWidget_Table_Sorting_spec imports updated
=> test: Cypress | Imports update

.github/workflows/ci-test.yml
- This PR fixes the right syntax to pick up the PR title for push workflows
=> ci: Commit Message syntax fix

app/client/cypress/e2e/Regression/ClientSide/Binding/InputWidget_TableV2_Sorting_spec.js
- This PR updates import for InputWidget_TableV2_Sorting_spec
=> test: Cypress | Import update

deploy/docker/entrypoint.sh
Fixes https://github.com/appsmithorg/appsmith/issues/24358 where postgres system files owner is updated with mongodb user on updating Appsmith.
Tested manually by updating v1.9.22 to nightly.
=> fix: Embedded postgres file owner fix

deploy/docker/entrypoint.sh
Fixes https://github.com/appsmithorg/appsmith/issues/24358 where postgres system files owner is updated with mongodb user on updating Appsmith.
Tested manually by updating v1.9.22 to nightly.
(cherry picked from commit 1e33a6c5dc4618986d43bcadc23b4079b8596559)
>
>
>
>
>
>
> if no issue exists, please …
=> fix: Embedded postgres file owner fix (#24601)

app/client/src/components/editorComponents/AutoLayoutDropTarget.tsx, app/client/src/utils/autoLayout/constants.ts, app/client/src/widgets/CameraWidget/index.ts, app/client/src/widgets/ChartWidget/index.ts, app/client/src/widgets/CheckboxGroupWidget/index.ts, app/client/src/widgets/CodeScannerWidget/index.ts, app/client/src/widgets/ContainerWidget/index.ts, app/client/src/widgets/DocumentViewerWidget/index.ts, app/client/src/widgets/FormWidget/index.ts, app/client/src/widgets/IframeWidget/index.ts, app/client/src/widgets/ImageWidget/index.ts, app/client/src/widgets/JSONFormWidget/index.ts, app/client/src/widgets/ListWidgetV2/index.ts, app/client/src/widgets/MapChartWidget/index.ts, app/client/src/widgets/MapWidget/index.ts, app/client/src/widgets/RadioGroupWidget/index.ts, app/client/src/widgets/RichTextEditorWidget/index.ts, app/client/src/widgets/StatboxWidget/index.ts, app/client/src/widgets/SwitchGroupWidget/index.ts, app/client/src/widgets/TableWidgetV2/index.ts, app/client/src/widgets/TabsWidget/component/index.tsx, app/client/src/widgets/TabsWidget/index.ts, app/client/src/widgets/VideoWidget/index.ts
Trying to implement what is being documented [here](https://www.notion.so/appsmith/Widget-s-vertical-positioning-update-WIP-b1866e4090ac4a4aba7a8163eff7d124).
fixes #24495
=> poc: Vertical alignment

scripts/deploy_preview.sh
Completes: [24356](https://github.com/appsmithorg/appsmith/issues/24356)
=> chore: bump helm chart version

app/client/src/widgets/CheckboxGroupWidget/index.ts, app/client/src/widgets/DatePickerWidget/index.ts, app/client/src/widgets/DatePickerWidget/widget/index.tsx, app/client/src/widgets/DatePickerWidget2/index.ts, app/client/src/widgets/DatePickerWidget2/widget/index.tsx, app/client/src/widgets/JSONFormWidget/widget/index.tsx, app/client/src/workers/Evaluation/__tests__/setters.test.ts
Fixes issues mentioned in comment here https://github.com/appsmithorg/appsmith/pull/23441#issuecomment-1577956441 
=> fix: Issues-wps-2

app/client/cypress/support/gitSync.js, app/client/src/ce/constants/messages.test.ts, app/client/src/ce/constants/messages.ts, app/client/src/pages/Editor/gitSync/Tabs/Deploy.tsx, app/client/src/pages/Editor/gitSync/components/DiscardChangesWarning.tsx
re-adding changes missed during merging pr 24414
Fixes #24414 
>
>
>
>
>
>
>
>
=> fix: re-adding diff missed in pr #24414

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/ExecutionTimeLogging.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/GitServiceCEImplTest.java
Added the execution time for the individual flows in the git ops - commit and status. This data will be sued to analyse the time consumed and improve the performance of these API's. 
Fixes https://github.com/appsmithorg/appsmith/issues/24312
=> chore: Add excution time for git commit flow

CODEOWNERS
=> chore: Add app viewer related codeowners

README.md
Added This project is tested with BrowserStack
- Manual
=> ocs: Adding Browserstack endorsement on our README

.github/workflows/integration-tests-command.yml
Reverts appsmithorg/appsmith#24616
=> Revert "chore: Skip tests in server build if no changes in server files for ok-to-test command"

app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug22499_Spec.ts, app/client/src/ce/workers/Evaluation/Actions.ts, app/client/src/entities/AppTheming/index.ts, app/client/src/entities/DataTree/dataTreeWidget.test.ts, app/client/src/entities/DataTree/dataTreeWidget.ts, app/client/src/utils/FilterInternalProperties/Widget.ts, app/client/src/utils/autocomplete/dataTreeTypeDefCreator.ts, app/client/src/widgets/DatePickerWidget/index.ts, app/client/src/widgets/TableWidgetV2/widget/index.tsx, app/client/src/workers/Evaluation/__tests__/setters.test.ts, app/client/src/workers/Evaluation/evaluate.ts, app/client/src/workers/Evaluation/setters.ts, app/client/src/workers/Linting/index.ts
feat:setSelectedRow setter shows up based on multiRowSelection value
>
>
>
>
>
>
>
>
> Please describe the tests that you ran to verify your changes. Also list any relevant details …
=> feat:setSelectedRow setter shows up based on multiRowSelection value

app/server/appsmith-server/src/main/java/com/appsmith/server/featureflags/FeatureFlagEnum.java
=> fix: Adds comma to make sure that after synching to EE build does not fail

app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/PropertyControl_spec.ts, app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/spec_utility.ts, app/client/cypress/locators/OneClickBindingLocator.ts, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/DatasourceDropdown/DropdownOption.tsx, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/DatasourceDropdown/index.tsx, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/DatasourceDropdown/useDatasource.tsx, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/TableOrSpreadsheetDropdown/index.tsx, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/DatasourceSpecificControls/GoogleSheetControls/SheetsDropdown/index.tsx, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/WidgetSpecificControls/ColumnDropdown/index.tsx, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/constants.ts, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/index.tsx, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/styles.tsx, app/client/src/components/propertyControls/OneClickBindingControl.tsx, app/client/src/sagas/SnipingModeSagas.ts
Fixes https://github.com/appsmithorg/appsmith/issues/24404
>
>
>
>
>
>
>
>
> Add Testsmith test cases links that relate to this …
=> chore: [one click binding] convert select component to menu component on property control

app/client/cypress/e2e/Regression/ClientSide/Autocomplete/Autocomplete_setters_spec.ts, app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug22499_Spec.ts, app/client/cypress/e2e/Regression/ClientSide/Widgets/Others/Autocomplete_spec.js, app/client/src/pages/Editor/Explorer/Entity/EntityProperties.tsx
Fixed failing tests for widget property setters
Fixes #23652
>
>
>
>
>
>
>
> …
=> Fixed failing tests for widget property setters

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration009RemoveStructureFromWithinDatasource.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration012RenameIndexesWithLongNames.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration015RemoveNullEnvIdDatasourceStrucutureDocuments.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/DatasourceStructureSolutionTest.java
Cherry picking release blocker fix into promotion PR
=> fix: changing the index for datasourceStorageStructure collection (#24629)

app/client/src/ce/sagas/ApplicationSagas.tsx, app/client/src/sagas/DatasourcesSagas.ts
This PR fixes forking related issues introduced in plugins like  Google Sheets, Amazon S3, DynamoDB, MongoDB etc.
Fixes #24566
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
=> fix: forking reconnect modal issue fixed

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/DatasourceStorageDTO.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ForkExamplesWorkspaceServiceTests.java
After forking an application, the reconnect modal appears. In the reconnect modal, it's not possible to reauthorize the google sheets plugin. This PR fixes the problem.
Fixes #24566
>
>
>
>
>
>
>
>
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on this …
=> fix: Reconnect failure error after fork application

app/client/cypress/e2e/Regression/ClientSide/Templates/Fork_Template_To_App_spec.js
Fixing flaky test seen in https://github.com/appsmithorg/appsmith/pull/24683#issuecomment-1603675137
=> chore: update fork template to app test

app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ApplicationSnapshot.java, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/ApplicationPagesDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationSnapshotServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewPageServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationSnapshotServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/NewPageServiceTest.java
This PR stops writing 404 error on log when snapshot is not found in the get snapshot API.
Fixes #24786
>
>
>
>
>
=> fix: Remove not found error in get snapshot API

app/client/src/pages/Editor/Explorer/Entity/EntityProperties.tsx, app/client/src/widgets/CategorySliderWidget/index.ts, app/client/src/widgets/CategorySliderWidget/widget/index.tsx, app/client/src/widgets/FormWidget/index.ts, app/client/src/widgets/FormWidget/widget/index.tsx, app/client/src/widgets/NumberSliderWidget/index.ts, app/client/src/widgets/NumberSliderWidget/widget/index.tsx, app/client/src/widgets/TableWidget/index.ts, app/client/src/widgets/TableWidget/widget/index.tsx
fix: Missing configs for some widgets and failing tests
Fixes #23652
>
>
>
>
>
>
>
>
> Add Testsmith test cases links that …
=> fix: Missing configs for some widgets and failing tests

app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/table_data_change_spec.ts
This PR fixes the flakiness that is observed in the [table_data_change_spec.ts](https://cloud.cypress.io/projects/eyxvp8/runs/36776/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%7B%22label%22%3A%22Regression%2FClientSide%2FWidgets%2FTableV2%2Ftable_data_change_spec.ts%22%2C%22value%22%3A%22%5B%5C%22cb0dda8d-2fda-4524-b5e9-2c9d3ac2ddfa%5C%22%5D%22%7D%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D)
>
>
>
>
>
> Link issues raised during DP …
=> fix: table spec flakiness

app/client/cypress/e2e/Regression/ClientSide/Autocomplete/Autocomplete_setters_spec.ts, app/client/src/widgets/MultiSelectWidget/widget/index.tsx, app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx, app/client/src/workers/Evaluation/setters.ts
- Change the error message.
- Add setSelectedOptions for multiSelect widget
>
>
>
>
>
>
>
>
=> fix: wps-issues-4

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserServiceTest.java
> Refactor the User creation workflow.
> Changes:
> - Changed the access of  `addUserPolicies` to protected so that it can be overridden in `UserServiceImpl.java`. 
> - Added `addUserPoliciesAndSaveToRepo` which wraps around `addUserPolicies` and then saves the updated user object to Database.
> - Removed a few debug logs, which were added earlier.
> - Updated the test case assertions in `createNewUser_WhenEmailHasUpperCase_SavedInLowerCase` and `createNewUserValid`
> No testing required as we are widening the scope of a method.
=> chore: refactor user creation flow 

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/NetworkUtils.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/NetworkUtilsCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/PingScheduledTaskImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/UserSignupImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PingScheduledTaskCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/UserSignupCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/UserSignupTest.java
PR to code split the Network utils class which is being used and modified in both CE and EE repo. This will fix the merge conflicts we were seeing recently for NetworkUtils class.  
EE PR: https://github.com/appsmithorg/appsmith-ee/pull/1708
Fixes https://github.com/appsmithorg/appsmith/issues/24271
=> chore: Code split for network utils class

app/client/src/pages/setup/Welcome.tsx
Fixes an issue with the welcome screen not loading the complete form if the browser was resized to a very small size.
Fixes #24520 
>
>
>
>
>
>
>
>
>
>
=> fix: set the min width to allow all content to load with a scroll 

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/ImportApplicationPermissionProvider.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/PolicyUtil.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/PermissionGroupServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserWorkspaceServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/WorkspaceServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/PermissionGroupServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserWorkspaceServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/EnvManagerImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/PolicySolution.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/PolicySolutionImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/EnvManagerCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PolicySolutionCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PolicySolutionCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/configurations/SeedMongoData.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ThemeServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserWorkspaceServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/ApplicationServiceCETest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/NewActionServiceCEImplTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/EnvManagerTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/UserSignupTest.java
Simply refactors code to allow EE overrides.
Only needs existing cases to pass
>
>
=> chore: Code split for policy utils

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/EnvManagerImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/EnvManagerTest.java
Fixes issues with component init because of policy utils changes
=> chore: Policy utils split constructor failures

app/client/.eslintrc.base.json, app/client/build.sh
Disable CRA built-in ESLint checks since we have our own config and a separate step for this
>
=> chore: disable cra eslint

app/client/src/ce/constants/messages.ts
Over all 3 points remain in #17745 :
1. Filters in templates should be sorted alphabetically.
2. The filters should have a clear all functionality.
3. Request a template  says that a "github issue portal will be opened" but instead opens one appsmith app - Need better text for this.
We are ignoring the first 2 based on our discussions [here](https://theappsmith.slack.com/archives/C02RCR2PURZ/p1688059428209129?thread_ts=1688032518.811489&cid=C02RCR2PURZ)
Fixing last one in here, updated the `Request for a template` message.
Fixes #17745 (17745 can be closed with this PR).
>
> Delete anything …
=> chore: Updates message shown for requesting a template

app/client/src/widgets/ImageWidget/component/index.tsx, app/client/src/widgets/ImageWidget/widget/index.tsx, app/client/src/workers/Evaluation/setters.ts
Fix: Added setter name to error message and setImage is fixed
>
>
>
>
>
>
>
> …
=> fix: Added setter name to error message and setImage is fixed

app/client/src/entities/DataTree/dataTreeWidget.test.ts, app/client/src/widgets/CategorySliderWidget/widget/index.tsx, app/client/src/widgets/CheckboxGroupWidget/widget/index.tsx, app/client/src/widgets/CheckboxWidget/widget/index.tsx, app/client/src/widgets/CurrencyInputWidget/widget/index.tsx, app/client/src/widgets/DatePickerWidget/widget/index.tsx, app/client/src/widgets/DatePickerWidget2/widget/index.tsx, app/client/src/widgets/InputWidget/widget/index.tsx, app/client/src/widgets/InputWidgetV2/widget/index.tsx, app/client/src/widgets/JSONFormWidget/widget/index.tsx, app/client/src/widgets/MultiSelectWidget/widget/index.tsx, app/client/src/widgets/MultiSelectWidgetV2/widget/index.tsx, app/client/src/widgets/NumberSliderWidget/widget/index.tsx, app/client/src/widgets/RadioGroupWidget/widget/index.tsx, app/client/src/widgets/RateWidget/widget/index.tsx, app/client/src/widgets/SwitchWidget/widget/index.tsx, app/client/src/widgets/TableWidget/widget/index.tsx, app/client/src/widgets/TableWidgetV2/widget/index.tsx, app/client/src/workers/Evaluation/__tests__/setters.test.ts
Removed setSelectedOptions, setData, setSourceData, setValue from the list of setters for V1
>
>
>
>
>
>
>
>
> Please describe the tests that you ran to verify your changes. Also list …
=> chore: Removed setSelectedOptions, setData, setSourceData, setValue from the list of setters for V1

app/client/src/widgets/CurrencyInputWidget/widget/index.tsx, app/client/src/widgets/InputWidgetV2/widget/index.tsx, app/client/src/widgets/JSONFormWidget/widget/propertyConfig.ts, app/client/src/workers/Evaluation/validations.ts
- Fix reference error related issue 
- Fix validation issue 
>
>
>
>
>
=> fix: validation

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ActionDTO.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/AnalyticsInfo.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/ActionServiceCE_Test.java
To measure the impact of query modules in Appsmith. We need to track the time a user takes to edit a copied query. Today, we do not have a mechanism to understand if a query in question is a copied query. To fix this, the data model of the Query action needs to change to include the `originalQueryId` if a query is, in fact, a copied query. 
|POST|`/api/v1/actions`|
----------|------|
Fixes #24734 
>
>
- …
=> Store `originalActionId` as part of Action DTO for copied action 

app/client/src/WidgetQueryGenerators/Snowflake/index.test.ts, app/client/src/WidgetQueryGenerators/Snowflake/index.ts, app/client/src/WidgetQueryGenerators/index.ts, app/client/src/entities/Action/index.ts
>
>
>
>
>
>
Fixes #24781 
>
>
>
>
- Bug fix (non-breaking …
=> feat: snowflake query generator

app/client/src/widgets/TableWidgetV2/index.ts
When setData is called, we update tableData's value and in tern all the dependent values are to be updated based on what is there in the inverseDependency map. Since we set the tableData initially as `undefined`, it is missing from the inverseDependencyMap and thereby the dependent values are not being updated resulting in no data showing up on the table. 
>
>
>
>
- Breaking change (fix or feature …
=> fix: Setting default of tableData to empty string

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
Add analytics data points for the merge status flow
Fixes #24803
=> chore: Add analytics event for merge branch status

app/client/cypress/e2e/Regression/ClientSide/MobileResponsiveTests/AutoFillWidgets_Reflow_spec.ts
**Skipped below flaky tests to unblock CI**
- AutoFillWidgets_Reflow_spec.ts
=> test: Cypress - Skipping test to unblock CI

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/SecurityConfig.java, app/server/appsmith-server/src/main/resources/application.properties
Adds provision to use custom basic authentication creds for actuator endpoints. If none are provided, we would still need to use basic auth header with empty creds.
This PR requires us to make the relevant changes on cloud (add env vars and change Grafana settings) before it is merged into any of the branches.
Fixes https://github.com/appsmithorg/appsmith-ee/issues/1441
>
>
>
>
>
>
>
>
>
>
>
=> chore: Added provision for specific basic auth creds for actuator endpoints

app/client/packages/design-system/theming/src/color/DarkModeTheme.ts, app/client/packages/design-system/theming/src/color/LightModeTheme.ts, app/client/packages/design-system/theming/src/color/types.ts
tl;dr Automatic adjustment for `*Warning` colors if seed is yellow. Fixes for found errors in prior algo.
Fixes #23802   
- Manual
=> feat: WDS algorithmic warning (yellow) colors

app/client/src/pages/common/datasourceAuth/AuthMessage.tsx
This PR fixes google sheets datasource documentation not pointing to correct link.
Fixes #25004 
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
=> fix: gsheet doc wrong link issue fixed

app/client/cypress/e2e/Regression/Apps/MongoDBShoppingCart_spec.ts, app/client/cypress/e2e/Regression/ClientSide/OtherUIFeatures/Omnibar_spec.js, app/client/cypress/e2e/Regression/ServerSide/QueryPane/DSDocs_Spec.ts, app/client/cypress/e2e/Regression/ServerSide/QueryPane/GoogleSheets_spec.js, app/client/cypress/support/Objects/CommonLocators.ts, app/client/cypress/support/Pages/AssertHelper.ts, app/client/cypress/support/Pages/DeployModeHelper.ts, app/client/cypress/support/Pages/Table.ts
- This PR has below:
- improves StubWindowNAssert()
- Adds new test for Bug # 25004
- AssertNetworkStatus() fixed
>
=> test: Cypress | Flakyfix + New Scripts

app/client/cypress/e2e/Regression/ClientSide/OtherUIFeatures/Omnibar_spec.js
- This PR fixes the failing Omnibar_spec.js
=> test: Cypress | Omnibar_spec.js fix

app/server/appsmith-server/src/main/java/com/appsmith/server/constants/LicensePlan.java, app/server/appsmith-server/src/main/java/com/appsmith/server/constants/ce/LicensePlan.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/License.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ce/LicenseCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ce/TenantConfigurationCE.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/TenantServiceCETest.java
This PR moved the License domain out of TenantConfiguration
>
>
>
>
>
>
>
>
>
>
>
=> chore: Moved the License domain out TenantConfiguration

app/client/cypress/fixtures/featureFlags.json, app/client/src/ce/entities/FeatureFlag.ts, app/server/appsmith-server/src/main/java/com/appsmith/server/featureflags/FeatureFlagEnum.java, app/server/appsmith-server/src/main/resources/features/init-flags.xml
Renaming feature flag in accordance to Flagsmith nomenclature.
=> chore: Renaming feature flags for ME to lower case

app/client/src/components/editorComponents/ActionRightPane/SuggestedWidgets.tsx, app/client/src/components/editorComponents/ActionRightPane/index.tsx, app/client/src/pages/Editor/Explorer/Datasources/DatasourceStructure.tsx, app/client/src/pages/Editor/Explorer/Datasources/DatasourceStructureContainer.tsx, app/client/src/pages/Editor/Explorer/Datasources/DatasourceStructureLoadingContainer.tsx, app/client/src/pages/Editor/Explorer/Datasources/QueryTemplates.tsx, app/client/src/pages/Editor/Explorer/Entity/index.tsx, app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx, app/client/src/pages/Editor/utils.ts
Fixes UI activation issues
>
>
>
>
>
>
>
>
> Delete …
=> fix: Fix/UI activation issues

app/client/src/components/editorComponents/ActionRightPane/SuggestedWidgets.tsx, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/WidgetSuggestionHelper.java
This PR fixes UI issues mentioned in [thread](https://theappsmith.slack.com/docs/TGA9SH07N/F05F32WKVKQ).
These are UI Audit issues mentioned by @carinanfonseca using the [DP](https://ce-24915.dp.appsmith.com/)
Fixes #25121 
>
>
>
>
>
>
>
>
>
>
>
> Link issues raised during DP testing for better visiblity and …
=> fix: UI review fixes

app/client/src/components/editorComponents/ActionRightPane/SuggestedWidgets.tsx
This PR adds new widget thumbnail in the connect to existing widgets section of bindings as per designs below:  
Fixes #25121 
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
=> fix: new widget thumbnail added for existing widgets

app/client/src/components/editorComponents/ActionRightPane/SuggestedWidgets.tsx, app/client/src/constants/DefaultTheme.tsx
This PR fixes API Editor UI issues in the right pane.
>
>
>
>
>
>
>
>
>
>
>
>
>
>
>
=> fix: Api editor right pane width issue fixed

app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/CustomServerOAuth2AuthorizationRequestResolverCE.java
> `CustomServerOAuth2AuthorizationRequestResolverCE.java` was missed from formatting. Reformatted it.
Fixes no issues. Just formats the file to avoid conflicts in Sync community workflow.
>
>
>
> Server build should pass.
>
>
>
>
>
=> refactor: CustomServerOAuth2AuthorizationRequestResolverCE.java

app/client/cypress/e2e/Regression/Apps/CommunityIssues_Spec.ts
- This PR skips Apps/CommunityIssues_Spec.ts - (8, 9, 10th) cases to replace the failing api to TED api
=> test: Cypress | Skipping test to unblock CI

app/client/.husky/pre-commit, app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/constants/S3PluginConstants.java, app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationSuccessHandlerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/CacheableFeatureFlagHelperImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CacheableFeatureFlagHelperCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/FeatureFlagServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/FeatureFlagServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ThemeServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/FeatureFlagServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ThemeServiceTest.java, app/server/pom.xml, pre-commit
Adds a check so that folks do not have to remember to have to build server when there are changes.
Also includes formatting for some files that were committed without merging from release.
=> ci: Added pre-commit hook to check for Spotless formatting

app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/utils/SheetsUtil.java
- Remove unused code.
Fixes #25160 
>
>
>
>
>
>
>
>
=> chore: remove redundant code

app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/MockDataServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ActionExecutionSolutionCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/CreateDBTablePageSolutionCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceTriggerSolutionCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ce/ActionExecutionSolutionCEImplTest.java
Only contains addition of a new overridden method that is the same as the existing method in this repo.
=> chore: Skeleton for ME OOS changes

app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java, app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithErrorCode.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceStorageServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ActionExecutionSolutionCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceStorageServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ce/ActionExecutionSolutionCETest.java
> TL;DR adds validation to datasource create flow and error handling to execution flow
Fixes #25200, #25204  
>
>
>
>
>
>
>
=> fix: add validation to datasource create flow and error handling

app/client/cypress/e2e/Regression/ClientSide/Onboarding/GuidedTour_spec.js
- This PR fixes the flaky Onboarding/GuidedTour_spec.js
=> test : Cypress | Flaky fix Onboarding/GuidedTour_spec.js

app/client/src/workers/Evaluation/evalTreeWithChanges.ts
Fixes https://github.com/appsmithorg/appsmith/issues/25287
>
>
>
>
>
None
>
>
>
=> fix: CurrencyInput setValue due to meta override

.github/workflows/integration-tests-command.yml
=> chore: Fix changeset workflow to run on external contributor PR

app/client/src/WidgetQueryGenerators/Snowflake/index.ts
The lodash import comes from a worker wrapper rather importing from lodash lib.
=> fix: lodash import

app/client/.husky/check-staged-files.sh, app/client/.husky/pre-commit
Fixes for running checks on pre-commit for BE and FE separately
>
=> fix: fixes for running checks on pre-commit for BE and FE separately

app/client/.husky/check-staged-files.sh
=> fix: pre-commit logic

app/client/src/pages/Editor/gitSync/GitSyncModal.tsx, app/client/src/pages/Editor/gitSync/Tabs/Merge.tsx, app/client/src/pages/Editor/gitSync/components/ConflictList.tsx, app/client/src/pages/Editor/gitSync/components/DiffViewer.tsx, app/client/src/pages/Editor/gitSync/components/MergeStatus.tsx, app/client/src/selectors/gitSyncSelectors.tsx
- Just initial barebones UI to show conflicting git files and open diff viewer
=> feat: display conflict files, skeleton diff viewer

app/client/src/pages/Editor/gitSync/components/DiffViewer.js
=> Add diff viewer

app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java, app/server/appsmith-git/src/main/java/com/appsmith/git/service/GitExecutorImpl.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/git/FileInterface.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/git/GitExecutor.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/GitControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/ConflictedFileVersionsDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitFileUtils.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
=> Added API to get versions of a conflicted file

app/client/packages/rts/src/controllers/jsEndpointExecute/JsEndpointExecuteController.ts
=> feat: new eval method

app/server/appsmith-git/src/main/java/com/appsmith/git/constants/CommonConstants.java, app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/DSLTransformerHelper.java, app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java, app/server/appsmith-git/src/test/java/com/appsmith/git/helpers/DSLTransformHelperTest.java
fix the Tabs Widget issue for canvas split
=> fix: tabs widget reading from file system

app/client/packages/design-system/theming/src/color/DarkModeTheme.ts, app/client/packages/design-system/theming/src/color/LightModeTheme.ts
tl;dr Nicer looking subtles
Fixes #24747
- Manual
=> feat: WDS colors `*Subtle` refinement

app/client/src/ce/utils/Environments/index.tsx, app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx, app/client/src/pages/Editor/gitSync/ReconnectDatasourceModal.tsx, app/client/src/pages/common/datasourceAuth/index.tsx, app/client/src/sagas/DatasourcesSagas.ts
=> chore: Add telemetry for ME

app/client/cypress/e2e/Regression/ServerSide/QueryPane/S3_1_spec.js
=> fix: cypress prettier

app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceContextServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/MockDataServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/ActionServiceCE_Test.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/ApplicationServiceCETest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ApplicationForkingServiceTests.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/AuthenticationServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/DatasourceStructureSolutionTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/DatasourceTriggerSolutionTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ForkExamplesWorkspaceServiceTests.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ce/ActionExecutionSolutionCETest.java
Only contains yet another Spotless formatting skipped during commit check
=> chore: Formatting fixes

app/client/src/ce/entities/FeatureFlag.ts, app/client/src/pages/Editor/AppSettingsPane/AppSettings/NavigationSettings/index.tsx
Quite simply use replace `APP_NAVIGATION_LOGO_UPLOAD` flag on FF4J to `release_appnavigationlogoupload_enabled` on Flagsmith.
Fixes #25184
>
> Please describe the tests that you ran to verify your changes. Also, list any relevant details for your test configuration.
>
>
>
>
>
>
>
=> chore: Move app navigation logo upload to Flagsmith

app/client/packages/design-system/theming/src/color/DarkModeTheme.ts, app/client/packages/design-system/theming/src/color/LightModeTheme.ts
tl;dr Accessible readable foregrounds on semantic backgrounds
Fixes #25018 
- Manual
=> feat: WDS algorithmic colors `fgOn*`

app/client/cypress/e2e/Regression/ClientSide/Autocomplete/BracketNotation_AC_spec.ts, app/client/cypress/limited-tests.txt, app/client/cypress/support/Objects/CommonLocators.ts
=> test: Cypress - Flaky fix BracketNotation_AC_spec.ts

app/client/packages/design-system/theming/src/color/DarkModeTheme.ts, app/client/packages/design-system/theming/src/color/LightModeTheme.ts
=> chore: WDS simpler semantic hovers

app/client/cypress/support/Objects/CommonLocators.ts, app/client/cypress/support/Pages/DeployModeHelper.ts
=> chore: Update cypress locators for ME

app/client/src/ce/constants/messages.ts, app/client/src/pages/Editor/DataSourceEditor/index.tsx
>
>
>
>
>
>
Fixes #25626 
>
>
>
>
- Bug fix (non-breaking …
=> chore: Remove environment name from the banner

app/client/src/sagas/ErrorSagas.tsx
The error passed to `Sentry.captureException ` was not an exception-like object.
Fixes https://github.com/appsmithorg/appsmith/issues/25397(https://github.com/appsmithorg/appsmith/issues/25397)
>
>
>
>
>
>
>
>
=> fix: throw exception-like object to sentry

app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/PluginTypeAndCountDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepository.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepositoryImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/BaseAppsmithRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomThemeRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewPageServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewPageServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCEImplTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/NewPageServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/NewActionServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/NewActionServiceUnitTest.java
This PR adds some refactoring to improve the time taken to publish an application. 
Fixes #24648
>
>
>
>
>
=> chore: Improve time to publish application

app/client/cypress/support/Pages/DataSources.ts, app/client/cypress/support/Pages/DeployModeHelper.ts, app/client/src/ce/utils/Environments/index.tsx, app/client/src/pages/Editor/DataSourceEditor/index.tsx, app/client/src/pages/Editor/GeneratePage/components/GeneratePageForm/GeneratePageForm.tsx, app/client/src/pages/Editor/GeneratePage/components/GeneratePageForm/hooks.ts, app/client/src/pages/Editor/IntegrationEditor/DatasourceCard.tsx, app/client/src/utils/editorContextUtils.ts
Fixes for issues found during ME regression
Fixes #25640 
Fixes #25653
=> fix: multiple env issues

app/client/packages/design-system/theming/src/color/DarkModeTheme.ts, app/client/packages/design-system/theming/src/color/LightModeTheme.ts
=> feat: WDS programmatic focus color

app/client/cypress/support/Pages/HomePage.ts
updated common method to handle CE/ EE scenario for ShareApp
=> test: cypress -udpated common method to handle CE/EE scenario

app/client/cypress/e2e/Regression/ClientSide/Widgets/ListV2/ListV2_nested_List_widget_spec.js
fix for flaky behaviour for listv2_nested spec
=> test: Added a fix for flaky failure

app/client/packages/design-system/theming/src/color/DarkModeTheme.ts, app/client/packages/design-system/theming/src/color/LightModeTheme.ts, app/client/packages/design-system/widgets/src/components/Button/Button.stories.mdx, app/client/packages/design-system/widgets/src/components/Button/Button.tsx, app/client/packages/design-system/widgets/src/components/ButtonGroup/ButtonGroup.stories.mdx, app/client/packages/design-system/widgets/src/components/ButtonGroup/index.styled.tsx
The first part of ButtonGroup component fixes. #25500 
- Add stubs for *bdOn* tokens
- Add borders for ButtonGroup component
- Add stories fixes
=> fix: add *bdOn* tokens and  add borders for buttonGroup

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceStorageServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java
=> chore: Added check for non-existent storage while importing and exporting

app/client/packages/design-system/theming/src/color/DarkModeTheme.ts, app/client/packages/design-system/theming/src/color/LightModeTheme.ts
=> feat: WDS colors `bdOn*`

app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/UserSessionDTO.java
> This PR fixes the NPE for anonymous user in userSessionDTO 
Fixes #25753 
>
>
>
>
>
>
>
>
>
>
>
>
>
=> fix: createdAt npe fixed

app/client/cypress/support/Pages/DataSources.ts, app/client/src/pages/Editor/DataSourceEditor/DBForm.tsx
Added code split for cypress test cases in EE
Fixes #1838 (EE)
=> chore: code split for me cypress

app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
Added error logs for the FileUtils flows.
=> chore: Add file error logs

.github/workflows/ci-test-hosted.yml
- Workflow fix for scheduled run for gsheet tests
- Workflow changes
>
- Workflow run
=> ci: Workflow fix for scheduled run for gsheet tests

.github/workflows/ci-test-hosted.yml
-  Fix workflow commit message for scheduled hosted workflow
- Workflow changes
>
- Workflow run
=> ci: Fix workflow commit message for scheduled hosted workflow

app/client/src/sagas/ActionExecution/PluginActionSaga.ts
This PR adds the number of params to EXECUTE_ACTION analytics event log
Fixes #25726 
>
>
>
>
>
>
>
>
> Add Testsmith test cases …
=> chore: Add number of params to logs

app/client/src/api/ApiResponses.tsx
- This PR removes commented out lines that are not useful anymore. I have verified with Abhinav and Hetu that these lines can be removed now. 
Fixes #25780 
>
>
>
- Does not apply.
>
>
>
>
>
=> chore: remove commented out lines

app/client/src/utils/widgetRenderUtils.test.ts, app/client/src/utils/widgetRenderUtils.tsx, app/client/src/widgets/BaseWidget.tsx
=> chore: Add property path to WidgetErrors

app/client/cypress/e2e/Regression/ClientSide/Widgets/Chart/ChartWidgetErrors_spec.ts, app/client/src/widgets/ChartWidget/component/ChartErrorComponent.tsx, app/client/src/widgets/ChartWidget/component/EChartsConfigurationBuilder.test.ts, app/client/src/widgets/ChartWidget/component/EChartsConfigurationBuilder.ts, app/client/src/widgets/ChartWidget/component/EChartsDatasetBuilder.test.ts, app/client/src/widgets/ChartWidget/component/EChartsDatasetBuilder.ts, app/client/src/widgets/ChartWidget/component/EmptyChartData.tsx, app/client/src/widgets/ChartWidget/component/index.test.tsx, app/client/src/widgets/ChartWidget/component/index.tsx, app/client/src/widgets/ChartWidget/constants.ts, app/client/src/widgets/ChartWidget/index.ts, app/client/src/widgets/ChartWidget/widget/SyntaxErrorsEvaluation.test.ts, app/client/src/widgets/ChartWidget/widget/SyntaxErrorsEvaluation.ts, app/client/src/widgets/ChartWidget/widget/index.test.ts, app/client/src/widgets/ChartWidget/widget/index.tsx
This PR fixes QA callouts in ECharts
=> chore: Fix EChart bugs

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration004PermissionGroupDefaultWorkspaceIdMigration.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration005CreateIndexForApplicationSnapshotMigration.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration006ResetOnPageLoadEdgesInLayouts.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration007OptOutUnsupportedPluginsForAirGap.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration008SupportNonHostedPluginsForAirgap.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration009UpdateOracleLogoToSVG.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration010UpdatePluginDocsLink.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration011CreateIndexDefaultDomainIdDefaultDomainTypeDropIndexDefaultWorkspaceId.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration012RemoveStructureFromWithinDatasource.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration013AddEmailBodyTypeToSMTPPlugin.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration014AddIndexToDatasourceStorage.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration015AddPluginTypeIndexToNewActionCollection.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration016RenameIndexesWithLongNames.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration017UnsetEncryptionVersion2Fields.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration018UpdateOraclePluginDocumentationLink.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration019RemoveNullEnvIdDatasourceStructureDocuments.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration020TransferToDatasourceStorage.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration021MoveGoogleMapsKeyToTenantConfiguration.java
Contains same changes as https://github.com/appsmithorg/appsmith-ee/pull/1764
Fixes #25608
=> chore: Renamed migrations to allow consistency and interleaving

.github/workflows/on-demand-build-docker-image-deploy-preview.yml
Non-impacting change, only adds some more content to the DP URL comment.
More context around this at https://notion.so/031b87bce3404e3a95240d4c14c82e46.
=> ci: Add a note about Vercel DPs with env=release

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/RedisConfig.java
This fixes a problem with connecting to Redis that require authentication.
This is a regression introduced in #24924.
Fixes #25259
=> fix: Fix Redis connections that require authentication

app/server/appsmith-server/src/main/resources/productAlerts/productAlertMessages.json
> Cloud maintainence message needed a time to be added.
Fixes #25610
>
>
>
> Will be tested on release
=> chore: Corrected maintenance alert message for cloud users

deploy/helm/templates/configMap.yaml, deploy/helm/templates/statefulset.yaml
Fixes: [25688](https://github.com/appsmithorg/appsmith/issues/25688)
=> fix: redis-url when deploying appsmith via helm

app/client/cypress/e2e/Regression/Apps/CommunityIssues_Spec.ts, app/client/cypress/e2e/Regression/Apps/MongoDBShoppingCart_spec.ts, app/client/cypress/e2e/Regression/ClientSide/IDE/MaintainContext&Focus_spec.js, app/client/cypress/e2e/Regression/ClientSide/VisualTests/AppPageLayout_spec.js, app/client/cypress/e2e/Regression/ClientSide/VisualTests/DatasourcePageLayout_spec.js, app/client/cypress/e2e/Regression/ClientSide/VisualTests/JSEditorComment_spec.js, app/client/cypress/e2e/Regression/ClientSide/VisualTests/JSEditorIndent_spec.js, app/client/cypress/e2e/Regression/ClientSide/VisualTests/JSEditorSaveAndAutoIndent_spec.js, app/client/cypress/e2e/Regression/ClientSide/VisualTests/WidgetsLayout_spec.js, app/client/cypress/e2e/Regression/ServerSide/GenerateCRUD/MongoURI_Spec.ts, app/client/cypress/e2e/Regression/ServerSide/QueryPane/Mongo_Spec.js, app/client/cypress/limited-tests.txt, app/client/cypress/support/Objects/CommonLocators.ts, app/client/cypress/support/Pages/DeployModeHelper.ts, app/client/cypress/support/Pages/EntityExplorer.ts, app/client/cypress/support/Pages/PropertyPane.ts
- This PR is adding new scripts for Mongo URI CRUD validations
- Add/Update/Delete from CRud page
- Search table
- FIlter table
- Download results
- Suggested widget from a mongo uri query
- Apps/CommunityIssues_Spec.ts - 5th fix
>
-
=> test: Cypress | Automated cases for MongoURI CRUD

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ActionExecutionSolutionCEImpl.java
> replaced wrongly assigned value for environmentName in actionExecution analytics
=> fix: fixed typo analytics constant

app/client/cypress/e2e/Sanity/Datasources/Airtable_Basic_Spec.ts
- This PR unskips Airtable spec - which is flaky in CI
- 
- ## Testing
>
=> test: Cypress | Unskip Airtable spec

app/server/pom.xml
Fixes https://github.com/appsmithorg/appsmith-ee/issues/1968
=> fix: Update spring-security-config for CVE-2023-34034

app/client/cypress/e2e/Regression/ClientSide/BugTests/InputTruncateCheck_Spec.ts
Temporary. Working on adding it back. 
Fix to unblock release https://theappsmith.slack.com/archives/CGBPVEJ5C/p1690912343959049
=> chore: skip interaction with explorer in input truncate test

scripts/local_testing.sh
Slack thread with details: https://theappsmith.slack.com/archives/CGBPVEJ5C/p1690917878540839?thread_ts=1690866395.690119&cid=CGBPVEJ5C
=> chore: Add support for custom CS URL in local_testing.sh script

app/client/src/utils/autocomplete/CodemirrorTernService.ts
=> chore: Add JSLibrary autocomplete analytics

app/client/packages/design-system/theming/src/color/ColorsAccessor.ts, app/client/packages/design-system/theming/src/color/DarkModeTheme.ts, app/client/packages/design-system/theming/src/color/LightModeTheme.ts, app/client/packages/design-system/theming/src/color/types.ts
=> chore: WDS color cleanup

app/server/appsmith-interfaces/pom.xml, app/server/appsmith-server/pom.xml
1. CVE-2023-3635 at https://github.com/appsmithorg/appsmith/security/dependabot/251.
2. CVE-2023-2976 at https://github.com/appsmithorg/appsmith/security/dependabot/235.
=> fix: Update dependencies to bring fixes for CVEs

app/client/src/ce/constants/messages.ts
> Update toast message CTA for environment switch action
>
>
>
Fixes #25924 
>
>
>
>
>
>
>
>
>
>
>
=> chore: Update environment switch toast text

app/client/src/widgets/ChartWidget/component/ChartErrorComponent.tsx, app/client/src/widgets/ChartWidget/component/index.tsx
=> fix: Skip echarts rerendering if props are same

app/client/src/widgets/ChartWidget/component/EChartsConfigurationBuilder.test.ts, app/client/src/widgets/ChartWidget/component/EChartsConfigurationBuilder.ts, app/client/src/widgets/ChartWidget/constants.ts
=> fix: Fix/chart widget use undefined series name if empty

app/client/src/ce/pages/UserAuth/SignUp.tsx, app/client/src/utils/AnalyticsUtil.tsx
Send referrer analytics on landing on signup page
Fixes https://github.com/appsmithorg/appsmith/issues/25677
=> chore: send referrer analytics on landing on signup page

app/client/src/sagas/InitSagas.ts
Contains the changes to wait for 20s for the service worker to become ready before dispatching the registration failed event
>
>
>
>
>
=> chore: Modified sw analtyics tracker

app/server/appsmith-git/src/main/java/com/appsmith/git/service/GitExecutorImpl.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/git/GitExecutor.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/GitControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/ce/UncommittedChangesDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/GitServiceCEImplTest.java
This PR brings those changes:
1. Creates a new API to know whether there are any uncommitted changes or not
2. Creates a new API to compare the local branch with remote
3. Adds an optional parameter to the status API so that we can skip the git fetch
Fixes #24340
>
>
>
>
>
>
=> feat: Create lightweight status api

app/client/packages/design-system/widgets/src/components/Button/Button.tsx, app/client/packages/design-system/widgets/src/components/Button/index.styled.tsx
=> fix: Loading state changes button width 

.github/workflows/cleanup-dp.yml, .github/workflows/on-demand-build-docker-image-deploy-preview.yml, scripts/cleanup_dp.sh, scripts/deploy_preview.sh
This reverts commit 6762d2ce9043072b428a108b6cb149ff6d18cb02.
=> Revert "update: migrate dp from sts to deployments (#25615)"

app/client/cypress/e2e/Regression/ClientSide/BugTests/DatasourceSchema_spec.ts, app/client/cypress/e2e/Regression/ClientSide/Widgets/ListV2/Event_Bindings_spec.ts, app/client/cypress/support/Pages/DataSources.ts
- This pR improves FilterAndVerifyDatasourceSchemaBySearch() method
- Alters locator for _datasourceTableSchemaInQueryEditor to narrow down the search result
- Hence fixing /BugTests/DatasourceSchema_spec.ts() causing chrome crash in CI runs
- Fixes ListV2/Event_Bindings_spec.ts
>
=> test: Cypress | CI Stabilize

README.md
Added UTM codes to 
- Doc Tutorial 
- Cloud signup link
- Discord
=> Fix: Added utm codes to readme links

app/client/src/widgets/ChartWidget/widget/propertyConfig.test.ts, app/client/src/widgets/ChartWidget/widget/propertyConfig.ts
=> fix: Make dataSource required true for customFusionChartConfig

app/client/src/widgets/DocumentViewerWidget/component/ExcelDataParser.test.ts, app/client/src/widgets/DocumentViewerWidget/component/ExcelDataParser.ts, app/client/src/widgets/DocumentViewerWidget/component/XlsxViewer.tsx
=> Document Viewer Widget : Parse maximum number of headers present in excel file raw data

.github/workflows/build-chromatic.yml, .github/workflows/build-storybook.yml, app/client/packages/storybook/stories/design-system/widgets/Switch.stories.mdx, app/client/packages/storybook/stories/design-system/widgets/SwitchGroup.stories.mdx
=> chore: clean up switch stories

app/client/yarn.lock
Should resolve https://github.com/appsmithorg/appsmith/security/dependabot/241.
=> chore(deps): Update tough-cookie

CODEOWNERS
This PR adds @rajatagrawal to reviews for cypress tests for app viewers code.
The purpose is to review cypress test code and explore possibilities to convert into UI Unit Tests using React Testing Library if possible.
=> chore: Add Rajat to codeowners for app viewers cypress tests code review

app/client/packages/design-system/widgets/src/components/ButtonGroup/index.styled.tsx, app/client/packages/storybook/stories/design-system/widgets/Switch.stories.mdx, app/client/packages/storybook/stories/design-system/widgets/testing/ComplexForm.tsx
Add components to complex form
=> chore: add components to complex form

app/client/cypress/e2e/Regression/ServerSide/LoginTests/LoginFailure_spec.js
- This PR skips ServerSide/LoginTests/LoginFailure_spec.js tp unblock CI until script issue fixed
=> test: Cypress | Skipping spec to unblock CI

app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/FeatureFlagServiceCETest.java
> This PR moves the feature flagging tests to ce folder. 
Fixes #26198 
>
>
>
>
>
>
>
>
>
>
=> chore: moved feature flagging ce tests to ce folder

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/MigrationHelperMethods.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/FeatureFlagServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/FeatureFlagServiceCEImpl.java
PR to add force update to tenant level feature flags which will be used in situations where we don't want to wait for scheduled job to run. 
e.g. When license is updated we want to fetch the latest flags to enable the features as per the license plan.
>
>
>
>
- Chore (housekeeping or task changes that …
=> chore: Add force update method to fetch latest tenant level feature flags

app/client/src/widgets/ChartWidget/widget/index.test.ts, app/client/src/widgets/ChartWidget/widget/index.tsx
=> hotfix: Add an optional data check around series data

app/client/cypress/e2e/Regression/ClientSide/BugTests/Bug25982_Spec.ts, app/client/src/components/formControls/DropDownControl.tsx, app/client/src/widgets/ChartWidget/widget/index.test.ts, app/client/src/widgets/ChartWidget/widget/index.tsx
Hot fix changes
>
>
>
>
>
>
>
>
>
>
> Link issues raised during DP …
=> fix: HotFix (#26167) and (#26207)

app/client/src/api/OAuthApi.ts, app/client/src/ce/api/ApiUtils.ts, app/client/src/entities/Datasource/index.ts, app/client/src/pages/common/datasourceAuth/index.tsx, app/client/src/sagas/DatasourcesSagas.ts, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/DatasourceControllerCE.java
> User was not able to configure Staging to connect to Dropbox with OAuth2.0.
> Server was not able to access current editing environment to save and authorise the DS. 
> We have update the `/code` endpoint to include current editing environment. This will help server to access the required environment.
Fixes #26113 
>
>
>
>
>
>
>
>
>
>
> Link issues raised during DP testing for better visiblity …
=> fix: Save and authorise flow in current editing environment

app/client/packages/design-system/theming/src/typography/types.ts, app/client/packages/design-system/theming/src/typography/typography.ts, app/client/packages/design-system/widgets/src/components/Button/Button.tsx, app/client/packages/design-system/widgets/src/components/Button/index.styled.tsx, app/client/packages/design-system/widgets/src/components/Text/Text.tsx, app/client/packages/design-system/widgets/src/components/Text/index.styled.tsx, app/client/packages/design-system/widgets/src/components/Text/types.ts, app/client/packages/storybook/chromatic/design-system/widgets/Text.chromatic.stories.tsx, app/client/packages/storybook/stories/design-system/widgets/Text.stories.mdx
=> fix: fix button font weight

app/client/src/ce/api/ApiUtils.ts, app/client/src/entities/Datasource/index.ts, app/client/src/pages/common/datasourceAuth/index.tsx, app/client/src/sagas/DatasourcesSagas.ts, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/DatasourceControllerCE.java
=> fix: save and authorise flow hotfix

CODEOWNERS
> 
> Added both client side and server side paths that usually Data Platform works on. The paths mentioned here would automatically add the respect users on each entry as reviewers. 
> 
> 
>
> 
>
>
Fixes #26068 
> 
>
>
> 
>
>
> 
>
>
>
>
>
>
>
>
>
>
>
>
=> ci: Update Codeowners with data platform paths

app/client/cypress/e2e/Regression/ClientSide/Widgets/Sliders/CategorySlider_spec.ts, app/client/cypress/e2e/Regression/ClientSide/Widgets/Sliders/NumberSlider_spec.ts, app/client/cypress/e2e/Regression/ClientSide/Widgets/Sliders/RangeSlider_spec.ts, app/client/cypress/support/Pages/AggregateHelper.ts, app/client/cypress/support/Pages/PropertyPane.ts
Range slider tests added, based on the tests that were not covered in below link
https://github.com/appsmithorg/TestSmith/issues/2066
https://github.com/appsmithorg/TestSmith/issues/2064
https://github.com/appsmithorg/TestSmith/issues/2061
=> test: cypress- Test/slider reg new

app/server/appsmith-server/src/main/resources/productAlerts/productAlertMessages.json
> The message for 6 Aug downtime of appsmith cloud has been removed in this pr.
Fixes #26270
>
>
>
> Can be tested by creating pr image and running it with isCloudHosting true flag and the downtime message should not show up.
=> chore: removed aug 6 downtime message

app/server/appsmith-server/src/main/resources/productAlerts/productAlertMessages.json
> CE repo pr to cherry pick changes for issue: https://github.com/appsmithorg/appsmith/pull/26296
Fixes #26296
=> chore: removed aug 6 downtime message (#26296)

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/SecurityConfig.java
Only allows authenticated access to actuator APIs moving forward.
Fixes #26310 
=> chore: Remove unauthenticated access to actuator APIs

app/client/src/constants/WidgetConstants.tsx, app/client/src/utils/DSLMigration.test.ts, app/client/src/utils/DSLMigrations.ts, app/client/src/utils/migrations/ChartWidget.test.ts, app/client/src/utils/migrations/ChartWidget.ts, app/client/src/widgets/ChartWidget/component/EChartsConfigurationBuilder.test.ts, app/client/src/widgets/ChartWidget/component/EChartsConfigurationBuilder.ts, app/client/src/widgets/ChartWidget/component/EChartsDatasetBuilder.test.ts, app/client/src/widgets/ChartWidget/component/index.test.tsx, app/client/src/widgets/ChartWidget/component/index.tsx, app/client/src/widgets/ChartWidget/index.ts, app/client/src/widgets/ChartWidget/widget/SyntaxErrorsEvaluation.test.ts, app/client/src/widgets/ChartWidget/widget/index.test.ts, app/client/src/widgets/ChartWidget/widget/index.tsx, app/client/src/widgets/ChartWidget/widget/propertyConfig.test.ts, app/client/src/widgets/ChartWidget/widget/propertyConfig.ts
=> fix: Add migration to show/hide data point labels on charts

app/client/src/ce/constants/messages.ts, app/client/src/pages/Editor/EditorHeader.tsx, app/client/src/pages/Templates/CommunityTemplates/Modals/CommunityTemplatesPublish.tsx, app/client/src/pages/Templates/CommunityTemplates/Modals/ConfirmCommunityTemplatePublish.tsx
Adds 3 modals required for community template.
Fixes #26344
>
>
>
>
>
>
>
>
> …
=> feat: Modal chanegs for Community templates

app/client/src/entities/Widget/utils.test.ts, app/client/src/widgets/ChartWidget/widget/index.test.ts, app/client/src/widgets/ChartWidget/widget/propertyConfig.test.ts, app/client/src/widgets/ChartWidget/widget/propertyConfig.ts
=> fix: Fix chart dataset crash

app/client/package.json
>
>
Adding/Increasing limit coz local setup fails to be usable without it.
>
>
>
>
- …
=> fix: Adding maximum limit coz of local dev setup JS heap issues

app/client/packages/design-system/widgets/src/components/Flex/Flex.tsx, app/client/packages/design-system/widgets/src/components/Flex/types.ts
Added `id` and `ref` properties to Flex component
=> chore: Add id & ref to Flex component

app/server/appsmith-git/src/test/java/com/appsmith/git/helpers/DSLTransformHelperTest.java, app/server/appsmith-git/src/test/resources/DSLWidget/AllWidgetsDSL.json, app/server/appsmith-git/src/test/resources/DSLWidget/TabWidgetNestedChildren.json
Improve the coverage for Widgets in Junit
Fixes #25589
=> test: canvas widget coverage junit

app/client/package.json, app/client/src/entities/DependencyMap/index.ts, app/client/yarn.lock
Previously, dependencyMap.addNode() had a O(n^2) complexity. 
Fixes https://github.com/appsmithorg/appsmith/issues/26400
>
>
>
>
>
> …
=> fix: improve performance of updateDependency flow

app/client/package.json, app/client/src/entities/DependencyMap/index.ts, app/client/yarn.lock
Previously, dependencyMap.addNode() had a O(n^2) complexity. 
Fixes https://github.com/appsmithorg/appsmith/issues/26400
> A video or a GIF is preferred. when using Loom, don’t embed because it
looks like it’s a GIF. instead, just link to the video
>
>
functionality to not work as expected)
>
>
>
>
> Please describe the tests that you ran to verify your changes. Also
list any relevant details for your test configuration. …
=> fix: improve performance of updateDependency flow (#26391)

CODEOWNERS
Adding CODEOWNERS file for Admin settings client-side files
=> chore: Adding CODEOWNERS file for Admin settings client-side files

app/client/cypress/e2e/Regression/ClientSide/Widgets/Chart/ChartDataPoint_Spec.ts, app/client/cypress/locators/Widgets.json, app/client/src/widgets/ChartWidget/component/EChartsConfigurationBuilder.test.ts, app/client/src/widgets/ChartWidget/component/EChartsConfigurationBuilder.ts, app/client/src/widgets/ChartWidget/component/LayoutBuilders/EChartsElementVisibilityCalculator.test.ts, app/client/src/widgets/ChartWidget/component/LayoutBuilders/EChartsElementVisibilityCalculator.ts, app/client/src/widgets/ChartWidget/component/LayoutBuilders/EChartsLayoutBuilder.test.ts, app/client/src/widgets/ChartWidget/component/LayoutBuilders/EChartsLayoutBuilder.ts, app/client/src/widgets/ChartWidget/component/LayoutBuilders/EChartsXAxisLayoutBuilder.test.ts, app/client/src/widgets/ChartWidget/component/LayoutBuilders/EChartsXAxisLayoutBuilder.ts, app/client/src/widgets/ChartWidget/component/LayoutBuilders/EChartsYAxisLayoutBuilder.test.ts, app/client/src/widgets/ChartWidget/component/LayoutBuilders/EChartsYAxisLayoutBuilder.ts, app/client/src/widgets/ChartWidget/component/index.test.tsx
=> fix: Add a charts layout builder to progressively hide chart elements

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/DatasourceAnalyticsUtils.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ActionExecutionSolutionCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/DatasourceAnalyticsUtilsTest.java
> Added test case for ensuring right environmentName and environmentId in mixpanel
Fixes https://github.com/appsmithorg/appsmith/issues/25872
=> chore: added test case for envName and envId

app/client/cypress/e2e/Regression/ClientSide/OneClickBinding/MultiSelectWidget/postgres_spec.ts, app/client/cypress/limited-tests.txt, app/client/cypress/locators/FormWidgets.json
=> ci: Fix flaky test - MultiSelectWidget/postgres_spec.ts

app/client/cypress/e2e/Regression/ClientSide/AdminSettings/General_settings_Spec.ts, app/client/cypress/e2e/Regression/ClientSide/EmbedSettings/EmbedSettings_spec.js, app/client/cypress/limited-tests.txt, app/client/cypress/support/AdminSettingsCommands.js, app/client/cypress/support/Pages/AggregateHelper.ts
=> chore: Adding custom delay parameter in TypeText aggregate helper

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/SecurityConfig.java
This change makes sure that an authenticated user is also not allowed to access internal endpoints.
=> chore: Disallow authenticated users from accessing internally controlled endpoints

app/client/src/ce/pages/AdminSettings/config/authentication/AuthPage.tsx, app/client/src/ce/pages/AdminSettings/config/branding/UpgradeBanner.tsx, app/client/src/ce/pages/Upgrade/AccessControlUpgradePage.tsx, app/client/src/ce/pages/Upgrade/AuditLogsUpgradePage.tsx, app/client/src/ce/pages/Upgrade/ProvisioningUpgradePage.tsx, app/client/src/constants/ThirdPartyConstants.tsx, app/client/src/utils/ProductRamps/RampsControlList.ts, app/client/src/utils/hooks/useOnUpgrade.ts
Added query params for ramps on admin settings page
1. Branding (branding)
2. SSO (sso)
3. GAC (gac)
4. Provisioning (provisioning)
5. Audit Logs (audit_logs)
>
>
Fixes # https://github.com/appsmithorg/cloud-services/issues/981
>
>
>
>
>
>
>
>
>
>
>
>
>
=> chore: added query params for ramps on admin settings page

app/client/cypress/e2e/Regression/ClientSide/Widgets/Container_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV1/Table_Button_Icon_validation_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV1/Table_Color_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV1/Table_Widget_Add_button_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_Button_Icon_validation_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_Color_spec.js, app/client/cypress/support/commands.js, app/client/src/components/propertyControls/ColorPickerComponentV2.tsx, app/client/src/utils/helpers.tsx
Fix color picker validation for empty state
Fixes #26394
>
>
>
>
>
>
>
>
=> fix: color picker validation for empty state

app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java
This PR extends the` /{datasourceId}/schema-preview` API for MySQL plugin as well
As per [designs](https://www.figma.com/file/kbU9xPv44neCfv1FFo9Ndu/User-Activation?type=design&node-id=1357-102198&mode=design&t=gISZ9qFQkK356kAw-4) We want to show the MySQL schema as well as preview on the datasource review page.
JUnit tests are not added as the feature is experimental, If we finalise on the feature in future, we should add JUnit tests, tracking here https://github.com/appsmithorg/appsmith/issues/26582
Fixes #26574 
>
>
>
>
- Bug fix …
=> feat: preview data api extended for mysql

app/client/public/index.html, app/client/src/pages/Editor/index.tsx
Google sheet file picker library should not be loaded for airgapped instance. This PR ensures that.
Fixes #26282 
>
>
>
>
>
>
>
>
=> feat: Disable gsheets api load for airgapped instance

app/client/package.json, app/client/yarn.lock
Bump ADS version. This release contains -
- feat: add affordance to link
- feat: revert tag and release only special and premium tags
- feat: add popover
- fix: change collapsible toggle arrow directions from up/down to down/right
- feat: documentation updates for popover, collapsible, number input, callout, spinner + documentation template for new components
- feat: Added toggle new size variant "lg"
>
>
>
>
- New feature (non-breaking change which adds …
=> chore: bump ADS version to 2.1.19

app/client/cypress/e2e/Regression/ClientSide/BugTests/Bugs26410_spec.ts
This PR excludes Bug26410 test for airgapped instances
>
>
>
>
>
>
>
>
> …
=> fix: This PR excludes Bug26410 test for airgapped instances

app/client/cypress/e2e/Regression/ClientSide/Widgets/Chart/ChartDataPoint_Spec.ts, app/client/src/widgets/ChartWidget/component/helpers.test.ts, app/client/src/widgets/ChartWidget/component/helpers.ts, app/client/src/widgets/ChartWidget/component/index.tsx
=> chore: Add support for custom echarts in chart datapoint click callback

app/client/cypress/e2e/Regression/ClientSide/Widgets/Text/Text_new_feature_spec.js
Fixes flaky test Text_new_feature_spec.js
=> test: fix flaky test Text_new_feature_spec.js

CODEOWNERS
Updating file paths in CODEOWNERS file
=> chore: Updating file paths in CODEOWNERS file

app/client/cypress/e2e/Regression/ClientSide/Widgets/Audio/Audio_spec.ts
This PR excludes test for Airgap 
>
>
>
>
>
>
>
>
> Delete …
=> test: Cypress - exclude test for Airgap

app/server/appsmith-server/src/main/java/com/appsmith/server/annotations/FeatureFlagged.java, app/server/appsmith-server/src/main/java/com/appsmith/server/aspect/FeatureFlaggedMethodInvokerAspect.java, app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java, app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithErrorCode.java
Details are provided in corresponding EE PR.
https://github.com/appsmithorg/appsmith-ee/pull/2076
=> feat: Add base structure for `@FeatureFlagged`

.github/workflows/integration-tests-command.yml
Migrate PR workflow to Dime defenders
=> ci : Migrate PR workflow to Dime defenders

app/client/src/pages/Editor/DataSourceEditor/DBForm.tsx
Changed callouts type from `warning` to `info` for the message asking user to whitelist couple of IPs on their datasource instance.
Earlier :
Now :
Fixes #26737
>
>
>
>
>
> …
=> fix: callouts changed from warning to info for db datasources

app/client/cypress/e2e/Regression/ClientSide/Widgets/Chart/ChartDataPoint_Spec.ts, app/client/cypress/e2e/Regression/ClientSide/Widgets/Chart/Custom_Chart_Data_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/Chart/Custom_Chart_spec.js, app/client/cypress/fixtures/chartUpdatedDsl.json, app/client/src/ce/entities/FeatureFlag.ts, app/client/src/constants/WidgetConstants.tsx, app/client/src/entities/Widget/utils.test.ts, app/client/src/pages/Editor/PropertyPane/PropertyPaneView.tsx, app/client/src/pages/Editor/PropertyPane/helpers.tsx, app/client/src/selectors/propertyPaneSelectors.tsx, app/client/src/utils/DSLMigration.test.ts, app/client/src/utils/DSLMigrations.ts, app/client/src/utils/migrations/ChartWidget.test.ts, app/client/src/utils/migrations/ChartWidget.ts, app/client/src/widgets/ChartWidget/component/EChartsConfigurationBuilder.test.ts, app/client/src/widgets/ChartWidget/component/EChartsDatasetBuilder.test.ts, app/client/src/widgets/ChartWidget/component/EChartsDatasetBuilder.ts, app/client/src/widgets/ChartWidget/component/helpers.test.ts, app/client/src/widgets/ChartWidget/component/helpers.ts, app/client/src/widgets/ChartWidget/component/index.test.tsx, app/client/src/widgets/ChartWidget/component/index.tsx, app/client/src/widgets/ChartWidget/constants.ts, app/client/src/widgets/ChartWidget/index.ts, app/client/src/widgets/ChartWidget/widget/SyntaxErrorsEvaluation.test.ts, app/client/src/widgets/ChartWidget/widget/SyntaxErrorsEvaluation.ts, app/client/src/widgets/ChartWidget/widget/index.test.ts, app/client/src/widgets/ChartWidget/widget/index.tsx, app/client/src/widgets/ChartWidget/widget/propertyConfig.test.ts, app/client/src/widgets/ChartWidget/widget/propertyConfig.ts, app/client/src/widgets/constants.ts
Fixes #24424
Fixes #26009
Fixes #25564
Fixes #26545
Fixes #26584
=> feat: ECharts Phase 2 - Custom ECharts

deploy/docker/scripts/run-java.sh
Better details when a `NullPointerException` occurs.
Ref: https://www.baeldung.com/java-14-nullpointerexception.
=> chore: Add `-XX:+ShowCodeDetailsInExceptionMessages` to backend

Dockerfile
⚠️ **This will cause conflicts.**
=> chore(deps): Update certbot from v0.40 to v2.6

app/client/src/pages/Editor/ToggleModeButton.tsx
Use toggle button
Fixes https://github.com/appsmithorg/appsmith/issues/24097
https://github.com/appsmithorg/appsmith/assets/67054171/f55a2eab-f624-490a-a395-da413ac882aa
>
>
>
>
>
>
>
>
=> chore: update preview button to make use of toggle

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitFileUtils.java, app/server/appsmith-server/src/main/resources/application.properties
Update the stale file lock time to 300 seconds.
=> chore: update stale lock time

app/client/cypress_ci_custom.config.ts
=> chore: airtable spec skip

CODEOWNERS
Added myself as owner to be notified ant changes in evaluation flow
>
>
>
>
>
>
>
>
> Please describe the tests that you ran to verify your changes. Also list any relevant details for …
=> chore: added myself as owner to be notified for any change

app/client/src/sagas/PostEvaluationSagas.ts, app/client/src/workers/common/DataTreeEvaluator/index.ts, app/client/src/workers/common/DependencyMap/index.ts
This PR ensures that only potential system-generated cyclic dependency errors are logged on sentry.
Fixes #25687
>
>
>
>
>
>
>
> …
=> chore: Log only potential system generated cyclic dependency errors to sentry

app/client/cypress/e2e/Regression/ClientSide/Widgets/Datepicker/DatePicker3_spec.ts
=> test: Cypress - date picker added after each to navigate to editor

app/client/packages/design-system/theming/src/color/src/LightModeTheme.ts, app/client/packages/design-system/theming/src/color/tests/DarkModeTheme.test.ts, app/client/packages/design-system/theming/src/color/tests/LightModeTheme.test.ts
=> chore: unit test for bgAccentActive

app/client/packages/design-system/theming/src/color/src/LightModeTheme.ts, app/client/packages/design-system/theming/src/color/tests/DarkModeTheme.test.ts, app/client/packages/design-system/theming/src/color/tests/LightModeTheme.test.ts
=> chore: add unit tests for bgAccentSubtle

app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/GitServiceCETest.java
PR to code split git service testcases. On EE need to test following functionality:
1. If the server is Appsmith cloud
2. For self hosted instances if the feature flag is enabled, does the check for private repo limit getting bypassed correctly
=> chore: Code split testcases for git service

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/plugins/PluginExecutor.java, app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java, app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java, app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourceStructureSolutionCEImpl.java
This PR extends `/schema-preview` API for movies mock mongo DB. For this experiment we will need to show schema along with preview of movies mongo DB on the review page. This feature is currently implemented only for mock mongo DB, if the experiment turns out to be a success, this will be further extended for non mock mongo datasources as well.
More info on Activation experiments can be found [here](https://www.notion.so/appsmith/User-Activation-Experiments-cecdd8af23ac4286968096da4a4fdc99)
Fixes #26936
>
>
>
>
>
>
>
> …
=> feat: schema preview API extended for movies mock DB

app/client/src/pages/Editor/PropertyPane/PropertyPaneView.tsx
Fixes https://github.com/appsmithorg/appsmith/issues/27032
=> fix: fix walkthrough component crashing for invalid selector

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
Fix sentry issue - https://appsmith.sentry.io/issues/4432979167/?alert_rule_id=14445463&alert_timestamp=1693292152222&alert_type=email&environment=Production&project=4505267188465664&referrer=alert_email
=> chore: add null check for repo name

app/server/appsmith-interfaces/pom.xml, app/server/appsmith-plugins/pom.xml, app/server/appsmith-server/pom.xml, app/server/pom.xml, app/server/reactive-caching/pom.xml
This includes fixes for the following High-severity Dependabot alerts:
1. https://github.com/appsmithorg/appsmith/security/dependabot/256
2. https://github.com/appsmithorg/appsmith/security/dependabot/257
3. https://github.com/appsmithorg/appsmith/security/dependabot/258
4. https://github.com/appsmithorg/appsmith/security/dependabot/259
5. https://github.com/appsmithorg/appsmith/security/dependabot/260
6. https://github.com/appsmithorg/appsmith/security/dependabot/261
=> chore(deps): Update pf4j to v3.10.0

app/client/package.json, app/client/yarn.lock
Uses new ds version which fixes an issue with divider color
>
>
>
>
>
>
>
> …
=> chore: use new ds version

app/server/appsmith-plugins/pom.xml, app/server/appsmith-server/pom.xml
More context at https://github.com/appsmithorg/cloud-services/pull/1293#discussion_r1318105550.
=> chore: Remove irrelevant exclusion introduced in #27044

app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationSuccessHandlerCE.java
> This PR fixes the error introduced in https://github.com/appsmithorg/appsmith/pull/25854 which lead to sending of welcome mails even for non signup - oauth type requests. 
Fixes #27054 
>
>
>
>
- Bug fix
>
>
>
>
>
>
>
>
>
>
>
=> fix:  Welcome mailer stopped for non signup oauth

app/client/packages/design-system/theming/src/color/tests/DarkModeTheme.test.ts, app/client/packages/design-system/theming/src/color/tests/LightModeTheme.test.ts
=> chore: add unit test for bgAssitive + bgAccentSubtleActive + bgAccentSubtleHover

.github/workflows/ci-test-limited.yml, app/client/cypress/e2e/Regression/ClientSide/OtherUIFeatures/Replay_Editor_spec.js, app/client/cypress/support/Objects/DataManager.ts, app/client/cypress/support/Pages/DataSources.ts
- This PR updates the name of datasource method from 'AssertDSActive' to  'AssertDSInActiveList'
- Updated ci-test-limit.yml to include the flagsmith params
- Updates Postgress staging db name/creds
=> test: Cypress | Update ci-test-limit to use Mock Flagsmith

app/client/cypress/e2e/Regression/ServerSide/Datasources/ElasticSearch_Basic_Spec.ts
- This PR fixes the ElasticSearch_Basic_Spec.ts failure in EE runs handling both CE & EE runs
=> test: Cypress | ElasticSearch_Basic_Spec.ts fix

.github/workflows/ci-test-custom-script.yml
- This PR fixes the Set Commit Message for workflows runs in CI
=> ci: Set Commit Message fix 

.github/workflows/ci-test-custom-script.yml
- This PR fixes the Set Commit Message step for workflow runs
=> ci: Set Commit Message fix

CODEOWNERS
Keep @rajatagrawal as code owner for only cypress tests of widgets.
=> chore: Keep Rajat as codeowner for only cypress tests of widgets

app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/AddNewRow1_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/AddNewRow2_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/Date_column_editing_2_spec.ts, app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/Edge_case_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2Filter1_2_Spec.ts, app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_Url_Column_spec.ts, app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_Widget_Add_button_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_Widget_Default_Row_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_Widget_Selected_row_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/Text_wrapping_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/VirtualRow_spec.js, app/client/cypress/support/Pages/Table.ts
1. Date_column_editing_2_spec.ts - time precision unavailable now in date  column in table - so removed the skipped case
2. fixed mindate and max date skipped case
3. AddNewRow1_spec.js and AddNewRow2_spec.js - combined test cases and added asserts
=> test: Cypress - fixing table test cases 

.github/workflows/cleanup-dp.yml, scripts/cleanup_dp.sh, scripts/deploy_preview.sh, scripts/efs_guardian_job.json
Fixes: [322](https://github.com/appsmithorg/cloud-deployment/issues/322)
=> update scripts to deploy dps with EFS

app/client/src/components/editorComponents/CodeEditor/hintHelpers.ts, app/client/src/components/editorComponents/CodeEditor/utils/sqlHint.ts
This PR adds a cap to the number of SQL autocompletion hints that can show up at a time. For a very large number of hints (this can happen when db has large tables), `editor.showHint` method can be very expensive.
The upper limit is set to `200` hint options
Fixes #27147
>
> Please describe the tests that you ran to verify your changes. Also
list any relevant details for your test configuration.
>
>
>
>
(copy link from comments dropped on this PR)
>
>
>
(cherry picked from commit d2a2c700fbf1af7f445a028cdb8da17df0a5610d)
>
> Use this template to …
=> fix: Add a upper limit to the number of autocompletion hints (#27136)

app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationSuccessHandlerCE.java
> This PR fixes the error introduced in https://github.com/appsmithorg/appsmith/pull/25854 which lead to sending of welcome mails for form-type login requests. 
Fixes #27054 
>
>
>
>
>
>
>
>
>
>
=> fix: welcome mail trigger

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCEImpl.java
> 1-click refactor changes for Layout Action Service
> EE PR: https://github.com/appsmithorg/appsmith-ee/pull/2291
Fixes https://github.com/appsmithorg/appsmith/issues/27155
>
>
>
>
>
> …
=> chore: 1-click refactor for Layout Action Service

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/ApplicationServiceCETest.java
> 1-click refactor for Application Page Service
> EE PR: https://github.com/appsmithorg/appsmith-ee/pull/2297
Fixes https://github.com/appsmithorg/appsmith/issues/27165
>
>
>
>
>
> …
=> chore: 1-click refactor for application page service

.github/workflows/ci-test-hosted.yml, .github/workflows/test-build-docker-image.yml
- This PR updates the slack notification for Push workflows for debugging flaky tests(internal purpose)
=> ci: Cypress Push Slack notification update

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CacheableFeatureFlagHelperCEImpl.java
> This PR returns only the local flags if the CS is down and there are no cached flags. 
Fixes #25977 
- Bug fix 
>
>
>
>
>
>
>
=> fix: added ff fallback if cs is down

.github/workflows/test-build-docker-image.yml
=> chore: Adding slack notification for promotion TBP workflow failure

app/client/packages/design-system/theming/src/color/tests/DarkModeTheme.test.ts, app/client/packages/design-system/theming/src/color/tests/LightModeTheme.test.ts
=> chore: add unit tests for bgNeutral and bgNeutralHover

.github/workflows/ci-test-hosted.yml, .github/workflows/test-build-docker-image.yml
- This PR updates the slack notification link from Cypress dashboard to Build failures Git actions link incase of any build failure
=> ci: Cypress Push Slack notification handling build failures

app/client/src/ce/utils/BusinessFeatures/brandingPageHelpers.tsx, app/client/src/ce/utils/index.ts, app/client/src/pages/UserAuth/Login.tsx, app/client/src/pages/UserAuth/SignUp.tsx, app/client/src/pages/common/PageWrapper.tsx
Fixes an issue with /applications crashing on page load for the first time.
Fixes #27183 
>
>
>
>
>
>
>
>
>
>
>
>
>
=> fix: fix 404 crash happening during first load

app/server/appsmith-server/src/main/java/com/appsmith/server/domains/GitApplicationMetadata.java
We already store the default branch information. We can store the `protectedBranches` as a list of string. Another option is to add a boolean field to denote whether the branch is protected on not.
Here is how `gitApplicationMetadata` property will look like in the default branch:
"gitApplicationMetadata": {
....
"branchName": "master",
"defaultBranchName": "master", 
"branchProtectionRules": ["develop", "master"], // present in default branch only
"isProtectedBranch": true, // present in all branches
"remoteUrl": "git@github.com:nayan-rafiq/merge-test.git",
...
}
Here is how `gitApplicationMetadata property` will look like in the child branches:
"gitApplicationMetadata": {
....
"branchName": "master",
"defaultBranchName": "master", 
"isProtectedBranch": true, // present in all branches …
=> feat: Add application metadata for branch protection

.github/workflows/ci-test-hosted.yml, .github/workflows/ci-test.yml, .github/workflows/test-build-docker-image.yml
- Since ci-hosted run has no build failures - that is removed
- For push flow, step id is added for correct status capture
=> ci: Cypress Push Slack notification fixes

app/client/src/WidgetProvider/factory/helpers.ts, app/client/src/sagas/WidgetOperationSagas.tsx, app/client/src/sagas/WidgetOperationUtils.ts, app/client/src/utils/helpers.tsx, app/client/src/widgets/ButtonWidgetV2/widget/index.tsx, app/client/src/widgets/WidgetUtils.ts
- Fixes #27064 
- issue where the scroll on load feature threw an error when failing to find the container to scroll into
Fixed by organising the code such that `undefined` values don't have their properties accessed.
In an edge case, the widget's parent container like widget was not correctly identified, as a result, accessing the `dynamicHeight` property of the parent container like widget threw an error.
- Fixes #27209 
- issue where the ButtonWidgetV2's dynamic height feature was incorrectly configured
Fixed by removing the dynamic height feature from ButtonWidgetV2.
- As the issue is an edge case scenario, no reliable mechanism to replicate this has been identified to automate. @Sripriya93 @kamakshibhat-appsmith
=> fix: error in scroll on load feature

app/client/src/actions/debuggerActions.ts, app/client/src/sagas/DebuggerSagas.ts
Add `appmode` to debugger analytics
Fixes #25730
>
>
>
>
>
>
>
>
=> chore: Add appmode to debugger analytics

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserWorkspaceServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserWorkspaceServiceUnitTest.java
> 1-click refactor for user workspace service
> EE PR: https://github.com/appsmithorg/appsmith-ee/pull/2322
Fixes https://github.com/appsmithorg/appsmith/issues/27225
>
>
>
>
>
> …
=> chore: 1-click refactor for user workspace service

app/client/src/pages/Editor/DataSourceEditor/index.tsx
> PageId was missing as part of code endpoint. This is because we move save and authorisse button from DSForm to DSEditor.
Fixes #27263 
> [Video](https://czqtakk0ok.vmaker.com/record/mf3ietNJek5e0Vxs)
>
>
>
>
>
>
Tested the following on CE DP:
1. Tested import from home page with all Datasources - including OAuth and GSheets
2. Tested fork of the above app into another workspace
3. Tested import from inside the application with Gsheets DS
4. Tested import from inside the application with OAuth DS
5. …
=> fix: OAuth pageId blocker

app/client/src/components/editorComponents/CodeEditor/styledComponents.ts
fix: .then syntax highlighting is not working correctly
Fixes #23585
>
>
>
>
>
>
>
> …
=> fix: .then syntax highlighting is not working correctly

.github/workflows/server-build.yml
Add environment variable for community template upload for the server-build workflow
>
>
>
>
>
>
>
>
=> feat: add template upload auth env var to server-build

app/client/src/pages/Editor/SaaSEditor/DatasourceForm.tsx
Fixes a CE only issue which sets the env ID for SAAS forms. Affects the usage of google sheets in CE.
>
>
>
>
>
>
>
>
> Please describe the tests that you ran to verify your changes. …
=> chore: update default ID for saas forms

app/client/src/ce/constants/tenantConstants.ts
Updating the restart timeout on Admin settings page to fix embed settings spec failures
>
>
>
>
>
>
>
> …
=> chore: Updating the restart timeout on Admin settings page to fix embed settings spec failures

app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/GitControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
>
>
>
>
>
>
Fixes #26771
>
>
>
>
- Bug fix (non-breaking change …
=> feat: Auto commit DSL migration

app/client/src/ce/constants/messages.ts, app/client/src/components/editorComponents/form/FormDialogComponent.tsx, app/client/src/pages/AppViewer/Navigation/components/ShareButton.tsx
Updating share modal title on app editor and viewer
=> chore: Updating share modal title on app editor and viewer

app/client/packages/design-system/theming/src/color/src/DarkModeTheme.ts, app/client/packages/design-system/theming/src/color/src/LightModeTheme.ts, app/client/packages/design-system/theming/src/theme/src/ProviderStyleSheet.ts, app/client/packages/design-system/theming/src/theme/src/useTheme.tsx, app/client/packages/design-system/theming/src/token/src/TokensAccessor.ts, app/client/packages/storybook/.storybook/preview-head.html, app/client/packages/storybook/package.json, app/client/packages/storybook/src/components/TokenTable.tsx, app/client/yarn.lock
- remove redundant dependency
- fix tokenTables
- add system default font
- change color for code
=> fix: multiple fixes for storybook

app/client/src/ce/constants/tenantConstants.ts
=> chore: updating restart timeout to fix flaky tests

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/RedisUtils.java
=> fix: remove the comments as the delete file lock flow works

app/client/packages/design-system/theming/src/color/tests/DarkModeTheme.test.ts, app/client/packages/design-system/theming/src/color/tests/LightModeTheme.test.ts
=> chore: add fg + bd tokens tests for color algo

app/client/cypress/e2e/Regression/ClientSide/EmbedSettings/EmbedSettings_spec.js, app/client/cypress/limited-tests.txt, app/client/src/ce/constants/tenantConstants.ts
=> ci: updating embed settings spec

app/client/src/widgets/ChartWidget/component/EChartsConfigurationBuilder.test.ts, app/client/src/widgets/ChartWidget/component/EChartsConfigurationBuilder.ts, app/client/src/widgets/ChartWidget/component/EChartsDatasetBuilder.test.ts, app/client/src/widgets/ChartWidget/component/EChartsDatasetBuilder.ts, app/client/src/widgets/ChartWidget/component/LayoutBuilders/EChartsElementVisibilityCalculator.test.ts, app/client/src/widgets/ChartWidget/component/LayoutBuilders/EChartsElementVisibilityCalculator.ts, app/client/src/widgets/ChartWidget/component/LayoutBuilders/EChartsLayoutBuilder.test.ts, app/client/src/widgets/ChartWidget/component/LayoutBuilders/EChartsLayoutBuilder.ts, app/client/src/widgets/ChartWidget/component/LayoutBuilders/EChartsXAxisLayoutBuilder.test.ts, app/client/src/widgets/ChartWidget/component/LayoutBuilders/EChartsXAxisLayoutBuilder.ts, app/client/src/widgets/ChartWidget/component/LayoutBuilders/EChartsYAxisLayoutBuilder.test.ts, app/client/src/widgets/ChartWidget/component/LayoutBuilders/EChartsYAxisLayoutBuilder.ts, app/client/src/widgets/ChartWidget/component/helpers.ts, app/client/src/widgets/ChartWidget/component/index.tsx, app/client/src/widgets/ChartWidget/constants.ts, app/client/src/widgets/ChartWidget/widget/index.tsx
This is the promotion branch for hotfix release_v1.9.39
=> chore: Release v1.9.39

scripts/deploy_preview.sh
Depends: [2304](https://github.com/appsmithorg/appsmith-ee/pull/2304)
=> bump helm chart version

app/client/src/ce/pages/Applications/ApplicationCardList.tsx
Reverted the button text from `New Application` to `New` when there are no apps present in the workspace
Fixes #27390
>
>
>
>
>
> …
=> fix: changed the button text to new when no apps are present in workspace

Dockerfile
Reverting https://github.com/appsmithorg/appsmith/pull/26856
=> chore: revert update dockerfile to install mongodb v6.x (#26856)

app/client/package.json, app/client/yarn.lock
=> fix: bump postcss version

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/EnvManagerCEImpl.java
>
>
the logic for handling user invitation on admin settings page was causing double emails on admin settings page. turns out, we cannot use isEnabled flag because that flag can also be set by other serviecs for an existing user.
no issue - it is for a fix for existing buggy code in release
>
>
>
>
>
>
>
>
>
> …
=> fix: fix invite flow while inviting via admin settings

app/client/src/ce/constants/SocialLogin.tsx, app/client/src/ce/pages/AdminSettings/config/general.tsx, app/client/src/ce/pages/Applications/index.tsx, app/client/src/ce/pages/workspace/Members.tsx, app/client/src/ce/reducers/settingsReducer.ts, app/client/src/ce/sagas/JSFunctionExecutionSaga.ts, app/client/src/ce/sagas/WorkspaceSagas.ts, app/client/src/ee/pages/Applications/ApplicationCardList.tsx, app/client/src/ee/pages/Applications/WorkspaceMenu.tsx, app/client/src/pages/AdminSettings/FormGroup/TagInputField.tsx
Updating instance admin emails input field to tag input field for better UX 
Fixes [#27418](https://github.com/appsmithorg/appsmith/issues/27418)
=> chore: Updating instance admin emails input field to tag input field for better UX

app/client/src/components/editorComponents/CodeEditor/index.tsx, app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx, app/client/src/pages/Editor/QueryEditor/Form.tsx
Fixing any potential merge conflicts as files changed directly on ee
>
>
>
>
>
>
>
>
> Please describe the tests that you ran to verify your changes. Also list any relevant details …
=> fix: Fixing any potential merge conflicts as files changed directly on ee

app/client/src/components/editorComponents/CodeEditor/index.tsx, app/client/src/components/propertyControls/ChartDataControl.tsx, app/client/src/components/propertyControls/CodeEditorControl.tsx, app/client/src/components/propertyControls/ComputeTablePropertyControl.tsx, app/client/src/components/propertyControls/InputTextControl.tsx, app/client/src/components/propertyControls/JSONFormComputeControl.tsx, app/client/src/components/propertyControls/MenuButtonDynamicItemsControl.tsx, app/client/src/components/propertyControls/SelectDefaultValueControl.tsx, app/client/src/components/propertyControls/TableComputeValue.tsx, app/client/src/components/propertyControls/TableInlineEditValidationControl.tsx, app/client/src/components/propertyControls/WrappedCodeEditorControl.tsx
#27070 accidentally introduced slash commands in API URL field. This could lead to a bad UX since `/` is predominant in URLs. This PR removes slash commands from the URL field.
Fixes #27425 
>
>
>
>
>
>
>
>
>
>
>
>
>
=> fix: remove slash commands from API url field

app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/Edge_case_spec.js
updated row click helper from js to ts
=> test: cypress - updated test for table row click

app/client/cypress/e2e/Regression/ClientSide/Widgets/CodeScanner/CodeScanner1_spec.ts
- This PR updates the CodeScanner1_spec from js to ts to comply rule
=> test: Cypress | CodeScanner1_spec from js to ts

app/client/src/ce/components/editorComponents/GPT/AskAIButton.tsx, app/client/src/components/editorComponents/CodeEditor/index.tsx, app/client/src/ee/components/editorComponents/GPT/AskAIButton.tsx
This PR adds a placeholder component for the AskAI button in the Code editor. 
>
>
>
>
>
>
>
>
> Please describe the tests that you ran to verify your changes. Also list any relevant …
=> feat: Add placeholder component for AskAI Button in Code Editor

app/client/src/reducers/evaluationReducers/treeReducer.ts
This PR handles case for which there is no update in SET_EVALUATED_TREE action
Fixes https://github.com/appsmithorg/appsmith/issues/27506
>
>
>
>
>
>
> Delete anything …
=> fix: Handle case for undefined evalTree update

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/GitPrivateRepoHelperCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/GitPrivateRepoHelperCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/ce/GitPrivateRepoCEImplTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/GitServiceCETest.java
Refactor the branch protection check to a utility class as part of 1 click upgrade
>
>
>
>
>
>
>
=> chore: refactor git protect branch check

app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/FileUtilsImpl.java
It fixes the Git import failure bug when there's a file in the  pages directory.
Fixes #27466
N/A
>
>
>
>
>
>
>
=> fix: Git import fails when pages directory contains a file

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ActionPermissionCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ApplicationPermissionCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/DatasourcePermissionCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/EnvironmentPermissionCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PagePermissionCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/WorkspacePermissionCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/ce/ImportApplicationPermissionProviderTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/ApplicationSnapshotServiceUnitTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ce/RefactoringSolutionCEImplTest.java
> 1-click refactor for domain permission
>
>
>
>
>
>
>
>
> …
=> chore: 1-click refactor for domain permission

app/client/cypress/e2e/Regression/ClientSide/Widgets/ListV2/ListV2_NestedList_spec.ts, app/client/cypress/e2e/Regression/ClientSide/Widgets/Text/Text2_Spec.ts
This PR fixes a cypress test failure which was introduced in #25939
=> fix: Cypress tests that were introduced in improved App typography PR

app/server/appsmith-server/src/main/java/com/appsmith/server/newactions/base/NewActionServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/newactions/base/NewActionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepositoryImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomNewActionRepositoryImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomNewPageRepositoryImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/BaseAppsmithRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/NewActionRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewPageServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewPageServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/NewActionServiceUnitTest.java
This reverts commit 66d5027126523fb73cb14ce1336b171a85f8db37.
>
>
>
>
>
>
>
>
>
>
> …
=> Revert "fix: fixed failing queries using aggregation pipeline (#26132)"

app/client/packages/design-system/headless/src/components/Checkbox/src/CheckboxGroup.tsx, app/client/packages/design-system/headless/src/components/Field/src/Field.tsx, app/client/packages/design-system/headless/src/components/Field/src/Label.tsx, app/client/packages/design-system/headless/src/components/Radio/src/RadioGroup.tsx, app/client/packages/design-system/headless/src/components/TextArea/src/types.ts, app/client/packages/design-system/headless/src/components/TextInput/src/types.ts, app/client/packages/design-system/headless/src/components/TextInputBase/src/types.ts, app/client/packages/design-system/widgets/src/components/CheckboxGroup/src/CheckboxGroup.tsx, app/client/packages/design-system/widgets/src/components/SwitchGroup/stories/SwitchGroup.stories.mdx, app/client/packages/design-system/widgets/src/components/TextArea/stories/TextArea.stories.mdx, app/client/packages/design-system/widgets/src/components/TextInput/stories/TextInput.stories.mdx, app/client/packages/design-system/widgets/src/components/testing/ComplexForm.tsx, app/client/src/widgets/BaseInputWidgetV2/component/types.ts, app/client/src/widgets/BaseInputWidgetV2/widget/contentConfig.ts, app/client/src/widgets/BaseInputWidgetV2/widget/types.ts, app/client/src/widgets/InputWidgetV3/widget/index.tsx
=> chore: Remove side label in WDS components

CODEOWNERS
Updating CODEOWNERS file
>
>
>
>
>
>
>
>
> Delete anything …
=> chore: Updating CODEOWNERS file

app/client/src/utils/AppsmithUtils.tsx
When a non-error rejection is sent to sentry, we extract the actual error message and log it to sentry.
Fixes https://github.com/appsmithorg/appsmith/issues/9740
>
>
>
>
>
>
>
>
=> chore: Handle non-error rejections in sentry

app/client/cypress/e2e/Regression/ClientSide/Widgets/Button/Button2_spec.ts
=> test: Cypress - fixes

app/client/packages/design-system/widgets/package.json, app/client/packages/design-system/widgets/src/components/ButtonGroup/src/ButtonGroup.tsx, app/client/packages/design-system/widgets/src/components/ButtonGroup/src/ButtonGroupItem.tsx, app/client/packages/design-system/widgets/src/components/ButtonGroup/src/index.tsx, app/client/packages/design-system/widgets/src/components/ButtonGroup/src/types.ts, app/client/packages/design-system/widgets/src/components/ButtonGroup/stories/ButtonGroup.stories.mdx, app/client/packages/design-system/widgets/src/components/ButtonGroup/tests/ButtonGroup.test.tsx, app/client/yarn.lock
=> chore: improve buttonGroup

app/client/src/pages/Editor/gitSync/Tabs/GitConnectionV2/index.tsx, app/client/src/pages/Editor/gitSync/hooks/useGitConnect.ts, app/client/src/sagas/GitSyncSagas.ts, app/client/src/selectors/gitSyncSelectors.tsx
Error message were ignored when offline. Fixed it!
Fixes #27589
>
>
>
>
>
>
>
>
=> fix: adding offline error for git failure

app/server/appsmith-server/src/main/java/com/appsmith/server/constants/ce/FieldNameCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/PluginScheduledTaskUtilsCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ConfigServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ConfigServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/PluginServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/PluginScheduledTaskImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PluginScheduledTaskCEImpl.java
Makes sure that workspaces are not loaded into memory every 2 hours
=> chore: Added checks to only return plugins when new updates are present

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PluginScheduledTaskCEImpl.java
To make sure cs req is called on init
=> chore: Fixed flatmapping cs req 

app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseRepositoryImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomNewActionRepositoryImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomNewPageRepositoryImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/BaseAppsmithRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/NewActionRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewPageServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewPageServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/NewActionServiceUnitTest.java
> Queries using aggregation update failing. hence added a fallback.
Fixes #26090
Fixes https://github.com/appsmithorg/appsmith-ee/issues/1659
- Bug fix (non-breaking change which fixes an issue) ## Testing
>
>
>
>
>
(copy link from comments dropped on this PR)
>
>
>
>
>
>
>
> …
=> fix: Cherry picking the document db support to master

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/AnalyticsServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/AnalyticsServiceCEImplTest.java
This PR fixes discrepancy in mixpanel event numbers for anonymous CE users. For self hosted instances, in mixpanel funnel, number of Execute Action backend events was much lesser compared to corresponding frontend events, Also much lesser when compared to corresponding cloud numbers. 
**Root cause of issue**:
Issue was not because events were not getting triggered for CE for anonymous users, but issue was with the distinct Id which is assigned to each event on mixpanel. This distinct ID is based on the username, In case of logged in users, it simply gets username and uses that as distinct ID, in case of anonymous users:
- for cloud users, it sets this userId as anonymousUser which then the segment library evaluates to the value of X-Anonymous-User-Id header, this value is a unique UUID, …
=> fix: anonymous CE users mixpanel issue fixed

app/client/src/pages/Editor/APIEditor/CommonEditorForm.tsx, app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
There was some issue in providing padding values to the api editor url container and action right side pane. Adding fix for both.
Previously:
Now:
Fixes #27651 
>
>
>
>
>
>
>
>
> Please describe the tests …
=> fix: spacing issues on action page

CODEOWNERS, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/exceptions/pluginExceptions/BasePluginErrorMessages.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/SSHUtils.java, app/server/appsmith-interfaces/src/test/java/com/appsmith/external/helpers/SSHUtilsTest.java, app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java, app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/utils/MySqlDatasourceUtils.java
- If the user provides no value for port number field in the datasource config form, then the API server should assume default value. This PR fixes this functionality.
Fixes #27604 
>
>
>
- Please check out the video provided in the description [here](https://github.com/appsmithorg/appsmith/pull/26632). Use the same config for datasource as shown in the video, but leave the port number fields empty. Please reach out to @sumitsum for key file. 
https://github.com/appsmithorg/TestSmith/issues/2527
>
>
https://github.com/appsmithorg/appsmith/pull/27612#issuecomment-1736788753
>
>
>
=> fix: fix MySQL SSH tunnel default port value

app/client/src/pages/Editor/CommunityTemplates/Modals/PublishCommunityTemplate/CommunityTemplateForm.tsx, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/CommunityTemplateUploadDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationTemplateServiceCEImpl.java
removed unnecessary params.
>
>
>
>
>
>
>
>
> Delete …
=> fix: removes extra param as it is already handled on the community platform side.

app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/CommunityTemplateUploadDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationTemplateServiceCEImpl.java
=> Corrects variable names

app/server/appsmith-server/src/main/java/com/appsmith/server/constants/AccessControlConstants.java, app/server/appsmith-server/src/main/java/com/appsmith/server/constants/ce/AccessControlConstants.java, app/server/appsmith-server/src/main/java/com/appsmith/server/constants/ce/AccessControlConstantsCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/ce/UserProfileCE_DTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserServiceTest.java
fixes: https://github.com/appsmithorg/appsmith/issues/24606
=> feat: add roles and groups to userProfileDTO and set the message

app/client/src/ce/constants/ReduxActionConstants.tsx, app/client/src/pages/Editor/EditorHeader.tsx, app/client/src/sagas/WidgetDeletionSagas.ts, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Application.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationTemplateServiceCEImpl.java
- Add analytics events for 
- when an application forked from any template is deployed
- when a widget is deleted from an application forked from a template
- It introduces a new variable in the `Application` class to hold the template name from which the application was created. This gets persisted in the DB.
Fixes #27623 
>
- Automation tests seem not possible for this at the moment.
>
>
>
>
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments dropped on …
=> chore: add analytics events for new onboarding flow - part 2

app/client/src/pages/Editor/SaaSEditor/DatasourceForm.tsx
Expose google sheets to all users.
Fixes #27443 
>
>
>
>
>
>
>
>
=> feat: Rollout Gsheets for all users

app/client/src/pages/Editor/CommunityTemplates/Modals/CommunityTemplatesPublishInfo.tsx
=> fix: Corrects url typo

app/client/cypress/support/Pages/HomePage.ts
Share App test failing is fixed
>
>
>
>
>
>
>
>
> Delete …
=> fix: share app test cypress test

app/client/src/ce/AppRouter.tsx, app/client/src/ce/pages/Applications/index.tsx, app/client/src/ce/pages/workspace/WorkspaceInviteUsersForm.tsx, app/client/src/components/common/Card.tsx
Optimizing code-split for mapStateToProps and mapDispatchToProps
Fixes [#27727](https://github.com/appsmithorg/appsmith/issues/27727)
=> chore: Optimizing code-split for mapStateToProps and mapDispatchToProps

app/client/cypress/e2e/Regression/ClientSide/OtherUIFeatures/Omnibar_spec.js
Doc link got updated which was causing test to fail, fixed it.
locally
=> test: Cypress| Fix omnibar test

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/AppsmithBeanUtils.java, app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationSuccessHandlerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ce/TenantConfigurationCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/TenantServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/TenantServiceCETest.java
> When the new branding tenant configuration is applied, we invoke the method `copyNestedNonNullProperties` which accepts a source and the target object and copies the non null key-value pairs from source to the target object. Due to this common utility method which calls the getter method of the fields in source object, if the getter method is overloaded to return False instead of Null, it copies the false value to the target object. 
> This PR fixes the getter method to only return the default null value if not present instead of defaulting it to false.
Fixes #27783 
>
>
- Bug fix (non-breaking change which fixes …
=> fix: boolean getter method for email verification enabled field

app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/UserUpdateDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/ce/UserUpdateDTO_CE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java
> Code split for UserUpdateDTO
> Move User Management Role's Default Domain Type tag to CE File
> EE PR: https://github.com/appsmithorg/appsmith-ee/pull/2531
Fixes https://github.com/appsmithorg/appsmith/issues/27782
Fixes https://github.com/appsmithorg/appsmith/issues/27781
>
>
>
>
>
>
>
> Link issues raised during DP testing for better visiblity and tracking (copy link from …
=> fix: Code split for UserUpdateDTO and fix UserServiceCEImpl

app/server/appsmith-server/src/main/java/com/appsmith/server/services/PACConfigurationService.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/PACConfigurationServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/PACConfigurationServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/PACConfigurationServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce_compatible/PACConfigurationServiceCECompatible.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce_compatible/PACConfigurationServiceCECompatibleImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce_compatible/UserServiceCECompatibleImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/PACConfigurationServiceCETest.java
PAC configuration service related CE changes
=> feat: PAC Service code split for configuration

app.json, deploy/docker/fs/opt/appsmith/install_docker.sh
Description:
I've Replaced the old URLs with the new URLs assigned to me provided in the Spreadsheet.
PR fixes the following issue(s):
Fixes #25513
=> chore: replaced decommisioned urls with new ones

app.json, app/client/src/ce/utils/autocomplete/EntityDefinitions.ts, app/client/src/pages/Editor/IntegrationEditor/mockData/index.ts, app/client/src/widgets/MapWidget/widget/index.tsx, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog1.java, deploy/docker/fs/opt/appsmith/install_docker.sh, deploy/heroku/README.MD
I have replaced the decommissioned versioned URLs with the correct new URLs based on the provided [list.](https://docs.google.com/spreadsheets/d/10qLHfy4XIjNN_8CPzTu8B7ZNYUrCJM212ZOo8Qfkt9Q/edit?usp=sharing)
Fixes https://github.com/appsmithorg/appsmith/issues/25513
=> chore: Replaced versioned URLs with new ones 

app/client/src/ce/utils/autocomplete/EntityDefinitions.ts, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog1.java
fix lint issue on EntityDefinition and DatabaseChangelog1
>
>
>
>
>
>
>
>
>
>
>
>
> Link issues raised during DP testing for better visiblity and tracking (copy link from …
=> fix: fix lint issue on EntityDefinition and DatabaseChangelog1

app/client/src/pages/Home/LeftPaneBottomSection.tsx
Current version of the upgrade button uses a hardcoded value for Orange color which doesnt change on changing the branding color, this PR resolves that issue and uses the branding color.
Fixes https://github.com/appsmithorg/cloud-services/issues/1388
>
>
>
>
>
>
>
>
>
>
>
=> fix: remove hardcoded color for upgrade button

app/client/build.sh, app/client/src/ce/constants/messages.ts, app/client/src/pages/Editor/CommunityTemplates/Modals/PublishCommunityTemplate/CommunityTemplateForm.tsx, app/client/src/pages/Editor/EditorHeader.tsx
=> fix: Updates tab title from publish to showcase

app/client/build.sh, app/client/src/ce/constants/messages.ts, app/client/src/pages/Editor/CommunityTemplates/Modals/PublishCommunityTemplate/CommunityTemplateForm.tsx, app/client/src/pages/Editor/EditorHeader.tsx
This reverts commit f7208c97752952a7711220bfa8155d10316b306e.
>
>
>
>
>
>
>
>
>
>
> …
=> fix: Revert "fix: Updates tab title from publish to showcase (#27867)"

app/server/appsmith-plugins/arangoDBPlugin/src/main/java/com/external/plugins/ArangoDBPlugin.java, app/server/appsmith-plugins/elasticSearchPlugin/src/main/java/com/external/plugins/ElasticSearchPlugin.java, app/server/appsmith-plugins/mssqlPlugin/src/main/java/com/external/plugins/MssqlPlugin.java, app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java, app/server/appsmith-plugins/oraclePlugin/src/main/java/com/external/plugins/OraclePlugin.java, app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java, app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/plugins/RedisPlugin.java, app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/utils/RedisURIUtils.java, app/server/appsmith-plugins/redshiftPlugin/src/main/java/com/external/plugins/RedshiftPlugin.java, app/server/appsmith-plugins/smtpPlugin/src/main/java/com/external/plugins/SmtpPlugin.java
This PR extends the rate limiting functionality to all the plugins, wherever applicable. This is an extension of PR #27777. As mentioned in the task ticket, we have extended this functionality to following plugins:
- ArangoDB
- Redshift
- Redis
- Oracle
- SMTP
- MySQL
- MSSQL
- Elastic Search
JUnit tests will be added as part of #27742 
Fixes #27737 
>
>
>
>
>
>
>
> …
=> feat: rate limiting functionality extended for other plugins

app/client/cypress/e2e/Regression/ClientSide/Widgets/Tab/Tabs_2_spec.ts
Skipping a test in this Tab regression spec
=> test: cypress - commenting a test in Tab spec

app/client/cypress/e2e/Regression/ClientSide/Git/GitSync/RepoLimitExceededErrorModal_spec.js, app/client/cypress/limited-tests.txt, app/client/cypress/support/Pages/HomePage.ts
Adds cypress method to delete app via api and updated git test.
locally
>
>
>
>
>
=> test: Add common method to delete app via api

app/client/craco.common.config.js, app/client/package.json, app/client/packages/storybook/.storybook/main.ts, app/client/packages/storybook/package.json, app/client/yarn.lock
Removed postcss-for as it's causin to pull in some old dependencies due to which have CVEs discovered on them.
=> chore: remove postcss-for

.github/workflows/perf-tests-command.yml
Piggyback on /perf-test command to run perf infra v2
Fixes #27931
=> ci: Run perf infra v2 in /perf-test command

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/FeatureFlagMigrationHelperCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/FeatureFlagMigrationHelperTest.java
In this code change, a separate loop has been introduced to handle the removal of specific flags from a map to avoid encountering a `ConcurrentModificationException` that can occur when attempting to remove an entry from a map while iterating over it directly. This new loop iterates through a collection of `featureFlagsToBeRemoved`, removing each corresponding flag from the mentioned maps, ensuring safe removal without disrupting the ongoing iteration process.
Fixes https://github.com/appsmithorg/appsmith-ee/issues/2608
>
>
>
=> fix: Concurrent modification issue with pending migrations feature flags

app/client/src/ce/sagas/SuperUserSagas.tsx, app/client/src/constants/routes/baseRoutes.ts
Change URL for License Settings page to /settings/license from /settings/billing, remove unused parameter from RestartPoll.
Fixes #https://github.com/appsmithorg/cloud-services/issues/1413
>
>
>
>
>
>
>
>
>
>
>
=> fix: change URL for License Settings page

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/RestAPIActivateUtils.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/util/WebClientUtils.java, app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java, app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> Fixes the API redirection problem where forwarding location only has uri path
This Pr adds null pointer checks for host address, adds stack trace in logging, and fixes the problem of erroring out when the  called endpoint redirection headers don't have full formed forwarding location
Fixes #25408 
1. Tried out with the  endpoint of the API hosted on Manish's ngrok, GET and POST requests fail with the java null pointer exception. However, on this DP, both GET and POST requests work. 
2. Tried out Sanity tests with other end points on Rest API
3. Did Sanity checks on GraphQL
4. Saved Rest API and GraphQL as datasource and ensured that works fine too
5. Exported this app, imported the same and ran the API to check for functionality
=> fix: for api-redirection

app/client/src/ce/AppRouter.tsx, app/client/src/reducers/uiReducers/usersReducer.ts, app/client/src/selectors/usersSelectors.tsx
Make features call a blocking API call for page load
Fixes #27973 
>
>
>
>
>
>
>
>
=> feat: make features call a blocking API call for page load

deploy/helm/Chart.yaml, deploy/helm/templates/statefulset.yaml, deploy/helm/values.yaml
Fixes: [27523](https://github.com/appsmithorg/appsmith/issues/27523)
=> Fix images with vulnerabilities

app/client/src/ce/sagas/ApplicationSagas.tsx, app/client/src/pages/AppViewer/PrimaryCTA.tsx
Removes branch on fork redirection for git connected applications
Fixes #27690
Only fixes the client redirection issue
>
>
>
>
>
>
>
>
>
>
>
=> fix: removing branch name on fork redirect

app/client/src/widgets/WidgetUtils.test.ts, app/client/src/widgets/WidgetUtils.ts
Fix auto label position
Fixes #27975
https://github.com/appsmithorg/appsmith/assets/11555074/bf6e4c8c-97db-4eab-8986-b4cd2de5bd0a
>
>
>
>
>
>
>
>
=> fix: auto label position

app/client/cypress/e2e/Regression/ClientSide/Onboarding/FirstTimeUserOnboarding_spec.js
- This PR fixes the FirstTimeUserOnboarding_spec failing in CI runs
>
=> test: Cypress | FirstTimeUserOnboarding_spec fix

app/client/package.json, app/client/yarn.lock
=> fix: postcss version

app/server/appsmith-server/src/main/java/com/appsmith/server/datasourcestorages/base/DatasourceStorageService.java, app/server/appsmith-server/src/main/java/com/appsmith/server/datasourcestorages/base/DatasourceStorageServiceCECompatible.java, app/server/appsmith-server/src/main/java/com/appsmith/server/datasourcestorages/base/DatasourceStorageServiceCECompatibleImpl.java
> CE support for PR https://github.com/appsmithorg/appsmith-ee/pull/2634
- Added compatibility classes for EE support
Fixes https://github.com/appsmithorg/appsmith-ee/issues/2621
=> chore: added support changes

app/server/appsmith-server/src/main/java/com/appsmith/server/datasources/export/DatasourceExportableServiceCEImpl.java
Fixes error with using app id instead of workspace id while figuring out env id
=> refactor: Export service to different consumer classes

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCEImpl.java
> chore: clear cache after saving workspace roles
>
>
>
>
>
>
>
> …
=> chore: clear cache after saving workspace roles

app/client/cypress/e2e/Regression/ClientSide/Git/GitSync/Connection_spec.js
- This PR fixes the flaky Connection_spec.js - test failing in CI runs
>
=> test: Cypress | Connection_spec.js flaky fix

app/server/appsmith-server/src/main/java/com/appsmith/server/datasourcestorages/base/DatasourceStorageServiceCECompatibleImpl.java
>  TL;DR plugin service import needed to be changed as the package was refactored
=> fix: fixing build failure

.github/workflows/ci-test-custom-script.yml, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CacheableFeatureFlagHelperCEImpl.java
PR to add the signature verification for tenant feature flags. With this PR we will make sure feature flags those are getting reported from CS can't be mocked.
Fixes https://github.com/appsmithorg/cloud-services/issues/1394
>
>
=> feat: Add signature verification for tenant feature flags

app/client/src/ce/sagas/userSagas.tsx, app/client/src/usagePulse/index.ts
Usage pulse without feature flags should default to CE interval
Fixes https://github.com/appsmithorg/appsmith-ee/issues/2547
>
>
>
>
>
>
>
>
=> fix: usage pulse without feature flags should default to CE interval

app/client/jest.config.js, app/client/src/ce/configs/index.ts, app/client/src/ce/configs/types.ts, app/client/src/ce/constants/tenantConstants.ts, app/client/src/ce/pages/AdminSettings/config/general.tsx, app/client/src/ce/selectors/tenantSelectors.tsx, app/client/src/pages/AppViewer/PageMenu.tsx, app/client/src/pages/AppViewer/index.tsx
Instead of using the env file to get the value for hideWatermark, we are moving it to the tenantConfig. Makes it easier to manage and does not need a server restart while changing the value.
Fixes #27922 
https://github.com/appsmithorg/appsmith-ee/pull/2628
>
>
>
>
>
>
>
>
> Link issues raised during DP testing for better …
=> feat: use hideWatermark from tenantConfig

app/client/src/ce/constants/messages.ts, app/client/src/ce/sagas/SuperUserSagas.tsx, app/client/src/pages/Editor/FirstTimeUserOnboarding/HelpMenu.tsx, app/client/src/pages/Editor/HelpButton.tsx, app/client/src/pages/Home/LeftPaneBottomSection.tsx, app/client/src/pages/common/MobileSidebar.tsx
As part of the 1-click project we want to update the version names for Appsmith Images.
CE: Appsmith Community vx.y.z
EE/Cloud: Appsmith vx.y.z 
Fixes https://github.com/appsmithorg/appsmith-ee/issues/1769
>
>
>
>
>
>
>
>
=> feat: remove cloudHosting conditional check, change version name

app/client/src/ce/pages/AdminSettings/Branding/UpgradeBanner.tsx, app/client/src/constants/ThirdPartyConstants.tsx, app/client/src/utils/hooks/useOnUpgrade.ts
Updated ramps to redirect on customer portal
>
>
>
>
>
>
>
>
>
>
>
>
>
=> chore: updated ramps to redirect on customer portal

app/client/src/usagePulse/utils.ts
This PR removes the redundant throwing of noop error in the` fetchWithRetry` function
Fixes #27714 
>
>
>
>
>
>
>
>
> Add …
=> fix: unhandledRejection error in sentry log

app/client/src/pages/common/SharedUserList.tsx
> Fixes render issue for `allUsers` after sharing the workspace access with new users.
Fixes #28013 and ensures that it does not break #17728
> https://www.loom.com/share/265e79e2e4a14d6b8312a6ea112365d0
>
>
>
=> fix: Updating the logic to render 'allUsers' having access to the workspace

app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/AppsmithRepository.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/BaseAppsmithRepositoryCEImpl.java
This pull request introduces the `updateAndReturn` method, a valuable addition to the codebase. The method is designed to facilitate efficient and real-time updates of domain objects in the database while returning the updated object itself. This feature is particularly useful in scenarios where a fresh representation of the object is required immediately after a database modification.
Implementation Details:
The `updateAndReturn` method utilizes MongoDB's `findAndModify` operation with appropriate query criteria and update instructions.
It optionally considers access control permissions to ensure secure and authorized operations.
Usage Example:
```
// Example usage of the `updateAndReturn` method
Mono<YourModel> updatedObject = 
repository.updateAndReturn("documentId", updateObj, …
```
=> chore: Add `findAndModify` function to base repository (#27969)

app/client/src/pages/AdminSettings/FormGroup/Button.tsx, app/client/src/pages/AdminSettings/FormGroup/Checkbox.tsx, app/client/src/pages/AdminSettings/FormGroup/Common.tsx, app/client/src/pages/AdminSettings/FormGroup/Radio.tsx, app/client/src/pages/AdminSettings/FormGroup/TextInput.tsx
Refactoring the code for label wrapper on admin settings
Fixes [#28099](https://github.com/appsmithorg/appsmith/issues/28099)
=> fix: Refactoring the code for label wrapper on admin settings

app/client/src/pages/Editor/EditorName/NavigationMenuData.ts, app/client/src/pages/Editor/EditorName/NavigationMenuItem.tsx, app/client/src/pages/Editor/EditorName/types.ts
Refactoring editor header component
Fixes [#26163](https://github.com/appsmithorg/appsmith/issues/26163)
=> chore: Refactoring editor header

app/server/appsmith-server/src/main/java/com/appsmith/server/newactions/base/NewActionServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/newactions/base/NewActionServiceCEImpl.java
This PR introduces a code-split for updating an unpublished action regardless of the type of action e.g. regular action or module action. The goal is to use the underlying implementation of updating unpublished actions in case of module action update.
Fixes #27967 
>
>
>
>
>
>
>
> Link issues raised during DP testing for better visiblity and tracking (copy link from comments …
=> chore: Introduce code split for updating unpublished action (#27967)

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce_compatible/GitServiceCECompatible.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce_compatible/GitServiceCECompatibleImpl.java
Contains new layer for ce compatible to prevent merge conflicts on EE
=> chore: Added ce compatible layer for git

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce_compatible/GitServiceCECompatible.java
=> chore: Fixes compilation error due to git svc changes

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/constants/AnalyticsEvents.java, app/server/appsmith-server/src/main/java/com/appsmith/server/constants/ce/FieldNameCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/InstanceConfigHelperImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/InstanceConfigHelperCEImpl.java
Send an analytics events on instance registration
Fixes https://github.com/appsmithorg/cloud-services/issues/1232
=> feat: server setup complete event

app/client/cypress/e2e/Regression/ClientSide/Git/ExistingApps/v1.9.24/DSCrudAndBindings_Spec.ts
- This PR fixes the flaky DSCrudAndBindings_Spec.ts - 2nd spec
- Script update (non-breaking change which fixes an issue)
=> test: Cypress | DSCrudAndBindings_Spec.ts flaky fix

app/client/cypress/e2e/Regression/ClientSide/Widgets/ListV2/ListV2_SerververSide_spec.js, app/client/src/reducers/evaluationReducers/treeReducer.ts, app/client/src/workers/Evaluation/__tests__/generateOpimisedUpdates.test.ts, app/client/src/workers/Evaluation/helpers.ts
Updates were trying to be added it to invalid moment objects which is not necessary. Earlier when we serialse invalid Moment objects it gets converted to null, made code corrections which it to keep it inline with earlier behaviour.
Fixes #27963
>
>
>
>
>
>
>
=> fix: remove moment patches

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/constants/PluginConstants.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceContextServiceTest.java
> Rest Api used cached datasourceContext which was providing older
tokens. Now when we look for datasourceContext we provide a new context.
Fixes #27699 
>
>
>
>
>
>
> if no issue exists, please create an issue and ask the maintainers about this …
=> fix: removed datasourceContextCaching for RestAPI (#28160)

app/client/src/ce/pages/workspace/InviteUsersForm.tsx, app/client/src/ce/sagas/userSagas.tsx, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/UserAndAccessManagementServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/WorkspaceServiceTest.java
> With the current workflow for inviting users to workspace, we are not filtering out duplicate emails. With this code change, we intend to only invite unique users to workspace.
Fixes https://github.com/appsmithorg/appsmith/issues/28067
>
>
>
>
>
>
>
>
>
>
=> chore: invite unique emails to workspace

app/client/cypress/e2e/Regression/ClientSide/ProductRamps/PrivateEmbedRamp_spec.ts, app/client/src/ce/selectors/rampSelectors.tsx
Updated the ramp selector link to redirect on customer portal
>
>
>
>
>
>
>
>
>
>
>
>
=> fix: Ramp selector link to redirect on portal

app/server/appsmith-interfaces/pom.xml
https://github.com/appsmithorg/appsmith/security/dependabot/267
=> chore: update version due to vulnebarity

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/UserAndAccessManagementServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ce/ActionExecutionSolutionCETest.java
> Fix error message thrown when permission group is not found.
>
>
>
>
>
>
>
>
>
>
>
>
=> chore: Fix error message for when permission group is not found

app/client/src/pages/Editor/FirstTimeUserOnboarding/testUtils.ts
Common test case is failing on EE
>
>
>
>
>
>
>
>
> Delete …
=> fix: common test case fix

app/client/cypress/e2e/Regression/ClientSide/Autocomplete/autocomplete_spec.js, app/client/cypress/e2e/Regression/ServerSide/JsFunctionExecution/JSFunctionExecution_spec.ts, app/client/packages/ast/index.ts, app/client/packages/ast/src/index.test.ts, app/client/packages/ast/src/index.ts, app/client/src/ce/entities/DataTree/types.ts, app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx, app/client/src/selectors/navigationSelectors.ts, app/client/src/utils/DynamicBindingUtils.ts, app/client/src/workers/Evaluation/__tests__/errorModifier.test.ts, app/client/src/workers/Evaluation/__tests__/evaluate.test.ts, app/client/src/workers/Evaluation/errorModifier.ts, app/client/src/workers/Evaluation/evaluate.ts, app/client/src/workers/Evaluation/fns/utils/jsObjectFnFactory.ts
This PR modifies the TypeError message (**`cannot read property of undefined`**), replacing it with a much easier-to-understand message.
Fixes #27753
>
>
>
>
>
> Link issues raised during DP testing …
=> feat: Improve error message for typeError

app/client/cypress/e2e/Regression/ServerSide/Postgres_DataTypes/Binary_Spec.ts, app/client/cypress/e2e/Regression/ServerSide/Postgres_DataTypes/Json_Spec.ts, app/client/cypress/e2e/Regression/ServerSide/QueryPane/S3_2_spec.ts
- This PR fixes below specs for random flaky behavior to reflect right data:
- ServerSide/Postgres_DataTypes/Binary_Spec.ts
- ServerSide/Postgres_DataTypes/Json_Spec.ts
- ServerSide/QueryPane/S3_2_spec.ts
=> test: Cypress | CI Flaky fixes

app/client/src/pages/Editor/FirstTimeUserOnboarding/Overlay.tsx, app/client/src/pages/Editor/HelpButton.tsx
=> fix: Reverts changes that hid the starter guide for users

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce_compatible/ApplicationServiceCECompatibleImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/ApplicationServiceCETest.java
> Set the correct lastModifiedBy when application or it's resources are updated.
Fixes https://github.com/appsmithorg/appsmith/issues/26120
>
>
>
>
>
>
>
>
>
>
=> fix: set the correct lastModifiedBy when application or it's resources are updated

app/client/cypress/e2e/Regression/ClientSide/Widgets/ListV2/ListV2_NestedList_spec.ts, app/client/cypress/fixtures/listV2NestedDsl.json, app/client/src/layoutSystems/common/dropTarget/DropTargetComponentWrapper.tsx, deploy/docker/fs/opt/appsmith/healthcheck.sh
Hotfix for Release v1.9.41
>
>
>
>
>
>
>
> …
=> fix: Hotfix for release v1.9.41

deploy/helm/Chart.yaml, deploy/helm/templates/statefulset.yaml
=> fix: Remove duplicate `securityContext` key

app/client/src/pages/Editor/FirstTimeUserOnboarding/Overlay.tsx, app/client/src/sagas/TemplatesSagas.ts
* Disallow hover screen when initial guide overlay is present. 
* Implements loader screen.
>
>
>
>
>
>
>
>
=> feat: Implements overlay screen and disallows hover events when guide overlay is visible

app/client/src/utils/hooks/useWidgetFocus/handleTab.ts
Traverses all tabbable widget until a focusable widget is found, then focuses it.
_Fixes #28341_
<table>
<tr>
<td><strong>Before
<td><strong>After
<tr>
<td>
https://github.com/appsmithorg/appsmith/assets/1488378/6cac6e01-a8ff-47cf-bf6b-b95e7c599128
<td>
https://github.com/appsmithorg/appsmith/assets/1488378/db48f4d4-498f-4516-8d09-6303daea953a
</table>
_I'm not sure how to test this..._
>
>
_I'm not sure what this is about..._
> Link issues raised during DP testing for …
=> fix: traverse to next focusable widget

app/server/appsmith-server/pom.xml, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationTemplateServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationTemplateServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationTemplateServiceUnitTest.java
Add support for java Instant new Java8 Date API datatype modules in Jackson. 
Fixes https://github.com/appsmithorg/appsmith/issues/28350
=> fix: Add support for jackson with java time modules

app/client/package.json, app/client/yarn.lock
PR to bump package version for ADS
=> chore: bump package version for ADS

app/client/cypress/e2e/Regression/ClientSide/Widgets/Others/IconButton_2_spec.ts, app/client/cypress/limited-tests.txt
**Flaky fixes below:**
- /Widgets/Others/IconButton_2_spec.ts
>
=> test: Cypress | IconButton_2_spec.ts flaky fix

app/server/appsmith-server/src/main/java/com/appsmith/server/jslibs/imports/CustomJSLibImportableServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/JsonSchemaMigration.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/JsonSchemaVersions.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/MigrationHelperMethods.java
> fixes xml parser
Fixes: https://github.com/appsmithorg/appsmith/issues/28364
=> chore: modified server schema version

app/server/appsmith-server/src/main/java/com/appsmith/server/exports/internal/ExportApplicationServiceCEImpl.java
=> fix: Analytics events not fired during export application

app/server/appsmith-plugins/arangoDBPlugin/src/test/java/com/external/plugins/ArangoDBPluginTest.java, app/server/appsmith-plugins/elasticSearchPlugin/src/test/java/com/external/plugins/ElasticSearchPluginTest.java, app/server/appsmith-plugins/mssqlPlugin/src/test/java/com/external/plugins/MssqlPluginTest.java, app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java, app/server/appsmith-plugins/oraclePlugin/src/test/java/com/external/plugins/OracleConnectionRateLimitTest.java, app/server/appsmith-plugins/postgresPlugin/src/test/java/com/external/plugins/PostgresPluginTest.java, app/server/appsmith-plugins/redisPlugin/src/test/java/com/external/plugins/RedisPluginTest.java, app/server/appsmith-plugins/redshiftPlugin/src/test/java/com/external/plugins/RedshiftPluginTest.java, app/server/appsmith-plugins/smtpPlugin/src/test/java/com/external/plugins/SmtpPluginTest.java
This PR adds JUnit test cases for rate limit functionality implemented for datasource test and datasource connections. 
Fixes ##27742
>
>
>
>
>
>
>
>
>
>
>
>
>
=> chore: JUnit test cases added for rate limit functions

app/client/src/sagas/PluginSagas.ts
This PR removes the error logs added to debug CI issue
Fixes #28319 
>
>
>
>
>
>
>
> …
=> chore: removed unnecessary logs added to debug CI issue

app/client/src/ce/plugins/Linting/lib/entity/entityConstructorMap.ts, app/client/src/ce/plugins/Linting/lib/entity/isDynamicEntity.ts, app/client/src/ce/plugins/Linting/lib/entity/types.ts, app/client/src/ee/plugins/Linting/lib/entity/entityConstructorMap.ts, app/client/src/ee/plugins/Linting/lib/entity/isDynamicEntity.ts, app/client/src/ee/plugins/Linting/lib/entity/types.ts, app/client/src/plugins/Linting/lib/entity/ActionEntity.ts, app/client/src/plugins/Linting/lib/entity/AppsmithEntity.ts, app/client/src/plugins/Linting/lib/entity/EntityTree.ts, app/client/src/plugins/Linting/lib/entity/JSActionEntity.ts, app/client/src/plugins/Linting/lib/entity/PagelistEntity.ts, app/client/src/plugins/Linting/lib/entity/WidgetEntity.ts, app/client/src/plugins/Linting/lib/entity/index.ts, app/client/src/plugins/Linting/utils/diffGenerator.ts, app/client/src/plugins/Linting/utils/getEntityDependencies.ts, app/client/src/plugins/Linting/utils/pathUtils.ts
CE changes for moduleInputs entity linting
Fixes https://github.com/appsmithorg/appsmith-ee/pull/2720
=> chore: CE changes for Linting ModuleInputs

app/client/cypress/support/e2e.js, app/client/src/ce/pages/workspace/Members.tsx, app/client/src/pages/Editor/Explorer/Common/components.tsx
Updating validateLicense function call in cypress
=> chore: Updating validateLicense function call in cypress

app/client/src/pages/Editor/DatasourceInfo/DatasourceStructureHeader.tsx
This PR fixes issue with refresh button on datasource preview page. Earlier it was a div, now changed it to button so all hover states are visible
>
>
Fixes #28430 
>
>
>
>
>
>
>
>
>
> …
=> fix: schema refresh button issue fixed

app/client/src/ce/utils/preloadHelpers.ts, app/client/src/ee/utils/preloadHelpers.ts, app/client/src/preload-route-chunks.ts
Our preloads were not using CDN, this PR fixes it. More details in the linked issue.
Fixes #28359
>
Should verify CDN once deployed on release.
=> fix: Refactor preloads to fix an issue with CDN on EE

app/server/appsmith-server/src/main/java/com/appsmith/server/datasources/base/DatasourceServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/datasources/base/DatasourceServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java, app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithErrorCode.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceContextServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceContextServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ce/ActionExecutionSolutionCETest.java
This PR adds rate limiting on connection creations. Connections with datasources are created in following situations:
- Whenever a query is executed, we create connection to datasource
- Whenever datasource structure is fetched
- Whenever trigger API is called in case of generate CRUD
In all above cases, if connection is successful, its context is saved in cache, but when the connection is unsuccessful, connection context is not saved in cache and connection creation is initiated every time. In such case, we need to apply rate limiting on connection creation, so that no brute force attacks can happen.
The code in this PR is written with the assumption that every time connection creation fails, each plugin throws an error, whenever we get this error, we consume token from bucket, if we …
=> feat: rate limiting added for connection creation during query execution

app/client/cypress/e2e/Regression/ClientSide/BugTests/GitBugs_Spec.ts, app/client/cypress/e2e/Regression/ClientSide/Git/GitSync/GitStatusLite_spec.ts, app/client/src/entities/Engine/AppEditorEngine.ts, app/client/src/pages/Editor/gitSync/Tabs/Deploy.tsx, app/client/src/pages/Editor/gitSync/Tabs/Merge.tsx, app/client/src/sagas/GitSyncSagas.ts
Does `fetch/remote` first and then `/status` on canvas load
Fixes #28462 
>
>
>
>
>
>
>
>
=> fix: adding missing `fetch` api with `status` call

app/server/appsmith-server/src/main/java/com/appsmith/server/constants/ce/EmailConstantsCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/EmailServiceHelperCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/EmailServiceHelperCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/EmailServiceCEImpl.java, app/server/appsmith-server/src/main/resources/email/ce/inviteWorkspaceExistingUserTemplate.html, app/server/appsmith-server/src/main/resources/email/ce/inviteWorkspaceNewUserTemplate.html, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/EmailServiceCEImplTest.java
> Fix email templates and subjects.
> Related EE PR: https://github.com/appsmithorg/appsmith-ee/pull/2791
>
>
>
>
>
Manual testing done on the DP: ee-2787
>
>
>
>
>
=> fix: subject and email templates

app/client/src/ce/constants/messages.ts, app/client/src/pages/Editor/DatasourceInfo/RenderInterimDataState.tsx
- Update title and text for loading state as per the description [here](https://www.notion.so/appsmith/5c8aa998aa94429995a6e0825ca2df05?v=14883d075b6649be9a8748938dcc224b&p=1f99652227ad4eada949fa72334154d8&pm=s). 
- skipped the progress bar because the ADS team has suggested so. 
- Skipping automation test case for now because the entire schema display feature is behind feature flag right now. In case the experiment is successful and the feature flag gets lifted, a test case should be added for this. Tracking it [here](https://github.com/appsmithorg/appsmith/issues/28519). 
Fixes #28047 
https://github.com/appsmithorg/appsmith/assets/1757421/bb64edcc-10fe-46c5-b60d-573a6ecb5b9e
>
- Skipping automation test case for now because …
=> feat: update loading state page for datasource schema display preview page

app/client/src/actions/jsActionActions.ts, app/client/src/actions/jsPaneActions.ts, app/client/src/ce/api/JSActionAPI.tsx, app/client/src/ce/sagas/JSActionSagas.ts, app/client/src/ce/sagas/index.tsx, app/client/src/ee/api/JSActionAPI.tsx, app/client/src/ee/sagas/JSActionSagas.ts, app/client/src/sagas/JSActionSagas.ts, app/client/src/sagas/JSPaneSagas.ts, app/client/test/sagas.ts
Code split JSActionAPI and JSActionSagas
Fixes https://github.com/appsmithorg/appsmith-ee/issues/2601
>
>
>
>
>
>
>
>
>
=> feat: code split JSActionAPI and JSActionSagas

app/client/cypress/e2e/Regression/ClientSide/Templates/Fork_Template_Existing_app_spec.js, app/client/cypress/locators/TemplatesLocators.json
Meeting scheduler is causing problems repeatedly, using another template(Vehicale maintenence app) - as this spec should be template agnostic.
=> chore: Fixes failing spec, Uses a different template

app/client/cypress/e2e/Regression/ClientSide/Git/ExistingApps/v1.9.24/DSCrudAndBindings_Spec.ts, app/server/appsmith-git/src/main/java/com/appsmith/git/service/GitExecutorImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/imports/internal/ImportApplicationServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportApplicationServiceTests.java
Fixes https://github.com/appsmithorg/appsmith/issues/28563
>
>
>
=> fix: Call out message in git sync modal for JS library is incorrect

app/client/src/ce/selectors/entitiesSelector.ts
Fixes https://github.com/appsmithorg/appsmith/issues/28373
>
>
>
>
>
>
>
>
=> fix: null check before accessing dsl of page in getCurrentPageWidgets selector

app/client/packages/design-system/theming/src/token/src/defaultTokens.json, app/client/packages/design-system/widgets/src/components/Button/src/styles.module.css, app/client/packages/design-system/widgets/src/styles/src/field.module.css, app/client/packages/design-system/widgets/src/styles/src/inline-label.module.css, app/client/packages/design-system/widgets/src/styles/src/text-input.module.css, app/client/packages/design-system/widgets/src/testing/ComplexForm.tsx
Closes #28104
Before
https://github.com/appsmithorg/appsmith/assets/80973/1bcbcf1a-f7ba-43ac-8b74-818e883c968b
After
https://github.com/appsmithorg/appsmith/assets/80973/3e02591a-c463-425a-9ebb-d681b7dcea56
=> chore: WDS fluid tokens refinement

app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/GlobalExceptionHandler.java
> 	This PR adds more fields to the sentry error logs.
Fixes #28665 
>
>
>
>
>
>
>
>
=> chore: added downstream error code and msg to sentry

app/client/src/ce/plugins/Linting/utils/getEntityDependencies.ts
=> chore: refactor entityDependency code

app/client/src/ce/constants/messages.ts, app/client/src/components/designSystems/appsmith/header/DeployLinkButton.tsx, app/client/src/pages/Editor/gitSync/QuickGitActions/index.tsx, app/client/src/pages/Editor/gitSync/Tabs/GitSettings/GitDisconnect.tsx, app/client/src/pages/Editor/gitSync/Tabs/GitSettings/index.test.tsx, app/client/src/pages/Editor/gitSync/Tabs/GitSettings/index.tsx, app/client/src/pages/Editor/gitSync/hooks/useIsGitAdmin.ts
- Derives isGitAdmin from workspace permissions
- Disables connect to git if not git admin
- Disables disconnect, default branch and branch protection if not git admin
Fixes #28020 
>
>
>
>
>
>
>
>
=> fix: adding git admin permissions

app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/TableOrSpreadsheetDropdown/index.tsx, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/CommonControls/TableOrSpreadsheetDropdown/useTableOrSpreadsheet.tsx, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/WidgetSpecificControls/ColumnDropdown/index.tsx, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/WidgetSpecificControls/ColumnDropdown/useColumnDropdown.tsx, app/client/src/components/editorComponents/WidgetQueryGeneratorForm/WidgetSpecificControls/OtherFields/Field/Dropdown/Dropdown.tsx
Make one-click binding form controls searchable. Leverage design system `showSearch` property
Fixes https://github.com/appsmithorg/appsmith/issues/27772
>
>
>
>
>
>
>
>
>
>
>
=> feat: Make one click binding form controls searchable

app/client/src/pages/Editor/DatasourceInfo/GoogleSheetSchema.tsx
On selection of spreadsheet the scrolling of the container wasn't scrolling properly to make the selected element visible to the viewport. Since the container target was wrong and it wasn't allowed for vertical scrolling.
Fixes #28543 
https://www.loom.com/share/4afd7b54d63e4b40b6b817fcc737747b?sid=73f6e6e3-1cf0-4b3e-ba19-fd27e0d93f12
>
>
>
>
> Please describe the tests that you ran to verify your changes. Also list …
=> fix: scrolling issue in gsheet structure on clicking on spreadsheet

app/client/src/pages/AdminSettings/Authentication/AuthPage.tsx
Moving SSO to Enterprise plan
Fixes #https://github.com/appsmithorg/cloud-services/issues/1427
>
>
>
>
>
>
>
>
>
>
>
=> feat: move SSO to Enterprise plan

app/server/appsmith-server/src/main/java/com/appsmith/server/newactions/refactors/NewActionRefactoringServiceCEImpl.java
>
>
>
>
>
>
Fixes https://github.com/appsmithorg/appsmith/issues/28704
>
>
>
>
> Please delete options that …
=> fix: Update refactored entity by branched id

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/PermissionGroupServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ThemeServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/ApplicationServiceCETest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/GitServiceCETest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportApplicationServiceTests.java, app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ce/ActionExecutionSolutionCETest.java
> Adding logs to test cases.
>
>
>
>
>
>
>
>
>
>
>
>
=> chore: adding more logs to the test cases for understanding failures

app/client/cypress/support/Pages/GitSync.ts, app/client/src/actions/gitSyncActions.ts, app/client/src/ce/constants/messages.ts, app/client/src/ce/sagas/ApplicationSagas.tsx, app/client/src/pages/Editor/gitSync/QuickGitActions/index.tsx, app/client/src/pages/Editor/gitSync/Tabs/GitSettings/GitDefaultBranch.tsx, app/client/src/pages/Editor/gitSync/Tabs/GitSettings/GitProtectedBranches.tsx, app/client/src/pages/Editor/gitSync/constants.ts, app/client/src/pages/Editor/gitSync/hooks/useIsGitAdmin.ts, app/client/src/sagas/GitSyncSagas.ts
Fixes a couple of issues with branch protection
- #28727 Toast message issues
- #28726 Pull count on pull icon
- #28748 Display remote branches in list
- #28697 Pulling protected branch shows discard toast
- Added branch name to default branch toast
- #28698 Select not scrolling bug
Mentioned above
>
>
>
>
>
>
>
>
>
>
> Link issues raised during DP testing for better visiblity and tracking (copy …
=> fix: git branch protection bug fixes

app/client/src/ce/constants/messages.ts, app/client/src/layoutSystems/common/dropTarget/DropTargetComponent.tsx, app/client/src/pages/Editor/IDE/LeftPane/AddLibraryPopover.tsx
This PR fixes,
1. ‘Drag and drop a widget’ not required to show when settings pane is open.
2. Overlap of the libraries popover is seen over the left pane
3. Data Pane : Change the text workplace to workspace.
Fixes https://github.com/appsmithorg/appsmith/issues/28782
>
>
>
>
>
>
>
>
=> fix: IDE texts and alignements bugs

app/client/src/ce/utils/BusinessFeatures/permissionPageHelpers.tsx, app/client/src/ce/utils/permissionHelpers.tsx, app/client/src/components/featureWalkthrough/walkthroughRenderer.tsx
PR to split code for env walkthrough. EE PR: [#2762](https://github.com/appsmithorg/appsmith-ee/pull/2762)
Changes:
- Update CSS for walkthrough section
- Create new selector for permission checking
Fixes [#27335](https://github.com/appsmithorg/appsmith/issues/27335)
>
>
>
>
>
>
>
=> chore: split for env walkthrough PR

app/server/appsmith-server/src/main/java/com/appsmith/server/imports/internal/PartialImportServiceCEImpl.java
=> feat: partial import ui

app/client/src/pages/Editor/gitSync/components/BranchList.tsx, app/client/src/selectors/gitSyncSelectors.tsx
Fetching updated protected branches when new branch list is synced
Fixes #28826
>
>
>
>
>
>
>
=> fix: calling protected branches on sync

app/client/src/widgets/ExternalWidget/component/reset.css
=> chore: Fix prettier issue in the reset css file

app/client/src/ce/constants/messages.ts, app/client/src/components/editorComponents/PartialImportExport/PartialExportModal/StyledSheet.ts, app/client/src/components/editorComponents/PartialImportExport/PartialExportModal/WidgetsExport.tsx, app/client/src/components/editorComponents/PartialImportExport/PartialExportModal/index.tsx, app/client/src/sagas/TemplatesSagas.ts, app/client/src/sagas/WidgetSelectionSagas.ts
Adds concise widget selection logic that does not create confusion.
>
>
>
>
>
>
>
>
> Please describe the tests that you ran to verify your changes. Also list any relevant details for …
=> fix: widget selection issues

app/client/cypress/e2e/Regression/ClientSide/Git/GitWithJSLibrary/GitwithCustomJSLibrary_spec.js
Fixes failing test GitWithCustomJSLibrary_spec.js
>
>
>
>
>
>
>
>
=> test: Cypress| fix test GitWithCustomJSLib

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ce/ActionCE_DTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/actioncollections/base/ActionCollectionServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/actioncollections/base/ActionCollectionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/ce/ActionCollectionCE_DTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/newactions/base/NewActionServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/newactions/base/NewActionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomActionCollectionRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomActionCollectionRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCEImpl.java
This PR adds ~contextId~ and contextType fields in the executables i.e. ActionCE_DTO and ActionCollectionCE_DTO. The eventual plan is to move pageId to contextId with contextType as PAGE.
Fixes https://github.com/appsmithorg/appsmith/issues/28797
>
>
>
>
>
>
> …
=> chore: Add `contextId` and `contextType` in executables

app/client/cypress/e2e/Regression/ClientSide/Linting/BasicLint_spec.ts, app/client/cypress/e2e/Sanity/Datasources/SMTPDatasource_spec.js, app/client/src/pages/Editor/Explorer/Pages/PageContextMenu.tsx, app/client/src/pages/Editor/IDE/LeftPane/AddLibraryPopover.tsx
=> fix: Sidebar release blockers

app/client/src/pages/Editor/DataSourceEditor/JSONtoForm.tsx
Introduced a hook call inside a class component in https://github.com/appsmithorg/appsmith/pull/28876
This change fixes it
fixes: #28894
=> fix: bad hook call in class component

app/client/src/pages/Editor/gitSync/QuickGitActions/index.tsx, app/server/appsmith-plugins/openAiPlugin/src/main/java/com/external/plugins/OpenAiPlugin.java, app/server/appsmith-plugins/openAiPlugin/src/main/java/com/external/plugins/commands/ChatCommand.java, app/server/appsmith-plugins/openAiPlugin/src/main/java/com/external/plugins/commands/EmbeddingsCommand.java, app/server/appsmith-plugins/openAiPlugin/src/main/java/com/external/plugins/commands/VisionCommand.java, app/server/appsmith-plugins/openAiPlugin/src/main/java/com/external/plugins/constants/OpenAIConstants.java, app/server/appsmith-plugins/openAiPlugin/src/main/java/com/external/plugins/constants/OpenAIErrorMessages.java, app/server/appsmith-plugins/openAiPlugin/src/main/java/com/external/plugins/models/QueryType.java, app/server/appsmith-plugins/openAiPlugin/src/main/java/com/external/plugins/models/UserContent.java, app/server/appsmith-plugins/openAiPlugin/src/main/java/com/external/plugins/models/UserImageContent.java, app/server/appsmith-plugins/openAiPlugin/src/main/java/com/external/plugins/models/UserQuery.java, app/server/appsmith-plugins/openAiPlugin/src/main/java/com/external/plugins/models/UserTextContent.java, app/server/appsmith-plugins/openAiPlugin/src/main/java/com/external/plugins/models/VisionMessage.java, app/server/appsmith-plugins/openAiPlugin/src/main/java/com/external/plugins/models/VisionRequestDTO.java, app/server/appsmith-plugins/openAiPlugin/src/main/java/com/external/plugins/utils/OpenAIMethodStrategy.java, app/server/appsmith-plugins/openAiPlugin/src/main/java/com/external/plugins/utils/RequestUtils.java, app/server/appsmith-plugins/openAiPlugin/src/main/resources/editor/chat.json, app/server/appsmith-plugins/openAiPlugin/src/main/resources/editor/embeddings.json, app/server/appsmith-plugins/openAiPlugin/src/main/resources/editor/root.json, app/server/appsmith-plugins/openAiPlugin/src/main/resources/editor/vision.json, app/server/appsmith-plugins/openAiPlugin/src/test/java/com/external/plugins/VisionCommandTest.java
Release v1.9.46
>
>
> Please describe the tests that you ran to verify your changes. Also
list any relevant details for your test configuration.
>
>
>
>
(copy link from comments dropped on this PR)
>
>
>
=> fix: enable pull when branch is protected (#28901)

app/client/src/pages/WidgetBuilder/index.tsx
=> chore: fix copy paste issue in custom widget builder

app/client/cypress/e2e/Regression/Apps/MongoDBShoppingCart_spec.ts
Skips MongoDBShoppingCart_spec.js tests to unblock CI
=> test: Cypress| skip failing cypress tests

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/exceptions/pluginExceptions/AppsmithPluginError.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/exceptions/pluginExceptions/AppsmithPluginErrorCode.java, app/server/appsmith-plugins/openAiPlugin/src/main/java/com/external/plugins/OpenAiPlugin.java
> Introduced a new error to address Appsmith Error type handling Plugin authentication errors
>
>
>
=> fix: modified error code for unauthorised trigger and execute calls

app/client/cypress/e2e/Regression/Apps/MongoDBShoppingCart_spec.ts, app/client/cypress/limited-tests.txt
- Flaky fix /Apps/MongoDBShoppingCart_spec.ts for CI runs
=> test: Cypress | Flaky fix /Apps/MongoDBShoppingCart_spec.ts for CI runs

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/DataUtils.java, app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
> Pr to preserve order of keys in body
Fixes #23456
>
>
>
>
>
=> fix: modified now issues preserve key order

app/client/cypress/e2e/Regression/ClientSide/Git/GitSync/GitSyncedApps_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/Modal/Modal_spec.ts
Skipping below caswes 
1. GitSyncedApps_spec.js
2. Modal_spec.ts
=> test: Cypress - skipping flaky cases in ce 

app/client/src/ce/constants/messages.ts
=> chore: Minor update to modal copy after Git Connect

app/client/cypress/support/Pages/HomePage.ts, app/client/cypress/support/commands.js
Modifying the cypress tests to account for the changes in EE to change logout to a Document GET request
Fixes https://github.com/appsmithorg/appsmith-ee/issues/1185
>
>
>
>
>
>
>
>
>
>
>
>
>
=> chore: changes to accomodate logout being a GET call in EE

app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesPage_filtering_spec.ts, app/client/src/ce/constants/messages.ts, app/client/src/components/editorComponents/PartialImportExport/PartialExportModal/index.tsx
This pull request fixes an issue where the reset click for "JS objects" was not functioning correctly. The reset click now works as expected.
Fix capitalization of "JS objects" in export modal
>
>
>
>
>
>
>
>
=> fix: Fixes reset click for jsobjects

.github/workflows/rts-build-self-host.yml
=> test: self-hosted github runner

app/client/src/ce/constants/messages.ts, app/client/src/pages/Editor/IDE/LeftPane/PaneHeader.tsx
=> fix: Datasource Title style issues

app/client/src/ce/utils/FilterInternalProperties/getEntityPeekData.ts, app/client/src/ee/utils/FilterInternalProperties/getEntityPeekData.ts, app/client/src/utils/FilterInternalProperties/__tests__/index.test.ts, app/client/src/utils/FilterInternalProperties/index.ts
Peekoverlay changes for moduleInput
- Introduce `getEntityPeekData` that will be extended in EE codebase for moduleInput entity
>
>
>
>
>
>
>
>
=> chore: Peekoverlay for moduleInputs

app/server/appsmith-server/src/main/java/com/appsmith/server/newactions/base/NewActionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/refactors/applications/RefactoringSolutionCEImpl.java
Make fields more visible to children and make pattern reusable.
=> chore: Modified visibility of a few deps

app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/ce/RefactorEntityNameCE_DTO.java
=> chore: Added constructor for CE DTO for refactor

app/client/src/sagas/DebuggerSagas.ts, app/client/src/sagas/EvaluationsSaga.ts, app/client/src/utils/AnalyticsUtil.tsx
This PR prevents logging of error analytics on first page load, and page navigation
Fixes #29018 
>
>
>
>
>
>
>
>
> Add …
=> chore: Prevent logging error analytics on first page load

app/client/src/ce/workers/Evaluation/fns/utils/isRunNClearFnQualifierEntity.ts, app/client/src/ce/workers/Evaluation/getEntityForEvalContextMap.ts, app/client/src/ee/workers/Evaluation/fns/utils/isRunNClearFnQualifierEntity.ts, app/client/src/ee/workers/Evaluation/getEntityForEvalContextMap.ts, app/client/src/workers/Evaluation/fns/index.ts, app/client/src/workers/Evaluation/getEntityForContext.ts, app/client/src/workers/Evaluation/getJSActionForEvalContext.ts
Change for set evalContext for module instance
Fixes #
>
>
>
>
>
>
>
>
=> chore: create evalContext for module instance CE changes

deploy/docker/fs/etc/supervisor/supervisord.conf
=> chore: Increase buffer size for supervisor events to 10000

deploy/docker/fs/etc/supervisor/supervisord.conf
This is a hotfix commit for [this issue](https://github.com/appsmithorg/appsmith/issues/29032#event-11035745390)
=> chore: hotfix: supervisord buffer size increase

app/server/appsmith-server/src/main/java/com/appsmith/server/actioncollections/refactors/ActionCollectionRefactoringServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/newactions/refactors/NewActionRefactoringServiceCEImpl.java
Contains split for a few reusable concepts in refactor flow
=> chore: Split get existing entities for refactor

app/client/packages/design-system/widgets-old/package.json, app/client/yarn.lock
Remove redundant `wait-on` package
=> chore: remove redundant package

app/client/src/pages/Editor/Explorer/Pages/PageContextMenu.tsx, app/client/src/pages/Editor/Explorer/Pages/index.tsx
This pull request adds a check to the `PageContextMenu` component to ensure that developers with the right access can use the export feature. This check is necessary to prevent unauthorized users from exporting sensitive data.
>
>
>
>
- Chore (housekeeping or task changes that don't impact user …
=> fix: Add check for export permission in PageContextMenu

app/client/src/widgets/ChartWidget/widget/index.test.ts, app/client/src/widgets/ChartWidget/widget/index.tsx
This PR replaces the announcement link for deprecation of fusion charts.
=> chore: Update learn more documentation link for echarts

app/client/src/ce/constants/messages.ts, app/client/src/ce/entities/FeatureFlag.ts, app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx
> Adds a larger JS toggle button in property pane based on feature flag
>
>
>
Fixes #28918 
>
>
>
>
- Experimental
>
>
>
>
>
>
>
>
>
>
=> chore: Experimental JS toggle based on feature flag

app/client/.lintstagedrc.json, contributions/CodeContributionsGuidelines.md
The `gitleaks` project provides a more out-of-the-box experience and is able to find more than AWS keys in the files.
=> chore: Switch to gitleaks from git-secrets

app/server/appsmith-server/src/main/java/com/appsmith/server/layouts/UpdateLayoutServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/layouts/UpdateLayoutServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutCollectionServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceImplTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutActionServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/ActionServiceCE_Test.java
=> chore: Split update layout

app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/ActionViewDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/ce/ActionViewCE_DTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/newactions/base/NewActionServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/newactions/base/NewActionServiceCEImpl.java
>
>
>
>
>
>
Fixes #29155
>
>
- …
=> chore: Split ActionViewDTO

app/client/cypress/support/commands.js
Fix Cypress Test cases related to License flow in case the Instance does not start with a License
Fixes #29166
>
>
>
>
>
>
>
>
=> fix: run validateLicense in case we are at /license after login

app/server/appsmith-server/src/main/java/com/appsmith/server/newactions/base/NewActionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/refactors/applications/RefactoringServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/refactors/ce/RefactoringServiceCEImplTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/refactors/ce/RefactoringServiceCETest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/refactors/ce/RefactoringServiceTest.java
Contains changes to be able to consume refactor service correctly after split
=> chore: Changes for refactor service split

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/Executable.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ce/ActionCE_DTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/onload/internal/OnLoadExecutablesUtilCEImpl.java
Contains split related changes for update layout only.
=> chore: Split related to update layout changes

app/client/src/ce/pages/Applications/CreateNewAppsOption.tsx, app/client/src/pages/Editor/IntegrationEditor/CreateNewDatasourceTab.tsx, app/client/src/sagas/ApiPaneSagas.ts
This PR fixes:
- UI issues with respect to the container that we show when users go through start with data flow
- Issue with Authenticated and Authenticated GraphQL API, when user select start with data flow, if we they select any of these two and save datasource, it was leading to invalid URL page. 
Fixes #29163 
>
>
>
>
>
>
>
>
> Delete anything that is …
=> fix: start with data onboarding issue fixes

app/client/src/entities/Engine/AppEditorEngine.ts, app/client/src/sagas/GitSyncSagas.ts
Git-connected apps are taking substantially more time to load compared to normal apps
The primary reason was due to long-running blocking API calls for `git status` and `git fetch`. This PR makes the blocking API calls run in the background instead
Fixes #29169
Previously
Now
>
>
>
>
>
>
>
>
>
>
>
=> fix: fixing non blocking calls

app/server/appsmith-plugins/openAiPlugin/src/main/java/com/external/plugins/OpenAiPlugin.java
=> chore: resolve merge conflicts in release PR

app/server/appsmith-server/src/main/java/com/appsmith/server/refactors/applications/RefactoringServiceCEImpl.java
Removed name validation for widgets as before.
=> fix: Removed entity name validation for widgets

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/CreatorContextType.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/CustomJSLib.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ce/CustomJSLibCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/CustomJSLibApplicationDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/ce/CustomJSLibApplicationCE_DTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/jslibs/base/CustomJSLibServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomJSLibRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomJSLibRepositoryCEImpl.java
Contains changes to be able to work with custom js libs locally as well.
=> chore: Split for custom js libs with local scope

app/client/cypress/e2e/Sanity/Datasources/SMTPDatasource_spec.js, app/client/cypress/fixtures/SMTPTestdsl.json, app/client/src/sagas/ActionExecution/PluginActionSaga.ts
Revert #28841
>
>
>
>
>
>
>
- Chore …
=> fix: revert #28841

app/server/appsmith-server/src/main/java/com/appsmith/server/jslibs/base/CustomJSLibServiceCEImpl.java
Changes to accommodate only public custom js in get call
=> chore: Changes to accommodate only public custom js libs in get call

app/client/src/entities/JSCollection/index.ts
JSCollection typing changes
Fixes for https://github.com/appsmithorg/appsmith-ee/pull/2910
>
>
>
>
>
>
>
>
>
>
=> chore: jscollection typing changes

app/server/appsmith-server/src/main/java/com/appsmith/server/newactions/base/NewActionServiceCEImpl.java
Contains a method split for validate action name
=> fix: Split validateActionName

app/client/src/widgets/ChartWidget/component/CustomEChartIFrameComponent.tsx, app/client/src/widgets/ChartWidget/component/index.test.tsx, app/client/src/widgets/ChartWidget/component/index.tsx
=> fix: fix overlay echarts iframe

app/client/cypress/support/Constants.js, app/client/cypress/support/Objects/FeatureFlags.ts
Add test cases for Audit Logs feature in the Context of 1-Click
Fixes [2420 ](https://github.com/appsmithorg/appsmith-ee/issues/2420)
>
>
>
>
>
>
>
>
>
>
>
>
>
=> feat: add intercept for license flags

app/client/packages/design-system/headless/src/components/Field/src/Field.tsx, app/client/packages/design-system/widgets/src/styles/src/field.module.css, app/client/packages/design-system/widgets/src/styles/src/text-input.module.css
Fixes #29091
Fixes #29086
Fixes #29088
=> fix: WDS Input widget bugs

app/server/appsmith-plugins/anthropicPlugin/src/main/resources/form.json, app/server/appsmith-plugins/openAiPlugin/src/main/resources/form.json
added from.json for datasource config to have `authenticationType`  without fail
=> fix: modified form.json for solving the issue

app/client/cypress/e2e/Regression/ClientSide/BugTests/SortedSchema_Spec.ts, app/client/src/ce/selectors/entitiesSelector.ts, app/client/src/utils/WorkerUtil.ts, app/client/src/workers/Evaluation/JSObject/utils.ts, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/connections/OAuth2AuthorizationCode.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/connections/OAuth2ClientCredentials.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/restApiUtils/helpers/RestAPIActivateUtils.java, app/server/appsmith-plugins/anthropicPlugin/src/main/resources/form.json, app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/FileInfoMethod.java, app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/FileListMethod.java, app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java, app/server/appsmith-plugins/openAiPlugin/src/main/resources/form.json, app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java, app/server/appsmith-plugins/postgresPlugin/src/test/java/com/external/plugins/PostgresPluginTest.java, app/server/appsmith-server/src/main/java/com/appsmith/server/actioncollections/base/ActionCollectionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/newactions/base/NewActionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PolicySolutionCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PolicySolutionCEImpl.java, deploy/docker/fs/opt/appsmith/caddy-reconfigure.mjs, deploy/docker/fs/opt/appsmith/starting-page-init.py
=> 13/12 Daily Promotion

.github/workflows/test-build-docker-image.yml
> Added a cron job for the TBP workflow to run at 6 am on weekdays-  Daily Promotion analysis purpose
- To check if the workflow is triggered as expected
=> ci: Added cron at 6 am ist on tbp ce workflow

app/server/appsmith-server/src/main/java/com/appsmith/server/applications/jslibs/ApplicationJsLibServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/newactions/exports/NewActionExportableServiceImpl.java
=> test: introduce conflict

app/client/packages/design-system/theming/src/color/src/DarkModeTheme.ts, app/client/packages/design-system/theming/src/color/src/LightModeTheme.ts, app/client/packages/design-system/theming/src/color/src/types.ts, app/client/packages/design-system/theming/src/theme/stories/Color.stories.mdx, app/client/packages/design-system/theming/src/token/src/defaultTokens.json, app/client/packages/design-system/theming/src/token/src/styles.module.css, app/client/packages/design-system/theming/src/token/src/themeTokens.json, app/client/packages/design-system/widgets/src/components/Menu/src/styles.module.css, app/client/packages/storybook/.storybook/preview-head.html, app/client/packages/storybook/src/components/StoryThemeProvider.tsx, app/client/packages/storybook/src/components/TokenTable.tsx
=> chore: add shadow elevation color tokens

.github/workflows/server-build.yml
=> CI: fixed token

.github/workflows/server-build.yml
=> CI: fixed clone dir

.github/workflows/server-build.yml
=> CI: commented caching changes

app/server/appsmith-server/src/main/java/com/appsmith/server/actioncollections/refactors/ActionCollectionRefactoringServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/widgets/refactors/WidgetRefactoringServiceCEImpl.java
Split changes to allow refactor to use view mode when gathering entities
=> chore: Split changes for refactor based on view mode

app/server/pom.xml
=> chore(deps): Update logback

.github/workflows/client-build.yml
=> CI: fix client cache sequence

app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/ConsolidatedAPIResponseDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ConsolidatedAPIServiceImpl.java
- Update variable names to make them more understandable
- Fix an error handling clause wherein the error was not caught at the right place. 
- Replace with defaults:
- when workspace Id is not found then don't supply workspace Id to downstream sub-APIs (effectively passing null value which is handled via validation check in the sub-APIs).
- when feature flag API errors out, then assign false value to migrate DSL flag
- This PR is targeted to be merged in development branch `oneApiChanges` instead of `release`  
Fixes #29994 #29995
>
> Delete …
=> chore: consolidated API: update variable names, fix error propagation, handle defaults in case error

app/client/src/ce/selectors/applicationSelectors.tsx, app/server/appsmith-interfaces/src/main/java/com/appsmith/util/WebClientUtils.java
=> fix: Adding release blocker fixes to master CE

app/server/appsmith-plugins/mongoPlugin/pom.xml, app/server/appsmith-server/pom.xml, app/server/pom.xml
Solves for these CVEs:
1. CVE-2021-36090
2. CVE-2021-35517
3. CVE-2021-35516
4. CVE-2021-35515
=> chore(deps): Update commons-compress

app/client/src/pages/Editor/IDE/EditorPane/PagesSection.tsx
=> fix: fix incorrect import issue

app/client/src/ce/pages/Applications/index.tsx, app/client/src/ce/utils/workspaceHelpers.ts
Fetching workflows based on workspace id
>
>
>
>
>
>
>
>
>
> …
=> chore: Fetching workflows based on workspace id

app/client/src/components/common/Card.tsx
export options menu visibility issue in homepage v2 project
>
>
>
>
>
>
>
>
>
>
> Please describe the tests that you ran to verify your changes. Also list any relevant details for …
=> fix: export options menu visibility issue in homepage v2 project

app/client/src/ce/sagas/WorkspaceSagas.ts
fix deleting the last workspace causes a toast error
>
>
>
>
>
>
>
> …
=> fix: fix deleting the last workspace causes a toast error

app/client/src/ce/constants/messages.ts, app/client/src/ce/pages/Applications/WorkspaceAction.tsx, app/client/src/sagas/PartialImportExportSagas/PartialImportSagas.ts
=> fix: make create new buttons consistent across CE and EE

app/client/src/ce/pages/Applications/index.tsx, app/client/src/ce/sagas/WorkspaceSagas.ts
Multiple api calls on create new workspace
#30392 
>
>
>
>
>
>
>
>
> Add Testsmith test cases links that …
=> fix: multiple api calls on create new workspace

app/client/src/ce/pages/Applications/index.tsx, app/client/src/ce/sagas/WorkspaceSagas.ts
Not showing more options dropdown when no options are there
>
https://github.com/appsmithorg/appsmith/issues/30377
>
>
>
>
>
>
>
>
>
> Link issues raised during DP testing for …
=> fix: not showing more options dropdown when no options are there

app/client/src/pages/common/SearchBar/HomepageHeaderAction.tsx
=> fix: remove guided tour since its been removed from release

app/client/src/ce/actions/workspaceActions.ts, app/client/src/ce/pages/Applications/index.tsx, app/client/src/ce/sagas/WorkspaceSagas.ts
fragment to query params for workspace selection in homepage
>
>
>
>
>
>
>
>
> …
=> chore: fragment to query params for workspace selection in homepage

app/client/packages/storybook/package.json, app/client/yarn.lock
Re - https://github.com/appsmithorg/appsmith/pull/30485
=> chore(deps): Update vite

app/client/cypress/e2e/Regression/ClientSide/Templates/Filtering/TemplatesModal_filtering_spec.ts, app/client/cypress/e2e/Regression/ClientSide/Templates/Fork_Template_spec.js
Due to the removal of the Templates tab, the fork_templates spec file needs to be modified in according with the onboarding flow. Reconnect Datasource test is moved to a more appropriate spec file.
>
>
>
>
- This change requires …
=> fix: fix fork application spec

app/client/src/ce/components/gitComponents/GitSettingsCDTab/UnlicensedGitCD.tsx, app/client/src/ce/components/gitComponents/GitSettingsCDTab/index.tsx, app/client/src/ce/constants/messages.ts, app/client/src/ce/entities/FeatureFlag.ts, app/client/src/ee/components/gitComponents/GitSettingsCDTab/index.tsx, app/client/src/pages/Editor/gitSync/GitSettingsModal/TabBranch/GitDefaultBranch.tsx, app/client/src/pages/Editor/gitSync/GitSettingsModal/TabBranch/index.tsx, app/client/src/pages/Editor/gitSync/GitSettingsModal/TabGeneral/index.tsx, app/client/src/pages/Editor/gitSync/GitSettingsModal/index.tsx
Part of continuous delivery with git feature. Includes CE UI elements for "Continuous delivery" tab. Utilizes feature flag `release_git_continuous_delivery_enabled` to hide the implementation from UI
Fixes #30510 
- New feature (non-breaking change which adds functionality)\
>
>
>
>
>
>
>
>
=> feat: adding continuous delivery tab in git settings

app/client/cypress/e2e/Regression/ClientSide/ActionExecution/ActionSelector_JsToNonJSMode_1_spec.ts, app/client/cypress/e2e/Regression/ClientSide/ActionExecution/ActionSelector_JsToNonJSMode_2_spec.ts, app/client/cypress/e2e/Regression/ClientSide/Branding/Branding_spec.js, app/client/cypress/e2e/Regression/ClientSide/ExplorerTests/Admin_settings_3_spec.ts, app/client/cypress/e2e/Regression/ClientSide/ExplorerTests/Widgets_Sidebar.ts, app/client/cypress/e2e/Regression/ClientSide/Fork/ForkApplicationReconnectModal_spec.ts, app/client/cypress/e2e/Regression/ClientSide/Linting/ErrorReporting_spec.ts, app/client/cypress/e2e/Regression/ClientSide/Onboarding/StartFromScratch_spec.ts, app/client/cypress/e2e/Regression/ClientSide/OtherUIFeatures/ExportApplication_spec.js, app/client/cypress/e2e/Regression/ClientSide/OtherUIFeatures/Replay_spec.js, app/client/cypress/e2e/Regression/ClientSide/Templates/Fork_Template_spec.js, app/client/cypress/e2e/Regression/ClientSide/ThemingTests/Basic_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/Custom/CustomWidgetDefaultComponent_spec.ts, app/client/cypress/e2e/Regression/ClientSide/Widgets/ListV2/Childwigets/List_Inputs_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/ListV2/Childwigets/List_Select_Widgets_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/Widgets_Labels_spec.js, app/client/cypress/e2e/Regression/ClientSide/Workspace/DeleteWorkspace_spec.ts, app/client/cypress/e2e/Regression/ClientSide/Workspace/LeaveWorkspaceTest_spec.js, app/client/cypress/e2e/Regression/ClientSide/Workspace/MemberRoles_Spec.ts, app/client/cypress/locators/TemplatesLocators.json, app/client/cypress/support/Pages/AdminSettings.ts, app/client/cypress/support/Pages/DataSources.ts, app/client/cypress/support/Pages/EditorNavigation.ts, app/client/cypress/support/Pages/EntityExplorer.ts, app/client/cypress/support/Pages/HomePage.ts, app/client/cypress/support/Pages/IDE/LeftPane.ts, app/client/cypress/support/WorkspaceCommands.js, app/client/cypress/support/commands.js
This PR adds the changes which were made in the EE repo for fixing cypress flakiness
>
>
>
>
>
>
>
> …
=> fix: cypress flaky fixes

app/client/src/layoutSystems/anvil/utils/paste/destinationUtils.ts, app/client/src/layoutSystems/anvil/utils/paste/mainCanvasPasteUtils.ts
1. Enable copy paste of entire modal on the MainCanvas.
=> feat: copy paste of entire modal

app/server/appsmith-server/src/main/java/com/appsmith/server/projections/IdOnly.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/ApplicationRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomApplicationRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomApplicationRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserDataServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/repositories/CustomApplicationRepositoryImplTest.java
This query doesn't need a custom query implementation. Switching to standard spring-data query method, so it can translate to Postgres easy.
=> chore: Use standard spring-data query method

.github/workflows/server-build.yml, app/server/appsmith-server/src/test/java/com/appsmith/server/TestResultLoggerExtension.java
And, don't show duplicates. Not sure why we're seeing duplicates though.
=> ci: Add server failed tests as PR comment

app/client/src/pages/Editor/IDE/LeftPane/DataSidePane.tsx
=> fix: Added airgap helper for datasource icon URL (#31027)

app/client/cypress/locators/WidgetLocators.ts
Fixes button group spec that started failing because of #30439
=> fix: button group spec

app/client/cypress/e2e/Regression/ClientSide/Onboarding/StartFromData_spec.ts, app/client/cypress/support/Pages/ApiPage.ts, app/client/cypress/support/Pages/DataSources.ts, app/client/src/ce/hooks/importModal/useMessages.ts, app/client/src/ce/hooks/importModal/useMethods.ts, app/client/src/ce/pages/Applications/index.tsx, app/client/src/ce/pages/Editor/IDE/MainPane/useMissingModuleNotification.tsx, app/client/src/components/editorComponents/GlobalSearch/HelpBar.tsx, app/client/src/ee/hooks/importModal/useMessages.ts, app/client/src/ee/hooks/importModal/useMethods.ts, app/client/src/ee/pages/Editor/IDE/MainPane/useMissingModuleNotification.tsx, app/client/src/pages/Editor/AppSettingsPane/AppSettings/ImportAppSettings.tsx, app/client/src/pages/Editor/Explorer/Entity/AddButton.tsx, app/client/src/pages/Editor/Explorer/Pages/AddPageContextMenu.tsx, app/client/src/pages/Editor/IDE/EditorPane/PagesSection.tsx, app/client/src/pages/Editor/IDE/Header/EditorTitle.tsx, app/client/src/pages/Editor/IDE/Header/index.tsx, app/client/src/pages/Editor/IDE/LeftPane/AppSettings.tsx, app/client/src/pages/Editor/IDE/LeftPane/PaneHeader.tsx, app/client/src/pages/Editor/WidgetsEditor/index.tsx, app/client/src/pages/Editor/commons/EditorSettingsPaneContainer.tsx, app/client/src/pages/common/ImportModal.tsx
>
>
14/02 Daily Promotion
>
>
>
>
>
>
>
>
- New …
=> 14/02 Daily Promotion

.github/workflows/ci-client-cyclic-deps-check.yml, app/client/scripts/cyclicDepsCheck.js
=> Fix formatting of output in github workflow

.github/workflows/integration-tests-command-2.yml, .github/workflows/ok-to-test-2.yml
=> ci: Added an alternate ok-to-test path

.github/workflows/ok-to-test-2.yml
Force merging for testing, does not affect prod
=> ci: Make sure target is release branch for new flow

.github/pull_request_template.md
=> ci: Simplified PR template to align with ok-to-test

.github/pull_request_template.md, .github/workflows/integration-tests-command-2.yml, .github/workflows/ok-to-test-2.yml
> [!TIP]  
> _Add a TL;DR when the description is longer than 500 words or extremely technical (helps the content team)._
>
_or_  
> [!WARNING]  
################# _Do Not Edit This Area_ #################
> [!CAUTION]  
###################################################
=> ci: Prettify and remove redundancies

.github/workflows/ci-test-custom-script.yml, app/client/test/testUtils.tsx, app/server/appsmith-server/src/main/java/com/appsmith/server/aspect/FeatureFlaggedMethodInvokerAspect.java, app/server/appsmith-server/src/test/java/com/appsmith/server/aspect/FeatureFlaggedMethodInvokerAspectTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/aspect/component/TestComponentImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/aspect/component/ce/TestComponentCE.java, app/server/appsmith-server/src/test/java/com/appsmith/server/aspect/component/ce/TestComponentCEImpl.java
> [!TIP]  
> _Add a TL;DR when the description is longer than 500 words or extremely technical (helps the content team)._
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> 19/03 Daily Promotion(attempt 2)

app/client/yarn.lock
Fixes https://github.com/appsmithorg/appsmith/security/dependabot/286
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8416483932>
> Commit: `3dde3b98a57c76152a93f1a7f2161103e536f9ac`
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8416483932&attempt=1" target="_blank">Click here!</a>
=> chore(deps): Update follow-redirects to 1.15.6

app/client/cypress/e2e/Regression/Apps/PgAdmin_spec.js, app/client/cypress/e2e/Regression/ClientSide/IDE/Canvas_Context_Property_Pane_1_spec.js, app/client/cypress/e2e/Regression/ClientSide/IDE/Canvas_Context_Property_Pane_2_spec.js, app/client/cypress/limited-tests.txt, app/client/src/actions/evaluationActions.ts, app/client/src/ce/workers/Evaluation/__tests__/dataTreeUtils.test.ts, app/client/src/ce/workers/Evaluation/dataTreeUtils.ts, app/client/src/pages/Editor/PropertyPane/PropertySection.tsx, app/client/src/reducers/evaluationReducers/treeReducer.ts, app/client/src/sagas/EvaluationSaga.utils.ts, app/client/src/workers/Evaluation/__tests__/generateOpimisedUpdates.test.ts, app/client/src/workers/Evaluation/evalTreeWithChanges.ts, app/client/src/workers/Evaluation/fns/resetWidget.ts, app/client/src/workers/Evaluation/handlers/evalTree.ts, app/client/src/workers/Evaluation/helpers.ts, app/client/src/workers/common/DataTreeEvaluator/index.ts, app/client/src/workers/common/DataTreeEvaluator/validationUtils.ts
> [!TIP]  
> _Add a TL;DR when the description is longer than 500 words or extremely technical (helps the content team)._
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: Daily promotion part 2 for 27th March, 2024

app/client/src/ce/sagas/userSagas.tsx, app/client/src/pages/Editor/WidgetsEditor/components/MainContainerWrapper.tsx
Deleted empty canvas space for new app
Fixes #32062 
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8598252297>
> Commit: `5f11d7425a89869753a10854d91c2a228623fd44`
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8598252297&attempt=1" target="_blank">Click here!</a>
=> fix:canvas empty space

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/SegmentConfig.java
=> fix: NPE in SegmentConfig

app/client/src/ce/sagas/userSagas.tsx
This PR reverts the test anvil code that was added in #32493
=> revert: anvil flags

.github/workflows/pr-automation.yml, .github/workflows/pr-cypress.yml
[Slack conversation](https://theappsmith.slack.com/archives/C06SQRK1PGW/p1712735164117619).
=> Better and more visible colors

app/client/src/pages/Editor/IDE/LeftPane/DataSidePane.tsx
Fix spacing in Data list
Fixes #32597  
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8644981445>
> Commit: f404bdab4e4fd2cddfcca060bdd75d0ac5390322
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8644981445&attempt=1" target="_blank">Click here!</a>
=> fix: Data list styling

app/client/src/actions/featureFlagActions.ts, app/client/src/ce/entities/FeatureFlag.ts, app/client/src/ce/selectors/featureFlagsSelectors.ts, app/client/src/reducers/uiReducers/usersReducer.ts, app/client/src/utils/hooks/useFeatureFlagOverride.ts, app/client/src/utils/storage.ts
[![workerB](https://img.shields.io/endpoint?url=https%3A%2F%2Fworkerb.linearb.io%2Fv2%2Fbadge%2Fprivate%2FU2FsdGVkX1RhworVRJTWKPbR01bvcARyY7mXv5SA%2Fcollaboration.svg%3FcacheSeconds%3D60)](https://workerb.linearb.io/v2/badge/collaboration-page?magicLinkId=-JgUAyW)
Fixing type check fails.
_or_  
> [!WARNING]  
/ok-to-test tags="@tag.MobileResponsive"
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8647236269>
> Commit: b2aa34efcacd0c5603b45dd177d8259500ee8c38
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d74 …
=> chore: fix ee type checks issue.

app/client/cypress/e2e/Regression/ClientSide/BugTests/GitBugs_Spec.ts, app/client/cypress/support/Pages/AutoLayout.ts, app/client/src/pages/Editor/gitSync/components/GitChangesList/NewChangesList.test.tsx, app/server/appsmith-git/src/main/java/com/appsmith/git/service/ce/GitExecutorCEImpl.java
Fixes broken builds due to missing overriden base methods
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8650609417>
> Commit: 9bf9e6d75b4bf29adfd65d16504ebcd2f451d32a
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8650609417&attempt=1" target="_blank">Click here!</a>
=> fix: missing methods in gitexecutorceimpl

app/client/public/index.html
> [!TIP]  
> _Add a TL;DR when the description is longer than 500 words or extremely technical (helps the content team)._
>
This PR removes unused environment variable
_or_  
> [!WARNING]  
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8613707077>
> Commit: `f86cfafda68bc6281dc3f7f431f4756d5f0c61af`
> Cypress dashboard url: <a …
=> chore: Remove unused environment variable

.github/workflows/pr-automation.yml
=> CI: Fix label Checker

.github/workflows/pr-automation.yml
=> CI: fix checkout for label

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/Datasource.java, app/server/appsmith-server/src/main/java/com/appsmith/server/fork/internal/ApplicationForkingServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/projections/IdPoliciesOnly.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/ActionCollectionRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomDatasourceRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomDatasourceRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/DatasourceRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/NewActionRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/NewPageRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java
PR to add IdPolicies record to make it easier to translate existing queries using the projections to JPA.
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8736013169>
> Commit: c2a024129eb899057db4dc1598515b90be567076
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8736013169&attempt=1" target="_blank">Click here!</a>
=> chore: Introduce IdPoliciesOnly record to handle projections

deploy/docker/fs/opt/appsmith/entrypoint.sh
Fixes: [21899](https://github.com/appsmithorg/appsmith/issues/21899)
=> [feat]: print appsmith info details in startup

app/server/appsmith-git/src/main/java/com/appsmith/git/service/ce/GitExecutorCEImpl.java
Fixes https://github.com/appsmithorg/appsmith/issues/32970
> [!CAUTION]  
=> fix: Remove atomic pushes temporarily

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/SecurityConfig.java, app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java, app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithErrorCode.java, app/server/appsmith-server/src/main/java/com/appsmith/server/filters/CSRFFilter.java
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8933699110>
> Commit: 4cdfd6a4c04e69fb16d841359df7cbd727f8254b
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8933699110&attempt=1" target="_blank">Click here!</a>
=> chore: Respond with 403 for missing CSRF header

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/SecurityConfig.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/User.java, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/UserSessionDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java, app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithErrorCode.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8934500674>
> Commit: 849a786269d97024b2b22a158845de7e48a08900
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8934500674&attempt=1" target="_blank">Click here!</a>
=> chore: Remove unused User.currentWorkspaceId

app/server/appsmith-git/src/main/java/com/appsmith/git/service/ce/GitExecutorCEImpl.java
Bug introduced in https://github.com/appsmithorg/appsmith/pull/33109
=> fix: Fixed path creation during commit

app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Plugin.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Tenant.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/User.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ce/ActionCollectionCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ce/NewActionCE.java
Add @Enumerated(EnumType.STRING) to all the enum fields in https://github.com/entity annotated classes
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: Add Enumerated type:string annotation on enum fields in entity classes

app/client/packages/design-system/widgets/src/components/Button/src/Button.tsx, app/client/packages/design-system/widgets/src/components/ButtonGroup/src/useButtonGroup.tsx, app/client/packages/design-system/widgets/src/components/Text/src/styles.module.css, app/client/packages/design-system/widgets/src/components/TextInput/src/TextInput.tsx
Fixed WDS components bugs
Fixes #
#33077
#33078
#32689
#32919
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8926075231>
> Commit: 0981cf8a45151cb3dc24b938efb7d79c7fefc766
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8926075231&attempt=1" target="_blank">Click here!</a>
=> fix: wds components

app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java, app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithErrorCode.java, app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/GlobalExceptionHandler.java
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8947042815>
> Commit: d55ecae565e42f4d05a26eb6c642a4b3e34df09e
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8947042815&attempt=1" target="_blank">Click here!</a>
=> chore: Don't mask 415 with 500

app/server/appsmith-server/src/main/java/com/appsmith/server/applications/base/ApplicationServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/applications/base/ApplicationServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/newpages/base/NewPageServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/newpages/base/NewPageServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/BaseService.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/WorkspaceServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/ApplicationServiceCETest.java
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8944427065>
> Commit: 3e939b8cc507b8ada7cbeefb94b1750a90b615f7
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8944427065&attempt=1" target="_blank">Click here!</a>
=> chore: Remove more unused methods in BaseService & ApplicationServiceCE

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/AuthenticationDTO.java
> Cherry-picking release blocker for Airtable 
Fixes https://github.com/appsmithorg/appsmith/issues/33184 
> [!CAUTION]  
=> chore: cherry picking airtable fix to master

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/SeedData.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/ce/V3__addPlugins.java
Add all the appsmith plugins with latest state in the DB as migration
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: Migrations for adding all the plugins

app/client/cypress/support/Pages/GitSync.ts, app/server/appsmith-git/pom.xml, app/server/appsmith-git/src/main/java/com/appsmith/git/helpers/SshTransportConfigCallback.java, app/server/appsmith-interfaces/pom.xml, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/git/constants/SSHConstants.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/git/utils/CryptoUtil.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitDeployKeyGenerator.java
Cherry picking sha1 algo switch to master
=> fix: Start using SHA2 instead of SHA1 algorithms for signing during git operations (#33166)

app/client/src/ce/components/DSDataFilter/index.tsx, app/client/src/ce/components/gitComponents/GitSettingsCDTab/UnlicensedGitCD.tsx, app/client/src/ce/components/gitComponents/GitSettingsCDTab/index.tsx, app/client/src/ce/pages/workspace/InviteUsersForm.tsx, app/client/src/ee/components/gitComponents/GitSettingsCDTab/UnlicensedGitCD.tsx
Updating invite modal component to fix issue on EE & improving code splitting of a file
Fixes [#3954](https://github.com/appsmithorg/appsmith-ee/issues/3954)
/ok-to-test tags="@tag.Workspace, @tag.Git"
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8972376691>
> Commit: cd3d806b5094358894977f28af83c43199ec15d9
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8972376691&attempt=1" target="_blank">Click here!</a>
=> fix: Updating invite modal component to fix issue on EE & improving code splitting of a file

app/server/appsmith-server/src/main/java/com/appsmith/server/actioncollections/base/ActionCollectionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/newactions/base/NewActionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/BaseService.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/CrudService.java
=> chore: Remove unused methods in `CrudService`

app/server/appsmith-interfaces/pom.xml, app/server/appsmith-server/pom.xml
> [!CAUTION]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/8978747021>
> Commit: f04bf494987e4814fe8d6e5ce645d8c7955e4aee
> Cypress dashboard: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=8978747021&attempt=2&selectiontype=test&testsstatus=failed&specsstatus=fail" target="_blank"> Click here!</a>
> <li>cypress/e2e/Regression/ClientSide/Widgets/Button/ButtonGroup2_spec.ts </ol>
> To know the list of identified flaky tests - <a href="https://internal.appsmith.com/app/cypress-dashboard/identified-flaky-tests-65890b3c81d7400d08fa9ee3?branch=master" …
=> chore(deps): Update BouncyCastle

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ApplicationPermissionCEImpl.java
tiny pr for adding the missing override annotation. 
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: added missing override annotation

app/server/appsmith-server/src/main/java/com/appsmith/server/actioncollections/base/ActionCollectionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutCollectionServiceCEImpl.java
Reverts appsmithorg/appsmith#33303
=> Revert "fix: Fixes CREATE_JS_ACTION_ERROR error that disallows creating js objects or updating actions on certain git connected apps"

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/GitUtils.java, app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/GitUtilsTest.java
> Added regex for supporting custom usernames in ssh
Fixes #19881
> [!TIP]
> Workflow run:
<https://github.com/appsmithorg/appsmith/actions/runs/9090239144>
> Commit: 05f2b6f8e6bbbbd6f05e70d9fa9194a07c89d86d
> Cypress dashboard url: <a
href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9090239144&attempt=1" target="_blank">Click here!</a>
> [!TIP]  
>
> _Please also include relevant motivation and context. List any dependencies that are required for …
=> chore: cherry-pick to master

app/client/package.json, app/client/yarn.lock
Update text wrap to pretty. This will enable better wrapping of text and balance white space.
Fixes #33474 
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9094378242>
> Commit: 06b95bd799c27ce4ebf05f5692b9a7e14e0110a8
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9094378242&attempt=1" target="_blank">Click here!</a>
=> feat: text-wrap change

app/client/src/ce/constants/messages.ts
Adding couple of messages to by used in modules cypress tests
PR for https://github.com/appsmithorg/appsmith-ee/pull/4118
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9105210254>
> Commit: da03a364f5c6f200f11b35aff10ee45fc5fc99eb
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9105210254&attempt=2" target="_blank">Click here!</a>
=> chore: Adding couple of messages for modules

app/client/src/components/editorComponents/CodeEditor/index.tsx
https://theappsmith.slack.com/archives/C0134BAVDB4/p1715768117676669
Fixes #33498 
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9101375888>
> Commit: 001db2594c4b70a19249699b5839a615785ae59c
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9101375888&attempt=2" target="_blank">Click here!</a>
=> fix: Peek overlay position flickering issue

deploy/docker/fs/usr/lib/python3/dist-packages/supervisor/appsmith_supervisor_stdout.py
Fix blank line noise in logs routed via Supervisor.
=> chore: Fix blank lines in logs

app/client/packages/design-system/widgets/src/components/Flex/stories/Flex.stories.tsx, app/client/packages/design-system/widgets/src/components/Link/src/Link.tsx, app/client/packages/design-system/widgets/src/components/Link/src/styles.module.css, app/client/packages/design-system/widgets/src/components/Link/src/types.ts, app/client/packages/design-system/widgets/src/components/Link/stories/Link.stories.tsx, app/client/packages/design-system/widgets/src/components/Modal/src/ModalHeader.tsx, app/client/packages/design-system/widgets/src/components/Select/src/Select.tsx, app/client/packages/design-system/widgets/src/components/Text/chromatic/Text.chromatic.stories.tsx, app/client/packages/design-system/widgets/src/components/Text/src/Text.tsx, app/client/packages/design-system/widgets/src/components/Text/src/types.ts, app/client/packages/design-system/widgets/src/components/Text/stories/Text.stories.tsx, app/client/packages/design-system/widgets/src/testing/ColorGrid.tsx, app/client/packages/design-system/widgets/src/testing/ComplexForm.tsx, app/client/packages/design-system/widgets/src/testing/Elevation.tsx, app/client/packages/storybook/.storybook/preview-head.html, app/client/packages/storybook/src/components/ThemeSettings.tsx, app/client/src/widgets/wds/WDSParagraphWidget/widget/index.tsx, app/client/src/widgets/wds/WDSStatBoxWidget/component/index.tsx, app/client/src/widgets/wds/WDSTableWidget/component/TableHeader/Pagination.tsx, app/client/src/widgets/wds/WDSTableWidget/component/cellComponents/HeaderCell.tsx, app/client/src/widgets/wds/WDSTableWidget/component/cellComponents/PlainTextCell.tsx, app/client/src/widgets/wds/WDSTableWidget/component/cellComponents/URLCell.tsx
This PR uses react aria link's component in our Link component
=> chore: Improve Link component

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/ce/V5__createDefaultTenant.java, app/server/appsmith-server/src/main/resources/sql/createIndexes.sql
=> chore: default tenant name in configuration

app/server/appsmith-server/src/main/java/com/appsmith/server/applications/base/ApplicationServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/applications/base/ApplicationServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/newpages/base/NewPageServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/newpages/base/NewPageServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ConsolidatedAPIServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationPageServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ConsolidatedAPIServiceImplTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/NewPageServiceTest.java
Reverts appsmithorg/appsmith#33496
=> revert:  "chore: fixing file lock issues on autocommit"

app/server/appsmith-server/src/main/java/com/appsmith/server/applications/base/ApplicationServiceCEImpl.java
-`application` attribute of `pages` field in consolidated apis was missing `isPublic`  field. 
it is part of transient properties which is not stored. Since the method was not included in the application find flow the property was not getting set.
> [!CAUTION]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9125066518>
> Commit: 6c5bd4a53943d3f78c45f72dc5e252d257895f19
> Cypress dashboard: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9125066518&attempt=4&selectiontype=test&testsstatus=failed&specsstatus=fail" target="_blank"> Click here!</a>
> …
=> chore: added fix for missing isPublic

app/client/src/components/propertyControls/DraggableListCard.tsx, app/client/src/components/propertyControls/ToolbarButtonListControl.tsx, app/client/src/components/propertyControls/index.ts, app/client/src/widgets/wds/WDSToolbarButtonsWidget/config/propertyPaneConfig/contentConfig.ts
Fixes: #33395 
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9127232599>
> Commit: 70759b80893d1c014ca305020f1a9e429267de2c
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9127232599&attempt=1" target="_blank">Click here!</a>
=> chore: allow deleting toolbar + add icon for toolbar creation

app/client/packages/design-system/widgets/src/components/ActionGroup/src/ActionGroup.tsx, app/client/packages/design-system/widgets/src/components/ActionGroup/src/index.tsx, app/client/packages/design-system/widgets/src/components/ActionGroup/src/styles.module.css, app/client/packages/design-system/widgets/src/components/ActionGroup/src/types.ts, app/client/packages/design-system/widgets/src/components/ActionGroup/stories/ActionGroup.stories.tsx, app/client/packages/design-system/widgets/src/components/ButtonGroup/src/types.ts, app/client/src/widgets/wds/WDSToolbarButtonsWidget/component/index.tsx, app/client/src/widgets/wds/WDSToolbarButtonsWidget/component/types.ts, app/client/src/widgets/wds/WDSToolbarButtonsWidget/config/propertyPaneConfig/styleConfig.ts, app/client/src/widgets/wds/WDSToolbarButtonsWidget/widget/index.tsx, app/client/src/widgets/wds/WDSToolbarButtonsWidget/widget/types.ts
Fixes #32309
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9127236127>
> Commit: 016f9d08fbdd87d6ff355d45e239f015d9401612
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9127236127&attempt=1" target="_blank">Click here!</a>
=> chore: add alignment to toolbar button

app/client/src/ce/api/ApplicationApi.tsx, app/client/src/ce/sagas/ApplicationSagas.tsx
Fixes #33436
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9128689128>
> Commit: 2981e783dfef4ce0b2064ccc9689a041770ef723
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9128689128&attempt=1" target="_blank">Click here!</a>
=> chore: hide navigation by default for anvil

.github/workflows/build-client-server.yml, .github/workflows/build-docker-image.yml, .github/workflows/ci-test-custom-script.yml, .github/workflows/ci-test-hosted.yml, .github/workflows/ci-test-limited.yml, .github/workflows/client-build.yml, .github/workflows/github-release.yml, .github/workflows/on-demand-build-docker-image-deploy-preview.yml, .github/workflows/pr-cypress.yml, .github/workflows/rts-build.yml, .github/workflows/server-build.yml, .github/workflows/test-build-docker-image.yml
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> ci: Upgrading the upload and download artifact library

.github/workflows/build-client-server.yml, .github/workflows/build-docker-image.yml, .github/workflows/ci-test-custom-script.yml, .github/workflows/ci-test-hosted.yml, .github/workflows/ci-test-limited.yml, .github/workflows/client-build.yml, .github/workflows/close-labeler.yml, .github/workflows/github-release.yml, .github/workflows/on-demand-build-docker-image-deploy-preview.yml, .github/workflows/pr-cypress.yml, .github/workflows/rts-build.yml, .github/workflows/server-build.yml, .github/workflows/test-build-docker-image.yml
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> ci: Upgrade GitHub Action steps to github-script@v7 and upload-artifact@v4

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/ce/V6__createAnonymousUser.java, app/server/appsmith-server/src/main/resources/sql/createIndexes.sql
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: new unique indexes

app/client/src/widgets/wds/WDSCurrencyInputWidget/config/propertyPaneConfig/contentConfig.ts
Fixes #32031
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9173526093>
> Commit: b15e04d80cd2dcf224cb97bb433a3217897dc8db
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9173526093&attempt=1" target="_blank">Click here!</a>
=> chore: remove allow currency change control in WDSCurrencyInputWidget

app/client/src/widgets/wds/WDSPhoneInputWidget/component/index.tsx, app/client/src/widgets/wds/WDSPhoneInputWidget/widget/index.tsx
Fixes #33241
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9173533714>
> Commit: 1cdcec81eb8c6ee6dc038aa3c000c7ddcca08777
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9173533714&attempt=1" target="_blank">Click here!</a>
=> chore: add the missing isRequired prop in WDSPhoneInputWidget

app/client/src/widgets/wds/WDSPhoneInputWidget/component/index.tsx, app/client/src/widgets/wds/WDSPhoneInputWidget/widget/index.tsx
Fixes #32469
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9174513923>
> Commit: d941e00d5a2ae357151a21075f757b4444c36087
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9174513923&attempt=1" target="_blank">Click here!</a>
=> chore: add the missing onKeyDown method

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonDBConfig.java, deploy/docker/fs/opt/appsmith/entrypoint.sh
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9191016385>
> Commit: c74e98018a6b4bd212e922eb1b3015195a5234a0
> Cypress dashboard url: <a …
=> fix: Remove the strict check for mongo url

app/client/cypress/support/commands.js
Added missing commands in commands.js file for EE repo
=> test: updated commands in CE

.github/workflows/server-build.yml, app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonDBConfig.java, app/server/appsmith-server/src/main/resources/application.properties, app/server/envs/test.env.example
> [!TIP]  
>
_or_  
> [!WARNING]  
/ok-to-test tags="@tag.GenerateCRUD"
> [!CAUTION]  
=> chore: Enable testscases on PG branch 

app/client/src/ce/selectors/entitiesSelector.ts, app/client/src/pages/Editor/IDE/EditorPane/JS/Add.tsx, app/client/src/pages/Editor/IDE/EditorPane/Query/Add.tsx, app/client/src/pages/Editor/IDE/EditorPane/Query/QueryRender.test.tsx, app/client/src/pages/Editor/IDE/EditorPane/components/SegmentAddHeader.tsx
This reverts commit f93410e245d4d6d3daf84a7b6066abae0819c39d.
https://github.com/appsmithorg/appsmith/pull/33627
_or_  
> [!WARNING]  
/ok-to-test tags="@tag.ImportExport"
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9203923153>
> Commit: 2da6d7e8a154f3c72c6a5b19887be42109c00a51
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9203923153&attempt=1" target="_blank">Click here!</a>
=> Revert "fix: Add pane issues (#33627)"

app/client/src/widgets/wds/WDSInputWidget/config/propertyPaneConfig/contentConfig.ts, app/client/src/widgets/wds/WDSInputWidget/widget/helper.ts, app/client/src/widgets/wds/WDSInputWidget/widget/index.tsx
Fixes #31805
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9202955378>
> Commit: af2713e5baa3268df6a0fbb8b4b501682ba5097f
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9202955378&attempt=1" target="_blank">Click here!</a>
=> chore: add dependency map for WDSInputWidget

deploy/docker/base.dockerfile
=> chore: Install latest NodeJS again

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/bridge/BridgeQuery.java
=> chore: Fix null equality with Postgres

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/bridge/BridgeUpdate.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/BaseAppsmithRepositoryCEImpl.java
=> fix: Fix updates setting multiple nested fields of the same JSON column

app/client/src/widgets/wds/WDSTableWidget/component/TableHeader/TableColumnHeader.tsx, app/client/src/widgets/wds/WDSTableWidget/component/TableStyledWrappers.tsx, app/client/src/widgets/wds/WDSTableWidget/component/cellComponents/EmptyCell.tsx
Fixes #33758
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9267730971>
> Commit: 5305b21086cc8965be0f9159d11ebeadf2503878
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9267730971&attempt=1" target="_blank">Click here!</a>
=> chore: fix table with and without connected data have different heights

app/client/src/widgets/wds/WDSTableWidget/component/cellComponents/HeaderCell.tsx
Fixes #33772
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9269076057>
> Commit: a7bcd27ea4438f4f881355b0d84099b7f29fc0ed
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9269076057&attempt=1" target="_blank">Click here!</a>
=> chore: fix Table column sorting toggle does not functional correctly

app/server/appsmith-interfaces/src/test/java/com/appsmith/external/helpers/restApiUtils/helpers/RequestCaptureFilterTest.java
Add unit test for RequestCaptureField
Fixes https://github.com/appsmithorg/appsmith/issues/33821
/test datasource
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9283183535>
> Commit: 7814315bab793ff7c2b1c92cbf1d5020fd574988
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9283183535&attempt=1" target="_blank">Click here!</a>
=> chore: Add unit test for RequestCaptureFilter

app/client/cypress/support/Pages/IDE/LeftPane.ts
Updating leftpane class in cypress to fix pageaccess_spec on EE
_or_  
> [!WARNING]  
> [!CAUTION]  
=> test: Updating leftpane class in cypress to fix pageaccess_spec on EE

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/ce/V3__addPlugins.java
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> fix: remove workflow plugin from ce migrations

app/client/src/ce/constants/messages.ts
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: Adding assign custom role text to messages to use it on Cypress EE

app/client/src/components/editorComponents/LazyCodeEditor/styles.tsx
Fixes #33110
/ok-to-test tags="@tag.IDE, @tag.Widget"
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9313286054>
> Commit: 447bcdabeeb2ccff8e09e4167b7c1cf2250c6f7b
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9313286054&attempt=1" target="_blank">Click here!</a>
=> chore: fix height flickering in code editor

deploy/helm/Publish-helm-chart.md
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> [Feature]: Fix typos in Publish-helm-chart.md: depencies -> dependencies

.github/workflows/server-build.yml
> [!TIP]
> _Add a TL;DR when the description is longer than 500 words or
extremely technical (helps the content, marketing, and DevRel team)._
>
> _Please also include relevant motivation and context. List any
dependencies that are required for this change. Add links to Notion, Figma or any other documents that might be relevant to the PR._
Fixes #`Issue Number`
_or_
> [!WARNING]
> _If no issue exists, please create an issue first, and check with the
maintainers if the issue is valid._
> [!CAUTION]
> If you modify the content in this section, you are likely to disrupt
the CI result for your PR.
> [!TIP]  
> _Add a TL;DR when the description is longer than 500 words or extremely …
=> chore: Increase pg max connections property for CI (#33923)

app/client/src/ce/api/ApplicationApi.tsx, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Application.java
This reverts commit dd387430308da5ede0705eb419d4ee0f839893c8.
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: Revert "chore: Remove `unreadCommentThreads` (#33905)"

app/client/packages/design-system/headless/src/components/TextArea/src/TextArea.tsx, app/client/src/ce/api/ApplicationApi.tsx, app/client/src/pages/Editor/PropertyPane/PropertyPaneView.tsx, app/client/src/pages/Editor/PropertyPane/helpers.tsx, app/client/src/utils/autocomplete/CodemirrorTernService.ts, app/client/src/utils/autocomplete/__tests__/TernServer.test.ts, app/client/src/widgets/CircularProgressWidget/widget/index.tsx, app/client/src/widgets/DatePickerWidget/widget/index.tsx, app/client/src/widgets/DropdownWidget/widget/index.tsx, app/client/src/widgets/FilepickerWidget/widget/index.tsx, app/client/src/widgets/FormButtonWidget/widget/index.tsx, app/client/src/widgets/IconWidget/widget/index.tsx, app/client/src/widgets/InputWidget/widget/index.tsx, app/client/src/widgets/ListWidget/widget/index.tsx, app/client/src/widgets/MultiSelectWidget/widget/index.tsx, app/client/src/widgets/ProgressBarWidget/widget/index.tsx, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/constants/spans/DatasourceSpan.java, app/server/appsmith-server/src/main/java/com/appsmith/server/datasources/base/DatasourceServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/datasources/base/DatasourceServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/datasourcestorages/base/DatasourceStorageServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/datasourcestorages/base/DatasourceStorageServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Application.java, app/server/appsmith-server/src/main/java/com/appsmith/server/plugins/base/PluginServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/plugins/base/PluginServiceCEImpl.java
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> 04/06 Daily Promotion

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/BearerTokenAuth.java, app/server/appsmith-server/src/main/java/com/appsmith/server/datasources/base/DatasourceServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/GitArtifactMetadata.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ce/CustomJSLibCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/RepositoryHelperMethods.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/ce/V013__addXmlParserCustomJsLib.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/cakes/BaseCake.java, app/server/appsmith-server/src/test/java/com/appsmith/server/exports/internal/ExportServiceTests.java, app/server/appsmith-server/src/test/java/com/appsmith/server/imports/internal/ImportServiceTests.java
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: fix export service

app/server/appsmith-server/src/main/java/com/appsmith/server/git/autocommit/helpers/AutoCommitEligibilityHelperImpl.java
Reverts appsmithorg/appsmith#34015
=> Revert "fix: added fix for disabling the autocommit feature without feature flag"

app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/BaseAppsmithRepositoryCEImpl.java
Making the `getPermissionGroupsPredicate` static and cleaning up its arguments, so I can use it from cacheable repo class on EE, which unfortunately doesn't go through repository classes to hit the database.
This is only a refactor. Isn't expected to fix any new tests, or break already-passing tests.
=> chore: Use static permission query builder for use elsewhere

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/CustomJsonType.java, app/server/appsmith-server/src/main/java/com/appsmith/server/actioncollections/base/ActionCollectionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/datasources/base/DatasourceServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/datasourcestorages/base/DatasourceStorageServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/cakes/BaseCake.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/BaseAppsmithRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/repositories/UserRepositoryTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/TenantServiceCETest.java
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> fix: datasource test pg

app/server/appsmith-server/src/main/java/com/appsmith/server/domains/NewPage.java
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> fix: add null check

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ActionExecutionSolutionCEImpl.java
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> fix: action execution service test

deploy/docker/fs/opt/appsmith/entrypoint.sh, deploy/docker/fs/opt/appsmith/run-postgres.sh
Reverts appsmithorg/appsmith#33987
=> Revert "chore: Update postgres version references"

app/client/src/widgets/wds/WDSPhoneInputWidget/config/propertyPaneConfig/contentConfig.ts
Fixes #33933
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9460615539>
> Commit: 6349d4235c3f3c26b785599ed721433df277ac9e
> Cypress dashboard url: <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9460615539&attempt=1" target="_blank">Click here!</a>
=> chore: remove allowDialCodeChange property

app/client/src/ce/api/ApplicationApi.tsx, app/client/src/ce/constants/ReduxActionConstants.tsx, app/client/src/ce/constants/WorkflowConstants.ts, app/client/src/ce/selectors/applicationSelectors.tsx, app/client/src/ce/workers/Evaluation/Actions.ts, app/client/src/constants/EvalConstants.ts, app/client/src/ee/configs/index.ts, app/client/src/sagas/EvaluationsSaga.ts
Cherry picking release blocker for workflows on master branch
Fixes #34171 
/test sanity
> [!CAUTION]  
=> fix: set eval version for workflows artefact  (#34197)

app/client/cypress/support/Pages/JSEditor.ts, app/client/src/sagas/JSPaneSagas.ts, app/client/src/utils/JSPaneUtils.tsx
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: Cherry pick/module refactor fix

scripts/deploy_preview.sh
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> fix: failing dp builder

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/ce/V002__loadMongoData.java
Old MongoDB databases have a lot of collections that we don't use anymore, and we don't have tables in Postgres for. We are skipping data from these collections.
This PR will ignore any `.jsonl` file that doesn't have a corresponding table, as they don't have a corresponding `@Entity` domain class either. Currently, it's these from our release database:
(sorted list)
```
actionTemplate
apiTemplate
category
comment
commentThread
datasourceConfigurationStructure
datasourceTemplate
group
inviteUser
knowledgeStore
mongockChangeLog
mongockLock
notification
organization
permission
propertyPane
provider
resetUserPasswordDTO
role
saasPlugins
setting
snippet
templateCollection
widget
```
=> chore: Ignore jsonl files for missing tables

app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceServiceTest.java
> [!TIP]  
>
Fixes https://github.com/appsmithorg/appsmith/issues/34041
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: password encrypted value check test datasource

.github/workflows/ci-test-custom-script.yml, app/client/cypress/fixtures/datasources.json, app/server/appsmith-server/src/main/java/com/appsmith/server/actioncollections/base/ActionCollectionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/applications/base/ApplicationServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/newactions/base/NewActionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/newpages/base/NewPageServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomActionCollectionRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomActionCollectionRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomApplicationRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomApplicationRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewActionRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomNewPageRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomWorkspaceRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomWorkspaceRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/WorkspaceServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PingScheduledTaskCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceTest.java, app/server/envs/test.env.example, app/server/tx/transform.py
_or_  
> [!WARNING]  
> [!WARNING]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9613243545>
> Commit: e1812f2115b2ce624562f674876c7c24cefaa0f4
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9613243545&attempt=1" target="_blank">Cypress dashboard</a>.
> It seems like **no tests ran** 😔. We are not able to recognize it, please check <a href="https://github.com/appsmithorg/appsmith/actions/runs/9613243545" target="_blank">workflow here</a>.
Should the DevRel and Marketing teams inform users …
=> chore: Update transform script to accept acl permission at any position

app/client/cypress/e2e/Regression/ClientSide/Widgets/Custom/CustomWidgetDefaultComponent_spec.ts, app/client/cypress/e2e/Regression/ClientSide/Widgets/Custom/CustomWidgetEditorPropertyPane_spec.ts, app/client/src/widgets/CustomWidget/widget/index.tsx
14/06 Daily Promotion## Description
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> fix: Disable custom widgets for airgap

app/server/appsmith-server/src/main/java/com/appsmith/server/fork/internal/ApplicationForkingServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/bridge/BridgeQuery.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> feat: Add `in` clause for enums and fix zipWith for flux

app/client/cypress/fixtures/anvilCurrencyInputWidget.json, app/client/cypress/fixtures/anvilInputWidget.json, app/client/cypress/fixtures/anvilPhoneInputWidget.json
**/test anvil**
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9707811922>
> Commit: ed747ced8289226840e96096a6a1ee86869d4bc5
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9707811922&attempt=2" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Anvil`
=> test: Fix Anvil DSLs used for testing

scripts/deploy_preview.sh
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> fix failing dps

app/client/src/api/DatasourcesApi.ts, app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonConfig.java
Cherry-pick appsmithorg/appsmith#34680.
[Slack conversation](https://theappsmith.slack.com/archives/C040LHZN03V/p1719997989677959).
/test sanity
=> chore: Cherry pick: Remove strict payload parsing

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/ThemesConfig.java
Adding repeating migration as bean for adding system themes
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: add bean for themes

.github/workflows/on-demand-build-docker-image-deploy-preview.yml, app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/AddNewRow1_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/AddNewRow2_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/Date_column_editing_1_spec.ts, app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/Inline_editing_1_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/Inline_editing_2_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/Inline_editing_3_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_Color_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_PropertyPane_2_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/TableV2_spec.js, app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/columnTypes/currency_spec.ts, app/client/cypress/support/Pages/PropertyPane.ts, app/client/cypress/support/Pages/Table.ts, app/client/cypress/support/widgetCommands.js, app/client/src/ce/actions/evaluationActionsList.ts, app/client/src/components/propertyControls/PrimaryColumnsControlV2.tsx, app/client/src/widgets/ModalWidget/widget/index.test.tsx, app/client/src/widgets/ModalWidget/widget/index.tsx, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/RTSCaller.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomThemeRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomThemeRepositoryCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/themes/base/ThemeServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ThemeServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/ThemeImportableServiceCETest.java
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> 15/07 Daily Promotion

app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/DryOperationRepository.java
PR to add transaction template structure for dry ops execution in the import flow.
/test git importexport sanity
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9906442027>
> Commit: cc8df4971d0f94b2156385a7fc04e611179e9ab8
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9906442027&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Git, @tag.ImportExport, @tag.Sanity`
> Spec:
> <hr>Fri, 12 Jul 2024 10:53:12 UTC
=> chore: Add transaction template for dry DB ops execution

app/client/cypress/support/Pages/IDE/Sidebar.ts
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/9986238309>
> Commit: 5ec099d5e44a0483a575ee41f6c88cf01241ed9f
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=9986238309&attempt=2" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.All`
> Spec:
> <hr>Thu, 18 Jul 2024 07:28:51 UTC
=> test: increased timeout for Sidebar

app/server/appsmith-server/src/main/java/com/appsmith/server/bbhack/BBService.java, app/server/appsmith-server/src/main/java/com/appsmith/server/bbhack/BBServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/constants/ce/UrlCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/BBController.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/BuildingBlockHack.java, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/BBMainDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/BBResponseDTO.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BBHackRepository.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomBBHackRepository.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomBBHackRepositoryImpl.java
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: Implement the basics for building custom bb

.github/workflows/rts-build.yml, app/client/.husky/pre-push, app/client/cypress/support/Pages/IDE/Sidebar.ts, app/client/src/sagas/BuildingBlockSagas/QuickerBuildingBlocks.utils.ts
Added utility functions in QuickerBuildingBlocks.utils.ts to extract tokens from widget bindings and get related entities. These functions will be used to improve the functionality of the application.
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
> If you modify the content in this section, …
=> feat: add utility functions for extracting tokens and related entities

app/client/src/actions/queryScehmaActions.ts, app/client/src/ce/reducers/index.tsx, app/client/src/ce/reducers/uiReducers/index.tsx, app/client/src/components/editorComponents/Debugger/Schema.tsx, app/client/src/reducers/uiReducers/querySchemaReducer.ts, app/client/src/selectors/querySchemaSelectors.ts
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> fix: form to use redux state

app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/CustomOAuth2UserServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/CustomOidcUserServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithOAuth2AuthenticationException.java, deploy/docker/fs/opt/appsmith/entrypoint.sh, deploy/docker/fs/opt/appsmith/pg-upgrade.sh
[Slack thread](https://theappsmith.slack.com/archives/C02GAUE9P5H/p1721722079613179)
_or_  
> [!WARNING]  
> [!CAUTION]  
=> Cherry pick/26 jul

app/client/src/UITelemetry/PageLoadInstrumentation.ts, app/client/src/UITelemetry/auto-otel-web.ts, app/client/src/UITelemetry/generateTraces.ts, app/client/src/index.tsx
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: Add page load trace with resource, paint and navigation spans (#34957)

app/server/appsmith-server/src/main/java/com/appsmith/server/actioncollections/base/ActionCollectionServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/actioncollections/base/ActionCollectionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomActionCollectionRepositoryCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ce/CustomActionCollectionRepositoryCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/refactors/ce/RefactoringServiceTest.java
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> fix: Do not return composed action collections after refactor

.github/workflows/client-build.yml
commented files changed step. It is a notification step
=> CI: commented files changed step. It is a notification step (#35460)

deploy/docker/fs/opt/appsmith/record-heap-dump.sh, deploy/docker/fs/opt/appsmith/record-thread-dump.sh, deploy/docker/fs/opt/appsmith/thread-profile-start.sh, deploy/docker/fs/opt/appsmith/thread-profile-stop.sh
12/08 Daily Promotion## Description
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: Cherry picking profiling scripts

app/client/src/pages/Editor/Explorer/Entity/EntityProperties.tsx, app/client/src/pages/Editor/IDE/EditorPane/Explorer.tsx, app/client/src/pages/Editor/IDE/EditorPane/index.tsx
=> chore: Cherry Pick Widget scroll bug fix

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/constants/DeprecatedFieldName.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/constants/FieldName.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration060AddIndexesForPolicyMap.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration061TenantPolicySetToPolicyMap.java
[chore/cherry-pick-policy-map-indexes 2ffa03247b] chore: Add indexes for policyMap to improve query response time (#35676)
Author: Abhijeet <41686026+abhvsn@users.noreply.github.com>
/test sanity
> [!CAUTION]  
=> chore: Cherry pick indexes for `policyMap` to improve query response time

app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/DryOperationRepository.java
- Pr https://github.com/appsmithorg/appsmith/pull/35692
Fixes https://github.com/appsmithorg/appsmith/issues/35588  
> [!CAUTION]  
=> chore: cherry-pick for themes pr to master

app/client/cypress_ci.config.ts, app/client/cypress_ci_custom.config.ts, app/client/cypress_ci_hosted.config.ts
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/10465694897>
> Commit: 59aa72f20f7b023a60889e75686b7441644c7caf
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=10465694897&attempt=1" target="_blank">Cypress dashboard</a>.
> Spec:
> <hr>Tue, 20 Aug 2024 05:40:54 UTC
=> test: removed retries from all config files

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/TenantConfig.java
12/08 Daily Promotion## Description
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: Cherry pick for fixing the policyMap migration 

app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Application.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/GitArtifactMetadata.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ce/ApplicationCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ce/GitArtifactMetadataCE.java
- CE EE split for Application and GitArtifactMetadata
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: splitting application and metadata class

app/server/appsmith-server/src/main/java/com/appsmith/server/applications/git/ApplicationGitFileUtilsCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/JsonSchemaMigration.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/JsonSchemaVersionsFallback.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/MigrationHelperMethods.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/utils/JsonSchemaMigrationHelper.java, app/server/appsmith-server/src/test/java/com/appsmith/server/git/autocommit/AutoCommitEventHandlerImplTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/git/autocommit/AutoCommitServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/migrations/JsonSchemaMigrationTest.java
- CP pr https://github.com/appsmithorg/appsmith/pull/36203
> [!IMPORTANT]
> 🟣 🟣 🟣 Your tests are running.
> Tests running at: <https://github.com/appsmithorg/appsmith/actions/runs/10807154764>
> Commit: 7713482003fb9eb73536066507ea4ed21b8c41a7
> Workflow: `PR Automation test suite`
> Tags: `@tag.Git`
> Spec: ``
> <hr>Wed, 11 Sep 2024 07:37:58 UTC
=> fix: cherry pick to master

.github/workflows/test-build-docker-image.yml
…(#36513)
> [!TIP]
> _Add a TL;DR when the description is longer than 500 words or
extremely technical (helps the content, marketing, and DevRel team)._
>
> _Please also include relevant motivation and context. List any
dependencies that are required for this change. Add links to Notion, Figma or any other documents that might be relevant to the PR._
Fixes #`Issue Number`
_or_
> [!WARNING]
> _If no issue exists, please create an issue first, and check with the
maintainers if the issue is valid._
> [!CAUTION]
> If you modify the content in this section, you are likely to disrupt
the CI result for your PR.
(cherry picked from commit 368fdac46438b14514f7ed1f5b8bbefdeb2591ef)
> [!TIP] …
=> fix: master package step to include server artifacts for pg and mongo

.github/workflows/github-release.yml, .github/workflows/test-build-docker-image.yml, app/client/cypress/e2e/Regression/ClientSide/Git/GitAutocommit_spec.ts, app/client/src/PluginActionEditor/components/PluginActionNameEditor.tsx, app/client/src/PluginActionEditor/index.ts, app/client/src/components/editorComponents/ActionNameEditor.tsx, app/client/src/components/editorComponents/EditableText.tsx, app/client/src/components/utils/NameEditorComponent.tsx, app/client/src/pages/Editor/APIEditor/ApiEditorContext.tsx, app/client/src/pages/Editor/APIEditor/CommonEditorForm.tsx, app/client/src/pages/Editor/APIEditor/index.tsx, app/client/src/pages/Editor/Explorer/Entity/Name.tsx, app/client/src/pages/Editor/JSEditor/JSObjectNameEditor.tsx, app/client/src/pages/Editor/QueryEditor/QueryEditorContext.tsx, app/client/src/pages/Editor/QueryEditor/QueryEditorHeader.tsx, app/client/src/pages/Editor/QueryEditor/index.tsx, app/client/src/pages/Editor/gitSync/Tabs/GitConnectionV2/index.tsx, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/constants/PluginConstants.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/DatasourcePluginContext.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java, deploy/docker/fs/opt/appsmith/caddy-reconfigure.mjs, deploy/docker/fs/opt/appsmith/pg-utils.sh, deploy/docker/fs/opt/appsmith/run-java.sh, deploy/docker/tests/test-pg-utils.sh
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> 30/09 Daily Promotion

app/server/appsmith-server/src/test/java/com/appsmith/server/extensions/AfterAllCleanUpExtension.java, app/server/appsmith-server/src/test/java/com/appsmith/server/testhelpers/cleanup/DBCleanup.java
TBP: https://github.com/appsmithorg/appsmith/actions/runs/11227881332
_or_  
> [!WARNING]  
> [!CAUTION]  
=> fix: Clean-up stage in server tests

app/client/src/widgets/TableWidgetV2/component/Table.tsx, app/client/src/widgets/TableWidgetV2/component/cellComponents/HTMLCell.tsx, app/client/src/widgets/TableWidgetV2/constants.ts, app/client/src/widgets/TableWidgetV2/widget/index.tsx, app/client/src/widgets/TableWidgetV2/widget/propertyConfig/PanelConfig/Data.ts
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> feat: POC1: Basic HTML rendering in table

.github/workflows/server-build.yml
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> fix: Bypassing the server file check

app/client/cypress/e2e/Regression/ServerSide/ApiTests/API_Bugs_Spec.js
```
/test
cypress/e2e/Regression/ServerSide/ApiTests/API_Bugs_Spec.js
```
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/12061903753>
> Commit: e3db469591f39622c9f975af01d536c6d82dedb7
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=12061903753&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: ``
> Spec: cypress/e2e/Regression/ServerSide/ApiTests/API_Bugs_Spec.js
> <hr>Thu, 28 Nov 2024 03:45:53 UTC
=> test: Fix failure in API_Bugs_Spec.js

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog2.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/MigrationHelperMethods.java
(cherry picked from commit 4727b4da995e14cd7ff4e1616b15a47b545f5ac1)
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> fix: Super user cache eviction when user is added via env variable (#37785)

app/client/src/widgets/TableWidgetV2/component/header/actions/Utilities.ts, app/client/src/widgets/TableWidgetV2/component/header/actions/filter/CascadeFields.tsx, app/client/src/widgets/TableWidgetV2/constants.ts, app/client/src/widgets/TableWidgetV2/widget/derived.js
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> feat: POC-4 HTML Column Integration with table features

app/client/cypress/limited-tests.txt
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: Reverted the change

.github/workflows/client-build.yml
added git lfs update
_or_  
> [!WARNING]  
> [!CAUTION]  
=> CI :  added git lfs update

app/client/packages/design-system/ads/src/List/List.tsx
Reverts appsmithorg/appsmith#38528
=> Revert "fix: Resolving merge conflict"

app/client/packages/design-system/ads/src/List/List.styles.tsx
Cherry picking this commit to master to fix the height issue for Function names on JS module instance.
_or_  
> [!WARNING]  
> [!CAUTION]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/12691961806>
> Commit: 43269b1369922f64400d0273688443241ac68ea5
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=12691961806&attempt=1&selectiontype=test&testsstatus=failed&specsstatus=fail" target="_blank">Cypress dashboard</a>.
> Tags: @tag.All
> Spec: 
> The following are new failures, please fix them …
=> fix: Updating CSS for list item to fix UI breaking on JS module instance in EE (#38558)

app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ce/GitArtifactMetadataCE.java
Make the refName and RefType transient for Artifact class.
=> chore: make refName and refType transient in Artifact Metadata class

.github/workflows/test-build-docker-image.yml
Changed TBP to run at different times, and added a new one
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> CI: Changing cron timing - Update test-build-docker-image.yml

app/client/build.sh
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: up max-old-space-size to 8192

app/server/appsmith-server/src/main/java/com/appsmith/server/applications/imports/ApplicationImportServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/DatasourceContextServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/themes/base/ThemeServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/themes/importable/ThemeImportableServiceCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/imports/internal/ImportServiceTests.java
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> 23/01 Daily Promotion

app/server/appsmith-server/src/test/it/com/appsmith/server/git/GitBranchesIT.java
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: reverting the git branches it

.github/workflows/build-client-server-count.yml, .github/workflows/ci-test-custom-script.yml, .github/workflows/ci-test-limited-with-count.yml, app/client/package.json, app/client/src/ce/constants/messages.ts, app/client/src/components/formControls/DropDownControl.test.tsx, app/client/src/components/formControls/DropDownControl.tsx, app/client/src/sagas/ActionSagas.ts, app/client/src/widgets/TableWidgetV2/component/LoadingIndicator.test.tsx, app/client/src/widgets/TableWidgetV2/component/LoadingIndicator.tsx, app/client/yarn.lock, app/server/appsmith-plugins/mssqlPlugin/src/main/java/com/external/plugins/MssqlPlugin.java, app/server/appsmith-plugins/mysqlPlugin/pom.xml
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> 13/02 - Daily promotion

app/client/cypress/e2e/Regression/ServerSide/Datasources/Hubspot_spec.ts
Add the @tag.excludeForAirgap
_or_  
> [!WARNING]  
/ok-to-test tags="@tag.Hubspot"
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/13669120033>
> Commit: ca53324880d5cc85b0fc1412e3ff7fc1d9e8f7a2
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=13669120033&attempt=1" target="_blank">Cypress dashboard</a>.
> Tags: `@tag.Hubspot`
> Spec:
> <hr>Wed, 05 Mar 2025 05:44:19 UTC
=> chore: added exclude airgap tag 

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/ce/CustomCookieWebSessionIdResolverCE.java
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: Missed adding argument for cookie init

app/client/cypress/support/commands.js, app/client/src/ce/entities/FeatureFlag.ts, app/client/src/ce/navigation/FocusStrategy/index.ts, app/client/src/components/editorComponents/JSResponseView.tsx, app/client/src/ee/navigation/FocusStrategy/NoIDEFocusStrategy.ts, app/client/src/pages/AppIDE/layouts/routers/JSEditor/JSRender.test.tsx, app/client/src/pages/common/PageHeader.tsx, app/client/src/utils/hooks/useFeatureFlagOverride.ts, app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/AuthenticationSuccessHandler.java, app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/ce/AuthenticationSuccessHandlerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/constants/ce/FieldNameCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ce/OrganizationConfigurationCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/InstanceVariablesHelper.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/InstanceVariablesHelperCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/db/ce/Migration069MigrateOrganizationConfigToInstanceConfig.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/OrganizationServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ConfigServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ConfigServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/OrganizationServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce_compatible/UserServiceCECompatibleImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/ce/InstanceVariablesTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/services/ce/OrganizationServiceCETest.java
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> 18/03 Daily Promotion

app/client/cypress/e2e/Regression/ServerSide/Postgres_DataTypes/BooleanEnum_Spec.ts, app/client/cypress/limited-tests.txt
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/13938545009>
> Commit: d8fa3afd6c61f7c95f112e3ebe5160beba8b8a4e
> <a href="https://internal.appsmith.com/app/cypress-dashboard/rundetails-65890b3c81d7400d08fa9ee5?branch=master&workflowId=13938545009&attempt=1" target="_blank">Cypress dashboard</a>.
> Spec:
> <hr>Wed, 19 Mar 2025 04:38:53 UTC
=> test: updated boolean spec

.github/workflows/ci-test-limited.yml
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: Remove postgres setup from services as embedded postgres will be started with prerequisites on demand by entrypoint

app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceImplTest.java
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> chore: Fixing AC tests after post-processing on delete

app/client/src/instrumentation/index.ts, app/client/src/instrumentation/sendFaroErrors.ts, app/client/src/sagas/EvalErrorHandler.ts, app/client/src/sagas/EvalWorkerActionSagas.ts, app/client/src/sagas/helper.ts, app/client/src/sagas/types.ts, app/client/src/utils/DynamicBindingUtils.ts, app/client/src/workers/Evaluation/JSObject/index.ts, app/client/src/workers/Evaluation/evalTreeWithChanges.test.ts, app/client/src/workers/Evaluation/evalTreeWithChanges.ts, app/client/src/workers/Evaluation/handlers/evalTree.ts, app/client/src/workers/Evaluation/helpers.ts, app/client/src/workers/common/DataTreeEvaluator/index.ts, app/client/src/workers/common/DependencyMap/utils.ts
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/14592240139>
> Commit: d7363c6c92b8ea521a96ae6439a796adb33aeaf3
> <a …
=> chore: cherry pick eval errors fix

app/client/src/ce/constants/messages.ts, app/client/src/pages/Editor/PropertyPane/PropertyPaneTitle.tsx, app/client/src/pages/Editor/PropertyPane/PropertyPaneView.tsx, app/client/src/selectors/editorSelectors.tsx, app/server/appsmith-git/src/main/java/com/appsmith/git/files/FileUtilsCEImpl.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/enums/FeatureFlagEnum.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/git/FileInterface.java, app/server/appsmith-plugins/snowflakePlugin/pom.xml, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/CommonGitFileUtilsCE.java
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> 05/05 Daily Promotion 

app/client/packages/design-system/widgets/src/components/Flex/src/flexCss.ts, app/client/packages/design-system/widgets/src/components/Flex/src/styles.module.css, app/client/src/layoutSystems/anvil/layoutComponents/components/styles.css, app/client/src/sagas/TemplatesSagas.ts, app/client/src/widgets/TableWidgetV2/widget/index.tsx
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> 09/05 Daily Promotion

app/client/src/api/ApiResponses.tsx, app/client/src/ce/sagas/PageSagas.tsx
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!TIP]
> Workflow run: <https://github.com/appsmithorg/appsmith/actions/runs/15160568329>
> Commit: 18e7784f9abc42ff21ce9f91ccd389f0e379d252
> <a …
=> chore: logout issue when switching pages in view mode

app/client/src/ce/selectors/modulesSelector.ts, app/client/src/components/editorComponents/ActionCreator/FieldGroup/index.tsx, app/client/src/sagas/WidgetLoadingSaga.ts, app/server/appsmith-git/src/main/java/com/appsmith/git/files/FileUtilsCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/plugins/solutions/PluginSchemaSolutionCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/plugins/solutions/PluginSchemaSolutionCEImpl.java
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> Daily promotion - 26/05

app/client/src/ce/reducers/organizationReducer.ts, deploy/docker/base.dockerfile, deploy/docker/fs/opt/appsmith/entrypoint.sh
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> 29/05 Daily Promotion

app/server/appsmith-git/src/main/java/com/appsmith/git/files/FileUtilsCEImpl.java, app/server/appsmith-git/src/main/java/com/appsmith/git/handler/ce/FSGitHandlerCEImpl.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/git/FileInterface.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/git/handler/FSGitHandler.java, app/server/appsmith-server/src/main/java/com/appsmith/server/applications/git/ApplicationGitFileUtilsCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/git/autocommit/AutoCommitEventHandlerCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/git/autocommit/AutoCommitEventHandlerImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/git/autocommit/AutoCommitServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/git/autocommit/helpers/GitAutoCommitHelperImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/git/central/CentralGitServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/git/central/CentralGitServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/git/central/GitHandlingServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/git/common/CommonGitServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/git/controllers/GitApplicationControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/git/fs/GitFSServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/CommonGitFileUtilsCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ConsolidatedAPIServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/LayoutActionServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/UserServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ActionExecutionSolutionCEImpl.java, app/server/appsmith-server/src/test/java/com/appsmith/server/git/ServerSchemaMigrationEnforcerTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/git/autocommit/AutoCommitEventHandlerImplTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/git/autocommit/AutoCommitServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/git/autocommit/helpers/GitAutoCommitHelperImplTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/testhelpers/git/GitFileSystemTestHelper.java
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> 11/06 Daily Promotion

app/client/src/pages/UserAuth/SignUp.tsx, app/client/src/utils/multiOrgDomains.ts, app/server/appsmith-git/src/main/java/com/appsmith/git/files/FileUtilsCEImpl.java, app/server/appsmith-git/src/main/java/com/appsmith/git/files/FileUtilsImpl.java, app/server/appsmith-git/src/main/java/com/appsmith/git/handler/ce/FSGitHandlerCEImpl.java, app/server/appsmith-git/src/test/java/com/appsmith/git/helpers/FileUtilsImplTest.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/git/FileInterface.java, app/server/appsmith-interfaces/src/main/java/com/appsmith/external/git/handler/FSGitHandler.java, app/server/appsmith-server/src/main/java/com/appsmith/server/git/central/CentralGitServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/git/central/GitHandlingServiceCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/git/fs/GitFSServiceCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ce/CommonGitFileUtilsCE.java
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> 19/06 - Daily Promotion

scripts/cleanup_dp.sh
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!WARNING]
> Tests have not run on the HEAD 9501b3de7fb5d2ef60a9c0411f4523661faee467 yet
> <hr>Thu, 26 Jun 2025 05:31:26 UTC
=> chore: update cleanup dp to delete merged PRs

app/client/src/ce/workers/Evaluation/evaluationUtils.ts, app/client/src/entities/DependencyMap/DependencyMapUtils.ts, app/client/src/entities/DependencyMap/__tests__/DependencyMapUtils.test.ts, app/client/src/utils/multiOrgDomains.ts, app/client/yarn.lock
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> 30/06 Daily Promotion

app/client/cypress/e2e/Regression/ClientSide/Widgets/TableV2/freeze_column_query_change_spec.js, app/client/package.json, app/client/src/ce/constants/messages.ts, app/client/src/ce/constants/routes/appRoutes.ts, app/client/src/ce/workers/Evaluation/evaluationUtils.ts, app/client/src/ce/workers/common/DependencyMap/utils/getEntityDependenciesByType.ts, app/client/src/entities/DependencyMap/DependencyMapUtils.ts, app/client/src/pages/Editor/AppsmithLink.tsx, app/client/src/utils/BrandingUtils.ts, app/client/yarn.lock
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> 30/07 Daily Promotion

app/client/cypress/e2e/Regression/ClientSide/Git/GitAutocommit_spec.ts, app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java, app/server/appsmith-plugins/amazons3Plugin/src/test/java/com/external/plugins/AmazonS3PluginTest.java, app/server/appsmith-server/src/main/java/com/appsmith/server/annotations/GitRoute.java, app/server/appsmith-server/src/main/java/com/appsmith/server/aspect/GitRouteAspect.java, app/server/appsmith-server/src/main/java/com/appsmith/server/git/autocommit/AutoCommitEventHandler.java, app/server/appsmith-server/src/main/java/com/appsmith/server/git/autocommit/AutoCommitSolution.java, app/server/appsmith-server/src/main/java/com/appsmith/server/git/autocommit/AutoCommitSolutionCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/git/autocommit/AutoCommitSolutionCEImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/git/autocommit/AutoCommitSolutionImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/git/autocommit/helpers/AutoCommitAsyncEventManager.java, app/server/appsmith-server/src/main/java/com/appsmith/server/git/autocommit/helpers/AutoCommitAsyncEventManagerImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/git/autocommit/helpers/GitAutoCommitHelperImpl.java, app/server/appsmith-server/src/main/java/com/appsmith/server/git/constants/GitRouteOperation.java, app/server/appsmith-server/src/main/java/com/appsmith/server/git/controllers/GitApplicationControllerCE.java, app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/RedisUtils.java, app/server/appsmith-server/src/test/it/com/appsmith/server/git/GitBranchesIT.java, app/server/appsmith-server/src/test/it/com/appsmith/server/git/GitBranchesWithCentralServiceIT.java, app/server/appsmith-server/src/test/java/com/appsmith/server/git/ServerSchemaMigrationEnforcerTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/git/autocommit/AutoCommitServiceTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/git/autocommit/AutoCommitSolutionImplTest.java, app/server/appsmith-server/src/test/java/com/appsmith/server/git/autocommit/helpers/GitAutoCommitHelperImplTest.java, deploy/helm/Chart.yaml, deploy/helm/templates/deployment.yaml, deploy/helm/tests/__snapshot__/defaults_snapshot_test.yaml.snap
> [!TIP]  
>
_or_  
> [!WARNING]  
> [!CAUTION]  
=> 24/09 Daily Promotion
