appsmithorg/appsmith

app/server/pom.xml

To generate a license listing text file with license details of all dependencies, run `mvn clean license:aggregate-add-third-party`.

Add maven-license-plugin to the project

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceContextServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceContextServiceTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceServiceTest.java

In the AuthenticationDTO object, if the password is null, the encryption and decryption process throws a NPE. This null check avoids that from happening.

Adding null checks before encrypting or decrypting the password 

---

app/client/src/entities/DataTree/dataTreeFactory.ts
app/client/src/sagas/ActionExecutionSagas.ts

Adds a third parameter to the Action.run function that can be referenced inside an action config
Usage
`{{ Api1.run(...,...,{key: value}) }}` inside property pane
`{{this.params.key}}` inside action pane
You can reference data tree properties in the params values:
- `{{ Api1.run(..., ..., { key: "Input1.text.toUpperCase()" })`
Bindings can have both params and data tree values referenced. Param values can be javascript functions
body: 
`{{ this.params.list.map(i => Input1.text + i ) }}`

Add support for run time params in action execution

---

app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/AuthenticationSuccessHandler.java
app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/CustomServerOAuth2AuthorizationRequestResolver.java
app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/RedirectHelper.java

The client can send the redirect URL in X-Redirect-Url header. The server will honour the value set and redirect the client browser to this particular url. By default the server will redirect to /applications if the custom header is missing.

Adding dynamic redirect to form & OAuth2 login

---

app/server/appsmith-plugins/mysqlPlugin/pom.xml
app/server/appsmith-plugins/postgresPlugin/pom.xml

The plugin class loader from Pf4J looks for jars under target/lib
to use to load any classes that are missing target/classes. This
PR adds the `maven-dependency-plugin` to copy the jars to this
folder automatically so the classes are available during
development.

Copy plugin dependencies to their target/lib to fix driver not found errors

---

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/pluginExceptions/AppsmithPluginException.java
app/server/appsmith-interfaces/src/main/java/com/appsmith/external/pluginExceptions/StaleConnectionException.java
app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java
app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ActionServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceContextServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionServiceTest.java

This PR introduces handling of stale database connections from datasources and creating new connections when such situation occurs.
The way this is implemented is that when a connection is identified as being stale by a plugin, it is expected to throw an instance of `StaleConnectionException`. When that happens, we destroy the connection context we have for that datasource, recreate a new connection context, and start the execution process again.
This has been currently implemented for Postgres and MySQL database plugins. The MongoDB driver seems to be clever enough to seamlessly handle such scenarios all by itself (in my tests). It still makes a log entry about the connection being closed, but it subsequently reconnects and continues as usual.

Handle stale database connection from datasources

---

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ExamplesOrganizationCloner.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ExamplesOrganizationClonerTests.java

Currently, the page list inside application objects is not cleared before cloning. So, the page list in cloned application objects contain links to new cloned pages as well old pages. This PR fixes this problem by clearing the page list in the application objects, just before cloning.

Clear application pages list before cloning

---

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ExamplesOrganizationCloner.java

The policies of `User` objects is an empty set by default. So, when using a new `User` object to call `update`, it also updates existing policies to be an empty list.

Reset default fields of User object before update

---

.github/workflows/client.yml
.github/workflows/github-release.yml
.github/workflows/server.yml

This will happen only when a tag is created on master branch. All pushes to master will still create the Docker image (with tag `latest`) but the Git tag will now create a tagged release with the version number on the image as well.

Github action to push to Docker Hub and create Github release

---

.github/workflows/client.yml
.github/workflows/github-release.yml
.github/workflows/server.yml

The latest tag will only be generated when a non-beta Github release is created.

Adding nightly builds that will be generated on each push to master

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceContextServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ExamplesOrganizationCloner.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ExamplesOrganizationClonerTests.java

This PR decrypts sensitive fields before cloning a datasource so they are encrypted only once.

Fix: Datasource password gets double encrypted on cloning

---

app/client/src/components/editorComponents/LightningMenu/LightningMenuTrigger.tsx

The lightning menu popper was pulling focus when pressing TAB key. Added a prop to fix this

Fix tab focus issue in code editor inputs

---

app/client/src/pages/Editor/WidgetsEditor.tsx

_*Fix*_: When navigating to a widget, the widget reference isn't found, resulting in the property pane rendering without reference. 
_*Resolution*_: Show property pane only if reference is available

Property pane render when navigating to a widget on a different page

---

app/client/src/api/UserApi.tsx
app/client/src/pages/organization/helpers.ts
app/client/src/reducers/uiReducers/orgReducer.ts
app/client/src/sagas/userSagas.tsx

- Use updated API structure
- Use single API to invite multiple users instead of looping.

Multi User Invite

---

app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java

When the POST body for a REST API action contains something like the following:
```JSON
{ "amount": 100 }
```
The REST API Plugin sends the following to the endpoint instead:
```JSON
{ "amount": 100.0 }
```
(You can inspect this by posting this body to `http://httpbin.org/post` as the URL).
Technically, this is okay, since JSON spec doesn't distinguish between integers and double numbers. However, it appears
APIs like that of RazorPay choke on such differences. Their API endpoints only accept integers, not floats or doubles.
To address this, I remove the part of the code that's deserializing the POST body and then serializing it again. There's no tests that broke because of this change, and I tested with a cases with newlines and tab characters, but couldn't reproduce a problem. If you …

Fix numbers being converted to floats in JSON Post body

---

app/client/src/pages/Editor/Explorer/hooks.ts

Fix for issue: When searching in the entity explorer. The widgets which have child widgets would not show up in the search results.

Fix: Missing widgets when searching in entity explorer

---

app/client/src/pages/Editor/Explorer/Entity/EntityProperty.tsx

Fix for issue: Entity property binding overflows when the names are long.
Resolution: Stop wrapping and add text ellipsis on overflow

Fix: Entity property overflows

---

app/client/src/pages/Editor/Explorer/Pages/PageEntity.tsx

Update: When the user clicks on a page in the entity explorer, the canvas should show up.

Entity explorer: Page click should open canvas

---

app/client/src/components/designSystems/appsmith/TabsComponent.tsx
app/client/src/components/propertyControls/TabControl.tsx
app/client/src/widgets/TabsWidget.tsx

Tab Widget Fixes

---

.github/workflows/client.yml
.github/workflows/server.yml
app/server/README.md

This is a hack to get around the fact that Github Actions doesn't support conditional status checks for monorepo PRs. Hence, we create similar jobs in the both server & client builds. In the server build, those jobs are dummy jobs that do nothing but satisfy the all-encompassing green tick so that PRs can be merged without using Admin privileges.

Adding dummy check in server build to satisfy required status checks

---

app/client/src/actions/datasourceActions.ts
app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx
app/client/src/components/editorComponents/DropTargetComponent.tsx
app/client/src/components/editorComponents/EditableText.tsx
app/client/src/components/editorComponents/FormRow.tsx
app/client/src/constants/ReduxActionConstants.tsx
app/client/src/index.css
app/client/src/pages/Editor/APIEditor/Form.tsx
app/client/src/pages/Editor/Explorer/Datasources/DatasourceEntity.tsx
app/client/src/pages/Editor/Explorer/Pages/PageEntity.tsx
app/client/src/pages/Editor/Explorer/Widgets/WidgetGroup.tsx
app/client/src/pages/Editor/PropertyPane/index.tsx
app/client/src/pages/Editor/PropertyPaneTitle.tsx
app/client/src/pages/Editor/QueryEditor/Form.tsx
app/client/src/pages/Editor/WidgetCard.tsx
app/client/src/pages/Editor/routes.tsx
app/client/src/reducers/uiReducers/propertyPaneReducer.tsx
app/client/src/sagas/ActionSagas.ts
app/client/src/sagas/DatasourcesSagas.ts
app/client/src/utils/hooks/dragResizeHooks.tsx

Entity Explorer Fixes

---

deploy/install.sh

Fixes #318
The issue occurred because code assumes that if `docker` is already installed, `docker-compose` would have been installed too. This PR is an attempt to fix it.

Fix docker-compose installation

---

app/client/src/constants/WidgetValidation.ts
app/client/src/utils/Validators.ts

Fixed by using a proper default format string for ISO dates

Fixes date widget crashing when no Date format is mentioned

---

deploy/aws/boot.sh
deploy/install.sh
deploy/template/docker.env.sh

This is to ensure that we handle special characters in the mongo url that's given to the Java server during configuration.

Encoding the mongo credentials in install.sh script

---

app/client/src/widgets/TableWidget.tsx

Since widget properties cannot be updated in published mode we are saving compact mode from editor and that value will persist on reload

Fix-table compact mode to persist and saved from canvas editor

---

app/client/src/components/editorComponents/FormRow.tsx
app/client/src/pages/Editor/Explorer/Datasources/DatasourceEntity.tsx
app/client/src/pages/Editor/PropertyPaneTitle.tsx
app/client/src/widgets/TableWidget.tsx

Fix issues:
- Table component calls updateWidgetMetaProperties recursively. This is a temporary fix.
- Remove console warnings about unused variables
- align form row items to `flex-start` to fix the api pane fields from jumping on focus.

Fix: Jump issue of APIPane fields

---

app/client/src/pages/Editor/QueryEditor/Table.tsx

- Overide table body height to auto to take the available space

Fix query response table style

---

app/client/src/pages/AppViewer/viewer/AppViewerHeader.tsx

- Set minimum width to 150 px, stretch if it exceeds

Fix tab name overflowing

---

deploy/install.sh

Changes in this PR address the following bugs:
1. Exit early if the script is run as `sudo` on macOS.
1. Port checking matches ports like 8080 and 8000 in addition to 80. Fixed.
1. Fix installation failing when the installation path contains a space.
1. Installation fails if a docker-appsmith instance is already up. Fixed.
1. Timeout display that waits for services doesn't show a countdown timer. Fixed.
1. Docker service was not being started correctly on Linux. Fixed.
There's individual commits for each of the above for more precise review.

Fix bugs in install.sh

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java

This is because public permissions are not given during cloning.

Example app being cloned must be set to private instead of public

---

app/client/src/pages/Applications/ApplicationCard.tsx
app/client/src/pages/Editor/Explorer/hooks.ts
app/client/src/pages/Editor/Explorer/index.tsx

- Use the without functions method since it is cached via selector
- Remove functionality where entity search is appended on the url

Update Entity Explorer to avoid extra evals of data tree

---

app/client/src/widgets/TableWidget.tsx

Removed selectedRowIndex validation to stop setting of selectedRowIndex as 0 after reset.

Fix-Setting valid table meta properties after table reset.

---

app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java
app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java
app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java
app/server/appsmith-plugins/postgresPlugin/src/test/java/com/external/plugins/PostgresPluginTest.java

Also fixes the following problems:
1. Give a predictable column ordering. The column order should now be in sync with that in the SELECT query executed.
1. Fix display of the various temporal data types in MySQL.

Fix column alias names in MySQL actions

---

app/server/appsmith-plugins/mongoPlugin/src/main/resources/form.json
app/server/appsmith-plugins/postgresPlugin/src/main/resources/form.json

We don't yet support this feature hence removing it from the UI. Will add it back again once the backend supports SSH tunnelling.
Fixes #520

Removing SSH Tunnel from Mongo & Postgres plugins

---

app/server/appsmith-plugins/mongoPlugin/src/main/resources/form.json
app/server/appsmith-plugins/postgresPlugin/src/main/resources/form.json

We don't yet support this feature hence removing it from the UI. Will add it back again once the backend supports SSH tunnelling.

Removing SSH Tunnel from Mongo & Postgres plugins (#529)

---

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/plugins/PluginExecutor.java
app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java
app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java
app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java
app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java
app/server/appsmith-plugins/postgresPlugin/src/test/java/com/external/plugins/PostgresPluginTest.java
app/server/appsmith-plugins/rapidApiPlugin/src/main/java/com/external/plugins/RapidApiPlugin.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceContextServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/DatasourceStructureSolution.java

This type variable is intended to represent the type of the
connection object, if any, that the plugin will use. This will
help make the implementations more robust by leveraging Java's
type checking instead of rudimentary type casts over the
connection objects.

Add a connection type variable for Plugin implementations

---

app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Action.java

This is because this `cacheResponse` field is only used for auto-complete on the UI. The user can still run the action manually and get the auto-complete to work. The downside to sending the `cacheResponse` field in the JSON response is that for large responses, the client times out as our response times increase to 20 secs. Hence removing this for now.
In future, we'll extract the JSON schema structure from the response body and send that to the client for populating auto-complete.

Removing cacheResponse from the JSON response for actions

---

app/client/src/pages/Editor/MainContainer.tsx

Add a switch router to not render the widgets editor while rendering the drawers (action panes) above it to get around 50% lesser frame drops in larger apps
Before 
After

Improve action pane performance

---

app/client/src/configs/index.ts

This is because window configurations have been set by the user while the build configurations have been set by the build script.

Giving higher preference to window variables instead of build variables in configuration

---

.github/workflows/client.yml

In the release Docker image, we should set the build environment to STAGING.

Fixing the condition in Github Actions to set React env during release build

---

app/client/src/pages/AppViewer/viewer/AppViewerHeader.tsx

Fixes #717 
Added `canOutsideClickClose` to form dialog for share link window which would close the window if clicked outside it.
@satbir121 @Nikhil-Nandagopal for review.
Thanks.

Invite user modal in view mode can be closed by clicking outside

---

contributions/ClientSetup.md

I have faced a minor issue during client setup that I thought can save somebody (especially not that skilled in Docker yet - like me) fair amount of time. I couldn't start my container via `./start-https` due to conficting ports. The solution was to turn off the default `apache2` webserver on port `80` that is installed by default on Linux Ubuntu (18.04).

docs: client setup troubleshooting for Ubuntu

---

app/client/src/pages/UserAuth/Login.tsx
app/client/src/pages/UserAuth/SignUp.tsx
app/client/src/pages/UserAuth/StyledComponents.tsx

Closes #691.
The problem was that 3rd party auth container was rendered despite no 3rd party auth providers should be allowed. I have fixed by adding it to an conditional rendering used for divider.
The second problem was `margin-right` that was set on `form`. This PR removes the margin if the form is the only child, thus has no siblings like 3rd party auth providers.
The changes fix the issues for both Login and Signup.

style: center login form when 3rd party auth is not enabled

---

app/client/cypress/integration/Smoke_TestSuite/FormWidgets/Radio_spec.js
app/client/src/utils/Validators.ts

After changing the validator for radio options (#662), we started seeing tests failing. This was because the validator was sending in empty array (no options) when even one option is invalid. The cypress test was asserting values which will not be present since it is treated as invalid. This PR will fix validator to return valid options and filter out invalid options and also fix the test to not assert invalid options
Fixes #662

Fix failing Radio tests

---

app/client/src/pages/UserAuth/ForgotPassword.tsx
app/client/src/pages/UserAuth/Login.tsx

Addressing issue found in https://github.com/appsmithorg/appsmith/issues/587
Changed login page credential errors to display the warning icon instead of the danger icon on the form message.

Display warning icon for login screen credential errors

---

app/client/src/pages/UserAuth/ResetPassword.tsx

The `Reset` button in the reset password page was not disabled after the password was reset successfully. This has been fixed by disabling the `Reset` button and 'New Password' input field after a successful password reset.
**After the changes**
Fixes #636 
- Tested it manually

Fix Reset password not disabled after successful reset

---

app/client/src/constants/DefaultTheme.tsx

- Create a checkbox and try toggling it, you will see a flicker due to the active styles removing the background
- Create a radio button and try clicking on an already selected option, the option will show as unselected but when the mouse is released it will be selected.
- Try dragging a checked checkbox due to the active styles it will show as unchecked, one dropped it will become checked again.
#994 
1. Creating a checkbox and toggling it
2. Creating a radio button and selecting the selected option
3. Dragging the checked checkbox

Fix active styles for checkbox & radio

---

app/client/src/components/designSystems/appsmith/TableColumnsVisibility.tsx

Hidden column list has now been bounded and had a scroll bar added.
Spacing added between name and Icon.
Text clipped for very long column names and width now bounded.
Fixes #981 
Tested manually and verified on the following systems.
Firefox on debian stretch 10
Chrome on debian stretch 10

Fix the hidden column list is not bounded and overflows in height (#981)

---

.github/workflows/client.yml

Our Cypress tests are not working properly for internal pull requests & re-running of Github Actions. This is a potential fix for that.

Getting Cypress to work correctly for internal pull requests

---

app/client/src/components/editorComponents/CodeEditor/styledComponents.ts

This fix if merged shows the selection background by hovering on autocomplete options.
Fixes #946 
Verified in the front end with the changes
Hey @hetunandu @Nikhil-Nandagopal I have made changes and attached a screenshot, please review if it is the change we are expecting here.
Thanks !

fix(autocomplete): show selection background on hover for autocomplete

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java

Removed invitation token from the invite URL in the invitation email
Fixes #650 
- Locally using Postman

Removed invitation token from the invite email

---

app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx

Fix extra blank scrollbars that showup in the evaluated value popup on Firefox, when there's an external mouse connected.
This is a Bug fix (non-breaking change which fixes an issue).
Before this PR:
After this PR:

Fix blank scrollbars on Firefox

---

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/SegmentConfig.java

This implementation allows us to configure the log level of Segment via setting the application property `logging.level.com.appsmith.server.configurations=trace`.

Add logging to segment SDK

---

app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/PageController.java

The list endpoint shouldn't be supported due to risk of OOM/huge data as mentioned in the related issue description
Fixes #836 
- Manually

Made getAll operation of PageController unsupported

---

app/server/appsmith-server/pom.xml
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/User.java
app/server/appsmith-server/src/main/java/com/appsmith/server/notifications/EmailSender.java
app/server/appsmith-server/src/test/java/com/appsmith/server/controllers/UserControllerTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/notifications/EmailSenderTest.java

Added email verification during `User `creation by adding Java validation API `@Email` annotation on the `email `field of the `User `object. Updated the email verification logic in the `EmailSender `using Apache commons validator's `EmailValidator`
Fixes #627 
- Locally using Postman

Added email verification while creating user and sending email

---

contributions/ServerSetup.md

Adds instructions on how to get a local MongoDB and Redis instances up for starting off.

Add pre-requisites instructions to server setup

---

app/client/cypress/integration/Smoke_TestSuite/ApiPaneTests/Action_PageOnLoad_spec.js
app/client/cypress/support/commands.js
app/client/src/api/Api.tsx
app/client/src/components/formControls/InputTextControl.tsx
app/client/src/sagas/ActionExecutionSagas.ts

- If a pageOnLoad action fails to execute, the client was put in a bad state. The main reason was that we were not handling this error in the saga. This PR will catch any issue during this execution and thus avoid the app crash
- Also noticed config getting mutated in the Api class which was causing the action specific timeout to be applied on subsequent api calls. This PR makes this operation generate a new object on each call instead of mutating the existing one
Fixes #1203 
- Cypress tests to assert page load and run after page load failure

Fixes issue for pageOnload action timing out crashing the app.

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/AnalyticsService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java

This PR adds an `isFromInvite` field to the `create_USER` event.

Add isFromInvite field to create_USER event

---

app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppSmithErrorWebExceptionHandler.java

All the errors which are not handled by `@ExceptionHandler` (ex- 404 by the Netty) are handled by [DefaultErrorWebExceptionHandler](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/web/reactive/error/DefaultErrorWebExceptionHandler.html) which is autoconfigured by [Spring boot](https://docs.spring.io/spring-boot/docs/current/api/org/springframework/boot/autoconfigure/web/reactive/error/ErrorWebFluxAutoConfiguration.html).
The behaviour of this particular handler is to render an HTML for browsers and JSON for machines (ex- Postman):
https://github.com/spring-projects/spring-boot/blob/bd27756efcad283cf5b6bf790e54ce2a4192c0c7/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/reactive/error/DefaultEr …

Added an WebExceptionHandler

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java

When an Application is cloned, the cloned Pages are suffixed with ` Copy` as well. This PR fixes it to not rename Pages that are cloned as part of cloning an Application.
Fixes #698 

Don't append " Copy" suffix to cloned pages in cloned application

---

app/client/src/pages/Editor/Explorer/Pages/PageEntity.tsx
app/client/src/utils/helpers.tsx

In page name edit, when the user entered a special character cursor shouldn't move with space. Previously defined `resolveAsSpaceChar` function was replace with `resolveAsEmptyChar` function.
Fixes #765 

Fix page name special character bug

---

README.md
app/server/appsmith-plugins/rapidApiPlugin/src/main/java/com/external/plugins/RapidApiPlugin.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java

Both REST and Rapid API Plugins had a dependency on the user adding the URL prefix, such as HTTP or HTTPS. With this change, by default, when the URL does not have a prefix, "http://" is added to the URL.
Additionally, found a quick typo in the main README.md for the word "manipulate" and fixed it.
Fixes #944 

BugFix (#944): Add HTTP prefix to URLs in RestApiPlugin and RapidApiPlugin

---

app/client/src/sagas/WidgetOperationSagas.tsx

The issue was caused due to the fact that when pasting a tabs widget, the references to the new child widgetIds in the `tabs` property of the tabs widget were not updated. Resulting in pasted widgets being reflected in the original tabs widget.
Fixes #1258 
- The fix will not fix existing widgets. Users with "copied" tabs widget, will have to delete them and paste again for the fix to work.

Update widgetId references to a copied TABS_WIDGET's tabs property

---

app/client/cypress/integration/Smoke_TestSuite/ExplorerTests/Entity_Explorer_Widgets_Copy_Paste_Delete_Undo_Keyboard_Event_spec.js
app/client/src/pages/Editor/index.tsx

Due to the use of incorrect hotkey modifier, Ctrl + C, Ctrl + V and Ctrl + X combos did not work on windows and linux machines.
Fixes #704 
Manually tested on Windows machine.
Not tested on linux machines.

Fix keyboard shortcuts on windows and linux machines

---

app/server/appsmith-plugins/mssqlPlugin/pom.xml

This is a hotfix for fixing the build step for the MsSQL jar. Since the dependency is a signed jar, we need to exclude some of files from the Manifest file in the final jar. Without this exclusion, the `mssql-plugin` will not come up.

Fixing the build for mssql plugin

---

app/client/src/AppRouter.tsx
app/client/src/utils/helpers.tsx

Fixes the issue of theme not properly loading in /applications/ route
Fixes #1386
- Test A tested with loading `/applications`, `/applications/`, `/settings`, `/settings/` routes theme was loading properly
Hey @trishaanand @mohanarpit can you review the code for the fix?

fix theme breaking with a slash in url

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/MockPluginExecutor.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionServiceTest.java

Fixes #1416
RestAPI throwing null pointer exception because of datasource configuration being null. This happened because we were reading datasource configuration from the action object instead of datasource object (which may or may not have been pulled from datasources collection). In case of external datasource, this was not populated correctly.
This was not caught during regression or manual testing because usually we do not use external datasources for rest api. We instead usually only use embedded datasources.

Bug Fix : Reading the datasource configuration incorrectly from actionDTO instead of datasource object.

---

app/client/cypress/integration/Smoke_TestSuite/OrganisationTests/UpdateOrgTests_spec.js
app/client/cypress/locators/HomePage.json
app/client/cypress/support/commands.js
app/client/src/components/ads/TextInput.tsx
app/client/src/pages/Applications/index.tsx
app/client/src/pages/organization/General.tsx
app/client/src/pages/organization/settings.tsx

Following test cases are implemented
1. Open the org general settings and update the org name. The update should reflect in the org. It should also reflect in the org names on the left side and the org dropdown.
2. Open the org general settings and update org email. The update should reflect in the org.
3. Open the org general settings and update org website. The update should reflect in the org.

Feature: Org update test cases 

---

app/client/src/components/ads/TagInputComponent.tsx
app/client/src/components/editorComponents/form/fields/TagListField.tsx
app/client/src/constants/messages.ts
app/client/src/pages/organization/OrgInviteUsersForm.tsx

An Invalid email error was shown after submitting the form with an incorrect email address. 
As soon as we hit the enter the incorrect email an error message is shown, and the submit button is disabled.

Fix: Invalid email error in invite modal

---

app/client/src/components/editorComponents/LightningMenu/helpers.tsx

The widgets can call for data from API or Datasources. This happens when the user will click on the lightning bolt to choose a data source. The interaction as of now is that they have to click on each of them to add. This has been changed to hover in this PR.
Fixes #1363 
- UI test
- Cypress does not have a [`cy.hover()`](https://docs.cypress.io/api/commands/hover.htm) command. As suggested in workaround, test cases remain as `click({ force: true })`

fix lightning bolt menu onhover bug

---

app/client/src/actions/pageActions.tsx
app/client/src/actions/widgetActions.tsx
app/client/src/constants/ReduxActionConstants.tsx
app/client/src/sagas/PageSagas.tsx
app/client/src/sagas/evaluationsSaga.ts
app/client/src/selectors/dataTreeSelectors.ts
app/client/src/workers/evaluation.worker.ts

Action execution needs an evaluation of all bindings before the server call is made. This means onLoadActions need to ensure an evaluation has taken place before it can execute. This PR will implement a postEvalActions support to any eval subscriber actions which lets it list any actions that need to be dispatched after evaluation trigger has successfully evaluated.
Fixes #1504

Add post eval action support

---

app/client/src/components/designSystems/appsmith/TabsComponent.tsx
app/client/src/components/propertyControls/TabControl.tsx
app/client/src/mockResponses/WidgetConfigResponse.tsx
app/client/src/sagas/WidgetOperationSagas.tsx
app/client/src/widgets/TabsWidget.tsx

Fixes issue where placing widgets into the first tab of a tabs widget was disallowed.
Solution: Deprecate use of `tabId`, instead use the tab's `widgetId` as a reference.
Fixes #1524
Fixes #1523 
All scenarios related to Tabs widget were manually tested

Fix: Tabs Widget

---

app/client/src/components/designSystems/appsmith/Table.tsx

Fix table crash issue when selectedRowIndices was reset
Fixes #1537 
Manually

Fix table crash issue when selectedRowIndices was reset

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/OrganizationServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/OrganizationServiceTest.java

Modified new organization creation to use the current user email as default if no email has been provided. This behaviour is meant to indicate POC for a new organization. Possible UI change corresponding to this is being discussed in the issue.
Fixes #782 
- Added additional assertion to create organization test

Added fallback email to new organization from user email

---

app/client/src/widgets/InputWidget.tsx

Input widget's regex function fails when `regexParts` is null.
Tested manually.

Handle null regex parts in input widget regex function

---

app/client/src/components/editorComponents/actioncreator/ActionCreator.tsx

Add a default selection to the Download File Type dropdown so that it can be deselected.
Fixes #674

Allow Download File Type dropdown to be deselected

---

app/client/package.json
app/client/src/utils/DynamicBindingUtils.ts
app/client/yarn.lock

After moving to worker based evaluation, we did not need the atob and btoa dependencies anymore. Using this was causing a maximum call stack error in our worker by calling itself again(same reference). This PR will fix this by removing that extra dependency and use the browser provided functions instead
Fixes #1611

Remove extra dependency and use browser atob and btoa

---

app/client/src/components/designSystems/appsmith/Table.tsx
app/client/src/components/designSystems/appsmith/TableStyledWrappers.tsx

Used display table to style table and adding overflow to wrapper div of table instead inner overflow.
Fixes #982 

Fix-Table header and body length going out of sync if extended via width

---

app/client/src/widgets/FormWidget.tsx

Form widget checks for children values and sets its property accordingly. While doing this it would check for previous values with `shalowEqual` which will always return `true` for arrays. Moving to lodash deep isEqual which does a value check solved this issue
Fixes #1280

Fix form widget eval loops for arrays

---

app/client/cypress/integration/Smoke_TestSuite/Applications/UpdateApplication_spec.js
app/client/src/components/ads/Tooltip.tsx
app/client/src/pages/Applications/ApplicationCard.tsx
app/client/src/utils/helpers.tsx

Description:
Adding an ellipsis by CSS for the text longer than 3 lines and adding popover that will show the full name on hover.
Fixes #720

Fix long app names not visible

---

app/client/package.json
app/client/public/index.html

This is to allow us to enable/disable Intercom chat based on the INTERCOM_APP_ID and CLOUD_HOSTED environment variables. Currently, the code would enable these configurations using build time variables. Now Intercom initialization is moved to a runtime variable.
- Manual

Moving the intercom initialization to the body in index.html

---

app/client/docker/templates/nginx-linux.conf.template
app/client/docker/templates/nginx-mac.conf.template
deploy/template/nginx_app.conf.sh

`client-max-body-size` directive is missing in the nginx https proxy server, resulting in a limit to the api request body sizes.
Fixes #1694
Manually

Add client-max-body-size directive to nginx https proxy

---

app/client/cypress/integration/Smoke_TestSuite/QueryPane/AddWidgetTableAndBind_spec.js
app/client/src/configs/index.ts
app/client/src/utils/AppsmithUtils.tsx

Now we enable/disable all analytics in a central location in the configs class. This ensures that each analytics function can simply check it's own value and not worry about checking for the disableTelemetry flag

Moving all telemetry check to the configs class

---

app/client/src/components/editorComponents/CodeEditor/styledComponents.ts

Binding brackets should go to error state if there is an error. Related to #1648

Add error style to bindings

---

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java

This change has been made to bring down the number of documents fetched in mongo db query during update layouts' fetching actions on page load.
Fixes #1730 

Adding index for unpublishedAction.pageId 

---

app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/UserController.java
app/server/appsmith-server/src/main/java/com/appsmith/server/notifications/EmailSender.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserOrganizationServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/OrganizationServiceTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserServiceTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ShareOrganizationPermissionTests.java

The blocking code for email sending is triggered and then immediately returned.
Fixes #1761 
This code has been tested by using Thread.sleep instead of blocking send mail call to ensure that the invite flow returns back successfully before the threads wake up.

Email sending is now non-blocking. 

---

app/client/src/pages/AppViewer/viewer/AppViewerHeader.tsx

Feature: Hide header in appviewer to embed a page in an iframe
Fixes #1765 
Tested with `embed=true` queryParams in Appviewer

Hide AppViewer Header

---

app/server/appsmith-server/src/main/java/com/appsmith/server/constants/FieldName.java
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Application.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ApplicationRepository.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewPageServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java

The cloned application process, when interrupted by client cancellation (due to request timeout) leads to the flow getting cancelled mid way. This leads to a clone getting created (and can be viewed by the user) which wasn't created completely and is in a corrupted state. To solve this, two changes have been made :
1. When creating the clone, start with a deep copy of the original application without the pages being copied. This ensures that even if the cloning process stops midway, the cloned application does not point to the original application's pages.
2. Ensuring that if the client cancels the request, the server still finishes the entire request, whether or not the client is interested. This ensures that once triggered, the clone of the application would be available on the user's …

[Bug Fix] : Clone Application creates corrupted clone when interrupted.

---

app/client/src/sagas/userSagas.tsx

> With this fix, the theme flag stored in localStorage will be cleared out when the user logout.
Fixes #963 

Fix: Theme restricted for selected account

---

app/client/src/pages/Applications/ApplicationCard.tsx
app/client/src/pages/Applications/index.tsx

> After this fix, hover UI on app cards will look the same on both sides of the card.
Fixes #1607 

Fix: App card boundaries UI

---

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java

Updated the indices to single indices and removed the compound index. This ensures that both fetch actions by app id (during load of actions in edit/view mode) and fetch actions by page id (during update layout) are indexed queries.

[Bug Fix] Indices not working for fetching actions during update layout

---

app/client/src/sagas/ActionExecutionSagas.ts
app/client/src/workers/evaluation.worker.ts

Pass the execution params in the action execution callback functions so that you can access them later on

Pass execution params to action callback

---

app/server/appsmith-server/src/main/java/com/appsmith/server/filters/MDCFilter.java

Adding thread name to the context of logs to allow for the thread names to be printed for each log.

Print the executor thread name in logs

---

app/client/.gitignore
contributions/docs/TestAutomation.md

This PR:
- Re-orders bullet points to follow `set up -> introduction -> running -> adding tests` order.
- Adds a link to client setup from test doc.
- Switches to complete relative paths from project root.
- Promotes use of gitignored `cypress.env.json` instead of `cypress.json`, links to other methods.
- Switches to the `1.` numbering system to aid in future reviews.
Fixes #1837

Improve test automation docs

---

app/server/appsmith-plugins/dynamoPlugin/src/main/java/com/external/plugins/DynamoPlugin.java

Scheduling the blocking dynamo db commands onto elastic thread pool to ensure that precious main event loop threads are not blocked by executing dynamo db plugin commands.
Fixes #1851

Making dynamo db's blocking commands run on elastic thread pool.

---

app/client/.gitignore
app/client/cypress/integration/Smoke_TestSuite/DisplayWidgets/Map_spec.js
app/client/cypress/plugins/index.js
app/client/src/components/designSystems/appsmith/MapComponent.tsx
app/client/src/components/propertyControls/LocationSearchControl.tsx
app/client/src/widgets/MapWidget.tsx

- Initial location title now shows up on reopening the widget.
- Fix for that also fixes the crash in map widget. (#1506)
- Added a workaround for a race condition on declaring and using `window.google` (#1808)
Fixes #1430 
Fixes #1431
Fixes #1506 
Temporary hotfix for #1808 
- Manually verified
- Added automated tests.

Fix: Maps widget crash on wrong initial location datatype

---

app/client/start-https.sh

Bash on mac doesn't like `*@(icrosoft|WSL)*` and `$(< /proc/version)`
Fixes #1756
Manually on both windows and mac

Hotfix for mac start-https.sh script

---

app/client/src/widgets/TabsWidget.tsx

Fixes issue where binding `selectedTab` of a tabs widget wasn't updating when tabs were switched.
Fixes #1889 
Tested manually

Fix selectedTab binding issue

---

app/client/src/components/designSystems/appsmith/MapComponent.tsx
app/client/src/components/editorComponents/DragLayerComponent.tsx

Changing `useLayoutEffect` to `useEffect` fixes the infinite loop issue.
Fixes #1833
Dragged the widget around the boundary of the page / modal.
Thank you for your help on repro! I was so lost without a proper repro.

Fix infinite loop crash on widget drag

---

contributions/ClientSetup.md

- Restructure client setup troubleshooting
- Update docs to explain the new argument for `./start-https.sh` (#1756)
- Documentation

Improved client setup and workflow

---

app/server/.run/ServerApplication.run.xml
contributions/ServerSetup.md

Run configuration makes use of the EnvFile to add .env to the run config.
Fixes #1938 
- Used to run project on IntelliJ

Added IntelliJ run configuration for an easier getting started experience for contributors

---

app/client/cypress/integration/Smoke_TestSuite/DisplayWidgets/Map_spec.js
app/client/src/components/designSystems/appsmith/MapComponent.tsx
app/client/src/components/designSystems/blueprint/ButtonComponent.tsx
app/client/src/components/propertyControls/LocationSearchControl.tsx
app/client/src/utils/hooks/useScript.tsx
app/client/src/widgets/MapWidget.tsx

- Add `head` option to `useScript`
- Start using enum `ScriptStatuses` instead of strings in `useScript`
- Switch `LocationSearchControl` and `MapComponent` to `useScript`
- Fix a bug where user could not clear initial location.
Fixes #1808
Manually, there should be no regression.

Make sure google is available before loading components

---

app/client/src/sagas/ActionExecutionSagas.ts

If any onPageLoad actions depend on an evaluation before execution, they fail. We are now waiting for an eval before executing the next set of onPageLoad
Fixes #1832 

Fix page load sequence not waiting for evaluation

---

app/client/.gitignore
app/client/package.json
app/client/yarn.lock

Update `react-scripts` to gain eslintcache capability.
Irrespective of the change eslint was linting all files on start and recompile
Fixes #1943
Local dev environment

Cache eslint results

---

app/client/src/sagas/ActionExecutionSagas.ts
app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java
app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java

1. Propagte mysql test datasource failure exception message to UI. 
2. Change build TC to reflect the same. 
Fixes appsmithorg/appsmith #2000 
- By providing false and true authentication credentials when testing datasource.

[Bug] Propagte mysql test datasource failure to UI.

---

contributions/CodeContributionsGuidelines.md

Although the test automation doc contains details for integration tests, felt might be useful to add it here as well.
- doc update

add step for running cypress tests at code contribution guidelines

---

app/client/src/components/designSystems/appsmith/Table.tsx

Table column max width limit removed so that column can be resized to whatever level user wants. 
Fixes #1835 
- Manually Tested

Table column max width limit removed

---

app/client/public/index.html

Check boolean env variables against 'true' string
Fixes #2036
Convention with respect to boolean env variables (currently affects just `mailEnabled`)
- set `APPSMITH_MAIL_ENABLED` as  'false' or '' or omit
- restart nginx
- `cd app/client`
- `./start-https.sh`
- Forgot password page should show email not configured warning
- set `APPSMITH_MAIL_ENABLED` as  any non empty string
- restart nginx
- `cd app/client`
- `./start-https.sh`
- Forgot password page should `not` show email not configured warning

Check boolean env values against 'true' string

---

app/client/src/widgets/DropdownWidget.tsx

Checks type and defaults to empty array for `this.props.selectedOptionValueArr` on Dropdown.
Fixes #2060 
N/A

Check type and default to empty array.

---

app/client/src/utils/DynamicBindingUtils.ts
app/client/src/workers/evaluation.worker.ts

Certain functions defer execution to later that happen after our eval context. This is not safe and should not be allowed to reference
Fixes #1816
Manually

Remove unsafe functions from eval

---

deploy/install.sh

Installation script calls the default database initialization as a "fresh" installation, which might not be true. Users can opt to choose an external database for a fresh install as well.
Fixes #2124 
- Minor fix

Modified installation instructions

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionServiceTest.java

The current solution resets "execute on page load" for all new actions. This means that even when the action that we copied from was set by the user to run on page load, the new action will not retain the setting. 
This is because the frontend is not aware of the "user set on load" prop, and server treats every new request as a fresh action.
The property will be auto-set in the future if it is referenced in the layout, but will need to be explicitly set by the user if they need it to be so.
Fixes #2133 
- Modified existing Junit

Reset execute on page load for new actions (copied or otherwise)

---

app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx
app/client/src/reducers/entityReducers/actionsReducer.tsx

Merge existing data source into action config. This is a hotfix to avoid crashing. A longer proper refactor will be part of #2167
Fixes #2102
Automated tests from #2087 cover the underlying case.
#2167 will remove the hotfix from here and #2087.
Manual QA steps on hotfix:
- Create a widget
- Create an API
- Convert API to data source
- Navigate to canvas
- Rename a widget
- Navigate to API

Hotfix crash on navigate to API page after widget rename

---

app/client/src/widgets/TableWidget.tsx

Added undefined check on selectedRowIndices property before checking its length since it can be undefined
Fixes #2110 
- Manual tests

Fix: Added undefined check on selectedRowIndices property before checking length

---

app/client/src/components/designSystems/appsmith/RichTextEditorComponent.tsx

Config to not force root element selected on press enter key
fixes #2048
Manually:
- enter should insert <br>
- shift+enter should insert <p>

br instead of p on enter within rte

---

app/client/src/pages/Editor/WidgetCard.tsx

Unselect prev widget on the canvas when dragging a new widget from the widgets sidebar
Fixes #2209
- manually

fix prev widget hidden when dragging new

---

app/client/src/components/designSystems/appsmith/TableUtilities.tsx

All other cases in the switch had a null check, default case was missing one
Fixes #2182 
@vicky-primathon can you reason about this and help with a way to test this out? I tried setting cell data in table to be undefined and it still worked.

null check on renderCell value

---

app/client/cypress/integration/Smoke_TestSuite/Binding/Bind_TableTextPagination_spec.js

Autocomplete was getting a bad data tree only when using tests. Keeping the property pane close to bypass the issue

Fix table text pagination

---

app/server/appsmith-plugins/postgresPlugin/src/main/resources/templates/meta.json
app/server/appsmith-server/src/main/java/com/appsmith/server/services/PluginServiceImpl.java

Two major things this PR fixes:
1. The meta.json files and the implementation of the reader were not in sync. This was a refactoring mistake. Fixed now.
2. When a meta.json file is not as expected, the whole plugins API breaks. This PR also fixes this by gracefully recovering when such a rogue meta.json file is present in any plugin.

Fix invalid templates and API breaking on invalid templates

---

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/AuthenticationDTO.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceContextServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/EncryptionServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/DatasourceStructureSolution.java

The `isEncrypted` field of `AuthenticationDTO` was not being ignored when serializing to JSON and sending to client. This is causing an incorrect value for this field being sent by the client, which shouldn't happen.

Fix Firestore datasources not encrypting secret key JSON when editing

---

app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/FirestorePlugin.java
app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/Method.java
app/server/appsmith-plugins/firestorePlugin/src/main/resources/editor.json
app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java

This PR adds support for `ADD_TO_COLLECTION` command, using which, one can add a document to a given collection, and it will be saved with an auto-generated ID, by Firestore.

Firestore ADD_TO_COLLECTION command support

---

app/client/src/components/designSystems/appsmith/TableColumnMenu.tsx

We can render the submenu inline, since the parent menu is rendered within a portal
fixes #2280
- manually

fix position for table column sub-menus while scrolling

---

app/client/src/sagas/WidgetOperationSagas.tsx

Since tabs array is an immutable we're not allowed to push objects. Create a copy of tabs to fix this.
fixes #2034
- manually

fix undo delete tab

---

app/client/src/widgets/TabsWidget.tsx

- select the first tab if the default tab is not found on load
- when the selected tab is deleted try to select default or first tab
- on deleting the default tab we are currently not updating the default tab at the moment since it would need further work and might be better to test and merge independently
Fixes #1984
Fixes #1638
- manually

select first when default or selected tab is not found

---

app/client/src/components/designSystems/blueprint/DropdownComponent.tsx

Added props `resetOnSelect`, `scrollToActiveItem` (is set as true this scrolls the list to the top selected item in list)
Fixes #2132
Fixes #998
- manually

fix options drop-down scrolling to top on selection and reset query for multi-select

---

app/client/src/components/editorComponents/EditableText.tsx
app/client/src/pages/Editor/PropertyPaneTitle.tsx

When the modal is closed by clicking the overlay the corresponding change method is not triggered.
Trigger change when the editable text unmounts
Fixes #992 
manually
deferred to adding tests once the new tests for the table widget are merged (#2184)

fix modal entity not renamed through property pane when closed by clicking on the overlay

---

app/server/appsmith-server/src/main/java/com/appsmith/server/constants/FieldName.java
app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/PageController.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ActionServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewPageService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewPageServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java

When an application is created, after creating a default page, just publish this application to ensure that both the application and the newly created default page have a published state before returning this to the user. This supports the launching of an application till this new application is deployed for the first time.
Fixes #1899 

All newly created applications now have a default published state.

---

app/client/cypress/plugins/index.js
app/client/src/sagas/evaluationsSaga.ts
app/client/src/utils/WorkerUtil.test.ts
app/client/src/utils/WorkerUtil.ts
app/client/src/workers/evaluation.worker.ts

- Create a rpc-like layer to communicate with our worker.
- Wrap messages from worker to also contain the `requestId`.
This is a tentative fix of an issue that can happen because of race between worker messages.
Fixes #2169
Added unit tests.

RPC-like layer with graceful startup and shutdown around a webworker

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewPageServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java

Zipping flux with mono leads to mono not getting repeated and only the first emitted value of flux is processed further. This is leading to only a single page getting emitted in a multi page application.

[Bug] Multi page applications return only a single page when fetching pages per application

---

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java

Added a migration to old rest api datasources which adds the new mandatory key `isSendSessionEnabled` with value `N`

---

app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/UserController.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/OrganizationServiceTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserServiceTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ShareOrganizationPermissionTests.java

Once the invite flow gets triggered, the client should not be able to cancel this flow. To achieve this, we use a synchronous sink which ignores cancellation.
Fixes #2395 
Added a test case which cancels the invite flow in 5 ms and asserts that the invite was successful.

Invite users once triggered should not be cancellable.

---

app/client/src/sagas/evaluationsSaga.ts
app/client/src/utils/WorkerUtil.test.ts
app/client/src/utils/WorkerUtil.ts

- Wait for shutdown to complete before letting new requests queue up.
- use `finally` to cleanup cancelled request channels
Fixes #2386
Added tests for saga cancel.

Cleanup cancelled requests

---

app/client/cypress/integration/Smoke_TestSuite/Onboarding/Onboarding_spec.js
app/client/cypress/support/index.js

`after` hook of the individual tests doesn't seem to get called when the test fails. Moving the clearing code to the  `before` hook to clear any indexeddb entries in `support/index.js` works.
Fixes #2405

Fix onboarding test failure causing other tests to fail

---

app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/APIConnection.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/APIConnectionFactory.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/OAuth2Connection.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java

This change uses an [ExchangeFilterFunction](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/reactive/function/client/ExchangeFilterFunction.html) type as a type parameter for REST APIs so that any mutations that need to be performed on the webclient during plugin execution can be recorded and created in the datasource create step in the future.
This change also contains the necessary changes to implement the status quo of REST APIs with no authentication.
Fixes #2255 
- Existing JUnit tests are all that is required since the change only introduces a new way of doing things
- Manual testing with existing datasource + API action (no auth):

Added type parameter for REST API plugin, and changes for no auth

---

app/client/src/components/designSystems/appsmith/ContainerComponent.tsx

Old Edge does not have scroll behaviour functionality 
https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-behavior
This PR will fallback to the old way of scrolling when this functionality does not exist
Fixes #2431 
> Not been tested

Handle for scenarios scrollTo is not available in browser

---

app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomNewActionRepository.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomNewActionRepositoryImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/LayoutActionServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutActionServiceTest.java

During the process of updating a page's layout, this fix adds a query to pick actions that are associated to the page, and marked to be executed on load by the user. This set of actions will exist in a separate list.
Fixes #2217 
- Added JUnit tests to check for actions that are not referenced in the dsl, but have been set to execute on load by the user

Fixed unreferenced actions not being triggered for execute on load

---

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonConfig.java
app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/UserController.java
app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java
app/server/appsmith-server/src/main/resources/application.properties
app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserServiceTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserServiceWithDisabledSignupTest.java

Sign up can be disabled by setting `APPSMITH_SIGNUP_DISABLED` environment variable to `true`. It defaults to `false` so signup is not disabled unless this environment variable is set.

Disable uninvited signups via environment variable

---

app/client/src/widgets/TableWidget.tsx

Fixes the `navigateTo` tests failing. 
This PR fixes table widget's selectedRow property getting set to undefined on mount by checking for null value in selectedRowIndex

Make sure Table selected row is not set to undefined on mount

---

app/client/src/sagas/EvaluationsSaga.ts

Whenever we load a new page, we want to clear all cache and re evaluate after new page layout is loaded into the state.
This was not happening because URL_DATA was getting set and triggering an evaluation before new layout is loaded.
This PR unsubscribes to the `SET_URL_DATA` event to avoid evaluating with new url data and old layout

Make first eval after page change happen with new layout first

---

app/client/package.json
app/client/src/components/editorComponents/form/FormTextField.tsx
app/client/src/pages/common/CustomizedDropdown/index.tsx
app/client/yarn.lock

Bump `@blueprintjs/core` to add support for `asyncControl` prop.
Fix for caret jumping to the end of the input in case we're not updating the input value directly using `setState` within the component (for example while using `redux-form`)
Ref: https://github.com/palantir/blueprint/issues/4298
Diff: https://github.com/palantir/blueprint/compare/@blueprintjs/core@3.33.0...@blueprintjs/core@3.36.0
Fixes #2485
- manually

Update blueprint core to use async control

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionServiceTest.java

When a user tried to test the "next url" for pagination without entering any input, the server throws a null pointer exception. This change adds a null check for this scenario.
Fixes #2424 
- Added a JUnit test case

Null check for empty pagination next url

---

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/constants/FieldName.java
app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/AuthenticationDTO.java
app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/OAuth2.java
app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/UpdatableConnection.java
app/server/appsmith-plugins/restApiPlugin/pom.xml
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/OAuth2Connection.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/connections/OAuth2ConnectionTest.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceContextServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/DatasourceStructureSolution.java

OAuth2 is inherently part of the API plugin. The following functionality has been added to the plugin as part of this PR:
1. Client credentials flow for OAuth2. Users can now connect to APIs that require long-lived or short lived access tokens. Since the automated flow for API plugins cannot be interrupted, this change only supports 2LO. 3LO will remain a front end feature for now.
2. All client secrets are encrypted on the backend. This also means that they are not editable once configured. Users will need to re-enter their authentication details.
3. Customizable Header prefix (defaults to Bearer)
4. Choice to include access token in either header or query params (Official documentation recommends using headers)
5. Auto refresh of credentials on expiry. The client credentials flow …

Added Oauth2 functionality for REST APIs

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserDataServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ReleaseNotesService.java

This is needed for remembering when a user has viewed
release notes. Snapshot versions aren't a tagged marker
on the version timeline so aren't useful for this purpose.

Handle snapshot versions as special

---

app/client/public/index.html
app/client/src/components/designSystems/appsmith/RichTextEditorComponent.tsx

Using `useScript` hook to load tinymce, also re-run effect to set value when `editorInstance` is created
This should fix the `RichTextEditor_spec`, where it seemed like a race condition b/w setting default value and tinymce instantiation
- existing RichTextEditor_spec should pass

use script loader for tinymce

---

app/client/src/components/ads/Dropdown.tsx

Use popover for dropdown options to prevent overflow issues.
- manually: invite modal, `select a role` styles

use popover for ads dropdown options

---

app/client/cypress/integration/Smoke_TestSuite/FormWidgets/RichTextEditor_spec.js
app/client/src/components/designSystems/appsmith/RichTextEditorComponent.tsx

Use `editor.on("init")` to set initialized status for RTE
ref: https://www.tiny.cloud/docs/advanced/events/#editorcoreevents
- manually: on refresh `RTE` should render default value

use editor init event intead of setup to check if initialised

---

app/client/src/constants/errors.ts
app/client/src/constants/messages.ts
app/client/src/sagas/ErrorSagas.tsx

Don't expose app redux action types in toast errors
Fixes: #2642
Fixes: #2656 
Could not be reproduced

Never show the redux action type in toast errors

---

app/client/src/components/designSystems/appsmith/TableColumnsVisibility.tsx
app/client/src/index.tsx

Clone hidden columns array intead of mutating
Always freeze by default in v8.0.0 (https://github.com/immerjs/immer/releases/tag/v8.0.0)
- manually: toggle visibility of a table column

enable immer autofreeze only in development

---

app/client/src/components/designSystems/appsmith/CascadeFields.tsx
app/client/src/components/designSystems/appsmith/TableFilters.tsx

Hide table filters delete icon when there is no filters
Fixes #2135 

Fix-Hide table filters delete icon when there is no filters

---

deploy/install.sh

Add support for Linux Mint to `install.sh` to allow users to install Appsmith on Mint.
Fixes #2693
1. Launch Linux Mint 20.1
2. Run `./install.sh` with modifications made in [this commit](https://github.com/trdillon/appsmith/commit/98c945adc92af65a16e32779be91ec0f64250f82)
3. Run command `docker ps` after installation and observe running containers
4. Access Appsmith at `http://localhost`

Add Linux Mint support to install.sh

---

app/client/src/api/ActionAPI.tsx
app/client/src/entities/Action/index.ts
app/client/src/sagas/ActionSagas.ts

Action structure is different in view mode. This was causing issues setting the correct timeout actions with long timeouts were getting cancelled in the default 20s time. This PR will fix the structure when storing this response in the view mode to fix the issue
Fixes #2553

Fix for timeout being sent in a different location in view mode

---

app/client/cypress/fixtures/datasources.json
app/client/cypress/locators/DatasourcesEditor.json
app/client/cypress/support/commands.js

Removes SSL config from mongo test.

Remove SSL related clicks from `fillMongoDatasourceForm` cypress command

---

app/client/src/pages/organization/Members.tsx

Disabled the ability to sort by the `Delete` column on the `Members` page. This functionality is not necessary.
Fixes #597 
1. Run Appsmith with the changes made in [this commit](https://github.com/trdillon/appsmith/commit/b08b2b081b59645e200fd41401fdc4c7cd73a9ec)
2. Navigate to Manage Users
3. Click the Delete column
4. Observe the data not being sorted

Disable sort by Delete column in Members page

---

app/client/src/components/ads/Toast.tsx
app/client/src/sagas/WidgetOperationSagas.tsx

Fixes issue where users could undo delete long after the timeout has expired
Fixes #2714 

Fix Application crash on widget delete undo

---

app/client/src/pages/Editor/Explorer/Widgets/WidgetEntity.tsx

Fix action not a plain object on updating widget name, when the widget page id does not match the page id from the params 
Fixes #2637
- manually

fix: action not a plain object for widget entity name action creater 

---

app/client/cypress/integration/Smoke_TestSuite/Binding/InputWidgets_NavigateTo_validation_spec.js
app/client/cypress/support/commands.js
app/client/src/components/designSystems/blueprint/InputComponent.tsx
app/client/src/mockResponses/PropertyPaneConfigResponse.tsx
app/client/src/widgets/InputWidget.tsx

Add support for an `onSubmit` action for the input widget
In case the input widget is a text-area, we're disabling new line insertion on pressing enter key if this trigger is enabled  
- todo

add support for an onSubmit action for the input widget

---

app/client/start-https.sh

I introduced a small bug in this script in https://github.com/appsmithorg/appsmith/pull/2729 when I didn't account for the swap to bash's `if` logic.
Ran the script without issues

Fixes a small syntax issue with ./start-https.sh

---

app/client/src/utils/DynamicBindingUtils.test.ts
app/client/src/utils/DynamicBindingUtils.ts
app/client/src/workers/evaluation.test.ts
app/client/src/workers/evaluation.worker.ts
app/client/src/workers/evaluationUtils.ts

We were running multiple validation on the same properties. The first one would trigger a validation failure, the second one would clear it.
This PR attempts to remove the 2nd validation altogether and adds fixes for tests that started failing as a result.
Fixes #2701
Fixes #2758 
Manually (Needs Automated tests to prevent future regression)

Avoid double validation

---

app/client/src/sagas/ActionExecutionSagas.ts

Allow for navigateTo urls to be of `mailto` or `tel` url schemes to open specific apps directly with pre filled data

Allow for navigateTo urls to be of `mailto` or `tel` url schemes t

---

app/server/appsmith-plugins/restApiPlugin/pom.xml

1. Run the server from IntelliJ, execute two Rest API actions, one with a signature and the other without.
2. Run the server from command line after building with Maven, execute two Rest API actions, on with a signature and the other without.
3. Run all tests from IntelliJ.
4. Run all tests from command line with Maven.
I've also ran the server as well as ran the tests after deleting the `~/.m2` folder.
1. Two dependencies needed a `provided` scope on them.
2. Added additional jackson datatype dependencies with explicitly mentioned version number, because their version was not being computed correctly by Maven.
3. Don't use `spring-boot-starter-webflux`, instead use `spring-webflux` directly and explicitly specify exclusions on libraries that need scope to be `provided`.
4. Added …

Fix RestAPI plugin not starting up

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserServiceTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserServiceWithDisabledSignupTest.java

Fix an issue with a user's email being duplicated as the user's name when inviting a new user.
Fixes #595 
1. Run Appsmith with the changes made in this PR
2. Navigate to Manage Users
3. Invite a new user
4. Observe the Name column

Fix user email duplicated as name

---

app/client/src/sagas/WidgetOperationSagas.tsx

Fix widget add scenarios to make sure there are not conflicts between widget names and action names
When adding a new widget, the new widget's name should not conflict with an existing action name
Fixes #2773 
Manually

Fix: New widget and action name conflicts

---

app/client/src/utils/WidgetPropsUtils.tsx

Set correct canvas names for renamed canvas widgets.
Should be merged only after #2778 & #2779
Fixes #2772 

Migrate renamed canvas widgets to the correct name

---

app/client/src/components/ads/Toast.tsx

Wrap words in a toast message to avoid loosing information in a message
Before
After
Fixes #2831

Wrap words in a toast message

---

app/client/build.sh

A script's return code is the return code of it's last line. This hides issues when there's an error in the middle of the script.
As a result, our builds were passing even when there was an error. 
This PR changes build to fail immediately on any failure in the script.

Set build.sh to fail on any failure

---

app/client/src/mockResponses/PropertyPaneConfigResponse.tsx
app/client/src/widgets/InputWidget.tsx

Add option to reset input text after submitting
- manually

Add an option to set reset the input widget's value on submit

---

app/client/src/components/editorComponents/ApiResponseView.tsx
app/client/src/constants/ActionConstants.tsx
app/client/src/reducers/entityReducers/actionsReducer.tsx
app/client/src/sagas/ActionExecutionSagas.ts
app/client/src/sagas/ErrorSagas.tsx

Actions with error responses were setting an undefined value inside the data tree. We need instead have a separate handling of the error messaging and the actual data getting set inside the data tree.
Fixes #2838 

Better handling of action error response

---

app/client/src/pages/AppViewer/viewer/AppViewerHeader.tsx
app/client/src/pages/AppViewer/viewer/PageTabsContainer.tsx

Fix app viewer's bottom border when the tabs arent rendered
- manually

Fix app viewer's bottom border when the tabs arent rendered

---

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java

Plugin documentation now points to v1.2.1 for all plugins. Plugins without documentation point to the expected urls. This is same as previous behaviour, and should be filled out within the week.

Modified documentation links for plugins

---

app/client/src/pages/AppViewer/viewer/PageTabsContainer.tsx

Handle `touchStart/touchEnd` events so that the tab navigation buttons work on mobile 
- manually

fix viewer tabs arrow btns on mobile

---

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/MustacheHelper.java
app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/MustacheHelperTest.java

This is a nasty edge case. We are using plugin specified templates as custom fields for individual plugins, but we are using them with hard-coded indexes. That means it is possible that a valid property is set at index 2, but indices 0 and 1 are null properties. The lack of null check here then breaks the whole action execution.

Fix bindings in Firestore plugin's where condition value

---

app/client/src/widgets/InputWidget.tsx

Do not trigger input on submit action if the input's state is invalid
Fixes #2928
- manually

Fix input's onSubmit action being triggered if its validation is failing

---

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ActionConfiguration.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java

1. Add toggle param to ActionConfiguration class.
2. Add TCs to test toggle on/off/null.
Fixes #2897 
Tested via Junit TCs. Add 3 TC:
1. for toggle set to true.
2. for toggle set to false.
3. for toggle see to null.

Enable toggle for params encoding

---

app/server/appsmith-server/src/main/java/com/appsmith/server/acl/RoleGraph.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/OrganizationServiceImpl.java

The order in the roles dropdown in the Share modal is unpredictable and often counter-intuitive. They are not ordered in increasing or decreasing privileges which makes it very confusing when trying to make a choice by reading the descriptions. This PR fixes the order and makes it predictable.
Screenshot with counter-intuitive order of roles:

Fix order of roles in share modal

---

app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java
app/server/appsmith-plugins/amazons3Plugin/src/test/java/com/external/plugins/AmazonS3PluginTest.java

Change reponse format. Earlier some responses could be accessed as query.data (based on some early feedback) but it shows up with an error label on UI. So changing it to a valid format. 
Fixes #3022 

change response data format for AmazonS3 Plugin

---

app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/AuthenticationFailureHandler.java
app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/CustomOidcUserServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/CustomServerOAuth2AuthorizationRequestResolver.java
app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/ClientUserRepository.java
app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonConfig.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java
app/server/appsmith-server/src/main/resources/application.properties

1. When signup is disabled with `APPSMITH_SIGNUP_DISABLED=true`, signing up is disabled from form as well as from OAuth.
2. When email domains that can sign up are restricted using `APPSMITH_SIGNUP_ALLOWED_DOMAINS=appsmith.com,example.com`, then any email with a domain other than these will not be allowed to sign up, from form or OAuth.
1. Any existing user can login using any method. A user who signed up with the form, can later login using OAuth, irrespective of the above two settings.
2. Any new user who has been *invited* by an existing user, can sign up using form or OAuth, irrespective of the above two settings.
1. Signup from form with a new appsmith.com address.
2. Signup from form with a new gmail.com address.
3. Signup from form with an invited appsmith.com address.
4. Signup …

Consistent handling of signup configuration over FORM and OAUTH

---

app/client/src/sagas/WidgetOperationSagas.tsx

When a form widget tries to reset the children's meta properties. Some container like widgets within it might not be available
This results in the `widget` being `undefined`
Fixes #2829
Difficult to reproduce. Fixed by handling the erroneous path in the code.

Fix #2829 When resetting form meta properties widget is undefined

---

app/client/src/components/formControls/utils.ts
app/client/src/sagas/ActionSagas.ts

There was a bug introduced in #2976
Editor config doesn't exist in all plugins, undefined broke `getConfigInitialValues`. Added null check there.

Null check in getConfigInitialValues

---

app/client/src/actions/actionActions.ts
app/client/src/api/PageApi.tsx
app/client/src/reducers/entityReducers/actionsReducer.tsx
app/client/src/sagas/PageSagas.tsx

https://user-images.githubusercontent.com/12022471/107935064-e6101500-6fa6-11eb-88db-47b8a95f8d70.mov
Fixes #3041

Show a toast when action executeOnLoad status updates

---

app/client/src/pages/Editor/QueryEditor/Form.tsx
app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java

Also improving the mongo error response string. Now we only send the error message instead of the entire stack trace back.
Fixes #2732 
Fixes #3046
- Manual
- Junit

Correcting the display message for query actions based on isExecutionSuccess flag

---

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/PolicyUtils.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionServiceTest.java

Datasource is given permission for a public app during create/update of a public action

---

app/client/src/components/propertyControls/ActionSelectorControl.tsx
app/client/src/components/propertyControls/BaseControl.tsx
app/client/src/constants/PropertyControlConstants.tsx
app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx
app/client/src/utils/PropertyControlFactory.tsx
app/client/src/utils/migrations/TableWidget.ts
app/client/src/widgets/TableWidget/TablePropertyPaneConfig.ts
app/client/src/widgets/TableWidget/index.tsx

- Fix migration of dynamicTriggerPathList
- currentRow binding in table column action calls the action on all rows
Manually

Internal Fix:  Column actions in Table Widget is called for all rows

---

app/client/src/pages/Editor/PropertyPane/index.tsx

Fix issue where the panel isn't scrolled to top when opening it
Manually

Internal Fix: Property panel doesn't scroll to top when opened

---

app/client/src/utils/migrations/TableWidget.ts

When tables are migrated, the computedValue for the columns do not have the  term `currentRow`
Manually

Internal Fix: Missing `currentRow` in computedValue field

---

app/client/src/components/formControls/SwitchControl.tsx

Handle false strings as falsy for the switch widget 
We need to handle this case since we have some limitations with the data type

Handle false (type: string) as falsy for the switch control (internal forms)

---

app/client/src/sagas/EvaluationsSaga.ts
app/client/src/utils/DynamicBindingUtils.ts
app/client/src/workers/evaluation.worker.ts

Evaluation errors are failed silently today and only shown in the browser console. This PR will add a toast if any evaluation error occurs when executing a trigger since those are more timely errors and harder to debug.
https://user-images.githubusercontent.com/12022471/108458982-c9702780-729b-11eb-9154-fdbeac140b92.mov
Fixes #1956

Add toast for trigger errors

---

app/client/src/components/ads/EditableText.tsx
app/client/src/pages/AppViewer/viewer/AppViewerHeader.tsx
app/client/src/pages/Editor/EditableAppName.tsx
app/client/src/pages/Editor/EditorHeader.tsx

Increase allowed width for app title for both viewer and editor
- manually

Fix app title widths for both viewer and editor

---

app/client/src/components/designSystems/appsmith/TableComponent/index.tsx
app/client/src/widgets/TableWidget/index.tsx

Allow Appsmith users to clear selection in a widget table without multi-select option enabled.
Fixes #2342 
- Manually
- [o] My code follows the style guidelines of this project
- [o] I have performed a self-review of my own code
- [o] My changes generate no new warnings
- [o] New and existing unit tests pass locally with my changes

Fix #2342 Un-select row

---

app/client/src/pages/Editor/APIEditor/Form.tsx
app/client/src/pages/Editor/QueryEditor/Form.tsx
app/client/src/pages/Editor/QueryEditor/index.tsx
app/client/src/reducers/entityReducers/pluginsReducer.ts
app/client/src/sagas/ActionSagas.ts
app/client/src/sagas/QueryPaneSagas.ts
app/client/src/selectors/entitiesSelector.ts
app/server/appsmith-plugins/postgresPlugin/src/main/resources/editor.json
app/server/appsmith-plugins/postgresPlugin/src/main/resources/setting.json
app/server/appsmith-server/src/main/java/com/appsmith/server/services/PluginServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/PluginServiceTest.java

Adds support for `setting.json` in plugins.
Todo: 
Fixes #3157
Manually.

Add support for setting.json

---

app/client/src/pages/Editor/EditorHeader.tsx

Fix popover position for editor header popovers
[Ref](https://github.com/popperjs/popper-core/issues/248): `preventOverflow` by default will keep the popper between its scroll parent boundaries
- manually

Fix popover position for editor header popovers

---

app/client/src/workers/DataTreeEvaluator.ts

Sort order fix if property path gets updated via multiple start nodes
Fixes #3172 

Sort order fix if property path gets updated via multiple start nodes

---

app/client/src/pages/Editor/Explorer/Widgets/WidgetEntity.tsx

Fix navigation to modal widget's children from the entity explorer by passing `parentModalId` to non-immediate descendents as well.
- manually

Fix navigation to modal widget's children from the entity explorer

---

app/client/src/utils/autocomplete/EntityDefinitions.ts
app/client/src/widgets/DropdownWidget.tsx

Allow access to selectedOptionLabel property in dropdown widget
Fixes #3115 

Added selectedOptionLabel property in dropdown widget

---

app/server/appsmith-plugins/dynamoPlugin/src/main/java/com/external/plugins/DynamoPlugin.java
app/server/appsmith-plugins/dynamoPlugin/src/main/resources/form.json
app/server/appsmith-plugins/dynamoPlugin/src/test/java/com/external/plugins/DynamoPluginTest.java

- creating connection with false creds does not throw error. Hence, using listTables() method to check connection validity.
- add TC to test this feature.
- add encrypted logo to password field
- rectify the default value of region dropdown
Fixes #2813 
- manual

check dynamodb connection validity using listTables cmd.

---

app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/FirestorePlugin.java
app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java

- Stop logging datasource argument error externally. The error described in the linked GitHub issue arises due to bad service account credentials provided as arg.
- Update error msg to make it clear.
- Add TC.
Fixes #3138 
- verified that that the source of error indeed is the bad argument. 
- new message:

stop logging datasource argument error externally.

---

app/client/src/actions/controlActions.tsx
app/client/src/components/editorComponents/EditorContextProvider.tsx
app/client/src/constants/WidgetConstants.tsx
app/client/src/pages/Editor/PropertyPane/PropertyControl.tsx
app/client/src/sagas/OnboardingSagas.ts
app/client/src/sagas/WidgetOperationSagas.tsx
app/client/src/widgets/BaseWidget.tsx
app/client/src/widgets/TableWidget/index.tsx

Add feature to simultaneously modify and remove property paths in a widget
Manually

Add feature to simultaneously modify and remove property paths in a widget

---

app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/ApiFlow/CurlImportFlow_spec.js
app/client/src/pages/Editor/APIEditor/CurlImportForm.tsx

Move to hint statement out of query box and put if above it - between the label and the query box - so that user's don't confuse it as a typed in statement.
Fixes #2584 
- manual

Modify hint statement for 'import from curl' form

---

app/client/src/utils/autocomplete/EntityDefinitions.ts

After a Map Widget created, the text field in the Text Widget can bind the map properties. Inside the map properties, "Map center" and "Center" are duplicate value. The "MapCenter" is deleted for the adjustment.
Fixes #2712  
Manual Testing
- [o] My code follows the style guidelines of this project
- [o ] I have performed a self-review of my own code
- [o] My changes generate no new warnings
- [o] New and existing unit tests pass locally with my changes

Fix #2712 - Duplicate Property For Map Widget

---

app/client/src/components/designSystems/appsmith/help/HelpModal.tsx

Fix help modal overlapping with close button
Fixes #3286
- manually

Fix help modal overlapping with close button

---

app/server/appsmith-plugins/dynamoPlugin/src/main/resources/form.json

- provide a max length to keyvalue_array type. If the max length is set to 1, then the "+" button will not appear.
- front end changes are pending. A new github issue will be opened to track the same : https://github.com/appsmithorg/appsmith/issues/3315 
Fixes #2854 
- can only be tested once the front end changes are added.

Provide option for only one endpoint and port in the dynamodb plugin datasource form 

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ActionExecution/ExecutionParams_spec.js
app/client/cypress/support/commands.js

Fixes https://github.com/appsmithorg/appsmith/issues/2804
Also, makes writing tests on this particular suite much quicker.
- Breaking change (fix or feature that would cause existing functionality to not work as expected)?
Running the test suite multiple times. Notice a speed increase from 20-30 seconds down to 5 per run for the Table display tests.

Updates json input from typing to value setting

---

app/client/src/components/editorComponents/DropTargetComponent.tsx
app/client/src/mockResponses/WidgetConfigResponse.tsx
app/client/src/selectors/editorSelectors.tsx
app/client/src/utils/WidgetPropsUtils.tsx

Added new flag to set for overlay widgets that can be dropped anywhere but will be rendered on the maincontainer.
Fixes #3304 
- Test A
- Test B

Fix: Drop overlay widgets anywhere and add them as main container child

---

app/client/src/components/propertyControls/StyledControls.tsx

Fix table delete column icon alignment in property pane theme changes

Fix delete icon alignment in table widget columns control

---

app/client/src/sagas/WidgetOperationSagas.tsx

Deleting from the explorer doesn't update the widgets `tab` property. So doing the same as a special case for tabs in a tab widget in the delete widget saga.
Fixes #2885 
Manually

Fix issue while deleting a tab from explorer 

---

app/client/src/widgets/RichTextEditorWidget.tsx

Added defaultText property for text type validations
Fixes #3384 

Added defaultText property for text type validations

---

app/client/src/sagas/WidgetOperationSagas.tsx

Fixes the wrong property pane updates that happens where a dynamicBindingPathList does not get removed from the widget
Reverts the bad fix for tab deletion

Fix widget updates not working properly

---

app/client/src/sagas/ActionExecutionSagas.ts
app/client/src/widgets/TableWidget/index.tsx

Table Widget has an onPageSizeChange trigger which was getting executed even when no trigger was defined in it. This was causing `UNESCAPE_STRING_ERROR` down the line in the evaluation workflow. We should invoke trigger properties actions unless it has something defined in the field.
This PR checks adds the check around onPageSizeChange trigger before trying to execute it and also adds better handling of the error before it goes through the evaluation workflow

Fix for Table onPageSizeChange trigger executing when not defined

---

app/client/src/actions/controlActions.tsx
app/client/src/reducers/entityReducers/canvasWidgetsReducer.tsx
app/client/src/sagas/OnboardingSagas.ts
app/client/src/sagas/WidgetOperationSagas.tsx
app/client/src/widgets/BaseWidget.tsx

With the BATCH_UPDATE_WIDGET_PROPERTY action UPDATE_WIDGET_PROPERTY is no longer required.
Fixes #3288
Fixes #3246
If this change works, all the existing tests should pass.

Deprecate UPDATE_WIDGET_PROPERTY action

---

app/client/src/components/designSystems/blueprint/ModalComponent.tsx
app/client/src/widgets/ModalWidget.tsx

Modal Resizing based on canvas size.
Fixes # #3416 

Fix: Modal Size gets cut in smaller screens.

---

app/server/appsmith-plugins/amazons3Plugin/src/main/resources/editor.json
app/server/appsmith-plugins/elasticSearchPlugin/src/main/resources/editor.json
app/server/appsmith-plugins/firestorePlugin/src/main/resources/editor.json

- Use dynamic input text for plugin editor forms so that the evaluated value of mustache expression is visible.
- Those fields which are meant to store Key only - i.e. they are not visible to the user and are only meant to provide key for key value pair in db have been skipped. 
- manual

use dynamic input text in plugin editor forms

---

app/client/src/constants/FieldExpectedValue.ts
app/client/src/workers/validations.ts

Allow null as acceptable value for date field
Fixes #3391 

Allow null as acceptable value for date field

---

app/client/src/widgets/TableWidget/index.tsx
app/client/src/workers/validations.ts

When there is a cyclic dependency, the table data is processed as a string, leading to incorrect column computations and a render loop. Fixed this by bailing out when table data is a string, as further computations are moot
Fixes #3440 
Fixes #3291 
Cypress test pending.

Table primary columns in cyclic dependencies

---

app/client/src/components/editorComponents/GlobalSearch/utils.tsx

`replace` has more support than `replaceAll`, including android browser 81, which does not support `replace`
Fixes #3529
- manually

Use replace instead of replaceAll for wider support

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java

The NPE noticed is with the return value of `.getStatusCode`.
But this PR adds NPE guards to a few other potential cases.

Fix NPE in action execution analytics

---

app/client/src/components/propertyControls/PrimaryColumnsControl.tsx

Handle scenario where columnOrder was unavailable in Table widget
Fixes #3298 

Handle scenario where columnOrder was unavailable in Table widget

---

app/client/src/workers/validations.ts

Fix dropdown option validation to allow null or empty string as value
Fixes #3330 
- Test A
- Test B

Fix dropdown option validation to allow null or empty string as value

---

app/client/src/actions/controlActions.tsx
app/client/src/actions/pageActions.tsx
app/client/src/api/PageApi.tsx
app/client/src/entities/Widget/utils.ts
app/client/src/pages/Editor/Explorer/Pages/PageGroup.tsx
app/client/src/reducers/entityReducers/canvasWidgetsReducer.tsx
app/client/src/sagas/WidgetOperationSagas.tsx
app/client/src/utils/WidgetPropsUtils.tsx
app/client/src/utils/hooks/useDynamicAppLayout.tsx

Calculate and set the initial height of pages dynamically.
Fixes #2962 
- Test A
- Test B

Fix: Dynamic Canvas Height based on bottom most widget.

---

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ConfigServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ApplicationForkingService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ExamplesOrganizationCloner.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserServiceTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserServiceWithDisabledSignupTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ExamplesOrganizationClonerTests.java

This PR:
1. Adds a migration to remove the configuration of template organization. So, after this, self-hosted instances won't have example applications being cloned for new users who sign up.
2. Add a few null checks around getting template organizations since it's now very possible to be `null` (and does indeed throw a few NPEs around).
3. Update tests accordingly.

Add migration to remove template organization config

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Onboarding/Onboarding_spec.js

We recently changed the test to make sure we wait for the client to create an onboarding data source if it did not exist. This kind of check was also happening on the source code, and the complexity was not getting translated properly in the tests. 
To improve the reliability of the test, I added an arbitrary wait time before we start the building

Add arbitrary wait on onboarding test

---

app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OrganisationTests/CreateOrgTests_spec.js
app/client/cypress/support/commands.js
app/client/src/constants/messages.ts
app/client/src/pages/organization/OrgInviteUsersForm.tsx

The invite text says: "Users have been invited." when I invited only one user. It should say, 'The user has been invited successfully' for one email and 'Users have been invited' for multiple emails.
Fixes #3542 
- Test 1: invited a single user, used cypress to check if the error message is correct.

Fix success message for single user invite and multiple user invite

---

app/server/appsmith-plugins/amazons3Plugin/src/main/resources/editor.json

- modify default value for s3 on file create to Yes.
- change dropdown option names to base64, text from yes, no.

change default value of s3 file data type on create file action

---

app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/LayoutActionServiceImpl.java

This is to ensure that the client can parse it correctly

Stringifying the binding name before setting in the error string

---

app/client/src/widgets/TableWidget/derived.js
app/client/src/widgets/TableWidget/derived.test.js
app/client/src/widgets/TableWidget/index.tsx

- Fix: Some comparison functions were not working correctly for non-string data
- Fix: Column properties were not updating based on the filter, sort and search values
Fixes #3381
- Updated unit tests
- Cypress test pending

Fix #3381: Table column properties now map correctly when filtering, sorting or searching

---

app/client/src/workers/DataTreeEvaluator.ts

Default value overrides happen by tracking value changes of their paths. Post our subtree optimisations, this can be improved by always updating the version of the default value property if it gets evaluated. That way, we make sure that the values are overridden any time the default property value changes
Fixes #3443

fix default override same value

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Onboarding/Onboarding_spec.js

Fix onboarding test spec: check res instead of req to validate
- Test spec

Fix onboarding test spec: check res instead of req to validate

---

app/client/src/components/editorComponents/LightningMenu/helpers.tsx

toUpperCase() on undefined was failing. Using lodash instead of native string functions.
Fixes #3672 #3673 
- Bug fix

Fix: TypeError: e.widgetName is undefined and TypeError: Cannot read property 'toUpperCase' of undefined

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/DatePicker_2_spec.js
app/client/src/workers/validations.test.ts
app/client/src/workers/validations.ts

Tries to auto parse the given date string in the `defaultDate` input of the date picker widget. This tries to retain the timezone of the user.
Fixes #3752 
- Unit tests added for validation

Fix #3752 Datepicker defaultDate auto parse

---

app/server/appsmith-plugins/firestorePlugin/pom.xml
app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/FirestorePlugin.java
app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/Method.java
app/server/appsmith-plugins/firestorePlugin/src/main/resources/editor.json
app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java

- Allow users to define key path for FieldValue.delete() and FieldValue.serverTimestamp() values. 
- delete() value is only valid for update operation, as Firestore does not seem to support it for any other ops.
- serverTimestamp() is valid for all operations excluding get and delete operations.
- `FieldValue.delete()` value cannot be used to delete array elements. To delete array elements `FieldValue.arrayRemove()` needs to be used. https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/FieldValue#arrayRemove(java.lang.Object...)
- `FieldValue.serverTimestamp()` value cannot be used inside array. It throws the following exception: 
`Caused by: com.google.cloud.firestore.FirestoreException: FieldValue.serverTimestamp() is not supported inside of an array.`
- …

Firestore plugin support for FieldValue.delete() and FieldValue.serverTimestamp() values

---

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/AuthenticationService.java

Really weird error to receive. I'm concerned about why this would ever arise. This PR fixes the NPE to make it prettier, but we should ideally never hit this state.
Tested this by hitting the server manually on that endpoint. This could be possible when there is no state provided at all, and a variation when state is not the same as the one we shared. I am guessing the authorization server is at fault, or someone was trying to hit our endpoint manually. :D
Fixes #3803 
The way to handle this is to still show a JSON error on the web page. All we have done with this change is to change the error type so that it does not get flagged by Sentry. Sample response:
```
{"responseMeta":{"status":403,"success":false,"error":{"code":4025,"message":"Unauthorized access"}}}
```

Null handling for bad state in OAuth2 callback

---

app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/DatasourceRepository.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ConfigService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ConfigServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ExamplesOrganizationCloner.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ExamplesOrganizationClonerTests.java

This PR enables setting an explicit list of datasources from the template organization, that will be cloned for any new user that signs up.
Today, only those datasources are cloned that are used by any of the example apps that are being cloned. If a datasource in the template org is not used by any example apps, it will *not* be cloned.
This PR provides a way to set a list of datasources, that will be cloned, even if there's no example app that uses this datasource.
To configure that list of datasources, the following MongoDB command can be used:
```javascript
db.config.updateOne({name: "template-organization"}, {$set: {"config.datasourceIds": ["datasourceId1", "datasourceId2"]}})
```
Note that this assumes, the organization ID is already set. If not, that can be done with the following: …

Clone explicitly set datasource for new users

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceServiceTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutActionServiceTest.java

Modify hint message
from: 
`
You may not be able to access your localhost if Appsmith is running inside a docker container or on the cloud. Please check out Appsmith's documentation to understand more.
`
to:
`
You may not be able to access your localhost if Appsmith is running inside a docker container or on the cloud. To enable access to your localhost you may use ngrok to expose your local endpoint to the internet. Please check out Appsmith's documentation to understand more.
`
Fixes #3725 

modify hint message to include a fix

---

app/client/src/widgets/TableWidget/derived.js
app/client/src/widgets/TableWidget/derived.test.js
app/client/src/widgets/TableWidget/index.tsx

Fix issue where table widget's dropzone (the box that appears when we drag a widget) was of width zero.
Fixes #3720 
Manually

Fix Table width on drag

---

app/client/src/sagas/ApiPaneSagas.ts
app/client/src/sagas/PluginSagas.ts

API plugin forms were not getting fetched if it did not have a saved datasource. This change guarantees that it will always be fetched during the initialisation
Fixes #3823

Always guarantee to fetch Api plugin forms

---

app/client/src/components/designSystems/appsmith/TableComponent/TableUtilities.tsx

Fix renderer error by using columnName to render instead of column.render function
Fixes #3645 
- Test A
- Test B

Use columnName to render table header column

---

app/client/src/components/formControls/BaseControl.tsx
app/client/src/components/formControls/utils.test.ts
app/client/src/components/formControls/utils.ts

Added capability for hidden field to support  for an array that ANDs(OR) all clauses so that the more complicated forms can be rendered with checks for multiple conditions. 
Fixes #3687 

Array support hidden field

---

app/client/cypress/fixtures/tableNewDsl.json

This DSL required update because server parses through all the Table widget jsons and expects the primary columns to be of the type Map. Earlier the table json was being dumped without being parsed and hence this is a new issue.

[Cypress Test Fix] Updated the DSL to change table's primary columns from an array to a map structure in the DSL

---

.github/workflows/client-test.yml

Add REACT_APP_GOOGLE_ANALYTICS_ID as a build time env var.
To be used here, within `index.html`:
``` 
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=%REACT_APP_GOOGLE_ANALYTICS_ID%"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
```
~~Also, @mohanarpit  just to confirm: we're using it in the above format, not as `process.env.REACT_APP_GOOGLE_ANALYTICS_ID`~~

Add REACT_APP_GOOGLE_ANALYTICS_ID as a build time env var

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/LayoutActionServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/LayoutServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionServiceTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutActionServiceTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/PageServiceTest.java

On updating actions, any layout updates required use the escaped primary columns to do so. This breaks the expectation of dynamic bindings. This fix unescapes the layout before update.
In draft state because I need to add test cases for this.

Fixed escaped layout being used for update

---

deploy/install.sh

As mentioned in below issue,
On curl version 7.29.0, --data-raw option is unknown.
So I changed --data-raw option to --data option in install.sh 
https://github.com/appsmithorg/appsmith/issues/3972
- on Mac + curl version 7.64.1 : this change was tested
- on Linux + curl  version 7.29.0 : this change was tested

Fixed --data-raw is unknown  (change to --data option)

---

app/server/appsmith-plugins/redshiftPlugin/pom.xml

Maven 3.8 now blocks HTTP repositories and only allows HTTPS. However, the version redshift jdbc dependency we are using connects to a separate repository that runs on HTTP. The latest version has switched to using HTTPS instead.
So this PR upgrades redshift dependency from version 2.0.0.1 to 2.0.0.4.
Ref: <https://maven.apache.org/docs/3.8.1/release-notes.html#cve-2021-26291>.

Fix build failure on Maven 3.8

---

app/client/src/components/formControls/DynamicTextFieldControl.tsx

Placeholder support wasn't there for QUERY_DYNAMIC_TEXT.
Fixes #3996 

placeholder support

---

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/annotations/documenttype/DocumentTypeMapper.java

Fixes #4003 
Unable to repro the issue itself, but this mapper is a bottleneck that has failed multiple times in the past for other errors as well. Fixed this by replicating default type mapper's logic.

Safe handling of alias

---

app/client/src/actions/datasourceActions.ts
app/client/src/sagas/DatasourcesSagas.ts

For Datasources created by API pane "Save as Datasource" button, we would want to redirect the user back to the API pane after saving the datasource. But if the datasource has an OAuth flow, it might need an authorisation redirection first. These two redirections would race today since the logic was not clear about redirection. 
This change is a hotfix to avoid the race and only redirect to one place depending on the flow

Hot fix redirection race in oAuth autorisation flow

---

app/client/src/index.css
app/client/src/pages/Editor/APIEditor/PostBodyData.tsx

The Evaluated values popover hinders the API Editor when in "Raw" and "JSON" mode so resized for just these 2 modes. 
Fixes #3254 

size change for raw and editor in API editor

---

app/client/src/pages/Editor/PropertyPaneTitle.tsx
app/client/src/sagas/ApiPaneSagas.ts
app/client/src/sagas/QueryPaneSagas.ts

In error scenario when action object is missing it can't have name, so sending empty name 
Fixes #3877 
Fixes #3898  

name can't be read from empty object

---

app/client/src/sagas/WidgetOperationUtils.ts

Fixes the test failing in cypress Entity_Explorer_Widgets_Copy_Paste_Delete_Undo_Keyboard_Event_spec.js for listwidget
Fixes #1427 
- Bug fix

Fix: Paste functionality fails when there is no parent available. 

---

app/client/src/components/formControls/DynamicTextFieldControl.tsx

evaluated value is overlapping on Query pane hence covering the data
Fixes #4158 

Query pane size adjusted as API pane field

---

app/client/cypress/fixtures/ChartTextDsl.json

The cypress test for chart and text binding was failing due to recent change. Updated the DSL to fix the test.
// Code coverage diff between base branch:release and head branch: fix/chart-widget-binding-test 
:green_circle: | total | 49.08 **(0.01)** | 29.8 **(0.04)** | 27.28 **(0.03)** | 49.47 **(0.02)**
:green_circle: | app/client/src/pages/Applications/ForkApplicationModal.tsx | 94.64 **(7.14)** | 96 **(20)** | 70 **(20)** | 94.44 **(7.4)**</details>

Fix: cypress test failing for chart-text binding

---

app/client/src/workers/evaluation.worker.ts
app/client/src/workers/evaluationUtils.ts

When there is a cyclical dependency, we don't evaluate any fields including widget derived values. While the user bindings were getting set to their parsed values, derived values were getting passed as is (the unevaluated value). This PR will now set this as undefined so widgets can better handle cyclical dependency states of their widgets
Fixes #3512
// Code coverage diff between base branch:release and head branch: fix/derived-values-evaluation 
:red_circle: | total | 48.64 **(-0.04)** | 30.7 **(0)** | 26.69 **(-0.03)** | 48.87 **(-0.03)**
:red_circle: | app/client/src/workers/evaluationUtils.ts | 88.79 …

Set derived values to undefined on cyclic dependency

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Dropdown_spec.js
app/client/src/workers/validations.ts

Trim Dropdown default value for special characters so that dropdown selection works
Fixes #3111 
- Cypress test to validate default dropdown selection works when default value contains special characters
// Code coverage diff between base branch:release and head branch: fix/dropdown-default-value 
:red_circle: | total | 49.04 **(0)** | 29.73 **(-0.01)** | 27.23 **(0)** | 49.43 **(0)**
:red_circle: | app/client/src/workers/validations.ts | 34.87 **(-0.1)** | 29.52 **(-0.44)** | 38.64 **(0)** | 35.33 **(-0.11)**</details>

Fix-Dropdown default value not trimming special characters

---

app/client/src/components/editorComponents/CodeEditor/styledComponents.ts
app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx

Invalid data sources were not showing up in API pane
Fixes #3238
// Code coverage diff between base branch:release and head branch: fix/show-invalid-datasources-in-red 
:green_circle: | total | 48.69 **(0.01)** | 29.73 **(0)** | 27.24 **(0.01)** | 49.14 **(0)**
:green_circle: | app/client/src/components/editorComponents/CodeEditor/styledComponents.ts | 92.54 **(0.12)** | 56.7 **(0)** | 100 **(0)** | 95.38 **(0.07)**</details>

show invalid datasource but in different color

---

app/client/src/pages/Editor/QueryEditor/JSONViewer.tsx

Fix to wrap long texts/urls in json viewer
Fixes #4007 

CSS fix to wrap long urls/text in json viewer

---

app/client/src/widgets/TableWidget/index.tsx

Fix cyclic dependency making the table widget crash the app. 
- Check if sanitizedTableData is array
Fixes #4209

Fix cyclic dependency making the table widget crash the app. #4209

---

app/client/src/workers/validations.test.ts
app/client/src/workers/validations.ts

Evaluations break when one of the evaluations fail
- Unit tests
// Code coverage diff between base branch:release and head branch: fix/defaultoption-validation 
:green_circle: | total | 50.09 **(0.03)** | 30.64 **(0.05)** | 28.99 **(0.02)** | 50.51 **(0.04)**
:green_circle: | app/client/src/workers/validations.ts | 37.26 **(2.19)** | 32.51 **(2.47)** | 42.22 **(2.22)** | 37.91 **(2.39)**</details>

Fix DEFAULT_OPTION_VALUE validations which were breaking evaluations

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/DatePicker_2_spec.js
app/client/src/components/designSystems/blueprint/DatePickerComponent2.tsx

Fix date string parsing for date from input field
Fixes #3957 
- Added cypress test case to validate issue fix
// Code coverage diff between base branch:release and head branch: fix/date-input-edit 
:red_circle: | total | 49.04 **(0)** | 29.73 **(-0.01)** | 27.23 **(0)** | 49.43 **(0)**
:red_circle: | app/client/src/components/designSystems/blueprint/DatePickerComponent2.tsx | 28.99 **(-0.42)** | 3.39 **(-0.12)** | 5.88 **(0)** | 28.36 **(-0.43)**</details>

Fix date string parsing for date from input field

---

app/client/src/workers/evaluationUtils.ts

In case the chart series data id starts with a number, it was incorrectly identified as a number instead of a string which led to incorrect path computed to check in binding paths
// Code coverage diff between base branch:release and head branch: bug/chart-data-eval-error 
:green_circle: | total | 48.93 **(0)** | 28.75 **(0.01)** | 26.77 **(0)** | 49.31 **(0)**
:green_circle: | app/client/src/workers/evaluationUtils.ts | 88.7 **(-0.09)** | 77.45 **(0.22)** | 90.48 **(0)** | 88.44 **(-0.06)**</details>

[Bug Fix] : Chart Series not getting evaluated if the chart series id starts with a number

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutActionServiceTest.java

1. Datasource policy generation moved to a function for easy re-use
2. Added a test for refactor widget name because none existed so far.

Small housekeeping server side changes

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Text_spec.js
app/client/src/workers/DataTreeEvaluator.ts
app/server/appsmith-plugins/rapidApiPlugin/pom.xml

This fix does the following :
1. Reverts the patch fix made to production to get the users unblocked ASAP.
2. Removes the cyclical dependencies being added during create action and update action
// Code coverage diff between base branch:release and head branch: bug/no-cyclical-dependency-direct 
:green_circle: | total | 48.94 **(0.01)** | 28.75 **(0)** | 26.78 **(0)** | 49.32 **(0.01)**
:red_circle: | app/client/src/workers/DataTreeEvaluator.ts | 88.68 **(0.12)** | 78.38 **(-0.31)** | 87.32 **(0)** | 88.86 **(0.1)**</details>

[Bug Fix] : Removal of cyclical dependencies due to action relationships being added to dependency map

---

app/client/src/constants/AppsmithActionConstants/ActionConstants.tsx
app/client/src/sagas/ApiPaneSagas.ts

Fix to correctly parse query params when there are dynamic bindings in the api url
Fixes #1957 
// Code coverage diff between base branch:release and head branch: fix/ternary_ops_api_pane 
:red_circle: | total | 48.69 **(0)** | 29.6 **(-0.02)** | 27.23 **(0)** | 49.14 **(0)**
:red_circle: | app/client/src/sagas/ApiPaneSagas.ts | 13.84 **(-0.12)** | 1.74 **(-0.09)** | 7.14 **(0)** | 15.46 **(-0.17)**</details>

Correctly parse query params when there are dynamic bindings in the api url

---

app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx

Null check to prevent Typeerror against missing datasource URLs in API actions
Fixes #4329 
// Code coverage diff between base branch:release and head branch: fix/type_error_datasource_url 
:red_circle: | total | 48.94 **(0)** | 28.72 **(-0.02)** | 26.78 **(0)** | 49.32 **(0)**
:red_circle: | app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx | 25 **(0)** | 2.94 **(-0.29)** | 4.35 **(0)** | 26.73 **(0)**</details>

Added null check against datasource url

---

app/server/appsmith-server/src/main/resources/application.properties

Removed cloud services url from application properties. This can now only be set via an environment variable. Cypress will thus not use cloud services.

Removed prod url from default config

---

app/client/src/widgets/DatePickerWidget2.tsx

-  While using date picker in YYYY:MM:DD HH:MM:SS format, the input field resets to 11:00 when the user chooses 23:00
-  Here optionWidth increase because of a design issue
Fixes #4278 
- UI Performance improvements (non-breaking change which fixes an issue)

change data-time format 'YYYY-MM-DD hh:mm:ss A' to 'YYYY-MM-DD hh:mm:ss'

---

app/client/src/components/ads/Tabs.tsx

Remove user-select: none from the tabs component
Fixes #4335 
Text can be selected from the tabs

Fix: Make contents of tab selectable

---

app/client/src/widgets/ListWidget/ListWidget.tsx

Numbers in the text widget in list widget were failing because we were directly passing to text widget component. So using toString before passing the numbers too.
Fixes #4402 
- Bugfix

Fix: TypeError: t.match is not a function

---

app/server/appsmith-plugins/rapidApiPlugin/pom.xml

Because of the Java version not being explicitly set
in this plugin, the build of the whole project fails
sporadically in IntelliJ since it's trying to compile the
code as Java 8, which will obviously fail.

Use explicit Java version in RapidApi plugin pom.xml

---

app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/CommentController.java
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Comment.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomCommentRepository.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomCommentRepositoryImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/CommentService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/CommentServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/CommentServiceTest.java

Introduces two API endpoints:
- `POST /comments/{commentId}/reactions` with body looking like `{"emoji": "a"}` to add a reaction on a comment, given by the ID.
- `DELETE /comments/{commentId}/reactions` with body looking like `{"emoji": "a"}` to remove a reaction on a comment, given by the ID.

APIs for adding and removing reactions on comments

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ExplorerTests/Entity_Explorer_Query_Datasource_spec.js
app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/ExplorerTests/Entity_Explorer_API_Pane_spec.js
app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/ExplorerTests/Entity_Explorer_CopyQuery_RenameDatasource_spec.js
app/client/src/entities/DataTree/dataTreeAction.ts
app/client/src/entities/DataTree/dataTreeFactory.ts
app/client/src/reducers/entityReducers/actionsReducer.tsx
app/client/src/utils/autocomplete/EntityDefinitions.ts
app/client/src/workers/evaluation.test.ts
app/client/src/workers/evaluationUtils.test.ts

Expose response headers/meta in API/DB actions
Fixes #3643 
// Code coverage diff between base branch:release and head branch: feature/bind_response_meta_to_actions 
:red_circle: | total | 48.93 **(-0.01)** | 28.61 **(-0.04)** | 26.78 **(0)** | 49.29 **(-0.01)**
:red_circle: | app/client/src/utils/autocomplete/EntityDefinitions.ts | 35 **(-11.67)** | 0 **(0)** | 25 **(0)** | 35 **(-11.67)**</details>

Expose response headers for API/DB actions

---

app/server/.run/ServerApplication.run.xml
app/server/appsmith-server/src/main/java/com/appsmith/server/constants/FieldName.java
app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/PageController.java
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/UserData.java
app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/CollectionUtils.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomUserDataRepository.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomUserDataRepositoryImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewPageServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserDataService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserDataServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserOrganizationServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ApplicationFetcher.java
app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/CollectionUtilsTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/repositories/CustomUserDataRepositoryImplTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserDataServiceTest.java

When user visits their home page, they can see the list of organization and list of applications under each organization. The list of organization are sorted alphabetically. This PR will change this behavior. The organizations will now be sorted based on usage - the last used one is shown at first. So if user has 3 organization A, B, C and she opens an app under the C, then organization list will be shown in order C, A, B in her home page. If she opens an app from A now, the order will change to A, C, B
Issue #2093
- Unit tests
- Integration tests

[Issue #2093]-show last used organizations first in home page

---

app/client/src/sagas/ApiPaneSagas.ts

r.match is not a function
Reason - when adding/updating API url which doesn't have datasource, 'value'(shown in sentry) is an Object but when updating/adding url which has datasource 'value' is a string. 
Fixes #4496
// Code coverage diff between base branch:release and head branch: fix/r-match-error-apipane 
:red_circle: | total | 48.93 **(0)** | 28.63 **(-0.01)** | 26.78 **(0)** | 49.3 **(0)**
:green_circle: | app/client/src/sagas/ApiPaneSagas.ts | 14.72 **(1)** | 1.67 **(-0.02)** | 7.14 **(0)** | 16.42 **(1.11)**</details>

r.match on API pane error

---

app/server/Dockerfile

- Change docker image java version to 11.0.10 to allow TLSv1 for mysql.
Fixes #4462 
- Via EC2 deployment

change java version to 11.0.10 to allow TLSv1 for mysql

---

app/client/cypress/fixtures/testdata.json
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ApiPaneTests/API_Edit_spec.js
app/client/cypress/locators/apiWidgetslocator.json
app/client/cypress/support/commands.js
app/client/src/sagas/ApiPaneSagas.ts

Fixed query params parsing when there are multiple "="s in the URL
Fixes #3585 
// Code coverage diff between base branch:release and head branch: fix/query_params_parsing_api_pane 
:red_circle: | total | 48.92 **(-0.01)** | 28.63 **(0)** | 26.78 **(0)** | 49.3 **(0)**
:red_circle: | app/client/src/sagas/ApiPaneSagas.ts | 13.66 **(-1.06)** | 1.67 **(0)** | 7.14 **(0)** | 15.23 **(-1.19)**</details>

Fixed query params parsing in API pane

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/DatePicker_2_spec.js
app/client/src/components/designSystems/blueprint/DatePickerComponent2.tsx
app/client/src/globalStyles/popover.ts

>  DatePicker calendar popover postion set bottom.
Fixes # (#4290) , (#4410)

fix: datepicker popover adjust height and width.

---

app/client/src/components/designSystems/blueprint/DropdownComponent.tsx

> In dropdown component option popover is scroll issue fixed. here we disabled `preventOverflow`.
Fixes # (#2356)

fix: select disabled option popover overflow

---

app/client/cypress/fixtures/tableWidgetDsl.json
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/Bind_tableApi_spec.js
app/client/cypress/locators/Widgets.json
app/client/src/components/designSystems/appsmith/SearchComponent.tsx
app/client/src/widgets/TableWidget/derived.js

Disable client side search when server side search is enabled in table widget
Fixes #4039 
- Added cypress test case to validate onSearchTextChange function if configured in table widget

Disable client side search when server side search is enabled in table widget

---

app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/ApiPaneTests/API_CurlPOSTImport_spec.js
app/client/src/constants/ApiEditorConstants.ts
app/client/src/pages/Editor/APIEditor/PostBodyData.tsx
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/CurlImporterService.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java

This PR adds the functionality of `multipart/form-data` to Appsmith's API pane section. A user can now select the tab "Form-Data" in the data types under "Body". Appsmith will send a multipart form data request to the backend API.
Fixes #1586
For now, this has been tested manually. Will add Cypress tests as well. 
// Code coverage diff between base branch:release and head branch: feature/multipart-form 
:red_circle: | total | 48.92 **(-0.01)** | 28.63 **(0)** | 26.76 **(-0.01)** | 49.29 **(-0.01)**
:red_circle: | …

Adding support for multipart form data

---

app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datasources/MongoDataSourceStub_spec.js
app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/QueryPane/MongoDatasource_spec.js

Updated to test to run for Raw Input

Fix: Mongo datasource and query Cypress test

---

app/client/src/index.tsx
app/client/src/utils/hooks/useRemoveSignUpCompleteParam.ts

Remove `isFromSignup` param from the URL to prevent duplicate analytics hits 
- manually

Remove isFromSignup param to prevent duplicate hits

---

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/OAuth2.java

In case an authorization server returns with a non-standard response (without `expires_in` or `expires_at` fields), the check for expiration currently fails. This PR modifies that logic to assume all responses with missing expiration to have always expired. 
This change will mean that every new execution request for such an action will always attempt to perform authentication before hitting the desired endpoint.
Fixes #4643

Assume tokens without expiry have always expired

---

.github/workflows/client-test.yml
.github/workflows/external-client-test.yml

This change modifies CI workflow to echo the result of running integration tests. It still fails for the same kind of scenarios, but skipped tests can now be identified more easily.
CI will also now use release cloud services for its tests.

Added output for matrix run result in CI workflow

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DynamicInput/autocomplete_spec.js
app/client/src/components/editorComponents/CodeEditor/EditorConfig.ts
app/client/src/components/editorComponents/CodeEditor/hintHelpers.ts
app/client/src/components/editorComponents/CodeEditor/index.tsx
app/client/src/components/editorComponents/CodeEditor/styledComponents.ts
app/client/src/utils/autocomplete/TernServer.ts
app/client/src/utils/autocomplete/dataTreeTypeDefCreator.test.ts
app/client/src/utils/autocomplete/dataTreeTypeDefCreator.ts

Autocomplete needs to show the next list even when the user hasn't type a '.'
Fixes #1844 
// Code coverage diff between base branch:release and head branch: invisble-dot 
:green_circle: | total | 51.6 **(-0.01)** | 32.51 **(0.08)** | 29.83 **(0.01)** | 52.09 **(0)**
:green_circle: | app/client/src/components/editorComponents/CodeEditor/index.tsx | 73.68 **(0.14)** | 53.98 **(0.83)** | 56.67 **(0)** | 73.74 **(0.14)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 44.78 **(0.3)** | 30 **(3.26)** | 31.48 **(-1.17)** | 49.84 **(0.37)** …

show pre-filled values for autocomplete

---

app/client/src/entities/Datasource/RestAPIForm.ts
app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
app/client/src/transformers/RestAPIDatasourceFormTransformer.ts
app/server/appsmith-interfaces/src/main/java/com/appsmith/external/constants/Authentication.java
app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/OAuth2.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/OAuth2AuthorizationCode.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/OAuth2ClientCredentials.java
app/server/appsmith-plugins/restApiPlugin/src/main/resources/form.json
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/AuthenticationService.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ExamplesOrganizationClonerTests.java

Adds the `audience` and `resource` fields to the token request when client credentials are being shared via body. When shared as a basic token in the authorization header, these fields are not available.
This field is stored as a string, and hence always added to the request as is. This means that the if the provider expects any form of encoding for the field, this should be handled on the Appsmith client itself. Similarly, in case multiple audiences or resources are required, the string expects to have the proper stringified array representation.
Fixes #4666 
-Tested against mocklab endpoint …

Added optional audience and resource fields for oauth2 datasources

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Applications/DuplicateApplication_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Applications/ForkApplication_spec.js
app/client/src/constants/WidgetConstants.tsx
app/client/src/mockResponses/WidgetConfigResponse.tsx
app/client/src/utils/WidgetPropsUtils.test.tsx
app/client/src/utils/WidgetPropsUtils.tsx
app/client/src/widgets/Tabs/TabsWidget.tsx

Tabs widget implementation had not included some position widget properties coz it already had rows required to render but new grid migration needs them, so I have added migration for tabs widgets.
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: fix/tabs-bad-data 
Status | File | % Stmts | % Branch | % Funcs …

Fix: Adding missing widget properties when a new tab is created.

---

app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx

Evaluated value pop is re rendered on every keypress and few other things.
On every render it triggers expensive style calculation of about 10-15ms. This value doesn't change after the initial mount, so calculate it only once.
Fixes #4679
- UI Performance improvement 
Profiling before and after
// Code coverage diff between base branch:release and head branch: ui/perf/optimize-expensive-style-calc-evalauatedValuePopup/4679 
:green_circle: | total | 51.62 **(0.01)** | 32.45 **(0)** | 29.83 **(0.01)** | 52.09 **(0)**
:green_circle: | app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx | …

Memoize the evaluate popup placement value

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/aTobAndbToaBasictest_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/loadashBasictest_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/momentBasictest_spec.js

cy.reload was causing some issue in saving the default value for input2.
In the test cases, cy.reload was causing some issue in saving the default value for input2.
Removed the cy.reload() to prevent the issue in saving the default value of input2.
Deleted below line from each test case. 
cy.reload()
- [ ✓] My code follows the style guidelines of this project
- [ ✓] I have performed a self-review of my own code
- [ ✓] I have commented my code, particularly in hard-to-understand areas
- [ ✓] I have made corresponding changes to the documentation
- [ ✓] My changes generate no new warnings
- [ ✓] I have added tests that prove my fix is effective or that my feature works
- [ ✓] New and existing unit tests pass locally with my changes
<details><summary>:white_circle: Total …

Removed the reload

---

app/client/src/pages/Editor/APIEditor/DatasourceList.tsx

Prevent text overflow in datasource source tab in API editor

Datasource url overflow bug

---

app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/plugins/RedisPlugin.java
app/server/appsmith-plugins/redisPlugin/src/test/java/com/external/plugins/RedisPluginTest.java

- fix socket error
- fix default port
- remove invalid check for missing port, since default port would be supplied if user leaves the port field empty. 
Fixes #4560 
- manually

Fix: Fix redis plugin socket error 

---

app/client/src/components/propertyControls/PrimaryColumnsControl.tsx

Truncate long column names. Added css to fix this.
Fixes #4603 
> Tested Locally.

FIX #4603 : updated css to truncate long column name

---

app/client/src/components/propertyControls/DropDownControl.tsx
app/client/src/widgets/TableWidget/TablePropertyPaneConfig.ts

> set default format `YYYY-MM-DD HH:mm` in `Orignal Date Format` and `Display Date Format` in table widget cell type **Date**. 
add `No Selection` additional option in date format 
>  In DropDownControl add support for set defaultValue.
Fixes # (#3318)
- Breaking change (fix that would cause existing functionality to not work as expected)
// Code coverage diff between base branch:release and head branch: fix/dropdown-default-value 
:green_circle: | total | 51.43 **(0)** | 32.1 **(0.01)** | 30.01 **(-0.01)** | …

fix: set default format in table date type cell

---

app/client/src/entities/Datasource/RestAPIForm.ts
app/client/src/entities/Datasource/index.ts
app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
app/client/src/transformers/RestAPIDatasourceFormTransformer.ts
app/server/appsmith-interfaces/src/main/java/com/appsmith/external/constants/Authentication.java
app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ApiKeyAuth.java
app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/AuthenticationDTO.java
app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/BearerTokenAuth.java
app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/DatasourceConfiguration.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/APIConnectionFactory.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/ApiKeyAuthentication.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/BasicAuthentication.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/BearerTokenAuthentication.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
app/server/appsmith-plugins/restApiPlugin/src/main/resources/form.json
app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/connections/ApiKeyAuthenticationTest.java
app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/connections/BearerTokenAuthenticationTest.java
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Datasource.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/DatasourceTemplateRepository.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceServiceImpl.java

- add support for api key auth, bearer token auth
- combine default config with user config.
Fixes #4511 

Feature: datasource changes for api key auth, bearer token auth, combine config.

---

app/client/src/sagas/ModalSagas.ts

> remove `resetChildrenMetaProperty` Widget Action in `closeModalSaga` saga function.
Fixes # (#3543)
// Code coverage diff between base branch:release and head branch: bug/model-reset-children-meta-onclose 
:green_circle: | app/client/src/widgets/TableWidget/index.tsx | 9.49 **(0.03)** | 0 **(0)** | 10.64 **(0)** | 10.27 **(0.06)**</details>

updated closeModal saga to stop reseting children meta properties.

---

app/client/src/constants/PropertyControlConstants.tsx
app/client/src/entities/Widget/utils.test.ts
app/client/src/entities/Widget/utils.ts
app/client/src/widgets/ChartWidget/propertyConfig.ts
app/client/src/widgets/DropdownWidget.tsx
app/client/src/widgets/FilepickerWidget.tsx
app/client/src/widgets/ListWidget/ListPropertyPaneConfig.ts
app/client/src/widgets/MapWidget.tsx
app/client/src/widgets/RadioGroupWidget.tsx
app/client/src/widgets/TableWidget/TablePropertyPaneConfig.ts

Widget properties that require an object like structure were failing when a user had multiple bindings in that property. This was because we would templatise the final output which would make the final output a string with escaped characters.
This change will enable smart substitution evaluation we use in JSON inputs like API post body to correctly evaluate properties configured with multiple bindings or binding + string combinations
Fixes #4688
// Code coverage diff between base branch:release and head branch: fix/smart-substitution-widgets 
:green_circle: | total | 51.59 **(0.01)** | 32.62 **(0.03)** | 29.76 …

Enable smart substitution for widgets

---

app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx

Fixes the OAuth2 form for client credentials grant type to show the audience and resource field

Changes to client credentials form for audience field

---

app/client/src/workers/evaluate.test.ts
app/client/src/workers/evaluate.ts

Evaluating multi-line JS without semicolons was failing because we would remove line break characters from the script before evaluating. This was also causing the line comments to fail in multi-line code. By avoiding the removal of line breaks, these errors go away
Fixes #948 
Fixes #1998 

Fix multiline js issues

---

app/client/src/components/editorComponents/CodeEditor/styledComponents.ts
app/client/src/components/editorComponents/StoreAsDatasource.tsx
app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx
app/client/src/pages/Editor/APIEditor/DatasourceList.tsx
app/client/src/pages/Editor/APIEditor/Form.tsx

Change CTA to apply datasource on click instead of navigation to datasource form. Fixed alignment of request method button. New UI changes for datasource list
Fixes #4858 
// Code coverage diff between base branch:release and head branch: fix/change_datasource_card_cta 
:red_circle: | total | 51.59 **(-0.01)** | 32.66 **(0.01)** | 29.74 **(-0.02)** | 52.11 **(0)**
:red_circle: | app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx | 29.37 **(0)** | 2.67 **(-0.03)** | 4 **(0)** | 31.3 **(0)**
:red_circle: | …

Change cta to apply datasource on datasource card click

---

app/client/src/components/editorComponents/CodeEditor/styledComponents.ts

Fixes partially hidden information in the right side of the suggestion box
Fixes #4897 

Fix to show datasource auth info clearly

---

app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/plugins/RedisPlugin.java

- remove DB Auth type check, since the type is not getting set and the check does not seem to be required in any way. 
Fixes #4862 
- manual

Fix: Fix redis plugin db authentication

---

app/client/src/components/designSystems/appsmith/Dropdown.tsx
app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx

Fixed overlapping dropdown in mysql datasource form
Fixes #4890 
// Code coverage diff between base branch:release and head branch: bug/overlapping_dropdown_mysql_form 
:red_circle: | total | 51.58 **(0)** | 32.65 **(0)** | 29.74 **(-0.01)** | 52.1 **(0)**
:red_circle: | app/client/src/components/designSystems/appsmith/Dropdown.tsx | 33.33 **(-4.17)** | 0 **(0)** | 0 **(0)** | 33.33 **(-4.17)**</details>

Fixed overlapping dropdown

---

app/client/src/components/designSystems/blueprint/DatePickerComponent2.tsx

> Fixed: If the same date is selected in the Default and Min/Max date field then “Date out of range error”.
Fixes #4407
// Code coverage diff between base branch:release and head branch: bug/datepicker-max-date-validation 
:red_circle: | app/client/src/components/designSystems/blueprint/DatePickerComponent2.tsx | 28.99 **(0)** | 3.28 **(-0.11)** | 5.88 **(0)** | 28.36 **(0)**</details>

Fix: Allow the same dates to be used in Default & Min/Max fields

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/OrganisationTests/LeaveOrganizationTest_spec.js
app/client/src/components/ads/Menu.tsx
app/client/src/constants/messages.ts
app/client/src/pages/Applications/index.tsx
app/client/src/pages/organization/DeleteConfirmationModal.tsx
app/client/src/pages/organization/Members.tsx
app/client/src/reducers/uiReducers/orgReducer.ts

1. Added in place warning for `leave org` option in organization context menu.
2. Added a deletion confirmation modal to members page
#4903 
> Updated the existing cypress tests
// Code coverage diff between base branch:release and head branch: feature/confirm-leaving-org 
:green_circle: | total | 51.61 **(0.01)** | 32.71 **(0)** | 29.71 **(-0.01)** | 52.11 **(0)**
:red_circle: | app/client/src/constants/messages.ts | 71.4 **(-0.05)** | 100 **(0)** | 13.5 **(-0.14)** | 75.18 **(-0.09)**</details>

[Feature #4903] Show warning text for choosing choosing to leave organisation.

---

app/client/src/pages/Applications/ApplicationCard.tsx

Added a condition to hide export option for members with appViewer permission.
#4933 

[Fixed #4933] - App viewer will not be able to export app

---

app/client/src/widgets/DropdownWidget.tsx

> This issue arises due to DropDown getting string prop  "options" even when validator detected this string input ( i.e. "{{ \n _.chain() \n}}" ) as invalid and returned parsed value as empty Array. I have handled the current scenario, but if I get more insights into how prop value can be different from the value returned by a validated function, there can be a better solution.
Fixes # (#4146)

added string check on options props

---

app/client/src/mockResponses/WidgetConfigResponse.tsx
app/client/src/widgets/ChartWidget/index.tsx

When the User drag and drop the Chart widget->and select the custom chart from chart type->the "chart type not supported text" is displayed. Added a default config to resolve it.
Fixes #4573 
> tested locally.

FIX #4573 : added custom fusion chart config to override default message

---

app/server/appsmith-plugins/elasticSearchPlugin/src/test/java/com/external/plugins/ElasticSearchPluginTest.java
app/server/appsmith-plugins/mssqlPlugin/src/test/java/com/external/plugins/MssqlPluginTest.java
app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java

The MySQL, MSSQL and Elasticsearch tests in the server codebase use the image which is only available for linux/amd64 architecture and not for arm64. Running this on M1 Silicon Mac needs the image to be available for the arm64 architecture as well.
Fixes #4860 
- Ran the tests on M1 mac and verified
- Need to run this on a intel chip machine and make sure that things are not breaking

Fix - tests don't run on an M1 Silicon Mac

---

app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ExamplesOrganizationCloner.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ExamplesOrganizationClonerTests.java

When we try to fork or import an application containing the MongoDB datasource authenticated with SRV string, the destination application breaks with an authentication failure error. 
Fixes :
#4936
#4929
Manually tested on local and release instances.

Bugfix for applications with MongoDB datasources authenticated with SRV string

---

.github/workflows/build-rts.yml
.github/workflows/client-test.yml
.github/workflows/external-client-test.yml
.github/workflows/server.yml

Made changes to workflows to include triggers for the `release-frozen` branch as well. The triggers are only for pushes into the branch, and not PRs, since the process of creating the branch is manual today. When a new branch is created, the push trigger should create the relevant docker images.
The PR related images how also been updated to use the PR head instead of the target branch server images while running client tests.

Release frozen related changes

---

app/client/src/comments/inlineComments/AddCommentInput.tsx
app/client/src/components/ads/MentionsInput.tsx

Use user's name while rendering mention within the comment
- manually
// Code coverage diff between base branch:release and head branch: tag-user-by-name 
:green_circle: | total | 51.66 **(0)** | 32.91 **(0.02)** | 29.56 **(-0.01)** | 52.14 **(0)**
:red_circle: | app/client/src/comments/inlineComments/AddCommentInput.tsx | 71.84 **(0)** | 39.47 **(-2.2)** | 63.16 **(0)** | 71.91 **(-0.82)**
:green_circle: | app/client/src/components/ads/MentionsInput.tsx | 65.79 **(0)** | 45.24 **(8.7)** | 27.27 **(0)** | 63.77 **(0)**
:red_circle: | …

[Fix] Tag user by name

---

app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/plugins/RedisPlugin.java
app/server/appsmith-plugins/redisPlugin/src/test/java/com/external/plugins/RedisPluginTest.java

- Replace single connection instance with a connection pool. This will ensure that simultaneous actions don't fail / break the connection. 
Fixes #4924 
- Manual. Created six actions and set them to on page load. Earlier I could see actions failing, but with this change no such failure is seen.

Fix: Use connection pool for Redis

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Applications/ExportApplication_spec.js
app/client/src/pages/Applications/ApplicationCard.tsx
app/client/src/pages/Applications/permissionHelpers.tsx
app/server/appsmith-server/src/main/java/com/appsmith/server/acl/AclPermission.java
app/server/appsmith-server/src/main/java/com/appsmith/server/acl/AppsmithRole.java
app/server/appsmith-server/src/main/java/com/appsmith/server/acl/PolicyGenerator.java
app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java

> This PR fixes the issue where only admins can have the export application functionality.
Fixes #5061
- Enhancement (non-breaking change which adds functionality)
Tested manually with the following steps:
1. Create 2 dummy users: User1, User2
2. Login to User1 account
3. Create a dummy application
4. Try exporting application (_Success_)
5. Share the application with User2 as a developer
6. Login with User2 account, export option will not be available.
// Code coverage diff between base branch:release and head branch: feature/allow-only-admins-to-export-application  …

Allow only organization admins to export application

---

app/client/src/api/ApiUtils.ts
app/client/src/comments/CommentCard/CommentCard.tsx
app/client/src/components/ads/MentionsInput.tsx
app/client/src/constants/userConstants.ts

Dispatch a logout action which resets the user in store.
Else since we redirect away from login pages based on the user in store there's an infinite loop of redirections.
Fixes #5149 
- To reproduce: manually delete session cookie, there's an infinite loop of redirection
// Code coverage diff between base branch:release and head branch: reset-user-on-401 
:green_circle: | total | 51.7 **(0.01)** | 32.93 **(0)** | 29.64 **(0)** | 52.17 **(0)**</details>

Reset the user in store on 401s

---

app/client/src/utils/PerformanceTracker.ts

Add an option to set tags on transactions to easily filter them, for example by widget type.
Unlike context tags are indexed.
Fixes #5147
Verified in a separate react app as I couldn't get sentry to work locally in appsmith app 
// Code coverage diff between base branch:release and head branch: ui/perf/add-tags-option-to-performance-tracker 
:red_circle: | total | 51.71 **(-0.01)** | 32.96 **(0.01)** | 29.66 **(-0.01)** | 52.2 **(0)**
:red_circle: | …

Add an option to set tags on sentry performance transactions #5147

---

app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java
app/server/appsmith-plugins/postgresPlugin/src/test/java/com/external/plugins/PostgresPluginTest.java

- parse json/jsonb data type values as json
- add support for json (non binary, earlier support for jsonb was added)
Fixes #4226 
- Via Junit TC
- Manual: by creating tables with json and jsonb types

Fix: parse json/jsonb data type values as json for postgres plugin

---

contributions/ClientSetup.md

Documentation for helping setup Client environment in Windows WSL2
Fixes #5119 
Documentation

Added Documentation for Windows WSL2 Client Setup

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ActionExecution/ExecutionParams_spec.js

removed an unnecessary wait for @postExecute route

removed unwanted wait

---

app/client/src/api/ApiUtils.ts

We're using the complete href instead of relative path, that the saga expected.
There's another logic for redirection that was trigged while testing so this bug wasn't detected:
```
// if user is not logged and the error is "PAGE_NOT_FOUND",
// redirecting user to login page with redirecTo param
if (
get(user, "email") === ANONYMOUS_USERNAME &&
code === ERROR_CODES.PAGE_NOT_FOUND
) {
window.location.href = `${AUTH_LOGIN_URL}?redirectUrl=${window.location.href}`;
return false;
}
```
Fixes #5149
- Navigate to edit app
- Delete session cookie
- Click on appsmith home icon
- Should be redirected to the login page with the applications page as the redirectURL (redirectUrl should be the complete href)
<details><summary>:white_circle: Total …

Fix redirect URL on 401s

---

.github/workflows/client-test.yml

Removes the condition that allows integration tests to only run for internal PRs. All approved PRs should now trigger this workflow.

Run tests for all approved PRs

---

app/client/src/sagas/DatasourcesSagas.ts

Fix to change behaviour of back button in API datasource page when "Save as datasource" button is clicked.
Fixes #4869 
// Code coverage diff between base branch:release and head branch: fix/datasource_redirect_bug 
:green_circle: | app/client/src/sagas/DatasourcesSagas.ts | 13.96 **(0.05)** | 2.11 **(0)** | 9.52 **(0)** | 16.44 **(0.08)**</details>

Removed intermediate navigation to datasource list page.

---

app/client/src/components/editorComponents/Debugger/Resizer/index.tsx
app/client/src/constants/DefaultTheme.tsx
app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
app/client/src/pages/Editor/QueryEditor/Table.tsx

Fix to enable scroll in sql query results and disappearing scroll bar.
Dynamically adjust table virtualiser's height according to re-sizer's.
Fixes #5042 
// Code coverage diff between base branch:release and head branch: fix/scroll_sql_query 
:red_circle: | total | 53.34 **(-0.01)** | 35.31 **(-0.01)** | 31.92 **(-0.01)** | 53.85 **(-0.01)**
:red_circle: | app/client/src/components/editorComponents/Debugger/Resizer/index.tsx | 15 **(-1.22)** | 28.57 **(-4.76)** | 0 **(0)** | 16.67 **(-1.51)**
:red_circle: | …

Fix to enable scroll in sql query results.

---

app/client/src/workers/DataTreeEvaluator.ts
app/client/src/workers/evaluation.worker.ts
app/client/src/workers/evaluationUtils.ts

Translating edit differences had an issue where static changes were processed as NOOP when the data type changed from an object to some other type and vice versa. This caused a cyclic dependency for nodes when a nested dependency path was deleted and newly added paths were not processed. Fixed this by translating those events correctly
Fixes #4775 
Follow the steps in the issue. When the API is returning a string error, it should not result in a cyclical dependency. When you fix the API again to make it return an object, it should populate the table again
// Code coverage diff between base branch:release and head branch: fix/cyclical-api-error 
Status | File | % …

Fix cyclical dependency issue when Api returns an error

---

app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx
app/client/src/components/editorComponents/CodeEditor/index.tsx
app/client/src/workers/DataTreeEvaluator.ts
app/client/src/workers/evaluate.ts

- Don't mark error fields when lint errors occur
- Correctly log widget entity type when cyclical dependency occurs
- Slightly improve JS error message
// Code coverage diff between base branch:release and head branch: fix/lint-validation-for-inputs 
:green_circle: | app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx | 64.71 **(0.76)** | 61.29 **(0)** | 42.86 **(1.48)** | 67.09 **(0.84)**
:red_circle: | app/client/src/components/editorComponents/CodeEditor/index.tsx | 73.79 **(-0.23)** | 50.43 **(0)** | 56.25 **(-1.81)** | 74.61 **(-0.26)**
:red_circle: | …

Minor fixes for errors

---

app/client/src/entities/Comments/CommentsInterfaces.ts
app/client/src/notifications/NotificationListItem.tsx
app/client/src/sagas/CommentSagas/index.ts
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Comment.java
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/CommentThread.java

Set mode (EDIT/PUBLISHED) for comment, that can be used to link comments with the viewer or editor page
- manually
// Code coverage diff between base branch:release and head branch: add-mode-to-comments 
:green_circle: | total | 53.28 **(0.01)** | 35.27 **(0)** | 31.88 **(0.01)** | 53.81 **(0)**
:green_circle: | app/client/src/sagas/CommentSagas/index.ts | 49.18 **(1.28)** | 20.83 **(0)** | 56.25 **(2.92)** | 48.39 **(0.56)**</details>

Set mode (EDIT/PUBLISHED) for comments for notification links

---

app/client/src/entities/Datasource/RestAPIForm.ts
app/client/src/entities/Datasource/index.ts
app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
app/client/src/transformers/RestAPIDatasourceFormTransformer.ts
app/server/appsmith-interfaces/src/main/java/com/appsmith/external/constants/Authentication.java
app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ApiKeyAuth.java
app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/AuthenticationDTO.java
app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/BearerTokenAuth.java
app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/DatasourceConfiguration.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/APIConnectionFactory.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/ApiKeyAuthentication.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/BearerTokenAuthentication.java
app/server/appsmith-plugins/restApiPlugin/src/main/resources/form.json
app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/connections/ApiKeyAuthenticationTest.java
app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/connections/BearerTokenAuthenticationTest.java

- add api key based and bearer token based authentication options to REST API datasource
- this change is ported to release from https://github.com/appsmithorg/appsmith/pull/4683 
Fixes #5366
- JUnit TC
- manually
// Code coverage diff between base branch:release and head branch: feature/api_key_and_bearer_token_auth 
:red_circle: | total | 53.29 **(-0.03)** | 35.23 **(-0.05)** | 31.94 **(0)** | 53.8 **(-0.04)**
:red_circle: | app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx | 26.88 **(-1.21)** | 22 **(-0.92)** | 3.03 **(-0.2)** | …

Feature: add api key based and bearer token based authentication options to REST API datasource

---

app/client/src/pages/Applications/OnboardingForm.tsx
app/client/src/pages/Applications/index.tsx
app/client/src/utils/storage.ts

Onboarding typeform related changes:
- Always show typeform on `/applications` page, if it was started and not completed
- Redirect away from the form using the redirect url, instead to `/applications`
Fixes #5132
Fixes #5131 
Fixes #5130
Fixes #5129
- Manually
// Code coverage diff between base branch:release and head branch: show-onboarding-form-if-not-completed 
:red_circle: | total | 53.24 **(-0.01)** | 35.22 **(0)** | 31.92 **(-0.02)** | 53.75 **(-0.01)**
:red_circle: | app/client/src/utils/storage.ts | 34.38 **(-0.4)** | 0 **(0)** | 3.33 **(-0.37)** | 27.47 **(-0.58)**</details>

Onboarding typeform related fixes

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/RichTextEditor_spec.js
app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/ExplorerTests/Entity_Explorer_CopyQuery_RenameDatasource_spec.js

Reload action is causing some issues with RichTextEditorSpec , hence we are removing this check.

Removed Reload action

---

app/client/src/components/editorComponents/CodeEditor/index.tsx

When a non-ASCII quote gets added, it breaks evaluations as they are not valid javascript. To fix this, we are replacing the quotes with ASCII quotes when typing
Fixes #3873
Follow steps in the issue by pasting or typing those characters
// Code coverage diff between base branch:release and head branch: fix/invalid-quote-chars 
:red_circle: | total | 53.23 **(0)** | 35.23 **(-0.01)** | 31.92 **(0.01)** | 53.74 **(-0.01)**
:red_circle: | app/client/src/components/editorComponents/CodeEditor/index.tsx | 72.09 **(-1.7)** | 49.58 **(-0.85)** | 55.88 **(-0.37)** | …

Fix invalid quotes breaking evaluation

---

app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/DatasourceController.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ExamplesOrganizationCloner.java

As a part of editor/nav simplification project, i have added two APIs 
1. To get the list of available mock datasets to user 
2. Create a mock data set from the available datasets. 
I have also removed the the flow - pre populating of fakeAPI dataset when the user is logged in for the first time. The reason to do this is because we have decided to give the control to user where he can choose mock-data set of his own choice. 
Fixes #4542 
Fixes #4962 
- Tested locally via postman

Feature/editor simplify - API to work with mock data sets

---

app/client/src/actions/pageActions.tsx
app/client/src/api/PageApi.tsx
app/client/src/sagas/InitSagas.ts
app/client/src/sagas/PageSagas.tsx

After fetching the page, the necessary actions such as loading the data were done only for published pages. In this PR, I've added the support for the unpublished pages to do the same.
Fixes #5247 
Manually verified by switching the pages in the editor view and confirmed that the API calls to get data were being made or not.

Triggers post page load actions in the editor

---

app/client/src/pages/Editor/IntegrationEditor/IntegrationsHomeScreen.tsx

Updated the buggy conditions to show mock data listing
Fixes #5516 
- manually
// Code coverage diff between base branch:release and head branch: bug/show_mock_dbs_new_nav 
:green_circle: | total | 54.07 **(0)** | 36.09 **(0)** | 32.57 **(0)** | 54.62 **(0.01)**
:green_circle: | app/client/src/pages/Editor/IntegrationEditor/IntegrationsHomeScreen.tsx | 30.89 **(0.24)** | 15.15 **(-0.48)** | 5.56 **(0)** | 32.17 **(0.27)**</details>

[Bug] Mock data section is missing

---

app/client/src/components/editorComponents/CodeEditor/index.tsx

On selecting a slash command menu item the editor gets blurred and the item doesn't register a click event. So it doesn't execute the click handler
- Manually

Fix slash command not executed on click

---

app/client/src/workers/DataTreeEvaluator.ts

Remove property from dependency map when binding is removed
Fixes #5537 
Manual
// Code coverage diff between base branch:release and head branch: fix/depedency-not-getting-removed 
:red_circle: | total | 54.07 **(0)** | 36.09 **(0)** | 32.57 **(0)** | 54.61 **(-0.01)**
:red_circle: | app/client/src/workers/DataTreeEvaluator.ts | 88.3 **(-0.36)** | 78.46 **(-0.81)** | 87.32 **(0)** | 88.44 **(-0.4)**</details>

Fix: Remove property from dependency map when binding is removed

---

app/client/src/constants/WidgetValidation.ts
app/client/src/widgets/TextWidget.tsx
app/client/src/workers/validations.test.ts
app/client/src/workers/validations.ts

> Added text color js convertible support in text widget.
> Added COLOR_PICKER_TEXT validation.
Fixes #5235 
> Test cases
> Testes locally.
// Code coverage diff between base branch:release and head branch: fix/5235-textwidget-textcolor-js-convertible 
:green_circle: | total | 53.26 **(0.01)** | 35.24 **(0.02)** | 31.95 **(0.01)** | 53.77 **(0.01)**
:green_circle: | app/client/src/workers/validations.ts | 38.93 **(0.99)** | 33.45 **(0.92)** | 43.48 **(1.26)** | 39.36 **(0.72)**</details>

FIX #5235: added text color js convertible support in text widget

---

app/client/src/widgets/FilepickerWidget.tsx

> Picking a file in filepicker keeps on loading. The loading state was not stopped by default fixed it. 
Fixes #5287 
Fixes #5312 
// Code coverage diff between base branch:release and head branch: FIX/5287-filepicker-keep-loading-state 
:red_circle: | total | 53.24 **(-0.01)** | 35.22 **(0)** | 31.93 **(-0.01)** | 53.76 **(0)**
:red_circle: | app/client/src/widgets/FilepickerWidget.tsx | 38.46 **(-0.87)** | 0 **(0)** | 17.86 **(-0.66)** | 37.78 **(-0.86)**</details>

FIX #5287 : updated isLoading state when event action completed

---

app/client/build.sh
app/client/package.json
app/client/public/index.html
app/client/src/comments/CommentsShowcaseCarousel/CommentsCarouselModal.tsx
app/client/src/components/designSystems/appsmith/TableComponent/CommonUtilities.test.ts
app/client/src/components/editorComponents/GlobalSearch/parseDocumentationContent.ts
app/client/src/configs/index.ts
app/client/src/pages/Editor/APIEditor/ResultPagination.tsx
app/client/src/pages/Editor/Canvas.tsx
app/client/src/pages/Editor/Explorer/Widgets/WidgetContextMenu.tsx
app/client/src/pages/common/CustomizedDropdown/dropdownHelpers.tsx
app/client/src/sagas/CommentSagas/index.ts
app/client/src/sagas/GlobalSearchSagas.ts
app/client/src/utils/AppsmithUtils.tsx
app/client/src/utils/storage.ts
app/client/src/widgets/ListWidget/ListWidget.tsx
app/client/src/widgets/TableWidget/TablePropertyPaneConfig.ts
app/client/src/widgets/TableWidget/derived.js

The fallback for logging was set to debug which made all logs getting printed in prod
- Fallback set to ERROR
- set correct env in dev and build scripts
- introduce `logLevelOverride` to override loglevel
- Prod deployments should not see any debug logging
- setting `logLevelOverride` to either "DEBUG" or "ERROR" should override logging
// Code coverage diff between base branch:release and head branch: fix/loglevel 
:red_circle: | total | 54.06 **(-0.01)** | 36.09 **(0)** | 32.57 **(0)** | 54.61 **(-0.01)** …

Don't log debug level logs in prod

---

app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx

Handle exception and log additional info on sentry
Fixes #5342
No valid reproduction found
// Code coverage diff between base branch:release and head branch: fix/critical-evaluated-value-split 
:red_circle: | total | 54.07 **(0)** | 36.09 **(0)** | 32.57 **(0)** | 54.61 **(-0.01)**
:red_circle: | app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx | 63.33 **(-1.38)** | 59.38 **(-1.91)** | 42.86 **(0)** | 65.48 **(-1.61)**</details>

Handle exception where prepared statements viewer does not get a value

---

app/client/src/components/designSystems/blueprint/TextComponent.tsx
app/client/src/mockResponses/WidgetConfigResponse.tsx
app/client/src/widgets/TextWidget.tsx

The switch option for the text widget render by HTML.
Fixes #3682 
// Code coverage diff between base branch:release and head branch: feat/render-as-html-option 
:red_circle: | app/client/src/components/designSystems/blueprint/TextComponent.tsx | 42.42 **(-1.33)** | 10 **(0)** | 9.09 **(0)** | 40.63 **(-1.31)**</details>

feat: HTML Render option

---

app/client/src/sagas/WidgetOperationSagas.tsx
app/client/src/sagas/WidgetOperationUtils.test.ts
app/client/src/sagas/WidgetOperationUtils.ts

Fixes the crashing of the list widget when the list widget is pasted into list widget.
Fixes #5591
- Bug fix
// Code coverage diff between base branch:release and head branch: fix/list-widget-in-list-widget-when-pasting 
:red_circle: | total | 54.15 **(-0.01)** | 36.12 **(0)** | 32.85 **(0)** | 54.64 **(-0.02)**
:red_circle: | app/client/src/sagas/WidgetOperationSagas.tsx | 43.87 **(-0.06)** | 30.28 **(0)** | 50.59 **(0)** | 44.22 **(-0.08)**
:red_circle: | app/client/src/sagas/WidgetOperationUtils.ts | 52.99 **(-1.88)** | 32.58 **(-0.75)** | 69.23 **(0)** | 52.34 **(-3.11)**</details>

Fix: App crash on list widget after copy/paste

---

app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java

Fixes #5561
We now set the response body as a String in case we can't parse the JSON response properly in the Rest API Plugin. This ensures that users aren't blocked on their usage of Appsmith if their Rest APIs aren't well defined.
- JUnit test cases

Setting string response if the JSON is not valid

---

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ActionExecutionResult.java
app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/WidgetType.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionServiceTest.java

As part of editor simplification and new navigation, this change set address the widget suggestion feature. Based on some basic rules(which will look for specific fields and records count) the suggested widget is sent along with executed query response. 
Fixes #4960 
- Unit Tests 

Suggest widget after executing Action

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java

Sometimes, when the server is taking time in finishing the request of changing view access of an application, the client could timeout and trigger cancellation of the process. This leads to partial updation of the application and its underlying actions, pages and datasources. This PR adds the feature where once triggered, the change access process would run to completion without getting cancelled.
Added a test case which cancels the flow after service function call after 10 ms ensuring that the cancellation is mid way. Asserting that all the appsmith objects got updated correctly.

Reliable change application access from public to private & vice versa

---

app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/CommentController.java
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Application.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseAppsmithRepositoryImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CommentThreadRepository.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomCommentThreadRepository.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomCommentThreadRepositoryImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/CommentService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/CommentServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/CommentServiceTest.java

In order to show a marker on the comment icon to denote there are unread comments, a new field has been added in the get applications API. The field will contain the number of unread threads for the currently logged in user under that application.
Fixes #5224 
- Unit tests

Added new API to get unread comment thread count

---

app/client/src/mockResponses/WidgetConfigResponse.tsx
app/client/src/widgets/RichTextEditorWidget.tsx

Add required option to Rich Text Editor for validations when used with Form widget
Fixes #5161 
Fixes #5376 
Fixes #5380 

Add required option to Rich Text Editor for validations when used with Form widget

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_Widget_Copy_Paste_spec.js
app/client/src/sagas/WidgetOperationSagas.tsx

Fix column definition get truncated when copying a table widget
Fixes #5279 
- Updated cypress test to validate no new errors exists on new table
// Code coverage diff between base branch:release and head branch: fix/copy-table-column-computation 
:green_circle: | total | 54.17 **(0.01)** | 36.12 **(0)** | 32.85 **(0)** | 54.66 **(0)**
:green_circle: | app/client/src/sagas/WidgetOperationSagas.tsx | 44.14 **(0.21)** | 30.28 **(0)** | 50.59 **(0)** | 44.54 **(0.24)**</details>

Fix-Column definition get truncated when copying a table widget

---

app/client/src/components/editorComponents/CodeEditor/commandsHelper.ts
app/client/src/components/editorComponents/CodeEditor/generateQuickCommands.tsx
app/client/src/components/editorComponents/CodeEditor/index.tsx
app/client/src/components/editorComponents/form/fields/KeyValueFieldArray.tsx
app/client/src/components/formControls/DynamicTextFieldControl.tsx
app/client/src/pages/Editor/APIEditor/PostBodyData.tsx
app/client/src/pages/Editor/APIEditor/RapidApiEditorForm.tsx
app/client/src/utils/FormControlRegistry.tsx

Reactivated the slash command in query/api pane. The suggestion box would only show up if user manually enters `/` or clicks on `/` button.
Fixes #5664
manually
// Code coverage diff between base branch:release and head branch: bug/slash-command-in-query-pane 
:green_circle: | app/client/src/components/editorComponents/CodeEditor/commandsHelper.ts | 42.11 **(1.04)** | 40 **(-1.67)** | 22.22 **(0)** | 44.23 **(1.09)**
:green_circle: | app/client/src/components/editorComponents/CodeEditor/generateQuickCommands.tsx | 17.24 **(0.29)** | 0 **(0)** | 0 **(0)** | …

[Bug] Slash command in query pane

---

app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/AuthenticationSuccessHandler.java

Currently, the `FIRST_LOGIN` event is being fired for _some_ existing users, since the way we are identifying this is tied to example applications, which we've moved on from. So, instead, we are now using the `isFromSignup` information to decide if this is a first-login.

Fix new user event being fired on every login

---

app/client/src/components/editorComponents/GlobalSearch/useRecentEntities.tsx
app/client/src/reducers/uiReducers/globalSearchReducer.ts

Adding a null check for now, since this is causing the user's app to crash
fixes #5721

Add null checks for recent entities

---

app/client/src/pages/Editor/SaaSEditor/DatasourceForm.tsx

On successful deletion of google sheet data source, user will be redirected to active datasources.
Fixes #5747
Manually
// Code coverage diff between base branch:release and head branch: bug/google-sheet-deletion 
:red_circle: | total | 53.83 **(0)** | 35.8 **(0)** | 32.43 **(-0.01)** | 54.41 **(0)**
:green_circle: | app/client/src/pages/Editor/SaaSEditor/DatasourceForm.tsx | 34.65 **(0.31)** | 17.14 **(0)** | 5.88 **(-0.37)** | 36.56 **(0.3)**</details>

[Fix] on google sheet deletion success, redirecting user to active datasources

---

app/client/src/components/ads/DisplayImageUpload.tsx
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserDataServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/repositories/UserRepositoryTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/OrganizationServiceUnitTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserDataServiceTest.java

We have a limit on the image size that can be uploaded as profile picture. The maximum allowed size is 244KB. This PR increases the allowed image size to 3MB in frontend and 1MB in backend.  
Fixes #5041 
- Unit tests

Increased maximum image size to be uploaded as profile picture

---

app/client/src/pages/Editor/SaaSEditor/DatasourceForm.tsx
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/AuthenticationService.java

1. Changing the redirection URL to redirect user to view mode, on google sheet datasource successful connection.
2. Remove the `New Query` btn from G Sheet datasource edit mode
Fixes #5759 
// Code coverage diff between base branch:release and head branch: fix/view-mode-true 
:green_circle: | total | 53.84 **(0.01)** | 35.81 **(0.01)** | 32.44 **(0.01)** | 54.42 **(0.01)**
:green_circle: | app/client/src/pages/Editor/SaaSEditor/DatasourceForm.tsx | 36.26 **(1.61)** | 17.39 **(0.25)** | 6.25 **(0.37)** | 38.55 **(1.99)**</details>

Redirecting to view mode of datasource after authorization

---

app/client/src/api/ActionAPI.tsx
app/client/src/components/editorComponents/ApiResponseView.tsx
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java

- return hint message to user if the expected content type is json but the api response is not a valid json.
Fixes #5667 
- JUnit TC
- Via curl cmd: 
```
curl --request POST 'https://mock-api.appsmith.com/echo/raw' \
--header 'Content-Type: application/json' \
--data-raw '{
"headers": {
"Content-Type": "application/json"
},
"body": "raw text"
}'
```
// Code coverage diff between base branch:release and head branch: feature/add_json_warning_msg 
:red_circle: | app/client/src/components/editorComponents/ApiResponseView.tsx | 53.33 **(-0.84)** | 36.11 …

Feature: return hint message to user if the expected content type is json but the api response is not a valid json.

---

app/client/src/comments/tests/Comments.test.tsx
app/client/src/reducers/uiReducers/commentsReducer/commentsReducer.ts

// Code coverage diff between base branch:release and head branch: check-comments-enabled-for-hotkeys 
:green_circle: | total | 53.86 **(0.03)** | 35.81 **(0.01)** | 32.49 **(0.05)** | 54.44 **(0.02)**
:green_circle: | app/client/src/actions/commentActions.ts | 80.33 **(0.82)** | 100 **(0)** | 46.15 **(2.56)** | 77.42 **(0)**
:green_circle: | app/client/src/reducers/uiReducers/commentsReducer/commentsReducer.ts | 45.95 **(1.36)** | 35.71 **(10.71)** | 55.56 **(3.71)** | 52.31 **(1.54)**
:green_circle: | app/client/src/sagas/WebsocketSagas/WebsocketSagas.ts | 29.69 **(10.94)** | 15.79 **(5.26)** | 26.67 …

Dont enable comment mode if deactivated

---

app/client/src/components/editorComponents/ActionCreator/Fields.tsx

Resolution for Issues with NavigateTo functionality
- Changed label to improve clarity that the input can be either page name or external URL
- Added default string `'{}'` to Query Params field since without it if navigation target is selected
Fixes #3125 
// Code coverage diff between base branch:release and head branch: fix/3125-adding-default-values-for-navigateTo-action 
:red_circle: | total | 53.83 **(-0.01)** | 35.81 **(0)** | 32.44 **(0)** | 54.41 **(-0.01)**
:red_circle: | app/client/src/components/editorComponents/ActionCreator/Fields.tsx | 28.47 …

Improved label, updating navigateTo default prams when action type is changed to navigateTo in JS actions

---

app/client/src/pages/Editor/Explorer/Entity/EntityProperties.tsx

Value of API's data was different in widgets and entity explorer. 
1. Create an API Api1
2. Drop a text widget and bind text to the API data.
3. Now disable the on-page loading of Api1
4. Reload the page.
5. See entity explorer value of Api1 and the value widget is getting. Both are different
When the API is run, the data is properly loaded and the same in both locations. The issue was only when the data was empty or the API was not yet run. For this case, I added a test to check if the data is undefined and set the value as `"{}"`. This way, the data shown at both the places is the same.
Fixes #4665  
// Code coverage diff between base branch:release and head …

Fix: Value of API's data is different in widgets and entity explorer. Showing curly brackets when empty data is received

---

app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/plugins/RedisPlugin.java
app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/utils/RedisURIUtils.java
app/server/appsmith-plugins/redisPlugin/src/main/resources/form.json
app/server/appsmith-plugins/redisPlugin/src/test/java/com/external/plugins/RedisPluginTest.java

- add support in Redis plugin to select database when creating db connection.
- refactor code to use URI string instead of constructor call, because of lack of appropriate constructor.
- add TCs.
- fix validate datasource.
Fixes #5394 
- JUnit TCs.
- Manual.

Feature: add support in Redis plugin to select database when creating db connection.

---

app/client/src/sagas/DebuggerSagas.ts

Fix incorrect type. `getAction` can return Action | undefined.
Fixes #5692 
Manually
// Code coverage diff between base branch:release and head branch: fix/plugintype-undefined 
:green_circle: | total | 53.91 **(0)** | 35.85 **(0)** | 32.55 **(0.01)** | 54.5 **(0.01)**
:green_circle: | app/client/src/pages/Editor/IntegrationEditor/MockDataSources.tsx | 55.56 **(10.11)** | 87.5 **(0)** | 0 **(0)** | 55.56 **(10.11)**
:red_circle: | app/client/src/reducers/entityReducers/datasourceReducer.ts | 9.09 **(-0.17)** | 0 **(0)** | 0 **(0)** | 9.62 **(0)**
:red_circle: | …

Fix: Update incorrect type to handle undefined sentry error

---

app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java
app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/utils/QueryUtils.java
app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/utils/QueryUtilsTest.java

The issue here was that the executable statement was splitting at the end of query keyword `;`. However, with this logic, comments were considered to be a separate executable statement. There were two things that broke because of this:
1. If the comment was the last substring from the keyword split, the query always returned false in the `isSelectOrShowQuery` check. As a result all such queries returned with the `affectedRows` response, even if it was a select query.
2. For non-select queries, the last executed statement would be the comment, which would always return with `0`, as reported in the original issue.
This fix discards all comments from the query string during execution since they hold no value for the executable statements.
Fixes #5310  …

Ignore comments while preparing executable statement in MySQL plugin

---

.github/workflows/client-test.yml
app/client/cypress/setup-test.sh

This PR checks if the server has started before proceeding to cypress tests
Fixes #5845
I have tested the new workflow in my local fork.

Wait for server to start before Cypress tests

---

app/client/src/sagas/ActionExecutionSagas.ts

`navigateTo('page',{})` doesn't clear the appsmith.URL.queryParam variable when being used on the same page. Reported by a user on Intercom.
When a button click triggers the navigateTo option for the same page in the same window with different query params, the `appsmith.URL` store is not getting updated because the `history.push` method didn't trigger any changes. Have added an explicit call to the function to update the URL parameters
Fixes #5544 
// Code coverage diff between base branch:release and head branch: fix/5544-clearing-url-query-params 
:red_circle: …

Updating the URL object in appsmith global object when the pageid is same as the previous one

---

app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx

Identical key `actionConfiguration.body` was being assigned to query editor component which was causing problem during update. Adding a unique key resolved the issue.
Fixes #5676 
manually
// Code coverage diff between base branch:release and head branch: fix/bug-5676-sql-body-problem 
:green_circle: | total | 53.76 **(0.02)** | 35.79 **(0.02)** | 32.32 **(0)** | 54.33 **(0.02)**
:green_circle: | app/client/src/sagas/ErrorSagas.tsx | 68.14 **(3.54)** | 52.38 **(4.76)** | 50 **(0)** | 68.63 **(3.92)**
:green_circle: | app/client/src/sagas/CommentSagas/index.ts | …

[Fix] Query editor fields get appended when switching between Mongo and other SQL Datasource queries.

---

app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java

RestApiPlugin get httpCall's response body which is a byte array, and then construst jsonBody by new String method,
but the default charset used by String constructor is determined during virtual-machine startup and typically depends upon the locale and charset of the underlying operating system,
if don't specify the charset in String constructor, the jsonBody byte array would not be decoded by UTF-8 when self-host locale charset is not UTF-8.
Fixes #5639
- Bug fix
- Tested in China which windows10's default charset is GBK

Add UTF-8 encoding in the RestApiPlugin for all invocations

---

deploy/k8s/scripts/appsmith-ingress.yaml.sh

The correct endpoint is `/oauth2`, not `/oauth`. This is a typo here.

Fix OAuth endpoint prefix

---

app/client/src/components/editorComponents/GlobalSearch/parseDocumentationContent.ts

Added a parsing logic to replace the gitbook embeddings with iframe to support youtube videos
Fixes #4887 
- Manually
// Code coverage diff between base branch:release and head branch: feature/video-in-ominibar 
:red_circle: | total | 53.71 **(-0.02)** | 35.68 **(-0.02)** | 32.32 **(0.01)** | 54.29 **(-0.02)**
:red_circle: | app/client/src/components/editorComponents/GlobalSearch/parseDocumentationContent.ts | 78.79 **(-0.33)** | 43.02 **(0)** | 92.86 **(0.55)** | 79.17 **(-0.38)**
:red_circle: | app/client/src/sagas/ErrorSagas.tsx | 64.6 **(-3.54)** | 47.62 …

[Fix] Support Videos in omnibar

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java

Before processing the data type we need to set the suggested widgets. If the data types are already defined along with the response then widget suggestion method will not be executed. 
Fixes # 
- Locally

Bug - Set Suggested widgets before processing data types

---

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/MongoConfig.java
app/server/appsmith-server/src/main/java/com/appsmith/server/converters/StringToInstantConverter.java
app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/PolicyUtils.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/CommentServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NotificationService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NotificationServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserOrganizationServiceImpl.java

For an unknown reason, the `updatedAt` field in `resolvedState` and `pinnedState` is updated to a string instead of ISODate object. Due to this issue, the notification API raises an internal server error. This PR added a converter from string to instant. When there is a malformed string, it catches the exception and set the date to null so that the API does not fail.
Fixes #5194 

Fix datetime parsing error in notifications

---

app/client/src/sagas/ActionExecutionSagas.ts
app/client/src/utils/TypeHelpers.ts

Steps to reproduce the behaviour:
1. Select download action on button click
2. Enter this JS {{download('https://www.learningcontainer.com/wp-content/uploads/2020/05/sample-large-zip-file.zip','abc.zip','application/zip')}}
3. Download the file
4. You will notice that the downloaded file is corrupt.
Downloadjs library is not able to support the download of binary files directly. For this, when we are making a call via axios and setting the headers as `repsonseType: arraybuffer` then the library is able to parse the binary file. If we use the api to download the data and then pass to downlaodjs lib, it doesn't work, even if we use the string to array buffer conversion. Here, I have added a special type check for URLs and added a special condition where the data type is `URL` and the file …

Added axios call to the special use case of downloading zip files

---

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonConfig.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/AnalyticsService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ReleaseNotesService.java

This PR will remove the sensitive fields getting logged in analytics events. For self-hosted instances, identity fields will be encrypted.    
Fixes #5919

Refactor analytics events to encrypt or remove sensitive information 

---

app/server/docker-compose.yml
deploy/ansible/appsmith_playbook/roles/generate_template/templates/docker-compose.j2
deploy/k8s/templates/mongo-template.yaml
deploy/template/docker-compose.yml.sh

Mongo v5 has some issues with seeding data. Refer:  https://stackoverflow.com/questions/68392064/error-when-running-mongo-image-docker-entrypoint-sh-line-381
Hence, locking the mongo version to a known working tag till we have more information on the problem.

Locking mongo Docker container to 4.4.6

---

app/client/cypress/locators/apiWidgetslocator.json
app/client/src/components/editorComponents/CodeEditor/index.tsx
app/client/src/components/editorComponents/CodeEditor/styledComponents.ts
app/client/src/components/formControls/DynamicInputTextControl.test.tsx

During blur and focus events we remove new line characters.
Here instead we set the height of the input when the size is COMPACT, when not in focus to fix the height
Another approach could be delaying the `blur` event and racing it with a `focus` event, such that in case we're picking a value from the autocomplete we don't reset the input value
// Code coverage diff between base branch:release and head branch: try-fixing-autocomplete-1 
:green_circle: | total | 53.6 **(0.01)** | 35.35 **(0.02)** | 32.14 **(0.02)** | 54.16 **(0.02)**
:green_circle: | app/client/src/components/editorComponents/CodeEditor/index.tsx …

[Fix] Fix mouse click for the autocomplete at the api pane

---

app/client/src/constants/AppsmithActionConstants/ActionConstants.tsx
app/client/src/reducers/entityReducers/actionsReducer.tsx
app/client/src/sagas/ActionExecutionSagas.ts

Added filter for the new header from server `X-APPSMITH-DATATYPE` and performing `atob` on the response.
Fixes #5878 
// Code coverage diff between base branch:release and head branch: fix/5878-adding-server-side-support-for-binaries 
:green_circle: | total | 53.6 **(0)** | 35.34 **(-0.01)** | 32.15 **(0.01)** | 54.16 **(0)**
:green_circle: | app/client/src/sagas/ActionExecutionSagas.ts | 12.53 **(0.3)** | 1.97 **(0.73)** | 9.68 **(3.01)** | 14.36 **(0.32)**</details>

Added filter for new header and doing atob on the response

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewPageServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/PageServiceTest.java

After the page order is fetched from the Application object, we should use the order from this object. I was not using this value to sort the pages. 
Fixes # 
- Unit Tests
- Postman

Bug - Fix page order sorting

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Onboarding/Onboarding_spec.js
app/client/src/components/editorComponents/ActionCreator/index.tsx

Previously creating a query from onSubmit action selector used to create a query with the first datasource which was the datasource used for onboarding, but with the new nav flow it won't anymore. This is fixed by conditionally creating a specific query when clicking on the Create new query option.
Fixes #5438
Cypress test
// Code coverage diff between base branch:release and head branch: fix/onboarding-nav 
:green_circle: | total | 53.6 **(0)** | 35.33 **(-0.01)** | 32.15 **(0.01)** | 54.16 **(0)** …

Fix: Fix onboarding flow after new nav changes

---

app/client/src/comments/inlineComments/Comments.tsx
app/client/src/selectors/commentsSelectors.ts

1. Add a comment at a position such that we need to scroll
2. Click on the comment card link from the sidebar 
3. Close the comment thread, scroll away and click on the same card again
4. The comment card is not refocused
Fixes #5993
- Manually
// Code coverage diff between base branch:release and head branch: fix-comment-card-link 
:red_circle: | total | 51.85 **(-0.01)** | 33.53 **(0)** | 29.94 **(0)** | 52.53 **(0)**
:red_circle: | app/client/src/comments/inlineComments/Comments.tsx | 28.57 **(-1.73)** | 0 **(0)** | 0 **(0)** | 31.25 **(-2.08)**</details>

[Bug] Comment is not refocused on closing the comment thread and clicking on it again

---

app.json

Simplifying the Heroku deployment process by removing all non-required configuration parameters from the setup flow. They can be set by a user later via the Heroku CLI or Web login. 
Now the user only needs to set 4 variables:
1. Telemetry enable/disable
2. Encryption password
3. Encryption secret
4. Mongo DB URL

Removing non-required fields from Heroku deployment.

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ActionExecution/ExecutionParams_spec.js

updated Wait for PostExecute call to finish after button click

updated ExecutionSpec

---

app/client/src/components/designSystems/appsmith/ImageComponent.tsx

>  Added function for Download image in new tab 
Fixes #5764
// Code coverage diff between base branch:release and head branch: bug/image-dwnload-cors 
:red_circle: | total | 53.58 **(-0.01)** | 35.32 **(0)** | 32.12 **(0)** | 54.13 **(-0.02)**
:red_circle: | app/client/src/components/designSystems/appsmith/ImageComponent.tsx | 15.84 **(-1.18)** | 15.63 **(0)** | 8.33 **(-0.37)** | 16.67 **(-1.4)**</details>

handle image download error

---

deploy/install.sh

The RHEL images are missing on Docker's S3 bucket.
See <https://download.docker.com/linux/rhel/8/x86_64/stable/repodata/repomd.xml>, and notice that `x86_64` isn't listed here. But on <https://download.docker.com/linux/centos/8/x86_64/stable/repodata/repomd.xml>, we see that an `x86_64` is indeed listed.
Now, if we look at the repo definition file at <https://download.docker.com/linux/centos/docker-ce.repo>, we can see the base URL for download Docker stable is:
```
baseurl=https://download.docker.com/linux/rhel/$releasever/$basearch/stable
```
This, on RHEL 8, on `x86_64` architecture, would resolve to `https://download.docker.com/linux/rhel/8/x86_64/stable`, which, sadly, suddenly, doesn't exist.
There's a chance this might be a deliberate action, since RHEL appears to be recommending …

Fix install script on RHEL

---

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/CreateDBTablePageSolutionTests.java

As the generate CRUD page functionality is not available in FE for S3 and GoogleSheets plugins we are updating the plugin object not to enable support for the mentioned plugins. Also as the changelog has already run previously I have deleted the particular entry from mongockChangeLog and deleted the particular field from the plugin object as well as I don't wanted another migration for this.

Removed support for S3 and GSheets for generate CRUD page

---

app/client/src/pages/Applications/index.tsx
app/client/src/pages/common/SubHeader.tsx

Fixed an issue in home page where searched key gets reset but searched results doesn't.
Fixes #5075 

Fix #5075 Retain search keyword and search results when user navigates to profile page and comes back to home page.

---

app/client/src/components/editorComponents/GlobalSearch/index.tsx
app/client/src/components/editorComponents/GlobalSearch/parseDocumentationContent.ts

- Use alogolia's highlight tag to determine query index, that is later used for sorting the search results, so matching results show on top
- Fix highlighting for the document title
Fixes #6096
- Manually
// Code coverage diff between base branch:release and head branch: docs-updates 
:red_circle: | total | 51.91 **(0)** | 33.47 **(-0.01)** | 30.04 **(-0.01)** | 52.58 **(0)**
:red_circle: | app/client/src/components/editorComponents/GlobalSearch/index.tsx | 57.69 **(-0.64)** | 13.75 **(-1.11)** | 39.53 **(-0.95)** | 58.2 **(-0.72)** …

[Fix] Minor omnibar updates

---

app/server/appsmith-plugins/postgresPlugin/pom.xml
app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java
app/server/appsmith-plugins/postgresPlugin/src/test/java/com/external/plugins/PostgresPluginTest.java

- fix data type appearing with data value for types that JDBC does not internally map. 
- ref: https://jdbc.postgresql.org/documentation/publicapi/org/postgresql/util/PGobject.html 
```
Normally, a data type not known by the driver is returned by ResultSet.getObject() as a PGobject instance
```
ref: https://www.postgresql.org/docs/7.3/jdbc-ext.html 
Fixes #4225 
- JUnit TC
- Manual

Fix: fix data type appearing with data value for citext type for Postgres plugin

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/CommentServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/CommentServiceTest.java

When a new comment added to a thread, the thread should be marked as unread. This is shown as a red circle on the comment icon in the UI. This PR also includes another fix. When a new comment is added to a resolved thread, the thread should be marked as unresolved.
Fixes #5814 
- Unit tests

[Bugfix] Mark a comment thread as unread when there is a new comment in the thread

---

app/server/appsmith-server/src/main/java/com/appsmith/server/constants/AnalyticsEvents.java
app/server/appsmith-server/src/main/java/com/appsmith/server/constants/Entity.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/CreateDBTablePageSolution.java

> Find query was failing for MongoDB datasource because of the _where_ operator, which is linked with Select Widget. Allocation of labels and values were incorrect earlier for MongoDB datasource. Also added a analytics datapoint after successful page creation.   
Fixes #6086
> Tested manually on local instance

Bugfix for generate page from db table and add analytics event after the successful CRUD page creation

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/CommentServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/CommentServiceTest.java

Currently, the first comment thread created by an user is a private thread. In that thread, we create a bot comment telling the user about how to use the comment features. Private thread is created for all roles. This PR disables the private thread for app viewers.
Fixes #6110 
- Unit tests

Stop creating bot comment thread when user is app viewer

---

app/client/src/comments/inlineComments/OverlayCommentsWrapper.tsx

This fix makes sure that we maintain the scroll position inside a widget when user switches to comment mode, if a user has scrolled into a scrollable widget (e.g. - form, table and container etc.).
Fixes #5795 
- manual
// Code coverage diff between base branch:release and head branch: feature/keep-widget-scroll-in-comment-mode 
:green_circle: | total | 51.95 **(0)** | 33.76 **(-0.01)** | 30.03 **(0.01)** | 52.6 **(0)**
:green_circle: | app/client/src/comments/inlineComments/OverlayCommentsWrapper.tsx | 76.67 **(2.48)** | 41.67 **(4.17)** | 66.67 …

[Feature] Keep the scroll position into a widget when user switches to comment mode

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Image_spec.js

Changed the zoom test, from zoom in to no zoom and validated things accordingly

Updated image spec

---

app/client/src/pages/Editor/IntegrationEditor/NewApi.tsx

Changed the texts on the datasources page from "Create new" to "Create new API" and from "CURL" to "CURL import".
This is a fix for issue #6019 
Here is an image showing the effected change.
Fixes #6019 
Text change did not require tests, however I ensured that all existing tests passed.

changed texts on datasources page

---

app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/helpers/RequestCaptureFilter.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java

This change now returns the request object populated from the actual request sent via WebClient. It handles both success and error states. The headers are redacted only for `Authorization` or `api_key` headers.
Fixes #5473 
- JUnit tests

Setting ActionExecutionRequest in response from executed API call

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/LayoutActionServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutActionServiceTest.java

This change adds a check for refactor so that action refactor fails if an invalid name is provided to the API.
Fixes part of the issue in #5988 
- JUnit testing

Added validation for refactor name

---

app/client/src/components/editorComponents/GlobalSearch/parseDocumentationContent.ts

This fix will add support for links of the format - `https://youtu.be/{videoId}`
Fixes #6161 
- manual
// Code coverage diff between base branch:release and head branch: fix/bug-6161-video-in-omnibar-v2 
:red_circle: | total | 51.83 **(-0.01)** | 33.69 **(-0.01)** | 29.75 **(0.01)** | 52.47 **(0)**
:red_circle: | app/client/src/components/editorComponents/GlobalSearch/parseDocumentationContent.ts | 77.45 **(-1.12)** | 45.35 **(0)** | 87.5 **(-5.36)** | 77.78 **(-1.17)**
:red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.59 **(-0.24)** | 39.41 …

[Fix] Support short youtube video link embedding format, for videos in omnibar

---

app/client/src/workers/evaluate.ts

Firefox JS errors were returning the call stack in the Evaluated value pane
This PR fixes this issue
Manually
// Code coverage diff between base branch:release and head branch: fix/js-error-handleing-firefox 
:green_circle: | total | 51.84 **(0)** | 33.67 **(0.01)** | 29.75 **(0)** | 52.47 **(0)**

Fix JS error message showing call stack in firefox

---

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/SecurityConfig.java

Fixes #5872 
Adding an expiry of 30 days to the cookie to ensure that browsers don't delete the cookie when the browser session is closed.
Manual

Adding expiry of 30 days to session cookies

---

app/client/src/components/editorComponents/ActionRightPane/Connections.tsx
app/client/src/components/editorComponents/Debugger/EntityDependecies.tsx
app/client/src/components/editorComponents/Debugger/helpers.tsx
app/client/src/components/editorComponents/Debugger/hooks.ts
app/client/src/pages/Editor/PropertyPane/PropertyPaneConnections.tsx

- Log event when property pane connected entity is clicked
- Also add entity type info to event
- Refactor to make this happen by moving useGetEntityInfo hook to debugger hooks
Related to #6221 
Manually
// Code coverage diff between base branch:release and head branch: fix/missing-analytics 
:green_circle: | total | 51.85 **(0.01)** | 33.63 **(-0.03)** | 29.78 **(0.03)** | 52.48 **(0.01)**
:green_circle: | app/client/src/components/editorComponents/ActionRightPane/Connections.tsx | 42.5 **(2.84)** | 30.77 **(-0.48)** | 0 **(0)** | 42.5 **(2.84)**
:red_circle: …

Add missed new nav analytics for connections

---

app/client/cypress/fixtures/addWidgetTable-mock.json
app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/QueryPane/AddWidgetTableAndBind_spec.js

Mock the execute action api for the add widget test. 
Fixes https://dashboard.cypress.io/projects/eyxvp8/analytics/top-failures/4c795857-06f9-c825-ec3a-f080836ef66e-a63d6407-9c5c-5344-7eb0-78f0bd6a39e7
Locally

Fix add widget test by mocking the response

---

app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomCommentThreadRepositoryImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/CommentServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/repositories/CustomCommentThreadRepositoryImplTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/CommentServiceTest.java

If a thread is marked as resolved when it's still not viewed by some user, that user can see a red circle on the comment icon which means there are unread comments. But they can see none as resolved comments are hidden by default. This PR fixes this issue. It also logs `widgetType` to analytics when new threads are created.
Fixes #6150 #6222 
- Unit tests
- Tested locally on dev machine

Fix: Mark comment threads as viewed when they are resolved

---

app/client/src/reducers/uiReducers/commentsReducer/handleUpdateCommentThreadEvent.ts

Refresh sidebar comments list when thread is unresolved:
When a resolved comment is unresolved it should be updated in the UI at realtime and should now be visible in the comments list.
- Manual
// Code coverage diff between base branch:release and head branch: fix-refresh-list-when-thread-is-unresolved 
:green_circle: | total | 51.51 **(0.01)** | 33.54 **(0.03)** | 29.3 **(0)** | 52.13 **(0)**
:green_circle: | app/client/src/reducers/uiReducers/commentsReducer/handleUpdateCommentThreadEvent.ts | 100 **(6.67)** | 71.05 **(13.55)** | 100 **(0)** | 100 …

Refresh sidebar comments list when thread is unresolved

---

app/client/src/pages/Editor/IntegrationEditor/IntegrationsHomeScreen.tsx

Changed the `mock databases` label to `Sample Databases`
Fixes #6329 
Manual 
// Code coverage diff between base branch:release and head branch: fix/change-label-mock-to-sample-databases 
:green_circle: | total | 51.51 **(0)** | 33.56 **(0.01)** | 29.3 **(0)** | 52.14 **(0.01)**
:red_circle: | app/client/src/components/designSystems/appsmith/TableComponent/TableHelpers.ts | 100 **(0)** | 80 **(-10)** | 100 **(0)** | 100 **(0)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.83 **(0.24)** | 40.25 **(0.84)** | 36.21 **(0)** | 55.04 …

Fix - Updated label Mock data to Sample data

---

app/client/src/comments/CommentCard/CommentCard.tsx

Widget by page map doesn't exist for the view mode.
Adding a check as a quick fix.
- Manually
// Code coverage diff between base branch:release and head branch: fix-comment-card-link-view-mode 
:green_circle: | total | 51.51 **(0)** | 33.56 **(0.01)** | 29.3 **(0)** | 52.14 **(0.01)**
:red_circle: | app/client/src/comments/CommentCard/CommentCard.tsx | 32.6 **(0)** | 22.4 **(-0.74)** | 7.14 **(0)** | 34.32 **(0)**

Fix comment card click at the view mode

---

app/client/src/components/editorComponents/ActionCreator/index.tsx
app/client/src/components/editorComponents/CodeEditor/index.tsx
app/client/src/pages/Editor/Explorer/Actions/ActionEntityContextMenu.tsx
app/client/src/pages/Editor/Explorer/Entity/Name.tsx
app/client/src/sagas/selectors.tsx
app/client/src/selectors/entitiesSelector.ts
app/client/src/selectors/globalSearchSelectors.tsx

The following components re-render every-time something changes in the redux store. That is about 150 times for a single keypress in a medium sized app.
- ActionCreator,
- EntityName,
- CodeEditor and
- ActionEntityContextMenu
This PR optimizes the selectors to fix these issues. 4-5x improvement in performance.
Fixes #6240 
- UI Performance improvement
- Profiled before and after
// Code coverage diff between base branch:release and head branch: ui/perf/fix-code-editor-actioncreatore-re-renders 
:green_circle: | total | 51.52 **(0.02)** | 33.46 **(0)** | 29.36 **(0.06)** | 52.15 **(0.03)**
:red_circle: | …

Fix unnecessary renders of ActionCreator, EntityName, CodeEditor and ActionEntityContextMenu

---

app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ConfigController.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/AnalyticsService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ConfigService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ConfigServiceImpl.java

> For each backend analytics datapoint insert instanceId to differentiate between self-hosted instances. 
Fixes #6250 
> Tested on local instance with segment platform

Add instance id in analytics datapoint

---

app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Action.java
app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java
app/server/appsmith-plugins/amazons3Plugin/src/test/java/com/external/plugins/AmazonS3PluginTest.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/CreateDBTablePageSolution.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/DatasourceStructureSolution.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/CreateDBTablePageSolutionTests.java

To generate a page from the DB table, to select the bucket on which the CRUD page needs to be created create an API to fetch all the buckets from the connected S3 datasource.
Fixes #6333
> Tested manually

Add list buckets API to S3

---

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/CreateDBTablePageSolution.java

> Check for NPE to find if the layout already has some widgets. 
> Tested manually

Added null check for widget names in empty layout validation

---

app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/helpers/BodyReceiver.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/helpers/BufferingFilter.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/helpers/RequestCaptureFilter.java
app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java

Fixes #5462 
The changes will now show requests in the debugger pane as:
_Content type: Anything other than multipart or url encoded form data_
_Content type: URL encoded form data_
_Content type: Multipart with normal text value_
_Content type: Multipart for files_
This will literally always say `<file>` since we do not want to delay execution with such heavy payloads

Added logic to show form data requests in debugger

---

app/client/src/constants/messages.ts
app/client/src/pages/UserAuth/Login.tsx
app/client/src/utils/formhelpers.ts
app/server/appsmith-server/src/main/java/com/appsmith/server/constants/FieldName.java
app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java
app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/ValidationUtils.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/UserSignup.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/UserSignupTest.java

Added a limit on password length when user signs up.
- Unit test
- Tested on local dev machine
// Code coverage diff between base branch:release and head branch: bugfix/add-password-length-limit 
:green_circle: | total | 51.7 **(0)** | 33.64 **(0.01)** | 29.55 **(0)** | 52.36 **(0.01)**
:red_circle: | app/client/src/utils/formhelpers.ts | 73.68 **(-2.79)** | 0 **(0)** | 20 **(0)** | 64.29 **(-2.38)**

Improvement: Add limit on password length in user signup

---

app/client/src/components/designSystems/appsmith/MultiSelectComponent/index.styled.tsx

> Multi-selectbox's checkbox widget has same border-radius as normal checkbox widget.
Fixes #6162 
> Please refer to attached issue.

changed style of multiselectbox with radius 0

---

app/client/src/selectors/commentsSelectors.ts

Check if comments are enabled for comment intro modal
- Manually
// Code coverage diff between base branch:release and head branch: hotfix-disable-comment-intro-shortcut-key 
:red_circle: | total | 51.68 **(0)** | 33.6 **(-0.01)** | 29.52 **(0)** | 52.33 **(0)**
:red_circle: | app/client/src/selectors/commentsSelectors.ts | 38.1 **(0)** | 14.29 **(-0.42)** | 11.54 **(0)** | 32.43 **(0)**</details>

[hotfix] Check if comments are enabled for comment intro modal

---

app/client/src/components/designSystems/appsmith/MultiSelectComponent/index.styled.tsx

Wrap overflowing option in multiselect dropdown
Fixes #6389  (issue)
// Code coverage diff between base branch:release and head branch: fix/Multiselect-options-gets-truncated 
:green_circle: | total | 51.69 **(0.01)** | 33.62 **(0.01)** | 29.51 **(0.01)** | 52.35 **(0.01)**
:green_circle: | app/client/src/utils/helpers.tsx | 54.88 **(1.83)** | 30.14 **(4.11)** | 25 **(3.57)** | 48.06 **(1.55)**</details>

Fix: Wrap overflowing option in multiselect dropdown

---

app/client/src/reducers/uiReducers/commentsReducer/handleUpdateCommentThreadEvent.ts
app/client/src/sagas/WebsocketSagas/handleSocketEvent.ts

- Mark resolved threads as read in realtime: thread should be marked as read, unread indicator should be updated
- Refresh list when thread resolved status is updated
Fixes #6406
- Manually
// Code coverage diff between base branch:release and head branch: mark-resolved-threads-as-read 
:red_circle: | total | 51.69 **(-0.03)** | 33.56 **(-0.08)** | 29.51 **(0)** | 52.34 **(-0.03)**
:red_circle: | app/client/src/constants/messages.ts | 69.12 **(0.01)** | 100 **(0)** | 6.72 **(0.03)** | 75.99 **(-0.07)**
:red_circle: | …

[Fix] Mark resolved threads as read in real time, refresh list when thread resolved status is updated

---

app/client/src/components/designSystems/appsmith/MultiSelectComponent/index.styled.tsx

Same Font-size for Select and Multiselect Dropdown
Fixes #6388 
// Code coverage diff between base branch:release and head branch: fix/font-size-for-multiselect-widget 
:red_circle: | total | 51.68 **(0)** | 33.6 **(-0.01)** | 29.5 **(0)** | 52.34 **(0)**

fix: Font size

---

app/client/src/pages/AppViewer/GlobalHotKeys.tsx
app/client/src/pages/Editor/GlobalHotKeys.tsx

Fix reset comment mode hotkey: set comment mode by updating the query param.
The `handleLocationUpdate` listener within the `ToggleModeButton` listens to this param and updates the store.
Fixes: #6402
- Manually
// Code coverage diff between base branch:release and head branch: fix-reset-comment-mode-hotkey 
:red_circle: | total | 51.72 **(-0.01)** | 33.43 **(-0.02)** | 29.41 **(-0.03)** | 52.39 **(0)**
:red_circle: | app/client/src/actions/commentActions.ts | 72.8 **(-0.8)** | 100 **(0)** | 22.5 **(-2.5)** | 73.02 **(0)**
:red_circle: | …

[Fix] Reset comment mode hotkey

---

app/client/src/comments/CommentsShowcaseCarousel/index.tsx
app/client/src/comments/inlineComments/AddCommentInput.tsx
app/client/src/utils/helpers.tsx

Admins have a `manage:organizations` permission
Developers just have a `manage:orgApplications` permission
Fixes #6432
This updates the check if a user has a dev role
- Manually
// Code coverage diff between base branch:release and head branch: fix-role-check-developers 
:red_circle: | total | 53.39 **(-0.01)** | 34.99 **(-0.02)** | 31.51 **(-0.01)** | 53.94 **(-0.01)**
:red_circle: | app/client/src/utils/helpers.tsx | 54.88 **(-1.83)** | 28.77 **(-4.11)** | 25 **(-3.57)** | 48.84 **(-1.55)**</details>

[Fix] Update permission check for determining a user with dev access for comments intro

---

app/client/src/comments/CommentCard/CommentCard.tsx
app/client/src/comments/inlineComments/InlineCommentPin.tsx

Focus the comment thread when opened after dismissing
Reset the comment thread in the URL to re-trigger effects to set the visible thread and scroll it into view
Fixes #5993
- Manually
// Code coverage diff between base branch:release and head branch: reset-comment-thread-in-url-on-closing 
:green_circle: | total | 53.41 **(0.01)** | 34.99 **(0.01)** | 31.54 **(0.01)** | 53.96 **(0.01)**
:green_circle: | app/client/src/comments/CommentCard/CommentCard.tsx | 71.67 **(0.4)** | 59.2 **(0)** | 42.86 **(0)** | 72.02 **(0.42)**
:red_circle: | …

[Fix] Focus the comment thread when opened after dismissing

---

app/client/src/pages/UserAuth/Login.tsx
app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/AuthenticationFailureHandler.java
app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/AuthenticationSuccessHandler.java
app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/CustomFormLoginServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java

With this change, we are implementing a hierarchical login flow where OAuth takes precedence over Form login. So in a nutshell users will have a single login method at any point in time. 
Scenario 1: User signs up with FORM method, user can use form login until she uses OAuth login after that only OAuth method will be enabled
Scenario 2: User signs up with OAuth then only the OAuth method is available. User can't sign in with the form method  
// Code coverage diff between base branch:release and head branch: oauth-signin-config 
:red_circle: | total | 53.3 **(0)** | 34.81 **(-0.01)** | 31.39 **(0)** | 53.85 …

[skip_changelog] Form login disabled after user uses OAuth login method

---

app/client/src/mockResponses/WidgetConfigResponse.tsx

> Image widget - default is large, now replaced with the old default
Fixes #6427

changed default image to old

---

deploy/template/docker-compose.yml.sh

This PR adds a `restart: always` configuration to all containers in the default `docker-compose.yml` file generated by `install.sh`. This will allow the containers to start automatically when the VM restarts (or the Docker daemon restarts). Otherwise, currently, after a VM restart, we need to SSH into the server and issue a `docker-compose up -d` command in the installation folder to bring Appsmith up.
Docs: <https://docs.docker.com/config/containers/start-containers-automatically/#use-a-restart-policy>.
Thanks to @abulka from <https://github.com/appsmithorg/appsmith/issues/4705#issuecomment-893956711>.
Fixes #4705.

Enable auto-start of containers after VM restart in self-hosted installations

---

app/client/src/sagas/ActionExecutionSagas.ts

This PR fixes the issue where command + enter was not executing the action when google sheets were used as a data source.
Issue Link: - https://github.com/appsmithorg/appsmith/issues/6414
Fixes #6414
I tested this issue by creating a test API with google sheets as a data source and executed the run button using shortcut key command + enter in MacOS. I was able to run the API which was not happening before.

Added fix for cmd + enter not running google sheets actions

---

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/exceptions/pluginExceptions/AppsmithPluginError.java
app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/Sizeof.java
app/server/appsmith-plugins/mssqlPlugin/src/main/java/com/external/plugins/MssqlPlugin.java
app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java

Fixes #5923
An error is now returned if you try to fetch more than 1 MB of data in one go using Postgres plugin

Adding a max size of approximately 1 MB of data fetched using appsmith

---

app/client/src/components/designSystems/appsmith/TableComponent/TableHelpers.test.ts
app/client/src/components/designSystems/appsmith/TableComponent/TableHelpers.ts
app/client/src/utils/migrations/TableWidget.ts
app/client/src/widgets/TableWidget/derived.js

Reverts appsmithorg/appsmith#6041,
This is causing issue, https://github.com/appsmithorg/appsmith/issues/6375. The special characters in primary columns gets into the `propertyPath`s. Which causes error in updating path dependencies and causes errors in evaluation.
Fixes: #6375 
Reverting the change to fix the blocker issue until we come up with a solution for the special characters
cc: @riodeuno @somangshu @techbhavin 
// Code coverage diff between base branch:release and head branch: revert-6041-bug/table-ascii-char 
:red_circle: | total | 53.39 **(0)** | 34.97 **(-0.01)** | 31.51 **(0)** | 53.94 **(0)** …

Revert "Supporting all ASCII characters in table widget"

---

app/client/src/components/designSystems/appsmith/TableComponent/TableHelpers.ts
app/client/src/widgets/TableWidget/index.tsx

Fixed generating table column keys as it was crashing during a cyclical dependency
Fixes #6459
Manually
// Code coverage diff between base branch:release and head branch: fix/data-tree-update-error 
:green_circle: | total | 53.36 **(0.01)** | 34.78 **(0.01)** | 31.48 **(0.02)** | 53.9 **(0)**
:red_circle: | app/client/src/components/designSystems/appsmith/TableComponent/TableHelpers.ts | 100 **(0)** | 75 **(-5)** | 100 **(0)** | 100 **(0)**
:green_circle: | app/client/src/utils/helpers.tsx | 56.71 **(1.83)** | 32.88 **(4.11)** | 28.57 **(3.57)** | 50.39 …

Hotfix Table Widget crashes when there is a cyclical dependency

---

app/client/src/pages/Editor/WidgetSidebar.tsx

On location change, closing the widget panel
Fixes #6515 
- Manual
// Code coverage diff between base branch:release and head branch: fix/close-widget-pane-on-canvas-close 
:red_circle: | total | 53.34 **(-0.01)** | 34.75 **(-0.02)** | 31.46 **(-0.01)** | 53.89 **(0)**
:red_circle: | app/client/src/pages/Editor/WidgetSidebar.tsx | 34.72 **(-0.06)** | 20.83 **(-0.45)** | 0 **(0)** | 35.71 **(-0.11)**
:red_circle: | app/client/src/utils/helpers.tsx | 54.88 **(-1.83)** | 28.77 **(-4.11)** | 25 **(-3.57)** | 48.84 **(-1.55)**</details>

Fix: Close widget pane when user moves away from canvas

---

app/client/src/components/designSystems/appsmith/help/DocumentationSearch.tsx
app/client/src/components/designSystems/appsmith/help/HelpModal.tsx
app/client/src/pages/Editor/HelpButton.tsx

User would only receive automated trigger msgs, if they open the intercom at least once on their own. Intercom was being initialised in inner component that doesn't get mounted on page load. 
Fixes #6514 
// Code coverage diff between base branch:release and head branch: fix/intercom-triggers-not-working-properly 
:green_circle: | total | 53.36 **(0.02)** | 34.79 **(0.03)** | 31.48 **(0.02)** | 53.91 **(0.02)**
:green_circle: | app/client/src/components/designSystems/appsmith/help/DocumentationSearch.tsx | 61.33 **(2.12)** | 37.14 **(4.28)** | 14.29 **(7.15)** …

Fix: intercom triggers are not working properly

---

app/server/appsmith-plugins/arangoDBPlugin/src/main/resources/form.json

- replace actual certificate string with '*' like it is done for hiding password on the UI.
Fixes #5762 
- Manual

Fix: Arango plugin: hide certificate string using dots on UI

---

app/client/src/entities/Widget/utils.test.ts
app/client/src/widgets/TableWidget/TablePropertyPaneConfig.ts

Fixes #6480
Fixes #6454
// Code coverage diff between base branch:release and head branch: fix/Table-visible-column-not-saving 
:red_circle: | total | 53.36 **(0)** | 34.81 **(0)** | 31.49 **(-0.01)** | 53.91 **(0)**
:red_circle: | app/client/src/sagas/WidgetOperationSagas.tsx | 44.22 **(-0.07)** | 30.89 **(0)** | 48.86 **(-0.57)** | 44.52 **(-0.07)**</details>

fix: table column order and isVisible

---

app/client/src/components/designSystems/appsmith/TableComponent/Table.tsx

Extended "select all" to all rows on all pages instead of only those rows on the current page.
Fixes #6430
I have populated the table and verified the correct selection of the rows through the selectedRows property.

Feature: select all rows across table pages

---

app/server/appsmith-server/src/main/java/com/appsmith/server/featureflags/FeatureFlagEnum.java
app/server/appsmith-server/src/main/java/com/appsmith/server/featureflags/strategies/EmailBasedRolloutStrategy.java
app/server/appsmith-server/src/main/resources/features/init-flags.yml
app/server/appsmith-server/src/test/java/com/appsmith/server/featureflags/strategies/EmailBasedRolloutStrategyTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/FeatureFlagServiceTest.java
app/server/appsmith-server/src/test/resources/features/init-flags-test.yml

This PR adds the email based rollout strategy to features. We can now define a list of domain names in the `init-flags.yml` file and define the domains for which the feature will be active.
Also added tests to assert the functionality for this flag flipping strategy.

Adding the email rollout strategy to ff4j

---

app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java

- The connection seems to get stuck while doing validation check with `depth=REMOTE` i.e it pings the MySQL server waiting for a response - which somehow doesn't seem to come. This check is meant to determine whether the connection is still valid. In case it is invalid a stale connection exception is returned. This PR adds to this check by adding a timeout, assuming the connection to be stale in case the validity check gets stuck for more than timeout seconds. 
- Another solution that could work was to change the validation depth to `depth=LOCAL` in which case the validity check would check for its own side of the connection and not try to probe the server, however it seemed like it would cause a problem when the connection is dropped from the server side as it would not be able to detect …

Fix: Mysql plugin: change validation check to avoid connection block.

---

app/client/src/constants/Colors.tsx
app/client/src/pages/Editor/DataSourceEditor/BackButton.tsx
app/client/src/pages/Editor/GeneratePage/index.tsx

Currently when a user selects "generate from a data table"
there is no way the user can go back to the "Build from drag & Drop" option.
To resolve this added a back button in generate CRUD form page.
Fixes #6558 
- Manually
// Code coverage diff between base branch:release and head branch: fix/add-backbtn-gen-crud-form 
:green_circle: | total | 54.85 **(0.01)** | 36.69 **(0.01)** | 33.26 **(0)** | 55.43 **(0.01)**
:green_circle: | app/client/src/pages/Editor/DataSourceEditor/BackButton.tsx | 60 **(5)** | 50 **(0)** | 0 **(0)** | 60 **(5)** …

Add back button in generate page form

---

app/client/src/notifications/NotificationListItem.tsx
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/CommentNotification.java
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/CommentThreadNotification.java
app/server/appsmith-server/src/main/java/com/appsmith/server/events/CommentNotificationEvent.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/NotificationRepository.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/CommentServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NotificationService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NotificationServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/CommentServiceTest.java

When an user mentions another user in the first comment of a thread, the mentioned user does not get a notification but gets the email notification. This PR fixes this issue. It also sends notifications for the following cases:
- A comment is deleted
- Someone is tagged in a comment
- A thread is deleted
- A thread is resolved
Fixes #6483 
- Unit tests

Bugfix: Create notification when comment added, deleted and thread resolved, deleted

---

app/client/src/constants/userConstants.ts
app/client/src/selectors/organizationSelectors.tsx
app/client/src/utils/AnalyticsUtil.tsx
app/server/appsmith-server/src/main/java/com/appsmith/server/ServerApplication.java
app/server/appsmith-server/src/main/java/com/appsmith/server/acl/AclPermission.java
app/server/appsmith-server/src/main/java/com/appsmith/server/constants/Url.java
app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/InstanceAdminController.java
app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/UserController.java
app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/UserProfileDTO.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomUserRepository.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomUserRepositoryImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/EnvManager.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/UserSignup.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/EnvManagerTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/UserSignupTest.java

Introduces two new APIs, one for creating a super user, and another for updating Env variables.
`PUT /api/v1/admin/env` &mdash; Update env variable values.
Only super user can use this API. This API can only ever _change_ values of variables already defined in the env file. It can never _add_ new ones or _remove_ existing ones. It can, however, set values to empty, if the request payload defines so.
`POST /api/v1/users/super` &mdash; Create a super user with given details.
Creating a super user is currently allowed, when there's no other users on the system.
For existing installations, creating a super user will need to be done by executing a documented query on their MongoDB database. Being able to execute such a query will prove instance level access for the user, so they should be able …

Env Manager API and super user signup API

---

app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datasources/MockDatasource_spec.js

[Mockdatasource test](https://github.com/appsmithorg/appsmith/blob/release/app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datasources/MockDatasource_spec.js) is flaky.

fix cypress mockdatasource flaky test

---

app/server/appsmith-server/src/main/java/com/appsmith/server/events/AbstractCommentEvent.java
app/server/appsmith-server/src/main/java/com/appsmith/server/events/CommentAddedEvent.java
app/server/appsmith-server/src/main/java/com/appsmith/server/events/CommentThreadClosedEvent.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/EmailEventHandler.java
app/server/appsmith-server/src/main/resources/email/commentAddedTemplate.html
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/EmailEventHandlerTest.java

Currently, the notification emails contain the organization name and application name. As per the UI design, it should contain application name and page names. This PR fixes that issue.
Fixes #6622 
- Unit tests

[Imrpovement] - Add page name in comment notification emails

---

app/client/cypress/fixtures/application-file.json
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ApplicationJson.java
app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java
app/server/appsmith-server/src/test/resources/test_assets/ImportExportServiceTest/invalid-file-without-version.json
app/server/appsmith-server/src/test/resources/test_assets/ImportExportServiceTest/valid-application.json

> If we try import-export application flow for different versions of appsmith, application breaks because of data migration issues, upgraded version may support different widgets than the other one etc. To avoid this we are introducing the version check as the first step so that the imported application won't break after it has been rehydrated in the destination instance.  
Fixes #6519 
> Tested manually on local instance
// Code coverage diff between base branch:release and head branch: bug-import-export 
:red_circle: | total | 54.75 **(0)** | 36.75 **(-0.01)** …

Add version check for import-export flow

---

app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/plugins/RedisPlugin.java
app/server/appsmith-plugins/redisPlugin/src/test/java/com/external/plugins/RedisPluginTest.java

- Earlier `split` method was used to segregate cmd and args which failed when multiple words inside a quoted string formed one argument. e.g. `set key "my value"` would produce `set`, `key`, `"my`, `value"` as the tokens when `split` method is used, which is not correct. This change introduces a regex that would create the following tokens: `set`, `key`, `"my value"`.
Fixes #6363 
- JUnit TC
- Manual

Fix: Redis plugin: extract cmd and args based on regex

---

app/client/src/components/designSystems/blueprint/ButtonComponent.tsx

Fixes button style bug
// Code coverage diff between base branch:release and head branch: fix/button-color-style-fix 
:red_circle: | total | 54.84 **(0)** | 37.03 **(0)** | 33.16 **(-0.01)** | 55.41 **(0)**
:red_circle: | app/client/src/components/designSystems/blueprint/ButtonComponent.tsx | 47.86 **(-0.45)** | 39.6 **(-0.21)** | 55.56 **(-1.58)** | 51.4 **(-0.45)**</details>

fix button color style bug

---

app/client/src/pages/UserAuth/ResetPassword.tsx
app/client/src/sagas/userSagas.tsx
app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/UserController.java
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/PasswordResetToken.java
app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/EmailTokenDTO.java
app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserServiceTest.java

This PR enhances the password reset experience. It brings the following changes:
- Instead of sending email and token in email, it'll send a encrypted token which will contain the email and token
- Adds a rate limiter which allows to send 3 password reset requests in each 24 hours 
- Unit tests
// Code coverage diff between base branch:release and head branch: improvement/password-reset 
:red_circle: | total | 54.81 **(-0.01)** | 36.76 **(-0.01)** | 33.15 **(0)** | 55.39 …

[Improvement]- Improve the password reset feature

---

app/server/appsmith-plugins/dynamoPlugin/src/main/java/com/external/plugins/DynamoPlugin.java
app/server/appsmith-plugins/dynamoPlugin/src/test/java/com/external/plugins/DynamoPluginTest.java

- A fix had been introduced earlier (I had introduced it a few months back) to remove data type info keys from the raw response. However, the transformation was not getting applied to the `Query` action as the transformation was explicitly limited to few actions. This PR removes that check and allows the transformation for all actions as there does not seem to be any reason to withhold this transformation for other actions.
- The earlier fix also restricted this transformation to results that had specific keys. This PR removes this check as well as it does not seem to be required and further may lead to similar issues if any particular key gets missed. 
- Some other redundant checks have been removed from the flow as the transformation function itself takes care of it as edge/base case. …

Fix: Dynamodb Plugin: remove data type info keys from raw values. 

---

app/client/src/components/designSystems/appsmith/TableComponent/CascadeFields.tsx
app/client/src/utils/hooks/useBlocksToBeDraggedOnCanvas.ts

> It is observed that when the user keeps the table filter open and drags and drops any other widgets to the canvas the app crashes. So, added check for open filter pane and close if before property pane open.
Fixes #6615 
// Code coverage diff between base branch:release and head branch: FIX/6615-close-filterpane-before-drag-new-widget 
:green_circle: | total | 54.86 **(0.01)** | 36.97 **(0.01)** | 33.21 **(0)** | 55.44 **(0.01)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.71 **(0.24)** | 38.6 **(0.88)** | 36.21 …

FIX #6615 : added check for open filter pane and close if before property pane open

---

app/client/cypress/fixtures/application-file.json
app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/CreateDBTablePageSolutionTests.java

> This PR will enable the S3 and GSheet plugin for generate CRUD page from DB. Earlier we have commented this as FE code was not available to address the customisations required for these plugins. Also, small fix related to versioning in cypruss test for import application is also included 
> TC update
// Code coverage diff between base branch:release and head branch: enable-s3-gsheet-generate-page 
:red_circle: | total | 54.91 **(-0.01)** | 36.93 **(-0.01)** | 33.26 **(0)** | 55.5 **(0)**
:red_circle: | app/client/src/utils/autocomplete/TernServer.ts | …

[skip-changelog] Enable S3 and GSheet plugins for generate CRUD page

---

app/client/.eslintrc.json
app/client/src/api/ApiUtils.ts
app/client/src/comments/AppComments/AppCommentsFilterPopover.tsx
app/client/src/components/designSystems/appsmith/IconButtonComponent.tsx
app/client/src/components/designSystems/blueprint/InputComponent.test.tsx
app/client/src/components/propertyControls/IconSelectControl.tsx
app/client/src/components/stories/FilePicker.stories.tsx
app/client/src/components/stories/Table.stories.tsx
app/client/src/components/stories/TableDropdown.stories.tsx
app/client/src/components/stories/TextInput.stories.tsx
app/client/src/pages/Editor/GeneratePage/components/GoogleSheetForm.tsx
app/client/src/sagas/WidgetOperationSagas.tsx
app/client/src/utils/storage.ts

Add eslint rule to disallow console.log and console.warn. We should use log.debug instead
// Code coverage diff between base branch:release and head branch: fix/remove-console-eslint 
:green_circle: | total | 54.93 **(0.01)** | 36.95 **(0.02)** | 33.24 **(0)** | 55.52 **(0.01)**
:green_circle: | app/client/src/comments/AppComments/AppCommentsFilterPopover.tsx | 46.15 **(1.41)** | 66.67 **(0)** | 0 **(0)** | 48.65 **(1.43)**
:green_circle: | app/client/src/components/designSystems/appsmith/IconButtonComponent.tsx | 59.18 **(1.18)** | 12 **(0)** | 36.36 **(0)** | 69.05 **(1.61)** …

Add eslint rule to disallow console.log

---

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/InstanceConfig.java
app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/SecurityConfig.java
app/server/appsmith-server/src/main/java/com/appsmith/server/constants/AnalyticsEvents.java
app/server/appsmith-server/src/main/java/com/appsmith/server/constants/ConfigNames.java
app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ConfigController.java
app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/UserController.java
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/UserData.java
app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/UserSignupRequestDTO.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/AnalyticsService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ConfigService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ConfigServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserDataService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserDataServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/UserSignup.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/UserSignupTest.java

The welcome page that is used to signup a superuser contains more information than the current ordinary signup form. This PR adds support for these extra fields.
The `/users/signup` API now accepts a payload like the following:
```json
{
"email": "superhero@wherever-superheroes-dwell.com",
"name": "Shri",
"source": "FORM",
"state": "ACTIVATED",
"isEnabled": true,
"password": "ofcourse-imma-put-my-real-password-here",
"role": "Developer",
"companyName": "Superheroes Inc.",
"allowCollectingAnonymousData": true,
"signupForNewsletter": true
}
```
This creates a superuser, and act on other attributes like signing up for newsletter, if enabled etc.

Accept richer inputs from welcome signup form

---

app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/CustomFormLoginServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/authentication/handlers/CustomFormLoginServiceImplUnitTest.java

This PR checks for case insensitive email when no user found with a provided email address.
Fixes #5998 
- Unit test

[Bugfix] - Allow login with case insensitive emails

---

app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ApplicationController.java
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Application.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ExamplesOrganizationCloner.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionServiceTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutActionServiceTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/PageServiceTest.java

This PR will store the date time of when an application is deployed. It adds a new field `lastDeployedAt` to the application object. This field is updated when user clicks the deploy button.
Fixes #6543 

[Feature] - Add lastDeployedAt date to application object

---

app/client/src/widgets/TableWidget/index.tsx

> Fixed table filter when data source is changed.
Fixes #4974
// Code coverage diff between base branch:release and head branch: fix/fix-filter-table-4974 
:green_circle: | app/client/src/widgets/TableWidget/index.tsx | 27.64 **(0.05)** | 6.29 **(0)** | 25.49 **(0)** | 27.82 **(0.04)**</details>

fixed the filter issue in table widget

---

app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java

> This PR will improve the error message for imported unsupported application JSON file, to make it more actionable and humane. 
Fixes #6778
> TC update

[skip_changelog] Update error message for import flow

---

app/client/src/components/ads/NumberedStep.tsx
app/client/src/constants/messages.ts
app/client/src/pages/Editor/gitSync/Deploy/Commit.tsx
app/client/src/pages/Editor/gitSync/components/StyledComponents.tsx

Commit page ui
- Manually
// Code coverage diff between base branch:release and head branch: commit-ui 
:green_circle: | total | 54.62 **(0.01)** | 36.71 **(0.01)** | 33.05 **(-0.01)** | 55.23 **(0.01)**
:green_circle: | app/client/src/constants/messages.ts | 70.27 **(-0.04)** | 100 **(0)** | 10.26 **(-0.11)** | 77.15 **(0.19)**

Commit page ui

---

app/client/src/pages/Editor/DataSourceEditor/JSONtoForm.tsx

Values to default to an empty array to prevent type error.
Fixes #6781 
// Code coverage diff between base branch:release and head branch: fix/mongo_form_config_bug 
:red_circle: | total | 54.54 **(0)** | 36.4 **(-0.01)** | 32.88 **(0)** | 55.15 **(0)**

fix: Sentry type error in DB form

---

app/client/src/reducers/evaluationReducers/treeReducer.ts
app/client/src/sagas/EvaluationsSaga.ts
app/client/src/workers/DataTreeEvaluator.ts
app/client/src/workers/evaluation.worker.ts

To improve the redux update of app state (data tree) we had implemented a optimised update of the state. This did not seem to work properly as many updates were not getting reflected. Till the time a proper RCA is done, we will be reverting this fix
Reverts #5594
Fixes #6807
// Code coverage diff between base branch:release and head branch: fix/data-tree-update 
:green_circle: | total | 54.54 **(0)** | 36.41 **(0.01)** | 32.88 **(0)** | 55.15 **(0)**
:green_circle: | app/client/src/sagas/EvaluationsSaga.ts | 21.24 **(0.14)** | 2.94 **(-0.19)** | 6.67 **(0)** | …

fix: Revert redux update perf improvements

---

app/server/appsmith-server/src/main/java/com/appsmith/server/featureflags/FeatureFlagEnum.java
app/server/appsmith-server/src/main/resources/features/init-flags.yml

- Introduce feature flags for snippets feature and linting feature. 
Fixes #6823 
- Manual

feat: Feature flags snippet and linting features.

---

app/client/src/components/editorComponents/CodeEditor/index.tsx
app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx

Fixed mouse click bug for datasource url. 
Set height to 35px for url input
// Code coverage diff between base branch:release and head branch: fix/datasource_click_bug 
:red_circle: | app/client/src/components/editorComponents/CodeEditor/index.tsx | 64.61 **(-0.66)** | 36.43 **(-0.53)** | 50 **(-1.35)** | 67.42 **(-0.78)**</details>

fix: Api pane url input height.

---

app/client/src/components/ads/Dropdown.tsx
app/client/src/pages/Editor/GeneratePage/components/GeneratePageForm/GeneratePageForm.tsx

Fixes #6824 &  #6239
Manually
// Code coverage diff between base branch:release and head branch: fix/gen-crud-disable-empty-table 
:red_circle: | total | 55.11 **(-0.01)** | 37.23 **(-0.04)** | 33.77 **(-0.01)** | 55.7 **(-0.01)**
:red_circle: | app/client/src/components/ads/Dropdown.tsx | 52.94 **(0)** | 37.7 **(-0.76)** | 25 **(0)** | 51.22 **(0)**
:red_circle: | app/client/src/pages/Editor/GeneratePage/components/GeneratePageForm/GeneratePageForm.tsx | 17.49 **(-0.65)** | 10.71 **(-0.61)** | 0 **(0)** | 19.6 **(-0.4)**
:red_circle: | …

fix: Generate Page using Empty Table error 

---

app/rts/src/server.ts

The RTS is shutting down when there is some unexpected errors. This PR adds a check and some more logs to address this issue

Fix: Improved logging and added handled some exceptions in RTS

---

app/client/cypress/fixtures/saveAction.json
app/client/src/entities/Datasource/index.ts
app/client/src/pages/Editor/SaaSEditor/DatasourceForm.tsx

Show status of authorization on Gsheets datasource form
Fixes #6101
// Code coverage diff between base branch:release and head branch: hotfix/include-timestamp-for-gsheet-authorisation 
:green_circle: | total | 54.62 **(0)** | 36.68 **(-0.01)** | 33.05 **(0.01)** | 55.23 **(0)**
:green_circle: | app/client/src/pages/Editor/SaaSEditor/DatasourceForm.tsx | 38.38 **(2.12)** | 19.51 **(2.12)** | 11.11 **(4.86)** | 40.66 **(2.11)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.71 **(0.24)** | 38.6 **(0.88)** | 36.21 **(0)** | 55.35 …

fix: inclusion of authorization error for Google sheets

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Chart_spec.js

Custom fusion chart was loading with some delay and cypress test cases were getting previous element to verify the x axis data. Added one more check to wait till the chart data is loaded before verifying.

fix: chart widget fix

---

app/client/src/components/ads/Tabs.tsx

fix tab component styles at the settings page (dark theme)
- Manually
// Code coverage diff between base branch:release and head branch: fix-tab-component-style-settings-page 
:green_circle: | total | 55.05 **(0.01)** | 36.98 **(0.01)** | 33.72 **(0)** | 55.64 **(0)**

fix: tab component styles at the settings page

---

app/client/src/pages/Editor/GeneratePage/components/GeneratePageForm/GoogleSheetForm.tsx

fix: Restrict e as input for table header index

---

app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/plugins/RedisPlugin.java
app/server/appsmith-plugins/redisPlugin/src/test/java/com/external/plugins/RedisPluginTest.java

- This method removes the outermost quotes - single or double quotes - so that end users don't have to do it via javascript inside widget fields where they are meant to be bound.
- Some examples of old and new outputs:
- `"my val"` -> `my val`
- `'my val'` -> `my val`
- `'{"key": "val"}'` -> `{"key": "val"}`
Fixes #5853 
- JUnit TC
- Manual

fix: remove outermost quotes from redis plugin result

---

app/client/src/components/designSystems/appsmith/TableComponent/TableUtilities.tsx

> When apply cell background of table property, it should be applied to empty row's cells.
Fixes #2868 
> Please refer attached issue
// Code coverage diff between base branch:release and head branch: FIX/2868-issue-of-adding-background-table 
:red_circle: | total | 51.7 **(0)** | 33.62 **(-0.02)** | 29.55 **(0)** | 52.35 **(-0.01)**
:red_circle: | app/client/src/components/designSystems/appsmith/TableComponent/TableUtilities.tsx | 38.02 **(-0.96)** | 16.85 **(-2.14)** | 9.38 …

added cell background of empty rows

---

app/client/src/comments/CommentCard/CommentContextMenu.tsx
app/client/src/comments/CommentCard/ResolveCommentButton.tsx
app/client/src/components/ads/EmojiPicker.tsx
app/client/src/constants/messages.ts

Added tooltips for - Reaction, Resolve thread and More options action buttons
Fixes #4994 
- Manual
// Code coverage diff between base branch:release and head branch: fix/4994-show-tooltips-in-comment-cards 
:green_circle: | total | 54.93 **(0.02)** | 36.81 **(0)** | 33.59 **(0.03)** | 55.46 **(0)**
:green_circle: | app/client/src/comments/CommentCard/CommentContextMenu.tsx | 80 **(0.41)** | 81.82 **(0)** | 33.33 **(0)** | 80.85 **(0.42)**
:green_circle: | app/client/src/comments/CommentCard/ResolveCommentButton.tsx | 92.86 **(0.55)** | 70 **(0)** | 80 **(0)** …

fix: show tooltips for action buttons in comment card

---

app/client/src/components/editorComponents/ActionRightPane/index.tsx
app/client/src/pages/Editor/APIEditor/ApiRightPane.tsx
app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx

Regardless, if user has ran a query/api or not, if the relationship maps are available we'll show them to the user.
-manual
// Code coverage diff between base branch:release and head branch: fix/show-connections-asap 
:red_circle: | total | 54.89 **(-0.01)** | 36.79 **(-0.01)** | 33.56 **(0)** | 55.44 **(-0.01)**
:red_circle: | app/client/src/components/editorComponents/ActionRightPane/index.tsx | 34.07 **(-0.41)** | 25 **(0)** | 0 **(0)** | 36.9 **(-0.6)**
:red_circle: | app/client/src/pages/Editor/APIEditor/ApiRightPane.tsx | 44.23 **(-2.71)** | 47.06 …

feat: show relationships mapping in api/query pane as soon as user makes a binding

---

app/rts/package.json
app/rts/yarn.lock

Fix potential race condition error that's killing RTS, when multiple several users leave a room at the same time, which isn't uncommon for our use case.
This is done by upgrading `socket.io-adapter` dependency to version `2.3.2`, which includes fix from PR https://github.com/socketio/socket.io-adapter/pull/74.

fix: Upgrade socket.io-adapter to fix race condition

---

app/client/start-https.sh

A potential contributor getting started with the client codebase ran into a problem, when they executed the following command:
```
./start-https.sh https://release.app.appsmith.com/
```
This doesn't work (notice the extra `/` at the end). This sets the `proxy_pass` directive in the generated Nginx configuration, pointing to `https://release.app.appsmith.com/`. Seeing that this ends with a `/`, Nginx strips the path from the incoming request.
This is part that gets generated:
```nginx
location /api {
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host $host;
proxy_pass https://release.app.appsmith.com/;
}
```
With this configuration, the URL `https://localhost/api/v1/users/me` will be forwarded to `https://release.app.appsmith.com/v1/users/me` (notice missing …

fix: Confirm when server endpoint ends with a slash

---

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/CreateDBTablePageSolution.java

> Generated CRUD page was showing only the table name on the canvas, this PR will keep the parent schema along with the DB table name 
Fixes #6870
> Tested manually on local instance

feat: Keep the table schema in the table name for the generated CRUD page 

---

app/client/src/constants/WidgetConstants.tsx
app/client/src/utils/WidgetPropsUtils.tsx

Fixes incorrect DSL versions in the migrations list.
// Code coverage diff between base branch:release and head branch: fix/dsl-versions 
:green_circle: | total | 54.92 **(0.02)** | 36.82 **(0.04)** | 33.64 **(0.03)** | 55.46 **(0.02)**
:green_circle: | app/client/src/utils/WidgetPropsUtils.tsx | 74.88 **(0.33)** | 66.47 **(0)** | 69.89 **(0)** | 73.91 **(0.34)**
:green_circle: | app/client/src/utils/migrations/MenuButtonWidget.ts | 69.23 **(46.15)** | 66.67 **(66.67)** | 100 **(100)** | 66.67 **(50)**</details>

fix: DSL versions during client migrations

---

app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/CustomFormLoginServiceImpl.java

This PR will update the login source capitalization in the error message displayed for a user who is trying to login using form when OAuth source is present. For example in case of google OAuth error message will be changed as follows: 
Before : Please use **GOOGLE** authentication to login to Appsmith
After : Please use **Google** authentication to login to Appsmith
Fixes #6890
> Tested manually on local instance

fix: Update error message for form login when OAuth login is present

---

app/client/src/components/editorComponents/CodeEditor/index.tsx

Fixes slash command mouse click in property pane.
Fixes #6976 
// Code coverage diff between base branch:release and head branch: fix/slash-command-click-bug 
:red_circle: | total | 54.92 **(-0.01)** | 36.82 **(-0.01)** | 33.65 **(0)** | 55.47 **(0)**

fix: Fixes mouse click for slash commands

---

app/client/src/comments/AppComments/AppCommentThreads.tsx
app/client/src/comments/inlineComments/AddCommentInput.tsx
app/client/src/comments/inlineComments/Comments.tsx
app/client/src/components/designSystems/appsmith/CenteredWrapper.tsx
app/client/src/constants/messages.ts

When user tries to open a link of resolved comment thread, we'll enforce the `show resolved comments` filter
Fixes #5811 
Fixes #5434 
- manually
// Code coverage diff between base branch:release and head branch: fix/5811-link-for-resolved-thread-not-visible 
:red_circle: | total | 54.92 **(0)** | 36.82 **(0)** | 33.64 **(-0.01)** | 55.46 **(-0.01)**
:green_circle: | app/client/src/comments/inlineComments/Comments.tsx | 97.22 **(0.08)** | 90 **(0)** | 100 **(0)** | 100 **(0)**
:red_circle: | app/client/src/components/designSystems/appsmith/CenteredWrapper.tsx | …

fix: link for resolved comment does not show a comment thread

---

.github/semantic.yml
app/client/src/constants/messages.ts
app/client/src/sagas/ActionSagas.ts
app/client/src/sagas/ErrorSagas.tsx

When creating/deleting actions, the client displays success toast messages that don't add value to the developer's workflow. Hence removing them. Also minor refactoring in the `ErrorSagas` to simplify code flow making it easier to understand.
- Chore
- Manual
// Code coverage diff between base branch:release and head branch: remove-redundant-toast-message 
:green_circle: | total | 54.9 **(0)** | 36.79 **(0.01)** | 33.63 **(0)** | 55.45 **(0.01)**
:green_circle: | app/client/src/constants/messages.ts | 70.89 **(0.03)** | 100 **(0)** | 12.15 **(0.08)** | 78.66 **(0.29)** …

chore: Removing redundant toast message in action creation & deletion flow

---

app/client/src/api/ActionAPI.tsx
app/client/src/sagas/ActionExecution/PluginActionSaga.ts

The errorType field was missed out in https://github.com/appsmithorg/appsmith/pull/6253 changes. Adding it to send the same for debugger error analytics
Related to https://github.com/appsmithorg/appsmith/pull/6754
Manually
// Code coverage diff between base branch:release and head branch: fix/action-subtype-error 
:red_circle: | total | 54.94 **(0)** | 36.83 **(0)** | 33.62 **(-0.01)** | 55.48 **(-0.01)**
:red_circle: | app/client/src/pages/Editor/GeneratePage/components/CrudInfoModal.tsx | 78.85 **(-1.92)** | 89.66 **(0)** | 33.33 **(-8.34)** | 77.08 …

fix: fix missed out errorType field for debugger error analytics

---

app/client/Dockerfile
app/client/docker/start-nginx.sh
app/client/docker/templates/nginx-app-http.conf.template
app/client/docker/templates/nginx-app-https.conf.template

Fixes #4635.
After this is fixed, the appsmith-editor container will be able to be run with a command like the following:
```sh
docker run -p 80:80 -p 443443 -e APPSMITH_SERVER_PROXY_PASS='http://host.docker.internal:8080' appsmith/appsmith-editor
```
Locally
// Code coverage diff between base branch:release and head branch: fix/editor-container-vanilla 
:red_circle: | total | 51.66 **(-0.01)** | 33.66 **(-0.01)** | 29.53 **(0)** | 52.32 **(0)**
:red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.59 **(-0.24)** | 39.41 **(-0.84)** | 36.21 **(0)** …

Fix editor container fails to run with vanilla config

---

app/client/src/components/editorComponents/CodeEditor/index.tsx

Added "Space" and "Semicolon" to the list of characters that trigger the closeHint function on the editor.
Fixes #6243
> Manual testing

fix: closing hint menu when space/semicolon is entered

---

app/client/src/components/ads/EmojiReactions.tsx

Unicode emojis are not center aligned horizontally on non-retina displays
Add a margin to fix that
- Manually
// Code coverage diff between base branch:release and head branch: fix-emoji-alignment-non-retina-display 
:red_circle: | total | 54.94 **(0)** | 36.8 **(-0.01)** | 33.69 **(0)** | 55.48 **(-0.01)**

fix: center align emoji for non-retina displays

---

app/client/package.json
app/client/src/constants/WebsocketConstants.tsx
app/client/src/pages/Editor/Canvas.tsx
app/client/src/sagas/WebsocketSagas/WebsocketSagas.ts
app/rts/.env.example
app/rts/package.json
app/rts/src/server.ts
app/rts/yarn.lock

* Adding logLevel library to RTS. Helps us control the logging level for RTS in different environments. 
* Moving the session login check to `/users/me` API instead of the data heavy `/applications/new`
* Removing the information about express header. This is a security loophole.
Chore PR
Manual
// Code coverage diff between base branch:release and head branch: refactor-rts 
:green_circle: | app/client/src/constants/WebsocketConstants.tsx | 72.73 **(2.73)** | 100 **(0)** | 0 **(0)** | 100 **(0)**
:green_circle: | app/client/src/pages/Editor/Canvas.tsx | 65.85 **(0.85)** | 28.57 **(0)** | 50 **(0)** | 66.67 …

chore: Minor refactoring changes for RTS

---

app/client/src/components/ads/Tabs.tsx
app/client/src/components/designSystems/appsmith/Dropdown.tsx
app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx

Fixes the tab container height to account for the header, there by preventing the scroll bar from leaving the container boundary. Fixed drop down placement in forms.
Fixes #5138 

fix: form data overflow

---

app/client/src/constants/messages.ts
app/client/src/pages/Editor/GlobalHotKeys.test.tsx
app/client/src/pages/Editor/GlobalHotKeys.tsx

Fixes #6424
Manual
// Code coverage diff between base branch:release and head branch: feature/override-meta-s-hotkey 
:green_circle: | total | 54.91 **(0.05)** | 36.88 **(0.06)** | 33.72 **(0.15)** | 55.5 **(0.05)**
:green_circle: | app/client/src/components/ads/Text.tsx | 100 **(4.65)** | 75 **(3.57)** | 100 **(0)** | 100 **(4.76)**
:green_circle: | app/client/src/components/ads/Toast.tsx | 78.26 **(30.43)** | 61.11 **(27.78)** | 88.24 **(76.48)** | 78.26 **(30.43)**
:green_circle: | app/client/src/constants/messages.ts | 70.31 **(0.11)** | 100 **(0)** …

feat: `mod + s` hotkey to suppress default page save and show toast message

---

app/client/src/components/editorComponents/ApiResponseView.tsx
app/client/src/pages/Editor/APIEditor/Form.tsx

Fix: bottom padding at the api editor
Currently on release:
Fixed:
- Manually
// Code coverage diff between base branch:release and head branch: fix-bottom-padding-api-editor 
:green_circle: | total | 55 **(0)** | 36.89 **(0.01)** | 33.89 **(0)** | 55.55 **(0)**
:green_circle: | app/client/src/components/editorComponents/ApiResponseView.tsx | 51.22 **(0.6)** | 37.33 **(1.22)** | 0 **(0)** | 52.5 **(0.6)**</details>

fix: bottom padding at the api editor

---

app/client/src/widgets/InputWidget.tsx

Fixes #6723 
Cause - This is a very old issue that yet to be resolved by Mozilla
https://bugzilla.mozilla.org/show_bug.cgi?id=800050
https://bugzilla.mozilla.org/show_bug.cgi?id=1189486
Manual
// Code coverage diff between base branch:release and head branch: fix/6723-firefox-input-selection 
:red_circle: | total | 54.85 **(-0.01)** | 36.79 **(-0.02)** | 33.55 **(-0.02)** | 55.44 **(-0.01)**
:red_circle: | app/client/src/utils/helpers.tsx | 66.11 **(-1.67)** | 37.89 **(-3.16)** | 45.16 **(-3.23)** | 63.19 **(-1.39)**
:red_circle: | …

fix: Firefox input widget text selection

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Pages/Pages_spec.js
app/client/src/pages/Editor/Explorer/Actions/ActionEntity.tsx
app/client/src/pages/Editor/GeneratePage/components/ActionCards.tsx
app/client/src/pages/Editor/WidgetsEditor.tsx
app/client/src/pages/Editor/index.tsx

Moving the effect at the parent component to make sure we track pageId from url params
Fixes #6996
- manually
// Code coverage diff between base branch:release and head branch: fix-current-page-id-not-tracking-pageid-param 
:green_circle: | total | 55.01 **(0.01)** | 36.92 **(0.01)** | 33.87 **(-0.01)** | 55.55 **(0)**
:green_circle: | app/client/src/pages/Editor/WidgetsEditor.tsx | 92.65 **(0.98)** | 75 **(3.12)** | 100 **(0)** | 92.31 **(1.01)**
:green_circle: | app/client/src/pages/Editor/Explorer/Actions/ActionEntity.tsx | 65 **(5)** | 0 **(0)** | 0 **(0)** …

fix: listen to page id param at the parent editor component

---

app/client/src/constants/messages.ts
app/client/src/sagas/ActionExecution/ActionExecutionSagas.ts
app/client/src/sagas/ActionExecution/PluginActionSaga.ts
app/client/src/sagas/ActionExecution/PromiseActionSaga.ts
app/client/src/workers/Actions.test.ts
app/client/src/workers/Actions.ts

Fixes to get promise actions working with backwards compatibility
Fixes: #6975
If any handing for a failure is done, a default message for action execution failure is not shown
Fixes: #4669
// Code coverage diff between base branch:release and head branch: feature/overloadin-action-run 
:red_circle: | total | 54.99 **(-0.01)** | 36.88 **(0)** | 33.88 **(0)** | 55.54 **(-0.01)**
:red_circle: | app/client/src/sagas/ActionExecution/ActionExecutionSagas.ts | 28.75 **(-1.12)** | 2.78 **(-0.08)** | 28.57 **(0)** | 27.63 **(-0.75)**
:green_circle: | app/client/src/sagas/ActionExecution/PluginActionSaga.ts | 18.65 …

fix: Promise action backwards compatibility

---

app/client/src/components/ads/TabItemBackgroundFill.tsx
app/client/src/constants/messages.ts
app/client/src/pages/Editor/gitSync/GitSyncModal.tsx
app/client/src/pages/Editor/gitSync/Menu.tsx
app/client/src/pages/Editor/gitSync/components/TabItem.tsx
app/client/src/pages/Editor/gitSync/constants.ts

This change adds horizontal tabs in gitSync Modal as per the new [design](https://www.figma.com/file/lqtUfzJO50RpEhxKttYeOg/Local-Dev-Main?node-id=1913%3A51585).
Manually in local
// Code coverage diff between base branch:release and head branch: feature/git-sync-ui 
:red_circle: | total | 55.02 **(0)** | 36.9 **(-0.01)** | 33.89 **(0)** | 55.56 **(-0.01)**

feat: Add horizontal tabs in gitSync Modal

---

app/client/src/components/editorComponents/ActionRightPane/index.tsx

- Sniping mode btn on top
- Manual
// Code coverage diff between base branch:release and head branch: feat/liftup-select-widgets-btn 
:green_circle: | total | 55.02 **(0.01)** | 36.89 **(0.01)** | 33.95 **(0)** | 55.57 **(0.01)**

fix: put the connect widget btn (sniping mode) on top

---

app/client/src/entities/Datasource/index.ts
app/client/src/sagas/DatasourcesSagas.ts

Added `success` key in interface `Datasource`.
Fixed missing toast incase of localhost as hostaddress.
Fixes #4488 
- Success toast is now shown incase of localhost
// Code coverage diff between base branch:release and head branch: fix/4488-toast-missing-localhost 
:green_circle: | total | 55.01 **(0)** | 36.92 **(0.01)** | 33.9 **(0)** | 55.56 **(0)**
:red_circle: | app/client/src/sagas/DatasourcesSagas.ts | 12.85 **(-0.08)** | 1.68 **(-0.03)** | 8.33 **(0)** | 15.21 **(-0.12)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.71 …

fix: fixed missing toast

---

app/client/Dockerfile

The env variable APPSMITH_SERVER_PROXY_PASS is missing a default value, and the start script in client image requires this. But since this env variable is not set on any _existing_ installations, they will break. So to fix that, we are adding an initial value to this variable to a sensible default.
// Code coverage diff between base branch:release and head branch: fix/client-image-on-existing-installations 
:green_circle: | total | 54.94 **(0)** | 36.81 **(0.01)** | 33.69 **(0)** | 55.49 **(0.01)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.71 **(0.24)** | 38.6 **(0.88)** | 36.21 …

fix: Include a default value for server proxy pass

---

app/client/yarn.lock
app/server/appsmith-server/src/main/java/com/appsmith/server/constants/ConfigNames.java
app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/UserSignupRequestDTO.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/UserSignup.java

We're not going to be collecting the company name for the self-hosted installation, but instead we'll be collecting the use-case that is being solved with Appsmith.
// Code coverage diff between base branch:release and head branch: chore/rename-user-company-to-usecase 
:red_circle: | total | 55.02 **(0)** | 36.91 **(-0.01)** | 33.91 **(0)** | 55.57 **(0)**

fix: Rename user company to user's useCase

---

app/client/src/comments/AppComments/AppCommentThreads.tsx
app/client/src/comments/inlineComments/Comments.tsx
app/client/src/comments/inlineComments/InlineCommentPin.tsx
app/client/src/comments/inlineComments/UnpublishedCommentThread.tsx
app/client/src/pages/Editor/MainContainerLayoutControl.tsx
app/client/src/pages/Editor/WidgetsEditor.tsx
app/client/src/pages/common/ArtBoard.tsx

Fixes #5100 
* manual
// Code coverage diff between base branch:release and head branch: fix/collab-z-index-issues 
:green_circle: | total | 55.12 **(0.11)** | 37.03 **(0.15)** | 34.04 **(0.09)** | 55.67 **(0.11)**
:sparkles: :new: | **app/client/src/comments/AppComments/AppCommentThreads.tsx** | **65.79** | **31.25** | **40** | **64.86**
:sparkles: :new: | **app/client/src/comments/AppComments/AppCommentsPlaceholder.tsx** | **75** | **100** | **0** | **75**
:sparkles: :new: | **app/client/src/comments/CommentThread/connectedCommentThread.tsx** | **75** | …

fix: comment pins related issues

---

app/client/docker/start-nginx.sh

Currently, in the editor Docker image, if the `APPSMITH_SERVER_PROXY_PASS` env variable is missing or set to empty, then the service will notify the user and refuses to start. This PR will change this behaviour to notify the user with a warning message, but don't refuse to start.

fix: Treat missing server proxy endpoing as a warning

---

app/client/src/widgets/ListWidget/ListPropertyPaneConfig.ts

The current validation is OBJECT_ARRAY due to which data like array of strings, or array of objects don't work in list widget now.
This PR changes the rule to ARRAY.
Fixes #7024 
- Bug fix

fix: change validation rule for data in list widget

---

app/client/yarn.lock

The `yarn.lock` file is currently out-of-sync with the dependencies we are using. So, running `yarn install --frozen-lockfile` fails with the following error:
```
yarn install v1.22.10
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
This PR gets it back in shape.
// Code coverage diff between base branch:release and head branch: sharat87-patch-2 
:red_circle: | total | 55.02 **(0)** | 36.91 **(-0.01)** | 33.91 **(0)** | …

Update lockfile with current dependencies

---

app/client/yarn.lock
app/server/appsmith-plugins/arangoDBPlugin/src/main/java/com/external/plugins/ArangoDBPlugin.java
app/server/appsmith-plugins/arangoDBPlugin/src/test/java/com/external/plugins/ArangoDBPluginTest.java

- ArangoDB has two types of command - one that fetches a response and the other that updates a document. Currently, ArangoDB plugin treats all cmds like the one that returns a response, hence when update cmds are run then an empty response is returned to the client since there is nothing to fetch. This PR adds a check to fetch the response based on the type of cmd. Hence, for an update cmd the number of writes succeeded or failed would be returned as a response. 
- From ArangoDB doc: 
```
An AQL query must either return a result (indicated by usage of the RETURN keyword) or execute a data-modification operation (indicated by usage of one of the keywords INSERT, UPDATE, REPLACE, REMOVE or UPSERT). The AQL parser will return an error if it detects more than one data-modification operation …
```

fix: fix Arangodb plugin response on update commands

---

app/client/src/constants/messages.ts
app/client/src/sagas/SnipingModeSagas.ts

added a check if selected widget even exists
Fixes #7119 
This is extremely rare case, couldn't find a way to reproduce and test.
// Code coverage diff between base branch:release and head branch: fix/sniping-mode-saga-safeguarding 
:red_circle: | total | 55.01 **(0)** | 36.88 **(0)** | 33.94 **(-0.01)** | 55.56 **(0)**
:red_circle: | app/client/src/constants/messages.ts | 70.88 **(-0.03)** | 100 **(0)** | 12.16 **(-0.08)** | 78.55 **(-0.29)**
:red_circle: | app/client/src/sagas/SnipingModeSagas.ts | 17.54 **(0.27)** | 3.45 **(-0.55)** | 40 **(0)** | 18.18 …

fix: safeguarding selected widgets saga

---

app/server/appsmith-plugins/mssqlPlugin/src/main/java/com/external/plugins/MssqlPlugin.java
app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java
app/server/appsmith-plugins/postgresPlugin/src/test/java/com/external/plugins/PostgresPluginTest.java

fix: Use BigDecimal to maintain precision for floating point numbers when using prepared statements

---

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java

Removes unnecessary fields from exported application. `updatedAt`, `lastDeployedAt` and `gitApplicationMetadata` are the fields that were removed from exported application.
Fixes #7196 
- Unit tests

feat: Removed unnecessary fields from exported application

---

app/client/src/notifications/NotificationListItem.tsx

Close notifications list on clicking a list item
- Manually
// Code coverage diff between base branch:release and head branch: close-notifs-on-item-click 
:green_circle: | total | 55.23 **(0)** | 37.21 **(0.01)** | 34.27 **(0)** | 55.79 **(0)**

fix: close notifications list on clicking a list item

---

app/client/src/comments/CommentThread/CommentThread.tsx
app/client/src/components/ads/TextInput.tsx
app/client/src/components/designSystems/appsmith/IconButtonComponent.tsx
app/client/src/components/designSystems/blueprint/ButtonComponent.tsx
app/client/src/components/designSystems/blueprint/InputComponent/index.tsx

This change avoids to passing of parent props to DOM element.
Fixes #7146
- Refactor
- Jest test in local
// Code coverage diff between base branch:release and head branch: fix/avoid_props_passing_DOM 
:green_circle: | total | 55.23 **(0.01)** | 37.21 **(0.01)** | 34.26 **(0)** | 55.79 **(0)**
:green_circle: | app/client/src/components/ads/TextInput.tsx | 73.17 **(0.67)** | 44.9 **(0)** | 85.71 **(0)** | 71.43 **(0.76)**
:red_circle: | app/client/src/components/designSystems/appsmith/IconButtonComponent.tsx | 48.84 **(0.06)** | 7.84 **(0)** | 20 **(-2.22)** | 61.76 **(1.15)** …

fix: omit props passing to DOM element

---

app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java
app/server/appsmith-plugins/postgresPlugin/src/test/java/com/external/plugins/PostgresPluginTest.java

> Due to the constraint to fetch schemas which are present in the search path for postgres table query, in most of the cases only public schemas were getting fetched which is present in the search path by default. This PR will remove the constraint to fetch all the schemas and the related tables within the DB.  
Fixes #7120 
- Tested manually with local DB

fix: Fetch all the schemas present in the postgres DB 

---

app/client/src/sagas/CommentSagas/index.ts

try making create new thread transition better:
we used to remove the unpublished thread before rendering the newly created thread
removing it later makes the transition better as the pin and the card are not completely removed during the process
- Manually
// Code coverage diff between base branch:release and head branch: try-making-create-new-thread-smoother 
:red_circle: | total | 55.26 **(0)** | 37.23 **(-0.01)** | 34.27 **(0)** | 55.81 **(0)**
:red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.47 **(-0.24)** | 38.26 **(-0.87)** | 36.21 …

fix: try making create new thread transition better

---

app/client/src/components/designSystems/appsmith/TabsComponent.tsx

Fixes #4747 
Manually
// Code coverage diff between base branch:release and head branch: fix/4747-tabs-widget-height 
:green_circle: | total | 55 **(0.01)** | 36.88 **(0)** | 33.87 **(0.01)** | 55.55 **(0.01)**
:red_circle: | app/client/src/components/designSystems/appsmith/TabsComponent.tsx | 100 **(0)** | 83.33 **(-1.96)** | 100 **(0)** | 100 **(0)**</details>

fix: Tabs widget - full height when showTabs is false

---

app/client/src/components/designSystems/appsmith/CheckboxGroupComponent.tsx
app/client/src/components/designSystems/blueprint/CheckboxComponent.tsx
app/client/src/components/designSystems/blueprint/RateComponent.tsx
app/client/src/constants/Colors.tsx
app/client/src/constants/DefaultTheme.tsx
app/client/src/widgets/CheckboxWidget.tsx

Fixes #3294 
Manual
// Code coverage diff between base branch:release and head branch: feature/3294-widget-disabled-state 
:green_circle: | total | 54.99 **(0)** | 36.88 **(0)** | 33.86 **(0.01)** | 55.54 **(0)**
:red_circle: | app/client/src/components/designSystems/appsmith/CheckboxGroupComponent.tsx | 42.86 **(1.68)** | 13.33 **(-10.2)** | 0 **(0)** | 50 **(0)**
:green_circle: | app/client/src/components/designSystems/blueprint/CheckboxComponent.tsx | 94.44 **(0.32)** | 73.33 **(6.66)** | 80 **(0)** | 93.33 **(0)**
:red_circle: | …

feat: Consistent styling for widgets disabled state

---

app/client/src/widgets/TableWidget/index.tsx

> Added check for Array type value.
Fixes #4952 
// Code coverage diff between base branch:release and head branch: FIX/4952-selectedRowIndices-not-iterable 
:green_circle: | total | 54.94 **(0.01)** | 36.81 **(0.01)** | 33.68 **(0)** | 55.48 **(0)**

fix: checked array before spread

---

app/client/src/widgets/TableWidget/derived.js

Filter columns which does not have an accessor property
Fixes #6968 
// Code coverage diff between base branch:release and head branch: fix/table-crash-column 
:red_circle: | total | 55.01 **(-0.01)** | 36.91 **(-0.01)** | 33.91 **(0.01)** | 55.56 **(-0.01)**
:red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.47 **(-0.24)** | 37.72 **(-0.88)** | 36.21 **(0)** | 55.08 **(-0.27)**
:green_circle: | app/client/src/widgets/TableWidget/derived.js | 54.5 **(0.24)** | 53.57 **(0)** | 39.47 **(1.63)** | 54.07 **(0)**</details>

fix: Filter columns which has a column accessor

---

app/client/src/pages/Editor/QueryEditor/Table.tsx

Issue - Table header text gets truncated due to small column width. 
Solution- Wrap the text in `AutotooltipComponent`.
Fixes #6057 
- Full text in  table header is now displayed in tootip. Tooltip shows up in case of text overflow only.
// Code coverage diff between base branch:release and head branch: fix/6057-add-tooltip-table-header 
:green_circle: | total | 55.23 **(0)** | 37.2 **(-0.01)** | 34.26 **(0.01)** | 55.79 **(0)**
:green_circle: | app/client/src/pages/Editor/GeneratePage/components/CrudInfoModal.tsx | 80.77 **(1.92)** | 89.66 **(0)** | 41.67 …

fix: wrapped header text in AutotooltipComponent

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Debugger/Widget_Error_spec.js
app/client/src/sagas/WidgetOperationSagas.tsx

Previously errors were simply getting removed after widget deletion even after undoing.
Moved widget deletion notifier outside timeout, which removes the errors immediately on delete. When the widgets are added back, there is an eval which then adds the errors back
Fixes #6782 
Cypress test

fix: Undoing delete widget does not restore the errors in the debugger

---

app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
app/client/src/sagas/FormEvaluationSaga.ts

1. The new JSON structure for editor JSON forms has made it easy for new contributors to add plugins. 
2. The changes also remove the issue of always having a strict structure that sections have to be root elements, allowing any element to be present at any level.
3. These changes also add error handling for improper JSON elements.
4. The changes will not be visible until the backend enables them by updating the UIComponentTypes options.
Fixes #7187 
// Code coverage diff between base branch:release and head branch: feature/7187-updating-render-according-to-new-json-structure  …

feat: Updating render according to new json structure

---

app/client/src/pages/Editor/WidgetsEditor.tsx
app/client/src/pages/common/CanvasSelectionArena.tsx
app/client/src/utils/hooks/useAllowEditorDragToSelect.ts

Release v1.5.18
// Code coverage diff between base branch:master and head branch: release-v1.5.18 
:green_circle: | total | 55.25 **(0.02)** | 37.24 **(0.03)** | 34.29 **(0.03)** | 55.82 **(0.03)**
:red_circle: | app/client/src/pages/Editor/WidgetsEditor.tsx | 92.86 **(0.32)** | 73.33 **(-1.67)** | 100 **(0)** | 92.54 **(0.35)**
:green_circle: | app/client/src/selectors/commentsSelectors.ts | 77.88 **(1.92)** | 57.58 **(3.03)** | 68 **(0)** | 85.14 **(2.71)**
:sparkles: :new: | **app/client/src/utils/hooks/useAllowEditorDragToSelect.ts** | **100** | **100** | **100** | **100**</details>

build: Release v1.5.18

---

app/client/src/components/editorComponents/Debugger/LogItem.tsx

App crashes when we try to render an object instead of a string
Manually
// Code coverage diff between base branch:release and head branch: fix/debugger-renders-objects 
:green_circle: | total | 54.27 **(0)** | 36.32 **(0.01)** | 33.43 **(0)** | 54.81 **(0)**
:green_circle: | app/client/src/components/editorComponents/Debugger/LogItem.tsx | 38.33 **(1.04)** | 23.81 **(-1.19)** | 0 **(0)** | 39.29 **(1.11)**

fix: convert message to string if it is not in debugger

---

app/client/src/constants/WidgetConstants.tsx
app/client/src/mockResponses/WidgetConfigResponse.tsx
app/client/src/utils/WidgetPropsUtils.tsx

> Add migration for removed default selected row in the table.
Fixes #7258
// Code coverage diff between base branch:release and head branch: bug/revert-table-row-migration 
:green_circle: | total | 54.29 **(0.02)** | 36.34 **(0.02)** | 33.45 **(0.02)** | 54.83 **(0.02)**
:green_circle: | app/client/src/utils/WidgetPropsUtils.tsx | 75.89 **(0.3)** | 66.91 **(0.24)** | 71.72 **(0.59)** | 75 **(0.33)**</details>

fix: add migration for removed table default selected row

---

app/server/docker-compose.yml

A lot of the front end folks are facing failures because of unmet expectations between release-client and prod-server. We should use the release image for development.

fix: Switched image to latest release image to avoid breaks while developing

---

app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/FirestorePlugin.java
app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java

The problem was that the pagination was designed & tested with only 2 pages. Firestore has a different function `limitToLast` which solves for previous page pagination commands.
Fixes #7111
- JUnit

fix: Fixing the previous page pagination for Firestore

---

app/client/src/pages/Editor/QueryEditor/index.tsx

Minor fix to update evals when the query is changed from the query pane. Issue is related to the new UQI changes and won't be visible if the changes from the backend are not made.
Fixes #7370 
// Code coverage diff between base branch:release and head branch: fix/7370-update-evals-on-query-change 
:red_circle: | total | 54.88 **(-0.01)** | 36.85 **(-0.01)** | 34.39 **(0)** | 55.4 **(-0.01)**
:red_circle: | app/client/src/pages/Editor/QueryEditor/index.tsx | 31.37 **(-0.31)** | 9.3 **(0)** | 6.25 **(0)** | 32.98 **(-0.35)**
:red_circle: | …

fix: Calling form eval init on form change

---

app/client/src/components/editorComponents/GlobalSearch/SnippetsDescription.tsx

Now {{ }} is a part of the snippet and needs to be removed before evaluation.
Execute snippet only for JS snippets and remove default dynamic binding before execute.
// Code coverage diff between base branch:release and head branch: fix/execute-snippet 
:green_circle: | total | 54.44 **(0)** | 36.26 **(0)** | 33.57 **(0.01)** | 55 **(0)**
:red_circle: | app/client/src/selectors/commentsSelectors.ts | 78.23 **(-1.61)** | 54.41 **(-2.94)** | 70 **(0)** | 84.09 **(-2.27)**
:green_circle: | app/client/src/utils/helpers.tsx | 65.45 **(1.58)** | 41.05 **(3.16)** | …

fix: Snippet execution changes

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/PropertyPane/Draggable_PropertyPane_Widgets_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/PropertyPane/Draggable_PropertyPane_spec.js
app/client/src/pages/Editor/Popper.tsx
app/client/src/pages/Editor/PropertyPane/index.tsx
app/client/src/pages/Editor/utils.ts

Fixes #7154 
Steps to reproduce
1. Add a table
2. Bind any data sources
3. Open filter pane
4. Click the datasource (in the sidebar) that was used in the table (make sure not to close the filter pane while moving to datasource)
5. Select the table in the outgoing widgets section.
6. The property pane should be open and in the `Table Data` try introducing some random error like `api.data` -> `api.datta`
7. The app should crash.
Reason - 
When we moved from step 3 to step 4, the `tableFilterPane` `isVisible` is true and the state remains the same when we move from step 4 to step 5.
Now both table filter pane and property pane are open and the drag handle shares the same id `popper-draghandler`. The filter pane tries to replace its drag handle and the error occurs.
- Bug fix (non-breaking …

fix: allow multiple draggable popper to co-exist

---

app/server/appsmith-server/src/main/java/com/appsmith/server/domains/AbstractCommentDomain.java
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Comment.java
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/CommentThread.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/CommentServiceImpl.java

When a comment is created along with a thread, the comment has no mode set. This change will set the mode of thread to comment.
Fixes #7264 

fix: Set thread mode to comment mode when comments created

---

app/client/src/components/editorComponents/Debugger/DebuggerMessage.tsx
app/client/src/constants/messages.ts
app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx

Update text
Fixes #6969 
Manually
// Code coverage diff between base branch:release and head branch: fix/query-message 
:red_circle: | total | 54.88 **(-0.01)** | 36.85 **(-0.01)** | 34.38 **(-0.02)** | 55.4 **(0)**
:red_circle: | app/client/src/constants/messages.ts | 75.2 **(-0.03)** | 100 **(0)** | 26.08 **(-0.07)** | 81.13 **(-0.12)**
:red_circle: | app/client/src/utils/helpers.tsx | 63.87 **(-1.58)** | 37.89 **(-3.16)** | 45.16 **(-3.23)** | 60.93 **(-1.32)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.71 **(0.24)** | 39.13 …

fix: debug button message shown in query pane

---

app/client/src/sagas/ActionExecution/PromiseActionSaga.ts

We were doing a regex search to figure our callback functions but we should always assume that onSuccess, onError, .then, .catch will be callbacks because that is the correct syntax
Fixes #7322
// Code coverage diff between base branch:release and head branch: fix/anon-func-regex 
:green_circle: | total | 54.88 **(0.01)** | 36.88 **(0.01)** | 34.23 **(0)** | 55.4 **(0.01)**
:red_circle: | app/client/src/sagas/ActionExecution/PromiseActionSaga.ts | 32.56 **(-0.77)** | 0 **(0)** | 33.33 **(0)** | 27.78 **(-1.17)** …

fix: always assume onSuccess, onError, .then, .catch to be callbacks

---

app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ActionController.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/LayoutActionService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/LayoutActionServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutActionServiceTest.java

- Currently, the list of actions to be run on page load is not updated when an action object gets deleted. Hence, sometimes, a previously deleted action may be set to run on page load which throws an error when the application tries to run it on page load. 
- This PR updates the list of actions to be run on page load whenever any action gets deleted. 
Fixes #7345 
- JUnit TC
- Manual

fix: update on page load actions on action delete.

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Debugger/Widget_Error_spec.js
app/client/src/components/editorComponents/Debugger/DebuggerTabs.tsx
app/client/src/reducers/uiReducers/debuggerReducer.ts

Shows recent errors first in the debugger error tab.
Fixes #6715 
cypress test
// Code coverage diff between base branch:release and head branch: fix/recent-error 
:red_circle: | total | 54.87 **(-0.01)** | 36.87 **(-0.01)** | 34.23 **(0)** | 55.39 **(-0.01)**
:red_circle: | app/client/src/reducers/uiReducers/debuggerReducer.ts | 43.75 **(-2.92)** | 0 **(0)** | 14.29 **(0)** | 46.67 **(-3.33)**
:red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.47 **(-0.24)** | 38.26 **(-0.87)** | 36.21 **(0)** | 55.08 **(-0.27)**</details>

fix: Show recent errors first in the debugger error tab

---

app/client/src/actions/jsActionActions.ts
app/client/src/api/JSActionAPI.tsx
app/client/src/sagas/JSActionSagas.ts
app/client/src/sagas/JSPaneSagas.ts

create default js action and global variable inside js object
// Code coverage diff between base branch:release and head branch: default-create-js-action 
:red_circle: | total | 54.87 **(0)** | 36.88 **(0)** | 34.23 **(-0.01)** | 55.4 **(0)**
:red_circle: | app/client/src/api/JSActionAPI.tsx | 60 **(-0.87)** | 100 **(0)** | 10 **(-1.11)** | 58.33 **(-0.76)**
:green_circle: | app/client/src/sagas/JSPaneSagas.ts | 20.26 **(0)** | 1.54 **(0.02)** | 7.69 **(0)** | 24.41 **(0)**</details>

feat: create js action default with js collection

---

app/server/appsmith-plugins/googleSheetsPlugin/src/main/resources/editor.json
app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java

fix: Add migrations for all google sheet actions to turn off smart substitution for existing actions

---

app/client/src/pages/Editor/PropertyPaneHelpButton.tsx

Fixes the default search text linked from the property pane's help button, for widgets.
Fixes #7522 
Manually (This would ideally need a cypress test #7528) 
// Code coverage diff between base branch:release and head branch: fix/widget-help-link 
:green_circle: | total | 54.9 **(0.01)** | 36.73 **(0.02)** | 34.22 **(0.01)** | 55.44 **(0.02)**
:red_circle: | app/client/src/pages/Editor/PropertyPaneHelpButton.tsx | 85 **(0)** | 66.67 **(-8.33)** | 50 **(0)** | 84.21 **(0)**
:green_circle: | app/client/src/selectors/commentsSelectors.ts | 79.84 **(1.61)** | 57.35 …

chore: widget help links from the property pane

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Input_spec.js

There was another issue with input spec but the failure was seen in CI alone.
I have updated that part

test: fixing the Cypress test for input spec

---

app/client/src/widgets/MultiSelectWidget/widget/index.tsx

only run onFilterUpdate when it's defined
Fixes #7512
// Code coverage diff between base branch:release and head branch: fix/multiselect-onFilterUpdate 
:green_circle: | total | 54.89 **(0)** | 36.71 **(0.01)** | 34.21 **(0)** | 55.42 **(0)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.71 **(0.24)** | 39.13 **(0.87)** | 36.21 **(0)** | 55.35 **(0.27)**
:red_circle: | app/client/src/widgets/MultiSelectWidget/widget/index.tsx | 48.98 **(-1.02)** | 0 **(0)** | 50 **(0)** | 50 **(-1.11)**</details>

fix: only run onFilterUpdate when it's defined

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java

Adds `modifiedBy` field to application when an user create, duplicate, clone or import an application. This field is required by UI to show last who last updated an application in the new home page.
Fixes #7451 
- Unit tests

feat: set `modifiedBy` during create, clone, fork, import app

---

app/server/appsmith-plugins/mongoPlugin/src/main/resources/editor/aggregate.json
app/server/appsmith-plugins/mongoPlugin/src/main/resources/editor/count.json
app/server/appsmith-plugins/mongoPlugin/src/main/resources/editor/delete.json
app/server/appsmith-plugins/mongoPlugin/src/main/resources/editor/distinct.json
app/server/appsmith-plugins/mongoPlugin/src/main/resources/editor/find.json
app/server/appsmith-plugins/mongoPlugin/src/main/resources/editor/insert.json
app/server/appsmith-plugins/mongoPlugin/src/main/resources/editor/update.json

Adding input type to BSON fields to ensure future client side validations can be added to these fields

feat: Adding input type to BSON fields in Mongo Plugin

---

app/client/src/components/editorComponents/Debugger/ContextualMenu.tsx
app/client/src/components/editorComponents/Debugger/DebugCTA.tsx
app/client/src/components/editorComponents/Debugger/LogItem.tsx
app/client/src/components/editorComponents/Debugger/helpers.tsx
app/client/src/constants/DefaultTheme.tsx

Using popover2 as it fixes the issue where clicking on a popover target doesn't dismiss the tooltip associated with the target.
Moved wand icon color styles to theme.
Fixes #7380
Manually
// Code coverage diff between base branch:release and head branch: fix/minor-debugger-ux 
:red_circle: | total | 54.78 **(-0.01)** | 36.51 **(0.01)** | 33.95 **(-0.03)** | 55.34 **(-0.01)**
:red_circle: | app/client/src/components/editorComponents/Debugger/ContextualMenu.tsx | 44.3 **(-1.03)** | 19.61 **(3.28)** | 10.53 **(-1.97)** | 44.3 **(-1.03)**
:red_circle: | …

chore: minor styling fixes for debugger

---

app/client/src/components/ads/TagInputComponent.tsx

When user filling out email in invite user to org form, pressing tab adds empty value to the list as a result we end up with "invalid email" issue. This commit fixes that issue by not adding empty values to the list.
Fixes: #6785
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: fix/invite-user-email-input 
:red_circle: | …

chore: Invite user to org form input tab issue

---

app/client/gitbook-algolia-lambda.js

GitBook API occasionally throws a 500 when trying to get a page. This makes our whole sync Lambda fail.
This PR adds a retry step, that will wait a second and retry the GitBook API, with retries capped to three, so the Lambda is a little more resilient to random 500s from GitBook API.

ci: Add retries when getting page from GitBook

---

app/client/src/comments/CommentCard/CommentCard.tsx
app/client/src/constants/userConstants.ts
app/client/src/entities/Comments/CommentsInterfaces.ts
app/server/appsmith-server/src/main/java/com/appsmith/server/constants/Constraint.java
app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/AssetController.java
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/AbstractCommentDomain.java
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Comment.java
app/server/appsmith-server/src/main/java/com/appsmith/server/events/UserPhotoChangedEvent.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomCommentRepository.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomCommentRepositoryImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/AssetService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/AssetServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/CommentServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/OrganizationServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserDataService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserDataServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/UserChangedHandler.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/CommentServiceTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/OrganizationServiceTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserDataServiceTest.java

Added the following changes in this PR. They are:
- Set author photo id in comments when new comment is added. Also update the photo id in comments when user changes or deletes their photo
- Resize the photo when user uploads their profile picture
- Display the profile photo in the comment card based on the uploaded asset id. Currently it shows by email address
- Added cache control header so that browser caches the profile pictures
Fixes #5385 
- Unit tests
// Code coverage diff between base branch:release and head branch: feature/set-profile-asset-id-in-comment  …

feat: [Feature] Use photo asset id instead of email address for profile picture in comments

---

app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/MethodConfig.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/resources/editor.json

Generate CRUD page fails since it does not use the `where` condition and defaults it to an empty string. This fix mandates that default to be an empty array.

fix: Default type of where conditions converted to array

---

app/client/src/components/editorComponents/ActionCreator/Fields.tsx
app/client/src/workers/Actions.ts

Update the default value for resetWidget's second argument(reset children) to `true`
Fixes #6859
// Code coverage diff between base branch:release and head branch: fix/reset-children-by-default 
:green_circle: | total | 54.89 **(0)** | 36.72 **(0.01)** | 34.21 **(0)** | 55.43 **(0.01)**
:green_circle: | app/client/src/selectors/commentsSelectors.ts | 79.84 **(1.61)** | 57.35 **(2.94)** | 70 **(0)** | 86.36 **(2.27)**</details>

fix: Reset widget children by default

---

app/client/src/widgets/ListWidget/widget/index.tsx

Rate widget was crashing inside a list widget as it wasn't getting the sanitised value in case of array. This pr ensures it gets the correct value
Fixes #7132
// Code coverage diff between base branch:release and head branch: fix/rate-widget-inside-list-issue-7132 
:red_circle: | total | 54.78 **(-0.01)** | 36.46 **(-0.04)** | 33.98 **(0)** | 55.33 **(-0.02)**
:red_circle: | app/client/src/components/formControls/DynamicInputTextControl.tsx | 96.55 **(1.43)** | 50 **(-16.67)** | …

fix: Rating widget crashing when put inside the list widget

---

app/client/cypress/fixtures/buttonApiDsl.json
app/client/cypress/fixtures/testdata.json
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/Bind_Button_with_API_spec.js
app/client/src/sagas/ActionSagas.ts
app/client/src/sagas/JSActionSagas.ts
app/client/src/sagas/PageSagas.tsx

Widget refactor was not reflected in API pane
Fixes #7627
// Code coverage diff between base branch:release and head branch: fetch-actions-after-update-canvas 
:red_circle: | total | 54.8 **(0)** | 36.55 **(-0.01)** | 33.93 **(0)** | 55.35 **(0)**
:green_circle: | app/client/src/sagas/ActionSagas.ts | 10.88 **(0.03)** | 0.78 **(0)** | 3.7 **(0)** | 13.14 **(0.04)**
:green_circle: | app/client/src/sagas/JSActionSagas.ts | 16.17 **(0.1)** | 2.04 **(0)** | 6.67 **(0)** | 19.12 **(0.14)**
:green_circle: | app/client/src/sagas/PageSagas.tsx | 23.95 **(0.08)** | 5.95 …

fix: widget refactor actions fetch change

---

app/client/src/components/editorComponents/DraggableComponent.tsx
app/client/src/pages/Editor/MainContainer.test.tsx

Fixes #7341 
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: fix/7341-drag-enabled-focused-widget 
:green_circle: | total | 54.95 **(0.07)** | 36.85 **(0.14)** | 34.22 **(0.02)** | 55.48 **(0.06)**
:green_circle: | app/client/src/components/editorComponents/DraggableComponent.tsx | 100 **(0)** | 91.84 **(2.71)** | 100 **(0)** | 100 **(0)** …

fix: Enable dragging of widgets only when focused on

---

app/client/src/widgets/TableWidget/widget/index.tsx

Fix clicking on button in table widget when no action is configured.
Fixes #6892 
// Code coverage diff between base branch:release and head branch: fix/table-button-column-no-action-click 
:red_circle: | app/client/src/widgets/TableWidget/widget/index.tsx | 26.67 **(-0.13)** | 5.9 **(-0.04)** | 26.42 **(0)** | 26.49 **(-0.14)**</details>

fix: Clicking on button in table widget when no action is configured throws error

---

app/client/src/widgets/InputWidget/component/index.tsx

Fix number of digits after decimal points in input widget
Fixes #6317
// Code coverage diff between base branch:release and head branch: fix/decimal-digits-input 
:red_circle: | app/client/src/widgets/InputWidget/component/index.tsx | 58.59 **(-0.47)** | 45.24 **(-0.54)** | 63.41 **(0)** | 57.26 **(-0.46)**</details>

fix: Number of digits after decimal in input widget

---

.github/workflows/test-build-docker-image.yml

Currently, all three services' artifact names are set to `build`. This leads to a single artifact with files from all three services as siblings. This has two problems:
1. If there's an overlap in a filename among the files in build folder of two services, one of them will be overwritten with the other.
2. The same large artifact is downloaded every time we do a `download-artifact`, once for server, once for client, and once for RTS, the same large artifact is downloaded thrice before building the Docker images.
Here's a preview of how the artifact looks like currently. The marked ones are from server and the rest are from client (and RTS as well I think).

ci: Use separate artifacts for separate services

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Replay/Replay_spec.js

// Code coverage diff between base branch:release and head branch: fix/comment-the-drag-cypress-test 
:red_circle: | total | 54.8 **(0)** | 36.6 **(-0.01)** | 33.92 **(0)** | 55.39 **(-0.01)**
:red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.47 **(-0.24)** | 38.26 **(-0.87)** | 36.21 **(0)** | 55.08 **(-0.27)**</details>

chore: comment out the moving widget cypress test

---

.github/workflows/test-build-docker-image.yml

Changes the CI packaging flow from:
- Package irrespective of test failures, if on `master` branch.
- Package only if tests pass, if on `release` branch.
To:
- Package irrespective of test failures, if on `release` branch.
- Package only if tests pass, if on `master` branch.

ci: Package release even if tests fail

---

app/client/src/entities/Datasource/RestAPIForm.ts
app/client/src/entities/Datasource/index.ts
app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
app/client/src/transformers/RestAPIDatasourceFormTransformer.ts
app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ApiKeyAuth.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/ApiKeyAuthentication.java
app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/connections/ApiKeyAuthenticationTest.java
app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java

When API key is used as a header, some endpoints might need to add a prefix to the value of the API key. For instance, Baserow needs the api keys to be prefixed by `Token`.
This fix introduces the field in REST API plugin and defaults it to empty for backward compatibility.
// Code coverage diff between base branch:release and head branch: fix/api-key-header-prefix 
:green_circle: | total | 54.75 **(0)** | 36.55 **(0)** | 33.8 **(0)** | 55.37 **(0.01)**
:red_circle: | app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx | 25 **(-0.4)** | 17.24 **(-0.94)** | 3.13 **(0)** | 27.98 **(-0.5)** …

fix: Changes to introduce header prefix in API key authentication type

---

app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx
app/client/src/components/editorComponents/CodeEditor/index.tsx
app/client/src/components/editorComponents/GlobalSearch/SnippetsDescription.tsx
app/client/src/constants/Layers.tsx

Evaluation popper persist on top of portals when snippets/docs are trigger from it. Fixed evaluation popper z-index. 
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: fix/evaluation_popper_zIndex 
:green_circle: | total | 54.76 **(0.01)** | 36.58 **(0.02)** | 33.8 **(0)** | 55.37 **(0.01)** …

fix: evaluation popper z index

---

.github/workflows/github-release.yml

The GitHub release workflow currently doesn't build the fat container image. This PR adds support for this.

ci: Build and push fat container in release workflow

---

app/client/src/sagas/ActionSagas.ts
app/client/src/sagas/QueryPaneSagas.ts

Bad URL construction was causing the mongo query to crash after move or copy
Fixes #7743 
Manual steps:
Create a mongo query and copy/move it to another page 
// Code coverage diff between base branch:release and head branch: fix/action-config-children-error 
:green_circle: | app/client/src/sagas/QueryPaneSagas.ts | 24.11 **(0.22)** | 11.63 **(0)** | 25 **(0)** | 27.96 **(0.3)**</details>

fix: issue when form crashes after copy or move of mongo query

---

.github/workflows/github-release.yml

The package job needs `prelude` to be declared as a dependency. Otherwise, we don't have access to variables from that job.

ci: The package job needs prelude

---

Dockerfile

Server jar paths are still pointing to old locations in fat container's Dockerfile. This PR fixes this.

ci: Fix server jar paths in fat container image

---

app/server/appsmith-plugins/amazons3Plugin/src/main/resources/editor.json

- Set the default setting for permanent / un-signed url for S3 list action to true. Ref: https://theappsmith.slack.com/archives/C01HXJPFWBC/p1631714575164700
Fixes #7702 
- Manual

feat: Always return permanent url for s3 list action

---

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/annotations/encryption/EncryptionHandler.java
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Organization.java
app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomOrganizationRepository.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomOrganizationRepositoryImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/OrganizationServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/PluginServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/PluginScheduledTask.java
app/server/appsmith-server/src/test/java/com/appsmith/server/configurations/SeedMongoData.java

The default installs were failing for existing organizations because the findAll function was expecting a user context. This fix uses a query without such an expectation.

fix: Fixed installation for multiple plugins into organizations

---

app/client/src/entities/Datasource/index.ts
app/client/src/pages/Editor/Explorer/Datasources/QueryTemplates.tsx

fix: [UQI] Fix for generating action from datasource structure for UQI plugins

---

app/client/src/pages/Editor/EditorHeader.tsx

Header resizes when the app loads for the first time. This PR replaces the skeleton component with a span to fix it.
// Code coverage diff between base branch:release and head branch: fix/header_resize 
:red_circle: | app/client/src/pages/Editor/EditorHeader.tsx | 87.72 **(-0.11)** | 53.19 **(0)** | 70 **(0)** | 87.16 **(-0.11)**</details>

fix: header resizing

---

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java

With SaaS plugins coming in, package names for plugins will not be unique anymore. Multiple plugins will point to the SaaS package, while maintaining separate identities. Further, since we want to support versioning for these plugins, the version should also be included as a unique identifier for the plugin.
I have still included package name for plugin identification in case we need to support deep integrations as a separate route for plugins to take (alternative to light weight SaaS).

fix: Modified unique index for plugin collection

---

app/client/src/widgets/InputWidget/index.ts
app/client/src/widgets/InputWidget/widget/index.tsx

Tweak how input fields validations for require, not required fields are handled when they are empty.
Fixes #6857
- Bug fix (non-breaking change which fixes an issue) 
// Code coverage diff between base branch:release and head branch: fix/inconsistent-validations-input-widget 
:red_circle: | total | 54.89 **(0)** | 37.04 **(-0.01)** | 33.88 **(0)** | 55.5 **(0)**
:red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.47 **(-0.24)** | 38.26 **(-0.87)** | 36.21 **(0)** | 55.08 **(-0.27)**</details>

fix: Tweak how we show errors for required and not required inputs

---

app/client/src/pages/Editor/RealtimeAppEditors.tsx
app/client/src/sagas/WebsocketSagas/WebsocketSagas.ts

Logging the error to sentry
- manual
// Code coverage diff between base branch:release and head branch: fix/handle-socket-exception 
:red_circle: | total | 54.89 **(-0.01)** | 37.04 **(-0.03)** | 33.88 **(-0.01)** | 55.5 **(-0.01)**
:red_circle: | app/client/src/pages/Editor/RealtimeAppEditors.tsx | 88.46 **(0)** | 31.25 **(-2.08)** | 62.5 **(0)** | 88.46 **(0)**
:green_circle: | app/client/src/sagas/WebsocketSagas/WebsocketSagas.ts | 18.75 **(0.72)** | 11.76 **(0)** | 13.33 **(0)** | 21.82 **(0.67)**
:red_circle: | …

fix: handle socket exception for write events.

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_PropertyPane_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/FormWidget_spec.js
app/client/src/pages/Editor/PropertyPane/index.tsx

Remove snippet and docs icon from property pane.
// Code coverage diff between base branch:release and head branch: fix/remove_icons_pp 
:red_circle: | total | 54.86 **(-0.03)** | 36.98 **(-0.04)** | 33.87 **(-0.01)** | 55.46 **(-0.04)**
:red_circle: | app/client/src/components/ads/Icon.tsx | 54.69 **(-0.65)** | 37.21 **(-0.77)** | 100 **(0)** | 54.55 **(-0.64)**
:red_circle: | app/client/src/components/ads/SnippetButton.tsx | 75 **(-18.75)** | 33.33 **(-50)** | 0 **(-50)** | 75 **(-18.75)**
:red_circle: | app/client/src/pages/Editor/PropertyPane/index.tsx | …

fix: Remove snippet and doc icon from property pane

---

deploy/aws_ami/first-time-setup.sh

- Due to the change in the docker.env.sh template, it cause an issue in the AMI init script
- This fix is about putting correct arguments when generating docker.env from docker.env.sh file in the init script
- Fail to run Appsmith using AMI from AWS Marketplace
- This fix had been tested on EC2 instance which we launch using new AMI

Fix mismatch arguments in AMI init script

---

app/client/package.json
app/client/yarn.lock

package upgrade from v4.0.0 to v4.2.0
Fixes #7710 
- already have automated test
// Code coverage diff between base branch:release and head branch: fix/socket-io-client-package-upgrade 
:green_circle: | total | 54.86 **(0)** | 37 **(0.01)** | 33.86 **(0)** | 55.49 **(0.01)**

fix: upgraded socket.io client package to latest stable version

---

app/client/src/components/editorComponents/JSResponseView.tsx

In response tab on js editor page could not scroll to see all functions 
// Code coverage diff between base branch:release and head branch: thin-scroll-response-tab-js 
:red_circle: | total | 54.86 **(-0.01)** | 36.99 **(-0.02)** | 33.86 **(0)** | 55.49 **(0)**
:green_circle: | app/client/src/components/editorComponents/JSResponseView.tsx | 44.59 **(0.75)** | 20.78 **(0)** | 0 **(0)** | 47.14 **(0.76)**
:red_circle: | app/client/src/selectors/commentsSelectors.ts | 78.23 **(-1.61)** | 54.41 **(-2.94)** | 70 **(0)** | 84.09 **(-2.27)**
:red_circle: | …

fix: scroll for response tab list of functions

---

app/client/src/pages/Editor/GeneratePage/components/GeneratePageForm/GeneratePageForm.tsx

Hide signposting progress bar once user has completed the signposting and immediately generates a page.
Fixes: #7660
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: fix/hide-progress-bar-signposting 
:red_circle: | app/client/src/pages/Editor/GeneratePage/components/GeneratePageForm/GeneratePageForm.tsx …

chore: Signposting progress should be hidden when user generates a page

---

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomNewActionRepository.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomNewActionRepositoryImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java

Fixes #4609.
Testing:
1. Create new organization, called `org1`.
2. Create an application in this, called `app1`.
3. Create a datasource called `ds1`, and an action for that datasource, in `app1`.
4. Now create another application in `org1`, called `app2`.
5. Now delete the application `app1`.
6. Go to `app2`, try to delete the datasource `ds1`.
- Before this PR: The deletion is not allowed because there's one action currently using it.
- After this PR: The deletion is successful because that other action is deleted when `app1` is deleted.

fix: Actions not being deleted when app is deleted

---

app/client/src/pages/Editor/ToggleModeButton.tsx

Removed the toggle button
Fixes #7884 
- manual
// Code coverage diff between base branch:release and head branch: fix/remove-comment-toggle-option-for-public-apps 
:red_circle: | app/client/src/pages/Editor/ToggleModeButton.tsx | 80 **(0.14)** | 54.41 **(-0.97)** | 80 **(0)** | 79.7 **(0.15)**</details>

fix: hide comments mode toggle for anonymous users

---

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java

> This PR fixes the action response display issue for the imported application, when we run the action from SQL datasource instead of tabluar format we used to see the response in JSON format. 
Fixes #6228
> JUnit TC update
> Manual test

fix: Display for action response for imported app with SQL datasource

---

app/client/src/widgets/TableWidget/component/TableUtilities.tsx
app/client/src/widgets/TableWidget/widget/index.tsx

makes the click event on the button propagate to the row so that the event handler for the row gets triggered.
Fixes #7838 
tested manually.
// Code coverage diff between base branch:release and head branch: fix/table-widget-button-issue 
:red_circle: | total | 54.83 **(0)** | 36.98 **(0)** | 33.81 **(-0.01)** | 55.44 **(-0.01)**
:green_circle: | app/client/src/selectors/commentsSelectors.ts | 79.84 **(1.61)** | 57.35 **(2.94)** | 70 **(0)** | 86.36 **(2.27)**
:red_circle: | app/client/src/widgets/TableWidget/component/TableUtilities.tsx | 40.56 **(-0.57)** | …

fix: make the row click event trigger when table button is clicked

---

app/client/src/actions/jsPaneActions.ts
app/client/src/api/ActionAPI.tsx
app/client/src/sagas/JSPaneSagas.ts

Send collection Name instead of collection id for refactor js collection's action
// Code coverage diff between base branch:release and head branch: refactor-js-action-change 
:green_circle: | total | 54.82 **(0)** | 36.97 **(0.01)** | 33.8 **(0)** | 55.43 **(0)**
:green_circle: | app/client/src/sagas/JSPaneSagas.ts | 18.9 **(0)** | 1.59 **(0.05)** | 7.14 **(0)** | 22.14 **(0)**</details>

fix: sending collectionName instead id in refactor

---

app/client/src/sagas/EvaluationsSaga.ts
app/client/src/workers/evaluation.worker.ts
app/client/src/workers/evaluationUtils.ts

During parsing js object we are getting only linting and parsing errors which are set in evalTree. Because sending these errors(errorType: LINT/PARSE) to errorHandler, errorHandler is posting it to Sentry.
Part of 6872
// Code coverage diff between base branch:release and head branch: stop-sentry-js-editor-errors 
:red_circle: | total | 54.82 **(0)** | 36.96 **(-0.01)** | 33.8 **(0)** | 55.43 **(-0.01)**
:red_circle: | app/client/src/selectors/commentsSelectors.ts | 78.23 **(-1.61)** | 54.41 **(-2.94)** | 70 **(0)** | 84.09 **(-2.27)**</details>

fix: Don't send LINT and Parse errors to Sentry

---

app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomActionCollectionRepository.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomActionCollectionRepositoryImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ActionCollectionService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ActionCollectionServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java

Fixes an issue with import/export that retained deleted collections. Root cause was that action collections were not getting deleted on deleting pages

fix: Delete action collections on deleting page

---

app/client/src/components/editorComponents/ActionCreator/index.tsx
app/client/src/pages/Editor/EditorAppName/NavigationMenuData.ts

1. Automatically deciding, whether to show active tab or new tab on datasource page
2. Only admin users will be able to see the export menu for app in edit mode
- manual
// Code coverage diff between base branch:release and head branch: fix/property-pane-redirection-issue 
:green_circle: | total | 54.81 **(0)** | 36.95 **(0.01)** | 33.8 **(0)** | 55.43 **(0.01)**
:green_circle: | app/client/src/pages/Editor/EditorAppName/NavigationMenuData.ts | 65.12 **(3.58)** | 40 **(30)** | 8.33 **(0)** | 64.29 **(3.76)**</details>

fix: small utility fixes for redirection to datasource and export app permissions

---

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java

This migration is loading all non-deleted action documents in their full glory into memory, which breaches Java's set memory limit and so throws an OOM.
This PR changes this by loading just two pieces of information from the actions, the `applicationId` and the action's `_id`, since that's all we need for the logic here. This should significantly reduce the memory required for this operation.

fix: Migration to not load full actions into memory

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java

The conversion here was typecasting the object type into JsonNode. However, when populating headers it is also possible for it to be a map, which is not a valid cast. This changes makes the conversion more liberal.

fix: Converting headers safely into jsonnode

---

app/client/src/pages/Editor/SaaSEditor/ActionForm.tsx

Fixes #7843 
Manually
// Code coverage diff between base branch:release and head branch: fix/where-key 
:red_circle: | total | 54.79 **(-0.02)** | 36.91 **(-0.04)** | 33.8 **(0)** | 55.4 **(-0.02)**
:red_circle: | app/client/src/pages/Editor/SaaSEditor/ActionForm.tsx | 20.29 **(-5.2)** | 0 **(0)** | 0 **(0)** | 21.54 **(-5.54)**</details>

fix: missing where key in plugin specified templates

---

.github/workflows/github-release.yml
.github/workflows/test-build-docker-image.yml

This PR introduces buildx into the workflow that builds Docker images to build images for both arm64 as well as amd64 architectures.
Note that only fat container images are build for multi-architecture.
Tested on a separate private repo. Image available at <https://hub.docker.com/layers/shrikantappsmith/appsmith-ce/release/images/sha256-ccee553338f82fff7a260c859ee2eeea27e70b8246c19323be860df37a795c01?context=explore>.
Fixes #4632.
Fixes #5542.

ci: Build ARM and AMD Docker images in CI

---

app/client/src/workers/evaluate.ts

Hotfix for resolution parsing error putting the app in the unrecoverable state
// Code coverage diff between base branch:release and head branch: hotfix/js-action-parsing-error 
:green_circle: | total | 54.79 **(0)** | 36.94 **(0.01)** | 33.81 **(0)** | 55.41 **(0)**
:green_circle: | app/client/src/selectors/commentsSelectors.ts | 79.84 **(1.61)** | 57.35 **(2.94)** | 70 **(0)** | 86.36 **(2.27)**
:red_circle: | app/client/src/workers/evaluate.ts | 89.66 **(-1.04)** | 75 **(-6.82)** | 80 **(0)** | 89.41 **(-1.07)**</details>

fix: js action parsing error resolution

---

app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/CommentController.java

Add API to get unread comment thread count for an application.
Fixes #7974
- Manually

feat: added API to get unread comment thread count in an application

---

app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomCommentRepositoryImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomNotificationRepository.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomNotificationRepositoryImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/NotificationRepository.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/UserChangedHandler.java
app/server/appsmith-server/src/test/java/com/appsmith/server/repositories/CustomNotificationRepositoryImplTest.java

Updates the username in notifications when users update their name. Also includes some refactoring and a tiny bug fix.
Fixes #7286 
- Manually
- Unit test

fix: update user names in notifications when users update their name

---

app/server/appsmith-server/src/main/java/com/appsmith/server/constants/AnalyticsEvents.java
app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/NetworkUtils.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/AnalyticsService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/PingScheduledTask.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/UserSignup.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/UserSignupTest.java

Solves for two things:
1. From the welcome page signup, depending on telemetry being enabled or disabled, we report.
2. When telemetry is changed from welcome page (which, it obviously will), we make the change persistent by writing to the env file.

fix: Effect the telemetry choice in welcome page

---

.github/workflows/test-build-docker-image.yml

Currently, we use the same Segment key for nightly and release images. This PR will change this to use a different release-only key for release images.

ci: Use separate Segment Key for release

---

app/client/src/widgets/MapWidget/widget/index.tsx

Removes the required field for initialLocation of MapWidget.
Related to https://github.com/appsmithorg/appsmith/issues/6787#issuecomment-925613272
Fixes #6787 
Manually

chore: Do not show initialLocation in an error state when field is blank

---

app/client/src/reducers/uiReducers/debuggerReducer.ts

Incorrect action type was used to check for the page switch event. The INIT_CANVAS_LAYOUT is called after renaming entity names as well. Updated the action type being used.
Fixes #7390 
Manually
// Code coverage diff between base branch:release and head branch: fix/debugger-not-having-error 
:green_circle: | total | 54.81 **(0)** | 36.95 **(0)** | 33.81 **(0.01)** | 55.43 **(0.01)**
:green_circle: | app/client/src/reducers/uiReducers/debuggerReducer.ts | 50 **(5.56)** | 0 **(0)** | 25 **(12.5)** | 52.94 **(5.88)**</details>

fix: Fixes scenario where renaming actions was clearing debugger errors.

---

app/client/src/pages/Applications/index.tsx
app/client/src/sagas/OnboardingSagas.ts
app/client/src/selectors/onboardingSelectors.tsx

Fixes scenario where onboarding was trying to create an application in an organisation where the user had view access only. Also hides welcome tour when no organisation exists to create an application.
~Fixes#7890~(linked by mistake)
Fixes #7980  
Manually
// Code coverage diff between base branch:release and head branch: fix/onboarding-app-viewer 
:red_circle: | total | 54.81 **(0)** | 36.94 **(-0.01)** | 33.8 **(0)** | 55.42 **(0)**
:red_circle: | app/client/src/sagas/OnboardingSagas.ts | 17.01 **(-0.21)** | 1.33 **(0)** | 11.11 **(0)** | 17.37 **(-0.24)** …

fix: Fixes scenario where onboarding was trying to create an app in an organisation with view access

---

README.md

Update the tutorials link on the readme
Fixes #8118 
Changed the link for tutorials in readme from https://github.com/appsmithorg/appsmith/tree/update/readme#tutorials to https://docs.appsmith.com/tutorials

docs: Update tutorials link on readme

---

app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ApplicationForkingServiceTests.java

> For forking the template applications we need to allow users with `READ_APPLICATIONS`. To avoid the updating the ACL permission adding a TC with this PR.  
Fixes #8078
- Improve TC coverage
- JUnit TCs

chore: Update TCs to check fork app is possible for user with VIEW permission

---

app/client/src/sagas/FormEvaluationSaga.ts

We are facing an issue when the editor and settings config is showing as undefined before evaluations start. To prevent this, added the check. The root cause for the configs being undefined is still not found.
Fixes #7605 
// Code coverage diff between base branch:release and head branch: fix/7605-check-config-befor-evaluations 
:red_circle: | total | 54.81 **(0)** | 36.93 **(-0.02)** | 33.8 **(0)** | 55.42 **(0)**
:red_circle: | app/client/src/sagas/FormEvaluationSaga.ts | 22.54 **(-0.65)** | 11.9 **(-3.73)** | 25 **(0)** | 25.4 **(-0.83)**</details>

fix: Added checks to ensure that the configs are valid before starting eval

---

app/client/src/reducers/evaluationReducers/formEvaluationReducer.ts
app/client/src/sagas/FormEvaluationSaga.ts

During page change, the `FETCH_INIT_PAGE` call was resetting the state due to the implementation. Have made it conditional to only set it for the first time app loads. Also, subsequent evaluation runs are now stopped if the current action id is not present or the state is empty.
Fixes #8055 
// Code coverage diff between base branch:release and head branch: fix/8055-prevent-state-reset-on-page-change 
:green_circle: | total | 54.85 **(0)** | 36.9 **(0.01)** | 33.93 **(0)** | 55.45 **(0)**
:red_circle: | …

fix: Preventing evaluations reset on page change unless it is the first load

---

app/client/src/actions/appCollabActions.ts
app/client/src/comments/ConcurrentPageEditorToast.tsx
app/client/src/pages/Editor/index.tsx
app/rts/src/server.ts

Fixes an issue in RTS - when someone leaves editing a page, it broadcast the list of users to others
- Manually
// Code coverage diff between base branch:release and head branch: fix/nothify-after-leave-page 
:green_circle: | total | 54.86 **(0)** | 36.89 **(0.01)** | 33.93 **(0)** | 55.46 **(0.01)**
:green_circle: | app/client/src/selectors/commentsSelectors.ts | 79.84 **(1.61)** | 57.35 **(2.94)** | 70 **(0)** | …

fix: send list of users to others when someone leaves the page edit

---

app/client/src/comments/ConcurrentPageEditorToast.tsx
app/client/src/components/editorComponents/Debugger/index.tsx
app/client/src/pages/Editor/gitSync/QuickGitActions/index.tsx

- update spacings: git connect placeholder icon margin, toast dismiss btn top margin
- debugger error badge padding/font-size
- Manually
// Code coverage diff between base branch:release and head branch: minor-ui-changes 
:green_circle: | total | 54.81 **(0)** | 36.83 **(0)** | 33.9 **(0.01)** | 55.41 **(0)**
:green_circle: | app/client/src/pages/Editor/gitSync/QuickGitActions/index.tsx | 72.73 **(0.51)** | 55 **(0)** | 41.18 **(3.68)** | 74.07 **(0.49)**</details>

fix: update spacings and debugger error badge padding/font-size

---

app/client/src/comments/ConcurrentPageEditorToast.tsx
app/client/src/components/ads/DialogComponent.tsx
app/client/src/components/ads/Tabs.tsx
app/client/src/components/designSystems/appsmith/help/DocumentationSearch.tsx
app/client/src/components/editorComponents/ActionRightPane/index.tsx
app/client/src/components/editorComponents/Debugger/LogItem.tsx
app/client/src/components/editorComponents/Debugger/index.tsx
app/client/src/components/editorComponents/Onboarding/EndTour.tsx
app/client/src/pages/AppViewer/index.tsx
app/client/src/pages/Applications/index.tsx
app/client/src/pages/Editor/Explorer/Entity/index.tsx
app/client/src/pages/Editor/Explorer/JSDependencies.tsx
app/client/src/pages/Editor/HelpButton.tsx
app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
app/client/src/pages/Editor/gitSync/QuickGitActions/index.tsx
app/client/src/pages/common/ProfileDropdown.tsx

This PR includes following fixes.
- Home page top padding to be reduced
-  JS Objects has a double line
-  Double line in query page
-  Double line debugger and api
-  Widget suggestions drop down icon is still too small
-  Dependencies tooltip is still old style
-  Documentation is still not centred vertically in the query
-  Clicking at the end of the page or any entity in the EE does not switch / fold it. Click are needs to be full width
-  The selected state of the query is not the same as the selected state of the widget
-  App view page sides should not be white
-  End tour button in welcome tour flow is greyed out
-  Extra padding after modal header
Fixes #8179 
<details><summary>:white_circle: Total coverage has …

fix: Appsmith design system style fixes

---

app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx

Falsy evaluated value would fail the if check and not render the copy button
fixes #7646
// Code coverage diff between base branch:release and head branch: fix/evaluated-value-bug 
:green_circle: | total | 54.82 **(0)** | 36.82 **(-0.01)** | 33.9 **(0.01)** | 55.41 **(0)**
:green_circle: | app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx | 65.87 **(0.79)** | 57.5 **(1.25)** | 38.89 **(2.78)** | 66.36 **(0.91)**
:red_circle: | app/client/src/selectors/commentsSelectors.ts | 78.23 **(-1.61)** | 54.41 **(-2.94)** | 70 **(0)** | 84.09 **(-2.27)**</details>

fix: Bug in evaluated value for falsy value checks

---

app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/MockDataServiceImpl.java

Fixes #8189 
The issue here was that the endpoint was returning a 502 with text/html content type from nginx itself. Instead of forcing conversion, this fix handles conversions only for 2xx status codes and errors out otherwise.

fix: Added graceful check for failure in mock data endpoint

---

app/client/src/components/editorComponents/Sidebar.tsx

show canvas when user selects widgets tab during signposting flow
Fixes #8203 
Manual
// Code coverage diff between base branch:release and head branch: fix/signposting-widget-step 
:green_circle: | total | 54.83 **(0.01)** | 36.85 **(0)** | 33.89 **(0)** | 55.42 **(0)**
:red_circle: | app/client/src/components/editorComponents/Sidebar.tsx | 88.68 **(-3.16)** | 64.71 **(-8.62)** | 70 **(0)** | 90 **(-3.48)**
:green_circle: | app/client/src/selectors/commentsSelectors.ts | 79.84 **(1.61)** | 57.35 **(2.94)** | 70 **(0)** | 86.36 **(2.27)**</details>

chore: show canvas when user selects widgets tab during signposting flow

---

app/client/src/widgets/SingleSelectTreeWidget/index.ts

Changed the ```SingleSelectTree``` displaying on canvas to ```TreeSelect``` ,
https://github.com/appsmithorg/appsmith/blob/a7a559cc62b302a860e52695a122bef2f9372f00/app/client/src/widgets/SingleSelectTreeWidget/index.ts#L31
Fixes #7990 
- Test A
- Test B

fix: [Bug] The name of the Widget is 'TreeSelect' in Widget Pane and 'SingleSelectTree' in the canvas

---

app/server/appsmith-server/src/main/java/com/appsmith/server/acl/PolicyGenerator.java
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/AbstractCommentDomain.java
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/CommentMode.java
app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/CommentThreadFilterDTO.java
app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/PolicyUtils.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseAppsmithRepositoryImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomCommentThreadRepository.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomCommentThreadRepositoryImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/CommentServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/repositories/CustomCommentThreadRepositoryImplTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationPageServiceTest.java

When a page is deleted, the comment threads in that page should also be deleted and should not appear to user. 
The Edit mode comments should not be visible to app viewers.
Fixes #7830
- JUnit tests
- Manually

fix: [Bugfix] Delete comments when unpublished page is deleted

---

app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Application.java
app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/PageDTO.java
app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/TextUtils.java
app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewPageServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/TextUtilsTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/PageServiceTest.java

Generates and stores a slug from application name and page names when they are created or updated. Also adds a migration to set slug to existing applications and pages.
Fixes #8638
- JUnit tests
- Manually

feat: [Feature] Add slug for applications and pages

---

app/client/src/configs/index.ts
app/client/src/utils/AppsmithUtils.tsx

To Integrate Smartlook and Sentry, we need to expose Sentry object globally according to [this article](https://help.smartlook.com/en/articles/3244594-sentry) from Sentry.
// Code coverage diff between base branch:release and head branch: chore/expose-sentry-object 
:red_circle: | app/client/src/utils/AppsmithUtils.tsx | 56.12 **(-0.29)** | 34.09 **(0)** | 34.88 **(0)** | 51.19 **(-0.31)**</details>

chore: Expose Sentry object globally

---

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/EnvManager.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/EnvManagerTest.java

Adds an API for super user to test the email configuration by sending a test email to himself.
Fixes #8840 
- Unit tests
- Manually

feat: [Feature] Add API to send test email

---

app/client/src/sagas/WidgetDeletionSagas.ts
app/client/src/sagas/WidgetOperationUtils.test.ts
app/client/src/sagas/WidgetOperationUtils.ts

Fixes #8862 
- Bug fix
- Added jest test
// Code coverage diff between base branch:release and head branch: fix/list-widget-trigger-path-bug 
:green_circle: | total | 54.84 **(0.03)** | 36.59 **(0.05)** | 33.48 **(0.03)** | 55.37 **(0.02)**
:green_circle: | app/client/src/sagas/WidgetDeletionSagas.ts | 40.94 **(2.43)** | 25 **(4.76)** | 42.11 **(4.01)** | 42.42 **(2.56)**
:green_circle: | app/client/src/sagas/WidgetEnhancementHelpers.ts | 38.36 **(1.37)** | 27.45 **(1.96)** | 14.29 **(0)** | 40.91 **(1.52)**
:green_circle: | app/client/src/sagas/WidgetOperationUtils.ts | 60.78 **(1.3)** | 41.94 **(2.97)** | 57.14 …

fix: List Widget shows cyclic dependency error when children widgets with bindings in action are deleted

---

app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/helpers/DataUtils.java
app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/helpers/DataUtilsTest.java

This fix retains support for single uploads as well as adds support for an array of files. This means that existing actions do not have to be migrated and future actions continue to have the option of using an array of files or just a single file.
Fixes #8985 
- Tested manually
- JUnit case

fix: Added support for multiple files in multipart REST

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/WidgetGrouping/WidgetGrouping_spec.js
app/client/src/sagas/WidgetOperationSagas.tsx
app/client/src/sagas/WidgetOperationUtils.ts

While working on #8954, I didn't realise `pasteWidgetSaga` is being used for widget grouping also. That caused this issue.
The issue is fixed and a test is added to avoid regression.
Fixes #9032
Open editor on an incognito window. Make sure you didn't copied any widget.
Try grouping a couple of widgets
// Code coverage diff between base branch:release and head branch: fix/unable-to-group 
:green_circle: | app/client/src/sagas/WidgetOperationSagas.tsx | 53.97 **(0.02)** | 42.7 **(0.54)** | 53.19 **(0)** | 55.56 **(-0.27)**</details>

fix: Unable to group widgets

---

app/client/src/components/ads/Toast.tsx
app/client/src/utils/replayHelpers.tsx

Set max-width for Toast.
Fixes #9049 
Use `showAlert` to create a lengthy message
// Code coverage diff between base branch:release and head branch: fix/toast-lengthy-content 
:red_circle: | total | 54.77 **(0)** | 36.62 **(-0.01)** | 33.48 **(0.01)** | 55.3 **(-0.01)**
:green_circle: | app/client/src/components/ads/Toast.tsx | 77.78 **(0.42)** | 63.64 **(1.14)** | 80.95 **(0.95)** | 77.78 **(0.42)**
:red_circle: | …

fix: set max-width for Toast message

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java

When a public app is edited by someone,`isPublic=false` is set to it even the app is not public. This PR fixes that issue.
Fixes #8999 
Fixes #8894
- Manually
- JUnit tests

fix: app is publicly accessible event if it's not public

---

app/client/cypress/support/commands.js
app/client/src/components/editorComponents/ActionNameEditor.tsx
app/client/src/pages/Editor/DataSourceEditor/FormTitle.tsx
app/client/src/pages/Editor/JSEditor/JSObjectNameEditor.tsx
app/client/src/sagas/PageSagas.tsx
app/client/src/utils/DynamicBindingUtils.ts
app/client/src/utils/helpers.tsx

This PR disallows entity names to be any name already used by extra libraries in Appsmith, such as _ , moment, forge, etc. It accomplishes this by creating a dynamic list of constants based on `accessor`s of `extraLibraries` .
Fixes #8580
Fixes #8881 
Fixes #8460
Fixes #9033 
- Bug fix 
- Test A: Tested manually on my local machine by trying to give a widget a name used by an extra library
- Test B: I also tested manually on my local machine by trying to give an API query a name used by an extra library

fix: Disallows entity name to be any extra library name

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_Widget_Add_button_spec.js
app/client/src/widgets/TableWidget/component/TableUtilities.tsx
app/client/src/widgets/TableWidget/widget/index.tsx

> Added support for disabled flag in icon button table widget
Fixes #8543 
> Tested locally. 

fix: 8543 added disabled flag support in icon button table widget

---

deploy/docker/entrypoint.sh

This awk command finds the following section in the default `redis.conf` file provided by Debian:
```ini
################################ SNAPSHOTTING  ################################
#
#
#
#
#
#
#
```
After this section, it appends `save 60 1` so that Redis writes all data to disk every minute, if there's any changes in that minute.

fix: Fix sessions being cleared after fat container is restarted

---

app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OrganisationTests/ShareAppTests_spec.js
app/client/src/sagas/ApplicationSagas.tsx

Null check was missing,
Fixes #9083 
- Cypress test
// Code coverage diff between base branch:release and head branch: fix/on-404-redirect-appviewer-to-login 
:green_circle: | total | 54.59 **(0.01)** | 36.44 **(0)** | 33.22 **(0)** | 55.11 **(0)**
:red_circle: | app/client/src/sagas/ApplicationSagas.tsx | 14.88 **(0)** | 1.15 **(-0.05)** | 4 **(0)** | 17.73 **(0)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.26 **(0.22)** | 41.25 **(0.83)** | 34.48 **(0)** | 56.22 **(0.26)**</details>

fix: redirect anonymous users to login page if they visit non public app

---

app/client/src/components/formControls/FieldArrayControl.tsx

The old where clause component was overflowing due to changes in the drop-down element. Updated CSS selector to fix this.
Fixes #9144 

fix: Added selector for drop down component, increased width

---

app/client/src/widgets/ListWidget/widget/derived.js

Fixes the failing of s3 crud app on second time on uploading the file
Fixes #9201 
- Bug fix 
// Code coverage diff between base branch:release and head branch: fix/list-widget-s3-crud-issue 
:green_circle: | total | 54.63 **(0)** | 36.35 **(0.01)** | 33.09 **(0)** | 55.15 **(0)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.26 **(0.22)** | 41.25 **(0.83)** | 34.48 **(0)** | 56.22 **(0.26)**
:green_circle: | app/client/src/widgets/ListWidget/widget/derived.js | 68.18 **(0.49)** | 37.5 …

fix: Second time file upload is failing in S3 crud page

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserServiceTest.java

If an user signs up with an email which is not in lowercase, we store it as it is. Instead, we should store the email in lowercase. User should be able to login with case insensitive emails. Also the reset password should work with case insensitive emails.
Fixes #9091 
- Manually
- JUnit tests

fix: [Fix] Set user email to lowercase before creating the user and in reset password

---

deploy/aws_ami/docker-compose.yml

This change will ensure the Appsmith server container and watchtower container will start automatically if the EC2 instance is rebooted.

chore: Let the server start automatically on boot

---

app/client/src/sagas/WidgetSelectionSagas.ts

> fixed cannot read properties of undefined (reading 'type') error occurs when the user groups widget as container and pressing cmd+A 
Fixes #8959
// Code coverage diff between base branch:release and head branch: bug/fixed-widget-selection 
:red_circle: | total | 54.63 **(0)** | 36.35 **(-0.01)** | 33.09 **(0)** | 55.15 **(-0.01)**
:red_circle: | app/client/src/sagas/WidgetSelectionSagas.ts | 90.6 **(-0.68)** | 88.42 **(0.25)** | 100 **(0)** | 89.84 **(-0.79)**
:red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.04 **(-0.22)** | 40.42 **(-0.83)** …

fix: updated condition select widget

---

app/client/src/pages/Editor/QueryEditor/Table.tsx
app/client/src/pages/Editor/__tests__/QueryEditorTable.test.tsx

return invalid data in query Editor causing table to crash
Fixes #6968 
// Code coverage diff between base branch:release and head branch: fix--column-ID-issue-in-Query-Editor 
:green_circle: | total | 54.77 **(0.14)** | 36.76 **(0.43)** | 33.37 **(0.29)** | 55.3 **(0.15)**
:green_circle: | app/client/src/pages/Editor/QueryEditor/Table.tsx | 86.15 **(61.59)** | 46.15 **(37.82)** | 100 **(100)** | 85.71 **(59.78)**
:green_circle: | app/client/src/utils/helpers.tsx | 62.41 **(2.26)** | 31.25 **(0)** | 47.5 **(2.5)** | 60.19 **(2.91)** …

fix: issues with key / column ID in QueryEditor

---

app/client/src/widgets/TableWidget/component/Table.tsx
app/client/src/widgets/TableWidget/index.ts

Hide scrollbar and show only when user hovers over header in Table Widget. Also change default table widget width to hide scrollbars. 
Fixes #9312 
// Code coverage diff between base branch:release and head branch: bug/horizonal-header-scroll 
:red_circle: | total | 55.03 **(-0.01)** | 36.93 **(-0.01)** | 33.76 **(0)** | 55.51 **(-0.01)**

fix: Hide scrollbar in header and show when user hovers over header in Table Widget

---

app/client/src/widgets/RadioGroupWidget/widget/index.tsx

Fixes #9289 
Refer [this comment](https://github.com/appsmithorg/appsmith/issues/9289#issuecomment-976417079) to reproduce the issue

fix: radio group widget crash when one of options becomes null

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ActionExecution/Error_handling_spec.js
app/client/src/sagas/ActionExecution/ActionExecutionSagas.ts
app/client/src/sagas/ActionExecution/PluginActionSaga.ts
app/client/src/sagas/ActionExecution/errorUtils.ts

Don't show platform Action errors when a error callback is configured
// Code coverage diff between base branch:release and head branch: fix/action-error-toasts 
:green_circle: | total | 55.04 **(0)** | 36.94 **(0.01)** | 33.78 **(0)** | 55.52 **(0)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.26 **(0.22)** | 41.25 **(0.83)** | 34.48 **(0)** | 56.22 **(0.26)**</details>

fix: Mute action execution errors when error callback is present

---

app/client/src/sagas/ActionExecution/PromiseActionSaga.ts

Added a logging action for a promisified trigger instead of throwing an error. 
Fixes #9258 
Steps To Reproduce
1. Create a Text Field and a button.
2. Call multiple API actions using JS on Click functionality on the button. Make sure one of them throws an error.
3. Add the response data of each API actions to the Text Field.
4. Notice when the button is clicked, now the text field does not go into infinite loading state when one of the API throws an error which was used to be the previous thing.
// Code coverage diff between base branch:release and head branch: fix/promise-errors  …

fix(promise-errors): Correcting the throwing error to logging error for promisified triggers

---

app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/MethodConfig.java
app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/MethodConfigTest.java
app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/plugins/GoogleSheetsPluginTest.java

> Google sheets plugin: Row limit does not parse properly
>When We give a space or enter in the input where an Integer is expected, it is throwing error. 
Fixes #8196
> By adding a trim() where an integer value is expected, this error is handle
>This fix resolves 5 input fields, and also handles enter keys before and after values
- Unit Test has been added for this issue
Use google sheet get query
-While defining the row limit add an additional new line after input value - Error was found and fixed now
-While defining the row limit add an additional new line before input value- Error was found and fixed now
-While defining the row limit add a space before input value- Error was found and fixed now
-While defining the row limit add a …

fix: Google Sheet Plugin Numeric inputs Whitespace issue.

---

app/client/src/components/ads/TreeDropdown.tsx

Sets the `line-height` of menu item from `17px` to `19px` so that letters such as "g" won't be truncated
Fixes #6548 
In windows OS, set the zoom level to 125% and check the Action selector items
// Code coverage diff between base branch:release and head branch: fix/menu-item-overflow 
:green_circle: | total | 54.63 **(0)** | 36.35 **(0.01)** | 33.09 **(0)** | 55.15 **(0)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.26 **(0.22)** | 41.25 **(0.83)** | 34.48 **(0)** | 56.22 **(0.26)**</details>

fix: MenuItem overflow

---

app/client/src/workers/DataTreeEvaluator.ts

Fixes #9334 #9096 
When we have a SelectWidget named `Select1` on canvas and `createFirstTree` runs, it was noticed that `Select1.defaultValue` is getting evaluated after `Select1.selectedOptionValue` 
This is due to an incorrect sorted dependency map.
Logically, `Select1.selectedOptionValue` is dependent on `defaultValue` but in dependencyMap current there is no such relation.
```
selectedOptionValue: `{{(()=>{const index = _.findIndex(this.options, { value: this.defaultValue }); return this.options[index]?.value; })()}}`
```
But when we see the actual dependencyMap, there is no relation between `selectedOptionValue` and `defaultValue`.
This doesn’t happen onPageLoad because there we also run updateDataTree,
1. In createDataTree’s evaluation itself defaultValue is evaluated and stored in …

fix: Add default props dependency in dependency map

---

app/client/src/components/ads/Toast.tsx
app/client/src/components/ads/common.tsx
app/client/src/sagas/ActionExecution/ShowAlertActionSaga.ts

- This PR makes a change to the list of acceptable styles for alert messages shown to the user when a wrong alert message style is entered.
Fixes #9384 
Manual
// Code coverage diff between base branch:release and head branch: fix/incorrect-toast-type-options 
:green_circle: | total | 55.1 **(0.01)** | 37.02 **(0)** | 33.86 **(0)** | 55.58 **(0)**
:green_circle: | app/client/src/components/ads/common.tsx | 72.55 **(2.98)** | 60 **(6.15)** | 62.5 **(5.36)** | 69.57 **(3.72)**
:red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.04 **(-0.22)** | …

fix: Show correct toast type options in debugger

---

app/server/appsmith-plugins/saasPlugin/src/main/java/com/external/plugins/SaasPlugin.java

Show the message "Unsupported operation" when trying to test SaaS integrations.

fix: Send unsupported message when trying to test SaaS integrations

---

app/client/src/pages/Editor/QueryEditor/Table.tsx

Adding an empty array check before mapping for keys for the query data. An array of keys is being created by looping the data there was no check added if there was empty data being returned for the query.
Fixes #9425 
Steps to reproduce :
1. Go to datasource
2.  Add a Select Query in Postgres Database
3.  Add A query as SELECT * FROM Company WHERE NAME LIKE 'Sh%';
4.  Run the query Or Copy the query from other Datasource and forget to change the Table name Run the query the application breaks
5. Previously it was breaking the application.
// Code coverage diff between base branch:release and head branch: fix/query-keys-map 
Status | File | % Stmts | % Branch | % …

fix(query-keys-map): Adding empty array check for mapping keys

---

app/client/src/widgets/ButtonGroupWidget/component/index.tsx

> add disable mouse pointer when ButtonGroup widget is disabled 
Fixes #9202 

fix: button group cursor in case of disable

---

deploy/helm/values.yaml

In Helm charts' values.yaml file, we are pointing to the slim editor image instead of the fat Appsmith image. This PR fixes this.

fix: Fix Appsmith image name in Helm chart values

---

app/client/cypress/fixtures/user.json
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Auth/Analytics_spec.js
app/client/public/index.html
app/client/src/configs/index.ts
app/client/src/configs/types.ts
app/client/src/constants/userConstants.ts
app/client/src/sagas/userSagas.tsx
app/client/src/utils/AnalyticsUtil.tsx
app/client/src/utils/AppsmithUtils.tsx
app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/UserProfileDTO.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java

// Code coverage diff between base branch:release and head branch: fix/telemetry-from-welcome-page 
:red_circle: | total | 55.15 **(-0.01)** | 37.19 **(0)** | 33.99 **(0)** | 55.66 **(-0.01)**
:green_circle: | app/client/src/configs/index.ts | 95.12 **(-0.53)** | 86.14 **(1.52)** | 100 **(0)** | 97.3 **(-0.32)**
:green_circle: | app/client/src/sagas/userSagas.tsx | 16.17 **(0.15)** | 1.23 **(-0.07)** | 5 **(0)** | 19.39 **(0.12)**
:green_circle: | app/client/src/utils/AnalyticsUtil.tsx | 29.17 **(0)** | 19.05 **(7.94)** | 30.77 **(0)** | 29.35 **(0)**
:red_circle: | app/client/src/utils/AppsmithUtils.tsx | 56.52 …

chore: Send telemetry option in user profile to client

---

app/client/src/utils/AppsmithUtils.tsx

Checks if smartlook, sentry and analytics exist on the `window` object before initing
Fixes #9575
- Manually: this would need smartlook enabled to verify 
// Code coverage diff between base branch:release and head branch: reinit-smartlook-error 
:red_circle: | total | 55.13 **(-0.01)** | 37.16 **(-0.02)** | 33.97 **(0)** | 55.63 **(-0.02)**
:red_circle: | app/client/src/utils/AppsmithUtils.tsx | 55.19 **(-1.33)** | 28.85 …

fix: check if smartlook, sentry and analytics are inited before the init call

---

deploy/docker/scripts/init_ssl_cert.sh
deploy/docker/scripts/run-nginx.sh

- Add logic to check exit code of certbot command
- Assign HTTP template if the exit code of certbot command is greater than 0 (provisioning fail) 

feat: Add flow to generate Nginx HTTP only if provision cert fail

---

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java

Fixing the DB migration to set default install true for SMTP plugin
Fixes: #9653

chore: Making smtp default install true for new all organizations

---

deploy/docker/scripts/run-with-env.sh

This sets the default value for the git root where all the git storage is done.

Set default APPSMITH_GIT_ROOT value in Docker

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/Widgets_Default_data_validation_spec.js
app/client/src/widgets/DropdownWidget/widget/index.test.tsx
app/client/src/widgets/DropdownWidget/widget/index.tsx

Reverts appsmithorg/appsmith#9444
// Code coverage diff between base branch:release and head branch: revert-9444-fix/selectedOptionValue-from-Select-widget 
:red_circle: | total | 55.12 **(0)** | 37.03 **(-0.01)** | 34.01 **(-0.01)** | 55.64 **(0)**
:red_circle: | app/client/src/widgets/DropdownWidget/widget/index.tsx | 72.92 **(-0.41)** | 23.53 **(-19.71)** | 63.64 **(-0.65)** | 72.09 **(-0.64)**</details>

fix: Revert "fix: Select widget Value"

---

app/client/src/utils/JSPaneUtils.tsx
app/client/src/workers/evaluationUtils.ts

After parsing, while updating data tree variables were undefined and to update we compare values by turning it into string. that was failing
Fixes #9730 
// Code coverage diff between base branch:release and head branch: Critical-9730-fix 
:red_circle: | total | 55.12 **(0)** | 37.01 **(-0.01)** | 34.01 **(0)** | 55.64 **(0)**
:red_circle: | …

fix: changed conditions for variables as variables were undefined

---

app/client/src/components/editorComponents/ActionCreator/Fields.test.ts
app/client/src/components/editorComponents/ActionCreator/Fields.tsx

Regex was not working with whitespace characters since we are using `.*`
Replaced it with `[\s\S]*` to include whitespace characters.
Arrow function was not matching when space is there between arrow (`()  =>  {}`) that is also fixed.
Fixes #8169
Tested this manually by providing whitespace characters into the argument fields of action selectors.
// Code coverage diff between base branch:release and head branch: fix/action-selector-issue 
:green_circle: | total | 55.15 **(0.02)** | 37.06 **(0.01)** | 34.04 **(0.02)** | 55.67 **(0.02)** …

fix: Regex to detect function args

---

app/client/src/constants/AppsmithActionConstants/ActionConstants.tsx
app/client/src/workers/DataTreeEvaluator.ts
app/client/src/workers/ast.ts
app/client/src/workers/evaluate.test.ts
app/client/src/workers/evaluate.ts
app/client/src/workers/evaluation.worker.ts
app/client/src/workers/lint.ts
app/client/src/workers/validations.ts

Adds a feature in evaluate to allow defining custom "this" and "global" variables that are not part of the data tree. It can help in defining field / entity level properties that we would not want to exist in the data tree during evaluation
Fixes #6732
- Jest
Test that these variables are available and evaluated
Test that errors are not raised
// Code coverage diff between base branch:release and head branch: fix/this.params-reference-issue 
:green_circle: | total | 55.14 **(0.01)** | 37.07 **(0.02)** …

feat: Add support for custom 'this' and 'global' variables during evaluation

---

app/client/src/components/formControls/WhereClauseControl.tsx
app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx

This resolves the continuous addition of new where clause "AND" fields every time the query is navigated to, from another query or API action.
Fixes #9665.
Manual Testing employed.
// Code coverage diff between base branch:release and head branch: fix/duplicated-and-condition 
:red_circle: | total | 55.12 **(0)** | 37.03 **(-0.01)** | 34.01 **(-0.01)** | 55.64 **(0)**
:red_circle: | app/client/src/components/formControls/WhereClauseControl.tsx | 34.92 **(0.44)** | 40 **(-2.42)** | 0 **(0)** | 34.92 **(0.44)**
:red_circle: | …

fix: fixes duplication of where clause AND-condition fields

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ApiPaneTests/API_Edit_spec.js
app/client/cypress/locators/apiWidgetslocator.json
app/client/src/reducers/entityReducers/actionsReducer.tsx
app/client/src/reducers/uiReducers/apiPaneReducer.ts

The run button status was updating to loading false by clicking on cancel button inside confirmation before running query pop up. So changed the apiPane and action loading to false when the request is cancelled.
Fixes #8457
```
1. go to the query editor
2. click on the setting tab
3. enable Request confirmation before running query toggle
4. now click on run 
5. inside the confirmation pop up click on cancel 
6. Now the run button becomes active but previously it used to be in loading state even if the query editor was changed by switching queries.
```
// Code coverage diff between base branch:release and head branch: fix/run-button-loading 
Status | File | % Stmts | …

fix: Correcting the run button loading state on cancel in API pane

---

app/client/src/pages/Editor/DataSourceEditor/NewActionButton.tsx

When an API was created from the datasource having some headers attached to it, then the created API used to get duplicated headers one from datasource (derived headers) and the other from its own headers. 
Fixes #6278
Steps to reproduce :
1.  Add an API
2.  Save as data source
3.  Add Header in the Datasource
4.  Save the data source
5.  Create an API from the data source observe the header section
6. In the previous version the headers were duplicated but now the datasource headers are present only in the derived headers section.
// Code coverage diff between base branch:release and head branch: fix/multiple-headers-api 
Status | File | % Stmts | % Branch | % …

fix: Correcting the duplication of headers from datasource to newer APIs

---

app/client/src/workers/DataTreeEvaluator.ts

This PR fixes the linting error which occurs when creating the first  tree
Fixes #9676
Fixes #9438
Manual

fix: properly lint triggerfields

---

app/client/src/pages/Editor/Explorer/Entity/Name.tsx
app/client/src/selectors/entitiesSelector.ts

Moving selector logic away from the component to a separate Selector to prevent re-render of 
https://github.com/appsmithorg/appsmith/blob/release/app/client/src/pages/Editor/Explorer/Entity/Name.tsx Component
Fixes #9702 
Performance fix
React profiler and performance profiler
// Code coverage diff between base branch:release and head branch: entity-name-rerender-fix 
:green_circle: | total | 55.12 **(0)** | 37.05 **(0.01)** | 34.02 **(0)** | 55.65 **(0.01)**
:red_circle: | app/client/src/pages/Editor/Explorer/Entity/Name.tsx | 62.35 **(0.28)** | 34.04 **(0)** | 38.46 **(-1.54)** | 61.73 **(0.28)** …

chore: Entity Name re-render fix

---

app/client/src/entities/DataTree/dataTreeJSAction.ts

The replaceAll function was added in ES12, in older browser versions `TypeError: replaceAll is not a function` exception occurs. With the / /g global flag set in the regex, the replace function is does that same thing but with better browser support.
Fixes #9762 
Manual
// Code coverage diff between base branch:release and head branch: fix/replace-all-browser-compatibility 
:red_circle: | total | 55.14 **(0)** | 37.07 **(-0.01)** | 33.96 **(0)** | 55.64 **(0)**
:red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** …

fix: Update replaceAll function for browser support

---

app/client/src/pages/Editor/PagesEditor/PageListItem.tsx

Old page id was getting cached caused failure in deleting pages
Fixes #9717 
Manually tested
// Code coverage diff between base branch:release and head branch: fix/issue-with-page-delete 
:red_circle: | total | 55.14 **(0)** | 37.07 **(-0.01)** | 33.96 **(0)** | 55.64 **(-0.01)**

fix: Issue with deleting page

---

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/constants/FieldName.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/helpers/DataUtils.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/helpers/RequestCaptureFilter.java
app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/helpers/DataUtilsTest.java
app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java
app/server/appsmith-plugins/saasPlugin/src/main/java/com/external/helpers/RequestCaptureFilter.java

This issue was being caused by the form data request body parser trying to create a map out of the input data. However, when the input data contains null keys (as part of the `Property` type), the map creation step was failing.
While adding safe handling, I have also removed the processing of k-v pairs where the key is null. Effectively the APIs will not be using such values at all.
Fixes #9362

fix: Ignore form data elements with null keys

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/AdminSettings/Admin_settings_spec.js
app/client/cypress/locators/AdminsSettingsLocators.json
app/client/cypress/support/commands.js
app/client/src/entities/FeatureFlag.ts
app/client/src/pages/Settings/LeftPane.tsx
app/client/src/pages/Settings/Main.tsx
app/client/src/pages/Settings/Main/Button.test.tsx
app/client/src/pages/Settings/Main/Button.tsx
app/client/src/pages/Settings/Main/Common.tsx
app/client/src/pages/Settings/Main/Group.text.tsx
app/client/src/pages/Settings/Main/Link.test.tsx
app/client/src/pages/Settings/Main/Link.tsx
app/client/src/pages/Settings/Main/Text.test.tsx
app/client/src/pages/Settings/Main/Text.tsx
app/client/src/pages/Settings/Main/TextInput.tsx
app/client/src/pages/Settings/Main/common.test.tsx
app/client/src/pages/Settings/Main/group.tsx
app/client/src/pages/Settings/RestartBanner.tsx
app/client/src/pages/Settings/index.tsx
app/client/src/pages/common/ProfileDropdown.tsx
app/server/appsmith-server/src/main/java/com/appsmith/server/featureflags/FeatureFlagEnum.java
app/server/appsmith-server/src/main/resources/features/init-flags.yml

Moving Admin settings page out of feature flag.
Fixes #9686
Manual
// Code coverage diff between base branch:release and head branch: feat/admin-settings-inauguration 
:green_circle: | total | 55.25 **(0.12)** | 37.13 **(0.08)** | 34.15 **(0.13)** | 55.77 **(0.12)**
:green_circle: | app/client/src/components/ads/Icon.tsx | 52.9 **(0.51)** | 36.2 **(0.62)** | 100 **(0)** | 52.78 **(0.51)**
:sparkles: :new: | **app/client/src/pages/Settings/SettingsConfig.ts** | **68.37** | **25** | **21.05** | **69.47**
:sparkles: :new: | …

feat: Admin settings page to tinker with env variables

---

app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/BulkAppendMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/plugins/GoogleSheetsPlugin.java
app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/BulkAppendMethodTest.java

> When executing a Google sheets Bulk insert rows query, an error is returned if the data array is empty.
Fixes #8924
- Bug fix (non-breaking change which fixes an issue)   
> Tested manually with different inputs of empty data
> JUnit Test implemented

fix: Google sheets Bulk insert of empty array returns an error

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/PluginServiceCEImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/PluginScheduledTaskCEImpl.java

We were only installing plugins to all organizations if the plugin was new. But since the testing process allows plugins to be introduced to the cloud db without default install, we would not ever be installing to existing organizations on the cloud.
This fix adds the same logic to the update plugin flow, with an extra check in place to avoid db updated in case the plugins for that organization have not changed.
- Manually tested for local Saas plugin

fix: Install plugin to existing organizations after approval

---

.github/ISSUE_TEMPLATE/--epic.yaml

docs: add new "documentation" section in epic template

docs: add new "documentation" section in epic template

---

app/client/src/selectors/entitiesSelector.ts

App breaks anytime you try to rename a widget, a page or a jsObject, This PR fixes that
The bug was as a result of an empty array being passed to one of the if else statements which made the wrong conditional block to run.
Fixes #9843
// Code coverage diff between base branch:release and head branch: fix/fix-widget-naming-bug 
:green_circle: | app/client/src/selectors/entitiesSelector.ts | 53.52 **(0)** | 13.13 **(0.63)** | 33.07 **(0)** | 50.81 **(0)**</details>

fix: fixes inability to rename other widgets, jsactions, pages

---

app/client/src/sagas/CommentSagas/index.ts
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CommentServiceCEImpl.java

Removes sentry reporting when application permission check fails during fetching comment threads.
Fixes #9838
- Manually

fix: [Fix] Removed sentry reporting when application not found

---

app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ce/GitControllerCE.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCE.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserDataServiceTest.java

> If the git-profile is not present for user, Appsmith user profile will be used as a fallback value. Also we will be supporting a null values in authorName and authorEmail when for gitProfile when user intends to use globalProfile. This PR introduces a boolean field in gitProfile to use repo specific 
> Junit TC
> Manual testing

fix: Use Appsmith user profile as a fallback git profile

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Applications/UpdateApplication_spec.js
app/client/src/sagas/ApplicationSagas.tsx
app/server/appsmith-plugins/amazons3Plugin/pom.xml
app/server/appsmith-plugins/arangoDBPlugin/pom.xml
app/server/appsmith-plugins/dynamoPlugin/pom.xml
app/server/appsmith-plugins/elasticSearchPlugin/pom.xml
app/server/appsmith-plugins/firestorePlugin/pom.xml
app/server/appsmith-plugins/googleSheetsPlugin/pom.xml
app/server/appsmith-plugins/jsPlugin/pom.xml
app/server/appsmith-plugins/mongoPlugin/pom.xml
app/server/appsmith-plugins/mssqlPlugin/pom.xml
app/server/appsmith-plugins/mysqlPlugin/pom.xml
app/server/appsmith-plugins/pom.xml
app/server/appsmith-plugins/postgresPlugin/pom.xml
app/server/appsmith-plugins/redisPlugin/pom.xml
app/server/appsmith-plugins/redshiftPlugin/pom.xml
app/server/appsmith-plugins/restApiPlugin/pom.xml
app/server/appsmith-plugins/saasPlugin/pom.xml
app/server/appsmith-plugins/smtpPlugin/pom.xml
app/server/appsmith-plugins/snowflakePlugin/pom.xml
app/server/pom.xml

Also making minor edit to not show "Application name updated" toast message. This is a counter-productive toast that is distracting the user
Recently, a CVE has been published which exploits message and JNDI lookups using log4j library. While we had fixed the command line to prevent message lookups immediately after the CVE was published, JNDI lookups is still possible. This fix upgrades the library to patch that fix. 
In order to do this, we have modified the structure of `pom.xml` in the `appsmith-plugins` maven module. Now, we put all common libraries in the `appsmith-plugins` root `pom.xml`. Each plugin then inherits these libraries by defining the root module as their parent. It ensures that we can upgrade the versions of any common libraries in the future via a single location. …

fix: Updating log4j to 2.17.0 to prevent JNDI lookups

---

app/client/src/entities/Datasource/RestAPIForm.ts
app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
app/client/src/transformers/RestAPIDatasourceFormTransformer.ts
app/server/appsmith-interfaces/src/main/java/com/appsmith/external/constants/Authentication.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/OAuth2ClientCredentials.java

> Add support to send arbitrary form values to oAuth server during Datasource authentication.
Fixes #9389
> New feature (non-breaking change which adds functionality)
- Debugged during development and ensured that the Custom Client Parameters are sent to the back-end and is available as a property known as customTokenParameters of oAuth object 
- Also added those value as a property to the bodyInserters for the next level of processing.
- No unit tests implemented at this time
- To be tested with the specific client requirement which requested this feature that is not available at the time of this implementation.

feat: Add support to send arbitrary form values to oAuth server during Datasource authentication

---

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ExamplesOrganizationClonerCEImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ApplicationForkingServiceTests.java

> When the application is forked to destination organization, default resource IDs are not getting updated as per new application   
Fixes #9873
> JUnit TC
> Manual Test

fix: Replace default IDs for forked application with destination resource IDs

---

app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/FirestorePlugin.java
app/server/appsmith-plugins/firestorePlugin/src/main/resources/editor/getCollection.json
app/server/appsmith-plugins/firestorePlugin/src/test/java/com/external/plugins/FirestorePluginTest.java
app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java

- fix cyclic dependency error caused by using Firestore query data in the same query's pagination fields. 
- fix bad migration for firestore UQI. 
Fixes #9871 
- Manual

fix: fix firestore pagination cyclic dependency error

---

app/client/src/pages/Editor/gitSync/components/DeployedKeyUI.tsx

chore: show only ssh key in the deploy key UI section, rm label
- Manually, UI change

chore: show only ssh key in the deploy key UI section, rm label

---

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ExamplesOrganizationClonerCEImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ApplicationForkingServiceTests.java

> Because of the default actionId was missing in layoutOnLoad action inside page layout for the forked application, forked application on page action was not getting executed. This PR assigns the newly created action id as the defaultActionId. 
Fixes #9945 
> Junit TC
> Manual test

fix: Fix for on page load action in forked application

---

deploy/aws_ami/docker-compose.yml
deploy/docker/README.md
deploy/docker/docker-compose.yml
deploy/template/docker-compose.yml.sh

> Updated the docker-compose value to check for updates every hour
was 
command: --interval 300 --label-enable --cleanup
changed to 
command: --schedule "0 0 * ? * *” --label-enable --cleanup
>Update interval changed to hourly
Updated the changes and tested in an ec2 instance
- Test A
- Test B
- [✓ My code follows the style guidelines of this project
- [✓] I have performed a self-review of my own code
- [ ✓ I have commented my code, particularly in hard-to-understand areas
- [ ✓ I have made corresponding changes to the documentation
- [ ✓ My changes generate no new warnings
- [ ✓ I have added tests that prove my fix is effective or that my feature works
- [ ✓ New and existing unit tests pass locally with my changes

chore: Update docker compose file to have update schedule to 1 hour

---

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java

- add another migration for those Firestore actions that could not be migrated. 
- handle ClassCastException via try catch and assigning default empty value. 
- Manual

fix: add work around to handle bad data in Firestore UQI migration

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/filepicker_spec.js
app/client/src/components/editorComponents/CodeEditor/index.tsx
app/client/src/widgets/FilePickerWidgetV2/widget/index.tsx

Fixes #9907
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: fix/filepicker-allowed-files 
Status | File | % Stmts | % …

fix: remove allowed filetype restriction in filepickerwidget

---

app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java

- Add query params from datasource to final URI used for REST API query.
Fixes #9962 
- JUnit TC
- Manual

fix: add query params from datasource to URI

---

app/client/src/pages/UserProfile/General.tsx

The toast shows up like this currently:
This PR fixes it to show just the message, instead of the function turned into a string.
// Code coverage diff between base branch:release and head branch: bug/toast-message-on-reset-password 
:green_circle: | total | 55.22 **(0)** | 37.02 **(0.01)** | 34.07 **(0)** | 55.73 **(0)**

fix: Toast message on reset password

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/NewActionServiceCEImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ExamplesOrganizationClonerTests.java

This change filters out JS actions when fetching actions by page.

fix: Do not return JS actions when fetching page actions

---

app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/AppendMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/BulkAppendMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/BulkUpdateMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/UpdateMethod.java

> Incorrect error handling when incorrect sheet name is used in Google Sheets query
Fixes #9463
> The already generated error from Response is parsed and displayed.
> Earlier as soon as an error is identified generic error message are thrown.

fix: Incorrect error handling when incorrect sheet name is used in Google Sheets query

---

app/client/src/sagas/DatasourcesSagas.ts

This PR fixes undefined data coming from getting datasource rest api form values from redux form, which is causing silent errors when dispatching update replay entity actions.
Fixes #9808.
Manual tests employed.
// Code coverage diff between base branch:release and head branch: fix/update-replay-error 
:green_circle: | total | 55.22 **(0)** | 37.02 **(0.01)** | 34.07 **(0)** | 55.74 **(0.01)**
:red_circle: | app/client/src/sagas/DatasourcesSagas.ts | 13.41 **(-0.05)** | 2.4 **(-0.08)** | 9.09 **(0)** | 15.87 **(-0.06)** …

fix: fixes undefined error coming from datasource rest api form values

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ApplicationPageServiceCEImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ExamplesOrganizationClonerCEImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java

> When a user is trying to duplicate an application, the action collection was getting updated instead of creating a separate resource for the cloned application. This was resulting in a state where both original and duplicated application unable to access the collection. 
Fixes #9372 
> Junit TC
> Manual Test

fix: Fix duplicate action collection getting updated instead of creating a new collection

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ApiPaneTests/API_Edit_spec.js
app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/ApiPaneTests/API_Bugs_Spec.js
app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx
app/client/src/entities/Action/actionProperties.test.ts
app/client/src/entities/Action/actionProperties.ts
app/client/src/entities/Action/index.ts
app/client/src/entities/DataTree/dataTreeAction.ts
app/client/src/entities/DataTree/dataTreeFactory.ts
app/client/src/pages/Editor/APIEditor/Form.tsx
app/client/src/utils/DynamicBindingUtils.ts

PR to show evaluated value in datasource URL. 
Fixes #821
- Cypress
- Jest
// Code coverage diff between base branch:release and head branch: feat/show-evaluated-value-in-action-url 
:red_circle: | total | 55.2 **(-0.02)** | 37.07 **(-0.02)** | 34.06 **(-0.01)** | 55.72 **(-0.02)**
:red_circle: | app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx | 29.63 **(-1.58)** | 2.06 **(-0.41)** | 3.57 **(-0.43)** | 31.97 **(-1.11)**
:red_circle: | app/client/src/entities/DataTree/dataTreeAction.ts | 21.05 **(-3.95)** | 0 **(0)** | 0 …

feat: Show evaluated value in embeddedDatasource url

---

.github/workflows/integration-tests-command.yml

Fix a typo in the integration-tests-command workflow

chore - Fix typo in integration-tests-command workflow

---

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java
app/server/appsmith-server/src/test/resources/test_assets/ImportExportServiceTest/invalid-application-without-pageId-action-collection.json

> When the application is imported from the JSON file with null pageId for action and actionCollection, `internal server error` is thrown. This PR will filter such resources and then import the application. This issue was happening because of the collection was not getting deleted from DB which is already addressed in https://github.com/appsmithorg/appsmith/pull/9785, but this is still throwing errors for JSON which were exported earlier
Fixes #9999
> Manual test
> Junit TC

fix: Filter the action and collection with no pageIds to fix server error while importing the application

---

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/DefaultResourcesUtils.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/ActionCollectionServiceCEImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java
app/server/appsmith-server/src/test/resources/test_assets/ImportExportServiceTest/valid-application.json

> When the JSObject only contains the variables with no action reference we were getting npe as `actionCollectionDTO.getDefaultToBranchedActionIdsMap()` was null. Also as the imported application is ina bad state with no defaultResource ids set this was throwing the exception while fetching the `actionCollection` as well
Fixes #10002
> JUnit TC
> Manual Test

fix: Fix npe while importing application when JSObject contains only variables and no action

---

app/client/cypress/fixtures/emptyDSL.json
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Checkbox_group_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Dropdown_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/MultiSelect_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/MultiTreeSelect_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/RadioGroup_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Switchgroup_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Tree_Select_spec.js
app/client/src/widgets/CheckboxGroupWidget/widget/index.tsx
app/client/src/widgets/DropdownWidget/widget/index.tsx
app/client/src/widgets/MultiSelectTreeWidget/widget/index.tsx
app/client/src/widgets/MultiSelectWidget/widget/index.tsx
app/client/src/widgets/RadioGroupWidget/widget/index.tsx
app/client/src/widgets/SingleSelectTreeWidget/widget/index.tsx
app/client/src/widgets/SwitchGroupWidget/widget/index.tsx

Fixes #10007 
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: fix/select-widget-empty-value 
:green_circle: | total | 55.09 **(0.01)** | 36.53 **(0.01)** | 34.48 **(0)** | 55.61 **(0)**
:green_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0.78)** | 72.55 **(1.96)** | 100 **(0)** | 93.33 **(0.95)**</details>

fix: Allow empty value in select type widgets options property

---

deploy/docker/scripts/renew-certificate.sh

The cert renewal script fails to renew the SSL certificate because it is checking the wrong env variable for the domain name.

fix: Fix custom domain's env variable name

---

deploy/docker/templates/nginx/nginx-app-https.conf.template.sh

Because this route definition is missing, cert renewal doesn't work, since when cert is up for renewal, it means HTTPS is already active with the old certificate, which means the HTTPS NGINX config is active, and this config is missing the acme routes needed for domain validation.

fix: Missing acme route in NGINX HTTPS config

---

app/client/src/pages/Editor/IntegrationEditor/IntegrationsHomeScreen.tsx

Removes unnecessary spaces from the active data source page for consistent page scroll
Fixes #8592 
Manually
// Code coverage diff between base branch:release and head branch: fix/active-datasources-page-scroll 
:red_circle: | total | 55.11 **(-0.01)** | 36.61 **(0)** | 34.54 **(0)** | 55.64 **(0)**
:red_circle: | app/client/src/pages/Editor/IntegrationEditor/IntegrationsHomeScreen.tsx | 27.81 **(-0.38)** | 11.63 **(-0.27)** | 4.55 **(-0.21)** | 32.54 **(-0.26)**</details>

fix: remove unnecessary spaces from the active datasource page for consistent page scroll

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ApiPaneTests/API_Edit_spec.js
app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx
app/client/src/transformers/RestActionTransformer.ts

- Duplicate query params are removed from the evaluated value in API url
- String.substr method is replaced, as it is deprecated.
Fixes #821
Cypress test
// Code coverage diff between base branch:release and head branch: fix/duplicate-query-params-in-evaluated-value 
:red_circle: | total | 55.13 **(0)** | 36.63 **(-0.01)** | 34.56 **(0)** | 55.66 **(0)**
:red_circle: | app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx | 29.27 **(-0.36)** | 1.98 **(-0.08)** | 3.57 **(0)** | 31.54 **(-0.43)**
:red_circle: | …

fix: remove duplicate query params in evaluated value

---

app/client/src/components/editorComponents/CodeEditor/BindingPromptHelper.ts

Fixes #8651
Manual
// Code coverage diff between base branch:release and head branch: fix/slash-command-not-showing 
:green_circle: | app/client/src/components/editorComponents/CodeEditor/BindingPromptHelper.ts | 100 **(0)** | 100 **(14.29)** | 100 **(0)** | 100 **(0)**

fix: improve slash command conditional

---

app/client/src/components/ads/Switch.tsx

> Added box shadow for switches on focus state in the property pane.
Fix #10032
> Manually
// Code coverage diff between base branch:release and head branch: fix/property-pane-switch-focus 
:green_circle: | total | 55.03 **(0)** | 36.46 **(0.01)** | 34.44 **(0)** | 55.56 **(0)**

fix: added focus styling for switches in property pane

---

app/client/src/components/editorComponents/CodeEditor/index.tsx

Added a fix to update entity start action only when the input is focused and there is a change in the input values.
This bug occurred because the query being switched from the left navigation pane was re-rendering the code editor and the onChange for the data was getting fired which was updating the status of the entity being updated to true but the success event was not getting triggered due to the check of focused input for redux store update. So the loading state was always true when the query was switched, I avoided that status update with the same check as for the redux store update.
#10124 
Either of the below method can be used to test the bug fix.
> Type in the query in the query editor of the datasource and then …

fix: run button loading infinitely due to entity update start action

---

app/client/src/components/editorComponents/CodeEditor/index.tsx

When we update the query `very fast` but the previous value and ending value remains same eg. `ABCD` we remove `D` and then add `D` so the ending data remains `ABCD`  and we hit `CMD+ENTER` or click on `RUN` for running the query. Then the loading state remains in the infinite loading state. 
Fixes #10124 
> Type in the query in the query editor of the datasource and then while typing the query continuously press CMD+ENTER to execute the query. After the fix the query should execute with the latest value in the editor after updating the values in the redux store as well.`
> Add two queries (eg. postgres queries). Update either of the two, execute the same query. Switch to another query from …

fix: run button loading infinitely due to query update when final and initial value remains same

---

app/client/src/widgets/TableWidget/widget/propertyConfig.ts

-- Fix on wrong ISO8601 format token
Fixes #9494 
- Test A
- Test B

fix: The date data in ISO 8601 format is throwing Invalid date on table widget
