appsmithorg/appsmith

app/client/src/components/designSystems/appsmith/MapComponent.tsx
app/client/src/widgets/MapWidget.tsx

- Remove hard-coded API key from MapComponent
- Use the google maps API key provided by the configs

Use Google Maps API key from configs

---

deploy/install.sh

Starting docker daemon if not already running

---

app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ActionController.java
app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/ActionViewDTO.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ActionService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ActionServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionServiceTest.java

Only id, name and jsonPathKeys are returned in view mode.

New endpoint added to get actions by applicationId in view mode. 

---

app/client/cypress/support/commands.js

I have removed the check for Edit icon which is not needed anymore.

Apipane fix

---

app/client/Dockerfile
app/client/docker/start-nginx.sh
deploy/install.sh
deploy/template/docker-compose.yml.sh
deploy/template/docker.env.sh
deploy/template/encryption.env.sh
deploy/template/init-letsencrypt.sh.sh
deploy/template/mongo-init.js.sh
deploy/template/nginx_app.conf.sh

* Getting the deploy script to work for Bash Version 3 on Mac OS X devices. 
* Modifying the nginx template and the way it's run in the `docker-compose.yml` file to ensure that any environment variable changes are reflected in the configuration on container restart.

Modifying deploy script to replace nginx configuration at runtime

---

app/client/cypress/integration/Smoke_TestSuite/ApiPaneTests/API_CurlPOSTImport_spec.js
app/client/cypress/locators/ApiEditor.json
app/client/cypress/support/commands.js

This PR has import updated for a test/locator updated and route updated

Updated locator/corrected typo/updated route

---

app/client/src/pages/Editor/QueryEditor/QueryHomeScreen.tsx
app/client/src/pages/Editor/QueryEditor/index.tsx
app/client/src/selectors/entitiesSelector.ts

Show all db datasources in query pane

Show all db datasources in query pane

---

app/server/appsmith-plugins/mysqlPlugin/src/main/resources/form.json
app/server/appsmith-plugins/postgresPlugin/src/main/resources/form.json
app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java

Also correcting icon details to mysql plugin migration.

Adding default values for mysql datasource

---

app/client/src/pages/Editor/QueryEditor/Form.tsx
app/client/src/pages/Editor/QueryEditor/Table.tsx

Fix table height bug

---

app/client/cypress/integration/Smoke_TestSuite/DisplayWidgets/Map_spec.js
app/client/src/components/designSystems/appsmith/Table.tsx

* Add table row index and col index

Fix widget tests

---

app/client/src/pages/Editor/APIEditor/Form.tsx
app/client/src/pages/Editor/EditorHeader.tsx
app/client/src/pages/Editor/ShareApplicationForm.tsx
app/client/src/pages/Editor/index.tsx
app/client/src/pages/UserAuth/CreatePassword.tsx
app/client/src/pages/UserAuth/ResetPassword.tsx
app/client/src/pages/organization/settings.tsx
app/client/src/sagas/InitSagas.ts
app/client/src/sagas/OrgSagas.ts
app/client/src/sagas/QueryPaneSagas.ts
app/client/src/selectors/organizationSelectors.tsx

- Settings page: whole page should scroll not the table
- Application name to be displayed to user on share
- Fix eslint errors

fix: Table scroll issue, application share issue, eslint errors

---

app/client/cypress/fixtures/testdata.json
app/client/cypress/integration/Smoke_TestSuite/ApiPaneTests/API_All_Verb_spec.js
app/client/cypress/integration/Smoke_TestSuite/ApiPaneTests/API_Edit_spec.js
app/client/cypress/integration/Smoke_TestSuite/OrganisationTests/CreateOrgTests_spec.js
app/client/cypress/support/commands.js
app/client/cypress/support/index.js

1.Fixed tests related to API pane.
2.create org had a failure in cleanup stage so added a fix.

Api test fixes

---

app/client/cypress/integration/Smoke_TestSuite/ApiFlow/CurlImportFlow_spec.js
app/client/cypress/integration/Smoke_TestSuite/ApiPaneTests/API_Edit_spec.js
app/client/cypress/integration/Smoke_TestSuite/Binding/TextTable.js
app/client/cypress/support/commands.js

Updated the type of assertion.
removed an assert which is not required.
added a small delay for one of the test.
updated one test with save and run which was only run earlier.

assertion type changed

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ActionServiceImpl.java

Please inspect changes with whitespace ignored. There's an indentation correction as well in this PR.

Return 200 when action could not be executed

---

app/client/src/api/ActionAPI.tsx
app/client/src/sagas/ActionExecutionSagas.ts

Use isExecutionSuccess for showing showing success message as status code string does not appear in query response

Use isExecutionSuccess for showing success message

---

.github/ISSUE_TEMPLATE/---bug-report.md
.github/ISSUE_TEMPLATE/bug_report.md

Update issue templates

---

app/client/src/components/propertyControls/LocationSearchControl.tsx

Fix: Location search control now uses the google maps api key from configs

Location search control google api key

---

app/client/cypress/support/commands.js
app/client/src/components/designSystems/appsmith/SearchComponent.tsx
app/client/src/components/designSystems/appsmith/TableHeader.tsx
app/client/src/components/designSystems/appsmith/TableStyledWrappers.tsx
app/client/src/components/designSystems/blueprint/TextComponent.tsx
app/client/src/pages/Editor/APIEditor/index.tsx
app/client/src/pages/Editor/QueryEditor/index.tsx
app/client/src/utils/Validators.ts
app/client/src/widgets/RichTextEditorWidget.tsx
app/client/src/widgets/TableWidget.tsx

- Table header style fixes
- Rich text editor widget crash fixes
- Api pane and query pane blank fix
- Add table default search text property
- Text widget heading styles

Widget fixes

---

app/client/cypress/integration/Smoke_TestSuite/ApiPaneTests/API_CurlPOSTImport_spec.js

curl command updated with double quotes in place of single quotes in payload

curl command updated for POST operation

---

app/client/src/components/editorComponents/SelectComponent.tsx
app/client/src/pages/organization/InviteUsersFromv2.tsx
app/client/src/selectors/organizationSelectors.tsx

Update dropdown UI on invite users modal.

update: Invite user dropdown UI

---

app/client/netlify.toml

- Netlify deploy contexts now include one for the branch `develop`

Add develop deploy context in netlify.toml

---

app/client/src/components/editorComponents/EditableText.tsx

- Show error tooltip when there is an error and focused.

Set current value instead of default value when there is an error

---

app/server/appsmith-server/src/test/java/com/appsmith/server/services/PluginServiceTest.java

We use `@SpyBean` annotation to partially mock the `PluginService` class.

Adding a test for the valid scenario when returning the plugin form details

---

deploy/install.sh

1. Mongo Docker container errors out incase the username or password are empty. Hence we enforce non-empty credentials for Mongo. 
2. Also checking for availability of Docker container at the beginning of the script to ensure that we install the relevant packages before asking for user inputs.
3. Waiting for server to start successfully before exiting the script.

Enforcing non-empty credentials for Mongo during installation

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/OrganizationService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/OrganizationServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ExamplesOrganizationCloner.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ExampleApplicationsAreMarked.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ExamplesOrganizationClonerTests.java

It will still be created, only if a example template organization
has not been configured in the system.

Don't always automatically create a blank personal org

---

app/client/src/components/designSystems/appsmith/SearchComponent.tsx
app/client/src/components/designSystems/appsmith/TableHeader.tsx
app/client/src/components/designSystems/appsmith/TableStyledWrappers.tsx
app/client/src/constants/Colors.tsx

…earch and pagination item font-size changed.

Fix-Table widget row items color changed. Pagination font-size changed.

---

app/client/src/pages/Editor/DataSourceEditor/FormTitle.tsx

- Use EditableText for datasource name

Validate datasource name without calling update api

---

app/client/src/AppRouter.tsx
app/client/src/api/Api.tsx
app/client/src/components/designSystems/appsmith/header/DeployLinkButton.tsx
app/client/src/constants/routes.ts
app/client/src/pages/AppViewer/viewer/AppViewerHeader.tsx
app/client/src/sagas/ApiPaneSagas.ts
app/client/src/sagas/QueryPaneSagas.ts

* Copy deploy link button
* Update form name after query name refactor, this was causing the current value to fail after renaming
* Default page is always placed first in view mode

Launch polish bug fixes

---

app/client/src/components/editorComponents/DropTargetComponent.tsx

Patch issue where new widget's property pane offset is large.

Patch: New widget property pane offset

---

app/client/src/components/designSystems/appsmith/ReactTableComponent.tsx
app/client/src/components/designSystems/appsmith/TableStyledWrappers.tsx
app/client/src/components/designSystems/appsmith/TableUtilities.tsx
app/client/src/widgets/TableWidget.tsx

- Sort icon reversed
- Remove sorting on 3rd click
- Warning due to rotate variable fixed

Fix-Table column sorting changes

---

app/client/cypress/support/commands.js

added delay after global search

Feature test/search delay

---

app/client/public/index.html
app/client/src/constants/AppConstants.ts
app/client/src/constants/messages.ts
app/client/src/constants/providerConstants.ts
app/client/src/index.tsx
app/client/src/pages/AppViewer/viewer/AppViewerHeader.tsx
app/client/src/pages/Editor/Explorer/index.tsx
app/client/src/reducers/entityReducers/appReducer.ts
app/client/src/utils/AppsmithUtils.tsx

* Rotate `Fork app` icon
* Change Explorer divider color
* Fix favicon not accessible
* Rename `appsmith.url` to `appsmith.URL`
* AppView page tab overflow ellipsis
* Rename `Back to editor` button to `Edit App`
* Update App card colors

Style polish

---

app/client/public/index.html
app/client/src/constants/AppConstants.ts
app/client/src/constants/messages.ts
app/client/src/constants/providerConstants.ts
app/client/src/index.tsx
app/client/src/pages/AppViewer/viewer/AppViewerHeader.tsx
app/client/src/pages/Editor/Explorer/index.tsx
app/client/src/reducers/entityReducers/appReducer.ts
app/client/src/utils/AppsmithUtils.tsx

* Rotate Fork app icon
* Change Explorer divider color
* Fix favicon not accessible
* Rename `appsmith.url` to `appsmith.URL`
* AppView page tab overflow ellipsis
* Rename `Back to editor` button to `Edit App`
* Update App card colors

Style polish (#371)

---

app/client/src/pages/Editor/QueryEditor/Form.tsx
app/client/src/pages/Editor/QueryEditor/index.tsx
app/client/src/sagas/ActionSagas.ts
app/client/src/sagas/ApiPaneSagas.ts
app/client/yarn.lock

Fix: When copying a query, the app tries to open the API page with the queryId
Fix: After moving a query, the query input box is empty

Fix: Action move & copy issues

---

app/client/src/assets/icons/ads/upper_arrow.svg
app/client/src/components/ads/Table.tsx
app/client/src/components/ads/TableDropdown.tsx
app/client/src/components/ads/Tabs.tsx
app/client/src/components/stories/Table.stories.tsx
app/client/src/components/stories/TableDropdown.stories.tsx

1. Table dropdown onBlue isssue fixed.
2. UI transparency issue fixed.
3. Table upper arrow icon imported.
4. Popover added in table dropdown.

Table dropdown onBlur, UI transparency, Popover issue fixed. Added sort arrow

---

app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Organization.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseAppsmithRepositoryImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/OrganizationServiceTest.java

2. Added email field in organization.

1. Fixed the bug where policies are being set to empty during organization update

---

app/client/cypress/fixtures/testdata.json
app/client/cypress/integration/Smoke_TestSuite/ApiPaneTests/API_RequestBody_spec.js
app/client/cypress/locators/ApiEditor.json
app/client/cypress/locators/apiWidgetslocator.json
app/client/src/components/editorComponents/form/fields/KeyValueFieldArray.tsx
app/client/src/pages/Editor/APIEditor/Form.tsx
app/client/src/pages/Editor/APIEditor/PostBodyData.tsx

- Add useEffect back to KeyValueFieldArray component to add minimum rows

Fix form-encoded body showing 0

---

app/client/cypress/fixtures/formResetDsl.json
app/client/cypress/integration/Smoke_TestSuite/FormWidgets/FormReset_spec.js
app/client/cypress/integration/Smoke_TestSuite/QueryPane/PostgreDatasource_spec.js
app/client/cypress/locators/Widgets.json
app/client/src/sagas/PageSagas.tsx
app/client/src/sagas/PluginSagas.ts
app/client/src/utils/AnalyticsUtil.tsx

* Possible fix for plugins not found
* Add user info on smart look
* Add test for form and table inside form reset
* Add test for postgres nested data render

Fixes for release

---

app/client/src/components/editorComponents/ActionNameEditor.tsx
app/client/src/pages/Editor/Explorer/Entity/Name.tsx
app/client/src/pages/Editor/Explorer/Entity/index.tsx
app/client/src/pages/Editor/Explorer/Pages/PageEntity.tsx
app/client/src/pages/Editor/PropertyPaneTitle.tsx
app/client/src/reducers/uiReducers/explorerReducer.ts
app/client/src/sagas/ActionSagas.ts
app/client/src/utils/helpers.tsx

- Keep new names of entities until failure
- Page Names can include one space between alphanumeric characters.

Fix Entity Names

---

app/client/cypress/integration/Smoke_TestSuite/ApiFlow/CurlImportFlow_spec.js

Update the production server api link with mock appsmith link in the curl test

Replaced production server link with mock api link

---

app/client/src/actions/datasourceActions.ts
app/client/src/pages/Editor/Explorer/Datasources/DatasourceEntity.tsx
app/client/src/sagas/DatasourcesSagas.ts

Fixes: Datasource name not getting updated from the explorer.

Fix: datasource name edit

---

app/client/src/pages/Editor/Explorer/Actions/ActionEntity.tsx
app/client/src/pages/Editor/Explorer/Entity/EntityProperties.tsx
app/client/src/pages/Editor/Explorer/Pages/PageEntity.tsx
app/client/src/pages/Editor/Explorer/Widgets/WidgetEntity.tsx

Fixes: Entity properties for pages other than current page are empty.

Fix: Entity properties

---

app/client/src/components/ads/Button.tsx

Height issue in fixed in all sizes of button.

Fix: Button height issue

---

app/client/src/components/ads/MenuItem.tsx
app/client/src/components/stories/Menu.stories.tsx

Menu item disabled state UI added.

Fix: Menu item disabled state

---

app/client/cypress/integration/Smoke_TestSuite/ExplorerTests/Entity_Explorer_DragAndDropWidget_spec.js
app/client/cypress/locators/explorerlocators.json
app/client/cypress/support/commands.js

In this test, we have added a test to drag and drop form widget to canvas.

Drag And drop widget

---

app/client/src/components/designSystems/appsmith/ReactTableComponent.tsx
app/client/src/components/designSystems/appsmith/Table.tsx
app/client/src/components/stories/Checkbox.stories.tsx
app/client/src/components/stories/Radio.stories.tsx
app/client/src/widgets/TableWidget.tsx

Data type of selectedRowIndices changed to array of numbers

Fix-multiple selected row datatype

---

app/client/src/mockResponses/ActionSettings.tsx
app/client/src/sagas/ActionExecutionSagas.ts

- Remove cache fields from settings
- Call the event callback method with success false to fix button widget loading issue

Fix: Button widget loading fix

---

app/client/src/mockResponses/ActionSettings.tsx

This PR basically reverts the changes of the following PR :
https://github.com/appsmithorg/appsmith/pull/524

Adding back API on load setting on the client side.

---

app/client/src/components/ads/EditableText.tsx
app/client/src/components/stories/EditableText.stories.tsx
app/client/src/components/stories/Menu.stories.tsx

SavingState prop is added instead of callback and `isSaving` prop.

Fix: State management in EditableText Component

---

app/client/src/sagas/WidgetOperationSagas.tsx

Fix action called on Cut widget trigger.

Fix cut widget feature issue

---

app/client/cypress/support/commands.js

Updated locator which was inconsistent

Updated locator

---

app/client/cypress/integration/Smoke_TestSuite/OrganisationTests/CreateOrgTests_spec.js
app/client/cypress/support/commands.js

locator updated

---

app/client/cypress/fixtures/layoutdsl.json
app/client/src/sagas/WidgetOperationSagas.tsx

- Handle widget's parenId undefined scenario.
- Update cypress layoutDSL to include parentIds.

Prime cut feature code for keyboard shortcut tests

---

app/client/cypress/integration/Smoke_TestSuite/ExplorerTests/Entity_Explorer_Widgets_Copy_Delete_Undo_spec.js
app/client/cypress/integration/Smoke_TestSuite/ExplorerTests/Entity_Explorer_Widgets_Copy_Paste_Delete_Undo_Keyboard_Event_spec.js
app/client/cypress/locators/commonlocators.json
app/client/src/components/editorComponents/ToastComponent.tsx
app/client/src/pages/Editor/PropertyPaneTitle.tsx

- Add selectors for delete trigger, toast action and copy trigger

Add Tests: Delete widget and Undo delete widget

---

app/client/src/index.tsx
app/client/src/pages/common/AppRoute.tsx

Reverts appsmithorg/appsmith#643

Revert "Fixing applications page first theme load."

---

deploy/install.sh

fix: use trap to run bye on errexit

---

app/client/src/sagas/DatasourcesSagas.ts

- Fix two toasts showing up for error

Fix previous name showing up in toast

---

app/client/src/jsExecution/RealmExecutor.ts
app/client/src/utils/DynamicBindingUtils.ts

Fix issue where unknown functions in data tree cause evaluation issues

---

app/client/src/components/ads/Button.tsx
app/client/src/components/ads/EditableText.tsx
app/client/src/components/ads/RectangularSwitcher.tsx
app/client/src/constants/DefaultTheme.tsx
app/client/src/pages/Applications/ApplicationCard.tsx
app/client/src/pages/Applications/index.tsx

1. Save app name on outside click
2. Fixed create app card misalignment.
3. Edit/Launch should not show up on app menu open.
4. Menu shadow in the User profile is fixed.
5. App name should be black.
6. Share button text alignment fixed.
7. Theme switcher border hover issue resolved.

Fix: Light mode bugs

---

app/client/src/pages/Editor/Explorer/Datasources/DatasourceField.tsx
app/client/src/pages/Editor/Explorer/Datasources/DatasourcesGroup.tsx

- Expand datasource by default
- Let column/key name take more space.
- Show column popup on hover instead of click

Datasource explorer fixes

---

README.md

Details of contributor to be added later by maintainers

Updating README to add contributor section

---

deploy/install.sh

Update deploy install script to use api64.ipify.org which supports IPv4

---

app/client/src/mockResponses/WidgetConfigResponse.tsx

As the id field is not required in the default options and it was causing some problems , So i have removed them .
Please have a look and give me a review .
It solves the issue #661

Solving issue #661 , Radio Button Id issue

---

app/client/src/widgets/DropdownWidget.tsx

Fix triggering of onChange when value is the same

---

app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java

fix(sign-up): change in sign up error message

---

app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java

Fix(backend): Wrong error message while resetting the password fixed,  changed from id to email

---

app/client/src/utils/Validators.ts

Previously there was no check for empty value of radio button . It was being processes as there was no check for empty string .
I have applied a check condition for empty string now . If string would be empty , it will return false.
Thus this solves issue #662 .

Solving #662 , Radio Button Empty Value problem

---

app/client/src/sagas/ActionExecutionSagas.ts

fixes https://github.com/appsmithorg/appsmith/issues/673

fix(sagas): add missed error callback

---

app/client/src/widgets/InputWidget.tsx

* Added number validation.
* Minor code style improvements.
Closes #768 .

fix: input widget number validation #768

---

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/PingScheduledTask.java

Updated the URL in `PingScheduledTask` 
Fixes #1012 
- Manually

Fixed the URL in PingScheduledTask

---

app/client/src/pages/organization/CreateOrganizationForm.tsx
app/client/src/utils/formhelpers.ts

fixes https://github.com/appsmithorg/appsmith/issues/807
potential fix case, mentioned https://github.com/appsmithorg/appsmith/issues/621, that button should be enabled, until name of org is typed

Fix: Do not allow for spaces inside create organisation form.

---

app/client/cypress/fixtures/formWidgetdsl.json
app/client/cypress/integration/Smoke_TestSuite/ExplorerTests/Entity_Explorer_Widgets_Copy_Delete_Undo_spec.js
app/client/cypress/integration/Smoke_TestSuite/ExplorerTests/Entity_Explorer_Widgets_Copy_Paste_Delete_Undo_Keyboard_Event_spec.js

Description:
Updated tests where we had implemented drag and drop with dsl.

replaced dragdrop with dsl

---

app/client/cypress/integration/Smoke_TestSuite/ExplorerTests/Entity_Explorer_Datasource_Structure_spec.js
app/client/cypress/support/commands.js

Fix failing datasource  structure tests.

Fix datasource structure test

---

.github/close-label.yml

The Github Bot that uses this file is: https://github.com/Logerfo/close-label
>
Fixes #1090 
When a PR is successfully merged, the Github bot will add the label `QA` to the issue. These issues can then be picked up by the QA team for verification.
Manual test

Adding the close-label.yml file required by Github App to label issues as QA

---

app/client/cypress/integration/Smoke_TestSuite/DisplayWidgets/Table_spec.js

This adds new cypress tests for the 
- Adds new tests
- Cypress

Adding filter tests for table

---

.github/workflows/client.yml
app/client/src/components/ads/MenuItem.tsx
app/client/src/components/designSystems/appsmith/TableColumnsVisibility.tsx
app/client/src/jsExecution/RealmExecutor.ts
app/client/src/pages/organization/CreateOrganizationForm.tsx
app/client/src/utils/Validators.ts
app/client/src/widgets/InputWidget.tsx

Release had a few minor code quality issues that was causing errors in development. This PR fixes those issues

fix release cleanup issues

---

app/client/src/sagas/WidgetOperationSagas.tsx

Fixes issue with new dynamic triggers not being set because of immutable objects

Fix issue with setting dynamic triggers

---

app/client/cypress/fixtures/formInputTableDsl.json
app/client/cypress/integration/Smoke_TestSuite/Binding/Widgets_form_input_table_default_validation.js

Binding form/input/table and validating default/dependancy validation

binding test added invloving form input and table

---

app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/AuthenticationSuccessHandler.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ExamplesOrganizationCloner.java

Primarily doing example app cloning and
analytics in parallel.

Refactor tasks on first-login

---

app/client/cypress/integration/Smoke_TestSuite/DisplayWidgets/video_spec.js

There is visible delay in toast message coming up, so added a wait for the same.

wait added for toast message

---

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java

Fixes #780
- Bug fix
- Added user
- Requested password reset
- Made sure entry was gone after expiration time

TTL must be set on date field

---

CONTRIBUTING.md
contributions/ClientSetup.md

Update contribution guide to cover node mismatch version error on client app.
Contribution guide update

Update contribution guide: add details about nvm

---

app/client/src/components/propertyControls/MultiSelectControl.tsx
app/client/src/widgets/FilepickerWidget.tsx

Adds the raw binary version of the file to the file picker

added binary raw data to be set for files picked

---

app/client/src/components/ads/Table.tsx

> A wrong fix was pushed into the codebase for fixing column shifting on sorting.. Need to revert it.
- Refactor
> This PR will recreate the issue #620 
- Test A
- Test B

Removing a bad fix for Table column width.

---

app/client/src/api/ActionAPI.tsx
app/client/src/api/Api.tsx
app/client/src/api/PageApi.tsx
app/client/src/sagas/PageSagas.tsx

Added cancel request logic for update layout, api and action

---

app/client/src/components/ads/Table.tsx

This change fixes an issue related to the Table column's resizing.  
Fixes #620 
While the fix needed to resolve this issue was to have a `min-width` to the columns irrespective of having flex underneath, that wasn't possible as it would have incurred quite some CSS changes which weren't feasible. So currently its resolved using a hidden SVG, which helps maintain consistent column width. Suggestion by @satbir121 
UI minor fix
Ran the unit test to make sure everything was still fine. 
Minor usability test - [changes](https://www.dropbox.com/s/e0p7ivq1z1vcwoi/Screen%20Recording%202020-10-15%20at%2011.23.14%20PM.mov?dl=0)
- [  ] I have commented my code, particularly in hard-to-understand areas
- [  ] I have made corresponding changes to the documentation
- [  ] I have added tests that prove …

minor fix for column resizing onevent

---

app/client/src/components/designSystems/appsmith/TabbedView.tsx
app/client/src/components/editorComponents/ApiResponseView.tsx

Remove extraneous scrollbars in API action pane

---

app/client/src/components/formControls/FixedKeyInputControl.tsx
app/client/src/pages/Editor/DataSourceEditor/Connected.tsx
app/client/src/utils/FormControlRegistry.tsx
app/server/appsmith-plugins/mysqlPlugin/src/main/resources/form.json

Create a new input field which outputs a key value pair

---

app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx

Update evaluated pane scrollbar style
Fixes #1182 
- Add vertical scroll by adding enter in text value and then checking the scroll

fix evaluated pane scrollbar style

---

app/client/src/components/propertyControls/MultiSelectControl.tsx
app/client/src/pages/organization/AppInviteUsersForm.tsx
app/client/src/sagas/ActionExecutionSagas.ts
app/client/src/sagas/userSagas.tsx
app/client/src/utils/AnalyticsUtil.tsx
app/client/src/widgets/FilepickerWidget.tsx

There's currently a conflict when trying to merge release into master. This PR is merging master branch into release, so the conflict is resolved.
Conflicts:
app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/AuthenticationSuccessHandler.java

Resolve conflict with master

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserOrganizationServiceImpl.java

Added sending email when the role of a member is changed
Fixes #1037 
- Created user A and an organization OA
- Invited B to join org OA
- B joins OA
- A changes B's role
- Used mailtrap.io as dummy SMTP server to verify an email is received intimidating user B of about the role change

Added sending email when the role of the member is changed

---

app/client/cypress/integration/Smoke_TestSuite/UnitTest/LoginFromUIApp_spec.js
app/client/cypress/locators/HomePage.json
app/client/cypress/support/commands.js
app/client/src/constants/userConstants.ts
app/client/src/pages/common/LoginHeader.tsx
app/client/src/pages/common/ProfileDropdown.tsx
app/client/src/reducers/uiReducers/usersReducer.ts

>
Updated the LOGOUT_USER_SUCCESS reducer. The currentUser field in state is defined after FETCH_USER_DETAILS_SUCCESS is called during initial load of Application. After log out, however, the currentUser field was set to undefined. Changed that to be on reflective of the state after FETCH_USER_DETAILS_SUCCESS has been dispatched. That means having a default setting for currentUser. Also reset user array state.
Updated state for currentUser and user array. 
fixes: #1136 
> Please describe the tests that you ran to verify your changes. Provide …

[#1136] Fix the Appsmith logo click href

---

app/client/src/pages/Editor/Explorer/Actions/ActionEntityContextMenu.tsx
app/client/src/pages/Editor/Explorer/Pages/PageContextMenu.tsx

Fixes #749 
> Issue 1: Go to edit mode --> On the left side, click on Delete against Home Page.
Actual Result : Cannot Delete Home Page.
Expected Result: No option to delete Homepage :heavy_check_mark: 
- Added a condition to ask if this page is the default page. If it is do not show the delete option in the `PageContextMenu`
> Issue 2: When there is just 1 page available (Home Page), try clicking on 'Move to Page'
Actual Result : Broken UI.
expected Result: Proper UI. :heavy_check_mark: 
- Added a conditional to check if we have more than 1 page in the `menuPages` item. If we do then filter out our current page and display the rest. Otherwise show `No Pages`
Tested manually on local machine

fix\Issues while performing actions on Home Page #749

---

app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/AuthenticationSuccessHandler.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java

Removed create_USER event during userCreate because this breaks OAUTH first user login.
Fixes #1289
- By testing Google & Github login on localhost

[Bug Fix] Removed create_USER event during userCreate because this breaks OAUTH first user login.

---

app/client/public/index.html

Fixes issue where uncaught errors cause the whole app to reload.

Fix chunk loading reload issue

---

app/client/src/constants/DefaultTheme.tsx

Update application card colors

---

app/client/cypress.json

Adds Cypress retry config to enable flaky tests detection

Add retry to Cypress tests

---

app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/OrganizationController.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserOrganizationService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserOrganizationServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/OrganizationServiceTest.java

Fixes #1306
- Invite user to organization
- Update role
- Click on link in email
- [x New and existing unit tests pass locally with my changes

Parameter missing for email template replace

---

app/client/src/components/formControls/DynamicTextFieldControl.tsx
app/client/src/pages/Editor/QueryEditor/Form.tsx
app/client/src/reducers/entityReducers/pluginsReducer.ts

Fixes for a form like UI in query tab in the query editor

Query editor styling fixes

---

app/client/src/api/Api.tsx
app/client/src/pages/Applications/index.tsx

> Supporting 5 application cards till 1368px screen width.
> At least 5 app cards should show for width above 1368px.

Supporting 5 app cards till 1368px resolution

---

app/client/cypress/locators/ViewWidgets.json

locator updated for one of the flaky test

Updated locator for test failure

---

app/client/cypress.json
app/client/cypress/integration/Smoke_TestSuite/FormWidgets/Dropdown_spec.js
app/client/cypress/locators/Widgets.json
app/client/src/widgets/DropdownWidget.tsx

Dropdown widget had a bad logic 
Fixes #1325
- Cypress Test case

Fix Dropdown widget selection

---

app/server/appsmith-plugins/redisPlugin/pom.xml
app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/plugins/RedisPlugin.java
app/server/appsmith-plugins/redisPlugin/src/main/resources/editor.json
app/server/appsmith-plugins/redisPlugin/src/main/resources/form.json
app/server/appsmith-plugins/redisPlugin/src/test/java/com/external/plugins/RedisPluginTest.java
app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java

1. Fixing the build by excluding the slf4j-api from redis-plugin pom.xml
2. Adding the editor.json and form.json for the query pane & datasource pane.
3. Adding array handling in the Redis response by feeding all the output into a "result" key
Fixes #1016
Automated test suite and manual testing on local machine.

Adding the database changelog for Redis

---

app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomOrganizationRepository.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomOrganizationRepositoryImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/OrganizationServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ApplicationFetcher.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java

- Organizations are now sorted by name. We can drop the last commit if create date makes more sense to you.
- Bug fix
- Added a bunch of organizations/applications and sorting was predictable

Fix organization ordering

---

app/client/cypress/fixtures/SimpleBinding.json
app/client/cypress/integration/Smoke_TestSuite/Binding/Entity_delete_spec.js
app/client/src/sagas/evaluationsSaga.ts
app/client/src/utils/DynamicBindingUtils.ts
app/client/src/workers/evaluation.worker.ts

Fixes a few async evaluation errors
Fixes #1333 Fixes issue with deletion of entity leaves behind references
Fixes #1327 Fixes Data clone issue with Firefox when error object is passed
Added a cypress test to check if deleting a widget affects bindings referencing it

Fix async evaluation issues

---

app/server/appsmith-plugins/elasticSearchPlugin/src/main/resources/form.json
app/server/appsmith-plugins/mongoPlugin/src/main/resources/form.json
app/server/appsmith-plugins/mysqlPlugin/src/main/resources/form.json
app/server/appsmith-plugins/postgresPlugin/src/main/resources/form.json
app/server/appsmith-plugins/redisPlugin/src/main/resources/form.json

Update datasource form config

---

app/client/src/sagas/WidgetOperationSagas.tsx

Fixes #1366 
Initialising widget props  with the tableData prop seems to fix it for now

Fix widget not having query data

---

app/client/cypress/fixtures/PageLoadDsl.json
app/client/cypress/fixtures/example.json
app/client/cypress/integration/Smoke_TestSuite/Binding/Bind_tableApi_spec.js
app/client/cypress/integration/Smoke_TestSuite/Pages/Page_Load_Spec.js
app/client/src/AppRouter.tsx
app/client/src/pages/AppViewer/index.tsx
app/client/src/pages/AppViewer/viewer/AppViewerHeader.tsx
app/client/src/sagas/InitSagas.ts

Fixes #1385
Cypress test to check for page load of two pages in view mode, and switching of those pages

Fix for app view not opening correct page

---

deploy/install.sh

Hi All, 
I've been trying to install this for a while, and perhaps it's just me, but it really wasn't obvious that the script was failing, being a typical dev used to build processes that spam lots and tell you there an error on the last line, and you go up and find it.. I skipped most of the log and just saw it was exiting after I entered my email address (Which also wasn't obvious why, being pre-trained to accept it as a usual step by lets encrypt) 
As you can probably see from the logs I tried about 5 times, after 2 times I built a fresh server as I thought maybe it was failing due to my server. Eventually, I took to git to inspect the script and see why it was failing.. then discovered the cause :) ... me
Anyway, all in all, I wasted about an hour when a simple 'Error' message or …

Be clear that there's an error on failure

---

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java

Remove unnecessary database migration

---

app/client/cypress/integration/Smoke_TestSuite/QueryPane/AddWidget_spec.js

Added assert for an existing test.

Added assertion for basic AddWidget test

---

deploy/install.sh

>
Adds support to deploy AppSmith on openSUSE Leap, openSUSE Tumbleweed and SUSE Linux Enterprise.
Fixes #1382 
- Tested locally by using it (installing on top of openSUSE Leap 15.2 and SLES 15 SP1)

Add support to deploy on SUSE

---

app/client/src/sagas/QueryPaneSagas.ts

If there are no templates to show then the editor should be shown directly.

Do not show template view if there no templates

---

app/client/src/pages/common/ServerUnavailable.tsx

This PR adds a "Back to homepage" CTA on the [500 page](https://app.appsmith.com/500) to match the [400 page](https://app.appsmith.com/404).
Fixes #1303.
- Using the internal tests available on GitHub.

Add "back to home" CTA on 500 page (#1303)

---

app/client/src/components/designSystems/appsmith/TableStyledWrappers.tsx

>
Adding display type as table to allow horizontal scrolling in table.
Fixes #1419 
- Manually tested the fix

Added horizontal scrolling in table widget

---

app/client/src/components/designSystems/appsmith/MapComponent.tsx

Storing map centre in  local state and updating it with selected marker in map component to avoid resetting map centre.
Fixes #733 
- Workflow is manually tested

Map resetting when clicking on a marker fix

---

app/client/docker/templates/nginx-linux.conf.template
contributions/ClientSetup.md
contributions/ServerSetup.md

Update server and client setup guide. (#1437)
1. Add Linux specific requirements.
2. Add debug info for common build errors.
3. Correct build step or any other statement wherever required.
4. For more info please see the attachment here: #1437
5. Update the Nginx config file for the client app to point to the LOCAL hosted api server by default for both MacOS and Linux.
Fixes appsmithorg/appsmith #1437
Fixes appsmithorg/appsmith #1453
Tested by building and running app on Ubuntu 16.04

Update server and client setup guide

---

app/client/src/reducers/entityReducers/actionsReducer.tsx
app/client/src/sagas/ActionSagas.ts

Update the action config with the datasource info

---

app/client/src/components/designSystems/appsmith/TableStyledWrappers.tsx
app/client/src/pages/Editor/QueryEditor/Table.tsx

Query table horizontal scroll issue fixed. 
Fixes #1460 

Query table scroll issue fixed

---

app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/AuthenticationEntryPoint.java
app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java

Bug fix : Invalids of the action are not being printed properly

Bug fix : Invalids of the action are not being printed properly

---

app/client/src/pages/Editor/Explorer/Datasources/DatasourceStructure.tsx

Show template menu on click of datasource table

---

app/client/src/pages/Editor/Explorer/hooks.ts
app/client/src/reducers/entityReducers/actionsReducer.tsx

For certain actions, datasource details were missing. This resulted in the app crashing.
Fixes #1491 
Manually tested with the culprit application which had the datasource missing in the datasources api call.

Fix issue where datasource was missing for an action

---

app/client/src/components/formControls/DynamicTextFieldControl.tsx
app/client/src/pages/Editor/QueryEditor/Form.tsx
app/client/src/pages/Editor/QueryEditor/Table.tsx

Update query form UI

---

README.md

Fixed JavaScript typo

---

app/client/cypress/fixtures/buttondsl.json
app/client/cypress/fixtures/testdata.json
app/client/cypress/integration/Smoke_TestSuite/Binding/ButtonWidgets_NavigateTo_validation_spec.js

Added tests:
1.Validating navigate to functionality for button click.
2.Validating external website for navigation.

Added tests for button click navigation

---

app/client/cypress/fixtures/containerdsl.json
app/client/cypress/integration/Smoke_TestSuite/LayoutWidgets/Container_spec.js
app/client/cypress/integration/Smoke_TestSuite/OrganisationTests/ShareAppTests_spec.js
app/client/cypress/locators/HomePage.json
app/client/cypress/support/commands.js

Updated dsl file

---

app/client/src/pages/Editor/APIEditor/Form.tsx

fix(API): remove cursor in API HTTP methods field

---

app/client/src/pages/Editor/QueryEditor/Table.tsx

Changes to resolve merge conflicts with master

Change to resolve conflicts

---

app/client/src/components/designSystems/appsmith/TabsComponent.tsx
app/client/src/components/propertyControls/TabControl.tsx
app/client/src/mockResponses/WidgetConfigResponse.tsx
app/client/src/sagas/WidgetOperationSagas.tsx
app/client/src/widgets/TabsWidget.tsx

* Fix issue where placing widgets into the first tab of a tabs widget was disallowed.
* Concatenate using spread instead of produce
* Remove widget blueprint from widget props
* Deal with nested blueprint
> …

Fix: Tabs Widget (#1532)

---

app/client/src/pages/Editor/QueryEditor/Table.tsx

Fix styles to show table rows in query results
Fixes #1539 
Tested manually using a postgres query
- [] I have commented my code, particularly in hard-to-understand areas

Fix styles to show table rows in query results

---

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/pluginExceptions/AppsmithPluginError.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionServiceTest.java

Fixed timeout error message, added new type of error for plugin timeout
Fixes #1422 
- JUnit test mocks timeout at 10ms (ActionServiceTest.testActionExecuteTimeout)

Fixed timeout error message, added new type of error for plugin timeout

---

app/client/cypress/fixtures/testdata.json
app/client/cypress/integration/Smoke_TestSuite/Binding/Widget_loading_spec.js
app/client/cypress/integration/Smoke_TestSuite/QueryPane/AddWidgetTableAndBind_spec.js

1.Commented One test related to query failure seen intermittently
2.Updated a binding change for a test due to change in data.

Updated a binding and commented out failing test

---

app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Organization.java
app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java
app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithException.java
app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/GlobalExceptionHandler.java

1. Assign an action attribute to each AppsmithError enum item. Take action based on the action attribute.
Fixes appsmithorg/appsmith #1278 
In Progress

Report selective errors to rollbar.

---

app/client/cypress/integration/Smoke_TestSuite/QueryPane/AddWidget_spec.js

commented AddWidget_spec

---

app/client/src/widgets/CanvasWidget.tsx

Fix: All canvas widgets should have no container styling applied
Fixes #1563
Visually confirmed

Fix CANVAS WIDGET styles

---

app/client/src/components/editorComponents/ToastComponent.tsx
app/client/src/sagas/ActionExecutionSagas.ts

Wrong toast types would crash the app. This PR will add checks for that.
Fixes #1583

Add checks for wrong alert types of Toast messages

---

app/client/src/pages/Editor/QueryEditor/Form.tsx
app/client/src/pages/Editor/QueryEditor/Table.tsx

Show query form headers while scrolling

---

app/client/src/pages/Editor/Explorer/Pages/PageEntity.tsx
app/client/src/pages/Editor/Explorer/Pages/PageGroup.tsx
app/client/src/pages/Editor/Explorer/index.tsx

Fix issue where clicking on widget add button redirects to the homepage
Fixes #1585 
Manually verified

Fix: Widget add redirects to homepage

---

app/client/src/components/designSystems/appsmith/MapComponent.tsx
app/client/src/widgets/MapWidget.tsx

Map not resetting to location selected fix. Resetting map to search location in map. 
Fixes #1505 

Map not resetting to location selected fix. Resetting map to search location in map.

---

app/client/src/AppErrorBoundry.tsx
app/client/src/index.tsx

Create an App Crash boundary for better crash experience.

Create app crash boundary

---

.imgbotconfig

Configured imgbot to ignore all resources under test for the server. 
Fixes #1644 
Unable to test, only applicable on CI

Added imgbot config file

---

app/client/src/transformers/RestActionTransformer.ts
app/client/src/transformers/RestActionTransformers.test.ts

Fix incorrect bodyFormData values being sent

---

app/client/src/pages/Editor/PropertyPane/index.tsx
app/client/src/sagas/WidgetOperationSagas.tsx
app/client/src/sagas/evaluationsSaga.ts
app/client/src/widgets/BaseWidget.tsx
app/client/src/workers/evaluation.worker.ts

Fixes #1683 
> Fix for dropdowns with option not being an object crashes dropdown and stops eval
Fixes #1656 #1657 
> Fix issue where updateWidgetProperty would get called without a widgetId

Fix critical issues

---

app/client/src/components/propertyControls/ChartDataControl.tsx

Add null check for evaluated value in Chart Data Control

---

app/client/cypress/integration/Smoke_TestSuite/Datasources/PostgresDatasource_spec.js
app/client/cypress/integration/Smoke_TestSuite/ExplorerTests/Entity_Explorer_Datasource_Structure_spec.js
app/client/cypress/integration/Smoke_TestSuite/QueryPane/ConfirmRunAction_spec.js
app/client/cypress/integration/Smoke_TestSuite/QueryPane/MongoDatasource_spec.js
app/client/cypress/integration/Smoke_TestSuite/QueryPane/SwitchDatasource_spec.js
app/client/cypress/support/commands.js
app/client/src/pages/Editor/QueryEditor/Form.tsx
app/client/src/sagas/QueryPaneSagas.ts

Fix switching datasource in the query pane

---

app/client/cypress/integration/Smoke_TestSuite/DisplayWidgets/Image_spec.js
app/client/cypress/locators/commonlocators.json
app/client/cypress/support/commands.js

Updated existing image_spec with,
1.select a zoomlevel
2.Validate the zoom-in
3.Validate the zoom-out

Added a check for zoom feature test

---

app/client/src/pages/Applications/index.tsx

Fix issue where creating a new application twice does not work
Fixes #1712 
Manually

Fix issue where creating a new application twice does not work

---

app/client/docker/templates/nginx-linux.conf.template
app/client/docker/templates/nginx-mac.conf.template

This change forces redirect to https on dev environment.
#1732 
Might be breaking if someone hasn't followed the steps for a local setup and lacks certs.
Manually tested on local

Force redirect https on development nginx server

---

app/server/appsmith-server/src/main/java/com/appsmith/server/constants/FieldName.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/LayoutActionServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutServiceTest.java

Fixed check for incorrect dynamic bindings

---

app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java

Fix mongodb datasource test. 
Fixes appsmithorg/appsmith #1778 
Tested against failing cypress TC.

Fix mongodb datasource test.

---

app/client/cypress/integration/Smoke_TestSuite/ApiFlow/CurlImportFlow_spec.js
app/client/cypress/integration/Smoke_TestSuite/ApiPaneTests/API_Edit_spec.js
app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx
app/client/src/pages/Editor/APIEditor/CurlImportForm.tsx
app/client/src/pages/Editor/APIEditor/Form.tsx

Fixes #1688
Fixes #1689 
Minor addition on the UI
- Manual.
- Added cypress tests for both cases.

Add placeholders on curl import and API create form

---

contributions/docs/TestAutomation.md

Updated contributions with test automation test steps.

Added to contribution docs with Test Automation steps

---

app/client/src/components/designSystems/appsmith/RichTextEditorComponent.tsx

Fix RTE line break render issue
Fixes #831 
Manually

Fix RTE line break issue

---

app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java

When Postgres plugin executes, the main proxy server's event loop thread gets blocked affecting the overall responsiveness of the server
Fixes #1822

Making postgres plugin blocking statements run on elastic threadpool.

---

app/server/appsmith-plugins/mssqlPlugin/src/main/java/com/external/plugins/MssqlPlugin.java
app/server/appsmith-plugins/mssqlPlugin/src/test/java/com/external/plugins/MssqlPluginTest.java

Making MS-SQL plugin blocking statements run on elastic thread pool

---

app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java

Moved my-sql blocking commands to elastic thread pool. 
Fixes #1856 

Making MySql blocking commands run on elastic thread pool

---

app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/plugins/RedisPlugin.java

As part of this PR, all the blocking commands of Redis plugin are scheduled on elastic thread pool so that the main event loop does not get blocked as part of this.
Fixes #1826

Making Redis plugin blocking statements run on elastic thread pool

---

app/client/cypress/plugins/index.js
contributions/docs/TestAutomation.md

Add documentation for using env variables in tests.
Fixes #1886

Use env variables in Cypress tests

---

app/client/src/components/designSystems/appsmith/TableHeader.tsx

It will show number of records on the header of table.
> #1205 

show number of the records

---

README.md

Changes
- Headline
- Added subset of UI widgets

Readme intro section changes

---

contributions/ClientSetup.md

Sorry, I should have left #1926 in draft state before fixing these.

Fix indents in ClientSetup.md

---

app/client/cypress/integration/Smoke_TestSuite/Datasources/RestApiDatasource_spec.js
app/client/src/actions/datasourceActions.ts
app/client/src/components/editorComponents/StoreAsDatasource.tsx
app/client/src/sagas/DatasourcesSagas.ts

Fixes #1922  
Also fixes rest api datasource form not initialising.

Sava api with datasource without having to click on save datasource

---

app/client/src/sagas/index.tsx

Respawn sagas on crash
Fixes #1881
Tested manually locally

Loop sagas to respawn when they crash

---

app/client/start-https.sh

Fix linux local.
Fixes #1946
On WSL
@devrk96 can you pull this branch and confirm that it actually works?

Fix linux local docker setup

---

app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java

1. Add TC in mysql so that any change to database driver can be tested against all the regularly used data types present in mysql.
Fixes appsmithorg/appsmith #1991 
- Build test shows TC passes for current mysql r2dbc driver.

Add a TC to mysql plugin to test all regularly used data types in mysql.

---

deploy/aws_ami/first-time-setup.sh
deploy/aws_ami/init-letsencrypt.sh

Fix request body sent to integromat
Add comma to request body in first-time-setup.sh & init-letsencrypt.sh
We use requestbin to capture the request when start a fresh  instance from ami

Fix setup script for AWS AMI

---

app/client/src/components/propertyControls/TabControl.tsx
app/client/src/sagas/WidgetOperationSagas.tsx
app/client/src/widgets/TabsWidget.tsx

Store tabs name data as array instead of string

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionServiceTest.java

[Bug] Update of an action leads to userSetOnLoad getting reset.

---

app/client/src/sagas/evaluationsSaga.ts

Add empty check on errors
Fixes #2024
Not tested

Fix forEach on undefined

---

app/server/appsmith-server/src/main/java/com/appsmith/server/acl/AppsmithRole.java

Modifying the text for the roles in the share modal

---

app/client/src/api/ApplicationApi.tsx
app/client/src/components/stories/ColorSelector.stories.tsx
app/client/src/components/stories/Menu.stories.tsx
app/client/src/constants/DefaultTheme.tsx
app/client/src/pages/Applications/ApplicationCard.tsx
app/client/src/pages/Applications/helpers.ts
app/client/src/pages/Applications/index.tsx
app/client/src/sagas/ApplicationSagas.tsx

1. Application icon and color was changing on page reload.
2. On creating new application color and icon name needed to be sent too.

Fix: App icon and color name change issue

---

app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx

Evaluated value was not displaying false values correctly. This PR will correctly render this value
Fixes #2050
Manually

Fix for false evaluated value showing as null

---

app/client/src/components/editorComponents/CodeEditor/EditorConfig.ts
app/client/src/components/editorComponents/CodeEditor/index.tsx

Disable matching brackets if we're outside of javascript `mode`
Fixes #1915

Fix brackets mismatch

---

app/client/src/mockResponses/WidgetConfigResponse.tsx

Create a copy of tab data before mutating it
Fixes #2081
N/A

Copy tab data before mutating

---

app/client/public/privacy-policy.html
app/client/public/terms-and-conditions.html
app/server/appsmith-server/src/main/resources/email/welcomeUserTemplate.html

This pull request applies style fixes from code review by [CodeFactor](https://www.codefactor.io).
---
For more information, click [here](https://www.codefactor.io/repository/github/appsmithorg/appsmith/issues).

Apply fixes from CodeFactor

---

app/server/appsmith-plugins/postgresPlugin/pom.xml
app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java
app/server/appsmith-plugins/postgresPlugin/src/test/java/com/external/plugins/PostgresPluginTest.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceContextServiceImpl.java

Adding hikariCP for postgres

---

app/client/src/reducers/uiReducers/applicationsReducer.tsx
app/client/src/sagas/OrgSagas.ts

Redux state is fixed when uploading an organization logo.

Fix: Org logo upload redux state

---

app/client/cypress/fixtures/CanvasResizeDsl.json
app/client/cypress/integration/Smoke_TestSuite/Canvas/Resize_spec.js
app/client/cypress/integration/Smoke_TestSuite/ExplorerTests/Entity_Explorer_DragAndDropWidget_spec.js
app/client/cypress/integration/Smoke_TestSuite/LayoutWidgets/Tab_spec.js
app/client/cypress/locators/commonlocators.json
app/client/cypress/support/commands.js
app/client/src/components/editorComponents/DropTargetComponent.tsx
app/client/src/sagas/WidgetOperationSagas.tsx

- Recalculate canvas rows on delete
Fixes #1919
Added automated test.

Resize canvas on delete widget

---

app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java

Added more configurations for HikariCP

---

app/client/src/components/editorComponents/DraggableComponent.tsx

Unmount the react component during drag
Fixes #612
Fixes #993
manual

unmount during drag

---

app/client/src/sagas/ApiPaneSagas.ts
app/client/src/sagas/QueryPaneSagas.ts

Added null check for actionObj before using it.
Fixes #2113 
N/A

Null check on actionObj before using it

---

app/client/src/components/designSystems/appsmith/ReactTableComponent.tsx
app/client/src/components/designSystems/appsmith/TableColumnMenu.tsx
app/client/src/components/designSystems/appsmith/TableStyledWrappers.tsx
app/client/src/components/designSystems/appsmith/TableUtilities.tsx
app/client/src/constants/Colors.tsx

Update color to #D3DEE3 for non-selectable options in general
Update font-weight specifically for Date Input Format option
Fixes #1635
- manual

update styles for non-selectable, select date format optins

---

app/client/cypress/integration/Smoke_TestSuite/Pages/Pages_spec.js
app/client/src/reducers/entityReducers/actionsReducer.tsx
app/client/src/sagas/PageSagas.tsx

Refactor fetch page actions success 
Fetch page actions after cloning
Fixes #1403 
- manually

fix actions/queries not fetched after cloning a page

---

app/client/src/workers/evaluation.worker.ts

Fixes: #2179
Sanitise the output before sending it across threads

Remove functions for action evals

---

app/client/cypress/integration/Smoke_TestSuite/OrganisationTests/CreateAppWithSameName_spec.js

Test fixed:
manged to split into 2 to avoid intermittent issues

Test split into 2 parts

---

app/client/cypress/integration/Smoke_TestSuite/ApiPaneTests/API_Edit_spec.js
app/client/cypress/locators/apiWidgetslocator.json
app/client/src/pages/Editor/APIEditor/PostBodyData.tsx
app/client/src/sagas/ApiPaneSagas.ts

Add a check for header and key to prevent undefined crash.
Fixes #2202
Automated test

Add headers null check

---

app/client/src/widgets/TableWidget.tsx

Fixed conversation of Unix timestamp in milliseconds
Fixes #2199 

Fixed conversion of Unix timestamp in milliseconds

---

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/DBAuth.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/DatasourceStructureSolution.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceServiceTest.java

Fixes issue with encryption being set to true for empty auth details
Fixes issue with inconsistent check during datasource structure get request
Fixes #2271 
- Fixed Junit tests
- Need help with writing tests for DatasourceStructureSolution, none exist right now

Fixed encryption related bugs for empty/new datasource

---

app/client/src/components/editorComponents/ErrorBoundry.tsx
app/client/src/pages/Editor/QueryEditor/Table.tsx
app/client/src/widgets/BaseWidget.tsx

Wrap the table in error boundary
Fixes #2201
N/A

Wrap Query Table in ErrorBoundary

---

app/client/src/components/designSystems/appsmith/header/DeployLinkButton.tsx
app/client/src/pages/Editor/PropertyPaneTitle.tsx

Small fixes for tooltips
Fixes #2204
Fixes #652 
manually

fix tooltip boundary, don't show on target focus

---

app/client/src/components/designSystems/appsmith/TableUtilities.tsx
app/client/src/widgets/TableWidget.tsx
app/client/src/workers/evaluation.worker.ts

Fixed issues due to improper table input data by modifying table data validations.
Fixes #2263  
Fixes #2264 

Fixed data validation issue

---

app/client/src/mockResponses/WidgetSidebarResponse.tsx
app/client/src/pages/Editor/WidgetSidebar.tsx
app/client/src/reducers/uiReducers/widgetSidebarReducer.ts
app/client/src/selectors/editorSelectors.tsx

- reorder widgets alphabetically
- autofocus search input
Fixes #1622
- manually

reorder widgets alphabetically, autofocus search input

---

app/client/cypress/integration/Smoke_TestSuite/DisplayWidgets/Text_spec.js
app/client/src/components/ads/Toast.tsx
app/client/src/workers/evaluation.worker.ts

Catch circularJSON error and send back a broken but editable evaltree
Fixes #1735.
Not yet

Hotfix circularJSON

---

app/client/src/components/editorComponents/EditableText.tsx

Expect a few of these in the next couple of days as all old PRs come in.

Prettier fix for release

---

app/client/src/pages/Editor/Explorer/Entity/index.tsx

Prettier has been changed to be more in line with eslint defaults.
@akash-codemonk please merge `release` into your open branches and then run to make sure your PRs don't cause issues on other people's local.
```
npx prettier --write src/**/*.ts*
```

Prettier fixes

---

app/client/cypress/integration/Smoke_TestSuite/Pages/Pages_spec.js

update test so that it doesn't on the order of the tabs

update tooltip test so that it doesn't rely on the pages tab sequence

---

app/client/src/workers/evaluation.worker.ts

Send clean validated tree back

---

app/client/src/pages/Editor/Explorer/ExplorerSearch.tsx
app/client/src/pages/Editor/WidgetSidebar.tsx

Focus just widget search and not entity search
- manual

only autofocus widget search

---

app/client/cypress/integration/Smoke_TestSuite/Binding/momentBasictest_spec.js

updated assertion

---

app/client/src/sagas/ErrorSagas.tsx

Check of undefined error payload
Fixes #2422
- manually

fix: check for undefined error action payload

---

app/client/src/entities/DataTree/dataTreeFactory.ts
app/client/src/sagas/ActionExecutionSagas.ts
app/client/src/sagas/EvaluationsSaga.ts
app/client/src/workers/evaluation.worker.ts

There was a toast message shown to the user on action execution regarding and unexpected error when evaluating. This was because of bad execution params being sent for evaluation. This PR fixes the issue
Fixes #2432
Fixes: #2429
> Manually

Fix invalid toast message for evaluation error

---

app/client/cypress/integration/Smoke_TestSuite/Onboarding/Onboarding_spec.js
app/client/src/constants/OnboardingConstants.tsx
app/client/src/pages/Editor/EditorHeader.tsx
app/client/src/sagas/OnboardingSagas.ts

Hide other header elements while showing the deploy button

---

app/client/src/sagas/ApplicationSagas.tsx

Open the already opened tab if it exists when clicking on deploy

---

app/client/src/mockResponses/WidgetConfigResponse.tsx
app/client/src/pages/Editor/APIEditor/Pagination.tsx

Fix widths for pagination test and modal confirm btns
- manually

Fix widths for pagination test and modal confirm btns

---

app/server/appsmith-plugins/pom.xml
app/server/appsmith-plugins/redshiftPlugin/plugin.properties
app/server/appsmith-plugins/redshiftPlugin/pom.xml
app/server/appsmith-plugins/redshiftPlugin/src/main/java/com/external/plugins/RedshiftPlugin.java
app/server/appsmith-plugins/redshiftPlugin/src/main/resources/editor.json
app/server/appsmith-plugins/redshiftPlugin/src/main/resources/form.json
app/server/appsmith-plugins/redshiftPlugin/src/main/resources/templates/CREATE.sql
app/server/appsmith-plugins/redshiftPlugin/src/main/resources/templates/DELETE.sql
app/server/appsmith-plugins/redshiftPlugin/src/main/resources/templates/SELECT.sql
app/server/appsmith-plugins/redshiftPlugin/src/main/resources/templates/UPDATE.sql
app/server/appsmith-plugins/redshiftPlugin/src/test/java/com/external/plugins/RedshiftPluginTest.java
app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/MongoConfig.java
app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java

1. Re-merge redshift plugin.
Fixes appsmithorg/appsmith #1267 
Tested post adding Trisha's fix:  https://github.com/appsmithorg/appsmith/pull/2464 
1. By running against mongo data of internal release server.
2. By running against mongo data of prod server.

Redshift plugin

---

app/client/cypress/integration/Smoke_TestSuite/Binding/TableWidgets_NavigateTo_Validation_spec.js
app/client/cypress/locators/Widgets.json
app/client/cypress/support/commands.js

1.removed redundant code.
2.Fixed a flaky test

flaky test updated

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java

Sample output logs now are :
```
- [nioEventLoopGroup-2-2]Execute Action called in Page 5fe9c76a2e89c727342bcada, for action id : 5fe9c7bb2e89c727342bcadd  action name : Query1, DatasourceConfiguration(connection=Connection(mode=READ_WRITE, type=null, ssl=null, defaultDatabaseName=null), endpoints=[Endpoint(host=fake-api.cvuydmurdlas.us-east-1.rds.amazonaws.com, port=5432)], authentication=DBAuth(authType=null, username=postgres, password=c2e41857714558b1488c1c8a63661f9962bb4d2ceeca5633900fbc9c5b75edb8, databaseName=fakeapi), sshProxy=null, sshProxyEnabled=false, properties=null, url=null, headers=null), ActionConfiguration(timeoutInMillisecond=10000, paginationType=NONE, path=null, headers=null, queryParameters=null, body=SELECT * FROM users ORDER BY id LIMIT 15; , bodyFormData=null, …
```

Adding action execution time to logs

---

app/client/cypress/integration/Smoke_TestSuite/Binding/Bind_TableTextPagination_spec.js

Updated test with wait for a route

wait for postExecute

---

app/client/src/sagas/ActionExecutionSagas.ts

Adds a new field to an exsting event

added appmode analytics to the execute action

---

app/client/src/components/editorComponents/ActionNameEditor.tsx
app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx
app/client/src/pages/Editor/APIEditor/Form.tsx

- Placeholder added in the search component
- Height of section API header section fixed

Fix: API pane style and integration changes

---

app/client/src/components/editorComponents/Onboarding/Tooltip.tsx
app/client/src/constants/OnboardingConstants.tsx
app/client/src/pages/Editor/EditorHeader.tsx
app/client/src/sagas/OnboardingSagas.ts

Show deploy tooltip if the user clicks anywhere after the binding success tooltip appears.

Onboarding deploy tooltip fix

---

app/client/src/components/designSystems/appsmith/TextInputComponent.tsx
app/client/src/pages/organization/CreateOrganizationForm.tsx

autofocus create organization form input
Fixes #2303

auto focus create org input field

---

app/client/src/workers/evaluation.worker.ts
app/client/src/workers/evaluationUtils.test.ts
app/client/src/workers/evaluationUtils.ts

They should only have property paths and not entity names themselves.

Sub tree fixes for issues found on Jarvis

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/LayoutActionServiceImpl.java

Adding id and pluginType correctly for a user set on page load action(non referenced in the DSL)

---

app/client/src/sagas/WidgetOperationSagas.tsx
app/client/src/utils/WidgetPropsUtils.tsx

Fix for tabs widget getting the same name

---

app/client/cypress/fixtures/datasources.json
app/client/cypress/integration/Smoke_TestSuite/QueryPane/MongoDatasource_spec.js
app/client/cypress/locators/DatasourcesEditor.json
app/client/cypress/support/commands.js

Updated mogodatasource test:
host:cypress-test.zljea.mongodb.net
Default Database name: sample_airbnb
Username: cypress-test
Password: RaopEmky505xYV4p
updated the test to change the connection type to the Replica set

Updated mongodatasource tests

---

app/client/src/components/editorComponents/LightningMenu/LightningMenuTrigger.tsx
app/client/src/components/editorComponents/LightningMenu/index.tsx
app/client/src/pages/common/CustomizedDropdown/StyledComponents.tsx

- Lightening menu border style fixed
- Arrow icon position fixed

Fix: Lightening Menu styles

---

app/client/src/pages/Applications/ProductUpdatesModal/UpdatesButton.tsx

Set min/max widths for new updates count tag
- manually

update styles for new updates count

---

app/client/src/constants/DefaultTheme.tsx
app/client/src/pages/Applications/ProductUpdatesModal/ReleaseComponent.tsx
app/client/src/pages/Applications/ProductUpdatesModal/UpdatesButton.tsx
app/client/src/pages/Applications/ProductUpdatesModal/index.tsx

Remove box-shadow and add hover states for modal elements
- manual

update release modal styles

---

app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ActionController.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java

In case an action has been deleted in unpublished state, dont return it to the user in edit mode.

---

app/client/src/workers/evaluation.worker.ts

Removes any functions that could in the result of a action binding.
Fixes #2654 

Remove functions from Eval Action bindings task returning from the worker

---

app/client/src/widgets/TableWidget.tsx

Show table columns in selectedRow autocomplete irrespective of table row selection
Fixes #1425 

Fix-Show table columns in selectedRow autocomplete irrespective of table row selection

---

app/client/src/workers/evaluation.worker.ts
app/client/src/workers/evaluationUtils.ts

Sanitise worker responses to remove any accidental functions
Fixes #2692 

Sanitise any other possible place which could send functions

---

contributions/ServerSetup.md

the documentation is not very clear on how to  run programs in IntelliJ IDEA
documentation improvement
yes

improve doc for setting up IntelliJ IDEA

---

app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java
app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java

Fixed null endpoint issue for MySQL plugin

---

app/client/src/components/editorComponents/actioncreator/ActionCreator.tsx
app/client/src/constants/routes.ts
app/client/src/sagas/ActionExecutionSagas.ts
app/client/src/utils/autocomplete/EntityDefinitions.ts
app/client/src/workers/evaluation.worker.ts

navigateTo new window
Fixes #2644 

Support for navigateTo function to open in new window

---

app/client/src/widgets/MapWidget.tsx

Update changed initial location in map 
Fixes #2711 
-Manually tested

Update changed initial location in map 

---

app/client/cypress/integration/Smoke_TestSuite/FormWidgets/FilePicker_spec.js
app/client/cypress/support/commands.js

action on the file selected updated to API call

updated action on file selected

---

app/client/start-https.sh
app/server/scripts/start-dev-server.sh
app/util/is_wsl.sh
app/util/is_wsl_test.sh

Fixes https://github.com/appsmithorg/appsmith/issues/2728
- Breaking change (fix or feature that would cause existing functionality to not work as expected)?
- This change requires a documentation update?
Reset dev environment and ran through the guide with the updated .env

Suggest server dev example .env to use IPv4 by default

---

app/server/appsmith-server/src/main/java/com/appsmith/server/constants/FieldName.java
app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/RestApiImportController.java
app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/GlobalExceptionHandler.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/CurlImporterService.java

Modified error displayed to user on generic bad request

---

app/client/src/pages/Editor/DataSourceEditor/DBForm.tsx
app/client/src/pages/Editor/DataSourceEditor/DatasourceSection.tsx

Hides sections that have `hidden` set to true.
Fixes #2633
Fixes #1804
Manually

Do not show sections that are supposed to be hidden

---

app/client/src/pages/Editor/Explorer/Entity/Name.tsx
app/client/src/sagas/PageSagas.tsx

Changing the tab name from the entity explorer changes the canvas widget name. This PR fixes this issue.
Fixes #2774 
Manually

Fix tab name update from the entity explorer

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/LayoutActionServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutActionServiceTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutServiceTest.java

Piped onpageload update function

---

app/server/appsmith-plugins/dynamoPlugin/src/main/java/com/external/plugins/DynamoPlugin.java
app/server/appsmith-plugins/dynamoPlugin/src/test/java/com/external/plugins/DynamoPluginTest.java

Fixes #2812 
- Added JUnit test

Fixed handling of lists in dynamodb

---

app/client/src/components/propertyControls/StyledControls.tsx
app/client/src/constants/DefaultTheme.tsx

- Update page context menu background
- unset menu border radius
Fixes #2085
- manually

Update page context menu background

---

app/client/cypress/integration/Smoke_TestSuite/Auth/Redirects__spec.js
app/client/cypress/support/commands.js
app/client/src/pages/UserAuth/index.tsx
app/client/src/pages/UserAuth/requiresAuthHOC.tsx

Redirect from auth pages -> applications if the user is logged in
Fixes #2768
- test spec

Fix: redirect to applications page from auth pages when the user is logged in 

---

app/client/cypress.json
app/client/src/components/designSystems/blueprint/DatePickerComponent.tsx
app/client/src/components/propertyControls/DatePickerControl.tsx
app/client/src/widgets/DatePickerWidget.tsx

Date widget crash due to invalid date in date picker issue fixed

Date widget crash due to invalid date in date picker

---

app/client/src/pages/Editor/DataSourceEditor/DBForm.tsx
app/client/src/pages/Editor/DataSourceEditor/DatasourceSection.tsx
app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
app/client/src/pages/Editor/DataSourceEditor/index.tsx

Copy DBForm into a new file, add logic in DataSourceEditor to manage loading directly.
Once this change gets merged, restAPIDatasource becomes free to modify code internally without worrying about changes outside the file.

Prep for a separate RestAPIDatasource

---

app/server/appsmith-plugins/postgresPlugin/pom.xml

[Ref](https://github.com/testcontainers/testcontainers-java/issues/3574) issue with container dependency

Switched test container version for Postgres

---

app/client/cypress/integration/Smoke_TestSuite/OrganisationTests/ShareAppTests_spec.js

updated flaky test

---

app/client/cypress/integration/Smoke_TestSuite/DisplayWidgets/Map_spec.js

updated test by removing an unwanted step

Remove unwanted step in Cypress Map widget test

---

app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ActionController.java
app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/LayoutController.java
app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/LayoutActionUpdateDTO.java
app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/LayoutDTO.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/LayoutActionService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/LayoutActionServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutActionServiceTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutServiceTest.java

Communicate action execute on load changes in update layout

---

.deepsource.toml
app/client/src/components/ads/Button.tsx
app/client/src/components/ads/EditableText.tsx
app/client/src/components/designSystems/appsmith/PopoverVideo.tsx
app/client/src/components/designSystems/appsmith/TableHeader.tsx
app/client/src/components/designSystems/appsmith/help/HelpModal.tsx

Hi :wave: I ran the [DeepSource](https://deepsource.io) static analyzer on the forked copy of this repo and found some [interesting code quality issues](https://deepsource.io/gh/withshubh/appsmith/issues/). This PR fixes a few of them.
- Removed `true` from boolean attribute 
- added .deepsource.toml file

Refactor: remove `true` from boolean attribute

---

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/exceptions/pluginExceptions/AppsmithPluginError.java
app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/DatasourceTestResult.java
app/server/appsmith-interfaces/src/test/java/com.appsmith.external.models/DatasourceTestResultTest.java
app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java

Added null check for error messages

---

contributions/ServerSetup.md

1. Add Discord channel link to server setup guide file.
Fixes #2901 

Add discord channel link to Server Setup guide.

---

app/client/package.json
app/client/start-https.sh
contributions/ClientSetup.md

>
host.docker.internal seems to have a problem in M1 chip macbooks, added changes by @rishabhsaxena to start-https.sh and added documentation and new start-m1 script in package.json.
Fixes #2957 
Try setting up the appsmith client in a M1 chip macbook.

Fix Local setup changes to accommodate M1 chip Macbooks.

---

app/server/appsmith-plugins/amazons3Plugin/src/main/resources/form.json

1. Add encrypted logo to password.
2. Enable save on empty username / password.
Fixes #2970 #2972 

Modify datatsource creation form for AmazonS3

---

app/client/cypress/integration/Smoke_TestSuite/Onboarding/Onboarding_spec.js

Do not delete application as retried tests stop working.
Works locally

Onboarding test fix

---

app/client/src/pages/Editor/QueryEditor/QueryHomeScreen.tsx
app/client/src/sagas/ActionSagas.ts
app/client/src/selectors/entitiesSelector.ts

Fix default values not sent as payload while creating a new action
Fixes #2973
- existing tests should pass

S3 Plugin: Fix default values not sent as payload while creating a new action

---

app/client/src/pages/UserAuth/SignUp.tsx

Follow the same sequence while displaying oauth options for Signup & Login
- manually

Follow the same sequence while displaying oauth options for Signup & Login

---

app/client/src/constants/DefaultTheme.tsx

>
Shrinking Entity explorer
Fixes #2918
Size of entity explorer
- Test A
- Test B

Fix: Shrink Entity explorer by 20%

---

app/client/src/constants/messages.ts
app/client/src/pages/Editor/WidgetSidebar.tsx

Remove message shown on the widget sidebar.
Fixes #3053 
Manually

Update message on the widget sidebar

---

app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java
app/server/appsmith-plugins/amazons3Plugin/src/main/resources/editor.json
app/server/appsmith-plugins/amazons3Plugin/src/test/java/com/external/plugins/AmazonS3PluginTest.java

- Return expiry date when signed URL is generated - for List and Create actions.
- In List action, make url expiry field dependent on 'Generate signed url' toggle.
- Rename labels.
- Change expiry duration input to minutes instead of milliseconds.
- Set default value for expiry duration.
- Update TCs.
Fixes #3078
https://user-images.githubusercontent.com/1757421/108202107-a4b66b80-7146-11eb-8d9d-c533a56e375f.mov

Enchancements for AWS S3 plugin

---

app/client/src/api/Api.tsx

[error.response](https://github.com/appsmithorg/appsmith/blob/fix/action-run-error/app/client/src/api/Api.tsx#L63) is undefined when there is no internet. [makeExecuteActionResponse](https://github.com/appsmithorg/appsmith/blob/fix/action-run-error/app/client/src/api/Api.tsx#L33) tries to access `response.data` hence the error.
Fixes #2872 
Manually

Fix execute action error message

---

app/client/src/pages/AppViewer/viewer/AppViewerHeader.tsx

Fix styles for the primary logo at the viewer for safari
Fixes #3126
- manually

Fix styles for the primary viewer logo for safari

---

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/AuthenticationService.java

Added null check for OAuth2 scopes

---

app/client/src/components/designSystems/appsmith/TableComponent/Table.tsx
app/client/src/components/designSystems/appsmith/TableComponent/index.tsx
app/client/src/utils/WidgetRegistry.tsx
app/client/src/utils/migrations/TableWidget.ts
app/client/src/widgets/IconWidget.tsx
app/client/src/widgets/SkeletonWidget.tsx
app/client/src/widgets/TableWidget/index.tsx

When opening non-migrated application in view mode, the selectedRow wasn't working.

Fix selected row issue in view mode

---

README.md

Updated readme to include the office hours link

Update README.md to include office hours link

---

app/client/src/components/propertyControls/LocationSearchControl.tsx

Fix issue when searching for certain places does not return a list from the location search control
Fixes #3196 
By generating this crash manually.

Location Search Control Crash

---

app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx

Removes check from `RestAPIDatasourceForm`
Fixes #3103

Remove validation for authtype Oauth

---

app/client/src/components/ads/Dropdown.tsx
app/client/src/components/designSystems/blueprint/DropdownComponent.tsx
app/client/src/components/editorComponents/form/fields/DropdownFieldWrapper.tsx
app/client/src/components/propertyControls/DropDownControl.tsx
app/client/src/components/propertyControls/StyledControls.tsx
app/client/src/constants/DefaultTheme.tsx

> add ads dropdown in property pane

add ads dropdown in property pane

---

app/client/cypress/fixtures/ChartDsl.json
app/client/cypress/fixtures/testdata.json
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Chart_Data_point_spec.js
app/client/cypress/support/commands.js

Added use case with char datapoint validation

WIP : Added test for chart datapoint validation

---

app/server/appsmith-plugins/dynamoPlugin/src/main/java/com/external/plugins/DynamoPlugin.java
app/server/appsmith-plugins/dynamoPlugin/src/test/java/com/external/plugins/DynamoPluginTest.java

remove raw response from transformed response structure.
Fixes #3208 
- manual

Internal fix: Remove raw response from transformed DynamoDB response structure.

---

app/client/src/components/designSystems/appsmith/TableComponent/TableHelpers.ts
app/client/src/components/designSystems/appsmith/TableComponent/TableUtilities.tsx
app/client/src/components/propertyControls/ComputeTablePropertyControl.tsx
app/client/src/utils/WidgetPropsUtils.tsx
app/client/src/utils/migrations/TableWidget.ts
app/client/src/widgets/TableWidget/derived.js
app/client/src/widgets/TableWidget/index.tsx

Fix issue where column ids have spaces in them leading to a crash
Fix hidden columns migration
Manually

Internal Fix: Migration issues with Table widget

---

app/client/src/components/propertyControls/DatePickerControl.tsx

Add min max values to datepicker control
Manually

Add min max values to datepicker control

---

app/client/src/components/ads/EditableText.tsx
app/client/src/components/editorComponents/ActionNameEditor.tsx
app/client/src/components/editorComponents/EditableText.tsx
app/client/src/pages/Editor/Explorer/Entity/Name.tsx
app/client/src/reducers/uiReducers/apiNameReducer.ts
app/client/src/sagas/ApiPaneSagas.ts
app/client/src/sagas/QueryPaneSagas.ts

Fix renaming action goes to the action page 

---

app/client/cypress/locators/Layout.json
app/client/src/components/designSystems/appsmith/DraggableListComponent.tsx
app/client/src/components/designSystems/appsmith/TabsComponent.tsx
app/client/src/components/propertyControls/StyledControls.tsx
app/client/src/components/propertyControls/TabControl.tsx
app/client/src/mockResponses/WidgetConfigResponse.tsx
app/client/src/widgets/TabsWidget.tsx

Allow individual tabs to be shown/hidden using isVisible property and from property pane controls.

Added functionality to show/hide a tab from tab property pane controls

---

app/client/src/sagas/QueryPaneSagas.ts

Use payload data that we already have instead of risking a race.
Fixes #3204
Difficult to test as this is a race issue

Fix race between action reducer and handleQueryCreatedSaga

---

app/client/src/components/ads/CopyToClipBoard.tsx
app/client/src/components/formControls/DropDownControl.tsx
app/client/src/components/formControls/InputTextControl.tsx
app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
app/client/src/pages/organization/AppInviteUsersForm.tsx

Display redirect URL for auth code flow
Manually

Redirect URL for oAuth Auth code flow

---

app/client/src/components/ads/EditableText.tsx
app/client/src/components/editorComponents/EditableText.tsx

Update useEffect dependency

---

app/client/src/sagas/OnboardingSagas.ts

Adds a validation to check if organisation is defined. Unsure how there could be no organisations. 
Fixes #3240
Manual

Fix fetching correct organisation during onboarding

---

app/client/src/components/ads/DatePickerComponent.tsx
app/client/src/components/ads/common.tsx
app/client/src/components/propertyControls/DatePickerControl.tsx
app/client/src/components/propertyControls/StyledControls.tsx
app/client/src/index.css

add ads dateinput in propertypane

---

app/client/src/components/editorComponents/actioncreator/ActionCreator.tsx
app/client/src/sagas/ActionExecutionSagas.ts
app/client/src/utils/autocomplete/EntityDefinitions.ts
app/client/src/workers/evaluationUtils.ts

Adds `resetWidget` feature.
Fixes #2335
- Test A
- Test B

Reset widget global function

---

app/server/appsmith-plugins/firestorePlugin/src/main/resources/form.json
app/server/appsmith-plugins/mongoPlugin/src/main/resources/form.json

- fix label for "placeholderText" in form.json for a few plugins. This configuration in form.json displays placeholder text.
- manual

fix placeholderText label in form.json files

---

app/client/src/widgets/TabsWidget.tsx
app/client/src/workers/validations.ts

Fixed tabs widget crash due to invalid data
Fixes #3182 

Fixed tabs widget crash due to invalid data

---

README.md
office_hours.md

>
Created a dedicated office hours page in the github repo.
No need to test as this is part of documentation

Akshay office hours page

---

app/client/src/workers/validations.test.ts
app/client/src/workers/validations.ts

Fixes chart validation after it broke from more granular property updates

fix chart validation

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Modal_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DynamicLayout/DynamicLayout_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ExplorerTests/Entity_Explorer_Entity_Naming_conflict_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ExplorerTests/Entity_Explorer_Tab_rename_Delete_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/DatePicker_2_Default_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/DatePicker_2_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/DatePicker_Toggle_js_spec.js

Moved tests to client and server-side

grouping another set of tests

---

app/client/src/components/propertyControls/DatePickerControl.tsx

> add date action bar in property pane

add date actionbar in propertypane

---

app/client/cypress/manual_TestSuite/Modal_Spec.js
app/client/cypress/manual_TestSuite/new_Table_Spec.js

Adding test cases for Table

---

app/client/cypress/fixtures/example.json
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_spec.js
app/client/cypress/support/commands.js
app/client/src/components/designSystems/appsmith/TableComponent/TableUtilities.tsx

Work in progress for a fix for #2753
- This change requires a documentation update?
Submitting as a draft until testing is figured out in my new WSL2 environment.

Adds support for base64 image strings to image cells

---

app/client/src/components/ads/Tooltip.tsx
app/client/src/pages/AppViewer/viewer/PageTabs.tsx
app/client/src/pages/Applications/ApplicationCard.tsx

api pane close tooltip fix

---

app/client/src/components/editorComponents/CodeEditor/styledComponents.ts
app/client/src/components/editorComponents/form/fields/KeyValueFieldArray.tsx
app/client/src/constants/Colors.tsx
app/client/src/constants/DefaultTheme.tsx

> api pane key value style fix

api pane key value style fix

---

app/client/src/components/ads/Dropdown.tsx
app/client/src/components/ads/MultiselectDropdown.tsx
app/client/src/components/ads/TreeDropdown.tsx

fix menu height

---

app/client/src/sagas/OnboardingSagas.ts

Fix incorrect property being validated
Fixes #3446 
Manually

Fix: Incorrect validation of image src in onboarding

---

app/client/src/components/propertyControls/ChartDataControl.tsx
app/client/src/pages/Editor/PropertyPane/PropertyHelpLabel.tsx
app/client/src/widgets/ChartWidget/propertyConfig.ts

property data chart ui fix

---

app/client/src/components/designSystems/appsmith/help/DocumentationSearch.tsx
app/client/src/components/designSystems/appsmith/help/HelpModal.tsx

Moved the initialization code so that it works at the editor header.
Fixes: #3462 
- manually

Fix chat with us button at the editor help menu

---

app/client/src/components/ads/Toast.tsx
app/client/src/sagas/EvaluationsSaga.ts
app/client/src/workers/DataTreeEvaluator.ts

Improve logging in sentry and messaging to the user

Improve cylical dependency error

---

app/client/cypress/support/index.js
app/client/src/components/ads/AppIcon.tsx

Fixes unreachable code issues reported by deepsource
Fixes #3482 
All existing tests should pass.

Fix unreachable code reported by deepsourcelabs

---

app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java
app/server/appsmith-plugins/dynamoPlugin/src/main/java/com/external/plugins/DynamoPlugin.java
app/server/appsmith-plugins/elasticSearchPlugin/src/main/java/com/external/plugins/ElasticSearchPlugin.java
app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/FirestorePlugin.java
app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
app/server/appsmith-plugins/mssqlPlugin/src/main/java/com/external/plugins/MssqlPlugin.java
app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java
app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java
app/server/appsmith-plugins/redisPlugin/src/main/java/com/external/plugins/RedisPlugin.java
app/server/appsmith-plugins/redshiftPlugin/src/main/java/com/external/plugins/RedshiftPlugin.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java

Plugin level : Catch all exceptions and set request in the result
Server level : Adding new fields to analytics : `isSuccessfulExecution`, `statusCode`, `timeElapsed` and `error` (in case of unsuccessful execution)

Enrichment of analytics event for execute.

---

app/client/src/components/ads/Checkbox.tsx

fix API settings page is not getting updated
Fixes #3191

Fix api settings page not getting updated

---

app/client/src/pages/AppViewer/index.tsx
app/client/src/pages/AppViewer/viewer/AppViewerHeader.tsx
app/client/src/pages/Applications/ForkApplicationModal.tsx

- Show fork modal while returning back after signing in
- Show loaders where required.
Manually with applications/6034ff4472504469bd50ed42/pages/6034ff4472504469bd50ed44

Fix: Fork application improvements

---

app/client/src/workers/DataTreeEvaluator.ts
app/client/src/workers/evaluate.test.ts
app/client/src/workers/evaluate.ts
app/client/src/workers/evaluation.worker.ts
app/client/src/workers/evaluationUtils.ts

Extract out evaluate function and add unit tests

---

app/client/src/components/editorComponents/GlobalSearch/Description.tsx
app/client/src/components/editorComponents/GlobalSearch/SearchResults.tsx
app/client/src/components/editorComponents/GlobalSearch/index.tsx
app/client/src/components/editorComponents/GlobalSearch/useRecentEntities.tsx
app/client/src/components/editorComponents/GlobalSearch/utils.tsx
app/client/src/constants/DefaultTheme.tsx
app/client/src/pages/Editor/HelpButton.tsx
app/client/src/sagas/GlobalSearchSagas.ts

Small global search updates:
- Update help button styles
- Keep the last entity on top by slicing the current one
- Manually

Small global search updates

---

app/client/src/widgets/TableWidget/index.tsx

Save updated table row height in application edit mode
- Test A
- Test B

Save updated table row height in application edit mode

---

app/client/src/components/designSystems/appsmith/TableComponent/CascadeFields.tsx

Fix AND/OR visibility in table widget filters
Fixes #2834 

Fix AND/OR visibility in table widget filters

---

app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx

Wrap evaluated data in computed value field
Fixes #2824 
- Test A
- Test B

Wrap evaluated data in computed value field

---

app/client/src/components/ads/Dropdown.tsx
app/client/src/components/ads/Icon.tsx
app/client/src/constants/DefaultTheme.tsx

> add icon and subText in ads dropdown

add icon and subText in ads dropdown

---

app/server/appsmith-server/src/main/java/com/appsmith/server/constants/AnalyticsEvents.java
app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/LayoutActionServiceImpl.java

- Changes to push a new analytics event at "update_layout" for every change in the layout
- Logging improved to display dsl when it breaks

Added logs and analytics

---

app/client/src/components/editorComponents/GlobalSearch/HelpBar.tsx
app/client/src/components/editorComponents/GlobalSearch/SearchResults.tsx

Minor globalsearch fixes

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Onboarding/Onboarding_spec.js
app/client/cypress/support/commands.js

Onboard spec: Instead of wait, added a check to wait for the loading spinner to disappear 
Table_Property_Pane spec updated test to scroll to element and click

WIP :udpated flaky tests

---

office_hours.md

Adds summary for Mar 18 office hours

chore: Adds summary for Mar 18 office hours

---

app/client/cypress/manual_TestSuite/Page_Features_Spec.js
app/client/cypress/manual_TestSuite/new_Table_Spec.js

1) Added test ideas for binding a datepicker widget to a custom column

Added test ideas for Table and Hide feature of the page 

---

app/client/src/widgets/TabsWidget.tsx

Added check to ensure tabs is Array before using array methods
Fixes #3454 
- Test A
- Test B

Added check to ensure tabs is Array before using array methods

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Onboarding/Onboarding_spec.js
app/client/src/sagas/OnboardingSagas.ts

This PR fixes the failing Cypress test for the onboarding flow

Fix onboarding Cypress test

---

office_hours.md

chore: Updates office hours

---

app/client/src/components/designSystems/appsmith/help/DocumentationSearch.tsx
app/client/src/constants/DefaultTheme.tsx

Fix editor help menu background color and icon size
- Manually

Fix editor help menu background color and icon size

---

app/client/cypress/manual_TestSuite/Switch_Widget_Spec.js

Added scenarios for switch widget
1) Simple "switch widget" functionality check
2) Added "switch widget" into "Form widget" and check for reset of widget

Adding test ideas for Switch widget

---

app/client/src/components/propertyControls/PrimaryColumnsControl.tsx
app/client/src/components/propertyControls/TabControl.tsx

Fix to add debounce to renaming tabs.
Fix to add state of visibility to tab property controls.
- Test A
- Test B

Fix: Adding debounce for renaming tabs.

---

app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java
app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java

- Fix regex for whitespace.
Fixes #3107 
- Manual
- Junit TCs

fix regex for whitespace

---

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/PolicyUtils.java

Bug fix : App viewer inviting another app viewer would assign correct permissions to applications

---

app/client/src/components/ads/DatePickerComponent.tsx
app/client/src/components/ads/Tooltip.tsx
app/client/src/components/editorComponents/ActionCreator.tsx

Property pane improvements bug fixes
Fixes #3760 
Fixes #3763 
Fixes #3771 
- Test A
- Test B

Fix: Property pane improvements and bug fixes

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/Table_Property_ToggleJs_With_Binding_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_Derived_Column_Data_validation_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_GeneralProperty_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GlobalSearch/GlobalSearch_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/LayoutWidgets/Tab_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Onboarding/Onboarding_spec.js
app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OrganisationTests/CreateOrgTests_spec.js
app/client/cypress/support/commands.js

Ignore cypress/no-unnecessary-waiting

Ignore cypress/no-unnecessary-waiting

---

app/client/src/components/editorComponents/ActionCreator.tsx
app/client/src/components/editorComponents/LightningMenu/index.tsx

Listing SAAS pluginType in the API sub-menus of the lightning menu to quickly bind to them.
Fixes #3787 

List SAAS plugin type actions under lightning menu apis

---

app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java
app/server/appsmith-plugins/postgresPlugin/src/test/java/com/external/plugins/PostgresPluginTest.java

Bug Fix : PSQL Prepared Statement - Handling exception for bindings in commented part of query

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_PropertyPane_spec.js
app/client/cypress/locators/commonlocators.json
app/client/cypress/support/commands.js

Updated one of the assert conditions
Also removed unused method

updated table property pane test

---

app/client/public/index.html

Update GTM script.
Would also need to update the env variable: 
`REACT_APP_GOOGLE_ANALYTICS_ID` as `GTM-WK943F8`
- Would need to verify this manually

Update GTM script

---

app/server/appsmith-plugins/mongoPlugin/src/main/resources/editor.json
app/server/appsmith-plugins/mssqlPlugin/src/main/resources/editor.json
app/server/appsmith-plugins/mysqlPlugin/src/main/resources/editor.json
app/server/appsmith-plugins/postgresPlugin/src/main/resources/editor.json

Add evaluationSubstitutionType in postgres editor form

Update editor.json for Postgres, Mongo, MySQL, MS-SQL adding evaluation type

---

app/client/src/actions/datasourceActions.ts
app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
app/client/src/pages/Editor/SaaSEditor/DatasourceForm.tsx
app/client/src/sagas/DatasourcesSagas.ts

REST API code was replaced by saasAPI. So the rest API was also using SaasAPI function to redirect while auth
Fixes #3830 

code for REST added

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/CurlImporterService.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/CurlImporterServiceTest.java

Fixed curl import without valid tokens

---

README.md

Add Tutorials to Readme

---

app/client/src/components/formControls/DynamicInputTextControl.tsx
app/client/src/components/formControls/DynamicTextFieldControl.tsx
app/client/src/components/formControls/utils.test.ts
app/client/src/components/formControls/utils.ts

Evaluated Value is displayed as undefined by passing valid Request Query in google sheets
Fixes #4008 

binding path added for query input field

---

app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/QueryPane/EmptyDataSource_spec.js

Empty DS creation
Error message check while query creation

Basic DS test scenarios

---

app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ActionCollectionServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/CurlImporterService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ItemServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/LayoutActionService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/LayoutActionServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ExamplesOrganizationCloner.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionServiceTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceServiceTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutActionServiceTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutServiceTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/PageServiceTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ShareOrganizationPermissionTests.java

[Bug fix] : Disallowing action creation with existing names from the page

---

app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/AppendMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/BulkAppendMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/BulkUpdateMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/DeleteSheetMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/MethodConfig.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/constants/GoogleSheets.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/domains/RowObject.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/resources/editor.json

- Fixed QA bugs
- Split delete sheet into two
- Removed dynamic query input types from hidden keys
Fixes #4011

Bug fixes and enhancements

---

app/client/cypress/fixtures/resetPassword.json
app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/UserProfile/UpdateUsersName_spec.js

Profile tests:
1.email validation
2.Reset pwd

WIP:Updated profile tests

---

app/client/src/components/editorComponents/form/fields/EmbeddedDatasourcePathField.tsx

Edit datasource should be always enabled
Fixes #3978 

REST API datasource edit should be always enabled

---

README.md

Update links and add GraphQL tutorial

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_PropertyPane_spec.js

Collapse/Open property pane test removed

removed test for collapse/open Property pane

---

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/annotations/encryption/EncryptionHandler.java
app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/MongoConfig.java

Reverting use of Mongo Listener since we aren't applying this yet

---

app/client/cypress/fixtures/example.json
app/client/cypress/fixtures/textDsl.json
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Text_new_feature_spec.js
app/client/cypress/support/commands.js

Text widget tests:
1.Text color
2.Text style

WIP: Added new test for Text widget

---

app/client/src/api/ActionAPI.tsx
app/client/src/components/formControls/utils.test.ts
app/client/src/components/formControls/utils.ts
app/client/src/sagas/ActionSagas.ts

fix the initialValue config exists check because `false` value would not set the correct initial value in the action
Also removed some unused Action API methods and renamed others

Fix initial value check for action form config

---

app/client/src/components/designSystems/appsmith/MapComponent.tsx

MapComponent markers prop can be empty, but it tries to access the map method on the prop without checking if its defined or it is an array.
Fixes #3843

Fix map method being called on undefined variable  in MapComponent #3843

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java

> This feature will add analytics datapoint for users invited to organization
> Expected fields in the datapoints : Number of users invite and emails of users
> Checked if the functionality for user invitation in organization is not hampered

Added new analytics datapoint to capture invite users event

---

app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/AppendMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/BulkAppendMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/BulkUpdateMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/ClearMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/CopyMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/DeleteRowMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/DeleteSheetMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/GetValuesMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/InfoMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/UpdateMethod.java

Modified error text when spreadsheet url is missing

---

app/client/cypress/fixtures/executionParamsDsl.json
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ActionExecution/ExecutionParams_spec.js

Revert ExecutionParams test change made at https://github.com/appsmithorg/appsmith/pull/3633/commits/56adef25c1bb88588d2a2594720159f487ae3c6e

Revert ExecutionParams test change

---

app/client/cypress/fixtures/executionParamsDsl.json
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ActionExecution/ExecutionParams_spec.js
app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/QueryPane/AddWidget_spec.js

Fix execution params and Add widget button tests which were flaky

Fix flaky tests

---

app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/GetValuesMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/domains/RowObject.java
app/server/appsmith-plugins/googleSheetsPlugin/src/test/java/com/external/config/GetValuesMethodTest.java

Fixes #4108 
Dear reviewer,
To fix this issue, I'm having to do an extra loop over the entire data set, which is a problem for the get and bulk update (especially the former). Please help if you see another way to optimize this. 🍡 😄 
**Edit: Please refer to the issue for more details on what was fixed, and what it now looks like for the developer user.**

Only consider headings till value grid size, but consider all values till this size

---

app/client/src/sagas/DatasourcesSagas.ts
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/DeleteRowMethod.java

Fixes #4105 
// Code coverage diff between base branch:release and head branch: fix/unknown-delete-row-sheet 
:green_circle: | total | 48.64 **(0)** | 30.64 **(0.01)** | 26.71 **(0)** | 48.85 **(0)**
:green_circle: | app/client/src/sagas/DatasourcesSagas.ts | 13.95 **(0)** | 2.2 **(0.05)** | 10 **(0)** | 16.43 **(0)**</details>

Error handling for unknown sheet when deleting row

---

app/client/src/widgets/ContainerWidget.tsx

>
Updated the color field in the property pane to color picker instead of 'Input_text'. This will make the color picker consistent across all widgets.
#4173
No test cases written.

Update Container Widget color picker to be consistent with other widgets

---

app/client/public/privacy-policy.html

Including services and their role

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/LayoutActionServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutActionServiceTest.java

[Bug Fix] : Fix for table renaming bug when its connected to data from mongo

---

app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
app/client/src/pages/Editor/QueryEditor/Form.tsx

hide section based on hidden conditions

mongo form change to show/hide section

---

app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/connections/APIConnectionFactory.java

Add isAuthorized check for REST structure information 

---

deploy/install.sh

Fix fail when write permissions missing in pwd

---

app/client/src/sagas/WidgetEnhancementHelpers.ts
app/client/src/sagas/WidgetOperationSagas.tsx
app/client/src/utils/autocomplete/EntityDefinitions.test.ts
app/client/src/utils/autocomplete/EntityDefinitions.ts
app/client/src/widgets/ListWidget/ListPropertyPaneConfig.ts

// Code coverage diff between base branch:release and head branch: fix/delete-child-on-list-bug 
:red_circle: | total | 50.06 **(-0.02)** | 30.6 **(-0.04)** | 29.01 **(-0.01)** | 50.47 **(-0.02)**
:green_circle: | app/client/src/sagas/WidgetEnhancementHelpers.ts | 27.78 **(1.02)** | 4.26 **(0)** | 7.14 **(0)** | 29.69 **(1.12)**
:green_circle: | app/client/src/sagas/WidgetOperationSagas.tsx | 8.13 **(0.14)** | 0.97 **(-0.05)** | 3.08 **(-0.09)** | 9.27 **(0.15)**</details>

Fix: Validation on grid gap + handle delete child on list widget

---

app/client/src/widgets/Tabs/TabsWidget.tsx

Updating help text for tabs widget.
Fixes #4234 
- Test A
- Test B

Fix: Updating help text for tabs widget after refactor.

---

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/AuthenticationService.java

Check for error class type before casting

---

app/client/public/privacy-policy.html

[This](https://support.google.com/cloud/answer/9110914#explain-types) link provides the requirements for access to restricted scopes in Google API.

Added limited use disclosure

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Applications/UpdateApplication_spec.js

// Code coverage diff between base branch:release and head branch: fix-tests 
:green_circle: | total | 50.07 **(0)** | 30.61 **(0.01)** | 28.97 **(0)** | 50.48 **(0)**</details>

Fix update application test

---

app/client/src/actions/apiPaneActions.ts
app/client/src/pages/Editor/APIEditor/index.tsx
app/client/src/pages/Editor/DataSourceEditor/index.tsx
app/client/src/pages/Editor/Explorer/helpers.test.ts
app/client/src/pages/Editor/SaaSEditor/constants.ts
app/client/src/sagas/ApiPaneSagas.ts

App crashes when switching between google sheets action and another normal api action
Fixes #4204 
// Code coverage diff between base branch:release and head branch: fix/app-crash-googl-rest-api 
:red_circle: | total | 50.07 **(0)** | 30.6 **(0)** | 28.97 **(0)** | 50.47 **(-0.01)**
:red_circle: | app/client/src/sagas/ApiPaneSagas.ts | 13.84 **(-0.12)** | 1.79 **(-0.04)** | 7.14 **(0)** | 15.46 **(-0.17)**</details>

app crashes when moving from google to rest api

---

app/client/src/sagas/DebuggerSagas.ts

Use correct types and check if validationMessages exists as it could be undefined
Fixes #4287
Fixes #4289 
// Code coverage diff between base branch:release and head branch: fix/debugger-undefined 
:red_circle: | total | 50.06 **(-0.01)** | 30.59 **(-0.01)** | 28.97 **(0)** | 50.47 **(0)**
:green_circle: | app/client/src/sagas/DebuggerSagas.ts | 16.49 **(0.53)** | 3.51 **(-0.26)** | 28.57 **(0)** | 18.18 **(0.74)**</details>

Fix undefined error in debugger sagas

---

.github/workflows/client-test.yml
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Applications/UpdateApplication_spec.js
app/client/src/actions/apiPaneActions.ts
app/client/src/pages/Editor/APIEditor/index.tsx
app/client/src/pages/Editor/DataSourceEditor/index.tsx
app/client/src/pages/Editor/Explorer/helpers.test.ts
app/client/src/pages/Editor/SaaSEditor/constants.ts
app/client/src/sagas/ApiPaneSagas.ts
app/client/src/sagas/DebuggerSagas.ts
app/client/src/workers/validations.test.ts
app/client/src/workers/validations.ts
app/server/appsmith-server/src/main/java/com/appsmith/server/services/PluginServiceImpl.java

- NPE fix for action execution
- Navigation fix for Google API
- Evaluation fix for dropdown widget
- Debugger crash fixes

Fixes for broken evaluation

---

app/client/src/sagas/EvaluationsSaga.ts
app/client/src/utils/AnalyticsUtil.tsx

// Code coverage diff between base branch:release and head branch: analytics-event-cyclic-dep 
:green_circle: | app/client/src/sagas/EvaluationsSaga.ts | 21.13 **(0.42)** | 1.92 **(0)** | 5 **(0)** | 24 **(0.42)**</details>

Log analytics event for cycl dep errors

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Text_spec.js
app/client/src/workers/DataTreeEvaluator.ts

Fixes #4297 
// Code coverage diff between base branch:release and head branch: bug/action-cyclical-dependency 
:green_circle: | total | 48.94 **(0.01)** | 28.75 **(0.01)** | 26.78 **(0.01)** | 49.32 **(0.01)**
:green_circle: | app/client/src/workers/DataTreeEvaluator.ts | 88.56 **(0.1)** | 78.69 **(-0.32)** | 87.32 **(0.18)** | 88.76 **(0.1)**</details>

During updateDependencyMap, when dependencies are getting added for a path, only add if the dependency is not a parent of the path.

---

app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx

Memoize CurrentValueViewer to prevent expensive rerenders of react JSON viewer
Fixes #4239 
- UI Performance improvements (non-breaking change which fixes an issue)
Profiling before and after.
// Code coverage diff between base branch:release and head branch: perf/optimize_react-json-viewer 
:red_circle: | total | 50.08 **(0)** | 30.63 **(-0.01)** | 29.01 **(-0.01)** | 50.49 **(0)**
:red_circle: | app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx | 65.38 **(-0.85)** | 62.71 **(-3.36)** | 42.31 **(-1.69)** | 68.06 **(-0.95)**</details>

Memoize CurrentValueViewer to prevent expensive rerenders of react JSON viewer

---

README.md

> Added information to the main repo readme, such that new developers can easily understand the appropriate steps to setup local environment for frontend development 
Fixes #4330 
NIL

Linking clientSetup to the main readme file

---

.github/config.json

Add UI Performance label to ui building pod

Add UI Performance label to ui building pod

---

app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/CommentController.java

We were using PATCH, because that was semantically more correct for what we are doing here. But since PUT is used everywhere else in the project, changing this to PUT for consistency.

Accept PUT requests for thread updates

---

app/server/README.md

The setup guide in the README.md in the server folder is outdated. This PR directs users to the up to date setup guide

docs: Updates server readme.md

---

contributions/ClientSetup.md

An improvement to the client setup doc that makes node module install script more obvious

docs: Makes yarn install script more obvious

---

app/client/src/constants/HelpConstants.ts
app/client/src/mockResponses/WidgetConfigResponse.tsx
app/client/src/mockResponses/WidgetSidebarResponse.tsx
app/client/src/utils/autocomplete/EntityDefinitions.ts

>  Rename dropdown widget as select widget
Fixes # (#2046)
- Refactor code (rename dropdown as select)

Refactor: Rename Dropdown to Select

---

app/client/src/components/designSystems/appsmith/ChartComponent.tsx
app/client/src/components/designSystems/blueprint/DropdownComponent.tsx

Fixes #4294 & #4402
- Bug fix
// Code coverage diff between base branch:release and head branch: fix/label-undefined 
:red_circle: | total | 48.99 **(0)** | 28.78 **(-0.01)** | 26.84 **(0)** | 49.36 **(0)**
:red_circle: | app/client/src/components/designSystems/blueprint/DropdownComponent.tsx | 32.89 **(0)** | 22.22 **(-1.78)** | 3.45 **(0)** | 33.33 **(0)**</details>

Fix: Cannot read property 'label' of undefined & Cannot read property 'length' of undefined 

---

app/client/cypress/fixtures/testdata.json
app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datasources/DatasourceBasicProfile_spec.js
app/client/cypress/locators/DatasourcesEditor.json
app/client/cypress/support/commands.js

basic profile added
response check also validated 

Datasource test with basic profile added

---

app/client/src/pages/Editor/SaaSEditor/DatasourceForm.tsx

Revert Gsheets warning modal

---

app/client/src/widgets/ListWidget/ListWidget.tsx

TypeError: t.match is not a function
Fixes #4339 
// Code coverage diff between base branch:release and head branch: fix/match_not_a_function 
:red_circle: | app/client/src/widgets/ListWidget/ListWidget.tsx | 37.95 **(0)** | 20.69 **(-0.49)** | 27.27 **(0)** | 37.02 **(0)**</details>

match is not a function

---

app/client/src/components/editorComponents/DraggableComponent.tsx

The top and bottom resize handles don't work properly. fixing them.
Fixes #4232 
- Test A
- Test B

Fix: Resize doesn't react as intended for top/bottom handles.

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ProductUpdates/ProductUpdates_spec.js

[Cypress Test Fix] Locator updated

---

.github/workflows/client-test.yml
app/client/public/index.html
deploy/k8s/scripts/appsmith-configmap.yaml.sh
deploy/k8s/scripts/nginx-configmap.yaml
deploy/template/docker.env.sh

Add default configs for prod and tests

---

app/client/cypress/support/commands.js

[Cypress Test] Updated method to print response

---

app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datasources/DatasourceBasicProfile_spec.js

[Cypress Test] Test commented

---

app/client/src/pages/Editor/APIEditor/Pagination.tsx

Fixed API editor form submit on pagination button clicks
Fixes #3224 

Fixed handleSubmit bug in API form editor

---

app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java

- fix jsbon type return value in postgres plugin.
Fixes #4226 
- Manual

Fix: postgres plugin: add support for jsonb type

---

app/client/src/components/designSystems/appsmith/TableComponent/index.tsx
app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx
app/client/src/utils/hooks/usePrevious.tsx
app/client/src/widgets/TableWidget/index.tsx

ReactTableComponent re-renders even when nothing in the table has actually changed.
Common cases
- User types a space that doesn't alter the data.
- Something in the actions has changed.
- Something on the canvas triggered a new evaluation.
- 
Fixes #4286
- Performance improvement
Profiled before and after, screenshots included.
// Code coverage diff between base branch:release and head branch: perf/optimize-table-widget 
:red_circle: | total | 48.94 **(0)** | 28.7 **(0)** | 26.78 **(0)** | 49.31 **(-0.01)**
:red_circle: | app/client/src/widgets/TableWidget/index.tsx | 9.46 **(-0.03)** | 0 **(0)** | 10.64 **(0)** | …

Optimize table widget

---

app/client/src/api/ApiUtils.ts
app/client/src/pages/UserAuth/Login.tsx
app/client/src/pages/UserAuth/SignUp.tsx
app/client/src/pages/UserAuth/ThirdPartyAuth.tsx
app/client/src/pages/common/ErrorPageHeader.tsx

Fix redirectUrl not being encoded

---

app/client/src/reducers/entityReducers/actionsReducer.tsx

Remove execute action data on copy action
Fixes #2229 

Remove request/response data from copies of an executed API

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Debugger/Widget_Error_spec.js
app/client/cypress/support/commands.js
app/client/src/components/editorComponents/CodeEditor/styledComponents.ts
app/client/src/components/editorComponents/Debugger/index.tsx
app/client/src/components/editorComponents/WidgetNameComponent/SettingsControl.tsx
app/client/src/components/editorComponents/WidgetNameComponent/index.tsx
app/client/src/mockResponses/WidgetConfigResponse.tsx
app/client/src/sagas/EvaluationsSaga.ts
app/client/src/utils/WidgetPropsUtils.test.tsx
app/client/src/utils/WidgetPropsUtils.tsx
app/client/src/utils/helpers.test.ts
app/client/src/utils/helpers.tsx
app/client/src/widgets/BaseWidget.tsx
app/client/src/workers/DataTreeEvaluator.ts
app/client/src/workers/evaluationUtils.ts

Add migration for widget initial values
Includes the widget error state changes made in [bf7a8b9](https://github.com/appsmithorg/appsmith/commit/bf7a8b91a4f07f6080cb10ba502a8f3496689f52)
- jest test for migration
// Code coverage diff between base branch:release and head branch: feat/widget-error-state 
:green_circle: | total | 49.04 **(0.11)** | 28.83 **(0.2)** | 26.85 **(0.08)** | 49.41 **(0.11)**
:red_circle: | app/client/src/components/editorComponents/CodeEditor/styledComponents.ts | 92.42 **(-0.12)** | 55.56 **(-1.14)** | 100 **(0)** | 95.31 …

Feature: Show widget error state

---

app/client/cypress/manual_TestSuite/Text_Widget_Spec.js

Added multiple test ideas related to new features in combination with old features of the Text Widget

Adding test ideas for Text Widget

---

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/Property.java
app/server/appsmith-server/pom.xml
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ActionTemplate.java
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Datasource.java
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/DatasourceTemplate.java
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Plugin.java
app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/ActionDTO.java
app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/JoltTransformer.java
app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ActionTemplateRepository.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/LayoutActionServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/configurations/SeedMongoData.java
app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/MockPluginExecutor.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionServiceTest.java

Needs additions for the jsonNode objects that will store the form schemas.
1. ~~Which of these can reuse existing params?~~ Fixed
2. ~~Do we store json configs in the db?~~ This will eventually be coming from cloud services
In a separate PR I'll be refactoring the execute action flow to make it more readable, it's LOC count is incredibly high at this point.

Domain model changes required for SaaS integrations

---

app/client/cypress/manual_TestSuite/List_Widget_Spec.js

Adding test ideas for List widget and contains the following
1) Background colour
2) API binding 
3) renaming the widget
4) Deploy of the widget
5) Copy delete and paste the widget
6) Pagination of the widget with respect to the spacing 
7) Pagination movement
8) Adding addition data to the widget via array
9) Error testing 
10) Adding apt widget
11)Adding unapt widget to identify the error

Test ideas for List Widget

---

app/client/src/sagas/ApiPaneSagas.ts

Fixed r.match bug in API pane sagas
Fixes #4588 
// Code coverage diff between base branch:release and head branch: bug/api_pane_regex_match_bug 
:green_circle: | total | 51.43 **(0)** | 32.09 **(0)** | 30.02 **(0)** | 51.93 **(0.01)**
:red_circle: | app/client/src/sagas/ApiPaneSagas.ts | 14.41 **(-0.25)** | 1.64 **(0)** | 7.14 **(0)** | 16.08 **(-0.26)**</details>

Fixed r.match bug in API pane sagas

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/DatasourceServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/DatasourceServiceTest.java

- Fix NPE with hint message on localhost URL.
Fixes #4598 
- Junit TC

[Bug] fix NPE

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java

Fixes #4610 
> Created test events on segment

Added pluginName in execute_ACTION_TRIGGERED analytics event

---

app/server/appsmith-server/src/main/java/com/appsmith/server/constants/AnalyticsEvents.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ApplicationForkingService.java

Fixes #4620
- Analytics event
> Tested on Segment manually

Fork application event added 

---

.github/ISSUE_TEMPLATE/---bug-report.md

Adding environment parameter to the bug report template because there is often a confusion in understanding where is the bug found. This will avoid the confusion
Not yet created
Template change only

[FIX] Added environment parameter to the bug report template

---

app/client/src/workers/evaluationUtils.ts

Fixed BIgInt bindings in API pane.
Fixes #4625 
// Code coverage diff between base branch:release and head branch: fix/big_int_stringify_error 
:green_circle: | total | 51.55 **(0)** | 32.45 **(0.01)** | 29.68 **(0.01)** | 52.06 **(0)**
:red_circle: | app/client/src/workers/evaluationUtils.ts | 88.89 **(0.05)** | 76.42 **(-0.5)** | 90.7 **(0.22)** | 88.67 **(0.06)**</details>

BigInt evaluation error

---

app/client/src/components/designSystems/appsmith/ChartComponent.tsx

> In chart component add onDataPointClick event for custom chart type.
Fixes # (#4695)

added click event config for customChart

---

app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/helpers/DatasourceValidator.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/AuthenticationService.java

Validation rule for URL
Fixes #4807

Fixes failure due to extra spaces in authorization url in OAuth2 datasource

---

app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/OrganisationTests/CreateOrgTests_spec.js
app/client/cypress/support/commands.js

fix org tests

---

app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ApplicationController.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java

> This will fix the duplicate action names in separate pages while importing the application. Application name included in exported file 
Fixes 
> #4876
> #4877

Bug fix while importing application for duplicate action names in different pages  

---

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java

Default state for mongo actions that were already configured

---

app/client/src/components/propertyControls/CustomFusionChartControl.tsx
app/client/src/widgets/ChartWidget/propertyConfig.ts

> update error message to show proper error description 
Fixes # (#3894)

fixing docs and expectation strings on custom chart

---

app/client/src/actions/pageActions.tsx
app/client/src/sagas/PageSagas.tsx

> Fix bug on Page Saga
Fixes  #4796 
- Bugfix
// Code coverage diff between base branch:release and head branch: fix/-page-saga-bug 
:green_circle: | total | 51.57 **(0)** | 32.71 **(-0.01)** | 29.66 **(0.01)** | 52.07 **(0.01)**
:green_circle: | app/client/src/actions/pageActions.tsx | 77.61 **(1.49)** | 0 **(0)** | 38.1 **(4.77)** | 69.77 **(2.33)**
:red_circle: | app/client/src/sagas/PageSagas.tsx | 17.63 **(0)** | 3.17 **(-0.22)** | 9.68 **(0)** | 20.17 **(0)**</details>

fix: *isRetry is undefined* bug on Page saga

---

app/client/src/comments/CommentsShowcaseCarousel/index.tsx

chore: Fixes typo in collab tour

---

app/client/cypress/manual_TestSuite/Tab_Widget_Spec.js

Added test ideas for Tab with new visible feature

Test Ideas for Tab widget

---

app/client/src/constants/AppsmithActionConstants/formConfig/ApiSettingsConfig.ts
app/server/appsmith-plugins/mongoPlugin/src/main/resources/editor.json
app/server/appsmith-plugins/mssqlPlugin/src/main/java/com/external/plugins/MssqlPlugin.java
app/server/appsmith-plugins/mssqlPlugin/src/main/resources/setting.json
app/server/appsmith-plugins/mssqlPlugin/src/test/java/com/external/plugins/MssqlPluginTest.java
app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java
app/server/appsmith-plugins/mysqlPlugin/src/main/resources/setting.json
app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java
app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java
app/server/appsmith-plugins/postgresPlugin/src/main/resources/setting.json
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java

Getting Prepared Statement for Postgres, MySQL, and MS-SQL and Smart Substitution for Rest API plugins out of beta

---

README.md

---
name: "Pull Request"
about: Create a pull request to submit new contributions to appsmith
title: "[FIX/FEATURE]"
labels:
assignees:
---
> …

Updated Readme with  community launch in Beta

---

README.md

---
name: "Pull Request"
about: Create a pull request to submit new contributions to appsmith
title: "[FIX/FEATURE]"
labels:
assignees:
---
>
> Use this template to quickly create a well-written pull request. Delete all quotes before creating the pull request. …

update notion page link and added events

---

contributions/ServerSetup.md

I was going through the document to setup Appsmith server and found the document confusing midway through. So I edited the document as I went along.
The following changes have been done to improve this document:
* The main change done is to bring the sections `Setting up a local MongoDB instance` and `Setting up a local Redis instance` under the prerequisites section. This improves the structure of the document as the reader can linearly go through it and set up the dependencies before setting up the Appsmith server.
* Apart from this, each section flows much more naturally to the next section as the last sentence of each section sets up the context about what's next.
* Other minor language improvements.
Fixes # (no issue)
I'm not sure if I need to create an issue for updating this …

Update ServerSetup.md for clarity

---

app/client/src/pages/Applications/OnboardingForm.tsx

Check if user exists before loading the form

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_Derived_Column_Data_validation_spec.js

updated test flow

---

.github/pull_request_template.md

Removing the section below 👇  as it only adds up to the description of PR, that's not useful 
```
---
name: "Pull Request"
about: Create a pull request to submit new contributions to appsmith
title: "[FIX/FEATURE]"
labels:
assignees:
---
```
None created
Template documentation update only

Modifying PR template to revert to older version

---

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java

Earlier we were having pluginId conflicts when there is no datasource present for API 
Fixes # (5181)
Tested manually on local instance

Support for orphan API (without parent datasource) added for import-export functionality

---

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/DatasourceStructure.java
app/server/appsmith-plugins/dynamoPlugin/src/main/java/com/external/plugins/DynamoPlugin.java
app/server/appsmith-plugins/firestorePlugin/src/main/java/com/external/plugins/FirestorePlugin.java
app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java
app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java
app/server/appsmith-plugins/redshiftPlugin/src/main/java/com/external/plugins/RedshiftPlugin.java
app/server/appsmith-plugins/snowflakePlugin/src/main/java/com/external/utils/SqlUtils.java
app/server/appsmith-plugins/snowflakePlugin/src/main/resources/templates/CREATE.sql
app/server/appsmith-plugins/snowflakePlugin/src/main/resources/templates/DELETE.sql
app/server/appsmith-plugins/snowflakePlugin/src/main/resources/templates/SELECT.sql
app/server/appsmith-plugins/snowflakePlugin/src/main/resources/templates/UPDATE.sql
app/server/appsmith-plugins/snowflakePlugin/src/main/resources/templates/meta.json

- Modified table structure to hold schema information
- Added templates to be used for new queries

Added schema information in templates query for Snowflake

---

app/client/src/components/editorComponents/WidgetNameComponent/index.tsx

Fixes #5190  
- Add UI performance tracker

Add widget type and id to property pane tracker

---

app/client/netlify.toml

Remove unused configurations in Netlify

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java

When user tries to update the application name with the duplicate application name within the same organisation, error message is thrown but doesn't give context of which one is the duplicate key
Fixes #4811
- Manual 
- Junit TC

Error message for duplicate name when updating application name modified to give more contextual information

---

app/rts/src/server.ts
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Comment.java
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/CommentThread.java
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Notification.java
app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/DateUtils.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/NotificationRepository.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NotificationServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/NotificationServiceImplTest.java

Adds some fields to notifications and comments. Also fixes the bug with get unread notification API.
Fixes #5282 
- Unit tests

Fix bug where some fields are missing for notifications from the API

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Onboarding/Onboarding_spec.js
app/client/src/components/ads/Toast.tsx
app/client/src/sagas/OnboardingSagas.ts

Fixes #5357 
Cypress test steps added to check the same
// Code coverage diff between base branch:release and head branch: fix/onboarding-step-1 
:red_circle: | total | 53.31 **(-0.01)** | 35.28 **(0)** | 31.94 **(0)** | 53.83 **(-0.01)**
:red_circle: | app/client/src/sagas/OnboardingSagas.ts | 18.06 **(-0.3)** | 3.65 **(-0.05)** | 12.24 **(0)** | 18.41 **(-0.3)**</details>

Fix: Fixes a bug in onboarding flow step 1

---

README.md

Update links on README

---

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/MustacheHelper.java
app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/ActionConfiguration.java
app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/ActionDTO.java
app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/DslActionDTO.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/PageLoadActionsUtil.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutActionServiceTest.java

- update on page load actions flow to accommodate JS action type. 
- update word pattern to match patterns like "foo.data.bar"
- use fullyQualifiedName to identify actions
- update json path keys extraction
Fixes #4736 
Fixes #4729 
- JUnit TC

Feature: support for updating on page load actions with JS action type

---

.github/config.json

Added pod label automation for the new iFrame widget
- None

added pod label automation for the new iFrame widget

---

app/client/cypress/manual_TestSuite/GoogleSheet_API_Spec.js
app/client/cypress/manual_TestSuite/Mongo_Datasource_Spec.js

Various test ideas to test GoogleSheet API and Mongo Plugin - Form Input

Test Ideas for GoogleSheets and Mongo DB Form Input

---

app/client/src/components/editorComponents/PreventInteractionsOverlay.tsx

> Updated css to change button widget height when deployed.
Fixes #4627 
- Tested locally.

FIX #4627: updated css to change button widget height when deployed

---

app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/QueryPane/MongoDatasource_spec.js

Fix mongo form test by changing labels

Update form label changes for Mongo Form

---

app/client/src/components/editorComponents/GlobalSearch/index.tsx

Show current page entities on top within global search results
Within the current page entities or for the rest of the pages, follow this sort order:
```
Actions
Widgets
Pages
Datasources
```
- manually
// Code coverage diff between base branch:release and head branch: global-search-results-sort 
:red_circle: | total | 54.12 **(-0.03)** | 36.12 **(-0.06)** | 32.79 **(-0.02)** | 54.62 **(-0.02)**
:red_circle: | app/client/src/components/editorComponents/GlobalSearch/index.tsx | 58.54 **(-4.16)** | 14.38 **(-2.78)** | 39.53 **(-2.97)** | 59.14 …

Show current page entities on top within global search results

---

app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPluginUtils.java

[Bug] Mongo Plugin : Handle socket exception when the connection is dropped by Mongo database

---

app/client/src/comments/CommentCard/CommentCard.tsx
app/client/src/comments/CommentsShowcaseCarousel/CommentsCarouselModal.tsx
app/client/src/components/ads/EmojiReactions.tsx
app/client/src/components/ads/Tooltip.tsx
app/client/src/components/designSystems/blueprint/ModalComponent.tsx
app/client/src/constants/DefaultTheme.tsx
app/client/src/globalStyles/popover.ts
app/client/src/pages/Editor/ToggleModeButton.tsx

- Update toggle button theme and icons
- Fix comments onboarding modal z-index
- Fix reaction when adding to an already added reaction, update list of users who reacted
Fixes #5524
- manually
// Code coverage diff between base branch:release and head branch: collab-fixes-3 
:red_circle: | total | 54.13 **(-0.01)** | 36.08 **(-0.04)** | 32.83 **(-0.01)** | 54.63 **(-0.01)**
:red_circle: | app/client/src/comments/CommentCard/CommentCard.tsx | 73.49 **(-0.45)** | 65.49 **(-1.18)** | 43.9 **(0)** | 74.03 **(-0.48)**
:red_circle: | …

Minor fixes related to the comments feature

---

app/client/src/pages/Editor/index.tsx

>Include App name in Browser  Title Bar
Fixes #4583 
- Visible change

fix: Add Appname to title

---

app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/helpers/BufferingFilter.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java

Fixes #5547 
- Unable to write a Junit for this, tested manually

Added content length header for multipart form data requests

---

app/client/src/components/editorComponents/CodeEditor/BindingPrompt.tsx
app/client/src/components/editorComponents/CodeEditor/index.tsx
app/client/src/components/editorComponents/form/fields/DynamicTextField.tsx
app/client/src/components/formControls/DynamicTextFieldControl.tsx
app/client/src/constants/DefaultTheme.tsx
app/client/src/pages/Editor/APIEditor/PostBodyData.tsx
app/client/src/pages/Editor/IntegrationEditor/DatasourceHome.tsx
app/client/src/pages/Editor/IntegrationEditor/IntegrationsHomeScreen.tsx
app/client/src/pages/Editor/IntegrationEditor/MockDataSources.tsx
app/client/src/pages/Editor/IntegrationEditor/NewApi.tsx
app/client/src/utils/FormControlRegistry.tsx

Fixes minor bugs in `/` commands and new nav in general
Fixes #5624 
Fixes #5623 
manually

Bug Fixes - New nav

---

app/client/src/workers/DataTreeEvaluator.ts
app/client/src/workers/evaluate.ts
app/client/src/workers/evaluation.worker.ts

- Fix actions not running with multiple actions are called at the top level of the binding
- Fix errors not showing when actions are not parsed or evaluated correctly
Fixes #5550
Top-level actions should run in parallel and all of them should be executed
In a button onClick trigger have multiple actions run
```
{{ 
Api1.run();
showAlert('Test Message', 'error');
Api2.run();
}}
```
All the above should run 
// Code coverage diff between base branch:release and head branch: fix/top-level-parallel-actions 
:green_circle: | total | 53.91 **(0.01)** | 36.02 …

Fix top level parallel runs

---

app/client/src/components/ads/Tabs.tsx
app/client/src/components/utils/CollapseComponent.tsx
app/client/src/pages/Editor/DataSourceEditor/Connected.tsx
app/client/src/pages/Editor/DataSourceEditor/JSONtoForm.tsx
app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
app/client/src/pages/Editor/DataSourceEditor/index.tsx
app/client/src/pages/Editor/IntegrationEditor/DatasourceCard.tsx
app/client/src/pages/Editor/IntegrationEditor/DatasourceHome.tsx
app/client/src/pages/Editor/IntegrationEditor/IntegrationsHomeScreen.tsx
app/client/src/pages/Editor/IntegrationEditor/MockDataSources.tsx
app/client/src/pages/Editor/IntegrationEditor/NewApi.tsx
app/client/src/pages/Editor/SaaSEditor/DatasourceCard.tsx

Minor styling improvements
- Fixed Card sizes for create new datasources
- Added icons to create api/query btns
- Fixed the height of editor components and accounted for back btns
Fixes #5654 
Enhancements
manually
// Code coverage diff between base branch:release and head branch: bug/new-nav-ui-improvements 
:red_circle: | total | 53.9 **(0)** | 36 **(0)** | 32.59 **(-0.01)** | 54.47 **(0)**
:red_circle: | app/client/src/pages/Editor/DataSourceEditor/JSONtoForm.tsx | 16.2 **(-0.11)** | 20.29 **(0)** | 4.35 **(-0.2)** | 17.32 **(-0.14)**
:red_circle: | app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceFo …

[Fix] New nav UI improvements

---

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java

Earlier during import-export applications with OAuth datasources, we were facing authentication failure issues because of the authentication response was not correctly set. With this change AuthenticationResponse will be update correctly while importing the application.
Fixes #5353 #5223
> Tested with GSheet plugin

Fix for OAuth datasource authentication failure for import-export application flow 

---

app/server/appsmith-server/src/main/java/com/appsmith/server/migrations/DatabaseChangelog.java

This PR contains a DB migration that updated the logo links for the plugins. It sets the new svg logos.
Fixes #5669 

Updated plugin logos from png to svg

---

app/client/src/pages/Editor/DataSourceEditor/Connected.tsx
app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
app/client/src/pages/Editor/Explorer/Actions/ActionsGroup.tsx
app/client/src/pages/Editor/IntegrationEditor/ActiveDataSources.tsx
app/client/src/pages/Editor/IntegrationEditor/DatasourceCard.tsx
app/client/src/pages/Editor/SaaSEditor/DatasourceForm.tsx

Fixed the bug, by using action creator which does not require URL to be provided at start. For datasources of pluginType `API` added a fix to properly set action config.
Fixes #5680 
Fixes #5686 
- Manually
// Code coverage diff between base branch:release and head branch: bug/new-api-not-working-google-sheet 
:red_circle: | total | 53.89 **(-0.02)** | 35.79 **(-0.06)** | 32.55 **(0.01)** | 54.48 **(-0.01)**
:green_circle: | app/client/src/pages/Editor/DataSourceEditor/Connected.tsx | 49.02 **(2.35)** | 11.11 **(0.58)** | 0 **(0)** | 50 **(2.54)**
:red_circle: | …

[Fix] create new api not working from saved google sheet state

---

app/client/src/reducers/uiReducers/globalSearchReducer.ts

Filter out undefined values from the recent entities array

---

app/client/src/actions/datasourceActions.ts
app/client/src/api/DatasourcesApi.ts
app/client/src/pages/Editor/IntegrationEditor/MockDataSources.tsx
app/client/src/sagas/DatasourcesSagas.ts
app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/MockDataSource.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/MockDataServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/MockDataServiceTest.java

Changing the variables name to avoid the confusion
Manually in local

Replace pluginName with packageName in mockDB creation

---

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/exceptions/pluginExceptions/AppsmithPluginError.java
app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/OAuth2.java

Modified error message and code for authentication failure

---

app/client/src/sagas/PageSagas.tsx
app/client/src/utils/hooks/useCanvasMinHeightUpdateHook.ts

>
Fixes #5834 
Fixes #5816 
> Please describe the tests that you ran to verify …

Fix: Stop page DSL updates in view mode.

---

app/client/src/workers/evaluate.test.ts
app/client/src/workers/evaluate.ts

Revert back to old way of eval

---

.github/workflows/client-test.yml
app/client/cypress/setup-test.sh

This PR builds server without running maven tests
Fixes #5881
I have tested the new workflow in my local fork.

Disabled maven Tests

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GlobalSearch/GlobalSearch_spec.js

[Fix test] Fix globalsearch test: wait for page load

---

app/client/src/constants/DefaultTheme.tsx

Increase initial height of bottom tabs

Fix: Minor change in initial height for bottom tabs in action screen

---

app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/constants/ResponseDataType.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/helpers/DataUtils.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java

[Bug Fix : Rest Api] Base64 encode binary response before sending it out to client

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/CommentServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/CommentServiceTest.java

Generates an analytics event when a new comment is created.
Fixes #5519 

Log analytics event when comment created

---

app/client/src/constants/messages.ts
app/client/src/sagas/ActionExecutionSagas.ts
app/server/appsmith-server/src/main/java/com/appsmith/server/exceptions/AppsmithError.java

Also removing the toast message for successful action runs. With the debugger, this is no longer required.
Fixes #5976 
Manual 
// Code coverage diff between base branch:release and head branch: fix/invalid-action-name 
:red_circle: | total | 51.85 **(-0.01)** | 33.51 **(-0.02)** | 29.87 **(-0.01)** | 52.51 **(-0.01)**
:red_circle: | app/client/src/constants/messages.ts | 69.34 **(0.02)** | 100 **(0)** | 7.31 **(0.04)** | 75.74 **(-0.08)**
:green_circle: | app/client/src/sagas/ActionExecutionSagas.ts | 12.56 **(0.03)** | 1.97 **(0)** | 9.68 **(0)** | 14.4 …

Improving error message for invalid entities

---

app/client/src/mockResponses/WidgetConfigResponse.tsx

Fix Menu Button truncating
Fixes #5815  

fix: Menu button truncating

---

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/PolicyUtils.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserOrganizationService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserOrganizationServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/helpers/PolicyUtilsTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/UserOrganizationServiceTest.java

This PR fixes the issue: Comments are missing when an user's role is changed in an organization.
Fixes #5859 

Fixed comment missing issue when user role is changed

---

app/server/appsmith-server/src/main/java/com/appsmith/server/constants/Appsmith.java
app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/CommentController.java
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/CommentThread.java
app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/RedirectHelper.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/CommentServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/EmailEventHandler.java

There is a change in UI side on how a comment thread is positioned on canvas. The backend is updated in this PR as per the new changes. Origin header was mandatory in create thread and create comment. This PR makes these fields optional.
Fixes #5996 

[Improvement] Update the positioning parameters for bot threads

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/AnalyticsService.java

> Earlier we were updating the Map which was passed as a parameter to sendEvent method which was throwing ImmutableCollection 
Fixes #6050 
> Tested manually on local instance with Segment dev env

[Bug] Fix for immutable map in analytics service

---

.github/workflows/external-client-test.yml

replaced docker image with local server 
Fixes #5900 
This has been tested in my a fork.
In order to test following things were changed
- Commented out steps requiring PR number.
- Added workflow dispatch to test manually.

Replaced docker image with local server

---

app/client/src/components/designSystems/appsmith/ChartComponent.tsx

> Add `onDataPointClick` event on chart config 
Fixes #4695

fix when component update

---

app/client/src/sagas/EvaluationsSaga.ts
app/client/src/sagas/PostEvaluationSagas.ts

Autocomplete definition creation change
Fixes #6070
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: change-def-creation-6070 
:red_circle: | total | 51.93 **(0)** | 33.52 **(-0.02)** | 30.01 **(0)** | 52.59 **(0)**</details>

changed the behaviour

---

app/client/src/api/ActionAPI.tsx
app/client/src/sagas/ActionExecutionSagas.ts

Fix base64 to binary transformation for action execution via trigger and onPageLoad
// Code coverage diff between base branch:release and head branch: fix/action-response-transformation 
:red_circle: | total | 51.92 **(-0.01)** | 33.53 **(-0.02)** | 30.01 **(-0.02)** | 52.59 **(0)**
:red_circle: | app/client/src/sagas/ActionExecutionSagas.ts | 12.53 **(-0.03)** | 1.98 **(0.01)** | 9.68 **(0)** | 14.36 **(-0.04)**
:red_circle: | app/client/src/utils/helpers.tsx | 53.46 **(-1.89)** | 26.03 **(-4.11)** | 22.22 **(-3.71)** | 47.2 **(-1.6)**</details>

Fix action binary transformation

---

app/client/src/components/editorComponents/CodeEditor/index.tsx
app/client/src/components/editorComponents/CodeEditor/styledComponents.ts

Fixed slash icon position
Fixes #6078 
// Code coverage diff between base branch:release and head branch: fix/slash_btn_position 
:red_circle: | total | 51.9 **(0)** | 33.5 **(-0.02)** | 29.99 **(-0.01)** | 52.56 **(-0.01)**
:red_circle: | app/client/src/components/editorComponents/CodeEditor/index.tsx | 66.81 **(-0.56)** | 40 **(-1.04)** | 50 **(-1.28)** | 68.69 **(-0.58)**
:red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.59 **(-0.24)** | 39.41 **(-0.84)** | 36.21 **(0)** | 54.77 **(-0.27)**</details>

Fixed slash button positioning

---

app/server/build.sh

Added a check for mvn failure.
Fixes #6106
Tested in my fork
https://github.com/yatinappsmith/appsmith/runs/3144105761

Added mvn failure check

---

.github/config.json

Added new labels for automated tagging on new widgets and core changes made by the UI building POD
NIL

Added new labels for automated tagging

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/PropertyPane/Draggable_PropertyPane_Widgets_spec.js

Add test cases for Property Pane drag and rop
Tested locally

Add tests for Property pane drag and drop

---

app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/dtos/MultipartFormDataDTO.java
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/helpers/DataUtils.java
app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/helpers/DataUtilsTest.java

Related to changes discussed in #5503

Updated multipart DTO to match file picker widget properties

---

app/client/src/components/editorComponents/GlobalSearch/githubHelper.ts

Fixes: #6172
// Code coverage diff between base branch:release and head branch: fix-doc-link 
:green_circle: | total | 51.84 **(0.01)** | 33.7 **(0.01)** | 29.74 **(0)** | 52.47 **(0)**

[Hotfix] Update link to fetch tutorial doc

---

app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/DeleteSheetMethod.java

Minor fixes on the Google Sheets plugin

---

app/client/src/widgets/DropdownWidget.tsx
app/client/src/widgets/MultiSelectWidget.tsx
app/client/src/workers/validations.test.ts
app/client/src/workers/validations.ts

Fixes validation issues found in the new multiselect widget.
Fixes #6126
Fixes: https://github.com/appsmithorg/appsmith/pull/5228#issuecomment-886544183
Unit tests and manual
// Code coverage diff between base branch:release and head branch: fix/multiselect-validations 
:green_circle: | total | 51.99 **(0.16)** | 33.83 **(0.14)** | 29.89 **(0.15)** | 52.64 **(0.17)**
:sparkles: :new: | **app/client/src/components/designSystems/appsmith/MultiSelectComponent/index.styled.tsx** | **92.31** | **100** | **0** | **100**
:sparkles: :new: | …

Multiselect validation fixes

---

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonConfig.java
app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/SegmentConfig.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/AnalyticsService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ReleaseNotesService.java
app/server/appsmith-server/src/main/resources/application.properties

> This will add analytics datapoint on self-hosted instances with hashed usernames
> Tested manually using segment cloud and dev env

Add analytics event for self-hosted instances

---

app/client/src/pages/Applications/index.tsx
app/client/src/pages/UserAuth/Login.tsx
app/client/src/pages/UserAuth/SignUp.tsx
app/client/src/utils/helpers.tsx
app/client/src/utils/validation/getIsSafeURL.ts
app/client/src/workers/validations.ts

// Code coverage diff between base branch:release and head branch: xss-redirect-url 
:green_circle: | total | 51.84 **(0)** | 33.66 **(0)** | 29.76 **(0.01)** | 52.47 **(0)**
:red_circle: | app/client/src/utils/helpers.tsx | 53.05 **(-0.41)** | 26.03 **(0)** | 21.43 **(-0.79)** | 46.51 **(-0.69)**
:sparkles: :new: | **app/client/src/utils/validation/getIsSafeURL.ts** | **100** | **100** | **100** | **100**
:red_circle: | app/client/src/workers/validations.ts | 80.85 **(-0.1)** | 68.45 **(-0.08)** | 83.33 **(0)** | 81.82 **(-0.1)**</details>

Fix xss redirectURL

---

app/client/src/components/editorComponents/Onboarding/Helper.tsx
app/client/src/constants/OnboardingConstants.tsx

Add skip tour in each step of onboarding
Fixes  (#6155)
Tested manually in local.
// Code coverage diff between base branch:release and head branch: fix/onboarding-flow-enhancement 
:green_circle: | total | 51.85 **(0.01)** | 33.72 **(0.02)** | 29.75 **(0.01)** | 52.48 **(0.01)**
:green_circle: | app/client/src/components/editorComponents/Onboarding/Helper.tsx | 71.21 **(0.44)** | 36.19 **(1.24)** | 35.29 **(0)** | 69.35 **(0.5)**
:green_circle: | app/client/src/utils/helpers.tsx | 55.35 **(1.89)** | 30.14 **(4.11)** | 25.93 **(3.71)** | 48.8 …

Onboarding Enhancement | Add skip tour option in welcome tour

---

app/client/src/components/editorComponents/ActionRightPane/Connections.tsx
app/client/src/components/editorComponents/ActionRightPane/SuggestedWidgets.tsx
app/client/src/components/editorComponents/ActionRightPane/index.tsx

To add minor improvements to suggested widget panel, as listed in the issue.
Fixes #6189 
- manual
// Code coverage diff between base branch:release and head branch: fix/minor-ux-changes-suggested-widgets 
:green_circle: | total | 51.85 **(0.01)** | 33.67 **(0)** | 29.76 **(0)** | 52.48 **(0)**
:green_circle: | app/client/src/components/editorComponents/ActionRightPane/index.tsx | 34.48 **(0.76)** | 25 **(0)** | 0 **(0)** | 37.5 **(0.79)**</details>

[Fix] Small UI improvements to suggested widgets section

---

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/SegmentConfig.java

The bean creation function will be called when any one of `writeKey` or `ceKey` are available. But the function uses one of them depending on a different logic, and so can end up with an empty key. For example, the `writeKey` is not available and `ceKey` is indeed available, the bean creation function is called, and if this function's logic tries to use the `writeKey`, an NPE is thrown.

Fix NPE when Segment key not available correctly

---

app/client/src/sagas/EvaluationsSaga.ts

Disable tern updates in view mode.
Fixes #6202
Manually tested in the application in which the issue was most apparent
Before:
After:
// Code coverage diff between base branch:release and head branch: fix/disable-viewmode-tern 
:green_circle: | app/client/src/sagas/EvaluationsSaga.ts | 20.54 **(0.91)** | 2.78 **(-0.25)** | 6.67 **(0)** | 23.71 **(1.13)**

Disable tern in view mode

---

app/client/cypress/fixtures/executionParamsDsl.json
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ActionExecution/ExecutionParams_spec.js

Changed required data as per available
Fixes #6267 
Tested locally.
// Code coverage diff between base branch:release and head branch: test/ExecutionParamsfix 
:green_circle: | total | 51.5 **(0)** | 33.48 **(0.02)** | 29.3 **(0)** | 52.13 **(0.01)**

Fixed ExecutionParams

---

app/client/src/entities/Widget/utils.test.ts
app/client/src/widgets/ChartWidget/propertyConfig.ts
app/client/src/workers/validations.test.ts
app/client/src/workers/validations.ts

Certain validations were either misconfigured, or were not correctly validating.
For example, OBJECT_ARRAY and Array of specific type objects
Fixes #6280
Jest tests added for missing scenarios
// Code coverage diff between base branch:release and head branch: fix/validation-scenarios 
:green_circle: | total | 51.51 **(0.01)** | 33.53 **(0.07)** | 29.3 **(0)** | 52.14 **(0.02)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.83 **(0.24)** | 40.25 **(0.84)** | 36.21 **(0)** | 55.04 **(0.27)** …

Missing validations

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GenerateCRUD/GenerateCRUDPage_Spec.js

As we await a fix for 
https://github.com/appsmithorg/appsmith/issues/6352
commenting current test 
// Code coverage diff between base branch:release and head branch: test/DisableTest 
:red_circle: | total | 51.67 **(-0.01)** | 33.68 **(-0.01)** | 29.54 **(0)** | 52.33 **(0)**
:red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.59 **(-0.24)** | 39.41 **(-0.84)** | 36.21 **(0)** | 54.77 **(-0.27)**</details>

Commenting test 

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GenerateCRUD/GenerateCRUDPage_Spec.js

Uncommenting the CRUD cypress test as
As PR #6359 fixes issue #6352, the test can be uncommented.

Uncomment Gen CRUD page Test

---

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/WidgetSuggestionHelper.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionServiceTest.java

> For nested data structures, after suggesting the widget the binding query doesnt work properly. This change address that issue.
Fixes #6103 
> 
- Unit Tests
- Manually in local environment

Fix binding query for the nested data responses

---

.github/config.json

Updated dropdown widget to select widget.
none

change label dropdown widget to select widget

---

app/client/src/selectors/commentsSelectors.ts

This got added due to a hotfix and another feature whose CI was run in parallel
- Manually
// Code coverage diff between base branch:release and head branch: fix-ts-error 
:green_circle: | total | 51.69 **(0.01)** | 33.62 **(0.02)** | 29.51 **(0.01)** | 52.35 **(0.01)**
:green_circle: | app/client/src/utils/helpers.tsx | 54.88 **(1.83)** | 30.14 **(4.11)** | 25 **(3.57)** | 48.06 **(1.55)**

Fix ts error release

---

app/client/src/mockResponses/WidgetConfigResponse.tsx

> Table Row evaluation was showing an error in the debugger. Removed evaluation in row default value.
Fixes #6160 

Fix #6160 Updated Text binding for row and removed variable evaluation

---

app/client/src/sagas/userSagas.tsx

Fixes #6443
- Manually
// Code coverage diff between base branch:release and head branch: fix-public-apps 
:green_circle: | total | 53.41 **(0)** | 34.99 **(0.02)** | 31.54 **(0)** | 53.96 **(0.01)**
:red_circle: | app/client/src/sagas/userSagas.tsx | 16.75 **(-0.08)** | 1.85 **(0)** | 5.88 **(0)** | 20 **(-0.12)**

[hotfix] Anonymous users get redirected to the login page for public apps

---

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java
app/server/appsmith-server/src/test/resources/test_assets/ImportExportServiceTest/valid-application.json

> When we have unpublished page for which the corresponding published page is not present an empty object was being created which was causing issue when we try to deploy the application. This PR will fix the issue by rehydrating only the non-empty applicationPage object in the application.
Fixes #6450
> Manually 
> Update TC to cover edgecase

Bugfix for empty object being created for published pages inside application 

---

app/client/src/components/designSystems/blueprint/ButtonComponent.tsx

Catch invalid google recaptcha v3 key error
Fixes #5734 
// Code coverage diff between base branch:release and head branch: fix/google-recaptcha-v2 
:green_circle: | total | 51.91 **(0.01)** | 33.51 **(0)** | 30 **(0)** | 52.57 **(0)**
:green_circle: | app/client/src/components/designSystems/blueprint/ButtonComponent.tsx | 49.48 **(1.48)** | 42.67 **(0)** | 56 **(0)** | 52.87 **(1.76)**</details>

Fix-Catch invalid google recaptcha v3 key error

---

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/WidgetSuggestionHelper.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionServiceTest.java

> Add null check for the nested data to fix NPE. 
Fixes #6457 
- Locally
- Unit Tests

Add null check for the nested data structure

---

app/client/src/comments/CommentsShowcaseCarousel/index.tsx
app/client/src/comments/inlineComments/AddCommentInput.tsx
app/client/src/components/ads/ShowcaseCarousel.tsx

- Skip btn: re-using skip after navigating back
- Sorting order for the mentions list
- Manually
// Code coverage diff between base branch:release and head branch: minor-comments-feature-fixes 
:red_circle: | total | 53.35 **(-0.02)** | 34.77 **(-0.03)** | 31.46 **(0)** | 53.9 **(-0.01)**
:red_circle: | app/client/src/comments/inlineComments/AddCommentInput.tsx | 64.6 **(-7.14)** | 17.7 **(-2.3)** | 60.87 **(-1.03)** | 66.19 **(-6.17)**</details>

[Fix] Minor comments feature fixes

---

deploy/install.sh
deploy/template/docker-compose.yml.sh
deploy/template/docker.env.sh

Store MongoDB creds in separate file from install.sh

---

app/client/src/sagas/WidgetOperationSagas.tsx

>
Fixes #6030
> Please describe the tests that you ran to verify your changes. …

Fix: Undo-Delete of Containers fix

---

app/client/cypress/fixtures/navigateToInputDsl.json
app/client/cypress/fixtures/navigateTotabledsl.json
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/NavigateToFeatureValidation_spec.js

NavigateTo feature testing 
1.Used multiple pages
2.Binding widgets and making sure the params are actually getting reflected
// Code coverage diff between base branch:release and head branch: test/NavitateTo 
:green_circle: | total | 53.29 **(0.01)** | 34.75 **(0.01)** | 31.33 **(0)** | 53.85 **(0)**

Added test for Navigate To feature

---

app/client/src/pages/Editor/ToggleModeButton.tsx

Remove comments discovery tooltip
- Manually
// Code coverage diff between base branch:release and head branch: remove-discovery-tooltip 
:red_circle: | app/client/src/pages/Editor/ToggleModeButton.tsx | 68.09 **(-0.22)** | 25.37 **(0)** | 43.33 **(0)** | 66.67 **(-0.25)**</details>

Remove comments discovery tooltip

---

app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/Aggregate.java
app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/Insert.java
app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java

[Mongo] : Aggregate pipeline and bulk inserts now use BSON parsing instead of JSON parsing

---

app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/PolicyUtils.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/ActionCollectionRepository.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserOrganizationServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceImplTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceTest.java

Changes to add acl permissions to action collections on inviting new users

Added logic to add acl permissions to action collections on invite

---

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeStringUtils.java
app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java

Escaped inputs for bson substitution

---

app/client/src/comments/CommentsShowcaseCarousel/index.tsx
app/client/src/components/ads/ShowcaseCarousel.tsx

Close button for the comments onboarding
- Manually
// Code coverage diff between base branch:release and head branch: close-btn-tour 
:green_circle: | total | 54.85 **(0)** | 36.7 **(0.01)** | 33.26 **(0)** | 55.43 **(0)**

Close button for the comments onboarding popup

---

app/server/appsmith-plugins/snowflakePlugin/src/main/java/com/external/plugins/SnowflakePlugin.java
app/server/appsmith-plugins/snowflakePlugin/src/main/resources/form.json

Changes to props to add role of user

---

app/server/appsmith-plugins/snowflakePlugin/src/main/java/com/external/plugins/SnowflakePlugin.java
app/server/appsmith-plugins/snowflakePlugin/src/test/java/com/external/plugins/SnowflakePluginTest.java

Throw a stale connection exception when authentication token expires in Snowflake

---

app/server/appsmith-server/src/main/java/com/appsmith/server/filters/MDCFilter.java

Provides additional context for #6318

Added user email to logging context

---

app/client/src/reducers/evaluationReducers/treeReducer.ts

Change to collect more information about #6461
// Code coverage diff between base branch:release and head branch: fix/handle-dt-update-issue 
:red_circle: | total | 54.8 **(0)** | 36.8 **(-0.01)** | 33.1 **(0)** | 55.37 **(0)**
:red_circle: | app/client/src/reducers/evaluationReducers/treeReducer.ts | 36.36 **(-0.48)** | 0 **(0)** | 50 **(0)** | 47.06 **(-2.94)**

Catch Data Tree update error and better sentry logging

---

app/client/src/workers/validations.ts

Fixes #6456 
// Code coverage diff between base branch:release and head branch: fix/6456_atob_error 
:green_circle: | total | 53.3 **(0.02)** | 34.78 **(0.04)** | 31.34 **(0.01)** | 53.86 **(0.01)**
:green_circle: | app/client/src/utils/helpers.tsx | 56.71 **(1.83)** | 32.88 **(4.11)** | 28.57 **(3.57)** | 50.39 **(1.55)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.71 **(0.24)** | 38.6 **(0.88)** | 36.21 **(0)** | 55.35 **(0.27)**
:green_circle: | app/client/src/workers/validations.ts | …

atob Invalid CharacterError for image url

---

app/client/src/sagas/ApplicationSagas.tsx

Fix redirection to auth page when trying an app without access
Fixes #6681
- Manually
// Code coverage diff between base branch:release and head branch: fix-redirection-to-login-wo-app-access 
:green_circle: | total | 54.85 **(0)** | 36.97 **(0.01)** | 33.21 **(0)** | 55.43 **(0)**
:green_circle: | app/client/src/sagas/ApplicationSagas.tsx | 20.83 **(0)** | 7.94 **(4.55)** | 9.09 **(0)** | 23.93 **(0)**</details>

Fix redirection to auth page when trying an app without access

---

app/server/appsmith-server/src/main/resources/features/init-flags.yml

Switched feature flag strategy for js editor to email domains

Enable JS editor by email

---

app/client/src/components/ads/Dropdown.tsx
app/client/src/constants/messages.ts
app/client/src/pages/Editor/gitSync/GitConnection.tsx
app/client/src/pages/Editor/gitSync/GitSyncModal.tsx
app/client/src/pages/Editor/gitSync/components/OptionSelector.tsx
app/client/src/pages/Editor/gitSync/components/StyledComponents.tsx
app/client/src/pages/Editor/gitSync/components/UserGitProfileSettings/index.tsx
app/client/src/pages/Editor/gitSync/constants.ts

Add User Profile Section
- Replace AuthTypeSelector with OptionSelector for general use.
- Fix Scroll issue in GitSyncModal
> Manually in local
// Code coverage diff between base branch:release and head branch: feature/git-userSettings-mock-ui 
:red_circle: | total | 54.92 **(0)** | 36.94 **(0)** | 33.24 **(-0.02)** | 55.51 **(0.01)**
:green_circle: | app/client/src/constants/messages.ts | 70.38 **(-0.08)** | 100 **(0)** | 10.57 **(-0.24)** | 77.07 **(0.38)**</details>

Add User Profile Section

---

app/client/src/sagas/ActionExecutionSagas.ts

A bad type assertion was causing debugger to render objects and crashing the app. Fixed by converting to the correct type
Fixes #6709
Fixes #5732
// Code coverage diff between base branch:release and head branch: fix/debugger-rendering-object 
:red_circle: | app/client/src/sagas/ActionExecutionSagas.ts | 12.77 **(0)** | 1.98 **(-0.02)** | 9.68 **(0)** | 14.6 **(0)**</details>

Fix debugger trying to render objects

---

app/client/src/reducers/evaluationReducers/treeReducer.ts
app/client/src/sagas/EvaluationsSaga.ts
app/client/src/workers/DataTreeEvaluator.ts
app/client/src/workers/evaluation.worker.ts

To be reverted before the next release
// Code coverage diff between base branch:release and head branch: hotfix/logging-debugging-override-updates 
:green_circle: | app/client/src/reducers/evaluationReducers/treeReducer.ts | 37.5 **(1.14)** | 0 **(0)** | 50 **(0)** | 47.37 **(0.31)**
:red_circle: | app/client/src/sagas/EvaluationsSaga.ts | 20.91 **(-0.19)** | 2.94 **(-0.19)** | 6.67 **(0)** | 24.21 **(-0.26)**</details>

Hotfix for logging and debugging redux updates

---

app/server/appsmith-plugins/mysqlPlugin/src/main/java/com/external/plugins/MySqlPlugin.java
app/server/appsmith-plugins/mysqlPlugin/src/test/java/com/external/plugins/MySqlPluginTest.java
app/server/appsmith-plugins/postgresPlugin/src/main/java/com/external/plugins/PostgresPlugin.java
app/server/appsmith-plugins/postgresPlugin/src/test/java/com/external/plugins/PostgresPluginTest.java
app/server/appsmith-plugins/snowflakePlugin/src/main/java/com/external/utils/SqlUtils.java

Fixed template queries for PG, MySQL and Snowflake

---

app/client/src/components/ads/Button.tsx
app/client/src/constants/DefaultTheme.tsx
app/client/src/constants/messages.ts
app/client/src/pages/Editor/gitSync/Deploy/Deploy.tsx
app/client/src/pages/Editor/gitSync/Deploy/InitialState.tsx
app/client/src/pages/Editor/gitSync/GitSyncModal.tsx
app/client/src/selectors/gitSyncSelectors.tsx

Default deploy section state
- UI
// Code coverage diff between base branch:release and head branch: default-deploy-tab-state 
:green_circle: | total | 54.93 **(0.01)** | 36.94 **(0.01)** | 33.22 **(-0.02)** | 55.52 **(0.01)**
:red_circle: | app/client/src/components/ads/Button.tsx | 92.19 **(0)** | 78.95 **(-0.62)** | 93.02 **(0)** | 92.86 **(0)**
:red_circle: | app/client/src/constants/messages.ts | 70.31 **(-0.07)** | 100 **(0)** | 10.37 **(-0.2)** | 76.96 **(-0.11)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.71 **(0.24)** …

[git-sync] Default deploy section state

---

.github/workflows/client-test.yml
.github/workflows/external-client-test.yml

Fix cypress test yml config

---

app/client/cypress/fixtures/application-file.json

> This will fix the failing cyprus TC for import application

Update template application file to fix failing TC

---

app/client/src/entities/Action/index.ts
app/client/src/pages/Editor/APIEditor/index.tsx
app/client/src/utils/FormControlFactory.tsx

With the new UQI structure, we are changing the format in which data is sent to the server on submit press. This PR is just for the frontend changes relevant to this feature.
Fixes #6745 
// Code coverage diff between base branch:release and head branch: feature/6745-support-data-format-change-frontend 
:red_circle: | total | 54.92 **(-0.01)** | 36.93 **(-0.01)** | 33.22 **(0)** | 55.51 **(-0.01)**

Added new type to the ActionConfig, fixed some typos 

---

app/client/src/widgets/ListWidget/ListWidget.tsx

Fixes #6850
Fixes #6841
- Bug fix
- Test manually
// Code coverage diff between base branch:release and head branch: fix/list-widget-bugs 
:green_circle: | total | 55.04 **(0)** | 36.98 **(0.01)** | 33.71 **(0)** | 55.64 **(0)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.71 **(0.24)** | 38.6 **(0.88)** | 36.21 **(0)** | 55.35 **(0.27)**
:red_circle: | app/client/src/widgets/ListWidget/ListWidget.tsx | 52.24 **(0)** | 33.12 **(0)** | 42.55 **(-0.93)** | 50.79 **(0)**</details>

fix: List Item de-selection and empty state on deploy mode

---

app/server/appsmith-server/src/main/java/com/appsmith/server/featureflags/FeatureFlagEnum.java
app/server/appsmith-server/src/main/resources/features/init-flags.yml

Adds a feature flag for the multiplayer feature so that it can be turned off for specific users.
Fixes #6810 

feat: Add feature flag for multiplayer feature

---

app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/Count.java
app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/Delete.java
app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/Distinct.java
app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/Find.java
app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/commands/UpdateMany.java
app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java
app/util/plugin-generation/.gitignore

[Mongo] Added default values for query for Find, Count and Distinct commands

---

.github/workflows/client-test.yml
app/client/src/configs/index.ts
app/client/src/configs/types.ts
app/client/src/utils/helpers.tsx

Anonymise user info intercom
- Manually
// Code coverage diff between base branch:release and head branch: hash-info-while-booting-intercom 
:red_circle: | total | 54.9 **(0)** | 36.76 **(0)** | 33.62 **(0)** | 55.44 **(-0.01)**
:red_circle: | app/client/src/utils/helpers.tsx | 63.87 **(-2.24)** | 37.89 **(0)** | 45.16 **(0)** | 60.93 **(-2.26)**</details>

fix: anonymize user info intercom

---

.github/workflows/stale.yml

Check for stale issues only if they are critical

ci: Update issue state check

---

app/client/src/components/designSystems/appsmith/CenteredWrapper.tsx
app/client/src/pages/AppViewer/AppViewerPageContainer.tsx

Will render base canvas even if there are no children and show the empty page graphics on top
Fixes #5812 
- manual

fix: comments added on the blank canvas do not show up in the deployed version

---

app/client/src/constants/messages.ts
app/client/src/pages/Editor/GeneratePage/components/GeneratePageForm/GeneratePageForm.tsx
app/client/src/pages/Editor/GeneratePage/components/GeneratePageForm/GoogleSheetForm.tsx

Fixes #6974
- Manually in local
// Code coverage diff between base branch:release and head branch: fix/text-casing 
:red_circle: | total | 54.93 **(0)** | 36.83 **(0)** | 33.63 **(-0.03)** | 55.47 **(0)**
:red_circle: | app/client/src/constants/messages.ts | 70.79 **(-0.07)** | 100 **(0)** | 11.86 **(-0.21)** | 78.45 **(0.08)**
:green_circle: | app/client/src/pages/Editor/GeneratePage/components/GeneratePageForm/GoogleSheetForm.tsx | 28.42 **(0.76)** | 14.43 **(0)** | 0 **(0)** | 31.76 **(0.81)**
:red_circle: | app/client/src/utils/helpers.tsx | 63.87 **(-1.58)** …

fix: label text casing

---

app/client/src/components/ads/EmojiReactions.tsx

- manually
// Code coverage diff between base branch:release and head branch: minor-spacing-issue-reaction-bubble 
:green_circle: | total | 54.94 **(0)** | 36.83 **(0.01)** | 33.63 **(0)** | 55.49 **(0.01)**

fix: minor spacing issue reaction bubble

---

app/client/src/components/ads/TextInput.tsx
app/client/src/constants/DefaultTheme.tsx

Fixes #6969
- manually
// Code coverage diff between base branch:release and head branch: caret-color-theme 
:green_circle: | total | 54.91 **(0)** | 36.77 **(0)** | 33.63 **(0.01)** | 55.45 **(0)**
:green_circle: | app/client/src/components/ads/TextInput.tsx | 72.5 **(0.35)** | 44.9 **(0)** | 85.71 **(0.71)** | 70.67 **(0.4)**</details>

fix: caret color light theme

---

app/client/src/components/ads/ColorPickerComponent.tsx

> Removed onblur and tab interactions.
Fixes #6978 
> Added test cases.
// Code coverage diff between base branch:release and head branch: FIX/6978-color-picker-fix 
:green_circle: | total | 54.96 **(0.02)** | 36.82 **(0.01)** | 33.73 **(0.04)** | 55.5 **(0.01)**
:green_circle: | app/client/src/components/ads/ColorPickerComponent.tsx | 37.84 **(9.27)** | 63.64 **(5.31)** | 0 **(0)** | 40 **(8.18)**
:green_circle: | app/client/src/utils/helpers.tsx | 65.45 **(1.58)** | 41.05 **(3.16)** | 48.39 **(3.23)** | 62.25 **(1.32)**
:red_circle: | …

fix: updated color picker interections

---

.github/config.json

Add JSsnippets, JS editor and JS linting and errors labels to bot.
Fixes #7057
Not testable

chore: Added labels for new features

---

app/client/src/mockResponses/WidgetConfigResponse.tsx

>  add default text null string in input widget
Fixes #7002
// Code coverage diff between base branch:release and head branch: bug/new-inp-wid-default-text-err 
:red_circle: | total | 54.94 **(0)** | 36.82 **(-0.01)** | 33.62 **(0)** | 55.48 **(0)**

fix: changed defaultText to empty string

---

app/client/src/components/designSystems/appsmith/TableComponent/TableUtilities.test.tsx

> Added test cases for null or undefined value.
Fixes #6700 
- Added Test Cases
> Added test cases.
// Code coverage diff between base branch:release and head branch: FIX/6700-write-jest-testcases-for-undefined-value 
:green_circle: | total | 54.93 **(0)** | 36.84 **(0.01)** | 33.65 **(0)** | 55.47 **(0)**
:green_circle: | app/client/src/components/designSystems/appsmith/TableComponent/TableUtilities.tsx | 43.9 **(0.81)** | 24.74 **(5.15)** | 18.75 **(0)** | 42.48 **(0.89)**
:red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.47 **(-0.24)** | …

fix: updated test cases for null or undefined value in table data

---

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/WidgetType.java
app/server/appsmith-server/src/main/java/com/appsmith/server/helpers/WidgetSuggestionHelper.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionServiceTest.java

> Remove list widget from the suggested widget since its hard to form the binding query for the list widget. 
- Locally
- Unit Tests

feat: Remove list widget from suggested widget on action execution

---

app/client/src/pages/Editor/APIEditor/Form.tsx
app/client/src/pages/Editor/APIEditor/PostBodyData.tsx
app/client/src/transformers/RestActionTransformer.ts

Removes empty key value pair from headers, query parameters and form data thereby avoid execution failures from this.
Fixes #5756 
// Code coverage diff between base branch:release and head branch: fix/empty-form-data 
:green_circle: | total | 55 **(0.01)** | 36.9 **(0.02)** | 33.87 **(0.02)** | 55.55 **(0.01)**
:green_circle: | app/client/src/transformers/RestActionTransformer.ts | 95.83 **(1.71)** | 81.82 **(0.57)** | 100 **(0)** | 100 **(0)**</details>

fix: empty form data in API pane

---

app/client/src/components/formControls/FieldArrayControl.tsx

Added css property to `PrimaryBox` and `SecondaryBox`.
Fixes # (#5854)
- Query filter now fits in the container.

fix: primary and secondary box in FieldArrayControl

---

app/client/src/comments/CommentThread/CommentThread.tsx

Account for tabs for comment thread height in published mode
- Manually
// Code coverage diff between base branch:release and head branch: fix-thread-height-view-mode 
:green_circle: | total | 55.01 **(0.02)** | 36.88 **(0)** | 33.95 **(0.01)** | 55.56 **(0.01)**
:green_circle: | app/client/src/comments/CommentThread/CommentThread.tsx | 95.24 **(0.8)** | 64.65 **(-0.94)** | 83.33 **(0)** | 98.31 **(0.31)**
:green_circle: | app/client/src/selectors/editorSelectors.tsx | 73.2 **(1.3)** | 63.46 **(1.92)** | 60 **(2)** | 70.4 **(1.6)**
:red_circle: | …

fix: account for tabs for comment thread height in published mode

---

app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Application.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/BaseAppsmithRepositoryImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomApplicationRepositoryImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/LayoutActionServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewPageServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java

This PR adds the last edit time and editor username to the application when there is a change in the application.
Fixes #6860 

feat: add last edit information to application

---

app/client/src/utils/autocomplete/TernServer.ts

Added null check on autocomplete generation code.
Fixes #6649 
// Code coverage diff between base branch:release and head branch: fix/autocomplete_null_pointer 
:red_circle: | total | 55.23 **(0)** | 37.2 **(-0.01)** | 34.27 **(0)** | 55.79 **(0)**
:red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.47 **(-0.24)** | 38.26 **(-0.34)** | 36.21 **(0)** | 55.08 **(-0.27)**</details>

fix: Added null check

---

app/client/src/components/editorComponents/GlobalSearch/SnippetsDescription.tsx
app/client/src/components/editorComponents/GlobalSearch/index.tsx
app/client/src/selectors/themeSelectors.tsx

Fixes tab color and removes play icon from the snippet.
// Code coverage diff between base branch:release and head branch: fix/snippets_ui 
:red_circle: | total | 55.22 **(-0.01)** | 37.2 **(-0.01)** | 34.26 **(-0.01)** | 55.79 **(0)**
:green_circle: | app/client/src/components/editorComponents/GlobalSearch/index.tsx | 54.41 **(0.17)** | 16.89 **(0)** | 38.71 **(0)** | 56.2 **(0.18)**
:red_circle: | app/client/src/pages/Editor/GeneratePage/components/CrudInfoModal.tsx | 78.85 **(-1.92)** | 89.66 **(0)** | 33.33 **(-8.34)** | 77.08 **(-2.09)**
:red_circle: | …

fix: snippets UI

---

app/client/src/pages/Editor/WidgetsEditor.tsx
app/client/src/pages/common/CanvasSelectionArena.tsx
app/client/src/utils/hooks/useAllowEditorDragToSelect.ts

Resizing a widget trigger canvas selection which breaks DnD.
Fixes #7138
- Test A
- Test B

fix: resize breaks DnD

---

app/client/src/pages/Editor/GeneratePage/components/GeneratePageForm/GeneratePageForm.tsx
app/client/src/pages/Editor/GeneratePage/components/GeneratePageForm/styles.ts

Fixes #7151
Manually in local
// Code coverage diff between base branch:release and head branch: fix/gen_form_text_overflow 
:green_circle: | total | 55.23 **(0)** | 37.21 **(0.01)** | 34.27 **(0)** | 55.79 **(0)**

fix: text overflow

---

app/client/src/pages/Editor/GeneratePage/components/CrudInfoModal.tsx

Fix jest react state update on unmount error avoiding memory leak.
Fixes #
// Code coverage diff between base branch:release and head branch: fix/jest_error_crudInfoModal 
:green_circle: | total | 55.23 **(0)** | 37.21 **(0.01)** | 34.26 **(0)** | 55.79 **(0)**
:red_circle: | app/client/src/pages/Editor/GeneratePage/components/CrudInfoModal.tsx | 80 **(-0.77)** | 87.1 **(-2.56)** | 38.46 **(-3.21)** | 78 **(-1.17)**

chore: jest state update on unmount error

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Dropdown_spec.js

commenting dropdown_spec
Fixes #  
relying on ci
// Code coverage diff between base branch:release and head branch: test/skipDropdown_spec 
:green_circle: | total | 54.28 **(0.01)** | 36.33 **(0.01)** | 33.43 **(0)** | 54.82 **(0.01)**
:green_circle: | app/client/src/selectors/commentsSelectors.ts | 78.76 **(1.77)** | 57.58 **(3.03)** | 67.86 **(0)** | 85 **(2.5)**</details>

test: commenting dropdown_spec

---

app/client/src/sagas/SnipingModeSagas.ts

assigning string value, rather than boolean
Fixes #7306 
- manual
// Code coverage diff between base branch:release and head branch: fix/broken-checkbox-sniping 
:green_circle: | total | 54.3 **(0.03)** | 36.32 **(0)** | 33.43 **(0)** | 54.84 **(0.03)**
:green_circle: | app/client/src/sagas/SnipingModeSagas.ts | 20.41 **(2.87)** | 3.33 **(-0.12)** | 40 **(0)** | 21.28 **(3.1)**</details>

fix: sniping checkbox will set the string not boolean

---

app/server/appsmith-git/src/main/java/com/appsmith/git/service/GitExecutorImpl.java
app/server/appsmith-interfaces/src/main/java/com/appsmith/external/git/GitExecutor.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/GitServiceImpl.java

> API to clone the remote repo
Fixes #
- Locally via postman
- Unit Tests

feat: Add clone API 

---

app/client/src/pages/Editor/GeneratePage/components/GeneratePageForm/GeneratePageForm.tsx

fixes the text overflow issue
Fixes #7151
Local
// Code coverage diff between base branch:release and head branch: fix/text_overflow_gen_crud 
:green_circle: | total | 54.27 **(0)** | 36.32 **(0.01)** | 33.43 **(0)** | 54.81 **(0)**

fix: text overflow issue

---

app/client/src/constants/messages.ts
app/client/src/pages/Editor/gitSync/GitConnection.tsx

feat: Add remoteURL unlink functionality

---

app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/GetValuesMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/InfoMethod.java

> Group the errors from plugin execution
Fixes #7096 
- Locally via postman

feat: Classify the error messages to validation or plugin errors

---

app/client/src/components/formControls/utils.ts
app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
app/client/src/pages/Editor/QueryEditor/index.tsx
app/client/src/sagas/FormEvaluationSaga.ts
app/client/src/sagas/QueryPaneSagas.ts

When we were extracting the initial values from the form JSON, there were 2 assumptions that were causing an issue
1. We assume the top-level object will always be a SECTION
2. If an object has children, its `initialValue` was ignored.
Have fixed this and did some refactoring.
Fixes #7399 
- Bug fix (non-breaking change which fixes an issue)## Checklist:
// Code coverage diff between base branch:release and head branch: fix/7399-fix-initial-values-extraction-from-json 
:green_circle: | total | 54.88 **(0.01)** | 36.89 **(0.02)** | 34.23 **(0)** | 55.4 **(0.01)** …

fix: Initial values extraction process from json 

---

app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/plugins/GoogleSheetsPlugin.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/resources/editor.json
app/server/appsmith-plugins/googleSheetsPlugin/src/main/resources/setting.json

feat: Smart Substitution for Google Sheets Plugin

---

app/client/src/pages/common/PageHeader.tsx

Check for anonymous user before fetching notifications to prevent unauthorised calls being done that would return 401s
- manually

chore: check for anonymous user before fetching notifs

---

app/client/cypress/support/index.js

Remove debugger as suggested by deepSource issue.
Fixes #7137 
Refactor
// Code coverage diff between base branch:release and head branch: remove-debugger 
:green_circle: | total | 54.88 **(0.01)** | 36.88 **(0.01)** | 34.23 **(0)** | 55.4 **(0.01)**

chore: remove debugger

---

app/client/src/AppRouter.tsx
app/client/src/pages/common/PageHeader.tsx

This commit suppresses irrelevant toaster when user visits welcome page post intallation.
Fixes #7433 
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: fix/login-redirect-error-welcome-page 
:green_circle: | total | 54.88 **(0.01)** | 36.88 **(0.01)** | 34.23 **(0)** | 55.4 **(0.01)** …

fix: Suppress unauthorised error when user visits welcome page post installation

---

app/client/src/constants/routes.ts
app/client/src/pages/Applications/index.tsx
app/client/src/pages/Editor/EditorHeader.tsx
app/client/src/pages/UserAuth/SignUp.tsx
app/client/src/selectors/onboardingSelectors.tsx

This PR fixes issue where signposting and welcome tour are active at the same time.
Fixes #7405 
Fixes #7226
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: fix/onbarding-signposting-overlap-issue 
:red_circle: | total | 54.86 **(-0.05)** | 36.81 **(-0.01)** | 34.25 **(-0.07)** | 55.39 **(-0.04)** …

fix: Signposting and Welcome tour overlapping issue

---

app/client/src/constants/messages.ts
app/client/src/pages/Applications/index.tsx
app/server/appsmith-plugins/mssqlPlugin/src/main/resources/setting.json
app/server/appsmith-plugins/mysqlPlugin/src/main/resources/setting.json
app/server/appsmith-plugins/postgresPlugin/src/main/resources/setting.json
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java

Fixing some typos and moving raw strings from the home page to `messages.ts` file
// Code coverage diff between base branch:release and head branch: chore/fix-messages 
:green_circle: | total | 54.86 **(0.01)** | 36.64 **(0.01)** | 34.23 **(-0.02)** | 55.39 **(0)**
:red_circle: | app/client/src/constants/messages.ts | 74.91 **(-0.13)** | 100 **(0)** | 25.19 **(-0.4)** | 81.29 **(0.06)**

chore: Minor changes for fixing some strings on the home page & action settings page

---

app/client/src/components/ads/Button.tsx
app/client/src/constants/DefaultTheme.tsx
app/client/src/constants/messages.ts
app/client/src/index.css
app/client/src/pages/Applications/ApplicationCard.tsx
app/client/src/pages/Applications/index.tsx
app/client/src/pages/UserAuth/FooterLinks.tsx
app/client/src/pages/UserAuth/ForgotPassword.tsx
app/client/src/pages/UserAuth/Login.tsx
app/client/src/pages/UserAuth/ResetPassword.tsx
app/client/src/pages/UserAuth/StyledComponents.tsx
app/client/src/pages/UserAuth/index.tsx

Login page UI changes and bug fixes
#7362 
- Tested the UI colors manually

feat: Login page UI v2

---

app/client/src/utils/helpers.tsx

>
changing Scrolling into view from center to nearest to make sure the scroll doesn't overdo.
Fixes #7526
- Test A
- Test B

fix: changing Scrolling into view from center to nearest

---

app/client/src/widgets/DropdownWidget/index.ts

During refactors, the name of the Select Widget was renamed to Dropdown Widget, this has been corrected in this PR.
Visually

chore: Correct Select widget name in widget list

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Input_spec.js

test: fixFlakyInputSpec

---

app/client/src/widgets/ListWidget/widget/derived.js

fix for list widget cyclic dependency
Fixes #7520 
manual ui verification
// Code coverage diff between base branch:release and head branch: listwidgetCyclic 
:red_circle: | total | 54.89 **(0)** | 36.7 **(-0.01)** | 34.21 **(0)** | 55.42 **(0)**
:red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.47 **(-0.24)** | 38.26 **(-0.87)** | 36.21 **(0)** | 55.08 **(-0.27)**
:red_circle: | app/client/src/widgets/ListWidget/widget/derived.js | 61.11 **(-1.15)** | 35.71 **(0)** | 50 **(0)** | 58.82 **(-1.18)**</details>

fix: list widget cyclic dependency

---

app/client/src/components/designSystems/appsmith/WidgetStyleContainer.tsx
app/client/src/pages/Editor/Explorer/Widgets/useNavigateToWidget.ts
app/client/src/utils/helpers.tsx
app/client/src/widgets/ContainerWidget/component/index.tsx

Removing newly added Container styles for Main container.
Fixes #7526
- Test A
- Test B …

fix: flashElement scrolls canvas too much.

---

app/client/src/pages/setup/DetailsForm.tsx
app/client/src/pages/setup/Landing.tsx
app/client/src/pages/setup/SetupForm.tsx
app/client/src/pages/setup/index.tsx
app/client/src/utils/storage.ts

This commit fixes confetti z-index, scrollbar and dropdown boundary issue welcome page.
Fixes: #7503
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: fix/misc-welcome-page-issues 
:green_circle: | app/client/src/utils/storage.ts | 35 **(0.19)** | 13.64 **(0)** | 12.82 **(0)** | 27.82 **(0.21)**</details>

chore: Misc welcome page minor issues

---

app/client/src/widgets/MultiSelectWidget/component/index.styled.tsx

Fix SelectAll design
Fixes #7261
// Code coverage diff between base branch:release and head branch: fix--Multiselect-selectAll-design 
:red_circle: | app/client/src/selectors/commentsSelectors.ts | 78.23 **(-1.61)** | 54.41 **(-2.94)** | 70 **(0)** | 84.09 **(-2.27)**

fix: multiselect selectAll design

---

app/client/src/widgets/MultiSelectWidget/component/index.tsx

Multiselect widget loading state
Fixes #7285
// Code coverage diff between base branch:release and head branch: fix--multiselect-show-skeleton-on-laod 
:green_circle: | total | 54.88 **(0.01)** | 36.88 **(0.01)** | 34.23 **(0)** | 55.4 **(0.01)**

fix: multiselect loading state

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ApplicationForkingService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ExamplesOrganizationCloner.java

If source application has an action with onPageLoad=true, it becomes false if application is forked. This PR fixes this issue.
Fixes #7220 

fix: on page load actions are disabled after fork app

---

app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/plugins/GoogleSheetsPlugin.java

fix: Datasource structure command failure for Google Sheets

---

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/Condition.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/GetValuesMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/MethodConfig.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/resources/editor.json

feat: Adding "where" clause support for Google Sheets Plugin

---

app/client/src/pages/Applications/ImportApplicationModal.tsx

added some margin at the top of the btn
Fixes #7394 
- manual

chore: fixed alignment for import btn

---

app/client/src/constants/messages.ts
app/client/src/pages/Editor/Explorer/EntityExplorer.tsx
app/client/src/pages/Editor/FirstTimeUserOnboarding/Checklist.tsx
app/client/src/pages/Editor/FirstTimeUserOnboarding/Statusbar.tsx
app/client/src/pages/Editor/FirstTimeUserOnboarding/testUtils.ts
app/client/src/selectors/onboardingSelectors.tsx

Fixes minor issues on the signposting flow
Fixes: #7223
Fixes: #7225
Fixes: #7228
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: fix/signposting-misc-issues 
:green_circle: | total | 54.9 **(0.02)** | 36.74 **(0.03)** | 34.21 **(0.01)** | 55.43 **(0.01)** …

chore: Miscellaneous signposting issues fixes

---

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/services/FilterDataService.java
app/server/appsmith-interfaces/src/test/java/com/appsmith/external/services/FilterDataServiceTest.java

fix: Adding handling for columns with multiple words in name for filtering data in filtering library

---

app/client/src/components/editorComponents/Sidebar.tsx
app/client/src/constants/DefaultTheme.tsx
app/client/src/pages/Editor/FirstTimeUserOnboarding/Statusbar.tsx

Remove unnecessary scrollbar that appears on the entity explorer during onboarding.
Fixes #7425 
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: fix/scrollbar-onboarding 
:green_circle: | total | 54.8 **(0)** | 36.55 **(0)** | 33.95 **(0.02)** | 55.35 **(0)**
:red_circle: | …

chore: Fix unnecessary scrollbar in entity explorer during onboarding

---

app/client/src/components/editorComponents/GlobalSearch/HelpBar.tsx

setting cursor to `default`
manual
// Code coverage diff between base branch:release and head branch: fix/omnibar-pointer 
:green_circle: | total | 54.8 **(0)** | 36.57 **(0.01)** | 33.95 **(0)** | 55.35 **(0)**

style: show default mouse pointer when user hovers over omnibar

---

app/client/src/components/ads/ButtonTabComponent.tsx
app/client/src/components/ads/ColorPickerComponent.tsx
app/client/src/components/ads/IconTabsComponent.tsx
app/client/src/components/ads/Switch.tsx
app/client/src/components/ads/TreeDropdown.tsx
app/client/src/components/editorComponents/CodeEditor/styledComponents.ts
app/client/src/components/editorComponents/PaneWrapper.tsx
app/client/src/components/propertyControls/IconSelectControl.tsx
app/client/src/components/propertyControls/InputTextControl.tsx
app/client/src/components/propertyControls/MenuItemsControl.tsx
app/client/src/components/propertyControls/PrimaryColumnsControl.tsx
app/client/src/components/propertyControls/StyledControls.tsx
app/client/src/components/propertyControls/TabControl.tsx
app/client/src/constants/Colors.tsx
app/client/src/icons/ControlIcons.tsx
app/client/src/icons/FormIcons.tsx
app/client/src/pages/Editor/Popper.tsx
app/client/src/pages/Editor/PropertyPane/PanelPropertiesEditor.tsx
app/client/src/pages/Editor/PropertyPane/PropertyPaneConnections.tsx
app/client/src/pages/Editor/PropertyPane/index.tsx
app/client/src/pages/Editor/PropertyPaneHelpButton.tsx
app/client/src/pages/Editor/PropertyPaneTitle.tsx

Updated the property pane according to the new light theme

style: property pane updates

---

app/server/appsmith-plugins/googleSheetsPlugin/src/main/resources/editor.json

feat: Adding where clause for command  Query range method for `Fetch sheet rows` 

---

app/client/src/components/editorComponents/CloseEditor.tsx
app/client/src/pages/Editor/Explorer/Actions/helpers.tsx

The back button across for all the editors now will perform true go back action. This simplifies a lots of scenarios including going back to generate page vs going back to empty canvas.
Fixes #6813
- manual
// Code coverage diff between base branch:release and head branch: fix/back-btn-bug 
:green_circle: | total | 54.62 **(0.01)** | 36.4 **(0.01)** | 33.83 **(0)** | 55.21 **(0.01)**
:green_circle: | app/client/src/components/editorComponents/CloseEditor.tsx | 53.33 **(11.39)** | 100 **(75)** | 0 **(0)** | 53.33 **(11.39)**</details>

fix: back btn navigation problems

---

app/client/src/widgets/MultiSelectWidget/widget/index.tsx
app/client/src/workers/validations.test.ts
app/client/src/workers/validations.ts

fix multiselect validation issue.
to reproduce us
```js
[
{
"label": true,
"value": {{true}}
},
{
"label": "Green",
"value": "GREEN"
},
{
"label": "Red",
"value": "RED"
}
]
```
in the options and search for `true` in the input
Fixes #7604
// Code coverage diff between base branch:release and head branch: fix/multiselect-widget-critical-error 
:green_circle: | total | 54.6 **(0)** | 36.38 **(0.01)** | 33.81 **(0)** | 55.2 **(0)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 50.71 **(0.24)** | 39.13 **(0.87)** | 36.21 **(0)** | 55.35 …

fix: multiselect validation

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/LayoutActionServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/LayoutActionServiceTest.java

fix: Use populated actionDTO for json path keys in JS during refactor

---

app/client/src/pages/Editor/FirstTimeUserOnboarding/Statusbar.test.tsx
app/client/src/pages/Editor/FirstTimeUserOnboarding/testUtils.ts
app/client/src/pages/Editor/utils.ts

Fixes: #7730
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: fix/nested-path-biding-signposting-issue 
:green_circle: | total | 54.8 **(0.04)** | 36.57 **(0.05)** | 33.88 **(0.08)** | 55.41 **(0.04)** …

chore: Fix signposting issue where application erroring out if there is nested binding

---

app/client/src/actions/applicationActions.ts
app/client/src/actions/gitSyncActions.ts
app/client/src/api/ApplicationApi.tsx
app/client/src/api/GitSyncAPI.tsx
app/client/src/components/ads/TextInput.tsx
app/client/src/constants/ReduxActionConstants.tsx
app/client/src/constants/messages.ts
app/client/src/pages/AppViewer/viewer/AppViewerHeader.tsx
app/client/src/pages/AppViewer/viewer/PageTabs.tsx
app/client/src/pages/AppViewer/viewer/PageTabsContainer.tsx
app/client/src/pages/Editor/APIEditor/index.tsx
app/client/src/pages/Editor/EditorHeader.tsx
app/client/src/pages/Editor/IntegrationEditor/DatasourceHome.tsx
app/client/src/pages/Editor/gitSync/GitSyncModal.tsx
app/client/src/pages/Editor/gitSync/ImportAppViaGitModal.tsx
app/client/src/pages/Editor/gitSync/Tabs/Deploy.tsx
app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx
app/client/src/pages/Editor/gitSync/components/DeployPreview.tsx
app/client/src/pages/Editor/gitSync/components/DirectDeploy.tsx
app/client/src/pages/Editor/gitSync/constants.ts
app/client/src/pages/Editor/gitSync/hooks.ts
app/client/src/reducers/uiReducers/applicationsReducer.tsx
app/client/src/reducers/uiReducers/gitSyncReducer.ts
app/client/src/sagas/ApplicationSagas.tsx
app/client/src/sagas/GitSyncSagas.ts
app/client/src/selectors/applicationSelectors.tsx
app/client/src/selectors/gitSyncSelectors.tsx

-  Add Global Config fetch in git connection
-  Add Success Toast Msg for commit and push API
-  Fix generate and fetch SSHKey API
-  Fix Close button UI
-  Add Tick Icon when SSH Key is copied
Fixes #6632 
// Code coverage diff between base branch:release and head branch: git_sync_modal_update 
:green_circle: | total | 54.76 **(0)** | 36.58 **(0.06)** | 33.84 **(0.04)** | 55.36 **(-0.01)**
:red_circle: | app/client/src/actions/apiPaneActions.ts | 67.86 **(0.12)** | 100 **(0)** | 0 **(0)** | 52.63 **(-2.37)**
:red_circle: | …

feat: Add Git push API & UI Updates

---

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/InstanceConfig.java

Since the file diff on GitHub doesn't do justice to what this PR actually is about, here's a picture!
This is printed after the server is up.

feat: Announce that Appsmith is running!

---

app/client/cypress/fixtures/checkboxgroupDsl.json
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/CheckboxGroup_spec.js
app/client/cypress/support/commands.js

updated common method
- force click 
- force clear

test: fix/Updated common method

---

.github/workflows/github-release.yml

Remove unused services from release builder workflow.

ci: Remove unneeded checks and services

---

app/client/src/pages/Editor/gitSync/Tabs/GitConnection.tsx
app/client/src/pages/Editor/gitSync/components/UserGitProfileSettings/index.tsx
app/client/src/sagas/ApplicationSagas.tsx
app/client/src/sagas/GitSyncSagas.ts

fix: Git sync modal minor fixes

---

app/server/appsmith-server/src/main/java/com/appsmith/server/ServerApplication.java

Since we have our own banner in #7735, this PR will remove the default Spring banner.

feat: Remove Spring startup banner

---

CONTRIBUTING.md
contributions/ClientSetup.md
contributions/CodeContributionsGuidelines.md
contributions/ServerSetup.md

Updated Contribution Guides
- Contributing.md
- ClientSetup.md
- ServerSetup.md

docs: Updating contribution guides

---

app/server/appsmith-server/src/main/resources/CRUD-DB-Table-Template-Application.json

fix: Adding where key in generate CRUD application with google sheets for SelectQuery

---

app/server/appsmith-server/src/main/java/com/appsmith/server/featureflags/FeatureFlagEnum.java
app/server/appsmith-server/src/main/resources/features/init-flags.yml

- Remove feature flag for Snippets feature since it is ready for public release now. 
- Manual

fix: remove feature flag for Snippets feature

---

app/client/src/utils/DSLMigrations.ts
app/client/src/utils/migrations/TableWidget.test.ts
app/client/src/utils/migrations/TableWidget.ts

Fixes the migration issues arrived from #7166 and #7310 
Fixes #7796 
Tested by using generate page as shown in the issue #7796 
// Code coverage diff between base branch:release and head branch: fix/table-button-migration 
:green_circle: | total | 54.89 **(0)** | 37.03 **(0.01)** | 33.88 **(0)** | 55.5 **(0)**
:green_circle: | app/client/src/selectors/commentsSelectors.ts | 79.84 **(1.61)** | 57.35 **(2.94)** | 70 **(0)** | 86.36 **(2.27)**
:red_circle: | app/client/src/utils/DSLMigrations.ts | 74.17 **(-0.23)** | 65.44 **(-0.17)** | 69.66 **(-0.79)** | 73.98 …

fix: table button migration issues

---

Dockerfile

fix: Added specific locale to root Dockerfile

---

app/server/appsmith-server/src/main/java/com/appsmith/server/domains/ApplicationJson.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomActionCollectionRepository.java
app/server/appsmith-server/src/main/java/com/appsmith/server/repositories/CustomActionCollectionRepositoryImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ActionCollectionService.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java
app/server/appsmith-server/src/test/resources/test_assets/ImportExportServiceTest/valid-application.json

fix: Changes for JS actions in the import/export feature

---

app/client/src/pages/Applications/index.tsx

Remove unnecessary scrolling in search result emprty UI.
Fixes #7459
Manually in local.

fix: Remove unneccessary scrolling

---

app/server/appsmith-server/src/main/java/com/appsmith/server/authentication/handlers/AuthenticationSuccessHandler.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/UserSignup.java

>
In the signposting feature, we create a default application when someone signs up. Currently, it works for form based signups only. This PR adds oauth for signposting also. 
Fixes #7417
- Manually

fix: Signposting when user signs up with oauth is not working

---

CONTRIBUTING.md

The current discord invite link seems broken, this change updates to the link.
Locally

fix: discord link in CONTRIBUTING.md

---

app/client/src/widgets/TableWidget/index.ts

Use correct link to docs
Fixes #7978 
// Code coverage diff between base branch:release and head branch: fix/Table-widget-wrong-doc-link 
:green_circle: | total | 54.81 **(0)** | 36.95 **(0)** | 33.8 **(0)** | 55.43 **(0.01)**
:green_circle: | app/client/src/sagas/SaaSPaneSagas.ts | 36.96 **(0.96)** | 33.33 **(7.01)** | 50 **(0)** | 47.06 **(2.32)**</details>

fix: wrong doc link

---

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ApplicationForkingService.java

Fixes #7986 
> Tested manually

fix: Update permission for forking application to enable templates forking

---

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ImportExportApplicationServiceTests.java
app/server/appsmith-server/src/test/resources/test_assets/ImportExportServiceTest/valid-application-without-action-collection.json

fix: Fixed check for missing action collections

---

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/models/Condition.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/MethodConfig.java

fix: Handling the empty object set for where clause value in new google sheets action

---

contributions/docs/CONTRIBUTING.md
contributions/docs/adding_guides.md

- Added How-to Guide guidelines
- updated links for Documentation issues

docs: Updating doc contribution guides

---

app/client/src/components/ads/Icon.tsx
app/client/src/pages/Applications/index.tsx
app/client/src/pages/Editor/EditorHeader.tsx
app/client/src/pages/Editor/EditorSaveIndicator.tsx
app/client/src/pages/common/SharedUserList.tsx

Enhancements to editor header

---

app/client/src/components/ads/FilePickerV2.tsx
app/client/src/pages/Applications/ImportApplicationModal.tsx

swap out file picker in import application modal

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/LayoutActionServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceTest.java

fix: Refactor now uses FQN when available

---

app/client/src/widgets/InputWidget/component/index.tsx

> add focus numericInputComponent . 
Fixes #7819
// Code coverage diff between base branch:release and head branch: fix/number-input-auto-focus 
:green_circle: | total | 54.81 **(0)** | 36.95 **(0.01)** | 33.8 **(0)** | 55.43 **(0.01)**
:green_circle: | app/client/src/selectors/commentsSelectors.ts | 79.84 **(1.61)** | 57.35 **(2.94)** | 70 **(0)** | 86.36 **(2.27)**</details>

fix: added auto focus for number input

---

app/client/src/components/designSystems/appsmith/Dropdown.tsx
app/client/src/components/designSystems/appsmith/TextInputComponent.tsx
app/client/src/components/editorComponents/FormLabel.tsx
app/client/src/components/formControls/DropDownControl.tsx
app/client/src/components/formControls/DynamicInputTextControl.tsx
app/client/src/components/formControls/FilePickerControl.tsx
app/client/src/components/formControls/StyledControls.tsx
app/client/src/pages/Editor/EditorHeader.tsx

Change editor input colors

---

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ImportExportApplicationService.java

> Check if the page is deleted (published and unpublished part) and then include to applicationPages list in application object
> Tested manually

fix: Don't include the deleted page in applicationPages for export application flow

---

app/rts/src/server.ts

Emits list of users who are currently editing a page of an application 
- Manually

feat: added event for online page editors

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Applications/ExportApplication_spec.js

Updated the test cases for export flow. It considers different user permissions to check if the export option is available to the users or not

chore: updated test cases for export app flow

---

app/client/src/pages/common/SharedUserList.tsx

Fix alignment in share user list

---

app/client/src/components/editorComponents/JSResponseView.tsx
app/client/src/constants/messages.ts
app/client/src/entities/DataTree/dataTreeJSAction.ts
app/client/src/pages/Editor/JSEditor/JSObjectNameEditor.tsx
app/client/src/sagas/PostEvaluationSagas.ts
app/client/src/utils/autocomplete/dataTreeTypeDefCreator.ts

Small fixes as part of 6872
// Code coverage diff between base branch:release and head branch: small-fixes-js-editor 
:green_circle: | total | 54.81 **(0)** | 36.94 **(-0.01)** | 33.8 **(0)** | 55.43 **(0.01)**
:red_circle: | app/client/src/constants/messages.ts | 74.31 **(-0.02)** | 100 **(0)** | 23.37 **(-0.06)** | 80.56 **(0.03)**
:green_circle: | app/client/src/entities/DataTree/dataTreeJSAction.ts | 12.9 **(0.78)** | 0 **(0)** | 0 **(0)** | 10.71 **(0.71)**
:red_circle: | app/client/src/pages/Editor/JSEditor/JSObjectNameEditor.tsx | 22.22 **(0)** | 4.26 …

fix: small fixes js editor

---

app/client/src/utils/AnalyticsUtil.tsx

using the cached anonymous id for user properties in ce

chore: anonymised user id for CE

---

app/client/src/pages/Applications/index.tsx

Removed hardcoded version name
// Code coverage diff between base branch:release and head branch: bug-fix/version-tag 
:green_circle: | total | 54.82 **(0.01)** | 36.85 **(0.02)** | 33.9 **(0.01)** | 55.42 **(0.01)**
:green_circle: | app/client/src/utils/helpers.tsx | 60.49 **(2.05)** | 31.85 **(3.7)** | 43.24 **(2.7)** | 57.89 **(2.1)**</details>

fix: Hardcoded version name removed

---

app/client/src/constants/messages.ts

Small PR to fix grammar
- Manual

chore: appsmith->Appsmith

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/Bind_InputWidget_Table_Sorting_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/ExplorerTests/Entity_Explorer_Query_Datasource_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/CheckboxGroup_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/Radio_spec.js
app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/ExplorerTests/Entity_Explorer_CopyQuery_RenameDatasource_spec.js
app/client/cypress/support/commands.js

test: Updated flaky test

---

app/client/src/constants/messages.ts
app/client/src/pages/setup/DataCollectionForm.tsx
app/client/src/pages/setup/DetailsForm.tsx
app/client/src/pages/setup/NewsletterForm.tsx

Makes following changes to welcome page form
Usage data preference
Share anonymous usage data to help improve the product.
See what is shared
If the toggle is on: Share data & make appsmith better!
If the toggle is off: Don't share any data
Fixes #8165
manual
// Code coverage diff between base branch:release and head branch: chore/welcome-page-text-change 
:red_circle: | total | 54.84 **(0.02)** | 36.85 **(0)** | 33.83 **(-0.06)** | 55.43 **(0.01)**
:red_circle: | app/client/src/constants/messages.ts | 74.42 **(-0.3)** | 100 **(0)** | 23.67 **(-0.91)** | 80.13 …

chore: change welcome page telemetry label

---

contributions/ClientSetup.md

Fixes #8249. Please check out the issue for more insights.
I presume this change doesn't need tests.

fix: grammatical issue

---

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/EnvManager.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/UserSignup.java
app/server/appsmith-server/src/main/resources/application.properties
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/EnvManagerTest.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/UserSignupTest.java

Update backend for the changes in admin settings page.
Fixes #8760 
- Manually

fix: Update admin settings API for changes in UI

---

app/client/src/widgets/AudioWidget/component/index.tsx

Fixes #7868
Hidden the audio options as per https://github.com/appsmithorg/appsmith/issues/7868#issuecomment-932018289
- Test A
- Test B

fix: [Bug]Audio option hidden on edit mode

---

app/client/cypress/setup-test.sh
app/client/cypress/support/index.js

Temporarily comment out super user cypress test
- Test A
- Test B

chore: Comment super user cypress test

---

app/client/src/widgets/MapWidget/widget/index.tsx

Fixes #8912
- Manual 
// Code coverage diff between base branch:release and head branch: mohanarpit-patch-1 
:green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(1.64)** | 64.71 **(2.95)** | 73.33 **(0)** | 90.59 **(2.35)**</details>

chore: Fixing typo in tooltip for Map widget property

---

app/server/appsmith-server/src/main/java/com/appsmith/server/configurations/CommonConfig.java

fix: Fix allowed domains configuration breaking OAuth

---

app/client/cypress/support/commands.js

test: Added suitable wait

---

app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/UserProfileDTO.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/UserServiceImpl.java

Added a new property `isConfigurable` in the response of the profile API i.e. `/me`. This will be present for super users only.
Fixes #8605 
- Manually

feat: [Feature] Add `isConfigurable` property in profile response for the super admins

---

app/server/appsmith-server/src/main/java/com/appsmith/server/domains/OrganizationPlugin.java

Tiny fix to make organization plugins unique to let SaaS plugin installation cleaner.

fix: Make organization plugins unique

---

app/server/appsmith-server/src/main/java/com/appsmith/server/controllers/ApplicationController.java
app/server/appsmith-server/src/main/java/com/appsmith/server/domains/Application.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java

chore: Adding evaluation version in application for new evaluation logic.

---

app/client/src/components/editorComponents/CodeEditor/lintHelpers.test.ts
app/client/src/components/editorComponents/CodeEditor/lintHelpers.ts

fix: lint position is incorrect

---

app/client/src/utils/autocomplete/TernServer.ts

Added global functions to autocompletion for widgets
Fixes #9003 
Manual
// Code coverage diff between base branch:release and head branch: fix/add-global-functions-to-widget-autocompletion 
:green_circle: | total | 54.76 **(0.01)** | 36.55 **(0.01)** | 33.51 **(0.01)** | 55.29 **(0.01)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.04 **(1.14)** | 40.42 **(1.93)** | 34.48 **(1.72)** | 55.96 …

fix: Add global functions to autocompletion for widgets

---

app/client/src/components/ads/Toast.tsx
app/client/src/index.css

Fixes #8102 
Manual
// Code coverage diff between base branch:release and head branch: fix/toast-width 
:red_circle: | app/client/src/components/ads/Toast.tsx | 77.36 **(-1.49)** | 62.5 **(0)** | 80 **(-4.21)** | 77.36 **(-1.49)**</details>

fix: toast width to fit-content

---

app/client/src/components/ads/Dropdown.tsx

Fixes #9037 
Locally
// Code coverage diff between base branch:release and head branch: fix/dropdown-subtext-alignment 
:red_circle: | total | 54.78 **(-0.01)** | 36.61 **(-0.02)** | 33.52 **(0)** | 55.32 **(-0.01)**
:green_circle: | app/client/src/components/ads/Dropdown.tsx | 53.55 **(0)** | 37.5 **(0.33)** | 25.86 **(0)** | 51.77 **(0)**
:red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.04 **(-0.22)** | …

fix: dropdown subtext alignment

---

.github/workflows/test-build-docker-image.yml

This step in the workflow would actually never run because of the way the workflow is triggered and the conditions set on it. So this PR removes this unused step.

ci: Remove unused package for DP step

---

app/server/appsmith-plugins/googleSheetsPlugin/src/main/resources/editor.json

fix: Add support for dynamic bindings in Google Sheets URL field

---

.github/workflows/integration-tests-command.yml

>
> Update integration-tests-command.yml for the CI changes to comment PR Number, github username and sha  info #9122
> 
> Replicated the CI into my own repo tested the changes there and could successfully comment on the PR
>
- Test A
- Test B
- [] I have performed a self-review of my own code

ci: Post comment on PRs with link to test workflow runs

---

app/server/appsmith-server/src/main/resources/features/init-flags.yml

Enabling JS editor for all users

chore: Enabling JS editor for all users

---

SECURITY.md
appsmith_events.md

I have updated appsmith_events.md

docs: Updated appsmith_events.md and SECURITY.md

---

app/client/src/entities/Replay/replayUtils.ts
app/client/src/pages/Editor/DataSourceEditor/RestAPIDatasourceForm.tsx
app/client/src/sagas/DatasourcesSagas.ts

* datasource bug fix

---

app/server/appsmith-interfaces/src/main/java/com/appsmith/external/helpers/DataTypeStringUtils.java
app/server/appsmith-plugins/amazons3Plugin/src/main/java/com/external/plugins/AmazonS3Plugin.java
app/server/appsmith-plugins/amazons3Plugin/src/main/resources/setting.json
app/server/appsmith-plugins/amazons3Plugin/src/test/java/com/external/plugins/AmazonS3PluginTest.java

feat: Added Smart substitution support for S3

---

app/client/src/entities/DataTree/dataTreeJSAction.ts
app/client/src/workers/DataTreeEvaluator.ts
app/client/src/workers/evaluationUtils.ts

this wasn't working because we were not saving in resolved function to execute
// Code coverage diff between base branch:release and head branch: this-js-bug 
:green_circle: | total | 54.59 **(0.01)** | 36.44 **(0.01)** | 33.22 **(0)** | 55.11 **(0)**
:red_circle: | app/client/src/entities/DataTree/dataTreeJSAction.ts | 12.5 **(-0.83)** | 0 **(0)** | 0 **(0)** | 10.34 **(-0.77)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.26 …

fix: this is undefined in js editor

---

app/client/cypress/setup-test.sh
app/client/cypress/support/index.js

Fixes #9180 
// Code coverage diff between base branch:release and head branch: task/comment-super-user-cypress-test-fix 
:red_circle: | total | 54.67 **(-0.01)** | 36.59 **(-0.01)** | 33.33 **(0)** | 55.19 **(-0.01)**
:red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.04 **(-0.22)** | 40.42 **(-0.83)** | 34.48 **(0)** | 55.96 **(-0.26)**</details>

test: Fix super user signup form cypress test

---

deploy/k8s/templates/backend-template.yaml

>
This PR addes a liveness Probe Check to the backend deployment template of k8s
Works on #4430 
It was discussed in the issue #4430 

feat: add liveness Probe to backend deployment manifest

---

app/client/cypress/support/commands.js
app/client/cypress/support/index.js

test: updated getUser route

---

app/server/appsmith-plugins/amazons3Plugin/src/main/resources/editor/create.json
app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/helpers/DataUtils.java
app/server/appsmith-plugins/restApiPlugin/src/test/java/com/external/plugins/RestApiPluginTest.java

Modified logic to use first character of incoming JSON string to look for best match.

fix: Modified multipart logic to avoid exception handling

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ActionCollectionServiceImpl.java

fix: Add null check for unpublished collections in view mode

---

app/client/src/widgets/CheckboxGroupWidget/widget/index.tsx

>  fixed the default value is unchecked when user add new value in multi-select checkbox
Fixes #8763 
// Code coverage diff between base branch:release and head branch: bug/checkbox-default-selected 
:red_circle: | total | 54.63 **(0)** | 36.35 **(-0.01)** | 33.09 **(0)** | 55.15 **(-0.01)**
:red_circle: | app/client/src/widgets/CheckboxGroupWidget/widget/index.tsx | 58.06 **(-2.96)** | 29.17 **(-5.83)** | 44.44 **(-2.62)** | 58.62 **(-3.2)**</details>

fix: handled component update value logic

---

app/client/src/constants/messages.ts

Fixes grammar of fat container welcome message
- Bug fix
It has been tested locally

chore: Fixes fat container welcome message for email

---

.github/workflows/integration-tests-command.yml
.github/workflows/test-build-docker-image.yml

change jobs to 24
Change number of jobs to 24
Tested locally

test: Change number of jobs to 24

---

app/client/src/components/editorComponents/CodeEditor/index.tsx

Fixes #9251 
Manual
// Code coverage diff between base branch:release and head branch: fix/editor-undefined-bug 
:red_circle: | total | 54.65 **(0)** | 36.34 **(-0.01)** | 33.11 **(0)** | 55.17 **(-0.01)**
:green_circle: | app/client/src/components/editorComponents/CodeEditor/index.tsx | 67.02 **(-0.12)** | 40.24 **(0.12)** | 51.28 **(0)** | 66.92 **(0.13)**
:red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.04 **(-0.22)** | 40.42 **(-0.83)** | 34.48 **(0)** | 55.96 **(-0.26)**</details>

fix: editor undefined bug

---

deploy/ansible/appsmith_playbook/roles/generate_template/templates/nginx-app.conf.j2
deploy/docker/templates/nginx_app.conf.sh
deploy/k8s/scripts/nginx-configmap.yaml
deploy/template/nginx_app.conf.sh

Fix OAuth failing when there's SSL termination

---

app/client/src/widgets/VideoWidget/component/index.tsx
app/client/src/widgets/VideoWidget/widget/index.tsx

>  added muted flag and updated helper text in video widget.
Fixes #5606

fix: added muted flag and updated helper text

---

app/client/src/workers/DataTreeEvaluator.ts
app/client/src/workers/evaluation.test.ts

This PR in conjunction with  [8981](https://github.com/appsmithorg/appsmith/pull/8981), fixes #9168 
Jest 

fix: properly update dependency map

---

app/client/src/api/GitSyncAPI.tsx
app/client/src/constants/messages.ts
app/client/src/pages/Editor/gitSync/QuickGitActions/index.tsx

- Disable pull button if we have local uncommitted changes
- Use body params instead of query params for the merge api
- Manually
// Code coverage diff between base branch:release and head branch: git-sync-fixes 
:green_circle: | total | 54.63 **(0)** | 36.33 **(0)** | 33.09 **(0.01)** | 55.15 **(0)**
:green_circle: | app/client/src/constants/messages.ts | 73.94 **(0.05)** | 100 **(0)** | 22.88 **(0.14)** | 79.75 **(0.06)**
:red_circle: | app/client/src/pages/Editor/gitSync/QuickGitActions/index.tsx | 71.43 **(-0.61)** | 46.15 **(-3.85)** | 34.78 **(0)** | …

fix: minor git sync fixes

---

app/client/src/comments/CommentThread/CommentThread.tsx
app/client/src/components/editorComponents/Button.tsx
app/client/src/components/editorComponents/GlobalSearch/SnippetRefinements.tsx
app/client/src/components/editorComponents/GlobalSearch/SnippetsFilter.tsx
app/client/src/components/editorComponents/JSResponseView.tsx
app/client/src/pages/Applications/index.tsx
app/client/src/pages/Editor/GeneratePage/components/DataSourceOption.tsx
app/client/src/pages/Editor/GeneratePage/components/GeneratePageForm/GeneratePageForm.tsx
app/client/src/pages/Editor/PropertyPane/PanelPropertiesEditor.tsx
app/client/src/pages/common/CanvasSelectionArena.tsx
app/client/src/pages/common/PageNotFound.tsx
app/client/src/widgets/IframeWidget/component/index.tsx

The height of the button in the table widget was increased and the property pane panel was not scrollable. Fixed those.
Fixes #9315
Fixes #9319
Fixes #9320
Fixes #9333
Fixes #9339
Fixes #9314
Fixes #9350
- Bug fix
- manually tested
// Code coverage diff between base branch:release and head branch: fix/release-blockers 
:green_circle: | total | 55.04 **(0.01)** | 36.94 **(0.02)** | 33.78 **(0.02)** | 55.52 **(0.01)**
:green_circle: | app/client/src/comments/CommentThread/CommentThread.tsx | 95.59 **(0.07)** | 65.14 **(-0.28)** | …

fix: Button size inside the Table widget has increased + Property pane's panel not scrollable + Alignment issues

---

app/client/cypress.json

As we have an intermittent failure we are commenting out this test
https://github.com/appsmithorg/appsmith/issues/9386

test: Ignoring Flaky test

---

app/client/cypress/fixtures/snippingTableDsl.json
app/client/cypress/integration/Smoke_TestSuite/Application/PgAdmin_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Onboarding/FirstTimeUserOnboarding_spec.js
app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/QueryPane/AddWidget_spec.js
app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/QueryPane/Mongo_Spec.js
app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/QueryPane/Postgres_Spec.js
app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/QueryPane/S3_spec.js
app/client/cypress/locators/GeneratePage.json
app/client/cypress/locators/QueryEditor.json
app/client/cypress/locators/commonlocators.json
app/client/cypress/support/commands.js

QueryPane test cases for Amazon S3 along with limited CRUD flow coverage
Fixes #9277 
Tested on Fat container - master

test: S3 QueryPane scripting along with possible CRUD flow coverage

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_GeneralProperty_spec.js

test: updated test flow

---

app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx

Fixes #9390 
Manual
// Code coverage diff between base branch:release and head branch: fix/correctly-copy-json-objects-in-evaluated-pane 
:red_circle: | total | 55.09 **(-0.01)** | 37.05 **(-0.02)** | 33.86 **(0)** | 55.58 **(-0.01)**
:red_circle: | app/client/src/components/editorComponents/CodeEditor/EvaluatedValuePopup.tsx | 65.35 **(-0.52)** | 56.1 **(-1.4)** | 38.89 **(0)** | 65.77 **(-0.59)**
:red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.04 **(-0.22)** | 40.42 **(-0.83)** | 34.48 **(0)** | 55.96 **(-0.26)**</details>

fix: Properly save JSON to clipboard

---

app/client/src/components/editorComponents/CodeEditor/hintHelpers.ts

Fixes #8867 
Manual
// Code coverage diff between base branch:release and head branch: fix/currentItem-showing-in-completion-when-not-available 
:green_circle: | total | 55.08 **(0.01)** | 37.05 **(0)** | 33.87 **(0.01)** | 55.58 **(0.01)**
:green_circle: | app/client/src/components/editorComponents/CodeEditor/hintHelpers.ts | 79.31 **(0.74)** | 58.33 **(0)** | 40 **(0)** | 78.57 **(0.79)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(0.67)** | 40.83 **(0.41)** | 36.21 **(1.73)** | 56.74 **(0.78)**</details>

fix: remove custom defs when not available in an entity's context

---

app/client/cypress.json
app/client/cypress/fixtures/apiParallelDsl.json
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/Bind_JSObject_Postgress_Table_spec.js
app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/ApiPaneTests/API_Bugs_Spec.js
app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/QueryPane/AddWidgetTableAndBind_spec.js
app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/QueryPane/Mongo_Spec.js
app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/QueryPane/S3_spec.js
app/client/cypress/locators/QueryEditor.json
app/client/cypress/locators/commonlocators.json
app/client/cypress/support/commands.js

Develop scripts for validating the closed application bugs & increase coverage!
Fixes #9434 
Tested on Fat container - release
// Code coverage diff between base branch:release and head branch: test/RestBugs 
:red_circle: | total | 55.09 **(-0.01)** | 37.16 **(-0.02)** | 33.87 **(-0.01)** | 55.59 **(-0.01)**
:red_circle: | app/client/src/utils/helpers.tsx | 61.62 **(-1.85)** | 29.22 **(-3.25)** | 46.34 **(-2.44)** | 59.24 **(-1.9)**
:red_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.71 **(-0.23)** | 40.83 **(-0.84)** | 36.21 **(0)** | …

test: RestAPI parallel run & Debug btn crash [Bugs 5550, 6863, 8686] - Script implementation

---

app/client/src/utils/AnalyticsUtil.tsx

- Test A
- Test B
// Code coverage diff between base branch:release and head branch: fix/telemetry-from-welcome-page-ce-key 
:green_circle: | total | 55.15 **(0)** | 37.18 **(0)** | 33.99 **(0)** | 55.66 **(0.01)**
:red_circle: | app/client/src/utils/AnalyticsUtil.tsx | 28.57 **(-0.6)** | 11.11 **(-7.94)** | 30.77 **(0)** | 29.03 **(-0.32)** …

fix: fix segment calls not getting fired issue on CE instances

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Auth/Analytics_spec.js
app/client/cypress/support/commands.js

chore: disable and assert disablility of telemetry on CI

---

app/client/cypress/integration/Smoke_TestSuite/Application/EchoApiCMS_spec.js

Updated test where we had some click issues
// Code coverage diff between base branch:release and head branch: test/FixEchotest 
:green_circle: | total | 55.13 **(0)** | 37.17 **(0.01)** | 33.97 **(0)** | 55.64 **(0)**

test: echoAPICMS

---

app/client/src/pages/Settings/SettingsConfig.ts
app/client/src/sagas/SuperUserSagas.tsx
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/EnvManager.java

Custom domain should be configurable from admin settings UI
Fixes #9377
- Manually
// Code coverage diff between base branch:release and head branch: feat/custom-domain-settings 
:red_circle: | total | 55.09 **(0)** | 36.97 **(0)** | 33.98 **(0)** | 55.6 **(-0.01)**
:red_circle: | app/client/src/sagas/SuperUserSagas.tsx | 26.56 **(-0.42)** | 3.85 **(0)** | 12.5 **(0)** | 30.36 **(-0.55)**

feat: [Feature] Custom domain should be configured from admin UI

---

app/client/src/api/UserApi.tsx
app/client/src/pages/Settings/Main/Button.tsx
app/client/src/pages/Settings/SettingsConfig.ts
app/client/src/sagas/SuperUserSagas.tsx

Fixes #9329 
- Test A
- Test B

chore: send email config details when making send test email call 

---

app/client/src/pages/Editor/PagesEditor/index.tsx

Fix for the issue of context menu auto closing after changing the settings.
Fixes #9193
// Code coverage diff between base branch:release and head branch: bugfix/9193-page-setting-re-render 
:red_circle: | total | 55.12 **(0)** | 37.04 **(-0.01)** | 34 **(0)** | 55.63 **(0)**
:red_circle: | app/client/src/pages/Editor/PagesEditor/index.tsx | 46.81 **(-2.08)** | 60 **(0)** | 0 **(0)** | 47.83 **(-2.17)**
:red_circle: | app/client/src/selectors/commentsSelectors.ts | 83.61 **(-1.64)** | 61.76 **(-2.95)** | 73.33 **(0)** | 88.24 …

fix: Context menu auto close issue in page settings

---

app/client/cypress/fixtures/apiParallelDsl.json
app/client/cypress/fixtures/apiTableDsl.json
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GenerateCRUD/Postgres_Spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/GenerateCRUD/S3_Spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/QueryPaneTests/SwitchDatasource_spec.js
app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/ApiPaneTests/API_Bugs_Spec.js
app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datasources/ArangoDataSourceStub_spec.js
app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datasources/MsSQLDataSourceStub_spec.js
app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datasources/MySQLDataSourceStub_spec.js
app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/Datasources/RedshiftDataSourceStub_spec.js
app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/QueryPane/EmptyDataSource_spec.js
app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/QueryPane/Mongo_Spec.js
app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/QueryPane/Postgres_Spec.js
app/client/cypress/integration/Smoke_TestSuite/ServerSideTests/QueryPane/S3_spec.js
app/client/cypress/locators/commonlocators.json
app/client/cypress/support/commands.js
app/client/cypress/support/index.js

Develop scripts for validating the closed application bugs to increase automation tests scope!
Fixes #9538
This PR includes automated test cases for Github issues: #8684 , #5550 , #4775 , #9425 , #9334
Tested on Fat container - release

test: Automated tests for RestApi, S3 Bugs

---

app/server/entrypoint.sh
deploy/docker/templates/supervisord/application_process/backend.conf

Ref: <https://spring.io/blog/2021/12/10/log4j2-vulnerability-and-spring-boot>.

fix: Add CLI argument to fix log4j2 RCE

---

app/client/gitbook-algolia-lambda.js

Loading them in parallel is causing us to breach some rate limiting restrictions sporadically and the whole process fails. So this reverts to loading pages sequentially instead.
Also fixes issue where some pages were being downloaded more than once, further feeding into breaching API limits.
// Code coverage diff between base branch:release and head branch: sharat87-patch-1 
:green_circle: | app/client/src/selectors/commentsSelectors.ts | 79.84 **(1.61)** | 57.35 **(2.94)** | 70 **(0)** | 86.36 **(2.27)**</details>

fix: Load pages from GitBook sequentially

---

deploy/aws_ami/README.md

Fix : #8461 Made changes to this Readme file of AWS Console to make it grammatically correct.
> This change requires a documentation update
> I presume this change doesn't need tests. Do have a look at the changes.

docs: Editing grammatical errors

---

app/client/src/components/ads/Icon.tsx

chore: Duplicate case labels found in switch case

---

app/client/public/index.html

remove plausible to improve page performance
- NA

chore: remove plausible to improve page load performance

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ApplicationPageServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ExamplesOrganizationCloner.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ApplicationServiceTest.java

fix: Added handling for action collections during duplicate app flow

---

app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/DslActionDTO.java
app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/LayoutActionUpdateDTO.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/NewActionServiceImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/PageLoadActionsUtil.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/ActionCollectionServiceImplTest.java

fix: Added collection id and clientSideExecution to layout on page load DTO

---

deploy/helm/Chart.yaml
deploy/helm/README.md
deploy/helm/templates/namespace.yaml
deploy/helm/values.yaml

Attempted to fix: https://github.com/appsmithorg/appsmith/issues/9625
Making the value optional allows to work around the error when the namespace exists.
Fixes # 9625
- Namespace **not created** beforehand, value `namespace.create: true` -> Release deployed and namespace created
- Namespace **created** beforehand with value `namespace.create: true` -> FAILURE (expected)
- Namespace **created** beforehand with value `namespace.create: false` -> Release deployed
~~- [ ] My code follows the style guidelines of this project~~
N/A ~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
- [?] My changes generate no new warnings
~~- [ ] I have added tests that …

Conditional Namespace Creation

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/Binding/Table_ClientSide_Search_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_Button_Icon_validation_spec.js
app/client/cypress/support/commands.js

#7382,#5134,#9033,#8522
// Code coverage diff between base branch:release and head branch: test/TableBugsAutomation 

test: TableWidget bugs 

---

app/client/src/pages/Editor/QueryEditor/index.tsx

Resolves merge conflicts blocking release.

fix: Fix merge problems

---

app/client/src/components/propertyControls/ChartDataControl.tsx
app/client/src/workers/validations.ts

Fix CHart widget expected value structure and validation
Fixes #9624 
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: fix/chart-widget-validation 
:red_circle: | total | 55.13 **(0)** | 37.03 **(-0.02)** | 34.02 **(0)** | 55.65 **(0)**
:red_circle: | app/client/src/workers/validations.ts | 77.23 **(0)** | 70.89 **(-0.66)** | 67.65 **(0)** | 78.78 …

fix: chart validation

---

app/server/appsmith-git/src/main/java/com/appsmith/git/configurations/GitServiceConfig.java
app/server/docker-compose.yml

To support volumes for git-sync this PR update default path. 

chore: Update local git repo path

---

deploy/aws_ami/remove-unused-docker-images.sh

- Add script to remove unused image in the AMI (daily execute) 

fix: Add script to remove unused Docker images in AMI

---

app/server/appsmith-plugins/restApiPlugin/src/main/java/com/external/plugins/RestApiPlugin.java

> Null point exception detected while accessing RestAPI
Fixes #9747
> Handled a probable nullpointexception for empty key from headers, similar which was handled in another location

fix: Handled a possible null key from headers - NullpointException in Sentry_Issue

---

app/client/src/constants/Colors.tsx
app/client/src/constants/typography.ts
app/client/src/pages/Editor/gitSync/components/UserGitProfileSettings/index.tsx

chore: update font for the user settings title
// Code coverage diff between base branch:release and head branch: fix-heading-font 
:green_circle: | total | 55.23 **(0)** | 37.09 **(0.01)** | 34.08 **(0)** | 55.74 **(0)**
:green_circle: | app/client/src/selectors/commentsSelectors.ts | 85.25 **(1.64)** | 64.71 **(2.95)** | 73.33 **(0)** | 90.59 **(2.35)**</details>

chore: update font for the user settings title

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java

> Fix the wrong url of Cloud service.
- Locally

fix: add missing part in CS url

---

app/client/src/widgets/TableWidget/widget/utilities.test.ts
app/client/src/widgets/TableWidget/widget/utilities.ts

Fixes #9812 #9813 
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: fix/undefined-filterdata-props-table 
:green_circle: | total | 55.23 **(0)** | 37.11 **(0.01)** | 34.08 **(0)** | 55.74 **(0)**
:green_circle: | app/client/src/widgets/TableWidget/widget/utilities.ts | 100 **(0)** | 77.78 **(2.78)** | 100 **(0)** | 100 **(0)**</details>

fix: handle undefined filterdata props in table widget

---

app/server/appsmith-server/src/main/java/com/appsmith/server/dtos/GitConnectDTO.java
app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/GitServiceTest.java

> This PR fixes a git profile related issues for scenarios like:
- Default git profile is null and useGlobalProfile flag is set
- Author name is empty for local git profile and useLocalGitProfile is set 
Fixes #9890
> Manual test
> JUnit TC

fix: Fixes related to git profile

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/PluginServiceCEImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/AuthenticationServiceCEImpl.java
app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ImportExportApplicationServiceCEImpl.java

fix: Switched reference from package name to plugin name for import export

---

deploy/template/docker.env.sh

https://appsmith.notion.site/Fix-server-not-starting-in-v1-6-4-d6456e8f6dcc443cb7a22bdc1cfa9a80

chore: Fix connecting to MongoDB fails

---

app/server/appsmith-plugins/mongoPlugin/src/main/java/com/external/plugins/MongoPlugin.java
app/server/appsmith-plugins/mongoPlugin/src/test/java/com/external/plugins/MongoPluginTest.java

Appends authSource param to mongo URI if absent
Also fixes inability to connect to mongo without user info
Fixes #7713

fix: Appends authSource param to mongo URI if absent

---

app/server/appsmith-server/src/main/resources/application.properties

fix: [Hotfix] Set auth db name in properties for mongoDB

---

app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_spec.js
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/DisplayWidgets/Table_tabledata_schema_spec.js
app/client/src/pages/AppViewer/index.tsx
app/client/src/widgets/TableWidget/widget/index.tsx

Fixes #9802
- Test A
- Test B
// Code coverage diff between base branch:release and head branch: fix/table-computedvalues-view-mode 
:red_circle: | total | 54.93 **(-0.01)** | 36.31 **(-0.01)** | 34.23 **(0)** | 55.46 **(0)**
:red_circle: | app/client/src/utils/WorkerUtil.ts | 88.98 **(-0.78)** | 70.59 **(-1.96)** | 100 **(0)** | 92.38 …

fix: allow updating computed values of table widget in view mode

---

deploy/helm/Chart.lock
deploy/helm/Chart.yaml
deploy/helm/Publish-helm-chart.md
deploy/helm/README.md
deploy/helm/Setup-https.md
deploy/helm/templates/_helpers.tpl
deploy/helm/templates/autoupdate.yaml
deploy/helm/templates/deployment.yaml
deploy/helm/templates/ingress.yaml
deploy/helm/templates/namespace.yaml
deploy/helm/templates/persistentVolumeClaim.yaml
deploy/helm/templates/service.yaml
deploy/helm/templates/serviceaccount.yaml
deploy/helm/templates/storageClass.yaml
deploy/helm/templates/tls-secret.yaml
deploy/helm/values.yaml

- Remove Helm chart dependency
- Remove Helm chart namespace resource
- Refactor Auto-update resource to attach Imago (auto-update service) to corresponding namespace
- Minor typo fix

chore: Minor improvement for Helm, remove dependency & namespace

---

app/client/src/components/ads/DraggableList.tsx
app/client/src/components/ads/DraggableListComponent.tsx
app/client/src/components/propertyControls/PrimaryColumnsControl.tsx

Reverts appsmithorg/appsmith#9944

fix: Users unable to drag a column outside of viewport of a property pane to rearrange column order

---

.github/ISSUE_TEMPLATE/Templates.yaml

>
> 
>Adding in an issue template for Template requests. This is just to allow a user to request a template is created
- Checked the file on another directory
- [ x] My code follows the style guidelines of this project
- [ x] I have performed a self-review of my own code
- [ x] I have commented my code, particularly in hard-to-understand areas
- [ x] My changes generate no new warnings

Adding Template request file

---

.github/ISSUE_TEMPLATE/Templates.yaml

Changed version, removed tag, and added label
>
> Please …

Updated Templates.yaml

---

app/client/cypress/fixtures/dropDownWidget_reset_check_dsl.json
app/client/cypress/integration/Smoke_TestSuite/ClientSideTests/FormWidgets/DropDownWidget_value_reset_spec.js
app/client/src/widgets/DropdownWidget/widget/index.tsx

**Summary of changes**
- Changed the condition to choose index inside changeSelectionOption as selectedOptionValue if it exists or else defaultOptionValue is selected.
**Motivation**
- For the dropdown down widget it was observed that the selected value was getting reset to default option if navigated to other section of the application such as navigating to query section and then coming back to the canvas.
Fixes #10038
Have written the integration test (cypress) with filename: `DropDownWidget_value_reset_spec.js`
// Code coverage diff between base branch:release and head branch: fix/fix-select_gets_reset_on_navigation 
Status | File | % Stmts | % Branch | % Funcs | …

fix: added selectedOptionValue for index change in changeSelectedOption func Dropdown widget

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/CommentServiceCEImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/services/CommentServiceTest.java

Commenting on a public app fails if the user is not not part of the corresponding organization. 
Fixes #10088
- JUnit tests
- Manually

fix: Unable to add comment to public apps

---

app/client/src/reducers/entityReducers/actionsReducer.tsx

In this PR, all action data gets cleared when page is switched
Fixes #9572
-Manual
// Code coverage diff between base branch:release and head branch: fix/clear-action-data-on-page-switch 
:green_circle: | app/client/src/reducers/entityReducers/actionsReducer.tsx | 6.9 **(0.76)** | 0 **(0)** | 1.75 **(1.75)** | 7.08 **(0.83)**</details>

fix: clear action data on page switch

---

app/server/appsmith-server/src/main/java/com/appsmith/server/services/ce/GitServiceCEImpl.java

fix: Merge and pull branch analytics NPE

---

.github/workflows/integration-tests-command.yml
.github/workflows/test-build-docker-image.yml

This PR makes updates to yaml files to include test files with ts or js extention

test: Updates to YAML file for TS cypress tests inclusion

---

app/client/cypress/fixtures/exportedApp.json
app/client/cypress/fixtures/forkedApp.json
app/client/cypress/integration/Smoke_TestSuite/Application/ImportExportForkApplication_spec.js

This PR contains tests for importing, exporting and forking an application and validating data binding for all apps. 
Fixes #10203 
locally
// Code coverage diff between base branch:release and head branch: forkApplicationTest 
:red_circle: | total | 55.1 **(-0.01)** | 36.63 **(0)** | 34.52 **(0)** | 55.63 **(0)**
:green_circle: | app/client/src/utils/autocomplete/TernServer.ts | 52.94 **(0.23)** …

test: added tests for import, export and fork application

---

app/client/src/components/editorComponents/form/fields/DynamicTextField.tsx
app/client/src/components/formControls/BaseControl.tsx
app/client/src/components/formControls/DropDownControl.tsx
app/client/src/components/formControls/DynamicInputTextControl.tsx
app/client/src/components/formControls/DynamicTextFieldControl.tsx
app/client/src/components/formControls/FilePickerControl.tsx
app/client/src/components/formControls/FixedKeyInputControl.tsx
app/client/src/components/formControls/InputTextControl.tsx
app/client/src/components/formControls/SwitchControl.tsx
app/client/src/pages/Editor/QueryEditor/EditorJSONtoForm.tsx
app/client/src/reducers/evaluationReducers/formEvaluationReducer.ts
app/client/src/workers/formEval.ts

This is to add enable disable functionality to the form components. This is part of the conditionals functionality for UQI components
Fixes #8048
// Code coverage diff between base branch:release and head branch: feat/8048-enable-disable-form-componenets-conditionally 
:red_circle: | total | 55.07 **(-0.03)** | 36.59 **(-0.03)** | 34.52 **(0)** | 55.58 **(-0.04)**
:red_circle: | app/client/src/components/formControls/DropDownControl.tsx | 44.44 **(-3.95)** | 2.17 **(0)** | 16.67 **(0)** | 42.86 **(-3.81)** …

feat: Add enable/disable functionality to form components

---

app/client/src/utils/DSLMigrations.ts
app/client/src/utils/migrations/TableWidget.ts

chore: Skip bad table migration version 47

---

app/client/src/pages/Editor/gitSync/Tabs/Merge.tsx
app/client/src/pages/Editor/gitSync/components/BranchList.tsx
app/client/src/pages/Editor/gitSync/components/MergeStatus.tsx
app/client/src/reducers/uiReducers/gitSyncReducer.ts
app/client/src/selectors/gitSyncSelectors.tsx

> updated conflicting condition of merge tab
Fixes #9870
> refer attached issue
// Code coverage diff between base branch:release and head branch: fix/9870-merge-change-button-issue 
:green_circle: | total | 55.12 **(0)** | 36.65 **(0.01)** | 34.54 **(0)** | 55.65 **(0)**
:red_circle: | app/client/src/pages/Editor/gitSync/components/BranchList.tsx | 23.31 **(-0.29)** | 10.13 **(-0.54)** | 2.5 **(0)** | 25.34 **(-0.18)** …

fix: 9870 merge button visible condition

---

app/client/src/utils/DSLMigrations.ts
app/client/src/workers/Actions.test.ts
app/client/src/workers/Actions.ts

Patching issues that got introduced in draft release of v1.6.6
// Code coverage diff between base branch:master and head branch: release-v1.6.6 
:red_circle: | total | 55.1 **(-0.02)** | 36.6 **(-0.03)** | 34.54 **(-0.02)** | 55.63 **(-0.02)**
:red_circle: | app/client/src/utils/DSLMigrations.ts | 74.11 **(-0.04)** | 64.94 **(0)** | 70.21 **(0)** | 73.94 **(-0.04)**
:red_circle: | app/client/src/utils/migrations/TableWidget.ts | 76.23 **(-4.15)** | 69.13 **(-4.78)** | 79.41 **(-5.88)** | 76.6 …

ci: Release v1.6.6

---

app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/AppendMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/BulkAppendMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/BulkUpdateMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/ClearMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/CopyMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/CreateMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/DeleteRowMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/DeleteSheetMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/config/UpdateMethod.java
app/server/appsmith-plugins/googleSheetsPlugin/src/main/java/com/external/plugins/GoogleSheetsPlugin.java

This PR also fixes encoding issues with all the other commands apart from the one mentioned in the issue.
Fixes #10209 
- Manually tested, cannot unit test since there are no mocks available

fix: Fixed encoding for all requests in Google Sheets

---

app/client/src/components/propertyControls/DatePickerControl.tsx

>  Extended Min Date Limit to last 150 Years
Fixes #10187
// Code coverage diff between base branch:release and head branch: bug/date-picker-min-date-outofrange 
:red_circle: | total | 55.07 **(0)** | 36.56 **(-0.01)** | 34.51 **(0)** | 55.58 **(0)**
:red_circle: | app/client/src/utils/WorkerUtil.ts | 89.76 **(0)** | 70.59 **(-1.96)** | 100 **(0)** | 93.33 **(0)**</details>

fix: extended min date limit to last 150 years

---

app/client/src/pages/Editor/IntegrationEditor/IntegrationsHomeScreen.tsx

Conditionally shows shadow div when on the active datasource tab
Fixes #10161 
Manually
// Code coverage diff between base branch:release and head branch: fix/broken-datasource-alignment 
:green_circle: | total | 55.1 **(0)** | 36.58 **(0)** | 34.54 **(0)** | 55.61 **(0.01)**
:red_circle: | app/client/src/pages/Editor/IntegrationEditor/IntegrationsHomeScreen.tsx | 27.81 **(0)** | 11.36 **(-0.27)** | 4.55 **(0)** | 32.54 **(0)** …

fix: Datasource alignment is broken under the active tab

---

app/server/appsmith-server/src/main/java/com/appsmith/server/solutions/ce/ApplicationForkingServiceCEImpl.java
app/server/appsmith-server/src/test/java/com/appsmith/server/solutions/ApplicationForkingServiceTests.java

This reverts commit 814a7d57f9dad02a89942e97db0d4646b489fd07.

revert: Don't take client subscription into account for fork application (#10220)
